function trial = stage8_k2_mc_generate_paired_trial(fixture, case_row, draw_mode)
%STAGE8_K2_MC_GENERATE_PAIRED_TRIAL Generate one rotated paired observation.

if nargin < 3 || isempty(draw_mode), draw_mode = 'PAIRED_LOCAL_DRAW'; end
draw_mode = upper(char(string(draw_mode)));
center_index = double(case_row.center_index);
noise_index = find(fixture.noise_profile_ids == ...
    string(case_row.noise_profile_id), 1);
profile_index = find(string({fixture.spec.context.constants.profiles.profile_id}) == ...
    string(case_row.profile_id), 1);
if isempty(noise_index) || isempty(profile_index) || ...
        center_index < 1 || center_index > fixture.center_count
    error('stage8_k2_mc_generate_paired_trial:Case', ...
        'The semantic case row is invalid.');
end
profile = fixture.spec.context.constants.profiles(profile_index);
bundle = fixture.bundles(center_index, noise_index);
center = fixture.centers(center_index);
model = bundle.model;
direction = [cosd(profile.direction_deg), sind(profile.direction_deg)];
truth_center = [profile.center_deg(1) + center.rotation_delta_deg, ...
    profile.center_deg(2)];
truth = [truth_center - profile.separation_deg * direction / 2; ...
    truth_center + profile.separation_deg * direction / 2];
if any(truth(:,1) < bundle.local_domain.domain_bounds_deg(1) | ...
        truth(:,1) > bundle.local_domain.domain_bounds_deg(2) | ...
        truth(:,2) < bundle.local_domain.domain_bounds_deg(3) | ...
        truth(:,2) > bundle.local_domain.domain_bounds_deg(4))
    error('stage8_k2_mc_generate_paired_trial:TruthDomain', ...
        'The rotated truth is outside the center domain.');
end
rng_state = rng;
rng_cleanup = onCleanup(@() rng(rng_state));
rng(double(case_row.source_seed), 'twister');
source_phase = 2 * pi * rand();
if strcmp(draw_mode, 'INDEPENDENT_CENTER_DRAW')
    source_phase = source_phase + 0.371;
end
manifold = build_stage8_element_manifold(truth, model);
[source, source_info] = construct_deterministic_source_matrix( ...
    2, double(case_row.L), profile.secondary_power_db, ...
    profile.correlation_magnitude, source_phase, char(case_row.trial_id));
unscaled = manifold.A * source;
source = source * sqrt(10 ^ (double(case_row.snr_db) / 10) * ...
    numel(unscaled) / max(norm(unscaled, 'fro') ^ 2, realmin));
signal = manifold.A * source;
[noise, noise_debug] = generate_stage8_element_noise( ...
    model, double(case_row.L), 1, double(case_row.noise_seed));
trial = struct('trial_id',char(case_row.trial_id), ...
    'case_row',case_row, 'center',center, 'model',model, ...
    'stage5_locked',bundle.stage5_locked, 'local_domain',bundle.local_domain, ...
    'Y_element',signal + noise, 'truth_angles_deg',truth, ...
    'source_matrix',source, 'signal_element',signal, 'noise_element',noise, ...
    'source_phase_rad',source_phase, 'source_info',source_info, ...
    'noise_debug',noise_debug, 'truth_used_in_fit_flag',false, ...
    'single_cpi_flag',true, 'same_range_doppler_cell_flag',true, ...
    'cross_cpi_data_used_flag',false, 'tracking_input_used_flag',false);
trial.element_trial_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_ELEMENT_TRIAL_V1', trial.trial_id, trial.Y_element, ...
    truth, double(case_row.L), double(case_row.snr_db), ...
    double(case_row.source_seed), double(case_row.noise_seed), ...
    char(case_row.noise_profile_id));
end
