function spec = stage8_k2_mc_reference_spec(repo_dir)
%STAGE8_K2_MC_REFERENCE_SPEC Freeze the parent production reference.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_mc_reference_spec:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
context = stage8_k2_tp_build_context(repo_dir);
cfg = sim_cfg();
pool = build_stage7_candidate_pool(cfg);
family = enumerate_stage7_rectangular_subsets(pool, cfg);
noise_ids = ["WHITE";"STAGE5_TOEPLITZ_CORRELATED"];
models = repmat(context.plan.measurement_model_registry.entries(1), ...
    numel(noise_ids), 1);
for index = 1:numel(noise_ids)
    models(index) = resolve_stage8_measurement_model( ...
        context.plan.measurement_model_registry, ...
        context.primary_measurement_config_id, noise_ids(index));
end
reference_model = models(1);
requested = double(cfg.beam.azSectorCenter);
column = double(reference_model.array_meta.colCtr);
physical = double(reference_model.array_meta.phiCol(column));
d_phi = 360 / double(cfg.arr.Naz);
if requested == physical || column ~= 5 || abs(physical - 7.5) > 1e-12
    error('stage8_k2_mc_reference_spec:PhysicalCenter', ...
        'BLOCKED_FIXED_REFERENCE_CENTER_UNRESOLVED.');
end
if norm(pool.W0(:, reference_model.channels) - ...
        reference_model.Wseq, 'fro') > 1e-13
    error('stage8_k2_mc_reference_spec:ReferencePool', ...
        'The rebuilt reference pool differs from the frozen model.');
end
relative_beam = pool.azimuth_beam_deg - physical;
relative_domain = context.plan.local_domain.az_grid_deg - physical;
spec = struct( ...
    'schema_version','STAGE8_K2_MC_REFERENCE_SPEC_V1', ...
    'repo_dir',repo_dir, 'context',context, 'cfg',cfg, ...
    'reference_pool',pool, 'reference_subset_family',family, ...
    'reference_models',models, 'noise_profile_ids',noise_ids, ...
    'measurement_config_id',context.primary_measurement_config_id, ...
    'reference_stage5_config',context.stage5_locked, ...
    'reference_domain',context.plan.local_domain, ...
    'reference_requested_center_az_deg',requested, ...
    'reference_physical_center_az_deg',physical, ...
    'reference_center_column',column, ...
    'Naz',double(cfg.arr.Naz), 'dPhi_deg',d_phi, ...
    'relative_azimuth_beam_deg',relative_beam, ...
    'relative_registered_delta_deg',relative_domain, ...
    'elevation_beam_deg',pool.elevation_beam_deg, ...
    'elevation_registered_grid_deg', ...
        context.plan.local_domain.el_grid_deg, ...
    'selected_center_offsets',[0,1,-1,8,-8,32,-32,96], ...
    'baseline_commit', ...
        'b6156655b2d51d5333522166f6509b100ead7d08');
spec.reference_spec_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_REFERENCE_SPEC_V1', requested, physical, column, ...
    d_phi, relative_beam, relative_domain, ...
    spec.elevation_beam_deg, spec.elevation_registered_grid_deg, ...
    string({models.fixed_measurement_hash}));
end
