function output = stage8_k2_mc_whitener_basis_diagnostics(repo_dir, spec)
%STAGE8_K2_MC_WHITENER_BASIS_DIAGNOSTICS Validate basis-invariant whitening.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_mc_whitener_basis_diagnostics:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
scope = stage8_k2_mc_add_paths(repo_dir); %#ok<NASGU>
if nargin < 2 || isempty(spec)
    spec = stage8_k2_mc_reference_spec(repo_dir);
end

centers = stage8_k2_mc_select_centers(spec);
noise_ids = spec.noise_profile_ids;
thresholds = struct( ...
    'forward_whitening_residual_default',1e-10, ...
    'whitening_backward_error',1e-10, ...
    'Q_unitarity_default_error',1e-8, ...
    'Q_unitarity_error',1e-7, ...
    'alignment_error',1e-10, ...
    'row_space_projector_error',1e-10);
row_count = numel(centers) * numel(noise_ids);
rows = repmat(row_template_local(), row_count, 1);
row_index = 0;
for noise_index = 1:numel(noise_ids)
    for center_index = 1:numel(centers)
        bundle = stage8_k2_mc_build_measurement_model( ...
            spec, centers(center_index), noise_ids(noise_index));
        T_raw = bundle.raw_rebuilt_model.Tseq;
        C_raw = bundle.raw_rebuilt_model.Cseq;
        T_ref = bundle.model.Tseq;
        if ~isequal(size(T_raw), size(T_ref)) || ...
                size(C_raw,1) ~= size(C_raw,2) || ...
                size(T_raw,2) ~= size(C_raw,1)
            error('stage8_k2_mc_whitener_basis_diagnostics:Shape', ...
                'Raw/reference whitener dimensions are incompatible.');
        end

        identity_now = eye(size(T_raw,1), 'like', T_raw);
        identity_norm = max(norm(identity_now,'fro'), realmin);
        raw_white = T_raw * C_raw * T_raw';
        ref_white = T_ref * C_raw * T_ref';
        raw_residual = norm(raw_white - identity_now,'fro') / identity_norm;
        ref_residual = norm(ref_white - identity_now,'fro') / identity_norm;
        raw_backward_error = whitening_backward_error_local(T_raw,C_raw);
        ref_backward_error = whitening_backward_error_local(T_ref,C_raw);

        Q = T_raw * pinv(T_ref);
        Q_identity = eye(size(Q,1), 'like', Q);
        Q_error = norm(Q * Q' - Q_identity,'fro') / ...
            max(norm(Q_identity,'fro'), realmin);
        alignment_error = norm(T_raw - Q * T_ref,'fro') / ...
            max(norm(T_raw,'fro'), realmin);

        raw_rank = stable_rank_local(T_raw);
        ref_rank = stable_rank_local(T_ref);
        full_row_rank = raw_rank == size(T_raw,1) && ...
            ref_rank == size(T_ref,1);
        raw_projector = pinv(T_raw) * T_raw;
        ref_projector = pinv(T_ref) * T_ref;
        projector_error = norm(raw_projector - ref_projector,'fro') / ...
            max(norm(ref_projector,'fro'), realmin);
        coordinate_gate = Q_error <= thresholds.Q_unitarity_error;
        if ~full_row_rank
            coordinate_gate = projector_error <= ...
                thresholds.row_space_projector_error;
        end
        pass = raw_backward_error <= thresholds.whitening_backward_error && ...
            ref_backward_error <= thresholds.whitening_backward_error && ...
            alignment_error <= thresholds.alignment_error && coordinate_gate;

        row_index = row_index + 1;
        rows(row_index) = struct( ...
            'center_offset',bundle.center.column_offset, ...
            'center_column',bundle.center.center_column, ...
            'noise_profile_id',string(bundle.noise_profile_id), ...
            'raw_row_rank',raw_rank, ...
            'reference_row_rank',ref_rank, ...
            'whitener_row_count',size(T_raw,1), ...
            'full_row_rank',full_row_rank, ...
            'covariance_condition_number',cond(C_raw), ...
            'minimum_relative_eigenvalue_gap', ...
                minimum_relative_eigenvalue_gap_local(C_raw), ...
            'raw_whitening_residual',raw_residual, ...
            'reference_whitening_residual',ref_residual, ...
            'raw_whitening_backward_error',raw_backward_error, ...
            'reference_whitening_backward_error',ref_backward_error, ...
            'Q_unitarity_error',Q_error, ...
            'alignment_error',alignment_error, ...
            'row_space_projector_error',projector_error, ...
            'pass',pass);
    end
end
rows = struct2table(rows);
output = struct( ...
    'schema_version','STAGE8_K2_MC_WHITENER_BASIS_DIAGNOSTICS_V2', ...
    'rows',rows,'thresholds',thresholds, ...
    'case_count',height(rows),'pass_count',nnz(rows.pass), ...
    'max_raw_whitening_residual',max(rows.raw_whitening_residual), ...
    'max_reference_whitening_residual', ...
        max(rows.reference_whitening_residual), ...
    'max_raw_whitening_backward_error', ...
        max(rows.raw_whitening_backward_error), ...
    'max_reference_whitening_backward_error', ...
        max(rows.reference_whitening_backward_error), ...
    'max_Q_unitarity_error',max(rows.Q_unitarity_error), ...
    'max_alignment_error',max(rows.alignment_error), ...
    'max_row_space_projector_error', ...
        max(rows.row_space_projector_error), ...
    'max_covariance_condition_number', ...
        max(rows.covariance_condition_number), ...
    'min_relative_eigenvalue_gap', ...
        min(rows.minimum_relative_eigenvalue_gap), ...
    'all_full_row_rank',all(rows.full_row_rank), ...
    'forward_default_threshold_met', ...
        max(rows.raw_whitening_residual) <= ...
        thresholds.forward_whitening_residual_default && ...
        max(rows.reference_whitening_residual) <= ...
        thresholds.forward_whitening_residual_default, ...
    'forward_residual_role', ...
        'DIAGNOSTIC_ONLY_ILL_CONDITIONED_FORWARD_EVALUATION', ...
    'gated_whitening_role', ...
        'BASIS_INVARIANT_COVARIANCE_BACKWARD_STABILITY', ...
    'Q_threshold_investigation', ...
        'CONDITION_NUMBER_AND_EIGENVALUE_GAPS_INVESTIGATED_LIMIT_10X_DEFAULT', ...
    'status','STAGE8_K2_MC_WHITENER_BASIS_INVARIANCE_PASS');
if ~all(rows.pass)
    output.status = 'STAGE8_K2_MC_WHITENER_BASIS_INVARIANCE_FAIL';
    error('stage8_k2_mc_whitener_basis_diagnostics:Failed', ...
        ['Whitener basis diagnostics failed: raw backward %.17g, ', ...
        'reference backward %.17g, Q %.17g, alignment %.17g, ', ...
        'projector %.17g.'], ...
        output.max_raw_whitening_backward_error, ...
        output.max_reference_whitening_backward_error, ...
        output.max_Q_unitarity_error,output.max_alignment_error, ...
        output.max_row_space_projector_error);
end
fprintf(['STAGE8_K2_MC_WHITENER_BASIS_PASS %d/%d raw_forward=%.3g ', ...
    'reference_forward=%.3g raw_backward=%.3g ', ...
    'reference_backward=%.3g Q=%.3g alignment=%.3g\n'], ...
    output.pass_count,output.case_count, ...
    output.max_raw_whitening_residual, ...
    output.max_reference_whitening_residual, ...
    output.max_raw_whitening_backward_error, ...
    output.max_reference_whitening_backward_error, ...
    output.max_Q_unitarity_error,output.max_alignment_error);
end

function value = whitening_backward_error_local(T,C)
identity_now = eye(size(T,1),'like',T);
if size(T,1) == size(T,2) && stable_rank_local(T) == size(T,1)
    implied_covariance = T \ (identity_now / T');
else
    residual = identity_now - T * C * T';
    T_pinv = pinv(T);
    implied_covariance = C + T_pinv * residual * T_pinv';
end
implied_covariance = 0.5 * (implied_covariance + implied_covariance');
value = norm(implied_covariance - C,'fro') / ...
    max(norm(C,'fro'),realmin);
end

function value = minimum_relative_eigenvalue_gap_local(C)
eigenvalues = sort(real(eig(0.5 * (C + C'))),'descend');
if numel(eigenvalues) < 2
    value = Inf;
    return;
end
scales = max(abs(eigenvalues(1:end-1)),abs(eigenvalues(2:end)));
value = min(abs(diff(eigenvalues)) ./ max(scales,realmin));
end

function rank_now = stable_rank_local(value)
singular_values = svd(value,'econ');
if isempty(singular_values) || singular_values(1) == 0
    rank_now = 0;
    return;
end
threshold = max(size(value)) * eps(singular_values(1));
rank_now = nnz(singular_values > threshold);
end

function value = row_template_local()
value = struct('center_offset',0,'center_column',0, ...
    'noise_profile_id',"",'raw_row_rank',0, ...
    'reference_row_rank',0,'whitener_row_count',0, ...
    'full_row_rank',false,'covariance_condition_number',NaN, ...
    'minimum_relative_eigenvalue_gap',NaN, ...
    'raw_whitening_residual',NaN, ...
    'reference_whitening_residual',NaN, ...
    'raw_whitening_backward_error',NaN, ...
    'reference_whitening_backward_error',NaN, ...
    'Q_unitarity_error',NaN, ...
    'alignment_error',NaN,'row_space_projector_error',NaN, ...
    'pass',false);
end
