function summary = stage8_k2_mc_run_tests(repo_dir, runtime_root)
%STAGE8_K2_MC_RUN_TESTS Run the 16 named multicenter contract tests.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_mc_run_tests:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
if nargin < 2 || isempty(runtime_root)
    runtime_root = 'E:\bs_innovation_runtime\stage8_k2_cylindrical_multicenter_cache_v1';
end
runtime_root = char(java.io.File(char(string(runtime_root))).getCanonicalPath());
required = { ...
    fullfile(runtime_root,'static','static_output.mat'); ...
    fullfile(runtime_root,'semantics','semantics_output.mat'); ...
    fullfile(runtime_root,'lifecycle','lifecycle_output.mat'); ...
    fullfile(runtime_root,'runtime_sentinel','runtime_output.mat'); ...
    fullfile(runtime_root,'runtime_sentinel','runtime_schedule.csv')};
if ~all(cellfun(@isfile,required))
    error('stage8_k2_mc_run_tests:Checkpoint', ...
        'All Gate A-D checkpoints must exist before named tests.');
end
scope = stage8_k2_mc_add_paths(repo_dir); %#ok<NASGU>
fixture = stage8_k2_mc_build_context(repo_dir,'',struct('include_trials',true));
static_loaded = load(required{1},'output');
semantics_loaded = load(required{2},'output');
lifecycle_loaded = load(required{3},'output');
runtime_loaded = load(required{4},'output');
schedule = readtable(required{5},'TextType','string');
outputs = struct('static',static_loaded.output, ...
    'semantics',semantics_loaded.output, ...
    'lifecycle',lifecycle_loaded.output, ...
    'runtime',runtime_loaded.output, ...
    'runtime_schedule',schedule);
test_names = { ...
    'test_stage8_k2_mc_actual_center_not_requested_center'; ...
    'test_stage8_k2_mc_all_192_geometry'; ...
    'test_stage8_k2_mc_rotated_beam_layout'; ...
    'test_stage8_k2_mc_W_C_T_equivalence'; ...
    'test_stage8_k2_mc_rotation_class_identity'; ...
    'test_stage8_k2_mc_actual_center_identity'; ...
    'test_stage8_k2_mc_shared_single_pair_G'; ...
    'test_stage8_k2_mc_negative_unshifted_beam'; ...
    'test_stage8_k2_mc_negative_wrong_center'; ...
    'test_stage8_k2_mc_negative_geometry_perturbation'; ...
    'test_stage8_k2_mc_stage5_rotation_contract'; ...
    'test_stage8_k2_mc_center_adapter'; ...
    'test_stage8_k2_mc_t4_bypass'; ...
    'test_stage8_k2_mc_compact_semantics'; ...
    'test_stage8_k2_mc_lifecycle_protocol'; ...
    'test_stage8_k2_mc_runtime_sentinel_protocol'};
rows = repmat(struct('test_name',"",'pass',false, ...
    'runtime_sec',0,'message',""),numel(test_names),1);
for index = 1:numel(test_names)
    rows(index).test_name = string(test_names{index});
    clock = tic;
    try
        value = feval(test_names{index},fixture,outputs);
        rows(index).pass = isstruct(value) && isfield(value,'pass') && ...
            logical(value.pass);
        if ~rows(index).pass
            rows(index).message = "TEST_RETURNED_FALSE";
        end
    catch exception
        rows(index).message = string(exception.identifier) + ": " + ...
            string(exception.message);
    end
    rows(index).runtime_sec = toc(clock);
end
summary = struct2table(rows);
disp(summary);
if ~all(summary.pass)
    error('stage8_k2_mc_run_tests:Failed', ...
        '%d of %d multicenter tests failed.', ...
        nnz(~summary.pass),height(summary));
end
fprintf('STAGE8_K2_MC_TESTS_PASS %d/%d\n',nnz(summary.pass),height(summary));
end
