function output = stage8_k2_mc_run_lifecycle(fixture, options)
%STAGE8_K2_MC_RUN_LIFECYCLE Gate C build/load/storage scaling.

if nargin<2||isempty(options),options=struct();end
if ~isfield(options,'repeat_count'),options.repeat_count=10;end
if isempty(fixture.runtime_root)
    error('stage8_k2_mc_run_lifecycle:RuntimeRoot', ...
        'Gate C requires an external runtime root.');
end
artifact_root=fullfile(fixture.runtime_root,'lifecycle','artifacts');
if ~isfolder(artifact_root),mkdir(artifact_root);end
[storage,paths]=serialize_artifacts_local(fixture,artifact_root);
repeat_count=double(options.repeat_count);
if ~(isscalar(repeat_count)&&repeat_count>=1&&repeat_count==fix(repeat_count))
    error('stage8_k2_mc_run_lifecycle:RepeatCount', ...
        'repeat_count must be a positive integer.');
end
raw_rows=cell(numel(fixture.noise_profile_ids)*repeat_count,1);
row_index=0;
for noise_index=1:numel(fixture.noise_profile_ids)
    for repeat_index=1:repeat_count
        row_index=row_index+1;
        independent_clock=tic;
        for center_index=1:fixture.center_count
            bundle=fixture.bundles(center_index,noise_index);
            [p,~]=stage8_k2_tfbc_build_provider( ...
                bundle.model,bundle.local_domain,struct());
            stage8_k2_tfbc_validate_provider( ...
                p,bundle.model,bundle.local_domain);
        end
        independent_build=toc(independent_clock);
        shared_clock=tic;
        [shared,~]=stage8_k2_mc_build_shared_provider( ...
            fixture.bundles(1,noise_index),struct());
        stage8_k2_mc_validate_shared_provider(shared);
        shared_provider_build=toc(shared_clock);
        adapter_clock=tic;
        for center_index=1:fixture.center_count
            bundle=fixture.bundles(center_index,noise_index);
            [adapter,~]=stage8_k2_mc_build_center_adapter(bundle,shared);
            stage8_k2_mc_validate_center_adapter(adapter,shared,bundle);
        end
        adapter_build=toc(adapter_clock);

        independent_load_clock=tic;
        for center_index=1:fixture.center_count
            loaded=load(paths.independent{center_index,noise_index},'provider');
            bundle=fixture.bundles(center_index,noise_index);
            stage8_k2_tfbc_validate_provider( ...
                loaded.provider,bundle.model,bundle.local_domain);
        end
        independent_load=toc(independent_load_clock);
        shared_load_clock=tic;
        loaded_shared=load(paths.shared{noise_index},'provider');
        stage8_k2_mc_validate_shared_provider(loaded_shared.provider);
        shared_provider_load=toc(shared_load_clock);
        adapter_load_clock=tic;
        for center_index=1:fixture.center_count
            loaded_adapter=load(paths.adapters{center_index,noise_index},'adapter');
            stage8_k2_mc_validate_center_adapter(loaded_adapter.adapter, ...
                loaded_shared.provider,fixture.bundles(center_index,noise_index));
        end
        adapter_load=toc(adapter_load_clock);
        raw_rows{row_index}=struct( ...
            'noise_profile_id',string(fixture.noise_profile_ids(noise_index)), ...
            'repeat_index',repeat_index, ...
            'independent_build_sec',independent_build, ...
            'shared_provider_build_sec',shared_provider_build, ...
            'adapter_build_sec',adapter_build, ...
            'shared_total_build_sec',shared_provider_build+adapter_build, ...
            'build_reduction',1-(shared_provider_build+adapter_build)/independent_build, ...
            'independent_load_sec',independent_load, ...
            'shared_provider_load_sec',shared_provider_load, ...
            'adapter_load_sec',adapter_load, ...
            'shared_total_load_sec',shared_provider_load+adapter_load, ...
            'load_reduction',1-(shared_provider_load+adapter_load)/independent_load);
        fprintf('MC LIFECYCLE noise=%s repeat=%02d/%02d build=%.3f load=%.3f\n', ...
            char(fixture.noise_profile_ids(noise_index)),repeat_index,repeat_count, ...
            raw_rows{row_index}.build_reduction,raw_rows{row_index}.load_reduction);
    end
end
raw=struct2table(vertcat(raw_rows{:}));
summary_rows=cell(numel(fixture.noise_profile_ids),1);
for noise_index=1:numel(fixture.noise_profile_ids)
    noise_id=fixture.noise_profile_ids(noise_index);
    subset=raw(raw.noise_profile_id==noise_id,:);
    s=storage(noise_index);
    summary_rows{noise_index}=struct( ...
        'noise_profile_id',string(noise_id),'repeat_count',height(subset), ...
        'independent_build_sec',median(subset.independent_build_sec), ...
        'shared_build_sec',median(subset.shared_total_build_sec), ...
        'build_reduction',median(subset.build_reduction), ...
        'independent_load_sec',median(subset.independent_load_sec), ...
        'shared_load_sec',median(subset.shared_total_load_sec), ...
        'load_reduction',median(subset.load_reduction), ...
        'independent_storage_bytes',s.independent_storage_bytes, ...
        'shared_storage_bytes',s.shared_storage_bytes, ...
        'storage_reduction',s.storage_reduction, ...
        'independent_logical_table_bytes',s.independent_logical_table_bytes, ...
        'shared_logical_table_bytes',s.shared_logical_table_bytes, ...
        'adapter_bytes',s.adapter_bytes,'independent_provider_count',8, ...
        'shared_provider_count',1,'center_adapter_count',8, ...
        'center_192_storage_reduction',s.center_192_storage_reduction, ...
        'center_192_extrapolation_status', ...
        "ANALYTIC_EXTRAPOLATION_FROM_CERTIFIED_ROTATION_CLASS", ...
        'pass',median(subset.build_reduction)>0&& ...
        median(subset.load_reduction)>0&&s.storage_reduction>0);
end
summary=struct2table(vertcat(summary_rows{:}));
status='STAGE8_K2_MULTICENTER_LIFECYCLE_NONPOSITIVE';
if all(summary.pass),status='STAGE8_K2_MULTICENTER_LIFECYCLE_POSITIVE';end
output=struct('schema_version','STAGE8_K2_MC_LIFECYCLE_V1', ...
    'raw',raw,'summary',summary,'repeat_count_per_identity',repeat_count, ...
    'status',status,'positive',all(summary.pass));
lifecycle_dir=fullfile(fixture.runtime_root,'lifecycle');
writetable(raw,fullfile(lifecycle_dir,'lifecycle_raw.csv'));
writetable(summary,fullfile(lifecycle_dir,'lifecycle_summary.csv'));
save(fullfile(lifecycle_dir,'lifecycle_output.mat'),'output','-v7');
end

function [storage,paths]=serialize_artifacts_local(fixture,root)
paths=struct('independent',{cell(8,2)},'shared',{cell(2,1)}, ...
    'adapters',{cell(8,2)});
storage=repmat(struct('independent_storage_bytes',0, ...
    'shared_storage_bytes',0,'storage_reduction',0, ...
    'independent_logical_table_bytes',0,'shared_logical_table_bytes',0, ...
    'adapter_bytes',0,'center_192_storage_reduction',0),2,1);
for noise_index=1:2
    independent_bytes=0; independent_table=0; adapter_bytes=0;
    for center_index=1:8
        bundle=fixture.bundles(center_index,noise_index);
        provider=stage8_k2_tfbc_build_provider( ...
            bundle.model,bundle.local_domain,struct()); %#ok<NASGU>
        path_now=fullfile(root,sprintf('independent_n%d_c%d.mat', ...
            noise_index,center_index));
        save(path_now,'provider','-v7'); paths.independent{center_index,noise_index}=path_now;
        item=dir(path_now); independent_bytes=independent_bytes+item.bytes;
        independent_table=independent_table+table_bytes_local(provider);
        adapter=fixture.adapters(center_index,noise_index); %#ok<NASGU>
        adapter_path=fullfile(root,sprintf('adapter_n%d_c%d.mat', ...
            noise_index,center_index));
        save(adapter_path,'adapter','-v7'); paths.adapters{center_index,noise_index}=adapter_path;
        item=dir(adapter_path); adapter_bytes=adapter_bytes+item.bytes;
    end
    provider=fixture.providers(noise_index); %#ok<NASGU>
    shared_path=fullfile(root,sprintf('shared_n%d.mat',noise_index));
    save(shared_path,'provider','-v7');paths.shared{noise_index}=shared_path;
    shared_item=dir(shared_path);shared_bytes=shared_item.bytes+adapter_bytes;
    shared_table=table_bytes_local(provider);
    provider_mean=independent_bytes/8; adapter_mean=adapter_bytes/8;
    storage(noise_index)=struct( ...
        'independent_storage_bytes',independent_bytes, ...
        'shared_storage_bytes',shared_bytes, ...
        'storage_reduction',1-shared_bytes/independent_bytes, ...
        'independent_logical_table_bytes',independent_table, ...
        'shared_logical_table_bytes',shared_table, ...
        'adapter_bytes',adapter_bytes, ...
        'center_192_storage_reduction', ...
        1-(shared_item.bytes+192*adapter_mean)/(192*provider_mean));
end
end

function bytes=table_bytes_local(provider)
names={'G_single_or_certified','G_single_exact_shape', ...
    'G_pair_first_exact_shape','G_pair_second_exact_shape'};
bytes=0;
for index=1:numel(names)
    value=provider.(names{index});
    bytes=bytes+numel(value)*8*(1+~isreal(value));
end
end
