function [G, indices] = stage8_k2_mc_get_manifold( ...
    angles_deg, model, local_domain, provider, adapter)
%STAGE8_K2_MC_GET_MANIFOLD Map global angles to one shared relative table.

validate_guard_local(model, local_domain, provider, adapter);
K = size(angles_deg, 1);
if ~(isnumeric(angles_deg) && ismatrix(angles_deg) && ...
        size(angles_deg, 2) == 2 && ismember(K, [1,2]) && ...
        all(isfinite(angles_deg(:))))
    error('stage8_k2_mc_get_manifold:Angles', ...
        'Only finite registered K1/K2 global angles are supported.');
end
indices = zeros(1, K);
for target = 1:K
    delta = stage8_k2_mc_periodic_difference( ...
        angles_deg(target, 1), adapter.physical_center_az_deg);
    az_index = 1 + round((delta - provider.delta_origin_deg) / ...
        provider.delta_step_deg);
    el_index = 1 + round((angles_deg(target, 2) - ...
        provider.el_origin_deg) / provider.el_step_deg);
    if az_index < 1 || az_index > numel(provider.relative_delta_grid_deg) || ...
            el_index < 1 || el_index > numel(provider.el_grid_deg) || ...
            abs(delta - provider.relative_delta_grid_deg(az_index)) > ...
                provider.key_tolerance_deg || ...
            abs(angles_deg(target, 2) - provider.el_grid_deg(el_index)) > ...
                provider.key_tolerance_deg
        error('stage8_k2_mc_get_manifold:OffGrid', ...
            'REGISTERED_BACKBONE_CONTRACT_MISS_STOP: off-grid angle.');
    end
    indices(target) = double(provider.index_lut(az_index, el_index));
    if indices(target) < 1
        error('stage8_k2_mc_get_manifold:MissingKey', ...
            'REGISTERED_BACKBONE_CONTRACT_MISS_STOP: key is absent.');
    end
end
if K == 1
    G = provider.G_single_exact_shape(:, indices);
else
    G = [provider.G_pair_first_exact_shape(:, indices(1)), ...
        provider.G_pair_second_exact_shape(:, indices(2))];
end
end

function validate_guard_local(model, domain, provider, adapter)
required_provider = {'schema_version','mode','rotation_class_hash', ...
    'provider_hash','relative_delta_grid_deg','el_grid_deg', ...
    'index_lut','G_single_exact_shape','G_pair_first_exact_shape', ...
    'G_pair_second_exact_shape','validate_once_status', ...
    'formal_contract_miss_stop','immutable','phase_factor'};
required_adapter = {'schema_version','actual_center_hash', ...
    'model_fixed_measurement_hash','rotation_class_hash', ...
    'shared_provider_hash','physical_center_az_deg','absolute_domain_hash', ...
    'adapter_certification_status','immutable','phase_factor'};
required_model = {'fixed_measurement_hash','rotation_class_hash', ...
    'actual_center_hash','phase_factor'};
if ~(isstruct(provider) && isscalar(provider) && ...
        all(isfield(provider, required_provider)) && provider.immutable && ...
        provider.formal_contract_miss_stop && ...
        strcmp(provider.schema_version, ...
        'STAGE8_K2_MULTICENTER_SHARED_PROVIDER_V1') && ...
        strcmp(provider.mode, 'REGISTERED_CACHE') && ...
        strcmp(provider.validate_once_status, 'VALIDATE_ONCE_COMPLETE'))
    error('stage8_k2_mc_get_manifold:Provider', ...
        'The shared provider contract is incomplete.');
end
if ~(isstruct(adapter) && isscalar(adapter) && ...
        all(isfield(adapter, required_adapter)) && adapter.immutable && ...
        strcmp(adapter.schema_version, ...
        'STAGE8_K2_MULTICENTER_CENTER_ADAPTER_V1') && ...
        strcmp(adapter.adapter_certification_status, ...
        'CENTER_ADAPTER_INDEPENDENTLY_CERTIFIED'))
    error('stage8_k2_mc_get_manifold:Adapter', ...
        'The center adapter contract is incomplete.');
end
if ~(isstruct(model) && isscalar(model) && ...
        all(isfield(model, required_model)))
    error('stage8_k2_mc_get_manifold:Model', ...
        'The multicenter model identity is incomplete.');
end
if ~strcmp(provider.rotation_class_hash, adapter.rotation_class_hash) || ...
        ~strcmp(provider.provider_hash, adapter.shared_provider_hash) || ...
        ~strcmp(model.rotation_class_hash, adapter.rotation_class_hash) || ...
        ~strcmp(model.actual_center_hash, adapter.actual_center_hash) || ...
        ~strcmp(model.fixed_measurement_hash, ...
        adapter.model_fixed_measurement_hash) || ...
        ~strcmp(char(string(domain.domain_hash)), ...
        adapter.absolute_domain_hash) || ...
        any([provider.phase_factor, adapter.phase_factor, ...
        model.phase_factor] ~= 1)
    error('stage8_k2_mc_get_manifold:Identity', ...
        'Provider, adapter, model, or domain identity mismatch.');
end
end
