function centers = stage8_k2_mc_select_centers(spec, offsets)
%STAGE8_K2_MC_SELECT_CENTERS Resolve integer physical-column rotations.

if nargin < 2 || isempty(offsets)
    offsets = spec.selected_center_offsets;
end
offsets = double(offsets(:));
if any(offsets ~= fix(offsets)) || numel(unique(offsets)) ~= numel(offsets)
    error('stage8_k2_mc_select_centers:Offsets', ...
        'Center offsets must be unique integer column shifts.');
end
rows = repmat(template_local(), numel(offsets), 1);
phi_col = double(spec.reference_pool.array_meta.phiCol);
for index = 1:numel(offsets)
    offset = offsets(index);
    column = mod(spec.reference_center_column - 1 + offset, spec.Naz) + 1;
    delta = offset * spec.dPhi_deg;
    physical_wrapped = phi_col(column);
    physical_unwrapped = spec.reference_physical_center_az_deg + delta;
    if abs(stage8_k2_mc_periodic_difference( ...
            physical_unwrapped, physical_wrapped)) > 1e-12
        error('stage8_k2_mc_select_centers:PhysicalCenter', ...
            'BLOCKED_PHYSICAL_CENTER_SELECTION_MISMATCH.');
    end
    rows(index) = struct( ...
        'center_index',index, 'column_offset',offset, ...
        'rotation_delta_deg',delta, 'center_column',column, ...
        'requested_center_az_deg', ...
            spec.reference_requested_center_az_deg + delta, ...
        'physical_center_az_deg',physical_wrapped, ...
        'physical_center_unwrapped_az_deg',physical_unwrapped, ...
        'center_id',sprintf('MC_COL_%03d_OFFSET_%+04d', column, offset));
end
centers = rows;
end

function value = template_local()
value = struct('center_index',0, 'column_offset',0, ...
    'rotation_delta_deg',0, 'center_column',0, ...
    'requested_center_az_deg',NaN, 'physical_center_az_deg',NaN, ...
    'physical_center_unwrapped_az_deg',NaN, 'center_id','');
end
