function info = stage8_k2_mc_validate_shared_provider(provider)
%STAGE8_K2_MC_VALIDATE_SHARED_PROVIDER Fully validate one loaded table.

required = {'schema_version','provider_hash','rotation_class_hash', ...
    'index_lut','G_single_exact_shape','G_pair_first_exact_shape', ...
    'G_pair_second_exact_shape','artifact_hash','phase_factor', ...
    'immutable','formal_contract_miss_stop','validate_once_status'};
if ~(isstruct(provider) && isscalar(provider) && ...
        all(isfield(provider,required)) && provider.immutable && ...
        provider.formal_contract_miss_stop && provider.phase_factor==1 && ...
        strcmp(provider.schema_version, ...
        'STAGE8_K2_MULTICENTER_SHARED_PROVIDER_V1') && ...
        strcmp(provider.validate_once_status,'VALIDATE_ONCE_COMPLETE'))
    error('stage8_k2_mc_validate_shared_provider:Contract', ...
        'The shared provider contract is incomplete.');
end
semantic=rmfield(provider,'provider_hash');
actual=stage8_k2_tecs_sha256( ...
    'STAGE8_K2_MULTICENTER_SHARED_PROVIDER_V1',semantic);
if ~strcmp(actual,provider.provider_hash) || nnz(provider.index_lut)~=21 || ...
        size(provider.G_single_exact_shape,2)~=21 || ...
        size(provider.G_pair_first_exact_shape,2)~=21 || ...
        size(provider.G_pair_second_exact_shape,2)~=21
    error('stage8_k2_mc_validate_shared_provider:Hash', ...
        'The loaded shared provider failed semantic validation.');
end
info=struct('status','MULTICENTER_SHARED_PROVIDER_VALIDATE_ONCE_PASS', ...
    'provider_hash',provider.provider_hash,'entry_count',21,'pass',true);
end
