function locked = stage8_k2_mc_build_rotated_stage5_config(spec, center)
%STAGE8_K2_MC_BUILD_ROTATED_STAGE5_CONFIG Rotate only absolute azimuths.

locked = spec.reference_stage5_config;
locked.conventional_center_deg(1) = ...
    locked.conventional_center_deg(1) + center.rotation_delta_deg;
locked.az_beam_deg = locked.az_beam_deg + center.rotation_delta_deg;
locked.configuration_hash = build_stage5_configuration_hash(locked);
class_payload = stage8_k2_mc_stage5_class_payload( ...
    locked, center.physical_center_unwrapped_az_deg);
locked.stage5_rotation_class_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_STAGE5_ROTATION_CLASS_V1', class_payload);
actual_payload = struct( ...
    'configuration_hash',locked.configuration_hash, ...
    'requested_center_az_deg',center.requested_center_az_deg, ...
    'physical_center_az_deg',center.physical_center_az_deg, ...
    'physical_center_unwrapped_az_deg', ...
        center.physical_center_unwrapped_az_deg, ...
    'center_column',center.center_column, ...
    'rotation_delta_deg',center.rotation_delta_deg, ...
    'absolute_conventional_center_deg',locked.conventional_center_deg, ...
    'absolute_az_beam_deg',locked.az_beam_deg);
locked.stage5_actual_center_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_STAGE5_ACTUAL_CENTER_V1', actual_payload);
locked.stage5_requested_center_az_deg = center.requested_center_az_deg;
locked.stage5_physical_center_az_deg = center.physical_center_az_deg;
locked.stage5_physical_center_unwrapped_az_deg = ...
    center.physical_center_unwrapped_az_deg;
locked.stage5_center_column = center.center_column;
locked.stage5_rotation_delta_deg = center.rotation_delta_deg;
locked.stage5_rotation_certification_status = ...
    'STAGE8_K2_MC_STAGE5_ROTATION_CERTIFIED';
locked.stage5_reference_configuration_hash = ...
    spec.reference_stage5_config.configuration_hash;
end
