function output = stage8_k2_mc_run_semantics(fixture)
%STAGE8_K2_MC_RUN_SEMANTICS Gate B compact production semantics.

registry = fixture.semantic_case_registry;
if height(registry) ~= 24
    error('stage8_k2_mc_run_semantics:Registry', ...
        'The compact semantic registry must contain 24 cases.');
end
[center_providers, dictionaries] = build_center_controls_local(fixture);
rows = cell(height(registry),1);
shared_results = cell(height(registry),1);
shared_diagnostics = cell(height(registry),1);
shared_audits = cell(height(registry),1);
shared_trials = cell(height(registry),1);
for case_index = 1:height(registry)
    row = registry(case_index,:);
    draw_mode = char(row.draw_mode);
    trial = stage8_k2_mc_generate_paired_trial(fixture,row,draw_mode);
    center_slot = find([1,-8,96] == double(row.center_offset),1);
    noise_index = find(fixture.noise_profile_ids == ...
        string(row.noise_profile_id),1);
    dictionary = dictionaries{center_slot,noise_index};
    [legacy, legacy_diag, legacy_audit] = audited_fit_local( ...
        trial, fixture.spec.context, [], [], ...
        'LEGACY_FULL', dictionary);
    provider = fixture.providers(noise_index);
    adapter = fixture.adapters(double(row.center_index),noise_index);
    [shared, shared_diag, shared_audit] = audited_fit_local( ...
        trial, fixture.spec.context, provider, adapter, ...
        'REGISTERED_CACHE', dictionary);
    metrics = compare_roots_local(legacy,legacy_diag,legacy_audit, ...
        shared,shared_diag,shared_audit);
    rows{case_index} = semantic_row_local(row,trial,metrics,shared_diag);
    shared_results{case_index}=shared;
    shared_diagnostics{case_index}=shared_diag;
    shared_audits{case_index}=shared_audit;
    shared_trials{case_index}=trial;
    fprintf('MC SEMANTICS %02d/24 %s pass=%d angle=%.3g rss=%.3g\n', ...
        case_index,char(row.trial_id),metrics.pass,metrics.angle_error, ...
        metrics.rss_error);
    if ~metrics.pass
        error('stage8_k2_mc_run_semantics:SemanticMismatch', ...
            'BLOCKED_SHARED_CACHE_SEMANTIC_MISMATCH at %s.', ...
            char(row.trial_id));
    end
end
semantics = struct2table(vertcat(rows{:}));
controls = center_cache_controls_local(fixture,registry,shared_results, ...
    shared_diagnostics,shared_audits,shared_trials,center_providers,dictionaries);
covariance = rotation_covariance_local(fixture,registry,shared_results, ...
    shared_diagnostics);
output = struct('schema_version','STAGE8_K2_MC_SEMANTICS_V1', ...
    'semantics',semantics,'center_cache_controls',controls, ...
    'rotation_covariance',covariance,'semantic_pass_count',nnz(semantics.pass), ...
    'case_count',height(semantics),'control_pass_count',nnz(controls.pass), ...
    'covariance_pass_count',nnz(covariance.pass), ...
    'truth_leakage_count',sum(semantics.truth_leakage_count), ...
    't4_cache_query_count',sum(semantics.t4_cache_query_count), ...
    'status','STAGE8_K2_MULTICENTER_SEMANTIC_PASS_24_OF_24');
if output.semantic_pass_count~=24 || output.control_pass_count~=6 || ...
        output.covariance_pass_count~=8 || output.truth_leakage_count~=0 || ...
        output.t4_cache_query_count~=0
    error('stage8_k2_mc_run_semantics:GateB', ...
        'BLOCKED_SHARED_CACHE_SEMANTIC_MISMATCH.');
end
end

function [providers,dictionaries]=build_center_controls_local(fixture)
offsets=[1,-8,96]; providers=cell(3,2); dictionaries=cell(3,2);
for center_slot=1:3
    center_index=find([fixture.centers.column_offset]==offsets(center_slot),1);
    for noise_index=1:2
        bundle=fixture.bundles(center_index,noise_index);
        [dictionaries{center_slot,noise_index},~]= ...
            stage8_k2_tcc_build_registered_dictionary( ...
            bundle.model,bundle.local_domain,struct());
        [providers{center_slot,noise_index},~]=stage8_k2_tfbc_build_provider( ...
            bundle.model,bundle.local_domain,struct( ...
            'timed_diagnostics_enabled',false));
    end
end
end

function [result,diag,audit]=audited_fit_local( ...
    trial,context,provider,adapter,mode,dictionary)
full_data=build_stage8_full_data_from_element(trial.Y_element,trial.model, ...
    struct('data_role','SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
metadata=struct('trial_id',trial.trial_id, ...
    'noise_profile_id',trial.model.noise_profile_id, ...
    'fixed_measurement_hash',trial.model.fixed_measurement_hash);
stage8_k2_tcc_audit_state('CONFIGURE',struct('mode','QUERY', ...
    'dictionary',dictionary,'model',trial.model, ...
    'Zseq_white',full_data.Zseq_white,'trial_metadata',metadata));
stage8_k2_tfbc_diagnostics_state('RESET');
[result,diag]=stage8_k2_mc_fit_mode(trial,context,provider,adapter,mode);
audit=stage8_k2_tcc_audit_state('GET_QUERY');
audit.fixed_exposure=stage8_k2_tfbc_diagnostics_state('SNAPSHOT');
stage8_k2_tcc_audit_state('CONFIGURE',struct('mode','OFF'));
end

function metrics=compare_roots_local(a,ad,aa,b,bd,ba)
metrics=struct();
metrics.angle_error=numeric_error_local(a.angles_hat_deg,b.angles_hat_deg);
metrics.rss_error=scaled_error_local(a.rss,b.rss);
metrics.loglik_error=scaled_error_local(a.loglik_concentrated,b.loglik_concentrated);
metrics.k1_angle_error=numeric_error_local(ad.K1_center_deg,bd.K1_center_deg);
metrics.direction_error=numeric_error_local(ad.direction_hat,bd.direction_hat);
metrics.rho_error=numeric_error_local(ad.rho_hat_deg,bd.rho_hat_deg);
metrics.raw_angle_error=numeric_error_local(ad.raw_tangent_angles_deg, ...
    bd.raw_tangent_angles_deg);
metrics.decision_equal=isequaln(decision_projection_local(a,ad), ...
    decision_projection_local(b,bd));
metrics.trajectory_equal=isequaln(trajectory_projection_local(aa), ...
    trajectory_projection_local(ba));
metrics.truth_leakage_count=truth_leakage_local(a,ad,aa)+ ...
    truth_leakage_local(b,bd,ba);
metrics.t4_cache_query_count=double(bd.cache_hit_count)+ ...
    double(bd.cache_miss_count)+double(bd.direct_fallback_count)+ ...
    double(ba.fixed_exposure.t4_cache_query_count);
metrics.pass=a.fit_valid==b.fit_valid && metrics.decision_equal && ...
    metrics.trajectory_equal && metrics.angle_error<=2e-4 && ...
    metrics.k1_angle_error<=2e-4 && metrics.raw_angle_error<=2e-4 && ...
    metrics.rss_error<=1e-8 && metrics.loglik_error<=1e-8 && ...
    metrics.direction_error<=2e-4 && metrics.rho_error<=2e-4 && ...
    metrics.truth_leakage_count==0 && metrics.t4_cache_query_count==0;
end

function value=decision_projection_local(result,diag)
value=struct('fit_valid',logical(result.fit_valid), ...
    'fit_status',char(result.fit_status),'selected_source',char(result.selected_source), ...
    'selected_start_id',char(result.selected_start_id), ...
    'effective_rank',double(result.effective_rank), ...
    'score_call_count',double(result.score_call_count), ...
    'svd_call_count',double(result.svd_call_count), ...
    'direction_status',char(diag.direction_status), ...
    'profile_status',char(diag.profile_status), ...
    'upgrade_flag',logical(diag.upgrade_flag), ...
    'fallback_flag',logical(diag.fallback_flag), ...
    'fallback_reason',char(diag.fallback_reason), ...
    'raw_tangent_candidate_valid',logical(diag.raw_tangent_candidate_valid));
end

function value=trajectory_projection_local(audit)
value=struct();
value.groups=project_struct_local(audit.candidate_groups, ...
    {'stage_id','candidate_count','production_best_candidate_index', ...
    'direct_tie_set','target_index','dimension_index'});
value.fits=project_struct_local(audit.fit_snapshots, ...
    {'role','K','rank','selected_start'});
value.nested=project_struct_local(audit.nested_records, ...
    {'stage_id','direct_anchor_index','direct_nested_pass'});
value.selector=project_struct_local(audit.selector_records, ...
    {'direct_source'});
value.initialization=project_struct_local(audit.initialization_snapshots, ...
    {'role','initialization_output_hash'});
value.stages=project_struct_local(audit.stage_rows, ...
    {'stage_id','manifold_build_count','requested_column_count', ...
    'dml_score_count','single_count','pair_count','off_grid_column_count', ...
    'key_histogram'});
end

function out=project_struct_local(input,names)
if isempty(input), out=struct([]); return; end
out=repmat(cell2struct(cell(size(names)),names,2),numel(input),1);
for i=1:numel(input)
    for n=1:numel(names), out(i).(names{n})=input(i).(names{n}); end
end
end

function row=semantic_row_local(spec,trial,m,diag)
row=struct('case_index',double(spec.case_index), 'trial_id',string(spec.trial_id), ...
    'center_offset',double(spec.center_offset), ...
    'noise_profile_id',string(spec.noise_profile_id), ...
    'profile_id',string(spec.profile_id), ...
    'element_trial_hash',string(trial.element_trial_hash), ...
    'decision_equal',m.decision_equal,'trajectory_equal',m.trajectory_equal, ...
    'angle_error_deg',m.angle_error,'K1_angle_error_deg',m.k1_angle_error, ...
    'direction_error',m.direction_error,'rho_error_deg',m.rho_error, ...
    'raw_angle_error_deg',m.raw_angle_error,'rss_error',m.rss_error, ...
    'loglik_error',m.loglik_error,'t4_cache_query_count',m.t4_cache_query_count, ...
    'truth_leakage_count',m.truth_leakage_count, ...
    'fixed_fallback_reason',string(diag.fallback_reason),'pass',m.pass);
end

function rows=center_cache_controls_local(fixture,registry,shared_results, ...
    shared_diags,shared_audits,trials,providers,dictionaries)
indices=find(strcmp(registry.profile_id,'P1'));
records=cell(numel(indices),1);
for k=1:numel(indices)
    i=indices(k); row=registry(i,:); slot=find([1,-8,96]==double(row.center_offset),1);
    noise=find(fixture.noise_profile_ids==string(row.noise_profile_id),1);
    [r,d,a]=audited_fit_local(trials{i},fixture.spec.context, ...
        providers{slot,noise},[],'REGISTERED_CACHE',dictionaries{slot,noise});
    m=compare_roots_local(r,d,a,shared_results{i},shared_diags{i}, ...
        shared_audits{i});
    records{k}=struct('case_index',double(row.case_index),'center_offset',double(row.center_offset), ...
        'noise_profile_id',string(row.noise_profile_id),'angle_error_deg',m.angle_error, ...
        'rss_error',m.rss_error,'loglik_error',m.loglik_error, ...
        'decision_equal',m.decision_equal,'trajectory_equal',m.trajectory_equal, ...
        'pass',m.pass);
end
rows=struct2table(vertcat(records{:}));
end

function rows=rotation_covariance_local(fixture,registry,shared_results,shared_diags)
mask=ismember(registry.center_offset,[1,96]) & ismember(registry.profile_id,["P1","P4"]);
indices=find(mask); records=cell(numel(indices),1);
for k=1:numel(indices)
    i=indices(k); row=registry(i,:); refrow=row; refrow.center_offset=0; refrow.center_index=1;
    refrow.trial_id=string(row.trial_id)+"_REF";
    reftrial=stage8_k2_mc_generate_paired_trial( ...
        fixture,refrow,char(row.draw_mode));
    noise=find(fixture.noise_profile_ids==string(row.noise_profile_id),1);
    [rr,rd]=stage8_k2_mc_fit_mode(reftrial,fixture.spec.context, ...
        fixture.providers(noise),fixture.adapters(1,noise),'REGISTERED_CACHE');
    center=fixture.centers(double(row.center_index)); shifted=shared_results{i}.angles_hat_deg;
    shifted(:,1)=shifted(:,1)-center.rotation_delta_deg;
    angle=numeric_error_local(shifted,rr.angles_hat_deg);
    direction=numeric_error_local(shared_diags{i}.direction_hat,rd.direction_hat);
    rho=numeric_error_local(shared_diags{i}.rho_hat_deg,rd.rho_hat_deg);
    decision=strcmp(shared_results{i}.selected_source,rr.selected_source) && ...
        shared_diags{i}.upgrade_flag==rd.upgrade_flag && ...
        shared_diags{i}.fallback_flag==rd.fallback_flag;
    records{k}=struct('case_index',double(row.case_index),'center_offset',double(row.center_offset), ...
        'noise_profile_id',string(row.noise_profile_id),'profile_id',string(row.profile_id), ...
        'angle_error_deg',angle,'direction_error',direction,'rho_error_deg',rho, ...
        'decision_equal',decision,'pass',decision && angle<=2e-4 && ...
        direction<=2e-4 && rho<=2e-4);
end
rows=struct2table(vertcat(records{:}));
end

function count=truth_leakage_local(result,diag,audit)
count=double(result.truth_used_in_fit_flag)+double(diag.selection_truth_used_flag)+ ...
    double(audit.truth_used_in_fit_flag)+double(audit.cache_truth_used_flag)+ ...
    double(audit.placement_truth_used_flag);
end
function value=scaled_error_local(a,b)
if ~(isfinite(a) && isfinite(b))
    if isequaln(a,b), value=0; else, value=Inf; end
    return;
end
value=abs(a-b)/max([1,abs(a),abs(b)]);
end
function value=numeric_error_local(a,b)
if ~isequal(size(a),size(b)), value=Inf; return; end
if any(~isfinite(a(:))) || any(~isfinite(b(:)))
    if isequaln(a,b), value=0; else, value=Inf; end
    return;
end
value=max(abs(a(:)-b(:)));
end
