function identity = stage8_k2_mc_build_rotation_class_identity( ...
    spec, center, pool, domain, stage5_locked, model)
%STAGE8_K2_MC_BUILD_ROTATION_CLASS_IDENTITY Build class and placement IDs.

canonical_geometry = canonical_geometry_local( ...
    pool.array_meta, center.rotation_delta_deg);
relative_beam = round(pool.azimuth_beam_deg - ...
    center.physical_center_unwrapped_az_deg, 12);
relative_domain = round(domain.az_grid_deg - ...
    center.physical_center_unwrapped_az_deg, 12);
canonical_W = struct('real',round(real(model.Wseq), 12), ...
    'imag',round(imag(model.Wseq), 12));
rotation_payload = struct( ...
    'schema_version','STAGE8_K2_MC_ROTATION_CLASS_IDENTITY_V1', ...
    'phase_factor',model.phase_factor, ...
    'steering_sign','EXP_POSITIVE_J_K_R_DOT_U', ...
    'lambda',model.lambda, ...
    'canonical_local_geometry',canonical_geometry, ...
    'local_element_order',model.element_order, ...
    'subarray_shape',size(pool.array_meta.XAct), ...
    'relative_azimuth_beam_deg',relative_beam, ...
    'elevation_beam_deg',round(pool.elevation_beam_deg, 12), ...
    'relative_registered_delta_deg',relative_domain, ...
    'elevation_registered_grid_deg',round(domain.el_grid_deg, 12), ...
    'measurement_config_id',model.measurement_config_id, ...
    'subset_id',model.subset_id, 'subset_channels',model.channels, ...
    'noise_profile_id',model.noise_profile_id, ...
    'R_el',model.noise_factorization.R_el, ...
    'R_az',model.noise_factorization.R_az, ...
    'noise_factorization_hash', ...
        model.noise_factorization.factorization_hash, ...
    'whitening_contract',model.whitening_coordinate_contract, ...
    'canonical_whitener',model.Tseq, ...
    'canonical_sequential_weights',canonical_W, ...
    'K1_shape',uint64([size(model.Tseq, 1),1]), ...
    'K2_shape',uint64([size(model.Tseq, 1),2]), ...
    'numeric_class',class(model.Wseq), ...
    'stage5_rotation_class_hash', ...
        stage5_locked.stage5_rotation_class_hash);
rotation_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_ROTATION_CLASS_IDENTITY_V1', rotation_payload);

absolute_geometry_hash = stage8_stable_hash( ...
    pool.array_meta.XAct, pool.array_meta.YAct, pool.array_meta.ZAct, ...
    pool.array_meta.colsAct, model.element_order);
absolute_beam_hash = stage8_stable_hash(pool.azimuth_beam_deg, ...
    pool.elevation_beam_deg, pool.W0_hash, model.channels);
actual_payload = struct( ...
    'schema_version','STAGE8_K2_MC_ACTUAL_CENTER_IDENTITY_V1', ...
    'actual_center_column',center.center_column, ...
    'physical_center_az_deg',center.physical_center_az_deg, ...
    'physical_center_unwrapped_az_deg', ...
        center.physical_center_unwrapped_az_deg, ...
    'requested_center_az_deg',center.requested_center_az_deg, ...
    'rotation_delta_deg',center.rotation_delta_deg, ...
    'absolute_active_geometry_hash',absolute_geometry_hash, ...
    'absolute_beam_centers_deg',pool.azimuth_beam_deg, ...
    'absolute_beam_layout_hash',absolute_beam_hash, ...
    'absolute_registered_domain',domain.candidate_points_deg, ...
    'absolute_domain_hash',domain.domain_hash, ...
    'actual_model_hash',model.fixed_measurement_hash, ...
    'actual_stage5_config_hash',stage5_locked.configuration_hash, ...
    'actual_stage5_identity_hash', ...
        stage5_locked.stage5_actual_center_hash);
actual_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_ACTUAL_CENTER_IDENTITY_V1', actual_payload);
reference_geometry = canonical_geometry_local( ...
    spec.reference_pool.array_meta, 0);
geometry_error = norm(canonical_geometry - reference_geometry, 'fro') / ...
    max(norm(reference_geometry, 'fro'), realmin);
identity = struct( ...
    'schema_version','STAGE8_K2_MC_TWO_LEVEL_IDENTITY_V1', ...
    'rotation_class_hash',rotation_hash, ...
    'actual_center_hash',actual_hash, ...
    'absolute_active_geometry_hash',absolute_geometry_hash, ...
    'absolute_beam_layout_hash',absolute_beam_hash, ...
    'absolute_domain_hash',domain.domain_hash, ...
    'actual_model_hash',model.fixed_measurement_hash, ...
    'actual_stage5_config_hash',stage5_locked.configuration_hash, ...
    'stage5_rotation_class_hash', ...
        stage5_locked.stage5_rotation_class_hash, ...
    'canonical_geometry_relative_error',geometry_error, ...
    'relative_azimuth_beam_deg',relative_beam, ...
    'relative_registered_delta_deg',relative_domain, ...
    'rotation_payload_hash',rotation_hash, ...
    'actual_payload_hash',actual_hash);
end

function coordinates = canonical_geometry_local(array_meta, delta_deg)
x = double(array_meta.XAct.');
y = double(array_meta.YAct.');
z = double(array_meta.ZAct.');
x_reference = cosd(delta_deg) * x + sind(delta_deg) * y;
y_reference = -sind(delta_deg) * x + cosd(delta_deg) * y;
coordinates = round([x_reference(:), y_reference(:), z(:)], 13);
coordinates(coordinates == 0) = 0;
end
