function validation = stage8_k2_mc_validate_rotation_class( ...
    spec, bundle, expected_rotation_hash)
%STAGE8_K2_MC_VALIDATE_ROTATION_CLASS Recompute and fail closed.

if nargin < 3, expected_rotation_hash = ''; end
required = {'center','pool','local_domain','stage5_locked','model','identity'};
if ~(isstruct(bundle) && isscalar(bundle) && all(isfield(bundle, required)))
    error('stage8_k2_mc_validate_rotation_class:Bundle', ...
        'The production bundle is incomplete.');
end
center = bundle.center;
model = bundle.model;
array_meta = model.array_meta;
physical = double(array_meta.phiCol(array_meta.colCtr));
if array_meta.colCtr ~= center.center_column || ...
        abs(stage8_k2_mc_periodic_difference(physical, ...
        center.physical_center_az_deg)) > 1e-12 || ...
        abs(double(array_meta.azCtr) - center.requested_center_az_deg) > 1e-12
    error('stage8_k2_mc_validate_rotation_class:PhysicalCenter', ...
        'BLOCKED_PHYSICAL_CENTER_SELECTION_MISMATCH.');
end
actual_stage5_hash = build_stage5_configuration_hash(bundle.stage5_locked);
if ~strcmp(actual_stage5_hash, bundle.stage5_locked.configuration_hash)
    error('stage8_k2_mc_validate_rotation_class:Stage5Hash', ...
        'BLOCKED_STAGE5_ROTATION_CONTRACT.');
end
stage5_payload = stage8_k2_mc_stage5_class_payload( ...
    bundle.stage5_locked, center.physical_center_unwrapped_az_deg);
stage5_class_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_STAGE5_ROTATION_CLASS_V1', stage5_payload);
if ~strcmp(stage5_class_hash, ...
        bundle.stage5_locked.stage5_rotation_class_hash)
    error('stage8_k2_mc_validate_rotation_class:Stage5Class', ...
        'BLOCKED_STAGE5_ROTATION_CONTRACT.');
end
recomputed = stage8_k2_mc_build_rotation_class_identity( ...
    spec, center, bundle.pool, bundle.local_domain, ...
    bundle.stage5_locked, model);
if ~strcmp(recomputed.rotation_class_hash, ...
        bundle.identity.rotation_class_hash) || ...
        ~strcmp(recomputed.actual_center_hash, ...
        bundle.identity.actual_center_hash)
    error('stage8_k2_mc_validate_rotation_class:DeclaredIdentity', ...
        'BLOCKED_ROTATION_CLASS_IDENTITY_FAILED.');
end
if ~isempty(expected_rotation_hash) && ...
        ~strcmp(recomputed.rotation_class_hash, ...
        char(string(expected_rotation_hash)))
    error('stage8_k2_mc_validate_rotation_class:RotationClass', ...
        'BLOCKED_ROTATION_CLASS_IDENTITY_FAILED.');
end
if recomputed.canonical_geometry_relative_error > 1e-13
    error('stage8_k2_mc_validate_rotation_class:Geometry', ...
        'BLOCKED_LOCAL_ELEMENT_ORDER_MISMATCH.');
end
validation = struct( ...
    'status','STAGE8_K2_MC_ROTATION_CLASS_ADMISSION_PASS', ...
    'rotation_class_hash',recomputed.rotation_class_hash, ...
    'actual_center_hash',recomputed.actual_center_hash, ...
    'canonical_geometry_relative_error', ...
        recomputed.canonical_geometry_relative_error, ...
    'stage5_rotation_class_hash',stage5_class_hash, ...
    'pass',true);
end
