function info = stage8_k2_mc_validate_center_adapter(adapter,provider,bundle)
%STAGE8_K2_MC_VALIDATE_CENTER_ADAPTER Fully validate one loaded adapter.

required={'schema_version','adapter_hash','actual_center_hash', ...
    'model_fixed_measurement_hash','rotation_class_hash', ...
    'shared_provider_hash','absolute_domain_hash', ...
    'adapter_certification_status','phase_factor','immutable'};
if ~(isstruct(adapter)&&isscalar(adapter)&&all(isfield(adapter,required))&& ...
        adapter.immutable&&adapter.phase_factor==1&& ...
        strcmp(adapter.schema_version, ...
        'STAGE8_K2_MULTICENTER_CENTER_ADAPTER_V1')&& ...
        strcmp(adapter.adapter_certification_status, ...
        'CENTER_ADAPTER_INDEPENDENTLY_CERTIFIED'))
    error('stage8_k2_mc_validate_center_adapter:Contract', ...
        'The center adapter contract is incomplete.');
end
semantic=rmfield(adapter,'adapter_hash');
actual=stage8_k2_tecs_sha256( ...
    'STAGE8_K2_MULTICENTER_CENTER_ADAPTER_V1',semantic);
if ~strcmp(actual,adapter.adapter_hash)|| ...
        ~strcmp(adapter.shared_provider_hash,provider.provider_hash)|| ...
        ~strcmp(adapter.rotation_class_hash,provider.rotation_class_hash)|| ...
        ~strcmp(adapter.actual_center_hash,bundle.identity.actual_center_hash)|| ...
        ~strcmp(adapter.model_fixed_measurement_hash,bundle.model.fixed_measurement_hash)|| ...
        ~strcmp(adapter.absolute_domain_hash,bundle.local_domain.domain_hash)|| ...
        any(startsWith(fieldnames(adapter),'G_'))
    error('stage8_k2_mc_validate_center_adapter:Identity', ...
        'The loaded center adapter failed identity validation.');
end
info=struct('status','MULTICENTER_CENTER_ADAPTER_VALIDATE_ONCE_PASS', ...
    'adapter_hash',adapter.adapter_hash,'pass',true);
end
