function table_out = stage8_k2_mc_static_metric_table(static, whitener)
%STAGE8_K2_MC_STATIC_METRIC_TABLE Add metric roles and explicit gates.

rows = { ...
    'GEOMETRY_192_COUNT',height(static.geometry), ...
        'GATED_PHYSICAL_ROTATION_EQUIVALENCE',192,'PASS'; ...
    'GEOMETRY_192_MAX_RELATIVE_ERROR', ...
        max(static.geometry.geometry_relative_error), ...
        'GATED_PHYSICAL_ROTATION_EQUIVALENCE',1e-13, ...
        gate_status_local(max(static.geometry.geometry_relative_error),1e-13); ...
    'GEOMETRY_192_MAX_STEERING_ERROR', ...
        max(static.geometry.steering_relative_error), ...
        'GATED_PHYSICAL_ROTATION_EQUIVALENCE',1e-13, ...
        gate_status_local(max(static.geometry.steering_relative_error),1e-13); ...
    'PRODUCTION_MODEL_COUNT',height(static.production), ...
        'GATED_PRODUCTION_MODEL_COUNT',16,'PASS'; ...
    'MAX_W_ERROR',max(static.production.W_error), ...
        'GATED_CANONICAL_ONLINE_EQUIVALENCE',1e-11, ...
        gate_status_local(max(static.production.W_error),1e-11); ...
    'MAX_C_ERROR',max(static.production.C_error), ...
        'GATED_CANONICAL_ONLINE_EQUIVALENCE',1e-11, ...
        gate_status_local(max(static.production.C_error),1e-11); ...
    'MAX_CANONICAL_ONLINE_T_ERROR',max(static.production.T_error), ...
        'GATED_REFERENCE_PSD_COORDINATE_EQUIVALENCE',1e-10, ...
        gate_status_local(max(static.production.T_error),1e-10); ...
    'MAX_RAW_REBUILT_W_ERROR',max(static.production.raw_rebuilt_W_error), ...
        'GATED_PHYSICAL_ROTATION_EQUIVALENCE',1e-11, ...
        gate_status_local(max(static.production.raw_rebuilt_W_error),1e-11); ...
    'MAX_RAW_REBUILT_C_ERROR',max(static.production.raw_rebuilt_C_error), ...
        'GATED_PHYSICAL_ROTATION_EQUIVALENCE',1e-11, ...
        gate_status_local(max(static.production.raw_rebuilt_C_error),1e-11); ...
    'MAX_RAW_REBUILT_T_ERROR',max(static.production.raw_rebuilt_T_error), ...
        'DIAGNOSTIC_ONLY_EIGENBASIS_DEPENDENT',NaN,'DIAGNOSTIC_ONLY'; ...
    'MAX_RAW_WHITENING_RESIDUAL',whitener.max_raw_whitening_residual, ...
        'DIAGNOSTIC_ONLY_ILL_CONDITIONED_FORWARD_EVALUATION', ...
        NaN,'DIAGNOSTIC_ONLY'; ...
    'MAX_REFERENCE_WHITENING_RESIDUAL', ...
        whitener.max_reference_whitening_residual, ...
        'DIAGNOSTIC_ONLY_ILL_CONDITIONED_FORWARD_EVALUATION', ...
        NaN,'DIAGNOSTIC_ONLY'; ...
    'MAX_RAW_WHITENING_BACKWARD_ERROR', ...
        whitener.max_raw_whitening_backward_error, ...
        'GATED_BASIS_INVARIANT_WHITENING_BACKWARD_STABILITY', ...
        whitener.thresholds.whitening_backward_error, ...
        gate_status_local(whitener.max_raw_whitening_backward_error, ...
        whitener.thresholds.whitening_backward_error); ...
    'MAX_REFERENCE_WHITENING_BACKWARD_ERROR', ...
        whitener.max_reference_whitening_backward_error, ...
        'GATED_BASIS_INVARIANT_WHITENING_BACKWARD_STABILITY', ...
        whitener.thresholds.whitening_backward_error, ...
        gate_status_local(whitener.max_reference_whitening_backward_error, ...
        whitener.thresholds.whitening_backward_error); ...
    'MAX_WHITENER_Q_UNITARITY_ERROR',whitener.max_Q_unitarity_error, ...
        'GATED_CONDITIONING_INVESTIGATED_COORDINATE_MAP', ...
        whitener.thresholds.Q_unitarity_error, ...
        gate_status_local(whitener.max_Q_unitarity_error, ...
        whitener.thresholds.Q_unitarity_error); ...
    'MAX_WHITENER_ALIGNMENT_ERROR',whitener.max_alignment_error, ...
        'GATED_BASIS_INVARIANT_COORDINATE_MAP', ...
        whitener.thresholds.alignment_error, ...
        gate_status_local(whitener.max_alignment_error, ...
        whitener.thresholds.alignment_error); ...
    'MAX_WHITENER_ROW_SPACE_PROJECTOR_ERROR', ...
        whitener.max_row_space_projector_error, ...
        'FALLBACK_ONLY_RANK_DEFICIENT_COORDINATE_MAP', ...
        whitener.thresholds.row_space_projector_error, ...
        fallback_status_local(whitener); ...
    'MAX_G_ERROR',max(static.production.G_error), ...
        'GATED_SHARED_PROVIDER_EQUIVALENCE',1e-10, ...
        gate_status_local(max(static.production.G_error),1e-10); ...
    'RANK_MISMATCH',sum(static.production.rank_mismatch), ...
        'GATED_SHARED_PROVIDER_EQUIVALENCE',0, ...
        exact_status_local(sum(static.production.rank_mismatch),0); ...
    'NEGATIVE_CONTROL_COUNT',height(static.negative_controls), ...
        'GATED_FAIL_CLOSED_ADMISSION',3, ...
        exact_status_local(nnz(static.negative_controls.pass),3); ...
    'ROTATION_CLASS_HASH_UNIQUE', ...
        numel(unique(static.production.rotation_class_hash)), ...
        'GATED_TWO_LEVEL_IDENTITY',2, ...
        exact_status_local( ...
        numel(unique(static.production.rotation_class_hash)),2); ...
    'ACTUAL_CENTER_HASH_UNIQUE', ...
        numel(unique(static.production.actual_center_hash)), ...
        'GATED_TWO_LEVEL_IDENTITY',16, ...
        exact_status_local( ...
        numel(unique(static.production.actual_center_hash)),16)};
table_out = table(string(rows(:,1)),cell2mat(rows(:,2)), ...
    string(rows(:,3)),cell2mat(rows(:,4)),string(rows(:,5)), ...
    'VariableNames',{'metric','value','metric_role', ...
    'gate_threshold','gate_status'});
end

function value = fallback_status_local(whitener)
value = 'NOT_APPLICABLE';
if ~whitener.all_full_row_rank
    value = gate_status_local(whitener.max_row_space_projector_error, ...
        whitener.thresholds.row_space_projector_error);
end
end

function value = gate_status_local(metric,threshold)
value = 'FAIL';
if metric <= threshold
    value = 'PASS';
end
end

function value = exact_status_local(metric,expected)
value = 'FAIL';
if metric == expected
    value = 'PASS';
end
end
