function output = stage8_k2_mc_run_runtime_sentinel(fixture)
%STAGE8_K2_MC_RUN_RUNTIME_SENTINEL Run the compact 48-pair Gate D.

if isempty(fixture.runtime_root)
    error('stage8_k2_mc_run_runtime_sentinel:RuntimeRoot', ...
        'Gate D requires an external runtime root.');
end
if ~strcmp(version('-release'), '2022b') || maxNumCompThreads ~= 1
    error('stage8_k2_mc_run_runtime_sentinel:Environment', ...
        'MATLAB R2022b with -singleCompThread is required.');
end
semantic_path = fullfile(fixture.runtime_root, 'semantics', ...
    'semantics_output.mat');
if ~isfile(semantic_path)
    error('stage8_k2_mc_run_runtime_sentinel:Semantics', ...
        'Gate B checkpoint is required before Gate D.');
end
semantic = load(semantic_path, 'output');
if ~strcmp(semantic.output.status, ...
        'STAGE8_K2_MULTICENTER_SEMANTIC_PASS_24_OF_24')
    error('stage8_k2_mc_run_runtime_sentinel:Semantics', ...
        'Gate B did not pass.');
end
[schedule, schedule_hash] = stage8_k2_mc_build_runtime_schedule(fixture);
runtime_dir = fullfile(fixture.runtime_root, 'runtime_sentinel');
checkpoint_dir = fullfile(runtime_dir, 'pairs');
if ~isfolder(checkpoint_dir), mkdir(checkpoint_dir); end
writetable(schedule, fullfile(runtime_dir, 'runtime_schedule.csv'));
trials = build_trials_local(fixture, schedule);
warmup_local(fixture, trials, schedule_hash, runtime_dir);

payloads = cell(height(schedule), 1);
for row_index = 1:height(schedule)
    row = schedule(row_index, :);
    checkpoint_path = fullfile(checkpoint_dir, sprintf( ...
        'pair_%03d.mat', row.global_pair_index));
    if isfile(checkpoint_path)
        loaded = load(checkpoint_path, 'payload');
        if isfield(loaded, 'payload') && ...
                strcmp(loaded.payload.schedule_hash, schedule_hash) && ...
                strcmp(loaded.payload.fixture_hash, fixture.fixture_hash)
            payloads{row_index} = loaded.payload;
            continue;
        end
    end
    trial = trials{row.case_index};
    noise_index = find(fixture.noise_profile_ids == ...
        string(row.noise_profile_id), 1);
    provider = fixture.providers(noise_index);
    adapter = fixture.adapters(row.center_index, noise_index);
    if row.pair_order == "AB"
        [baseline_sec, baseline_projection] = ...
            timed_fit_local(trial, fixture.spec.context, [], [], ...
            'LEGACY_FULL');
        [cache_sec, cache_projection] = timed_fit_local( ...
            trial, fixture.spec.context, provider, adapter, ...
            'REGISTERED_CACHE');
    else
        [cache_sec, cache_projection] = timed_fit_local( ...
            trial, fixture.spec.context, provider, adapter, ...
            'REGISTERED_CACHE');
        [baseline_sec, baseline_projection] = ...
            timed_fit_local(trial, fixture.spec.context, [], [], ...
            'LEGACY_FULL');
    end
    metrics = compare_projections_local( ...
        baseline_projection, cache_projection);
    if ~metrics.pass
        error('stage8_k2_mc_run_runtime_sentinel:Projection', ...
            'BLOCKED_SHARED_CACHE_SEMANTIC_MISMATCH at pair %d.', ...
            row.global_pair_index);
    end
    result = struct('global_pair_index',row.global_pair_index, ...
        'case_index',row.case_index,'trial_id',row.trial_id, ...
        'center_offset',row.center_offset, ...
        'noise_profile_id',row.noise_profile_id, ...
        'profile_id',row.profile_id,'repeat_index',row.repeat_index, ...
        'pair_order',row.pair_order, ...
        'baseline_runtime_sec',baseline_sec, ...
        'cache_runtime_sec',cache_sec, ...
        'paired_difference_sec',baseline_sec-cache_sec, ...
        'decision_checksum_hash',string(cache_projection.exact_hash), ...
        'decision_checksum_match',metrics.exact_match, ...
        'semantic_projection_match',metrics.pass, ...
        'angle_error_deg',metrics.angle_error, ...
        'rss_error',metrics.rss_error, ...
        'loglik_error',metrics.loglik_error, ...
        'K1_angle_error_deg',metrics.K1_angle_error, ...
        'fixed_grid_loglik_error',metrics.fixed_grid_loglik_error, ...
        'direction_error',metrics.direction_error, ...
        'rho_error_deg',metrics.rho_error, ...
        'raw_angle_error_deg',metrics.raw_angle_error, ...
        'raw_loglik_error',metrics.raw_loglik_error, ...
        'metric_error',metrics.metric_error, ...
        'evaluated_rho_error_deg',metrics.evaluated_rho_error, ...
        'evaluated_loglik_error',metrics.evaluated_loglik_error);
    payload = struct('schedule_hash',schedule_hash, ...
        'fixture_hash',fixture.fixture_hash,'result',result);
    atomic_save_local(checkpoint_path, payload);
    payloads{row_index} = payload;
    fprintf('MC RUNTIME %02d/48 %s %s delta=%.6f\n', ...
        row_index,char(row.trial_id),char(row.pair_order), ...
        result.paired_difference_sec);
end
results = cellfun(@(value) value.result, payloads, ...
    'UniformOutput', false);
raw = struct2table(vertcat(results{:}));
summary = summarize_local(raw);
overall = summary(summary.row_type == "OVERALL", :);
status = "ONLINE_SENTINEL_NONPOSITIVE";
if overall.paired_point_saving_sec > 0 && ...
        overall.ab_point_saving_sec > 0 && overall.ba_point_saving_sec > 0
    status = "ONLINE_SENTINEL_POSITIVE";
elseif overall.paired_point_saving_sec > 0
    status = "ONLINE_SENTINEL_INCONCLUSIVE";
end
output = struct('schema_version','STAGE8_K2_MC_RUNTIME_SENTINEL_V1', ...
    'schedule_hash',schedule_hash,'fixture_hash',fixture.fixture_hash, ...
    'raw',raw,'summary',summary,'case_count',12,'pair_count',height(raw), ...
    'root_call_count',2*height(raw), ...
    'projection_match_count',nnz(raw.semantic_projection_match), ...
    'checksum_match_count',nnz(raw.decision_checksum_match), ...
    'max_angle_error_deg',max(raw.angle_error_deg), ...
    'max_rss_error',max(raw.rss_error), ...
    'max_loglik_error',max(raw.loglik_error), ...
    'max_fixed_grid_loglik_error',max(raw.fixed_grid_loglik_error), ...
    'matlab_release',version('-release'), ...
    'single_comp_thread',maxNumCompThreads == 1, ...
    'status',char(status), ...
    'scope','DIRECTIONAL_CROSS_CENTER_RUNTIME_SENTINEL');
writetable(raw, fullfile(runtime_dir, 'runtime_raw.csv'));
writetable(summary, fullfile(runtime_dir, 'runtime_summary.csv'));
save(fullfile(runtime_dir, 'runtime_output.mat'), 'output', '-v7');
end

function trials = build_trials_local(fixture, schedule)
trials = cell(height(fixture.semantic_case_registry), 1);
case_indices = unique(schedule.case_index, 'stable');
for index = 1:numel(case_indices)
    case_index = case_indices(index);
    row = fixture.semantic_case_registry(case_index, :);
    trials{case_index} = stage8_k2_mc_generate_paired_trial( ...
        fixture, row, char(row.draw_mode));
end
end

function warmup_local(fixture, trials, schedule_hash, runtime_dir)
path_now = fullfile(runtime_dir, 'formal_warmup.mat');
if isfile(path_now)
    loaded = load(path_now, 'warmup');
    if isfield(loaded, 'warmup') && ...
            strcmp(loaded.warmup.schedule_hash, schedule_hash) && ...
            strcmp(loaded.warmup.fixture_hash, fixture.fixture_hash)
        return;
    end
end
case_indices = unique(fixture.semantic_case_registry.case_index( ...
    ismember(fixture.semantic_case_registry.center_offset, [1,-8,96]) & ...
    fixture.semantic_case_registry.profile_id == "P1"), 'stable');
hashes = strings(numel(case_indices), 2);
for index = 1:numel(case_indices)
    case_index = case_indices(index);
    row = fixture.semantic_case_registry(case_index, :);
    trial = trials{case_index};
    if isempty(trial)
        trial = stage8_k2_mc_generate_paired_trial( ...
            fixture,row,char(row.draw_mode));
    end
    noise_index = find(fixture.noise_profile_ids == ...
        string(row.noise_profile_id), 1);
    [~,baseline_projection] = timed_fit_local( ...
        trial,fixture.spec.context,[],[],'LEGACY_FULL');
    [~,cache_projection] = timed_fit_local( ...
        trial,fixture.spec.context,fixture.providers(noise_index), ...
        fixture.adapters(row.center_index,noise_index), ...
        'REGISTERED_CACHE');
    metrics = compare_projections_local( ...
        baseline_projection, cache_projection);
    if ~metrics.pass
        error('stage8_k2_mc_run_runtime_sentinel:Warmup', ...
            'Warmup semantic projection differs at case %d.', case_index);
    end
    hashes(index,1) = string(baseline_projection.exact_hash);
    hashes(index,2) = string(cache_projection.exact_hash);
end
if ~all(hashes(:,1) == hashes(:,2))
    error('stage8_k2_mc_run_runtime_sentinel:Warmup', ...
        'Warmup semantic projections differ.');
end
warmup = struct('schedule_hash',schedule_hash, ...
    'fixture_hash',fixture.fixture_hash,'result_hashes',hashes, ...
    'status','FORMAL_WARMUP_COMPLETE');
save(path_now, 'warmup', '-v7');
end

function [runtime_sec, projection] = timed_fit_local( ...
    trial, context, provider, adapter, mode)
run_context = context;
run_context.plan.local_domain = trial.local_domain;
run_context.stage5_locked = trial.stage5_locked;
run_context.fixed_manifold_mode = mode;
run_context.fixed_registered_manifold_provider = provider;
run_context.fixed_registered_center_adapter = adapter;
if isfield(run_context, 't4_manifold_provider')
    run_context = rmfield(run_context, 't4_manifold_provider');
end
if isfield(run_context, 'manifold_provider')
    run_context = rmfield(run_context, 'manifold_provider');
end
clock = tic;
[result, diagnostics] = stage8_k2_tp_fit_safe( ...
    trial.Y_element, trial.model, run_context);
runtime_sec = toc(clock);
projection = stage8_k2_tecs_root_projection( ...
    result, diagnostics, 'CACHE_OFF_BASELINE');
projection = semantic_projection_local(projection.result, ...
    projection.diagnostics);
end

function projection = semantic_projection_local(result, diagnostics)
projection = struct();
projection.exact = struct( ...
    'K',double(result.K),'mode',char(result.mode), ...
    'fit_valid',logical(result.fit_valid), ...
    'fit_status',char(result.fit_status), ...
    'selected_source',char(result.selected_source), ...
    'selected_start_id',char(result.selected_start_id), ...
    'effective_rank',double(result.effective_rank), ...
    'score_call_count',double(result.score_call_count), ...
    'svd_call_count',double(result.svd_call_count), ...
    'single_cpi_flag',logical(result.single_cpi_flag), ...
    'same_range_doppler_cell_flag', ...
        logical(result.same_range_doppler_cell_flag), ...
    'cross_cpi_data_used_flag',logical(result.cross_cpi_data_used_flag), ...
    'tracking_input_used_flag',logical(result.tracking_input_used_flag), ...
    'K_estimated_inside_module_flag', ...
        logical(result.K_estimated_inside_module_flag), ...
    'truth_used_in_fit_flag',logical(result.truth_used_in_fit_flag), ...
    'K1_fit_valid',logical(diagnostics.K1_fit_valid), ...
    'fixed_grid_fit_valid',logical(diagnostics.fixed_grid_fit_valid), ...
    'metric_rank',double(diagnostics.metric_rank), ...
    'direction_status',char(diagnostics.direction_status), ...
    'profile_status',char(diagnostics.profile_status), ...
    'raw_tangent_candidate_valid', ...
        logical(diagnostics.raw_tangent_candidate_valid), ...
    'upgrade_flag',logical(diagnostics.upgrade_flag), ...
    'fallback_flag',logical(diagnostics.fallback_flag), ...
    'fallback_reason',char(diagnostics.fallback_reason), ...
    'endpoint_in_domain_flag',logical(diagnostics.endpoint_in_domain_flag), ...
    'evaluated_valid',logical(diagnostics.evaluated_valid), ...
    'evaluated_status',string(diagnostics.evaluated_status), ...
    'selection_truth_used_flag', ...
        logical(diagnostics.selection_truth_used_flag));
projection.numeric = struct( ...
    'angles_hat_deg',result.angles_hat_deg, ...
    'rss',result.rss,'loglik',result.loglik_concentrated, ...
    'K1_center_deg',diagnostics.K1_center_deg, ...
    'fixed_grid_loglik',diagnostics.fixed_grid_loglik, ...
    'metric_condition',diagnostics.metric_condition, ...
    'metric_eigenvalues',diagnostics.metric_eigenvalues, ...
    'metric_rank_threshold',diagnostics.metric_rank_threshold, ...
    'direction_hat',diagnostics.direction_hat, ...
    'rho_hat_deg',diagnostics.rho_hat_deg, ...
    'rho_max_deg',diagnostics.rho_max_deg, ...
    'raw_tangent_loglik',diagnostics.raw_tangent_loglik, ...
    'raw_tangent_angles_deg',diagnostics.raw_tangent_angles_deg, ...
    'evaluated_rho_deg',diagnostics.evaluated_rho_deg, ...
    'evaluated_loglik',diagnostics.evaluated_loglik);
projection.exact_hash = stage8_k2_tecs_sha256( ...
    'STAGE8_K2_MC_DECISION_PROJECTION_V1', projection.exact);
end

function metrics = compare_projections_local(left, right)
a = left.numeric; b = right.numeric;
metrics = struct();
metrics.exact_match = isequaln(left.exact, right.exact) && ...
    strcmp(left.exact_hash, right.exact_hash);
metrics.angle_error = numeric_error_local( ...
    a.angles_hat_deg,b.angles_hat_deg);
metrics.rss_error = scaled_error_local(a.rss,b.rss);
metrics.loglik_error = scaled_error_local(a.loglik,b.loglik);
metrics.K1_angle_error = numeric_error_local( ...
    a.K1_center_deg,b.K1_center_deg);
metrics.fixed_grid_loglik_error = scaled_error_local( ...
    a.fixed_grid_loglik,b.fixed_grid_loglik);
metrics.direction_error = numeric_error_local( ...
    a.direction_hat,b.direction_hat);
metrics.rho_error = max(numeric_error_local( ...
    a.rho_hat_deg,b.rho_hat_deg),numeric_error_local( ...
    a.rho_max_deg,b.rho_max_deg));
metrics.raw_angle_error = numeric_error_local( ...
    a.raw_tangent_angles_deg,b.raw_tangent_angles_deg);
metrics.raw_loglik_error = scaled_error_local( ...
    a.raw_tangent_loglik,b.raw_tangent_loglik);
metrics.metric_error = max([scaled_error_local( ...
    a.metric_condition,b.metric_condition),scaled_error_local( ...
    a.metric_eigenvalues,b.metric_eigenvalues),scaled_error_local( ...
    a.metric_rank_threshold,b.metric_rank_threshold)]);
metrics.evaluated_rho_error = numeric_error_local( ...
    a.evaluated_rho_deg,b.evaluated_rho_deg);
metrics.evaluated_loglik_error = scaled_error_local( ...
    a.evaluated_loglik,b.evaluated_loglik);
metrics.pass = metrics.exact_match && metrics.angle_error <= 2e-4 && ...
    metrics.rss_error <= 1e-8 && metrics.loglik_error <= 1e-8 && ...
    metrics.K1_angle_error <= 2e-4 && ...
    metrics.fixed_grid_loglik_error <= 1e-8 && ...
    metrics.direction_error <= 2e-4 && metrics.rho_error <= 2e-4 && ...
    metrics.raw_angle_error <= 2e-4 && ...
    metrics.raw_loglik_error <= 1e-8 && metrics.metric_error <= 1e-8 && ...
    metrics.evaluated_rho_error <= 2e-4 && ...
    metrics.evaluated_loglik_error <= 1e-8;
end

function value = numeric_error_local(a,b)
if ~isequal(size(a),size(b)), value=Inf; return; end
if isempty(a), value=0; return; end
if any(~isfinite(a(:))) || any(~isfinite(b(:)))
    if isequaln(a,b), value=0; else, value=Inf; end
    return;
end
value=max(abs(a(:)-b(:)));
end

function value = scaled_error_local(a,b)
if ~isequal(size(a),size(b)), value=Inf; return; end
if isempty(a), value=0; return; end
if any(~isfinite(a(:))) || any(~isfinite(b(:)))
    if isequaln(a,b), value=0; else, value=Inf; end
    return;
end
value=max(abs(a(:)-b(:))./max(1,max(abs(a(:)),abs(b(:)))));
end

function summary = summarize_local(raw)
rows = cell(1 + numel(unique(raw.center_offset)) + ...
    numel(unique(raw.noise_profile_id)), 1);
row_index = 0;
centers = unique(raw.center_offset, 'stable');
for index = 1:numel(centers)
    row_index = row_index + 1;
    subset = raw(raw.center_offset == centers(index), :);
    rows{row_index} = summary_row_local( ...
        "CENTER", string(sprintf('%+d', centers(index))), subset);
end
noise_ids = unique(raw.noise_profile_id, 'stable');
for index = 1:numel(noise_ids)
    row_index = row_index + 1;
    subset = raw(raw.noise_profile_id == noise_ids(index), :);
    rows{row_index} = summary_row_local( ...
        "NOISE", noise_ids(index), subset);
end
row_index = row_index + 1;
rows{row_index} = summary_row_local("OVERALL", "ALL_12_CASES", raw);
summary = struct2table(vertcat(rows{:}));
end

function row = summary_row_local(row_type, row_id, subset)
case_ids = unique(subset.case_index, 'stable');
case_differences = zeros(numel(case_ids), 1);
case_baselines = zeros(numel(case_ids), 1);
case_caches = zeros(numel(case_ids), 1);
for index = 1:numel(case_ids)
    case_rows = subset(subset.case_index == case_ids(index), :);
    case_differences(index) = median(case_rows.paired_difference_sec);
    case_baselines(index) = median(case_rows.baseline_runtime_sec);
    case_caches(index) = median(case_rows.cache_runtime_sec);
end
baseline = sum(case_baselines);
cache = sum(case_caches);
point = sum(case_differences);
row = struct('row_type',string(row_type),'row_id',string(row_id), ...
    'case_count',numel(case_ids),'pair_count',height(subset), ...
    'baseline_runtime_sec',baseline,'cache_runtime_sec',cache, ...
    'paired_point_saving_sec',point, ...
    'ab_point_saving_sec',sum_case_medians_local( ...
        subset(subset.pair_order == "AB", :)), ...
    'ba_point_saving_sec',sum_case_medians_local( ...
        subset(subset.pair_order == "BA", :)), ...
    'runtime_reduction_pct',100*point/max(baseline,realmin), ...
    'speedup_ratio',baseline/max(cache,realmin));
end

function value = sum_case_medians_local(subset)
case_ids = unique(subset.case_index, 'stable');
medians = zeros(numel(case_ids), 1);
for index = 1:numel(case_ids)
    medians(index) = median(subset.paired_difference_sec( ...
        subset.case_index == case_ids(index)));
end
value = sum(medians);
end

function atomic_save_local(path_now, payload)
temporary = [path_now, '.tmp'];
if isfile(temporary), delete(temporary); end
save(temporary, 'payload', '-v7');
[moved, message] = movefile(temporary, path_now, 'f');
if ~moved
    error('stage8_k2_mc_run_runtime_sentinel:Checkpoint', '%s', message);
end
end
