function [provider, info] = stage8_k2_mc_build_shared_provider(reference_bundle, options)
%STAGE8_K2_MC_BUILD_SHARED_PROVIDER Build one relative-key shared table.

if nargin < 2 || isempty(options), options = struct(); end
if ~isfield(options, 'timed_diagnostics_enabled')
    options.timed_diagnostics_enabled = false;
end
clock = tic;
[parent, parent_info] = stage8_k2_tfbc_build_provider( ...
    reference_bundle.model, reference_bundle.local_domain, struct( ...
    'timed_diagnostics_enabled', ...
    logical(options.timed_diagnostics_enabled)));
relative_grid = round(reference_bundle.local_domain.az_grid_deg - ...
    reference_bundle.center.physical_center_unwrapped_az_deg, 12);
provider = struct( ...
    'schema_version','STAGE8_K2_MULTICENTER_SHARED_PROVIDER_V1', ...
    'mode','REGISTERED_CACHE', ...
    'measurement_config_id',reference_bundle.model.measurement_config_id, ...
    'noise_profile_id',reference_bundle.model.noise_profile_id, ...
    'rotation_class_hash', ...
        reference_bundle.identity.rotation_class_hash, ...
    'relative_delta_grid_deg',relative_grid, ...
    'el_grid_deg',parent.el_grid_deg, ...
    'delta_origin_deg',relative_grid(1), ...
    'el_origin_deg',parent.el_origin_deg, ...
    'delta_step_deg',parent.az_step_deg, ...
    'el_step_deg',parent.el_step_deg, ...
    'key_tolerance_deg',parent.key_tolerance_deg, ...
    'index_lut',parent.index_lut, ...
    'G_single_or_certified',parent.G_single_or_certified, ...
    'G_single_exact_shape',parent.G_single_exact_shape, ...
    'G_pair_first_exact_shape',parent.G_pair_first_exact_shape, ...
    'G_pair_second_exact_shape',parent.G_pair_second_exact_shape, ...
    'numeric_class',parent.numeric_class, ...
    'numeric_representative',parent.numeric_representative, ...
    'source_numeric_representative', ...
        parent.source_numeric_representative, ...
    'reference_artifact_hash',parent.artifact_hash, ...
    'artifact_hash',parent.artifact_hash, ...
    'reference_provider_hash',parent.provider_hash, ...
    'reference_fixed_measurement_hash', ...
        reference_bundle.model.fixed_measurement_hash, ...
    'reference_actual_center_hash', ...
        reference_bundle.identity.actual_center_hash, ...
    'reference_domain_hash',reference_bundle.local_domain.domain_hash, ...
    'validate_once_status','VALIDATE_ONCE_COMPLETE', ...
    'formal_contract_miss_stop',true, ...
    'timed_diagnostics_enabled', ...
        logical(options.timed_diagnostics_enabled), ...
    'phase_factor',1, 'immutable',true);
provider.provider_hash = stage8_k2_tecs_sha256( ...
    'STAGE8_K2_MULTICENTER_SHARED_PROVIDER_V1', provider);
info = struct( ...
    'status','ONE_ROTATION_CLASS_SHARED_PROVIDER_READY', ...
    'provider_hash',provider.provider_hash, ...
    'rotation_class_hash',provider.rotation_class_hash, ...
    'reference_artifact_hash',provider.reference_artifact_hash, ...
    'key_count',size(provider.G_single_exact_shape, 2), ...
    'build_runtime_sec',toc(clock), 'parent_info',parent_info);
end
