function [adapter, info] = stage8_k2_mc_build_center_adapter( ...
    bundle, provider)
%STAGE8_K2_MC_BUILD_CENTER_ADAPTER Certify one lightweight center map.

clock = tic;
if ~strcmp(bundle.identity.rotation_class_hash, ...
        provider.rotation_class_hash)
    error('stage8_k2_mc_build_center_adapter:RotationClass', ...
        'BLOCKED_ROTATION_CLASS_IDENTITY_FAILED.');
end
domain = bundle.local_domain;
delta = stage8_k2_mc_periodic_difference( ...
    domain.az_grid_deg, bundle.center.physical_center_az_deg);
if max(abs(delta - provider.relative_delta_grid_deg)) > ...
        provider.key_tolerance_deg
    error('stage8_k2_mc_build_center_adapter:DomainMap', ...
        'The absolute domain does not map exactly to the shared keys.');
end
max_G_error = 0;
key_angles = sortrows(domain.candidate_points_deg, [1,2]);
for index = 1:size(key_angles, 1)
    [direct_single, ~] = stage8_k2_tcc_build_g_direct( ...
        key_angles(index, :), bundle.model, struct());
    relative = stage8_k2_mc_periodic_difference( ...
        key_angles(index, 1), bundle.center.physical_center_az_deg);
    az_index = 1 + round((relative - provider.delta_origin_deg) / ...
        provider.delta_step_deg);
    el_index = 1 + round((key_angles(index, 2) - ...
        provider.el_origin_deg) / provider.el_step_deg);
    column = double(provider.index_lut(az_index, el_index));
    error_now = relative_error_local(direct_single, ...
        provider.G_single_exact_shape(:, column));
    max_G_error = max(max_G_error, error_now);
end
if max_G_error > 1e-10
    error('stage8_k2_mc_build_center_adapter:GCertification', ...
        'BLOCKED_SHARED_G_EQUIVALENCE_FAILED (%.17g).', max_G_error);
end
adapter = struct( ...
    'schema_version','STAGE8_K2_MULTICENTER_CENTER_ADAPTER_V1', ...
    'actual_center_hash',bundle.identity.actual_center_hash, ...
    'model_fixed_measurement_hash',bundle.model.fixed_measurement_hash, ...
    'rotation_class_hash',bundle.identity.rotation_class_hash, ...
    'shared_provider_hash',provider.provider_hash, ...
    'physical_center_az_deg',bundle.center.physical_center_az_deg, ...
    'physical_center_unwrapped_az_deg', ...
        bundle.center.physical_center_unwrapped_az_deg, ...
    'center_column',bundle.center.center_column, ...
    'requested_center_az_deg',bundle.center.requested_center_az_deg, ...
    'rotation_delta_deg',bundle.center.rotation_delta_deg, ...
    'absolute_domain_hash',domain.domain_hash, ...
    'absolute_beam_layout_hash', ...
        bundle.identity.absolute_beam_layout_hash, ...
    'absolute_active_geometry_hash', ...
        bundle.identity.absolute_active_geometry_hash, ...
    'adapter_certification_status', ...
        'CENTER_ADAPTER_INDEPENDENTLY_CERTIFIED', ...
    'certification_max_G_relative_error',max_G_error, ...
    'phase_factor',1, 'immutable',true);
adapter.adapter_hash = stage8_k2_tecs_sha256( ...
    'STAGE8_K2_MULTICENTER_CENTER_ADAPTER_V1', adapter);
if any(startsWith(fieldnames(adapter), 'G_'))
    error('stage8_k2_mc_build_center_adapter:TableLeakage', ...
        'A center adapter must not contain shared G tables.');
end
info = struct('status',adapter.adapter_certification_status, ...
    'adapter_hash',adapter.adapter_hash, ...
    'max_G_relative_error',max_G_error, ...
    'build_runtime_sec',toc(clock), 'pass',true);
end

function value = relative_error_local(actual, reference)
value = norm(actual - reference, 'fro') / ...
    max(norm(reference, 'fro'), realmin);
end
