function [schedule, schedule_hash] = stage8_k2_mc_build_runtime_schedule(fixture)
%STAGE8_K2_MC_BUILD_RUNTIME_SCHEDULE Freeze the 48-pair sentinel schedule.

registry = fixture.semantic_case_registry;
mask = ismember(registry.center_offset, [1,-8,96]) & ...
    ismember(registry.profile_id, ["P1","P4"]);
cases = registry(mask, :);
if height(cases) ~= 12
    error('stage8_k2_mc_build_runtime_schedule:Registry', ...
        'The runtime sentinel requires exactly 12 frozen cases.');
end
rows = repmat(struct('global_pair_index',0,'case_index',0, ...
    'trial_id',"",'center_index',0,'center_offset',0, ...
    'noise_profile_id',"",'profile_id',"",'repeat_index',0, ...
    'pair_order',"",'baseline_mode',"LEGACY_FULL", ...
    'treatment_mode',"REGISTERED_CACHE"), 48, 1);
row_index = 0;
for case_slot = 1:height(cases)
    for repeat_index = 1:4
        row_index = row_index + 1;
        pair_order = "AB";
        if repeat_index > 2, pair_order = "BA"; end
        rows(row_index) = struct( ...
            'global_pair_index',row_index, ...
            'case_index',double(cases.case_index(case_slot)), ...
            'trial_id',string(cases.trial_id(case_slot)), ...
            'center_index',double(cases.center_index(case_slot)), ...
            'center_offset',double(cases.center_offset(case_slot)), ...
            'noise_profile_id',string(cases.noise_profile_id(case_slot)), ...
            'profile_id',string(cases.profile_id(case_slot)), ...
            'repeat_index',repeat_index,'pair_order',pair_order, ...
            'baseline_mode',"LEGACY_FULL", ...
            'treatment_mode',"REGISTERED_CACHE");
    end
end
schedule = struct2table(rows);
schedule_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_RUNTIME_SCHEDULE_V1', schedule);
end
