function fixture = stage8_k2_mc_build_context(repo_dir, runtime_root, options)
%STAGE8_K2_MC_BUILD_CONTEXT Build the reusable multicenter fixture.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_mc_build_context:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
if nargin < 2, runtime_root = ''; end
if nargin < 3 || isempty(options), options = struct(); end
if ~isfield(options, 'include_trials'), options.include_trials = true; end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
if ~isempty(runtime_root)
    runtime_root = char(java.io.File(char(string(runtime_root))).getCanonicalPath());
    if ~isfolder(runtime_root), mkdir(runtime_root); end
end
spec = stage8_k2_mc_reference_spec(repo_dir);
centers = stage8_k2_mc_select_centers(spec);
noise_ids = spec.noise_profile_ids;
bundles = repmat(bundle_template_local(), numel(centers), numel(noise_ids));
provider_cells = cell(numel(noise_ids), 1);
adapter_cells = cell(numel(centers), numel(noise_ids));
for noise_index = 1:numel(noise_ids)
    for center_index = 1:numel(centers)
        bundles(center_index, noise_index) = ...
            stage8_k2_mc_build_measurement_model( ...
            spec, centers(center_index), noise_ids(noise_index));
    end
    [provider_cells{noise_index}, ~] = stage8_k2_mc_build_shared_provider( ...
        bundles(1, noise_index), struct());
    expected = provider_cells{noise_index}.rotation_class_hash;
    for center_index = 1:numel(centers)
        stage8_k2_mc_validate_rotation_class( ...
            spec, bundles(center_index, noise_index), expected);
        [adapter_cells{center_index, noise_index}, ~] = ...
            stage8_k2_mc_build_center_adapter( ...
            bundles(center_index, noise_index), provider_cells{noise_index});
    end
end
providers = vertcat(provider_cells{:});
adapters = reshape([adapter_cells{:}], numel(centers), numel(noise_ids));
fixture = struct( ...
    'schema_version','STAGE8_K2_MC_FIXTURE_V1', 'repo_dir',repo_dir, ...
    'runtime_root',runtime_root, 'spec',spec, 'centers',centers, ...
    'noise_profile_ids',noise_ids, 'bundles',bundles, ...
    'providers',providers, 'adapters',adapters, ...
    'provider_count',numel(providers), ...
    'center_count',numel(centers), 'model_count',numel(bundles));
fixture.fixture_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_FIXTURE_V1', spec.reference_spec_hash, ...
    string({centers.center_id}), string({providers.provider_hash}), ...
    string(reshape(cellfun(@(identity) identity.actual_center_hash, ...
    {bundles.identity}, 'UniformOutput', false), [], 1)));
if logical(options.include_trials)
    fixture.semantic_case_registry = stage8_k2_mc_semantic_registry_local( ...
        fixture);
else
    fixture.semantic_case_registry = table();
end
end

function rows = stage8_k2_mc_semantic_registry_local(fixture)
offsets = [1,-8,96];
profiles = fixture.spec.context.constants.profiles;
rows = repmat(struct('case_index',0,'center_offset',0, ...
    'center_index',0,'noise_profile_id',"",'profile_id',"", ...
    'L',8,'snr_db',6,'source_seed',0,'noise_seed',0, ...
    'draw_mode',"PAIRED_LOCAL_DRAW",'trial_id',""), ...
    numel(offsets) * numel(fixture.noise_profile_ids) * numel(profiles), 1);
index = 0;
for offset = offsets
    center_index = find([fixture.centers.column_offset] == offset, 1);
    for noise_index = 1:numel(fixture.noise_profile_ids)
        for profile_index = 1:numel(profiles)
            index = index + 1;
            profile = profiles(profile_index);
            draw_mode = "PAIRED_LOCAL_DRAW";
            if ismember(index, [4,12,20])
                draw_mode = "INDEPENDENT_CENTER_DRAW";
            end
            rows(index) = struct('case_index',index, ...
                'center_offset',offset, 'center_index',center_index, ...
                'noise_profile_id',string(fixture.noise_profile_ids(noise_index)), ...
                'profile_id',string(profile.profile_id), 'L',8, ...
                'snr_db',6, 'source_seed', ...
                fixture.spec.context.constants.source_seed_base + index - 1, ...
                'noise_seed', ...
                fixture.spec.context.constants.noise_seed_base + index - 1, ...
                'draw_mode',draw_mode, ...
                'trial_id',string(sprintf('MC24_C%+04d_N%d_%s', ...
                offset, noise_index, profile.profile_id)));
        end
    end
end
rows = struct2table(rows);
end

function value = bundle_template_local()
value = struct('schema_version','','center',struct(), 'noise_profile_id','', ...
    'cfg',struct(),'pool',struct(),'subset_family',table(), ...
    'noise',struct(),'model',struct(),'raw_rebuilt_model',struct(), ...
    'stage5_locked',struct(),'local_domain',struct(),'identity',struct(), ...
    'debug',struct(),'bundle_hash','');
end

function value = provider_template_local()
value = struct('schema_version','','provider_hash','', ...
    'rotation_class_hash','');
end

function value = adapter_template_local()
value = struct('schema_version','','adapter_hash','', ...
    'actual_center_hash','');
end
