function domain = stage8_k2_mc_build_local_domain(spec, center, stage5_locked)
%STAGE8_K2_MC_BUILD_LOCAL_DOMAIN Build one unwrapped co-rotated chart.

[domain, ~] = build_common_registered_local_domain( ...
    stage5_locked.conventional_center_deg, struct( ...
    'azimuth_offsets_deg',stage5_locked.azimuth_offsets_deg, ...
    'elevation_offsets_deg',stage5_locked.elevation_offsets_deg, ...
    'domain_id','STAGE8_STAGE5_REGISTERED_LOCAL_DOMAIN', ...
    'domain_source','STAGE5_LOCKED_CONVENTIONAL_CENTER', ...
    'configuration_hash',stage5_locked.configuration_hash, ...
    'phase_factor',1));
expected_az = spec.reference_domain.az_grid_deg + ...
    center.rotation_delta_deg;
if max(abs(domain.az_grid_deg - expected_az)) > 1e-12 || ...
        ~isequal(domain.el_grid_deg, spec.reference_domain.el_grid_deg)
    error('stage8_k2_mc_build_local_domain:Rotation', ...
        'The registered domain did not co-rotate with the center.');
end
if any(diff(domain.az_grid_deg) <= 0)
    error('stage8_k2_mc_build_local_domain:UnwrappedChart', ...
        'The global azimuth chart must remain continuous and monotone.');
end
domain.physical_center_az_deg = center.physical_center_az_deg;
domain.physical_center_unwrapped_az_deg = ...
    center.physical_center_unwrapped_az_deg;
domain.requested_center_az_deg = center.requested_center_az_deg;
domain.center_column = center.center_column;
domain.rotation_delta_deg = center.rotation_delta_deg;
domain.relative_delta_grid_deg = domain.az_grid_deg - ...
    center.physical_center_unwrapped_az_deg;
domain.rotation_class_domain_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_RELATIVE_DOMAIN_V1', ...
    round(domain.relative_delta_grid_deg, 12), ...
    round(domain.el_grid_deg, 12), domain.grid_step_az_deg, ...
    domain.grid_step_el_deg, domain.phase_factor);
end
