function rows = stage8_k2_mc_test_method_rows(spec, rmse_values)
%STAGE8_K2_MC_TEST_METHOD_ROWS Build three explicit synthetic outcomes.

if nargin < 2
    rmse_values = [1, 1, 1];
end
methods = ["CORE_LITE"; "CORE_PLUS"; "TANGENT_PROFILE_SAFE"];
rows = table(repmat(string(spec.trial_id), 3, 1), methods, ...
    true(3, 1), repmat("VALID", 3, 1), ones(3, 1), ones(3, 1), ...
    double(rmse_values(:)), zeros(3, 1), zeros(3, 1), ...
    zeros(3, 1), zeros(3, 1), zeros(3, 1), ...
    false(3, 1), false(3, 1), ones(3, 1), ones(3, 1), ...
    zeros(3, 1), false(3, 1), ...
    'VariableNames', {'trial_id','method_id','fit_valid','fit_status', ...
    'RSS','loglik','joint_RMSE_deg','center_error_deg', ...
    'direction_axis_error_deg','rho_error_deg','rho_relative_error', ...
    'separation_vector_error_deg','upgrade_flag','fallback_flag', ...
    'score_call_count','SVD_call_count','runtime_sec', ...
    'truth_used_in_fit_flag'});
end
