function result = test_seed_uniqueness(fixture)
%TEST_SEED_UNIQUENESS Verify 240 seeds and distinct base noise matrices.

registry = fixture.registry;
constants = fixture.context.constants;
assert(numel(unique(registry.source_seed)) == 240 && ...
    numel(unique(registry.noise_seed)) == 240, ...
    'test_seed_uniqueness:SeedCount', ...
    'Source or noise seeds are not unique across 240 base realizations.');
hashes = strings(240, 1);
for base_index = 0:239
    spec = registry(registry.base_realization_index == base_index & ...
        registry.snr_index == 1, :);
    trial = stage8_k2_mc_generate_trial(spec, fixture.context);
    hashes(base_index + 1) = string(stage8_k2_mc_stable_hash( ...
        'BASE_NOISE_FIXTURE', trial.noise_element));
end
assert(numel(unique(hashes)) == constants.base_realization_count, ...
    'test_seed_uniqueness:NoiseIdentity', ...
    'Different base realizations produced duplicate noise matrices.');
result = struct('pass', true, 'unique_source_seeds', 240, ...
    'unique_noise_seeds', 240, 'unique_noise_matrices', 240);
end
