function result = test_four_trial_smoke(fixture)
%TEST_FOUR_TRIAL_SMOKE Run the four registered MC smoke trials.

registry = fixture.registry;
selectors = ["P1","WHITE","6"; "P2","WHITE","14"; ...
    "P3","STAGE5_TOEPLITZ_CORRELATED","14"; ...
    "P4","STAGE5_TOEPLITZ_CORRELATED","22"];
blocks = cell(4, 1);
for index = 1:4
    selected = registry.profile_id == selectors(index, 1) & ...
        registry.noise_profile_id == selectors(index, 2) & ...
        registry.L == 4 & registry.white_beamspace_snr_target_db == ...
        str2double(selectors(index, 3)) & registry.replicate_id == 1;
    spec = registry(selected, :);
    assert(height(spec) == 1, 'test_four_trial_smoke:Selector', ...
        'A registered smoke selector is not unique.');
    [trial, metrics] = stage8_k2_mc_generate_trial(spec, fixture.context);
    blocks{index} = stage8_k2_mc_evaluate_trial( ...
        spec, trial, metrics, fixture.context);
    tangent = blocks{index}( ...
        blocks{index}.method_id == "TANGENT_PROFILE_SAFE", :);
    assert(height(blocks{index}) == 3 && ...
        all(blocks{index}.fit_status ~= "NOT_RUN") && ...
        ~any(blocks{index}.truth_used_in_fit_flag) && ...
        height(tangent) == 1 && tangent.fit_valid && ...
        isfinite(tangent.RSS) && isfinite(tangent.loglik), ...
        'test_four_trial_smoke:Outcome', ...
        'A smoke trial lacks an explicit usable Tangent safe result.');
end
all_rows = vertcat(blocks{:});
result = struct('pass', true, 'trial_count', 4, ...
    'method_row_count', height(all_rows), ...
    'tangent_valid_count', nnz(all_rows.method_id == ...
    "TANGENT_PROFILE_SAFE" & all_rows.fit_valid));
end
