function result = test_trial_hash_uniqueness(fixture)
%TEST_TRIAL_HASH_UNIQUENESS Require 1680 scientific identities.

hashes = fixture.registry.element_trial_hash;
assert(height(fixture.registry) == 1680 && ...
    numel(unique(hashes)) == 1680 && all(strlength(hashes) == 64), ...
    'test_trial_hash_uniqueness:HashCount', ...
    'The registry does not contain 1680 unique SHA-256 trial identities.');
result = struct('pass', true, 'trial_count', 1680, ...
    'unique_hash_count', numel(unique(hashes)));
end
