function result = test_42_formula_equivalence(fixture)
%TEST_42_FORMULA_EQUIVALENCE Compare four trials with the frozen generator.

context = fixture.context;
registry = fixture.registry;
selectors = ["P1","WHITE","1","-6"; ...
    "P2","WHITE","4","6"; ...
    "P3","STAGE5_TOEPLITZ_CORRELATED","4","14"; ...
    "P4","STAGE5_TOEPLITZ_CORRELATED","8","22"];
maximum = 0;
for index = 1:size(selectors, 1)
    selected = registry.profile_id == selectors(index, 1) & ...
        registry.noise_profile_id == selectors(index, 2) & ...
        registry.L == str2double(selectors(index, 3)) & ...
        registry.white_beamspace_snr_target_db == ...
        str2double(selectors(index, 4)) & registry.replicate_id == 1;
    spec = registry(selected, :);
    assert(height(spec) == 1, ...
        'test_42_formula_equivalence:Selector', ...
        'A representative selector is not unique.');
    frozen = stage8_k2_snr_generate_white_control_trial( ...
        spec, context.snr_context);
    frozen_metrics = stage8_k2_snr_compute_metrics(frozen);
    [current, current_metrics] = stage8_k2_mc_generate_trial(spec, context);
    differences = [ ...
        norm(frozen.source_unscaled - current.source_unscaled, 'fro'), ...
        abs(frozen.source_phase_rad - current.source_phase_rad), ...
        abs(frozen.source_scale - current.source_scale), ...
        norm(frozen.noise_element - current.noise_element, 'fro'), ...
        norm(frozen.Y_element - current.Y_element, 'fro'), ...
        abs(frozen_metrics.element_snr_expected_db - ...
        current_metrics.element_snr_expected_db), ...
        abs(frozen_metrics.raw_beam_snr_expected_db - ...
        current_metrics.raw_beam_snr_expected_db), ...
        abs(frozen_metrics.white_beam_snr_expected_db - ...
        current_metrics.white_beam_snr_expected_db), ...
        abs(frozen_metrics.k2_projected_snr_expected_db - ...
        current_metrics.k2_projected_snr_expected_db)];
    maximum = max(maximum, max(differences));
end
assert(maximum == 0, 'test_42_formula_equivalence:Mismatch', ...
    'The MC trial construction differs from the frozen 42 construction.');
result = struct('pass', true, 'case_count', 4, ...
    'maximum_absolute_or_frobenius_difference', maximum);
end
