function result = test_common_random_numbers(fixture)
%TEST_COMMON_RANDOM_NUMBERS Verify one complete seven-SNR paired sequence.

registry = fixture.registry;
base_index = 57;
specs = sortrows(registry( ...
    registry.base_realization_index == base_index, :), 'snr_index');
assert(height(specs) == 7, 'test_common_random_numbers:Count', ...
    'The selected base realization lacks seven SNR points.');
trials = cell(7, 1);
for index = 1:7
    trials{index} = stage8_k2_mc_generate_trial( ...
        specs(index, :), fixture.context);
end
reference = trials{1};
max_source = 0;
max_noise = 0;
max_phase = 0;
scales = zeros(7, 1);
for index = 1:7
    max_source = max(max_source, norm( ...
        trials{index}.source_unscaled - reference.source_unscaled, 'fro'));
    max_noise = max(max_noise, norm( ...
        trials{index}.noise_element - reference.noise_element, 'fro'));
    max_phase = max(max_phase, abs( ...
        trials{index}.source_phase_rad - reference.source_phase_rad));
    scales(index) = trials{index}.source_scale;
end
assert(max([max_source,max_noise,max_phase]) == 0 && ...
        numel(unique(specs.source_seed)) == 1 && ...
        numel(unique(specs.noise_seed)) == 1 && ...
        numel(unique(scales)) == 7 && all(diff(scales) > 0), ...
    'test_common_random_numbers:Pairing', ...
    'A seven-SNR sequence changed more than its common signal scale.');
result = struct('pass', true, 'snr_count', 7, ...
    'max_source_difference', max_source, ...
    'max_noise_difference', max_noise, ...
    'max_phase_difference', max_phase);
end
