function result = test_summary_fixture(fixture)
%TEST_SUMMARY_FIXTURE Verify registered statistics and transition gates.

constants = fixture.context.constants;
trial_ids = ["S1";"S2";"S3";"S4"];
method_ids = repmat(constants.method_ids, 4, 1);
trial_column = repelem(trial_ids, 3);
rmse = repmat([3;2;1], 4, 1);
rows = table(trial_column, method_ids, repmat(6, 12, 1), ...
    true(12, 1), rmse, rmse, rmse, rmse, rmse, rmse, ...
    false(12, 1), false(12, 1), ones(12, 1), ones(12, 1), ...
    ones(12, 1), ...
    'VariableNames', {'trial_id','method_id', ...
    'white_beamspace_snr_target_db','fit_valid','joint_RMSE_deg', ...
    'center_error_deg','direction_axis_error_deg','rho_error_deg', ...
    'rho_relative_error','separation_vector_error_deg','upgrade_flag', ...
    'fallback_flag','score_call_count','SVD_call_count','runtime_sec'});
summary = stage8_k2_mc_build_scope_summary( ...
    rows, "SNR", "6", constants, true);
tangent = summary(summary.row_type == "METHOD" & ...
    summary.method_id == "TANGENT_PROFILE_SAFE", :);
pair_lite = summary(summary.row_type == "PAIRWISE" & ...
    summary.reference_method_id == "CORE_LITE", :);
pair_plus = summary(summary.row_type == "PAIRWISE" & ...
    summary.reference_method_id == "CORE_PLUS", :);
classification = stage8_k2_mc_classify_scope(summary, constants);
assert(tangent.median_joint_RMSE_deg == 1 && ...
    tangent.p90_joint_RMSE_deg == 1 && tangent.fallback_rate == 0 && ...
    pair_lite.wins == 4 && pair_lite.ties == 0 && ...
    pair_lite.losses == 0 && pair_plus.wins == 4 && ...
    classification == "STABLE_RELATIVE_GAIN", ...
    'test_summary_fixture:Statistics', ...
    'Median, P90, pairing, fallback, or stable classification failed.');
modified = summary;
modified.fallback_rate(modified.row_type == "METHOD" & ...
    modified.method_id == "TANGENT_PROFILE_SAFE") = 0.5;
assert(stage8_k2_mc_classify_scope(modified, constants) == ...
    "FALLBACK_DOMINATED", 'test_summary_fixture:Fallback', ...
    'Fallback-dominated classification failed.');
equal_median = summary;
method_mask = equal_median.row_type == "METHOD";
equal_median.median_joint_RMSE_deg(method_mask) = 1;
tangent_mask = method_mask & ...
    equal_median.method_id == "TANGENT_PROFILE_SAFE";
equal_median.p90_joint_RMSE_deg(tangent_mask) = 4;
assert(stage8_k2_mc_classify_scope(equal_median, constants) == ...
    "NO_RELATIVE_GAIN", 'test_summary_fixture:StrictGain', ...
    'A tied median was incorrectly classified as a relative gain.');

figure_root = tempname;
mkdir(figure_root);
cleanup = onCleanup(@() cleanup_local(figure_root));
[plot_summary, plot_profiles, plot_snr] = plot_fixture_local(rows, constants);
figure_paths = stage8_k2_mc_plot( ...
    plot_summary, plot_profiles, plot_snr, figure_root, constants);
figure_names = fieldnames(figure_paths);
assert(numel(figure_names) == 5 && all(cellfun( ...
    @(name) isfile(figure_paths.(name)), figure_names)), ...
    'test_summary_fixture:Figures', ...
    'The registered five-figure R2022b smoke test failed.');
result = struct('pass', true, 'median', 1, 'p90', 1, ...
    'wins_vs_lite', 4, 'wins_vs_plus', 4, ...
    'stable_classification', classification, 'figure_count', 5);
clear cleanup
cleanup_local(figure_root);
end

function [summary, profiles, snr_rows] = plot_fixture_local(rows, constants)
targets = constants.white_snr_targets_db;
summary_blocks = cell(numel(targets), 1);
profile_blocks = cell(numel(targets) * numel(constants.profile_ids), 1);
profile_block_index = 0;
for target_index = 1:numel(targets)
    target = targets(target_index);
    subset = rows;
    subset.white_beamspace_snr_target_db(:) = target;
    subset.trial_id = "T" + string(target_index) + "_" + rows.trial_id;
    summary_blocks{target_index} = stage8_k2_mc_build_scope_summary( ...
        subset, "SNR", string(target), constants, true);
    for profile = reshape(constants.profile_ids, 1, [])
        profile_block_index = profile_block_index + 1;
        profile_blocks{profile_block_index} = ...
            stage8_k2_mc_build_scope_summary(subset, ...
            "SNR_X_PROFILE", string(target) + "|" + profile, ...
            constants, true);
    end
end
summary = vertcat(summary_blocks{:});
profiles = vertcat(profile_blocks{:});
profile_id = repelem(constants.profile_ids, numel(targets));
k2_projected_snr_expected_db = repmat(targets(:), ...
    numel(constants.profile_ids), 1);
snr_rows = table(profile_id, k2_projected_snr_expected_db);
end

function cleanup_local(root)
if isfolder(root)
    rmdir(root, 's');
end
end
