function result = test_truth_isolation(~)
%TEST_TRUTH_ISOLATION Audit the data-only fit adapter and evaluation order.

assert(nargin(@stage8_k2_mc_fit_methods) == 3, ...
    'test_truth_isolation:Signature', ...
    'The fit adapter must accept only data, model, and frozen context.');
source = lower(fileread(which('stage8_k2_mc_fit_methods')));
for forbidden = ["truth","profile_id","target","projected", ...
        "previous","other_method"]
    assert(~contains(source, forbidden), ...
        'test_truth_isolation:Forbidden', ...
        'The fit adapter contains forbidden analysis input: %s', forbidden);
end
evaluation = lower(fileread(which('stage8_k2_mc_evaluate_trial')));
fit_position = strfind(evaluation, 'fits = stage8_k2_mc_fit_methods');
score_position = strfind(evaluation, 'trial.truth_angles_deg');
assert(numel(fit_position) == 1 && numel(score_position) == 1 && ...
    fit_position < score_position, 'test_truth_isolation:Order', ...
    'Evaluation must finish fitting before reading evaluation-only data.');
result = struct('pass', true, 'adapter_nargin', 3, ...
    'fit_precedes_scoring', true);
end
