function result = test_tangent_axis_error_contract()
%TEST_TANGENT_AXIS_ERROR_CONTRACT Verify unoriented-axis invariance.

tolerance_deg = 1e-12;
u = [0.6, -0.8];
same_error = stage8_k2_tp_axis_error_deg(u, u);
opposite_error = stage8_k2_tp_axis_error_deg(-u, u);
orthogonal_error = stage8_k2_tp_axis_error_deg([1, 0], [0, 1]);
assert(abs(same_error) <= tolerance_deg, ...
    'test_tangent_axis_error_contract:Same', ...
    'Identical directions must have zero axis error.');
assert(abs(opposite_error) <= tolerance_deg, ...
    'test_tangent_axis_error_contract:Opposite', ...
    'Opposite directions represent the same axis.');
assert(abs(orthogonal_error - 90) <= tolerance_deg, ...
    'test_tangent_axis_error_contract:Orthogonal', ...
    'Orthogonal axes must have 90-degree error.');

rng_state = rng;
cleanup = onCleanup(@() rng(rng_state));
rng(813207, 'twister');
maximum_invariance_error = 0;
for index = 1:64
    first = randn(1, 2);
    second = randn(1, 2);
    reference = stage8_k2_tp_axis_error_deg(first, second);
    variants = [ ...
        stage8_k2_tp_axis_error_deg(-first, second), ...
        stage8_k2_tp_axis_error_deg(first, -second), ...
        stage8_k2_tp_axis_error_deg(-first, -second)];
    maximum_invariance_error = max(maximum_invariance_error, ...
        max(abs(variants - reference)));
end
assert(maximum_invariance_error <= tolerance_deg, ...
    'test_tangent_axis_error_contract:SignInvariance', ...
    'Random sign variants changed an unoriented-axis error.');
result = struct('pass', true, 'same_error_deg', same_error, ...
    'opposite_error_deg', opposite_error, ...
    'orthogonal_error_deg', orthogonal_error, ...
    'maximum_invariance_error_deg', maximum_invariance_error);
fprintf(['test_tangent_axis_error_contract PASS ', ...
    'max_invariance_error=%.17g deg\n'], maximum_invariance_error);
end
