function result = test_one_trial_full_manifold_smoke()
%TEST_ONE_TRIAL_FULL_MANIFOLD_SMOKE Exercise one complete safe K2 trial.

test_dir = fileparts(mfilename('fullpath'));
repo_dir = fileparts(fileparts(fileparts(test_dir)));
scope = stage8_k2_tp_add_paths(repo_dir); %#ok<NASGU>
context = stage8_k2_tp_build_context(repo_dir);
registry = stage8_k2_tp_build_registry( ...
    context.plan.local_domain, context.constants);
index = find(registry.noise_profile_id == "WHITE" & ...
    registry.L == 4 & registry.snr_db == 6 & ...
    registry.profile_id == "P1", 1);
smoke_spec = registry(index, :);
smoke_spec.trial_id = "TP1_SMOKE_OUTSIDE_FORMAL_REGISTRY";
smoke_spec.source_seed = context.constants.source_seed_base - 1;
smoke_spec.noise_seed = context.constants.noise_seed_base - 1;
[rows, diagnostic] = stage8_k2_tp_evaluate_trial( ...
    smoke_spec, context);
m2 = rows(rows.method_id == "TANGENT_PROFILE_SAFE", :);
assert(height(rows) == 3 && height(m2) == 1 && ...
    numel(unique(rows.element_trial_hash)) == 1, ...
    'test_one_trial_full_manifold_smoke:Pairing', ...
    'The three methods did not share one element trial.');
assert(~any(rows.truth_used_in_fit_flag) && ...
    ~diagnostic.truth_used_in_fit_flag, ...
    'test_one_trial_full_manifold_smoke:TruthLeakage', ...
    'Truth entered a fitting or selection path.');
assert(diagnostic.raw_tangent_candidate_valid && ...
    diagnostic.endpoint_in_domain_flag && ...
    diagnostic.full_manifold_profile_used_flag, ...
    'test_one_trial_full_manifold_smoke:Profile', ...
    'The raw tangent profile did not use a valid in-domain full manifold.');
assert(m2.fit_valid && isfinite(m2.RSS) && isfinite(m2.loglik) && ...
    isfinite(m2.joint_RMSE_deg) && ...
    ismember(m2.selected_source, ...
    ["FIXED_GRID_FALLBACK", "TANGENT_PROFILE_UPGRADE"]), ...
    'test_one_trial_full_manifold_smoke:SafeResult', ...
    'The safe method did not return one finite registered result.');
result = struct('pass', true, 'selected_source', char(m2.selected_source), ...
    'raw_tangent_loglik', diagnostic.raw_tangent_loglik, ...
    'final_loglik', m2.loglik);
fprintf('test_one_trial_full_manifold_smoke PASS selected=%s\n', ...
    char(m2.selected_source));
end
