function bundle = build_stage7_1_writer_fixture(repo_dir)
%BUILD_STAGE7_1_WRITER_FIXTURE Return a deterministic minimal closure bundle.

identity = build_stage7_1_code_identity(repo_dir);
artifact_id = "fixture_comparison";
file_name = "fixture.csv";
primary_key_columns = "id";
column_name = "value";
comparison_type = "EXACT_TEXT";
current_row_count = 1;
historical_row_count = 1;
mismatch_count = 0;
maximum_absolute_difference = 0;
maximum_relative_difference = 0;
absolute_tolerance = 1e-12;
relative_tolerance = 1e-10;
pass_flag = true;
historical_comparison = table(artifact_id, file_name, ...
    primary_key_columns, column_name, comparison_type, current_row_count, ...
    historical_row_count, mismatch_count, maximum_absolute_difference, ...
    maximum_relative_difference, absolute_tolerance, relative_tolerance, ...
    pass_flag);
historical_commit = ...
    "85615e0f5027e7d6dee840dcb71aa1a2c07e85c3";
comparison_status = "PASS_STAGE7_CORE_MATCHES_HISTORICAL_COMMIT";
historical_summary = table(historical_commit, comparison_status, pass_flag);

semantics = struct('processing_order', ...
    'ELEVATION_DBF_THEN_ELEVATION_CONDITIONED_AZIMUTH_DBF', ...
    'Zel_formula', 'Zel=V''*Y', ...
    'conditioned_output_formula', 'z(b,c)=u(c|b)''*Zel(b,:)''', ...
    'equivalent_weight_formula', 'w(b,c)=kron(u(c|b),v(b))', ...
    'B_out_formula', 'B_out=B_el*B_az', ...
    'terminology_status', ...
    '3 elevation intermediate channels, each with 5 azimuth outputs');
method_id = ["FIXED_RECT_3X5";"GREEDY_ETA_080";"FULL_PARENT_5X5"];
subset_id = ["RECT_E14_A31";"RECT_E28_A31";"RECT_E31_A31"];
aliases = table(method_id, subset_id);
minimum_cost = table(subset_id(1:2), [7215;7215], ...
    'VariableNames', {'subset_id','MAC_total'});
same_cost_dominance = table(subset_id(1:2), [false;true], ...
    'VariableNames', {'subset_id','same_cost_dominates_registered_flag'});
pareto = table(method_id, false(3, 1), false(3, 1), ...
    'VariableNames', {'method_id','scheme_A_pass','scheme_B_pass'});
complexity = struct('N_el', 32, 'N_az', 65, 'B_el', 3, 'B_az', 5, ...
    'dimension_source', 'FROZEN_STAGE7_PLAN_EXPLICIT_DIMENSIONS');
memory = struct( ...
    'historical_peak_memory_estimate_bytes', 110347346, ...
    'current_peak_memory_estimate_bytes', 110417088, ...
    'peak_memory_delta_bytes', 69742, ...
    'peak_memory_relative_delta', 69742 / 110347346, ...
    'peak_memory_comparison_status', ...
    'EXPECTED_PROVENANCE_SCHEMA_DEPENDENT_VARIATION', ...
    'peak_memory_diagnostic_reason', ...
    'PROVENANCE_SCHEMA_CHANGED_CONTEXT_WHOS_BYTES', ...
    'workspace_contract_bytes', 34611200, ...
    'deterministic_memory_contract_pass', true, ...
    'overall_memory_audit_pass', true);
paired_group_id = repmat("EDGE_FIXTURE", 3, 1);
trial_index = ones(3, 1);
trial_seed = repmat(20260719, 3, 1);
edge_plan = table(method_id, subset_id, paired_group_id, trial_seed);
trials = table(paired_group_id, trial_index, trial_seed, method_id, ...
    subset_id, true(3, 1), 'VariableNames', {'paired_group_id', ...
    'trial_index','trial_seed','method_id','subset_id','oracle_k_success'});
summary = table(method_id, subset_id, ones(3, 1), ...
    'VariableNames', {'method_id','subset_id','n_trials'});
edge = struct('edge_plan', edge_plan, 'trials', trials, 'summary', summary);
metric = ["stage7_1_closure_status";"stage7_status"];
value = ["PASS_STAGE7_1_CLOSURE_AUDIT";"PASS_SYSTEM_ANALYSIS_ONLY"];
unit = ["status";"status"];
status = ["PASS";"PASS"];
keypoints = table(metric, value, unit, status, true(2, 1), ...
    'VariableNames', {'metric','value','unit','status','pass_flag'});
runtime_diagnostics = table(method_id, [1;2;3] * 1e-6, ...
    'VariableNames', {'method_id','runtime_sec'});

bundle = struct('identity', identity, ...
    'historical_comparison', historical_comparison, ...
    'historical_summary', historical_summary, ...
    'sequential_semantics', semantics, 'aliases', aliases, ...
    'minimum_cost', minimum_cost, ...
    'same_cost_dominance', same_cost_dominance, ...
    'pareto', pareto, 'complexity', complexity, ...
    'memory_contract_audit', memory, 'edge', edge, ...
    'keypoints', keypoints, ...
    'closure_report', "Synthetic deterministic closure writer fixture.", ...
    'runtime_diagnostics', runtime_diagnostics);
end
