function [rows, runtime] = evaluate_stage7_1_synthetic_edge_methods( ...
    trial, plan_group, ~)
%EVALUATE_STAGE7_1_SYNTHETIC_EDGE_METHODS Return three paired fixture rows.

expected = ["FIXED_RECT_3X5";"GREEDY_ETA_080";"FULL_PARENT_5X5"];
ordered = plan_group([],:);
for index = 1:numel(expected)
    ordered = [ordered;plan_group(plan_group.method_id == expected(index), :)]; %#ok<AGROW>
end
out = cell(3, 1);
runtime_out = cell(3, 1);
for index = 1:3
    success = mod(trial.trial_index + index, 2) == 0;
    error_value = 0.01 * (trial.trial_index + index);
    out{index} = struct('paired_group_id', string(trial.paired_group_id), ...
        'paired_group_index', trial.paired_group_index, ...
        'scenario_id', ordered.scenario_id(index), ...
        'element_snr_db', ordered.element_snr_db(index), ...
        'trial_index', trial.trial_index, 'trial_seed', trial.trial_seed, ...
        'method_id', ordered.method_id(index), ...
        'subset_id', ordered.subset_id(index), ...
        'target1_az_deg', trial.target_angles_deg(1, 1), ...
        'target1_el_deg', trial.target_angles_deg(1, 2), ...
        'target2_az_deg', trial.target_angles_deg(2, 1), ...
        'target2_el_deg', trial.target_angles_deg(2, 2), ...
        'realized_element_snr_db', trial.realized_element_snr_db, ...
        'historical_registered_domain_pass', ...
        trial.historical_registered_domain_pass, ...
        'tolerant_registered_domain_pass', ...
        trial.tolerant_registered_domain_pass, ...
        'boundary_numeric_disagreement_flag', ...
        trial.boundary_numeric_disagreement_flag, ...
        'domain_tolerance_deg', trial.domain_tolerance_deg, ...
        'edge_diagnostic_domain_pass', trial.edge_diagnostic_domain_pass, ...
        'oracle_k_success', success, 'azimuth_error_deg', error_value, ...
        'elevation_error_deg', error_value, ...
        'pair_error_deg', sqrt(2) * error_value, ...
        'unconditional_penalized_error', error_value, ...
        'wrong_local_peak', false, 'converged', true, ...
        'normalized_score', 1 - 0.01 * index, ...
        'normalized_score_gap_to_full_parent', 0.01 * (index - 3), ...
        'score_calls', index, 'SVD_calls', index, 'iterations', 1, ...
        'multi_start_count', 1, 'status', "SYNTHETIC_PASS", ...
        'diagnostic_status', ...
        "POST_HOC_EDGE_SENSITIVITY_NOT_USED_FOR_SELECTION", ...
        'selection_effect_status', ...
        "NOT_USED_FOR_STAGE7_SELECTION_OR_OPERATING_POINT", ...
        'method_varying_objects', "W_I;C_I;T_I;G_BANK", ...
        'common_trial_identity_hash', compose('FIXTURE_%d_%d', ...
        trial.paired_group_index, trial.trial_index));
    runtime_out{index} = struct('paired_group_id', ...
        string(trial.paired_group_id), 'trial_index', trial.trial_index, ...
        'method_id', ordered.method_id(index), ...
        'runtime_sec', 1e-6 * index);
end
rows = struct2table(vertcat(out{:}));
runtime = struct2table(vertcat(runtime_out{:}));
end
