function result = test_summary_schema_fixture(fixture)
%TEST_SUMMARY_SCHEMA_FIXTURE Exercise final tables, figures, and manifest.

temporary_repo = tempname;
mkdir(temporary_repo);
mkdir(fullfile(temporary_repo, 'innovation-mining'));
mkdir(fullfile(temporary_repo, 'innovation-mining', 'figures'));
runtime_root = fullfile(temporary_repo, 'runtime');
mkdir(runtime_root);
mkdir(fullfile(runtime_root, 'merged'));
cleanup = onCleanup(@() cleanup_local(temporary_repo));

context = fixture.context;
context.repo_dir = temporary_repo;
registry = fixture.registry;
tangent = sortrows(context.tangent_rows, 'global_trial_index');
baseline = synthetic_rows_local(registry, tangent);
audit = table(double(registry.global_trial_index), registry.trial_id, ...
    registry.element_trial_hash, registry.measurement_hash, ...
    true(height(registry), 1), repmat("fixture", height(registry), 1), ...
    zeros(height(registry), 1), ones(height(registry), 1), ...
    'VariableNames', {'global_trial_index','trial_id', ...
    'element_trial_hash','measurement_hash','checkpoint_valid', ...
    'scientific_hash','white_target_error_db','runtime_sec'});
scan = struct('completed_count', height(registry), ...
    'runtime_sec', ones(height(registry), 1));
merged = struct('registry', registry, 'registry_audit', audit, ...
    'baseline_rows', baseline, 'scan', scan, ...
    'total_active_runtime_sec', height(registry), ...
    'median_trial_runtime_sec', 1);
test_output = struct('pass', true, 'test_count', 10);
runtime_state = struct('registry_hash', fixture.registry_hash, ...
    'run_state', struct('launch_count', 1, 'resume_count', 0));
preflight = struct('head', fixture.context.constants.prompt_commit);
output = stage8_k2_wcb_summarize(merged, context, runtime_root, ...
    test_output, runtime_state, preflight);
manifest_path = fullfile(temporary_repo, 'innovation-mining', ...
    '46_stage8_k2_white_snr_classical_baseline_runtime_manifest.json');
manifest = jsondecode(fileread(manifest_path));
artifacts_exist = true;
for index = 1:numel(manifest.artifacts)
    artifacts_exist = artifacts_exist && isfile(fullfile(temporary_repo, ...
        strrep(manifest.artifacts(index).path, '/', filesep)));
end
assert(strcmp(output.status, ...
    'FINALIZATION_COMPLETE_READY_FOR_INDEPENDENT_AUDIT') && ...
    manifest.baseline_row_count == 5040 && ...
    manifest.music_applicable_count == 1120 && ...
    manifest.element_cml_applicable_count == 160 && ...
    numel(manifest.artifacts) == 15 && artifacts_exist, ...
    'test_summary_schema_fixture:Output', ...
    'Synthetic finalization failed schema, count, or artifact contracts.');
result = struct('pass', true, 'artifact_count', ...
    numel(manifest.artifacts), 'baseline_row_count', ...
    manifest.baseline_row_count);
clear cleanup
end

function rows = synthetic_rows_local(registry, tangent)
count = height(registry);
template = synthetic_template_local();
items = repmat(template, count * 3, 1);
methods = ["FULL4D_BEAMSPACE_CML_MULTISTART"; ...
    "BEAMSPACE_MUSIC_K2"; "FULL4D_ELEMENT_CML_MULTISTART"];
for index = 1:count
    for method_index = 1:3
        at = (index - 1) * 3 + method_index;
        item = template;
        item.trial_id = registry.trial_id(index);
        item.global_trial_index = double(registry.global_trial_index(index));
        item.element_trial_hash = registry.element_trial_hash(index);
        item.measurement_hash = registry.measurement_hash(index);
        item.method_id = methods(method_index);
        item.observation_domain = "BEAMSPACE";
        item.white_beamspace_snr_target_db = ...
            double(registry.white_beamspace_snr_target_db(index));
        item.noise_profile_id = registry.noise_profile_id(index);
        item.L = double(registry.L(index));
        item.profile_id = registry.profile_id(index);
        item.replicate_id = double(registry.replicate_id(index));
        item.base_realization_index = ...
            double(registry.base_realization_index(index));
        base_rmse = double(tangent.joint_RMSE_deg(index));
        if method_index == 1
            item.fit_valid = true;
            item.fit_status = "FULL4D_CML_VALID";
            item.optimizer_status = "FULL4D_CML_STATIONARY";
            item.joint_RMSE_deg = base_rmse * 1.05;
            item.loglik = double(tangent.loglik(index)) + 0.1;
            item.RSS = max(1, double(tangent.RSS(index)) - 0.01);
            item.complete_likelihood_subset_flag = true;
            item.numerical_optimization_status = "NOT_DETECTED";
            item.score_call_count = 1000;
            item.SVD_call_count = 2000;
            item.runtime_sec = 5;
        elseif method_index == 2
            item.optimizer_status = "NOT_APPLICABLE";
            item.eig_call_count = double(registry.music_applicable_flag(index));
            item.sample_rank = min(2, double(registry.L(index)));
            if registry.music_applicable_flag(index)
                item.fit_valid = true;
                item.fit_status = "MUSIC_K2_VALID";
                item.joint_RMSE_deg = base_rmse * 1.3;
                item.local_peak_count = 2;
                item.runtime_sec = 0.2;
            else
                item.applicable = false;
                item.applicability_status = ...
                    "NOT_APPLICABLE_INSUFFICIENT_SAMPLE_SUBSPACE_RANK";
                item.fit_status = item.applicability_status;
            end
        else
            item.observation_domain = "ELEMENT";
            item.more_informative_element_reference_flag = true;
            item.same_hardware_interface_flag = false;
            if registry.element_cml_registered_flag(index)
                item.fit_valid = true;
                item.fit_status = "FULL4D_CML_VALID";
                item.optimizer_status = "FULL4D_CML_CONVERGED";
                item.joint_RMSE_deg = base_rmse * 0.8;
                item.RSS = 1;
                item.loglik = 1;
                item.score_call_count = 1000;
                item.SVD_call_count = 1000;
                item.runtime_sec = 20;
            else
                item.applicable = false;
                item.applicability_status = ...
                    "NOT_IN_REGISTERED_ELEMENT_REFERENCE_SUBSET";
                item.fit_status = item.applicability_status;
                item.optimizer_status = "NOT_APPLICABLE";
            end
        end
        if item.fit_valid
            item.center_error_deg = item.joint_RMSE_deg;
            item.axis_error_deg = item.joint_RMSE_deg;
            item.rho_error_deg = item.joint_RMSE_deg;
            item.rho_relative_error = item.joint_RMSE_deg;
            item.separation_vector_error_deg = item.joint_RMSE_deg;
        end
        items(at) = item;
    end
end
rows = struct2table(items);
end

function row = synthetic_template_local()
row = struct('trial_id', "", 'global_trial_index', 0, ...
    'element_trial_hash', "", 'measurement_hash', "", ...
    'method_id', "", 'observation_domain', "", ...
    'white_beamspace_snr_target_db', NaN, 'noise_profile_id', "", ...
    'L', 0, 'profile_id', "", 'replicate_id', 0, ...
    'base_realization_index', 0, 'applicable', true, ...
    'applicability_status', "APPLICABLE", 'fit_valid', false, ...
    'fit_status', "NOT_RUN", 'optimizer_status', "NOT_RUN", ...
    'selected_source', "FIXTURE", 'selected_start_id', "", ...
    'angles_hat_deg', "[0 0;1 1]", 'RSS', NaN, 'loglik', NaN, ...
    'effective_rank', 2, 'joint_RMSE_deg', NaN, ...
    'azimuth_RMSE_deg', NaN, 'elevation_RMSE_deg', NaN, ...
    'center_error_deg', NaN, 'axis_error_deg', NaN, ...
    'rho_error_deg', NaN, 'rho_relative_error', NaN, ...
    'separation_vector_error_deg', NaN, 'score_call_count', 0, ...
    'SVD_call_count', 0, 'eig_call_count', 0, 'runtime_sec', 0, ...
    'online_runtime_sec', 0, 'precompute_runtime_sec_amortized', 0, ...
    'coarse_candidate_count', 210, 'continuous_start_count', 6, ...
    'sweep_count', 1, 'local_peak_count', 0, 'sample_rank', 0, ...
    'peak_values', "[NaN NaN]", ...
    'numerical_optimization_incomplete_flag', false, ...
    'numerical_optimization_status', "NOT_APPLICABLE", ...
    'complete_likelihood_subset_flag', false, ...
    'raw_tangent_loglik_reference', NaN, 'likelihood_tolerance', NaN, ...
    'truth_used_in_fit_flag', false, ...
    'profile_used_in_fit_flag', false, ...
    'tangent_used_in_start_flag', false, ...
    'core_used_in_start_flag', false, ...
    'full_manifold_used_flag', true, ...
    'more_informative_element_reference_flag', false, ...
    'same_hardware_interface_flag', true);
end

function cleanup_local(path_now)
if isfolder(path_now)
    rmdir(path_now, 's');
end
end
