function result = test_element_subset_cardinality(fixture)
%TEST_ELEMENT_SUBSET_CARDINALITY Verify the mechanical 160-trial subset.

registry = fixture.registry;
selected = registry(registry.element_cml_registered_flag, :);
assert(height(selected) == 160 && ...
    isequal(sort(unique(double(selected.white_beamspace_snr_target_db))).', ...
    [10, 14, 18, 22]) && ...
    isequal(sort(unique(double(selected.L))).', 4) && ...
    isequal(sort(unique(double(selected.replicate_id))).', 1:5) && ...
    numel(unique(selected.profile_id)) == 4 && ...
    numel(unique(selected.noise_profile_id)) == 2, ...
    'test_element_subset_cardinality:Subset', ...
    'The preregistered Element CML factor subset changed.');
result = struct('pass', true, 'row_count', height(selected), ...
    'snr_count', numel(unique(selected.white_beamspace_snr_target_db)), ...
    'profile_count', numel(unique(selected.profile_id)), ...
    'noise_count', numel(unique(selected.noise_profile_id)));
end
