function result = test_four_trial_smoke(fixture)
%TEST_FOUR_TRIAL_SMOKE Run four fixed registered baseline cases.

registry = fixture.registry;
cases = { ...
    "P1", "WHITE", 4, 10; ...
    "P2", "STAGE5_TOEPLITZ_CORRELATED", 4, 14; ...
    "P3", "WHITE", 8, 18; ...
    "P4", "STAGE5_TOEPLITZ_CORRELATED", 1, 22};
resources = stage8_k2_wcb_prepare_music_resources(fixture.context);
statuses = strings(4, 3);
for index = 1:size(cases, 1)
    selected = registry.profile_id == cases{index, 1} & ...
        registry.noise_profile_id == cases{index, 2} & ...
        double(registry.L) == cases{index, 3} & ...
        double(registry.white_beamspace_snr_target_db) == ...
        cases{index, 4} & double(registry.replicate_id) == 1;
    spec = registry(selected, :);
    assert(height(spec) == 1, 'test_four_trial_smoke:Selection', ...
        'A fixed smoke case is not unique.');
    [trial, ~] = stage8_k2_wcb_reconstruct_trial(spec, fixture.context);
    [rows, diagnostics] = stage8_k2_wcb_evaluate_trial( ...
        spec, trial, fixture.context, resources);
    beam = rows(rows.method_id == ...
        "FULL4D_BEAMSPACE_CML_MULTISTART", :);
    music = rows(rows.method_id == "BEAMSPACE_MUSIC_K2", :);
    element = rows(rows.method_id == ...
        "FULL4D_ELEMENT_CML_MULTISTART", :);
    assert(beam.fit_status ~= "NOT_RUN" && ...
        music.fit_status ~= "NOT_RUN" && ...
        element.fit_status ~= "NOT_RUN" && ...
        logical(element.applicable) == (index <= 2) && ...
        diagnostics.truth_isolation_flag, ...
        'test_four_trial_smoke:Outcome', ...
        'A smoke case violated outcome, subset, or isolation contracts.');
    if index == 4
        assert(~music.applicable && music.fit_status == ...
            "NOT_APPLICABLE_INSUFFICIENT_SAMPLE_SUBSPACE_RANK", ...
            'test_four_trial_smoke:L1Music', ...
            'The L=1 smoke MUSIC row is not explicitly N/A.');
    end
    statuses(index, :) = [beam.fit_status, music.fit_status, ...
        element.fit_status];
end
result = struct('pass', true, 'case_count', 4, 'statuses', statuses, ...
    'element_case_count', 2, 'truth_leakage_count', 0);
end
