function result = test_full4d_contains_frozen_candidate(fixture)
%TEST_FULL4D_CONTAINS_FROZEN_CANDIDATE Verify grid and Tangent feasibility.

context = fixture.context;
tangent = context.tangent_rows;
selected = [find(logical(tangent.upgrade_flag), 1); ...
    find(logical(tangent.fallback_flag), 1)];
assert(numel(selected) == 2 && all(selected > 0), ...
    'test_full4d_contains_frozen_candidate:Cases', ...
    'Upgrade and fallback Tangent cases are both required.');
statuses = strings(2, 1);
for case_index = 1:2
    tangent_row = tangent(selected(case_index), :);
    spec = fixture.registry( ...
        fixture.registry.trial_id == tangent_row.trial_id, :);
    [trial, ~] = stage8_k2_wcb_reconstruct_trial(spec, context);
    angles = parse_angles_local(tangent_row.angles_hat_deg);
    bounds = context.plan.local_domain.domain_bounds_deg;
    feasible = all(angles(:, 1) >= bounds(1) & ...
        angles(:, 1) <= bounds(2) & angles(:, 2) >= bounds(3) & ...
        angles(:, 2) <= bounds(4)) && ...
        norm(angles(2, :) - angles(1, :)) >= ...
        context.constants.minimum_separation_deg;
    full_data = build_stage8_full_data_from_element( ...
        trial.Y_element, trial.model, struct('data_role', 'TEST_ONLY'));
    [G, ~, info] = build_full_sequential_local_manifold( ...
        angles, trial.model, struct('rank_multiplier', 1));
    [~, rss, ~, loglik, rank_now] = concentrated_dml_rss( ...
        full_data.Zseq_white, G, struct('requested_rank', 2, ...
        'rank_multiplier', 1, 'compute_projector_checks', false));
    assert(feasible && info.rank_Gseq >= 2 && rank_now >= 2 && ...
        isfinite(rss) && isfinite(loglik), ...
        'test_full4d_contains_frozen_candidate:Feasible', ...
        'A frozen Tangent candidate is outside the Full4D feasible set.');
    statuses(case_index) = string(tangent_row.selected_source);
end
point_count = size(context.plan.local_domain.candidate_points_deg, 1);
assert(point_count == 21 && nchoosek(point_count, 2) == 210, ...
    'test_full4d_contains_frozen_candidate:Grid', ...
    'The complete fixed-grid pair set changed.');
result = struct('pass', true, 'case_count', 2, ...
    'selected_sources', statuses, 'coarse_pair_count', 210);
end

function angles = parse_angles_local(value)
text = char(string(value));
text = strrep(text, '[', '');
text = strrep(text, ']', '');
parts = strsplit(text, ';');
assert(numel(parts) == 2, ...
    'test_full4d_contains_frozen_candidate:Angles', ...
    'Frozen Tangent endpoint serialization changed.');
first = sscanf(parts{1}, '%f').';
second = sscanf(parts{2}, '%f').';
angles = [first; second];
assert(isequal(size(angles), [2, 2]), ...
    'test_full4d_contains_frozen_candidate:AnglesShape', ...
    'Frozen Tangent endpoints are not 2-by-2.');
end
