function result = test_truth_isolation(fixture)
%TEST_TRUTH_ISOLATION Verify prohibited evaluation fields are rejected.

dummy = struct('Y_element', 0, 'model', struct(), ...
    'local_domain', struct(), 'resource_entry', struct(), ...
    'resources', struct(), 'L', 4, 'run_element_cml', false, ...
    'truth_angles_deg', zeros(2, 2));
rejected = false;
try
    stage8_k2_wcb_fit_baselines(dummy, fixture.context.constants);
catch exception
    rejected = strcmp(exception.identifier, ...
        'stage8_k2_wcb_fit_baselines:TruthIsolation');
end
assert(rejected, 'test_truth_isolation:Injection', ...
    'The fit entry did not reject injected truth.');

rows = fixture.context.evidence44.method_rows;
assert(~any(rows.truth_used_in_fit_flag), ...
    'test_truth_isolation:FrozenRows', ...
    'Evidence-44 methods contain truth leakage.');
result = struct('pass', true, 'injected_truth_rejected', rejected, ...
    'frozen_truth_leakage_count', nnz(rows.truth_used_in_fit_flag));
end
