function result = test_classical_budget_identity(fixture)
%TEST_CLASSICAL_BUDGET_IDENTITY Compare every frozen numerical budget value.

actual = fixture.context.constants;
frozen = stage8_k2_cb_constants();
fields = {'top_start_count','max_sweeps', ...
    'scan_nodes_per_coordinate','fminbnd_TolX_deg', ...
    'fminbnd_MaxFunEvals','minimum_separation_deg', ...
    'relative_score_tolerance','endpoint_update_tolerance_deg', ...
    'rank_multiplier','music_grid_step_deg','music_grid_chunk_size'};
for index = 1:numel(fields)
    assert(isequal(actual.(fields{index}), frozen.(fields{index})), ...
        'test_classical_budget_identity:Mismatch', ...
        'Frozen classical budget changed: %s', fields{index});
end
assert(actual.music_applicable_count == 1120 && ...
    actual.element_cml_count == 160, ...
    'test_classical_budget_identity:Counts', ...
    'Registered applicability counts changed.');
result = struct('pass', true, 'field_count', numel(fields));
end
