function result = test_evidence44_identity(fixture)
%TEST_EVIDENCE44_IDENTITY Verify completed evidence and all artifact hashes.

evidence = fixture.context.evidence44;
constants = fixture.context.constants;
assert(height(evidence.registry) == constants.trial_count && ...
    height(evidence.snr_rows) == constants.trial_count && ...
    height(evidence.method_rows) == constants.existing_method_row_count && ...
    numel(evidence.artifact_sha256) == ...
    constants.evidence44_artifact_count && ...
    numel(unique(evidence.registry.element_trial_hash)) == ...
    constants.trial_count && ...
    ~any(evidence.method_rows.truth_used_in_fit_flag), ...
    'test_evidence44_identity:Integrity', ...
    'Evidence 44 failed a registered identity or truth gate.');
result = struct('pass', true, ...
    'manifest_sha256', evidence.manifest_sha256, ...
    'artifact_count', numel(evidence.artifact_sha256), ...
    'registry_count', height(evidence.registry), ...
    'snr_row_count', height(evidence.snr_rows), ...
    'method_row_count', height(evidence.method_rows));
end
