function sensitivity = apply_stage7_pareto_to_existing_methods(result_dir)
%APPLY_STAGE7_PARETO_TO_EXISTING_METHODS Reapply frozen gates post hoc.

result_dir = validate_result_dir_local(result_dir);
summary = read_summary_local(result_dir);
method_ids = ["EXACT_ETA_080";"GREEDY_ETA_080"; ...
    "FULL_PARENT_5X5";"FIXED_RECT_3X5"; ...
    "FIXED_RECT_5X3";"FIXED_RECT_3X3"];
alignment = validate_stage7_method_scenario_alignment(summary, method_ids);
baseline_id = "FIXED_RECT_3X5";
full_parent_id = "FULL_PARENT_5X5";
baseline_rows = summary(summary.method_id == baseline_id, :);
full_rows = summary(summary.method_id == full_parent_id, :);
if isempty(baseline_rows) || isempty(full_rows)
    error('apply_stage7_pareto_to_existing_methods:References', ...
        'The frozen baseline or full-parent rows are missing.');
end
baseline_mac = unique(baseline_rows.MAC_total);
full_parent_mac = unique(full_rows.MAC_total);
if numel(baseline_mac) ~= 1 || numel(full_parent_mac) ~= 1
    error('apply_stage7_pareto_to_existing_methods:ReferenceCost', ...
        'Reference methods must have one fixed MAC value.');
end
full_success = pool_interval_local(full_rows, ...
    'paired_success_difference','paired_success_difference_95_low', ...
    'paired_success_difference_95_high');

rows = cell(numel(method_ids), 1);
for index = 1:numel(method_ids)
    selected = summary(summary.method_id == method_ids(index), :);
    if isempty(selected)
        error('apply_stage7_pareto_to_existing_methods:Method', ...
            'Missing persisted finite-sample summaries for %s.', method_ids(index));
    end
    success = pool_interval_local(selected, ...
        'paired_success_difference','paired_success_difference_95_low', ...
        'paired_success_difference_95_high');
    penalty = pool_interval_local(selected, ...
        'paired_error_difference','paired_error_difference_95_low', ...
        'paired_error_difference_95_high');
    wrong = pool_interval_local(selected, ...
        'wrong_peak_increase','wrong_peak_increase_95_low', ...
        'wrong_peak_increase_95_high');
    method_mac = unique(selected.MAC_total);
    method_class = unique(selected.method_class);
    subset_id = unique(selected.subset_id);
    if numel(method_mac) ~= 1 || numel(method_class) ~= 1 || ...
            numel(subset_id) ~= 1
        error('apply_stage7_pareto_to_existing_methods:Identity', ...
            'Method identity is inconsistent across persisted summaries.');
    end

    success_vs_full_mean = success.mean - full_success.mean;
    success_vs_full_sd_upper = success.standard_deviation + ...
        full_success.standard_deviation;
    full_half_width = 1.95996398454005 * success_vs_full_sd_upper / ...
        sqrt(success.n);
    success_vs_full_low = success_vs_full_mean - full_half_width;
    success_vs_full_high = success_vs_full_mean + full_half_width;
    mac_reduction = 1 - method_mac / baseline_mac;
    full_parent_reduction = 1 - method_mac / full_parent_mac;
    scheme_A = success.low >= -0.02 && mac_reduction >= 0.20 && ...
        wrong.high <= 0.02;
    scheme_B = method_mac <= baseline_mac && ...
        (success.low > 0 || penalty.high < 0) && ...
        success_vs_full_low >= -0.02 && full_parent_reduction >= 0.05;

    rows{index} = struct('method_id', method_ids(index), ...
        'method_class', method_class, 'subset_id', subset_id, ...
        'paired_success_difference', success.mean, ...
        'paired_success_difference_95_low', success.low, ...
        'paired_success_difference_95_high', success.high, ...
        'paired_penalized_error_difference', penalty.mean, ...
        'paired_penalized_error_difference_95_low', penalty.low, ...
        'paired_penalized_error_difference_95_high', penalty.high, ...
        'wrong_peak_difference', wrong.mean, ...
        'wrong_peak_difference_95_low', wrong.low, ...
        'wrong_peak_difference_95_high', wrong.high, ...
        'paired_success_difference_vs_full_parent', success_vs_full_mean, ...
        'paired_success_difference_vs_full_parent_95_low', ...
        success_vs_full_low, ...
        'paired_success_difference_vs_full_parent_95_high', ...
        success_vs_full_high, 'MAC_reduction', mac_reduction, ...
        'full_parent_MAC_reduction', full_parent_reduction, ...
        'scheme_A_pass', scheme_A, 'scheme_B_pass', scheme_B, ...
        'paired_interval_status', ...
        "EXACT_FROM_PERSISTED_PAIRED_SUMMARIES;FULL_PARENT_USES_CONSERVATIVE_SHARED_REFERENCE_BOUND", ...
        'method_scenario_alignment_status', ...
        string(alignment.alignment_status), ...
        'diagnostic_status', ...
        "POST_HOC_SENSITIVITY_NOT_USED_FOR_SELECTION");
end
sensitivity = struct2table(vertcat(rows{:}));
end

function summary = read_summary_local(result_dir)
names = ["finite_sample_normal_holdout.csv"; ...
    "finite_sample_threshold_holdout.csv"; ...
    "finite_sample_mismatch_holdout.csv"; ...
    "finite_sample_stress_holdout.csv"];
tables = cell(numel(names), 1);
for index = 1:numel(names)
    tables{index} = readtable(fullfile(result_dir, names(index)), ...
        'TextType', 'string');
end
summary = vertcat(tables{:});
end

function interval = pool_interval_local(rows, mean_name, low_name, high_name)
z = 1.95996398454005;
n = rows.n_trials;
means = rows.(mean_name);
half_width = max(abs(rows.(high_name) - means), ...
    abs(means - rows.(low_name)));
standard_deviation = half_width .* sqrt(n) / z;
sum_values = sum(n .* means);
sum_squares = sum((n - 1) .* standard_deviation .^ 2 + ...
    n .* means .^ 2);
total_n = sum(n);
pooled_mean = sum_values / total_n;
pooled_variance = max(0, ...
    (sum_squares - total_n * pooled_mean ^ 2) / max(total_n - 1, 1));
pooled_sd = sqrt(pooled_variance);
pooled_half_width = z * pooled_sd / sqrt(total_n);
interval = struct('mean', pooled_mean, ...
    'low', pooled_mean - pooled_half_width, ...
    'high', pooled_mean + pooled_half_width, ...
    'standard_deviation', pooled_sd, 'n', total_n);
end

function result_dir = validate_result_dir_local(result_dir)
if isstring(result_dir), result_dir = char(result_dir); end
if ~(ischar(result_dir) && isrow(result_dir) && exist(result_dir, 'dir') == 7)
    error('apply_stage7_pareto_to_existing_methods:ResultDir', ...
        'result_dir must identify the Stage 7 results directory.');
end
end
