function diagnostic = evaluate_stage7_1_tolerant_domain_check( ...
    targets_deg, domain_bounds_deg, historical_pass)
%EVALUATE_STAGE7_1_TOLERANT_DOMAIN_CHECK Apply an eps-derived boundary guard.

if ~(isnumeric(targets_deg) && ismatrix(targets_deg) && ...
        size(targets_deg, 2) == 2 && ~isempty(targets_deg) && ...
        all(isfinite(targets_deg), 'all'))
    error('evaluate_stage7_1_tolerant_domain_check:Targets', ...
        'targets_deg must be a finite nonempty N-by-2 matrix.');
end
if ~(isnumeric(domain_bounds_deg) && ...
        isequal(size(domain_bounds_deg), [2,2]) && ...
        all(isfinite(domain_bounds_deg), 'all') && ...
        all(domain_bounds_deg(:, 1) < domain_bounds_deg(:, 2)))
    error('evaluate_stage7_1_tolerant_domain_check:Bounds', ...
        'domain_bounds_deg must contain [min,max] rows for azimuth/elevation.');
end
if ~(isscalar(historical_pass) && ...
        (islogical(historical_pass) || isnumeric(historical_pass)) && ...
        isfinite(historical_pass) && ismember(double(historical_pass), [0,1]))
    error('evaluate_stage7_1_tolerant_domain_check:HistoricalPass', ...
        'historical_pass must be a logical or numeric zero/one scalar.');
end

parameter_dimension = numel(targets_deg);
domain_scale_deg = max(abs(domain_bounds_deg), [], 'all');
domain_tolerance_deg = parameter_dimension * eps(domain_scale_deg);
azimuth_pass = targets_deg(:, 1) >= ...
    domain_bounds_deg(1, 1) - domain_tolerance_deg & ...
    targets_deg(:, 1) <= domain_bounds_deg(1, 2) + domain_tolerance_deg;
elevation_pass = targets_deg(:, 2) >= ...
    domain_bounds_deg(2, 1) - domain_tolerance_deg & ...
    targets_deg(:, 2) <= domain_bounds_deg(2, 2) + domain_tolerance_deg;
tolerant_pass = all(azimuth_pass & elevation_pass);
historical_pass = logical(historical_pass);

diagnostic = struct();
diagnostic.historical_registered_domain_pass = historical_pass;
diagnostic.tolerant_registered_domain_pass = tolerant_pass;
diagnostic.boundary_numeric_disagreement_flag = ...
    historical_pass ~= tolerant_pass;
diagnostic.domain_tolerance_deg = domain_tolerance_deg;
diagnostic.domain_scale_deg = domain_scale_deg;
diagnostic.domain_parameter_dimension = parameter_dimension;
diagnostic.edge_diagnostic_domain_pass = tolerant_pass;
diagnostic.domain_tolerance_formula = ...
    'parameter_dimension*eps(domain_scale_deg)';
diagnostic.domain_gate_source = 'TOLERANT_REGISTERED_DOMAIN_PASS';
end
