function registry = stage7_1_artifact_registry()
%STAGE7_1_ARTIFACT_REGISTRY Return the fixed closure artifact contract.

rows = { ...
    row_local("stage7_1_provenance", "results/stage7_1_provenance.csv", ...
    "CSV", "RUNTIME_PROVENANCE", false, false, true); ...
    row_local("stage7_1_source_manifest", ...
    "results/stage7_1_source_manifest.csv", "CSV", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("stage7_core_historical_comparison", ...
    "results/stage7_core_historical_comparison.csv", "CSV", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("sequential_3by5_semantics", ...
    "results/sequential_3by5_semantics.md", "MARKDOWN", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("method_subset_aliases", ...
    "results/method_subset_aliases.csv", "CSV", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("minimum_cost_feasible_3by5", ...
    "results/minimum_cost_feasible_3by5.csv", "CSV", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("same_cost_dominance", ...
    "results/same_cost_dominance.csv", "CSV", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("existing_method_pareto_sensitivity", ...
    "results/existing_method_pareto_sensitivity.csv", "CSV", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("complexity_accounting_correction", ...
    "results/complexity_accounting_correction.csv", "CSV", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("edge_diagnostic_plan", ...
    "results/edge_diagnostic_plan.csv", "CSV", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("edge_diagnostic_trials", ...
    "results/edge_diagnostic_trials.csv", "CSV", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("edge_diagnostic_summary", ...
    "results/edge_diagnostic_summary.csv", "CSV", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("stage7_1_evidence_manifest", ...
    "results/stage7_1_evidence_manifest.csv", "CSV", ...
    "MANIFEST_META", false, true, false); ...
    row_local("stage7_1_keypoints", ...
    "results/stage7_1_keypoints.csv", "CSV", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("stage7_1_closure_report", ...
    "results/stage7_1_closure_report.md", "MARKDOWN", ...
    "DETERMINISTIC_CORE", true, false, false); ...
    row_local("stage7_1_runtime_diagnostics", ...
    "results/stage7_1_runtime_diagnostics.csv", "CSV", ...
    "RUNTIME_DIAGNOSTIC", false, false, true)};
registry = struct2table(vertcat(rows{:}));
if numel(unique(registry.artifact_id)) ~= height(registry) || ...
        numel(unique(registry.relative_path)) ~= height(registry)
    error('stage7_1_artifact_registry:Duplicate', ...
        'Artifact ids and relative paths must be unique.');
end
if any(registry.self_referential_exclusion_flag & ...
        registry.included_in_deterministic_bundle) || ...
        any(registry.contains_runtime_metadata & ...
        registry.included_in_deterministic_bundle)
    error('stage7_1_artifact_registry:BundleScope', ...
        'Runtime and self-referential artifacts cannot enter the bundle.');
end
end

function row = row_local(id, path_now, type, evidence_class, ...
    bundle_included, self_excluded, runtime_metadata)
row = struct('artifact_id', string(id), ...
    'relative_path', string(path_now), ...
    'artifact_type', string(type), ...
    'evidence_class', string(evidence_class), ...
    'required_by_closure_runner', true, ...
    'included_in_deterministic_bundle', logical(bundle_included), ...
    'self_referential_exclusion_flag', logical(self_excluded), ...
    'contains_runtime_metadata', logical(runtime_metadata));
end
