function table_out = test_stage7_1_no_core_algorithm_mutation(repo_dir)
%TEST_STAGE7_1_NO_CORE_ALGORITHM_MUTATION Alias the strict A3 scope gate.

scope = test_stage7_1_no_algorithm_mutation(repo_dir);
required = ["FORBIDDEN_CORE_MODIFICATION_COUNT"; ...
    "STAGE7_MODIFICATION_COUNT"; ...
    "STAGE7_RESULT_FIGURE_MODIFICATION_COUNT"; ...
    "SCOPE_VIOLATION_COUNT";"STAGE8_FILE_COUNT";"NEW_PNG_COUNT"];
case_id = "A3_STRICT_SCOPE_CASE_SET";
pass_flag = isequal(scope.case_id, required) && ...
    all(scope.actual_count == 0) && all(scope.pass_flag);
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_stage7_1_no_core_algorithm_mutation:Failed', ...
    'The A3 code-only scope gate failed.');
end
