function table_out = test_d0286_boundary_case(result_dir)
%TEST_D0286_BOUNDARY_CASE Freeze the historical/tolerant disagreement.

plan = build_stage7_1_edge_diagnostic_plan(result_dir);
d0286 = plan(plan.scenario_id == "D0286", :);
expected_tolerance = 4 * eps(10.4);

case_id = ["ROW_COUNT";"HISTORICAL_PASS_FALSE"; ...
    "TOLERANT_PASS_TRUE";"BOUNDARY_DISAGREEMENT_TRUE"; ...
    "TOLERANCE_EPS_DERIVED";"EDGE_GATE_TOLERANT_TRUE"; ...
    "HISTORICAL_FIELD_PRESERVED"];
pass_flag = [height(d0286) == 9; ...
    all(~d0286.historical_registered_domain_pass); ...
    all(d0286.tolerant_registered_domain_pass); ...
    all(d0286.boundary_numeric_disagreement_flag); ...
    all(d0286.domain_tolerance_deg == expected_tolerance); ...
    all(d0286.edge_diagnostic_domain_pass); ...
    all(d0286.registered_domain_pass == 0)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_d0286_boundary_case:Failed', ...
    'D0286 boundary classification is not frozen correctly.');
end
