function table_out = test_edge_three_methods_share_trial(result_dir)
%TEST_EDGE_THREE_METHODS_SHARE_TRIAL Exercise the real evaluator contract.

plan = build_stage7_1_synthetic_edge_fixture(result_dir);
group = plan(plan.paired_group_index == 1, :);
trial = generate_stage7_1_synthetic_common_trial(group(1, :), 1, struct());
finite = finite_fixture_local();
models = model_fixture_local();
opts = struct('unit_test_mode', true, ...
    'solver_function', @solver_fixture_local);
[rows, runtime] = evaluate_stage7_1_edge_methods( ...
    trial, models([3,1,2]), finite, group([2,3,1], :), opts);
shared_columns = {'trial_seed','realized_element_snr_db', ...
    'target1_az_deg','target1_el_deg','target2_az_deg','target2_el_deg', ...
    'common_trial_identity_hash'};
shared = true;
for index = 1:numel(shared_columns)
    shared = shared && numel(unique(rows.(shared_columns{index}))) == 1;
end

case_id = ["THREE_ROWS";"FIXED_METHOD_ORDER";"FIXED_SUBSET_MAPPING"; ...
    "SEED_SNR_TRUTH_SHARED";"ONLY_METHOD_OBJECTS_VARY"; ...
    "RUNTIME_SEPARATE"];
pass_flag = [height(rows) == 3;isequal(rows.method_id, ...
    ["FIXED_RECT_3X5";"GREEDY_ETA_080";"FULL_PARENT_5X5"]); ...
    isequal(rows.subset_id, ...
    ["RECT_E14_A31";"RECT_E28_A31";"RECT_E31_A31"]); ...
    shared;all(rows.method_varying_objects == "W_I;C_I;T_I;G_BANK"); ...
    height(runtime) == 3 && ~ismember('runtime_sec', ...
    rows.Properties.VariableNames)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_edge_three_methods_share_trial:Failed', ...
    'The fixed edge methods did not share one common trial.');
end

function finite = finite_fixture_local()
pool = struct('W0', eye(2));
success = struct('azimuth_gate_deg', 0.21, ...
    'elevation_gate_deg', 0.21, 'wrong_peak_pair_gate_deg', 0.45, ...
    'unconditional_penalty_deg', sqrt(0.4));
plan = struct('pool', pool, 'success', success);
finite = struct('context', struct('plan', plan));
end

function models = model_fixture_local()
method = ["FIXED_RECT_3X5";"GREEDY_ETA_080";"FULL_PARENT_5X5"];
subset = ["RECT_E14_A31";"RECT_E28_A31";"RECT_E31_A31"];
models = repmat(struct('method_id', "", 'subset_id', "", ...
    'channels', [], 'model', struct(), 'G_bank', []), 3, 1);
for index = 1:3
    models(index) = struct('method_id', method(index), ...
        'subset_id', subset(index), 'channels', 1:2, ...
        'model', struct('T_I', eye(2)), 'G_bank', eye(2));
end
end

function estimate = solver_fixture_local(~, ~, ~, ~)
estimate = struct('angles_hat_deg', [7.5,10;7.7,10], ...
    'score', 1, 'rss', 0, 'rank_G', 2, 'score_calls', 2, ...
    'svd_calls', 2, 'iterations', 1, 'multi_start_count', 1, ...
    'runtime_sec', 1e-6, 'estimate_returned_flag', true, ...
    'converged_flag', true, 'status', "SYNTHETIC_SOLVER_PASS");
end
