function table_out = test_same_cost_dominance_detection(result_dir)
%TEST_SAME_COST_DOMINANCE_DETECTION Preserve selection while marking risk.

family = enumerate_stage7_minimum_cost_feasible_set(result_dir, 0.80);
registered = family(family.subset_id == "RECT_E14_A31", :);
sensitivity = family(family.subset_id == "RECT_E28_A31", :);
dominators = family(family.same_cost_dominates_registered_flag, :);

case_id = ["SAME_MAC";"E28_COMPONENTWISE_HIGHER"; ...
    "E28_DOMINATES_REGISTERED";"ONLY_E28_DOMINATES"; ...
    "REGISTERED_SELECTION_UNCHANGED";"DOMINANCE_REASON"];
pass_flag = [registered.MAC_total == sensitivity.MAC_total; ...
    sensitivity.eta_design > registered.eta_design && ...
    sensitivity.eta_validation > registered.eta_validation && ...
    sensitivity.eta_holdout > registered.eta_holdout; ...
    sensitivity.same_cost_dominates_registered_flag; ...
    height(dominators) == 1 && dominators.subset_id == "RECT_E28_A31"; ...
    registered.registered_selection_flag && ...
    ~sensitivity.registered_selection_flag; ...
    sensitivity.dominance_reason == ...
    "SAME_MAC_AND_NO_LOWER_ETA_ACROSS_ALL_SPLITS"];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_same_cost_dominance_detection:Failed', ...
    'Same-cost dominance audit failed.');
end
