function table_out = test_stage7_source_hashed_readme_stability(repo_dir)
%TEST_STAGE7_SOURCE_HASHED_README_STABILITY Freeze the stable README contract.

relative_path = ['beamspace_ml_v18/source/stepwise_signal_model/steps/', ...
    'step_12_5_exact_subset_fim_beam_design/README.md'];
absolute_path = fullfile(repo_dir, strrep(relative_path, '/', filesep));
readme_text = string(fileread(absolute_path));
lower_text = lower(readme_text);
forbidden = ["closure rerun pending";"code tools implemented"; ...
    "the current registered result"; ...
    "the committed stage 7 results still describe"];
required = ["source-hashed contract"; ...
    "Stage7.1 result artifacts"; ...
    "innovation-mining/16_stage7_exact_subset_fim_audit.md"; ...
    "Subsequent Stage7.1B work must not modify this README"];
forbidden_absent = true;
for index = 1:numel(forbidden)
    forbidden_absent = forbidden_absent && ...
        ~contains(lower_text, forbidden(index));
end
required_present = false(size(required));
for index = 1:numel(required)
    required_present(index) = contains(readme_text, required(index));
end
command = sprintf('git -C "%s" hash-object --path="%s" -- "%s"', ...
    repo_dir, relative_path, relative_path);
[hash_status, hash_text] = system(command);
blob_hash = lower(string(strtrim(hash_text)));
expected_blob_hash = ...
    "ad2e11de647e31a8c92de9fdc653e5d1f1040d18";

case_id = ["README_READABLE";"DYNAMIC_STATUS_ABSENT"; ...
    "STABLE_CONTRACT_PRESENT";"STATUS_LOCATION_PRESENT"; ...
    "STAGE7_1B_IMMUTABILITY_PRESENT";"GIT_BLOB_HASH_FROZEN"];
pass_flag = [isfile(absolute_path);forbidden_absent; ...
    required_present(1);all(required_present(2:3)); ...
    required_present(4); ...
    hash_status == 0 && blob_hash == expected_blob_hash];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_stage7_source_hashed_readme_stability:Failed', ...
    'The Stage 7 source-hashed README contract changed.');
end
