function table_out = test_stage7_historical_comparison_contract( ...
    repo_dir, result_dir)
%TEST_STAGE7_HISTORICAL_COMPARISON_CONTRACT Compare locked Git objects.

[comparison, summary] = compare_stage7_core_results_to_commit( ...
    repo_dir, result_dir, struct());
keypoint_path = fullfile(result_dir, 'stage7_keypoints.csv');
keypoint_options = detectImportOptions(keypoint_path, 'TextType', 'string');
keypoint_options = setvartype(keypoint_options, ...
    {'metric','value','unit','status'}, 'string');
keypoints = readtable(keypoint_path, keypoint_options);
expected_variation = keypoints;
variation_mask = contains(lower(expected_variation.metric), 'runtime') | ...
    contains(lower(expected_variation.metric), 'plan_hash') | ...
    contains(lower(expected_variation.metric), 'source_tree_hash') | ...
    expected_variation.metric == "result_data_volume";
expected_variation.value(variation_mask) = "EXPECTED_TEST_VARIATION";
override = struct('unit_test_mode', true, ...
    'current_tables_override', struct( ...
    'stage7_keypoints', expected_variation));
[~, variation_summary] = compare_stage7_core_results_to_commit( ...
    repo_dir, result_dir, override);
status_change = keypoints;
status_change.value(status_change.metric == "stage7_status") = ...
    "FAIL_TEST_STATUS";
override.current_tables_override.stage7_keypoints = status_change;
[~, status_change_summary] = compare_stage7_core_results_to_commit( ...
    repo_dir, result_dir, override);
required = ["fim_subset_enumeration";"fim_operating_points"; ...
    "fim_greedy_exact_gap";"fim_subset_validation"; ...
    "fim_subset_holdout";"finite_sample_normal_holdout"; ...
    "finite_sample_threshold_holdout"; ...
    "finite_sample_mismatch_holdout"; ...
    "finite_sample_stress_holdout";"fim_vs_finite_sample_risk"; ...
    "stage7_keypoints"];

case_id = ["LOCKED_HISTORICAL_COMMIT";"ELEVEN_FILES_COMPARED"; ...
    "EXPLICIT_PRIMARY_KEYS";"ALL_COLUMN_GATES_PASS"; ...
    "SUBSET_SET_961_EXACT";"SELECTED_SUBSET_EXACT"; ...
    "STAGE7_STATUS_EXACT";"FINITE_SUCCESS_COUNTS_EXACT"; ...
    "NUMERIC_TOLERANCES_FROZEN"; ...
    "EXPECTED_METADATA_VARIATION_IGNORED"; ...
    "CORE_STATUS_CHANGE_REJECTED"];
pass_flag = [summary.historical_commit == ...
    "85615e0f5027e7d6dee840dcb71aa1a2c07e85c3"; ...
    summary.compared_file_count == 11 && ...
    all(ismember(required, unique(comparison.artifact_id))); ...
    all(strlength(comparison.primary_key_columns) > 0); ...
    all(comparison.pass_flag);summary.subset_contract_pass; ...
    summary.selected_exact_subset_pass && ...
    summary.selected_exact_subset_id == "RECT_E14_A31"; ...
    summary.stage7_status_pass && ...
    summary.stage7_status == "PASS_SYSTEM_ANALYSIS_ONLY"; ...
    nnz(comparison.column_name == ...
    "__FINITE_SAMPLE_SUCCESS_COUNT__") == 4 && all( ...
    comparison.pass_flag(comparison.column_name == ...
    "__FINITE_SAMPLE_SUCCESS_COUNT__")); ...
    summary.absolute_tolerance == 1e-12 && ...
    summary.relative_tolerance == 1e-10; ...
    variation_summary.pass_flag;~status_change_summary.pass_flag];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_stage7_historical_comparison_contract:Failed', ...
    'The Stage 7 Git-object historical comparison contract failed.');
end
