function table_out = ...
    test_non_memory_keypoint_change_still_fails(repo_dir, result_dir)
%TEST_NON_MEMORY_KEYPOINT_CHANGE_STILL_FAILS Preserve scientific strictness.

[~, summary] = run_stage7_keypoint_comparison_override( ...
    repo_dir, result_dir, 'stage7_status', 'value', ...
    "FAIL_TEST_SCIENTIFIC_CHANGE");
case_id = ["NON_MEMORY_CHANGE_REJECTED"; ...
    "SCIENTIFIC_FAILURE_RETAINED";"STATUS_CONTRACT_REJECTED"];
pass_flag = [~summary.pass_flag && summary.failed_comparison_count > 0; ...
    summary.core_scientific_failed_comparison_count > 0; ...
    ~summary.stage7_status_pass];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_non_memory_keypoint_change_still_fails:Failed', ...
    'A non-memory Stage 7 keypoint change was not rejected.');
end
