function table_out = test_common_trial_generated_once(repo_dir, result_dir)
%TEST_COMMON_TRIAL_GENERATED_ONCE Run a two-group synthetic edge fixture.

plan = build_stage7_1_synthetic_edge_fixture(result_dir);
opts = struct('unit_test_mode', true, 'edge_plan', plan, ...
    'execution_context', struct('fixture', true), ...
    'common_trial_generator', @generate_stage7_1_synthetic_common_trial, ...
    'method_evaluator', @evaluate_stage7_1_synthetic_edge_methods);
output = run_stage7_1_edge_diagnostics(repo_dir, opts);
common = unique(output.trials(:, ...
    {'paired_group_id','trial_index','trial_seed'}), 'rows');

case_id = ["FIXTURE_COMMON_TRIAL_COUNT_4"; ...
    "GENERATOR_CALLED_ONCE_PER_COMMON_TRIAL"; ...
    "METHOD_EVALUATION_COUNT_12";"THREE_METHODS_PER_TRIAL"; ...
    "SUMMARY_ROW_COUNT_6"];
pass_flag = [height(common) == 4; ...
    output.common_trial_generation_count == height(common); ...
    output.method_evaluation_count == 12; ...
    height(output.trials) == 3 * height(common); ...
    height(output.summary) == 6];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_common_trial_generated_once:Failed', ...
    'The edge runner regenerated a common trial per method.');
end
