function table_out = test_method_scenario_alignment(result_dir)
%TEST_METHOD_SCENARIO_ALIGNMENT Verify paired summary preconditions.

summary = read_summary_local(result_dir);
method_ids = ["EXACT_ETA_080";"GREEDY_ETA_080"; ...
    "FULL_PARENT_5X5";"FIXED_RECT_3X5"; ...
    "FIXED_RECT_5X3";"FIXED_RECT_3X3"];
contract = validate_stage7_method_scenario_alignment(summary, method_ids);

missing = summary;
remove_index = find(missing.method_id == "FIXED_RECT_3X3", 1);
missing(remove_index, :) = [];
missing_stopped = throws_local(@() ...
    validate_stage7_method_scenario_alignment(missing, method_ids), ...
    'validate_stage7_method_scenario_alignment:ScenarioSet');

duplicate = [summary;summary(find(summary.method_id == ...
    "EXACT_ETA_080", 1), :)];
duplicate_stopped = throws_local(@() ...
    validate_stage7_method_scenario_alignment(duplicate, method_ids), ...
    'validate_stage7_method_scenario_alignment:DuplicateScenario');

mismatched_trials = summary;
trial_index = find(mismatched_trials.method_id == "GREEDY_ETA_080", 1);
mismatched_trials.n_trials(trial_index) = ...
    mismatched_trials.n_trials(trial_index) - 1;
trial_stopped = throws_local(@() ...
    validate_stage7_method_scenario_alignment( ...
    mismatched_trials, method_ids), ...
    'validate_stage7_method_scenario_alignment:TrialCount');

sensitivity = apply_stage7_pareto_to_existing_methods(result_dir);
case_id = ["REAL_METHOD_COUNT";"REAL_SCENARIO_COUNT"; ...
    "REAL_ALIGNMENT_PASS";"MISSING_SCENARIO_STOPS"; ...
    "DUPLICATE_SCENARIO_STOPS";"TRIAL_MISMATCH_STOPS"; ...
    "OUTPUT_ALIGNMENT_STATUS";"FULL_PARENT_INTERVAL_LABEL_RETAINED"];
pass_flag = [contract.method_count == 6;contract.scenario_count == 29; ...
    strcmp(contract.alignment_status, ...
    'PASS_IDENTICAL_SCENARIO_SET_AND_PER_SCENARIO_TRIAL_COUNT'); ...
    missing_stopped;duplicate_stopped;trial_stopped; ...
    all(sensitivity.method_scenario_alignment_status == ...
    "PASS_IDENTICAL_SCENARIO_SET_AND_PER_SCENARIO_TRIAL_COUNT"); ...
    all(contains(sensitivity.paired_interval_status, ...
    "FULL_PARENT_USES_CONSERVATIVE_SHARED_REFERENCE_BOUND"))];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_method_scenario_alignment:Failed', ...
    'Method/scenario paired-summary alignment contract failed.');
end

function summary = read_summary_local(result_dir)
names = ["finite_sample_normal_holdout.csv"; ...
    "finite_sample_threshold_holdout.csv"; ...
    "finite_sample_mismatch_holdout.csv"; ...
    "finite_sample_stress_holdout.csv"];
tables = cell(numel(names), 1);
for index = 1:numel(names)
    tables{index} = readtable(fullfile(result_dir, names(index)), ...
        'TextType', 'string');
end
summary = vertcat(tables{:});
end

function flag = throws_local(action, expected_identifier)
flag = false;
try
    action();
catch exception
    flag = strcmp(exception.identifier, expected_identifier);
end
end
