function table_out = ...
    test_memory_contract_uses_frozen_plan(repo_dir, result_dir)
%TEST_MEMORY_CONTRACT_USES_FROZEN_PLAN Reject missing or changed dimensions.

plan = build_stage7_1_memory_plan_fixture(result_dir);
aliases = build_stage7_method_subset_alias_table(result_dir);
[~, historical] = compare_stage7_core_results_to_commit( ...
    repo_dir, result_dir, struct());
dimensions = build_stage7_1_complexity_dimensions_from_frozen_plan(plan);
complexity = compute_stage7_complexity_accounting_correction( ...
    result_dir, aliases, dimensions, struct());

missing = rmfield(plan, 'cost');
missing_rejected = throws_local(@() build_stage7_memory_contract_audit( ...
    result_dir, missing, historical, complexity), ...
    'build_stage7_memory_contract_audit:FrozenPlan');
changed = plan;
changed.cost.N_el = 31;
changed_dimensions = ...
    build_stage7_1_complexity_dimensions_from_frozen_plan(changed);
changed_complexity = compute_stage7_complexity_accounting_correction( ...
    result_dir, aliases, changed_dimensions, struct());
changed_audit = build_stage7_memory_contract_audit( ...
    result_dir, changed, historical, changed_complexity);
short_pool = plan;
short_pool.pool.table(end, :) = [];
short_pool_audit = build_stage7_memory_contract_audit( ...
    result_dir, short_pool, historical, complexity);

case_id = ["MISSING_PLAN_DIMENSIONS_REJECTED"; ...
    "CHANGED_PLAN_DIMENSION_FAILS";"CHANGED_POOL_FAILS"; ...
    "NO_DEFAULT_DIMENSION_SOURCE"];
pass_flag = [missing_rejected; ...
    ~changed_audit.deterministic_contract_pass && ...
    changed_audit.workspace_contract_bytes ~= 34611200; ...
    ~short_pool_audit.deterministic_contract_pass && ...
    short_pool_audit.candidate_pool_size == 24; ...
    strcmp(complexity.dimension_source, ...
    'FROZEN_STAGE7_PLAN_EXPLICIT_DIMENSIONS')];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_memory_contract_uses_frozen_plan:Failed', ...
    'Memory accounting accepted an unfrozen dimension source.');
end

function flag = throws_local(action, expected_identifier)
flag = false;
try
    action();
catch exception
    flag = strcmp(exception.identifier, expected_identifier);
end
end
