function table_out = test_stage7_1_no_algorithm_mutation(repo_dir)
%TEST_STAGE7_1_NO_ALGORITHM_MUTATION Enforce the code-only audit scope.

stage7 = ['beamspace_ml_v18/source/stepwise_signal_model/steps/', ...
    'step_12_5_exact_subset_fim_beam_design'];
stage71 = ['beamspace_ml_v18/source/stepwise_signal_model/steps/', ...
    'step_12_5_1_stage7_closure_audit/'];
forbidden = string(stage7) + [ ...
    "/common/build_exact_subset_model.m"; ...
    "/common/effective_deterministic_fim.m"; ...
    "/common/relative_fim_retention.m"; ...
    "/common/build_stage7_element_manifold.m"; ...
    "/common/apply_stage7_element_whitener.m"; ...
    "/common/construct_deterministic_source_matrix.m"; ...
    "/common/enumerate_exact_subset_design.m"; ...
    "/common/evaluate_stage7_subset.m"; ...
    "/common/greedy_exchange_exact_subset_design.m"; ...
    "/common/run_stage7_oracle_dml.m"; ...
    "/common/run_stage7_finite_sample_validation.m"; ...
    "/common/apply_stage7_finite_sample_pareto_gate.m"];
allowed_stage7 = string(stage7) + "/README.md";
allowed_docs = ["innovation-mining/13_next_step_execution_prompts.md"; ...
    "innovation-mining/16_stage7_exact_subset_fim_audit.md"];

[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain=v1 --untracked-files=all', repo_dir));
if status ~= 0
    error('test_stage7_1_no_algorithm_mutation:Git', ...
        'Unable to inspect the working tree.');
end
lines = splitlines(string(regexprep(output, '[\r\n]+$', '')));
lines(lines == "") = [];
paths = strings(numel(lines), 1);
for index = 1:numel(lines)
    paths(index) = extractAfter(lines(index), 3);
end
forbidden_changed = ismember(paths, forbidden);
allowed = startsWith(paths, stage71) | ismember(paths, allowed_stage7) | ...
    ismember(paths, allowed_docs);
result_or_figure_changed = startsWith(paths, string(stage7) + "/results/") | ...
    startsWith(paths, string(stage7) + "/figures/");
stage7_nonreadme_changed = startsWith(paths, string(stage7) + "/") & ...
    paths ~= allowed_stage7;
stage8_changed = contains(paths, '/step_12_6_') | ...
    contains(paths, '/stage8');
png_added = endsWith(lower(paths), '.png');

case_id = ["FORBIDDEN_CORE_MODIFICATION_COUNT"; ...
    "STAGE7_NONREADME_MODIFICATION_COUNT"; ...
    "STAGE7_RESULT_FIGURE_MODIFICATION_COUNT";"SCOPE_VIOLATION_COUNT"; ...
    "STAGE8_FILE_COUNT";"NEW_PNG_COUNT"];
actual_count = [nnz(forbidden_changed);nnz(stage7_nonreadme_changed); ...
    nnz(result_or_figure_changed);nnz(~allowed);nnz(stage8_changed); ...
    nnz(png_added)];
expected_count = zeros(size(actual_count));
pass_flag = actual_count == expected_count;
table_out = table(case_id, actual_count, expected_count, pass_flag);
assert(all(pass_flag), 'test_stage7_1_no_algorithm_mutation:Failed', ...
    'Stage7.1A changed a forbidden file or exceeded its scope.');
end
