function table_out = test_stage7_1_code_identity(repo_dir)
%TEST_STAGE7_1_CODE_IDENTITY Verify the bindable worktree source identity.

first = build_stage7_1_code_identity(repo_dir);
second = build_stage7_1_code_identity(repo_dir);
[head_status, head_text] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', repo_dir));
head_commit = lower(string(strtrim(head_text)));
manifest = first.manifest;
paths = string(manifest.relative_path);
blob_lengths = strlength(string(manifest.git_blob_hash));
expected_root = ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/" + ...
    "step_12_5_1_stage7_closure_audit/";
scope_pass = all(startsWith(paths, expected_root)) && ...
    all(endsWith(paths, '.m') | paths == expected_root + "README.md");
if first.working_tree_clean_flag
    expected_role = "COMMITTED_SOURCE_COMMIT";
    expected_status = "COMMITTED_GIT_BLOB_TREE_IDENTITY";
else
    expected_role = "BASE_COMMIT_FOR_WORKTREE_GIT_BLOB_MANIFEST";
    expected_status = "WORKTREE_GIT_BLOB_TREE_IDENTITY";
end

case_id = ["HEAD_READABLE";"SOURCE_COMMIT_BOUND"; ...
    "SOURCE_SCOPE_NONEMPTY";"SOURCE_SCOPE_ONLY"; ...
    "MANIFEST_ORDER_STABLE";"GIT_BLOB_HASH_FORMAT"; ...
    "TREE_HASH_FORMAT";"TREE_HASH_ALIAS";"IDENTITY_HASH_FORMAT"; ...
    "IDENTITY_VERSION";"WORKTREE_ROLE_BOUND";"WORKTREE_STATUS_BOUND"; ...
    "DETERMINISTIC_IDENTITY"];
pass_flag = [head_status == 0;string(first.source_commit) == head_commit; ...
    first.source_file_count == height(manifest) && height(manifest) > 0; ...
    scope_pass;isequal(manifest.manifest_order, (1:height(manifest)).'); ...
    all(blob_lengths == 40 | blob_lengths == 64); ...
    strlength(string(first.stage7_1_source_tree_hash)) == 64; ...
    strcmp(first.stage7_1_git_blob_tree_hash, ...
    first.stage7_1_source_tree_hash); ...
    strlength(string(first.stage7_1_code_identity_hash)) == 64; ...
    strcmp(first.code_identity_contract_version, ...
    'STAGE7_1_CODE_IDENTITY_V1'); ...
    string(first.source_commit_role) == expected_role; ...
    string(first.code_identity_status) == expected_status; ...
    strcmp(first.stage7_1_code_identity_hash, ...
    second.stage7_1_code_identity_hash) && ...
    isequal(first.manifest, second.manifest)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_stage7_1_code_identity:Failed', ...
    'Stage7.1 code identity is not deterministic and bindable.');
end
