function table_out = test_stage7_1_untracked_source_rejected(repo_dir)
%TEST_STAGE7_1_UNTRACKED_SOURCE_REJECTED Enforce tracked-only formal scope.

untracked_m = ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/" + ...
    "step_12_5_1_stage7_closure_audit/common/untracked_fixture.m";
opts = formal_fixture_options_local();
opts.git_status_porcelain_override = "?? " + untracked_m;
opts.untracked_source_paths_override = untracked_m;
m_rejected = throws_local(@() build_stage7_1_code_identity(repo_dir, opts), ...
    'build_stage7_1_code_identity:UntrackedSource');
untracked_readme = ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/" + ...
    "step_12_5_1_stage7_closure_audit/common/README.md";
opts.git_status_porcelain_override = "?? " + untracked_readme;
opts.untracked_source_paths_override = untracked_readme;
readme_rejected = throws_local(@() ...
    build_stage7_1_code_identity(repo_dir, opts), ...
    'build_stage7_1_code_identity:UntrackedSource');
case_id = ["UNTRACKED_M_REJECTED";"UNTRACKED_README_REJECTED"; ...
    "FORMAL_MODE_ENABLED"];
pass_flag = [m_rejected;readme_rejected;opts.formal_mode];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_stage7_1_untracked_source_rejected:Failed', ...
    'Formal Stage7.1 identity accepted untracked source.');
end

function opts = formal_fixture_options_local()
opts = struct('formal_mode', true, 'unit_test_mode', true, ...
    'runtime_head_commit_override', ...
    '25e063730309dac2595390d46744040ba6fbe4b3', ...
    'baseline_ancestor_flag_override', true, ...
    'git_status_porcelain_override', '', ...
    'untracked_source_paths_override', strings(0, 1));
end

function flag = throws_local(action, expected_identifier)
flag = false;
try
    action();
catch exception
    flag = strcmp(exception.identifier, expected_identifier);
end
end
