function table_out = ...
    test_peak_memory_pass_flag_change_fails(repo_dir, result_dir)
%TEST_PEAK_MEMORY_PASS_FLAG_CHANGE_FAILS Reject a failed diagnostic row.

[comparison, summary] = run_stage7_keypoint_comparison_override( ...
    repo_dir, result_dir, 'peak_memory_estimate', 'pass_flag', 0);
diagnostic = comparison(comparison.comparison_type == ...
    "SCHEMA_DEPENDENT_ESTIMATE_DIAGNOSTIC", :);
case_id = ["PASS_FLAG_CHANGE_REJECTED"; ...
    "DIAGNOSTIC_PASS_FLAG_CONTRACT_FAILS"];
pass_flag = [~summary.pass_flag && summary.failed_comparison_count > 0; ...
    height(diagnostic) == 1 && ~diagnostic.pass_flag];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_peak_memory_pass_flag_change_fails:Failed', ...
    'A false peak-memory pass flag was not rejected.');
end
