function table_out = test_stage7_1_stable_readme_contract(step_dir)
%TEST_STAGE7_1_STABLE_README_CONTRACT Reject run-specific README state.

text_value = string(fileread(fullfile(step_dir, 'README.md')));
lower_text = lower(text_value);
required = ["schema-dependent workspace diagnostic"; ...
    "Deterministic memory evidence is independently derived"; ...
    "true measured process peak"; ...
    "Current closure state belongs in Stage7.1 result"; ...
    "innovation-mining/16_stage7_exact_subset_fim_audit.md"];
forbidden = ["closure pending";"closure completed"; ...
    "closure rerun pending";"69742";"69,742"; ...
    "current bundle hash";"current runtime head"];
required_present = false(numel(required), 1);
for index = 1:numel(required)
    required_present(index) = contains(text_value, required(index));
end
forbidden_absent = true(numel(forbidden), 1);
for index = 1:numel(forbidden)
    forbidden_absent(index) = ~contains(lower_text, forbidden(index));
end
case_id = ["STABLE_MEMORY_CONTRACT_PRESENT"; ...
    "RUNTIME_PEAK_EXCLUSION_PRESENT";"STATUS_LOCATION_PRESENT"; ...
    "RUN_SPECIFIC_STATE_ABSENT"];
pass_flag = [all(required_present(1:2));required_present(3); ...
    all(required_present(4:5));all(forbidden_absent)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_stage7_1_stable_readme_contract:Failed', ...
    'The Stage7.1 README contains unstable run state.');
end
