function table_out = test_existing_method_pareto_sensitivity(result_dir)
%TEST_EXISTING_METHOD_PARETO_SENSITIVITY Verify post-hoc-only gate output.

sensitivity = apply_stage7_pareto_to_existing_methods(result_dir);
required = ["EXACT_ETA_080";"GREEDY_ETA_080";"FULL_PARENT_5X5"; ...
    "FIXED_RECT_3X5";"FIXED_RECT_5X3";"FIXED_RECT_3X3"];
exact = sensitivity(sensitivity.method_id == "EXACT_ETA_080", :);
fixed = sensitivity(sensitivity.method_id == "FIXED_RECT_3X5", :);
zero_columns = {'paired_success_difference', ...
    'paired_penalized_error_difference','wrong_peak_difference'};
exact_zero = true;
fixed_zero = true;
for index = 1:numel(zero_columns)
    exact_zero = exact_zero && abs(exact.(zero_columns{index})) <= 1e-15;
    fixed_zero = fixed_zero && abs(fixed.(zero_columns{index})) <= 1e-15;
end

case_id = ["METHOD_SET";"POST_HOC_STATUS";"EXACT_FIXED_SUBSET_ALIAS"; ...
    "EXACT_ZERO_DIFFERENCES";"FIXED_ZERO_DIFFERENCES"; ...
    "EXACT_SCHEME_A_REJECTED";"EXACT_SCHEME_B_REJECTED"; ...
    "PERSISTED_INTERVAL_STATUS"];
pass_flag = [height(sensitivity) == 6 && ...
    all(ismember(required, sensitivity.method_id)); ...
    all(sensitivity.diagnostic_status == ...
    "POST_HOC_SENSITIVITY_NOT_USED_FOR_SELECTION"); ...
    exact.subset_id == fixed.subset_id;exact_zero;fixed_zero; ...
    ~exact.scheme_A_pass;~exact.scheme_B_pass; ...
    all(contains(sensitivity.paired_interval_status, ...
    "EXACT_FROM_PERSISTED_PAIRED_SUMMARIES"))];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_existing_method_pareto_sensitivity:Failed', ...
    'Existing-method Pareto sensitivity audit failed.');
end
