function table_out = ...
    test_peak_memory_schema_dependent_difference_passes(repo_dir, result_dir)
%TEST_PEAK_MEMORY_SCHEMA_DEPENDENT_DIFFERENCE_PASSES Accept valid variation.

[comparison, summary] = run_stage7_keypoint_comparison_override( ...
    repo_dir, result_dir, 'peak_memory_estimate', 'value', "110417088");
diagnostic = comparison(comparison.comparison_type == ...
    "SCHEMA_DEPENDENT_ESTIMATE_DIAGNOSTIC", :);
case_id = ["CORE_COMPARISON_PASSES";"DIAGNOSTIC_ROW_UNIQUE"; ...
    "ORIGINAL_VALUES_RETAINED";"DELTA_RETAINED"; ...
    "DIAGNOSTIC_REASON_RETAINED";"VARIATION_NOT_FAILURE"; ...
    "SCIENTIFIC_FAILURE_COUNT_ZERO";"DIAGNOSTIC_STATUS_EXPLICIT"];
pass_flag = [summary.pass_flag; height(diagnostic) == 1; ...
    diagnostic.historical_value_numeric == 110347346 && ...
    diagnostic.current_value_numeric == 110417088; ...
    diagnostic.absolute_difference == 69742 && ...
    abs(diagnostic.relative_difference - 69742 / 110347346) <= ...
    eps(69742 / 110347346); ...
    diagnostic.diagnostic_reason == ...
    "PROVENANCE_SCHEMA_CHANGED_CONTEXT_WHOS_BYTES"; ...
    summary.failed_comparison_count == 0 && ...
    summary.diagnostic_variation_count == 1; ...
    summary.core_scientific_failed_comparison_count == 0; ...
    summary.peak_memory_comparison_status == ...
    "EXPECTED_PROVENANCE_SCHEMA_DEPENDENT_VARIATION"];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_peak_memory_schema_dependent_difference_passes:Failed', ...
    'A valid schema-dependent peak-memory variation was rejected.');
end
