function table_out = test_complexity_accounting_correction(result_dir)
%TEST_COMPLEXITY_ACCOUNTING_CORRECTION Verify duplicate and memory counts.

aliases = build_stage7_method_subset_alias_table(result_dir);
frozen_plan = frozen_plan_fixture_local();
dimensions = build_stage7_1_complexity_dimensions_from_frozen_plan( ...
    frozen_plan);
accounting = compute_stage7_complexity_accounting_correction( ...
    result_dir, aliases, dimensions);
unit_test_options = struct('unit_test_mode', true, ...
    'allow_default_dimensions', true);
default_accounting = compute_stage7_complexity_accounting_correction( ...
    result_dir, aliases, [], unit_test_options);
missing_dimensions_stopped = throws_local(@() ...
    compute_stage7_complexity_accounting_correction(result_dir, aliases), ...
    'compute_stage7_complexity_accounting_correction:ExplicitDimensions');
test_only_flag_required = throws_local(@() ...
    compute_stage7_complexity_accounting_correction( ...
    result_dir, aliases, [], struct('allow_default_dimensions', true)), ...
    'compute_stage7_complexity_accounting_correction:DefaultScope');
default_opt_in_required = throws_local(@() ...
    compute_stage7_complexity_accounting_correction( ...
    result_dir, aliases, [], struct('unit_test_mode', true)), ...
    'compute_stage7_complexity_accounting_correction:ExplicitDimensions');
untrusted_dimensions = dimensions;
untrusted_dimensions.dimension_source = 'UNIT_TEST_DEFAULT_DIMENSIONS';
frozen_source_required = throws_local(@() ...
    compute_stage7_complexity_accounting_correction( ...
    result_dir, aliases, untrusted_dimensions), ...
    'compute_stage7_complexity_accounting_correction:FrozenPlanSource');
expected_ratio = 499200 / 17136;

case_id = ["FROZEN_PLAN_DIMENSIONS";"FROZEN_PLAN_SOURCE"; ...
    "FROZEN_PLAN_HASH_BOUND";"ACTUAL_SCORE_CALLS";"CHARGED_SCORE_CALLS"; ...
    "DUPLICATE_CHARGE";"UNIQUE_SUBSETS";"METHOD_LABELS"; ...
    "MATERIALIZED_BYTES";"ELEVATION_BYTES";"AZIMUTH_BYTES"; ...
    "FACTORIZED_BYTES";"MEMORY_RATIO";"FORMAL_DIMENSIONS_REQUIRED"; ...
    "DEFAULTS_REQUIRE_TEST_MODE";"DEFAULTS_REQUIRE_EXPLICIT_OPT_IN"; ...
    "FORMAL_SOURCE_REQUIRED";"UNIT_TEST_DEFAULTS_AVAILABLE"];
pass_flag = [isequal([dimensions.N_el,dimensions.N_az, ...
    dimensions.B_el,dimensions.B_az], [32,65,3,5]); ...
    strcmp(dimensions.dimension_source, ...
    'FROZEN_STAGE7_PLAN_EXPLICIT_DIMENSIONS'); ...
    strcmp(accounting.frozen_stage7_plan_hash, ...
    frozen_plan.hashes.stage7_plan_hash); ...
    accounting.actual_unique_subset_score_calls == 9152562; ...
    accounting.charged_method_score_calls == 11734516; ...
    accounting.duplicate_method_charge == 2581954; ...
    accounting.unique_subset_count == 7; ...
    accounting.method_label_count == 9; ...
    accounting.materialized_equivalent_W_bytes == 16 * 2080 * 15; ...
    accounting.factorized_elevation_weight_bytes == 16 * 32 * 3; ...
    accounting.factorized_azimuth_weight_bytes == 16 * 65 * 5 * 3; ...
    accounting.factorized_total_weight_bytes == ...
    16 * (32 * 3 + 65 * 5 * 3); ...
    abs(accounting.materialized_to_factorized_memory_ratio - ...
    expected_ratio) <= 16 * eps(expected_ratio); ...
    missing_dimensions_stopped;test_only_flag_required; ...
    default_opt_in_required;frozen_source_required; ...
    strcmp(default_accounting.dimension_source, ...
    'UNIT_TEST_DEFAULT_DIMENSIONS')];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_complexity_accounting_correction:Failed', ...
    'Corrected Stage 7 complexity accounting failed.');
end

function plan = frozen_plan_fixture_local()
subset_id = ["RECT_E14_A31";"RECT_E31_A31"];
B_e = [3;5];
B_a = [5;5];
plan = struct();
plan.cost = struct('N_el', 32, 'N_az', 65, ...
    'complex_double_bytes', 16);
plan.subset_family = table(subset_id, B_e, B_a);
plan.hashes = struct('stage7_plan_hash', repmat('a', 1, 64));
end

function flag = throws_local(action, expected_identifier)
flag = false;
try
    action();
catch exception
    flag = strcmp(exception.identifier, expected_identifier);
end
end
