function table_out = ...
    test_stage7_1_stable_identity_excludes_runtime_head(repo_dir)
%TEST_STAGE7_1_STABLE_IDENTITY_EXCLUDES_RUNTIME_HEAD Freeze stable inputs.

common = struct('unit_test_mode', true, ...
    'baseline_ancestor_flag_override', true, ...
    'git_status_porcelain_override', '', ...
    'untracked_source_paths_override', strings(0, 1));
first_opts = common;
first_opts.runtime_head_commit_override = repmat('a', 1, 40);
second_opts = common;
second_opts.runtime_head_commit_override = repmat('b', 1, 40);
first = build_stage7_1_code_identity(repo_dir, first_opts);
second = build_stage7_1_code_identity(repo_dir, second_opts);

case_id = ["FAKE_RUNTIME_HEADS_DIFFER";"SOURCE_TREE_SAME"; ...
    "STABLE_IDENTITY_SAME";"RUNTIME_METADATA_ONLY_CHANGED"];
pass_flag = [~strcmp(first.runtime_head_commit, second.runtime_head_commit); ...
    strcmp(first.stage7_1_source_tree_hash, ...
    second.stage7_1_source_tree_hash); ...
    strcmp(first.stage7_1_stable_code_identity_hash, ...
    second.stage7_1_stable_code_identity_hash); ...
    strcmp(first.runtime_head_role, 'RUNTIME_METADATA_ONLY') && ...
    strcmp(second.runtime_head_role, 'RUNTIME_METADATA_ONLY')];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_stage7_1_stable_identity_excludes_runtime_head:Failed', ...
    'Runtime HEAD contaminated the stable Stage7.1 identity.');
end
