function table_out = test_edge_paired_seed_contract(result_dir)
%TEST_EDGE_PAIRED_SEED_CONTRACT Verify common random data across methods.

plan = build_stage7_1_edge_diagnostic_plan(result_dir);
group_keys = unique(plan(:, {'scenario_id','element_snr_db'}), ...
    'rows', 'stable');
group_seed = zeros(height(group_keys), 1);
method_pass = false(height(group_keys), 1);
seed_pass = false(height(group_keys), 1);
paired_id_pass = false(height(group_keys), 1);
common_trial_pass = false(height(group_keys), 1);
group_ids = strings(height(group_keys), 1);
expected_methods = sort(["FIXED_RECT_3X5";"GREEDY_ETA_080"; ...
    "FULL_PARENT_5X5"]);
for group_index = 1:height(group_keys)
    selected = plan(plan.scenario_id == group_keys.scenario_id(group_index) & ...
        plan.element_snr_db == group_keys.element_snr_db(group_index), :);
    group_seed(group_index) = selected.seed(1);
    group_ids(group_index) = selected.paired_group_id(1);
    method_pass(group_index) = height(selected) == 3 && ...
        isequal(sort(selected.method_id), expected_methods);
    seed_pass(group_index) = numel(unique(selected.seed)) == 1;
    paired_id_pass(group_index) = ...
        numel(unique(selected.paired_group_id)) == 1;
    common_trial_pass(group_index) = ...
        all(selected.common_trial_generation_status == ...
        "GENERATE_ELEMENT_DOMAIN_TRIAL_ONCE_THEN_APPLY_THREE_PHYSICAL_SUBSETS");
end

case_id = ["PAIRED_GROUP_COUNT";"THREE_METHODS_PER_GROUP"; ...
    "ONE_SEED_WITHIN_GROUP";"UNIQUE_SEED_ACROSS_GROUPS"; ...
    "PAIRED_GROUP_ID_SHARED";"PAIRED_GROUP_IDS_UNIQUE"; ...
    "COMMON_ELEMENT_TRIAL_GENERATED_ONCE"];
pass_flag = [height(group_keys) == 18;all(method_pass);all(seed_pass); ...
    numel(unique(group_seed)) == numel(group_seed); ...
    all(paired_id_pass);numel(unique(group_ids)) == numel(group_ids); ...
    all(common_trial_pass)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_edge_paired_seed_contract:Failed', ...
    'Edge diagnostic methods do not share paired random trials.');
end
