function table_out = test_minimum_cost_feasible_set(result_dir)
%TEST_MINIMUM_COST_FEASIBLE_SET Verify the complete eta0=0.80 family.

family = enumerate_stage7_minimum_cost_feasible_set(result_dir, 0.80);
registered = family(family.subset_id == "RECT_E14_A31", :);
sensitivity = family(family.subset_id == "RECT_E28_A31", :);

case_id = ["FAMILY_SIZE";"ALL_MINIMUM_COST";"ALL_TRIPLE_FEASIBLE"; ...
    "REGISTERED_MEMBER";"REGISTERED_ROLE";"CENTRAL_ROLE"; ...
    "SENSITIVITY_MEMBER";"SENSITIVITY_ROLES"];
pass_flag = [height(family) == 6; ...
    all(family.MAC_total == 7215 & family.B_out == 15 & ...
    family.minimum_cost_flag); ...
    all(family.eta_design >= 0.80 & family.eta_validation >= 0.80 & ...
    family.eta_holdout >= 0.80);height(registered) == 1 && ...
    registered.registered_selection_flag; ...
    contains(registered.role, "LEXICOGRAPHIC_REGISTERED_SELECTION"); ...
    contains(registered.role, "CENTRAL_SYMMETRIC_FIXED_BASELINE"); ...
    height(sensitivity) == 1; ...
    contains(sensitivity.role, "MAX_DESIGN_ETA_SENSITIVITY") && ...
    contains(sensitivity.role, "MAX_VALIDATION_ETA_SENSITIVITY") && ...
    contains(sensitivity.role, "MAX_HOLDOUT_ETA_SENSITIVITY")];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_minimum_cost_feasible_set:Failed', ...
    'Minimum-cost feasible family audit failed.');
end
