function table_out = test_stage7_1_identity_changes_with_source_blob(repo_dir)
%TEST_STAGE7_1_IDENTITY_CHANGES_WITH_SOURCE_BLOB Change one manifest blob.

base = build_stage7_1_code_identity(repo_dir);
changed_manifest = base.manifest;
original_blob = changed_manifest.git_blob_hash(1);
replacement = string(repmat('f', 1, strlength(original_blob)));
if replacement == original_blob
    replacement = string(repmat('e', 1, strlength(original_blob)));
end
changed_manifest.git_blob_hash(1) = replacement;
opts = struct('unit_test_mode', true, ...
    'runtime_head_commit_override', base.runtime_head_commit, ...
    'baseline_ancestor_flag_override', true, ...
    'git_status_porcelain_override', '', ...
    'untracked_source_paths_override', strings(0, 1), ...
    'source_manifest_override', changed_manifest);
changed = build_stage7_1_code_identity(repo_dir, opts);

case_id = ["ONE_BLOB_CHANGED";"SOURCE_TREE_CHANGED"; ...
    "STABLE_IDENTITY_CHANGED";"RUNTIME_HEAD_UNCHANGED"];
pass_flag = [changed.manifest.git_blob_hash(1) ~= original_blob; ...
    ~strcmp(base.stage7_1_source_tree_hash, ...
    changed.stage7_1_source_tree_hash); ...
    ~strcmp(base.stage7_1_stable_code_identity_hash, ...
    changed.stage7_1_stable_code_identity_hash); ...
    strcmp(base.runtime_head_commit, changed.runtime_head_commit)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_stage7_1_identity_changes_with_source_blob:Failed', ...
    'A source blob change did not change the stable identity.');
end
