function table_out = test_edge_trial_seed_blocks_nonoverlapping(result_dir)
%TEST_EDGE_TRIAL_SEED_BLOCKS_NONOVERLAPPING Freeze all common trial seeds.

plan = build_stage7_1_edge_diagnostic_plan(result_dir);
groups = unique(plan(:, {'paired_group_id','paired_group_index', ...
    'group_seed_start','paired_trial_count','seed_block_stride'}), ...
    'rows', 'stable');
seed_matrix = zeros(height(groups), 200);
for index = 1:height(groups)
    seed_matrix(index, :) = groups.group_seed_start(index) + (0:199);
end
all_seeds = seed_matrix(:);
block_gap = diff(groups.group_seed_start);
method_rows = repelem(all_seeds, 3);

case_id = ["GROUP_COUNT_18";"TRIAL_COUNT_PER_GROUP_200"; ...
    "BLOCK_STRIDE_1000";"BLOCK_INTERVALS_NONOVERLAPPING"; ...
    "COMMON_SEED_COUNT_3600";"ALL_COMMON_SEEDS_UNIQUE"; ...
    "METHOD_ROW_COUNT_10800";"THREE_ROWS_PER_COMMON_SEED"];
pass_flag = [height(groups) == 18;all(groups.paired_trial_count == 200); ...
    all(groups.seed_block_stride == 1000);all(block_gap >= 1000); ...
    numel(all_seeds) == 3600;numel(unique(all_seeds)) == 3600; ...
    numel(method_rows) == 10800;all(accumarray( ...
    repelem((1:3600).', 3), 1) == 3)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_edge_trial_seed_blocks_nonoverlapping:Failed', ...
    'Edge paired trial seed blocks overlap or contain duplicates.');
end
