function table_out = test_complexity_accounting_correction(result_dir)
%TEST_COMPLEXITY_ACCOUNTING_CORRECTION Verify duplicate and memory counts.

aliases = build_stage7_method_subset_alias_table(result_dir);
accounting = compute_stage7_complexity_accounting_correction( ...
    result_dir, aliases, struct('N_el', 32, 'N_az', 65, ...
    'B_el', 3, 'B_az', 5, 'complex_double_bytes', 16));
expected_ratio = 499200 / 17136;

case_id = ["ACTUAL_SCORE_CALLS";"CHARGED_SCORE_CALLS"; ...
    "DUPLICATE_CHARGE";"UNIQUE_SUBSETS";"METHOD_LABELS"; ...
    "MATERIALIZED_BYTES";"ELEVATION_BYTES";"AZIMUTH_BYTES"; ...
    "FACTORIZED_BYTES";"MEMORY_RATIO"];
pass_flag = [accounting.actual_unique_subset_score_calls == 9152562; ...
    accounting.charged_method_score_calls == 11734516; ...
    accounting.duplicate_method_charge == 2581954; ...
    accounting.unique_subset_count == 7; ...
    accounting.method_label_count == 9; ...
    accounting.materialized_equivalent_W_bytes == 16 * 2080 * 15; ...
    accounting.factorized_elevation_weight_bytes == 16 * 32 * 3; ...
    accounting.factorized_azimuth_weight_bytes == 16 * 65 * 5 * 3; ...
    accounting.factorized_total_weight_bytes == ...
    16 * (32 * 3 + 65 * 5 * 3); ...
    abs(accounting.materialized_to_factorized_memory_ratio - ...
    expected_ratio) <= 16 * eps(expected_ratio)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_complexity_accounting_correction:Failed', ...
    'Corrected Stage 7 complexity accounting failed.');
end
