function table_out = test_stage7_1_code_identity(repo_dir)
%TEST_STAGE7_1_CODE_IDENTITY Verify tracked source and runtime separation.

first = build_stage7_1_code_identity(repo_dir);
second = build_stage7_1_code_identity(repo_dir);
[head_status, head_text] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', repo_dir));
head_commit = lower(string(strtrim(head_text)));
manifest = first.manifest;
reordered_manifest = manifest(end:-1:1, ...
    {'relative_path','git_mode','git_blob_hash'});
reorder_opts = struct('unit_test_mode', true, ...
    'runtime_head_commit_override', first.runtime_head_commit, ...
    'baseline_ancestor_flag_override', first.baseline_ancestor_flag, ...
    'git_status_porcelain_override', first.git_status_porcelain, ...
    'untracked_source_paths_override', first.untracked_source_paths, ...
    'source_manifest_override', reordered_manifest);
reordered = build_stage7_1_code_identity(repo_dir, reorder_opts);
paths = string(manifest.relative_path);
expected_root = ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/" + ...
    "step_12_5_1_stage7_closure_audit/";
scope_pass = all(startsWith(paths, expected_root)) && ...
    all(~contains(paths, expected_root + "results/") & ...
    ~contains(paths, expected_root + "figures/")) && ...
    all(endsWith(paths, '.m') | paths == expected_root + "README.md");

case_id = ["HEAD_READABLE";"RUNTIME_HEAD_RECORDED"; ...
    "HISTORICAL_BASELINE_FROZEN";"SOURCE_SCOPE_NONEMPTY"; ...
    "SOURCE_SCOPE_TRACKED_ONLY";"MANIFEST_ORDER_STABLE"; ...
    "TREE_HASH_FORMAT";"STABLE_IDENTITY_HASH_FORMAT"; ...
    "IDENTITY_VERSION";"RUNTIME_ROLE_METADATA_ONLY"; ...
    "DETERMINISTIC_IDENTITY";"MANIFEST_INPUT_ORDER_INVARIANT"];
pass_flag = [head_status == 0;string(first.runtime_head_commit) == head_commit; ...
    strcmp(first.historical_baseline_commit, ...
    '25e063730309dac2595390d46744040ba6fbe4b3'); ...
    first.source_file_count == height(manifest) && height(manifest) > 0; ...
    scope_pass;isequal(manifest.manifest_order, (1:height(manifest)).'); ...
    strlength(string(first.stage7_1_source_tree_hash)) == 64; ...
    strlength(string(first.stage7_1_stable_code_identity_hash)) == 64; ...
    strcmp(first.code_identity_contract_version, ...
    'STAGE7_1_STABLE_CODE_IDENTITY_V2'); ...
    strcmp(first.runtime_head_role, 'RUNTIME_METADATA_ONLY'); ...
    strcmp(first.stage7_1_stable_code_identity_hash, ...
    second.stage7_1_stable_code_identity_hash) && ...
    isequal(first.manifest, second.manifest); ...
    strcmp(first.stage7_1_stable_code_identity_hash, ...
    reordered.stage7_1_stable_code_identity_hash) && ...
    isequal(first.manifest, reordered.manifest)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_stage7_1_code_identity:Failed', ...
    'Stage7.1 tracked-source identity contract failed.');
end
