function table_out = test_sequential_3by5_semantics()
%TEST_SEQUENTIAL_3BY5_SEMANTICS Verify dimensions and equivalent weights.

rng(20260719, 'twister');
N_el = 4;
N_az = 7;
V = randn(N_el, 3) + 1i * randn(N_el, 3);
Uset = randn(N_az, 5, 3) + 1i * randn(N_az, 5, 3);
Y = randn(N_el, N_az) + 1i * randn(N_el, N_az);
audit = audit_stage7_sequential_channel_semantics(V, Uset, Y);

case_id = ["B_EL";"B_AZ";"B_OUT";"ZEL_DIMENSION"; ...
    "ZSEQ_DIMENSION";"PROCESSING_ORDER";"FIRST_STAGE_FORMULA"; ...
    "SECOND_STAGE_FORMULA";"EQUIVALENT_WEIGHT"; ...
    "FORMAL_TERMINOLOGY";"NUMERICAL_EQUIVALENCE"];
pass_flag = [audit.B_el == 3;audit.B_az == 5;audit.B_out == 15; ...
    isequal(audit.Zel_dimension, [3,N_az]); ...
    isequal(audit.Zseq_dimension, [3,5]); ...
    strcmp(audit.processing_order, ...
    'ELEVATION_DBF_THEN_ELEVATION_CONDITIONED_AZIMUTH_DBF'); ...
    strcmp(audit.Zel_formula, 'Zel=V''*Y'); ...
    strcmp(audit.conditioned_output_formula, ...
    'z(b,c)=u(c|b)''*Zel(b,:)'''); ...
    strcmp(audit.equivalent_weight_formula, ...
    'w(b,c)=kron(u(c|b),v(b))'); ...
    audit.terminology_status == ...
    "3 个俯仰中间通道，每通道 5 个条件方位输出"; ...
    audit.equivalence_relative_error <= 1e-12 && ...
    audit.maximum_channel_relative_error <= 1e-12];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_sequential_3by5_semantics:Failed', ...
    'Sequential 3/5 channel semantics failed.');
end
