function table_out = test_tolerant_domain_boundary_contract()
%TEST_TOLERANT_DOMAIN_BOUNDARY_CONTRACT Verify the eps-only tolerance rule.

bounds = [7.4,8.6;9.6,10.4];
scale = max(abs(bounds), [], 'all');
targets = [7.4,10.2;7.8,10.2];
exact = evaluate_stage7_1_tolerant_domain_check(targets, bounds, true);
roundoff_targets = targets;
roundoff_targets(1, 1) = bounds(1, 1) - eps(scale);
roundoff = evaluate_stage7_1_tolerant_domain_check( ...
    roundoff_targets, bounds, false);
outside_targets = targets;
outside_targets(1, 1) = bounds(1, 1) - 2 * roundoff.domain_tolerance_deg;
outside = evaluate_stage7_1_tolerant_domain_check( ...
    outside_targets, bounds, false);

case_id = ["TOLERANCE_FORMULA";"PARAMETER_DIMENSION"; ...
    "EXACT_BOUNDARY_PASS";"ONE_ULP_ROUNDOFF_PASS"; ...
    "ROUNDOFF_DISAGREEMENT";"BEYOND_TOLERANCE_FAIL"; ...
    "EDGE_GATE_USES_TOLERANT_PASS"];
pass_flag = [roundoff.domain_tolerance_deg == numel(targets) * eps(scale); ...
    roundoff.domain_parameter_dimension == numel(targets); ...
    exact.tolerant_registered_domain_pass; ...
    roundoff.tolerant_registered_domain_pass; ...
    roundoff.boundary_numeric_disagreement_flag; ...
    ~outside.tolerant_registered_domain_pass; ...
    roundoff.edge_diagnostic_domain_pass == ...
    roundoff.tolerant_registered_domain_pass];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_tolerant_domain_boundary_contract:Failed', ...
    'The tolerance-aware domain contract failed.');
end
