function table_out = test_memory_audit_writer_determinism(repo_dir)
%TEST_MEMORY_AUDIT_WRITER_DETERMINISM Freeze the merged memory artifact.

first_root = tempname;
second_root = tempname;
mkdir(first_root);
mkdir(second_root);
cleanup = onCleanup(@() remove_temp_local(first_root, second_root));
first_result = fullfile(first_root, 'results');
second_result = fullfile(second_root, 'results');
mkdir(first_result);
mkdir(second_result);
bundle = build_stage7_1_writer_fixture(repo_dir);
[~, first_manifest] = write_stage7_1_results_bundle( ...
    first_result, bundle, struct('unit_test_mode', true));
[~, second_manifest] = write_stage7_1_results_bundle( ...
    second_result, bundle, struct('unit_test_mode', true));
first = readtable(fullfile(first_result, ...
    'complexity_accounting_correction.csv'), 'TextType', 'string');
second = readtable(fullfile(second_result, ...
    'complexity_accounting_correction.csv'), 'TextType', 'string');
required = {'workspace_contract_bytes', ...
    'legacy_peak_memory_estimate_historical_bytes', ...
    'legacy_peak_memory_estimate_current_bytes', ...
    'legacy_peak_memory_estimate_delta_bytes', ...
    'legacy_peak_memory_estimate_relative_delta', ...
    'legacy_peak_memory_estimate_status', ...
    'legacy_peak_memory_estimate_reason', ...
    'deterministic_memory_contract_pass'};
first_row = first_manifest.artifact_id == ...
    "complexity_accounting_correction";
second_row = second_manifest.artifact_id == ...
    "complexity_accounting_correction";

case_id = ["MEMORY_COLUMNS_PRESENT";"WORKSPACE_VALUE_WRITTEN"; ...
    "LEGACY_VALUES_WRITTEN";"LEGACY_STATUS_WRITTEN"; ...
    "DETERMINISTIC_PASS_WRITTEN";"MEMORY_ARTIFACT_BYTES_IDENTICAL"; ...
    "MEMORY_ARTIFACT_HASH_IDENTICAL"];
pass_flag = [all(ismember(required, first.Properties.VariableNames)); ...
    first.workspace_contract_bytes == 34611200; ...
    first.legacy_peak_memory_estimate_historical_bytes == 110347346 && ...
    first.legacy_peak_memory_estimate_current_bytes == 110417088 && ...
    first.legacy_peak_memory_estimate_delta_bytes == 69742; ...
    first.legacy_peak_memory_estimate_status == ...
    "EXPECTED_PROVENANCE_SCHEMA_DEPENDENT_VARIATION" && ...
    first.legacy_peak_memory_estimate_reason == ...
    "PROVENANCE_SCHEMA_CHANGED_CONTEXT_WHOS_BYTES"; ...
    logical(first.deterministic_memory_contract_pass); ...
    first_manifest.byte_count(first_row) == ...
    second_manifest.byte_count(second_row); ...
    first_manifest.sha256(first_row) == second_manifest.sha256(second_row) && ...
    isequal(first, second)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_memory_audit_writer_determinism:Failed', ...
    'The merged memory-accounting artifact is not deterministic.');
clear cleanup
end

function remove_temp_local(first_root, second_root)
if exist(first_root, 'dir') == 7, rmdir(first_root, 's'); end
if exist(second_root, 'dir') == 7, rmdir(second_root, 's'); end
end
