function [result_table, context] = verify_stage6_frozen_evidence(package_dir)
%VERIFY_STAGE6_FROZEN_EVIDENCE Recheck the deterministic Stage 6 manifest.

stage6_dir = fullfile(package_dir, 'source', 'stepwise_signal_model', ...
    'steps', 'step_12_4_near_pair_tangent_asymptotics');
manifest = readtable(fullfile(stage6_dir, 'results', ...
    'stage6_evidence_manifest.csv'), 'TextType', 'string');
frozen = manifest(manifest.included_in_deterministic_bundle == 1, :);
missing = false(height(frozen), 1);
size_mismatch = false(height(frozen), 1);
hash_mismatch = false(height(frozen), 1);
for index = 1:height(frozen)
    path_now = fullfile(stage6_dir, ...
        strrep(char(frozen.relative_path(index)), '/', filesep));
    if exist(path_now, 'file') ~= 2
        missing(index) = true;
        continue;
    end
    info = dir(path_now);
    size_mismatch(index) = info.bytes ~= frozen.byte_count(index);
    hash_mismatch(index) = ~strcmpi(stage7_1_sha256_file(path_now), ...
        char(frozen.sha256(index)));
end
pass_flag = ~(missing | size_mismatch | hash_mismatch);
result_table = table(frozen.artifact_id, frozen.relative_path, missing, ...
    size_mismatch, hash_mismatch, pass_flag, 'VariableNames', ...
    {'artifact_id','relative_path','missing_flag','size_mismatch_flag', ...
    'hash_mismatch_flag','pass_flag'});
bundle_hash = unique(manifest.stage6_evidence_bundle_hash);
expected = "0c1f444603398e03865043af4e4c6e4a414dd15a3cc90e0539b19c56e990c839";
assert(height(frozen) == 21 && all(pass_flag) && ...
    isscalar(bundle_hash) && bundle_hash == expected, ...
    'verify_stage6_frozen_evidence:Failed', ...
    'The frozen deterministic Stage 6 evidence changed.');
context = struct('file_count', height(frozen), ...
    'hash_mismatch_count', nnz(hash_mismatch), ...
    'bundle_hash', char(bundle_hash), 'pass_flag', all(pass_flag));
end
