function fixture = stage8_k2_sb_test_vertical_fixture(context, noise_id)
%STAGE8_K2_SB_TEST_VERTICAL_FIXTURE Build a high-SNR coherent vertical fixture.

entry = context.models([context.models.noise_profile_id] == string(noise_id));
model = entry.model;
constants = context.constants;
theta = [9.90, 10.10];
k0_dz = 2 * pi / model.lambda * ...
    model.array_configuration.arr.dz;
V = exp(1j * (0:constants.N_el - 1).' * ...
    (k0_dz * sind(theta)));
coherent_snapshot = V * [1; 0.85 * exp(1j * 0.73)];
R_signal = coherent_snapshot * coherent_snapshot';
R_vertical = 1e4 * R_signal + entry.noise_factors.R_el;
[R_fb, R_noise_subarray, fbss_info] = ...
    stage8_k2_sb_fbss_covariance(R_vertical, ...
    entry.noise_factors.R_el, constants);
fixture = struct('theta_deg', theta, 'model', model, ...
    'noise_factors', entry.noise_factors, ...
    'R_signal', R_signal, 'R_vertical', R_vertical, ...
    'R_fb', R_fb, 'R_noise_subarray', R_noise_subarray, ...
    'fbss_info', fbss_info);
end
