function context = prepare_stage7_fim_context(plan, cfg)
%PREPARE_STAGE7_FIM_CONTEXT Precompute registered scenario geometry.

noise_models = { ...
    build_stage7_noise_covariance('WHITE', cfg), ...
    build_stage7_noise_covariance('STAGE5_TOEPLITZ_CORRELATED', cfg)};
for noise_index = 1:2
    noise_models{noise_index}.C0 = plan.pool.W0' * ...
        noise_models{noise_index}.Rn * plan.pool.W0;
end
full_channels = 1:size(plan.pool.W0, 2);
parent_models = cell(2, 1);
for noise_index = 1:2
    parent_models{noise_index} = build_exact_subset_model( ...
        plan.pool, full_channels, noise_models{noise_index}, struct());
end
scenario_tables = {plan.design_scenarios, plan.validation_scenarios, ...
    plan.fim_holdout_scenarios};
all_scenarios = vertcat(scenario_tables{:});
scenario_count = height(all_scenarios);
template = struct('scenario_id', '', 'data_split', '', 'noise_index', 0, ...
    'target_angles_deg', zeros(2), 'S', zeros(2, 1), ...
    'raw_G0', zeros(25, 2), 'raw_dG0_az', zeros(25, 2), ...
    'raw_dG0_el', zeros(25, 2), 'F_element', zeros(4), ...
    'F_parent', zeros(4), 'element_rank', 0, 'parent_rank', 0, ...
    'eta_parent', NaN, 'element_status', '', 'parent_status', '');
scenarios = repmat(template, scenario_count, 1);
for scenario_index = 1:scenario_count
    row = all_scenarios(scenario_index, :);
    targets = [row.target1_az_deg, row.target1_el_deg; ...
        row.target2_az_deg, row.target2_el_deg];
    [S, ~] = construct_deterministic_source_matrix(2, row.L, ...
        row.secondary_power_db, row.correlation_magnitude, ...
        row.correlation_phase_rad, row.source_profile_id);
    manifold = build_stage7_element_manifold(targets, plan.pool, cfg);
    noise_index = noise_index_local(row.noise_covariance_id);
    noise = noise_models{noise_index};
    G_element = apply_stage7_element_whitener(manifold.A, noise, cfg);
    dG_element = struct( ...
        'azimuth', apply_stage7_element_whitener(manifold.dA_az, noise, cfg), ...
        'elevation', apply_stage7_element_whitener(manifold.dA_el, noise, cfg));
    element_fim = effective_deterministic_fim( ...
        G_element, dG_element, S, plan.controls.sigma2_fim, struct());
    raw_G0 = plan.pool.W0' * manifold.A;
    raw_dG0_az = plan.pool.W0' * manifold.dA_az;
    raw_dG0_el = plan.pool.W0' * manifold.dA_el;
    parent_model = parent_models{noise_index};
    parent_fim = effective_deterministic_fim( ...
        parent_model.T_I * raw_G0, struct( ...
        'azimuth', parent_model.T_I * raw_dG0_az, ...
        'elevation', parent_model.T_I * raw_dG0_el), ...
        S, plan.controls.sigma2_fim, struct());
    retention = relative_fim_retention(element_fim.F, parent_fim.F, ...
        struct('expected_rank', 4));
    scenarios(scenario_index) = struct( ...
        'scenario_id', char(row.scenario_id), ...
        'data_split', char(row.data_split), 'noise_index', noise_index, ...
        'target_angles_deg', targets, 'S', S, 'raw_G0', raw_G0, ...
        'raw_dG0_az', raw_dG0_az, 'raw_dG0_el', raw_dG0_el, ...
        'F_element', element_fim.F, 'F_parent', parent_fim.F, ...
        'element_rank', element_fim.rank_F, 'parent_rank', parent_fim.rank_F, ...
        'eta_parent', retention.eta, 'element_status', element_fim.status, ...
        'parent_status', parent_fim.status);
end
context = struct();
context.plan = plan;
context.cfg = cfg;
context.noise_models = noise_models;
context.parent_models = parent_models;
context.scenarios = scenarios;
context.scenario_table = all_scenarios;
context.design_indices = find(string({scenarios.data_split}) == "DESIGN");
context.validation_indices = find(string({scenarios.data_split}) == "VALIDATION");
context.holdout_indices = find(string({scenarios.data_split}) == "FIM_HOLDOUT");
context.precompute_counts = struct('scenario_count', scenario_count, ...
    'element_fim_evaluations', scenario_count, ...
    'parent_fim_evaluations', scenario_count, ...
    'receive_manifold_evaluations', scenario_count, ...
    'derivative_evaluations', 2 * scenario_count, ...
    'parent_covariance_decompositions', 2);
end

function index = noise_index_local(noise_id)
if string(noise_id) == "WHITE"
    index = 1;
elseif string(noise_id) == "STAGE5_TOEPLITZ_CORRELATED"
    index = 2;
else
    error('prepare_stage7_fim_context:NoiseId', ...
        'Unknown noise id: %s.', char(noise_id));
end
end
