function [operating, pareto] = select_stage7_operating_points(enumeration, context)
%SELECT_STAGE7_OPERATING_POINTS Apply the registered exact tie-breaks.

eta_values = context.plan.controls.eta_operating_points(:);
parent_match = enumeration.elevation_mask_integer == 31 & ...
    enumeration.azimuth_mask_integer == 31;
eta_parent = enumeration.eta_design(parent_match);
rows = cell(numel(eta_values), 1);
for index = 1:numel(eta_values)
    eta0 = eta_values(index);
    feasible = enumeration(enumeration.eta_design >= eta0, :);
    if eta_parent < eta0 || isempty(feasible)
        rows{index} = operating_row_local(eta0, table(), eta_parent, ...
            'DESIGN_OPERATING_POINT_INFEASIBLE');
        continue;
    end
    feasible.incremental_cost = feasible.MAC_total - ...
        (context.cfg.arr.Nel * context.cfg.beam.subNaz + ...
        context.cfg.beam.subNaz);
    feasible.lexicographic_id = string(feasible.subset_id);
    feasible = sortrows(feasible, {'MAC_total','B_out','incremental_cost', ...
        'lexicographic_id'}, {'ascend','ascend','ascend','ascend'});
    rows{index} = operating_row_local(eta0, feasible(1, :), eta_parent, ...
        'EXACT_RECTANGULAR_ENUMERATION_SELECTED');
end
operating = struct2table(vertcat(rows{:}));

valid = isfinite(enumeration.eta_design);
candidate = enumeration(valid, :);
dominated = false(height(candidate), 1);
for index = 1:height(candidate)
    dominates = candidate.MAC_total <= candidate.MAC_total(index) & ...
        candidate.eta_design >= candidate.eta_design(index) & ...
        (candidate.MAC_total < candidate.MAC_total(index) | ...
        candidate.eta_design > candidate.eta_design(index));
    dominated(index) = any(dominates);
end
pareto = candidate(~dominated, :);
pareto = sortrows(pareto, {'MAC_total','eta_design'}, {'ascend','descend'});
end

function row = operating_row_local(eta0, selected, eta_parent, status)
if isempty(selected)
    row = struct('eta0', eta0, 'method_id', sprintf('EXACT_ETA_%03d', ...
        round(100 * eta0)), 'subset_id', "", ...
        'elevation_mask_integer', NaN, 'azimuth_mask_integer', NaN, ...
        'B_e', NaN, 'B_a', NaN, 'B_out', NaN, 'MAC_total', NaN, ...
        'eta_design', NaN, 'eta_validation', NaN, 'eta_holdout', NaN, ...
        'eta_parent', eta_parent, 'fim_gate_pass', false, ...
        'status', string(status));
    return;
end
fim_pass = selected.eta_design >= eta0 && ...
    selected.eta_validation >= eta0 && selected.eta_holdout >= eta0;
if fim_pass
    final_status = 'FIM_DESIGN_VALIDATION_HOLDOUT_PASS';
else
    final_status = 'FIM_VALIDATION_OR_HOLDOUT_REJECTED';
end
row = struct('eta0', eta0, 'method_id', sprintf('EXACT_ETA_%03d', ...
    round(100 * eta0)), 'subset_id', string(selected.subset_id), ...
    'elevation_mask_integer', selected.elevation_mask_integer, ...
    'azimuth_mask_integer', selected.azimuth_mask_integer, ...
    'B_e', selected.B_e, 'B_a', selected.B_a, ...
    'B_out', selected.B_out, 'MAC_total', selected.MAC_total, ...
    'eta_design', selected.eta_design, ...
    'eta_validation', selected.eta_validation, ...
    'eta_holdout', selected.eta_holdout, 'eta_parent', eta_parent, ...
    'fim_gate_pass', fim_pass, 'status', string(final_status));
end
