function [scenario_summary, aggregate] = summarize_stage7_finite_sample_trials( ...
    trials, methods, strongest_fixed_method)
%SUMMARIZE_STAGE7_FINITE_SAMPLE_TRIALS Report unconditional paired metrics.

scenario_ids = unique(trials.scenario_id, 'stable');
rows = cell(numel(scenario_ids) * height(methods), 1);
row_index = 0;
for scenario_index = 1:numel(scenario_ids)
    for method_index = 1:height(methods)
        row_index = row_index + 1;
        selected = trials.scenario_id == scenario_ids(scenario_index) & ...
            trials.method_id == methods.method_id(method_index);
        reference = trials.scenario_id == scenario_ids(scenario_index) & ...
            trials.method_id == strongest_fixed_method;
        rows{row_index} = summary_row_local(trials(selected, :), ...
            trials(reference, :), methods(method_index, :));
    end
end
scenario_summary = struct2table(vertcat(rows{:}));

aggregate_rows = cell(height(methods), 1);
for method_index = 1:height(methods)
    selected = trials.method_id == methods.method_id(method_index);
    reference = trials.method_id == strongest_fixed_method;
    row = summary_row_local(trials(selected, :), trials(reference, :), ...
        methods(method_index, :));
    full_reference = trials.method_id == "FULL_PARENT_5X5";
    [full_difference, full_low, full_high] = paired_interval_local( ...
        double(trials.oracle_k_success(selected)) - ...
        double(trials.oracle_k_success(full_reference)));
    row.paired_success_difference_vs_full_parent = full_difference;
    row.paired_success_difference_vs_full_parent_95_low = full_low;
    row.paired_success_difference_vs_full_parent_95_high = full_high;
    aggregate_rows{method_index} = row;
end
aggregate = struct2table(vertcat(aggregate_rows{:}));
end

function row = summary_row_local(selected, reference, method)
n = height(selected);
success_rate = mean(selected.oracle_k_success);
[wilson_low, wilson_high] = wilson_local(nnz(selected.oracle_k_success), n);
[success_difference, success_low, success_high] = paired_interval_local( ...
    double(selected.oracle_k_success) - double(reference.oracle_k_success));
[error_difference, error_low, error_high] = paired_interval_local( ...
    selected.unconditional_penalized_error - ...
    reference.unconditional_penalized_error);
[wrong_difference, wrong_low, wrong_high] = paired_interval_local( ...
    double(selected.wrong_local_peak) - double(reference.wrong_local_peak));
row = struct('data_split', join(unique(selected.data_split), ';'), ...
    'scenario_id', join(unique(selected.scenario_id), ';'), ...
    'method_id', method.method_id, 'method_class', method.method_class, ...
    'subset_id', method.subset_id, 'n_trials', n, ...
    'oracle_k_success_rate', success_rate, 'Wilson_95_low', wilson_low, ...
    'Wilson_95_high', wilson_high, ...
    'azimuth_rmse_all_trials', sqrt(mean(selected.azimuth_error_deg .^ 2)), ...
    'elevation_rmse_all_trials', sqrt(mean(selected.elevation_error_deg .^ 2)), ...
    'pair_rmse_all_trials', sqrt(mean(selected.pair_error_deg .^ 2)), ...
    'unconditional_penalized_error', ...
    mean(selected.unconditional_penalized_error), ...
    'wrong_local_peak_rate', mean(selected.wrong_local_peak), ...
    'convergence_rate', mean(selected.converged), ...
    'normalized_score_gap_to_full_parent', ...
    mean(selected.normalized_score_gap_to_full_parent, 'omitnan'), ...
    'paired_success_difference', success_difference, ...
    'paired_success_difference_95_low', success_low, ...
    'paired_success_difference_95_high', success_high, ...
    'paired_error_difference', error_difference, ...
    'paired_error_difference_95_low', error_low, ...
    'paired_error_difference_95_high', error_high, ...
    'wrong_peak_increase', wrong_difference, ...
    'wrong_peak_increase_95_low', wrong_low, ...
    'wrong_peak_increase_95_high', wrong_high, ...
    'MAC_total', method.MAC_total, 'B_out', method.B_out, ...
    'output_bytes', 16 * method.B_out, ...
    'runtime', sum(selected.runtime_sec), ...
    'score_calls', sum(selected.score_calls), ...
    'SVD_calls', sum(selected.SVD_calls), ...
    'iterations', sum(selected.iterations), ...
    'multi_start_count', max(selected.multi_start_count), ...
    'paired_reference_method', string(reference.method_id(1)));
end

function [mean_value, low, high] = paired_interval_local(values)
values = values(isfinite(values));
mean_value = mean(values);
if numel(values) <= 1
    low = mean_value;
    high = mean_value;
else
    half_width = 1.95996398454005 * std(values, 0) / sqrt(numel(values));
    low = mean_value - half_width;
    high = mean_value + half_width;
end
end

function [low, high] = wilson_local(success_count, n)
z = 1.95996398454005;
p = success_count / n;
denominator = 1 + z ^ 2 / n;
center = (p + z ^ 2 / (2 * n)) / denominator;
half_width = z * sqrt(p * (1 - p) / n + z ^ 2 / (4 * n ^ 2)) / denominator;
low = max(0, center - half_width);
high = min(1, center + half_width);
end
