function [contract, digest] = stage8_r1_solver_contract(opts)
%STAGE8_R1_SOLVER_CONTRACT Return and enforce the fixed continuous solver.

contract = struct( ...
    'max_sweeps', 8, ...
    'coordinate_radius_deg', 0.20, ...
    'scan_point_count', 9, ...
    'fminbnd_TolX_deg', 1e-4, ...
    'fminbnd_MaxFunEvals', 80, ...
    'relative_score_tolerance', 1e-9, ...
    'angle_update_tolerance_deg', 1e-3, ...
    'rank_multiplier', 1, ...
    'update_order', 'TARGET_THEN_AZIMUTH_THEN_ELEVATION', ...
    'canonical_order', 'ELEVATION_THEN_AZIMUTH', ...
    'selection_rule', ...
    'MAXIMUM_CONCENTRATED_LOG_LIKELIHOOD_AMONG_VALID_STARTS', ...
    'phase_factor', 1);
if nargin >= 1 && ~isempty(opts)
    if ~(isstruct(opts) && isscalar(opts))
        error('stage8_r1_solver_contract:Options', ...
            'opts must be a scalar struct.');
    end
    unknown = setdiff(fieldnames(opts), fieldnames(contract));
    if ~isempty(unknown)
        error('stage8_r1_solver_contract:UnknownOption', ...
            'Unknown solver option: %s.', unknown{1});
    end
    names = fieldnames(opts);
    for index = 1:numel(names)
        name = names{index};
        if ~isequal(opts.(name), contract.(name))
            error('stage8_r1_solver_contract:FrozenValue', ...
                'Solver option %s differs from the decisive protocol.', name);
        end
    end
end
digest = stage8_stable_hash( ...
    'STAGE8_R1_CONTINUOUS_FULL_SEQUENTIAL_DML_SOLVER_V1', contract);
end
