function output = stage8_r1_merge_analyze(repo_dir, runtime_root, output_root)
%STAGE8_R1_MERGE_ANALYZE Merge 24 checkpoints and write four final outputs.

repo_dir = char(string(repo_dir));
runtime_root = char(string(runtime_root));
output_root = char(string(output_root));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
protocol = jsondecode(fileread(fullfile(runtime_root, 'protocol.json')));
if ~strcmp(string(protocol.registry_kind), "FORMAL") || ...
        double(protocol.element_trial_count) ~= 24 || ...
        double(protocol.row_count) ~= 72 || ...
        logical(protocol.stage8_2_executed_flag)
    error('stage8_r1_merge_analyze:Protocol', ...
        'Finalize requires the complete formal non-Stage8.2 runtime.');
end
status = stage8_r1_build_status(repo_dir, runtime_root);
if ~(status.completed_element_trials == 24 && status.completed_rows == 72 && ...
        status.valid_checkpoint_count == 24 && ...
        status.invalid_checkpoint_count == 0 && ...
        status.tmp_checkpoint_count == 0 && ...
        status.current_trial_lock_count == 0 && ...
        status.active_worker_count == 0 && isempty(status.last_error) && ...
        ~status.stage8_2_executed_flag)
    error('stage8_r1_merge_analyze:Runtime', ...
        'Runtime is incomplete or unsafe to finalize.');
end
context = stage8_r1_context(repo_dir, true);
registry = context.registry;
cells = cell(height(registry), 1);
hashes = strings(height(registry), 1);
for index = 1:height(registry)
    path_now = fullfile(runtime_root, 'checkpoints', ...
        [char(registry.trial_id(index)), '.mat']);
    stage8_r1_validate_checkpoint(path_now, protocol, registry(index, :));
    loaded = load(path_now, 'checkpoint', '-mat');
    cells{index} = loaded.checkpoint.rows;
    hashes(index) = string(loaded.checkpoint.scientific_content_hash);
end
trials = sortrows(vertcat(cells{:}), {'global_trial_index','method_id'});
validate_trial_table_local(trials, registry);
[summary, comparison, decision] = analyze_local(trials, protocol);
if ~isfolder(output_root), mkdir(output_root); end
trial_path = fullfile(output_root, ...
    '24_stage8_r1_continuous_refinement_decisive_trials.csv');
summary_path = fullfile(output_root, ...
    '24_stage8_r1_continuous_refinement_decisive_summary.csv');
comparison_path = fullfile(output_root, ...
    '24_stage8_r1_continuous_refinement_method_comparison.csv');
report_path = fullfile(output_root, ...
    '24_stage8_r1_continuous_refinement_decisive_experiment.md');
writetable(trials, trial_path);
writetable(summary, summary_path);
writetable(comparison, comparison_path);
write_report_local(report_path, protocol, status, summary, comparison, ...
    decision, hashes);
output = struct('trials', trials, 'summary', summary, ...
    'comparison', comparison, 'decision', decision, 'status', status, ...
    'trial_path', trial_path, 'summary_path', summary_path, ...
    'comparison_path', comparison_path, 'report_path', report_path);
clear path_cleanup
end

function validate_trial_table_local(trials, registry)
methods = ["M0_FIXED_GRID_REGISTERED_STAGE8"; ...
    "M1_CONVENTIONAL_CONTINUOUS_FULL_SEQUENTIAL_DML"; ...
    "M2_GROUPED_CONDITIONAL_CONTINUOUS_FULL_SEQUENTIAL_DML"];
if height(trials) ~= 72 || ...
        numel(unique(string(trials.trial_id))) ~= 24 || ...
        numel(unique(string(trials.trial_id) + "|" + ...
        string(trials.method_id))) ~= 72 || ...
        ~isequal(sort(unique(string(trials.method_id))), sort(methods)) || ...
        nnz(trials.truth_K == 1) ~= 48 || nnz(trials.truth_K == 2) ~= 24 || ...
        any(trials.truth_used_in_initialization_flag) || ...
        any(trials.truth_used_in_fit_flag) || ...
        any(trials.truth_used_in_lrt_flag) || ...
        any(trials.monotonicity_violation_count ~= 0) || ...
        any(~trials.shared_element_data_flag) || ...
        any(trials.phase_factor ~= 1) || height(registry) ~= 24
    error('stage8_r1_merge_analyze:Trials', ...
        'Merged trials violate completeness or truth-isolation contracts.');
end
for index = 1:height(registry)
    subset = trials(trials.trial_id == registry.trial_id(index), :);
    if height(subset) ~= 3 || numel(unique(subset.element_trial_hash)) ~= 1
        error('stage8_r1_merge_analyze:Pairing', ...
            'One trial does not contain three paired method rows.');
    end
end
end

function [summary, comparison, decision] = analyze_local(trials, protocol)
method_ids = ["M0_FIXED_GRID_REGISTERED_STAGE8"; ...
    "M1_CONVENTIONAL_CONTINUOUS_FULL_SEQUENTIAL_DML"; ...
    "M2_GROUPED_CONDITIONAL_CONTINUOUS_FULL_SEQUENTIAL_DML"];
rows = cell(numel(method_ids), 1);
analysis = repmat(struct('method_id', "", 'valid_k1_both', 0, ...
    'valid_k2_both', 0, 'auc', NaN, 'best_tpr', NaN, 'best_fpr', NaN, ...
    'best_threshold', NaN, 'offgrid_closure_median', NaN, ...
    'offgrid_closure_count', 0, 'offgrid_closure_half_count', 0, ...
    'k2_median_rmse', NaN, 'k1_median_lambda', NaN, ...
    'k1_offgrid_median_lambda', NaN, 'k2_median_lambda', NaN, ...
    'mean_score_calls', NaN, 'mean_svd_calls', NaN, ...
    'median_runtime_sec', NaN), numel(method_ids), 1);
for index = 1:numel(method_ids)
    method = trials(trials.method_id == method_ids(index), :);
    k1 = method(method.truth_K == 1, :);
    k2 = method(method.truth_K == 2, :);
    [auc, op] = auc_and_operating_local(k1.lambda_12, k2.lambda_12);
    [closure_median, closure_count, closure_half_count] = ...
        closure_local(trials, method_ids(index));
    valid_k1_both = nnz(k1.fit1_valid & k1.fit2_valid);
    valid_k2_both = nnz(k2.fit1_valid & k2.fit2_valid);
    k2_rmse = k2.known_K_joint_rmse_deg(k2.fit2_valid);
    analysis(index) = struct('method_id', method_ids(index), ...
        'valid_k1_both', valid_k1_both, 'valid_k2_both', valid_k2_both, ...
        'auc', auc, 'best_tpr', op.best_tpr, 'best_fpr', op.best_fpr, ...
        'best_threshold', op.best_threshold, ...
        'offgrid_closure_median', closure_median, ...
        'offgrid_closure_count', closure_count, ...
        'offgrid_closure_half_count', closure_half_count, ...
        'k2_median_rmse', median_or_nan_local(k2_rmse), ...
        'k1_median_lambda', median_or_nan_local(k1.lambda_12), ...
        'k1_offgrid_median_lambda', ...
        median_or_nan_local(k1.lambda_12(k1.support_or_difficulty == ...
        "INSIDE_OFF_GRID")), ...
        'k2_median_lambda', median_or_nan_local(k2.lambda_12), ...
        'mean_score_calls', mean(method.score_call_count), ...
        'mean_svd_calls', mean(method.svd_call_count), ...
        'median_runtime_sec', median(method.runtime_sec));
    rows{index} = struct('method_id', method_ids(index), ...
        'K1_fit_pair_valid_count', valid_k1_both, ...
        'K2_fit_pair_valid_count', valid_k2_both, ...
        'empirical_auc', auc, ...
        'best_K2_TPR_at_K1_FPR_le_0_125', op.best_tpr, ...
        'best_K1_FPR', op.best_fpr, ...
        'diagnostic_operating_threshold', op.best_threshold, ...
        'offgrid_pseudogap_closure_median', closure_median, ...
        'offgrid_pseudogap_closure_count', closure_count, ...
        'offgrid_pseudogap_closure_ge_0_50_count', closure_half_count, ...
        'K2_median_known_K_joint_rmse_deg', ...
        median_or_nan_local(k2_rmse), ...
        'K1_median_lambda_12', median_or_nan_local(k1.lambda_12), ...
        'K1_offgrid_median_lambda_12', ...
        median_or_nan_local(k1.lambda_12(k1.support_or_difficulty == ...
        "INSIDE_OFF_GRID")), ...
        'K2_median_lambda_12', median_or_nan_local(k2.lambda_12), ...
        'mean_score_call_count', mean(method.score_call_count), ...
        'mean_svd_call_count', mean(method.svd_call_count), ...
        'median_runtime_sec', median(method.runtime_sec));
end
summary = struct2table(vertcat(rows{:}));
comparison = comparison_local(trials);
m1 = analysis(2);
m2 = analysis(3);
m1_recovered = recovered_local(m1);
m2_recovered = recovered_local(m2);
if ~m1_recovered && ~m2_recovered
    conclusion = "STAGE8_R1_CONTINUOUS_MODEL_ORDER_NOT_RECOVERED";
elseif m2_recovered && ~m1_recovered
    conclusion = "STAGE8_R1_CONTINUOUS_MODEL_ORDER_RECOVERED_GROUPED_RETAIN";
elseif m1_recovered && ~m2_recovered
    conclusion = ...
        "STAGE8_R1_CONTINUOUS_MODEL_ORDER_RECOVERED_GROUPED_PRUNE_CANDIDATE";
else
    wins = nnz(comparison.outcome == "M2_WIN");
    losses = nnz(comparison.outcome == "M2_LOSS");
    median_m1 = median_or_nan_local(comparison.M1_known_K_joint_rmse_deg);
    median_m2 = median_or_nan_local(comparison.M2_known_K_joint_rmse_deg);
    if wins >= 5 && median_m2 <= 0.90 * median_m1
        conclusion = ...
            "STAGE8_R1_CONTINUOUS_MODEL_ORDER_RECOVERED_GROUPED_RETAIN";
    elseif losses >= 6 && median_m2 >= 1.10 * median_m1
        conclusion = ...
            "STAGE8_R1_CONTINUOUS_MODEL_ORDER_RECOVERED_GROUPED_PRUNE_CANDIDATE";
    else
        conclusion = ...
            "STAGE8_R1_CONTINUOUS_MODEL_ORDER_RECOVERED_GROUPED_OPTIONAL";
    end
end
decision = struct('M1_model_order_recovered', m1_recovered, ...
    'M2_model_order_recovered', m2_recovered, ...
    'final_conclusion', conclusion, ...
    'formal_6000_trial_status', protocol.formal_6000_trial_status, ...
    'stage8_2_executed_flag', false);
end

function [auc, op] = auc_and_operating_local(k1_lambda, k2_lambda)
k1 = k1_lambda(isfinite(k1_lambda));
k2 = k2_lambda(isfinite(k2_lambda));
if isempty(k1) || isempty(k2)
    auc = NaN;
    op = struct('best_tpr', NaN, 'best_fpr', NaN, 'best_threshold', NaN);
    return;
end
pair = k2(:) > k1(:).';
equal = k2(:) == k1(:).';
auc = mean(pair(:) + 0.5 * equal(:));
candidates = [-Inf; unique([k1;k2]); Inf];
best = struct('best_tpr', -Inf, 'best_fpr', Inf, 'best_threshold', -Inf);
for index = 1:numel(candidates)
    threshold = candidates(index);
    fpr = mean(k1 > threshold);
    tpr = mean(k2 > threshold);
    if fpr <= 0.125 && (tpr > best.best_tpr || ...
            (tpr == best.best_tpr && (fpr < best.best_fpr || ...
            (fpr == best.best_fpr && threshold > best.best_threshold))))
        best = struct('best_tpr', tpr, 'best_fpr', fpr, ...
            'best_threshold', threshold);
    end
end
op = best;
end

function [median_closure, count, half_count] = closure_local(trials, method_id)
offgrid = unique(trials.trial_id(trials.truth_K == 1 & ...
    trials.support_or_difficulty == "INSIDE_OFF_GRID"));
closure = NaN(numel(offgrid), 1);
for index = 1:numel(offgrid)
    m0 = trials(trials.trial_id == offgrid(index) & ...
        trials.method_id == "M0_FIXED_GRID_REGISTERED_STAGE8", :);
    method = trials(trials.trial_id == offgrid(index) & ...
        trials.method_id == method_id, :);
    if isempty(m0) || isempty(method) || ~isfinite(m0.rss_gap) || ...
            ~isfinite(method.rss_gap) || m0.rss_gap <= ...
            64 * eps(max(1, abs(m0.rss_gap)))
        continue;
    end
    closure(index) = 1 - max(method.rss_gap, 0) / max(m0.rss_gap, eps);
end
valid = isfinite(closure);
median_closure = median_or_nan_local(closure(valid));
count = nnz(valid);
half_count = nnz(closure(valid) >= 0.50);
end

function value = recovered_local(metrics)
value = metrics.valid_k1_both == 16 && metrics.valid_k2_both >= 7 && ...
    isfinite(metrics.auc) && metrics.auc >= 0.80 && ...
    isfinite(metrics.best_tpr) && metrics.best_tpr >= 0.75 && ...
    metrics.offgrid_closure_count == 8 && ...
    isfinite(metrics.offgrid_closure_median) && ...
    metrics.offgrid_closure_median >= 0.70 && ...
    metrics.offgrid_closure_half_count >= 6;
end

function comparison = comparison_local(trials)
k2_ids = unique(trials.trial_id(trials.truth_K == 2));
rows = cell(numel(k2_ids), 1);
for index = 1:numel(k2_ids)
    m1 = trials(trials.trial_id == k2_ids(index) & ...
        startsWith(trials.method_id, "M1_"), :);
    m2 = trials(trials.trial_id == k2_ids(index) & ...
        startsWith(trials.method_id, "M2_"), :);
    rmse1 = m1.known_K_joint_rmse_deg;
    rmse2 = m2.known_K_joint_rmse_deg;
    if ~isfinite(rmse1) || ~isfinite(rmse2)
        outcome = "INVALID_COMPARISON";
    elseif rmse2 < rmse1 - 1e-6
        outcome = "M2_WIN";
    elseif abs(rmse2 - rmse1) <= 1e-6
        outcome = "TIE";
    else
        outcome = "M2_LOSS";
    end
    rows{index} = struct('trial_id', k2_ids(index), ...
        'M1_fit_valid', m1.fit2_valid, 'M2_fit_valid', m2.fit2_valid, ...
        'M1_known_K_joint_rmse_deg', rmse1, ...
        'M2_known_K_joint_rmse_deg', rmse2, 'outcome', outcome, ...
        'M1_score_call_count', m1.score_call_count, ...
        'M2_score_call_count', m2.score_call_count, ...
        'M1_svd_call_count', m1.svd_call_count, ...
        'M2_svd_call_count', m2.svd_call_count, ...
        'M1_runtime_sec', m1.runtime_sec, 'M2_runtime_sec', m2.runtime_sec);
end
comparison = struct2table(vertcat(rows{:}));
end

function value = median_or_nan_local(values)
values = values(isfinite(values));
if isempty(values), value = NaN; else, value = median(values); end
end

function write_report_local(path_now, protocol, ~, summary, comparison, ...
    decision, hashes)
fid = fopen(path_now, 'w', 'n', 'UTF-8');
if fid < 0, error('stage8_r1_merge_analyze:Report', 'Cannot write report.'); end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# Stage8 R1 Continuous Refinement Decisive Experiment\n\n');
fprintf(fid, 'DIAGNOSTIC_DECISIVE_EXPERIMENT_ONLY\n\n');
fprintf(fid, 'NO_FORMAL_THRESHOLD\n\n');
fprintf(fid, 'NO_STAGE8_1_VALIDATION_PASS\n\n');
fprintf(fid, 'NO_STAGE8_2_AUTHORIZATION\n\n');
fprintf(fid, 'Branch/HEAD: %s / %s\n\n', ...
    protocol.repo_dir, protocol.protocol_runner_commit);
fprintf(fid, 'Audit anchor: %s\n\n', protocol.audit_anchor_commit);
fprintf(fid, 'Protocol source hash: %s\n\n', protocol.protocol_document_sha256);
fprintf(fid, 'Worker mode: %s (%d)\n\n', ...
    protocol.selected_execution_mode, protocol.selected_worker_count);
fprintf(fid, 'Trials: 24/24; K1: 16/16; K2: 8/8; method rows: 72/72.\n\n');
fprintf(fid, 'R0/R1/R2/R3 are recorded in runtime gate evidence.\n\n');
fprintf(fid, '| Method | K1 valid | K2 valid | AUC | TPR at FPR<=0.125 | Off-grid closure | K2 median RMSE |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|\n');
for index = 1:height(summary)
    fprintf(fid, '| %s | %d | %d | %.6g | %.6g | %.6g | %.6g |\n', ...
        summary.method_id(index), summary.K1_fit_pair_valid_count(index), ...
        summary.K2_fit_pair_valid_count(index), summary.empirical_auc(index), ...
        summary.best_K2_TPR_at_K1_FPR_le_0_125(index), ...
        summary.offgrid_pseudogap_closure_median(index), ...
        summary.K2_median_known_K_joint_rmse_deg(index));
end
fprintf(fid, '\nM2 vs M1: wins=%d, ties=%d, losses=%d.\n\n', ...
    nnz(comparison.outcome == "M2_WIN"), nnz(comparison.outcome == "TIE"), ...
    nnz(comparison.outcome == "M2_LOSS"));
fprintf(fid, 'Scientific checkpoint hashes: %d valid.\n\n', numel(unique(hashes)));
fprintf(fid, 'Final conclusion: %s\n\n', decision.final_conclusion);
fprintf(fid, 'Formal 6000-trial status: %s\n\n', ...
    decision.formal_6000_trial_status);
fprintf(fid, 'Stage8.2 executed: false.\n');
clear cleanup
end
