function audit = stage8_r1_validate_checkpoint(path_now, protocol, spec)
%STAGE8_R1_VALIDATE_CHECKPOINT Validate one immutable element trial.

if ischar(protocol) || (isstring(protocol) && isscalar(protocol))
    protocol = jsondecode(fileread(char(protocol)));
end
loaded = load(char(string(path_now)), 'checkpoint', '-mat');
if ~isfield(loaded, 'checkpoint') || ...
        ~(isstruct(loaded.checkpoint) && isscalar(loaded.checkpoint))
    error('stage8_r1_validate_checkpoint:Payload', ...
        'Checkpoint must contain one scalar checkpoint struct.');
end
checkpoint = loaded.checkpoint;
required = {'protocol_version','checkpoint_contract_version', ...
    'trial_id','global_trial_index','trial_type','rows', ...
    'element_trial_hash','solver_contract_hash', ...
    'protocol_source_tree_hash','completion_status', ...
    'scientific_content_hash','runtime_sec','worker_id','pid', ...
    'attempt_id','created_utc'};
if ~all(isfield(checkpoint, required))
    error('stage8_r1_validate_checkpoint:Contract', ...
        'Checkpoint is missing required fields.');
end
identity_fields = {'protocol_version','checkpoint_contract_version', ...
    'solver_contract_hash','protocol_source_tree_hash'};
for index = 1:numel(identity_fields)
    field = identity_fields{index};
    if ~strcmp(string(checkpoint.(field)), string(protocol.(field)))
        error('stage8_r1_validate_checkpoint:Identity', ...
            'Checkpoint field %s differs from protocol.', field);
    end
end
if ~(istable(spec) && height(spec) == 1) || ...
        string(checkpoint.trial_id) ~= string(spec.trial_id) || ...
        double(checkpoint.global_trial_index) ~= ...
        double(spec.global_trial_index) || ...
        string(checkpoint.trial_type) ~= string(spec.trial_type)
    error('stage8_r1_validate_checkpoint:Registry', ...
        'Checkpoint differs from its registry row.');
end
rows = checkpoint.rows;
required_rows = fieldnames(stage8_r1_row_template());
method_ids = ["M0_FIXED_GRID_REGISTERED_STAGE8"; ...
    "M1_CONVENTIONAL_CONTINUOUS_FULL_SEQUENTIAL_DML"; ...
    "M2_GROUPED_CONDITIONAL_CONTINUOUS_FULL_SEQUENTIAL_DML"];
if ~(istable(rows) && height(rows) == 3) || ...
        ~all(ismember(required_rows, rows.Properties.VariableNames)) || ...
        ~isequal(sort(string(rows.method_id)), sort(method_ids)) || ...
        any(string(rows.trial_id) ~= string(spec.trial_id)) || ...
        any(double(rows.global_trial_index) ~= spec.global_trial_index) || ...
        any(string(rows.element_trial_hash) ~= ...
        string(checkpoint.element_trial_hash)) || ...
        any(rows.truth_used_in_initialization_flag) || ...
        any(rows.truth_used_in_fit_flag) || ...
        any(rows.truth_used_in_lrt_flag) || ...
        ~all(rows.shared_element_data_flag) || ...
        any(rows.phase_factor ~= 1) || ...
        any(rows.monotonicity_violation_count ~= 0)
    error('stage8_r1_validate_checkpoint:Rows', ...
        'Checkpoint method rows violate the scientific contract.');
end
invalid_lrt = ~(rows.fit1_valid & rows.fit2_valid);
if any(isfinite(rows.lambda_12(invalid_lrt))) || ...
        ~strcmp(string(checkpoint.completion_status), "COMPLETE_PASS")
    error('stage8_r1_validate_checkpoint:LRT', ...
        'Invalid fits entered LRT output or completion status changed.');
end
computed = stage8_r1_checkpoint_hash(checkpoint);
if ~strcmp(string(computed), string(checkpoint.scientific_content_hash))
    error('stage8_r1_validate_checkpoint:ScientificHash', ...
        'Checkpoint scientific hash is invalid.');
end
audit = struct('valid', true, 'trial_id', char(string(checkpoint.trial_id)), ...
    'global_trial_index', double(checkpoint.global_trial_index), ...
    'trial_type', char(string(checkpoint.trial_type)), ...
    'row_count', height(rows), 'runtime_sec', double(checkpoint.runtime_sec), ...
    'scientific_content_hash', char(string(computed)), ...
    'created_utc', char(string(checkpoint.created_utc)));
end
