function context = stage8_r1_context(repo_dir, require_formal_runtime)
%STAGE8_R1_CONTEXT Load frozen Stage8 models without loading old thresholds.

if nargin < 2, require_formal_runtime = true; end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
tool_dir = fileparts(mfilename('fullpath'));
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(tool_dir);
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
plan = build_stage8_locked_plan(repo_dir, sim_cfg(), ...
    struct('require_formal_runtime', logical(require_formal_runtime)));
constants = stage8_r1_constants();
actual = [string(plan.identity.stage8_stable_code_identity_hash), ...
    string(plan.stage8_plan_hash), ...
    string(plan.stage8_calibration_plan_hash), ...
    string(plan.stage8_validation_plan_hash), ...
    string(plan.measurement_model_registry.registry_hash)];
expected = [string(constants.stage8_stable_code_identity_hash), ...
    string(constants.stage8_plan_hash), ...
    string(constants.stage8_calibration_plan_hash), ...
    string(constants.stage8_validation_plan_hash), ...
    string(constants.measurement_registry_hash)];
if ~isequal(actual, expected)
    error('stage8_r1_context:FrozenIdentity', ...
        'One or more frozen Stage8 identities changed.');
end
[solver_contract, solver_contract_hash] = stage8_r1_solver_contract(struct());
context = struct('repo_dir', repo_dir, 'step', step, 'plan', plan, ...
    'constants', constants, 'solver_contract', solver_contract, ...
    'solver_contract_hash', solver_contract_hash, ...
    'stage5_locked', build_stage8_stage5_locked_config());
context.registry = stage8_r1_build_registry(context, 'FORMAL');
clear path_cleanup
end
