function digest = stage8_r1_checkpoint_hash(checkpoint)
%STAGE8_R1_CHECKPOINT_HASH Hash runtime-independent scientific content.

rows = sortrows(checkpoint.rows, 'method_id');
runtime_fields = {'runtime_sec','shared_initialization_runtime_sec', ...
    'initialization_runtime_sec','refinement_runtime_sec'};
for index = 1:numel(runtime_fields)
    name = runtime_fields{index};
    if ismember(name, rows.Properties.VariableNames), rows.(name)(:) = 0; end
end
digest = stage8_stable_hash( ...
    'STAGE8_R1_ELEMENT_TRIAL_CHECKPOINT_V1', ...
    char(string(checkpoint.protocol_version)), ...
    char(string(checkpoint.checkpoint_contract_version)), ...
    char(string(checkpoint.trial_id)), ...
    double(checkpoint.global_trial_index), ...
    char(string(checkpoint.trial_type)), rows, ...
    char(string(checkpoint.element_trial_hash)), ...
    char(string(checkpoint.solver_contract_hash)), ...
    char(string(checkpoint.protocol_source_tree_hash)), ...
    char(string(checkpoint.completion_status)));
end
