function [fit, debug] = stage8_r1_fit_continuous_method( ...
    full_data, K, starts, local_domain, model, opts)
%STAGE8_R1_FIT_CONTINUOUS_METHOD Refine and select one fixed start set.

if nargin < 6, opts = struct(); end
[~, solver_hash] = stage8_r1_solver_contract(opts);
if ~(isstruct(starts) && isvector(starts) && ~isempty(starts))
    error('stage8_r1_fit_continuous_method:Starts', ...
        'starts must be a nonempty struct vector.');
end
clock = tic;
fit = empty_fit_local(K, full_data, local_domain, model, solver_hash);
results = repmat(empty_start_result_local(K), numel(starts), 1);
for index = 1:numel(starts)
    results(index).initialization_id = char(string(starts(index).initialization_id));
    results(index).initial_angles_deg = starts(index).angles_deg;
    results(index).initialization_available_flag = ...
        logical(starts(index).available_flag);
    results(index).initialization_status = ...
        char(string(starts(index).initialization_status));
    if ~results(index).initialization_available_flag || ...
            ~all(isfinite(results(index).initial_angles_deg(:)))
        continue;
    end
    [estimate, history, refinement_debug] = ...
        stage8_r1_refine_continuous_dml(full_data, ...
        results(index).initial_angles_deg, local_domain, model, opts);
    results(index).angles_hat_deg = estimate.angles_hat_deg;
    results(index).continuous_solver_status = estimate.status;
    results(index).initial_score = estimate.initial_score;
    results(index).final_score = estimate.final_score;
    results(index).estimate_returned_flag = estimate.estimate_returned_flag;
    results(index).converged_flag = estimate.converged_flag;
    results(index).fit_status = estimate.status;
    results(index).score_call_count = estimate.score_call_count;
    results(index).svd_call_count = estimate.svd_call_count;
    results(index).monotonicity_violation_count = ...
        estimate.monotonicity_violation_count;
    results(index).runtime_sec = estimate.runtime_sec;
    results(index).history = history;
    results(index).refinement_debug = refinement_debug;
    if ~estimate.fit_valid_for_lrt, continue; end
    [G_hat, ~, manifold_info] = build_full_sequential_local_manifold( ...
        estimate.angles_hat_deg, model, struct('rank_multiplier', 1));
    [score, rss, sigma2_hat, loglik, effective_rank] = ...
        concentrated_dml_rss(full_data.Zseq_white, G_hat, struct( ...
        'requested_rank', K, 'rank_multiplier', 1, ...
        'compute_projector_checks', false));
    [S_hat, solve_info] = solve_fitted_source_coefficients( ...
        G_hat, full_data.Zseq_white, struct('rank_multiplier', 1));
    results(index).score_call_count = results(index).score_call_count + 1;
    results(index).svd_call_count = results(index).svd_call_count + ...
        manifold_info.num_svd + 1 + solve_info.num_svd;
    results(index).score = score;
    results(index).rss = rss;
    results(index).sigma2_hat = sigma2_hat;
    results(index).loglik_concentrated = loglik;
    results(index).effective_rank = min(effective_rank, ...
        solve_info.effective_rank);
    results(index).G_hat = G_hat;
    results(index).S_hat = S_hat;
    candidate_fit = result_to_fit_local(results(index), fit);
    [valid, validity] = validate_stage8_fit_for_lrt( ...
        candidate_fit, K, identity_local(fit));
    results(index).valid_for_selection_flag = valid;
    results(index).validity_status = validity.status;
    if valid
        results(index).fit_status = 'CONTINUOUS_REFINEMENT_CONVERGED';
    end
end
valid_indices = find([results.valid_for_selection_flag]);
fit.all_start_results = results;
fit.num_start = numel(starts);
fit.valid_start_count = numel(valid_indices);
fit.num_score_eval = sum([results.score_call_count]);
fit.num_svd = sum([results.svd_call_count]);
fit.runtime = toc(clock);
fit.monotonicity_violation_count = ...
    sum([results.monotonicity_violation_count]);
if isempty(valid_indices)
    fit.fit_status = 'SEARCH_NOT_CONVERGED';
    debug = struct('selected_start_index', 0, ...
        'selected_start_id', '', 'valid_start_count', 0, ...
        'selection_rule', ...
        'MAXIMUM_CONCENTRATED_LOG_LIKELIHOOD_AMONG_VALID_STARTS');
    return;
end
loglik = [results(valid_indices).loglik_concentrated];
maximum = max(loglik);
tolerance = 64 * eps(max(1, abs(maximum)));
selected_index = valid_indices(find(loglik >= maximum - tolerance, 1, 'first'));
selected = results(selected_index);
fit = result_to_fit_local(selected, fit);
fit.all_start_results = results;
fit.num_start = numel(starts);
fit.valid_start_count = numel(valid_indices);
fit.num_score_eval = sum([results.score_call_count]);
fit.num_svd = sum([results.svd_call_count]);
fit.runtime = toc(clock);
fit.initialization_id = selected.initialization_id;
fit.selected_initial_angles_deg = selected.initial_angles_deg;
debug = struct('selected_start_index', selected_index, ...
    'selected_start_id', selected.initialization_id, ...
    'valid_start_count', numel(valid_indices), ...
    'selection_tolerance', tolerance, ...
    'selection_rule', ...
    'MAXIMUM_CONCENTRATED_LOG_LIKELIHOOD_AMONG_VALID_STARTS');
end

function fit = empty_fit_local(K, data, domain, model, solver_hash)
r_C = size(data.Zseq_white, 1);
L = size(data.Zseq_white, 2);
fit = struct('K', K, 'angles_hat_deg', NaN(K, 2), ...
    'G_hat', complex(NaN(r_C, K)), 'S_hat', complex(NaN(K, L)), ...
    'score', NaN, 'rss', NaN, 'sigma2_hat', NaN, ...
    'loglik_concentrated', NaN, 'effective_rank', 0, ...
    'fit_status', 'SEARCH_NOT_CONVERGED', ...
    'estimate_returned_flag', false, 'converged_flag', false, ...
    'initialization_id', '', 'selected_initial_angles_deg', NaN(K, 2), ...
    'all_start_results', struct([]), 'num_start', 0, ...
    'valid_start_count', 0, 'num_score_eval', 0, 'num_svd', 0, ...
    'runtime', 0, 'monotonicity_violation_count', 0, ...
    'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'local_domain_hash', domain.domain_hash, ...
    'solver_contract_hash', solver_hash, ...
    'observation_hash', stage8_stable_hash(data.Zseq_white), ...
    'effective_whitening_dimension', r_C, 'snapshot_count', L, ...
    'n_complex_observations', r_C * L, 'phase_factor', 1);
end

function result = empty_start_result_local(K)
result = struct('initialization_id', '', ...
    'initialization_available_flag', false, ...
    'initialization_status', 'INITIALIZATION_NOT_BUILT', ...
    'initial_angles_deg', NaN(K, 2), 'angles_hat_deg', NaN(K, 2), ...
    'score', NaN, 'rss', NaN, 'sigma2_hat', NaN, ...
    'loglik_concentrated', -Inf, 'effective_rank', 0, ...
    'G_hat', complex(NaN(0, K)), 'S_hat', complex(NaN(K, 0)), ...
    'fit_status', 'INITIALIZATION_FAILED', ...
    'continuous_solver_status', 'NOT_RUN', ...
    'initial_score', NaN, 'final_score', NaN, ...
    'estimate_returned_flag', false, 'converged_flag', false, ...
    'valid_for_selection_flag', false, ...
    'validity_status', 'INITIALIZATION_FAILED', ...
    'score_call_count', 0, 'svd_call_count', 0, ...
    'monotonicity_violation_count', 0, 'runtime_sec', 0, ...
    'history', table(), 'refinement_debug', struct());
end

function output = result_to_fit_local(result, base)
output = base;
names = {'angles_hat_deg','G_hat','S_hat','score','rss','sigma2_hat', ...
    'loglik_concentrated','effective_rank','fit_status', ...
    'estimate_returned_flag','converged_flag'};
for index = 1:numel(names), output.(names{index}) = result.(names{index}); end
output.initialization_id = result.initialization_id;
output.selected_initial_angles_deg = result.initial_angles_deg;
end

function value = identity_local(fit)
value = struct('fixed_measurement_hash', fit.fixed_measurement_hash, ...
    'local_domain_hash', fit.local_domain_hash, ...
    'solver_contract_hash', fit.solver_contract_hash, ...
    'observation_hash', fit.observation_hash);
end
