function digest = stage8_r1_source_hash(repo_dir)
%STAGE8_R1_SOURCE_HASH Hash committed experiment-tool blobs.

command = sprintf(['git -C "%s" ls-tree -r --full-tree HEAD -- ', ...
    'tools/stage8_r1_continuous_decisive ', ...
    'innovation-mining/stage8_execution_prompts/', ...
    '004_stage8_r1_continuous_refinement_decisive_v1.md'], ...
    char(string(repo_dir)));
[status, output] = system(command);
if status ~= 0 || isempty(strtrim(output))
    error('stage8_r1_source_hash:Git', ...
        'Unable to enumerate committed decisive-experiment blobs.');
end
output = strrep(output, [char(13), newline], newline);
output = strrep(output, char(13), newline);
digest = stage8_stable_hash( ...
    'STAGE8_R1_PROTOCOL_SOURCE_TREE_V1', output);
end
