function trial = stage8_r1_generate_trial(spec, context)
%STAGE8_R1_GENERATE_TRIAL Generate one shared element-domain observation.

if ~(istable(spec) && height(spec) == 1)
    error('stage8_r1_generate_trial:Spec', ...
        'spec must be one registry row.');
end
model = resolve_stage8_measurement_model( ...
    context.plan.measurement_model_registry, ...
    context.constants.primary_measurement_config_id, spec.noise_profile_id);
if spec.truth_K == 1
    truth = [spec.center_az_deg, spec.center_el_deg];
    [Y_element, simulation] = generate_stage8_k1_element_trial( ...
        truth, spec.snr_db, spec.L, model, spec.noise_seed);
    source = simulation.source_matrix;
    signal = simulation.signal_element;
    noise = simulation.noise_element;
else
    direction = [cosd(spec.direction_deg), sind(spec.direction_deg)];
    center = [spec.center_az_deg, spec.center_el_deg];
    truth = [center - spec.separation_deg * direction / 2; ...
        center + spec.separation_deg * direction / 2];
    manifold = build_stage8_element_manifold(truth, model);
    profile_id = sprintf('STAGE8_R1_%s', char(spec.trial_id));
    [source, source_info] = construct_deterministic_source_matrix( ...
        2, spec.L, 0, 0, 0, profile_id);
    unscaled = manifold.A * source;
    target_energy = 10 ^ (spec.snr_db / 10) * numel(unscaled);
    source = source * sqrt(target_energy / ...
        max(norm(unscaled, 'fro') ^ 2, realmin));
    signal = manifold.A * source;
    [noise, noise_info] = generate_stage8_element_noise( ...
        model, spec.L, 1, spec.noise_seed);
    Y_element = signal + noise;
    simulation = struct('source_info', source_info, ...
        'noise_debug', noise_info);
end
bounds = context.plan.local_domain.domain_bounds_deg;
if any(truth(:, 1) < bounds(1) | truth(:, 1) > bounds(2) | ...
        truth(:, 2) < bounds(3) | truth(:, 2) > bounds(4))
    error('stage8_r1_generate_trial:Domain', ...
        'Truth support lies outside the frozen local domain.');
end
element_trial_hash = stage8_stable_hash( ...
    'STAGE8_R1_ELEMENT_TRIAL_V1', char(spec.trial_id), Y_element, ...
    char(spec.noise_profile_id), double(spec.L), double(spec.snr_db), ...
    double(spec.noise_seed));
trial = struct('Y_element', Y_element, 'truth_angles_deg', truth, ...
    'model', model, 'source_matrix', source, 'signal_element', signal, ...
    'noise_element', noise, 'simulation', simulation, ...
    'element_trial_hash', element_trial_hash, ...
    'truth_used_in_initialization_flag', false, ...
    'truth_used_in_fit_flag', false, 'truth_used_in_lrt_flag', false);
end
