function result = stage8_r1_gate_r0(repo_dir, output_root, process_audit_path)
%STAGE8_R1_GATE_R0 Verify clean branch and frozen-artifact boundaries.

repo_dir = char(string(repo_dir));
output_root = char(string(output_root));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if ~isfolder(output_root), mkdir(output_root); end
result_path = fullfile(output_root, 'gate_r0_result.json');
result = struct('gate_r0_pass', false, 'status', 'R0_FAIL_STOPPED', ...
    'checked_utc', utc_now_local(), 'last_error', '');
stage8_r1_write_json_atomic(result_path, result);
try
    if ~strcmp(version('-release'), '2022b') || maxNumCompThreads ~= 1
        error('stage8_r1_gate_r0:Runtime', ...
            'Gate R0 requires MATLAB R2022b -singleCompThread.');
    end
    audit = jsondecode(fileread(char(string(process_audit_path))));
    required_audit = {'matlab_count','mwpython_count', ...
        'coordinator_count','active_lock_count','prompt_sha256'};
    if ~all(isfield(audit, required_audit)) || ...
            any([audit.matlab_count,audit.mwpython_count, ...
            audit.coordinator_count,audit.active_lock_count] ~= 0)
        error('stage8_r1_gate_r0:ProcessAudit', ...
            'Pre-launch process audit was not zero.');
    end
    constants = stage8_r1_constants();
    [head_status, head] = system(sprintf( ...
        'git -C "%s" rev-parse HEAD', repo_dir));
    [branch_status, branch] = system(sprintf( ...
        'git -C "%s" branch --show-current', repo_dir));
    [worktree_status, worktree] = system(sprintf( ...
        'git -C "%s" status --porcelain=v1 --untracked-files=all', repo_dir));
    [ancestor_status, ~] = system(sprintf( ...
        'git -C "%s" merge-base --is-ancestor %s HEAD', repo_dir, ...
        constants.audit_anchor_commit));
    [allowed_status, changed] = system(sprintf( ...
        'git -C "%s" diff --name-only %s..HEAD', repo_dir, ...
        constants.audit_anchor_commit));
    changed = splitlines(strtrim(string(changed)));
    changed = changed(strlength(changed) > 0);
    prompt_relative = ...
        "innovation-mining/stage8_execution_prompts/004_stage8_r1_continuous_refinement_decisive_v1.md";
    allowed = startsWith(changed, ...
        "tools/stage8_r1_continuous_decisive/") | ...
        (changed == prompt_relative);
    protected = { ...
        'beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_6_k12_bootstrap_resolution', ...
        'beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml', ...
        'beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_exact_subset_fim_beam_design', ...
        'beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_1_stage7_closure_audit', ...
        'innovation-mining/23_stage8_compact_algorithm_diagnostic'};
    protected_clean = true;
    for index = 1:numel(protected)
        command = sprintf('git -C "%s" diff --quiet %s..HEAD -- "%s"', ...
            repo_dir, constants.audit_anchor_commit, protected{index});
        [code, ~] = system(command);
        protected_clean = protected_clean && code == 0;
    end
    calibration_files = dir(fullfile(step, 'calibration', '*.csv'));
    tracked_count = tracked_count_local(repo_dir, step);
    result_files = dir(fullfile(step, 'results'));
    result_names = string({result_files(~[result_files.isdir]).name});
    stage8_r1_context(repo_dir, true);
    prompt_hash = char(string(audit.prompt_sha256));
    checks = struct('head_status_zero', head_status == 0, ...
        'branch_status_zero', branch_status == 0, ...
        'worktree_status_zero', worktree_status == 0, ...
        'anchor_is_ancestor', ancestor_status == 0, ...
        'allowed_diff_status_zero', allowed_status == 0, ...
        'expected_branch', string(constants.experiment_branch), ...
        'actual_branch', strtrim(string(branch)), ...
        'worktree_empty', isempty(strtrim(string(worktree))), ...
        'all_changed_paths_allowed', all(allowed), ...
        'protected_paths_clean', protected_clean, ...
        'calibration_csv_count', numel(calibration_files), ...
        'tracked_calibration_csv_count', tracked_count, ...
        'result_names', result_names, ...
        'prompt_sha256_actual', string(prompt_hash), ...
        'prompt_sha256_expected', string(constants.protocol_source_hash), ...
        'prompt_sha256_matches', strcmpi(prompt_hash, ...
        constants.protocol_source_hash));
    result.preflight = checks;
    if ~(checks.head_status_zero && checks.branch_status_zero && ...
            checks.worktree_status_zero && checks.anchor_is_ancestor && ...
            checks.allowed_diff_status_zero && ...
            checks.actual_branch == checks.expected_branch && ...
            checks.worktree_empty && checks.all_changed_paths_allowed && ...
            checks.protected_paths_clean && ...
            checks.calibration_csv_count == 13 && ...
            checks.tracked_calibration_csv_count == 13 && ...
            numel(result_names) == 1 && result_names == ".gitkeep" && ...
            checks.prompt_sha256_matches)
        error('stage8_r1_gate_r0:Boundary', ...
            'Repository, frozen artifacts, or prompt identity failed R0.');
    end
    result = struct('gate_r0_pass', true, ...
        'status', 'R0_BOUNDARY_IDENTITY_PASS', ...
        'checked_utc', utc_now_local(), ...
        'protocol_runner_commit', strtrim(head), ...
        'protocol_source_tree_hash', stage8_r1_source_hash(repo_dir), ...
        'protocol_document_sha256', prompt_hash, ...
        'audit_anchor_commit', constants.audit_anchor_commit, ...
        'branch', strtrim(branch), ...
        'calibration_csv_count', numel(calibration_files), ...
        'tracked_calibration_csv_count', tracked_count, ...
        'formal_results_clean', true, ...
        'protected_paths_clean', true, ...
        'matlab_release', version('-release'), ...
        'max_num_comp_threads', maxNumCompThreads, 'last_error', '');
    stage8_r1_write_json_atomic(result_path, result);
catch exception
    result.checked_utc = utc_now_local();
    result.last_error = getReport(exception, 'extended', 'hyperlinks', 'off');
    stage8_r1_write_json_atomic(result_path, result);
    rethrow(exception);
end
clear path_cleanup
end

function count = tracked_count_local(repo_dir, step)
relative = strrep(fullfile(strrep(step, [repo_dir, filesep], ''), ...
    'calibration', '*.csv'), filesep, '/');
[status, output] = system(sprintf( ...
    'git -C "%s" ls-files -- "%s"', repo_dir, relative));
if status ~= 0, error('stage8_r1_gate_r0:Git', 'Unable to list calibration.'); end
lines = splitlines(strtrim(string(output)));
if isscalar(lines) && strlength(lines) == 0, count = 0; else, count = numel(lines); end
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
