function row = stage8_r1_row_template()
%STAGE8_R1_ROW_TEMPLATE Define one method-level scientific result row.

row = struct('trial_id', "", 'global_trial_index', 0, ...
    'truth_K', 0, 'trial_type', "", 'support_or_difficulty', "", ...
    'noise_profile_id', "", 'L', 0, 'snr_db', NaN, 'noise_seed', 0, ...
    'element_trial_hash', "", 'method_id', "", ...
    'fit1_valid', false, 'fit2_valid', false, ...
    'fit1_status', "NOT_RUN", 'fit2_status', "NOT_RUN", ...
    'fit1_selected_start', "", 'fit2_selected_start', "", ...
    'fit1_start_count', 0, 'fit2_start_count', 0, ...
    'rss1', NaN, 'rss2', NaN, 'rss_gap', NaN, 'lambda_12', NaN, ...
    'lrt_status', "NOT_RUN", ...
    'n_complex_observations', 0, ...
    'k1_estimate_az_deg', NaN, 'k1_estimate_el_deg', NaN, ...
    'k2_estimate_target1_az_deg', NaN, ...
    'k2_estimate_target1_el_deg', NaN, ...
    'k2_estimate_target2_az_deg', NaN, ...
    'k2_estimate_target2_el_deg', NaN, ...
    'known_K_joint_rmse_deg', NaN, ...
    'known_K_azimuth_rmse_deg', NaN, ...
    'known_K_elevation_rmse_deg', NaN, ...
    'known_K_separation_vector_error_deg', NaN, ...
    'initial_known_K_joint_rmse_deg', NaN, ...
    'refinement_improved_flag', false, ...
    'score_call_count', 0, 'svd_call_count', 0, 'runtime_sec', 0, ...
    'shared_initialization_runtime_sec', 0, ...
    'initialization_runtime_sec', 0, 'refinement_runtime_sec', 0, ...
    'continuous_solver_status', "NOT_APPLICABLE", ...
    'monotonicity_violation_count', 0, ...
    'truth_used_in_initialization_flag', false, ...
    'truth_used_in_fit_flag', false, 'truth_used_in_lrt_flag', false, ...
    'shared_element_data_flag', true, 'phase_factor', 1);
end
