function registry = stage8_k2_rtc_build_registry()
c = stage8_k2_rtc_constants();
rows = cell(c.scenario_count, 1);
i = 0;
for s = 1:numel(c.snr_db_values)
    for l = 1:numel(c.snapshot_counts)
        for p = 1:numel(c.profile_ids)
            for replicate = 1:c.replicates
                i = i + 1;
                base = ((l - 1) * numel(c.profile_ids) + p - 1) * c.replicates + replicate;
                v = c.profile_values(p, :);
                correlation = v(6);
                rows{i} = struct('scenario_index', i, ...
                    'scenario_id', string(sprintf('RTC2L8_S%02d_B%03d', s, base)), ...
                    'base_realization_index', base, 'profile_id', c.profile_ids(p), ...
                    'L', c.snapshot_counts(l), 'replicate_id', replicate, ...
                    'nominal_snr_db', c.snr_db_values(s), ...
                    'center_az_deg', v(1), 'center_el_deg', v(2), ...
                    'rho_true_deg', v(3), 'direction_deg', v(4), ...
                    'secondary_power_db', v(5), 'correlation_magnitude', correlation, ...
                    'source_seed', c.source_seed_base + base, ...
                    'beam_noise_seed', c.beam_noise_seed_base + base, ...
                    'element_noise_seed', c.element_noise_seed_base + base);
            end
        end
    end
end
registry = struct2table(vertcat(rows{:}));
assert(height(registry) == c.scenario_count && numel(unique(registry.base_realization_index)) == c.base_count);
end
