function context = stage8_k2_rtc_build_context(repo)
assert(strcmp(version('-release'), '2022b'), 'RTC:Release', 'MATLAB R2022b required.');
cfg = sim_cfg();
assert(cfg.beam.spatialPhaseFactor == 1);
noise = struct('noise_id', 'WHITE', 'R_el', eye(32), 'R_az', eye(65), ...
    'Rn', speye(2080), 'L_el', eye(32), 'L_az', eye(65), ...
    'rho_el', 0, 'rho_az', 0, 'rank', 2080, ...
    'hash', stage7_stable_hash('WHITE', eye(32), eye(65)));
[model, debug] = build_stage8_measurement_model('PRIMARY_RECT_E14_A31', ...
    'WHITE', cfg, struct('noise', noise));
model.array_configuration = struct('arr', cfg.arr);
[domain, ~] = build_common_registered_local_domain([8 10], ...
    struct('azimuth_offsets_deg', -.6:.2:.6, 'elevation_offsets_deg', -.2:.2:.2, ...
    'domain_id', 'STAGE8_STAGE5_REGISTERED_LOCAL_DOMAIN', ...
    'domain_source', 'STAGE5_LOCKED_CONVENTIONAL_CENTER', ...
    'configuration_hash', '77e50c6af0c1f6078ebedcd05084b1d11abe606d026677d4017ca2d83d459a86', ...
    'phase_factor', 1));
assert(isequal(size(model.W_I), [2080 15]) && isequal(size(model.T_I), [15 15]));
assert(model.whitening_rank == 15 && isfinite(debug.whitening_error));
assert(isequal(domain.domain_bounds_deg, [7.4 8.6 9.8 10.2]));
assert(size(domain.candidate_points_deg, 1) == 21);
context = struct('repo', repo, 'cfg', cfg, 'model', model, 'domain', domain, ...
    'whitening_error', debug.whitening_error, ...
    'configuration_hash', stage8_k2_rtc_hash(cfg, model.fixed_measurement_hash, domain.domain_hash));
end
