function c = stage8_k2_rtc_constants()
c = struct('protocol', 'STAGE8_K2_RAW_TANGENT_TWO_SCENARIOS_L8_V1', ...
    'authorization', 'AUTHORIZE_STAGE8_K2_RAW_TANGENT_TWO_SCENARIOS_L8_V1', ...
    'branch', 'experiment/stage8-k2-raw-tangent-two-scenarios-l8-v1', ...
    'base_commit', 'f1b13422a91540073ecf417c3b25f5cac552b9d6', ...
    'main_commit', '644fc6e0041e400b6500579bba93d49f45e46990', ...
    'research_commit', 'a7139204d717923cb89d0d629b67f1b3ab7ae94d', ...
    'worktree', 'E:\bs_innovation_worktrees\raw-tangent-two-scenarios-l8', ...
    'runtime_root', 'E:\bs_innovation_runtime\experiment_stage8-k2-raw-tangent-two-scenarios-l8-v1', ...
    'output_prefix', '60_stage8_k2_raw_tangent_two_scenarios_', ...
    'snapshot_counts', 8, 'snr_db_values', [-6 0 6 10 14 18 22], ...
    'replicates', 20, 'source_seed_base', 580100000, ...
    'beam_noise_seed_base', 580200000, 'element_noise_seed_base', 580300000);
c.profile_ids = ["SC_A"; "SC_B"];
c.profile_values = [8 10 .45 30 0 0; 8 10 .45 30 -3 .7];
c.method_ids = ["TANGENT_PROFILE_CORE"; "FULL4D_BEAMSPACE_CML_MULTISTART"; ...
    "BEAMSPACE_MUSIC_K2"; "FULL4D_ELEMENT_CML_MULTISTART"; ...
    "ELEMENT_VERTICAL_FBSS_ROOT_MUSIC_AZ_CML"];
c.beamspace_method_ids = c.method_ids(1:3);
c.element_method_ids = c.method_ids(4:5);
c.base_count = numel(c.snapshot_counts)*numel(c.profile_ids)*c.replicates;
c.scenario_count = numel(c.snr_db_values)*c.base_count;
c.checkpoint_count = 2*c.scenario_count;
c.method_row_count = numel(c.method_ids)*c.scenario_count;
c.expected_applicable = repmat(c.scenario_count,1,numel(c.method_ids));
c.representative_count = c.scenario_count/c.replicates;
c.paired_tie_tolerance_deg = 1e-6;
c.core = struct('rho_min_deg', .001, 'scan_node_count', 33, ...
    'fminbnd_TolX_deg', 1e-4, 'fminbnd_MaxFunEvals', 80, ...
    'rank_multiplier', 1, 'direction_sign_tolerance', 1e-12);
c.classical = struct('top_start_count', 6, 'max_sweeps', 12, ...
    'scan_nodes_per_coordinate', 9, 'fminbnd_TolX_deg', 1e-4, ...
    'fminbnd_MaxFunEvals', 80, 'minimum_separation_deg', .001, ...
    'relative_score_tolerance', 1e-8, 'endpoint_update_tolerance_deg', .001, ...
    'rank_multiplier', 1, 'music_grid_step_deg', .005, 'music_applicable_L', [4 8]);
c.structured = struct('N_el', 32, 'N_az', 65, 'K', 2, ...
    'smoothing_length', 31, 'smoothing_subarray_count', 2, ...
    'elevation_grid_deg', 9.8:.001:10.2, 'elevation_domain_deg', [9.8 10.2], ...
    'elevation_distinct_tolerance_deg', 1e-6, 'azimuth_grid_deg', 7.4:.02:8.6, ...
    'azimuth_domain_deg', [7.4 8.6], 'top_start_count', 4, 'max_sweeps', 8, ...
    'scan_nodes_per_coordinate', 9, 'fminbnd_TolX_deg', 1e-4, ...
    'fminbnd_MaxFunEvals', 80, 'relative_score_tolerance', 1e-8, ...
    'coordinate_update_tolerance_deg', 1e-4, 'rank_multiplier', 1, ...
    'root_unit_circle_tolerance', 1e-7, 'root_duplicate_tolerance_deg', 1e-5);
end
