function [hybrid_rows, audit] = stage8_core_v2_build_hybrid_rows(source_rows)
%STAGE8_CORE_V2_BUILD_HYBRID_ROWS Build H1/H2 from committed B0/B1/B2 rows.

methods = ["B0_FIXED_GRID_KNOWN_K"; ...
    "B1_DIRECT_CONTINUOUS_KNOWN_K"; ...
    "B2_GROUPED_CONTINUOUS_KNOWN_K"];
if ~(istable(source_rows) && height(source_rows) == 72) || ...
        numel(unique(source_rows.trial_id)) ~= 24 || ...
        ~isequal(sort(unique(source_rows.method_id)), sort(methods))
    error('stage8_core_v2_build_hybrid_rows:Source', ...
        'Committed source rows do not match the 72-row B0/B1/B2 contract.');
end

trial_indices = unique(source_rows.global_trial_index);
trial_indices = sort(trial_indices);
cells = cell(2 * numel(trial_indices), 1);
output_index = 0;
for index = 1:numel(trial_indices)
    trial = source_rows(source_rows.global_trial_index == ...
        trial_indices(index), :);
    b0 = trial(trial.method_id == "B0_FIXED_GRID_KNOWN_K", :);
    b1 = trial(trial.method_id == "B1_DIRECT_CONTINUOUS_KNOWN_K", :);
    b2 = trial(trial.method_id == "B2_GROUPED_CONTINUOUS_KNOWN_K", :);
    if height(b0) ~= 1 || height(b1) ~= 1 || height(b2) ~= 1
        error('stage8_core_v2_build_hybrid_rows:Pairing', ...
            'Each trial must contain exactly one B0, B1 and B2 row.');
    end
    output_index = output_index + 1;
    cells{output_index} = stage8_core_v2_select_safe_hybrid( ...
        b0, b1, 'H1_DIRECT_SAFE_HYBRID_KNOWN_K');
    output_index = output_index + 1;
    cells{output_index} = stage8_core_v2_select_safe_hybrid( ...
        b0, b2, 'H2_GROUPED_SAFE_HYBRID_KNOWN_K');
end
hybrid_rows = sortrows(vertcat(cells{:}), ...
    {'global_trial_index','method_id'});
if height(hybrid_rows) ~= 48 || ...
        numel(unique(hybrid_rows.trial_id + "|" + ...
        hybrid_rows.method_id)) ~= 48 || ...
        any(~hybrid_rows.fit_valid) || ...
        any(hybrid_rows.truth_used_in_initialization_flag) || ...
        any(hybrid_rows.truth_used_in_fit_flag) || ...
        any(hybrid_rows.selection_truth_used_flag) || ...
        any(hybrid_rows.selected_source == "CONTINUOUS_UPGRADE" & ...
        hybrid_rows.loglik < hybrid_rows.B0_candidate_loglik)
    error('stage8_core_v2_build_hybrid_rows:Output', ...
        'Hybrid rows violate validity, identity or selection contracts.');
end
audit = struct('source_row_count', height(source_rows), ...
    'hybrid_row_count', height(hybrid_rows), ...
    'element_trial_count', numel(unique(hybrid_rows.trial_id)), ...
    'all_valid', all(hybrid_rows.fit_valid), ...
    'truth_leakage_count', nnz( ...
    hybrid_rows.truth_used_in_initialization_flag | ...
    hybrid_rows.truth_used_in_fit_flag | ...
    hybrid_rows.selection_truth_used_flag), ...
    'continuous_upgrade_count', nnz(hybrid_rows.continuous_upgrade_flag), ...
    'fallback_count', nnz(hybrid_rows.fallback_flag));
end
