function row = stage8_core_v2_row_template()
%STAGE8_CORE_V2_ROW_TEMPLATE One known-K method result row.

row = struct( ...
    'trial_id', "", 'global_trial_index', 0, 'truth_K', 0, ...
    'support_or_difficulty', "", 'noise', "", 'L', 0, 'SNR', NaN, ...
    'noise_seed', 0, 'element_trial_hash', "", 'method_id', "", ...
    'fit_valid', false, 'fit_status', "NOT_RUN", ...
    'solver_status', "NOT_RUN", 'selected_start_id', "", ...
    'start_count', 0, 'valid_start_count', 0, ...
    'initial_angles', "[]", 'final_angles', "[]", ...
    'estimate_target1_az_deg', NaN, ...
    'estimate_target1_el_deg', NaN, ...
    'estimate_target2_az_deg', NaN, ...
    'estimate_target2_el_deg', NaN, ...
    'known_K_joint_RMSE', NaN, 'known_K_azimuth_RMSE', NaN, ...
    'known_K_elevation_RMSE', NaN, ...
    'known_K_separation_vector_error', NaN, ...
    'initial_known_K_joint_RMSE', NaN, ...
    'refinement_improved_flag', false, ...
    'RSS', NaN, 'loglik', NaN, 'effective_rank', 0, ...
    'score_calls', 0, 'SVD_calls', 0, 'runtime_sec', 0, ...
    'monotonicity_violation_count', 0, ...
    'truth_used_in_initialization_flag', false, ...
    'truth_used_in_fit_flag', false, ...
    'shared_element_data_flag', true, ...
    'solver_contract_hash', "");
end
