function digest = stage8_core_v2_source_hash(repo_dir)
%STAGE8_CORE_V2_SOURCE_HASH Hash committed protocol and tool blobs.

command = sprintf(['git -C "%s" ls-tree -r --full-tree HEAD -- ', ...
    'tools/stage8_core_v2_known_k ', ...
    'innovation-mining/25_stage8_core_v2_known_k_refactor.md ', ...
    'innovation-mining/stage8_execution_prompts/active/', ...
    '005_stage8_core_v2_known_k_center_difference_pruning_v2.md'], ...
    char(string(repo_dir)));
[status, output] = system(command);
if status ~= 0 || isempty(strtrim(output))
    error('stage8_core_v2_source_hash:Git', ...
        'Unable to enumerate committed Core-V2 blobs.');
end
output = strrep(output, [char(13), newline], newline);
output = strrep(output, char(13), newline);
digest = stage8_stable_hash('STAGE8_CORE_V2_PROTOCOL_SOURCE_TREE_V2', ...
    output);
end
