function output = stage8_core_v2_finalize_hybrid(repo_dir, output_root)
%STAGE8_CORE_V2_FINALIZE_HYBRID Select, gate and summarize H1/H2.

repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
output_root = char(java.io.File(char(string(output_root))).getCanonicalPath());
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
h0 = boundary_gate_local(repo_dir);
if ~h0.pass
    error('stage8_core_v2_finalize_hybrid:H0', '%s', h0.status);
end
source_path = fullfile(repo_dir, 'innovation-mining', ...
    '26_stage8_core_v2_known_k_pruning_trials.csv');
source = readtable(source_path, 'TextType', 'string');
[trials, build_audit] = stage8_core_v2_build_hybrid_rows(source);
h1 = selection_gate_local(source, trials, build_audit, tool_dir);
if ~h1.pass
    error('stage8_core_v2_finalize_hybrid:H1', '%s', h1.status);
end
[summary, comparison, decision] = analyze_local(trials);

paths = { ...
    fullfile(output_root, '27_stage8_core_v2_1_safe_hybrid_closure.md'), ...
    fullfile(output_root, '27_stage8_core_v2_1_safe_hybrid_trials.csv'), ...
    fullfile(output_root, '27_stage8_core_v2_1_safe_hybrid_summary.csv'), ...
    fullfile(output_root, '27_stage8_core_v2_1_safe_hybrid_comparison.csv')};
for index = 1:numel(paths)
    if isfile(paths{index})
        error('stage8_core_v2_finalize_hybrid:Overwrite', ...
            'Finalize refuses to overwrite %s.', paths{index});
    end
end
writetable(trials, paths{2});
writetable(summary, paths{3});
writetable(comparison, paths{4});
write_report_local(paths{1}, h0, h1, summary, comparison, decision);
output = struct('trials', trials, 'summary', summary, ...
    'comparison', comparison, 'decision', decision, ...
    'h0', h0, 'h1', h1, 'build_audit', build_audit, ...
    'report_path', paths{1}, 'trial_path', paths{2}, ...
    'summary_path', paths{3}, 'comparison_path', paths{4});
end

function result = boundary_gate_local(repo_dir)
starting = '1581550b675b12e7c7c1bfd0541b4fbc52f39923';
main_anchor = '247fad2208e77b04f7062e22b0fd3fd8a81bfc1f';
branch = git_output_local(repo_dir, 'branch --show-current');
head = git_output_local(repo_dir, 'rev-parse HEAD');
main = git_output_local(repo_dir, 'rev-parse origin/main');
worktree = git_output_local(repo_dir, ...
    'status --porcelain=v1 --untracked-files=all');
[ancestor_status, ~] = system(sprintf( ...
    'git -C "%s" merge-base --is-ancestor %s HEAD', repo_dir, starting));
protected = { ...
    'beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_6_k12_bootstrap_resolution', ...
    'beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml', ...
    ':(glob)beamspace_ml_v18/**/calibration/**', ...
    ':(glob)beamspace_ml_v18/**/results/**', ...
    ':(glob)innovation-mining/23_stage8_compact_algorithm_diagnostic*', ...
    ':(glob)innovation-mining/24_stage8_r1_continuous_refinement_decisive*', ...
    'innovation-mining/25_stage8_core_v2_known_k_refactor.md', ...
    ':(glob)innovation-mining/26_stage8_core_v2_known_k_pruning_*', ...
    'innovation-mining/stage8_execution_prompts/archive', ...
    'tools/stage8_1b_validation_sharded', ...
    'tools/stage8_compact_diagnostic', ...
    'tools/stage8_r1_continuous_decisive'};
protected_clean = true;
for index = 1:numel(protected)
    [code, ~] = system(sprintf( ...
        'git -C "%s" diff --quiet %s..HEAD -- "%s"', ...
        repo_dir, starting, protected{index}));
    protected_clean = protected_clean && code == 0;
end
solver_files = { ...
    'tools/stage8_core_v2_known_k/matlab/stage8_core_v2_k2_center_difference_solver.m', ...
    'tools/stage8_core_v2_known_k/matlab/stage8_core_v2_fit_known_k.m'};
solver_clean = true;
for index = 1:numel(solver_files)
    [code, ~] = system(sprintf( ...
        'git -C "%s" diff --quiet %s..HEAD -- "%s"', ...
        repo_dir, starting, solver_files{index}));
    solver_clean = solver_clean && code == 0;
end
pass = strcmp(strtrim(branch), 'experiment/stage8-core-v2') && ...
    strcmp(strtrim(main), main_anchor) && isempty(strtrim(worktree)) && ...
    ancestor_status == 0 && protected_clean && solver_clean;
result = struct('pass', pass, ...
    'status', ternary_local(pass, 'H0_BOUNDARY_PASS', 'H0_BOUNDARY_FAIL'), ...
    'branch', strtrim(branch), 'head', strtrim(head), ...
    'starting_head', starting, 'origin_main', strtrim(main), ...
    'worktree_clean', isempty(strtrim(worktree)), ...
    'protected_paths_clean', protected_clean, ...
    'existing_solver_unchanged', solver_clean, ...
    'prelaunch_process_audit', 'MATLAB_LOCK_COORDINATOR_0_0_0');
end

function result = selection_gate_local(source, rows, audit, tool_dir)
[again, again_audit] = stage8_core_v2_build_hybrid_rows(source);
deterministic = isequaln(rows, again) && isequal(audit, again_audit);
required_ids = ["R1_K2_N1_L4_EASY"; ...
    "R1_K2_N1_L4_MODERATE"; ...
    "R1_K2_N1_L8_MODERATE"; ...
    "R1_K2_N2_L8_MODERATE"];
gate = rows(ismember(rows.trial_id, required_ids), :);
coverage = source_coverage_local(source, required_ids);
expected_sources = [ ...
    "R1_K2_N1_L4_EASY", "H1_DIRECT_SAFE_HYBRID_KNOWN_K", "FIXED_GRID_FALLBACK"; ...
    "R1_K2_N1_L4_EASY", "H2_GROUPED_SAFE_HYBRID_KNOWN_K", "CONTINUOUS_UPGRADE"; ...
    "R1_K2_N1_L4_MODERATE", "H1_DIRECT_SAFE_HYBRID_KNOWN_K", "CONTINUOUS_UPGRADE"; ...
    "R1_K2_N1_L4_MODERATE", "H2_GROUPED_SAFE_HYBRID_KNOWN_K", "CONTINUOUS_UPGRADE"; ...
    "R1_K2_N1_L8_MODERATE", "H1_DIRECT_SAFE_HYBRID_KNOWN_K", "FIXED_GRID_FALLBACK"; ...
    "R1_K2_N1_L8_MODERATE", "H2_GROUPED_SAFE_HYBRID_KNOWN_K", "FIXED_GRID_FALLBACK"; ...
    "R1_K2_N2_L8_MODERATE", "H1_DIRECT_SAFE_HYBRID_KNOWN_K", "CONTINUOUS_UPGRADE"; ...
    "R1_K2_N2_L8_MODERATE", "H2_GROUPED_SAFE_HYBRID_KNOWN_K", "FIXED_GRID_FALLBACK"];
expected = true;
for index = 1:size(expected_sources, 1)
    row = gate(gate.trial_id == expected_sources(index, 1) & ...
        gate.method_id == expected_sources(index, 2), :);
    expected = expected && height(row) == 1 && ...
        row.selected_source == expected_sources(index, 3);
end
identity = true;
for index = 1:numel(required_ids)
    source_hash = unique(source.element_trial_hash( ...
        source.trial_id == required_ids(index)));
    selected_hash = unique(gate.element_trial_hash( ...
        gate.trial_id == required_ids(index)));
    identity = identity && numel(source_hash) == 1 && ...
        numel(selected_hash) == 1 && source_hash == selected_hash;
end
selector_text = fileread(fullfile(tool_dir, ...
    'stage8_core_v2_select_safe_hybrid.m'));
forbidden_access = ~isempty(regexp(selector_text, ...
    '\.(known_K_.*RMSE|support_or_difficulty|noise|L|SNR)', 'once'));
pass = deterministic && coverage && expected && identity && ...
    height(gate) == 8 && all(gate.fit_valid) && ...
    all(gate.loglik >= gate.B0_candidate_loglik) && ...
    ~any(gate.selection_truth_used_flag) && ~forbidden_access;
result = struct('pass', pass, ...
    'status', ternary_local(pass, ...
    'H1_SELECTION_CORRECTNESS_PASS', 'H1_SELECTION_CORRECTNESS_FAIL'), ...
    'fixture_count', numel(required_ids), ...
    'hybrid_fixture_row_count', height(gate), ...
    'deterministic', deterministic, 'branch_coverage', coverage, ...
    'expected_selection_sources', expected, ...
    'element_identity_unchanged', identity, ...
    'all_selected_loglik_not_below_B0', ...
    all(gate.loglik >= gate.B0_candidate_loglik), ...
    'all_rows_valid', all(gate.fit_valid), ...
    'truth_not_read', ~forbidden_access && ...
    ~any(gate.selection_truth_used_flag));
end

function coverage = source_coverage_local(source, ids)
fixture = source(ismember(source.trial_id, ids), :);
validity = false(4, 2);
for index = 1:numel(ids)
    trial = fixture(fixture.trial_id == ids(index), :);
    b1 = trial(trial.method_id == "B1_DIRECT_CONTINUOUS_KNOWN_K", :);
    b2 = trial(trial.method_id == "B2_GROUPED_CONTINUOUS_KNOWN_K", :);
    validity(index, :) = [logical(b1.fit_valid), logical(b2.fit_valid)];
end
coverage = any(~validity(:)) && any(validity(:)) && ...
    any(validity(:, 1) & ~validity(:, 2)) && ...
    any(~validity(:, 1) & validity(:, 2));
end

function [summary, comparison, decision] = analyze_local(trials)
methods = ["H1_DIRECT_SAFE_HYBRID_KNOWN_K"; ...
    "H2_GROUPED_SAFE_HYBRID_KNOWN_K"];
cells = cell(2, 1);
metrics = repmat(struct('operational', false, 'k2_median', NaN), 2, 1);
for index = 1:2
    subset = trials(trials.method_id == methods(index), :);
    k1 = subset(subset.truth_K == 1, :);
    k2 = subset(subset.truth_K == 2, :);
    offgrid = k1(k1.support_or_difficulty == "INSIDE_OFF_GRID", :);
    easy = k2(k2.support_or_difficulty == "EASY", :);
    moderate = k2(k2.support_or_difficulty == "MODERATE", :);
    k1_median = median(offgrid.known_K_joint_RMSE);
    k2_median = median(k2.known_K_joint_RMSE);
    leakage = nnz(subset.truth_used_in_initialization_flag | ...
        subset.truth_used_in_fit_flag | subset.selection_truth_used_flag);
    operational = nnz(k1.fit_valid) == 16 && nnz(k2.fit_valid) == 8 && ...
        k1_median <= 0.05 && k2_median <= 0.20 && leakage == 0;
    metrics(index) = struct('operational', operational, ...
        'k2_median', k2_median);
    cells{index} = struct('method_id', methods(index), ...
        'K1_valid', nnz(k1.fit_valid), 'K2_valid', nnz(k2.fit_valid), ...
        'K1_off_grid_median_RMSE_deg', k1_median, ...
        'K2_overall_median_RMSE_deg', k2_median, ...
        'K2_easy_median_RMSE_deg', median(easy.known_K_joint_RMSE), ...
        'K2_moderate_median_RMSE_deg', ...
        median(moderate.known_K_joint_RMSE), ...
        'continuous_upgrade_count', nnz(subset.continuous_upgrade_flag), ...
        'fixed_grid_fallback_count', nnz(subset.fallback_flag), ...
        'K1_continuous_upgrade_count', nnz(k1.continuous_upgrade_flag), ...
        'K2_continuous_upgrade_count', nnz(k2.continuous_upgrade_flag), ...
        'B0_candidate_mean_score_calls', ...
        mean(subset.B0_candidate_score_calls), ...
        'B0_candidate_mean_SVD_calls', ...
        mean(subset.B0_candidate_SVD_calls), ...
        'B0_candidate_mean_runtime_sec', ...
        mean(subset.B0_candidate_runtime_sec), ...
        'continuous_candidate_mean_score_calls', ...
        mean(subset.continuous_candidate_score_calls), ...
        'continuous_candidate_mean_SVD_calls', ...
        mean(subset.continuous_candidate_SVD_calls), ...
        'continuous_candidate_mean_runtime_sec', ...
        mean(subset.continuous_candidate_runtime_sec), ...
        'conservative_upper_bound_mean_score_calls', ...
        mean(subset.conservative_upper_bound_score_calls), ...
        'conservative_upper_bound_mean_SVD_calls', ...
        mean(subset.conservative_upper_bound_SVD_calls), ...
        'conservative_upper_bound_mean_runtime_sec', ...
        mean(subset.conservative_upper_bound_runtime_sec), ...
        'cost_accounting_note', "DOUBLE_COUNTS_SHARED_INITIALIZATION", ...
        'truth_leakage_count', leakage, 'operational', operational);
end
summary = struct2table(vertcat(cells{:}));
comparison = compare_local(trials);
wins = nnz(comparison.outcome == "H2_WIN");
ties = nnz(comparison.outcome == "TIE");
losses = nnz(comparison.outcome == "H2_LOSS");
h1 = metrics(1); h2 = metrics(2);
if ~h1.operational && ~h2.operational
    conclusion = 'STAGE8_CORE_V2_1_EXPERIMENT_INVALID';
elseif h2.operational && ~h1.operational
    conclusion = 'STAGE8_CORE_V2_1_OPERATIONAL_GROUPED_RETAIN';
elseif h1.operational && ~h2.operational
    conclusion = 'STAGE8_CORE_V2_1_OPERATIONAL_GROUPED_PRUNE';
elseif wins >= 5 && h2.k2_median <= 0.95 * h1.k2_median
    conclusion = 'STAGE8_CORE_V2_1_OPERATIONAL_GROUPED_RETAIN';
elseif losses >= 5 && h2.k2_median >= 1.05 * h1.k2_median
    conclusion = 'STAGE8_CORE_V2_1_OPERATIONAL_GROUPED_PRUNE';
else
    conclusion = 'STAGE8_CORE_V2_1_OPERATIONAL_GROUPED_OPTIONAL';
end
decision = struct('H1_operational', h1.operational, ...
    'H2_operational', h2.operational, 'H2_wins', wins, ...
    'H2_ties', ties, 'H2_losses', losses, ...
    'final_conclusion', conclusion, 'model_order_status', 'DEFERRED', ...
    'formal_6000_trial_status', 'DEFERRED_NOT_FAILED', ...
    'stage8_2_status', 'NOT_EXECUTED');
end

function comparison = compare_local(trials)
ids = unique(trials.trial_id(trials.truth_K == 2), 'stable');
cells = cell(numel(ids), 1);
for index = 1:numel(ids)
    h1 = trials(trials.trial_id == ids(index) & ...
        trials.method_id == "H1_DIRECT_SAFE_HYBRID_KNOWN_K", :);
    h2 = trials(trials.trial_id == ids(index) & ...
        trials.method_id == "H2_GROUPED_SAFE_HYBRID_KNOWN_K", :);
    if h2.known_K_joint_RMSE < h1.known_K_joint_RMSE - 1e-3
        outcome = "H2_WIN";
    elseif h1.known_K_joint_RMSE < h2.known_K_joint_RMSE - 1e-3
        outcome = "H2_LOSS";
    else
        outcome = "TIE";
    end
    cells{index} = struct('trial_id', ids(index), ...
        'H1_selected_source', h1.selected_source, ...
        'H2_selected_source', h2.selected_source, ...
        'H1_known_K_joint_RMSE_deg', h1.known_K_joint_RMSE, ...
        'H2_known_K_joint_RMSE_deg', h2.known_K_joint_RMSE, ...
        'outcome', outcome);
end
comparison = struct2table(vertcat(cells{:}));
end

function write_report_local(path_now, h0, h1, summary, comparison, decision)
fid = fopen(path_now, 'w', 'n', 'UTF-8');
if fid < 0
    error('stage8_core_v2_finalize_hybrid:Report', ...
        'Cannot write hybrid closure report.');
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# Stage8 Core-V2.1 Safe Known-K Hybrid Closure\n\n');
fprintf(fid, 'KNOWN_K_SAFE_HYBRID_DIAGNOSTIC_ONLY\n\n');
fprintf(fid, 'MODEL_ORDER_DEFERRED\n\nNO_FORMAL_THRESHOLD\n\n');
fprintf(fid, 'NO_STAGE8_1_VALIDATION_PASS\n\nNO_STAGE8_2_AUTHORIZATION\n\n');
fprintf(fid, 'Branch: %s\n\nStarting/runner HEAD: %s / %s\n\n', ...
    h0.branch, h0.starting_head, h0.head);
fprintf(fid, 'H0: PASS, %s\n\nH1: PASS, %s\n\n', h0.status, h1.status);
fprintf(fid, 'Source fits reused: 24 trials and 72 B0/B1/B2 rows. No fit rerun.\n\n');
fprintf(fid, '| Hybrid | K1 valid | K2 valid | K1 off-grid RMSE | K2 RMSE | K2 easy | K2 moderate | upgrades | fallbacks | operational |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|---:|---:|---|\n');
for index = 1:height(summary)
    fprintf(fid, '| %s | %d | %d | %.9g | %.9g | %.9g | %.9g | %d | %d | %d |\n', ...
        summary.method_id(index), summary.K1_valid(index), ...
        summary.K2_valid(index), ...
        summary.K1_off_grid_median_RMSE_deg(index), ...
        summary.K2_overall_median_RMSE_deg(index), ...
        summary.K2_easy_median_RMSE_deg(index), ...
        summary.K2_moderate_median_RMSE_deg(index), ...
        summary.continuous_upgrade_count(index), ...
        summary.fixed_grid_fallback_count(index), ...
        summary.operational(index));
end
fprintf(fid, '\n## Candidate Cost Audit\n\n');
fprintf(fid, 'All values are means over the 24 registered element trials. The conservative upper bound is labeled `DOUBLE_COUNTS_SHARED_INITIALIZATION` and does not trigger RETAIN or PRUNE.\n\n');
fprintf(fid, '| Hybrid | B0 score/SVD/runtime | Continuous score/SVD/runtime | Conservative score/SVD/runtime |\n');
fprintf(fid, '|---|---:|---:|---:|\n');
for index = 1:height(summary)
    fprintf(fid, '| %s | %.6g / %.6g / %.6g | %.6g / %.6g / %.6g | %.6g / %.6g / %.6g |\n', ...
        summary.method_id(index), ...
        summary.B0_candidate_mean_score_calls(index), ...
        summary.B0_candidate_mean_SVD_calls(index), ...
        summary.B0_candidate_mean_runtime_sec(index), ...
        summary.continuous_candidate_mean_score_calls(index), ...
        summary.continuous_candidate_mean_SVD_calls(index), ...
        summary.continuous_candidate_mean_runtime_sec(index), ...
        summary.conservative_upper_bound_mean_score_calls(index), ...
        summary.conservative_upper_bound_mean_SVD_calls(index), ...
        summary.conservative_upper_bound_mean_runtime_sec(index));
end
fprintf(fid, '\nH2 vs H1: wins=%d, ties=%d, losses=%d.\n\n', ...
    nnz(comparison.outcome == "H2_WIN"), ...
    nnz(comparison.outcome == "TIE"), ...
    nnz(comparison.outcome == "H2_LOSS"));
fprintf(fid, 'Final conclusion: %s\n\n', decision.final_conclusion);
fprintf(fid, 'Model-order = DEFERRED\n');
fprintf(fid, 'Formal 6000-trial = DEFERRED_NOT_FAILED\n');
fprintf(fid, 'Stage8.2 = NOT_EXECUTED\n');
clear cleanup
end

function value = git_output_local(repo_dir, arguments)
[status, value] = system(sprintf('git -C "%s" %s', repo_dir, arguments));
if status ~= 0
    error('stage8_core_v2_finalize_hybrid:Git', ...
        'Git command failed: %s.', arguments);
end
value = strtrim(value);
end

function value = ternary_local(condition, yes_value, no_value)
if condition, value = yes_value; else, value = no_value; end
end
