function registry = stage8_core_v2_registry(context, registry_kind)
%STAGE8_CORE_V2_REGISTRY Reuse and verify the exact R1 trial registry.

if nargin < 2, registry_kind = 'FORMAL'; end
formal = stage8_r1_build_registry(context, 'FORMAL');
validate_historical_identity_local(formal, context.repo_dir);
kind = upper(char(string(registry_kind)));
switch kind
    case 'FORMAL'
        registry = formal;
    case 'GATES'
        f1 = formal.truth_K == 1 & ...
            formal.support_or_difficulty == "INSIDE_OFF_GRID" & ...
            formal.noise_profile_id == "WHITE" & formal.L == 8 & ...
            formal.snr_db == 6;
        f2 = formal.truth_K == 2 & ...
            formal.support_or_difficulty == "EASY" & ...
            formal.noise_profile_id == "WHITE" & formal.L == 8 & ...
            formal.snr_db == 6 & formal.separation_deg == 0.30;
        registry = formal(f1 | f2, :);
        if height(registry) ~= 2 || nnz(f1) ~= 1 || nnz(f2) ~= 1
            error('stage8_core_v2_registry:Gates', ...
                'The required F1/F2 fixtures are not unique.');
        end
    otherwise
        error('stage8_core_v2_registry:Kind', ...
            'Unsupported registry kind: %s.', kind);
end
end

function validate_historical_identity_local(registry, repo_dir)
path_now = fullfile(repo_dir, 'innovation-mining', ...
    '24_stage8_r1_continuous_refinement_decisive_trials.csv');
historical = readtable(path_now, 'TextType', 'string');
[trial_ids, first] = unique(historical.trial_id, 'stable');
if numel(trial_ids) ~= 24
    error('stage8_core_v2_registry:HistoricalCardinality', ...
        'Historical trial evidence does not contain 24 trials.');
end
one = historical(first, :);
one = sortrows(one, 'global_trial_index');
registry = sortrows(registry, 'global_trial_index');
same = height(registry) == height(one) && ...
    all(registry.trial_id == one.trial_id) && ...
    all(registry.global_trial_index == one.global_trial_index) && ...
    all(registry.truth_K == one.truth_K) && ...
    all(registry.support_or_difficulty == one.support_or_difficulty) && ...
    all(registry.noise_profile_id == one.noise_profile_id) && ...
    all(registry.L == one.L) && all(registry.snr_db == one.snr_db) && ...
    all(registry.noise_seed == one.noise_seed);
for index = 1:height(one)
    subset = historical(historical.trial_id == one.trial_id(index), :);
    same = same && height(subset) == 3 && ...
        numel(unique(subset.element_trial_hash)) == 1 && ...
        numel(unique(subset.noise_seed)) == 1 && ...
        numel(unique(subset.truth_K)) == 1;
end
if ~same
    error('stage8_core_v2_registry:HistoricalIdentity', ...
        'STAGE8_CORE_V2_EXPERIMENT_INVALID: R1 trial identity changed.');
end
end
