function protocol = stage8_core_v2_initialize_runtime( ...
    repo_dir, runtime_root, worker_count, trial_indices, registry_kind, role)
%STAGE8_CORE_V2_INITIALIZE_RUNTIME Create an immutable resumable runtime.

repo_dir = canonical_local(repo_dir);
runtime_root = canonical_local(runtime_root);
worker_count = double(worker_count);
trial_indices = sort(double(trial_indices(:)));
registry_kind = upper(char(string(registry_kind)));
role = upper(char(string(role)));
tool_dir = fileparts(mfilename('fullpath'));
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(tool_dir); addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
context = stage8_core_v2_context(repo_dir, true);
registry = stage8_core_v2_registry(context, registry_kind);
selected = registry(ismember(registry.global_trial_index, trial_indices), :);
if ~ismember(worker_count, [1, 2]) || worker_count ~= fix(worker_count) || ...
        isempty(trial_indices) || height(selected) ~= numel(trial_indices) || ...
        numel(unique(trial_indices)) ~= numel(trial_indices)
    error('stage8_core_v2_initialize_runtime:Selection', ...
        'Worker count or trial selection is invalid.');
end
create_dirs_local(runtime_root);
protocol_path = fullfile(runtime_root, 'protocol.json');
if isfile(protocol_path)
    protocol = jsondecode(fileread(protocol_path));
    immutable = double(protocol.selected_worker_count) == worker_count && ...
        strcmp(string(protocol.registry_kind), string(registry_kind)) && ...
        isequal(sort(double(protocol.trial_indices(:))), trial_indices);
    if ~immutable
        error('stage8_core_v2_initialize_runtime:Immutable', ...
            'Existing runtime protocol differs from this request.');
    end
    clear path_cleanup
    return;
end
if ~isempty(dir(fullfile(runtime_root, 'checkpoints', '*.mat')))
    error('stage8_core_v2_initialize_runtime:OrphanCheckpoint', ...
        'Checkpoints exist without protocol.json.');
end
[head_status, head] = system(sprintf('git -C "%s" rev-parse HEAD', repo_dir));
[status_code, status_text] = system(sprintf( ...
    'git -C "%s" status --porcelain=v1 --untracked-files=all', repo_dir));
if head_status ~= 0 || status_code ~= 0 || ~isempty(strtrim(status_text))
    error('stage8_core_v2_initialize_runtime:Repository', ...
        'Runtime initialization requires a clean committed repository.');
end
constants = context.constants;
protocol = struct('protocol_version', constants.protocol_version, ...
    'checkpoint_contract_version', constants.checkpoint_contract_version, ...
    'execution_authorization', constants.execution_authorization, ...
    'role', role, 'registry_kind', registry_kind, ...
    'repo_dir', repo_dir, 'runtime_root', runtime_root, ...
    'protocol_runner_commit', strtrim(head), ...
    'protocol_source_tree_hash', stage8_core_v2_source_hash(repo_dir), ...
    'protocol_document_sha256', constants.protocol_source_hash, ...
    'starting_commit', constants.starting_commit, ...
    'origin_main_anchor_commit', constants.origin_main_anchor_commit, ...
    'k1_solver_contract_hash', context.k1_solver_contract_hash, ...
    'k2_solver_contract_hash', context.k2_solver_contract_hash, ...
    'selected_worker_count', worker_count, ...
    'selected_execution_mode', ternary_local(worker_count == 2, ...
    'TWO_WORKER_RESUMABLE', 'ONE_WORKER_RESUMABLE'), ...
    'partition_rule', 'MOD_GLOBAL_TRIAL_INDEX_MINUS_ONE', ...
    'trial_indices', trial_indices, ...
    'element_trial_count', height(selected), ...
    'row_count', 3 * height(selected), 'threads_per_worker', 1, ...
    'model_order_status', constants.model_order_status, ...
    'formal_6000_trial_status', constants.formal_6000_trial_status, ...
    'stage8_2_executed_flag', false, ...
    'stage8_2_authorized_flag', false, 'created_utc', utc_now_local());
stage8_core_v2_write_json_atomic(protocol_path, protocol);
writetable(selected, fullfile(runtime_root, 'registry.csv'));
clear path_cleanup
end

function create_dirs_local(root)
if ~isfolder(root), mkdir(root); end
names = {'control','checkpoints','tmp','workers','logs'};
for index = 1:numel(names)
    path_now = fullfile(root, names{index});
    if ~isfolder(path_now), mkdir(path_now); end
end
end

function value = canonical_local(path_now)
value = char(java.io.File(char(string(path_now))).getCanonicalPath());
end

function value = ternary_local(condition, yes_value, no_value)
if condition, value = yes_value; else, value = no_value; end
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
