function value = stage8_core_v2_constants()
%STAGE8_CORE_V2_CONSTANTS Frozen identities and budgets for Core-V2.

k2_contract = struct( ...
    'max_sweeps', 20, ...
    'scan_point_count', 9, ...
    'center_radius_deg', 0.20, ...
    'delta_az_radius_deg', 0.40, ...
    'delta_el_radius_deg', 0.20, ...
    'fminbnd_TolX_deg', 1e-4, ...
    'fminbnd_MaxFunEvals', 80, ...
    'relative_score_tolerance', 1e-8, ...
    'endpoint_update_tolerance_deg', 1e-3, ...
    'usable_relative_tolerance', 1e-7, ...
    'usable_endpoint_tolerance_deg', 2e-3, ...
    'minimum_separation_deg', 1e-3, ...
    'rank_multiplier', 1, ...
    'update_order', {{'c_az','c_el','d_az','d_el'}});

value = struct( ...
    'protocol_version', ...
    'STAGE8_CORE_V2_KNOWN_K_CENTER_DIFFERENCE_PRUNING_V2', ...
    'checkpoint_contract_version', ...
    'STAGE8_CORE_V2_ELEMENT_TRIAL_CHECKPOINT_V2', ...
    'execution_authorization', ...
    'AUTHORIZE_STAGE8_CORE_V2_KNOWN_K_CENTER_DIFFERENCE_PRUNING_V2', ...
    'starting_commit', ...
    'b6068407a0dc40b94471119d593acaeee8707ddb', ...
    'origin_main_anchor_commit', ...
    '247fad2208e77b04f7062e22b0fd3fd8a81bfc1f', ...
    'protocol_source_hash', ...
    '8c96252659fd81eb019237a605e82df6df337fb5991e154c280bf0d410974131', ...
    'primary_measurement_config_id', 'PRIMARY_RECT_E14_A31', ...
    'runtime_root', ...
    'E:\bs_innovation_runtime\stage8_core_v2_known_k_center_difference_v2_b606840', ...
    'experiment_branch', 'experiment/stage8-core-v2', ...
    'formal_trial_count', 24, 'formal_row_count', 72, ...
    'formal_k1_trial_count', 16, 'formal_k2_trial_count', 8, ...
    'default_worker_count', 2, ...
    'model_order_status', 'MODEL_ORDER_DEFERRED', ...
    'formal_6000_trial_status', 'DEFERRED_NOT_FAILED', ...
    'k2_solver_contract', k2_contract);
end
