function result = stage8_core_v2_run_gates( ...
    repo_dir, gate_root, process_audit_path, mode, varargin)
%STAGE8_CORE_V2_RUN_GATES Run G0 before work and analyze G1/G2 fixtures.

repo_dir = char(string(repo_dir));
gate_root = char(string(gate_root));
mode = upper(char(string(mode)));
if ~isfolder(gate_root), mkdir(gate_root); end
tool_dir = fileparts(mfilename('fullpath'));
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(tool_dir); addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
switch mode
    case 'G0'
        result = gate_g0_local(repo_dir, process_audit_path);
        stage8_core_v2_write_json_atomic( ...
            fullfile(gate_root, 'gate_g0_result.json'), result);
        if ~result.pass
            error('stage8_core_v2_run_gates:G0', '%s', result.last_error);
        end
    case 'G1_G2'
        if numel(varargin) ~= 2
            error('stage8_core_v2_run_gates:Arguments', ...
                'G1_G2 requires one-worker and two-worker runtime roots.');
        end
        g0_path = fullfile(gate_root, 'gate_g0_result.json');
        if ~isfile(g0_path) || ~jsondecode(fileread(g0_path)).pass
            error('stage8_core_v2_run_gates:G0Required', ...
                'A passing G0 record is required before G1/G2.');
        end
        one_root = char(string(varargin{1}));
        two_root = char(string(varargin{2}));
        [one_rows, one_hashes, context] = ...
            load_gate_runtime_local(repo_dir, one_root);
        [two_rows, two_hashes] = load_gate_runtime_local(repo_dir, two_root);
        g2 = gate_g2_local(one_rows, one_hashes, two_rows, two_hashes);
        g1 = gate_g1_local(one_rows, context);
        stage8_core_v2_write_json_atomic( ...
            fullfile(gate_root, 'gate_g1_result.json'), g1);
        stage8_core_v2_write_json_atomic( ...
            fullfile(gate_root, 'gate_g2_result.json'), g2);
        selected = 1 + double(g2.equivalent);
        execution_mode = ternary_local(selected == 2, ...
            'TWO_WORKER_RESUMABLE', 'ONE_WORKER_RESUMABLE');
        result = struct('protocol_version', ...
            stage8_core_v2_constants().protocol_version, ...
            'gate_g0_pass', true, 'gate_g1_pass', logical(g1.pass), ...
            'gate_g1_status', g1.status, 'gate_g2_pass', true, ...
            'gate_g2_status', g2.status, ...
            'selected_worker_count', selected, ...
            'selected_execution_mode', execution_mode, ...
            'hard_stop_conclusion', g1.hard_stop_conclusion);
        stage8_core_v2_write_json_atomic( ...
            fullfile(gate_root, 'gate_decision.json'), result);
        if ~g1.pass
            error('stage8_core_v2_run_gates:G1', '%s', g1.status);
        end
    otherwise
        error('stage8_core_v2_run_gates:Mode', ...
            'Unsupported gate mode: %s.', mode);
end
clear path_cleanup
end

function result = gate_g0_local(repo_dir, process_audit_path)
constants = stage8_core_v2_constants();
result = struct('pass', false, 'status', 'G0_FAIL_STOPPED', ...
    'last_error', 'G0 did not complete.');
try
    if ~strcmp(version('-release'), '2022b') || maxNumCompThreads ~= 1
        error('MATLAB R2022b -singleCompThread is required.');
    end
    audit = jsondecode(fileread(char(string(process_audit_path))));
    required = {'matlab_count','lock_count','coordinator_count', ...
        'prompt_sha256'};
    if ~all(isfield(audit, required)) || ...
            any([audit.matlab_count,audit.lock_count, ...
            audit.coordinator_count] ~= 0) || ...
            ~strcmpi(char(string(audit.prompt_sha256)), ...
            constants.protocol_source_hash)
        error('Pre-launch process or prompt audit failed.');
    end
    branch = git_output_local(repo_dir, 'branch --show-current');
    head = git_output_local(repo_dir, 'rev-parse HEAD');
    main = git_output_local(repo_dir, 'rev-parse origin/main');
    worktree = git_output_local(repo_dir, ...
        'status --porcelain=v1 --untracked-files=all');
    [ancestor_status, ~] = system(sprintf( ...
        'git -C "%s" merge-base --is-ancestor %s HEAD', ...
        repo_dir, constants.starting_commit));
    changed_text = git_output_local(repo_dir, sprintf( ...
        'diff --name-only %s..HEAD', constants.starting_commit));
    changed = splitlines(string(changed_text));
    changed = changed(strlength(changed) > 0);
    allowed = startsWith(changed, "tools/stage8_core_v2_known_k/") | ...
        changed == "innovation-mining/25_stage8_core_v2_known_k_refactor.md" | ...
        changed == ("innovation-mining/stage8_execution_prompts/active/" + ...
        "005_stage8_core_v2_known_k_center_difference_pruning_v2.md");
    protected = { ...
        'beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_6_k12_bootstrap_resolution', ...
        'beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml', ...
        'beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_exact_subset_fim_beam_design', ...
        'beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_1_stage7_closure_audit', ...
        ':(glob)innovation-mining/23_stage8_compact_algorithm_diagnostic*', ...
        ':(glob)innovation-mining/24_stage8_r1_continuous_refinement_decisive*', ...
        'innovation-mining/stage8_execution_prompts/archive', ...
        'tools/stage8_1b_validation_sharded', ...
        'tools/stage8_compact_diagnostic', ...
        'tools/stage8_r1_continuous_decisive'};
    protected_clean = true;
    for index = 1:numel(protected)
        [code, ~] = system(sprintf( ...
            'git -C "%s" diff --quiet %s..HEAD -- "%s"', ...
            repo_dir, constants.starting_commit, protected{index}));
        protected_clean = protected_clean && code == 0;
    end
    context = stage8_core_v2_context(repo_dir, true); %#ok<NASGU>
    checks = strcmp(strtrim(branch), constants.experiment_branch) && ...
        strcmp(strtrim(main), constants.origin_main_anchor_commit) && ...
        isempty(strtrim(worktree)) && ancestor_status == 0 && ...
        all(allowed) && protected_clean;
    if ~checks
        error('Branch, anchor, worktree, allowed paths, or frozen history failed.');
    end
    result = struct('pass', true, 'status', 'G0_BOUNDARY_IDENTITY_PASS', ...
        'branch', strtrim(branch), 'head', strtrim(head), ...
        'starting_commit', constants.starting_commit, ...
        'origin_main', strtrim(main), 'worktree_clean', true, ...
        'protected_paths_clean', true, 'matlab_count', 0, ...
        'lock_count', 0, 'coordinator_count', 0, 'last_error', '');
catch exception
    result.last_error = getReport(exception, 'extended', 'hyperlinks', 'off');
end
end

function result = gate_g1_local(rows, context)
f1 = rows.truth_K == 1;
f2 = rows.truth_K == 2;
f1_rows = rows(f1, :);
f2_rows = rows(f2, :);
b0_f1 = f1_rows(f1_rows.method_id == "B0_FIXED_GRID_KNOWN_K", :);
continuous_f1 = f1_rows(f1_rows.method_id ~= "B0_FIXED_GRID_KNOWN_K", :);
continuous_f2 = f2_rows(f2_rows.method_id ~= "B0_FIXED_GRID_KNOWN_K", :);
rss_tolerance = 64 * eps(max(1, abs(b0_f1.RSS)));
f1_valid = height(continuous_f1) == 2 && all(continuous_f1.fit_valid) && ...
    all(continuous_f1.monotonicity_violation_count == 0) && ...
    all(continuous_f1.RSS <= b0_f1.RSS + rss_tolerance) && ...
    all(~grid_snapped_local(continuous_f1, context.plan.local_domain));
f2_valid_count = nnz(continuous_f2.fit_valid);
f2_contract = f2_valid_count >= 1;
bounds = context.plan.local_domain.domain_bounds_deg;
minimum = context.k2_solver_contract.minimum_separation_deg;
for index = find(continuous_f2.fit_valid).'
    angles = [continuous_f2.estimate_target1_az_deg(index), ...
        continuous_f2.estimate_target1_el_deg(index); ...
        continuous_f2.estimate_target2_az_deg(index), ...
        continuous_f2.estimate_target2_el_deg(index)];
    f2_contract = f2_contract && all(isfinite(angles(:))) && ...
        all(angles(:, 1) >= bounds(1) & angles(:, 1) <= bounds(2) & ...
        angles(:, 2) >= bounds(3) & angles(:, 2) <= bounds(4)) && ...
        norm(angles(2, :) - angles(1, :)) >= minimum && ...
        continuous_f2.monotonicity_violation_count(index) == 0 && ...
        isfinite(continuous_f2.known_K_joint_RMSE(index));
end
pass = f1_valid && f2_contract;
hard_stop = '';
if f2_valid_count == 0
    hard_stop = 'STAGE8_CORE_V2_K2_SOLVER_NOT_OPERATIONAL_STOP';
end
status = ternary_local(pass, 'G1_SOLVER_SCIENTIFIC_USABILITY_PASS', ...
    ternary_local(~isempty(hard_stop), hard_stop, ...
    'G1_SOLVER_SCIENTIFIC_USABILITY_FAIL'));
result = struct('pass', pass, 'status', status, ...
    'F1_continuous_valid_count', nnz(continuous_f1.fit_valid), ...
    'F1_rss_not_above_B0', all(continuous_f1.RSS <= ...
    b0_f1.RSS + rss_tolerance), ...
    'F1_non_grid_snap', all(~grid_snapped_local( ...
    continuous_f1, context.plan.local_domain)), ...
    'F2_continuous_valid_count', f2_valid_count, ...
    'hard_stop_conclusion', hard_stop);
end

function snapped = grid_snapped_local(rows, domain)
points = domain.candidate_points_deg;
snapped = false(height(rows), 1);
for index = 1:height(rows)
    angle = [rows.estimate_target1_az_deg(index), ...
        rows.estimate_target1_el_deg(index)];
    snapped(index) = any(vecnorm(points - angle, 2, 2) <= 1e-10);
end
end

function result = gate_g2_local(one_rows, one_hashes, two_rows, two_hashes)
one_rows = sortrows(one_rows, {'global_trial_index','method_id'});
two_rows = sortrows(two_rows, {'global_trial_index','method_id'});
same_shape = height(one_rows) == 6 && height(two_rows) == 6 && ...
    isequal(one_rows.trial_id, two_rows.trial_id) && ...
    isequal(one_rows.method_id, two_rows.method_id);
hashes_equal = isequal(sort(one_hashes), sort(two_hashes));
angles_equal = same_shape && ...
    isequal(num2hex(one_rows.estimate_target1_az_deg), ...
    num2hex(two_rows.estimate_target1_az_deg)) && ...
    isequal(num2hex(one_rows.estimate_target1_el_deg), ...
    num2hex(two_rows.estimate_target1_el_deg)) && ...
    isequal(num2hex(one_rows.estimate_target2_az_deg), ...
    num2hex(two_rows.estimate_target2_az_deg)) && ...
    isequal(num2hex(one_rows.estimate_target2_el_deg), ...
    num2hex(two_rows.estimate_target2_el_deg));
rss_equal = same_shape && isequal(num2hex(one_rows.RSS), ...
    num2hex(two_rows.RSS));
selection_equal = same_shape && ...
    isequal(one_rows.selected_start_id, two_rows.selected_start_id) && ...
    isequal(one_rows.solver_status, two_rows.solver_status);
equivalent = same_shape && hashes_equal && angles_equal && ...
    rss_equal && selection_equal;
result = struct('pass', true, 'equivalent', equivalent, ...
    'status', ternary_local(equivalent, ...
    'G2_TWO_WORKER_EQUIVALENCE_PASS', ...
    'G2_DIFFERENCE_RECORDED_ONE_WORKER_SELECTED'), ...
    'scientific_hashes_equal', hashes_equal, ...
    'angles_num2hex_equal', angles_equal, ...
    'RSS_num2hex_equal', rss_equal, ...
    'selected_start_and_status_equal', selection_equal);
end

function [rows, hashes, context] = load_gate_runtime_local(repo_dir, root)
protocol = jsondecode(fileread(fullfile(root, 'protocol.json')));
context = stage8_core_v2_context(repo_dir, true);
registry = stage8_core_v2_registry(context, 'GATES');
cells = cell(height(registry), 1);
hashes = strings(height(registry), 1);
for index = 1:height(registry)
    path_now = fullfile(root, 'checkpoints', ...
        [char(registry.trial_id(index)), '.mat']);
    stage8_core_v2_validate_checkpoint(path_now, protocol, ...
        registry(index, :));
    loaded = load(path_now, 'checkpoint', '-mat');
    cells{index} = loaded.checkpoint.rows;
    hashes(index) = string(loaded.checkpoint.scientific_content_hash);
end
rows = vertcat(cells{:});
end

function value = git_output_local(repo_dir, arguments)
[status, value] = system(sprintf('git -C "%s" %s', repo_dir, arguments));
if status ~= 0
    error('stage8_core_v2_run_gates:Git', ...
        'Git command failed: %s.', arguments);
end
value = strtrim(value);
end

function value = ternary_local(condition, yes_value, no_value)
if condition, value = yes_value; else, value = no_value; end
end
