function result = test_one_trial_no_truth_smoke()
%TEST_ONE_TRIAL_NO_TRUTH_SMOKE Validate one P2 data-only safe fit.

[status, repo_dir] = system('git rev-parse --show-toplevel');
assert(status == 0, 'Unable to locate the repository root.');
repo_dir = strtrim(repo_dir);
scope = stage8_k2_va_add_paths(repo_dir); %#ok<NASGU>
context = stage8_k2_va_build_context(repo_dir);
registry = stage8_k2_va_build_registry( ...
    context.plan.local_domain, context.constants);
selected = registry.profile_id == "P2" & registry.L == 4 & ...
    registry.snr_db == 0 & registry.noise_profile_id == "WHITE";
spec = registry(selected, :);
assert(height(spec) == 1, 'The no-truth smoke selector is not unique.');
[rows, diagnostic] = stage8_k2_va_evaluate_trial(spec, context);
m2 = rows(rows.method_id == ...
    "VINCENT_ANCHORED_PROJECTOR_AML_SAFE", :);
assert(height(m2) == 1 && m2.fit_valid && isfinite(m2.loglik) && ...
    isfinite(m2.RSS), 'The safe fit did not return a finite candidate.');
assert(height(rows) == 4 && all(~rows.truth_used_in_fit_flag) && ...
    ~diagnostic.truth_used_in_fit_flag, ...
    'Truth was reported as used by the fitting or selection path.');
assert(m2.full_manifold_used_flag && ...
    (diagnostic.raw_anchor_valid_count > 0 || ...
    diagnostic.fallback_flag), ...
    'The smoke fit did not retain exact full-manifold or fallback behavior.');
result = struct('test_name', 'one_trial_no_truth_smoke', 'pass', true, ...
    'fit_status', string(m2.fit_status), ...
    'selected_source', string(m2.selected_source), ...
    'raw_candidate_valid', logical(diagnostic.raw_candidate_valid), ...
    'fallback_flag', logical(diagnostic.fallback_flag));
end
