function full_data = build_stage8_full_data_from_element(Y_element, model, metadata)
%BUILD_STAGE8_FULL_DATA_FROM_ELEMENT Apply one fixed sequential measurement.

if nargin < 3 || isempty(metadata)
    metadata = struct();
end
if ~(isnumeric(Y_element) && ismatrix(Y_element) && ~isempty(Y_element) && ...
        size(Y_element, 1) == size(model.W_I, 1) && ...
        all(isfinite(Y_element(:))))
    error('build_stage8_full_data_from_element:Data', ...
        'Y_element must be finite and match the measurement rows.');
end
Zseq_raw = model.W_I' * Y_element;
Zseq_white = model.T_I * Zseq_raw;
full_data = struct('Y_element', Y_element, 'Zseq_raw', Zseq_raw, ...
    'Zseq_white', Zseq_white, ...
    'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'model_key', model.model_key, ...
    'measurement_config_id', model.measurement_config_id, ...
    'noise_profile_id', model.noise_profile_id, ...
    'phase_factor', 1, 'element_data_retained_flag', true, ...
    'data_identity_hash', stage8_stable_hash( ...
    'STAGE8_ELEMENT_OBSERVATION_V1', Y_element, ...
    model.fixed_measurement_hash));
names = fieldnames(metadata);
for field_index = 1:numel(names)
    if isfield(full_data, names{field_index})
        error('build_stage8_full_data_from_element:MetadataCollision', ...
            'metadata cannot replace full_data.%s.', names{field_index});
    end
    full_data.(names{field_index}) = metadata.(names{field_index});
end
end
