function plan = build_stage8_validation_plan()
%BUILD_STAGE8_VALIDATION_PLAN Freeze independent K1 and K2 validation.

validation_seed_base = 2226072200;
seed_block_stride = 2000;
L_values = [1,4,8];
noise_ids = ["WHITE";"STAGE5_TOEPLITZ_CORRELATED"];
strata = cell(numel(L_values) * numel(noise_ids), 1);
stratum_index = 0;
for L_index = 1:numel(L_values)
    for noise_index = 1:numel(noise_ids)
        stratum_index = stratum_index + 1;
        block_start = validation_seed_base + ...
            seed_block_stride * (stratum_index - 1);
        strata{stratum_index} = struct( ...
            'stratum_index', stratum_index, ...
            'stratum_id', sprintf('K1V_L%d_N%d', ...
            L_values(L_index), noise_index), ...
            'L', L_values(L_index), ...
            'noise_profile_id', noise_ids(noise_index), ...
            'seed_block_start', block_start, ...
            'element_seed_start', block_start, ...
            'element_seed_end', block_start + 999, ...
            'auxiliary_seed_start', block_start + 1000, ...
            'auxiliary_seed_end', block_start + 1999, ...
            'seed_block_end', block_start + seed_block_stride - 1, ...
            'seed_block_stride', seed_block_stride, ...
            'trials_per_stratum', 1000);
    end
end
strata = struct2table(vertcat(strata{:}));
plan = struct();
plan.K1 = struct('measurement_config_ids', ...
    ["PRIMARY_RECT_E14_A31";"SENSITIVITY_FULL_PARENT_5X5"], ...
    'L_values', L_values, 'noise_profile_ids', noise_ids, ...
    'trials_per_stratum', 1000, 'trials_per_config', 6000, ...
    'common_element_trial_count', 6000, ...
    'config_evaluation_row_count', 12000, ...
    'center_bounds_deg', [7.5,8.5;9.7,10.3], ...
    'snr_bounds_db', [-12,12], 'validation_seed_base', ...
    validation_seed_base, 'seed_block_stride', seed_block_stride, ...
    'seed', validation_seed_base, 'strata', strata, ...
    'paired_measurement_configs', true, ...
    'threshold_recalibration_allowed', false, ...
    'threshold_source', 'LOCKED_STAGE8_1_CALIBRATION_ARTIFACT_ONLY', ...
    'gates', struct( ...
    'overall_false_split_wilson_upper', 0.07, ...
    'stratum_false_split_wilson_upper', 0.08, ...
    'false_resolved_wilson_upper', 0.07, ...
    'nondecision_wilson_upper', 0.05));
plan.K2 = struct('measurement_config_id', 'PRIMARY_RECT_E14_A31', ...
    'trial_count', 1200, 'seed', 20260724, ...
    'center_rule', 'UNIFORM_WITH_BOTH_ENDPOINTS_IN_LOCAL_DOMAIN', ...
    'separation_bounds_deg', [0.05,0.40], ...
    'separation_distribution', 'LOG_UNIFORM', ...
    'direction_bounds_rad', [0,2*pi], 'snr_bounds_db', [-9,9], ...
    'L_values', [1,4,8], 'secondary_power_db_values', [0,-6,-12], ...
    'correlation_magnitude_values', [0,0.9,0.99], ...
    'correlation_phase_bounds_rad', [0,2*pi], ...
    'noise_profile_ids', ["WHITE";"STAGE5_TOEPLITZ_CORRELATED"]);
plan.execution_status = 'FROZEN_NOT_EXECUTED_STAGE8_1A';
plan.validation_plan_hash = stage8_stable_hash(plan.K1, plan.K2);
end
