function plan = build_stage8_locked_plan(repo_dir, cfg, opts)
%BUILD_STAGE8_LOCKED_PLAN Freeze Stage8.0 code and future experiment contracts.

if nargin < 1 || isempty(repo_dir)
    repo_dir = repository_root_local();
end
if nargin < 2 || isempty(cfg)
    cfg = sim_cfg();
end
if nargin < 3 || isempty(opts)
    opts = struct();
end
opts = normalize_options_local(opts);
if ~strcmp(version('-release'), '2022b') || cfg.beam.spatialPhaseFactor ~= 1
    error('build_stage8_locked_plan:Runtime', ...
        'Stage8 is frozen for MATLAB R2022b and phase_factor=1.');
end
identity = build_stage8_code_identity(repo_dir, struct( ...
    'require_formal_runtime', opts.require_formal_runtime, ...
    'historical_baseline_commit', opts.historical_baseline_commit));
dependency = collect_stage8_dependency_scope(repo_dir);
measurement_model_registry = build_stage8_measurement_registry(cfg, struct());
measurement_registry = measurement_model_registry.table;
[local_domain, ~] = build_common_registered_local_domain([8,10], ...
    struct('azimuth_offsets_deg', -0.6:0.2:0.6, ...
    'elevation_offsets_deg', -0.2:0.2:0.2, ...
    'domain_id', 'STAGE8_STAGE5_REGISTERED_LOCAL_DOMAIN', ...
    'domain_source', 'STAGE5_LOCKED_CONVENTIONAL_CENTER', ...
    'configuration_hash', ...
    '77e50c6af0c1f6078ebedcd05084b1d11abe606d026677d4017ca2d83d459a86', ...
    'phase_factor', 1));
solver = struct('max_iter', 6, 'relative_score_tolerance', 1e-9, ...
    'angle_tolerance_deg', 0, 'rank_multiplier', 1, ...
    'coordinate_update_order', ...
    'target_then_azimuth_then_elevation', ...
    'same_domain_for_K1_K2_bootstrap', true);
fit_contract = struct('K1_start_ids', ...
    ["K1_GROUPED_Q1_KQ1";"K1_CONVENTIONAL_SINGLETON_PEAK"], ...
    'K2_start_ids', ["K2_GROUPED_Q1_KQ2"; ...
    "K2_GROUPED_Q2_KQ1_PLUS_KQ1"; ...
    "K2_K1_EMBEDDED_NESTED_START"], ...
    'selection_rule', ...
    'MAXIMUM_CONCENTRATED_LOG_LIKELIHOOD_AMONG_VALID_REGISTERED_STARTS', ...
    'start_eligibility_contract', ...
    ['INITIALIZATION_AVAILABLE_AND_ESTIMATE_RETURNED_AND_CONVERGED_', ...
    'AND_FULL_RANK_AND_FINITE_RSS_SIGMA2_LOGLIK_AND_COMPLETE_IDENTITY'], ...
    'group_gate_role', 'INITIALIZATION_DIAGNOSTIC_ONLY');
controls = struct('phase_factor', 1, 'alpha', 0.05, 'beta', 0.05, ...
    'Bboot_per_cell', 199, 'Bsep', 199, ...
    'minimum_valid_fraction', 0.90, ...
    'engineering_halfwidth_gate_deg', [0.21,0.21], ...
    'threshold_policy', ...
    'ONE_GLOBAL_THRESHOLD_PER_FIXED_MEASUREMENT_CONFIG', ...
    'ordinary_chi_square_role', 'DIAGNOSTIC_ONLY', ...
    'model_mismatch_state', ...
    'MODEL_MISMATCH_STATE_DISABLED_UNTIL_CALIBRATED_GOF');
calibration = build_stage8_calibration_plan(measurement_model_registry);
validation = build_stage8_validation_plan();
holdout = build_stage8_holdout_plan();
stage7_1_hash = stage7_1_bundle_hash_local(repo_dir);
hashes = struct();
hashes.stage8_source_tree_hash = identity.stage8_source_tree_hash;
hashes.stage8_dependency_tree_hash = dependency.dependency_tree_hash;
hashes.stage8_controls_hash = stage8_stable_hash(controls);
hashes.stage8_measurement_plan_hash = stage8_stable_hash( ...
    measurement_registry, local_domain.domain_hash);
hashes.stage8_fit_contract_hash = stage8_stable_hash(fit_contract, solver);
hashes.stage8_calibration_plan_hash = calibration.calibration_plan_hash;
hashes.stage8_validation_plan_hash = validation.validation_plan_hash;
hashes.stage8_holdout_plan_hash = holdout.holdout_plan_hash;
hashes.stage7_1_evidence_bundle_hash = stage7_1_hash;
hashes.stage8_plan_hash = stage8_stable_hash( ...
    'STAGE8_LOCKED_PLAN_V2', opts.historical_baseline_commit, hashes);
plan = struct('historical_baseline_commit', ...
    opts.historical_baseline_commit, ...
    'runtime_head_commit', identity.runtime_head_commit, ...
    'matlab_release', 'R2022b', 'phase_factor', 1, ...
    'identity', identity, 'dependency_scope', dependency, ...
    'measurement_registry', measurement_registry, ...
    'measurement_model_registry', measurement_model_registry, ...
    'local_domain', local_domain, 'local_domain_hash', ...
    local_domain.domain_hash, 'solver', solver, ...
    'solver_contract_hash', stage8_stable_hash(solver), ...
    'fit_contract', fit_contract, 'controls', controls, ...
    'calibration', calibration, 'validation', validation, ...
    'holdout', holdout, 'hashes', hashes, ...
    'stage8_source_tree_hash', hashes.stage8_source_tree_hash, ...
    'stage8_dependency_tree_hash', hashes.stage8_dependency_tree_hash, ...
    'stage8_controls_hash', hashes.stage8_controls_hash, ...
    'stage8_measurement_plan_hash', hashes.stage8_measurement_plan_hash, ...
    'stage8_fit_contract_hash', hashes.stage8_fit_contract_hash, ...
    'stage8_calibration_plan_hash', hashes.stage8_calibration_plan_hash, ...
    'stage8_validation_plan_hash', hashes.stage8_validation_plan_hash, ...
    'stage8_holdout_plan_hash', hashes.stage8_holdout_plan_hash, ...
    'stage8_plan_hash', hashes.stage8_plan_hash, ...
    'stage7_1_evidence_bundle_hash', stage7_1_hash, ...
    'execution_status', 'STAGE8_1A_CODE_ONLY_NO_PERFORMANCE_RESULTS');
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('build_stage8_locked_plan:Options', 'opts must be a scalar struct.');
end
allowed = {'historical_baseline_commit','require_formal_runtime'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('build_stage8_locked_plan:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
if ~isfield(opts, 'historical_baseline_commit')
    opts.historical_baseline_commit = ...
        '386d1fe618455423ccce9855b53e2a1ed529f883';
end
if ~isfield(opts, 'require_formal_runtime')
    opts.require_formal_runtime = false;
end
end

function hash = stage7_1_bundle_hash_local(repo_dir)
path_now = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_5_1_stage7_closure_audit', 'results', ...
    'stage7_1_evidence_manifest.csv');
manifest = readtable(path_now, 'TextType', 'string');
hashes = unique(manifest.stage7_1_evidence_bundle_hash);
expected = "af40f8a7e8a0edfc7077594ebf08257cd0c7385d10902bc8dd624c83434bc322";
if ~isscalar(hashes) || hashes ~= expected
    error('build_stage8_locked_plan:Stage7Evidence', ...
        'The frozen Stage7.1 evidence identity changed.');
end
hash = char(hashes);
end

function repo_dir = repository_root_local()
[status, output] = system('git rev-parse --show-toplevel');
if status ~= 0
    error('build_stage8_locked_plan:Repository', ...
        'Unable to locate the Git repository root.');
end
repo_dir = strtrim(output);
end
