function plan = build_stage8_validation_plan()
%BUILD_STAGE8_VALIDATION_PLAN Freeze independent K1 and K2 validation.

plan = struct();
plan.K1 = struct('measurement_config_ids', ...
    ["PRIMARY_RECT_E14_A31";"SENSITIVITY_FULL_PARENT_5X5"], ...
    'L_values', [1,4,8], ...
    'noise_profile_ids', ["WHITE";"STAGE5_TOEPLITZ_CORRELATED"], ...
    'trials_per_stratum', 1000, 'trials_per_config', 6000, ...
    'center_bounds_deg', [7.5,8.5;9.7,10.3], ...
    'snr_bounds_db', [-12,12], 'seed', 20260722);
plan.K2 = struct('measurement_config_id', 'PRIMARY_RECT_E14_A31', ...
    'trial_count', 1200, 'seed', 20260724, ...
    'center_rule', 'UNIFORM_WITH_BOTH_ENDPOINTS_IN_LOCAL_DOMAIN', ...
    'separation_bounds_deg', [0.05,0.40], ...
    'separation_distribution', 'LOG_UNIFORM', ...
    'direction_bounds_rad', [0,2*pi], 'snr_bounds_db', [-9,9], ...
    'L_values', [1,4,8], 'secondary_power_db_values', [0,-6,-12], ...
    'correlation_magnitude_values', [0,0.9,0.99], ...
    'correlation_phase_bounds_rad', [0,2*pi], ...
    'noise_profile_ids', ["WHITE";"STAGE5_TOEPLITZ_CORRELATED"]);
plan.execution_status = 'FROZEN_NOT_EXECUTED_STAGE8_0';
plan.validation_plan_hash = stage8_stable_hash(plan.K1, plan.K2);
end
