function contract = build_stage8_bootstrap_mean_identity_contract()
%BUILD_STAGE8_BOOTSTRAP_MEAN_IDENTITY_CONTRACT Define the numeric contract.

contract = struct( ...
    'contract_version', 'STAGE8_BOOTSTRAP_MEAN_BACKWARD_ERROR_V1', ...
    'arithmetic_model', 'IEEE_754_BINARY64_ROUND_TO_NEAREST', ...
    'unit_roundoff', eps('double') / 2, ...
    'complex_product_real_operation_count', 6, ...
    'complex_accumulation_real_operation_count', 2, ...
    'complex_multiply_accumulate_ops_per_inner_term', 8, ...
    'independent_path_count', 2, ...
    'componentwise_ratio_pass_limit', 1, ...
    'gamma_definition', ...
    'gamma(q,d)=q*d*u/(1-q*d*u)', ...
    'complex_operation_count_basis', ...
    ['ONE_COMPLEX_PRODUCT_USES_FOUR_REAL_MULTIPLIES_AND_TWO_REAL_ADDS_', ...
    'AND_ACCUMULATION_USES_TWO_REAL_ADDS'], ...
    'independent_path_bound_basis', ...
    ['THE_DIFFERENCE_OF_TWO_INDEPENDENTLY_ROUNDED_PATHS_IS_BOUNDED_', ...
    'BY_THE_SUM_OF_THEIR_FORWARD_ERROR_BOUNDS'], ...
    'G_componentwise_scale_definition', ...
    'abs(T_I)*(abs(W_I)''*abs(A))', ...
    'mean_componentwise_scale_definition', ...
    'abs(T_I)*(abs(W_I)''*(abs(A)*abs(S_hat)))', ...
    'dimension_definition', ...
    'N=ELEMENT_ROWS_B=SEQUENTIAL_CHANNELS_K=FITTED_SOURCE_COUNT', ...
    'old_relative_metric_role', 'DIAGNOSTIC_ONLY_NOT_A_FORMAL_GATE', ...
    'fixed_relative_tolerance_role', 'PROHIBITED_IN_FORMAL_GATE');
contract.contract_hash = stage8_stable_hash( ...
    'STAGE8_BOOTSTRAP_MEAN_BACKWARD_ERROR_CONTRACT_HASH_V1', contract);
end
