function contract = build_stage8_threshold_contract(plan)
%BUILD_STAGE8_THRESHOLD_CONTRACT Bind thresholds to the frozen Stage8 plan.

required = {'identity','stage8_plan_hash','stage8_calibration_plan_hash', ...
    'measurement_model_registry'};
if ~(isstruct(plan) && isscalar(plan) && all(isfield(plan, required)) && ...
        isfield(plan.identity, 'stage8_stable_code_identity_hash') && ...
        isfield(plan.measurement_model_registry, 'registry_hash'))
    error('build_stage8_threshold_contract:Plan', ...
        'The frozen Stage8 plan does not expose threshold provenance.');
end
contract = struct( ...
    'stage8_stable_code_identity_hash', ...
    char(string(plan.identity.stage8_stable_code_identity_hash)), ...
    'stage8_plan_hash', char(string(plan.stage8_plan_hash)), ...
    'stage8_calibration_plan_hash', ...
    char(string(plan.stage8_calibration_plan_hash)), ...
    'measurement_registry_hash', ...
    char(string(plan.measurement_model_registry.registry_hash)));
validate_stage8_threshold_contract(contract);
end
