function [context, debug] = build_stage8_initialization_context_from_data( ...
    full_data, model, local_domain, stage5_locked, noise_model, opts)
%BUILD_STAGE8_INITIALIZATION_CONTEXT_FROM_DATA Run real Stage4/5 starts.

if nargin < 6 || isempty(opts)
    opts = struct();
end
opts = normalize_options_local(opts);
validate_inputs_local(full_data, model, local_domain, stage5_locked, noise_model);
start_clock = tic;
[singleton, conventional_debug] = conventional_start_local( ...
    full_data, model, local_domain, opts);
[stage4_data, group_model, shared] = prepare_group_data_local( ...
    full_data.Y_element, model, stage5_locked, noise_model, opts);
[q1, q1_debug] = run_group_stage_local( ...
    stage4_data, group_model, 1, local_domain, model, stage5_locked, ...
    noise_model, shared, [1, 2], opts);
[q2, q2_debug] = run_group_stage_local( ...
    stage4_data, group_model, 2, local_domain, model, stage5_locked, ...
    noise_model, shared, [1, 1], opts);

context = struct();
context.grouped_q1_kq1_angles_deg = q1.partition_angles{1};
context.conventional_singleton_peak_deg = singleton;
context.grouped_q1_kq2_angles_deg = q1.partition_angles{2};
context.grouped_q2_kq1_plus_kq1_angles_deg = q2.partition_angles{1};
context.grouped_q1_kq1_status = q1.partition_status{1};
context.conventional_singleton_status = conventional_debug.status;
context.grouped_q1_kq2_status = q1.partition_status{2};
context.grouped_q2_kq1_plus_kq1_status = q2.partition_status{1};
context.initialization_scope = 'DATA_DRIVEN_STAGE4_STAGE5_INITIALIZATION';
context.fixed_measurement_hash = model.fixed_measurement_hash;
context.local_domain_hash = local_domain.domain_hash;
context.stage5_configuration_hash = stage5_locked.configuration_hash;
context.observation_hash = stage8_stable_hash(full_data.Y_element);
context.factory_invocation_hash = stage8_stable_hash( ...
    'STAGE8_INITIALIZATION_FACTORY_V1', context.observation_hash, ...
    context.fixed_measurement_hash, context.local_domain_hash, ...
    context.stage5_configuration_hash);
context.simulation_metadata_used_flag = false;
context.num_score_eval = conventional_debug.num_score_eval + ...
    q1.num_score_eval + q2.num_score_eval;
context.num_svd = conventional_debug.num_svd + shared.num_svd + ...
    q1.num_svd + q2.num_svd;
context.runtime = toc(start_clock);
context.status_counters = struct( ...
    'registered_start_count', 4, ...
    'available_start_count', nnz([all(isfinite( ...
    context.grouped_q1_kq1_angles_deg(:))), ...
    all(isfinite(context.conventional_singleton_peak_deg(:))), ...
    all(isfinite(context.grouped_q1_kq2_angles_deg(:))), ...
    all(isfinite(context.grouped_q2_kq1_plus_kq1_angles_deg(:)))]), ...
    'group_stage_failure_count', nnz([~q1.stage_returned_flag, ...
    ~q2.stage_returned_flag]), ...
    'invalid_group_noise_scale_count', ...
    q1.invalid_group_noise_scale_count + ...
    q2.invalid_group_noise_scale_count);
context.invalid_group_noise_scale_count = ...
    context.status_counters.invalid_group_noise_scale_count;
context.group_noise_scale_status = ternary_local( ...
    context.invalid_group_noise_scale_count == 0, ...
    'ALL_GROUP_NOISE_SCALES_VALID', 'GROUP_NOISE_SCALE_INVALID');
context.phase_factor = 1;
debug = struct('conventional', conventional_debug, 'q1', q1_debug, ...
    'q2', q2_debug, 'shared', shared, ...
    'num_score_eval', context.num_score_eval, ...
    'num_svd', context.num_svd, 'runtime', context.runtime, ...
    'factory_invocation_hash', context.factory_invocation_hash, ...
    'phase_factor', 1);
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('build_stage8_initialization_context_from_data:Options', ...
        'opts must be a scalar struct.');
end
allowed = {'rank_multiplier'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('build_stage8_initialization_context_from_data:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
if ~isfield(opts, 'rank_multiplier')
    opts.rank_multiplier = 1;
end
end

function validate_inputs_local(data, model, domain, locked, noise)
data_fields = {'Y_element','Zseq_white','fixed_measurement_hash'};
model_fields = {'W_I','T_I','array_meta','array_configuration', ...
    'fixed_measurement_hash','phase_factor'};
domain_fields = {'az_grid_deg','el_grid_deg','candidate_points_deg', ...
    'domain_hash'};
locked_fields = {'az_beam_deg','el_beam_deg','configuration_hash'};
noise_fields = {'R_el','R_az'};
if ~(isstruct(data) && isscalar(data) && all(isfield(data, data_fields)) && ...
        isnumeric(data.Y_element) && ~isempty(data.Y_element) && ...
        all(isfinite(data.Y_element(:))))
    error('build_stage8_initialization_context_from_data:Data', ...
        'full_data must retain finite element and whitened observations.');
end
if ~(isstruct(model) && isscalar(model) && all(isfield(model, model_fields)) && ...
        model.phase_factor == 1 && strcmp(data.fixed_measurement_hash, ...
        model.fixed_measurement_hash))
    error('build_stage8_initialization_context_from_data:Model', ...
        'The data and factor-1 measurement model must have one identity.');
end
if ~(isstruct(domain) && isscalar(domain) && all(isfield(domain, domain_fields)))
    error('build_stage8_initialization_context_from_data:Domain', ...
        'local_domain is incomplete.');
end
if ~(isstruct(locked) && isscalar(locked) && all(isfield(locked, locked_fields)))
    error('build_stage8_initialization_context_from_data:Stage5Config', ...
        'stage5_locked is incomplete.');
end
if ~(isstruct(noise) && isscalar(noise) && all(isfield(noise, noise_fields)))
    error('build_stage8_initialization_context_from_data:Noise', ...
        'noise_model must expose the element covariance factors.');
end
end

function [angle, debug] = conventional_start_local(data, model, domain, opts)
candidates = sortrows(domain.candidate_points_deg, [1, 2]);
score = -Inf(size(candidates, 1), 1);
rank_now = zeros(size(candidates, 1), 1);
for candidate_index = 1:size(candidates, 1)
    [G_now, ~, info] = build_full_sequential_local_manifold( ...
        candidates(candidate_index, :), model, ...
        struct('rank_multiplier', opts.rank_multiplier));
    rank_now(candidate_index) = info.rank_Gseq;
    if info.rank_Gseq == 1
        score(candidate_index) = beamspace_dml_score_svd( ...
            data.Zseq_white, G_now, struct('requested_rank', 1, ...
            'rank_multiplier', opts.rank_multiplier, ...
            'compute_projector_checks', false));
    end
end
valid = isfinite(score) & rank_now == 1;
if any(valid)
    valid_index = find(valid);
    [~, relative_index] = max(score(valid));
    best_index = valid_index(relative_index);
    angle = candidates(best_index, :);
    status = 'CONVENTIONAL_SINGLETON_RETURNED';
else
    angle = NaN(1, 2);
    best_index = 0;
    status = 'CONVENTIONAL_SINGLETON_UNAVAILABLE';
end
debug = struct('status', status, 'best_index', best_index, ...
    'candidate_score', score, 'candidate_rank', rank_now, ...
    'num_score_eval', nnz(valid), ...
    'num_svd', size(candidates, 1) + nnz(valid), 'phase_factor', 1);
end

function [data, group_model, shared] = prepare_group_data_local( ...
    Y_element, model, locked, noise, opts)
N_el = size(noise.R_el, 1);
N_az = size(noise.R_az, 1);
L = size(Y_element, 2);
if size(Y_element, 1) ~= N_el * N_az
    error('build_stage8_initialization_context_from_data:ElementShape', ...
        'Element observations do not match the noise factors.');
end
Ycube = reshape(Y_element, N_el, N_az, L);
[Zel4, V] = form_elevation_dbf_cube( ...
    Ycube, locked.el_beam_deg, model.array_configuration);
Zel_raw = reshape(Zel4, numel(locked.el_beam_deg), N_az, L);
C_row = V' * noise.R_el * V;
[T_row, T_col, whitening] = build_separable_mmv_whiteners( ...
    C_row, noise.R_az, struct('rank_multiplier', opts.rank_multiplier));
[data, prepare_info] = prepare_elevation_group_mmv_data( ...
    Zel_raw, T_row, T_col, struct('phase_factor', 1, ...
    'observation_regime', 'NOISY_UNCALIBRATED', ...
    'column_covariance_model', 'REGISTERED_STAGE8_ELEMENT_COVARIANCE'));
group_model = struct('V', V, 'whitener', T_row, ...
    'z_el_m', (0:N_el - 1).' * model.array_configuration.arr.dz, ...
    'lambda', model.lambda, 'phase_factor', 1, ...
    'model_id', 'STAGE8_STAGE5_FIXED_ROW_WHITENED_ELEVATION_BEAMS');
shared = struct('Rphi_selected', noise.R_az, ...
    'aperture_index', 1:N_az, 'num_svd', 0, ...
    'whitening', whitening, 'prepare_info', prepare_info, ...
    'phase_factor', 1);
end

function [stage, debug] = run_group_stage_local(data, group_model, Q, ...
    domain, model, locked, noise, shared, partition_Kq, opts)
[estimate, estimate_debug] = estimate_elevation_groups_dml( ...
    data, Q, domain.el_grid_deg, group_model, ...
    struct('rank_multiplier', opts.rank_multiplier));
stage = struct('partition_angles', {cell(numel(partition_Kq) / Q, 1)}, ...
    'partition_status', {cell(numel(partition_Kq) / Q, 1)}, ...
    'stage_returned_flag', false, 'num_score_eval', estimate.num_score_eval, ...
    'num_svd', estimate.num_svd, 'invalid_group_noise_scale_count', 0);
partition_count = numel(partition_Kq) / Q;
for partition_index = 1:partition_count
    stage.partition_angles{partition_index} = NaN(sum( ...
        partition_Kq((partition_index - 1) * Q + (1:Q))), 2);
    stage.partition_status{partition_index} = 'GROUP_STAGE_UNAVAILABLE';
end
recovery_debug = struct('num_svd', 0, 'recovery_returned_flag', false);
noise_debug = struct('num_svd', 0);
conditional_debug = cell(partition_count, Q);
if ~(estimate.estimate_returned_flag && estimate.structural_gate_pass_flag)
    debug = struct('estimate', estimate, 'estimate_debug', estimate_debug, ...
        'recovery_debug', recovery_debug, 'noise_debug', noise_debug, ...
        'conditional_debug', {conditional_debug}, 'phase_factor', 1);
    return;
end
[Xphi, ~, recovery_debug] = recover_group_azimuth_data( ...
    data, estimate.Ge_hat, struct('rank_multiplier', opts.rank_multiplier));
[recovery_noise, noise_debug] = propagate_group_recovery_noise( ...
    estimate.Ge_hat, shared.Rphi_selected, ...
    struct('rank_multiplier', opts.rank_multiplier, 'phase_factor', 1));
stage.num_svd = stage.num_svd + recovery_debug.num_svd + noise_debug.num_svd;
if ~recovery_debug.recovery_returned_flag
    debug = struct('estimate', estimate, 'estimate_debug', estimate_debug, ...
        'recovery_debug', recovery_debug, 'noise_debug', noise_debug, ...
        'conditional_debug', {conditional_debug}, 'phase_factor', 1);
    return;
end
stage.stage_returned_flag = true;
for partition_index = 1:partition_count
    Kq_now = partition_Kq((partition_index - 1) * Q + (1:Q));
    angles = zeros(0, 2);
    returned = true;
    for group_index = 1:Q
        [estimate_az, chain_debug] = conditional_group_local( ...
            Xphi{group_index}, estimate.eta_hat_deg(group_index), ...
            Kq_now(group_index), model, domain, locked, noise, ...
            shared, estimate, recovery_noise, group_index, opts);
        conditional_debug{partition_index, group_index} = chain_debug;
        stage.invalid_group_noise_scale_count = ...
            stage.invalid_group_noise_scale_count + ...
            chain_debug.invalid_group_noise_scale_count;
        stage.num_score_eval = stage.num_score_eval + estimate_az.num_score_eval;
        stage.num_svd = stage.num_svd + estimate_az.num_svd;
        returned = returned && estimate_az.estimate_returned_flag;
        if estimate_az.estimate_returned_flag
            angles = [angles;estimate_az.az_hat_deg(:), ...
                repmat(estimate.eta_hat_deg(group_index), ...
                Kq_now(group_index), 1)]; %#ok<AGROW>
        end
    end
    if returned && size(angles, 1) == sum(Kq_now)
        stage.partition_angles{partition_index} = canonicalize_local(angles);
        stage.partition_status{partition_index} = ...
            'GROUPED_INITIALIZATION_RETURNED';
    else
        stage.partition_status{partition_index} = ...
            'GROUPED_INITIALIZATION_UNAVAILABLE';
    end
end
debug = struct('estimate', estimate, 'estimate_debug', estimate_debug, ...
    'recovery_debug', recovery_debug, 'noise_debug', noise_debug, ...
    'conditional_debug', {conditional_debug}, 'phase_factor', 1);
end

function [estimate, debug] = conditional_group_local(Xphi, eta, Kq, ...
    model, domain, locked, noise, shared, group_estimate, ...
    recovery_noise, group_index, opts)
[Uq, bank_info] = build_fixed_conditional_azimuth_beam_bank( ...
    locked.az_beam_deg, eta, model.array_meta, struct( ...
    'lambda', model.lambda, 'aperture_index', shared.aperture_index, ...
    'phase_factor', 1));
alpha_q = recovery_noise.group_noise_scale(group_index);
scale_contract = validate_stage8_group_noise_scale(alpha_q);
if ~scale_contract.start_available_flag
    estimate = unavailable_conditional_estimate_local(Kq);
    debug = struct('prepare', struct(), 'estimate', struct(), ...
        'group_noise_scale_status', scale_contract.status, ...
        'invalid_group_noise_scale_count', 1, ...
        'unit_fallback_used_flag', false, 'phase_factor', 1);
    return;
end
prepare_opts = struct('eta_condition_deg', eta, ...
    'condition_source', 'STAGE8_ESTIMATED_ELEVATION_GROUP', ...
    'upstream_group_support_status', group_estimate.support_status, ...
    'estimate_returned_flag', group_estimate.estimate_returned_flag, ...
    'structural_gate_pass_flag', group_estimate.structural_gate_pass_flag, ...
    'array_coordinates', bank_info.array_coordinates, ...
    'lambda', model.lambda, 'beam_bank_hash', bank_info.beam_bank_hash, ...
    'rank_multiplier', opts.rank_multiplier, 'phase_factor', 1);
[conditional_data, conditional_model, prepare_debug] = ...
    prepare_conditional_azimuth_data( ...
    Xphi, Uq, noise.R_az, scale_contract.scale, prepare_opts);
[estimate, estimate_debug] = estimate_conditional_azimuth_dml( ...
    conditional_data, Kq, domain, conditional_model, ...
    struct('rank_multiplier', opts.rank_multiplier));
debug = struct('prepare', prepare_debug, 'estimate', estimate_debug, ...
    'group_noise_scale_status', scale_contract.status, ...
    'invalid_group_noise_scale_count', 0, ...
    'unit_fallback_used_flag', false, 'phase_factor', 1);
end

function estimate = unavailable_conditional_estimate_local(Kq)
estimate = struct('az_hat_deg', NaN(Kq, 1), ...
    'estimate_returned_flag', false, 'num_score_eval', 0, 'num_svd', 0, ...
    'status', 'GROUP_NOISE_SCALE_INVALID');
end

function angles = canonicalize_local(angles)
[~, order] = sortrows([angles(:, 2), angles(:, 1)], [1, 2]);
angles = angles(order, :);
end

function value = ternary_local(condition, yes_value, no_value)
if condition
    value = yes_value;
else
    value = no_value;
end
end
