function plan = build_stage8_calibration_plan(model_registry)
%BUILD_STAGE8_CALIBRATION_PLAN Freeze the offline K1 calibration registry.

if nargin < 1 || isempty(model_registry)
    model_registry = build_stage8_measurement_registry(sim_cfg(), struct());
end
data_seed_base = 2026072100;
bootstrap_seed_base = 2126072100;
seed_block_stride = 1000;
config_ids = ["PRIMARY_RECT_E14_A31"; ...
    "SENSITIVITY_FULL_PARENT_5X5"];
centers = [8.0,10.0;7.6,9.8;7.6,10.2;8.4,9.8;8.4,10.2];
snr_db = [-12,-6,0,6,12];
snapshot_counts = [1,4,8];
noise_ids = ["WHITE";"STAGE5_TOEPLITZ_CORRELATED"];
rows = cell(300, 1);
row_index = 0;
for config_index = 1:numel(config_ids)
    cell_index = 0;
    for center_index = 1:size(centers, 1)
        for snr_index = 1:numel(snr_db)
            for snapshot_index = 1:numel(snapshot_counts)
                for noise_index = 1:numel(noise_ids)
                    row_index = row_index + 1;
                    cell_index = cell_index + 1;
                    bootstrap_seed_start = bootstrap_seed_base + ...
                        seed_block_stride * (row_index - 1);
                    model = resolve_stage8_measurement_model(model_registry, ...
                        config_ids(config_index), noise_ids(noise_index));
                    rows{row_index} = struct( ...
                        'measurement_config_id', config_ids(config_index), ...
                        'calibration_cell_id', sprintf('C%d_%03d', ...
                        config_index, cell_index), ...
                        'center_az_deg', centers(center_index, 1), ...
                        'center_el_deg', centers(center_index, 2), ...
                        'snr_db', snr_db(snr_index), ...
                        'L', snapshot_counts(snapshot_index), ...
                        'noise_profile_id', noise_ids(noise_index), ...
                        'model_key', string(model.model_key), ...
                        'fixed_measurement_hash', ...
                        string(model.fixed_measurement_hash), ...
                        'Bboot_per_cell', 199, ...
                        'global_cell_index', row_index, ...
                        'calibration_data_seed', data_seed_base + row_index - 1, ...
                        'bootstrap_seed_start', bootstrap_seed_start, ...
                        'bootstrap_seed_end', bootstrap_seed_start + 198, ...
                        'seed_block_stride', seed_block_stride, ...
                        'bootstrap_seed_formula', ...
                        "bootstrap_seed_start + bootstrap_index - 1");
                end
            end
        end
    end
end
cells = struct2table(vertcat(rows{:}));
plan = struct('cells', cells, 'alpha', 0.05, ...
    'Bboot_per_cell', 199, ...
    'calibration_data_seed_base', data_seed_base, ...
    'calibration_bootstrap_seed_base', bootstrap_seed_base, ...
    'calibration_seed_block_stride', seed_block_stride, ...
    'quantile_rule', 'TYPE1_ORDER_STATISTIC', ...
    'threshold_policy', ...
    'ONE_GLOBAL_THRESHOLD_PER_FIXED_MEASUREMENT_CONFIG', ...
    'cell_count_per_config', 150, 'bootstrap_count_per_config', 29850, ...
    'total_bootstrap_count', 59700, ...
    'execution_status', 'FROZEN_NOT_EXECUTED_STAGE8_1A', ...
    'calibration_plan_hash', stage8_stable_hash(cells, 0.05, 199, ...
    'TYPE1_ORDER_STATISTIC'));
end
