function registry = build_stage8_measurement_registry(cfg, opts)
%BUILD_STAGE8_MEASUREMENT_REGISTRY Build four frozen config/noise models.

if nargin < 1 || isempty(cfg)
    cfg = sim_cfg();
end
if nargin < 2 || isempty(opts)
    opts = struct();
end
if ~(isstruct(opts) && isscalar(opts)) || ...
        ~isempty(setdiff(fieldnames(opts), {'pool','subset_family'}))
    error('build_stage8_measurement_registry:Options', ...
        'opts may contain only pool and subset_family.');
end
if ~isfield(opts, 'pool') || isempty(opts.pool)
    pool = build_stage7_candidate_pool(cfg);
else
    pool = opts.pool;
end
if ~isfield(opts, 'subset_family') || isempty(opts.subset_family)
    family = enumerate_stage7_rectangular_subsets(pool, cfg);
else
    family = opts.subset_family;
end
config_ids = ["PRIMARY_RECT_E14_A31"; ...
    "SENSITIVITY_FULL_PARENT_5X5"];
noise_ids = ["WHITE";"STAGE5_TOEPLITZ_CORRELATED"];
entries = cell(4, 1);
rows = cell(4, 1);
row_index = 0;
for config_index = 1:numel(config_ids)
    for noise_index = 1:numel(noise_ids)
        row_index = row_index + 1;
        noise = build_stage7_noise_covariance(noise_ids(noise_index), ...
            cfg, struct('rho_el', 0.45, 'rho_az', 0.70));
        [model, debug] = build_stage8_measurement_model( ...
            config_ids(config_index), noise_ids(noise_index), cfg, ...
            struct('pool', pool, 'subset_family', family, 'noise', noise));
        entries{row_index} = model;
        rows{row_index} = struct( ...
            'measurement_config_id', string(model.measurement_config_id), ...
            'noise_profile_id', string(model.noise_profile_id), ...
            'model_key', string(model.model_key), ...
            'fixed_measurement_hash', string(model.fixed_measurement_hash), ...
            'subset_id', string(model.subset_id), ...
            'B_el', debug.B_el, 'B_az', debug.B_az, ...
            'B_out', debug.B_out, ...
            'whitening_rank', model.whitening_rank, ...
            'noise_factorization_hash', ...
            string(model.noise_factorization.factorization_hash), ...
            'array_geometry_hash', string(pool.array_geometry_hash), ...
            'phase_factor', 1);
    end
end
entries = vertcat(entries{:});
registry_table = struct2table(vertcat(rows{:}));
if height(registry_table) ~= 4 || ...
        numel(unique(registry_table.model_key)) ~= 4 || ...
        numel(unique(registry_table.fixed_measurement_hash)) ~= 4
    error('build_stage8_measurement_registry:Cardinality', ...
        'The formal registry must contain four distinct config/noise models.');
end
registry_hash = stage8_stable_hash( ...
    'STAGE8_MEASUREMENT_REGISTRY_V1', registry_table);
registry = struct('entries', entries, 'table', registry_table, ...
    'registry_hash', registry_hash, 'entry_count', 4, ...
    'registry_version', 'STAGE8_MEASUREMENT_REGISTRY_V1', ...
    'phase_factor', 1);
end
