function plan = build_stage8_holdout_plan()
%BUILD_STAGE8_HOLDOUT_PLAN Freeze independent Stage8.2 evaluation contracts.

plan = struct();
plan.K1 = struct('distribution_id', 'SAME_AS_K1_VALIDATION', ...
    'seed', 20260723, 'trials_per_config', 6000, ...
    'threshold_recalibration_allowed', false);
plan.K2 = struct('distribution_id', 'SAME_AS_K2_VALIDATION', ...
    'measurement_config_id', 'PRIMARY_RECT_E14_A31', ...
    'seed', 20260725, 'trial_count', 2000, ...
    'threshold_recalibration_allowed', false);
plan.full_parent_sensitivity = struct('K1_count', 600, 'K2_count', 600, ...
    'paired_realization_required', true, ...
    'measurement_config_id', 'SENSITIVITY_FULL_PARENT_5X5');
plan.mismatch = struct('seed', 20260726, 'trials_per_type', 200, ...
    'mismatch_ids', ["M0_COVARIANCE";"M1_GAIN_PHASE"; ...
    "M2_POSITION";"M3_CHANNEL_FAILURE"], ...
    'covariance_true_rho', [0.55,0.80], ...
    'covariance_fit_rho', [0.45,0.70], ...
    'gain_std_db', 0.5, 'phase_std_deg', 5, ...
    'position_std_lambda', 0.02, 'element_failure_fraction', 0.02);
plan.stage5_boundary = struct('scenario_id', ...
    'STAGE5_COHERENT_WEAK', 'trial_count', 200, ...
    'paired_measurement_configs', true);
plan.gates = struct('alpha', 0.05, 'beta', 0.05, ...
    'K1_overall_false_split_wilson_upper', 0.07, ...
    'K1_stratum_false_split_wilson_upper', 0.08, ...
    'K1_false_resolved_wilson_upper', 0.07, ...
    'K2_normal_resolved_wilson_lower', 0.80, ...
    'K2_normal_missed_split_wilson_upper', 0.10, ...
    'K2_false_resolved_wilson_upper', 0.07, ...
    'separation_coverage_wilson_lower', 0.90, ...
    'mismatch_wrong_confidence_wilson_upper', 0.10);
plan.execution_status = 'FROZEN_NOT_EXECUTED_STAGE8_0';
plan.holdout_plan_hash = stage8_stable_hash(plan.K1, plan.K2, ...
    plan.full_parent_sensitivity, plan.mismatch, plan.stage5_boundary, ...
    plan.gates);
end
