function [artifact, debug] = calibrate_global_bootstrap_threshold( ...
    calibration_cells, local_domain, model_registry, opts)
%CALIBRATE_GLOBAL_BOOTSTRAP_THRESHOLD Refit K1/K2 and take max cell quantile.

if nargin < 4 || isempty(opts)
    opts = struct();
end
opts = normalize_options_local(opts);
if isempty(opts.expected_contract)
    if opts.formal_run
        error('calibrate_global_bootstrap_threshold:ThresholdContract', ...
            'Formal calibration requires the current threshold contract.');
    end
    opts.expected_contract = struct( ...
        'stage8_stable_code_identity_hash', 'SYNTHETIC_UNIT_SOURCE', ...
        'stage8_plan_hash', 'SYNTHETIC_UNIT_STAGE8_PLAN', ...
        'stage8_calibration_plan_hash', 'SYNTHETIC_UNIT_CALIBRATION_PLAN', ...
        'measurement_registry_hash', 'SYNTHETIC_UNIT_MEASUREMENT_REGISTRY');
end
contract = validate_stage8_threshold_contract(opts.expected_contract);
cells = normalize_cells_local(calibration_cells);
config_ids = unique(string({cells.measurement_config_id}));
if ~isscalar(config_ids)
    error('calibrate_global_bootstrap_threshold:MeasurementConfig', ...
        'One invocation calibrates exactly one fixed measurement configuration.');
end
if opts.formal_run && (opts.Bboot_per_cell ~= 199 || numel(cells) ~= 150)
    error('calibrate_global_bootstrap_threshold:FormalPlan', ...
        'Formal calibration requires 150 cells and 199 samples per cell.');
end
if opts.formal_run && ~is_stage8_registry_local(model_registry)
    error('calibrate_global_bootstrap_threshold:FormalRegistry', ...
        'Formal calibration requires the four-entry noise-specific registry.');
end
if opts.formal_run && numel(unique(string({cells.noise_profile_id}))) ~= 2
    error('calibrate_global_bootstrap_threshold:FormalNoiseCoverage', ...
        'A formal config threshold must aggregate both noise profiles.');
end
lambda = NaN(opts.Bboot_per_cell, numel(cells));
cell_quantile = NaN(numel(cells), 1);
k1_fit_count = 0;
k2_fit_count = 0;
score_calls = 0;
svd_calls = 0;
start_clock = tic;
for cell_index = 1:numel(cells)
    model = resolve_cell_model_local( ...
        model_registry, cells(cell_index), opts.formal_run);
    verify_cell_model_local(cells(cell_index), model);
    context = build_context_local(cells(cell_index), ...
        cells(cell_index).full_data, model, local_domain, opts);
    [fit1, ~] = fit_local_model_k(cells(cell_index).full_data, 1, ...
        local_domain, model, context, opts.fit_options);
    k1_fit_count = k1_fit_count + 1;
    score_calls = score_calls + fit1.num_score_eval;
    svd_calls = svd_calls + fit1.num_svd;
    [valid1, validity1] = validate_stage8_fit_for_lrt(fit1, 1, ...
        struct('fixed_measurement_hash', model.fixed_measurement_hash, ...
        'local_domain_hash', local_domain.domain_hash));
    if ~valid1
        error('calibrate_global_bootstrap_threshold:OriginalK1Fit', ...
            'Calibration cell %d rejected K1 status %s.', ...
            cell_index, validity1.status);
    end
    for bootstrap_index = 1:opts.Bboot_per_cell
        seed = bootstrap_seed_local(cells(cell_index), bootstrap_index);
        if isfield(model, 'Rn_elem')
            [boot_data, ~] = simulate_bootstrap_under_k1(fit1, model, ...
                struct('seed', seed, 'formal_run', opts.formal_run));
        else
            [boot_data, ~] = simulate_bootstrap_under_k1( ...
                fit1, struct('seed', seed));
        end
        boot_context = build_context_local(cells(cell_index), ...
            boot_data, model, local_domain, opts);
        [fit1_boot, ~] = fit_local_model_k(boot_data, 1, ...
            local_domain, model, boot_context, opts.fit_options);
        boot_context.k1_fit = fit1_boot;
        [fit2_boot, ~] = fit_local_model_k(boot_data, 2, ...
            local_domain, model, boot_context, opts.fit_options);
        k1_fit_count = k1_fit_count + 1;
        k2_fit_count = k2_fit_count + 1;
        score_calls = score_calls + fit1_boot.num_score_eval + ...
            fit2_boot.num_score_eval;
        svd_calls = svd_calls + fit1_boot.num_svd + fit2_boot.num_svd;
        [valid1_boot, validity1_boot] = validate_stage8_fit_for_lrt( ...
            fit1_boot, 1, struct('fixed_measurement_hash', ...
            model.fixed_measurement_hash, 'local_domain_hash', ...
            local_domain.domain_hash));
        expected2 = struct('fixed_measurement_hash', ...
            fit1_boot.fixed_measurement_hash, 'local_domain_hash', ...
            fit1_boot.local_domain_hash, 'solver_contract_hash', ...
            fit1_boot.solver_contract_hash, 'observation_hash', ...
            fit1_boot.observation_hash);
        [valid2_boot, validity2_boot] = validate_stage8_fit_for_lrt( ...
            fit2_boot, 2, expected2);
        if ~(valid1_boot && valid2_boot)
            error('calibrate_global_bootstrap_threshold:BootstrapRefit', ...
                'Bootstrap validity failed: %s/%s.', ...
                validity1_boot.status, validity2_boot.status);
        end
        [lrt, ~] = nested_dml_likelihood_ratio(fit1_boot, fit2_boot, struct());
        if ~strcmp(lrt.lrt_status, 'OK')
            error('calibrate_global_bootstrap_threshold:BootstrapRefit', ...
                'A bootstrap K1/K2 refit did not satisfy the nested LRT contract.');
        end
        lambda(bootstrap_index, cell_index) = lrt.lambda_12;
    end
    cell_quantile(cell_index) = stage8_type1_quantile( ...
        lambda(:, cell_index), 1 - opts.alpha);
end
cell_ids = string({cells.calibration_cell_id}).';
cell_table = table(cell_ids, cell_quantile, ...
    'VariableNames', {'calibration_cell_id','q_cell_0p95'});
q_global = max(cell_quantile);
calibration_hash = stage8_stable_hash(config_ids, opts.alpha, ...
    opts.Bboot_per_cell, 'TYPE1_ORDER_STATISTIC', cell_table, lambda);
artifact = struct( ...
    'stage8_stable_code_identity_hash', ...
    contract.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', contract.stage8_plan_hash, ...
    'stage8_calibration_plan_hash', ...
    contract.stage8_calibration_plan_hash, ...
    'measurement_registry_hash', contract.measurement_registry_hash, ...
    'measurement_config_id', char(config_ids), ...
    'q_global', q_global, 'alpha', opts.alpha, ...
    'Bboot_per_cell', opts.Bboot_per_cell, ...
    'quantile_rule', 'TYPE1_ORDER_STATISTIC', ...
    'threshold_policy', ...
    'ONE_GLOBAL_THRESHOLD_PER_FIXED_MEASUREMENT_CONFIG', ...
    'cell_quantiles', cell_table, 'calibration_hash', calibration_hash, ...
    'source_identity', contract.stage8_stable_code_identity_hash, ...
    'threshold_status', 'LOCKED_BOOTSTRAP_THRESHOLD', ...
    'threshold_artifact_hash', '', ...
    'artifact_scope', ternary_local(opts.formal_run, ...
    'FORMAL_STAGE8_1', 'SYNTHETIC_UNIT_TEST_ONLY'));
artifact.threshold_artifact_hash = stage8_threshold_artifact_hash(artifact);
debug = struct('lambda_samples', lambda, 'cell_count', numel(cells), ...
    'bootstrap_sample_count', numel(lambda), ...
    'K1_fit_count', k1_fit_count, 'K2_fit_count', k2_fit_count, ...
    'score_call_count', score_calls, 'svd_call_count', svd_calls, ...
    'runtime', toc(start_clock), 'complete_refit_flag', ...
    k2_fit_count == numel(lambda) && ...
    k1_fit_count == numel(lambda) + numel(cells));
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('calibrate_global_bootstrap_threshold:Options', ...
        'opts must be a scalar struct.');
end
allowed = {'alpha','Bboot_per_cell','formal_run','fit_options', ...
    'stage5_locked_config','expected_contract'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('calibrate_global_bootstrap_threshold:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
defaults = struct('alpha', 0.05, 'Bboot_per_cell', 199, ...
    'formal_run', false, 'fit_options', struct(), ...
    'stage5_locked_config', build_stage8_stage5_locked_config(), ...
    'expected_contract', []);
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(opts, names{index})
        opts.(names{index}) = defaults.(names{index});
    end
end
end

function cells = normalize_cells_local(input)
if iscell(input)
    cells = vertcat(input{:});
elseif isstruct(input)
    cells = input(:);
else
    error('calibrate_global_bootstrap_threshold:Cells', ...
        'calibration_cells must be a struct array or cell array of structs.');
end
required = {'measurement_config_id','calibration_cell_id','full_data'};
if isempty(cells) || ~all(isfield(cells, required))
    error('calibrate_global_bootstrap_threshold:CellContract', ...
        'Every calibration cell must expose data and its registered ID.');
end
has_seed = all(arrayfun(@(x) isfield(x, 'bootstrap_seed_start') || ...
    isfield(x, 'seed'), cells));
if ~has_seed
    error('calibrate_global_bootstrap_threshold:Seed', ...
        'Every cell needs a registered bootstrap seed start.');
end
end

function flag = is_stage8_registry_local(registry)
flag = isstruct(registry) && isscalar(registry) && ...
    all(isfield(registry, {'entries','table','entry_count'})) && ...
    registry.entry_count == 4;
end

function model = resolve_cell_model_local(registry, cell_now, formal_run)
if is_stage8_registry_local(registry)
    if ~isfield(cell_now, 'noise_profile_id')
        error('calibrate_global_bootstrap_threshold:NoiseProfile', ...
            'Registry-backed cells must expose noise_profile_id.');
    end
    model = resolve_stage8_measurement_model(registry, ...
        cell_now.measurement_config_id, cell_now.noise_profile_id);
elseif formal_run
    error('calibrate_global_bootstrap_threshold:FormalRegistry', ...
        'Formal calibration cannot use a single measurement model.');
else
    model = registry;
end
end

function verify_cell_model_local(cell_now, model)
if ~strcmp(cell_now.full_data.fixed_measurement_hash, ...
        model.fixed_measurement_hash)
    error('calibrate_global_bootstrap_threshold:MeasurementHash', ...
        'Cell data and resolved noise-specific model identities differ.');
end
if isfield(cell_now, 'model_key') && ...
        ~strcmp(cell_now.model_key, model.model_key)
    error('calibrate_global_bootstrap_threshold:ModelKey', ...
        'Cell model_key does not match the registry.');
end
end

function context = build_context_local(cell_now, data, model, domain, opts)
if opts.formal_run
    context = build_stage8_initialization_context_from_data( ...
        data, model, domain, opts.stage5_locked_config, ...
        model.noise_factorization, struct());
elseif isfield(cell_now, 'initialization_factory') && ...
        isa(cell_now.initialization_factory, 'function_handle')
    context = cell_now.initialization_factory(data);
else
    context = build_stage8_initialization_context_from_data( ...
        data, model, domain, opts.stage5_locked_config, ...
        model.noise_factorization, struct());
end
end

function seed = bootstrap_seed_local(cell_now, bootstrap_index)
if isfield(cell_now, 'bootstrap_seed_start')
    seed = cell_now.bootstrap_seed_start + bootstrap_index - 1;
else
    seed = cell_now.seed + bootstrap_index - 1;
end
end

function value = ternary_local(condition, yes_value, no_value)
if condition
    value = yes_value;
else
    value = no_value;
end
end
