function scope = collect_stage8_dependency_scope(repo_dir)
%COLLECT_STAGE8_DEPENDENCY_SCOPE Freeze the upstream interfaces Stage8 uses.

if nargin < 1 || isempty(repo_dir)
    repo_dir = repository_root_local();
end
paths = [ ...
    "beamspace_ml_v18/source/stepwise_signal_model/core/config/sim_cfg.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/core/array/arr_cyl.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_1_sequential_dbf_model/common/form_elevation_dbf_cube.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_2_stable_dml_backend/common/beamspace_dml_score_svd.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_2_stable_dml_backend/common/concentrated_dml_rss.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_2_stable_dml_backend/common/build_psd_whitener.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_2_stable_dml_backend/common/stable_numeric_rank.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/estimate_elevation_groups_dml.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/estimate_conditional_azimuth_dml.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/build_separable_mmv_whiteners.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/prepare_elevation_group_mmv_data.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/recover_group_azimuth_data.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/propagate_group_recovery_noise.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/build_fixed_conditional_azimuth_beam_bank.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/prepare_conditional_azimuth_data.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/prepare_full_sequential_dml_data.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/build_full_sequential_local_manifold.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/refine_joint_sequential_dml.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/build_common_registered_local_domain.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_4_near_pair_tangent_asymptotics/common/compute_projected_jacobian_metric.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_exact_subset_fim_beam_design/common/build_stage7_candidate_pool.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_exact_subset_fim_beam_design/common/enumerate_stage7_rectangular_subsets.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_exact_subset_fim_beam_design/common/build_exact_subset_model.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_exact_subset_fim_beam_design/common/build_stage7_noise_covariance.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_exact_subset_fim_beam_design/common/build_stage7_element_manifold.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_exact_subset_fim_beam_design/common/construct_deterministic_source_matrix.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_exact_subset_fim_beam_design/common/stage7_stable_hash.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_exact_subset_fim_beam_design/results/stage7_plan_registry.csv"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_5_1_stage7_closure_audit/results/stage7_1_evidence_manifest.csv"];
manifest = stage8_git_blob_manifest(repo_dir, paths);
if height(manifest) ~= numel(paths)
    error('collect_stage8_dependency_scope:MissingDependency', ...
        'Every registered Stage8 dependency must have one tracked Git identity.');
end
scope = struct('manifest', manifest, ...
    'dependency_tree_hash', stage8_stable_hash(manifest), ...
    'scope_version', 'STAGE8_DEPENDENCY_SCOPE_V2', ...
    'path_count', height(manifest));
end

function repo_dir = repository_root_local()
[status, output] = system('git rev-parse --show-toplevel');
if status ~= 0
    error('collect_stage8_dependency_scope:Repository', ...
        'Unable to locate the Git repository root.');
end
repo_dir = strtrim(output);
end
