function evaluation = evaluate_stage8_bootstrap_mean_identity(fit, model)
%EVALUATE_STAGE8_BOOTSTRAP_MEAN_IDENTITY Bound equivalent mean paths.

contract = build_stage8_bootstrap_mean_identity_contract();
validate_inputs_local(fit, model);
W_alias_pass = isequal(model.Wseq, model.W_I);
T_alias_pass = isequal(model.Tseq, model.T_I);
fixed_measurement_pass = strcmp(fit.fixed_measurement_hash, ...
    model.fixed_measurement_hash) && fit.phase_factor == 1 && ...
    model.phase_factor == 1;

manifold = build_stage8_element_manifold(fit.angles_hat_deg, model);
A = manifold.A;
G_rebuilt = model.T_I * (model.W_I' * A);
mean_element = A * fit.S_hat;
mean_white_element = model.T_I * (model.W_I' * mean_element);
mean_white_rebuilt = G_rebuilt * fit.S_hat;
mean_white_fit = fit.G_hat * fit.S_hat;

N = size(A, 1);
B = size(model.W_I, 2);
K = size(A, 2);
q = contract.complex_multiply_accumulate_ops_per_inner_term;
u = contract.unit_roundoff;
gamma_N = gamma_local(q, N, u);
gamma_B = gamma_local(q, B, u);
gamma_K = gamma_local(q, K, u);
gamma_G_path = (1 + gamma_N) * (1 + gamma_B) - 1;
gamma_mean_path = (1 + gamma_K) * (1 + gamma_N) * ...
    (1 + gamma_B) - 1;

G_componentwise_residual = abs(G_rebuilt - fit.G_hat);
G_backward_scale = abs(model.T_I) * (abs(model.W_I)' * abs(A));
G_backward_bound = contract.independent_path_count * ...
    gamma_G_path * G_backward_scale;
G_componentwise_bound_ratio = ratio_local( ...
    G_componentwise_residual, G_backward_bound);
G_max_bound_ratio = max(G_componentwise_bound_ratio(:));
G_numeric_pass = G_max_bound_ratio <= ...
    contract.componentwise_ratio_pass_limit;
G_identity_pass = W_alias_pass && T_alias_pass && ...
    fixed_measurement_pass && G_numeric_pass;

mean_element_rebuilt_residual = abs( ...
    mean_white_element - mean_white_rebuilt);
mean_rebuilt_fit_residual = abs(mean_white_rebuilt - mean_white_fit);
mean_componentwise_residual = max( ...
    mean_element_rebuilt_residual, mean_rebuilt_fit_residual);
mean_backward_scale = abs(model.T_I) * ...
    (abs(model.W_I)' * (abs(A) * abs(fit.S_hat)));
mean_backward_bound = contract.independent_path_count * ...
    gamma_mean_path * mean_backward_scale;
mean_element_rebuilt_bound_ratio = ratio_local( ...
    mean_element_rebuilt_residual, mean_backward_bound);
mean_rebuilt_fit_bound_ratio = ratio_local( ...
    mean_rebuilt_fit_residual, mean_backward_bound);
mean_componentwise_bound_ratio = max( ...
    mean_element_rebuilt_bound_ratio, mean_rebuilt_fit_bound_ratio);
mean_max_bound_ratio = max(mean_componentwise_bound_ratio(:));
mean_identity_pass = mean_max_bound_ratio <= ...
    contract.componentwise_ratio_pass_limit;

if ~G_identity_pass
    failure_status = 'STRUCTURAL_MANIFOLD_IDENTITY_FAILURE';
elseif ~mean_identity_pass
    failure_status = 'NUMERICAL_MEAN_BACKWARD_ERROR_FAILURE';
else
    failure_status = 'BOOTSTRAP_MEAN_IDENTITY_PASS';
end

G_absolute_residual = norm(G_rebuilt - fit.G_hat, 'fro');
mean_absolute_residual = max( ...
    norm(mean_white_element - mean_white_rebuilt, 'fro'), ...
    norm(mean_white_rebuilt - mean_white_fit, 'fro'));
evaluation = struct( ...
    'contract_version', contract.contract_version, ...
    'contract_hash', contract.contract_hash, 'contract', contract, ...
    'A_rebuilt', A, 'G_rebuilt', G_rebuilt, ...
    'mean_white_element', mean_white_element, ...
    'mean_white_rebuilt', mean_white_rebuilt, ...
    'mean_white_fit', mean_white_fit, ...
    'G_absolute_residual', G_absolute_residual, ...
    'G_old_relative_residual', G_absolute_residual / ...
    max(norm(fit.G_hat, 'fro'), realmin), ...
    'G_componentwise_residual', G_componentwise_residual, ...
    'G_backward_scale', G_backward_scale, ...
    'G_backward_bound', G_backward_bound, ...
    'G_absolute_bound', norm(G_backward_bound, 'fro'), ...
    'G_componentwise_bound_ratio', G_componentwise_bound_ratio, ...
    'G_max_bound_ratio', G_max_bound_ratio, ...
    'G_identity_pass', G_identity_pass, ...
    'mean_absolute_residual', mean_absolute_residual, ...
    'mean_old_relative_residual', norm( ...
    mean_white_element - mean_white_fit, 'fro') / ...
    max(norm(mean_white_fit, 'fro'), realmin), ...
    'mean_componentwise_residual', mean_componentwise_residual, ...
    'mean_element_rebuilt_residual', mean_element_rebuilt_residual, ...
    'mean_rebuilt_fit_residual', mean_rebuilt_fit_residual, ...
    'mean_backward_scale', mean_backward_scale, ...
    'mean_backward_bound', mean_backward_bound, ...
    'mean_absolute_bound', norm(mean_backward_bound, 'fro'), ...
    'mean_componentwise_bound_ratio', mean_componentwise_bound_ratio, ...
    'mean_element_rebuilt_bound_ratio', ...
    mean_element_rebuilt_bound_ratio, ...
    'mean_rebuilt_fit_bound_ratio', mean_rebuilt_fit_bound_ratio, ...
    'mean_max_bound_ratio', mean_max_bound_ratio, ...
    'mean_identity_pass', mean_identity_pass, ...
    'fitted_mean_norm', norm(mean_white_fit, 'fro'), ...
    'W_alias_pass', W_alias_pass, 'T_alias_pass', T_alias_pass, ...
    'fixed_measurement_pass', fixed_measurement_pass, ...
    'angles_source', 'fit.angles_hat_deg', ...
    'phase_factor', model.phase_factor, ...
    'element_dimension_N', N, 'sequential_dimension_B', B, ...
    'source_dimension_K', K, 'gamma_N', gamma_N, ...
    'gamma_B', gamma_B, 'gamma_K', gamma_K, ...
    'gamma_G_path', gamma_G_path, ...
    'gamma_mean_path', gamma_mean_path, ...
    'overall_pass', G_identity_pass && mean_identity_pass, ...
    'failure_status', failure_status);
end

function validate_inputs_local(fit, model)
fit_fields = {'K','angles_hat_deg','G_hat','S_hat', ...
    'fixed_measurement_hash','phase_factor'};
model_fields = {'Wseq','W_I','Tseq','T_I','fixed_measurement_hash', ...
    'phase_factor','array_meta','array_configuration','lambda', ...
    'element_order'};
if ~(isstruct(fit) && isscalar(fit) && all(isfield(fit, fit_fields)) && ...
        isstruct(model) && isscalar(model) && ...
        all(isfield(model, model_fields)))
    error('evaluate_stage8_bootstrap_mean_identity:Contract', ...
        'fit and model must expose the complete mean-identity contract.');
end
K = fit.K;
numeric_values = {fit.angles_hat_deg, fit.G_hat, fit.S_hat, ...
    model.Wseq, model.W_I, model.Tseq, model.T_I};
all_double = all(cellfun(@(value) isa(value, 'double'), numeric_values));
all_finite = all(cellfun(@(value) all(isfinite(value(:))), numeric_values));
shape_pass = isscalar(K) && any(K == [1, 2]) && ...
    isequal(size(fit.angles_hat_deg), [K, 2]) && ...
    size(fit.S_hat, 1) == K && size(fit.G_hat, 2) == K && ...
    size(model.Wseq, 1) == size(model.W_I, 1) && ...
    size(model.Wseq, 2) == size(model.W_I, 2) && ...
    size(model.Tseq, 1) == size(model.T_I, 1) && ...
    size(model.Tseq, 2) == size(model.T_I, 2) && ...
    size(model.W_I, 1) > 0 && size(model.W_I, 2) > 0 && ...
    size(model.T_I, 2) == size(model.W_I, 2) && ...
    size(fit.G_hat, 1) == size(model.T_I, 1);
if ~(all_double && all_finite && shape_pass)
    error('evaluate_stage8_bootstrap_mean_identity:Shape', ...
        'The mean-identity matrices must be finite binary64 arrays of matching shape.');
end
end

function gamma = gamma_local(operation_count, inner_dimension, unit_roundoff)
x = operation_count * inner_dimension * unit_roundoff;
if ~(isfinite(x) && x < 1)
    error('evaluate_stage8_bootstrap_mean_identity:GammaDomain', ...
        'The dimension-derived gamma bound requires q*d*u < 1.');
end
gamma = x / (1 - x);
end

function ratio = ratio_local(residual, bound)
ratio = zeros(size(residual));
positive = bound > 0;
ratio(positive) = residual(positive) ./ bound(positive);
ratio(~positive & residual > 0) = Inf;
end
