function [fit, debug] = fit_local_model_k( ...
    full_data, K, local_domain, model, init_context, opts)
%FIT_LOCAL_MODEL_K Run every registered K1 or K2 full-DML start.

if nargin < 6 || isempty(opts)
    opts = struct();
end
opts = normalize_options_local(opts);
validate_inputs_local(full_data, K, local_domain, model, init_context);
fit = empty_fit_local(K, full_data, local_domain, model, opts);
start_clock = tic;
audit = audit_context_local(K);
start_stage_clock = audit_stage_start_local(audit.start_stage);
previous_query_stage = audit_set_query_stage_local(audit.start_stage);
if K == 1
    [starts, initialization_debug] = build_k1_initializations( ...
        local_domain, init_context, struct());
else
    if ~isfield(init_context, 'k1_fit')
        error('fit_local_model_k:K1Fit', ...
            'K2 fitting requires init_context.k1_fit for the nested start.');
    end
    [starts, initialization_debug] = build_k2_initializations( ...
        full_data, local_domain, model, init_context, ...
        init_context.k1_fit, struct('rank_multiplier', opts.rank_multiplier));
end
audit_restore_query_stage_local(previous_query_stage);
audit_stage_stop_local(audit.start_stage, start_stage_clock);
all_results = repmat(empty_start_result_local(K), numel(starts), 1);
expected_identity = struct( ...
    'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'local_domain_hash', local_domain.domain_hash, ...
    'solver_contract_hash', opts.solver_contract_hash, ...
    'observation_hash', fit.observation_hash);
for start_index = 1:numel(starts)
    all_results(start_index).K = K;
    all_results(start_index).initialization_id = ...
        starts(start_index).initialization_id;
    all_results(start_index).initial_angles_deg = starts(start_index).angles_deg;
    all_results(start_index).initialization_status = ...
        starts(start_index).initialization_status;
    all_results(start_index).initialization_available_flag = ...
        starts(start_index).available_flag;
    all_results(start_index).nested_rss_pass = starts(start_index).nested_rss_pass;
    all_results(start_index).fixed_measurement_hash = ...
        model.fixed_measurement_hash;
    all_results(start_index).local_domain_hash = local_domain.domain_hash;
    all_results(start_index).solver_contract_hash = opts.solver_contract_hash;
    all_results(start_index).observation_hash = fit.observation_hash;
    all_results(start_index).phase_factor = 1;
    if ~starts(start_index).available_flag
        all_results(start_index).fit_status = 'INITIALIZATION_FAILED';
        continue;
    end
    refinement_opts = struct('max_iter', opts.max_iter, ...
        'relative_score_tolerance', opts.relative_score_tolerance, ...
        'angle_tolerance_deg', opts.angle_tolerance_deg, ...
        'rank_multiplier', opts.rank_multiplier, ...
        'require_upstream_group_gate', false, ...
        'upstream_estimate_returned_flag', true, ...
        'upstream_structural_gate_pass_flag', true, ...
        'upstream_group_support_status', ...
        'INITIALIZATION_DIAGNOSTIC_ONLY', ...
        'method_status_scope', 'FULL_MODEL_FIT_NOT_GROUP_GATED', ...
        'num_multi_start', numel(starts));
    refinement_stage_clock = audit_stage_start_local(audit.refinement_stage);
    previous_query_stage = audit_set_query_stage_local( ...
        audit.refinement_stage);
    [estimate, history, refinement_debug] = refine_joint_sequential_dml( ...
        full_data, starts(start_index).angles_deg, local_domain, model, ...
        refinement_opts);
    audit_restore_query_stage_local(previous_query_stage);
    audit_stage_stop_local(audit.refinement_stage, refinement_stage_clock);
    [all_results(start_index), score_required_flag] = ...
        record_stage8_start_refinement_result(all_results(start_index), ...
        estimate, history, refinement_debug);
    if ~score_required_flag
        continue;
    end
    final_stage_clock = audit_stage_start_local(audit.final_stage);
    previous_query_stage = audit_set_query_stage_local(audit.final_stage);
    [G_hat, ~, manifold_info] = build_full_sequential_local_manifold( ...
        estimate.angles_hat_deg, model, ...
        struct('rank_multiplier', opts.rank_multiplier));
    [score, rss, sigma2_hat, loglik, effective_rank, score_debug] = ...
        concentrated_dml_rss(full_data.Zseq_white, G_hat, struct( ...
        'requested_rank', K, 'rank_multiplier', opts.rank_multiplier, ...
        'compute_projector_checks', false));
    [S_hat, solve_info] = solve_fitted_source_coefficients( ...
        G_hat, full_data.Zseq_white, ...
        struct('rank_multiplier', opts.rank_multiplier));
    audit_record_final_query_local(estimate.angles_hat_deg, G_hat, ...
        manifold_info, score, model, opts.rank_multiplier, audit.final_stage);
    audit_restore_query_stage_local(previous_query_stage);
    audit_stage_stop_local(audit.final_stage, final_stage_clock);
    all_results(start_index).score = score;
    all_results(start_index).rss = rss;
    all_results(start_index).sigma2_hat = sigma2_hat;
    all_results(start_index).loglik_concentrated = loglik;
    all_results(start_index).effective_rank = effective_rank;
    all_results(start_index).G_hat = G_hat;
    all_results(start_index).S_hat = S_hat;
    all_results(start_index).num_svd = all_results(start_index).num_svd + ...
        manifold_info.num_svd + 1 + solve_info.num_svd;
    all_results(start_index).score_debug = score_debug;
    all_results(start_index).solve_info = solve_info;
    if effective_rank < K || solve_info.effective_rank < K
        all_results(start_index).fit_status = 'NUMERIC_RANK_DEFICIENT';
        all_results(start_index).effective_rank = min( ...
            effective_rank, solve_info.effective_rank);
    end
end
selection_stage_clock = audit_stage_start_local(audit.selection_stage);
[best_index, selection, all_results] = ...
    select_stage8_valid_registered_start(all_results, K, expected_identity);
audit_stage_stop_local(audit.selection_stage, selection_stage_clock);
fit.num_start = numel(starts);
fit.all_start_results = all_results;
fit.num_score_eval = sum([all_results.num_score_eval]) + ...
    initialization_debug.num_score_eval;
fit.num_svd = sum([all_results.num_svd]) + ...
    initialization_debug.num_svd;
fit.runtime = toc(start_clock);
fit.valid_start_count = selection.valid_start_count;
fit.unreturned_start_count = selection.unreturned_start_count;
fit.initialization_failed_start_count = ...
    selection.initialization_failed_start_count;
fit.nonconverged_start_count = selection.nonconverged_start_count;
fit.rank_deficient_start_count = selection.rank_deficient_start_count;
fit.numeric_invalid_start_count = selection.numeric_invalid_start_count;
fit.selected_from_valid_start_set_flag = ...
    selection.selected_from_valid_start_set_flag;
if best_index == 0
    fit.fit_status = stage8_no_valid_start_fit_status(selection);
    audit_record_fit_snapshot_local(audit.snapshot_role, fit, ...
        init_context, model, full_data);
    debug = struct('initialization', initialization_debug, ...
        'selected_start_index', 0, 'selected_start_id', '', ...
        'selection', selection, 'phase_factor', 1);
    return;
end
selected = all_results(best_index);
fit.angles_hat_deg = selected.angles_hat_deg;
fit.G_hat = selected.G_hat;
fit.S_hat = selected.S_hat;
fit.score = selected.score;
fit.rss = selected.rss;
fit.sigma2_hat = selected.sigma2_hat;
fit.loglik_concentrated = selected.loglik_concentrated;
fit.effective_rank = selected.effective_rank;
fit.fit_status = selected.fit_status;
fit.estimate_returned_flag = selected.estimate_returned_flag;
fit.converged_flag = selected.converged_flag;
fit.initialization_id = selected.initialization_id;
audit_record_fit_snapshot_local(audit.snapshot_role, fit, ...
    init_context, model, full_data);
debug = struct('initialization', initialization_debug, ...
    'selected_start_index', best_index, ...
    'selected_start_id', selected.initialization_id, ...
    'selection', selection, 'phase_factor', 1);
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('fit_local_model_k:Options', 'opts must be a scalar struct.');
end
allowed = {'max_iter','relative_score_tolerance','angle_tolerance_deg', ...
    'rank_multiplier','solver_contract_hash'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('fit_local_model_k:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
defaults = struct('max_iter', 6, 'relative_score_tolerance', 1e-9, ...
    'angle_tolerance_deg', 0, 'rank_multiplier', 1, ...
    'solver_contract_hash', '');
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(opts, names{index})
        opts.(names{index}) = defaults.(names{index});
    end
end
if isempty(opts.solver_contract_hash)
    opts.solver_contract_hash = stage8_stable_hash( ...
        opts.max_iter, opts.relative_score_tolerance, ...
        opts.angle_tolerance_deg, opts.rank_multiplier);
end
end

function validate_inputs_local(data, K, domain, model, context)
if ~(isscalar(K) && any(K == [1, 2]))
    error('fit_local_model_k:TargetCount', 'K must be exactly 1 or 2.');
end
if ~(isstruct(data) && isscalar(data) && ...
        all(isfield(data, {'Zseq_white','fixed_measurement_hash'})) && ...
        isnumeric(data.Zseq_white) && ~isempty(data.Zseq_white) && ...
        all(isfinite(data.Zseq_white(:))))
    error('fit_local_model_k:Data', ...
        'full_data must contain finite Zseq_white and a measurement hash.');
end
if ~(isstruct(domain) && isscalar(domain) && ...
        all(isfield(domain, {'az_grid_deg','el_grid_deg','candidate_points_deg', ...
        'domain_bounds_deg','domain_hash'})))
    error('fit_local_model_k:Domain', 'local_domain is incomplete.');
end
if ~(isstruct(model) && isscalar(model) && ...
        all(isfield(model, {'Wseq','Tseq','fixed_measurement_hash','phase_factor'})))
    error('fit_local_model_k:Model', 'model is incomplete.');
end
if ~strcmp(data.fixed_measurement_hash, model.fixed_measurement_hash)
    error('fit_local_model_k:Measurement', ...
        'Data and model fixed-measurement hashes differ.');
end
if model.phase_factor ~= 1
    error('fit_local_model_k:PhaseFactor', 'Stage8 requires phase_factor=1.');
end
if ~(isstruct(context) && isscalar(context))
    error('fit_local_model_k:InitializationContext', ...
        'init_context must be a scalar struct.');
end
end

function fit = empty_fit_local(K, data, domain, model, opts)
r_C = size(data.Zseq_white, 1);
L = size(data.Zseq_white, 2);
fit = struct('K', K, 'angles_hat_deg', NaN(K, 2), ...
    'G_hat', complex(NaN(r_C, K)), 'S_hat', complex(NaN(K, L)), ...
    'score', NaN, 'rss', NaN, 'sigma2_hat', NaN, ...
    'loglik_concentrated', NaN, 'effective_rank', 0, ...
    'fit_status', 'SEARCH_NOT_CONVERGED', ...
    'estimate_returned_flag', false, 'converged_flag', false, ...
    'initialization_id', '', 'all_start_results', struct([]), ...
    'num_start', 0, 'num_score_eval', 0, 'num_svd', 0, 'runtime', 0, ...
    'valid_start_count', 0, 'unreturned_start_count', 0, ...
    'initialization_failed_start_count', 0, ...
    'nonconverged_start_count', 0, ...
    'rank_deficient_start_count', 0, 'numeric_invalid_start_count', 0, ...
    'selected_from_valid_start_set_flag', false, ...
    'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'local_domain_hash', domain.domain_hash, ...
    'solver_contract_hash', opts.solver_contract_hash, ...
    'observation_hash', stage8_stable_hash(data.Zseq_white), ...
    'effective_whitening_dimension', r_C, 'snapshot_count', L, ...
    'n_complex_observations', r_C * L, 'phase_factor', 1);
end

function result = empty_start_result_local(K)
result = struct('K', K, 'initialization_id', '', ...
    'initialization_status', 'INITIALIZATION_NOT_BUILT', ...
    'initialization_available_flag', false, ...
    'initial_angles_deg', NaN(K, 2), 'angles_hat_deg', NaN(K, 2), ...
    'score', NaN, 'rss', NaN, 'sigma2_hat', NaN, ...
    'loglik_concentrated', -Inf, 'effective_rank', 0, ...
    'G_hat', complex(NaN(0, K)), 'S_hat', complex(NaN(K, 0)), ...
    'fit_status', 'INITIALIZATION_FAILED', ...
    'estimate_returned_flag', false, 'converged_flag', false, ...
    'valid_for_selection_flag', false, ...
    'selection_eligibility_status', 'INITIALIZATION_FAILED', ...
    'nested_rss_pass', false, 'num_score_eval', 0, 'num_svd', 0, ...
    'runtime', 0, 'history', table(), 'refinement_debug', struct(), ...
    'score_debug', struct(), 'solve_info', struct(), ...
    'fixed_measurement_hash', '', 'local_domain_hash', '', ...
    'solver_contract_hash', '', 'observation_hash', '', ...
    'phase_factor', 1);
end

function audit = audit_context_local(K)
current = '';
if exist('stage8_k2_tcc_audit_state', 'file') == 2
    current = upper(char(string(stage8_k2_tcc_audit_state( ...
        'GET_QUERY_STAGE'))));
end
if K == 1 && strcmp(current, 'K2_HELPER_K1')
    audit = struct('start_stage', 'K2_HELPER_K1', ...
        'refinement_stage', 'K2_HELPER_K1', ...
        'final_stage', 'K2_HELPER_K1', ...
        'selection_stage', 'K2_HELPER_K1', ...
        'snapshot_role', 'K2_INTERNAL_HELPER_K1');
elseif K == 1
    audit = struct('start_stage', 'K1_FIXED_START_BUILD', ...
        'refinement_stage', 'K1_FIXED_REGISTERED_REFINEMENT', ...
        'final_stage', 'K1_FIXED_FINAL_CERTIFICATION', ...
        'selection_stage', 'K1_FIXED_REGISTERED_SELECTION', ...
        'snapshot_role', 'PUBLIC_K1_FIXED_SUBFIT');
else
    audit = struct('start_stage', 'K2_START_BUILD', ...
        'refinement_stage', 'K2_REGISTERED_REFINEMENT', ...
        'final_stage', 'K2_FINAL_CERTIFICATION', ...
        'selection_stage', 'K2_SELECTION', ...
        'snapshot_role', 'K2_REGISTERED_FIT');
end
end

function token = audit_stage_start_local(stage_id)
token = [];
if exist('stage8_k2_tcc_audit_state', 'file') == 2 && ...
        stage8_k2_tcc_audit_state('STAGE_ENABLED')
    token = stage8_k2_tcc_audit_state('STAGE_START', stage_id);
end
end

function audit_stage_stop_local(stage_id, token)
if exist('stage8_k2_tcc_audit_state', 'file') == 2 && ~isempty(token)
    stage8_k2_tcc_audit_state('STAGE_STOP', stage_id, token);
end
end

function previous = audit_set_query_stage_local(stage_id)
previous = '';
if exist('stage8_k2_tcc_audit_state', 'file') == 2
    previous = stage8_k2_tcc_audit_state('SET_QUERY_STAGE', stage_id);
end
end

function audit_restore_query_stage_local(previous)
if exist('stage8_k2_tcc_audit_state', 'file') == 2
    stage8_k2_tcc_audit_state('SET_QUERY_STAGE', previous);
end
end

function audit_record_final_query_local(angles, G, info, score, model, ...
    rank_multiplier, stage_id)
if exist('stage8_k2_tcc_audit_state', 'file') ~= 2 || ...
        ~stage8_k2_tcc_audit_state('QUERY_ENABLED')
    return;
end
event = struct('stage_id', stage_id, 'angles_deg', angles, 'G', G, ...
    'direct_rank', info.rank_Gseq, 'direct_score', score, ...
    'score_evaluated', true, 'derivatives_required', false, ...
    'query_class', 'G_ONLY_ELIGIBLE', 'expect_registered', true, ...
    'rank_multiplier', rank_multiplier);
stage8_k2_tcc_audit_state('RECORD_QUERY', event);
end

function audit_record_fit_snapshot_local(role, fit, init_context, model, data)
if exist('stage8_k2_tcc_audit_state', 'file') ~= 2 || ...
        ~stage8_k2_tcc_audit_state('QUERY_ENABLED')
    return;
end
event = struct('role', role, 'fit', fit, ...
    'init_context', init_context, 'model', model, 'full_data', data);
stage8_k2_tcc_audit_state('RECORD_FIT_SNAPSHOT', event);
end
