function [Y_element, simulation] = generate_stage8_k1_element_trial( ...
    center_angles_deg, snr_db, L, model, seed)
%GENERATE_STAGE8_K1_ELEMENT_TRIAL Generate one registered K1 realization.

if ~(isnumeric(center_angles_deg) && ...
        isequal(size(center_angles_deg), [1, 2]) && ...
        all(isfinite(center_angles_deg)))
    error('generate_stage8_k1_element_trial:Center', ...
        'center_angles_deg must be one finite azimuth/elevation row.');
end
if ~(isscalar(snr_db) && isreal(snr_db) && isfinite(snr_db))
    error('generate_stage8_k1_element_trial:SNR', ...
        'snr_db must be finite and real.');
end
manifold = build_stage8_element_manifold(center_angles_deg, model);
[source, source_info] = construct_deterministic_source_matrix( ...
    1, L, 0, 0, 0, 'STAGE8_K1_REGISTERED_SOURCE');
unscaled_signal = manifold.A * source;
target_energy = 10 ^ (snr_db / 10) * ...
    size(unscaled_signal, 1) * size(unscaled_signal, 2);
source = source * sqrt(target_energy / ...
    max(norm(unscaled_signal, 'fro') ^ 2, realmin));
signal = manifold.A * source;
[noise, noise_debug] = generate_stage8_element_noise(model, L, 1, seed);
Y_element = signal + noise;
simulation = struct('center_angles_deg', center_angles_deg, ...
    'snr_db', snr_db, 'L', L, 'source_matrix', source, ...
    'signal_element', signal, 'noise_element', noise, 'seed', seed, ...
    'source_info', source_info, 'noise_debug', noise_debug, ...
    'realized_snr_db', 10 * log10(norm(signal, 'fro') ^ 2 / ...
    max(norm(noise, 'fro') ^ 2, realmin)), 'phase_factor', 1);
end
