function threshold = lookup_locked_lrt_threshold( ...
    measurement_config_id, locked_calibration_artifact, expected_contract)
%LOOKUP_LOCKED_LRT_THRESHOLD Look up one provenance-bound config threshold.

if nargin ~= 3
    error('lookup_locked_lrt_threshold:InputCount', ...
        'Only config ID, locked artifact, and expected contract are accepted.');
end
expected_contract = validate_stage8_threshold_contract(expected_contract);
required = {'stage8_stable_code_identity_hash','stage8_plan_hash', ...
    'stage8_calibration_plan_hash','measurement_registry_hash', ...
    'measurement_config_id','q_global','q_global_hex','alpha','alpha_hex', ...
    'Bboot_per_cell','cell_count','noise_profile_count','quantile_rule', ...
    'threshold_contract_version','calibration_hash', ...
    'source_identity','threshold_status','threshold_policy', ...
    'threshold_artifact_hash'};
artifact = locked_calibration_artifact;
if ~(isstruct(artifact) && all(isfield(artifact, required)))
    error('lookup_locked_lrt_threshold:Artifact', ...
        'The locked calibration artifact is incomplete.');
end
matches = strcmp(string({artifact.measurement_config_id}), ...
    string(measurement_config_id));
if nnz(matches) ~= 1
    error('lookup_locked_lrt_threshold:Configuration', ...
        'The requested measurement configuration must have one locked threshold.');
end
selected = artifact(matches);
if ~strcmp(string(selected.threshold_contract_version), ...
        "STAGE8_LOCKED_THRESHOLD_ARTIFACT_V3")
    error('lookup_locked_lrt_threshold:Version', ...
        'The locked threshold does not use the V3 artifact contract.');
end
if ~strcmp(selected.threshold_policy, ...
        'ONE_GLOBAL_THRESHOLD_PER_FIXED_MEASUREMENT_CONFIG') || ...
        ~strcmp(selected.threshold_status, 'LOCKED_BOOTSTRAP_THRESHOLD')
    error('lookup_locked_lrt_threshold:Status', ...
        'The threshold artifact is not locked under the registered global policy.');
end
contract_fields = fieldnames(expected_contract);
for field_index = 1:numel(contract_fields)
    field = contract_fields{field_index};
    if ~strcmp(string(selected.(field)), string(expected_contract.(field)))
        error('lookup_locked_lrt_threshold:ProvenanceMismatch', ...
            'Locked threshold provenance does not match %s.', field);
    end
end
if ~strcmp(string(selected.source_identity), ...
        string(selected.stage8_stable_code_identity_hash))
    error('lookup_locked_lrt_threshold:SourceIdentity', ...
        'source_identity must equal the stable Stage8 code identity.');
end
computed_hash = stage8_threshold_artifact_hash(selected);
if ~strcmp(string(selected.threshold_artifact_hash), string(computed_hash))
    error('lookup_locked_lrt_threshold:ArtifactHash', ...
        'The locked threshold artifact hash is invalid.');
end
[q_global, alpha] = restore_numeric_values_local(selected);
threshold = struct('q_global', q_global, ...
    'q_global_hex', lower(char(string(selected.q_global_hex))), ...
    'alpha', alpha, 'alpha_hex', lower(char(string(selected.alpha_hex))), ...
    'Bboot_per_cell', selected.Bboot_per_cell, ...
    'cell_count', selected.cell_count, ...
    'noise_profile_count', selected.noise_profile_count, ...
    'quantile_rule', selected.quantile_rule, ...
    'threshold_contract_version', selected.threshold_contract_version, ...
    'calibration_hash', selected.calibration_hash, ...
    'threshold_status', selected.threshold_status, ...
    'threshold_policy', selected.threshold_policy, ...
    'measurement_config_id', selected.measurement_config_id, ...
    'stage8_stable_code_identity_hash', ...
    selected.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', selected.stage8_plan_hash, ...
    'stage8_calibration_plan_hash', ...
    selected.stage8_calibration_plan_hash, ...
    'measurement_registry_hash', selected.measurement_registry_hash, ...
    'source_identity', selected.source_identity, ...
    'threshold_artifact_hash', selected.threshold_artifact_hash);
end

function [q_global, alpha] = restore_numeric_values_local(artifact)
q_global = restore_one_local(artifact.q_global_hex, 'q_global_hex');
alpha = restore_one_local(artifact.alpha_hex, 'alpha_hex');
if ~decimal_matches_local(artifact.q_global, q_global) || ...
        ~decimal_matches_local(artifact.alpha, alpha)
    error('lookup_locked_lrt_threshold:DecimalHexMismatch', ...
        'Decimal threshold values do not match their lossless hex values.');
end
end

function value = restore_one_local(hex_value, field)
text_value = lower(char(string(hex_value)));
if numel(text_value) ~= 16 || isempty(regexp(text_value, ...
        '^[0-9a-f]{16}$', 'once'))
    error('lookup_locked_lrt_threshold:HexEncoding', ...
        '%s must contain one IEEE-754 double hex value.', field);
end
value = hex2num(text_value);
if ~(isscalar(value) && isreal(value) && isfinite(value))
    error('lookup_locked_lrt_threshold:HexEncoding', ...
        '%s does not restore a finite real double.', field);
end
end

function pass = decimal_matches_local(decimal_value, restored_value)
pass = isnumeric(decimal_value) && isscalar(decimal_value) && ...
    isreal(decimal_value) && isfinite(decimal_value);
if pass
    tolerance = max(eps(max(1, abs(restored_value))) * 4, realmin);
    pass = abs(double(decimal_value) - restored_value) <= tolerance;
end
end
