function threshold = lookup_locked_lrt_threshold( ...
    measurement_config_id, locked_calibration_artifact)
%LOOKUP_LOCKED_LRT_THRESHOLD Look up one global threshold by config ID only.

if nargin ~= 2
    error('lookup_locked_lrt_threshold:InputCount', ...
        'Only measurement_config_id and locked artifact are accepted.');
end
required = {'measurement_config_id','q_global','alpha', ...
    'calibration_hash','threshold_status','threshold_policy'};
artifact = locked_calibration_artifact;
if ~(isstruct(artifact) && all(isfield(artifact, required)))
    error('lookup_locked_lrt_threshold:Artifact', ...
        'The locked calibration artifact is incomplete.');
end
matches = strcmp(string({artifact.measurement_config_id}), ...
    string(measurement_config_id));
if nnz(matches) ~= 1
    error('lookup_locked_lrt_threshold:Configuration', ...
        'The requested measurement configuration must have one locked threshold.');
end
selected = artifact(matches);
if ~strcmp(selected.threshold_policy, ...
        'ONE_GLOBAL_THRESHOLD_PER_FIXED_MEASUREMENT_CONFIG') || ...
        ~strcmp(selected.threshold_status, 'LOCKED_BOOTSTRAP_THRESHOLD')
    error('lookup_locked_lrt_threshold:Status', ...
        'The threshold artifact is not locked under the registered global policy.');
end
threshold = struct('q_global', selected.q_global, ...
    'alpha', selected.alpha, 'calibration_hash', selected.calibration_hash, ...
    'threshold_status', selected.threshold_status, ...
    'measurement_config_id', selected.measurement_config_id);
end
