function [cells, debug] = materialize_stage8_calibration_cells( ...
    calibration_plan, local_domain, model_registry, stage5_locked, opts)
%MATERIALIZE_STAGE8_CALIBRATION_CELLS Build data-driven K1 cell inputs.

if nargin < 5 || isempty(opts)
    opts = struct();
end
opts = normalize_options_local(opts, height(calibration_plan.cells));
required = {'cells','calibration_plan_hash','Bboot_per_cell'};
if ~(isstruct(calibration_plan) && isscalar(calibration_plan) && ...
        all(isfield(calibration_plan, required)))
    error('materialize_stage8_calibration_cells:Plan', ...
        'calibration_plan is incomplete.');
end
rows = calibration_plan.cells(opts.cell_indices, :);
cells = cell(height(rows), 1);
score_calls = 0;
svd_calls = 0;
start_clock = tic;
for output_index = 1:height(rows)
    row = rows(output_index, :);
    model = resolve_stage8_measurement_model(model_registry, ...
        row.measurement_config_id, row.noise_profile_id);
    verify_plan_model_local(row, model);
    [Y_element, simulation] = generate_stage8_k1_element_trial( ...
        [row.center_az_deg, row.center_el_deg], row.snr_db, row.L, ...
        model, row.calibration_data_seed);
    full_data = build_stage8_full_data_from_element(Y_element, model, ...
        struct('calibration_data_seed', row.calibration_data_seed, ...
        'data_role', 'STAGE8_K1_CALIBRATION_CELL'));
    [initialization_context, ~] = ...
        build_stage8_initialization_context_from_data( ...
        full_data, model, local_domain, stage5_locked, ...
        model.noise_factorization, struct());
    score_calls = score_calls + initialization_context.num_score_eval;
    svd_calls = svd_calls + initialization_context.num_svd;
    cell_input_hash = stage8_calibration_cell_input_hash( ...
        row, opts.source_identity, calibration_plan.calibration_plan_hash);
    cells{output_index} = struct( ...
        'measurement_config_id', char(row.measurement_config_id), ...
        'noise_profile_id', char(row.noise_profile_id), ...
        'calibration_cell_id', char(row.calibration_cell_id), ...
        'global_cell_index', row.global_cell_index, ...
        'model_key', char(row.model_key), ...
        'fixed_measurement_hash', char(row.fixed_measurement_hash), ...
        'calibration_data_seed', row.calibration_data_seed, ...
        'bootstrap_seed_start', row.bootstrap_seed_start, ...
        'bootstrap_seed_end', row.bootstrap_seed_end, ...
        'seed_block_stride', row.seed_block_stride, ...
        'Bboot_per_cell', row.Bboot_per_cell, ...
        'center_az_deg', row.center_az_deg, ...
        'center_el_deg', row.center_el_deg, 'snr_db', row.snr_db, ...
        'L', row.L, 'full_data', full_data, ...
        'initialization_context', initialization_context, ...
        'initialization_factory_contract', ...
        'BUILD_STAGE8_INITIALIZATION_CONTEXT_FROM_DATA_V1', ...
        'simulation_audit', simulation_audit_local(simulation), ...
        'data_identity_hash', full_data.data_identity_hash, ...
        'cell_input_hash', cell_input_hash, ...
        'source_identity', opts.source_identity, ...
        'plan_hash', calibration_plan.calibration_plan_hash, ...
        'materialization_status', 'CALIBRATION_CELL_MATERIALIZED', ...
        'phase_factor', 1);
end
cells = vertcat(cells{:});
debug = struct('materialized_cell_count', numel(cells), ...
    'global_cell_indices', opts.cell_indices(:), ...
    'initialization_score_call_count', score_calls, ...
    'initialization_svd_call_count', svd_calls, ...
    'runtime', toc(start_clock), 'formal_run', opts.formal_run, ...
    'materialization_mode', opts.materialization_mode, ...
    'phase_factor', 1);
end

function audit = simulation_audit_local(simulation)
audit = struct('center_angles_deg', simulation.center_angles_deg, ...
    'snr_db', simulation.snr_db, 'L', simulation.L, ...
    'seed', simulation.seed, 'realized_snr_db', ...
    simulation.realized_snr_db, 'source_profile_id', ...
    simulation.source_info.profile_id, 'phase_factor', 1);
end

function opts = normalize_options_local(opts, cell_count)
if ~(isstruct(opts) && isscalar(opts))
    error('materialize_stage8_calibration_cells:Options', ...
        'opts must be a scalar struct.');
end
allowed = {'cell_indices','formal_run','source_identity', ...
    'materialization_mode'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('materialize_stage8_calibration_cells:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
if ~isfield(opts, 'cell_indices')
    opts.cell_indices = (1:cell_count).';
end
if ~isfield(opts, 'formal_run')
    opts.formal_run = false;
end
if ~isfield(opts, 'source_identity')
    opts.source_identity = 'STAGE8_1A_UNIT_SCOPE';
end
if ~isfield(opts, 'materialization_mode')
    opts.materialization_mode = ternary_local( ...
        opts.formal_run, 'FORMAL_SHARD', 'UNIT_TEST');
end
indices = opts.cell_indices(:);
if isempty(indices) || any(indices < 1) || any(indices > cell_count) || ...
        any(indices ~= fix(indices)) || numel(unique(indices)) ~= numel(indices)
    error('materialize_stage8_calibration_cells:CellIndices', ...
        'cell_indices must be unique valid plan row indices.');
end
if opts.formal_run && ~strcmp(opts.materialization_mode, 'FORMAL_SHARD')
    error('materialize_stage8_calibration_cells:FormalMode', ...
        'Formal materialization requires FORMAL_SHARD mode.');
elseif ~opts.formal_run && ~strcmp(opts.materialization_mode, 'UNIT_TEST')
    error('materialize_stage8_calibration_cells:UnitMode', ...
        'Nonformal materialization requires UNIT_TEST mode.');
end
opts.cell_indices = indices;
end

function value = ternary_local(condition, yes_value, no_value)
if condition
    value = yes_value;
else
    value = no_value;
end
end

function verify_plan_model_local(row, model)
if string(model.model_key) ~= row.model_key || ...
        string(model.fixed_measurement_hash) ~= row.fixed_measurement_hash
    error('materialize_stage8_calibration_cells:ModelIdentity', ...
        'The calibration row and resolved model identities differ.');
end
if row.bootstrap_seed_end - row.bootstrap_seed_start + 1 ~= ...
        row.Bboot_per_cell
    error('materialize_stage8_calibration_cells:SeedBlock', ...
        'The cell bootstrap seed block does not contain Bboot samples.');
end
end
