function model = resolve_stage8_measurement_model( ...
    registry, measurement_config_id, noise_profile_id)
%RESOLVE_STAGE8_MEASUREMENT_MODEL Resolve exactly one config/noise object.

required = {'entries','table','registry_hash','entry_count'};
if ~(isstruct(registry) && isscalar(registry) && ...
        all(isfield(registry, required)) && registry.entry_count == 4)
    error('resolve_stage8_measurement_model:Registry', ...
        'registry must be the four-entry Stage8 measurement registry.');
end
config_id = string(measurement_config_id);
noise_id = string(noise_profile_id);
matches = registry.table.measurement_config_id == config_id & ...
    registry.table.noise_profile_id == noise_id;
if nnz(matches) ~= 1
    error('resolve_stage8_measurement_model:ModelKey', ...
        'The config/noise pair must resolve to exactly one model.');
end
row_index = find(matches, 1);
model = registry.entries(row_index);
row = registry.table(row_index, :);
if string(model.model_key) ~= row.model_key || ...
        string(model.fixed_measurement_hash) ~= row.fixed_measurement_hash || ...
        string(model.subset_id) ~= row.subset_id || ...
        ~strcmp(model.measurement_config_id, char(config_id)) || ...
        ~strcmp(model.noise_profile_id, char(noise_id))
    error('resolve_stage8_measurement_model:RegistryIdentity', ...
        'The registry table and retained model object disagree.');
end
end
