function [selected_index, diagnostics, results] = ...
    select_stage8_valid_registered_start(results, K, expected)
%SELECT_STAGE8_VALID_REGISTERED_START Select the best valid registered start.

if nargin < 3 || isempty(expected)
    expected = struct();
end
if ~(isstruct(results) && isvector(results) && ~isempty(results))
    error('select_stage8_valid_registered_start:Results', ...
        'results must be a nonempty registered-start struct vector.');
end
if ~(isscalar(K) && ismember(K, [1, 2]))
    error('select_stage8_valid_registered_start:TargetCount', ...
        'K must be exactly 1 or 2.');
end
required = {'initialization_available_flag','estimate_returned_flag', ...
    'converged_flag','effective_rank','rss','sigma2_hat', ...
    'loglik_concentrated'};
if ~all(isfield(results, required))
    error('select_stage8_valid_registered_start:Contract', ...
        'A registered-start result is incomplete.');
end

valid = false(numel(results), 1);
status = strings(numel(results), 1);
nonconverged = false(numel(results), 1);
rank_deficient = false(numel(results), 1);
numeric_invalid = false(numel(results), 1);
for start_index = 1:numel(results)
    if ~logical_scalar_true_local( ...
            results(start_index).initialization_available_flag)
        status(start_index) = "INITIALIZATION_FAILED";
        continue;
    end
    [valid(start_index), details] = validate_stage8_fit_for_lrt( ...
        results(start_index), K, expected);
    status(start_index) = string(details.status);
    nonconverged(start_index) = ...
        details.checks.estimate_returned && ~details.checks.converged;
    rank_deficient(start_index) = details.checks.estimate_returned && ...
        ~details.checks.effective_rank;
    numeric_invalid(start_index) = details.checks.estimate_returned && ...
        details.checks.converged && details.checks.effective_rank && ...
        ~(details.checks.rss && details.checks.sigma2 && ...
        details.checks.loglik && details.checks.phase_factor && ...
        details.checks.identity && details.checks.target_count);
end

for start_index = 1:numel(results)
    results(start_index).valid_for_selection_flag = valid(start_index);
    results(start_index).selection_eligibility_status = ...
        char(status(start_index));
end
eligible = find(valid);
if isempty(eligible)
    selected_index = 0;
else
    loglik = [results(eligible).loglik_concentrated].';
    [~, relative_index] = max(loglik);
    selected_index = eligible(relative_index);
end
diagnostics = struct( ...
    'valid_start_count', nnz(valid), ...
    'nonconverged_start_count', nnz(nonconverged), ...
    'rank_deficient_start_count', nnz(rank_deficient), ...
    'numeric_invalid_start_count', nnz(numeric_invalid), ...
    'selected_from_valid_start_set_flag', selected_index > 0, ...
    'eligibility_status', status, ...
    'selection_rule', ...
    'MAXIMUM_CONCENTRATED_LOG_LIKELIHOOD_AMONG_VALID_REGISTERED_STARTS');
end

function pass = logical_scalar_true_local(value)
pass = islogical(value) && isscalar(value) && value;
end
