function [full_data_boot, debug] = simulate_stage8_element_bootstrap( ...
    fit, model, opts)
%SIMULATE_STAGE8_ELEMENT_BOOTSTRAP Draw one fitted K1/K2 element sample.

if nargin < 3 || isempty(opts)
    opts = struct();
end
allowed = {'seed','formal_run','substream'};
if ~(isstruct(opts) && isscalar(opts))
    error('simulate_stage8_element_bootstrap:Options', ...
        'opts must be a scalar struct.');
end
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('simulate_stage8_element_bootstrap:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
if ~isfield(opts, 'seed')
    error('simulate_stage8_element_bootstrap:Seed', ...
        'opts.seed must come from a frozen seed registry.');
end
if ~isfield(opts, 'formal_run')
    opts.formal_run = false;
end
if ~isfield(opts, 'substream')
    opts.substream = [];
end
required = {'K','angles_hat_deg','S_hat','sigma2_hat', ...
    'fixed_measurement_hash','phase_factor'};
if ~(isstruct(fit) && isscalar(fit) && all(isfield(fit, required)) && ...
        any(fit.K == [1, 2]) && fit.phase_factor == 1)
    error('simulate_stage8_element_bootstrap:Fit', ...
        'fit must be a contract-complete K1 or K2 fit.');
end
if ~strcmp(fit.fixed_measurement_hash, model.fixed_measurement_hash)
    error('simulate_stage8_element_bootstrap:MeasurementIdentity', ...
        'fit and model fixed-measurement identities differ.');
end
if opts.formal_run
    [valid_fit, validity] = validate_stage8_fit_for_lrt( ...
        fit, fit.K, struct('fixed_measurement_hash', ...
        model.fixed_measurement_hash));
    if ~valid_fit
        error('simulate_stage8_element_bootstrap:InvalidFit', ...
            'Formal bootstrap rejected fit status %s.', validity.status);
    end
end
manifold = build_stage8_element_manifold(fit.angles_hat_deg, model);
if size(fit.S_hat, 1) ~= fit.K
    error('simulate_stage8_element_bootstrap:SourceShape', ...
        'fit.S_hat must have K rows.');
end
mean_element = manifold.A * fit.S_hat;
[noise_element, noise_debug] = generate_stage8_element_noise( ...
    model, size(fit.S_hat, 2), fit.sigma2_hat, opts.seed, opts.substream);
Y_element = mean_element + noise_element;
Zseq_raw = model.W_I' * Y_element;
Zseq_white = model.T_I * Zseq_raw;
mean_white = model.T_I * (model.W_I' * mean_element);
if isfield(fit, 'G_hat') && ~isempty(fit.G_hat) && ...
        all(isfinite(fit.G_hat(:)))
    fitted_white_mean = fit.G_hat * fit.S_hat;
    mean_error = norm(mean_white - fitted_white_mean, 'fro') / ...
        max(norm(fitted_white_mean, 'fro'), realmin);
else
    fitted_white_mean = mean_white;
    mean_error = 0;
end
if opts.formal_run && mean_error > 1e-10
    error('simulate_stage8_element_bootstrap:MeanIdentity', ...
        'Element and whitened fitted means disagree.');
end
full_data_boot = struct('Y_element', Y_element, ...
    'Zseq_raw', Zseq_raw, 'Zseq_white', Zseq_white, ...
    'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'model_key', model.model_key, 'bootstrap_seed', opts.seed, ...
    'bootstrap_substream', opts.substream, ...
    'bootstrap_model_K', fit.K, 'phase_factor', 1, ...
    'bootstrap_source', 'FITTED_ELEMENT_DOMAIN_STAGE8');
debug = struct('Y_element_mean', mean_element, ...
    'Zseq_white_mean', mean_white, 'fitted_white_mean', fitted_white_mean, ...
    'mean_identity_relative_error', mean_error, ...
    'noise_element', noise_element, 'noise', noise_debug, ...
    'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'bootstrap_seed', opts.seed, 'bootstrap_model_K', fit.K, ...
    'bootstrap_substream', opts.substream, ...
    'phase_factor', 1);
end
