function [full_data_boot, debug] = simulate_stage8_element_bootstrap( ...
    fit, model, opts)
%SIMULATE_STAGE8_ELEMENT_BOOTSTRAP Draw one fitted K1/K2 element sample.

if nargin < 3 || isempty(opts)
    opts = struct();
end
allowed = {'seed','formal_run','substream'};
if ~(isstruct(opts) && isscalar(opts))
    error('simulate_stage8_element_bootstrap:Options', ...
        'opts must be a scalar struct.');
end
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('simulate_stage8_element_bootstrap:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
if ~isfield(opts, 'seed')
    error('simulate_stage8_element_bootstrap:Seed', ...
        'opts.seed must come from a frozen seed registry.');
end
if ~isfield(opts, 'formal_run')
    opts.formal_run = false;
end
if ~isfield(opts, 'substream')
    opts.substream = [];
end
required = {'K','angles_hat_deg','G_hat','S_hat','sigma2_hat', ...
    'fixed_measurement_hash','phase_factor'};
if ~(isstruct(fit) && isscalar(fit) && all(isfield(fit, required)) && ...
        any(fit.K == [1, 2]) && fit.phase_factor == 1)
    error('simulate_stage8_element_bootstrap:Fit', ...
        'fit must be a contract-complete K1 or K2 fit.');
end
if ~strcmp(fit.fixed_measurement_hash, model.fixed_measurement_hash)
    error('simulate_stage8_element_bootstrap:MeasurementIdentity', ...
        'fit and model fixed-measurement identities differ.');
end
if opts.formal_run
    [valid_fit, validity] = validate_stage8_fit_for_lrt( ...
        fit, fit.K, struct('fixed_measurement_hash', ...
        model.fixed_measurement_hash));
    if ~valid_fit
        error('simulate_stage8_element_bootstrap:InvalidFit', ...
            'Formal bootstrap rejected fit status %s.', validity.status);
    end
end
if size(fit.S_hat, 1) ~= fit.K
    error('simulate_stage8_element_bootstrap:SourceShape', ...
        'fit.S_hat must have K rows.');
end
mean_identity = evaluate_stage8_bootstrap_mean_identity(fit, model);
if opts.formal_run && ~mean_identity.overall_pass
    error('simulate_stage8_element_bootstrap:MeanIdentityContract', ...
        ['%s; G_max_bound_ratio=%.17g; mean_max_bound_ratio=%.17g; ', ...
        'old_relative_mean_error=%.17g; fitted_mean_norm=%.17g; ', ...
        'fixed_measurement_hash=%s.'], mean_identity.failure_status, ...
        mean_identity.G_max_bound_ratio, ...
        mean_identity.mean_max_bound_ratio, ...
        mean_identity.mean_old_relative_residual, ...
        mean_identity.fitted_mean_norm, model.fixed_measurement_hash);
end
A = mean_identity.A_rebuilt;
mean_element = A * fit.S_hat;
[noise_element, noise_debug] = generate_stage8_element_noise( ...
    model, size(fit.S_hat, 2), fit.sigma2_hat, opts.seed, opts.substream);
Y_element = mean_element + noise_element;
Zseq_raw = model.W_I' * Y_element;
Zseq_white = model.T_I * Zseq_raw;
mean_white = model.T_I * (model.W_I' * mean_element);
fitted_white_mean = mean_identity.mean_white_fit;
full_data_boot = struct('Y_element', Y_element, ...
    'Zseq_raw', Zseq_raw, 'Zseq_white', Zseq_white, ...
    'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'model_key', model.model_key, 'bootstrap_seed', opts.seed, ...
    'bootstrap_substream', opts.substream, ...
    'bootstrap_model_K', fit.K, 'phase_factor', 1, ...
    'bootstrap_source', 'FITTED_ELEMENT_DOMAIN_STAGE8');
debug = struct('Y_element_mean', mean_element, ...
    'Zseq_white_mean', mean_white, 'fitted_white_mean', fitted_white_mean, ...
    'mean_identity_relative_error', ...
    mean_identity.mean_old_relative_residual, ...
    'mean_identity_contract', scalar_diagnostics_local(mean_identity), ...
    'noise_element', noise_element, 'noise', noise_debug, ...
    'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'bootstrap_seed', opts.seed, 'bootstrap_model_K', fit.K, ...
    'bootstrap_substream', opts.substream, ...
    'phase_factor', 1);
end

function diagnostics = scalar_diagnostics_local(evaluation)
names = {'contract_version','contract_hash','G_absolute_residual', ...
    'G_old_relative_residual','G_absolute_bound','G_max_bound_ratio', ...
    'G_identity_pass','mean_absolute_residual', ...
    'mean_old_relative_residual','mean_absolute_bound', ...
    'mean_max_bound_ratio','mean_identity_pass','fitted_mean_norm', ...
    'W_alias_pass','T_alias_pass','fixed_measurement_pass', ...
    'angles_source','phase_factor','element_dimension_N', ...
    'sequential_dimension_B','source_dimension_K','gamma_N','gamma_B', ...
    'gamma_K','gamma_G_path','gamma_mean_path','overall_pass', ...
    'failure_status'};
diagnostics = struct();
for index = 1:numel(names)
    diagnostics.(names{index}) = evaluation.(names{index});
end
end
