function digest = stage8_threshold_artifact_hash(artifact)
%STAGE8_THRESHOLD_ARTIFACT_HASH Hash a locked threshold and its provenance.

required = {'stage8_stable_code_identity_hash','stage8_plan_hash', ...
    'stage8_calibration_plan_hash','measurement_registry_hash', ...
    'measurement_config_id','q_global_hex','alpha_hex','Bboot_per_cell', ...
    'cell_count','noise_profile_count','quantile_rule', ...
    'threshold_policy','calibration_hash','source_identity', ...
    'threshold_status','threshold_contract_version'};
if ~(isstruct(artifact) && isscalar(artifact) && all(isfield(artifact, required)))
    error('stage8_threshold_artifact_hash:Artifact', ...
        'The locked threshold artifact is incomplete.');
end
names = lower(string(fieldnames(artifact)));
forbidden = ["truth";"scene";"separation"; ...
    "score" + "_" + "gap";"scoregap"];
for token_index = 1:numel(forbidden)
    if any(contains(names, forbidden(token_index)))
        error('stage8_threshold_artifact_hash:ForbiddenInput', ...
            'Threshold artifacts cannot depend on trial or scene information.');
    end
end
if ~strcmp(string(artifact.threshold_contract_version), ...
        "STAGE8_LOCKED_THRESHOLD_ARTIFACT_V3")
    error('stage8_threshold_artifact_hash:Version', ...
        'Threshold artifacts must use the fixed V3 contract.');
end
payload = struct( ...
    'stage8_stable_code_identity_hash', ...
    char(string(artifact.stage8_stable_code_identity_hash)), ...
    'stage8_plan_hash', char(string(artifact.stage8_plan_hash)), ...
    'stage8_calibration_plan_hash', ...
    char(string(artifact.stage8_calibration_plan_hash)), ...
    'measurement_registry_hash', ...
    char(string(artifact.measurement_registry_hash)), ...
    'measurement_config_id', char(string(artifact.measurement_config_id)), ...
    'q_global_hex', lower(char(string(artifact.q_global_hex))), ...
    'alpha_hex', lower(char(string(artifact.alpha_hex))), ...
    'Bboot_per_cell', artifact.Bboot_per_cell, ...
    'cell_count', artifact.cell_count, ...
    'noise_profile_count', artifact.noise_profile_count, ...
    'quantile_rule', char(string(artifact.quantile_rule)), ...
    'threshold_policy', char(string(artifact.threshold_policy)), ...
    'calibration_hash', char(string(artifact.calibration_hash)), ...
    'source_identity', char(string(artifact.source_identity)), ...
    'threshold_status', char(string(artifact.threshold_status)));
digest = stage8_stable_hash( ...
    'STAGE8_LOCKED_THRESHOLD_ARTIFACT_V3', payload);
end
