function interval = stage8_wilson_interval(success_count, trial_count, alpha)
%STAGE8_WILSON_INTERVAL Compute a two-sided binomial Wilson interval.

if nargin < 3 || isempty(alpha)
    alpha = 0.05;
end
if ~(isscalar(success_count) && isfinite(success_count) && ...
        success_count >= 0 && success_count == fix(success_count) && ...
        isscalar(trial_count) && isfinite(trial_count) && ...
        trial_count >= success_count && trial_count >= 1 && ...
        trial_count == fix(trial_count) && isscalar(alpha) && ...
        alpha > 0 && alpha < 1)
    error('stage8_wilson_interval:Inputs', ...
        'Counts and alpha do not define a binomial interval.');
end
z = sqrt(2) * erfcinv(alpha);
p = success_count / trial_count;
denominator = 1 + z ^ 2 / trial_count;
center = (p + z ^ 2 / (2 * trial_count)) / denominator;
halfwidth = z / denominator * sqrt( ...
    p * (1 - p) / trial_count + z ^ 2 / (4 * trial_count ^ 2));
interval = struct('count', success_count, 'n', trial_count, ...
    'rate', p, 'lower', max(0, center - halfwidth), ...
    'upper', min(1, center + halfwidth), 'alpha', alpha, ...
    'method', 'WILSON_SCORE_TWO_SIDED');
end
