function status = stage8_no_valid_start_fit_status(selection)
%STAGE8_NO_VALID_START_FIT_STATUS Resolve a failed registered-start search.

required = {'rank_deficient_start_count', ...
    'selected_from_valid_start_set_flag'};
if ~(isstruct(selection) && isscalar(selection) && ...
        all(isfield(selection, required)) && ...
        isscalar(selection.rank_deficient_start_count) && ...
        isfinite(selection.rank_deficient_start_count) && ...
        selection.rank_deficient_start_count >= 0 && ...
        ~selection.selected_from_valid_start_set_flag)
    error('stage8_no_valid_start_fit_status:Contract', ...
        'A failed registered-start selection diagnostic is required.');
end
if selection.rank_deficient_start_count > 0
    status = 'NUMERIC_RANK_DEFICIENT';
else
    status = 'SEARCH_NOT_CONVERGED';
end
end
