function [summary, gate, paired] = ...
    summarize_stage8_k1_validation(trials, K1)
%SUMMARIZE_STAGE8_K1_VALIDATION Keep primary and sensitivity samples separate.

required = {'common_trial_id','stratum_id','measurement_config_id','state'};
if ~(istable(trials) && all(ismember(required, ...
        trials.Properties.VariableNames)))
    error('summarize_stage8_k1_validation:Trials', ...
        'Validation trials do not expose the paired decision contract.');
end
required_plan = {'measurement_config_ids','primary_measurement_config_id', ...
    'sensitivity_measurement_config_id','sensitivity_authorization_status', ...
    'gates'};
if ~(isstruct(K1) && isscalar(K1) && all(isfield(K1, required_plan)))
    error('summarize_stage8_k1_validation:Plan', ...
        'The K1 validation summary contract is incomplete.');
end
config_ids = string(K1.measurement_config_ids(:));
if ~isempty(setxor(unique(trials.measurement_config_id), config_ids))
    error('summarize_stage8_k1_validation:ConfigurationCoverage', ...
        'Validation rows must cover the two registered configurations only.');
end
strata = unique(trials.stratum_id, 'stable');
scopes = ["OVERALL";strata];
rows = cell(numel(config_ids) * numel(scopes), 1);
row_index = 0;
for config_index = 1:numel(config_ids)
    for scope_index = 1:numel(scopes)
        row_index = row_index + 1;
        selected = trials.measurement_config_id == config_ids(config_index);
        if scope_index > 1
            selected = selected & trials.stratum_id == scopes(scope_index);
        end
        rows{row_index} = summary_row_local( ...
            trials(selected, :), config_ids(config_index), ...
            scopes(scope_index), K1);
    end
end
summary = struct2table(vertcat(rows{:}));
primary_id = string(K1.primary_measurement_config_id);
primary = summary(summary.measurement_config_id == primary_id, :);
if height(primary) ~= numel(scopes)
    error('summarize_stage8_k1_validation:PrimarySummary', ...
        'The primary configuration summary is incomplete.');
end
overall = primary(primary.summary_scope == "OVERALL", :);
stratum_rows = primary(primary.summary_scope ~= "OVERALL", :);
overall_split_pass = overall.false_split_wilson_upper <= ...
    K1.gates.overall_false_split_wilson_upper;
stratum_split_pass = all(stratum_rows.false_split_wilson_upper <= ...
    K1.gates.stratum_false_split_wilson_upper);
false_resolved_pass = overall.false_resolved_wilson_upper <= ...
    K1.gates.false_resolved_wilson_upper;
nondecision_pass = overall.nondecision_wilson_upper <= ...
    K1.gates.nondecision_wilson_upper;
gate_pass = overall_split_pass && stratum_split_pass && ...
    false_resolved_pass && nondecision_pass;
gate = struct('authorization_measurement_config_id', char(primary_id), ...
    'overall_false_split_pass', overall_split_pass, ...
    'each_stratum_false_split_pass', stratum_split_pass, ...
    'false_resolved_pass', false_resolved_pass, ...
    'nondecision_pass', nondecision_pass, 'gate_pass', gate_pass, ...
    'sensitivity_status', K1.sensitivity_authorization_status, ...
    'sensitivity_used_for_authorization_flag', false, ...
    'gate_status', ternary_local(gate_pass, ...
    'STAGE8_1_K1_VALIDATION_PASS', 'STAGE8_1_K1_VALIDATION_FAIL'));
paired = paired_sensitivity_local(trials, K1);
end

function row = summary_row_local(trials, config_id, scope, K1)
n = height(trials);
if n == 0
    error('summarize_stage8_k1_validation:EmptyScope', ...
        'Every configuration/scope summary requires observations.');
end
state = string(trials.state);
false_split = ismember(state, ["K2_RESOLVED","K2_UNRESOLVED"]);
false_resolved = state == "K2_RESOLVED";
unresolved = state == "K2_UNRESOLVED";
search = state == "SEARCH_NOT_CONVERGED";
rank_failure = state == "NUMERIC_RANK_DEFICIENT";
available = ismember(state, ["K1","K2_RESOLVED","K2_UNRESOLVED"]);
nondecision = search | rank_failure;
split_interval = stage8_wilson_interval(nnz(false_split), n, 0.05);
resolved_interval = stage8_wilson_interval(nnz(false_resolved), n, 0.05);
unresolved_interval = stage8_wilson_interval(nnz(unresolved), n, 0.05);
search_interval = stage8_wilson_interval(nnz(search), n, 0.05);
rank_interval = stage8_wilson_interval(nnz(rank_failure), n, 0.05);
availability_interval = stage8_wilson_interval(nnz(available), n, 0.05);
nondecision_interval = stage8_wilson_interval(nnz(nondecision), n, 0.05);
is_primary = config_id == string(K1.primary_measurement_config_id);
row = struct('measurement_config_id', config_id, ...
    'summary_scope', scope, 'common_trial_count', n, ...
    'authorization_role', ternary_local(is_primary, ...
    'PRIMARY_STAGE8_2_AUTHORIZATION', ...
    K1.sensitivity_authorization_status), ...
    'false_split_rate', split_interval.rate, ...
    'false_split_wilson_lower', split_interval.lower, ...
    'false_split_wilson_upper', split_interval.upper, ...
    'false_resolved_rate', resolved_interval.rate, ...
    'false_resolved_wilson_upper', resolved_interval.upper, ...
    'K2_UNRESOLVED_rate', unresolved_interval.rate, ...
    'K2_UNRESOLVED_wilson_upper', unresolved_interval.upper, ...
    'SEARCH_NOT_CONVERGED_rate', search_interval.rate, ...
    'NUMERIC_RANK_DEFICIENT_rate', rank_interval.rate, ...
    'decision_availability_rate', availability_interval.rate, ...
    'decision_availability_wilson_lower', availability_interval.lower, ...
    'nondecision_wilson_upper', nondecision_interval.upper);
end

function paired = paired_sensitivity_local(trials, K1)
pair_ids = unique(trials.common_trial_id, 'stable');
common_trial_id = strings(numel(pair_ids), 1);
primary_state = strings(numel(pair_ids), 1);
full_parent_state = strings(numel(pair_ids), 1);
false_split_discordance = false(numel(pair_ids), 1);
false_resolved_discordance = false(numel(pair_ids), 1);
nondecision_discordance = false(numel(pair_ids), 1);
primary_id = string(K1.primary_measurement_config_id);
sensitivity_id = string(K1.sensitivity_measurement_config_id);
for pair_index = 1:numel(pair_ids)
    selected = trials(trials.common_trial_id == pair_ids(pair_index), :);
    primary = selected(selected.measurement_config_id == primary_id, :);
    sensitivity = selected(selected.measurement_config_id == sensitivity_id, :);
    if height(primary) ~= 1 || height(sensitivity) ~= 1
        error('summarize_stage8_k1_validation:Pairing', ...
            'Every common trial must have one primary and one sensitivity row.');
    end
    common_trial_id(pair_index) = pair_ids(pair_index);
    primary_state(pair_index) = string(primary.state);
    full_parent_state(pair_index) = string(sensitivity.state);
    false_split_discordance(pair_index) = ...
        is_false_split_local(primary_state(pair_index)) ~= ...
        is_false_split_local(full_parent_state(pair_index));
    false_resolved_discordance(pair_index) = ...
        (primary_state(pair_index) == "K2_RESOLVED") ~= ...
        (full_parent_state(pair_index) == "K2_RESOLVED");
    nondecision_discordance(pair_index) = ...
        is_nondecision_local(primary_state(pair_index)) ~= ...
        is_nondecision_local(full_parent_state(pair_index));
end
paired = table(common_trial_id, primary_state, full_parent_state, ...
    false_split_discordance, false_resolved_discordance, ...
    nondecision_discordance);
end

function flag = is_false_split_local(state)
flag = ismember(state, ["K2_RESOLVED","K2_UNRESOLVED"]);
end

function flag = is_nondecision_local(state)
flag = ismember(state, ...
    ["SEARCH_NOT_CONVERGED","NUMERIC_RANK_DEFICIENT"]);
end

function value = ternary_local(condition, yes_value, no_value)
if condition
    value = yes_value;
else
    value = no_value;
end
end
