function checkpoint_root = validate_stage8_formal_checkpoint_root( ...
    repo_dir, checkpoint_root)
%VALIDATE_STAGE8_FORMAL_CHECKPOINT_ROOT Keep formal checkpoints outside Git.

if ~(ischar(repo_dir) || (isstring(repo_dir) && isscalar(repo_dir))) || ...
        ~(ischar(checkpoint_root) || ...
        (isstring(checkpoint_root) && isscalar(checkpoint_root))) || ...
        strlength(string(checkpoint_root)) == 0
    error('validate_stage8_formal_checkpoint_root:CheckpointRootRequired', ...
        'Formal checkpoint_root must be supplied explicitly.');
end
repo_canonical = char(java.io.File(char(repo_dir)).getCanonicalPath());
checkpoint_canonical = char( ...
    java.io.File(char(checkpoint_root)).getCanonicalPath());
repo_key = lower(strrep(repo_canonical, '/', filesep));
checkpoint_key = lower(strrep(checkpoint_canonical, '/', filesep));
inside = strcmp(checkpoint_key, repo_key) || ...
    startsWith(checkpoint_key, [repo_key, filesep]);
if inside
    error(['validate_stage8_formal_checkpoint_root:', ...
        'FORMAL_CHECKPOINT_ROOT_INSIDE_REPOSITORY'], ...
        'Formal checkpoint_root must be outside the Git repository.');
end
checkpoint_root = checkpoint_canonical;
end
