function contract = validate_stage8_group_noise_scale(alpha_q)
%VALIDATE_STAGE8_GROUP_NOISE_SCALE Reject invalid scales without substitution.

valid = isscalar(alpha_q) && isreal(alpha_q) && ...
    isfinite(alpha_q) && alpha_q > 0;
if valid
    contract = struct('scale', alpha_q, 'start_available_flag', true, ...
        'status', 'GROUP_NOISE_SCALE_VALID', ...
        'unit_fallback_used_flag', false);
else
    contract = struct('scale', NaN, 'start_available_flag', false, ...
        'status', 'GROUP_NOISE_SCALE_INVALID', ...
        'unit_fallback_used_flag', false);
end
end
