function context = stage8_k2_va_build_context(repo_dir)
%STAGE8_K2_VA_BUILD_CONTEXT Load immutable Stage8 dependencies.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_va_build_context:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
constants = stage8_k2_va_constants();
plan = build_stage8_locked_plan(repo_dir, sim_cfg(), ...
    struct('require_formal_runtime', false));
expected_bounds = [7.4, 8.6, 9.8, 10.2];
if ~isequal(plan.local_domain.domain_bounds_deg, expected_bounds) || ...
        height(plan.measurement_registry) ~= 4
    error('stage8_k2_va_build_context:FrozenPlan', ...
        'The frozen Stage8 domain or measurement registry changed.');
end

tangent_context = stage8_k2_tp_build_context(repo_dir);
if ~isequal(tangent_context.plan.local_domain.domain_bounds_deg, ...
        expected_bounds)
    error('stage8_k2_va_build_context:TangentContext', ...
        'The frozen Tangent context disagrees with the local domain.');
end

context = struct('repo_dir', repo_dir, 'constants', constants, ...
    'plan', plan, 'stage5_locked', build_stage8_stage5_locked_config(), ...
    'tangent_context', tangent_context, ...
    'classical_constants', stage8_k2_cb_constants(), ...
    'primary_measurement_config_id', ...
    constants.primary_measurement_config_id, ...
    'single_cpi_flag', true, ...
    'same_range_doppler_cell_flag', true, ...
    'cross_cpi_data_used_flag', false, ...
    'tracking_input_used_flag', false, ...
    'K_estimated_inside_module_flag', false);
context.context_hash = stage8_k2_va_stable_hash(constants.protocol, ...
    plan.local_domain.domain_hash, plan.stage8_measurement_plan_hash, ...
    tangent_context.context_hash, constants.base_commit);
end
