function output = stage8_k2_va_summarize( ...
    method_rows, diagnostics, registry, repo_dir, runtime_root, ...
    theory_tests, preflight)
%STAGE8_K2_VA_SUMMARIZE Write the fixed V1 evidence and decision.

if nargin < 6 || isempty(theory_tests)
    theory_tests = struct2table(struct('test_name', "NOT_RECORDED", ...
        'pass', false));
end
if nargin < 7 || isempty(preflight)
    preflight = struct('pass', false, 'last_error', 'NOT_RECORDED');
end
constants = stage8_k2_va_constants();
validate_inputs_local(method_rows, diagnostics, registry, constants);
summary_rows = build_summary_rows_local(method_rows, constants);
paired = build_paired_rows_local(method_rows, constants);
summary_rows = [summary_rows; paired.rows];
summary_table = struct2table(summary_rows);
complexity = build_complexity_local(method_rows, constants);
integrity = integrity_local(method_rows, diagnostics, registry, ...
    constants, preflight);
conclusion = decision_local(summary_table, paired.records, integrity, ...
    constants);
decision_row = summary_template_local();
decision_row.row_type = "DECISION";
decision_row.scope_type = "ALL";
decision_row.scope_value = "ALL";
decision_row.decision = string(conclusion);
summary_table = [summary_table; struct2table(decision_row)];
profile_summary = summary_table(summary_table.row_type == "METHOD" & ...
    summary_table.scope_type == "PROFILE", :);
overall = build_overall_local(summary_table, diagnostics, complexity, ...
    paired.records, constants);

evidence_dir = fullfile(repo_dir, 'innovation-mining');
paths = evidence_paths_local(evidence_dir);
path_names = fieldnames(paths);
for index = 1:numel(path_names)
    if isfile(paths.(path_names{index}))
        error('stage8_k2_va_summarize:ExistingEvidence', ...
            'Refusing to overwrite existing evidence: %s', ...
            paths.(path_names{index}));
    end
end
if ~isfolder(runtime_root)
    mkdir(runtime_root);
end
writetable(method_rows, fullfile(runtime_root, ...
    '36_stage8_k2_vincent_anchored_aml_trials.csv'));
writetable(summary_table, fullfile(runtime_root, ...
    '36_stage8_k2_vincent_anchored_aml_summary.csv'));
writetable(profile_summary, fullfile(runtime_root, ...
    '36_stage8_k2_vincent_anchored_aml_profile_summary.csv'));
writetable(diagnostics, fullfile(runtime_root, ...
    '36_stage8_k2_vincent_anchored_aml_diagnostics.csv'));
writetable(complexity, fullfile(runtime_root, ...
    '36_stage8_k2_vincent_anchored_aml_complexity.csv'));
writetable(theory_tests, fullfile(runtime_root, 'theory_tests.csv'));
writetable(method_rows, paths.trials);
writetable(summary_table, paths.summary);
writetable(profile_summary, paths.profile_summary);
writetable(diagnostics, paths.diagnostics);
writetable(complexity, paths.complexity);
write_report_local(paths.report, method_rows, diagnostics, profile_summary, ...
    complexity, theory_tests, overall, integrity, conclusion, constants, ...
    runtime_root);
output = struct('summary_table', summary_table, ...
    'profile_summary', profile_summary, 'complexity', complexity, ...
    'overall', overall, 'paired', paired, 'integrity', integrity, ...
    'conclusion', conclusion, 'evidence_paths', paths);
end

function rows = build_summary_rows_local(method_rows, constants)
rows = repmat(summary_template_local(), 0, 1);
scope_types = ["ALL"; "PROFILE"; "L"; "SNR_DB"; "NOISE"];
scope_values = {["ALL"], ["P1", "P2", "P3", "P4"], ...
    ["1", "4", "8"], ["-6", "0", "6"], ...
    ["WHITE", "STAGE5_TOEPLITZ_CORRELATED"]};
for method_index = 1:numel(constants.method_ids)
    method_id = constants.method_ids(method_index);
    method_subset = method_rows(method_rows.method_id == method_id, :);
    for scope_index = 1:numel(scope_types)
        for value_index = 1:numel(scope_values{scope_index})
            scope_value = scope_values{scope_index}(value_index);
            subset = select_scope_local(method_subset, ...
                scope_types(scope_index), scope_value);
            rows(end + 1, 1) = metric_row_local(scope_types(scope_index), ...
                scope_value, method_id, subset); %#ok<AGROW>
        end
    end
end
end

function subset = select_scope_local(rows, scope_type, scope_value)
switch char(scope_type)
    case 'ALL'
        subset = rows;
    case 'PROFILE'
        subset = rows(rows.profile_id == scope_value, :);
    case 'L'
        subset = rows(rows.L == str2double(scope_value), :);
    case 'SNR_DB'
        subset = rows(rows.snr_db == str2double(scope_value), :);
    case 'NOISE'
        subset = rows(rows.noise_profile_id == scope_value, :);
    otherwise
        error('stage8_k2_va_summarize:Scope', ...
            'Unknown summary scope.');
end
end

function row = metric_row_local(scope_type, scope_value, method_id, subset)
row = summary_template_local();
row.row_type = "METHOD";
row.scope_type = string(scope_type);
row.scope_value = string(scope_value);
row.method_id = string(method_id);
row.trial_count = height(subset);
row.valid_count = nnz(subset.fit_valid);
valid = subset.fit_valid & isfinite(subset.joint_RMSE_deg);
row.median_joint_RMSE_deg = median_or_nan_local( ...
    subset.joint_RMSE_deg(valid));
row.p90_joint_RMSE_deg = percentile_or_nan_local( ...
    subset.joint_RMSE_deg(valid), 90);
row.median_center_error_deg = median_or_nan_local( ...
    subset.center_error_deg(valid));
row.p90_center_error_deg = percentile_or_nan_local( ...
    subset.center_error_deg(valid), 90);
row.median_axis_error_deg = median_or_nan_local( ...
    subset.axis_error_deg(valid));
row.p90_axis_error_deg = percentile_or_nan_local( ...
    subset.axis_error_deg(valid), 90);
row.median_rho_error_deg = median_or_nan_local( ...
    subset.separation_error_deg(valid));
row.p90_rho_error_deg = percentile_or_nan_local( ...
    subset.separation_error_deg(valid), 90);
row.median_separation_vector_error_deg = median_or_nan_local( ...
    subset.separation_vector_error_deg(valid));
row.p90_separation_vector_error_deg = percentile_or_nan_local( ...
    subset.separation_vector_error_deg(valid), 90);
row.mean_score_calls = mean_or_nan_local(subset.score_call_count);
row.mean_SVD_calls = mean_or_nan_local(subset.SVD_call_count);
row.median_runtime_sec = median_or_nan_local(subset.runtime_sec);
row.p90_runtime_sec = percentile_or_nan_local(subset.runtime_sec, 90);
end

function paired = build_paired_rows_local(method_rows, constants)
specifications = { ...
    "ALL", "ALL", "VINCENT_ANCHORED_PROJECTOR_AML_SAFE", ...
        "TANGENT_PROFILE_SAFE"; ...
    "PROFILE", "P2", "VINCENT_ANCHORED_PROJECTOR_AML_SAFE", ...
        "TANGENT_PROFILE_SAFE"; ...
    "PROFILE", "P4", "VINCENT_ANCHORED_PROJECTOR_AML_SAFE", ...
        "TANGENT_PROFILE_SAFE"; ...
    "ALL", "ALL", "VINCENT_ANCHORED_PROJECTOR_AML_SAFE", ...
        "FULL4D_BEAMSPACE_CML_MULTISTART"};
rows = repmat(summary_template_local(), size(specifications, 1), 1);
records = repmat(struct('comparison_id', "", 'scope_type', "", ...
    'scope_value', "", 'pairs', 0, 'wins', 0, 'ties', 0, 'losses', 0), ...
    size(specifications, 1), 1);
for index = 1:size(specifications, 1)
    scope_type = specifications{index, 1};
    scope_value = specifications{index, 2};
    method_a = specifications{index, 3};
    method_b = specifications{index, 4};
    a = select_scope_local(method_rows( ...
        method_rows.method_id == method_a, :), scope_type, scope_value);
    b = select_scope_local(method_rows( ...
        method_rows.method_id == method_b, :), scope_type, scope_value);
    a = sortrows(a, 'trial_id');
    b = sortrows(b, 'trial_id');
    if ~isequal(a.trial_id, b.trial_id)
        error('stage8_k2_va_summarize:Pairing', ...
            'Paired method rows do not share trial identities.');
    end
    delta = a.joint_RMSE_deg - b.joint_RMSE_deg;
    finite_pair = isfinite(delta);
    tie = finite_pair & abs(delta) <= constants.paired_tie_tolerance_deg;
    win = finite_pair & delta < -constants.paired_tie_tolerance_deg;
    loss = finite_pair & delta > constants.paired_tie_tolerance_deg;
    comparison_id = method_a + "_vs_" + method_b;
    rows(index).row_type = "PAIRED";
    rows(index).scope_type = scope_type;
    rows(index).scope_value = scope_value;
    rows(index).method_id = method_a;
    rows(index).comparison_id = comparison_id;
    rows(index).trial_count = nnz(finite_pair);
    rows(index).paired_count = nnz(finite_pair);
    rows(index).wins = nnz(win);
    rows(index).ties = nnz(tie);
    rows(index).losses = nnz(loss);
    records(index) = struct('comparison_id', comparison_id, ...
        'scope_type', scope_type, 'scope_value', scope_value, ...
        'pairs', nnz(finite_pair), 'wins', nnz(win), ...
        'ties', nnz(tie), 'losses', nnz(loss));
end
paired = struct('rows', rows, 'records', records);
end

function complexity = build_complexity_local(method_rows, constants)
rows = cell(numel(constants.method_ids), 1);
for index = 1:numel(constants.method_ids)
    method_id = constants.method_ids(index);
    subset = method_rows(method_rows.method_id == method_id, :);
    rows{index} = struct('method_id', string(method_id), ...
        'applicable_count', nnz(subset.applicable), ...
        'valid_count', nnz(subset.fit_valid), ...
        'mean_score_calls', mean_or_nan_local(subset.score_call_count), ...
        'mean_SVD_calls', mean_or_nan_local(subset.SVD_call_count), ...
        'median_runtime_sec', median_or_nan_local(subset.runtime_sec), ...
        'p90_runtime_sec', percentile_or_nan_local(subset.runtime_sec, 90));
end
complexity = struct2table(vertcat(rows{:}));
end

function overall = build_overall_local(summary, diagnostics, complexity, ...
    paired_records, constants)
overall = struct();
for index = 1:numel(constants.method_ids)
    method_id = constants.method_ids(index);
    summary_row = lookup_metric_local(summary, method_id, "ALL", "ALL");
    cost = complexity(complexity.method_id == method_id, :);
    field = method_field_local(method_id);
    overall.(field) = struct('valid_count', summary_row.valid_count, ...
        'median_joint_RMSE_deg', summary_row.median_joint_RMSE_deg, ...
        'p90_joint_RMSE_deg', summary_row.p90_joint_RMSE_deg, ...
        'median_center_error_deg', summary_row.median_center_error_deg, ...
        'p90_center_error_deg', summary_row.p90_center_error_deg, ...
        'mean_score_calls', cost.mean_score_calls, ...
        'mean_SVD_calls', cost.mean_SVD_calls, ...
        'median_runtime_sec', cost.median_runtime_sec, ...
        'p90_runtime_sec', cost.p90_runtime_sec);
end
selected_alpha = diagnostics.selected_alpha_deg( ...
    isfinite(diagnostics.selected_alpha_deg));
p2 = diagnostics(diagnostics.profile_id == "P2", :);
p2_alpha = p2.selected_alpha_deg(isfinite(p2.selected_alpha_deg));
overall.anchored_diagnostics = struct( ...
    'raw_valid_count', nnz(diagnostics.raw_candidate_valid), ...
    'upgrade_count', nnz(diagnostics.upgrade_flag), ...
    'fallback_count', nnz(diagnostics.fallback_flag), ...
    'conditional_invalid_count', sum(diagnostics.conditional_invalid_count), ...
    'q2_nonconcave_count', sum(diagnostics.q2_nonconcave_count), ...
    'rho_out_of_contract_count', ...
    sum(diagnostics.rho_out_of_contract_count), ...
    'selected_alpha_median_deg', median_or_nan_local(selected_alpha), ...
    'selected_alpha_p90_deg', percentile_or_nan_local(selected_alpha, 90), ...
    'P2_alpha_median_deg', median_or_nan_local(p2_alpha), ...
    'P2_alpha_p90_deg', percentile_or_nan_local(p2_alpha, 90), ...
    'median_axis_error_deg', median_or_nan_local( ...
        diagnostics.axis_error_deg), ...
    'p90_axis_error_deg', percentile_or_nan_local( ...
        diagnostics.axis_error_deg, 90), ...
    'median_rho_error_deg', median_or_nan_local( ...
        diagnostics.rho_error_deg), ...
    'p90_rho_error_deg', percentile_or_nan_local( ...
        diagnostics.rho_error_deg, 90), ...
    'median_vector_error_deg', median_or_nan_local( ...
        diagnostics.separation_vector_error_deg), ...
    'p90_vector_error_deg', percentile_or_nan_local( ...
        diagnostics.separation_vector_error_deg, 90));
overall.paired = paired_records;
end

function integrity = integrity_local(method_rows, diagnostics, registry, ...
    constants, preflight)
pair_ids = method_rows.trial_id + "|" + method_rows.method_id;
count_ok = height(registry) == constants.trial_count && ...
    height(method_rows) == constants.method_row_count && ...
    height(diagnostics) == constants.trial_count && ...
    numel(unique(pair_ids)) == constants.method_row_count && ...
    numel(unique(diagnostics.trial_id)) == constants.trial_count;
truth_ok = ~any(method_rows.truth_used_in_fit_flag) && ...
    ~any(diagnostics.truth_used_in_fit_flag);
scenario_ok = all(method_rows.single_cpi_flag) && ...
    all(method_rows.same_range_doppler_cell_flag) && ...
    ~any(method_rows.cross_cpi_data_used_flag) && ...
    ~any(method_rows.tracking_input_used_flag) && ...
    ~any(method_rows.K_estimated_inside_module_flag);
hash_ok = true;
registry_ok = true;
for index = 1:height(registry)
    subset = method_rows(method_rows.trial_id == registry.trial_id(index), :);
    diagnostic = diagnostics(diagnostics.trial_id == ...
        registry.trial_id(index), :);
    hash_ok = hash_ok && height(subset) == 4 && height(diagnostic) == 1 && ...
        numel(unique(subset.element_trial_hash)) == 1 && ...
        unique(subset.element_trial_hash) == diagnostic.element_trial_hash;
    registry_ok = registry_ok && height(subset) == 4 && ...
        all(subset.noise_profile_id == registry.noise_profile_id(index)) && ...
        all(subset.L == registry.L(index)) && ...
        all(subset.snr_db == registry.snr_db(index)) && ...
        all(subset.profile_id == registry.profile_id(index)) && ...
        all(subset.source_seed == registry.source_seed(index)) && ...
        all(subset.noise_seed == registry.noise_seed(index));
end
m2 = method_rows(method_rows.method_id == ...
    "VINCENT_ANCHORED_PROJECTOR_AML_SAFE", :);
m2_safe = height(m2) == constants.trial_count && all(m2.fit_valid) && ...
    all(isfinite(m2.RSS)) && all(isfinite(m2.loglik)) && ...
    all(isfinite(m2.joint_RMSE_deg));
required = method_rows(method_rows.method_id ~= ...
    "FULL4D_BEAMSPACE_CML_MULTISTART", :);
finite_required = all(isfinite(required.loglik(required.fit_valid)));
integrity = struct('count_ok', count_ok, 'truth_isolation_ok', truth_ok, ...
    'scenario_ok', scenario_ok, 'element_pairing_ok', hash_ok, ...
    'registry_pairing_ok', registry_ok, 'm2_safe_return_ok', m2_safe, ...
    'finite_required_outputs_ok', finite_required, ...
    'preflight_ok', logical(get_local(preflight, 'pass', false)), ...
    'experiment_valid', count_ok && truth_ok && scenario_ok && hash_ok && ...
    registry_ok && m2_safe && finite_required && ...
    logical(get_local(preflight, 'pass', false)));
end

function conclusion = decision_local(summary_rows, paired_records, ...
    integrity, constants)
if ~integrity.experiment_valid
    conclusion = 'STAGE8_K2_VINCENT_ANCHORED_AML_EXPERIMENT_INVALID';
    return;
end
m2 = lookup_metric_local(summary_rows, ...
    "VINCENT_ANCHORED_PROJECTOR_AML_SAFE", "ALL", "ALL");
m1 = lookup_metric_local(summary_rows, ...
    "TANGENT_PROFILE_SAFE", "ALL", "ALL");
m3 = lookup_metric_local(summary_rows, ...
    "FULL4D_BEAMSPACE_CML_MULTISTART", "ALL", "ALL");
p2_m2 = lookup_metric_local(summary_rows, ...
    "VINCENT_ANCHORED_PROJECTOR_AML_SAFE", "PROFILE", "P2");
p2_m1 = lookup_metric_local(summary_rows, ...
    "TANGENT_PROFILE_SAFE", "PROFILE", "P2");
overall_pair = paired_records(1);
retain = m2.valid_count == constants.trial_count && ...
    m2.median_joint_RMSE_deg <= m1.median_joint_RMSE_deg && ...
    m2.p90_joint_RMSE_deg <= m1.p90_joint_RMSE_deg && ...
    overall_pair.wins >= overall_pair.losses && ...
    p2_m2.median_joint_RMSE_deg < p2_m1.median_joint_RMSE_deg && ...
    p2_m2.median_center_error_deg < p2_m1.median_center_error_deg && ...
    m2.mean_score_calls < m3.mean_score_calls && ...
    m2.mean_SVD_calls < m3.mean_SVD_calls;
if retain
    conclusion = 'STAGE8_K2_VINCENT_ANCHORED_AML_RETAIN';
else
    conclusion = 'STAGE8_K2_VINCENT_ANCHORED_AML_NOT_RETAINED';
end
end

function row = lookup_metric_local(rows, method_id, scope_type, scope_value)
selected = rows(rows.row_type == "METHOD" & rows.method_id == method_id & ...
    rows.scope_type == scope_type & rows.scope_value == scope_value, :);
if height(selected) ~= 1
    error('stage8_k2_va_summarize:MetricLookup', ...
        'Expected exactly one metric row.');
end
row = selected;
end

function write_report_local(path_now, method_rows, diagnostics, ...
    profile_summary, complexity, theory_tests, overall, integrity, ...
    conclusion, constants, runtime_root)
[status, head] = system('git rev-parse HEAD');
if status ~= 0, head = 'UNKNOWN'; else, head = strtrim(head); end
fid = fopen(path_now, 'w');
if fid < 0
    error('stage8_k2_va_summarize:ReportOpen', ...
        'Unable to create the experiment report.');
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# Stage8 K2 Vincent Anchored Projector AML Experiment\n\n');
fprintf(fid, 'Protocol: %s\n\nExecution HEAD: %s\n\n', ...
    constants.protocol, head);
fprintf(fid, 'Runtime root: %s\n\n', strrep(runtime_root, char(92), '/'));
fprintf(fid, 'Base: %s\n\n', constants.base_commit);
fprintf(fid, '## Contract and integrity\n\n');
fprintf(fid, '- Registry 72/72 trials; method rows %d/%d; diagnostics %d/72.\n', ...
    height(method_rows), constants.method_row_count, height(diagnostics));
fprintf(fid, '- Counts %d; truth isolation %d; shared hashes %d; registry/seeds %d; scenario %d; finite outputs %d; preflight %d.\n\n', ...
    integrity.count_ok, integrity.truth_isolation_ok, ...
    integrity.element_pairing_ok, integrity.registry_pairing_ok, ...
    integrity.scenario_ok, integrity.finite_required_outputs_ok, ...
    integrity.preflight_ok);
fprintf(fid, '## Theory tests\n\n');
for index = 1:height(theory_tests)
    fprintf(fid, '- %s: %s.\n', char(theory_tests.test_name(index)), ...
        ternary_local(logical(theory_tests.pass(index)), 'PASS', 'FAIL'));
end
fprintf(fid, '\n## Overall methods\n\n');
fprintf(fid, '| Method | Valid | Median/P90 joint RMSE deg | Median/P90 center deg | Mean score | Mean SVD | Median/P90 runtime sec |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|\n');
for index = 1:numel(constants.method_ids)
    id = constants.method_ids(index);
    value = overall.(method_field_local(id));
    fprintf(fid, '| %s | %d/72 | %.17g / %.17g | %.17g / %.17g | %.17g | %.17g | %.17g / %.17g |\n', ...
        char(id), value.valid_count, value.median_joint_RMSE_deg, ...
        value.p90_joint_RMSE_deg, value.median_center_error_deg, ...
        value.p90_center_error_deg, value.mean_score_calls, ...
        value.mean_SVD_calls, value.median_runtime_sec, ...
        value.p90_runtime_sec);
end
fprintf(fid, '\n## Anchored diagnostics\n\n');
d = overall.anchored_diagnostics;
fprintf(fid, '- Raw valid %d/72; upgrades/fallbacks %d/%d.\n', ...
    d.raw_valid_count, d.upgrade_count, d.fallback_count);
fprintf(fid, '- Conditional invalid anchors %d; q2 nonconcave %d; rho out of contract %d.\n', ...
    d.conditional_invalid_count, d.q2_nonconcave_count, ...
    d.rho_out_of_contract_count);
fprintf(fid, '- Selected alpha median/p90 %.17g / %.17g deg; P2 alpha median/p90 %.17g / %.17g deg.\n', ...
    d.selected_alpha_median_deg, d.selected_alpha_p90_deg, ...
    d.P2_alpha_median_deg, d.P2_alpha_p90_deg);
fprintf(fid, '- Axis median/p90 %.17g / %.17g deg; rho median/p90 %.17g / %.17g deg; vector median/p90 %.17g / %.17g deg.\n\n', ...
    d.median_axis_error_deg, d.p90_axis_error_deg, ...
    d.median_rho_error_deg, d.p90_rho_error_deg, ...
    d.median_vector_error_deg, d.p90_vector_error_deg);
fprintf(fid, '## Profile summaries\n\n');
fprintf(fid, '| Profile | Method | Valid | Median/P90 joint RMSE deg | Median/P90 center deg | Median/P90 rho error deg |\n');
fprintf(fid, '|---|---|---:|---:|---:|---:|\n');
for index = 1:height(profile_summary)
    row = profile_summary(index, :);
    fprintf(fid, '| %s | %s | %d/%d | %.17g / %.17g | %.17g / %.17g | %.17g / %.17g |\n', ...
        char(row.scope_value), char(row.method_id), row.valid_count, ...
        row.trial_count, row.median_joint_RMSE_deg, ...
        row.p90_joint_RMSE_deg, row.median_center_error_deg, ...
        row.p90_center_error_deg, row.median_rho_error_deg, ...
        row.p90_rho_error_deg);
end
fprintf(fid, '\n## Paired comparisons\n\n');
fprintf(fid, '| Scope | Comparison | Pairs | Wins | Ties | Losses |\n');
fprintf(fid, '|---|---|---:|---:|---:|---:|\n');
for index = 1:numel(overall.paired)
    pair = overall.paired(index);
    fprintf(fid, '| %s=%s | %s | %d | %d | %d | %d |\n', ...
        char(pair.scope_type), char(pair.scope_value), ...
        char(pair.comparison_id), pair.pairs, pair.wins, ...
        pair.ties, pair.losses);
end
fprintf(fid, '\nTie tolerance is reporting-only at 1e-6 deg.\n\n');
fprintf(fid, '## Complexity\n\n');
for index = 1:height(complexity)
    row = complexity(index, :);
    fprintf(fid, '- %s: mean score/SVD %.17g / %.17g; median/p90 runtime %.17g / %.17g sec.\n', ...
        char(row.method_id), row.mean_score_calls, row.mean_SVD_calls, ...
        row.median_runtime_sec, row.p90_runtime_sec);
end
fprintf(fid, '\nFull4D is diagnostic only and does not participate in anchored safe selection.\n\n');
fprintf(fid, '## Decision\n\nFinal conclusion: %s\n\n', conclusion);
fprintf(fid, 'Production integration authorized: false.\n\n');
fprintf(fid, '## Prior-art positioning\n\n');
fprintf(fid, 'Vincent, Besson, and Chaumette (2014, DOI 10.1016/j.sigpro.2013.10.017) and Bonacci, Vincent, and Gigleux (2017, DOI 10.1049/iet-rsn.2016.0446) motivate close-source conditional AML expansions. This result is positioned only as a system-specific implementation on the fixed exactly whitened cylindrical-array sequential beamspace curve. No first-in-field claim is made; an identical combination is SYSTEM-SPECIFIC IMPLEMENTATION / ENGINEERING SPECIALIZATION.\n\n');
fprintf(fid, '## Stop boundary\n\nNo second axis, perpendicular offset, two-dimensional anchor grid, fourth-order expansion, extra starts, automatic K, bootstrap, more trials, V2, or production integration is authorized.\n');
end

function row = summary_template_local()
row = struct('row_type', "", 'scope_type', "", 'scope_value', "", ...
    'method_id', "", 'trial_count', NaN, 'valid_count', NaN, ...
    'median_joint_RMSE_deg', NaN, 'p90_joint_RMSE_deg', NaN, ...
    'median_center_error_deg', NaN, 'p90_center_error_deg', NaN, ...
    'median_axis_error_deg', NaN, 'p90_axis_error_deg', NaN, ...
    'median_rho_error_deg', NaN, 'p90_rho_error_deg', NaN, ...
    'median_separation_vector_error_deg', NaN, ...
    'p90_separation_vector_error_deg', NaN, ...
    'mean_score_calls', NaN, 'mean_SVD_calls', NaN, ...
    'median_runtime_sec', NaN, 'p90_runtime_sec', NaN, ...
    'comparison_id', "", 'paired_count', NaN, 'wins', NaN, ...
    'ties', NaN, 'losses', NaN, 'decision', "");
end

function paths = evidence_paths_local(directory)
prefix = fullfile(directory, '36_stage8_k2_vincent_anchored_aml_');
paths = struct('report', [prefix, 'experiment.md'], ...
    'trials', [prefix, 'trials.csv'], ...
    'summary', [prefix, 'summary.csv'], ...
    'profile_summary', [prefix, 'profile_summary.csv'], ...
    'diagnostics', [prefix, 'diagnostics.csv'], ...
    'complexity', [prefix, 'complexity.csv']);
end

function field = method_field_local(method_id)
field = lower(char(method_id));
field = strrep(field, '-', '_');
end

function validate_inputs_local(method_rows, diagnostics, registry, constants)
if ~(istable(method_rows) && istable(diagnostics) && istable(registry) && ...
        height(registry) == constants.trial_count && ...
        height(method_rows) == constants.method_row_count && ...
        height(diagnostics) == constants.trial_count)
    error('stage8_k2_va_summarize:Input', ...
        'Summary tables do not satisfy the 72/288/72 contract.');
end
end

function value = mean_or_nan_local(values)
values = values(isfinite(values));
if isempty(values), value = NaN; else, value = mean(values); end
end

function value = median_or_nan_local(values)
values = values(isfinite(values));
if isempty(values), value = NaN; else, value = median(values); end
end

function value = percentile_or_nan_local(values, percentage)
values = sort(values(isfinite(values)));
if isempty(values)
    value = NaN;
    return;
end
position = 1 + (numel(values) - 1) * percentage / 100;
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    weight = position - lower;
    value = (1 - weight) * values(lower) + weight * values(upper);
end
end

function value = get_local(input, field, default)
if isfield(input, field)
    value = input.(field);
else
    value = default;
end
end

function value = ternary_local(condition, yes_value, no_value)
if condition, value = yes_value; else, value = no_value; end
end
