function metrics = stage8_k2_va_geometry_metrics( ...
    true_center_deg, k1_center_deg, axis_hat, rho_true_deg, ...
    selected_alpha_deg)
%STAGE8_K2_VA_GEOMETRY_METRICS Decompose the frozen K1 center error.

true_center_deg = reshape(double(true_center_deg), 1, []);
k1_center_deg = reshape(double(k1_center_deg), 1, []);
axis_hat = reshape(double(axis_hat), 1, []);
if numel(true_center_deg) ~= 2 || numel(k1_center_deg) ~= 2 || ...
        numel(axis_hat) ~= 2 || any(~isfinite(true_center_deg)) || ...
        any(~isfinite(k1_center_deg)) || any(~isfinite(axis_hat))
    error('stage8_k2_va_geometry_metrics:Input', ...
        'Centers and axis must be finite two-vectors.');
end
axis_norm = norm(axis_hat);
if abs(axis_norm - 1) > 1e-10
    error('stage8_k2_va_geometry_metrics:AxisNorm', ...
        'The frozen tangent axis is not unit norm.');
end
if ~(isscalar(rho_true_deg) && isfinite(rho_true_deg) && ...
        rho_true_deg > 0)
    error('stage8_k2_va_geometry_metrics:Rho', ...
        'True separation must be finite and positive.');
end
center_offset = true_center_deg - k1_center_deg;
alpha_true = dot(axis_hat, center_offset);
perpendicular = center_offset - alpha_true * axis_hat;
metrics = struct( ...
    'center_offset_deg', center_offset, ...
    'alpha_true_deg', alpha_true, ...
    'perpendicular_offset_deg', perpendicular, ...
    'b_parallel_abs', abs(alpha_true) / rho_true_deg, ...
    'b_perp', norm(perpendicular) / rho_true_deg, ...
    'alpha_correction_error_normalized', NaN);
if isfinite(selected_alpha_deg)
    metrics.alpha_correction_error_normalized = ...
        abs(selected_alpha_deg - alpha_true) / rho_true_deg;
end
end
