function report = run_stage7_1_closure_audit()
%RUN_STAGE7_1_CLOSURE_AUDIT Execute the formal Stage7.1 closure workflow.

step_dir = fileparts(mfilename('fullpath'));
steps_dir = fileparts(step_dir);
project_dir = fileparts(steps_dir);
package_dir = fileparts(fileparts(project_dir));
repo_dir = fileparts(package_dir);
stage7_dir = fullfile(steps_dir, ...
    'step_12_5_exact_subset_fim_beam_design');
stage7_result_dir = fullfile(stage7_dir, 'results');
result_dir = fullfile(step_dir, 'results');
old_path = path;
addpath(fullfile(step_dir, 'common'));
addpath(fullfile(step_dir, 'tests'));
addpath(fullfile(stage7_dir, 'common'));
addpath(fullfile(stage7_dir, 'tests'));
path_cleanup = onCleanup(@() path(old_path));

if ~strcmp(version('-release'), '2022b')
    error('run_stage7_1_closure_audit:MatlabRelease', ...
        'Formal Stage7.1 closure requires MATLAB R2022b.');
end
identity = build_stage7_1_code_identity(repo_dir, ...
    struct('formal_mode', true));
stage7_evidence = validate_stage7_evidence_local(stage7_result_dir);
[stage6_frozen, stage6_context] = verify_stage6_frozen_evidence(package_dir);
[stage5_frozen, stage5_context] = verify_stage5_frozen_results(package_dir);
[step11_frozen, step11_context] = verify_step11_frozen_results(package_dir);
if ~(all(stage7_evidence.pass_flag) && all(stage6_frozen.pass_flag) && ...
        all(stage5_frozen.pass_flag) && all(step11_frozen.pass_flag))
    error('run_stage7_1_closure_audit:FrozenEvidence', ...
        'Stage7/6/5/Step11 frozen evidence validation failed.');
end

[historical_comparison, historical_summary] = ...
    compare_stage7_core_results_to_commit( ...
    repo_dir, stage7_result_dir, struct());
if ~all(historical_summary.pass_flag)
    error('run_stage7_1_closure_audit:HistoricalComparison', ...
        'Stage 7 core results differ from the locked historical commit.');
end
execution = build_stage7_1_execution_context( ...
    repo_dir, stage7_dir, stage7_result_dir);
semantics = sequential_semantics_local(execution.stage7_plan.pool);
aliases = build_stage7_method_subset_alias_table(stage7_result_dir);
minimum_cost = enumerate_stage7_minimum_cost_feasible_set( ...
    stage7_result_dir, 0.80);
same_cost_dominance = minimum_cost(:, { ...
    'subset_id','MAC_total','eta_design','eta_validation','eta_holdout', ...
    'registered_selection_flag','same_cost_dominates_registered_flag', ...
    'dominance_reason'});
pareto = apply_stage7_pareto_to_existing_methods(stage7_result_dir);
dimensions = build_stage7_1_complexity_dimensions_from_frozen_plan( ...
    execution.stage7_plan);
complexity = compute_stage7_complexity_accounting_correction( ...
    stage7_result_dir, aliases, dimensions, struct());
memory = build_stage7_memory_contract_audit(stage7_result_dir, ...
    execution.stage7_plan, historical_summary, complexity);
if ~all(historical_summary.pass_flag) || ...
        ~memory.overall_memory_audit_pass
    error('run_stage7_1_closure_audit:MemoryContract', ...
        'Historical comparison or the Stage 7 memory contract failed.');
end
edge = run_stage7_1_edge_diagnostics(repo_dir, ...
    struct('execution_context', execution));
if edge.stage7_selection_changed_flag || ...
        edge.common_trial_generation_count ~= 3600 || ...
        edge.method_evaluation_count ~= 10800
    error('run_stage7_1_closure_audit:EdgeContract', ...
        'Formal edge diagnostic execution violated its frozen count contract.');
end

keypoints = keypoints_local(identity, historical_summary, memory, edge);
closure_report = closure_report_local();
runtime_diagnostics = edge.runtime_diagnostics;
runtime_diagnostics.runtime_scope = repmat( ...
    "EDGE_METHOD_EVALUATION_ONLY", height(runtime_diagnostics), 1);
bundle = struct('identity', identity, ...
    'historical_comparison', historical_comparison, ...
    'historical_summary', historical_summary, ...
    'sequential_semantics', semantics, 'aliases', aliases, ...
    'minimum_cost', minimum_cost, ...
    'same_cost_dominance', same_cost_dominance, ...
    'pareto', pareto, 'complexity', complexity, ...
    'memory_contract_audit', memory, 'edge', edge, ...
    'keypoints', keypoints, 'closure_report', closure_report, ...
    'runtime_diagnostics', runtime_diagnostics);
[outputs, evidence_manifest, evidence_bundle] = ...
    write_stage7_1_results_bundle(result_dir, bundle, struct());
if ~evidence_bundle.pass_flag
    error('run_stage7_1_closure_audit:EvidenceManifest', ...
        'The Stage7.1 deterministic evidence manifest failed.');
end

report = struct('identity', identity, ...
    'stage7_evidence', stage7_evidence, ...
    'stage6_frozen', stage6_frozen, 'stage6_context', stage6_context, ...
    'stage5_frozen', stage5_frozen, 'stage5_context', stage5_context, ...
    'step11_frozen', step11_frozen, 'step11_context', step11_context, ...
    'historical_summary', historical_summary, ...
    'memory_contract_audit', memory, ...
    'edge_execution', edge, 'evidence_manifest', evidence_manifest, ...
    'evidence_bundle', evidence_bundle, 'outputs', outputs, ...
    'stage7_status', 'PASS_SYSTEM_ANALYSIS_ONLY', ...
    'stage8_technical_permission', false, ...
    'closure_status', 'PASS_STAGE7_1_CLOSURE_AUDIT');
fprintf(['Stage7.1 closure audit complete: historical=%d, ', ...
    'edge=%d/%d, bundle=%s\n'], historical_summary.pass_flag, ...
    edge.common_trial_generation_count, edge.method_evaluation_count, ...
    evidence_bundle.stage7_1_evidence_bundle_hash);
fprintf('Stage 7 remains PASS_SYSTEM_ANALYSIS_ONLY. Stage 8 was not run.\n');
clear path_cleanup
end

function table_out = validate_stage7_evidence_local(result_dir)
required = ["stage7_plan_registry.csv";"stage7_subset_family.csv"; ...
    "fim_subset_enumeration.csv";"fim_operating_points.csv"; ...
    "finite_sample_normal_holdout.csv"; ...
    "finite_sample_threshold_holdout.csv"; ...
    "finite_sample_mismatch_holdout.csv"; ...
    "finite_sample_stress_holdout.csv";"stage7_keypoints.csv"];
exists_flag = false(numel(required), 1);
for index = 1:numel(required)
    exists_flag(index) = exist(fullfile(result_dir, required(index)), ...
        'file') == 2;
end
registry_path = fullfile(result_dir, 'stage7_plan_registry.csv');
registry_options = detectImportOptions(registry_path, 'TextType', 'string');
registry_options = setvartype(registry_options, ...
    {'registry_key','registry_value'}, 'string');
registry = readtable(registry_path, registry_options);
phase = registry.registry_value(registry.registry_key == "phase_factor");
family = readtable(fullfile(result_dir, 'stage7_subset_family.csv'), ...
    'TextType', 'string');
enumeration = readtable(fullfile(result_dir, ...
    'fim_subset_enumeration.csv'), 'TextType', 'string');
keypoints_path = fullfile(result_dir, 'stage7_keypoints.csv');
keypoint_options = detectImportOptions(keypoints_path, 'TextType', 'string');
keypoint_options = setvartype(keypoint_options, ...
    {'metric','value','unit','status'}, 'string');
keypoints = readtable(keypoints_path, keypoint_options);
status = keypoints.value(keypoints.metric == "stage7_status");
case_id = ["REQUIRED_RESULTS_PRESENT";"PHASE_FACTOR_ONE"; ...
    "SUBSET_FAMILY_961";"ENUMERATION_961"; ...
    "STAGE7_STATUS_SYSTEM_ANALYSIS_ONLY"];
pass_flag = [all(exists_flag);isscalar(phase) && phase == "1"; ...
    height(family) == 961 && numel(unique(family.subset_id)) == 961; ...
    height(enumeration) == 961 && ...
    numel(unique(enumeration.subset_id)) == 961; ...
    isscalar(status) && status == "PASS_SYSTEM_ANALYSIS_ONLY"];
table_out = table(case_id, pass_flag);
end

function audit = sequential_semantics_local(pool)
elevation = pool.center_3x3_elevation_indices;
V = pool.V(:, elevation);
Uset = pool.Uset(:, :, elevation);
N_el = size(V, 1);
N_az = size(Uset, 1);
values = reshape(1:(N_el * N_az), N_el, N_az);
Y = complex(values, flip(values, 2));
audit = audit_stage7_sequential_channel_semantics(V, Uset, Y);
if audit.B_el ~= 3 || audit.B_az ~= 5 || ...
        audit.equivalence_relative_error > 1e-12
    error('run_stage7_1_closure_audit:SequentialSemantics', ...
        'The frozen sequential 3/5 semantics audit failed.');
end
end

function keypoints = keypoints_local(identity, historical, memory, edge)
metric = ["stage7_1_closure_status";"stage7_status"; ...
    "stage8_technical_permission";"historical_comparison_status"; ...
    "historical_comparison_failed_count"; ...
    "stage7_core_scientific_comparison_status"; ...
    "stage7_diagnostic_variation_count"; ...
    "peak_memory_comparison_status";"peak_memory_delta_bytes"; ...
    "peak_memory_relative_delta"; ...
    "deterministic_memory_contract_status"; ...
    "edge_common_trial_generation_count"; ...
    "edge_method_evaluation_count";"stage7_selection_changed_flag"; ...
    "stage7_1_source_tree_hash";"stage7_1_stable_code_identity_hash"];
value = ["PASS_STAGE7_1_CLOSURE_AUDIT"; ...
    "PASS_SYSTEM_ANALYSIS_ONLY";"false"; ...
    string(historical.comparison_status); ...
    string(historical.failed_comparison_count); ...
    "PASS_STAGE7_CORE_SCIENTIFIC_MATCHES_HISTORICAL_COMMIT"; ...
    string(historical.diagnostic_variation_count); ...
    string(historical.peak_memory_comparison_status); ...
    string(memory.peak_memory_delta_bytes); ...
    string(memory.peak_memory_relative_delta); ...
    "PASS_DETERMINISTIC_MEMORY_CONTRACT"; ...
    string(edge.common_trial_generation_count); ...
    string(edge.method_evaluation_count);"false"; ...
    string(identity.stage7_1_source_tree_hash); ...
    string(identity.stage7_1_stable_code_identity_hash)];
unit = ["status";"status";"boolean";"status";"count"; ...
    "status";"count";"status";"byte";"ratio";"status"; ...
    "count";"count";"boolean";"sha256";"sha256"];
status = ["PASS";"PASS";"NOT_PERMITTED";"PASS";"PASS"; ...
    "PASS";"PASS";"PASS";"PASS";"PASS";"PASS"; ...
    "PASS";"PASS";"PASS";"PASS";"PASS"];
pass_flag = true(numel(metric), 1);
keypoints = table(metric, value, unit, status, pass_flag);
end

function text = closure_report_local()
text = ...
    "Formal Stage7.1 closure verifies the stable tracked-source identity, " + ...
    "upstream frozen evidence, and Git-object historical Stage7 results. " + ...
    "The scientific and algorithmic core matches the historical commit; " + ...
    "the only diagnostic variation is the schema-dependent legacy " + ...
    "workspace estimate caused by provenance context bytes. That diagnostic " + ...
    "is not a FIM, DML, finite-sample, or measured process-peak change. " + ...
    "The independent deterministic memory contract passes. The audit also " + ...
    "verifies " + ...
    "sequential 3/5 semantics, physical-subset aliases, minimum-cost and " + ...
    "same-cost sensitivity, existing-method Pareto intervals, corrected " + ...
    "complexity, and paired edge diagnostics. Stage 7 remains " + ...
    "PASS_SYSTEM_ANALYSIS_ONLY. These post-hoc audits do not alter Stage7 " + ...
    "selection and do not authorize or execute Stage8.";
end
