function context = build_stage8_known_k_local_context( ...
    Y_element, model, local_domain, stage5_locked, noise_model, opts)
%BUILD_STAGE8_KNOWN_K_LOCAL_CONTEXT Build only data-driven fixed context.

expected_stage5 = build_stage8_stage5_locked_config();
if ~strcmp(char(string(stage5_locked.configuration_hash)), ...
        char(string(expected_stage5.configuration_hash)))
    error('build_stage8_known_k_local_context:Stage5Identity', ...
        'stage5_locked differs from the frozen Stage5 configuration.');
end
full_data = build_stage8_full_data_from_element(Y_element, model, ...
    struct('data_role', 'SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
[initialization, initialization_debug] = ...
    build_stage8_initialization_context_from_data(full_data, model, ...
    local_domain, stage5_locked, noise_model, ...
    struct('rank_multiplier', opts.rank_multiplier));
context = struct('full_data', full_data, 'model', model, ...
    'local_domain', local_domain, 'stage5_locked', stage5_locked, ...
    'noise_model', noise_model, 'initialization', initialization, ...
    'initialization_debug', initialization_debug, ...
    'truth_used_in_initialization_flag', false, ...
    'tracking_input_used_flag', false, ...
    'cross_cpi_data_used_flag', false);
end
