function context = build_stage8_known_k_local_context( ...
    Y_element, model, local_domain, stage5_locked, noise_model, opts)
%BUILD_STAGE8_KNOWN_K_LOCAL_CONTEXT Build only data-driven fixed context.

expected_stage5 = build_stage8_stage5_locked_config();
stage5_admission_status = stage5_admission_local( ...
    stage5_locked, expected_stage5, model);
audit_available = exist('stage8_k2_tcc_audit_state', 'file') == 2;
prefix = audit_public_prefix_local(audit_available);
full_clock = audit_stage_start_local(audit_available, ...
    [prefix, '_FULL_DATA']);
full_data = build_stage8_full_data_from_element(Y_element, model, ...
    struct('data_role', 'SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
audit_stage_stop_local(audit_available, [prefix, '_FULL_DATA'], full_clock);
init_clock = audit_stage_start_local(audit_available, ...
    [prefix, '_INITIALIZATION_TOTAL']);
[initialization, initialization_debug] = ...
    build_stage8_initialization_context_from_data(full_data, model, ...
    local_domain, stage5_locked, noise_model, ...
    struct('rank_multiplier', opts.rank_multiplier, ...
    'fixed_registered_manifold_provider', ...
    opts.fixed_registered_manifold_provider, ...
    'fixed_registered_center_adapter', ...
    opts.fixed_registered_center_adapter, ...
    'fixed_manifold_mode', opts.fixed_manifold_mode));
audit_stage_stop_local(audit_available, [prefix, '_INITIALIZATION_TOTAL'], ...
    init_clock);
context = struct('full_data', full_data, 'model', model, ...
    'local_domain', local_domain, 'stage5_locked', stage5_locked, ...
    'noise_model', noise_model, 'initialization', initialization, ...
    'initialization_debug', initialization_debug, ...
    'fixed_registered_manifold_provider', ...
    opts.fixed_registered_manifold_provider, ...
    'fixed_registered_center_adapter', ...
    opts.fixed_registered_center_adapter, ...
    'fixed_manifold_mode', opts.fixed_manifold_mode, ...
    'stage5_admission_status', stage5_admission_status, ...
    'truth_used_in_initialization_flag', false, ...
    'tracking_input_used_flag', false, ...
    'cross_cpi_data_used_flag', false);
audit_record_initialization_local(audit_available, prefix, full_data, ...
    initialization);
end

function status = stage5_admission_local(locked, expected, model)
declared_hash = char(string(locked.configuration_hash));
expected_hash = char(string(expected.configuration_hash));
if strcmp(declared_hash, expected_hash)
    status = 'LEGACY_REFERENCE_EXACT_STAGE5_HASH_ACCEPTED';
    return;
end
required = {'stage5_rotation_class_hash','stage5_actual_center_hash', ...
    'stage5_requested_center_az_deg','stage5_physical_center_az_deg', ...
    'stage5_physical_center_unwrapped_az_deg','stage5_center_column', ...
    'stage5_rotation_delta_deg','stage5_rotation_certification_status', ...
    'stage5_reference_configuration_hash'};
if ~all(isfield(locked, required)) || ...
        exist('stage8_k2_mc_stage5_class_payload', 'file') ~= 2 || ...
        ~strcmp(char(string(locked.stage5_rotation_certification_status)), ...
        'STAGE8_K2_MC_STAGE5_ROTATION_CERTIFIED') || ...
        ~strcmp(char(string(locked.stage5_reference_configuration_hash)), ...
        expected_hash) || ...
        ~strcmp(build_stage5_configuration_hash(locked), declared_hash)
    error('build_stage8_known_k_local_context:Stage5RotationIdentity', ...
        'BLOCKED_STAGE5_ROTATION_CONTRACT.');
end
physical = double(locked.stage5_physical_center_unwrapped_az_deg);
delta = double(locked.stage5_rotation_delta_deg);
reference_physical = physical - delta;
current_payload = stage8_k2_mc_stage5_class_payload(locked, physical);
reference_payload = stage8_k2_mc_stage5_class_payload( ...
    expected, reference_physical);
current_class_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_STAGE5_ROTATION_CLASS_V1', current_payload);
reference_class_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_STAGE5_ROTATION_CLASS_V1', reference_payload);
actual_payload = struct( ...
    'configuration_hash',declared_hash, ...
    'requested_center_az_deg', ...
        double(locked.stage5_requested_center_az_deg), ...
    'physical_center_az_deg', ...
        double(locked.stage5_physical_center_az_deg), ...
    'physical_center_unwrapped_az_deg',physical, ...
    'center_column',double(locked.stage5_center_column), ...
    'rotation_delta_deg',delta, ...
    'absolute_conventional_center_deg',locked.conventional_center_deg, ...
    'absolute_az_beam_deg',locked.az_beam_deg);
actual_hash = stage8_stable_hash( ...
    'STAGE8_K2_MC_STAGE5_ACTUAL_CENTER_V1', actual_payload);
model_fields = {'actual_center_column','actual_physical_center_az_deg', ...
    'actual_physical_center_unwrapped_az_deg','requested_center_az_deg', ...
    'rotation_delta_deg','stage5_rotation_class_hash', ...
    'stage5_actual_center_hash'};
model_match = all(isfield(model, model_fields));
if model_match
    model_match = ...
        double(model.actual_center_column) == ...
            double(locked.stage5_center_column) && ...
        abs(double(model.actual_physical_center_az_deg) - ...
            double(locked.stage5_physical_center_az_deg)) <= 1e-12 && ...
        abs(double(model.actual_physical_center_unwrapped_az_deg) - ...
            physical) <= 1e-12 && ...
        abs(double(model.requested_center_az_deg) - ...
            double(locked.stage5_requested_center_az_deg)) <= 1e-12 && ...
        abs(double(model.rotation_delta_deg) - delta) <= 1e-12 && ...
        strcmp(char(string(model.stage5_rotation_class_hash)), ...
            current_class_hash) && ...
        strcmp(char(string(model.stage5_actual_center_hash)), actual_hash);
end
if ~strcmp(current_class_hash, reference_class_hash) || ...
        ~strcmp(current_class_hash, ...
        char(string(locked.stage5_rotation_class_hash))) || ...
        ~strcmp(actual_hash, char(string(locked.stage5_actual_center_hash))) || ...
        ~model_match
    error('build_stage8_known_k_local_context:Stage5RotationAdmission', ...
        'BLOCKED_STAGE5_ROTATION_CONTRACT.');
end
status = 'MULTICENTER_STAGE5_ROTATION_CLASS_ACCEPTED';
end

function prefix = audit_public_prefix_local(available)
prefix = 'K1';
if ~available
    return;
end
stage = upper(char(string(stage8_k2_tcc_audit_state( ...
    'GET_QUERY_STAGE'))));
if startsWith(stage, 'K2')
    prefix = 'K2';
end
end

function token = audit_stage_start_local(available, stage_id)
token = [];
if available && stage8_k2_tcc_audit_state('STAGE_ENABLED')
    token = stage8_k2_tcc_audit_state('STAGE_START', stage_id);
end
end

function audit_stage_stop_local(available, stage_id, token)
if available && ~isempty(token)
    stage8_k2_tcc_audit_state('STAGE_STOP', stage_id, token);
end
end

function audit_record_initialization_local(available, prefix, full_data, init)
if ~(available && stage8_k2_tcc_audit_state('QUERY_ENABLED'))
    return;
end
event = struct('role', [prefix, '_CONTEXT'], ...
    'full_data', full_data, 'initialization', init);
stage8_k2_tcc_audit_state('RECORD_INITIALIZATION_SNAPSHOT', event);
end
