function geometry = compute_stage8_projected_separation_geometry( ...
    targets_deg, model)
%COMPUTE_STAGE8_PROJECTED_SEPARATION_GEOMETRY Offline Stage6 q geometry.

if ~(isnumeric(targets_deg) && isequal(size(targets_deg), [2, 2]) && ...
        all(isfinite(targets_deg(:))))
    error('compute_stage8_projected_separation_geometry:Targets', ...
        'targets_deg must be two finite angular endpoints.');
end
center = mean(targets_deg, 1);
[g, derivatives] = build_full_sequential_local_manifold(center, model, ...
    struct('rank_multiplier', 1));
metric = compute_projected_jacobian_metric(g, ...
    [derivatives.azimuth, derivatives.elevation], ...
    struct('rank_multiplier', 1));
d_rad = deg2rad(targets_deg(2, :) - targets_deg(1, :)).';
geometry = struct('center_deg', center, 'separation_deg', ...
    targets_deg(2, :) - targets_deg(1, :), 'separation_rad', d_rad, ...
    'q', real(d_rad.' * metric.T * d_rad), ...
    'metric_T', metric.T, 'metric_condition', metric.condition_T, ...
    'metric_rank', metric.rank_T, 'truth_used_in_fit_flag', false);
end
