function outcome = fit_stage8_core_plus(context, K)
%FIT_STAGE8_CORE_PLUS Add only grouped K2 center-difference refinement.

if K == 1
    outcome = fit_stage8_core_lite(context, K);
    return;
end
fixed_grid = fixed_grid_candidate_local(context);
start1 = context_start_local('B2_K2_GROUPED_Q1_KQ2', ...
    context.initialization.grouped_q1_kq2_angles_deg, ...
    context.initialization.grouped_q1_kq2_status, context.local_domain);
start2 = context_start_local('B2_K2_GROUPED_Q2_KQ1_PLUS_KQ1', ...
    context.initialization.grouped_q2_kq1_plus_kq1_angles_deg, ...
    context.initialization.grouped_q2_kq1_plus_kq1_status, ...
    context.local_domain);
continuous = continuous_k2_candidate_local(context, [start1; start2]);
[selected, selection] = select_stage8_safe_known_k_candidate( ...
    fixed_grid, continuous);
outcome = struct('fixed_grid', fixed_grid, 'continuous', continuous, ...
    'selected', selected, 'selected_source', selection.selected_source, ...
    'continuous_upgrade_flag', selection.continuous_upgrade_flag, ...
    'fallback_flag', selection.fallback_flag, 'selection', selection);
end

function candidate = fixed_grid_candidate_local(context)
[helper, ~] = fit_local_model_k(context.full_data, 1, ...
    context.local_domain, context.model, context.initialization, struct());
init2 = context.initialization;
init2.k1_fit = helper;
[fit, ~] = fit_local_model_k(context.full_data, 2, ...
    context.local_domain, context.model, init2, struct());
[valid, validity] = validate_stage8_fit_for_lrt(fit, 2, struct());
fit.selected_initial_angles_deg = selected_initial_local(fit);
fit.solver_status = 'REGISTERED_STAGE8_FIXED_GRID_BASELINE';
fit.monotonicity_violation_count = 0;
candidate = struct('method_id', 'B0_FIXED_GRID_KNOWN_K', 'fit', fit, ...
    'fit_valid', logical(valid), 'fit_status', char(string(validity.status)));
end

function candidate = continuous_k2_candidate_local(context, starts)
[fit, ~] = fit_k2_local(context.full_data, starts, ...
    context.local_domain, context.model);
valid = logical(fit.estimate_returned_flag && fit.converged_flag && ...
    fit.effective_rank >= 2 && isfinite(fit.score) && ...
    isfinite(fit.rss) && fit.rss >= 0 && isfinite(fit.sigma2_hat) && ...
    isfinite(fit.loglik_concentrated) && ...
    fit.monotonicity_violation_count == 0);
candidate = struct('method_id', 'B2_GROUPED_CONTINUOUS_KNOWN_K', ...
    'fit', fit, 'fit_valid', valid, 'fit_status', fit.fit_status);
end

function [fit, debug] = fit_k2_local(data, starts, domain, model)
clock = tic;
results = repmat(empty_start_local(), numel(starts), 1);
for index = 1:numel(starts)
    results(index).initialization_id = ...
        char(string(starts(index).initialization_id));
    results(index).initial_angles_deg = starts(index).angles_deg;
    results(index).initialization_available_flag = ...
        logical(starts(index).available_flag);
    results(index).initialization_status = ...
        char(string(starts(index).initialization_status));
    if ~results(index).initialization_available_flag || ...
            ~isequal(size(results(index).initial_angles_deg), [2, 2]) || ...
            any(~isfinite(results(index).initial_angles_deg(:)))
        continue;
    end
    [estimate, history, solver_debug] = refine_stage8_k2_center_difference( ...
        data, results(index).initial_angles_deg, domain, model, struct());
    solver_status = char(string(estimate.status));
    solver_usable = logical(estimate.usable_flag);
    results(index).angles_hat_deg = estimate.angles_hat_deg;
    results(index).initial_angles_deg = estimate.initial_angles_deg;
    results(index).solver_status = solver_status;
    results(index).initial_score = estimate.initial_score;
    results(index).final_score = estimate.final_score;
    results(index).score_call_count = estimate.score_call_count;
    results(index).svd_call_count = estimate.svd_call_count;
    results(index).monotonicity_violation_count = ...
        estimate.monotonicity_violation_count;
    results(index).solver_contract_hash = estimate.solver_contract_hash;
    results(index).history = history;
    results(index).solver_debug = solver_debug;
    if ~(solver_usable && estimate.estimate_returned_flag && ...
            estimate.monotonicity_violation_count == 0)
        results(index).fit_status = 'SOLVER_NOT_OPERATIONAL';
        continue;
    end
    [results(index), valid] = rebuild_fit_local(results(index), data, model);
    results(index).valid_for_selection_flag = valid;
end

valid_indices = find([results.valid_for_selection_flag]);
fit = empty_fit_local(data, domain, model);
fit.all_start_results = results;
fit.num_start = numel(starts);
fit.valid_start_count = numel(valid_indices);
fit.num_score_eval = sum([results.score_call_count]);
fit.num_svd = sum([results.svd_call_count]);
fit.monotonicity_violation_count = ...
    sum([results.monotonicity_violation_count]);
fit.runtime = toc(clock);
if isempty(valid_indices)
    debug = struct('selected_start_index', 0, ...
        'selected_start_id', '', 'valid_start_count', 0, ...
        'selection_rule', ...
        'MAXIMUM_CONCENTRATED_LOG_LIKELIHOOD_AMONG_VALID_STARTS');
    return;
end
loglik = [results(valid_indices).loglik_concentrated];
maximum = max(loglik);
tolerance = 64 * eps(max(1, abs(maximum)));
selected_index = valid_indices(find(loglik >= maximum - tolerance, ...
    1, 'first'));
selected = results(selected_index);
fit = copy_result_local(selected, fit);
fit.fit_status = 'KNOWN_K_FIT_VALID';
fit.estimate_returned_flag = true;
fit.converged_flag = true;
fit.initialization_id = selected.initialization_id;
fit.selected_initial_angles_deg = selected.initial_angles_deg;
fit.runtime = toc(clock);
debug = struct('selected_start_index', selected_index, ...
    'selected_start_id', selected.initialization_id, ...
    'valid_start_count', numel(valid_indices), ...
    'selection_tolerance', tolerance, 'selection_rule', ...
    'MAXIMUM_CONCENTRATED_LOG_LIKELIHOOD_AMONG_VALID_STARTS');
end

function [result, valid] = rebuild_fit_local(result, data, model)
[G, ~, manifold_info] = build_full_sequential_local_manifold( ...
    result.angles_hat_deg, model, struct('rank_multiplier', 1));
[score, rss, sigma2, loglik, rank_now] = concentrated_dml_rss( ...
    data.Zseq_white, G, struct('requested_rank', 2, ...
    'rank_multiplier', 1, 'compute_projector_checks', false));
[S, solve_info] = solve_fitted_source_coefficients( ...
    G, data.Zseq_white, struct('rank_multiplier', 1));
result.score_call_count = result.score_call_count + 1;
result.svd_call_count = result.svd_call_count + ...
    manifold_info.num_svd + 1 + solve_info.num_svd;
result.G_hat = G;
result.S_hat = S;
result.score = score;
result.rss = rss;
result.sigma2_hat = sigma2;
result.loglik_concentrated = loglik;
result.effective_rank = min(rank_now, solve_info.effective_rank);
valid = result.effective_rank >= 2 && isfinite(score) && ...
    isfinite(rss) && rss >= 0 && isfinite(sigma2) && sigma2 >= 0 && ...
    isfinite(loglik) && all(isfinite(S(:)));
if valid, result.fit_status = 'KNOWN_K_FIT_VALID'; ...
else, result.fit_status = 'FIT_NUMERIC_INVALID'; end
end

function fit = empty_fit_local(data, domain, model)
r_C = size(data.Zseq_white, 1);
L = size(data.Zseq_white, 2);
fit = struct('K', 2, 'angles_hat_deg', NaN(2, 2), ...
    'G_hat', complex(NaN(r_C, 2)), 'S_hat', complex(NaN(2, L)), ...
    'score', NaN, 'rss', NaN, 'sigma2_hat', NaN, ...
    'loglik_concentrated', NaN, 'effective_rank', 0, ...
    'fit_status', 'NO_VALID_START', 'solver_status', 'NO_VALID_START', ...
    'estimate_returned_flag', false, 'converged_flag', false, ...
    'initialization_id', '', 'selected_initial_angles_deg', NaN(2, 2), ...
    'all_start_results', struct([]), 'num_start', 0, ...
    'valid_start_count', 0, 'num_score_eval', 0, 'num_svd', 0, ...
    'runtime', 0, 'monotonicity_violation_count', 0, ...
    'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'local_domain_hash', domain.domain_hash, 'solver_contract_hash', '', ...
    'observation_hash', stage8_core_v2_2_stable_hash(data.Zseq_white), ...
    'effective_whitening_dimension', r_C, 'snapshot_count', L, ...
    'n_complex_observations', r_C * L, 'phase_factor', 1);
end

function result = empty_start_local()
result = struct('initialization_id', '', ...
    'initialization_available_flag', false, ...
    'initialization_status', 'INITIALIZATION_NOT_BUILT', ...
    'initial_angles_deg', NaN(2, 2), 'angles_hat_deg', NaN(2, 2), ...
    'score', NaN, 'rss', NaN, 'sigma2_hat', NaN, ...
    'loglik_concentrated', -Inf, 'effective_rank', 0, ...
    'G_hat', complex(NaN(0, 2)), 'S_hat', complex(NaN(2, 0)), ...
    'fit_status', 'INITIALIZATION_FAILED', 'solver_status', 'NOT_RUN', ...
    'initial_score', NaN, 'final_score', NaN, ...
    'valid_for_selection_flag', false, 'score_call_count', 0, ...
    'svd_call_count', 0, 'monotonicity_violation_count', 0, ...
    'solver_contract_hash', '', 'history', table(), ...
    'solver_debug', struct());
end

function output = copy_result_local(result, base)
output = base;
fields = {'angles_hat_deg','G_hat','S_hat','score','rss','sigma2_hat', ...
    'loglik_concentrated','effective_rank','solver_status', ...
    'solver_contract_hash'};
for index = 1:numel(fields)
    output.(fields{index}) = result.(fields{index});
end
end

function start = context_start_local(id, angles, status, domain)
available = isnumeric(angles) && isequal(size(angles), [2, 2]) && ...
    all(isfinite(angles(:)));
if available
    bounds = domain.domain_bounds_deg;
    available = all(angles(:, 1) >= bounds(1) & ...
        angles(:, 1) <= bounds(2) & angles(:, 2) >= bounds(3) & ...
        angles(:, 2) <= bounds(4));
end
start = struct('initialization_id', id, 'angles_deg', angles, ...
    'available_flag', logical(available), ...
    'initialization_status', char(string(status)));
end

function initial = selected_initial_local(fit)
initial = NaN(2, 2);
if ~isfield(fit, 'all_start_results') || isempty(fit.all_start_results)
    return;
end
ids = string({fit.all_start_results.initialization_id});
index = find(ids == string(fit.initialization_id), 1);
if ~isempty(index)
    initial = fit.all_start_results(index).initial_angles_deg;
end
end
