function [selected, selection] = select_stage8_safe_known_k_candidate( ...
    fixed_grid, continuous)
%SELECT_STAGE8_SAFE_KNOWN_K_CANDIDATE Keep a valid B0 unless ML improves it.

validate_candidate_local(fixed_grid, 'fixed_grid');
validate_candidate_local(continuous, 'continuous');
if ~fixed_grid.fit_valid || ~isfinite(fixed_grid.fit.loglik_concentrated)
    error('select_stage8_safe_known_k_candidate:FixedGrid', ...
        'The fixed-grid known-K candidate must be valid.');
end
continuous_valid = continuous.fit_valid && ...
    isfinite(continuous.fit.loglik_concentrated);
upgrade = continuous_valid && ...
    continuous.fit.loglik_concentrated >= fixed_grid.fit.loglik_concentrated;
if upgrade
    selected = continuous;
    source = 'CONTINUOUS_UPGRADE';
else
    selected = fixed_grid;
    source = 'FIXED_GRID_FALLBACK';
end
selection = struct('selected_source', source, ...
    'continuous_upgrade_flag', logical(upgrade), ...
    'fallback_flag', logical(~upgrade), ...
    'selection_truth_used_flag', false, ...
    'selection_rule', ...
    'VALID_CONTINUOUS_WITH_LOG_LIKELIHOOD_NOT_BELOW_B0_ELSE_B0', ...
    'B0_candidate_loglik', fixed_grid.fit.loglik_concentrated, ...
    'continuous_candidate_loglik', continuous.fit.loglik_concentrated);
end

function validate_candidate_local(candidate, name)
required = {'fit','fit_valid','fit_status','method_id'};
if ~(isstruct(candidate) && isscalar(candidate) && ...
        all(isfield(candidate, required)) && isstruct(candidate.fit) && ...
        isfield(candidate.fit, 'loglik_concentrated'))
    error('select_stage8_safe_known_k_candidate:Candidate', ...
        '%s is not a complete candidate.', name);
end
end
