function opts = validate_stage8_known_k_local_cell_input( ...
    Y_element, model, local_domain, stage5_locked, noise_model, K, opts)
%VALIDATE_STAGE8_KNOWN_K_LOCAL_CELL_INPUT Enforce the public known-K boundary.

if nargin < 7 || isempty(opts)
    opts = struct();
end
if ~(isa(Y_element, 'double') && ismatrix(Y_element) && ...
        ~isempty(Y_element) && all(isfinite(Y_element(:))))
    error('validate_stage8_known_k_local_cell_input:YElement', ...
        'Y_element must be a finite M-by-L complex double matrix.');
end
model_fields = {'W_I','T_I','array_meta','array_configuration', ...
    'fixed_measurement_hash','phase_factor','noise_factorization'};
if ~(isstruct(model) && isscalar(model) && ...
        all(isfield(model, model_fields)) && model.phase_factor == 1 && ...
        size(Y_element, 1) == size(model.W_I, 1))
    error('validate_stage8_known_k_local_cell_input:Model', ...
        'model must be the fixed factor-one sequential measurement model.');
end
domain_fields = {'az_grid_deg','el_grid_deg','candidate_points_deg', ...
    'domain_bounds_deg','domain_hash'};
if ~(isstruct(local_domain) && isscalar(local_domain) && ...
        all(isfield(local_domain, domain_fields)) && ...
        isequal(size(local_domain.domain_bounds_deg), [1, 4]) && ...
        all(isfinite(local_domain.domain_bounds_deg)))
    error('validate_stage8_known_k_local_cell_input:LocalDomain', ...
        'local_domain must be one fixed, finite local angular domain.');
end
locked_fields = {'az_beam_deg','el_beam_deg','configuration_hash'};
if ~(isstruct(stage5_locked) && isscalar(stage5_locked) && ...
        all(isfield(stage5_locked, locked_fields)))
    error('validate_stage8_known_k_local_cell_input:Stage5Locked', ...
        'stage5_locked must be the frozen sequential-DBF configuration.');
end
noise_fields = {'R_el','R_az'};
if ~(isstruct(noise_model) && isscalar(noise_model) && ...
        all(isfield(noise_model, noise_fields)))
    error('validate_stage8_known_k_local_cell_input:NoiseModel', ...
        'noise_model must expose the fixed element covariance factors.');
end
if ~(isscalar(K) && isa(K, 'double') && isfinite(K) && ...
        K == fix(K) && ismember(K, [1, 2]))
    error('validate_stage8_known_k_local_cell_input:K', ...
        'K must be the scalar externally supplied integer 1 or 2.');
end
if ~(isstruct(opts) && isscalar(opts))
    error('validate_stage8_known_k_local_cell_input:Options', ...
        'opts must be a scalar struct.');
end
allowed = {'mode','rank_multiplier','return_diagnostics', ...
    'scenario_contract','K_conditioning', ...
    'fixed_registered_manifold_provider', ...
    'fixed_registered_center_adapter','fixed_manifold_mode'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('validate_stage8_known_k_local_cell_input:ForbiddenOption', ...
        'Unsupported or forbidden option: %s.', unknown{1});
end
defaults = struct('mode', 'CORE_LITE', 'rank_multiplier', 1, ...
    'return_diagnostics', true, ...
    'scenario_contract', 'SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL', ...
    'K_conditioning', 'EXTERNALLY_GIVEN_NOT_ESTIMATED', ...
    'fixed_registered_manifold_provider', [], ...
    'fixed_registered_center_adapter', [], ...
    'fixed_manifold_mode', 'LEGACY_FULL');
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(opts, names{index})
        opts.(names{index}) = defaults.(names{index});
    end
end
opts.mode = upper(char(string(opts.mode)));
if ~ismember(opts.mode, {'CORE_LITE','CORE_PLUS'})
    error('validate_stage8_known_k_local_cell_input:Mode', ...
        'opts.mode must be CORE_LITE or CORE_PLUS.');
end
opts.fixed_manifold_mode = upper(char(string(opts.fixed_manifold_mode)));
if ~ismember(opts.fixed_manifold_mode, ...
        {'LEGACY_FULL','DIRECT_G_ONLY','REGISTERED_CACHE'})
    error('validate_stage8_known_k_local_cell_input:FixedManifoldMode', ...
        ['fixed_manifold_mode must be LEGACY_FULL, DIRECT_G_ONLY, ', ...
        'or REGISTERED_CACHE.']);
end
if ~isempty(opts.fixed_registered_manifold_provider) && ...
        ~(isstruct(opts.fixed_registered_manifold_provider) && ...
        isscalar(opts.fixed_registered_manifold_provider))
    error('validate_stage8_known_k_local_cell_input:FixedProvider', ...
        'fixed_registered_manifold_provider must be a scalar struct.');
end
if ~isempty(opts.fixed_registered_center_adapter) && ...
        ~(isstruct(opts.fixed_registered_center_adapter) && ...
        isscalar(opts.fixed_registered_center_adapter))
    error('validate_stage8_known_k_local_cell_input:CenterAdapter', ...
        'fixed_registered_center_adapter must be a scalar struct.');
end
if strcmp(opts.fixed_manifold_mode, 'REGISTERED_CACHE') && ...
        isempty(opts.fixed_registered_manifold_provider)
    error('validate_stage8_known_k_local_cell_input:FixedProviderRequired', ...
        'REGISTERED_CACHE requires a fixed registered provider.');
end
if strcmp(opts.fixed_manifold_mode, 'REGISTERED_CACHE') && ...
        ~isempty(opts.fixed_registered_manifold_provider) && ...
        isfield(opts.fixed_registered_manifold_provider, 'schema_version') && ...
        strcmp(char(string(opts.fixed_registered_manifold_provider.schema_version)), ...
        'STAGE8_K2_MULTICENTER_SHARED_PROVIDER_V1') && ...
        isempty(opts.fixed_registered_center_adapter)
    error('validate_stage8_known_k_local_cell_input:CenterAdapterRequired', ...
        'The multicenter shared provider requires a certified center adapter.');
end
if ~strcmp(opts.fixed_manifold_mode, 'REGISTERED_CACHE') && ...
        ~isempty(opts.fixed_registered_center_adapter)
    error('validate_stage8_known_k_local_cell_input:CenterAdapterMode', ...
        'A fixed registered center adapter is only valid for REGISTERED_CACHE.');
end
if ~(isscalar(opts.rank_multiplier) && opts.rank_multiplier == 1)
    error('validate_stage8_known_k_local_cell_input:RankMultiplier', ...
        'rank_multiplier is frozen at 1.');
end
if ~(isscalar(opts.return_diagnostics) && ...
        (islogical(opts.return_diagnostics) || isnumeric(opts.return_diagnostics)))
    error('validate_stage8_known_k_local_cell_input:Diagnostics', ...
        'return_diagnostics must be scalar logical.');
end
opts.return_diagnostics = logical(opts.return_diagnostics);
if ~strcmp(char(string(opts.scenario_contract)), ...
        'SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL') || ...
        ~strcmp(char(string(opts.K_conditioning)), ...
        'EXTERNALLY_GIVEN_NOT_ESTIMATED')
    error('validate_stage8_known_k_local_cell_input:ScenarioContract', ...
        'The single-CPI and externally-given-K contracts are fixed.');
end
if isfield(model.noise_factorization, 'factorization_hash') && ...
        isfield(noise_model, 'factorization_hash') && ...
        ~strcmp(char(string(model.noise_factorization.factorization_hash)), ...
        char(string(noise_model.factorization_hash)))
    error('validate_stage8_known_k_local_cell_input:NoiseIdentity', ...
        'noise_model does not match model.noise_factorization.');
end
if ~isequaln(model.noise_factorization.R_el, noise_model.R_el) || ...
        ~isequaln(model.noise_factorization.R_az, noise_model.R_az)
    error('validate_stage8_known_k_local_cell_input:NoiseFactors', ...
        'noise_model must exactly match the fixed model factors.');
end
end
