function result = test_stage8_k2_mc_all_192_geometry(~, outputs)
%TEST_STAGE8_K2_MC_ALL_192_GEOMETRY Check the exhaustive static checkpoint.
geometry = outputs.static.geometry;
pass = height(geometry) == 192 && all(geometry.pass) && ...
    max(geometry.geometry_relative_error) <= 1e-13 && ...
    max(geometry.steering_relative_error) <= 1e-13;
assert(pass, 'test_stage8_k2_mc_all_192_geometry:Failed');
result = struct('pass',pass,'count',height(geometry), ...
    'max_geometry_error',max(geometry.geometry_relative_error), ...
    'max_steering_error',max(geometry.steering_relative_error));
end
