function result = test_stage8_k2_mc_whitener_basis_invariance(~, outputs)
%TEST_STAGE8_K2_MC_WHITENER_BASIS_INVARIANCE Check basis-invariant gates.

value = outputs.whitener;
pass = value.case_count == 16 && value.pass_count == 16 && ...
    strcmp(value.status, ...
    'STAGE8_K2_MC_WHITENER_BASIS_INVARIANCE_PASS') && ...
    value.max_raw_whitening_backward_error <= ...
        value.thresholds.whitening_backward_error && ...
    value.max_reference_whitening_backward_error <= ...
        value.thresholds.whitening_backward_error && ...
    value.max_Q_unitarity_error <= value.thresholds.Q_unitarity_error && ...
    value.thresholds.Q_unitarity_error <= 10 * ...
        value.thresholds.Q_unitarity_default_error && ...
    value.max_alignment_error <= value.thresholds.alignment_error && ...
    ~value.forward_default_threshold_met && ...
    value.max_covariance_condition_number > 1e9 && ...
    value.min_relative_eigenvalue_gap > 0 && ...
    strcmp(value.forward_residual_role, ...
        'DIAGNOSTIC_ONLY_ILL_CONDITIONED_FORWARD_EVALUATION');
assert(pass, ...
    'test_stage8_k2_mc_whitener_basis_invariance:Failed');
result = struct('pass',pass, ...
    'max_raw_whitening_residual',value.max_raw_whitening_residual, ...
    'max_reference_whitening_residual', ...
        value.max_reference_whitening_residual, ...
    'max_raw_whitening_backward_error', ...
        value.max_raw_whitening_backward_error, ...
    'max_reference_whitening_backward_error', ...
        value.max_reference_whitening_backward_error, ...
    'max_Q_unitarity_error',value.max_Q_unitarity_error, ...
    'max_alignment_error',value.max_alignment_error, ...
    'max_covariance_condition_number', ...
        value.max_covariance_condition_number);
end
