function result = test_stage8_k2_mc_manifest_provenance_fields(~, outputs)
%TEST_STAGE8_K2_MC_MANIFEST_PROVENANCE_FIELDS Check manifest V2 provenance.

manifest = outputs.manifest;
[status,head] = system(['git -C "',outputs.repo_dir, ...
    '" rev-parse HEAD']);
if status ~= 0
    error('test_stage8_k2_mc_manifest_provenance_fields:Git', ...
        'Unable to resolve current HEAD.');
end
head = strtrim(head);
pass = strcmp(manifest.schema_version,'STAGE8_K2_MC_MANIFEST_V2') && ...
    ~isfield(manifest,'head_commit') && ...
    strcmp(manifest.runtime_code_commit, ...
    'ad6a015ca53185552ebda1b95e645be057559c99') && ...
    strcmp(manifest.evidence_generator_commit,head) && ...
    strcmp(manifest.evidence_reuse_status, ...
    'REUSED_EXISTING_GATE_A_B_C_D_OUTPUTS_NO_LARGE_RERUN');
assert(pass, ...
    'test_stage8_k2_mc_manifest_provenance_fields:Failed');
result = struct('pass',pass,'evidence_generator_commit',head, ...
    'head_self_reference_removed',~isfield(manifest,'head_commit'));
end
