function result = test_stage8_k2_mc_manifest_provenance_fields(~, outputs)
%TEST_STAGE8_K2_MC_MANIFEST_PROVENANCE_FIELDS Check manifest V2 provenance.

manifest = outputs.manifest;
[status,current_head] = system(['git -C "',outputs.repo_dir, ...
    '" rev-parse HEAD']);
if status ~= 0
    error('test_stage8_k2_mc_manifest_provenance_fields:Git', ...
        'Unable to resolve current HEAD.');
end
current_head = strtrim(current_head);
runtime_code_commit = manifest.runtime_code_commit;
evidence_generator_commit = manifest.evidence_generator_commit;
runtime_sha_valid = valid_sha_local(runtime_code_commit);
evidence_generator_sha_valid = valid_sha_local( ...
    evidence_generator_commit);
current_head_valid = valid_sha_local(current_head);
if ~current_head_valid
    error('test_stage8_k2_mc_manifest_provenance_fields:GitHead', ...
        'Current HEAD is not a valid lowercase 40-character Git SHA.');
end
runtime_is_ancestor = false;
evidence_generator_is_ancestor = false;
if runtime_sha_valid
    runtime_is_ancestor = git_is_ancestor_local( ...
        outputs.repo_dir,runtime_code_commit,current_head);
end
if evidence_generator_sha_valid
    evidence_generator_is_ancestor = git_is_ancestor_local( ...
        outputs.repo_dir,evidence_generator_commit,current_head);
end
pass = strcmp(manifest.schema_version,'STAGE8_K2_MC_MANIFEST_V2') && ...
    ~isfield(manifest,'head_commit') && ...
    runtime_sha_valid && strcmp(runtime_code_commit, ...
    'ad6a015ca53185552ebda1b95e645be057559c99') && ...
    evidence_generator_sha_valid && strcmp(evidence_generator_commit, ...
    'ba02c67c117d0e6981f7a0c8fedabe57641a11a3') && ...
    strcmp(manifest.evidence_reuse_status, ...
    'REUSED_EXISTING_GATE_A_B_C_D_OUTPUTS_NO_LARGE_RERUN') && ...
    runtime_is_ancestor && evidence_generator_is_ancestor;
assert(pass, ...
    'test_stage8_k2_mc_manifest_provenance_fields:Failed');
result = struct('pass',pass,'current_head',current_head, ...
    'runtime_code_commit',runtime_code_commit, ...
    'runtime_code_is_ancestor',runtime_is_ancestor, ...
    'evidence_generator_commit',evidence_generator_commit, ...
    'evidence_generator_is_ancestor',evidence_generator_is_ancestor, ...
    'head_self_reference_removed',~isfield(manifest,'head_commit'));
end

function value = valid_sha_local(commit)
value = ischar(commit) && isrow(commit) && ...
    ~isempty(regexp(commit,'^[0-9a-f]{40}$','once'));
end

function value = git_is_ancestor_local(repo_dir,commit,current_head)
[status,message] = system(sprintf( ...
    'git -C "%s" merge-base --is-ancestor %s %s', ...
    repo_dir,commit,current_head));
if status == 0
    value = true;
elseif status == 1
    value = false;
else
    error('test_stage8_k2_mc_manifest_provenance_fields:GitAncestor', ...
        'Git ancestor query failed (%d): %s',status,strtrim(message));
end
end
