function result = test_stage8_k2_mc_lifecycle_protocol(~, outputs)
%TEST_STAGE8_K2_MC_LIFECYCLE_PROTOCOL Check the 10-repeat lifecycle gate.
o = outputs.lifecycle;
pass = o.repeat_count_per_identity == 10 && o.positive && ...
    height(o.summary) == 2 && all(o.summary.pass) && ...
    all(o.summary.build_reduction > 0) && ...
    all(o.summary.storage_reduction > 0);
assert(pass, 'test_stage8_k2_mc_lifecycle_protocol:Failed');
result = struct('pass',pass,'repeat_count',o.repeat_count_per_identity, ...
    'build_reduction',o.summary.build_reduction, ...
    'storage_reduction',o.summary.storage_reduction);
end
