function result = test_stage8_k2_mc_static_metric_roles(~, outputs)
%TEST_STAGE8_K2_MC_STATIC_METRIC_ROLES Check explicit gate/diagnostic roles.

metrics = outputs.static_metrics;
required_columns = ["metric","value","metric_role", ...
    "gate_threshold","gate_status"];
has_columns = all(ismember(required_columns, ...
    string(metrics.Properties.VariableNames)));
raw_T = metrics(metrics.metric == "MAX_RAW_REBUILT_T_ERROR",:);
canonical_T = metrics( ...
    metrics.metric == "MAX_CANONICAL_ONLINE_T_ERROR",:);
forward_metrics = metrics(ismember(metrics.metric,[ ...
    "MAX_RAW_WHITENING_RESIDUAL", ...
    "MAX_REFERENCE_WHITENING_RESIDUAL"]),:);
gated_basis_metrics = metrics(ismember(metrics.metric,[ ...
    "MAX_RAW_WHITENING_BACKWARD_ERROR", ...
    "MAX_REFERENCE_WHITENING_BACKWARD_ERROR", ...
    "MAX_WHITENER_Q_UNITARITY_ERROR", ...
    "MAX_WHITENER_ALIGNMENT_ERROR"]),:);
pass = has_columns && height(raw_T) == 1 && ...
    raw_T.metric_role == "DIAGNOSTIC_ONLY_EIGENBASIS_DEPENDENT" && ...
    isnan(raw_T.gate_threshold) && ...
    raw_T.gate_status == "DIAGNOSTIC_ONLY" && ...
    height(canonical_T) == 1 && canonical_T.value == 0 && ...
    canonical_T.gate_status == "PASS" && ...
    height(forward_metrics) == 2 && ...
    all(forward_metrics.gate_status == "DIAGNOSTIC_ONLY") && ...
    all(isnan(forward_metrics.gate_threshold)) && ...
    height(gated_basis_metrics) == 4 && ...
    all(gated_basis_metrics.gate_status == "PASS");
assert(pass, 'test_stage8_k2_mc_static_metric_roles:Failed');
result = struct('pass',pass, ...
    'raw_T_role',char(raw_T.metric_role), ...
    'raw_T_value',raw_T.value, ...
    'gated_basis_metric_count',height(gated_basis_metrics));
end
