function result = test_stage8_k2_mc_actual_center_not_requested_center(fixture, ~)
%TEST_STAGE8_K2_MC_ACTUAL_CENTER_NOT_REQUESTED_CENTER Check the frozen reference.
delta = stage8_k2_mc_periodic_difference( ...
    fixture.spec.reference_requested_center_az_deg, ...
    fixture.spec.reference_physical_center_az_deg);
pass = abs(delta) > 1e-12 && fixture.spec.reference_center_column == 5;
assert(pass, 'test_stage8_k2_mc_actual_center_not_requested_center:Failed');
result = struct('pass',pass,'requested_center_az_deg', ...
    fixture.spec.reference_requested_center_az_deg, ...
    'physical_center_az_deg',fixture.spec.reference_physical_center_az_deg, ...
    'center_column',fixture.spec.reference_center_column);
end
