function result = test_stage8_k2_mc_runtime_sentinel_protocol(~, outputs)
%TEST_STAGE8_K2_MC_RUNTIME_SENTINEL_PROTOCOL Check the frozen 48-pair gate.
o = outputs.runtime;
s = outputs.runtime_schedule;
groups = findgroups(s.case_index);
ab = splitapply(@(x)nnz(strcmp(x,'AB')),cellstr(s.pair_order),groups);
ba = splitapply(@(x)nnz(strcmp(x,'BA')),cellstr(s.pair_order),groups);
overall = o.summary(o.summary.row_type == "OVERALL",:);
pass = o.case_count == 12 && o.pair_count == 48 && ...
    o.root_call_count == 96 && o.projection_match_count == 48 && ...
    o.checksum_match_count == 48 && all(ab == 2) && all(ba == 2) && ...
    overall.paired_point_saving_sec > 0 && ...
    overall.ab_point_saving_sec > 0 && overall.ba_point_saving_sec > 0;
assert(pass, 'test_stage8_k2_mc_runtime_sentinel_protocol:Failed');
result = struct('pass',pass,'case_count',o.case_count, ...
    'pair_count',o.pair_count,'point_saving_sec', ...
    overall.paired_point_saving_sec);
end
