function result = test_stage8_k2_mc_evidence_reference_dynamic(fixture, ~)
%TEST_STAGE8_K2_MC_EVIDENCE_REFERENCE_DYNAMIC Check dynamic reference metadata.

cfg = sim_cfg();
spec = fixture.spec;
delta = stage8_k2_mc_periodic_difference( ...
    spec.reference_requested_center_az_deg, ...
    spec.reference_physical_center_az_deg);
pass = abs(cfg.beam.azSectorCenter - 8.0) <= 1e-12 && ...
    abs(spec.reference_requested_center_az_deg - ...
    cfg.beam.azSectorCenter) <= 1e-12 && ...
    abs(spec.reference_physical_center_az_deg - 7.5) <= 1e-12 && ...
    spec.reference_center_column == 5 && abs(delta) > 1e-12;
assert(pass, ...
    'test_stage8_k2_mc_evidence_reference_dynamic:Failed');
result = struct('pass',pass, ...
    'requested_center_az_deg',spec.reference_requested_center_az_deg, ...
    'physical_center_az_deg',spec.reference_physical_center_az_deg, ...
    'center_column',spec.reference_center_column);
end
