function result = test_stage8_k2_mc_compact_semantics(~, outputs)
%TEST_STAGE8_K2_MC_COMPACT_SEMANTICS Check the 24-case semantic gate.
o = outputs.semantics;
pass = strcmp(o.status,'STAGE8_K2_MULTICENTER_SEMANTIC_PASS_24_OF_24') && ...
    o.semantic_pass_count == 24 && o.control_pass_count == 6 && ...
    o.covariance_pass_count == 8 && o.truth_leakage_count == 0;
assert(pass, 'test_stage8_k2_mc_compact_semantics:Failed');
result = struct('pass',pass,'semantic_pass_count',o.semantic_pass_count, ...
    'control_pass_count',o.control_pass_count, ...
    'covariance_pass_count',o.covariance_pass_count);
end
