clc
clear
close all

script_dir = fileparts(mfilename('fullpath'));
step_dir = script_dir;
steps_dir = fileparts(step_dir);
project_dir = fileparts(steps_dir);
common_dir = fullfile(step_dir, 'common');
tests_dir = fullfile(step_dir, 'tests');
result_dir = fullfile(step_dir, 'results');

addpath(common_dir);
addpath(tests_dir);
addpath(fullfile(project_dir, 'core', 'config'));
if exist(result_dir, 'dir') ~= 7
    mkdir(result_dir);
end

cfg = sim_cfg();
if cfg.beam.spatialPhaseFactor ~= 1
    error('run_step12_2:ActivePhaseFactor', ...
        'Step12.2 requires the active receive spatial phase factor to be 1.');
end

validation_tic = tic;
[rank_table_base, rank_context] = test_stable_rank_and_whitener();
[trial_table, trial_context] = test_svd_dml_matrix();
[concentrated_table, concentrated_context] = test_concentrated_dml_rss();
[comparison_table, comparison_context] = test_old_vs_new_score_comparison();
source_rule_table = test_step12_2_has_no_fixed_ridge(step_dir);
rank_table = append_dml_rank_cases_local(rank_table_base, trial_table);
validation_runtime_sec = toc(validation_tic);

trial_csv = fullfile(result_dir, 'stable_dml_trial.csv');
keypoints_csv = fullfile(result_dir, 'stable_dml_keypoints.csv');
rank_csv = fullfile(result_dir, 'rank_deficiency_cases.csv');
comparison_csv = fullfile(result_dir, 'old_vs_new_score_comparison.csv');
report_md = fullfile(result_dir, 'stable_dml_report.md');
writetable(trial_table, trial_csv);
writetable(rank_table, rank_csv);
writetable(comparison_table, comparison_csv);

duplicate_row = trial_table.case_name == "exact_duplicate";
b_less_k_row = trial_table.case_name == "B_less_K";
rank_def_whitener_row = rank_table.case_name == "rank_deficient_Cb";
general_psd_row = rank_table.case_name == "general_psd_noise";
nonorthogonal_row = rank_table.case_name == "nonorthogonal_W_covariance";
concentrated_duplicate_row = concentrated_table.case_name == ...
    "rank_deficient_whitening_duplicate_G";
source_violation_count = sum(~source_rule_table.pass_flag);
num_svd_calls = trial_context.num_svd_calls + ...
    concentrated_context.num_svd_calls + comparison_context.num_svd_calls;
num_qr_calls = trial_context.num_qr_calls;
num_pinv_reference_calls = height(trial_table) + height(comparison_table);

overall_pass = all(rank_table.pass_flag) && all(trial_table.pass_flag) && ...
    all(concentrated_table.pass_flag) && all(comparison_table.pass_flag) && ...
    all(source_rule_table.pass_flag) && ...
    trial_context.max_well_conditioned_pinv_error < 1e-10 && ...
    trial_context.scale_score_relative_spread < 1e-12 && ...
    trial_context.nonfinite_count == 0 && ...
    concentrated_context.max_sigma2_relative_error < 1e-14;

metric = ["active_phase_factor"; "stable_rank_scale_invariant_flag"; ...
    "nonorthogonal_whitening_error"; "rank_deficient_whitening_error"; ...
    "general_psd_whitening_error"; "rank_deficient_whitener_output_rows"; ...
    "well_conditioned_svd_pinv_max_relative_error"; ...
    "well_conditioned_svd_qr_max_relative_error"; ...
    "manifold_scale_score_relative_spread"; ...
    "stress_nonfinite_count"; "duplicate_manifold_effective_rank"; ...
    "B_less_K_rank_deficient_flag"; ...
    "concentrated_sigma2_mle_max_relative_error"; ...
    "concentrated_duplicate_rank_deficient_flag"; ...
    "common_source_violation_count"; "rss_material_negative_count"; ...
    "rss_roundoff_clipped_count"; "svd_score_calls"; "qr_score_calls"; ...
    "pinv_reference_calls"; "legacy_ridge_comparison_calls"; ...
    "legacy_fast_comparison_calls"; "multi_start_runs"; ...
    "validation_runtime_sec"; "overall_pass_flag"];
value = [1; double(all(rank_table.effective_rank(1:3) == 2)); ...
    rank_table.whitening_error(nonorthogonal_row); ...
    rank_table.whitening_error(rank_def_whitener_row); ...
    rank_table.whitening_error(general_psd_row); ...
    rank_table.output_rows(rank_def_whitener_row); ...
    trial_context.max_well_conditioned_pinv_error; ...
    trial_context.max_well_conditioned_qr_error; ...
    trial_context.scale_score_relative_spread; ...
    trial_context.nonfinite_count; trial_table.effective_rank(duplicate_row); ...
    double(trial_table.status(b_less_k_row) == "RANK_DEFICIENT"); ...
    concentrated_context.max_sigma2_relative_error; ...
    double(concentrated_table.status(concentrated_duplicate_row) == ...
        "RANK_DEFICIENT"); ...
    source_violation_count; 0; trial_context.rss_clipped_count; ...
    num_svd_calls; num_qr_calls; num_pinv_reference_calls; ...
    height(comparison_table); height(comparison_table); 0; ...
    validation_runtime_sec; double(overall_pass)];
unit = ["dimensionless"; "boolean"; repmat("relative", 3, 1); ...
    "rows"; repmat("relative", 3, 1); "count"; "rank"; "boolean"; ...
    "relative"; "boolean"; repmat("count", 9, 1); "second"; "boolean"];
pass_flag = [true; all(rank_table.effective_rank(1:3) == 2); ...
    rank_table.whitening_error(nonorthogonal_row) < 1e-12; ...
    rank_table.whitening_error(rank_def_whitener_row) < 1e-12; ...
    rank_table.whitening_error(general_psd_row) < 1e-12; ...
    rank_table.output_rows(rank_def_whitener_row) == ...
        rank_table.effective_rank(rank_def_whitener_row); ...
    trial_context.max_well_conditioned_pinv_error < 1e-10; ...
    trial_context.max_well_conditioned_qr_error < 1e-10; ...
    trial_context.scale_score_relative_spread < 1e-12; ...
    trial_context.nonfinite_count == 0; ...
    trial_table.effective_rank(duplicate_row) == 1; ...
    trial_table.status(b_less_k_row) == "RANK_DEFICIENT"; ...
    concentrated_context.max_sigma2_relative_error < 1e-14; ...
    concentrated_table.status(concentrated_duplicate_row) == "RANK_DEFICIENT"; ...
    source_violation_count == 0; true; true; num_svd_calls > 0; ...
    num_qr_calls > 0; num_pinv_reference_calls > 0; ...
    height(comparison_table) > 0; height(comparison_table) > 0; true; ...
    validation_runtime_sec > 0; overall_pass];
phase_factor = ones(size(value));
keypoints_table = table(metric, value, unit, pass_flag, phase_factor);
writetable(keypoints_table, keypoints_csv);

write_report_local(report_md, rank_table, trial_table, concentrated_table, ...
    comparison_table, source_rule_table, rank_context, trial_context, ...
    concentrated_context, comparison_context, num_svd_calls, num_qr_calls, ...
    validation_runtime_sec, overall_pass);

fprintf('Step12.2 stable whitening/DML validation: %s\n', ...
    pass_fail_local(overall_pass));
fprintf('Max well-conditioned SVD/pinv error: %.3e\n', ...
    trial_context.max_well_conditioned_pinv_error);
fprintf('Manifold-scale score spread: %.3e\n', ...
    trial_context.scale_score_relative_spread);
fprintf('Rank-deficient whitener shape: %d x %d; error %.3e\n', ...
    size(rank_context.T_rank_deficient, 1), ...
    size(rank_context.T_rank_deficient, 2), ...
    rank_context.rank_deficient_info.whitening_error);
fprintf('SVD/QR score calls: %d / %d\n', num_svd_calls, num_qr_calls);
fprintf('Validation runtime: %.6f s\n', validation_runtime_sec);
fprintf('Results: %s\n', result_dir);
assert(overall_pass, 'run_step12_2:ValidationFailed', ...
    'Step12.2 failed at least one registered gate.');

function result = append_dml_rank_cases_local(base, trial)
case_names = ["exact_duplicate"; "B_less_K"];
rows = zeros(2, 1);
cols = zeros(2, 1);
expected = zeros(2, 1);
effective = zeros(2, 1);
requested = zeros(2, 1);
thresholds = zeros(2, 1);
statuses = strings(2, 1);
finite = false(2, 1);
passed = false(2, 1);
for idx = 1:2
    mask = trial.case_name == case_names(idx);
    rows(idx) = trial.matrix_rows(mask);
    cols(idx) = trial.requested_K(mask);
    effective(idx) = trial.effective_rank(mask);
    requested(idx) = trial.requested_K(mask);
    thresholds(idx) = trial.rank_threshold(mask);
    statuses(idx) = trial.status(mask);
    finite(idx) = trial.finite_flag(mask);
    passed(idx) = trial.pass_flag(mask);
end
expected(1) = 1;
expected(2) = rows(2);
extra = table("dml_" + case_names, repmat("dml_manifold", 2, 1), ...
    rows, cols, expected, effective, requested, thresholds, effective, ...
    NaN(2, 1), NaN(2, 1), statuses, finite, passed, ones(2, 1), ...
    'VariableNames', base.Properties.VariableNames);
result = [base; extra];
end

function write_report_local(path_out, rank_table, trial_table, concentrated_table, ...
    comparison_table, source_rule_table, rank_context, trial_context, ...
    concentrated_context, comparison_context, num_svd_calls, num_qr_calls, ...
    runtime_sec, overall_pass)
fid = fopen(path_out, 'w');
if fid < 0
    error('run_step12_2:ReportOpen', 'Cannot open report file: %s', path_out);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '---\nphase_factor: 1\nvalidation_status: %s\n', ...
    pass_fail_local(overall_pass));
fprintf(fid, 'whitening_coordinate: effective_subspace_rows\n---\n\n');
fprintf(fid, '# Step12.2 Stable Whitening and DML Validation\n\n');
fprintf(fid, '## Scope\n\n');
fprintf(fid, ['This report validates numerical rank, effective-subspace PSD ', ...
    'whitening, economy-SVD DML scoring, an optional QR comparison, and ', ...
    'concentrated RSS. No grouping, angle search, FIM design, bootstrap, ', ...
    'or model-order decision is implemented.\n\n']);
fprintf(fid, '## Legacy audit\n\n');
fprintf(fid, ['The frozen Step11 whitener uses a fixed absolute eigenvalue ', ...
    'floor, the frozen DML score uses a fixed ridge normal equation, and ', ...
    'five frozen search functions contain a 2-by-2 Gram determinant score. ', ...
    'Step12.2 calls none of these paths.\n\n']);
fprintf(fid, '## Rank and whitening\n\n');
write_table_header_local(fid, ...
    {'case','expected rank','effective rank','T rows','whitening error','status','pass'});
for idx = 1:height(rank_table)
    fprintf(fid, '| %s | %d | %d | %d | %.6e | %s | %d |\n', ...
        char(rank_table.case_name(idx)), rank_table.expected_rank(idx), ...
        rank_table.effective_rank(idx), rank_table.output_rows(idx), ...
        rank_table.whitening_error(idx), char(rank_table.status(idx)), ...
        rank_table.pass_flag(idx));
end
fprintf(fid, ['\nThe rank-deficient covariance returns a %d-by-%d whitener; ', ...
    '`T*C*T''` relative error is %.6e.\n\n'], ...
    size(rank_context.T_rank_deficient, 1), ...
    size(rank_context.T_rank_deficient, 2), ...
    rank_context.rank_deficient_info.whitening_error);

fprintf(fid, '## Stable score matrix\n\n');
write_table_header_local(fid, ...
    {'case','rank','status','SVD/pinv error','SVD/QR error','RSS','pass'});
for idx = 1:height(trial_table)
    fprintf(fid, '| %s | %d | %s | %.6e | %.6e | %.6e | %d |\n', ...
        char(trial_table.case_name(idx)), trial_table.effective_rank(idx), ...
        char(trial_table.status(idx)), ...
        trial_table.svd_pinv_relative_error(idx), ...
        trial_table.svd_qr_relative_error(idx), trial_table.rss(idx), ...
        trial_table.pass_flag(idx));
end
fprintf(fid, '\n- Maximum well-conditioned SVD/pinv error: %.6e.\n', ...
    trial_context.max_well_conditioned_pinv_error);
fprintf(fid, '- Maximum well-conditioned SVD/QR error: %.6e.\n', ...
    trial_context.max_well_conditioned_qr_error);
fprintf(fid, '- Scale score relative spread: %.6e.\n', ...
    trial_context.scale_score_relative_spread);
fprintf(fid, '- Non-finite stable results: %d; roundoff RSS clips: %d.\n\n', ...
    trial_context.nonfinite_count, trial_context.rss_clipped_count);

fprintf(fid, '## Concentrated RSS\n\n');
write_table_header_local(fid, ...
    {'case','rC','rank(Gw)','sigma2 ML error','status','pass'});
for idx = 1:height(concentrated_table)
    fprintf(fid, '| %s | %d | %d | %.6e | %s | %d |\n', ...
        char(concentrated_table.case_name(idx)), concentrated_table.rC(idx), ...
        concentrated_table.effective_rank(idx), ...
        concentrated_table.sigma2_relative_error(idx), ...
        char(concentrated_table.status(idx)), concentrated_table.pass_flag(idx));
end
fprintf(fid, ['\nThe variance denominator is `rC*L` with rC=%d in the ', ...
    'rank-deficient-whitening test; no unbiased correction is applied.\n\n'], ...
    concentrated_context.whitening_rank);

fprintf(fid, '## Legacy score comparison\n\n');
fprintf(fid, '- Stable SVD scale spread: %.6e.\n', ...
    comparison_context.new_scale_relative_spread);
fprintf(fid, '- Legacy ridge scale spread: %.6e.\n', ...
    comparison_context.old_ridge_scale_relative_spread);
fprintf(fid, '- Legacy 2-by-2 fast-score scale spread: %.6e.\n', ...
    comparison_context.old_fast_scale_relative_spread);
fprintf(fid, '- Near-rank pinv/stable relative difference: %.6e.\n\n', ...
    comparison_context.near_rank_pinv_relative_difference);
fprintf(fid, 'All %d comparison rows retained the stable score as finite.\n\n', ...
    height(comparison_table));

fprintf(fid, '## Source and complexity checks\n\n');
fprintf(fid, '- Common-source dependency rules passed: %d/%d.\n', ...
    nnz(source_rule_table.pass_flag), height(source_rule_table));
fprintf(fid, '- Registered SVD/QR score calls: %d/%d.\n', ...
    num_svd_calls, num_qr_calls);
fprintf(fid, ['- Per-candidate SVD/projection complexity: ', ...
    '`O(B*K^2 + rank(G)*B*L)`; whitening eigendecomposition: `O(B^3)`.\n']);
fprintf(fid, ['- Working-storage orders: `O(B*K + rank(G)*L)` for scoring ', ...
    'and `O(B^2)` for whitening; peak process memory was not profiled.\n']);
fprintf(fid, '- Multi-start, grouping, FIM, and bootstrap calls: 0.\n\n');
fprintf(fid, '## Result\n\n');
fprintf(fid, ['**%s.** Runtime %.6f s. This deterministic numerical ', ...
    'validation reports no confidence interval.\n'], ...
    pass_fail_local(overall_pass), runtime_sec);
clear cleanup;
end

function write_table_header_local(fid, headings)
fprintf(fid, '| %s |\n', strjoin(headings, ' | '));
separators = repmat({'---'}, 1, numel(headings));
fprintf(fid, '| %s |\n', strjoin(separators, ' | '));
end

function text = pass_fail_local(flag)
if flag
    text = 'PASS';
else
    text = 'FAIL';
end
end
