function registry = stage8_k2_tp_build_registry(local_domain, constants)
%STAGE8_K2_TP_BUILD_REGISTRY Build the independent fixed 72-trial K2 set.

if nargin < 2 || isempty(constants)
    constants = stage8_k2_tp_constants();
end
if nargin < 1 || isempty(local_domain)
    bounds = [7.4, 8.6, 9.8, 10.2];
else
    bounds = local_domain.domain_bounds_deg;
end
rows = cell(constants.trial_count, 1);
trial_index = 0;
for noise_index = 1:numel(constants.noise_profile_ids)
    for L = constants.snapshot_counts
        for snr_db = constants.snr_db_values
            for profile_index = 1:numel(constants.profiles)
                trial_index = trial_index + 1;
                profile = constants.profiles(profile_index);
                correlation = profile.correlation_magnitude;
                correlation_contract = 'SPECIFIED_CORRELATION';
                if L == 1
                    correlation = 1;
                    correlation_contract = ...
                        'L1_FULLY_COHERENT_BY_CONTRACT';
                end
                rows{trial_index} = row_local(trial_index, ...
                    constants.noise_profile_ids(noise_index), L, snr_db, ...
                    profile, correlation, correlation_contract, constants);
            end
        end
    end
end
registry = struct2table(vertcat(rows{:}));
validate_registry_local(registry, bounds, constants);
end

function row = row_local(index, noise_id, L, snr_db, profile, ...
    correlation, correlation_contract, constants)
trial_id = sprintf('TP1_K2_N%d_L%d_S%s_%s', ...
    find(constants.noise_profile_ids == noise_id, 1), L, ...
    signed_token_local(snr_db), profile.profile_id);
row = struct('global_trial_index', double(index), ...
    'trial_id', string(trial_id), 'K', 2, ...
    'noise_profile_id', string(noise_id), 'L', double(L), ...
    'snr_db', double(snr_db), 'profile_id', string(profile.profile_id), ...
    'center_az_deg', profile.center_deg(1), ...
    'center_el_deg', profile.center_deg(2), ...
    'separation_deg', profile.separation_deg, ...
    'direction_deg', profile.direction_deg, ...
    'secondary_power_db', profile.secondary_power_db, ...
    'correlation_magnitude', double(correlation), ...
    'source_correlation_contract', string(correlation_contract), ...
    'source_seed', double(constants.source_seed_base + index - 1), ...
    'noise_seed', double(constants.noise_seed_base + index - 1), ...
    'cpi_id', "ONE_SYNTHETIC_CPI", ...
    'range_doppler_cell_id', "ONE_SELECTED_RANGE_DOPPLER_CELL", ...
    'single_cpi_flag', true, 'same_range_doppler_cell_flag', true, ...
    'cross_cpi_data_used_flag', false, ...
    'tracking_input_used_flag', false, ...
    'K_estimated_inside_module_flag', false);
end

function validate_registry_local(registry, bounds, constants)
expected_sources = constants.source_seed_base + (0:constants.trial_count-1).';
expected_noise = constants.noise_seed_base + (0:constants.trial_count-1).';
if height(registry) ~= constants.trial_count || ...
        numel(unique(registry.trial_id)) ~= constants.trial_count || ...
        ~isequal(registry.source_seed, expected_sources) || ...
        ~isequal(registry.noise_seed, expected_noise) || ...
        numel(unique(registry.source_seed)) ~= constants.trial_count || ...
        numel(unique(registry.noise_seed)) ~= constants.trial_count
    error('stage8_k2_tp_build_registry:Cardinality', ...
        'The fixed 72-trial registry or seed sequence is invalid.');
end
expected_factor_count = numel(constants.noise_profile_ids) * ...
    numel(constants.snapshot_counts) * numel(constants.snr_db_values) * ...
    numel(constants.profiles);
if expected_factor_count ~= constants.trial_count || ...
        any(registry.K ~= 2) || any(~registry.single_cpi_flag) || ...
        any(~registry.same_range_doppler_cell_flag) || ...
        any(registry.cross_cpi_data_used_flag) || ...
        any(registry.tracking_input_used_flag) || ...
        any(registry.K_estimated_inside_module_flag)
    error('stage8_k2_tp_build_registry:Scenario', ...
        'The known-K single-cell scenario contract is invalid.');
end
for index = 1:height(registry)
    direction = [cosd(registry.direction_deg(index)), ...
        sind(registry.direction_deg(index))];
    center = [registry.center_az_deg(index), registry.center_el_deg(index)];
    targets = [center - registry.separation_deg(index) * direction / 2; ...
        center + registry.separation_deg(index) * direction / 2];
    if any(targets(:, 1) < bounds(1) | targets(:, 1) > bounds(2) | ...
            targets(:, 2) < bounds(3) | targets(:, 2) > bounds(4))
        error('stage8_k2_tp_build_registry:Domain', ...
            'A registered truth endpoint is outside the frozen domain.');
    end
    if registry.L(index) == 1 && ...
            (registry.correlation_magnitude(index) ~= 1 || ...
            registry.source_correlation_contract(index) ~= ...
            "L1_FULLY_COHERENT_BY_CONTRACT")
        error('stage8_k2_tp_build_registry:L1Contract', ...
            'An L=1 trial violates the coherent-source contract.');
    end
end
end

function token = signed_token_local(value)
if value < 0
    token = sprintf('M%d', abs(value));
else
    token = sprintf('P%d', value);
end
end
