function constants = stage8_k2_tp_constants()
%STAGE8_K2_TP_CONSTANTS Frozen decisive-experiment contract.

profiles = repmat(struct('profile_id', '', 'center_deg', [NaN, NaN], ...
    'separation_deg', NaN, 'direction_deg', NaN, ...
    'secondary_power_db', NaN, 'correlation_magnitude', NaN), 4, 1);
profiles(1) = profile_local('P1', [8.00, 10.00], 0.30, 45, 0, 0);
profiles(2) = profile_local('P2', [8.20, 10.00], 0.20, 0, -6, 0);
profiles(3) = profile_local('P3', [7.90, 10.10], 0.15, 90, 0, 0.9);
profiles(4) = profile_local('P4', [8.10, 9.95], 0.10, 135, -6, 0.9);

constants = struct( ...
    'protocol', 'STAGE8_K2_TANGENT_PROFILE_DECISIVE_EXPERIMENT_V1', ...
    'authorization', ...
    'AUTHORIZE_STAGE8_K2_TANGENT_PROFILE_DECISIVE_EXPERIMENT_V1', ...
    'branch', 'experiment/stage8-k2-tangent-profile-v1', ...
    'base_commit', '9bcb4f7e0d4ec314e5a822deb0ea02216c10c8f7', ...
    'expected_origin_core_v2', ...
    '9bcb4f7e0d4ec314e5a822deb0ea02216c10c8f7', ...
    'expected_origin_main', ...
    '247fad2208e77b04f7062e22b0fd3fd8a81bfc1f', ...
    'primary_measurement_config_id', 'PRIMARY_RECT_E14_A31', ...
    'noise_profile_ids', ...
    ["WHITE"; "STAGE5_TOEPLITZ_CORRELATED"], ...
    'snapshot_counts', [1, 4, 8], 'snr_db_values', [-6, 0, 6], ...
    'profiles', profiles, 'source_seed_base', 3326074000, ...
    'noise_seed_base', 3326075000, 'trial_count', 72, ...
    'method_ids', ["CORE_LITE"; "CORE_PLUS"; ...
    "TANGENT_PROFILE_SAFE"], 'method_row_count', 216, ...
    'rho_min_deg', 1e-3, 'scan_node_count', 33, ...
    'fminbnd_TolX_deg', 1e-4, 'fminbnd_MaxFunEvals', 80, ...
    'rank_multiplier', 1, 'direction_sign_tolerance', 1e-12, ...
    'paired_tie_tolerance_deg', 1e-6, ...
    'runtime_root', ...
    'E:\bs_innovation_runtime\stage8_k2_tangent_profile_v1');
end

function profile = profile_local(id, center, separation, direction, power, correlation)
profile = struct('profile_id', id, 'center_deg', center, ...
    'separation_deg', separation, 'direction_deg', direction, ...
    'secondary_power_db', power, ...
    'correlation_magnitude', correlation);
end
