function context = stage8_k2_tp_build_context(repo_dir)
%STAGE8_K2_TP_BUILD_CONTEXT Load fixed measurement and whitening context.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_tp_build_context:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
constants = stage8_k2_tp_constants();
plan = build_stage8_locked_plan(repo_dir, sim_cfg(), ...
    struct('require_formal_runtime', false));
expected_bounds = [7.4, 8.6, 9.8, 10.2];
if ~isequal(plan.local_domain.domain_bounds_deg, expected_bounds)
    error('stage8_k2_tp_build_context:Domain', ...
        'The frozen Stage8 local domain changed.');
end
stage5_locked = build_stage8_stage5_locked_config();
context = struct('repo_dir', repo_dir, 'constants', constants, ...
    'plan', plan, 'stage5_locked', stage5_locked, ...
    'primary_measurement_config_id', ...
    constants.primary_measurement_config_id, ...
    'single_cpi_flag', true, ...
    'same_range_doppler_cell_flag', true, ...
    'cross_cpi_data_used_flag', false, ...
    'tracking_input_used_flag', false, ...
    'K_estimated_inside_module_flag', false);
context.context_hash = stage8_k2_tp_stable_hash(constants.protocol, ...
    plan.local_domain.domain_hash, plan.stage8_measurement_plan_hash, ...
    stage5_locked.configuration_hash);
end
