function output = stage8_k2_tp_summarize( ...
    method_rows, diagnostics, registry, repo_dir, runtime_root)
%STAGE8_K2_TP_SUMMARIZE Build fixed decisive metrics and evidence files.

constants = stage8_k2_tp_constants();
validate_inputs_local(method_rows, diagnostics, registry, constants);
summary_rows = build_summary_rows_local(method_rows, constants);
[pair_lite, pair_plus] = paired_results_local(method_rows, constants);
summary_rows = [summary_rows; paired_row_local(pair_lite); ...
    paired_row_local(pair_plus)]; %#ok<AGROW>
complexity = complexity_local(method_rows, constants);
geometry = geometry_quartiles_local(method_rows, diagnostics);
overall = overall_metrics_local(method_rows, diagnostics, ...
    complexity, pair_lite, pair_plus, constants);
integrity = integrity_local(method_rows, diagnostics, registry, constants);
conclusion = decision_local(overall, integrity);
summary_rows = [summary_rows; decision_row_local(conclusion)]; %#ok<AGROW>
summary_table = struct2table(summary_rows);

repo_evidence_dir = fullfile(repo_dir, 'innovation-mining');
paths = evidence_paths_local(repo_evidence_dir);
path_names = fieldnames(paths);
for index = 1:numel(path_names)
    if isfile(paths.(path_names{index}))
        error('stage8_k2_tp_summarize:ExistingEvidence', ...
            'Refusing to overwrite existing evidence: %s', ...
            paths.(path_names{index}));
    end
end
if ~isfolder(runtime_root), mkdir(runtime_root); end
writetable(method_rows, fullfile(runtime_root, ...
    '31_stage8_k2_tangent_profile_trials.csv'));
writetable(summary_table, fullfile(runtime_root, ...
    '31_stage8_k2_tangent_profile_summary.csv'));
writetable(geometry, fullfile(runtime_root, ...
    '31_stage8_k2_tangent_profile_geometry_analysis.csv'));
writetable(complexity, fullfile(runtime_root, ...
    '31_stage8_k2_tangent_profile_complexity.csv'));
writetable(method_rows, paths.trials);
writetable(summary_table, paths.summary);
writetable(geometry, paths.geometry);
writetable(complexity, paths.complexity);
write_report_local(paths.report, method_rows, diagnostics, summary_table, ...
    geometry, complexity, overall, integrity, conclusion, constants, ...
    runtime_root);
output = struct('summary_table', summary_table, ...
    'geometry_table', geometry, 'complexity_table', complexity, ...
    'overall', overall, 'integrity', integrity, ...
    'conclusion', conclusion, 'evidence_paths', paths);
end

function rows = build_summary_rows_local(method_rows, constants)
template = summary_template_local();
rows = repmat(template, 0, 1);
for method_index = 1:numel(constants.method_ids)
    method_id = constants.method_ids(method_index);
    subset = method_rows(method_rows.method_id == method_id, :);
    rows(end + 1, 1) = metric_row_local( ...
        'OVERALL', 'ALL', method_id, subset); %#ok<AGROW>
    for profile = ["P1", "P2", "P3", "P4"]
        rows(end + 1, 1) = metric_row_local('PROFILE', char(profile), ...
            method_id, subset(subset.profile_id == profile, :)); %#ok<AGROW>
    end
    for L = [1, 4, 8]
        rows(end + 1, 1) = metric_row_local('L', sprintf('%d', L), ...
            method_id, subset(subset.L == L, :)); %#ok<AGROW>
    end
    for snr_db = [-6, 0, 6]
        rows(end + 1, 1) = metric_row_local('SNR_DB', ...
            sprintf('%+d', snr_db), method_id, ...
            subset(subset.snr_db == snr_db, :)); %#ok<AGROW>
    end
end
end

function row = metric_row_local(scope_type, scope_value, method_id, subset)
row = summary_template_local();
row.scope_type = string(scope_type);
row.scope_value = string(scope_value);
row.method_id = string(method_id);
row.valid_count = nnz(subset.fit_valid);
row.trial_count = height(subset);
values = subset.joint_RMSE_deg(subset.fit_valid & ...
    isfinite(subset.joint_RMSE_deg));
row.median_joint_RMSE_deg = median_or_nan_local(values);
row.p90_joint_RMSE_deg = percentile_or_nan_local(values, 90);
end

function row = summary_template_local()
row = struct('scope_type', "", 'scope_value', "", 'method_id', "", ...
    'valid_count', NaN, 'trial_count', NaN, ...
    'median_joint_RMSE_deg', NaN, 'p90_joint_RMSE_deg', NaN, ...
    'comparison_id', "", 'wins', NaN, 'ties', NaN, 'losses', NaN, ...
    'decision', "");
end

function pair = paired_one_local(method_rows, baseline_id, constants)
m2 = sortrows(method_rows(method_rows.method_id == ...
    "TANGENT_PROFILE_SAFE", :), 'trial_id');
baseline = sortrows(method_rows(method_rows.method_id == baseline_id, :), ...
    'trial_id');
if height(m2) ~= constants.trial_count || ...
        ~isequal(m2.trial_id, baseline.trial_id)
    error('stage8_k2_tp_summarize:Pairing', ...
        'Paired method rows do not share the fixed trial IDs.');
end
delta = m2.joint_RMSE_deg - baseline.joint_RMSE_deg;
finite_pair = isfinite(delta);
tie = finite_pair & abs(delta) <= constants.paired_tie_tolerance_deg;
win = finite_pair & delta < -constants.paired_tie_tolerance_deg;
loss = finite_pair & delta > constants.paired_tie_tolerance_deg;
pair = struct('comparison_id', ...
    "TANGENT_PROFILE_SAFE_vs_" + string(baseline_id), ...
    'baseline_id', string(baseline_id), 'wins', nnz(win), ...
    'ties', nnz(tie), 'losses', nnz(loss), ...
    'finite_pair_count', nnz(finite_pair));
end

function [lite, plus] = paired_results_local(method_rows, constants)
lite = paired_one_local(method_rows, "CORE_LITE", constants);
plus = paired_one_local(method_rows, "CORE_PLUS", constants);
end

function row = paired_row_local(pair)
row = summary_template_local();
row.scope_type = "PAIRED";
row.scope_value = pair.comparison_id;
row.method_id = "TANGENT_PROFILE_SAFE";
row.comparison_id = pair.comparison_id;
row.trial_count = pair.finite_pair_count;
row.wins = pair.wins;
row.ties = pair.ties;
row.losses = pair.losses;
end

function row = decision_row_local(conclusion)
row = summary_template_local();
row.scope_type = "DECISION";
row.scope_value = string(conclusion);
row.decision = string(conclusion);
end

function table_out = complexity_local(method_rows, constants)
rows = cell(numel(constants.method_ids), 1);
for index = 1:numel(constants.method_ids)
    method_id = constants.method_ids(index);
    subset = method_rows(method_rows.method_id == method_id, :);
    rows{index} = struct('method_id', string(method_id), ...
        'valid_count', nnz(subset.fit_valid), ...
        'trial_count', height(subset), ...
        'mean_score_calls', mean(subset.score_call_count), ...
        'mean_SVD_calls', mean(subset.SVD_call_count), ...
        'median_runtime_sec', median(subset.runtime_sec), ...
        'p90_runtime_sec', percentile_or_nan_local(subset.runtime_sec, 90));
end
table_out = struct2table(vertcat(rows{:}));
end

function table_out = geometry_quartiles_local(method_rows, diagnostics)
m2 = method_rows(method_rows.method_id == "TANGENT_PROFILE_SAFE", :);
[matched, location] = ismember(diagnostics.trial_id, m2.trial_id);
if ~all(matched)
    error('stage8_k2_tp_summarize:GeometryPairing', ...
        'A diagnostic row has no M2 method row.');
end
m2_rmse = m2.joint_RMSE_deg(location);
[~, order] = sort(diagnostics.Gamma_K2_proxy, 'ascend');
quartile_id = zeros(height(diagnostics), 1);
for rank_index = 1:height(diagnostics)
    quartile_id(order(rank_index)) = ceil(4 * rank_index / ...
        height(diagnostics));
end
rows = cell(4, 1);
for quartile = 1:4
    selected = quartile_id == quartile;
    direction = diagnostics.direction_error_deg(selected);
    rho = diagnostics.rho_error_deg(selected);
    rmse = m2_rmse(selected);
    rows{quartile} = struct('Gamma_quartile', ...
        string(sprintf('Q%d', quartile)), 'trial_count', nnz(selected), ...
        'Gamma_min', min(diagnostics.Gamma_K2_proxy(selected)), ...
        'Gamma_max', max(diagnostics.Gamma_K2_proxy(selected)), ...
        'Gamma_median', median(diagnostics.Gamma_K2_proxy(selected)), ...
        'median_direction_error_deg', ...
        median_or_nan_local(direction(isfinite(direction))), ...
        'p90_direction_error_deg', ...
        percentile_or_nan_local(direction(isfinite(direction)), 90), ...
        'median_rho_error_deg', ...
        median_or_nan_local(rho(isfinite(rho))), ...
        'p90_rho_error_deg', ...
        percentile_or_nan_local(rho(isfinite(rho)), 90), ...
        'median_RMSE_deg', median_or_nan_local(rmse(isfinite(rmse))), ...
        'raw_candidate_valid_rate', ...
        mean(diagnostics.raw_tangent_candidate_valid(selected)), ...
        'fallback_rate', mean(diagnostics.fallback_flag(selected)));
end
table_out = struct2table(vertcat(rows{:}));
end

function overall = overall_metrics_local(method_rows, diagnostics, ...
    complexity, pair_lite, pair_plus, constants)
overall = struct();
for index = 1:numel(constants.method_ids)
    method_id = constants.method_ids(index);
    field = lower(char(method_id));
    subset = method_rows(method_rows.method_id == method_id, :);
    valid_values = subset.joint_RMSE_deg(subset.fit_valid & ...
        isfinite(subset.joint_RMSE_deg));
    cost = complexity(complexity.method_id == method_id, :);
    overall.(field) = struct('valid_count', nnz(subset.fit_valid), ...
        'median_RMSE_deg', median_or_nan_local(valid_values), ...
        'p90_RMSE_deg', percentile_or_nan_local(valid_values, 90), ...
        'mean_score_calls', cost.mean_score_calls, ...
        'mean_SVD_calls', cost.mean_SVD_calls, ...
        'median_runtime_sec', cost.median_runtime_sec, ...
        'p90_runtime_sec', cost.p90_runtime_sec);
end
direction = diagnostics.direction_error_deg( ...
    isfinite(diagnostics.direction_error_deg));
rho = diagnostics.rho_error_deg(isfinite(diagnostics.rho_error_deg));
m2 = method_rows(method_rows.method_id == "TANGENT_PROFILE_SAFE", :);
separation = m2.separation_vector_error_deg( ...
    isfinite(m2.separation_vector_error_deg));
overall.tangent_diagnostics = struct( ...
    'raw_candidate_valid_count', ...
    nnz(diagnostics.raw_tangent_candidate_valid), ...
    'upgrade_count', nnz(diagnostics.upgrade_flag), ...
    'fallback_count', nnz(diagnostics.fallback_flag), ...
    'median_direction_error_deg', median_or_nan_local(direction), ...
    'p90_direction_error_deg', percentile_or_nan_local(direction, 90), ...
    'median_rho_error_deg', median_or_nan_local(rho), ...
    'p90_rho_error_deg', percentile_or_nan_local(rho, 90), ...
    'median_separation_vector_error_deg', ...
    median_or_nan_local(separation), ...
    'p90_separation_vector_error_deg', ...
    percentile_or_nan_local(separation, 90));
overall.paired_vs_core_lite = pair_lite;
overall.paired_vs_core_plus = pair_plus;
end

function integrity = integrity_local(method_rows, diagnostics, registry, constants)
pair_ids = method_rows.trial_id + "|" + method_rows.method_id;
count_ok = height(registry) == constants.trial_count && ...
    height(method_rows) == constants.method_row_count && ...
    height(diagnostics) == constants.trial_count && ...
    numel(unique(pair_ids)) == constants.method_row_count && ...
    numel(unique(diagnostics.trial_id)) == constants.trial_count;
truth_ok = ~any(method_rows.truth_used_in_fit_flag) && ...
    ~any(diagnostics.truth_used_in_fit_flag);
scenario_ok = all(method_rows.single_cpi_flag) && ...
    all(method_rows.same_range_doppler_cell_flag) && ...
    ~any(method_rows.cross_cpi_data_used_flag) && ...
    ~any(method_rows.tracking_input_used_flag) && ...
    ~any(method_rows.K_estimated_inside_module_flag);
hash_ok = true;
registry_pairing_ok = true;
for index = 1:height(registry)
    subset = method_rows(method_rows.trial_id == registry.trial_id(index), :);
    diagnostic = diagnostics(diagnostics.trial_id == registry.trial_id(index), :);
    hash_ok = hash_ok && height(subset) == 3 && height(diagnostic) == 1 && ...
        numel(unique(subset.element_trial_hash)) == 1 && ...
        unique(subset.element_trial_hash) == diagnostic.element_trial_hash;
    registry_pairing_ok = registry_pairing_ok && height(subset) == 3 && ...
        all(subset.noise_profile_id == registry.noise_profile_id(index)) && ...
        all(subset.L == registry.L(index)) && ...
        all(subset.snr_db == registry.snr_db(index)) && ...
        all(subset.profile_id == registry.profile_id(index)) && ...
        all(subset.source_seed == registry.source_seed(index)) && ...
        all(subset.noise_seed == registry.noise_seed(index));
end
m2 = method_rows(method_rows.method_id == "TANGENT_PROFILE_SAFE", :);
m2_safe = height(m2) == constants.trial_count && all(m2.fit_valid) && ...
    all(isfinite(m2.RSS)) && all(isfinite(m2.loglik)) && ...
    all(isfinite(m2.joint_RMSE_deg));
integrity = struct('count_ok', count_ok, 'truth_isolation_ok', truth_ok, ...
    'scenario_ok', scenario_ok, 'element_pairing_ok', hash_ok, ...
    'registry_pairing_ok', registry_pairing_ok, ...
    'm2_safe_return_ok', m2_safe, ...
    'experiment_valid', count_ok && truth_ok && scenario_ok && ...
    hash_ok && registry_pairing_ok && m2_safe);
end

function conclusion = decision_local(overall, integrity)
if ~integrity.experiment_valid
    conclusion = 'STAGE8_K2_TANGENT_PROFILE_EXPERIMENT_INVALID';
    return;
end
m2 = overall.tangent_profile_safe;
lite = overall.core_lite;
plus = overall.core_plus;
paired_lite = overall.paired_vs_core_lite;
paired_plus = overall.paired_vs_core_plus;
retain = m2.valid_count == 72 && ...
    m2.median_RMSE_deg <= plus.median_RMSE_deg && ...
    m2.p90_RMSE_deg <= plus.p90_RMSE_deg && ...
    paired_plus.wins >= paired_plus.losses && ...
    m2.mean_score_calls < plus.mean_score_calls && ...
    m2.mean_SVD_calls < plus.mean_SVD_calls;
efficient = m2.valid_count == 72 && ...
    m2.median_RMSE_deg <= lite.median_RMSE_deg && ...
    m2.p90_RMSE_deg <= lite.p90_RMSE_deg && ...
    paired_lite.wins >= paired_lite.losses && ...
    m2.mean_score_calls < plus.mean_score_calls && ...
    m2.mean_SVD_calls < plus.mean_SVD_calls;
if retain
    conclusion = 'STAGE8_K2_TANGENT_PROFILE_RETAIN';
elseif efficient
    conclusion = 'STAGE8_K2_TANGENT_PROFILE_RETAIN_AS_EFFICIENT_OPTION';
else
    conclusion = 'STAGE8_K2_TANGENT_PROFILE_NOT_RETAINED';
end
end

function paths = evidence_paths_local(directory)
prefix = fullfile(directory, '31_stage8_k2_tangent_profile_');
paths = struct('report', [prefix, 'decisive_experiment.md'], ...
    'trials', [prefix, 'trials.csv'], ...
    'summary', [prefix, 'summary.csv'], ...
    'geometry', [prefix, 'geometry_analysis.csv'], ...
    'complexity', [prefix, 'complexity.csv']);
end

function write_report_local(path_now, method_rows, diagnostics, summary, ...
    geometry, complexity, overall, integrity, conclusion, constants, runtime_root)
[status, head] = system('git rev-parse HEAD');
if status ~= 0, head = 'UNKNOWN'; else, head = strtrim(head); end
fid = fopen(path_now, 'w');
if fid < 0
    error('stage8_k2_tp_summarize:ReportOpen', ...
        'Unable to create the decisive report.');
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, '# Stage8 K2 Tangent-Profile Decisive Experiment\n\n');
fprintf(fid, 'Protocol: `%s`\n\n', constants.protocol);
fprintf(fid, 'Execution HEAD: `%s`\n\n', head);
fprintf(fid, 'Runtime root: `%s`\n\n', strrep(runtime_root, '\\', '/'));
fprintf(fid, 'Theory tests: noiseless direction PASS; isotropic noise shift PASS; rank deficiency PASS; full-manifold smoke PASS.\n\n');
fprintf(fid, 'Registry: K2 `72/72`; method rows `216/216`; tangent diagnostics `72/72`.\n\n');
fprintf(fid, 'Integrity: counts `%d`; truth isolation `%d`; shared element data `%d`; registry/seeds `%d`; scenario `%d`; M2 safe returns `%d`.\n\n', ...
    integrity.count_ok, integrity.truth_isolation_ok, ...
    integrity.element_pairing_ok, integrity.registry_pairing_ok, ...
    integrity.scenario_ok, ...
    integrity.m2_safe_return_ok);
fprintf(fid, '## Overall accuracy and cost\n\n');
fprintf(fid, '| Method | Valid | Median RMSE deg | P90 RMSE deg | Mean score | Mean SVD | Median runtime sec | P90 runtime sec |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|---:|\n');
write_overall_row_local(fid, 'CORE_LITE', overall.core_lite);
write_overall_row_local(fid, 'CORE_PLUS', overall.core_plus);
write_overall_row_local(fid, 'TANGENT_PROFILE_SAFE', ...
    overall.tangent_profile_safe);
fprintf(fid, '\n## Tangent diagnostics\n\n');
d = overall.tangent_diagnostics;
fprintf(fid, '- Raw valid: `%d/72`; upgrades/fallbacks: `%d/%d`.\n', ...
    d.raw_candidate_valid_count, d.upgrade_count, d.fallback_count);
fprintf(fid, '- Direction median/p90: `%.17g / %.17g deg`.\n', ...
    d.median_direction_error_deg, d.p90_direction_error_deg);
fprintf(fid, '- Rho median/p90: `%.17g / %.17g deg`.\n', ...
    d.median_rho_error_deg, d.p90_rho_error_deg);
fprintf(fid, '- Separation-vector median/p90: `%.17g / %.17g deg`.\n\n', ...
    d.median_separation_vector_error_deg, ...
    d.p90_separation_vector_error_deg);
fprintf(fid, '## Paired comparisons\n\n');
fprintf(fid, '| Comparison | Wins | Ties | Losses |\n|---|---:|---:|---:|\n');
write_pair_local(fid, overall.paired_vs_core_lite);
write_pair_local(fid, overall.paired_vs_core_plus);
fprintf(fid, '\nTie tolerance is reporting-only at `1e-6 deg`.\n\n');
fprintf(fid, '## Profile, L, and SNR summaries\n\n');
fprintf(fid, '| Scope | Value | Method | Valid | N | Median RMSE deg | P90 RMSE deg |\n');
fprintf(fid, '|---|---|---|---:|---:|---:|---:|\n');
metric_rows = summary(ismember(summary.scope_type, ...
    ["PROFILE", "L", "SNR_DB"]), :);
for index = 1:height(metric_rows)
    fprintf(fid, '| %s | %s | %s | %d | %d | %.17g | %.17g |\n', ...
        char(metric_rows.scope_type(index)), ...
        char(metric_rows.scope_value(index)), ...
        char(metric_rows.method_id(index)), ...
        metric_rows.valid_count(index), metric_rows.trial_count(index), ...
        metric_rows.median_joint_RMSE_deg(index), ...
        metric_rows.p90_joint_RMSE_deg(index));
end
fprintf(fid, '\n## Gamma_K2_proxy quartiles\n\n');
fprintf(fid, '| Quartile | N | Gamma median | Direction median/p90 deg | Rho median/p90 deg | RMSE median deg | Raw valid rate | Fallback rate |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|---:|\n');
for index = 1:height(geometry)
    fprintf(fid, '| %s | %d | %.17g | %.17g / %.17g | %.17g / %.17g | %.17g | %.17g | %.17g |\n', ...
        char(geometry.Gamma_quartile(index)), geometry.trial_count(index), ...
        geometry.Gamma_median(index), ...
        geometry.median_direction_error_deg(index), ...
        geometry.p90_direction_error_deg(index), ...
        geometry.median_rho_error_deg(index), ...
        geometry.p90_rho_error_deg(index), ...
        geometry.median_RMSE_deg(index), ...
        geometry.raw_candidate_valid_rate(index), ...
        geometry.fallback_rate(index));
end
fprintf(fid, '\nGamma is truth-only descriptive analysis and is not an online threshold.\n\n');
fprintf(fid, '## Decision\n\nFinal conclusion: `%s`\n\n', conclusion);
fprintf(fid, 'The decision applies the frozen RETAIN, RETAIN_AS_EFFICIENT_OPTION, NOT_RETAINED, and EXPERIMENT_INVALID rules without tuning or rerunning.\n\n');
fprintf(fid, '## Prior-art position\n\n');
fprintf(fid, 'The result is positioned only as a system-specific combination of a K1 projected residual, a Fisher-metric generalized eigenvector on the actual fixed exactly whitened two-dimensional sequential beamspace manifold, and a one-dimensional exact full-manifold K2 profile likelihood with fixed-grid fallback. Vincent et al. (2014, DOI 10.1016/j.sigpro.2013.10.017) and Bonacci et al. (2017, DOI 10.1049/iet-rsn.2016.0446) already cover close-source Taylor approximate ML and one-dimensional reductions; Partial Relaxation (arXiv:1711.01982) covers eigenvalue-based dimension reduction; Kim et al. (2012, DOI 10.1049/iet-rsn.2010.0163) covers two targets in beamspace. No first-in-field claim is made. If the identical combination is found, the classification is `SYSTEM-SPECIFIC IMPLEMENTATION / ENGINEERING SPECIALIZATION`.\n\n');
fprintf(fid, '## Stop rule\n\nNo V2, extra starts, center correction, second direction, Hessian solver, automatic K, bootstrap, additional trials, production change, or merge is authorized by this result.\n');
% Keep arguments visible in the generated-evidence contract.
assert(height(method_rows) == 216 && height(diagnostics) == 72 && ...
    height(complexity) == 3);
end

function write_overall_row_local(fid, id, value)
fprintf(fid, '| %s | %d/72 | %.17g | %.17g | %.17g | %.17g | %.17g | %.17g |\n', ...
    id, value.valid_count, value.median_RMSE_deg, value.p90_RMSE_deg, ...
    value.mean_score_calls, value.mean_SVD_calls, ...
    value.median_runtime_sec, value.p90_runtime_sec);
end

function write_pair_local(fid, pair)
fprintf(fid, '| %s | %d | %d | %d |\n', char(pair.comparison_id), ...
    pair.wins, pair.ties, pair.losses);
end

function validate_inputs_local(method_rows, diagnostics, registry, constants)
if ~(istable(method_rows) && istable(diagnostics) && istable(registry) && ...
        height(registry) == constants.trial_count)
    error('stage8_k2_tp_summarize:Input', ...
        'Summary inputs do not satisfy the table contract.');
end
end

function value = median_or_nan_local(values)
values = values(isfinite(values));
if isempty(values), value = NaN; else, value = median(values); end
end

function value = percentile_or_nan_local(values, percentage)
values = sort(values(isfinite(values)));
if isempty(values)
    value = NaN;
    return;
end
position = 1 + (numel(values) - 1) * percentage / 100;
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    weight = position - lower;
    value = (1 - weight) * values(lower) + weight * values(upper);
end
end
