clc
clear
close all

script_dir = fileparts(mfilename('fullpath'));
step_dir = script_dir;
steps_dir = fileparts(step_dir);
project_dir = fileparts(steps_dir);
common_dir = fullfile(step_dir, 'common');
tests_dir = fullfile(step_dir, 'tests');
result_dir = fullfile(step_dir, 'results');

addpath(fullfile(steps_dir, 'step_12_0_receive_model_correction', 'common'));
addpath(fullfile(steps_dir, 'step_12_1_sequential_dbf_model', 'common'));
addpath(fullfile(steps_dir, 'step_12_2_stable_dml_backend', 'common'));
addpath(common_dir);
addpath(tests_dir);
addpath(fullfile(project_dir, 'core', 'config'));
addpath(fullfile(project_dir, 'core', 'array'));
if exist(result_dir, 'dir') ~= 7
    mkdir(result_dir);
end

cfg = sim_cfg();
if cfg.beam.spatialPhaseFactor ~= 1
    error('run_step12_3:ActivePhaseFactor', ...
        'Step12.3 requires the active receive spatial phase factor to be 1.');
end
el_beam_deg = [4, 6, 8, 10, 12, 14, 16, 18, 20];

validation_tic = tic;
[interface_table, interface_context] = ...
    test_elevation_group_interfaces(cfg, el_beam_deg);
[trial_table, identifiability_table, recovery_table, scenario_context] = ...
    test_elevation_group_scenarios(cfg, el_beam_deg);
scope_table = test_step12_3_scope_rules(step_dir);
[analyzer_message_count, analyzer_summary] = run_code_analyzer_local(step_dir);
validation_runtime_sec = toc(validation_tic);

trial_csv = fullfile(result_dir, 'elevation_group_trial.csv');
identifiability_csv = fullfile(result_dir, ...
    'elevation_group_identifiability.csv');
recovery_csv = fullfile(result_dir, 'group_recovery_error.csv');
keypoints_csv = fullfile(result_dir, 'elevation_group_keypoints.csv');
report_md = fullfile(result_dir, 'elevation_group_report.md');
writetable(trial_table, trial_csv);
writetable(identifiability_table, identifiability_csv);
writetable(recovery_table, recovery_csv);

main_rows = trial_table.method == "grouped_svd_dml";
element_rows = trial_table.method == "vertical_element_domain_dml";
peak_rows = trial_table.method == "elevation_beam_peak";
identifiable_rows = identifiability_table.expected_status == ...
    "GROUP_IDENTIFIABLE";
structural_row = identifiability_table.scenario == ...
    "structural_rank_ce_deficient_l1";
structural_trial_row = main_rows & trial_table.scenario == ...
    "structural_rank_ce_deficient_l1";
close_trial_row = main_rows & trial_table.scenario == ...
    "k2_q2_extremely_close_l1";
close_ident_row = identifiability_table.scenario == ...
    "k2_q2_extremely_close_l1";
correlated_trial_row = main_rows & trial_table.scenario == ...
    "k2_q2_correlated_noise_l4";
valid_recovery_rows = recovery_table.status == "GROUP_IDENTIFIABLE";

[max_primary_input_bytes, max_candidate_manifold_bytes] = ...
    memory_bounds_local(scenario_context.fixtures);
source_violation_count = sum(~scope_table.pass_flag);
all_phase_factor_one = all(trial_table.phase_factor == 1) && ...
    all(identifiability_table.phase_factor == 1) && ...
    all(recovery_table.phase_factor == 1) && ...
    all(interface_table.phase_factor == 1) && ...
    all(scope_table.phase_factor == 1);
structural_rejection_flag = identifiability_table.rank_Ce_truth(structural_row) < 2 && ...
    identifiability_table.status(structural_row) == "GROUP_UNIDENTIFIABLE" && ...
    trial_table.status(structural_trial_row) == "GROUP_UNIDENTIFIABLE" && ...
    ~trial_table.high_confidence_group_flag(structural_trial_row);

overall_pass = all(interface_table.pass_flag) && all(trial_table.pass_flag) && ...
    all(identifiability_table.pass_flag) && all(recovery_table.pass_flag) && ...
    all(scope_table.pass_flag) && analyzer_message_count == 0 && ...
    all_phase_factor_one && structural_rejection_flag && ...
    scenario_context.common_group_sum_relative_error < 5e-10 && ...
    scenario_context.max_identifiable_truth_residual < 5e-12;

metric = ["active_phase_factor"; "public_interface_gate_count"; ...
    "physical_scenario_count"; "structural_counterexample_count"; ...
    "identifiable_scenario_pass_count"; ...
    "rank_Ce_deficient_rejection_flag"; ...
    "rank_Ce_deficient_high_confidence_count"; ...
    "rank_Ce_counterexample_Nphi_gt_Q_flag"; ...
    "common_elevation_group_sum_relative_error"; ...
    "max_identifiable_truth_residual"; ...
    "extremely_close_max_abs_error_deg"; ...
    "extremely_close_sigma_ratio_Ge"; ...
    "correlated_noise_max_abs_error_deg"; ...
    "max_group_recovery_relative_fro_error"; ...
    "max_group_recovery_subspace_chordal_distance"; ...
    "max_group_recovery_offdiagonal_crosstalk"; ...
    "local_alias_violation_count"; "main_estimator_pass_count"; ...
    "vertical_element_baseline_pass_count"; ...
    "beam_peak_baseline_pass_count"; ...
    "main_search_is_local_full_reference_flag"; ...
    "ap_dml_exact_reproduction_available_flag"; ...
    "pr_dml_exact_reproduction_available_flag"; ...
    "score_calls"; "svd_calls"; "multi_start_runs"; ...
    "max_primary_input_bytes"; "max_candidate_manifold_bytes"; ...
    "peak_process_memory_profiled_flag"; ...
    "code_analyzer_message_count"; "scope_source_violation_count"; ...
    "validation_runtime_sec"; "overall_pass_flag"];
value = [1; height(interface_table); scenario_context.num_physical_scenarios; ...
    scenario_context.num_structural_counterexamples; nnz(identifiable_rows); ...
    double(structural_rejection_flag); ...
    nnz(trial_table.high_confidence_group_flag(structural_trial_row)); ...
    double(identifiability_table.Nphi_gt_Q_flag(structural_row)); ...
    scenario_context.common_group_sum_relative_error; ...
    scenario_context.max_identifiable_truth_residual; ...
    trial_table.max_abs_error_deg(close_trial_row); ...
    identifiability_table.sigma_ratio_Ge(close_ident_row); ...
    trial_table.max_abs_error_deg(correlated_trial_row); ...
    max(recovery_table.relative_fro_error(valid_recovery_rows)); ...
    max(recovery_table.subspace_chordal_distance(valid_recovery_rows)); ...
    max(recovery_table.max_offdiagonal_crosstalk(valid_recovery_rows)); ...
    nnz(identifiability_table.local_alias_flag); nnz(trial_table.pass_flag(main_rows)); ...
    nnz(trial_table.pass_flag(element_rows)); nnz(trial_table.pass_flag(peak_rows)); ...
    1; 0; 0; scenario_context.total_score_calls; ...
    scenario_context.total_svd_calls; scenario_context.total_multi_start; ...
    max_primary_input_bytes; max_candidate_manifold_bytes; 0; ...
    analyzer_message_count; source_violation_count; validation_runtime_sec; ...
    double(overall_pass)];
unit = ["dimensionless"; "count"; "count"; "count"; "count"; ...
    "boolean"; "count"; "boolean"; "relative"; "relative"; ...
    "degree"; "ratio"; "degree"; "relative"; "chordal"; ...
    "absolute_mixing"; "count"; "count"; "count"; "count"; ...
    "boolean"; "boolean"; "boolean"; "count"; "count"; "count"; ...
    "byte"; "byte"; "boolean"; "count"; "count"; "second"; "boolean"];
status = repmat("PASS", size(metric));
status(metric == "ap_dml_exact_reproduction_available_flag" | ...
    metric == "pr_dml_exact_reproduction_available_flag") = "DOCUMENTED_GAP";
status(metric == "peak_process_memory_profiled_flag") = "NOT_PROFILED";
pass_flag = [true; all(interface_table.pass_flag); ...
    scenario_context.num_physical_scenarios == 9; ...
    scenario_context.num_structural_counterexamples == 1; ...
    nnz(identifiable_rows) == 9; structural_rejection_flag; ...
    ~any(trial_table.high_confidence_group_flag(structural_trial_row)); ...
    identifiability_table.Nphi_gt_Q_flag(structural_row); ...
    scenario_context.common_group_sum_relative_error < 5e-10; ...
    scenario_context.max_identifiable_truth_residual < 5e-12; ...
    trial_table.max_abs_error_deg(close_trial_row) < 0.013; ...
    identifiability_table.sigma_ratio_Ge(close_ident_row) > 0; ...
    trial_table.max_abs_error_deg(correlated_trial_row) <= 0.21; ...
    max(recovery_table.relative_fro_error(valid_recovery_rows)) <= 0.15; ...
    max(recovery_table.subspace_chordal_distance(valid_recovery_rows)) <= 0.35; ...
    max(recovery_table.max_offdiagonal_crosstalk(valid_recovery_rows)) < 5e-9; ...
    ~any(identifiability_table.local_alias_flag); all(trial_table.pass_flag(main_rows)); ...
    all(trial_table.pass_flag(element_rows)); all(trial_table.pass_flag(peak_rows)); ...
    true; true; true; scenario_context.total_score_calls > 0; ...
    scenario_context.total_svd_calls > 0; scenario_context.total_multi_start == 0; ...
    max_primary_input_bytes > 0; max_candidate_manifold_bytes > 0; true; ...
    analyzer_message_count == 0; source_violation_count == 0; ...
    validation_runtime_sec > 0; overall_pass];
phase_factor = ones(size(value));
keypoints_table = table(metric, value, unit, status, pass_flag, phase_factor);
writetable(keypoints_table, keypoints_csv);

write_report_local(report_md, cfg, el_beam_deg, interface_table, trial_table, ...
    identifiability_table, recovery_table, scope_table, analyzer_summary, ...
    scenario_context, max_primary_input_bytes, max_candidate_manifold_bytes, ...
    validation_runtime_sec, overall_pass);

fprintf('Step12.3A-C elevation-group validation: %s\n', ...
    pass_fail_local(overall_pass));
fprintf('Physical/structural scenarios: %d/%d\n', ...
    scenario_context.num_physical_scenarios, ...
    scenario_context.num_structural_counterexamples);
fprintf('Max identifiable truth residual: %.3e\n', ...
    scenario_context.max_identifiable_truth_residual);
fprintf('Common-elevation group-sum error: %.3e\n', ...
    scenario_context.common_group_sum_relative_error);
fprintf('Score/SVD/multi-start: %d/%d/%d\n', ...
    scenario_context.total_score_calls, scenario_context.total_svd_calls, ...
    scenario_context.total_multi_start);
fprintf('Code Analyzer/source violations: %d/%d\n', ...
    analyzer_message_count, source_violation_count);
fprintf('Validation runtime: %.6f s\n', validation_runtime_sec);
fprintf('Results: %s\n', result_dir);
assert(overall_pass, 'run_step12_3:ValidationFailed', ...
    'Step12.3A-C failed at least one registered gate.');

function [message_count, summary] = run_code_analyzer_local(step_dir)
files = dir(fullfile(step_dir, '**', '*.m'));
message_count = 0;
file_with_message_count = 0;
for idx = 1:numel(files)
    messages = checkcode(fullfile(files(idx).folder, files(idx).name), '-id');
    message_count = message_count + numel(messages);
    file_with_message_count = file_with_message_count + ~isempty(messages);
    for jdx = 1:numel(messages)
        fprintf('Code Analyzer %s:%d %s %s\n', files(idx).name, ...
            messages(jdx).line, messages(jdx).id, messages(jdx).message);
    end
end
summary = struct('file_count', numel(files), ...
    'file_with_message_count', file_with_message_count, ...
    'message_count', message_count);
end

function [max_input_bytes, max_candidate_bytes] = memory_bounds_local(fixtures)
max_input_bytes = 0;
max_candidate_bytes = 0;
for idx = 1:numel(fixtures)
    fixture = fixtures{idx};
    max_input_bytes = max(max_input_bytes, 16 * numel(fixture.Zemmv));
    grid_count = numel(unique(fixture.search_grid_deg));
    if fixture.Q == 1
        candidate_count = grid_count;
    else
        candidate_count = grid_count * (grid_count - 1) / 2;
    end
    candidate_bytes = 16 * size(fixture.Zemmv, 1) * ...
        fixture.Q * candidate_count;
    max_candidate_bytes = max(max_candidate_bytes, candidate_bytes);
end
end

function write_report_local(path_out, cfg, el_beam_deg, interface_table, ...
    trial_table, identifiability_table, recovery_table, scope_table, ...
    analyzer_summary, context, max_input_bytes, max_candidate_bytes, ...
    runtime_sec, overall_pass)
fid = fopen(path_out, 'w');
if fid < 0
    error('run_step12_3:ReportOpen', 'Cannot open report: %s', path_out);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '---\nphase_factor: 1\nvalidation_status: %s\n', ...
    pass_fail_local(overall_pass));
fprintf(fid, 'scope: Step12.3_subphases_A_to_C_only\n---\n\n');
fprintf(fid, '# Step12.3A-C Elevation-Group DML Report\n\n');

fprintf(fid, '## A. Phase conclusion\n\n');
fprintf(fid, ['**%s.** Oracle-known Q=1/Q=2 elevation-group DML, structural ', ...
    'identifiability diagnosis, and group-data recovery passed the registered ', ...
    'phase-4 gates. This does not validate any later-stage estimator.\n\n'], ...
    pass_fail_local(overall_pass));

fprintf(fid, '## B. Read basis and prior-art boundary\n\n');
fprintf(fid, ['Read the phase-4 prompt in document 13, Step12.3 in document 12, ', ...
    'theory Sections 5.1-5.5 in document 11, formula prior-art F01/F02, ', ...
    'algorithm prior-art A01/A02, and the Step12.1/12.2 README/results/source.\n\n']);
fprintf(fid, ['F01/F02 and A01/A02 classify the cylindrical receive manifold, ', ...
    'concentrated DML, nuisance-coefficient absorption, and staged estimation ', ...
    'as existing or similar mechanisms. The evidence here supports only their ', ...
    'factor-1 sequential-DBF interface combination; no atomic novelty is claimed.\n\n']);

fprintf(fid, '## C. Files\n\n');
fprintf(fid, ['Added five public common modules, three private numerical helpers, ', ...
    'three interface/scenario/scope tests plus private fixtures, this README ', ...
    'and runner, and the five required result files. The v0.19 manuscript, ', ...
    'revision-scope note, and active-route README were updated only with ', ...
    'passed phase-4 facts. No frozen Step11 file or later Step12 directory ', ...
    'was modified or created.\n\n']);

fprintf(fid, '## D. Formula-to-code mapping\n\n');
write_table_header_local(fid, {'formula/contract','implementation','test evidence'});
fprintf(fid, '| `Zemmv=[Zel(:,:,1),...,Zel(:,:,L)]` | `stack_elevation_mmv_data` | mapping/order interface gates |\n');
fprintf(fid, '| `Ge=T*V''*Az(eta)` and per-radian derivative | `build_elevation_group_manifold` | fixed projection and finite difference |\n');
fprintf(fid, '| `rank(Ge)=rank(Ce)=Q` plus local uniqueness | `diagnose_elevation_group_identifiability` | 9 identifiable plus 1 structural counterexample |\n');
fprintf(fid, '| `J=norm(Ur''*Z,''fro'')^2`, `RSS=norm(Z)^2-J` | `estimate_elevation_groups_dml` using Step12.2 SVD score | Q1 1-D and Q2 local full reference |\n');
fprintf(fid, '| `Ce_hat=Ge_hat^dagger*Z` through effective SVD | `recover_group_azimuth_data` | Frobenius, vector-subspace chordal, and mixing crosstalk |\n\n');

fprintf(fid, '## E. Data and convention ledger\n\n');
fprintf(fid, '- Active spatial phase factor: `%g` (receive-only).\n', ...
    cfg.beam.spatialPhaseFactor);
fprintf(fid, '- Elevation beams: `%s` deg; physical B=%d.\n', ...
    vector_text_local(el_beam_deg), numel(el_beam_deg));
fprintf(fid, '- `Zel`: `[B_e,Nphi,L]`; `Zemmv`: `[B_e,Nphi*L]`; `Ce`: `[Q,Nphi*L]`.\n');
fprintf(fid, ['- Stacked order is azimuth column fastest and time snapshot next. ', ...
    'At L=1, circumferential columns are MMV coefficient observations, not ', ...
    'independent temporal snapshots.\n']);
fprintf(fid, ['- External angles are degrees; the manifold derivative is per ', ...
    'radian. The beam matrix, covariance, whitener, and retained coordinates ', ...
    'are fixed across every candidate.\n']);
fprintf(fid, ['- Group-data chordal error compares the one-dimensional subspaces ', ...
    'spanned by vectorized recovered and truth group matrices; it does not ', ...
    'estimate a noisy signal-subspace order.\n\n']);

fprintf(fid, '## F. Executed tests and commands\n\n');
fprintf(fid, ['Unified MATLAB command: `run(''.../step_12_3_grouped_conditional_dml/', ...
    'run_step12_3_elevation_group_validation.m'')`.\n\n']);
fprintf(fid, '- Public-interface gates: %d/%d.\n', ...
    nnz(interface_table.pass_flag), height(interface_table));
fprintf(fid, '- Trial rows: %d/%d passed.\n', ...
    nnz(trial_table.pass_flag), height(trial_table));
fprintf(fid, '- Identifiability rows: %d/%d passed.\n', ...
    nnz(identifiability_table.pass_flag), height(identifiability_table));
fprintf(fid, '- Recovery rows: %d/%d passed.\n', ...
    nnz(recovery_table.pass_flag), height(recovery_table));
fprintf(fid, '- Scope-source rules: %d/%d passed.\n', ...
    nnz(scope_table.pass_flag), height(scope_table));
fprintf(fid, '- Code Analyzer: %d files, %d messages in %d files.\n\n', ...
    analyzer_summary.file_count, analyzer_summary.message_count, ...
    analyzer_summary.file_with_message_count);

fprintf(fid, '## G. Results and key values\n\n');
structural = identifiability_table.scenario == ...
    "structural_rank_ce_deficient_l1";
close_case = identifiability_table.scenario == ...
    "k2_q2_extremely_close_l1";
main_close = trial_table.method == "grouped_svd_dml" & ...
    trial_table.scenario == "k2_q2_extremely_close_l1";
main_correlated = trial_table.method == "grouped_svd_dml" & ...
    trial_table.scenario == "k2_q2_correlated_noise_l4";
valid_recovery = recovery_table.status == "GROUP_IDENTIFIABLE";
fprintf(fid, '- Maximum identifiable noiseless truth residual: `%.6e`.\n', ...
    context.max_identifiable_truth_residual);
fprintf(fid, ['- Structural counterexample: `Nphi=%d>Q=%d`, `rank(Ge)=%d`, ', ...
    '`rank(Ce)=%d`, status `%s`, high-confidence output 0.\n'], ...
    identifiability_table.Nphi(structural), identifiability_table.oracle_Q(structural), ...
    identifiability_table.rank_Ge(structural), ...
    identifiability_table.rank_Ce_truth(structural), ...
    char(identifiability_table.status(structural)));
fprintf(fid, ['- Extremely close 10.00/10.05 deg case: sigma ratio Ge ', ...
    '`%.6e`, maximum angle error `%.6e` deg.\n'], ...
    identifiability_table.sigma_ratio_Ge(close_case), ...
    trial_table.max_abs_error_deg(main_close));
fprintf(fid, '- Correlated-noise maximum angle error: `%.6e` deg.\n', ...
    trial_table.max_abs_error_deg(main_correlated));
element_identifiable = trial_table.method == "vertical_element_domain_dml" & ...
    trial_table.expected_status == "GROUP_IDENTIFIABLE";
peak_rows = trial_table.method == "elevation_beam_peak";
fprintf(fid, ['- Vertical element-domain DML passed all %d rows; maximum ', ...
    'identifiable-case angle error was `%.6e` deg.\n'], ...
    nnz(trial_table.method == "vertical_element_domain_dml"), ...
    max(trial_table.max_abs_error_deg(element_identifiable)));
fprintf(fid, ['- The Q1 elevation-beam peak baseline passed all %d execution ', ...
    'rows; its maximum angle error was `%.6e` deg.\n'], ...
    nnz(peak_rows), max(trial_table.max_abs_error_deg(peak_rows)));
fprintf(fid, ['- The Q1/Q2 grouped SVD-DML search is the exhaustive registered ', ...
    'local full elevation-DML reference; no duplicate reference call is reported.\n']);
fprintf(fid, '- Common-elevation Q1/K2 within-group sum error: `%.6e`.\n', ...
    context.common_group_sum_relative_error);
fprintf(fid, '- Maximum accepted recovery Frobenius/chordal errors: `%.6e` / `%.6e`.\n', ...
    max(recovery_table.relative_fro_error(valid_recovery)), ...
    max(recovery_table.subspace_chordal_distance(valid_recovery)));
fprintf(fid, ['- These are deterministic registered validation cases. No Monte ', ...
    'Carlo confidence interval is reported; later resampling/calibration is ', ...
    'outside this phase.\n\n']);

fprintf(fid, '## H. Complexity\n\n');
fprintf(fid, '- Registered DML score calls: %d; registered SVD calls: %d.\n', ...
    context.total_score_calls, context.total_svd_calls);
fprintf(fid, '- Multi-start runs: %d. Validation runtime: %.6f s.\n', ...
    context.total_multi_start, runtime_sec);
fprintf(fid, ['- Q1 evaluates `Ne` candidates; Q2 evaluates `Ne*(Ne-1)/2` ', ...
    'unordered candidates. Each score uses `O(B*Q^2+rank(Ge)*B*Nphi*L)`.\n']);
fprintf(fid, '- Maximum primary input storage: %d bytes (complex double).\n', ...
    max_input_bytes);
fprintf(fid, '- Maximum stored candidate-manifold storage: %d bytes (complex double).\n', ...
    max_candidate_bytes);
fprintf(fid, '- Peak MATLAB process memory was not profiled.\n\n');

fprintf(fid, '## I. Failures, risks, and stop conditions\n\n');
fprintf(fid, ['- AP-DML and PR-DML were not run because this repository contains ', ...
    'no audited exact reproduction for the required model; no simplified ', ...
    'substitute was invented.\n']);
fprintf(fid, ['- The finite registered candidate-bank alias check is not a ', ...
    'continuous global uniqueness proof. Q is oracle-known, so these results ', ...
    'do not support automatic grouping or statistical confidence.\n']);
fprintf(fid, ['- The structural coefficient counterexample is explicitly an MMV ', ...
    'model counterexample, not presented as a complete physical target scene.\n']);
fprintf(fid, ['- Extremely close, weak, coherent, reduced-aperture, and correlated-', ...
    'noise outcomes remain visible in the CSVs; no failure-repair rule was added.\n']);
fprintf(fid, ['- This runner stops before every later subphase. No conditional ', ...
    'circumferential estimator, joint correction, beam design, or automatic ', ...
    'order selection exists here.\n\n']);

fprintf(fid, '## J. Next-stage decision\n\n');
if overall_pass
    fprintf(fid, ['Phase 4 passes its registered engineering gate. Phase 5 may ', ...
        'be started only after explicit user authorization; this run stops here.\n']);
else
    fprintf(fid, ['Phase 4 fails at least one registered gate and must not ', ...
        'advance. This run stops here.\n']);
end
clear cleanup;
end

function write_table_header_local(fid, headings)
fprintf(fid, '| %s |\n', strjoin(headings, ' | '));
fprintf(fid, '| %s |\n', strjoin(repmat({'---'}, 1, numel(headings)), ' | '));
end

function text = vector_text_local(values)
text = strtrim(sprintf('%.6g ', values));
end

function text = pass_fail_local(flag)
if flag
    text = 'PASS';
else
    text = 'FAIL';
end
end
