clc
clear
close all

script_dir = fileparts(mfilename('fullpath'));
step_dir = script_dir;
steps_dir = fileparts(step_dir);
project_dir = fileparts(steps_dir);
common_dir = fullfile(step_dir, 'common');
tests_dir = fullfile(step_dir, 'tests');
result_dir = fullfile(step_dir, 'results');

addpath(fullfile(steps_dir, 'step_12_0_receive_model_correction', 'common'));
addpath(fullfile(steps_dir, 'step_12_1_sequential_dbf_model', 'common'));
addpath(fullfile(steps_dir, 'step_12_2_stable_dml_backend', 'common'));
addpath(common_dir);
addpath(tests_dir);
addpath(fullfile(project_dir, 'core', 'config'));
addpath(fullfile(project_dir, 'core', 'array'));
if exist(result_dir, 'dir') ~= 7
    mkdir(result_dir);
end

cfg = sim_cfg();
if cfg.beam.spatialPhaseFactor ~= 1
    error('run_step12_3:ActivePhaseFactor', ...
        'Step12.3 requires receive spatial phase_factor=1.');
end
el_beam_deg = [4, 6, 8, 10, 12, 14, 16, 18, 20];

validation_tic = tic;
[interface_table, interface_context] = ...
    test_elevation_group_interfaces(cfg, el_beam_deg);
[separable_table, separable_context] = test_separable_mmv_whitening();
[kronecker_table, kronecker_context] = ...
    test_separable_vs_kronecker_whitening();
whitening_table = [separable_table; kronecker_table];
[status_table_core, status_context] = test_stage4_status_semantics();
[noisy_rank_table, noisy_rank_context] = ...
    test_noisy_rank_is_diagnostic_only();
status_table = [status_table_core; noisy_rank_table];
[trial_table, identifiability_table, recovery_table, scenario_context] = ...
    test_elevation_group_scenarios(cfg, el_beam_deg);
public_boundary_table = test_public_api_has_no_truth_dependency(step_dir);
scope_table = test_step12_3_scope_rules(step_dir);
[analyzer_message_count, analyzer_summary] = run_code_analyzer_local(step_dir);
validation_runtime_sec = toc(validation_tic);

trial_csv = fullfile(result_dir, 'elevation_group_trial.csv');
identifiability_csv = fullfile(result_dir, ...
    'elevation_group_identifiability.csv');
recovery_csv = fullfile(result_dir, 'group_recovery_error.csv');
keypoints_csv = fullfile(result_dir, 'elevation_group_keypoints.csv');
whitening_csv = fullfile(result_dir, 'separable_whitening_validation.csv');
status_csv = fullfile(result_dir, 'stage4_status_semantics.csv');
report_md = fullfile(result_dir, 'elevation_group_report.md');
revision_report_md = fullfile(result_dir, 'stage4_revision_report.md');

writetable(trial_table, trial_csv);
writetable(identifiability_table, identifiability_csv);
writetable(recovery_table, recovery_csv);
writetable(whitening_table, whitening_csv);
writetable(status_table, status_csv);

main_rows = trial_table.method == "grouped_svd_dml";
element_rows = trial_table.method == "vertical_element_domain_dml";
peak_rows = trial_table.method == "elevation_beam_peak";
structural_trial_row = main_rows & trial_table.scenario == ...
    "structural_rank_ce_deficient_l1";
structural_ident_row = identifiability_table.scenario == ...
    "structural_rank_ce_deficient_l1";
close_trial_row = main_rows & trial_table.scenario == ...
    "k2_q2_extremely_close_l1";
close_ident_row = identifiability_table.scenario == ...
    "k2_q2_extremely_close_l1";
correlated_trial_row = main_rows & trial_table.scenario == ...
    "k2_q2_correlated_noise_l4";
correlated_ident_row = identifiability_table.scenario == ...
    "k2_q2_correlated_noise_l4";
valid_recovery_rows = recovery_table.group_index > 0;
noisy_main_rows = main_rows & trial_table.observation_regime == ...
    "NOISY_UNCALIBRATED";

[max_primary_input_bytes, max_candidate_manifold_bytes, ...
    max_whitener_bytes] = memory_bounds_local(scenario_context.fixtures);
total_score_calls = scenario_context.total_score_calls + ...
    noisy_rank_context.num_score_eval + 2;
total_svd_calls = scenario_context.total_svd_calls + ...
    noisy_rank_context.num_svd + status_context.num_svd + ...
    kronecker_context.num_svd;
total_whitener_eigendecompositions = ...
    separable_context.num_eigendecompositions + ...
    kronecker_context.num_eigendecompositions + 4 + ...
    3 * scenario_context.num_physical_scenarios + 2;

structural_rejection_flag = ...
    trial_table.estimate_status(structural_trial_row) == ...
    "ESTIMATE_NOT_RUN_STRUCTURAL_RANK_FAILURE" && ...
    trial_table.support_status(structural_trial_row) == ...
    "GROUP_MMV_RANK_UNCERTIFIED" && ...
    ~trial_table.estimate_returned_flag(structural_trial_row) && ...
    identifiability_table.rank_Ce_truth(structural_ident_row) < 2;
noisy_certified_count = nnz(trial_table.registered_model_certified_flag( ...
    noisy_main_rows));
correlated_column_whitening_flag = ...
    trial_table.column_whitening_applied(correlated_trial_row) && ...
    trial_table.column_whitening_rank(correlated_trial_row) > 0;
baseline_scope_flag = all(trial_table.method_status_scope(peak_rows) == ...
    "UPSTREAM_FIXTURE_ONLY") && ...
    all(trial_table.method_certification_status(peak_rows) == ...
    "NOT_APPLICABLE_BASELINE") && ...
    all(trial_table.support_status(peak_rows) == ...
    "NOT_APPLICABLE_BASELINE") && ...
    all(~trial_table.registered_model_certified_flag(peak_rows));
all_calibration_fixed = ...
    all(trial_table.statistical_calibration_status == ...
    "NOT_CALIBRATED_STAGE4") && ...
    all(identifiability_table.statistical_calibration_status == ...
    "NOT_CALIBRATED_STAGE4") && ...
    all(recovery_table.statistical_calibration_status == ...
    "NOT_CALIBRATED_STAGE4") && ...
    all(whitening_table.statistical_calibration_status == ...
    "NOT_CALIBRATED_STAGE4") && ...
    all(status_table.statistical_calibration_status == ...
    "NOT_CALIBRATED_STAGE4");
all_phase_factor_one = all(trial_table.phase_factor == 1) && ...
    all(identifiability_table.phase_factor == 1) && ...
    all(recovery_table.phase_factor == 1) && ...
    all(whitening_table.phase_factor == 1) && ...
    all(status_table.phase_factor == 1) && ...
    all(interface_table.phase_factor == 1) && ...
    all(scope_table.phase_factor == 1) && ...
    all(public_boundary_table.phase_factor == 1);

base_pass = all(interface_table.pass_flag) && ...
    all(whitening_table.pass_flag) && all(status_table.pass_flag) && ...
    all(trial_table.pass_flag) && all(identifiability_table.pass_flag) && ...
    all(recovery_table.pass_flag) && all(scope_table.pass_flag) && ...
    all(public_boundary_table.pass_flag) && analyzer_message_count == 0 && ...
    all_phase_factor_one && all_calibration_fixed && ...
    structural_rejection_flag && noisy_certified_count == 0 && ...
    correlated_column_whitening_flag && baseline_scope_flag && ...
    scenario_context.common_group_sum_relative_error < 5e-10 && ...
    scenario_context.max_structurally_supported_truth_residual < 5e-12 && ...
    kronecker_context.data_transform_relative_error < 1e-12 && ...
    kronecker_context.score_relative_error < 1e-10 && ...
    kronecker_context.rss_relative_error < 1e-10;

keypoints_table = build_keypoints_local(base_pass, interface_table, ...
    whitening_table, status_table, trial_table, identifiability_table, ...
    recovery_table, scope_table, public_boundary_table, scenario_context, ...
    separable_context, kronecker_context, structural_rejection_flag, ...
    noisy_certified_count, correlated_column_whitening_flag, ...
    total_score_calls, total_svd_calls, total_whitener_eigendecompositions, ...
    max_primary_input_bytes, max_candidate_manifold_bytes, ...
    max_whitener_bytes, analyzer_message_count, validation_runtime_sec);
writetable(keypoints_table, keypoints_csv);

write_report_local(report_md, cfg, el_beam_deg, interface_table, ...
    whitening_table, status_table, trial_table, identifiability_table, ...
    recovery_table, scope_table, public_boundary_table, analyzer_summary, ...
    scenario_context, separable_context, kronecker_context, ...
    total_score_calls, total_svd_calls, total_whitener_eigendecompositions, ...
    max_primary_input_bytes, max_candidate_manifold_bytes, ...
    max_whitener_bytes, validation_runtime_sec, base_pass);
write_revision_report_local(revision_report_md, trial_table, ...
    identifiability_table, recovery_table, whitening_table, status_table, ...
    scenario_context, kronecker_context, analyzer_message_count, ...
    nnz(~scope_table.pass_flag) + nnz(~public_boundary_table.pass_flag), ...
    validation_runtime_sec, base_pass);

result_scope_violation_count = scan_active_outputs_local(result_dir);
overall_pass = base_pass && result_scope_violation_count == 0;
if overall_pass ~= base_pass
    keypoints_table = build_keypoints_local(overall_pass, interface_table, ...
        whitening_table, status_table, trial_table, identifiability_table, ...
        recovery_table, scope_table, public_boundary_table, scenario_context, ...
        separable_context, kronecker_context, structural_rejection_flag, ...
        noisy_certified_count, correlated_column_whitening_flag, ...
        total_score_calls, total_svd_calls, ...
        total_whitener_eigendecompositions, max_primary_input_bytes, ...
        max_candidate_manifold_bytes, max_whitener_bytes, ...
        analyzer_message_count, validation_runtime_sec);
    writetable(keypoints_table, keypoints_csv);
end

fprintf('Step12.3 phase-4 revision validation: %s\n', ...
    pass_fail_local(overall_pass));
fprintf('Physical/structural scenarios: %d/%d\n', ...
    scenario_context.num_physical_scenarios, ...
    scenario_context.num_structural_counterexamples);
fprintf('Maximum row/column whitening errors: %.3e / %.3e\n', ...
    separable_context.max_row_whitening_error, ...
    separable_context.max_column_whitening_error);
fprintf('Kronecker data/score/RSS errors: %.3e / %.3e / %.3e\n', ...
    kronecker_context.data_transform_relative_error, ...
    kronecker_context.score_relative_error, ...
    kronecker_context.rss_relative_error);
fprintf('Score/SVD/whitener eig calls: %d/%d/%d\n', ...
    total_score_calls, total_svd_calls, total_whitener_eigendecompositions);
fprintf('Code Analyzer/common-output scope violations: %d/%d\n', ...
    analyzer_message_count, nnz(~scope_table.pass_flag) + ...
    nnz(~public_boundary_table.pass_flag) + result_scope_violation_count);
fprintf('Validation runtime: %.6f s\n', validation_runtime_sec);
fprintf('Results: %s\n', result_dir);
assert(overall_pass, 'run_step12_3:ValidationFailed', ...
    'The phase-4 revision failed at least one registered gate.');

function table_out = build_keypoints_local(overall_pass, interface_table, ...
    whitening_table, status_table, trial_table, ident_table, recovery_table, ...
    scope_table, public_table, context, separable_context, kron_context, ...
    structural_rejection_flag, noisy_certified_count, ...
    correlated_column_whitening_flag, total_score_calls, total_svd_calls, ...
    total_eig_calls, max_input_bytes, max_candidate_bytes, ...
    max_whitener_bytes, analyzer_count, runtime_sec)
rows = cell(0, 1);
rows{end + 1} = keypoint_row_local('active_phase_factor', 1, ...
    'dimensionless', 'PASS', true);
rows{end + 1} = keypoint_row_local('public_interface_gate_count', ...
    height(interface_table), 'count', 'PASS', all(interface_table.pass_flag));
rows{end + 1} = keypoint_row_local('separable_whitening_case_count', ...
    height(whitening_table), 'count', 'PASS', all(whitening_table.pass_flag));
rows{end + 1} = keypoint_row_local('status_semantics_case_count', ...
    height(status_table), 'count', 'PASS', all(status_table.pass_flag));
rows{end + 1} = keypoint_row_local('physical_scenario_count', ...
    context.num_physical_scenarios, 'count', 'PASS', ...
    context.num_physical_scenarios == 9);
rows{end + 1} = keypoint_row_local('structural_counterexample_count', ...
    context.num_structural_counterexamples, 'count', 'PASS', ...
    context.num_structural_counterexamples == 1);
rows{end + 1} = keypoint_row_local('registered_certified_main_count', ...
    nnz(trial_table.support_status == "GROUP_REGISTERED_MODEL_CERTIFIED" & ...
    trial_table.method == "grouped_svd_dml"), 'count', 'PASS', true);
rows{end + 1} = keypoint_row_local('supported_uncalibrated_main_count', ...
    nnz(trial_table.support_status == ...
    "GROUP_REGISTERED_MODEL_SUPPORTED_UNCALIBRATED" & ...
    trial_table.method == "grouped_svd_dml"), 'count', 'PASS', true);
rows{end + 1} = keypoint_row_local('noisy_registered_certified_count', ...
    noisy_certified_count, 'count', 'PASS', noisy_certified_count == 0);
rows{end + 1} = keypoint_row_local('structural_rank_rejection_flag', ...
    structural_rejection_flag, 'boolean', 'PASS', structural_rejection_flag);
rows{end + 1} = keypoint_row_local('correlated_column_whitening_flag', ...
    correlated_column_whitening_flag, 'boolean', 'PASS', ...
    correlated_column_whitening_flag);
rows{end + 1} = keypoint_row_local('max_row_whitening_error', ...
    separable_context.max_row_whitening_error, 'relative', 'PASS', ...
    separable_context.max_row_whitening_error < 1e-10);
rows{end + 1} = keypoint_row_local('max_column_whitening_error', ...
    separable_context.max_column_whitening_error, 'relative', 'PASS', ...
    separable_context.max_column_whitening_error < 1e-10);
rows{end + 1} = keypoint_row_local('kronecker_data_transform_error', ...
    kron_context.data_transform_relative_error, 'relative', 'PASS', ...
    kron_context.data_transform_relative_error < 1e-12);
rows{end + 1} = keypoint_row_local('kronecker_score_error', ...
    kron_context.score_relative_error, 'relative', 'PASS', ...
    kron_context.score_relative_error < 1e-10);
rows{end + 1} = keypoint_row_local('kronecker_rss_error', ...
    kron_context.rss_relative_error, 'relative', 'PASS', ...
    kron_context.rss_relative_error < 1e-10);
rows{end + 1} = keypoint_row_local( ...
    'common_elevation_group_sum_relative_error', ...
    context.common_group_sum_relative_error, 'relative', 'PASS', ...
    context.common_group_sum_relative_error < 5e-10);
rows{end + 1} = keypoint_row_local( ...
    'max_structurally_supported_truth_residual', ...
    context.max_structurally_supported_truth_residual, 'relative', 'PASS', ...
    context.max_structurally_supported_truth_residual < 5e-12);
main_close = trial_table.method == "grouped_svd_dml" & ...
    trial_table.scenario == "k2_q2_extremely_close_l1";
ident_close = ident_table.scenario == "k2_q2_extremely_close_l1";
main_correlated = trial_table.method == "grouped_svd_dml" & ...
    trial_table.scenario == "k2_q2_correlated_noise_l4";
rows{end + 1} = keypoint_row_local('extremely_close_max_abs_error_deg', ...
    trial_table.max_abs_error_deg(main_close), 'degree', 'PASS', ...
    trial_table.max_abs_error_deg(main_close) < 0.013);
rows{end + 1} = keypoint_row_local('extremely_close_sigma_ratio_Ge', ...
    ident_table.sigma_ratio_Ge(ident_close), 'ratio', 'PASS', ...
    ident_table.sigma_ratio_Ge(ident_close) > 0);
rows{end + 1} = keypoint_row_local('correlated_noise_max_abs_error_deg', ...
    trial_table.max_abs_error_deg(main_correlated), 'degree', 'PASS', ...
    trial_table.max_abs_error_deg(main_correlated) <= 0.21);
valid_recovery = recovery_table.group_index > 0;
rows{end + 1} = keypoint_row_local( ...
    'max_group_recovery_relative_fro_error', ...
    max(recovery_table.relative_fro_error(valid_recovery)), ...
    'relative', 'PASS', all(recovery_table.pass_flag));
rows{end + 1} = keypoint_row_local( ...
    'max_group_recovery_subspace_chordal_distance', ...
    max(recovery_table.subspace_chordal_distance(valid_recovery)), ...
    'chordal', 'PASS', all(recovery_table.pass_flag));
rows{end + 1} = keypoint_row_local( ...
    'max_group_recovery_offdiagonal_crosstalk', ...
    max(recovery_table.max_offdiagonal_crosstalk(valid_recovery)), ...
    'absolute_mixing', 'PASS', all(recovery_table.pass_flag));
rows{end + 1} = keypoint_row_local('registered_alias_violation_count', ...
    nnz(ident_table.registered_bank_exact_alias_flag), 'count', 'PASS', ...
    ~any(ident_table.registered_bank_exact_alias_flag));
rows{end + 1} = keypoint_row_local('main_estimator_pass_count', ...
    nnz(trial_table.pass_flag(trial_table.method == "grouped_svd_dml")), ...
    'count', 'PASS', all(trial_table.pass_flag( ...
    trial_table.method == "grouped_svd_dml")));
rows{end + 1} = keypoint_row_local('vertical_element_baseline_pass_count', ...
    nnz(trial_table.pass_flag( ...
    trial_table.method == "vertical_element_domain_dml")), ...
    'count', 'PASS', all(trial_table.pass_flag( ...
    trial_table.method == "vertical_element_domain_dml")));
rows{end + 1} = keypoint_row_local('beam_peak_baseline_pass_count', ...
    nnz(trial_table.pass_flag(trial_table.method == "elevation_beam_peak")), ...
    'count', 'PASS', all(trial_table.pass_flag( ...
    trial_table.method == "elevation_beam_peak")));
peak_rows = trial_table.method == "elevation_beam_peak";
baseline_scope_flag = all(trial_table.method_status_scope(peak_rows) == ...
    "UPSTREAM_FIXTURE_ONLY") && ...
    all(trial_table.method_certification_status(peak_rows) == ...
    "NOT_APPLICABLE_BASELINE") && ...
    all(~trial_table.registered_model_certified_flag(peak_rows));
rows{end + 1} = keypoint_row_local('beam_peak_baseline_status_scope_flag', ...
    baseline_scope_flag, 'boolean', 'PASS', baseline_scope_flag);
rows{end + 1} = keypoint_row_local( ...
    'ap_dml_exact_reproduction_available_flag', 0, 'boolean', ...
    'DOCUMENTED_GAP', true);
rows{end + 1} = keypoint_row_local( ...
    'pr_dml_exact_reproduction_available_flag', 0, 'boolean', ...
    'DOCUMENTED_GAP', true);
rows{end + 1} = keypoint_row_local('score_calls', total_score_calls, ...
    'count', 'PASS', total_score_calls > 0);
rows{end + 1} = keypoint_row_local('svd_calls', total_svd_calls, ...
    'count', 'PASS', total_svd_calls > 0);
rows{end + 1} = keypoint_row_local('row_column_whitener_eig_calls', ...
    total_eig_calls, 'count', 'PASS', total_eig_calls > 0);
rows{end + 1} = keypoint_row_local('multi_start_runs', ...
    context.total_multi_start, 'count', 'PASS', ...
    context.total_multi_start == 0);
rows{end + 1} = keypoint_row_local('max_primary_input_bytes', ...
    max_input_bytes, 'byte', 'PASS', max_input_bytes > 0);
rows{end + 1} = keypoint_row_local('max_candidate_manifold_bytes', ...
    max_candidate_bytes, 'byte', 'PASS', max_candidate_bytes > 0);
rows{end + 1} = keypoint_row_local('max_row_column_whitener_bytes', ...
    max_whitener_bytes, 'byte', 'PASS', max_whitener_bytes > 0);
rows{end + 1} = keypoint_row_local('peak_process_memory_profiled_flag', ...
    0, 'boolean', 'NOT_PROFILED', true);
rows{end + 1} = keypoint_row_local('code_analyzer_message_count', ...
    analyzer_count, 'count', 'PASS', analyzer_count == 0);
rows{end + 1} = keypoint_row_local('scope_source_violation_count', ...
    nnz(~scope_table.pass_flag) + nnz(~public_table.pass_flag), ...
    'count', 'PASS', all(scope_table.pass_flag) && ...
    all(public_table.pass_flag));
rows{end + 1} = keypoint_row_local('validation_runtime_sec', runtime_sec, ...
    'second', 'PASS', runtime_sec > 0);
rows{end + 1} = keypoint_row_local('overall_pass_flag', overall_pass, ...
    'boolean', 'PASS', overall_pass);
table_out = struct2table(vertcat(rows{:}));
end

function row = keypoint_row_local(metric, value, unit, status, pass_flag)
row = struct();
row.metric = string(metric);
row.value = double(value);
row.unit = string(unit);
row.status = string(status);
row.estimate_status = "NOT_APPLICABLE_COMPONENT_VALIDATION";
row.support_status = "NOT_APPLICABLE_COMPONENT_VALIDATION";
row.statistical_calibration_status = "NOT_CALIBRATED_STAGE4";
row.registered_model_certified_flag = false;
row.structural_gate_pass_flag = false;
row.estimate_returned_flag = false;
row.observation_regime = "MIXED_REGISTERED_STAGE4";
row.coefficient_rank_evidence_kind = "MIXED_STAGE4_EVIDENCE";
row.row_whitening_rank = NaN;
row.column_whitening_rank = NaN;
row.column_whitening_applied = false;
row.column_covariance_model = "mixed_registered_cases";
row.truth_on_registered_grid_flag = false;
row.search_domain_source = "stage4_keypoint_aggregation";
row.pass_flag = pass_flag;
row.phase_factor = 1;
end

function [message_count, summary] = run_code_analyzer_local(step_dir)
files = dir(fullfile(step_dir, '**', '*.m'));
message_count = 0;
file_with_message_count = 0;
for idx = 1:numel(files)
    messages = checkcode(fullfile(files(idx).folder, files(idx).name), '-id');
    message_count = message_count + numel(messages);
    file_with_message_count = file_with_message_count + ~isempty(messages);
    for jdx = 1:numel(messages)
        fprintf('Code Analyzer %s:%d %s %s\n', files(idx).name, ...
            messages(jdx).line, messages(jdx).id, messages(jdx).message);
    end
end
summary = struct('file_count', numel(files), ...
    'file_with_message_count', file_with_message_count, ...
    'message_count', message_count);
end

function [max_input_bytes, max_candidate_bytes, max_whitener_bytes] = ...
    memory_bounds_local(fixtures)
max_input_bytes = 0;
max_candidate_bytes = 0;
max_whitener_bytes = 0;
for idx = 1:numel(fixtures)
    fixture = fixtures{idx};
    input_elements = numel(fixture.data.Z_score_mmv) + ...
        numel(fixture.data.Z_recovery_mmv);
    max_input_bytes = max(max_input_bytes, 16 * input_elements);
    grid_count = numel(unique(fixture.search_grid_deg));
    if fixture.Q == 1
        candidate_count = grid_count;
    else
        candidate_count = grid_count * (grid_count - 1) / 2;
    end
    candidate_bytes = 16 * fixture.data.row_whitening_rank * ...
        fixture.Q * candidate_count;
    max_candidate_bytes = max(max_candidate_bytes, candidate_bytes);
    whitener_bytes = 16 * (numel(fixture.T_row) + numel(fixture.T_col));
    max_whitener_bytes = max(max_whitener_bytes, whitener_bytes);
end
end

function count = scan_active_outputs_local(result_dir)
files = [dir(fullfile(result_dir, '*.csv')); dir(fullfile(result_dir, '*.md'))];
patterns = {'GROUP_UNIDENTIFIABLE', 'high_confidence_group_flag'};
count = 0;
for idx = 1:numel(files)
    content = fileread(fullfile(files(idx).folder, files(idx).name));
    for jdx = 1:numel(patterns)
        count = count + numel(regexp(content, patterns{jdx}, 'match'));
    end
end
end

function write_report_local(path_out, cfg, el_beam_deg, interface_table, ...
    whitening_table, status_table, trial_table, ident_table, recovery_table, ...
    scope_table, public_table, analyzer_summary, context, ...
    separable_context, kron_context, score_calls, svd_calls, eig_calls, ...
    max_input_bytes, max_candidate_bytes, max_whitener_bytes, ...
    runtime_sec, overall_pass)
fid = fopen(path_out, 'w');
if fid < 0
    error('run_step12_3:ReportOpen', 'Cannot open report: %s', path_out);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '---\nphase_factor: 1\nvalidation_status: %s\n', ...
    pass_fail_local(overall_pass));
fprintf(fid, 'scope: Step12.3_phase_4_revision_only\n---\n\n');
fprintf(fid, '# Step12.3 Elevation-Group DML Revision Report\n\n');

fprintf(fid, '## A. Phase conclusion\n\n');
fprintf(fid, ['**%s.** The oracle-Q registered elevation-group chain now ', ...
    'separates estimator execution, structural support, and statistical ', ...
    'calibration. Phase 5 remains unimplemented in this run.\n\n'], ...
    pass_fail_local(overall_pass));

fprintf(fid, '## B. Read basis and prior-art boundary\n\n');
fprintf(fid, ['The revision follows documents 06, 10, 11, 12, 13, and 14; ', ...
    'the failed adaptive-W/B record; the code manifest; the v0.19 manuscript; ', ...
    'the sequential scope note; and all Step12.2/12.3 source and results. ', ...
    'Concentrated DML, SVD projection, whitening, and nuisance-coefficient ', ...
    'elimination remain prior-art mechanisms. This revision claims interface ', ...
    'and noise-model correctness, not an atomic algorithmic novelty.\n\n']);

fprintf(fid, '## C. Public/private boundary\n\n');
fprintf(fid, ['Public code builds fixed separable whiteners, prepares score ', ...
    'and recovery coordinates, evaluates registered candidates, diagnoses ', ...
    'support, and recovers physical circumferential group data. Error and ', ...
    'mixing metrics against reference coefficients are computed only by ', ...
    '`tests/private/evaluate_group_recovery_against_truth.m`. Public boundary ', ...
    'tests passed %d/%d.\n\n'], nnz(public_table.pass_flag), ...
    height(public_table));

fprintf(fid, '## D. Formula-to-code mapping\n\n');
fprintf(fid, '| Contract | Implementation | Evidence |\n');
fprintf(fid, '| --- | --- | --- |\n');
fprintf(fid, ['| `T_row*C_row*T_row''=I` and `T_col*C_col*T_col''=I` | ', ...
    '`build_separable_mmv_whiteners` | %d whitening cases |\n'], ...
    height(whitening_table));
fprintf(fid, ['| `Z_score=T_row*Z*T_col''` | ', ...
    '`prepare_elevation_group_mmv_data` | separable/Kronecker check |\n']);
fprintf(fid, ['| `Z_recovery=T_row*Z` in physical columns | same bundle and ', ...
    '`recover_group_azimuth_data` | test-only recovery errors |\n']);
fprintf(fid, ['| execution/support/calibration split | estimator and ', ...
    'diagnostic modules | %d status cases |\n\n'], height(status_table));

fprintf(fid, '## E. Data and convention ledger\n\n');
fprintf(fid, '- Active receive spatial phase factor: `%g`.\n', ...
    cfg.beam.spatialPhaseFactor);
fprintf(fid, '- Registered elevation beams: `%s` deg.\n', ...
    vector_text_local(el_beam_deg));
fprintf(fid, ['- `Zel_raw`: `[B_phys,Nphi,L]`; `T_row`: `[r_row,B_phys]`; ', ...
    '`T_col`: `[r_col,Nphi]`.\n']);
fprintf(fid, ['- `Z_score_mmv`: `[r_row,r_col*L]`; `Z_recovery_mmv`: ', ...
    '`[r_row,Nphi*L]`; `Ge`: `[r_row,Q]`.\n']);
fprintf(fid, ['- `Ce_score`: `[Q,r_col*L]`; `Ce_recovery`: `[Q,Nphi*L]`. ', ...
    'Right whitening never enters `Ge`.\n']);
fprintf(fid, ['- External angles use degrees; derivatives use radians; ', ...
    '`phase_factor=1`. At `L=1`, circumferential columns are MMV coefficient ', ...
    'observations rather than independent temporal snapshots.\n\n']);

fprintf(fid, '## F. Executed tests\n\n');
fprintf(fid, '- Public interface: %d/%d.\n', ...
    nnz(interface_table.pass_flag), height(interface_table));
fprintf(fid, '- Whitening/Kronecker: %d/%d.\n', ...
    nnz(whitening_table.pass_flag), height(whitening_table));
fprintf(fid, '- Status semantics: %d/%d.\n', ...
    nnz(status_table.pass_flag), height(status_table));
fprintf(fid, '- Trial/diagnostic/recovery rows: %d/%d, %d/%d, %d/%d.\n', ...
    nnz(trial_table.pass_flag), height(trial_table), ...
    nnz(ident_table.pass_flag), height(ident_table), ...
    nnz(recovery_table.pass_flag), height(recovery_table));
fprintf(fid, '- Common scope rules: %d/%d.\n', ...
    nnz(scope_table.pass_flag), height(scope_table));
fprintf(fid, '- Code Analyzer: %d files, %d messages.\n\n', ...
    analyzer_summary.file_count, analyzer_summary.message_count);

fprintf(fid, '## G. Key numerical results\n\n');
main_rows = trial_table.method == "grouped_svd_dml";
structural = main_rows & trial_table.scenario == ...
    "structural_rank_ce_deficient_l1";
correlated = main_rows & trial_table.scenario == ...
    "k2_q2_correlated_noise_l4";
valid_recovery = recovery_table.group_index > 0;
fprintf(fid, '- Maximum row/column whitening errors: `%.6e` / `%.6e`.\n', ...
    separable_context.max_row_whitening_error, ...
    separable_context.max_column_whitening_error);
fprintf(fid, '- Separable/Kronecker data, score, and RSS errors: `%.6e`, `%.6e`, `%.6e`.\n', ...
    kron_context.data_transform_relative_error, ...
    kron_context.score_relative_error, kron_context.rss_relative_error);
fprintf(fid, ['- Structural counterexample: estimate `%s`, support `%s`, ', ...
    '`rank(Ce)=%d`; this rejects certification of the current registered ', ...
    'Q-group MMV recovery chain only.\n'], ...
    char(trial_table.estimate_status(structural)), ...
    char(trial_table.support_status(structural)), ...
    ident_table.rank_Ce_truth(ident_table.scenario == ...
    "structural_rank_ce_deficient_l1"));
fprintf(fid, ['- Correlated row/column case: column whitening applied `%d`, ', ...
    'angle error `%.6e` deg.\n'], ...
    trial_table.column_whitening_applied(correlated), ...
    trial_table.max_abs_error_deg(correlated));
peak_rows = trial_table.method == "elevation_beam_peak";
fprintf(fid, ['- Elevation-beam peak baseline scope: `%s`; method ', ...
    'certification: `%s`; fixture support is retained only in ', ...
    '`upstream_group_support_status`.\n'], ...
    char(trial_table.method_status_scope(find(peak_rows, 1))), ...
    char(trial_table.method_certification_status(find(peak_rows, 1))));
fprintf(fid, '- Common-elevation group-sum recovery error: `%.6e`.\n', ...
    context.common_group_sum_relative_error);
fprintf(fid, '- Maximum test-only recovery Frobenius/chordal errors: `%.6e` / `%.6e`.\n', ...
    max(recovery_table.relative_fro_error(valid_recovery)), ...
    max(recovery_table.subspace_chordal_distance(valid_recovery)));
fprintf(fid, ['- No interval, posterior, or calibrated probability is ', ...
    'reported; every active calibration state is `NOT_CALIBRATED_STAGE4`.\n\n']);

fprintf(fid, '## H. Complexity\n\n');
fprintf(fid, '- Score calls: %d; SVD calls: %d; row/column eig calls: %d.\n', ...
    score_calls, svd_calls, eig_calls);
fprintf(fid, '- Multi-start runs: %d; validation runtime: %.6f s.\n', ...
    context.total_multi_start, runtime_sec);
fprintf(fid, '- Maximum score-plus-recovery data storage: %d bytes.\n', ...
    max_input_bytes);
fprintf(fid, '- Maximum candidate-manifold storage: %d bytes.\n', ...
    max_candidate_bytes);
fprintf(fid, '- Maximum row-plus-column whitener storage: %d bytes.\n', ...
    max_whitener_bytes);
fprintf(fid, '- Peak MATLAB process memory was not measured.\n\n');

fprintf(fid, '## I. Risks and unfinished work\n\n');
fprintf(fid, ['Q remains oracle-known, the search is a registered local ', ...
    'full reference, and current reference angles are primarily grid aligned. ', ...
    'Off-grid super-resolution performance is unverified. Exact AP/PR-DML ', ...
    'reproduction remains unavailable. No statistical calibration, automatic ', ...
    'Q selection, conditional-azimuth DML, joint correction, information ', ...
    'beam design, or K=3 path is implemented.\n\n']);

fprintf(fid, '## J. Next-stage decision\n\n');
if overall_pass
    fprintf(fid, ['The phase-4 revision passes its technical gates. A later ', ...
        'phase-5 run requires separate user authorization; this run stops here.\n']);
else
    fprintf(fid, ['At least one phase-4 revision gate failed. Phase 5 is ', ...
        'not technically permitted; this run stops here.\n']);
end
clear cleanup;
end

function write_revision_report_local(path_out, trial_table, ident_table, ...
    recovery_table, whitening_table, status_table, context, kron_context, ...
    analyzer_count, scope_violation_count, runtime_sec, overall_pass)
fid = fopen(path_out, 'w');
if fid < 0
    error('run_step12_3:RevisionReportOpen', ...
        'Cannot open revision report: %s', path_out);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# Stage 4 Revision Acceptance\n\n');
fprintf(fid, '- Result: **%s**.\n', pass_fail_local(overall_pass));
fprintf(fid, '- Trial/identifiability/recovery rows: `%d/%d/%d`.\n', ...
    height(trial_table), height(ident_table), height(recovery_table));
fprintf(fid, '- Whitening/status rows: `%d/%d`.\n', ...
    height(whitening_table), height(status_table));
fprintf(fid, '- Separable/Kronecker errors (data/score/RSS): `%.6e / %.6e / %.6e`.\n', ...
    kron_context.data_transform_relative_error, ...
    kron_context.score_relative_error, kron_context.rss_relative_error);
fprintf(fid, '- Maximum structurally supported truth residual: `%.6e`.\n', ...
    context.max_structurally_supported_truth_residual);
fprintf(fid, '- Code Analyzer messages: `%d`; scope violations: `%d`.\n', ...
    analyzer_count, scope_violation_count);
fprintf(fid, '- Runtime: `%.6f s`; peak process memory: not measured.\n\n', ...
    runtime_sec);
fprintf(fid, ['The exact rank-deficient counterexample limits only the ', ...
    'registered MMV grouping/recovery certification. No general physical ', ...
    'non-identifiability theorem or statistical confidence statement follows. ', ...
    'No phase-5 module was implemented.\n']);
clear cleanup;
end

function text = vector_text_local(values)
text = strtrim(sprintf('%.6g ', values));
end

function text = pass_fail_local(flag)
if flag
    text = 'PASS';
else
    text = 'FAIL';
end
end
