function table_out = add_stage6_provenance_metadata( ...
    table_in, context, default_measurement_hash)
%ADD_STAGE6_PROVENANCE_METADATA Attach the stable CSV trace contract.

if nargin < 3, default_measurement_hash = ""; end
if ~(istable(table_in) && isstruct(context) && isscalar(context) && ...
        isfield(context, 'plan'))
    error('add_stage6_provenance_metadata:Inputs', ...
        'table_in and a scalar stage-6 context are required.');
end
plan = context.plan;
required = {'baseline_commit','baseline_ancestor_flag', ...
    'working_tree_clean_at_start','stage6_source_tree_hash', ...
    'stage6_dependency_tree_hash','stage6_controls_hash', ...
    'stage6_measurement_plan_hash','stage6_experiment_plan_hash', ...
    'stage6_provenance_hash','provenance_contract_version'};
if ~all(isfield(plan, required))
    error('add_stage6_provenance_metadata:Plan', ...
        'The plan does not implement the stage-6 provenance contract.');
end

table_out = table_in;
n = height(table_out);
if ~ismember('fixed_measurement_hash', table_out.Properties.VariableNames)
    table_out.fixed_measurement_hash = repmat( ...
        string(default_measurement_hash), n, 1);
end
table_out.baseline_commit = repmat(string(plan.baseline_commit), n, 1);
table_out.stage6_source_tree_hash = repmat( ...
    string(plan.stage6_source_tree_hash), n, 1);
table_out.stage6_dependency_tree_hash = repmat( ...
    string(plan.stage6_dependency_tree_hash), n, 1);
table_out.stage6_controls_hash = repmat( ...
    string(plan.stage6_controls_hash), n, 1);
table_out.stage6_measurement_plan_hash = repmat( ...
    string(plan.stage6_measurement_plan_hash), n, 1);
table_out.stage6_experiment_plan_hash = repmat( ...
    string(plan.stage6_experiment_plan_hash), n, 1);
table_out.stage6_provenance_hash = repmat( ...
    string(plan.stage6_provenance_hash), n, 1);
table_out.provenance_contract_version = repmat( ...
    string(plan.provenance_contract_version), n, 1);
table_out.baseline_ancestor_flag = repmat( ...
    logical(plan.baseline_ancestor_flag), n, 1);
table_out.working_tree_clean_at_start = repmat( ...
    logical(plan.working_tree_clean_at_start), n, 1);
table_out.phase_factor = ones(n, 1);
if ~ismember('theory_status', table_out.Properties.VariableNames)
    table_out.theory_status = repmat(string(context.theory_status), n, 1);
end
if ~ismember('prior_art_status', table_out.Properties.VariableNames)
    table_out.prior_art_status = repmat(string(context.prior_art_status), n, 1);
end
if ~ismember('pass_flag', table_out.Properties.VariableNames)
    table_out.pass_flag = true(n, 1);
end
end
