function registry = stage6_required_artifact_registry()
%STAGE6_REQUIRED_ARTIFACT_REGISTRY Return explicit stage-6 output contracts.

stable_csv = [ ...
    "stage6_configuration_registry"; ...
    "measurement_hash_registry"; ...
    "first_derivative_validation"; ...
    "higher_directional_derivative_validation"; ...
    "projected_metric_properties"; ...
    "tangent_eigenvalues"; ...
    "secant_tangent_nondegenerate"; ...
    "secant_tangent_tail_summary"; ...
    "secant_tangent_exact_null"; ...
    "secant_tangent_near_null"; ...
    "synthetic_null_validation"; ...
    "two_column_exact_identity"; ...
    "geometry_invariance_validation"; ...
    "column_norm_asymmetry"; ...
    "stage6_keypoints"; ...
    "stage6_source_manifest"; ...
    "stage6_dependency_manifest"; ...
    "stage6_provenance_contract"];

artifact_id = stable_csv;
relative_path = "results/" + stable_csv + ".csv";
artifact_type = repmat("CSV", numel(stable_csv), 1);
evidence_class = repmat("DETERMINISTIC_CORE", numel(stable_csv), 1);
schema_contract = repmat("STABLE_PROVENANCE_CSV", numel(stable_csv), 1);
required_by_runner = true(numel(stable_csv), 1);

[artifact_id, relative_path, artifact_type, evidence_class, ...
    schema_contract, required_by_runner] = append_local( ...
    artifact_id, relative_path, artifact_type, evidence_class, ...
    schema_contract, required_by_runner, ...
    "stage6_runtime_diagnostics", "results/stage6_runtime_diagnostics.csv", ...
    "CSV", "RUNTIME_DIAGNOSTIC", "RUNTIME_PROVENANCE_CSV", true);

markdown = ["stage6_prior_art_mapping", "stage6_theory_validation"];
for index = 1:numel(markdown)
    [artifact_id, relative_path, artifact_type, evidence_class, ...
        schema_contract, required_by_runner] = append_local( ...
        artifact_id, relative_path, artifact_type, evidence_class, ...
        schema_contract, required_by_runner, markdown(index), ...
        "results/" + markdown(index) + ".md", "MARKDOWN", ...
        "DETERMINISTIC_CORE", "NONE", true);
end

figures = [ ...
    "sigma2_ratio_vs_separation"; ...
    "coherence_ratio_vs_separation"; ...
    "normalized_gram_ratio_vs_separation"; ...
    "taylor_residual_vs_separation"; ...
    "tangent_eigenvalue_map"; ...
    "null_direction_order_fit"; ...
    "column_norm_ratio_vs_separation"];
for index = 1:numel(figures)
    [artifact_id, relative_path, artifact_type, evidence_class, ...
        schema_contract, required_by_runner] = append_local( ...
        artifact_id, relative_path, artifact_type, evidence_class, ...
        schema_contract, required_by_runner, figures(index), ...
        "figures/" + figures(index) + ".png", "PNG", ...
        "DETERMINISTIC_CORE", "NONE", true);
end

[artifact_id, relative_path, artifact_type, evidence_class, ...
    schema_contract, required_by_runner] = append_local( ...
    artifact_id, relative_path, artifact_type, evidence_class, ...
    schema_contract, required_by_runner, ...
    "stage6_reproduction_comparison", ...
    "results/stage6_reproduction_comparison.csv", "CSV", ...
    "STAGE6_1B_COMPARISON", "STAGE6_1B_COMPARISON_CSV", false);

registry = table(artifact_id, relative_path, artifact_type, evidence_class, ...
    schema_contract, required_by_runner);
if numel(unique(registry.relative_path)) ~= height(registry)
    error('stage6_required_artifact_registry:Duplicate', ...
        'Artifact relative paths must be unique.');
end
end

function [ids, paths, types, classes, schemas, required] = append_local( ...
    ids, paths, types, classes, schemas, required, ...
    id, path_now, type, class_now, schema, required_now)
ids(end + 1, 1) = id;
paths(end + 1, 1) = path_now;
types(end + 1, 1) = type;
classes(end + 1, 1) = class_now;
schemas(end + 1, 1) = schema;
required(end + 1, 1) = required_now;
end
