function registry = stage6_required_artifact_registry()
%STAGE6_REQUIRED_ARTIFACT_REGISTRY Return explicit stage-6 artifact contracts.

rows = cell(0, 1);
stable_csv = [ ...
    "stage6_configuration_registry"; ...
    "measurement_hash_registry"; ...
    "first_derivative_validation"; ...
    "higher_directional_derivative_validation"; ...
    "projected_metric_properties"; ...
    "tangent_eigenvalues"; ...
    "secant_tangent_nondegenerate"; ...
    "secant_tangent_tail_summary"; ...
    "secant_tangent_exact_null"; ...
    "secant_tangent_near_null"; ...
    "synthetic_null_validation"; ...
    "two_column_exact_identity"; ...
    "geometry_invariance_validation"; ...
    "column_norm_asymmetry"; ...
    "stage6_keypoints"; ...
    "stage6_source_manifest"; ...
    "stage6_dependency_manifest"; ...
    "stage6_provenance_contract"];
for index = 1:numel(stable_csv)
    rows{end + 1, 1} = row_local(stable_csv(index), ...
        "results/" + stable_csv(index) + ".csv", "CSV", ...
        "DETERMINISTIC_CORE", "STABLE_PROVENANCE_CSV", ...
        true, true, true, false); %#ok<AGROW>
end

rows{end + 1, 1} = row_local("stage6_runtime_diagnostics", ...
    "results/stage6_runtime_diagnostics.csv", "CSV", ...
    "RUNTIME_DIAGNOSTIC", "RUNTIME_PROVENANCE_CSV", ...
    true, true, false, false);

markdown = ["stage6_prior_art_mapping", "stage6_theory_validation"];
for index = 1:numel(markdown)
    rows{end + 1, 1} = row_local(markdown(index), ...
        "results/" + markdown(index) + ".md", "MARKDOWN", ...
        "DETERMINISTIC_CORE", "NONE", true, true, true, false); %#ok<AGROW>
end

figures = [ ...
    "sigma2_ratio_vs_separation"; ...
    "coherence_ratio_vs_separation"; ...
    "normalized_gram_ratio_vs_separation"; ...
    "taylor_residual_vs_separation"; ...
    "tangent_eigenvalue_map"; ...
    "null_direction_order_fit"; ...
    "column_norm_ratio_vs_separation"];
for index = 1:numel(figures)
    rows{end + 1, 1} = row_local(figures(index), ...
        "figures/" + figures(index) + ".png", "PNG", ...
        "FIGURE_DIAGNOSTIC", "PNG_STRUCTURE", ...
        true, true, false, false); %#ok<AGROW>
end

rows{end + 1, 1} = row_local("stage6_reproduction_comparison", ...
    "results/stage6_reproduction_comparison.csv", "CSV", ...
    "COMPARISON_EVIDENCE", "STAGE6_REPRODUCTION_COMPARISON_V1", ...
    false, true, true, false);
rows{end + 1, 1} = row_local("stage6_evidence_manifest", ...
    "results/stage6_evidence_manifest.csv", "CSV", ...
    "MANIFEST_META", "STAGE6_EVIDENCE_MANIFEST_V1", ...
    false, true, false, true);
rows{end + 1, 1} = row_local("stage6_self_reproduction_check", ...
    "results/stage6_self_reproduction_check.csv", "CSV", ...
    "SELF_REPRODUCTION_META", "STAGE6_SELF_REPRODUCTION_CHECK_V1", ...
    false, true, false, true);

registry = struct2table(vertcat(rows{:}));
registry.required_by_runner = registry.required_by_core_runner;
registry.required_by_runner_deprecated_flag = true(height(registry), 1);
validate_registry_local(registry);
end

function row = row_local(id, path_now, type, class_now, schema, ...
    core_required, final_required, bundle_included, self_excluded)
row = struct('artifact_id', string(id), ...
    'relative_path', string(path_now), ...
    'artifact_type', string(type), ...
    'evidence_class', string(class_now), ...
    'schema_contract', string(schema), ...
    'required_by_core_runner', logical(core_required), ...
    'required_by_final_freeze', logical(final_required), ...
    'included_in_deterministic_bundle', logical(bundle_included), ...
    'self_referential_exclusion_flag', logical(self_excluded));
end

function validate_registry_local(registry)
if numel(unique(registry.artifact_id)) ~= height(registry) || ...
        numel(unique(registry.relative_path)) ~= height(registry)
    error('stage6_required_artifact_registry:Duplicate', ...
        'Artifact ids and relative paths must be unique.');
end
allowed_classes = ["DETERMINISTIC_CORE"; "COMPARISON_EVIDENCE"; ...
    "RUNTIME_DIAGNOSTIC"; "FIGURE_DIAGNOSTIC"; "MANIFEST_META"; ...
    "SELF_REPRODUCTION_META"];
if ~all(ismember(registry.evidence_class, allowed_classes))
    error('stage6_required_artifact_registry:EvidenceClass', ...
        'The registry contains an unsupported evidence class.');
end
if any(registry.included_in_deterministic_bundle & ...
        ismember(registry.evidence_class, ...
        ["RUNTIME_DIAGNOSTIC", "FIGURE_DIAGNOSTIC", ...
        "MANIFEST_META", "SELF_REPRODUCTION_META"]))
    error('stage6_required_artifact_registry:BundleClass', ...
        'Runtime, figure, manifest and self-check artifacts are excluded.');
end
if any(registry.self_referential_exclusion_flag & ...
        registry.included_in_deterministic_bundle)
    error('stage6_required_artifact_registry:SelfReference', ...
        'A self-referential artifact cannot enter the deterministic bundle.');
end
end
