function table_out = test_stage6_final_freeze_registry()
%TEST_STAGE6_FINAL_FREEZE_REGISTRY Verify core/final artifact semantics.

registry = stage6_required_artifact_registry();
ids = string(registry.artifact_id);
comparison = ids == "stage6_reproduction_comparison";
runtime = registry.evidence_class == "RUNTIME_DIAGNOSTIC";
figures = registry.evidence_class == "FIGURE_DIAGNOSTIC";
manifest = ids == "stage6_evidence_manifest";
self_check = ids == "stage6_self_reproduction_check";
final_ids = ["stage6_reproduction_comparison"; ...
    "stage6_evidence_manifest"; "stage6_self_reproduction_check"];
case_id = ["UNIQUE_ARTIFACT_IDS"; "UNIQUE_RELATIVE_PATHS"; ...
    "CORE_FINAL_FLAGS_SEPARATE"; "COMPARISON_IN_BUNDLE"; ...
    "RUNTIME_EXCLUDED_FROM_BUNDLE"; "PNG_EXCLUDED_FROM_BUNDLE"; ...
    "MANIFEST_SELF_EXCLUDED"; "SELF_CHECK_SELF_EXCLUDED"; ...
    "FINAL_FREEZE_ARTIFACTS_REGISTERED"; "DEPRECATED_ALIAS_MATCHES_CORE"];
pass_flag = [ ...
    numel(unique(ids)) == height(registry); ...
    numel(unique(registry.relative_path)) == height(registry); ...
    ~registry.required_by_core_runner(comparison) && ...
    registry.required_by_final_freeze(comparison); ...
    registry.included_in_deterministic_bundle(comparison); ...
    all(~registry.included_in_deterministic_bundle(runtime)); ...
    all(~registry.included_in_deterministic_bundle(figures)); ...
    registry.self_referential_exclusion_flag(manifest) && ...
    ~registry.included_in_deterministic_bundle(manifest); ...
    registry.self_referential_exclusion_flag(self_check) && ...
    ~registry.included_in_deterministic_bundle(self_check); ...
    all(ismember(final_ids, ids)) && ...
    all(registry.required_by_final_freeze(ismember(ids, final_ids))); ...
    all(registry.required_by_runner == registry.required_by_core_runner) && ...
    all(registry.required_by_runner_deprecated_flag)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_stage6_final_freeze_registry:Failed', ...
    'The final-freeze registry contract failed.');
end
