function table_out = test_stage6_scope_rules(step_dir)
%TEST_STAGE6_SCOPE_RULES Scan the active implementation for forbidden routes.

files = [dir(fullfile(step_dir, 'common', '*.m')); ...
    dir(fullfile(step_dir, 'common', 'private', '*.m')); ...
    dir(fullfile(step_dir, 'run_step12_4_tangent_asymptotics_validation.m'))];
rules = { ...
    'phase_factor_two', 'PhaseFactor\s*[,=]\s*2|phase_factor\s*[,=]\s*2'; ...
    'fixed_ridge', '1e-10'; ...
    'gram_determinant_score', '\<det\s*\('; ...
    'legacy_c05', '\<C05\>'; ...
    'legacy_topk', '\<topK\>'; ...
    'score_gap', 'score[_-]gap'; ...
    'stage4_primary_manifold', '\<Xphi\>'; ...
    'conditional_primary_manifold', '\<Gphi\>'; ...
    'empirical_theory_constants', 'fitted_(sigma|coherence|gram)_constant'; ...
    'pass_only_filter', '\w+\s*=\s*\w+\s*\(\s*\w+\.pass_flag\s*,\s*:\s*\)'};
rows = cell(size(files, 1) * size(rules, 1), 1);
row_index = 0;
for file_index = 1:numel(files)
    text_now = fileread(fullfile(files(file_index).folder, files(file_index).name));
    for rule_index = 1:size(rules, 1)
        row_index = row_index + 1;
        hit = ~isempty(regexp(text_now, rules{rule_index, 2}, 'once'));
        rows{row_index} = struct('file', string(files(file_index).name), ...
            'rule_id', string(rules{rule_index, 1}), ...
            'violation_count', double(hit), 'pass_flag', ~hit);
    end
end
table_out = struct2table(vertcat(rows{:}));
assert(all(table_out.pass_flag), 'test_stage6_scope_rules:Violation', ...
    'The active stage-6 implementation contains a forbidden route.');
end
