function table_out = test_stage6_dependency_manifest_contract(repo_dir)
%TEST_STAGE6_DEPENDENCY_MANIFEST_CONTRACT Verify explicit tracked dependencies.

scope = collect_stage6_source_scope(repo_dir, struct());
[manifest, tree_hash] = build_git_blob_manifest(repo_dir, ...
    scope.dependency_paths, scope.dependency_scope_version, struct());
required_names = [ ...
    "build_receive_cyl_steering_vec.m"; ...
    "build_receive_cyl_steering_with_derivatives.m"; ...
    "build_sequential_beam_matrix.m"; ...
    "form_elevation_dbf_cube.m"; ...
    "form_azimuth_dbf_cube.m"; ...
    "reshape_cyl_vector_to_matrix.m"; ...
    "reshape_cyl_matrix_to_vector.m"; ...
    "derive_cyl_array_layout.m"; ...
    "build_psd_whitener.m"; "stable_numeric_rank.m"; ...
    "build_full_sequential_local_manifold.m"; "stable_matrix_rank.m"; ...
    "sim_cfg.m"; "arr_cyl.m"];
actual_names = strings(height(manifest), 1);
for index = 1:height(manifest)
    [~, name, extension] = fileparts(manifest.relative_path(index));
    actual_names(index) = name + extension;
end

case_id = ["REQUIRED_DEPENDENCIES"; "NO_DUPLICATES"; ...
    "ALL_TRACKED"; "NO_GENERATED_OUTPUTS"; "TREE_HASH_SHA256"];
pass_flag = [all(ismember(required_names, actual_names)); ...
    numel(unique(manifest.relative_path)) == height(manifest); ...
    all(strlength(manifest.git_blob_hash) >= 40); ...
    ~any(contains(manifest.relative_path, '/results/') | ...
    contains(manifest.relative_path, '/figures/')); ...
    strlength(string(tree_hash)) == 64];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_stage6_dependency_manifest_contract:Failed', ...
    'Dependency manifest contract failed.');
end
