function table_out = test_stage6_readme_stability(step_dir)
%TEST_STAGE6_README_STABILITY Ensure README is an invariant source contract.

path_now = fullfile(step_dir, 'README.md');
text_now = fileread(path_now);
lower_text = lower(text_now);
forbidden = { ...
    'old_patch_status', 'STAGE6_PROVENANCE_PATCH_IMPLEMENTED_EVIDENCE_RERUN_PENDING'; ...
    'a2_pending_status', 'STAGE6_REPRODUCTION_FINALIZERS_IMPLEMENTED_EVIDENCE_RERUN_PENDING'; ...
    'runtime_head_value', 'runtime_head_commit\s*[:=]\s*[0-9a-f]'; ...
    'specific_a2_commit', 'ac92c37'; ...
    'historical_run_state', '17c2022'; ...
    'runtime_value', 'validation_runtime_sec\s*[:=]\s*[0-9]'; ...
    'source_hash_value', 'stage6_source_tree_hash\s*[:=]\s*[0-9a-f]'; ...
    'provenance_hash_value', 'stage6_provenance_hash\s*[:=]\s*[0-9a-f]'; ...
    'bundle_hash_value', 'stage6_evidence_bundle_hash\s*[:=]\s*[0-9a-f]'; ...
    'rerun_pending', 'rerun[ _-]pending'};
case_id = strings(size(forbidden, 1) + 4, 1);
pass_flag = false(size(case_id));
for index = 1:size(forbidden, 1)
    case_id(index) = string(forbidden{index, 1});
    pass_flag(index) = isempty(regexp(text_now, forbidden{index, 2}, 'once'));
end
offset = size(forbidden, 1);
case_id(offset + (1:4)) = ["EVIDENCE_PATHS_DOCUMENTED"; ...
    "RUNTIME_ISOLATION_DOCUMENTED"; "PHASE_FACTOR_LOCKED"; ...
    "STAGE7_NOT_STARTED"];
pass_flag(offset + (1:4)) = [ ...
    contains(text_now, 'results/stage6_evidence_manifest.csv') && ...
    contains(text_now, 'results/stage6_self_reproduction_check.csv'); ...
    contains(text_now, 'results/stage6_runtime_diagnostics.csv') && ...
    contains(lower_text, 'run-specific'); ...
    contains(text_now, 'phase_factor=1'); ...
    contains(lower_text, 'not implemented here')];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_stage6_readme_stability:Failed', ...
    'The stage-6 README contains mutable run state.');
end
