function table_out = test_stage6_stable_hash_excludes_runtime_head(repo_dir)
%TEST_STAGE6_STABLE_HASH_EXCLUDES_RUNTIME_HEAD Compare two fake runtime HEADs.

inputs = plan_inputs_local();
head_a = repmat('a', 1, 40);
head_b = repmat('b', 1, 40);
contract_a = contract_local(repo_dir, inputs, head_a);
contract_b = contract_local(repo_dir, inputs, head_b);

case_id = ["RUNTIME_HEAD_CHANGED"; "CONTROLS_HASH_STABLE"; ...
    "MEASUREMENT_HASH_STABLE"; "EXPERIMENT_HASH_STABLE"; ...
    "PROVENANCE_HASH_STABLE"];
pass_flag = [~strcmp(contract_a.runtime_head_commit, ...
    contract_b.runtime_head_commit); ...
    strcmp(contract_a.stage6_controls_hash, contract_b.stage6_controls_hash); ...
    strcmp(contract_a.stage6_measurement_plan_hash, ...
    contract_b.stage6_measurement_plan_hash); ...
    strcmp(contract_a.stage6_experiment_plan_hash, ...
    contract_b.stage6_experiment_plan_hash); ...
    strcmp(contract_a.stage6_provenance_hash, ...
    contract_b.stage6_provenance_hash)];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_stage6_stable_hash_excludes_runtime_head:Failed', ...
    'A stable hash depends on runtime HEAD.');
end

function contract = contract_local(repo_dir, inputs, runtime_head)
git_options = struct( ...
    'runtime_head_commit_override', runtime_head, ...
    'baseline_ancestor_flag_override', true, ...
    'git_status_porcelain_override', '', ...
    'enforce_guards', true, 'phase_factor', 1);
contract = build_stage6_provenance_contract(repo_dir, inputs, ...
    struct('git_provenance_options', git_options));
end

function inputs = plan_inputs_local()
controls = struct( ...
    'phase_factor', 1, 'matlab_precision', 'double', ...
    'first_derivative_step_rad', 1e-6, ...
    'second_derivative_step_rad', 2e-4, ...
    'third_derivative_step_rad', 5e-4, ...
    'derivative_sensitivity_scales', [0.8, 1.25], ...
    'numeric_floor_multiplier', 4096, 'rank_multiplier', 1, ...
    'negative_eigenvalue_tolerance_multiplier', 64, ...
    'null_tolerance_multiplier', 256, 'near_null_ratio', 1e-6, ...
    'first_derivative_relative_error_gate', 1e-6, ...
    'stage5_manifold_consistency_gate', 1e-10, ...
    'second_derivative_relative_error_gate', 1e-4, ...
    'third_derivative_relative_error_gate', 1e-3, ...
    'sigma2_ratio_error_gate', 0.02, ...
    'coherence_ratio_error_gate', 0.02, ...
    'normalized_gram_ratio_error_gate', 0.05, ...
    'exact_identity_relative_error_gate', 1e-10, ...
    'exact_identity_roundoff_multiplier', 64, ...
    'invariance_relative_error_gate', 1e-10, ...
    'synthetic_null_slope_gate', 0.25, ...
    'synthetic_null_ratio_error_gate', 0.02, ...
    'theory_sigma2_constant', 0.5, 'theory_coherence_constant', 1, ...
    'theory_normalized_gram_constant', 4, ...
    'method_version_id', 'STEP12_4_TANGENT_ASYMPTOTICS_V1', ...
    'measurement_version_id', 'FIXED_SEQUENTIAL_DBFFACTOR1_V1');
config = struct('config_id', 'TEST_CONFIG', 'az_beam_deg', 8, ...
    'el_beam_deg', 10, 'az_beam_indices', 1, 'el_beam_indices', 1, ...
    'az_beam_global_indices', 2, 'el_beam_global_indices', 2, ...
    'noise_covariance_id', 'IDENTITY', 'rho_el', 0, 'rho_az', 0, ...
    'is_primary_configuration', true, 'diagnostic_role', 'PRIMARY');
direction = struct('direction_id', 'V_AZ', 'vector_rad', [1; 0]);
inputs = struct('baseline_commit', ...
    '0430f25272690a3ddf378dcf0bab465ca93edb68', ...
    'controls', controls, 'configs', config, 'centers_deg', [8, 10], ...
    'directions', direction, 'separation_deg', [0.4, 0.2], ...
    'matlab_release_contract', 'MATLAB_R2022b');
end
