function table_out = test_stage6_baseline_ancestry_contract(repo_dir)
%TEST_STAGE6_BASELINE_ANCESTRY_CONTRACT Verify ancestor, not equality, policy.

baseline = repmat('a', 1, 40);
descendant = repmat('b', 1, 40);
base_options = struct('git_status_porcelain_override', '', ...
    'enforce_guards', false, 'phase_factor', 1);

equal_options = base_options;
equal_options.runtime_head_commit_override = baseline;
equal_options.baseline_ancestor_flag_override = true;
equal_case = read_stage6_git_provenance( ...
    repo_dir, baseline, equal_options);

ancestor_options = base_options;
ancestor_options.runtime_head_commit_override = descendant;
ancestor_options.baseline_ancestor_flag_override = true;
ancestor_case = read_stage6_git_provenance( ...
    repo_dir, baseline, ancestor_options);

nonancestor_options = ancestor_options;
nonancestor_options.baseline_ancestor_flag_override = false;
nonancestor_case = read_stage6_git_provenance( ...
    repo_dir, baseline, nonancestor_options);

enforced_options = nonancestor_options;
enforced_options.enforce_guards = true;
enforced_failure = false;
try
    read_stage6_git_provenance(repo_dir, baseline, enforced_options);
catch exception
    enforced_failure = strcmp(exception.identifier, ...
        'read_stage6_git_provenance:STAGE6_BASELINE_NOT_ANCESTOR');
end

plan = build_stage6_locked_plan(repo_dir, struct( ...
    'git_provenance_options', struct( ...
    'git_status_porcelain_override', '', 'enforce_guards', true, ...
    'phase_factor', 1)));

case_id = ["BASELINE_EQUALS_HEAD"; "BASELINE_IS_ANCESTOR"; ...
    "BASELINE_NOT_ANCESTOR"; "NONANCESTOR_GUARD"; ...
    "REAL_LOCKED_PLAN_DESCENDANT"];
pass_flag = [equal_case.baseline_ancestor_flag && ...
    strcmp(equal_case.provenance_status, 'PASS'); ...
    ancestor_case.baseline_ancestor_flag && ...
    ~strcmp(ancestor_case.runtime_head_commit, baseline) && ...
    strcmp(ancestor_case.provenance_status, 'PASS'); ...
    ~nonancestor_case.baseline_ancestor_flag && ...
    strcmp(nonancestor_case.provenance_status, ...
    'STAGE6_BASELINE_NOT_ANCESTOR'); enforced_failure; ...
    plan.baseline_ancestor_flag && ...
    ~strcmp(plan.runtime_head_commit, plan.baseline_commit) && ...
    strcmp(plan.provenance_status, 'PASS')];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_stage6_baseline_ancestry_contract:Failed', ...
    'Baseline ancestry contract failed.');
end
