function table_out = test_stage6_reproduction_comparison_contract()
%TEST_STAGE6_REPRODUCTION_COMPARISON_CONTRACT Verify explicit CSV semantics.

contract = build_stage6_reproduction_comparison_contract();
expected_ids = [ ...
    "stage6_configuration_registry"; "measurement_hash_registry"; ...
    "first_derivative_validation"; ...
    "higher_directional_derivative_validation"; ...
    "projected_metric_properties"; "tangent_eigenvalues"; ...
    "secant_tangent_nondegenerate"; "secant_tangent_tail_summary"; ...
    "secant_tangent_exact_null"; "secant_tangent_near_null"; ...
    "synthetic_null_validation"; "two_column_exact_identity"; ...
    "geometry_invariance_validation"; "column_norm_asymmetry"; ...
    "stage6_keypoints"];
forbidden_ignored = ["phase_factor"; "pass_flag"; "theory_status"; ...
    "prior_art_status"; "physical_null_status"];
keys_explicit = all(cellfun(@(x) ~isempty(x), contract.key_columns));
ignored_safe = all(cellfun(@(x) ...
    ~any(ismember(forbidden_ignored, string(x))), contract.ignored_columns));
exact_protected = all(cellfun(@(x) ...
    all(ismember(["phase_factor"; "pass_flag"; "theory_status"], ...
    string(x))), contract.exact_columns));
case_id = ["FIFTEEN_HISTORICAL_CSVS"; "EXPLICIT_KEYS"; ...
    "KEYS_ARE_EXACT"; "IGNORED_COLUMNS_ARE_PROVENANCE_OR_RUNTIME"; ...
    "PROTECTED_COLUMNS_NOT_IGNORED"; "PROTECTED_COLUMNS_EXACT"; ...
    "ABSOLUTE_TOLERANCE_LOCKED"; "RELATIVE_TOLERANCE_LOCKED"; ...
    "FIXED_MEASUREMENT_HASH_EXPLICIT_CHANGE"; ...
    "TEST_COUNT_IDENTITY_CHANGE_EXPLICIT"; ...
    "KEYPOINT_COUNTS_EXACT_BY_ROW"];
keys_are_exact = true;
for index = 1:height(contract)
    keys_are_exact = keys_are_exact && all(ismember( ...
        string(contract.key_columns{index}), ...
        string(contract.exact_columns{index})));
end
allowed_ignored = [ ...
    "baseline_commit"; "stage6_source_tree_hash"; ...
    "stage6_dependency_tree_hash"; "stage6_controls_hash"; ...
    "stage6_measurement_plan_hash"; "stage6_experiment_plan_hash"; ...
    "stage6_provenance_hash"; "provenance_contract_version"; ...
    "baseline_ancestor_flag"; "working_tree_clean_at_start"; ...
    "runtime_head_commit"; "validation_runtime_sec"; ...
    "registered_experiment_runtime_sec"; "process_peak_memory"; ...
    "matlab_process_peak_memory_bytes"; "file_byte_count"; ...
    "result_data_volume_bytes"; "figure_volume_bytes"];
all_ignored = unique(vertcat(contract.ignored_columns{:}));
pass_flag = [ ...
    height(contract) == 15 && all(ismember(expected_ids, contract.artifact_id)); ...
    keys_explicit; keys_are_exact; all(ismember(all_ignored, allowed_ignored)); ...
    ignored_safe; exact_protected; ...
    all(contract.numeric_absolute_tolerance == 1e-14); ...
    all(contract.numeric_relative_tolerance == 1e-12); ...
    all(cellfun(@(x) ismember("fixed_measurement_hash", string(x)), ...
    contract.expected_identity_change_columns)); ...
    ismember("metric=registered_test_row_count", string( ...
    contract.expected_identity_change_row_keys{ ...
    contract.artifact_id == "stage6_keypoints"})); ...
    all(ismember("metric=" + ["active_phase_factor"; ...
    "registered_measurement_config_count"; "minimum_tail_point_count"; ...
    "stage5_frozen_file_count"; "step11_frozen_file_count"; ...
    "stage6_overall_pass"], string(contract.exact_value_row_keys{ ...
    contract.artifact_id == "stage6_keypoints"})))];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), ...
    'test_stage6_reproduction_comparison_contract:Failed', ...
    'The reproduction comparison contract is not fully frozen.');
end
