function table_out = test_stage6_finalizer_scope_rules(step_dir)
%TEST_STAGE6_FINALIZER_SCOPE_RULES Keep finalizers outside numerical routes.

private_names = [ ...
    "build_stage6_reproduction_comparison_contract.m"; ...
    "build_stage6_reproduction_comparison_output.m"; ...
    "compare_stage6_evidence_directories.m"; ...
    "compare_stage6_evidence_to_commit.m"; "stage6_sha256_file.m"; ...
    "build_stage6_evidence_manifest.m"; ...
    "verify_stage6_self_reproduction.m"; ...
    "capture_stage6_evidence_snapshot.m"; ...
    "write_stage6_comparison_csv.m"];
files = fullfile(step_dir, 'tests', 'private', cellstr(private_names));
files{end + 1, 1} = fullfile(step_dir, 'tests', ...
    'write_stage6_final_freeze_artifacts.m');
rules = { ...
    'physical_manifold', 'build_(fixed_whitened|stage6_fixed_measurement|receive_cyl)'; ...
    'dml_backend', '(beamspace|concentrated).*dml|svd.*dml'; ...
    'controls_mutation', '\.controls\s*='; ...
    'truth_scenario', '(truth|ground_truth|scenario_truth)'; ...
    'stage7_route', 'step_12_5|stage[_ ]?7|fim_beam'; ...
    'formal_runner', 'run_step12_4_tangent_asymptotics_validation'; ...
    'figure_write', '(exportgraphics|saveas|imwrite)\s*\('; ...
    'numeric_result_writer', '(stage6_configuration_registry|measurement_hash_registry|secant_tangent_nondegenerate)\.csv'};
rows = cell(numel(files) * size(rules, 1), 1);
row_index = 0;
for file_index = 1:numel(files)
    text_now = fileread(files{file_index});
    for rule_index = 1:size(rules, 1)
        row_index = row_index + 1;
        hit = ~isempty(regexp(text_now, rules{rule_index, 2}, 'once'));
        [~, name, extension] = fileparts(files{file_index});
        rows{row_index} = struct('file', string([name, extension]), ...
            'rule_id', string(rules{rule_index, 1}), ...
            'violation_count', double(hit), 'pass_flag', ~hit);
    end
end
table_out = struct2table(vertcat(rows{:}));
assert(all(table_out.pass_flag), ...
    'test_stage6_finalizer_scope_rules:Violation', ...
    'A finalizer crossed into numerical or stage-7 implementation.');
end
