function table_out = test_stage6_fixed_measurement_registry(context, evidence)
%TEST_STAGE6_FIXED_MEASUREMENT_REGISTRY Check all registered fixed models.

table_out = evidence.configuration_table;
assert(height(table_out) == 5 && all(table_out.pass_flag), ...
    'test_stage6_fixed_measurement_registry:Registry', ...
    'A registered fixed measurement configuration failed.');
assert(nnz(table_out.is_primary_configuration) == 4 && ...
    all(table_out.phase_factor == 1), ...
    'test_stage6_fixed_measurement_registry:PrimaryCount', ...
    'The primary configuration count or phase factor is incorrect.');
assert(all(string({context.plan.configs.config_id}).' == table_out.config_id), ...
    'test_stage6_fixed_measurement_registry:Order', ...
    'Configuration registry order changed.');
end
