function table_out = test_stage6_evidence_manifest_contract()
%TEST_STAGE6_EVIDENCE_MANIFEST_CONTRACT Verify raw-file bundle semantics.

root = tempname;
mkdir(root);
cleanup = onCleanup(@() rmdir(root, 's'));
first_dir = fullfile(root, 'first');
second_dir = fullfile(root, 'second');
snapshot_dir = fullfile(root, 'snapshot');
mkdir(first_dir);
mkdir(second_dir);
registry = registry_local();
write_fixture_local(first_dir);
copyfile(fullfile(first_dir, '*'), second_dir, 'f');
opts = struct('validation_scope', "FINAL_FREEZE", ...
    'allow_missing_self_referential_artifacts', true);
[first_manifest, first_bundle] = build_stage6_evidence_manifest( ...
    first_dir, registry, opts);
[~, reordered_bundle] = build_stage6_evidence_manifest( ...
    second_dir, registry(end:-1:1, :), opts);

write_text_local(second_dir, 'results/core.csv', 'core-changed');
[~, deterministic_bundle] = build_stage6_evidence_manifest( ...
    second_dir, registry, opts);
copyfile(fullfile(first_dir, 'results', 'core.csv'), ...
    fullfile(second_dir, 'results', 'core.csv'), 'f');
write_text_local(second_dir, 'results/runtime.csv', 'runtime-changed');
[~, runtime_bundle] = build_stage6_evidence_manifest( ...
    second_dir, registry, opts);
write_text_local(second_dir, 'figures/plot.png', 'png-changed');
[~, figure_bundle] = build_stage6_evidence_manifest( ...
    second_dir, registry, opts);
write_text_local(second_dir, 'results/comparison.csv', 'comparison-changed');
[~, comparison_bundle] = build_stage6_evidence_manifest( ...
    second_dir, registry, opts);
delete(fullfile(second_dir, 'results', 'core.csv'));
[missing_manifest, missing_bundle] = build_stage6_evidence_manifest( ...
    second_dir, registry, opts);

snapshot = capture_stage6_evidence_snapshot(first_dir, snapshot_dir, ...
    registry, struct());
inside_rejected = false;
try
    capture_stage6_evidence_snapshot(first_dir, ...
        fullfile(first_dir, 'snapshot'), registry, struct());
catch exception
    inside_rejected = strcmp(exception.identifier, ...
        'capture_stage6_evidence_snapshot:DestinationInsideStep');
end
empty_path = fullfile(root, 'empty.bin');
fid = fopen(empty_path, 'wb'); fclose(fid);
empty_hash = string(stage6_sha256_file(empty_path));
writer_result_dir = fullfile(root, 'writer', 'results');
comparison_table = comparison_table_local();
comparison_summary = comparison_summary_local();
writer_opts = opts;
writer_opts.comparison_table = comparison_table;
writer_opts.comparison_summary = comparison_summary;
[writer_manifest, writer_bundle] = build_stage6_evidence_manifest( ...
    first_dir, registry, writer_opts);
self_reproduction = table("bundle_match", "same", "same", ...
    "DETERMINISTIC_BUNDLE", true, 'VariableNames', {'check_id', ...
    'expected_value','observed_value','comparison_scope','pass_flag'});
self_summary = table(1, 0, "BUNDLE", "BUNDLE", "PASS", true, ...
    'VariableNames', {'check_count','failed_check_count', ...
    'first_bundle_hash','second_bundle_hash', ...
    'self_reproduction_status','pass_flag'});
writer_outputs = write_stage6_final_freeze_artifacts( ...
    writer_result_dir, comparison_table, comparison_summary, ...
    writer_manifest, writer_bundle, self_reproduction, ...
    struct('self_reproduction_summary', self_summary));
writer_files = structfun(@(path_now) exist(path_now, 'file') == 2, ...
    writer_outputs);
writer_entries = dir(writer_result_dir);
writer_entries = writer_entries(~[writer_entries.isdir]);
writer_manifest_output = readtable( ...
    writer_outputs.stage6_evidence_manifest, 'TextType', 'string');

case_id = ["RAW_FILE_SHA256"; "EMPTY_FILE_SHA256"; ...
    "SAME_SET_HASH_STABLE"; "REGISTRY_ORDER_INVARIANT"; ...
    "DETERMINISTIC_CHANGE_CHANGES_BUNDLE"; ...
    "RUNTIME_CHANGE_DOES_NOT_CHANGE_BUNDLE"; ...
    "PNG_CHANGE_DOES_NOT_CHANGE_BUNDLE"; ...
    "MANIFEST_SELF_EXCLUDED"; "SELF_CHECK_SELF_EXCLUDED"; ...
    "COMPARISON_INCLUDED"; "COMPARISON_CHANGE_CHANGES_BUNDLE"; ...
    "MISSING_REQUIRED_FINAL_FAILS"; "SNAPSHOT_COPIES_REGISTERED_FILES"; ...
    "SNAPSHOT_INSIDE_STEP_REJECTED"; ...
    "WRITER_WRITES_ONLY_FINAL_FREEZE_FILES"; ...
    "WRITER_COMPARISON_HASH_MATCHES_MANIFEST"; ...
    "WRITER_PERSISTS_BUNDLE_METADATA"; ...
    "IN_MEMORY_COMPARISON_ENTERS_BUNDLE"; ...
    "WRITER_HASHES_SELF_CHECK_BYTES"; ...
    "WRITER_EXCLUDES_MANIFEST_SELF_HASH"];
manifest_id = first_manifest.artifact_id;
pass_flag = [ ...
    all(strlength(first_manifest.sha256(first_manifest.file_exists_flag)) == 64); ...
    empty_hash == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"; ...
    first_bundle.stage6_evidence_bundle_hash == ...
    reordered_bundle.stage6_evidence_bundle_hash; ...
    first_bundle.stage6_evidence_bundle_hash == ...
    reordered_bundle.stage6_evidence_bundle_hash; ...
    first_bundle.stage6_evidence_bundle_hash ~= ...
    deterministic_bundle.stage6_evidence_bundle_hash; ...
    first_bundle.stage6_evidence_bundle_hash == ...
    runtime_bundle.stage6_evidence_bundle_hash; ...
    first_bundle.stage6_evidence_bundle_hash == ...
    figure_bundle.stage6_evidence_bundle_hash; ...
    ~first_manifest.included_in_deterministic_bundle( ...
    manifest_id == "stage6_evidence_manifest"); ...
    ~first_manifest.included_in_deterministic_bundle( ...
    manifest_id == "stage6_self_reproduction_check"); ...
    first_manifest.included_in_deterministic_bundle( ...
    manifest_id == "stage6_reproduction_comparison"); ...
    first_bundle.stage6_evidence_bundle_hash ~= ...
    comparison_bundle.stage6_evidence_bundle_hash; ...
    ~missing_bundle.pass_flag && any(~missing_manifest.pass_flag & ...
    missing_manifest.artifact_id == "core"); ...
    snapshot.pass_flag && snapshot.copied_artifact_count == 4 && ...
    snapshot.bundle.stage6_evidence_bundle_hash == ...
    first_bundle.stage6_evidence_bundle_hash; ...
    inside_rejected; all(writer_files) && numel(writer_entries) == 3; ...
    string(stage6_sha256_file( ...
    writer_outputs.stage6_reproduction_comparison)) == ...
    writer_manifest.sha256(writer_manifest.artifact_id == ...
    "stage6_reproduction_comparison"); ...
    all(ismember({'stage6_evidence_bundle_hash', ...
    'deterministic_artifact_count','deterministic_total_bytes', ...
    'bundle_contract_version','bundle_pass_flag'}, ...
    writer_manifest_output.Properties.VariableNames)) && ...
    all(writer_manifest_output.stage6_evidence_bundle_hash == ...
    writer_bundle.stage6_evidence_bundle_hash); ...
    writer_manifest.file_exists_flag(writer_manifest.artifact_id == ...
    "stage6_reproduction_comparison") && ...
    writer_bundle.stage6_evidence_bundle_hash ~= ...
    runtime_bundle.stage6_evidence_bundle_hash; ...
    writer_manifest_output.file_exists_flag( ...
    writer_manifest_output.artifact_id == ...
    "stage6_self_reproduction_check") && ...
    writer_manifest_output.sha256(writer_manifest_output.artifact_id == ...
    "stage6_self_reproduction_check") == string(stage6_sha256_file( ...
    writer_outputs.stage6_self_reproduction_check)); ...
    writer_manifest_output.file_exists_flag( ...
    writer_manifest_output.artifact_id == "stage6_evidence_manifest") && ...
    writer_manifest_output.sha256(writer_manifest_output.artifact_id == ...
    "stage6_evidence_manifest") == "SELF_REFERENTIAL_EXCLUSION"];
pass_flag = logical(pass_flag);
table_out = table(case_id, pass_flag);
assert(all(table_out.pass_flag), ...
    'test_stage6_evidence_manifest_contract:Failed', ...
    'The evidence manifest contract failed a synthetic case.');
end

function registry = registry_local()
artifact_id = ["core"; "stage6_runtime_diagnostics"; "plot"; ...
    "stage6_reproduction_comparison"; "stage6_evidence_manifest"; ...
    "stage6_self_reproduction_check"];
relative_path = ["results/core.csv"; "results/runtime.csv"; ...
    "figures/plot.png"; "results/comparison.csv"; ...
    "results/manifest.csv"; "results/self.csv"];
artifact_type = ["CSV"; "CSV"; "PNG"; "CSV"; "CSV"; "CSV"];
evidence_class = ["DETERMINISTIC_CORE"; "RUNTIME_DIAGNOSTIC"; ...
    "FIGURE_DIAGNOSTIC"; "COMPARISON_EVIDENCE"; "MANIFEST_META"; ...
    "SELF_REPRODUCTION_META"];
required_by_core_runner = [true; true; true; false; false; false];
required_by_final_freeze = true(6, 1);
included_in_deterministic_bundle = [true; false; false; true; false; false];
self_referential_exclusion_flag = [false; false; false; false; true; true];
registry = table(artifact_id, relative_path, artifact_type, evidence_class, ...
    required_by_core_runner, required_by_final_freeze, ...
    included_in_deterministic_bundle, self_referential_exclusion_flag);
end

function write_fixture_local(root)
write_text_local(root, 'results/core.csv', 'core');
write_text_local(root, 'results/runtime.csv', 'runtime');
write_text_local(root, 'figures/plot.png', 'png');
writetable(comparison_table_local(), ...
    fullfile(root, 'results', 'comparison.csv'));
end

function table_out = comparison_table_local()
artifact_id = "core";
relative_path = "results/core.csv";
row_key = "id=1";
column_name = "value";
comparison_kind = "EXACT";
old_value_text = "1";
new_value_text = "1";
old_numeric_value = NaN;
new_numeric_value = NaN;
absolute_difference = NaN;
relative_difference = NaN;
absolute_tolerance = 0;
relative_tolerance = 0;
expected_identity_change_flag = false;
pass_flag = true;
table_out = table(artifact_id, relative_path, row_key, column_name, ...
    comparison_kind, old_value_text, new_value_text, old_numeric_value, ...
    new_numeric_value, absolute_difference, relative_difference, ...
    absolute_tolerance, relative_tolerance, ...
    expected_identity_change_flag, pass_flag);
end

function summary = comparison_summary_local()
artifact_count = 1;
row_count_compared = 1;
numeric_value_count = 0;
exact_value_count = 1;
missing_artifact_count = 0;
row_key_mismatch_count = 0;
numeric_failure_count = 0;
exact_failure_count = 0;
maximum_absolute_difference = 0;
maximum_relative_difference = 0;
comparison_status = "PASS";
pass_flag = true;
summary = table(artifact_count, row_count_compared, numeric_value_count, ...
    exact_value_count, missing_artifact_count, row_key_mismatch_count, ...
    numeric_failure_count, exact_failure_count, ...
    maximum_absolute_difference, maximum_relative_difference, ...
    comparison_status, pass_flag);
end

function write_text_local(root, relative, text_now)
path_now = fullfile(root, relative);
parent = fileparts(path_now);
if exist(parent, 'dir') ~= 7, mkdir(parent); end
fid = fopen(path_now, 'wb');
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, unicode2native(text_now, 'UTF-8'), 'uint8');
end
