function table_out = test_stage6_clean_tree_guard()
%TEST_STAGE6_CLEAN_TREE_GUARD Verify pure porcelain classification.

case_id = ["EMPTY_CHAR"; "EMPTY_STRING"; "MODIFIED"; ...
    "UNTRACKED"; "MULTILINE"];
actual = [is_stage6_git_status_clean(''); ...
    is_stage6_git_status_clean(""); ...
    is_stage6_git_status_clean(' M tracked.m'); ...
    is_stage6_git_status_clean('?? untracked.m'); ...
    is_stage6_git_status_clean(sprintf(' M a.m\n?? b.m\n'))];
expected = [true; true; false; false; false];
pass_flag = actual == expected;
table_out = table(case_id, actual, expected, pass_flag);
assert(all(pass_flag), 'test_stage6_clean_tree_guard:Failed', ...
    'Clean-tree guard classification failed.');
end
