function table_out = test_two_column_exact_identity(~, evidence)
%TEST_TWO_COLUMN_EXACT_IDENTITY Verify the normalized two-column identity.

table_out = evidence.identity_table;
unsaturated = ~table_out.identity_numerically_saturated_flag;
assert(~isempty(table_out) && nnz(unsaturated) > 0 && ...
    all(table_out.pass_flag) && ...
    max(table_out.relative_identity_error(unsaturated)) <= 1e-10, ...
    'test_two_column_exact_identity:Failed', ...
    'The exact normalized-Gram/coherence identity failed.');
end
