function table_out = test_physical_tangent_null(~, evidence)
%TEST_PHYSICAL_TANGENT_NULL Verify honest physical-null classification.

table_out = evidence.exact_null_table;
assert(strcmp(evidence.physical_null_status, ...
    'NO_EXACT_PHYSICAL_TANGENT_NULL_FOUND') || ...
    any(table_out.null_status == "PHYSICAL_EXACT_TANGENT_NULL"), ...
    'test_physical_tangent_null:Status', ...
    'Physical tangent-null status is inconsistent.');
diagnostic = table_out(table_out.config_id == "SINGLE_CHANNEL_DIAGNOSTIC", :);
assert(height(diagnostic) == 9 && ...
    all(diagnostic.null_status == "EXACT_MEASUREMENT_COLLAPSE"), ...
    'test_physical_tangent_null:Diagnostic', ...
    'The single-channel diagnostic collapse was not preserved.');
end
