function outputs = write_stage6_final_freeze_artifacts( ...
    result_dir, comparison, comparison_summary, ...
    evidence_manifest, bundle, self_reproduction, opts)
%WRITE_STAGE6_FINAL_FREEZE_ARTIFACTS Write only three final-freeze CSVs.

if nargin < 7 || isempty(opts), opts = struct(); end
opts = normalize_options_local(opts);
validate_inputs_local(result_dir, comparison, comparison_summary, ...
    evidence_manifest, bundle, self_reproduction, opts);
if exist(result_dir, 'dir') ~= 7, mkdir(result_dir); end

manifest_columns = {'artifact_id','relative_path','artifact_type', ...
    'evidence_class','byte_count','sha256','required_by_core_runner', ...
    'required_by_final_freeze','included_in_deterministic_bundle', ...
    'self_referential_exclusion_flag','file_exists_flag','pass_flag'};
self_columns = {'check_id','expected_value','observed_value', ...
    'comparison_scope','pass_flag'};

paths = struct( ...
    'stage6_reproduction_comparison', fullfile(result_dir, ...
    'stage6_reproduction_comparison.csv'), ...
    'stage6_evidence_manifest', fullfile(result_dir, ...
    'stage6_evidence_manifest.csv'), ...
    'stage6_self_reproduction_check', fullfile(result_dir, ...
    'stage6_self_reproduction_check.csv'));
comparison_output = build_stage6_reproduction_comparison_output( ...
    comparison, comparison_summary);
write_stage6_comparison_csv(paths.stage6_reproduction_comparison, ...
    comparison_output);
verify_comparison_hash_local(paths.stage6_reproduction_comparison, ...
    evidence_manifest);
self_output = self_reproduction(:, self_columns);
self_summary = opts.self_reproduction_summary;
self_output.summary_check_count = repmat( ...
    self_summary.check_count(1), height(self_output), 1);
self_output.summary_failed_check_count = repmat( ...
    self_summary.failed_check_count(1), height(self_output), 1);
self_output.summary_first_bundle_hash = repmat( ...
    string(self_summary.first_bundle_hash(1)), height(self_output), 1);
self_output.summary_second_bundle_hash = repmat( ...
    string(self_summary.second_bundle_hash(1)), height(self_output), 1);
self_output.summary_self_reproduction_status = repmat( ...
    string(self_summary.self_reproduction_status(1)), height(self_output), 1);
self_output.summary_pass_flag = repmat( ...
    logical(self_summary.pass_flag(1)), height(self_output), 1);
writetable(self_output, ...
    paths.stage6_self_reproduction_check);
manifest_output = evidence_manifest(:, manifest_columns);
manifest_output = finalize_meta_rows_local(manifest_output, paths);
manifest_output.stage6_evidence_bundle_hash = repmat( ...
    string(bundle.stage6_evidence_bundle_hash(1)), height(manifest_output), 1);
manifest_output.deterministic_artifact_count = repmat( ...
    bundle.deterministic_artifact_count(1), height(manifest_output), 1);
manifest_output.deterministic_total_bytes = repmat( ...
    bundle.deterministic_total_bytes(1), height(manifest_output), 1);
manifest_output.excluded_runtime_artifact_count = repmat( ...
    bundle.excluded_runtime_artifact_count(1), height(manifest_output), 1);
manifest_output.excluded_figure_artifact_count = repmat( ...
    bundle.excluded_figure_artifact_count(1), height(manifest_output), 1);
manifest_output.excluded_self_referential_artifact_count = repmat( ...
    bundle.excluded_self_referential_artifact_count(1), ...
    height(manifest_output), 1);
manifest_output.bundle_contract_version = repmat( ...
    string(bundle.bundle_contract_version(1)), height(manifest_output), 1);
manifest_output.bundle_pass_flag = repmat( ...
    logical(bundle.pass_flag(1)), height(manifest_output), 1);
writetable(manifest_output, paths.stage6_evidence_manifest);
outputs = paths;
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('write_stage6_final_freeze_artifacts:Options', ...
        'opts must be a scalar struct.');
end
allowed = {'self_reproduction_summary'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('write_stage6_final_freeze_artifacts:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
if ~isfield(opts, 'self_reproduction_summary')
    opts.self_reproduction_summary = table();
end
end

function validate_inputs_local(result_dir, comparison, comparison_summary, ...
    evidence_manifest, bundle, self_reproduction, opts)
if isstring(result_dir), result_dir = char(result_dir); end
if ~(ischar(result_dir) && isrow(result_dir) && ~isempty(result_dir) && ...
        istable(comparison) && istable(comparison_summary) && ...
        istable(evidence_manifest) && istable(bundle) && ...
        istable(self_reproduction))
    error('write_stage6_final_freeze_artifacts:Inputs', ...
        'A result directory and all final-freeze tables are required.');
end
if ~table_pass_local(comparison) || ~table_pass_local(comparison_summary) || ...
        ~table_pass_local(evidence_manifest) || ~table_pass_local(bundle) || ...
        ~table_pass_local(self_reproduction) || ...
        isempty(opts.self_reproduction_summary) || ...
        ~table_pass_local(opts.self_reproduction_summary)
    error('write_stage6_final_freeze_artifacts:FailedInput', ...
        'All final-freeze inputs must pass before writing.');
end
required_self_summary = {'check_count','failed_check_count', ...
    'first_bundle_hash','second_bundle_hash','self_reproduction_status', ...
    'pass_flag'};
if height(opts.self_reproduction_summary) ~= 1 || ...
        ~all(ismember(required_self_summary, ...
        opts.self_reproduction_summary.Properties.VariableNames))
    error('write_stage6_final_freeze_artifacts:SelfSummary', ...
        'One complete self-reproduction summary row is required.');
end
forbidden_columns = ["runtime_head_commit"; "current_date"; ...
    "validation_runtime_sec"; "registered_experiment_runtime_sec"; ...
    "wall_clock_sec"];
tables = {comparison, evidence_manifest, self_reproduction};
for index = 1:numel(tables)
    if any(ismember(forbidden_columns, ...
            string(tables{index}.Properties.VariableNames)))
        error('write_stage6_final_freeze_artifacts:RuntimeColumn', ...
            'Stable final-freeze files cannot contain runtime identity.');
    end
end
end

function pass = table_pass_local(table_now)
pass = ~isempty(table_now) && ...
    ismember('pass_flag', table_now.Properties.VariableNames) && ...
    all(logical(table_now.pass_flag));
end

function verify_comparison_hash_local(comparison_path, manifest)
rows = string(manifest.artifact_id) == "stage6_reproduction_comparison";
if nnz(rows) ~= 1 || ~manifest.file_exists_flag(rows)
    error('write_stage6_final_freeze_artifacts:ComparisonManifest', ...
        'The evidence manifest must register the comparison file.');
end
digest = string(stage6_sha256_file(comparison_path));
if digest ~= string(manifest.sha256(rows))
    error('write_stage6_final_freeze_artifacts:ComparisonHash', ...
        'Written comparison bytes do not match the evidence manifest.');
end
end

function manifest = finalize_meta_rows_local(manifest, paths)
self_rows = manifest.artifact_id == "stage6_self_reproduction_check";
manifest_rows = manifest.artifact_id == "stage6_evidence_manifest";
if nnz(self_rows) ~= 1 || nnz(manifest_rows) ~= 1
    error('write_stage6_final_freeze_artifacts:MetaRows', ...
        'Manifest and self-reproduction rows must each be registered once.');
end
self_details = dir(paths.stage6_self_reproduction_check);
manifest.byte_count(self_rows) = self_details.bytes;
manifest.sha256(self_rows) = string( ...
    stage6_sha256_file(paths.stage6_self_reproduction_check));
manifest.file_exists_flag(self_rows) = true;
manifest.pass_flag(self_rows) = true;
manifest.byte_count(manifest_rows) = NaN;
manifest.sha256(manifest_rows) = "SELF_REFERENTIAL_EXCLUSION";
manifest.file_exists_flag(manifest_rows) = true;
manifest.pass_flag(manifest_rows) = true;
end
