function [thresholds, debug] = aggregate_stage8_1_calibration( ...
    cell_artifacts, calibration_plan, opts)
%AGGREGATE_STAGE8_1_CALIBRATION Require all cells before two thresholds.

path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if nargin < 3 || isempty(opts)
    opts = struct();
end
opts = normalize_options_local(opts);
artifacts = normalize_artifacts_local(cell_artifacts);
expected_count = height(calibration_plan.cells);
if opts.formal_run && expected_count ~= 300
    error('aggregate_stage8_1_calibration:FormalPlan', ...
        'Formal aggregation requires the frozen 300-cell plan.');
end
if numel(artifacts) ~= expected_count
    error('aggregate_stage8_1_calibration:IncompleteCells', ...
        'Aggregation requires all %d planned cells.', expected_count);
end
indices = [artifacts.global_cell_index].';
if ~isequal(sort(indices), (1:expected_count).') || ...
        numel(unique(string({artifacts.calibration_cell_id}))) ~= expected_count
    error('aggregate_stage8_1_calibration:CellRegistry', ...
        'Cell indices and IDs must cover the plan exactly once.');
end
if ~all(strcmp({artifacts.status}, 'CALIBRATION_CELL_PASS'))
    error('aggregate_stage8_1_calibration:CellFailure', ...
        'Every calibration cell must pass before threshold aggregation.');
end
plan_hashes = unique(string({artifacts.plan_hash}));
source_hashes = unique(string({artifacts.source_identity}));
if ~isscalar(plan_hashes) || ...
        plan_hashes ~= string(calibration_plan.calibration_plan_hash) || ...
        ~isscalar(source_hashes)
    error('aggregate_stage8_1_calibration:Identity', ...
        'All cells must share the frozen plan and source identity.');
end
if isempty(opts.expected_contract)
    if opts.formal_run
        error('aggregate_stage8_1_calibration:ThresholdContract', ...
            'Formal aggregation requires the current threshold contract.');
    end
    opts.expected_contract = struct( ...
        'stage8_stable_code_identity_hash', char(source_hashes), ...
        'stage8_plan_hash', 'UNIT_TEST_STAGE8_PLAN', ...
        'stage8_calibration_plan_hash', ...
        calibration_plan.calibration_plan_hash, ...
        'measurement_registry_hash', 'UNIT_TEST_MEASUREMENT_REGISTRY');
end
contract = validate_stage8_threshold_contract(opts.expected_contract);
if string(contract.stage8_stable_code_identity_hash) ~= source_hashes || ...
        string(contract.stage8_calibration_plan_hash) ~= plan_hashes
    error('aggregate_stage8_1_calibration:ThresholdContractIdentity', ...
        'Cell source/calibration identities do not match the threshold contract.');
end
all_seeds = zeros(0, 1);
for artifact_index = 1:numel(artifacts)
    artifact = artifacts(artifact_index);
    plan_row = calibration_plan.cells(artifact.global_cell_index, :);
    verify_plan_row_local(artifact, plan_row);
    if ~strcmp(artifact.cell_artifact_hash, ...
            stage8_calibration_artifact_hash(artifact))
        error('aggregate_stage8_1_calibration:CellArtifactHash', ...
            'Cell %s failed artifact hash verification.', ...
            artifact.calibration_cell_id);
    end
    seeds = artifact.bootstrap_seed_start + ...
        (0:numel(artifact.lambda_samples) - 1).';
    if artifact.bootstrap_seed_end ~= seeds(end) || ...
            any(~isfinite(artifact.lambda_samples))
        error('aggregate_stage8_1_calibration:CellSamples', ...
            'Cell %s has an incomplete seed or Lambda vector.', ...
            artifact.calibration_cell_id);
    end
    expected_quantile = stage8_type1_quantile( ...
        artifact.lambda_samples, 1 - opts.alpha);
    if artifact.q_cell_0p95 ~= expected_quantile
        error('aggregate_stage8_1_calibration:CellQuantile', ...
            'Cell %s q_cell does not match its Lambda samples.', ...
            artifact.calibration_cell_id);
    end
    all_seeds = [all_seeds;seeds]; %#ok<AGROW>
end
if numel(unique(all_seeds)) ~= numel(all_seeds)
    error('aggregate_stage8_1_calibration:SeedCollision', ...
        'Bootstrap seeds must be globally unique.');
end
if opts.formal_run && numel(all_seeds) ~= 59700
    error('aggregate_stage8_1_calibration:FormalSeedCount', ...
        'Formal aggregation requires all 59,700 bootstrap seeds.');
end
config_ids = unique(string({artifacts.measurement_config_id}), 'stable');
if opts.formal_run && numel(config_ids) ~= 2
    error('aggregate_stage8_1_calibration:ConfigurationCount', ...
        'Formal aggregation requires two physical configurations.');
end
thresholds = repmat(empty_threshold_local(), numel(config_ids), 1);
for config_index = 1:numel(config_ids)
    selected = string({artifacts.measurement_config_id}) == ...
        config_ids(config_index);
    selected_artifacts = artifacts(selected);
    noise_ids = unique(string({selected_artifacts.noise_profile_id}));
    if opts.formal_run && (numel(selected_artifacts) ~= 150 || ...
            numel(noise_ids) ~= 2)
        error('aggregate_stage8_1_calibration:NoiseCoverage', ...
            'Each formal threshold must aggregate 150 cells across two noises.');
    end
    q_values = [selected_artifacts.q_cell_0p95].';
    q_global = max(q_values);
    cell_table = table(string({selected_artifacts.calibration_cell_id}).', ...
        string({selected_artifacts.noise_profile_id}).', q_values, ...
        'VariableNames', {'calibration_cell_id','noise_profile_id', ...
        'q_cell_0p95'});
    calibration_hash = stage8_stable_hash( ...
        'STAGE8_1_LOCKED_THRESHOLD_V2', config_ids(config_index), ...
        opts.alpha, 'TYPE1_ORDER_STATISTIC', cell_table, ...
        string({selected_artifacts.cell_artifact_hash}).', contract);
    threshold = struct( ...
        'stage8_stable_code_identity_hash', ...
        contract.stage8_stable_code_identity_hash, ...
        'stage8_plan_hash', contract.stage8_plan_hash, ...
        'stage8_calibration_plan_hash', ...
        contract.stage8_calibration_plan_hash, ...
        'measurement_registry_hash', contract.measurement_registry_hash, ...
        'measurement_config_id', char(config_ids(config_index)), ...
        'q_global', q_global, 'alpha', opts.alpha, ...
        'Bboot_per_cell', calibration_plan.Bboot_per_cell, ...
        'cell_count', numel(selected_artifacts), ...
        'noise_profile_count', numel(noise_ids), ...
        'quantile_rule', 'TYPE1_ORDER_STATISTIC', ...
        'threshold_policy', ...
        'ONE_GLOBAL_THRESHOLD_PER_FIXED_MEASUREMENT_CONFIG', ...
        'cell_quantiles', cell_table, ...
        'calibration_hash', calibration_hash, ...
        'source_identity', contract.stage8_stable_code_identity_hash, ...
        'threshold_status', 'LOCKED_BOOTSTRAP_THRESHOLD', ...
        'threshold_artifact_hash', '', ...
        'runtime_head_in_identity_flag', false, ...
        'phase_factor', 1);
    threshold.threshold_artifact_hash = ...
        stage8_threshold_artifact_hash(threshold);
    thresholds(config_index) = threshold;
end
debug = struct('cell_count', numel(artifacts), ...
    'bootstrap_seed_count', numel(all_seeds), ...
    'unique_bootstrap_seed_count', numel(unique(all_seeds)), ...
    'configuration_count', numel(config_ids), ...
    'source_identity', char(source_hashes), ...
    'phase_factor', 1);
clear path_cleanup
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('aggregate_stage8_1_calibration:Options', ...
        'opts must be a scalar struct.');
end
allowed = {'formal_run','alpha','expected_contract'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('aggregate_stage8_1_calibration:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
if ~isfield(opts, 'formal_run'), opts.formal_run = false; end
if ~isfield(opts, 'alpha'), opts.alpha = 0.05; end
if ~isfield(opts, 'expected_contract'), opts.expected_contract = []; end
if opts.formal_run && opts.alpha ~= 0.05
    error('aggregate_stage8_1_calibration:FormalAlpha', ...
        'Formal aggregation requires alpha=0.05.');
end
end

function artifacts = normalize_artifacts_local(input)
if iscell(input)
    artifacts = vertcat(input{:});
elseif isstruct(input)
    artifacts = input(:);
else
    error('aggregate_stage8_1_calibration:Artifacts', ...
        'cell_artifacts must be a struct or cell array.');
end
required = {'measurement_config_id','noise_profile_id', ...
    'calibration_cell_id','global_cell_index','bootstrap_seed_start', ...
    'bootstrap_seed_end','lambda_samples','q_cell_0p95','source_identity', ...
    'plan_hash','model_key','model_hash','cell_input_hash', ...
    'cell_artifact_hash','status'};
if isempty(artifacts) || ~all(isfield(artifacts, required))
    error('aggregate_stage8_1_calibration:ArtifactContract', ...
        'A cell artifact is incomplete.');
end
end

function verify_plan_row_local(artifact, row)
if string(artifact.calibration_cell_id) ~= row.calibration_cell_id || ...
        string(artifact.measurement_config_id) ~= row.measurement_config_id || ...
        string(artifact.noise_profile_id) ~= row.noise_profile_id || ...
        string(artifact.model_key) ~= row.model_key || ...
        string(artifact.model_hash) ~= row.fixed_measurement_hash || ...
        artifact.data_seed ~= row.calibration_data_seed || ...
        artifact.bootstrap_seed_start ~= row.bootstrap_seed_start || ...
        artifact.bootstrap_seed_end ~= row.bootstrap_seed_end
    error('aggregate_stage8_1_calibration:PlanCellMismatch', ...
        'Cell artifact %d does not match its frozen plan row.', ...
        artifact.global_cell_index);
end
end

function threshold = empty_threshold_local()
threshold = struct('stage8_stable_code_identity_hash', '', ...
    'stage8_plan_hash', '', 'stage8_calibration_plan_hash', '', ...
    'measurement_registry_hash', '', 'measurement_config_id', '', ...
    'q_global', NaN, ...
    'alpha', 0.05, 'Bboot_per_cell', 199, 'cell_count', 0, ...
    'noise_profile_count', 0, 'quantile_rule', '', ...
    'threshold_policy', '', 'cell_quantiles', table(), ...
    'calibration_hash', '', 'source_identity', '', 'threshold_status', '', ...
    'threshold_artifact_hash', '', ...
    'runtime_head_in_identity_flag', false, ...
    'phase_factor', 1);
end
