function bundle = build_stage8_1_calibration_bundle( ...
    plan, artifacts, thresholds, checkpoint_manifest_hash)
%BUILD_STAGE8_1_CALIBRATION_BUNDLE Build calibration-only CSV payloads.

required = {'identity','calibration','measurement_model_registry', ...
    'stage8_plan_hash','stage8_calibration_plan_hash', ...
    'stage8_validation_plan_hash','stage8_holdout_plan_hash'};
if ~(isstruct(plan) && isscalar(plan) && all(isfield(plan, required)))
    error('build_stage8_1_calibration_bundle:Plan', ...
        'The frozen Stage8 plan is incomplete.');
end
if ~(isstruct(artifacts) && ~isempty(artifacts))
    error('build_stage8_1_calibration_bundle:Artifacts', ...
        'Calibration artifacts must be a nonempty struct vector.');
end
contract = build_stage8_threshold_contract(plan);
config_ids = string(plan.validation.K1.measurement_config_ids(:));
[thresholds, threshold_set_hash] = validate_stage8_locked_threshold_set( ...
    config_ids, thresholds, contract);
bundle = struct();
bundle.plan_registry = table( ...
    ["STAGE8_PLAN";"CALIBRATION_PLAN";"K1_VALIDATION_PLAN"; ...
    "HOLDOUT_PLAN"], ...
    [string(plan.stage8_plan_hash); ...
    string(plan.stage8_calibration_plan_hash); ...
    string(plan.stage8_validation_plan_hash); ...
    string(plan.stage8_holdout_plan_hash)], ...
    'VariableNames', {'artifact_id','artifact_hash'});
bundle.measurement_registry = plan.measurement_model_registry.table;
bundle.calibration_cells = plan.calibration.cells;
bundle.seed_registry = seed_registry_local(plan.calibration);
[bundle.cell_results, bundle.lambda_samples, bundle.cell_quantiles, ...
    bundle.complexity] = cell_tables_local(artifacts);
bundle.locked_thresholds = thresholds_table_local(thresholds);
bootstrap_sample_count = sum(arrayfun( ...
    @(item) numel(item.lambda_samples), artifacts));
bundle.calibration_provenance = table( ...
    string(contract.stage8_stable_code_identity_hash), ...
    string(contract.stage8_plan_hash), ...
    string(contract.stage8_calibration_plan_hash), ...
    string(plan.stage8_validation_plan_hash), ...
    string(contract.measurement_registry_hash), ...
    string(threshold_set_hash), string(checkpoint_manifest_hash), ...
    numel(artifacts), bootstrap_sample_count, ...
    "PASS_STAGE8_1_THRESHOLD_EVIDENCE_FREEZE", ...
    'VariableNames', {'stage8_stable_code_identity_hash', ...
    'stage8_plan_hash','stage8_calibration_plan_hash', ...
    'stage8_validation_plan_hash','measurement_registry_hash', ...
    'threshold_set_hash','checkpoint_manifest_hash','cell_count', ...
    'bootstrap_sample_count','calibration_freeze_status'});
bundle.source_manifest = plan.identity.source_manifest;
runtime = sum(arrayfun(@runtime_local, artifacts));
bundle.runtime_diagnostics = table(runtime, ...
    'VariableNames', {'calibration_cell_runtime_sec'});
end

function table_out = seed_registry_local(calibration)
cells = calibration.cells;
Bboot = calibration.Bboot_per_cell;
bootstrap_seeds = reshape((cells.bootstrap_seed_start + ...
    (0:Bboot - 1)).', [], 1);
bootstrap_ids = repelem(cells.calibration_cell_id(:), Bboot, 1);
table_out = table( ...
    [repmat("CALIBRATION_DATA", height(cells), 1); ...
    repmat("CALIBRATION_BOOTSTRAP", numel(bootstrap_seeds), 1)], ...
    [cells.calibration_data_seed;bootstrap_seeds], ...
    [cells.calibration_cell_id(:);bootstrap_ids], ...
    'VariableNames', {'seed_role','seed','registry_id'});
end

function [results, lambda, quantiles, complexity] = ...
    cell_tables_local(artifacts)
results = table(string({artifacts.calibration_cell_id}).', ...
    [artifacts.global_cell_index].', string({artifacts.status}).', ...
    [artifacts.q_cell_0p95].', [artifacts.failure_count].', ...
    string({artifacts.cell_artifact_hash}).', ...
    'VariableNames', {'calibration_cell_id','global_cell_index', ...
    'status','q_cell_0p95','failure_count','cell_artifact_hash'});
total = sum(arrayfun(@(item) numel(item.lambda_samples), artifacts));
cell_id = strings(total, 1);
bootstrap_index = zeros(total, 1);
bootstrap_seed = zeros(total, 1);
lambda_12 = zeros(total, 1);
row_index = 0;
for artifact_index = 1:numel(artifacts)
    count = numel(artifacts(artifact_index).lambda_samples);
    rows = row_index + (1:count);
    cell_id(rows) = string(artifacts(artifact_index).calibration_cell_id);
    bootstrap_index(rows) = (1:count).';
    bootstrap_seed(rows) = artifacts(artifact_index).bootstrap_seed_start + ...
        (0:count - 1).';
    lambda_12(rows) = artifacts(artifact_index).lambda_samples(:);
    row_index = row_index + count;
end
lambda = table(cell_id, bootstrap_index, bootstrap_seed, lambda_12);
quantiles = table(string({artifacts.calibration_cell_id}).', ...
    string({artifacts.measurement_config_id}).', ...
    string({artifacts.noise_profile_id}).', ...
    [artifacts.q_cell_0p95].', ...
    string({artifacts.cell_artifact_hash}).', ...
    'VariableNames', {'calibration_cell_id','measurement_config_id', ...
    'noise_profile_id','q_cell_0p95','cell_artifact_hash'});
complexity = table(string({artifacts.calibration_cell_id}).', ...
    arrayfun(@(item) field_or_zero_local(item, 'K1_fit_count'), artifacts), ...
    arrayfun(@(item) field_or_zero_local(item, 'K2_fit_count'), artifacts), ...
    arrayfun(@(item) field_or_zero_local(item, 'score_call_count'), artifacts), ...
    arrayfun(@(item) field_or_zero_local(item, 'svd_call_count'), artifacts), ...
    'VariableNames', {'calibration_cell_id','K1_fit_count', ...
    'K2_fit_count','score_call_count','svd_call_count'});
end

function table_out = thresholds_table_local(thresholds)
excluded = intersect(fieldnames(thresholds), ...
    {'runtime_head_in_identity_flag','phase_factor'});
if ~isempty(excluded), thresholds = rmfield(thresholds, excluded); end
table_out = struct2table(thresholds);
preferred = {'stage8_stable_code_identity_hash','stage8_plan_hash', ...
    'stage8_calibration_plan_hash','measurement_registry_hash', ...
    'measurement_config_id','q_global','q_global_hex','alpha','alpha_hex', ...
    'Bboot_per_cell','cell_count','noise_profile_count','quantile_rule', ...
    'threshold_policy','calibration_hash','source_identity', ...
    'threshold_status','threshold_contract_version', ...
    'threshold_artifact_hash'};
table_out = table_out(:, preferred);
end

function value = field_or_zero_local(item, field)
value = 0;
if isfield(item, field), value = item.(field); end
end

function value = runtime_local(item)
value = 0;
if isfield(item, 'runtime'), value = item.runtime; end
end
