function [artifacts, manifest] = collect_stage8_1_cell_artifacts( ...
    checkpoint_root, calibration_plan, expected_contract)
%COLLECT_STAGE8_1_CELL_ARTIFACTS Collect one valid checkpoint per plan cell.

path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
required_plan = {'cells','calibration_plan_hash'};
if ~(isstruct(calibration_plan) && isscalar(calibration_plan) && ...
        all(isfield(calibration_plan, required_plan)))
    error('collect_stage8_1_cell_artifacts:Plan', ...
        'calibration_plan is incomplete.');
end
expected_contract = validate_stage8_threshold_contract(expected_contract);
if ~strcmp(string(calibration_plan.calibration_plan_hash), ...
        string(expected_contract.stage8_calibration_plan_hash))
    error('collect_stage8_1_cell_artifacts:PlanIdentity', ...
        'The calibration plan does not match the expected contract.');
end
[manifest, artifact_cells] = ...
    load_stage8_1_checkpoint_manifest(checkpoint_root);
expected_count = height(calibration_plan.cells);
if numel(unique(manifest.global_cell_index)) ~= height(manifest) || ...
        numel(unique(manifest.calibration_cell_id)) ~= height(manifest)
    error('collect_stage8_1_cell_artifacts:DuplicateCheckpoint', ...
        'Each calibration cell must have exactly one checkpoint.');
end
if height(manifest) ~= expected_count || ...
        ~isequal(sort(manifest.global_cell_index), (1:expected_count).')
    error('collect_stage8_1_cell_artifacts:MissingCheckpoint', ...
        'All %d calibration cell checkpoints are required.', expected_count);
end
[~, order] = sort(manifest.global_cell_index);
manifest = manifest(order, :);
artifact_cells = artifact_cells(order);
for cell_index = 1:expected_count
    artifact = artifact_cells{cell_index};
    row = calibration_plan.cells(cell_index, :);
    expected_cell_hash = stage8_calibration_cell_input_hash( ...
        row, expected_contract.stage8_stable_code_identity_hash, ...
        expected_contract.stage8_calibration_plan_hash);
    if ~manifest.artifact_hash_match(cell_index)
        error('collect_stage8_1_cell_artifacts:ArtifactHashMismatch', ...
            'Checkpoint %d failed its artifact hash.', cell_index);
    end
    if manifest.source_identity(cell_index) ~= ...
            string(expected_contract.stage8_stable_code_identity_hash) || ...
            manifest.plan_hash(cell_index) ~= ...
            string(expected_contract.stage8_calibration_plan_hash) || ...
            manifest.model_hash(cell_index) ~= row.fixed_measurement_hash || ...
            manifest.cell_input_hash(cell_index) ~= string(expected_cell_hash) || ...
            manifest.calibration_cell_id(cell_index) ~= ...
            row.calibration_cell_id || ...
            manifest.status(cell_index) ~= "CALIBRATION_CELL_PASS"
        error('collect_stage8_1_cell_artifacts:CheckpointIdentityMismatch', ...
            'Checkpoint %d does not match source/plan/model/cell identity.', ...
            cell_index);
    end
    artifact_cells{cell_index} = artifact;
end
artifacts = vertcat(artifact_cells{:});
clear path_cleanup
end
