function [thresholds, evidence] = load_stage8_1_locked_thresholds( ...
    repo_dir, calibration_root, frozen_plan, opts)
%LOAD_STAGE8_1_LOCKED_THRESHOLDS Load committed lossless thresholds.

path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if nargin < 4 || isempty(opts), opts = struct(); end
opts = normalize_options_local(opts);
artifact_root = artifact_root_local(calibration_root);
registry = stage8_1_calibration_artifact_registry();
if opts.require_tracked_artifacts
    verify_clean_tracked_local(repo_dir, artifact_root, registry);
end
manifest_path = fullfile(artifact_root, char(registry.table.relative_path( ...
    registry.table.manifest_self_excluded_flag)));
if ~isfile(manifest_path)
    error('load_stage8_1_locked_thresholds:ManifestMissing', ...
        'The calibration evidence manifest is missing.');
end
committed_manifest = readtable(manifest_path, 'TextType', 'string');
[computed_manifest, bundle_hash] = build_stage8_1_evidence_manifest( ...
    artifact_root, registry);
verify_manifest_local(committed_manifest, computed_manifest, bundle_hash);
contract = build_stage8_threshold_contract(frozen_plan);
threshold_path = fullfile(artifact_root, 'calibration', ...
    'stage8_1_locked_thresholds.csv');
import_options = detectImportOptions(threshold_path, 'TextType', 'string');
hex_fields = intersect({'q_global_hex','alpha_hex'}, ...
    import_options.VariableNames);
import_options = setvartype(import_options, hex_fields, 'string');
threshold_table = readtable(threshold_path, import_options);
threshold_artifacts = table2struct(threshold_table);
config_ids = string(frozen_plan.validation.K1.measurement_config_ids(:));
[thresholds, threshold_set_hash] = validate_stage8_locked_threshold_set( ...
    config_ids, threshold_artifacts, contract);
provenance_path = fullfile(artifact_root, 'calibration', ...
    'stage8_1_provenance.csv');
provenance = readtable(provenance_path, 'TextType', 'string');
verify_provenance_local(provenance, frozen_plan, contract, ...
    threshold_set_hash, bundle_hash);
evidence = struct('repo_dir', repo_dir, 'artifact_root', artifact_root, ...
    'manifest', committed_manifest, ...
    'calibration_evidence_bundle_hash', bundle_hash, ...
    'threshold_set_hash', threshold_set_hash, ...
    'locked_thresholds', thresholds, 'provenance', provenance, ...
    'stage8_stable_code_identity_hash', ...
    contract.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', contract.stage8_plan_hash, ...
    'stage8_calibration_plan_hash', ...
    contract.stage8_calibration_plan_hash, ...
    'measurement_registry_hash', contract.measurement_registry_hash, ...
    'calibration_freeze_status', ...
    'PASS_STAGE8_1_THRESHOLD_EVIDENCE_FREEZE');
clear path_cleanup
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('load_stage8_1_locked_thresholds:Options', ...
        'opts must be a scalar struct.');
end
allowed = {'formal_run','require_tracked_artifacts'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('load_stage8_1_locked_thresholds:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
if ~isfield(opts, 'formal_run'), opts.formal_run = true; end
if ~isfield(opts, 'require_tracked_artifacts')
    opts.require_tracked_artifacts = opts.formal_run;
end
end

function root = artifact_root_local(input_root)
root = char(string(input_root));
if isfile(fullfile(root, 'stage8_1_calibration_evidence_manifest.csv'))
    root = fileparts(root);
end
end

function verify_manifest_local(committed, computed, bundle_hash)
required = {'artifact_id','relative_path','sha256','byte_count', ...
    'calibration_evidence_bundle_hash'};
if ~all(ismember(required, committed.Properties.VariableNames)) || ...
        height(committed) ~= height(computed)
    error('load_stage8_1_locked_thresholds:ManifestContract', ...
        'The committed calibration manifest is incomplete.');
end
committed = sortrows(committed, 'artifact_id');
computed = sortrows(computed, 'artifact_id');
same = isequal(string(committed.artifact_id), string(computed.artifact_id)) && ...
    isequal(string(committed.relative_path), string(computed.relative_path)) && ...
    isequal(string(committed.sha256), string(computed.sha256)) && ...
    isequal(double(committed.byte_count), double(computed.byte_count));
declared = unique(string(committed.calibration_evidence_bundle_hash));
if ~same || ~isscalar(declared) || declared ~= string(bundle_hash)
    error('load_stage8_1_locked_thresholds:ManifestMismatch', ...
        'Calibration artifacts do not match the committed manifest.');
end
end

function verify_provenance_local(provenance, plan, contract, set_hash, bundle_hash)
required = {'stage8_stable_code_identity_hash','stage8_plan_hash', ...
    'stage8_calibration_plan_hash','stage8_validation_plan_hash', ...
    'measurement_registry_hash','threshold_set_hash', ...
    'calibration_freeze_status'};
if height(provenance) ~= 1 || ...
        ~all(ismember(required, provenance.Properties.VariableNames))
    error('load_stage8_1_locked_thresholds:ProvenanceContract', ...
        'Calibration provenance is incomplete.');
end
actual = [string(provenance.stage8_stable_code_identity_hash), ...
    string(provenance.stage8_plan_hash), ...
    string(provenance.stage8_calibration_plan_hash), ...
    string(provenance.stage8_validation_plan_hash), ...
    string(provenance.measurement_registry_hash), ...
    string(provenance.threshold_set_hash)];
expected = [string(contract.stage8_stable_code_identity_hash), ...
    string(contract.stage8_plan_hash), ...
    string(contract.stage8_calibration_plan_hash), ...
    string(plan.stage8_validation_plan_hash), ...
    string(contract.measurement_registry_hash), string(set_hash)];
if ~isequal(actual, expected) || ...
        string(provenance.calibration_freeze_status) ~= ...
        "PASS_STAGE8_1_THRESHOLD_EVIDENCE_FREEZE"
    error('load_stage8_1_locked_thresholds:StaleEvidence', ...
        'Calibration evidence does not match the active frozen plan.');
end
manifest_hash = unique(string(bundle_hash));
if ~isscalar(manifest_hash)
    error('load_stage8_1_locked_thresholds:BundleHash', ...
        'Calibration bundle identity is ambiguous.');
end
end

function verify_clean_tracked_local(repo_dir, artifact_root, registry)
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain=v1 --untracked-files=all', repo_dir));
if status ~= 0 || ~isempty(strtrim(output))
    error('load_stage8_1_locked_thresholds:DirtyRepository', ...
        'Formal threshold loading requires a clean Git worktree.');
end
repo_prefix = char(java.io.File(repo_dir).getCanonicalPath());
root_path = char(java.io.File(artifact_root).getCanonicalPath());
if ~startsWith(lower(root_path), lower([repo_prefix, filesep]))
    error('load_stage8_1_locked_thresholds:ArtifactRoot', ...
        'Committed calibration evidence must be inside the repository.');
end
required_rows = registry.table.deterministic_bundle_flag | ...
    registry.table.manifest_self_excluded_flag;
for row_index = find(required_rows).'
    path_now = fullfile(artifact_root, ...
        char(registry.table.relative_path(row_index)));
    relative = erase(char(java.io.File(path_now).getCanonicalPath()), ...
        [repo_prefix, filesep]);
    command = sprintf('git -C "%s" ls-files --error-unmatch -- "%s"', ...
        repo_dir, strrep(relative, '\', '/'));
    if system(command) ~= 0
        error('load_stage8_1_locked_thresholds:UntrackedArtifact', ...
            'Calibration artifact is not Git-tracked: %s.', relative);
    end
end
end
