function output = run_stage8_1_k1_validation_from_frozen_thresholds( ...
    repo_dir, opts)
%RUN_STAGE8_1_K1_VALIDATION_FROM_FROZEN_THRESHOLDS Run committed thresholds.

path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if nargin < 2 || isempty(opts), opts = struct(); end
opts = normalize_options_local(opts);
if opts.formal_run && ~strcmp(opts.execution_authorization, ...
        'AUTHORIZE_STAGE8_1B_K1_VALIDATION_FROM_COMMITTED_THRESHOLDS')
    error(['run_stage8_1_k1_validation_from_frozen_thresholds:', ...
        'Authorization'], ...
        'Formal validation requires committed-threshold authorization.');
end
if isempty(opts.frozen_plan)
    plan = build_stage8_locked_plan(repo_dir, sim_cfg(), ...
        struct('require_formal_runtime', opts.formal_run));
else
    if opts.formal_run
        error(['run_stage8_1_k1_validation_from_frozen_thresholds:', ...
            'PlanOverride'], 'Formal validation cannot override the plan.');
    end
    plan = opts.frozen_plan;
end
if isempty(opts.calibration_root)
    opts.calibration_root = fileparts(mfilename('fullpath'));
end
[thresholds, calibration] = load_stage8_1_locked_thresholds( ...
    repo_dir, opts.calibration_root, plan, struct( ...
    'formal_run', opts.formal_run, ...
    'require_tracked_artifacts', opts.require_tracked_artifacts));
runner_opts = struct('formal_run', opts.formal_run, ...
    'max_common_trials_per_stratum', ...
    plan.validation.K1.trials_per_stratum, ...
    'evaluation_callback', opts.evaluation_callback, ...
    'fit_options', opts.fit_options, 'Bsep', opts.Bsep, ...
    'run_separation', opts.run_separation, ...
    'execution_authorization', ...
    'INTERNAL_COMMITTED_THRESHOLD_PREFLIGHT_COMPLETE', ...
    'frozen_plan', plan);
output = run_stage8_1_k1_validation(plan.validation, plan.local_domain, ...
    plan.measurement_model_registry, thresholds, ...
    build_stage8_stage5_locked_config(), runner_opts);
output = bind_output_local(output, plan, calibration);
validate_stage8_1_validation_output(plan, calibration, output);
clear path_cleanup
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error(['run_stage8_1_k1_validation_from_frozen_thresholds:', ...
        'Options'], 'opts must be a scalar struct.');
end
require_tracked_supplied = isfield(opts, 'require_tracked_artifacts');
allowed = {'formal_run','execution_authorization','calibration_root', ...
    'require_tracked_artifacts','frozen_plan','evaluation_callback', ...
    'fit_options','Bsep','run_separation'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error(['run_stage8_1_k1_validation_from_frozen_thresholds:', ...
        'UnknownOption'], 'Unknown option: %s.', unknown{1});
end
defaults = struct('formal_run', true, 'execution_authorization', '', ...
    'calibration_root', '', 'require_tracked_artifacts', true, ...
    'frozen_plan', [], 'evaluation_callback', [], ...
    'fit_options', struct(), 'Bsep', 199, 'run_separation', true);
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(opts, names{index}), opts.(names{index}) = defaults.(names{index}); end
end
if ~opts.formal_run && ~require_tracked_supplied
    opts.require_tracked_artifacts = false;
end
end

function output = bind_output_local(output, plan, calibration)
output.stage8_stable_code_identity_hash = ...
    plan.identity.stage8_stable_code_identity_hash;
output.stage8_plan_hash = plan.stage8_plan_hash;
output.stage8_calibration_plan_hash = plan.stage8_calibration_plan_hash;
output.stage8_validation_plan_hash = plan.stage8_validation_plan_hash;
output.measurement_registry_hash = ...
    plan.measurement_model_registry.registry_hash;
output.calibration_evidence_bundle_hash = ...
    calibration.calibration_evidence_bundle_hash;
output.threshold_set_hash = calibration.threshold_set_hash;
output.validation_trial_set_hash = stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_TRIAL_SET_V1', ...
    sortrows(output.trials, 'evaluation_row_index'));
output.validation_summary_hash = stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_SUMMARY_V1', output.summary);
output.paired_sensitivity_hash = stage8_stable_hash( ...
    'STAGE8_1_PAIRED_SENSITIVITY_V1', output.paired_sensitivity);
output.primary_gate_hash = stage8_stable_hash( ...
    'STAGE8_1_PRIMARY_GATE_V1', output.gate);
output.validation_execution_status = 'STAGE8_1_K1_VALIDATION_COMPLETED';
end
