function output = run_stage8_1_k1_validation( ...
    validation_plan, local_domain, model_registry, locked_thresholds, ...
    stage5_locked, opts)
%RUN_STAGE8_1_K1_VALIDATION Run paired K1 validation without calibration.

path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if nargin < 6 || isempty(opts)
    opts = struct();
end
opts = normalize_options_local(opts, validation_plan);
registry = materialize_stage8_k1_validation_plan(validation_plan);
registry = select_registry_local(registry, opts);
pair_ids = unique(registry.common_trial_id, 'stable');
rows = cell(height(registry), 1);
row_index = 0;
start_clock = tic;
for pair_index = 1:numel(pair_ids)
    pair_rows = registry(registry.common_trial_id == pair_ids(pair_index), :);
    if height(pair_rows) ~= 2 || ...
            numel(unique(pair_rows.measurement_config_id)) ~= 2
        error('run_stage8_1_k1_validation:Pairing', ...
            'Every selected common trial must have two configuration rows.');
    end
    base_model = resolve_stage8_measurement_model(model_registry, ...
        pair_rows.measurement_config_id(1), pair_rows.noise_profile_id(1));
    [center, snr_db] = draw_trial_parameters_local( ...
        pair_rows.element_seed(1), validation_plan.K1);
    [Y_element, ~] = generate_stage8_k1_element_trial( ...
        center, snr_db, pair_rows.L(1), base_model, ...
        pair_rows.element_seed(1));
    element_identity = stage8_stable_hash( ...
        'STAGE8_K1_VALIDATION_ELEMENT_TRIAL_V1', Y_element, ...
        pair_rows.element_seed(1));
    for config_row = 1:height(pair_rows)
        row_index = row_index + 1;
        spec = pair_rows(config_row, :);
        model = resolve_stage8_measurement_model(model_registry, ...
            spec.measurement_config_id, spec.noise_profile_id);
        if ~strcmp(model.noise_factorization.factorization_hash, ...
                base_model.noise_factorization.factorization_hash)
            error('run_stage8_1_k1_validation:PairedNoise', ...
                'Paired configurations must share the element covariance.');
        end
        full_data = build_stage8_full_data_from_element(Y_element, model, ...
            struct('validation_element_seed', spec.element_seed, ...
            'data_role', 'STAGE8_K1_VALIDATION'));
        threshold = lookup_locked_lrt_threshold( ...
            spec.measurement_config_id, locked_thresholds);
        if isempty(opts.evaluation_callback)
            evaluation = evaluate_method_local(full_data, model, ...
                local_domain, threshold, stage5_locked, spec, opts);
        else
            evaluation = opts.evaluation_callback( ...
                spec, full_data, model, threshold);
        end
        rows{row_index} = validation_row_local(spec, center, snr_db, ...
            element_identity, threshold, evaluation);
    end
end
trials = struct2table(vertcat(rows{1:row_index}));
[summary, gate] = summarize_local(trials, validation_plan.K1);
output = struct('trials', trials, 'summary', summary, 'gate', gate, ...
    'paired_common_trial_count', numel(pair_ids), ...
    'method_row_count', height(trials), ...
    'threshold_lookup_only_flag', true, ...
    'threshold_modification_flag', false, ...
    'runtime', toc(start_clock), ...
    'execution_scope', ternary_local(opts.formal_run, ...
    'FORMAL_STAGE8_1_K1_VALIDATION', 'MINIATURE_UNIT_TEST'), ...
    'phase_factor', 1);
clear path_cleanup
end

function opts = normalize_options_local(opts, plan)
if ~(isstruct(opts) && isscalar(opts))
    error('run_stage8_1_k1_validation:Options', ...
        'opts must be a scalar struct.');
end
allowed = {'formal_run','max_common_trials_per_stratum', ...
    'evaluation_callback','fit_options','Bsep','run_separation', ...
    'execution_authorization'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('run_stage8_1_k1_validation:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
defaults = struct('formal_run', false, ...
    'max_common_trials_per_stratum', plan.K1.trials_per_stratum, ...
    'evaluation_callback', [], 'fit_options', struct(), ...
    'Bsep', 199, 'run_separation', true, 'execution_authorization', '');
names = fieldnames(defaults);
for field_index = 1:numel(names)
    if ~isfield(opts, names{field_index})
        opts.(names{field_index}) = defaults.(names{field_index});
    end
end
if opts.formal_run && ~strcmp(opts.execution_authorization, ...
        'AUTHORIZE_STAGE8_1B_K1_VALIDATION')
    error('run_stage8_1_k1_validation:Authorization', ...
        'Formal validation requires separate Stage8.1B authorization.');
end
if opts.formal_run && (opts.max_common_trials_per_stratum ~= 1000 || ...
        ~isempty(opts.evaluation_callback) || opts.Bsep ~= 199 || ...
        ~opts.run_separation)
    error('run_stage8_1_k1_validation:FormalContract', ...
        'Formal validation requires 1000 paired trials, Bsep=199, and real fits.');
end
end

function selected = select_registry_local(registry, opts)
selected = registry(registry.trial_index_within_stratum <= ...
    opts.max_common_trials_per_stratum, :);
if isempty(selected)
    error('run_stage8_1_k1_validation:EmptySelection', ...
        'At least one common trial per stratum is required.');
end
end

function [center, snr_db] = draw_trial_parameters_local(seed, K1)
rng_state = rng;
cleanup = onCleanup(@() rng(rng_state));
rng(seed, 'twister');
center = [K1.center_bounds_deg(1, 1) + ...
    diff(K1.center_bounds_deg(1, :)) * rand(), ...
    K1.center_bounds_deg(2, 1) + ...
    diff(K1.center_bounds_deg(2, :)) * rand()];
snr_db = K1.snr_bounds_db(1) + diff(K1.snr_bounds_db) * rand();
clear cleanup
end

function evaluation = evaluate_method_local(data, model, domain, threshold, ...
    locked, spec, opts)
[context, ~] = build_stage8_initialization_context_from_data( ...
    data, model, domain, locked, model.noise_factorization, struct());
[fit1, ~] = fit_local_model_k( ...
    data, 1, domain, model, context, opts.fit_options);
[valid1, validity1] = validate_stage8_fit_for_lrt(fit1, 1, ...
    struct('fixed_measurement_hash', model.fixed_measurement_hash, ...
    'local_domain_hash', domain.domain_hash));
if ~valid1
    evaluation = failed_evaluation_local(validity1.status);
    return;
end
context.k1_fit = fit1;
[fit2, ~] = fit_local_model_k( ...
    data, 2, domain, model, context, opts.fit_options);
[valid2, validity2] = validate_stage8_fit_for_lrt(fit2, 2, ...
    identity_from_fit_local(fit1));
if ~valid2
    evaluation = failed_evaluation_local(validity2.status);
    return;
end
[lrt, ~] = nested_dml_likelihood_ratio(fit1, fit2, struct());
if ~strcmp(lrt.lrt_status, 'OK')
    evaluation = failed_evaluation_local(lrt.lrt_status);
    return;
end
if lrt.lambda_12 <= threshold.q_global
    state = 'K1';
    separation_status = 'NOT_RUN_LRT_DID_NOT_EXCEED_THRESHOLD';
elseif opts.run_separation
    [separation, ~] = bootstrap_separation_confidence( ...
        fit2, domain, model, struct('Bsep', opts.Bsep, ...
        'seed', spec.auxiliary_seed, 'formal_run', opts.formal_run, ...
        'stage5_locked_config', locked, 'fit_options', opts.fit_options));
    decision = classify_local_cluster_state( ...
        fit1, fit2, lrt, threshold, separation, struct());
    state = decision.state;
    separation_status = separation.confidence_status;
else
    state = 'K2_UNRESOLVED';
    separation_status = 'NOT_RUN_MINIATURE_CONTRACT';
end
evaluation = struct('state', state, 'lambda_12', lrt.lambda_12, ...
    'fit1_validity_status', validity1.status, ...
    'fit2_validity_status', validity2.status, ...
    'separation_status', separation_status);
end

function identity = identity_from_fit_local(fit)
identity = struct('fixed_measurement_hash', fit.fixed_measurement_hash, ...
    'local_domain_hash', fit.local_domain_hash, ...
    'solver_contract_hash', fit.solver_contract_hash, ...
    'observation_hash', fit.observation_hash);
end

function evaluation = failed_evaluation_local(status)
if strcmp(status, 'NUMERIC_RANK_DEFICIENT')
    state = 'NUMERIC_RANK_DEFICIENT';
else
    state = 'SEARCH_NOT_CONVERGED';
end
evaluation = struct('state', state, 'lambda_12', NaN, ...
    'fit1_validity_status', status, 'fit2_validity_status', status, ...
    'separation_status', 'NOT_RUN_INVALID_LRT_FIT');
end

function row = validation_row_local(spec, center, snr_db, element_hash, ...
    threshold, evaluation)
state = string(evaluation.state);
row = struct('evaluation_row_index', spec.evaluation_row_index, ...
    'stratum_index', spec.stratum_index, ...
    'stratum_id', spec.stratum_id, ...
    'common_trial_id', spec.common_trial_id, ...
    'pairing_key', spec.pairing_key, ...
    'measurement_config_id', spec.measurement_config_id, ...
    'noise_profile_id', spec.noise_profile_id, 'L', spec.L, ...
    'element_seed', spec.element_seed, ...
    'auxiliary_seed', spec.auxiliary_seed, ...
    'center_az_deg', center(1), 'center_el_deg', center(2), ...
    'snr_db', snr_db, 'element_trial_hash', string(element_hash), ...
    'threshold_calibration_hash', string(threshold.calibration_hash), ...
    'q_global', threshold.q_global, 'lambda_12', evaluation.lambda_12, ...
    'state', state, 'false_split_flag', ismember(state, ...
    ["K2_RESOLVED","K2_UNRESOLVED"]), ...
    'false_resolved_flag', state == "K2_RESOLVED", ...
    'K2_UNRESOLVED_flag', state == "K2_UNRESOLVED", ...
    'SEARCH_NOT_CONVERGED_flag', state == "SEARCH_NOT_CONVERGED", ...
    'NUMERIC_RANK_DEFICIENT_flag', state == "NUMERIC_RANK_DEFICIENT", ...
    'decision_available_flag', ismember(state, ...
    ["K1","K2_RESOLVED","K2_UNRESOLVED"]), ...
    'fit1_validity_status', string(evaluation.fit1_validity_status), ...
    'fit2_validity_status', string(evaluation.fit2_validity_status), ...
    'separation_status', string(evaluation.separation_status));
end

function [summary, gate] = summarize_local(trials, K1)
strata = ["OVERALL";unique(trials.stratum_id, 'stable')];
rows = cell(numel(strata), 1);
for row_index = 1:numel(strata)
    if row_index == 1
        selected = true(height(trials), 1);
    else
        selected = trials.stratum_id == strata(row_index);
    end
    n = nnz(selected);
    split = stage8_wilson_interval(nnz(trials.false_split_flag(selected)), n, 0.05);
    resolved = stage8_wilson_interval( ...
        nnz(trials.false_resolved_flag(selected)), n, 0.05);
    unresolved = stage8_wilson_interval( ...
        nnz(trials.K2_UNRESOLVED_flag(selected)), n, 0.05);
    search = stage8_wilson_interval( ...
        nnz(trials.SEARCH_NOT_CONVERGED_flag(selected)), n, 0.05);
    rank_failure = stage8_wilson_interval( ...
        nnz(trials.NUMERIC_RANK_DEFICIENT_flag(selected)), n, 0.05);
    availability = stage8_wilson_interval( ...
        nnz(trials.decision_available_flag(selected)), n, 0.05);
    nondecision = stage8_wilson_interval(nnz( ...
        trials.SEARCH_NOT_CONVERGED_flag(selected) | ...
        trials.NUMERIC_RANK_DEFICIENT_flag(selected)), n, 0.05);
    rows{row_index} = struct('summary_id', strata(row_index), ...
        'method_row_count', n, 'false_split_rate', split.rate, ...
        'false_split_wilson_lower', split.lower, ...
        'false_split_wilson_upper', split.upper, ...
        'false_resolved_rate', resolved.rate, ...
        'false_resolved_wilson_upper', resolved.upper, ...
        'K2_UNRESOLVED_rate', unresolved.rate, ...
        'SEARCH_NOT_CONVERGED_rate', search.rate, ...
        'NUMERIC_RANK_DEFICIENT_rate', rank_failure.rate, ...
        'decision_availability_rate', availability.rate, ...
        'decision_availability_wilson_lower', availability.lower, ...
        'nondecision_wilson_upper', nondecision.upper);
end
summary = struct2table(vertcat(rows{:}));
overall = summary(1, :);
stratum_rows = summary(2:end, :);
gate_pass = overall.false_split_wilson_upper <= ...
    K1.gates.overall_false_split_wilson_upper && ...
    all(stratum_rows.false_split_wilson_upper <= ...
    K1.gates.stratum_false_split_wilson_upper) && ...
    overall.false_resolved_wilson_upper <= ...
    K1.gates.false_resolved_wilson_upper && ...
    overall.nondecision_wilson_upper <= K1.gates.nondecision_wilson_upper;
gate = struct('overall_false_split_pass', ...
    overall.false_split_wilson_upper <= ...
    K1.gates.overall_false_split_wilson_upper, ...
    'each_stratum_false_split_pass', all( ...
    stratum_rows.false_split_wilson_upper <= ...
    K1.gates.stratum_false_split_wilson_upper), ...
    'false_resolved_pass', overall.false_resolved_wilson_upper <= ...
    K1.gates.false_resolved_wilson_upper, ...
    'nondecision_pass', overall.nondecision_wilson_upper <= ...
    K1.gates.nondecision_wilson_upper, 'gate_pass', gate_pass, ...
    'gate_status', ternary_local(gate_pass, ...
    'STAGE8_1_K1_VALIDATION_PASS', 'STAGE8_1_K1_VALIDATION_FAIL'));
end

function value = ternary_local(condition, yes_value, no_value)
if condition
    value = yes_value;
else
    value = no_value;
end
end
