function evidence = run_stage8_1_finalize( ...
    plan, calibration_cells, cell_artifacts, locked_thresholds, ...
    validation_output, artifact_root, opts)
%RUN_STAGE8_1_FINALIZE Write Stage8.1 evidence and stop at its gate.

path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if nargin < 7 || isempty(opts)
    opts = struct();
end
opts = normalize_options_local(opts);
if opts.formal_run && ~strcmp(opts.execution_authorization, ...
        'AUTHORIZE_STAGE8_1_FINALIZE')
    error('run_stage8_1_finalize:Authorization', ...
        'Formal evidence finalization requires explicit authorization.');
end
expected_contract = build_stage8_threshold_contract(plan);
config_ids = string(plan.validation.K1.measurement_config_ids(:));
if numel(config_ids) ~= 2
    error('run_stage8_1_finalize:ThresholdConfigurationCount', ...
        'Final evidence requires exactly two measurement configurations.');
end
[locked_thresholds, threshold_set_hash] = ...
    validate_stage8_locked_threshold_set( ...
    config_ids, locked_thresholds, expected_contract);
validate_validation_thresholds_local( ...
    validation_output, locked_thresholds, expected_contract, ...
    threshold_set_hash);
bundle = build_bundle_local(plan, calibration_cells, cell_artifacts, ...
    locked_thresholds, validation_output);
evidence = write_stage8_1_results_bundle( ...
    bundle, artifact_root, struct('overwrite', opts.overwrite, ...
    'allow_incomplete', false));
evidence.validation_gate_pass = validation_output.gate.gate_pass;
evidence.stage8_2_executed_flag = false;
evidence.stage8_2_separate_authorization_required_flag = true;
evidence.stage8_2_eligible_for_separate_authorization = ...
    validation_output.gate.gate_pass;
clear path_cleanup
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('run_stage8_1_finalize:Options', 'opts must be a scalar struct.');
end
allowed = {'formal_run','execution_authorization','overwrite'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('run_stage8_1_finalize:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
if ~isfield(opts, 'formal_run'), opts.formal_run = false; end
if ~isfield(opts, 'execution_authorization')
    opts.execution_authorization = '';
end
if ~isfield(opts, 'overwrite'), opts.overwrite = false; end
end

function bundle = build_bundle_local(plan, cells, artifacts, thresholds, validation)
bundle = struct();
bundle.plan_registry = plan_registry_local(plan);
bundle.measurement_registry = plan.measurement_model_registry.table;
bundle.calibration_cells = calibration_cells_table_local(cells);
bundle.seed_registry = seed_registry_local(plan);
[bundle.cell_results, bundle.lambda_samples, bundle.complexity] = ...
    cell_tables_local(artifacts);
bundle.locked_thresholds = thresholds_table_local(thresholds);
bundle.provenance = table( ...
    string(plan.identity.stage8_stable_code_identity_hash), ...
    string(plan.stage8_plan_hash), ...
    string(plan.stage8_calibration_plan_hash), ...
    string(plan.measurement_model_registry.registry_hash), ...
    string(validation.threshold_set_hash), ...
    string(plan.stage7_1_evidence_bundle_hash), ...
    'VariableNames', {'stage8_stable_code_identity_hash', ...
    'stage8_plan_hash','stage8_calibration_plan_hash', ...
    'measurement_registry_hash','threshold_set_hash', ...
    'stage7_1_evidence_bundle_hash'});
bundle.source_manifest = plan.identity.source_manifest;
bundle.k1_validation_trials = validation.trials;
bundle.k1_validation_summary = validation.summary;
bundle.k1_validation_paired_sensitivity = validation.paired_sensitivity;
bundle.keypoints = table( ...
    string(validation.gate.gate_status), ...
    validation.gate.gate_pass, false, ...
    'VariableNames', {'stage8_1_gate_status','stage8_1_gate_pass', ...
    'stage8_2_executed_flag'});
bundle.report_text = report_local(validation);
bundle.runtime_diagnostics = table( ...
    sum([artifacts.runtime]), validation.runtime, ...
    'VariableNames', {'calibration_cell_runtime_sec', ...
    'k1_validation_runtime_sec'});
end

function table_out = plan_registry_local(plan)
artifact_id = ["STAGE8_PLAN";"CALIBRATION_PLAN"; ...
    "K1_VALIDATION_PLAN";"HOLDOUT_PLAN"];
artifact_hash = [string(plan.stage8_plan_hash); ...
    string(plan.stage8_calibration_plan_hash); ...
    string(plan.stage8_validation_plan_hash); ...
    string(plan.stage8_holdout_plan_hash)];
table_out = table(artifact_id, artifact_hash);
end

function table_out = calibration_cells_table_local(cells)
table_out = table(string({cells.calibration_cell_id}).', ...
    [cells.global_cell_index].', string({cells.measurement_config_id}).', ...
    string({cells.noise_profile_id}).', string({cells.model_key}).', ...
    string({cells.fixed_measurement_hash}).', ...
    [cells.calibration_data_seed].', [cells.bootstrap_seed_start].', ...
    [cells.bootstrap_seed_end].', string({cells.cell_input_hash}).', ...
    'VariableNames', {'calibration_cell_id','global_cell_index', ...
    'measurement_config_id','noise_profile_id','model_key', ...
    'fixed_measurement_hash','calibration_data_seed', ...
    'bootstrap_seed_start','bootstrap_seed_end','cell_input_hash'});
end

function table_out = seed_registry_local(plan)
calibration = plan.calibration.cells;
validation = materialize_stage8_k1_validation_plan(plan.validation);
bootstrap_count = plan.calibration.Bboot_per_cell;
bootstrap_seeds = reshape((calibration.bootstrap_seed_start + ...
    (0:bootstrap_count - 1)).', [], 1);
bootstrap_ids = repelem( ...
    calibration.calibration_cell_id(:), bootstrap_count, 1);
seed_role = [repmat("CALIBRATION_DATA", height(calibration), 1); ...
    repmat("CALIBRATION_BOOTSTRAP", numel(bootstrap_seeds), 1); ...
    repmat("K1_VALIDATION_PARAMETER", ...
    plan.validation.K1.common_element_trial_count, 1); ...
    repmat("K1_VALIDATION_ELEMENT_NOISE", ...
    plan.validation.K1.common_element_trial_count, 1); ...
    repmat("K1_VALIDATION_SEPARATION_AUXILIARY", ...
    plan.validation.K1.common_element_trial_count, 1)];
seed = [calibration.calibration_data_seed;bootstrap_seeds; ...
    unique(validation.parameter_seed, 'stable'); ...
    unique(validation.element_noise_seed, 'stable'); ...
    unique(validation.separation_auxiliary_seed, 'stable')];
registry_id = [calibration.calibration_cell_id(:); ...
    bootstrap_ids; ...
    unique(validation.common_trial_id, 'stable'); ...
    unique(validation.common_trial_id, 'stable'); ...
    unique(validation.common_trial_id, 'stable')];
table_out = table(seed_role, seed, registry_id);
end

function [results, lambda, complexity] = cell_tables_local(artifacts)
results = table(string({artifacts.calibration_cell_id}).', ...
    [artifacts.global_cell_index].', string({artifacts.status}).', ...
    [artifacts.q_cell_0p95].', [artifacts.failure_count].', ...
    string({artifacts.cell_artifact_hash}).', ...
    'VariableNames', {'calibration_cell_id','global_cell_index', ...
    'status','q_cell_0p95','failure_count','cell_artifact_hash'});
total = sum(arrayfun(@(x) numel(x.lambda_samples), artifacts));
cell_id = strings(total, 1);
bootstrap_index = zeros(total, 1);
bootstrap_seed = zeros(total, 1);
lambda_12 = zeros(total, 1);
row_index = 0;
for artifact_index = 1:numel(artifacts)
    count = numel(artifacts(artifact_index).lambda_samples);
    rows = row_index + (1:count);
    cell_id(rows) = string(artifacts(artifact_index).calibration_cell_id);
    bootstrap_index(rows) = (1:count).';
    bootstrap_seed(rows) = artifacts(artifact_index).bootstrap_seed_start + ...
        (0:count - 1).';
    lambda_12(rows) = artifacts(artifact_index).lambda_samples;
    row_index = row_index + count;
end
lambda = table(cell_id, bootstrap_index, bootstrap_seed, lambda_12);
complexity = table(string({artifacts.calibration_cell_id}).', ...
    [artifacts.K1_fit_count].', [artifacts.K2_fit_count].', ...
    [artifacts.score_call_count].', [artifacts.svd_call_count].', ...
    'VariableNames', {'calibration_cell_id','K1_fit_count', ...
    'K2_fit_count','score_call_count','svd_call_count'});
end

function table_out = thresholds_table_local(thresholds)
table_out = table( ...
    string({thresholds.stage8_stable_code_identity_hash}).', ...
    string({thresholds.stage8_plan_hash}).', ...
    string({thresholds.stage8_calibration_plan_hash}).', ...
    string({thresholds.measurement_registry_hash}).', ...
    string({thresholds.measurement_config_id}).', ...
    [thresholds.q_global].', [thresholds.alpha].', ...
    string({thresholds.calibration_hash}).', ...
    string({thresholds.source_identity}).', ...
    string({thresholds.threshold_status}).', ...
    string({thresholds.threshold_policy}).', ...
    string({thresholds.threshold_artifact_hash}).', ...
    'VariableNames', {'stage8_stable_code_identity_hash', ...
    'stage8_plan_hash','stage8_calibration_plan_hash', ...
    'measurement_registry_hash','measurement_config_id','q_global', ...
    'alpha','calibration_hash','source_identity','threshold_status', ...
    'threshold_policy','threshold_artifact_hash'});
end

function validate_validation_thresholds_local( ...
    validation, thresholds, expected_contract, expected_set_hash)
required = {'trials','threshold_contract','threshold_set_hash', ...
    'paired_sensitivity'};
if ~(isstruct(validation) && isscalar(validation) && ...
        all(isfield(validation, required)))
    error('run_stage8_1_finalize:ValidationThresholdContract', ...
        'Validation output does not expose threshold provenance.');
end
actual_contract = validate_stage8_threshold_contract( ...
    validation.threshold_contract);
names = fieldnames(expected_contract);
for field_index = 1:numel(names)
    if ~strcmp(string(actual_contract.(names{field_index})), ...
            string(expected_contract.(names{field_index})))
        error('run_stage8_1_finalize:ValidationThresholdContract', ...
            'Validation used a threshold from another Stage8 contract.');
    end
end
if ~strcmp(string(validation.threshold_set_hash), ...
        string(expected_set_hash)) || ...
        ~ismember('threshold_artifact_hash', ...
        validation.trials.Properties.VariableNames)
    error('run_stage8_1_finalize:ValidationThresholdHash', ...
        'Validation and final evidence threshold hashes differ.');
end
used = unique(string(validation.trials.threshold_artifact_hash));
expected = unique(string({thresholds.threshold_artifact_hash}).');
if ~isempty(setxor(used, expected))
    error('run_stage8_1_finalize:ValidationThresholdHash', ...
        'Validation trial rows did not use both final locked thresholds.');
end
end

function text_out = report_local(validation)
text_out = sprintf(['# Stage8.1 Calibration and K1 Validation\n\n', ...
    'Gate status: `%s`.\n\n', ...
    'Stage8.2 was not executed and requires separate authorization.\n'], ...
    validation.gate.gate_status);
end
