function evidence = run_stage8_1_finalize( ...
    frozen_plan, committed_calibration_evidence, validation_output, ...
    validation_artifact_root, opts)
%RUN_STAGE8_1_FINALIZE Recompute validation evidence and write results only.

path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if nargin < 5 || isempty(opts), opts = struct(); end
opts = normalize_options_local(opts);
if opts.formal_run && ~strcmp(opts.execution_authorization, ...
        'AUTHORIZE_STAGE8_1_FINALIZE')
    error('run_stage8_1_finalize:Authorization', ...
        'Formal finalization requires explicit authorization.');
end
required = {'repo_dir','artifact_root'};
if ~(isstruct(committed_calibration_evidence) && ...
        all(isfield(committed_calibration_evidence, required)))
    error('run_stage8_1_finalize:CalibrationEvidence', ...
        'Finalization requires reloadable committed calibration evidence.');
end
if opts.formal_run
    validation_artifact_root = validate_stage8_formal_artifact_root( ...
        committed_calibration_evidence.repo_dir, ...
        validation_artifact_root, 'VALIDATION', struct( ...
        'require_empty_lifecycle', true));
end
[~, calibration] = load_stage8_1_locked_thresholds( ...
    committed_calibration_evidence.repo_dir, ...
    committed_calibration_evidence.artifact_root, frozen_plan, struct( ...
    'formal_run', opts.formal_run, ...
    'require_tracked_artifacts', opts.require_tracked_artifacts));
[~, calibration_snapshot_hash] = ...
    capture_stage8_1_calibration_snapshot(calibration.artifact_root);
if ~isfield(validation_output, 'calibration_artifact_snapshot_hash') || ...
        ~strcmp(string(validation_output.calibration_artifact_snapshot_hash), ...
        string(calibration_snapshot_hash))
    error('run_stage8_1_finalize:CalibrationSnapshotMismatch', ...
        'Calibration evidence differs from the pre-validation snapshot.');
end
validated = validate_stage8_1_validation_output( ...
    frozen_plan, calibration, validation_output);
bundle = validation_bundle_local(frozen_plan, calibration, ...
    validation_output, validated);
[~, prewrite_snapshot_hash] = ...
    capture_stage8_1_calibration_snapshot(calibration.artifact_root);
if ~strcmp(calibration_snapshot_hash, prewrite_snapshot_hash)
    error('run_stage8_1_finalize:CalibrationEvidenceMutation', ...
        'Calibration evidence changed before validation evidence writing.');
end
written = write_stage8_1_validation_evidence(bundle, ...
    validation_artifact_root, ...
    calibration.calibration_evidence_bundle_hash, ...
    struct('overwrite', opts.overwrite));
[~, postwrite_snapshot_hash] = ...
    capture_stage8_1_calibration_snapshot(calibration.artifact_root);
if ~strcmp(calibration_snapshot_hash, postwrite_snapshot_hash)
    error('run_stage8_1_finalize:CalibrationEvidenceMutation', ...
        'Calibration evidence changed while writing validation evidence.');
end
evidence = written;
evidence.validation_gate_pass = validated.recomputed_primary_gate_pass;
evidence.recomputed_primary_gate_pass = ...
    validated.recomputed_primary_gate_pass;
evidence.validation_trial_set_hash = validated.validation_trial_set_hash;
evidence.validation_summary_hash = validated.validation_summary_hash;
evidence.paired_sensitivity_hash = validated.paired_sensitivity_hash;
evidence.primary_gate_hash = validated.primary_gate_hash;
evidence.threshold_set_hash = calibration.threshold_set_hash;
evidence.calibration_evidence_bundle_hash = ...
    calibration.calibration_evidence_bundle_hash;
evidence.stage8_2_executed_flag = false;
evidence.stage8_2_separate_authorization_required_flag = true;
evidence.stage8_2_eligible_for_separate_authorization = ...
    validated.recomputed_primary_gate_pass;
clear path_cleanup
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('run_stage8_1_finalize:Options', 'opts must be a scalar struct.');
end
allowed = {'formal_run','execution_authorization','overwrite', ...
    'require_tracked_artifacts'};
tracked_option_supplied = isfield(opts, 'require_tracked_artifacts');
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('run_stage8_1_finalize:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
if ~isfield(opts, 'formal_run'), opts.formal_run = true; end
if ~isfield(opts, 'execution_authorization')
    opts.execution_authorization = '';
end
if ~isfield(opts, 'overwrite'), opts.overwrite = false; end
if ~isfield(opts, 'require_tracked_artifacts')
    opts.require_tracked_artifacts = opts.formal_run;
end
if opts.formal_run && tracked_option_supplied && ...
        ~logical_scalar_true_local(opts.require_tracked_artifacts)
    error(['run_stage8_1_finalize:', ...
        'FORMAL_TRACKED_CALIBRATION_EVIDENCE_REQUIRED'], ...
        'Formal finalization cannot disable tracked calibration evidence.');
end
if opts.formal_run && opts.overwrite
    error(['run_stage8_1_finalize:', ...
        'FORMAL_EVIDENCE_OVERWRITE_FORBIDDEN'], ...
        'Formal validation evidence cannot overwrite existing artifacts.');
end
if opts.formal_run
    opts.require_tracked_artifacts = true;
end
end

function pass = logical_scalar_true_local(value)
pass = islogical(value) && isscalar(value) && value;
end

function bundle = validation_bundle_local(plan, calibration, output, validated)
bundle = struct('k1_validation_trials', validated.trials, ...
    'k1_validation_summary', validated.summary, ...
    'k1_validation_paired_sensitivity', validated.paired_sensitivity);
bundle.validation_provenance = table( ...
    string(plan.identity.stage8_stable_code_identity_hash), ...
    string(plan.stage8_plan_hash), ...
    string(plan.stage8_calibration_plan_hash), ...
    string(plan.stage8_validation_plan_hash), ...
    string(plan.measurement_model_registry.registry_hash), ...
    string(calibration.calibration_evidence_bundle_hash), ...
    string(calibration.threshold_set_hash), ...
    string(validated.validation_trial_set_hash), ...
    string(validated.validation_summary_hash), ...
    string(validated.paired_sensitivity_hash), ...
    string(validated.primary_gate_hash), ...
    string(output.calibration_artifact_snapshot_hash), ...
    string(output.committed_threshold_preflight_status), ...
    "STAGE8_1_K1_VALIDATION_COMPLETED", ...
    'VariableNames', {'stage8_stable_code_identity_hash', ...
    'stage8_plan_hash','stage8_calibration_plan_hash', ...
    'stage8_validation_plan_hash','measurement_registry_hash', ...
    'calibration_evidence_bundle_hash','threshold_set_hash', ...
    'validation_trial_set_hash','validation_summary_hash', ...
    'paired_sensitivity_hash','primary_gate_hash', ...
    'calibration_artifact_snapshot_hash', ...
    'committed_threshold_preflight_status', ...
    'validation_execution_status'});
bundle.keypoints = table(string(validated.gate.gate_status), ...
    validated.recomputed_primary_gate_pass, false, true, ...
    'VariableNames', {'stage8_1_gate_status','stage8_1_gate_pass', ...
    'stage8_2_executed_flag', ...
    'stage8_2_separate_authorization_required_flag'});
bundle.report_text = sprintf(['# Stage8.1 K1 Validation\n\n', ...
    'Gate status: `%s`.\n\n', ...
    'Stage8.2 was not executed and requires separate authorization.\n'], ...
    validated.gate.gate_status);
runtime = 0;
if isfield(output, 'runtime'), runtime = output.runtime; end
bundle.runtime_diagnostics = table(runtime, ...
    'VariableNames', {'k1_validation_runtime_sec'});
end
