function output = run_stage8_1_k1_validation( ...
    validation_plan, local_domain, model_registry, locked_thresholds, ...
    stage5_locked, opts)
%RUN_STAGE8_1_K1_VALIDATION Run paired K1 validation without calibration.

path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if nargin < 6 || isempty(opts)
    opts = struct();
end
opts = normalize_options_local(opts, validation_plan);
[expected_contract, frozen_plan] = ...
    threshold_contract_local(opts, validation_plan);
[thresholds, threshold_set_hash] = ...
    validate_stage8_locked_threshold_set( ...
    validation_plan.K1.measurement_config_ids, locked_thresholds, ...
    expected_contract);
if opts.formal_run
    verify_formal_runtime_local(frozen_plan);
end
registry = materialize_stage8_k1_validation_plan(validation_plan);
registry = select_registry_local(registry, opts);
pair_ids = unique(registry.common_trial_id, 'stable');
rows = cell(height(registry), 1);
row_index = 0;
start_clock = tic;
for pair_index = 1:numel(pair_ids)
    pair_rows = registry(registry.common_trial_id == pair_ids(pair_index), :);
    if height(pair_rows) ~= 2 || ...
            numel(unique(pair_rows.measurement_config_id)) ~= 2
        error('run_stage8_1_k1_validation:Pairing', ...
            'Every selected common trial must have two configuration rows.');
    end
    base_model = resolve_stage8_measurement_model(model_registry, ...
        pair_rows.measurement_config_id(1), pair_rows.noise_profile_id(1));
    [center, snr_db] = draw_trial_parameters_local( ...
        pair_rows.parameter_seed(1), validation_plan.K1);
    [Y_element, ~] = generate_stage8_k1_element_trial( ...
        center, snr_db, pair_rows.L(1), base_model, ...
        pair_rows.element_noise_seed(1));
    element_identity = stage8_stable_hash( ...
        'STAGE8_K1_VALIDATION_ELEMENT_TRIAL_V2', Y_element, ...
        pair_rows.parameter_seed(1), pair_rows.element_noise_seed(1));
    for config_row = 1:height(pair_rows)
        row_index = row_index + 1;
        spec = pair_rows(config_row, :);
        model = resolve_stage8_measurement_model(model_registry, ...
            spec.measurement_config_id, spec.noise_profile_id);
        if ~strcmp(model.noise_factorization.factorization_hash, ...
                base_model.noise_factorization.factorization_hash)
            error('run_stage8_1_k1_validation:PairedNoise', ...
                'Paired configurations must share the element covariance.');
        end
        full_data = build_stage8_full_data_from_element(Y_element, model, ...
            struct('validation_parameter_seed', spec.parameter_seed, ...
            'validation_element_noise_seed', spec.element_noise_seed, ...
            'data_role', 'STAGE8_K1_VALIDATION'));
        threshold = threshold_for_config_local( ...
            thresholds, spec.measurement_config_id);
        if isempty(opts.evaluation_callback)
            evaluation = evaluate_method_local(full_data, model, ...
                local_domain, threshold, stage5_locked, spec, opts);
        else
            evaluation = opts.evaluation_callback( ...
                spec, full_data, model, threshold);
        end
        rows{row_index} = validation_row_local(spec, center, snr_db, ...
            element_identity, threshold, evaluation);
    end
end
trials = struct2table(vertcat(rows{1:row_index}));
[summary, gate, paired_sensitivity] = ...
    summarize_stage8_k1_validation(trials, validation_plan.K1);
output = struct('trials', trials, 'summary', summary, 'gate', gate, ...
    'paired_sensitivity', paired_sensitivity, ...
    'threshold_contract', expected_contract, ...
    'threshold_set_hash', threshold_set_hash, ...
    'paired_common_trial_count', numel(pair_ids), ...
    'method_row_count', height(trials), ...
    'threshold_lookup_only_flag', true, ...
    'threshold_modification_flag', false, ...
    'runtime', toc(start_clock), ...
    'execution_scope', ternary_local(opts.formal_run, ...
    'FORMAL_STAGE8_1_K1_VALIDATION', 'MINIATURE_UNIT_TEST'), ...
    'phase_factor', 1);
clear path_cleanup
end

function opts = normalize_options_local(opts, plan)
if ~(isstruct(opts) && isscalar(opts))
    error('run_stage8_1_k1_validation:Options', ...
        'opts must be a scalar struct.');
end
allowed = {'formal_run','max_common_trials_per_stratum', ...
    'evaluation_callback','fit_options','Bsep','run_separation', ...
    'execution_authorization','expected_threshold_contract','frozen_plan'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('run_stage8_1_k1_validation:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
defaults = struct('formal_run', false, ...
    'max_common_trials_per_stratum', plan.K1.trials_per_stratum, ...
    'evaluation_callback', [], 'fit_options', struct(), ...
    'Bsep', 199, 'run_separation', true, 'execution_authorization', '', ...
    'expected_threshold_contract', [], 'frozen_plan', []);
names = fieldnames(defaults);
for field_index = 1:numel(names)
    if ~isfield(opts, names{field_index})
        opts.(names{field_index}) = defaults.(names{field_index});
    end
end
if opts.formal_run && ~strcmp(opts.execution_authorization, ...
        'INTERNAL_COMMITTED_THRESHOLD_PREFLIGHT_COMPLETE')
    error('run_stage8_1_k1_validation:Authorization', ...
        'Formal validation must enter through the committed-threshold wrapper.');
end
if opts.formal_run && (opts.max_common_trials_per_stratum ~= 1000 || ...
        ~isempty(opts.evaluation_callback) || opts.Bsep ~= 199 || ...
        ~opts.run_separation)
    error('run_stage8_1_k1_validation:FormalContract', ...
        'Formal validation requires 1000 paired trials, Bsep=199, and real fits.');
end
end

function [contract, frozen_plan] = threshold_contract_local(opts, validation_plan)
frozen_plan = opts.frozen_plan;
if isempty(frozen_plan)
    if opts.formal_run
        error('run_stage8_1_k1_validation:FrozenPlanRequired', ...
            'Formal validation requires the current frozen Stage8 plan.');
    end
    contract = validate_stage8_threshold_contract( ...
        opts.expected_threshold_contract);
    return;
end
contract = build_stage8_threshold_contract(frozen_plan);
if ~isempty(opts.expected_threshold_contract)
    supplied = validate_stage8_threshold_contract( ...
        opts.expected_threshold_contract);
    names = fieldnames(contract);
    for field_index = 1:numel(names)
        if ~strcmp(string(contract.(names{field_index})), ...
                string(supplied.(names{field_index})))
            error('run_stage8_1_k1_validation:ThresholdContractMismatch', ...
                'The supplied threshold contract differs from the frozen plan.');
        end
    end
end
if ~isfield(frozen_plan, 'validation') || ...
        ~strcmp(string(frozen_plan.validation.validation_plan_hash), ...
        string(validation_plan.validation_plan_hash))
    error('run_stage8_1_k1_validation:ValidationPlanMismatch', ...
        'The active validation plan differs from the frozen Stage8 plan.');
end
end

function threshold = threshold_for_config_local(thresholds, config_id)
matches = string({thresholds.measurement_config_id}) == string(config_id);
if nnz(matches) ~= 1
    error('run_stage8_1_k1_validation:ThresholdPreflight', ...
        'Threshold preflight did not retain one artifact per configuration.');
end
threshold = thresholds(matches);
end

function verify_formal_runtime_local(plan)
required = {'working_tree_clean_flag','untracked_source_count', ...
    'repository_root','runtime_head_commit'};
if ~all(isfield(plan.identity, required)) || ...
        ~(plan.identity.working_tree_clean_flag && ...
        plan.identity.untracked_source_count == 0)
    error('run_stage8_1_k1_validation:DirtyThresholdEvidenceCommit', ...
        'Formal validation requires a clean threshold evidence commit.');
end
repo_dir = plan.identity.repository_root;
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain=v1 --untracked-files=all', repo_dir));
[head_status, head] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', repo_dir));
if status ~= 0 || head_status ~= 0 || ~isempty(strtrim(output)) || ...
        ~strcmp(strtrim(head), plan.identity.runtime_head_commit)
    error('run_stage8_1_k1_validation:DirtyThresholdEvidenceCommit', ...
        'Formal validation requires the current clean threshold evidence commit.');
end
end

function selected = select_registry_local(registry, opts)
selected = registry(registry.trial_index_within_stratum <= ...
    opts.max_common_trials_per_stratum, :);
if isempty(selected)
    error('run_stage8_1_k1_validation:EmptySelection', ...
        'At least one common trial per stratum is required.');
end
end

function [center, snr_db] = draw_trial_parameters_local(seed, K1)
rng_state = rng;
cleanup = onCleanup(@() rng(rng_state));
rng(seed, 'twister');
center = [K1.center_bounds_deg(1, 1) + ...
    diff(K1.center_bounds_deg(1, :)) * rand(), ...
    K1.center_bounds_deg(2, 1) + ...
    diff(K1.center_bounds_deg(2, :)) * rand()];
snr_db = K1.snr_bounds_db(1) + diff(K1.snr_bounds_db) * rand();
clear cleanup
end

function evaluation = evaluate_method_local(data, model, domain, threshold, ...
    locked, spec, opts)
[context, ~] = build_stage8_initialization_context_from_data( ...
    data, model, domain, locked, model.noise_factorization, struct());
[fit1, ~] = fit_local_model_k( ...
    data, 1, domain, model, context, opts.fit_options);
[valid1, validity1] = validate_stage8_fit_for_lrt(fit1, 1, ...
    struct('fixed_measurement_hash', model.fixed_measurement_hash, ...
    'local_domain_hash', domain.domain_hash));
if ~valid1
    evaluation = failed_evaluation_local(validity1.status);
    return;
end
context.k1_fit = fit1;
[fit2, ~] = fit_local_model_k( ...
    data, 2, domain, model, context, opts.fit_options);
[valid2, validity2] = validate_stage8_fit_for_lrt(fit2, 2, ...
    identity_from_fit_local(fit1));
if ~valid2
    evaluation = failed_evaluation_local(validity2.status);
    return;
end
[lrt, ~] = nested_dml_likelihood_ratio(fit1, fit2, struct());
if ~strcmp(lrt.lrt_status, 'OK')
    evaluation = failed_evaluation_local(lrt.lrt_status);
    return;
end
if lrt.lambda_12 <= threshold.q_global
    state = 'K1';
    separation_status = 'NOT_RUN_LRT_DID_NOT_EXCEED_THRESHOLD';
elseif opts.run_separation
    [separation, ~] = bootstrap_separation_confidence( ...
        fit2, domain, model, struct('Bsep', opts.Bsep, ...
        'seed', spec.separation_auxiliary_seed, ...
        'formal_run', opts.formal_run, ...
        'stage5_locked_config', locked, 'fit_options', opts.fit_options));
    decision = classify_local_cluster_state( ...
        fit1, fit2, lrt, threshold, separation, struct());
    state = decision.state;
    separation_status = separation.confidence_status;
else
    state = 'K2_UNRESOLVED';
    separation_status = 'NOT_RUN_MINIATURE_CONTRACT';
end
evaluation = struct('state', state, 'lambda_12', lrt.lambda_12, ...
    'fit1_validity_status', validity1.status, ...
    'fit2_validity_status', validity2.status, ...
    'separation_status', separation_status);
end

function identity = identity_from_fit_local(fit)
identity = struct('fixed_measurement_hash', fit.fixed_measurement_hash, ...
    'local_domain_hash', fit.local_domain_hash, ...
    'solver_contract_hash', fit.solver_contract_hash, ...
    'observation_hash', fit.observation_hash);
end

function evaluation = failed_evaluation_local(status)
if strcmp(status, 'NUMERIC_RANK_DEFICIENT')
    state = 'NUMERIC_RANK_DEFICIENT';
else
    state = 'SEARCH_NOT_CONVERGED';
end
evaluation = struct('state', state, 'lambda_12', NaN, ...
    'fit1_validity_status', status, 'fit2_validity_status', status, ...
    'separation_status', 'NOT_RUN_INVALID_LRT_FIT');
end

function row = validation_row_local(spec, center, snr_db, element_hash, ...
    threshold, evaluation)
state = string(evaluation.state);
row = struct('evaluation_row_index', spec.evaluation_row_index, ...
    'stratum_index', spec.stratum_index, ...
    'stratum_id', spec.stratum_id, ...
    'common_trial_id', spec.common_trial_id, ...
    'pairing_key', spec.pairing_key, ...
    'trial_index_within_stratum', spec.trial_index_within_stratum, ...
    'measurement_config_id', spec.measurement_config_id, ...
    'noise_profile_id', spec.noise_profile_id, 'L', spec.L, ...
    'parameter_seed', spec.parameter_seed, ...
    'element_noise_seed', spec.element_noise_seed, ...
    'separation_auxiliary_seed', spec.separation_auxiliary_seed, ...
    'center_az_deg', center(1), 'center_el_deg', center(2), ...
    'snr_db', snr_db, 'element_trial_hash', string(element_hash), ...
    'threshold_calibration_hash', string(threshold.calibration_hash), ...
    'threshold_artifact_hash', string(threshold.threshold_artifact_hash), ...
    'q_global', threshold.q_global, 'lambda_12', evaluation.lambda_12, ...
    'state', state, 'false_split_flag', ismember(state, ...
    ["K2_RESOLVED","K2_UNRESOLVED"]), ...
    'false_resolved_flag', state == "K2_RESOLVED", ...
    'K2_UNRESOLVED_flag', state == "K2_UNRESOLVED", ...
    'SEARCH_NOT_CONVERGED_flag', state == "SEARCH_NOT_CONVERGED", ...
    'NUMERIC_RANK_DEFICIENT_flag', state == "NUMERIC_RANK_DEFICIENT", ...
    'decision_available_flag', ismember(state, ...
    ["K1","K2_RESOLVED","K2_UNRESOLVED"]), ...
    'fit1_validity_status', string(evaluation.fit1_validity_status), ...
    'fit2_validity_status', string(evaluation.fit2_validity_status), ...
    'separation_status', string(evaluation.separation_status));
end

function value = ternary_local(condition, yes_value, no_value)
if condition
    value = yes_value;
else
    value = no_value;
end
end
