function registry = stage8_1_validation_artifact_registry()
%STAGE8_1_VALIDATION_ARTIFACT_REGISTRY Freeze validation evidence paths.

path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
artifact_id = ["K1_VALIDATION_TRIALS";"K1_VALIDATION_SUMMARY"; ...
    "K1_PAIRED_SENSITIVITY";"VALIDATION_PROVENANCE";"KEYPOINTS"; ...
    "REPORT";"VALIDATION_EVIDENCE_MANIFEST";"RUNTIME_DIAGNOSTICS"];
relative_path = [ ...
    "results/stage8_1_k1_validation_trials.csv"; ...
    "results/stage8_1_k1_validation_summary.csv"; ...
    "results/stage8_1_k1_paired_sensitivity.csv"; ...
    "results/stage8_1_validation_provenance.csv"; ...
    "results/stage8_1_keypoints.csv"; ...
    "results/stage8_1_report.md"; ...
    "results/stage8_1_validation_evidence_manifest.csv"; ...
    "results/stage8_1_runtime_diagnostics.csv"];
bundle_field = ["k1_validation_trials";"k1_validation_summary"; ...
    "k1_validation_paired_sensitivity";"validation_provenance"; ...
    "keypoints";"report_text";"validation_evidence_manifest"; ...
    "runtime_diagnostics"];
deterministic_bundle_flag = true(numel(artifact_id), 1);
deterministic_bundle_flag(artifact_id == ...
    "VALIDATION_EVIDENCE_MANIFEST" | ...
    artifact_id == "RUNTIME_DIAGNOSTICS") = false;
manifest_self_excluded_flag = artifact_id == "VALIDATION_EVIDENCE_MANIFEST";
runtime_excluded_flag = artifact_id == "RUNTIME_DIAGNOSTICS";
formal_required_flag = true(numel(artifact_id), 1);
artifact_class = repmat("VALIDATION", numel(artifact_id), 1);
table_out = table(artifact_id, relative_path, bundle_field, artifact_class, ...
    deterministic_bundle_flag, manifest_self_excluded_flag, ...
    runtime_excluded_flag, formal_required_flag);
registry = struct('table', table_out, 'checkpoint_glob_exclusion', '', ...
    'registry_hash', stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_ARTIFACT_REGISTRY_V1', table_out), ...
    'registry_version', 'STAGE8_1_VALIDATION_ARTIFACT_REGISTRY_V1', ...
    'lifecycle', 'VALIDATION');
clear path_cleanup
end
