function registry = stage8_1_artifact_registry()
%STAGE8_1_ARTIFACT_REGISTRY Freeze Stage8.1 evidence paths and roles.

path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
artifact_id = [ ...
    "PLAN_REGISTRY";"MEASUREMENT_REGISTRY";"CALIBRATION_CELLS"; ...
    "SEED_REGISTRY";"CELL_RESULTS";"LAMBDA_SAMPLES"; ...
    "LOCKED_THRESHOLDS";"COMPLEXITY";"PROVENANCE"; ...
    "SOURCE_MANIFEST";"EVIDENCE_MANIFEST";"K1_VALIDATION_TRIALS"; ...
    "K1_VALIDATION_SUMMARY";"KEYPOINTS";"REPORT"; ...
    "RUNTIME_DIAGNOSTICS"];
relative_path = [ ...
    "calibration/stage8_1_plan_registry.csv"; ...
    "calibration/stage8_1_measurement_registry.csv"; ...
    "calibration/stage8_1_calibration_cells.csv"; ...
    "calibration/stage8_1_seed_registry.csv"; ...
    "calibration/stage8_1_cell_results.csv"; ...
    "calibration/stage8_1_lambda_samples.csv"; ...
    "calibration/stage8_1_locked_thresholds.csv"; ...
    "calibration/stage8_1_complexity.csv"; ...
    "calibration/stage8_1_provenance.csv"; ...
    "calibration/stage8_1_source_manifest.csv"; ...
    "calibration/stage8_1_evidence_manifest.csv"; ...
    "results/stage8_1_k1_validation_trials.csv"; ...
    "results/stage8_1_k1_validation_summary.csv"; ...
    "results/stage8_1_keypoints.csv"; ...
    "results/stage8_1_report.md"; ...
    "results/stage8_1_runtime_diagnostics.csv"];
bundle_field = [ ...
    "plan_registry";"measurement_registry";"calibration_cells"; ...
    "seed_registry";"cell_results";"lambda_samples"; ...
    "locked_thresholds";"complexity";"provenance"; ...
    "source_manifest";"evidence_manifest";"k1_validation_trials"; ...
    "k1_validation_summary";"keypoints";"report_text"; ...
    "runtime_diagnostics"];
artifact_class = [repmat("CALIBRATION", 11, 1); ...
    repmat("RESULT", 5, 1)];
deterministic_bundle_flag = true(numel(artifact_id), 1);
deterministic_bundle_flag(artifact_id == "EVIDENCE_MANIFEST" | ...
    artifact_id == "RUNTIME_DIAGNOSTICS") = false;
manifest_self_excluded_flag = artifact_id == "EVIDENCE_MANIFEST";
runtime_excluded_flag = artifact_id == "RUNTIME_DIAGNOSTICS";
formal_required_flag = true(numel(artifact_id), 1);
table_out = table(artifact_id, relative_path, bundle_field, artifact_class, ...
    deterministic_bundle_flag, manifest_self_excluded_flag, ...
    runtime_excluded_flag, formal_required_flag);
registry = struct('table', table_out, ...
    'checkpoint_glob_exclusion', 'calibration/checkpoints/*.mat', ...
    'registry_hash', stage8_stable_hash( ...
    'STAGE8_1_ARTIFACT_REGISTRY_V1', table_out), ...
    'registry_version', 'STAGE8_1_ARTIFACT_REGISTRY_V1');
clear path_cleanup
end
