function validated = validate_stage8_1_validation_output( ...
    frozen_plan, calibration_evidence, validation_output)
%VALIDATE_STAGE8_1_VALIDATION_OUTPUT Recompute validation evidence from trials.

required_plan = {'validation','stage8_validation_plan_hash','identity', ...
    'stage8_plan_hash','stage8_calibration_plan_hash', ...
    'measurement_model_registry'};
if ~(isstruct(frozen_plan) && isscalar(frozen_plan) && ...
        all(isfield(frozen_plan, required_plan)))
    error('validate_stage8_1_validation_output:Plan', ...
        'The frozen Stage8 validation plan is incomplete.');
end
required_calibration = {'calibration_evidence_bundle_hash', ...
    'threshold_set_hash','locked_thresholds'};
if ~(isstruct(calibration_evidence) && isscalar(calibration_evidence) && ...
        all(isfield(calibration_evidence, required_calibration)))
    error('validate_stage8_1_validation_output:CalibrationEvidence', ...
        'Committed calibration evidence is incomplete.');
end
required_output = {'trials','summary','gate','paired_sensitivity', ...
    'stage8_stable_code_identity_hash','stage8_plan_hash', ...
    'stage8_calibration_plan_hash','stage8_validation_plan_hash', ...
    'measurement_registry_hash','calibration_evidence_bundle_hash', ...
    'threshold_set_hash','validation_trial_set_hash', ...
    'validation_summary_hash','paired_sensitivity_hash', ...
    'primary_gate_hash','validation_execution_status', ...
    'calibration_artifact_snapshot_hash', ...
    'committed_threshold_preflight_status'};
if ~(isstruct(validation_output) && isscalar(validation_output) && ...
        all(isfield(validation_output, required_output)))
    error('validate_stage8_1_validation_output:OutputContract', ...
        'Validation output does not expose the self-contained contract.');
end

trials = validation_output.trials;
expected = materialize_stage8_k1_validation_plan(frozen_plan.validation);
verify_trial_registry_local(trials, expected, frozen_plan.validation.K1);
verify_threshold_mapping_local(trials, calibration_evidence, ...
    frozen_plan.validation.K1);
[summary, gate, paired] = summarize_stage8_k1_validation( ...
    trials, frozen_plan.validation.K1);
if height(summary) ~= 14
    error('validate_stage8_1_validation_output:SummaryCardinality', ...
        'Recomputed K1 validation summary must contain exactly 14 rows.');
end
if ~strcmp(string(gate.authorization_measurement_config_id), ...
        string(frozen_plan.validation.K1.primary_measurement_config_id)) || ...
        gate.sensitivity_used_for_authorization_flag
    error('validate_stage8_1_validation_output:PrimaryAuthorization', ...
        'Only PRIMARY may authorize Stage8.2.');
end
if ~strcmp(string(validation_output.committed_threshold_preflight_status), ...
        "COMMITTED_THRESHOLD_PREFLIGHT_PASS")
    error('validate_stage8_1_validation_output:CommittedThresholdPreflight', ...
        'Validation did not complete committed-threshold preflight.');
end

hashes = compute_hashes_local(trials, summary, paired, gate);
verify_identity_local(frozen_plan, calibration_evidence, ...
    validation_output, hashes);
if ~table_equal_local(validation_output.summary, summary) || ...
        ~table_equal_local(validation_output.paired_sensitivity, paired) || ...
        ~strcmp(stage8_stable_hash('STAGE8_1_PRIMARY_GATE_V1', ...
        validation_output.gate), hashes.primary_gate_hash)
    error('validate_stage8_1_validation_output:DerivedEvidenceMismatch', ...
        'Supplied summary, paired sensitivity, or gate differs from raw trials.');
end
validated = struct('trials', trials, 'summary', summary, 'gate', gate, ...
    'paired_sensitivity', paired, ...
    'validation_trial_set_hash', hashes.validation_trial_set_hash, ...
    'validation_summary_hash', hashes.validation_summary_hash, ...
    'paired_sensitivity_hash', hashes.paired_sensitivity_hash, ...
    'primary_gate_hash', hashes.primary_gate_hash, ...
    'recomputed_primary_gate_pass', gate.gate_pass, ...
    'validation_plan_hash', frozen_plan.stage8_validation_plan_hash, ...
    'calibration_evidence_bundle_hash', ...
    calibration_evidence.calibration_evidence_bundle_hash, ...
    'threshold_set_hash', calibration_evidence.threshold_set_hash, ...
    'validation_execution_status', ...
    'STAGE8_1_K1_VALIDATION_COMPLETED');
end

function verify_trial_registry_local(trials, expected, K1)
required = [expected.Properties.VariableNames, {'state', ...
    'threshold_artifact_hash'}];
if ~(istable(trials) && all(ismember(required, ...
        trials.Properties.VariableNames)))
    error('validate_stage8_1_validation_output:TrialContract', ...
        'Raw trials do not expose the frozen registry and decision fields.');
end
if height(trials) ~= K1.config_evaluation_row_count || ...
        numel(unique(string(trials.common_trial_id))) ~= ...
        K1.common_element_trial_count || ...
        numel(unique(string(trials.stratum_id))) ~= height(K1.strata)
    error('validate_stage8_1_validation_output:TrialCardinality', ...
        'Raw trials do not have the frozen paired cardinality.');
end
trials = sortrows(trials, 'evaluation_row_index');
expected = sortrows(expected, 'evaluation_row_index');
for field_index = 1:width(expected)
    field = expected.Properties.VariableNames{field_index};
    if ~column_equal_local(trials.(field), expected.(field))
        error('validate_stage8_1_validation_output:TrialRegistryMismatch', ...
            'Raw validation trials differ from the frozen %s registry.', field);
    end
end
states = ["K1";"K2_RESOLVED";"K2_UNRESOLVED"; ...
    "SEARCH_NOT_CONVERGED";"NUMERIC_RANK_DEFICIENT"; ...
    "OUT_OF_LOCAL_CELL"];
if any(~ismember(string(trials.state), states))
    error('validate_stage8_1_validation_output:StateVocabulary', ...
        'Validation states must use the frozen six-state classifier.');
end
for stratum_index = 1:height(K1.strata)
    selected = string(trials.stratum_id) == ...
        string(K1.strata.stratum_id(stratum_index));
    counts = groupcounts(string(trials.measurement_config_id(selected)));
    if numel(counts) ~= 2 || any(counts ~= K1.trials_per_stratum)
        error('validate_stage8_1_validation_output:StratumCoverage', ...
            'Each stratum/configuration must have the frozen trial count.');
    end
end
end

function verify_threshold_mapping_local(trials, calibration, K1)
thresholds = calibration.locked_thresholds;
for config_index = 1:numel(K1.measurement_config_ids)
    config_id = string(K1.measurement_config_ids(config_index));
    artifact = thresholds(string({thresholds.measurement_config_id}) == ...
        config_id);
    rows = string(trials.measurement_config_id) == config_id;
    if numel(artifact) ~= 1 || ~any(rows) || ...
            any(string(trials.threshold_artifact_hash(rows)) ~= ...
            string(artifact.threshold_artifact_hash))
        error('validate_stage8_1_validation_output:ThresholdMapping', ...
            'Every config row must reference its committed threshold hash.');
    end
end
end

function hashes = compute_hashes_local(trials, summary, paired, gate)
trials = sortrows(trials, 'evaluation_row_index');
hashes = struct( ...
    'validation_trial_set_hash', stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_TRIAL_SET_V1', trials), ...
    'validation_summary_hash', stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_SUMMARY_V1', summary), ...
    'paired_sensitivity_hash', stage8_stable_hash( ...
    'STAGE8_1_PAIRED_SENSITIVITY_V1', paired), ...
    'primary_gate_hash', stage8_stable_hash( ...
    'STAGE8_1_PRIMARY_GATE_V1', gate));
end

function verify_identity_local(plan, calibration, output, hashes)
actual = [string(output.stage8_stable_code_identity_hash), ...
    string(output.stage8_plan_hash), ...
    string(output.stage8_calibration_plan_hash), ...
    string(output.stage8_validation_plan_hash), ...
    string(output.measurement_registry_hash), ...
    string(output.calibration_evidence_bundle_hash), ...
    string(output.threshold_set_hash), ...
    string(output.validation_trial_set_hash), ...
    string(output.validation_summary_hash), ...
    string(output.paired_sensitivity_hash), ...
    string(output.primary_gate_hash), ...
    string(output.validation_execution_status)];
expected = [string(plan.identity.stage8_stable_code_identity_hash), ...
    string(plan.stage8_plan_hash), ...
    string(plan.stage8_calibration_plan_hash), ...
    string(plan.stage8_validation_plan_hash), ...
    string(plan.measurement_model_registry.registry_hash), ...
    string(calibration.calibration_evidence_bundle_hash), ...
    string(calibration.threshold_set_hash), ...
    string(hashes.validation_trial_set_hash), ...
    string(hashes.validation_summary_hash), ...
    string(hashes.paired_sensitivity_hash), ...
    string(hashes.primary_gate_hash), ...
    "STAGE8_1_K1_VALIDATION_COMPLETED"];
if ~isequal(actual, expected)
    error('validate_stage8_1_validation_output:ProvenanceMismatch', ...
        'Validation output hashes do not match current plan or raw trials.');
end
end

function pass = table_equal_local(left, right)
pass = istable(left) && istable(right) && ...
    strcmp(stage8_stable_hash(left), stage8_stable_hash(right));
end

function pass = column_equal_local(left, right)
if isstring(left) || iscellstr(left) || ischar(left) || ...
        isstring(right) || iscellstr(right) || ischar(right)
    pass = isequal(string(left), string(right));
else
    pass = isequal(left, right);
end
end
