function indices = stage8_k2_tfbc_registered_indices(angles_deg, provider)
%STAGE8_K2_TFBC_REGISTERED_INDICES O(K) exact registered lookup.

required = {'az_grid_deg','el_grid_deg','az_origin_deg','el_origin_deg', ...
    'az_step_deg','el_step_deg','key_tolerance_deg','index_lut'};
if ~(isstruct(provider) && isscalar(provider) && ...
        all(isfield(provider, required)))
    error('stage8_k2_tfbc_registered_indices:Provider', ...
        'The registered provider indexing contract is incomplete.');
end
if ~(isnumeric(angles_deg) && ismatrix(angles_deg) && ...
        size(angles_deg, 2) == 2 && ~isempty(angles_deg) && ...
        all(isfinite(angles_deg(:))))
    error('stage8_k2_tfbc_registered_indices:Angles', ...
        'angles_deg must be a finite K-by-2 matrix.');
end
K = size(angles_deg, 1);
indices = zeros(1, K);
for target = 1:K
    az_index = 1 + round((angles_deg(target, 1) - ...
        provider.az_origin_deg) / provider.az_step_deg);
    el_index = 1 + round((angles_deg(target, 2) - ...
        provider.el_origin_deg) / provider.el_step_deg);
    if az_index < 1 || az_index > numel(provider.az_grid_deg) || ...
            el_index < 1 || el_index > numel(provider.el_grid_deg) || ...
            abs(angles_deg(target, 1) - ...
            provider.az_grid_deg(az_index)) > provider.key_tolerance_deg || ...
            abs(angles_deg(target, 2) - ...
            provider.el_grid_deg(el_index)) > provider.key_tolerance_deg
        error('stage8_k2_tfbc_registered_indices:OffGrid', ...
            'REGISTERED_BACKBONE_CONTRACT_MISS_STOP: off-grid angle.');
    end
    column = double(provider.index_lut(az_index, el_index));
    if column < 1
        error('stage8_k2_tfbc_registered_indices:MissingKey', ...
            'REGISTERED_BACKBONE_CONTRACT_MISS_STOP: key is absent.');
    end
    indices(target) = column;
end
end
