function snapshot = stage8_k2_tfbc_provider_snapshot(provider)
%STAGE8_K2_TFBC_PROVIDER_SNAPSHOT Return immutable provider metadata.

required = {'schema_version','mode','fixed_measurement_hash', ...
    'domain_hash','phase_factor','numeric_class','artifact_hash', ...
    'provider_hash','validate_once_status', ...
    'timed_diagnostics_enabled','immutable', ...
    'G_single_or_certified','index_lut'};
if ~(isstruct(provider) && isscalar(provider) && ...
        all(isfield(provider, required)))
    error('stage8_k2_tfbc_provider_snapshot:Provider', ...
        'Provider metadata is incomplete.');
end
snapshot = struct('schema_version',provider.schema_version, ...
    'mode',provider.mode, ...
    'fixed_measurement_hash',provider.fixed_measurement_hash, ...
    'domain_hash',provider.domain_hash, ...
    'phase_factor',provider.phase_factor, ...
    'numeric_class',provider.numeric_class, ...
    'artifact_hash',provider.artifact_hash, ...
    'provider_hash',provider.provider_hash, ...
    'validate_once_status',provider.validate_once_status, ...
    'timed_diagnostics_enabled',provider.timed_diagnostics_enabled, ...
    'immutable',provider.immutable, ...
    'entry_count',size(provider.G_single_or_certified, 2), ...
    'projected_dimension',size(provider.G_single_or_certified, 1), ...
    'mapped_entry_count',nnz(provider.index_lut));
end
