function output = stage8_k2_tfbc_run_runtime( ...
    repo_dir, runtime_root, comparison_id)
%STAGE8_K2_TFBC_RUN_RUNTIME Run one resumable 72x20 paired comparison.

comparison_id = upper(char(string(comparison_id)));
if ~ismember(comparison_id, {'CACHE_VS_LEGACY','CACHE_VS_DIRECT_G'})
    error('stage8_k2_tfbc_run_runtime:Comparison', ...
        'Unsupported comparison: %s.', comparison_id);
end
runtime_root = char(java.io.File( ...
    char(string(runtime_root))).getCanonicalPath());
correctness_path = fullfile(runtime_root, 'correctness', ...
    'correctness_output.mat');
if ~isfile(correctness_path)
    error('stage8_k2_tfbc_run_runtime:Correctness', ...
        '72-trial correctness must pass before formal timing.');
end
correctness_loaded = load(correctness_path, 'output');
assert(strcmp(correctness_loaded.output.status, ...
    'STAGE8_K2_TFBC_CORRECTNESS_PASS'));
fixture = stage8_k2_tfbc_build_fixture( ...
    repo_dir, runtime_root, struct('include_trials',true));
[full_schedule, schedule_hash] = ...
    stage8_k2_tfbc_build_timing_schedule(fixture.registry);
schedule = full_schedule(full_schedule.comparison_id == ...
    string(comparison_id), :);
freeze_dir = fullfile(runtime_root, 'freeze');
if ~isfolder(freeze_dir), mkdir(freeze_dir); end
writetable(full_schedule, fullfile(freeze_dir, 'timing_schedule.csv'));
pair_dir = fullfile(runtime_root, 'runtime', lower(comparison_id));
if ~isfolder(pair_dir), mkdir(pair_dir); end

stage8_k2_tcc_audit_state('CONFIGURE', struct('mode','OFF'));
warmup_local(fixture, comparison_id, schedule_hash, pair_dir);
payloads = cell(height(schedule), 1);
for row_index = 1:height(schedule)
    row = schedule(row_index, :);
    checkpoint_path = fullfile(pair_dir, sprintf('pair_%04d.mat', ...
        row.global_pair_index));
    if isfile(checkpoint_path)
        loaded = load(checkpoint_path, 'payload');
        if isfield(loaded, 'payload') && ...
                strcmp(loaded.payload.schedule_hash, schedule_hash) && ...
                strcmp(loaded.payload.fixture_hash, fixture.fixture_hash)
            payloads{row_index} = loaded.payload;
            continue;
        end
    end
    trial = fixture.trials{row.trial_index};
    identity = stage8_k2_tfbc_identity_for_trial(fixture, trial);
    provider = identity.provider_timed;
    baseline_mode = char(row.baseline_mode);
    if row.pair_order == "AB"
        [baseline_sec, baseline_hash] = timed_fit_local( ...
            trial, fixture.context, provider, baseline_mode);
        [cache_sec, cache_hash] = timed_fit_local( ...
            trial, fixture.context, provider, 'REGISTERED_CACHE');
    else
        [cache_sec, cache_hash] = timed_fit_local( ...
            trial, fixture.context, provider, 'REGISTERED_CACHE');
        [baseline_sec, baseline_hash] = timed_fit_local( ...
            trial, fixture.context, provider, baseline_mode);
    end
    if ~strcmp(baseline_hash, cache_hash)
        error('stage8_k2_tfbc_run_runtime:Checksum', ...
            'FIXED_BACKBONE_CACHE_SEMANTIC_MISMATCH_STOP at pair %d.', ...
            row.global_pair_index);
    end
    result = struct('global_pair_index',row.global_pair_index, ...
        'comparison_id',string(comparison_id), ...
        'trial_index',row.trial_index, 'trial_id',row.trial_id, ...
        'fixed_measurement_hash',string(trial.model.fixed_measurement_hash), ...
        'repeat_index',row.repeat_index, 'pair_order',row.pair_order, ...
        'baseline_mode',row.baseline_mode, ...
        'treatment_mode',row.treatment_mode, ...
        'baseline_runtime_sec',baseline_sec, ...
        'cache_runtime_sec',cache_sec, ...
        'paired_difference_sec',baseline_sec - cache_sec, ...
        'result_checksum_hash',string(cache_hash), ...
        'checksum_match',true);
    payload = struct('schedule_hash',schedule_hash, ...
        'fixture_hash',fixture.fixture_hash, 'result',result);
    atomic_save_local(checkpoint_path, payload);
    payloads{row_index} = payload;
    if mod(row_index, 10) == 0 || row_index == height(schedule)
        fprintf('TFBC RUNTIME %s %d/%d trial=%s\n', ...
            comparison_id, row_index, height(schedule), char(row.trial_id));
    end
end
results = cellfun(@(x) x.result, payloads, 'UniformOutput', false);
raw = struct2table(vertcat(results{:}));
summary = summarize_local(raw, fixture.registry);
bootstrap = stage8_k2_tecs_paired_bootstrap(raw, fixture.registry);
output = struct('schema_version','STAGE8_K2_TFBC_RUNTIME_V1', ...
    'comparison_id',comparison_id, 'schedule_hash',schedule_hash, ...
    'fixture_hash',fixture.fixture_hash, 'raw',raw, 'summary',summary, ...
    'bootstrap',bootstrap, 'pair_count',height(raw), ...
    'checksum_match_count',nnz(raw.checksum_match), ...
    'status','FORMAL_PAIRED_RUNTIME_COMPLETE');
writetable(raw, fullfile(pair_dir, 'raw_pairs.csv'));
writetable(summary, fullfile(pair_dir, 'runtime_summary.csv'));
save(fullfile(pair_dir, 'runtime_output.mat'), 'output', '-v7');
end

function warmup_local(fixture, comparison_id, schedule_hash, pair_dir)
path_now = fullfile(pair_dir, 'formal_warmup.mat');
if isfile(path_now)
    loaded = load(path_now, 'warmup');
    if isfield(loaded, 'warmup') && ...
            strcmp(loaded.warmup.schedule_hash, schedule_hash)
        return;
    end
end
baseline_mode = 'LEGACY_FULL';
if strcmp(comparison_id, 'CACHE_VS_DIRECT_G')
    baseline_mode = 'DIRECT_G_ONLY';
end
hashes = strings(numel(fixture.identities), 2);
for identity_index = 1:numel(fixture.identities)
    target_hash = fixture.identities(identity_index).fixed_measurement_hash;
    trial_index = find(cellfun(@(x) strcmp( ...
        x.model.fixed_measurement_hash, target_hash), fixture.trials), 1);
    trial = fixture.trials{trial_index};
    provider = fixture.identities(identity_index).provider_timed;
    [~, hashes(identity_index, 1)] = timed_fit_local( ...
        trial, fixture.context, provider, baseline_mode);
    [~, hashes(identity_index, 2)] = timed_fit_local( ...
        trial, fixture.context, provider, 'REGISTERED_CACHE');
end
assert(all(hashes(:, 1) == hashes(:, 2)), ...
    'stage8_k2_tfbc_run_runtime:WarmupChecksum');
warmup = struct('schedule_hash',schedule_hash, ...
    'comparison_id',comparison_id, 'result_hashes',hashes, ...
    'status','FORMAL_WARMUP_COMPLETE');
save(path_now, 'warmup', '-v7');
end

function [runtime_sec, hash] = timed_fit_local(trial, context, provider, mode)
run_context = context;
run_context.fixed_registered_manifold_provider = provider;
run_context.fixed_manifold_mode = mode;
if isfield(run_context, 't4_manifold_provider')
    run_context = rmfield(run_context, 't4_manifold_provider');
end
if isfield(run_context, 'manifold_provider')
    run_context = rmfield(run_context, 'manifold_provider');
end
clock = tic;
[result, diagnostics] = stage8_k2_tp_fit_safe( ...
    trial.Y_element, trial.model, run_context);
runtime_sec = toc(clock);
projection = stage8_k2_tecs_root_projection( ...
    result, diagnostics, 'CACHE_OFF_BASELINE');
hash = stage8_k2_tecs_sha256( ...
    'STAGE8_K2_TFBC_RESULT_V1', projection);
end

function summary = summarize_local(raw, registry)
rows = cell(72 + 3, 1);
for trial_index = 1:72
    trial_id = string(registry.trial_id(trial_index));
    subset = raw(raw.trial_id == trial_id, :);
    rows{trial_index} = summary_row_local('TRIAL', trial_id, ...
        subset.fixed_measurement_hash(1), height(subset), ...
        median(subset.baseline_runtime_sec), ...
        median(subset.cache_runtime_sec), ...
        median(subset.paired_difference_sec), ...
        median(subset.paired_difference_sec(subset.pair_order == "AB")), ...
        median(subset.paired_difference_sec(subset.pair_order == "BA")));
end
identity_hashes = unique(raw.fixed_measurement_hash, 'stable');
all_trial_rows = vertcat(rows{1:72});
trial_identity_hashes = string({all_trial_rows.fixed_measurement_hash});
for identity_index = 1:2
    members = trial_identity_hashes == identity_hashes(identity_index);
    trial_rows = all_trial_rows(members);
    rows{72 + identity_index} = summary_row_local( ...
        'IDENTITY', identity_hashes(identity_index), ...
        identity_hashes(identity_index), sum([trial_rows.pair_count]), ...
        sum([trial_rows.baseline_runtime_sec]), ...
        sum([trial_rows.cache_runtime_sec]), ...
        sum([trial_rows.paired_difference_sec]), ...
        sum([trial_rows.ab_difference_sec]), ...
        sum([trial_rows.ba_difference_sec]));
end
trial_rows = vertcat(rows{1:72});
rows{75} = summary_row_local('OVERALL', "ALL_72_TRIALS", ...
    "MULTIPLE_IDENTITIES", sum([trial_rows.pair_count]), ...
    sum([trial_rows.baseline_runtime_sec]), ...
    sum([trial_rows.cache_runtime_sec]), ...
    sum([trial_rows.paired_difference_sec]), ...
    sum([trial_rows.ab_difference_sec]), ...
    sum([trial_rows.ba_difference_sec]));
summary = struct2table(vertcat(rows{:}));
end

function row = summary_row_local(row_type, row_id, identity, count, ...
    baseline, cache, difference, ab, ba)
row = struct('row_type',string(row_type), 'row_id',string(row_id), ...
    'fixed_measurement_hash',string(identity), 'pair_count',count, ...
    'baseline_runtime_sec',baseline, 'cache_runtime_sec',cache, ...
    'paired_difference_sec',difference, 'ab_difference_sec',ab, ...
    'ba_difference_sec',ba, ...
    'runtime_reduction_pct',100 * difference / baseline, ...
    'speedup_ratio',baseline / cache);
end

function atomic_save_local(path_now, payload)
temporary = [path_now, '.tmp'];
if isfile(temporary), delete(temporary); end
save(temporary, 'payload', '-v7');
[moved, message] = movefile(temporary, path_now, 'f');
if ~moved
    error('stage8_k2_tfbc_run_runtime:Checkpoint', '%s', message);
end
end
