function output = stage8_k2_tfbc_run_lifecycle(repo_dir, runtime_root)
%STAGE8_K2_TFBC_RUN_LIFECYCLE Measure cold build/load outside online timing.

runtime_root = char(java.io.File( ...
    char(string(runtime_root))).getCanonicalPath());
primary_path = fullfile(runtime_root, 'runtime', ...
    'cache_vs_legacy', 'runtime_output.mat');
if ~isfile(primary_path)
    error('stage8_k2_tfbc_run_lifecycle:PrimaryRuntime', ...
        'Primary runtime must complete before lifecycle analysis.');
end
loaded_runtime = load(primary_path, 'output');
fixture = stage8_k2_tfbc_build_fixture( ...
    repo_dir, runtime_root, struct('include_trials',false));
rows = repmat(struct('fixed_measurement_hash',"", ...
    'noise_profile_id',"", 'repeat_index',0, ...
    'cold_build_sec',NaN, 'cold_load_sec',NaN), ...
    numel(fixture.identities) * 20, 1);
row_index = 0;
for identity_index = 1:numel(fixture.identities)
    identity = fixture.identities(identity_index);
    provider_path = fullfile(runtime_root, 'artifacts', ...
        ['provider_', identity.fixed_measurement_hash, '.mat']);
    for repeat_index = 1:20
        row_index = row_index + 1;
        build_clock = tic;
        [dictionary, ~] = stage8_k2_tcc_build_registered_dictionary( ...
            identity.model, fixture.context.plan.local_domain, struct());
        artifact = stage8_k2_tecs_promote_c1_artifact(dictionary);
        built_provider = stage8_k2_tfbc_build_provider( ...
            identity.model, fixture.context.plan.local_domain, ...
            struct('artifact',artifact, ...
            'timed_diagnostics_enabled',false));
        stage8_k2_tfbc_validate_provider(built_provider, ...
            identity.model, fixture.context.plan.local_domain);
        cold_build_sec = toc(build_clock);

        load_clock = tic;
        loaded = load(provider_path, 'provider');
        stage8_k2_tfbc_validate_provider(loaded.provider, ...
            identity.model, fixture.context.plan.local_domain);
        cold_load_sec = toc(load_clock);
        rows(row_index) = struct( ...
            'fixed_measurement_hash',string(identity.fixed_measurement_hash), ...
            'noise_profile_id',string(identity.noise_profile_id), ...
            'repeat_index',repeat_index, ...
            'cold_build_sec',cold_build_sec, ...
            'cold_load_sec',cold_load_sec);
    end
end
raw = struct2table(rows);
identity_rows = loaded_runtime.output.summary( ...
    loaded_runtime.output.summary.row_type == "IDENTITY", :);
summary_rows = repmat(struct('fixed_measurement_hash',"", ...
    'noise_profile_id',"", 'cold_build_median_sec',NaN, ...
    'cold_load_median_sec',NaN, 'online_saving_36_trials_sec',NaN, ...
    'per_trial_saving_sec',NaN, 'cold_build_break_even_trials',Inf, ...
    'cold_load_break_even_trials',Inf), numel(fixture.identities), 1);
for identity_index = 1:numel(fixture.identities)
    identity = fixture.identities(identity_index);
    subset = raw(raw.fixed_measurement_hash == ...
        string(identity.fixed_measurement_hash), :);
    runtime_row = identity_rows(identity_rows.fixed_measurement_hash == ...
        string(identity.fixed_measurement_hash), :);
    saving = runtime_row.paired_difference_sec;
    per_trial = saving / 36;
    build_median = median(subset.cold_build_sec);
    load_median = median(subset.cold_load_sec);
    build_break_even = Inf;
    load_break_even = Inf;
    if per_trial > 0
        build_break_even = ceil(build_median / per_trial);
        load_break_even = ceil(load_median / per_trial);
    end
    summary_rows(identity_index) = struct( ...
        'fixed_measurement_hash',string(identity.fixed_measurement_hash), ...
        'noise_profile_id',string(identity.noise_profile_id), ...
        'cold_build_median_sec',build_median, ...
        'cold_load_median_sec',load_median, ...
        'online_saving_36_trials_sec',saving, ...
        'per_trial_saving_sec',per_trial, ...
        'cold_build_break_even_trials',build_break_even, ...
        'cold_load_break_even_trials',load_break_even);
end
summary = struct2table(summary_rows);
output = struct('schema_version','STAGE8_K2_TFBC_LIFECYCLE_V1', ...
    'raw',raw, 'summary',summary, 'repeat_count_per_identity',20, ...
    'status','COLD_BUILD_LOAD_MEASUREMENT_COMPLETE');
lifecycle_dir = fullfile(runtime_root, 'lifecycle');
if ~isfolder(lifecycle_dir), mkdir(lifecycle_dir); end
writetable(raw, fullfile(lifecycle_dir, 'lifecycle_raw.csv'));
writetable(summary, fullfile(lifecycle_dir, 'lifecycle_summary.csv'));
save(fullfile(lifecycle_dir, 'lifecycle_output.mat'), 'output', '-v7');
end
