function info = stage8_k2_tfbc_validate_provider(provider, model, domain)
%STAGE8_K2_TFBC_VALIDATE_PROVIDER Fully validate a loaded provider once.

required = {'provider_hash','fixed_measurement_hash','domain_hash', ...
    'phase_factor','immutable','index_lut','G_single_or_certified', ...
    'G_single_exact_shape','G_pair_first_exact_shape', ...
    'G_pair_second_exact_shape','artifact_hash'};
if ~(isstruct(provider) && isscalar(provider) && ...
        all(isfield(provider, required)) && provider.immutable)
    error('stage8_k2_tfbc_validate_provider:Contract', ...
        'Loaded provider contract is incomplete.');
end
semantic = rmfield(provider, 'provider_hash');
actual_hash = stage8_k2_tecs_sha256( ...
    'STAGE8_K2_TFBC_PROVIDER_V1', semantic);
if ~strcmp(actual_hash, provider.provider_hash)
    error('stage8_k2_tfbc_validate_provider:Hash', ...
        'Loaded provider semantic hash mismatch.');
end
if ~strcmp(provider.fixed_measurement_hash, ...
        char(string(model.fixed_measurement_hash))) || ...
        ~strcmp(provider.domain_hash, char(string(domain.domain_hash))) || ...
        provider.phase_factor ~= 1 || model.phase_factor ~= 1 || ...
        nnz(provider.index_lut) ~= 21 || ...
        size(provider.G_single_exact_shape, 2) ~= 21 || ...
        size(provider.G_pair_first_exact_shape, 2) ~= 21 || ...
        size(provider.G_pair_second_exact_shape, 2) ~= 21
    error('stage8_k2_tfbc_validate_provider:Identity', ...
        'Loaded provider does not match the requested identity/domain.');
end
info = struct('status','VALIDATE_ONCE_COMPLETE', ...
    'provider_hash',provider.provider_hash, ...
    'artifact_hash',provider.artifact_hash, ...
    'fixed_measurement_hash',provider.fixed_measurement_hash, ...
    'domain_hash',provider.domain_hash, 'entry_count',21);
end
