function [G, dG, info] = stage8_k2_tfbc_get_manifold( ...
    angles_deg, model, local_domain, provider, options)
%STAGE8_K2_TFBC_GET_MANIFOLD Dispatch one fixed registered G-only build.

if nargin < 5 || isempty(options), options = struct(); end
options = normalize_options_local(options);
mode = options.mode;
if options.derivatives_required
    if ~strcmp(mode, 'LEGACY_FULL')
        contract_miss_local(provider, size(angles_deg, 1), false);
        error('stage8_k2_tfbc_get_manifold:Derivatives', ...
            ['REGISTERED_BACKBONE_CONTRACT_MISS_STOP: finite registered ', ...
            'providers do not serve derivatives.']);
    end
    [G, dG, info] = build_full_sequential_local_manifold( ...
        angles_deg, model, struct('rank_multiplier', ...
        options.rank_multiplier));
    info = extend_info_local(info, mode, 0, 0, 0, 0, '');
    return;
end

dG = struct('azimuth',[], 'elevation',[], 'coordinate','radian');
switch mode
    case 'LEGACY_FULL'
        [G, ~, info] = build_full_sequential_local_manifold( ...
            angles_deg, model, struct('rank_multiplier', ...
            options.rank_multiplier));
        info = extend_info_local(info, mode, 0, 0, 0, 0, '');
    case 'DIRECT_G_ONLY'
        [G, direct_info] = stage8_k2_tcc_build_g_direct( ...
            angles_deg, model, struct());
        [rank_value, singular_values, threshold] = ...
            stage8_k2_tcc_stable_matrix_rank(G, options.rank_multiplier);
        info = base_info_local(angles_deg, model, G, rank_value, ...
            singular_values, threshold, mode, '');
        info.direct_g_only_flag = direct_info.direct_g_only_flag;
    case 'REGISTERED_CACHE'
        try
            validate_cheap_guard_local(provider, model, local_domain);
            indices = stage8_k2_tfbc_registered_indices( ...
                angles_deg, provider);
            if numel(indices) == 1
                G = provider.G_single_exact_shape(:, indices);
            elseif numel(indices) == 2
                G = [provider.G_pair_first_exact_shape(:, indices(1)), ...
                    provider.G_pair_second_exact_shape(:, indices(2))];
            else
                error('stage8_k2_tfbc_get_manifold:TargetCount', ...
                    'Only the frozen K1/K2 accumulation shapes are certified.');
            end
        catch exception
            contract_miss_local(provider, size(angles_deg, 1), ...
                contains(exception.identifier, 'OffGrid'));
            if options.allow_legacy_fallback
                [G, ~, info] = build_full_sequential_local_manifold( ...
                    angles_deg, model, struct('rank_multiplier', ...
                    options.rank_multiplier));
                info = extend_info_local(info, mode, 0, 1, 1, 0, '');
                return;
            end
            error('stage8_k2_tfbc_get_manifold:ContractMiss', ...
                'REGISTERED_BACKBONE_CONTRACT_MISS_STOP: %s', ...
                exception.message);
        end
        [rank_value, singular_values, threshold] = ...
            stage8_k2_tcc_stable_matrix_rank(G, options.rank_multiplier);
        hit_count = size(angles_deg, 1);
        info = base_info_local(angles_deg, model, G, rank_value, ...
            singular_values, threshold, mode, provider.artifact_hash);
        info = extend_info_local(info, mode, hit_count, 0, 0, 1, ...
            provider.artifact_hash);
        if provider.timed_diagnostics_enabled
            stage8_k2_tfbc_diagnostics_state( ...
                'RECORD_HIT', size(angles_deg, 1));
        end
    otherwise
        error('stage8_k2_tfbc_get_manifold:Mode', ...
            'Unsupported fixed manifold mode: %s.', mode);
end
end

function options = normalize_options_local(options)
if ~(isstruct(options) && isscalar(options))
    error('stage8_k2_tfbc_get_manifold:Options', ...
        'options must be a scalar struct.');
end
allowed = {'mode','rank_multiplier','derivatives_required', ...
    'allow_legacy_fallback'};
unknown = setdiff(fieldnames(options), allowed);
if ~isempty(unknown)
    error('stage8_k2_tfbc_get_manifold:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
defaults = struct('mode','LEGACY_FULL', 'rank_multiplier',1, ...
    'derivatives_required',false, 'allow_legacy_fallback',false);
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(options, names{index})
        options.(names{index}) = defaults.(names{index});
    end
end
options.mode = upper(char(string(options.mode)));
if ~ismember(options.mode, ...
        {'LEGACY_FULL','DIRECT_G_ONLY','REGISTERED_CACHE'}) || ...
        ~(isscalar(options.rank_multiplier) && ...
        options.rank_multiplier == 1)
    error('stage8_k2_tfbc_get_manifold:OptionsContract', ...
        'Mode or frozen rank multiplier is invalid.');
end
options.derivatives_required = logical(options.derivatives_required);
options.allow_legacy_fallback = logical(options.allow_legacy_fallback);
end

function validate_cheap_guard_local(provider, model, domain)
required = {'schema_version','mode','fixed_measurement_hash', ...
    'domain_hash','phase_factor','numeric_class', ...
    'G_single_or_certified','artifact_hash','validate_once_status', ...
    'G_single_exact_shape','G_pair_first_exact_shape', ...
    'G_pair_second_exact_shape','numeric_representative', ...
    'formal_contract_miss_stop','timed_diagnostics_enabled','immutable'};
if ~(isstruct(provider) && isscalar(provider) && ...
        all(isfield(provider, required)) && provider.immutable && ...
        provider.formal_contract_miss_stop && ...
        strcmp(provider.schema_version, 'STAGE8_K2_TFBC_PROVIDER_V1') && ...
        strcmp(provider.mode, 'REGISTERED_CACHE') && ...
        strcmp(provider.validate_once_status, 'VALIDATE_ONCE_COMPLETE') && ...
        strcmp(provider.fixed_measurement_hash, ...
        char(string(model.fixed_measurement_hash))) && ...
        strcmp(provider.domain_hash, char(string(domain.domain_hash))) && ...
        provider.phase_factor == 1 && model.phase_factor == 1 && ...
        strcmp(provider.numeric_class, class(provider.G_single_or_certified)))
    error('stage8_k2_tfbc_get_manifold:Identity', ...
        'Provider identity scalar guard failed.');
end
end

function info = base_info_local(angles, model, G, rank_value, sigma, ...
    threshold, mode, artifact_hash)
info = struct('rank_Gseq',rank_value, ...
    'singular_values_Gseq',sigma, ...
    'rank_threshold_Gseq',threshold, ...
    'target_angles_deg',angles, ...
    'fixed_measurement_hash',char(string(model.fixed_measurement_hash)), ...
    'phase_factor',1, 'num_svd',1, 'Gseq_size',size(G), ...
    'full_receive_geometry_used_flag',false, ...
    'factorized_scoring_used_flag',false, ...
    'fixed_manifold_mode',mode, 'artifact_hash',artifact_hash);
end

function info = extend_info_local(info, mode, hits, misses, fallbacks, ...
    eligible_calls, artifact_hash)
info.fixed_manifold_mode = mode;
info.eligible_registered_call_count = eligible_calls;
info.eligible_registered_column_count = hits;
info.cache_hit_count = hits;
info.cache_miss_count = misses;
info.fallback_count = fallbacks;
info.identity_rejection_count = 0;
info.artifact_hash = artifact_hash;
end

function contract_miss_local(provider, K, off_grid)
if isstruct(provider) && isscalar(provider) && ...
        isfield(provider, 'timed_diagnostics_enabled') && ...
        provider.timed_diagnostics_enabled
    stage8_k2_tfbc_diagnostics_state('RECORD_MISS', K, off_grid);
end
end
