function [provider, info] = stage8_k2_tfbc_build_provider( ...
    model, local_domain, options)
%STAGE8_K2_TFBC_BUILD_PROVIDER Build one immutable registered provider.

if nargin < 3 || isempty(options), options = struct(); end
options = normalize_options_local(options);
validate_inputs_local(model, local_domain);
clock = tic;
dictionary_info = struct();
if ~isempty(options.artifact)
    artifact = options.artifact;
elseif ~isempty(options.dictionary)
    artifact = stage8_k2_tecs_promote_c1_artifact(options.dictionary);
else
    [dictionary, dictionary_info] = ...
        stage8_k2_tcc_build_registered_dictionary( ...
        model, local_domain, struct());
    artifact = stage8_k2_tecs_promote_c1_artifact(dictionary);
end
stage8_k2_tecs_validate_c1_value( ...
    artifact, char(string(model.fixed_measurement_hash)));

required = {'local_domain_hash','phase_factor','numeric_class', ...
    'key_tolerance_deg','key_angles_deg','G','artifact_hash', ...
    'validate_once_status'};
if ~all(isfield(artifact, required)) || ...
        ~strcmp(char(string(artifact.local_domain_hash)), ...
        char(string(local_domain.domain_hash))) || ...
        double(artifact.phase_factor) ~= 1 || ...
        ~strcmp(char(string(artifact.numeric_class)), class(artifact.G)) || ...
        ~isnumeric(artifact.G) || any(~isfinite(artifact.G(:)))
    error('stage8_k2_tfbc_build_provider:ArtifactIdentity', ...
        'The C1 artifact does not match the fixed registered domain.');
end

az_grid = double(local_domain.az_grid_deg(:).');
el_grid = double(local_domain.el_grid_deg(:).');
[az_step, el_step] = regular_steps_local(az_grid, el_grid);
key_angles = double(artifact.key_angles_deg);
key_count = numel(az_grid) * numel(el_grid);
if ~isequal(size(key_angles), [key_count, 2]) || ...
        size(artifact.G, 2) ~= key_count
    error('stage8_k2_tfbc_build_provider:ArtifactCardinality', ...
        'The artifact is not the complete registered Cartesian domain.');
end
index_lut = zeros(numel(az_grid), numel(el_grid), 'uint8');
tolerance = double(artifact.key_tolerance_deg);
for column = 1:key_count
    az_index = 1 + round((key_angles(column, 1) - az_grid(1)) / az_step);
    el_index = 1 + round((key_angles(column, 2) - el_grid(1)) / el_step);
    if az_index < 1 || az_index > numel(az_grid) || ...
            el_index < 1 || el_index > numel(el_grid) || ...
            abs(key_angles(column, 1) - az_grid(az_index)) > tolerance || ...
            abs(key_angles(column, 2) - el_grid(el_index)) > tolerance || ...
            index_lut(az_index, el_index) ~= 0
        error('stage8_k2_tfbc_build_provider:ArtifactKeys', ...
            'Artifact keys are not a one-to-one exact registered mapping.');
    end
    index_lut(az_index, el_index) = uint8(column);
end
if any(index_lut(:) == 0)
    error('stage8_k2_tfbc_build_provider:ArtifactCoverage', ...
        'Artifact keys do not cover the registered domain.');
end

projected_dimension = size(artifact.G, 1);
G_single_shape = complex(zeros(projected_dimension, key_count));
G_pair_first_shape = complex(zeros(projected_dimension, key_count));
G_pair_second_shape = complex(zeros(projected_dimension, key_count));
for column = 1:key_count
    angle = key_angles(column, :);
    G_single_shape(:, column) = stage8_k2_tcc_build_g_direct( ...
        angle, model, struct());
    G_pair = stage8_k2_tcc_build_g_direct( ...
        [angle;angle], model, struct());
    G_pair_first_shape(:, column) = G_pair(:, 1);
    G_pair_second_shape(:, column) = G_pair(:, 2);
    legacy_single = build_full_sequential_local_manifold( ...
        angle, model, struct('rank_multiplier', 1));
    legacy_pair = build_full_sequential_local_manifold( ...
        [angle;angle], model, struct('rank_multiplier', 1));
    if ~isequal(G_single_shape(:, column), legacy_single(:, 1)) || ...
            ~isequal(G_pair_first_shape(:, column), legacy_pair(:, 1)) || ...
            ~isequal(G_pair_second_shape(:, column), legacy_pair(:, 2))
        error('stage8_k2_tfbc_build_provider:ShapeCertification', ...
            ['Frozen K1/K2 BLAS-shape representatives are not exactly ', ...
            'equal to the legacy producer.']);
    end
end

provider = struct( ...
    'schema_version','STAGE8_K2_TFBC_PROVIDER_V1', ...
    'mode','REGISTERED_CACHE', ...
    'fixed_measurement_hash',char(string(model.fixed_measurement_hash)), ...
    'domain_hash',char(string(local_domain.domain_hash)), ...
    'phase_factor',1, ...
    'numeric_class',class(artifact.G), ...
    'az_grid_deg',az_grid, ...
    'el_grid_deg',el_grid, ...
    'az_origin_deg',az_grid(1), ...
    'el_origin_deg',el_grid(1), ...
    'az_step_deg',az_step, ...
    'el_step_deg',el_step, ...
    'key_tolerance_deg',tolerance, ...
    'index_lut',index_lut, ...
    'G_single_or_certified',artifact.G, ...
    'G_single_exact_shape',G_single_shape, ...
    'G_pair_first_exact_shape',G_pair_first_shape, ...
    'G_pair_second_exact_shape',G_pair_second_shape, ...
    'numeric_representative', ...
        'FROZEN_K1_K2_BLAS_SHAPE_CERTIFIED', ...
    'source_numeric_representative', ...
        'BALANCED_SINGLE_PAIR_DIRECT_ACCUMULATION_MIDPOINT', ...
    'artifact_hash',char(string(artifact.artifact_hash)), ...
    'source_dictionary_hash',char(string(artifact.source_dictionary_hash)), ...
    'validate_once_status','VALIDATE_ONCE_COMPLETE', ...
    'formal_contract_miss_stop',true, ...
    'timed_diagnostics_enabled', ...
        logical(options.timed_diagnostics_enabled), ...
    'immutable',true);
provider.provider_hash = stage8_k2_tecs_sha256( ...
    'STAGE8_K2_TFBC_PROVIDER_V1', provider);
info = struct('status','IMMUTABLE_FIXED_BACKBONE_PROVIDER_READY', ...
    'artifact_hash',provider.artifact_hash, ...
    'fixed_measurement_hash',provider.fixed_measurement_hash, ...
    'domain_hash',provider.domain_hash, ...
    'key_count',key_count, ...
    'provider_hash',provider.provider_hash, ...
    'build_runtime_sec',toc(clock), ...
    'dictionary_info',dictionary_info);
end

function options = normalize_options_local(options)
if ~(isstruct(options) && isscalar(options))
    error('stage8_k2_tfbc_build_provider:Options', ...
        'options must be a scalar struct.');
end
allowed = {'artifact','dictionary','timed_diagnostics_enabled'};
unknown = setdiff(fieldnames(options), allowed);
if ~isempty(unknown)
    error('stage8_k2_tfbc_build_provider:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
defaults = struct('artifact',[], 'dictionary',[], ...
    'timed_diagnostics_enabled',false);
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(options, names{index})
        options.(names{index}) = defaults.(names{index});
    end
end
if ~isempty(options.artifact) && ~isempty(options.dictionary)
    error('stage8_k2_tfbc_build_provider:ArtifactSource', ...
        'Specify an artifact or a dictionary, not both.');
end
if ~(islogical(options.timed_diagnostics_enabled) && ...
        isscalar(options.timed_diagnostics_enabled))
    error('stage8_k2_tfbc_build_provider:Diagnostics', ...
        'timed_diagnostics_enabled must be scalar logical.');
end
end

function validate_inputs_local(model, domain)
required_model = {'fixed_measurement_hash','phase_factor','Wseq','Tseq'};
required_domain = {'az_grid_deg','el_grid_deg','candidate_points_deg', ...
    'domain_hash'};
if ~(isstruct(model) && isscalar(model) && ...
        all(isfield(model, required_model)) && model.phase_factor == 1)
    error('stage8_k2_tfbc_build_provider:Model', ...
        'model is not the fixed factor-1 measurement identity.');
end
if ~(isstruct(domain) && isscalar(domain) && ...
        all(isfield(domain, required_domain)))
    error('stage8_k2_tfbc_build_provider:Domain', ...
        'local_domain is incomplete.');
end
end

function [az_step, el_step] = regular_steps_local(az_grid, el_grid)
az_delta = diff(az_grid);
el_delta = diff(el_grid);
if isempty(az_delta) || isempty(el_delta) || ...
        any(az_delta <= 0) || any(el_delta <= 0) || ...
        max(abs(az_delta - az_delta(1))) > 64 * eps(max(abs(az_grid))) || ...
        max(abs(el_delta - el_delta(1))) > 64 * eps(max(abs(el_grid)))
    error('stage8_k2_tfbc_build_provider:RegularGrid', ...
        'The fixed registered domain must be a regular Cartesian grid.');
end
az_step = az_delta(1);
el_step = el_delta(1);
end
