function output = stage8_k2_tfbc_run_correctness(repo_dir, runtime_root)
%STAGE8_K2_TFBC_RUN_CORRECTNESS Run resumable 72-trial semantic equality.

runtime_root = char(java.io.File( ...
    char(string(runtime_root))).getCanonicalPath());
checkpoint_dir = fullfile(runtime_root, 'correctness', 'trials');
if ~isfolder(checkpoint_dir), mkdir(checkpoint_dir); end
fixture = stage8_k2_tfbc_build_fixture( ...
    repo_dir, runtime_root, struct('include_trials',true));
static_summary = stage8_k2_tfbc_run_static_certification(fixture);
writetable(static_summary, fullfile(runtime_root, 'correctness', ...
    'static_certification.csv'));
trial_payloads = cell(height(fixture.registry), 1);
for trial_index = 1:height(fixture.registry)
    checkpoint_path = fullfile(checkpoint_dir, sprintf( ...
        'trial_%03d.mat', trial_index));
    if isfile(checkpoint_path)
        loaded = load(checkpoint_path, 'payload');
        if isfield(loaded, 'payload') && ...
                strcmp(loaded.payload.fixture_hash, fixture.fixture_hash)
            trial_payloads{trial_index} = loaded.payload;
            fprintf('TFBC CORRECTNESS RESUME %d/72 %s\n', trial_index, ...
                char(fixture.registry.trial_id(trial_index)));
            continue;
        end
    end
    spec = fixture.registry(trial_index, :);
    trial = fixture.trials{trial_index};
    identity = stage8_k2_tfbc_identity_for_trial(fixture, trial);
    full_data = build_stage8_full_data_from_element( ...
        trial.Y_element, trial.model, struct( ...
        'data_role','SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
    metadata = struct('trial_id',char(spec.trial_id), ...
        'noise_profile_id',char(spec.noise_profile_id), ...
        'L',double(spec.L), 'snr_db',double(spec.snr_db), ...
        'profile_id',char(spec.profile_id), ...
        'element_trial_hash',trial.element_trial_hash, ...
        'fixed_measurement_hash',trial.model.fixed_measurement_hash);
    audit_config = struct('mode','QUERY', ...
        'dictionary',identity.dictionary, 'model',trial.model, ...
        'Zseq_white',full_data.Zseq_white, 'trial_metadata',metadata);

    stage8_k2_tcc_audit_state('CONFIGURE', audit_config);
    [legacy_result, ~, legacy_hash, ...
        legacy_projection] = stage8_k2_tfbc_fit_mode( ...
        trial, fixture.context, identity.provider_diagnostic, ...
        'LEGACY_FULL');
    legacy_query = stage8_k2_tcc_audit_state('GET_QUERY');
    legacy_query_hash = stage8_k2_tcc_stable_hash( ...
        'TFBC_QUERY_TRAJECTORY_V1', legacy_query);

    stage8_k2_tfbc_diagnostics_state('RESET');
    stage8_k2_tcc_audit_state('CONFIGURE', audit_config);
    [cache_result, cache_diagnostics, cache_hash, ...
        cache_projection] = stage8_k2_tfbc_fit_mode( ...
        trial, fixture.context, identity.provider_diagnostic, ...
        'REGISTERED_CACHE');
    cache_query = stage8_k2_tcc_audit_state('GET_QUERY');
    cache_query_hash = stage8_k2_tcc_stable_hash( ...
        'TFBC_QUERY_TRAJECTORY_V1', cache_query);
    exposure = stage8_k2_tfbc_diagnostics_state('SNAPSHOT');
    stage8_k2_tcc_audit_state('CONFIGURE', struct('mode','OFF'));

    mismatch = mismatch_totals_local(cache_query.stage_rows);
    fixed_off_grid_count = fixed_off_grid_local(cache_query.stage_rows);
    root_equal = isequaln(legacy_projection, cache_projection) && ...
        strcmp(legacy_hash, cache_hash);
    trajectory_equal = strcmp(legacy_query_hash, cache_query_hash);
    t4_cache_queries = double(cache_diagnostics.cache_hit_count) + ...
        double(cache_diagnostics.cache_miss_count) + ...
        double(cache_diagnostics.direct_fallback_count);
    truth_leakage = double(cache_query.truth_used_in_fit_flag || ...
        cache_query.cache_truth_used_flag || ...
        cache_query.placement_truth_used_flag || ...
        cache_result.truth_used_in_fit_flag || ...
        cache_diagnostics.selection_truth_used_flag);
    semantic_pass = root_equal && trajectory_equal && ...
        mismatch.total == 0 && fixed_off_grid_count == 0 && ...
        exposure.eligible_registered_call_count > 0 && ...
        exposure.cache_hit_count == ...
        exposure.eligible_registered_column_count && ...
        exposure.cache_miss_count == 0 && exposure.fallback_count == 0 && ...
        exposure.identity_rejection_count == 0 && ...
        t4_cache_queries == 0 && truth_leakage == 0;
    row = struct('trial_index',trial_index, ...
        'trial_id',string(spec.trial_id), ...
        'noise_profile_id',string(spec.noise_profile_id), ...
        'fixed_measurement_hash',string(trial.model.fixed_measurement_hash), ...
        'element_trial_hash',string(trial.element_trial_hash), ...
        'fit_valid_equal',legacy_result.fit_valid == cache_result.fit_valid, ...
        'root_projection_equal',root_equal, ...
        'trajectory_equal',trajectory_equal, ...
        'result_checksum_hash',string(cache_hash), ...
        'legacy_result_checksum_hash',string(legacy_hash), ...
        'cache_result_checksum_hash',string(cache_hash), ...
        'legacy_trajectory_hash',string(legacy_query_hash), ...
        'cache_trajectory_hash',string(cache_query_hash), ...
        'query_mismatch_count',mismatch.total, ...
        'fixed_off_grid_count',fixed_off_grid_count, ...
        'eligible_registered_call_count', ...
        exposure.eligible_registered_call_count, ...
        'eligible_registered_column_count', ...
        exposure.eligible_registered_column_count, ...
        'cache_hit_count',exposure.cache_hit_count, ...
        'cache_miss_count',exposure.cache_miss_count, ...
        'fallback_count',exposure.fallback_count, ...
        'identity_rejection_count',exposure.identity_rejection_count, ...
        't4_cache_query_count',t4_cache_queries, ...
        'truth_leakage_count',truth_leakage, ...
        'semantic_pass',semantic_pass);
    payload = struct('fixture_hash',fixture.fixture_hash, 'row',row, ...
        'exposure',exposure, 'mismatch',mismatch);
    atomic_save_local(checkpoint_path, payload);
    trial_payloads{trial_index} = payload;
    fprintf('TFBC CORRECTNESS RUN %d/72 %s pass=%d hits=%d\n', ...
        trial_index, char(spec.trial_id), semantic_pass, ...
        exposure.cache_hit_count);
    if ~semantic_pass
        error('stage8_k2_tfbc_run_correctness:SemanticMismatch', ...
            'FIXED_BACKBONE_CACHE_SEMANTIC_MISMATCH_STOP at %s.', ...
            char(spec.trial_id));
    end
end
rows = cellfun(@(x) x.row, trial_payloads, 'UniformOutput', false);
correctness = struct2table(vertcat(rows{:}));
exposure = exposure_table_local(trial_payloads);
writetable(correctness, fullfile(runtime_root, 'correctness', ...
    'correctness.csv'));
writetable(exposure, fullfile(runtime_root, 'correctness', ...
    'exposure.csv'));
assert(height(correctness) == 72 && all(correctness.semantic_pass), ...
    'stage8_k2_tfbc_run_correctness:Completeness');
output = struct('schema_version','STAGE8_K2_TFBC_CORRECTNESS_V1', ...
    'fixture_hash',fixture.fixture_hash, ...
    'trial_registry_hash',fixture.trial_registry_hash, ...
    'static_summary',static_summary, 'correctness',correctness, ...
    'exposure',exposure, 'semantic_pass_count',nnz(correctness.semantic_pass), ...
    'trial_count',height(correctness), ...
    'full_checksum_status','FULL_CHECKSUM_72_OF_72_MATCH', ...
    'trajectory_status','FULL_TRAJECTORY_72_OF_72_MATCH', ...
    'status','STAGE8_K2_TFBC_CORRECTNESS_PASS');
save(fullfile(runtime_root, 'correctness', ...
    'correctness_output.mat'), 'output', '-v7');
end

function totals = mismatch_totals_local(rows)
fields = {'key_mismatch_count','rank_mismatch_count', ...
    'candidate_order_mismatch_count','tie_mismatch_count', ...
    'best_index_mismatch_count','accepted_update_mismatch_count', ...
    'trajectory_mismatch_count','selected_start_mismatch_count', ...
    'nested_pass_mismatch_count','final_selector_mismatch_count'};
totals = struct();
totals.total = 0;
for index = 1:numel(fields)
    name = fields{index};
    if isempty(rows), value = 0; else, value = sum([rows.(name)]); end
    totals.(name) = value;
    totals.total = totals.total + value;
end
end

function count = fixed_off_grid_local(rows)
fixed_ids = ["K1_INIT_CONVENTIONAL"; ...
    "K1_FIXED_REGISTERED_REFINEMENT"; ...
    "K1_FIXED_FINAL_CERTIFICATION";"K2_INIT_CONVENTIONAL"; ...
    "K2_HELPER_K1";"K2_NESTED_ANCHOR"; ...
    "K2_REGISTERED_REFINEMENT";"K2_FINAL_CERTIFICATION"];
count = 0;
for index = 1:numel(rows)
    if any(rows(index).stage_id == fixed_ids)
        count = count + rows(index).off_grid_column_count;
    end
end
end

function table_out = exposure_table_local(payloads)
rows = cell(numel(payloads), 1);
for trial_index = 1:numel(payloads)
    snapshot = payloads{trial_index}.exposure;
    values = repmat(struct('trial_index',0, 'trial_id',"", ...
        'stage_id',"", 'call_count',0, 'column_count',0), ...
        numel(snapshot.stage_ids), 1);
    for stage_index = 1:numel(snapshot.stage_ids)
        values(stage_index) = struct('trial_index',trial_index, ...
            'trial_id',payloads{trial_index}.row.trial_id, ...
            'stage_id',snapshot.stage_ids(stage_index), ...
            'call_count',snapshot.stage_call_count(stage_index), ...
            'column_count',snapshot.stage_column_count(stage_index));
    end
    rows{trial_index} = values;
end
table_out = struct2table(vertcat(rows{:}));
end

function atomic_save_local(path_now, payload)
temporary = [path_now, '.tmp'];
if isfile(temporary), delete(temporary); end
save(temporary, 'payload', '-v7');
[moved, message] = movefile(temporary, path_now, 'f');
if ~moved
    error('stage8_k2_tfbc_run_correctness:Checkpoint', '%s', message);
end
end
