function fixture = stage8_k2_tfbc_build_fixture( ...
    repo_dir, runtime_root, options)
%STAGE8_K2_TFBC_BUILD_FIXTURE Materialize frozen trials and providers.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_tfbc_build_fixture:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
if nargin < 2, runtime_root = ''; end
if nargin < 3 || isempty(options), options = struct(); end
if ~isfield(options, 'include_trials'), options.include_trials = true; end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
if ~isempty(runtime_root)
    runtime_root = char(java.io.File( ...
        char(string(runtime_root))).getCanonicalPath());
end
context = stage8_k2_tp_build_context(repo_dir);
registry = stage8_k2_tp_build_registry( ...
    context.plan.local_domain, context.constants);
registry_hash = stage8_k2_tcc_stable_hash( ...
    'PLACEMENT_AUDIT_REGISTRY', registry);
noise_ids = unique(registry.noise_profile_id, 'stable');
identities = repmat(identity_template_local(), numel(noise_ids), 1);
if ~isempty(runtime_root)
    artifact_dir = fullfile(runtime_root, 'artifacts');
    if ~isfolder(artifact_dir), mkdir(artifact_dir); end
end
for identity_index = 1:numel(noise_ids)
    model = resolve_stage8_measurement_model( ...
        context.plan.measurement_model_registry, ...
        context.primary_measurement_config_id, noise_ids(identity_index));
    [dictionary, dictionary_info] = ...
        stage8_k2_tcc_build_registered_dictionary( ...
        model, context.plan.local_domain, struct());
    artifact = stage8_k2_tecs_promote_c1_artifact(dictionary);
    [provider_timed, timed_info] = stage8_k2_tfbc_build_provider( ...
        model, context.plan.local_domain, struct('artifact',artifact, ...
        'timed_diagnostics_enabled',false));
    [provider_diagnostic, diagnostic_info] = ...
        stage8_k2_tfbc_build_provider(model, context.plan.local_domain, ...
        struct('artifact',artifact, 'timed_diagnostics_enabled',true));
    identities(identity_index) = struct( ...
        'noise_profile_id',char(noise_ids(identity_index)), ...
        'fixed_measurement_hash',char(model.fixed_measurement_hash), ...
        'model',model, 'dictionary',dictionary, ...
        'dictionary_info',dictionary_info, 'artifact',artifact, ...
        'provider_timed',provider_timed, ...
        'provider_diagnostic',provider_diagnostic, ...
        'timed_provider_info',timed_info, ...
        'diagnostic_provider_info',diagnostic_info);
    if ~isempty(runtime_root)
        artifact_path = fullfile(artifact_dir, ...
            ['artifact_', char(model.fixed_measurement_hash), '.mat']);
        provider_path = fullfile(artifact_dir, ...
            ['provider_', char(model.fixed_measurement_hash), '.mat']);
        save(artifact_path, 'artifact', '-v7');
        provider = provider_timed; %#ok<NASGU>
        save(provider_path, 'provider', '-v7');
    end
end
trials = cell(0, 1);
if logical(options.include_trials)
    trials = cell(height(registry), 1);
    for trial_index = 1:height(registry)
        trials{trial_index} = stage8_k2_tcc_generate_frozen_trial( ...
            registry(trial_index, :), context);
    end
end
provider_hashes = string(arrayfun(@(x) ...
    x.provider_timed.provider_hash, identities, 'UniformOutput', false));
fixture = struct('schema_version','STAGE8_K2_TFBC_FIXTURE_V1', ...
    'repo_dir',repo_dir, 'runtime_root',runtime_root, ...
    'context',context, 'registry',registry, ...
    'trial_registry_hash',registry_hash, 'identities',identities, ...
    'trials',{trials}, 'provider_hashes',provider_hashes, ...
    'fixture_hash',stage8_k2_tecs_sha256('TFBC_FIXTURE_V1', ...
    struct('registry_hash',registry_hash, ...
    'provider_hashes',provider_hashes)));
end

function value = identity_template_local()
value = struct('noise_profile_id','', 'fixed_measurement_hash','', ...
    'model',struct(), 'dictionary',struct(), ...
    'dictionary_info',struct(), 'artifact',struct(), ...
    'provider_timed',struct(), 'provider_diagnostic',struct(), ...
    'timed_provider_info',struct(), 'diagnostic_provider_info',struct());
end
