function [rows, diagnostics] = stage8_1b_evaluate_common_trial( ...
    pair_rows, frozen_plan, locked_thresholds, opts)
%STAGE8_1B_EVALUATE_COMMON_TRIAL Evaluate one paired common trial.

if nargin < 4 || isempty(opts), opts = struct(); end
opts = normalize_options_local(opts);
pair_rows = sortrows(pair_rows, 'evaluation_row_index');
if height(pair_rows) ~= 2 || ...
        numel(unique(string(pair_rows.measurement_config_id))) ~= 2 || ...
        numel(unique(string(pair_rows.common_trial_id))) ~= 1
    error('stage8_1b_evaluate_common_trial:Pairing', ...
        'A common trial must contain exactly two configuration rows.');
end

model_registry = frozen_plan.measurement_model_registry;
validation_plan = frozen_plan.validation;
local_domain = frozen_plan.local_domain;
stage5_locked = build_stage8_stage5_locked_config();
base_model = resolve_stage8_measurement_model(model_registry, ...
    pair_rows.measurement_config_id(1), pair_rows.noise_profile_id(1));
[center, snr_db] = draw_trial_parameters_local( ...
    pair_rows.parameter_seed(1), validation_plan.K1);
[Y_element, ~] = generate_stage8_k1_element_trial( ...
    center, snr_db, pair_rows.L(1), base_model, ...
    pair_rows.element_noise_seed(1));
element_identity = stage8_stable_hash( ...
    'STAGE8_K1_VALIDATION_ELEMENT_TRIAL_V2', Y_element, ...
    pair_rows.parameter_seed(1), pair_rows.element_noise_seed(1));

row_cells = cell(2, 1);
separation_trigger_count = 0;
for config_row = 1:2
    spec = pair_rows(config_row, :);
    model = resolve_stage8_measurement_model(model_registry, ...
        spec.measurement_config_id, spec.noise_profile_id);
    if ~strcmp(model.noise_factorization.factorization_hash, ...
            base_model.noise_factorization.factorization_hash)
        error('stage8_1b_evaluate_common_trial:PairedNoise', ...
            'Paired configurations must share the element covariance.');
    end
    full_data = build_stage8_full_data_from_element(Y_element, model, ...
        struct('validation_parameter_seed', spec.parameter_seed, ...
        'validation_element_noise_seed', spec.element_noise_seed, ...
        'data_role', 'STAGE8_K1_VALIDATION'));
    threshold = threshold_for_config_local( ...
        locked_thresholds, spec.measurement_config_id);
    evaluation = evaluate_method_local(full_data, model, local_domain, ...
        threshold, stage5_locked, spec, opts);
    separation_trigger_count = separation_trigger_count + ...
        double(evaluation.separation_triggered_flag);
    row_cells{config_row} = validation_row_local(spec, center, snr_db, ...
        element_identity, threshold, evaluation);
end
rows = struct2table(vertcat(row_cells{:}));
diagnostics = struct('common_trial_id', ...
    char(string(pair_rows.common_trial_id(1))), ...
    'element_trial_hash', char(string(element_identity)), ...
    'separation_trigger_row_count', separation_trigger_count);
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('stage8_1b_evaluate_common_trial:Options', ...
        'opts must be a scalar struct.');
end
separation_formal_supplied = isfield(opts, 'separation_formal_run');
allowed = {'formal_run','separation_formal_run','fit_options','Bsep', ...
    'run_separation','force_separation_fixture'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('stage8_1b_evaluate_common_trial:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
defaults = struct('formal_run', false, 'fit_options', struct(), ...
    'separation_formal_run', false, 'Bsep', 199, 'run_separation', true, ...
    'force_separation_fixture', false);
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(opts, names{index})
        opts.(names{index}) = defaults.(names{index});
    end
end
if ~separation_formal_supplied
    opts.separation_formal_run = opts.formal_run;
end
if opts.formal_run && (~isempty(fieldnames(opts.fit_options)) || ...
        opts.Bsep ~= 199 || ~opts.run_separation || ...
        opts.force_separation_fixture || ~opts.separation_formal_run)
    error('stage8_1b_evaluate_common_trial:FormalContract', ...
        'Formal evaluation fixes Bsep=199 and forbids test overrides.');
end
end

function [center, snr_db] = draw_trial_parameters_local(seed, K1)
rng_state = rng;
cleanup = onCleanup(@() rng(rng_state));
rng(seed, 'twister');
center = [K1.center_bounds_deg(1, 1) + ...
    diff(K1.center_bounds_deg(1, :)) * rand(), ...
    K1.center_bounds_deg(2, 1) + ...
    diff(K1.center_bounds_deg(2, :)) * rand()];
snr_db = K1.snr_bounds_db(1) + diff(K1.snr_bounds_db) * rand();
clear cleanup
end

function threshold = threshold_for_config_local(thresholds, config_id)
matches = string({thresholds.measurement_config_id}) == string(config_id);
if nnz(matches) ~= 1
    error('stage8_1b_evaluate_common_trial:ThresholdPreflight', ...
        'Threshold preflight did not retain one artifact per configuration.');
end
threshold = thresholds(matches);
end

function evaluation = evaluate_method_local(data, model, domain, threshold, ...
    locked, spec, opts)
[context, ~] = build_stage8_initialization_context_from_data( ...
    data, model, domain, locked, model.noise_factorization, struct());
[fit1, ~] = fit_local_model_k( ...
    data, 1, domain, model, context, opts.fit_options);
[valid1, validity1] = validate_stage8_fit_for_lrt(fit1, 1, ...
    struct('fixed_measurement_hash', model.fixed_measurement_hash, ...
    'local_domain_hash', domain.domain_hash));
if ~valid1
    evaluation = failed_evaluation_local(validity1.status);
    return;
end
context.k1_fit = fit1;
[fit2, ~] = fit_local_model_k( ...
    data, 2, domain, model, context, opts.fit_options);
[valid2, validity2] = validate_stage8_fit_for_lrt(fit2, 2, ...
    identity_from_fit_local(fit1));
if ~valid2
    evaluation = failed_evaluation_local(validity2.status);
    return;
end
[lrt, ~] = nested_dml_likelihood_ratio(fit1, fit2, struct());
if ~strcmp(lrt.lrt_status, 'OK')
    evaluation = failed_evaluation_local(lrt.lrt_status);
    return;
end
separation_triggered = lrt.lambda_12 > threshold.q_global || ...
    opts.force_separation_fixture;
if ~separation_triggered
    state = 'K1';
    separation_status = 'NOT_RUN_LRT_DID_NOT_EXCEED_THRESHOLD';
elseif opts.run_separation
    [separation, ~] = bootstrap_separation_confidence( ...
        fit2, domain, model, struct('Bsep', opts.Bsep, ...
        'seed', spec.separation_auxiliary_seed, ...
        'formal_run', opts.separation_formal_run, ...
        'stage5_locked_config', locked, 'fit_options', opts.fit_options));
    decision = classify_local_cluster_state( ...
        fit1, fit2, lrt, threshold, separation, struct());
    state = decision.state;
    separation_status = separation.confidence_status;
else
    state = 'K2_UNRESOLVED';
    separation_status = 'NOT_RUN_MINIATURE_CONTRACT';
end
evaluation = struct('state', state, 'lambda_12', lrt.lambda_12, ...
    'fit1_validity_status', validity1.status, ...
    'fit2_validity_status', validity2.status, ...
    'separation_status', separation_status, ...
    'separation_triggered_flag', separation_triggered);
end

function identity = identity_from_fit_local(fit)
identity = struct('fixed_measurement_hash', fit.fixed_measurement_hash, ...
    'local_domain_hash', fit.local_domain_hash, ...
    'solver_contract_hash', fit.solver_contract_hash, ...
    'observation_hash', fit.observation_hash);
end

function evaluation = failed_evaluation_local(status)
if strcmp(status, 'NUMERIC_RANK_DEFICIENT')
    state = 'NUMERIC_RANK_DEFICIENT';
else
    state = 'SEARCH_NOT_CONVERGED';
end
evaluation = struct('state', state, 'lambda_12', NaN, ...
    'fit1_validity_status', status, 'fit2_validity_status', status, ...
    'separation_status', 'NOT_RUN_INVALID_LRT_FIT', ...
    'separation_triggered_flag', false);
end

function row = validation_row_local(spec, center, snr_db, element_hash, ...
    threshold, evaluation)
state = string(evaluation.state);
row = struct('evaluation_row_index', spec.evaluation_row_index, ...
    'stratum_index', spec.stratum_index, ...
    'stratum_id', spec.stratum_id, ...
    'common_trial_id', spec.common_trial_id, ...
    'pairing_key', spec.pairing_key, ...
    'trial_index_within_stratum', spec.trial_index_within_stratum, ...
    'measurement_config_id', spec.measurement_config_id, ...
    'noise_profile_id', spec.noise_profile_id, 'L', spec.L, ...
    'parameter_seed', spec.parameter_seed, ...
    'element_noise_seed', spec.element_noise_seed, ...
    'separation_auxiliary_seed', spec.separation_auxiliary_seed, ...
    'center_az_deg', center(1), 'center_el_deg', center(2), ...
    'snr_db', snr_db, 'element_trial_hash', string(element_hash), ...
    'threshold_calibration_hash', string(threshold.calibration_hash), ...
    'threshold_artifact_hash', string(threshold.threshold_artifact_hash), ...
    'q_global', threshold.q_global, 'lambda_12', evaluation.lambda_12, ...
    'state', state, 'false_split_flag', ismember(state, ...
    ["K2_RESOLVED","K2_UNRESOLVED"]), ...
    'false_resolved_flag', state == "K2_RESOLVED", ...
    'K2_UNRESOLVED_flag', state == "K2_UNRESOLVED", ...
    'SEARCH_NOT_CONVERGED_flag', state == "SEARCH_NOT_CONVERGED", ...
    'NUMERIC_RANK_DEFICIENT_flag', state == "NUMERIC_RANK_DEFICIENT", ...
    'decision_available_flag', ismember(state, ...
    ["K1","K2_RESOLVED","K2_UNRESOLVED"]), ...
    'fit1_validity_status', string(evaluation.fit1_validity_status), ...
    'fit2_validity_status', string(evaluation.fit2_validity_status), ...
    'separation_status', string(evaluation.separation_status));
end
