function result = stage8_1b_pilot_gate1(repo_dir, pilot_root)
%STAGE8_1B_PILOT_GATE1 Compare the external evaluator to the reference runner.

repo_dir = char(string(repo_dir));
pilot_root = char(string(pilot_root));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if ~isfolder(pilot_root), mkdir(pilot_root); end
result_path = fullfile(pilot_root, 'gate1_result.json');
result = struct('gate1_pass', false, 'protocol_stage', ...
    'GATE1_REFERENCE_RUNNING', 'last_error', '');
stage8_1b_write_json_atomic(result_path, result);
try
    context = stage8_1b_frozen_context(repo_dir, true);
    stage5_locked = build_stage8_stage5_locked_config();
    reference_callback = @(spec, full_data, model, threshold) ...
        reference_evaluation_local(full_data, model, ...
        context.plan.local_domain, threshold, stage5_locked, spec);
    reference_clock = tic;
    reference = run_stage8_1_k1_validation( ...
        context.plan.validation, context.plan.local_domain, ...
        context.plan.measurement_model_registry, context.thresholds, ...
        stage5_locked, struct( ...
        'formal_run', false, 'max_common_trials_per_stratum', 10, ...
        'evaluation_callback', reference_callback, 'fit_options', struct(), ...
        'Bsep', 199, 'run_separation', true, ...
        'execution_authorization', '', 'frozen_plan', context.plan));
    reference_wall_sec = toc(reference_clock);

    selected = context.registry( ...
        context.registry.trial_index_within_stratum <= 10, :);
    pair_ids = unique(string(selected.common_trial_id), 'stable');
    external_cells = cell(numel(pair_ids), 1);
    external_clock = tic;
    for index = 1:numel(pair_ids)
        pair_rows = selected(selected.common_trial_id == pair_ids(index), :);
        external_cells{index} = stage8_1b_evaluate_common_trial( ...
            pair_rows, context.plan, context.thresholds, struct( ...
            'formal_run', false, 'separation_formal_run', true, ...
            'fit_options', struct(), ...
            'Bsep', 199, 'run_separation', true));
    end
    external_trials = sortrows(vertcat(external_cells{:}), ...
        'evaluation_row_index');
    external_wall_sec = toc(external_clock);
    [external_summary, external_gate, external_paired] = ...
        summarize_stage8_k1_validation( ...
        external_trials, context.plan.validation.K1);

    reference_trials = sortrows(reference.trials, 'evaluation_row_index');
    reference_hash = stage8_stable_hash( ...
        'STAGE8_1_VALIDATION_TRIAL_SET_V1', reference_trials);
    external_hash = stage8_stable_hash( ...
        'STAGE8_1_VALIDATION_TRIAL_SET_V1', external_trials);
    row_equal = strcmp(reference_hash, external_hash) && ...
        height(reference_trials) == 120 && height(external_trials) == 120;
    lambda_equal = isequal(num2hex(double(reference_trials.lambda_12)), ...
        num2hex(double(external_trials.lambda_12)));
    state_equal = isequal(string(reference_trials.state), ...
        string(external_trials.state));
    separation_equal = isequal(string(reference_trials.separation_status), ...
        string(external_trials.separation_status));
    element_hash_equal = isequal(string(reference_trials.element_trial_hash), ...
        string(external_trials.element_trial_hash));
    derived_equal = strcmp(stage8_stable_hash(reference.summary), ...
        stage8_stable_hash(external_summary)) && ...
        strcmp(stage8_stable_hash(reference.paired_sensitivity), ...
        stage8_stable_hash(external_paired)) && ...
        strcmp(stage8_stable_hash('STAGE8_1_PRIMARY_GATE_V1', ...
        reference.gate), stage8_stable_hash( ...
        'STAGE8_1_PRIMARY_GATE_V1', external_gate));
    gate1_pass = row_equal && lambda_equal && state_equal && ...
        separation_equal && element_hash_equal && derived_equal;
    natural_separation_trigger_count = nnz( ...
        isfinite(external_trials.lambda_12) & ...
        external_trials.lambda_12 > external_trials.q_global);
    result = struct('gate1_pass', gate1_pass, ...
        'protocol_stage', ternary_local(gate1_pass, ...
        'GATE1_REFERENCE_PASS', 'GATE1_REFERENCE_FAIL_STOPPED'), ...
        'reference_row_hash', reference_hash, ...
        'external_row_hash', external_hash, ...
        'row_equality', row_equal, 'lambda_num2hex_equality', lambda_equal, ...
        'state_equality', state_equal, ...
        'separation_status_equality', separation_equal, ...
        'element_trial_hash_equality', element_hash_equal, ...
        'summary_gate_paired_equality', derived_equal, ...
        'natural_separation_trigger_count', ...
        natural_separation_trigger_count, ...
        'forced_separation_fixture_required', ...
        natural_separation_trigger_count == 0, ...
        'reference_wall_sec', reference_wall_sec, ...
        'external_wall_sec', external_wall_sec, ...
        'last_error', '');
    save(fullfile(pilot_root, 'gate1_rows.mat'), 'reference', ...
        'external_trials', 'external_summary', 'external_gate', ...
        'external_paired', '-mat');
    stage8_1b_write_json_atomic(result_path, result);
    if ~gate1_pass
        error('stage8_1b_pilot_gate1:ReferenceMismatch', ...
            'External common-trial evaluator differs from the reference runner.');
    end
catch exception
    if ~isfield(result, 'reference_row_hash')
        result.protocol_stage = 'GATE1_REFERENCE_FAIL_STOPPED';
        result.last_error = getReport(exception, 'extended', ...
            'hyperlinks', 'off');
        stage8_1b_write_json_atomic(result_path, result);
    end
    rethrow(exception);
end
clear path_cleanup
end

function value = ternary_local(condition, yes_value, no_value)
if condition, value = yes_value; else, value = no_value; end
end

function evaluation = reference_evaluation_local(data, model, domain, ...
    threshold, locked, spec)
[context, ~] = build_stage8_initialization_context_from_data( ...
    data, model, domain, locked, model.noise_factorization, struct());
[fit1, ~] = fit_local_model_k(data, 1, domain, model, context, struct());
[valid1, validity1] = validate_stage8_fit_for_lrt(fit1, 1, ...
    struct('fixed_measurement_hash', model.fixed_measurement_hash, ...
    'local_domain_hash', domain.domain_hash));
if ~valid1
    evaluation = failed_reference_evaluation_local(validity1.status);
    return;
end
context.k1_fit = fit1;
[fit2, ~] = fit_local_model_k(data, 2, domain, model, context, struct());
[valid2, validity2] = validate_stage8_fit_for_lrt(fit2, 2, ...
    identity_from_fit_local(fit1));
if ~valid2
    evaluation = failed_reference_evaluation_local(validity2.status);
    return;
end
[lrt, ~] = nested_dml_likelihood_ratio(fit1, fit2, struct());
if ~strcmp(lrt.lrt_status, 'OK')
    evaluation = failed_reference_evaluation_local(lrt.lrt_status);
    return;
end
if lrt.lambda_12 <= threshold.q_global
    state = 'K1';
    separation_status = 'NOT_RUN_LRT_DID_NOT_EXCEED_THRESHOLD';
else
    [separation, ~] = bootstrap_separation_confidence( ...
        fit2, domain, model, struct('Bsep', 199, ...
        'seed', spec.separation_auxiliary_seed, 'formal_run', true, ...
        'stage5_locked_config', locked, 'fit_options', struct()));
    decision = classify_local_cluster_state( ...
        fit1, fit2, lrt, threshold, separation, struct());
    state = decision.state;
    separation_status = separation.confidence_status;
end
evaluation = struct('state', state, 'lambda_12', lrt.lambda_12, ...
    'fit1_validity_status', validity1.status, ...
    'fit2_validity_status', validity2.status, ...
    'separation_status', separation_status);
end

function identity = identity_from_fit_local(fit)
identity = struct('fixed_measurement_hash', fit.fixed_measurement_hash, ...
    'local_domain_hash', fit.local_domain_hash, ...
    'solver_contract_hash', fit.solver_contract_hash, ...
    'observation_hash', fit.observation_hash);
end

function evaluation = failed_reference_evaluation_local(status)
if strcmp(status, 'NUMERIC_RANK_DEFICIENT')
    state = 'NUMERIC_RANK_DEFICIENT';
else
    state = 'SEARCH_NOT_CONVERGED';
end
evaluation = struct('state', state, 'lambda_12', NaN, ...
    'fit1_validity_status', status, 'fit2_validity_status', status, ...
    'separation_status', 'NOT_RUN_INVALID_LRT_FIT');
end
