function result = stage8_1b_compare_runtime_roots( ...
    repo_dir, baseline_root, candidate_root, result_path, gate_name)
%STAGE8_1B_COMPARE_RUNTIME_ROOTS Compare two complete pilot checkpoint sets.

repo_dir = char(string(repo_dir));
baseline_root = char(string(baseline_root));
candidate_root = char(string(candidate_root));
result_path = char(string(result_path));
gate_name = upper(char(string(gate_name)));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
context = stage8_1b_frozen_context(repo_dir, true);
left_protocol = jsondecode(fileread(fullfile(baseline_root, 'protocol.json')));
right_protocol = jsondecode(fileread(fullfile(candidate_root, 'protocol.json')));
stage8_1b_verify_protocol(left_protocol, context);
stage8_1b_verify_protocol(right_protocol, context);
if double(left_protocol.trials_per_stratum) ~= ...
        double(right_protocol.trials_per_stratum)
    error('stage8_1b_compare_runtime_roots:Registry', ...
        'Pilot roots use different subsets.');
end
registry = context.registry(context.registry.trial_index_within_stratum <= ...
    double(left_protocol.trials_per_stratum), :);
pair_ids = unique(string(registry.common_trial_id), 'stable');
left_rows = cell(numel(pair_ids), 1);
right_rows = cell(numel(pair_ids), 1);
left_hashes = strings(numel(pair_ids), 1);
right_hashes = strings(numel(pair_ids), 1);
for index = 1:numel(pair_ids)
    expected = registry(registry.common_trial_id == pair_ids(index), :);
    left_path = fullfile(baseline_root, 'checkpoints', ...
        [char(pair_ids(index)), '.mat']);
    right_path = fullfile(candidate_root, 'checkpoints', ...
        [char(pair_ids(index)), '.mat']);
    if ~isfile(left_path) || ~isfile(right_path)
        error('stage8_1b_compare_runtime_roots:Missing', ...
            'Pilot checkpoint set is incomplete at %s.', pair_ids(index));
    end
    stage8_1b_validate_checkpoint(left_path, left_protocol, expected);
    stage8_1b_validate_checkpoint(right_path, right_protocol, expected);
    left = load(left_path, 'checkpoint', '-mat');
    right = load(right_path, 'checkpoint', '-mat');
    left_rows{index} = left.checkpoint.rows;
    right_rows{index} = right.checkpoint.rows;
    left_hashes(index) = string(left.checkpoint.content_hash);
    right_hashes(index) = string(right.checkpoint.content_hash);
end
left_trials = sortrows(vertcat(left_rows{:}), 'evaluation_row_index');
right_trials = sortrows(vertcat(right_rows{:}), 'evaluation_row_index');
[left_summary, left_gate, left_paired] = summarize_stage8_k1_validation( ...
    left_trials, context.plan.validation.K1);
[right_summary, right_gate, right_paired] = summarize_stage8_k1_validation( ...
    right_trials, context.plan.validation.K1);
left_row_hash = stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_TRIAL_SET_V1', left_trials);
right_row_hash = stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_TRIAL_SET_V1', right_trials);
checkpoint_equal = isequal(left_hashes, right_hashes);
row_equal = strcmp(left_row_hash, right_row_hash);
lambda_equal = isequal(num2hex(double(left_trials.lambda_12)), ...
    num2hex(double(right_trials.lambda_12)));
state_equal = isequal(string(left_trials.state), string(right_trials.state));
separation_equal = isequal(string(left_trials.separation_status), ...
    string(right_trials.separation_status));
element_equal = isequal(string(left_trials.element_trial_hash), ...
    string(right_trials.element_trial_hash));
derived_equal = strcmp(stage8_stable_hash(left_summary), ...
    stage8_stable_hash(right_summary)) && ...
    strcmp(stage8_stable_hash(left_paired), ...
    stage8_stable_hash(right_paired)) && ...
    strcmp(stage8_stable_hash('STAGE8_1_PRIMARY_GATE_V1', left_gate), ...
    stage8_stable_hash('STAGE8_1_PRIMARY_GATE_V1', right_gate));
pass = checkpoint_equal && row_equal && lambda_equal && state_equal && ...
    separation_equal && element_equal && derived_equal && ...
    height(left_trials) == double(left_protocol.row_count) && ...
    numel(unique(string(left_trials.common_trial_id))) == ...
    double(left_protocol.common_trial_count);
result = struct('gate_name', gate_name, 'pass', pass, ...
    'checkpoint_hash_equality', checkpoint_equal, ...
    'baseline_row_hash', left_row_hash, ...
    'candidate_row_hash', right_row_hash, ...
    'row_equality', row_equal, 'lambda_num2hex_equality', lambda_equal, ...
    'state_equality', state_equal, ...
    'separation_status_equality', separation_equal, ...
    'element_trial_hash_equality', element_equal, ...
    'summary_gate_paired_equality', derived_equal, ...
    'common_trial_count', numel(pair_ids), 'row_count', height(left_trials), ...
    'separation_trigger_count', nnz(isfinite(left_trials.lambda_12) & ...
    left_trials.lambda_12 > left_trials.q_global), 'last_error', '');
stage8_1b_write_json_atomic(result_path, result);
save([result_path, '.mat'], 'left_trials', 'right_trials', ...
    'left_summary', 'right_summary', 'left_gate', 'right_gate', ...
    'left_paired', 'right_paired', '-mat');
clear path_cleanup
end
