function record = stage8_1b_write_checkpoint_audit( ...
    checkpoint_path, protocol, checkpoint_audit)
%STAGE8_1B_WRITE_CHECKPOINT_AUDIT Bind a validated checkpoint to its bytes.

checkpoint_path = char(string(checkpoint_path));
if nargin < 3 || isempty(checkpoint_audit)
    checkpoint_audit = stage8_1b_validate_checkpoint( ...
        checkpoint_path, protocol);
end
file_info = dir(checkpoint_path);
if numel(file_info) ~= 1 || file_info.isdir
    error('stage8_1b_write_checkpoint_audit:Checkpoint', ...
        'Checkpoint file is missing: %s.', checkpoint_path);
end
record = struct( ...
    'protocol_version', char(string(protocol.protocol_version)), ...
    'checkpoint_contract_version', ...
    char(string(protocol.checkpoint_contract_version)), ...
    'protocol_runner_commit', ...
    char(string(protocol.protocol_runner_commit)), ...
    'common_trial_id', char(string(checkpoint_audit.common_trial_id)), ...
    'global_common_trial_index', ...
    double(checkpoint_audit.global_common_trial_index), ...
    'content_hash', char(string(checkpoint_audit.content_hash)), ...
    'checkpoint_file_name', file_info.name, ...
    'checkpoint_file_sha256', stage8_sha256_file(checkpoint_path), ...
    'checkpoint_byte_count', double(file_info.bytes), ...
    'validation_status', 'VALIDATED_COMPLETE_PASS', ...
    'validated_utc', utc_now_local());
stage8_1b_write_json_atomic([checkpoint_path, '.audit.json'], record);
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
