function decision = stage8_1b_sharded_pilot(pilot_root)
%STAGE8_1B_SHARDED_PILOT Apply the V2 correctness and resource decision tree.

pilot_root = char(string(pilot_root));
gate0 = read_json_local(fullfile(pilot_root, 'gate0_preflight.json'));
gate1 = read_json_local(fullfile(pilot_root, 'gate1', 'gate1_result.json'));
gate2a = read_json_local(fullfile(pilot_root, 'gate2a_result.json'));
gate2b = read_json_local(fullfile(pilot_root, 'gate2b_result.json'));
resources = read_json_local(fullfile(pilot_root, 'pilot_resources.json'));
gate0_pass = logical(gate0.gate0_pass);
gate1_pass = logical(gate1.gate1_pass);
gate2a_pass = logical(gate2a.pass) && ...
    logical(resources.resume_file_identity_pass) && ...
    strcmp(string(gate1.external_row_hash), ...
    string(gate2a.baseline_row_hash));
gate2b_pass = logical(gate2b.pass);
fixture_pass = true;
if logical(gate1.forced_separation_fixture_required)
    fixture = read_json_local(fullfile(pilot_root, ...
        'forced_separation_result.json'));
    fixture_pass = logical(fixture.pass);
end
resource_pass = double(resources.speedup) >= 1.15 && ...
    double(resources.peak_total_memory_utilization) <= 0.85 && ...
    double(resources.minimum_available_physical_bytes) >= 2 * 1024^3 && ...
    ~logical(resources.sustained_pagefile_thrashing) && ...
    ~logical(resources.worker_crash_or_oom);

selected = 0;
mode = 'NONE';
fallback = 'NONE';
if ~gate0_pass
    pilot_decision = 'GATE0_FAIL_STOP';
elseif ~gate1_pass || ~fixture_pass
    pilot_decision = 'REFERENCE_EQUIVALENCE_FAIL_STOP_AND_FIX_TOOL';
elseif ~gate2a_pass
    pilot_decision = 'RESUME_EQUIVALENCE_FAIL_STOP_AND_FIX_RECOVERY';
elseif ~gate2b_pass
    pilot_decision = 'PILOT_PASS_ONE_WORKER_PARALLEL_FALLBACK';
    selected = 1;
    mode = 'ONE_WORKER_RESUMABLE';
    fallback = 'PARALLEL_NUMERIC_OR_STATE_MISMATCH';
elseif ~resource_pass
    pilot_decision = 'PILOT_PASS_ONE_WORKER_RESOURCE_FALLBACK';
    selected = 1;
    mode = 'ONE_WORKER_RESUMABLE';
    fallback = char(string(resources.resource_failure_reason));
else
    pilot_decision = 'PILOT_PASS_TWO_WORKERS';
    selected = 2;
    mode = 'TWO_WORKER_SHARDED_RESUMABLE';
end
decision = struct('gate0_pass', gate0_pass, 'gate1_pass', gate1_pass, ...
    'gate2a_pass', gate2a_pass, 'gate2b_pass', gate2b_pass, ...
    'forced_separation_fixture_pass', fixture_pass, ...
    'resource_gate_pass', resource_pass, ...
    'pilot_decision', pilot_decision, ...
    'selected_execution_mode', mode, ...
    'selected_worker_count', selected, 'fallback_reason', fallback, ...
    'reference_row_hash', gate1.reference_row_hash, ...
    'external_reference_row_hash', gate1.external_row_hash, ...
    'single_uninterrupted_row_hash', gate2a.baseline_row_hash, ...
    'single_resumed_row_hash', gate2a.candidate_row_hash, ...
    'sharded_row_hash', gate2b.candidate_row_hash, ...
    'checkpoint_hash_equality_gate2a', ...
    gate2a.checkpoint_hash_equality, ...
    'checkpoint_hash_equality_gate2b', ...
    gate2b.checkpoint_hash_equality, ...
    'lambda_num2hex_equality_gate2a', ...
    gate2a.lambda_num2hex_equality, ...
    'lambda_num2hex_equality_gate2b', ...
    gate2b.lambda_num2hex_equality, ...
    'natural_separation_trigger_count', ...
    gate1.natural_separation_trigger_count, ...
    'single_worker_wall_sec', resources.single_worker_wall_sec, ...
    'two_worker_active_wall_sec', resources.two_worker_active_wall_sec, ...
    'speedup', resources.speedup, ...
    'peak_private_memory_bytes', resources.peak_private_memory_bytes, ...
    'peak_total_memory_utilization', ...
    resources.peak_total_memory_utilization, ...
    'minimum_available_physical_bytes', ...
    resources.minimum_available_physical_bytes, ...
    'created_utc', utc_now_local());
stage8_1b_write_json_atomic( ...
    fullfile(pilot_root, 'pilot_decision.json'), decision);
end

function value = read_json_local(path_now)
if ~isfile(path_now)
    error('stage8_1b_sharded_pilot:MissingPilotArtifact', ...
        'Missing pilot artifact: %s.', path_now);
end
value = jsondecode(fileread(path_now));
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
