function digest = stage8_1b_checkpoint_content_hash(checkpoint)
%STAGE8_1B_CHECKPOINT_CONTENT_HASH Hash scientific checkpoint content only.

rows = sortrows(checkpoint.rows, 'evaluation_row_index');
digest = stage8_stable_hash( ...
    'STAGE8_1B_K1_COMMON_TRIAL_CHECKPOINT_V1', ...
    char(string(checkpoint.common_trial_id)), ...
    double(checkpoint.global_common_trial_index), rows, ...
    char(string(checkpoint.stage8_stable_code_identity_hash)), ...
    char(string(checkpoint.stage8_plan_hash)), ...
    char(string(checkpoint.stage8_validation_plan_hash)), ...
    char(string(checkpoint.measurement_registry_hash)), ...
    char(string(checkpoint.calibration_evidence_bundle_hash)), ...
    char(string(checkpoint.threshold_set_hash)), ...
    char(string(checkpoint.calibration_snapshot_hash)), ...
    logical(checkpoint.threshold_lookup_only_flag), ...
    logical(checkpoint.threshold_modification_flag), ...
    char(string(checkpoint.completion_status)));
end
