function protocol = stage8_1b_initialize_pilot_runtime( ...
    repo_dir, runtime_root, worker_count)
%STAGE8_1B_INITIALIZE_PILOT_RUNTIME Create one isolated 60-trial pilot root.

if ~ismember(double(worker_count), [1, 2])
    error('stage8_1b_initialize_pilot_runtime:WorkerCount', ...
        'Pilot worker count must be one or two.');
end
repo_dir = char(string(repo_dir));
runtime_root = char(string(runtime_root));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
context = stage8_1b_frozen_context(repo_dir, true);
if isfolder(runtime_root) && ~isempty(dir(fullfile(runtime_root, '**', '*')))
    error('stage8_1b_initialize_pilot_runtime:NotEmpty', ...
        'Pilot runtime root must be new and empty: %s.', runtime_root);
end
create_runtime_dirs_local(runtime_root);
protocol = protocol_local(context, runtime_root, worker_count, ...
    context.constants.pilot_trials_per_stratum, false, ...
    'PILOT_PENDING', 'PILOT_RESUMABLE_TEST', 'NONE');
write_immutable_protocol_local(runtime_root, protocol);
writetable(context.calibration_snapshot, ...
    fullfile(runtime_root, 'frozen_calibration_snapshot.csv'));
clear path_cleanup
end

function protocol = protocol_local(context, root, worker_count, ...
    trials_per_stratum, scientific_formal_run, decision, mode, fallback)
[status, head] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', context.repo_dir));
if status ~= 0, error('stage8_1b_initialize_pilot_runtime:Git', ...
        'Unable to resolve protocol runner commit.'); end
constants = context.constants;
protocol = struct( ...
    'protocol_version', constants.protocol_version, ...
    'execution_authorization', constants.execution_authorization, ...
    'repo_dir', context.repo_dir, 'runtime_root', root, ...
    'protocol_runner_commit', strtrim(head), ...
    'protocol_source_tree_hash', ...
    stage8_1b_protocol_source_tree_hash(context.repo_dir), ...
    'threshold_evidence_commit', constants.threshold_evidence_commit, ...
    'stage8_stable_code_identity_hash', ...
    constants.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', constants.stage8_plan_hash, ...
    'stage8_calibration_plan_hash', ...
    constants.stage8_calibration_plan_hash, ...
    'stage8_validation_plan_hash', ...
    constants.stage8_validation_plan_hash, ...
    'measurement_registry_hash', constants.measurement_registry_hash, ...
    'calibration_evidence_bundle_hash', ...
    constants.calibration_evidence_bundle_hash, ...
    'threshold_set_hash', constants.threshold_set_hash, ...
    'calibration_snapshot_hash', context.calibration_snapshot_hash, ...
    'matlab_release', 'R2022b', 'threads_per_worker', 1, ...
    'requested_worker_count', 2, ...
    'selected_worker_count', double(worker_count), ...
    'selected_execution_mode', mode, 'pilot_decision', decision, ...
    'fallback_reason', fallback, 'status_interval_minutes', 15, ...
    'automatic_start_enabled', false, ...
    'automatic_pause_enabled', false, ...
    'automatic_shutdown_enabled', false, ...
    'status_task_name', constants.status_task_name, ...
    'partition_rule', 'ODD_EVEN_GLOBAL_COMMON_TRIAL_INDEX', ...
    'stratum_ids', {cellstr(string( ...
    context.plan.validation.K1.strata.stratum_id))}, ...
    'trials_per_stratum', double(trials_per_stratum), ...
    'common_trial_count', double(6 * trials_per_stratum), ...
    'row_count', double(12 * trials_per_stratum), ...
    'Bsep', constants.Bsep, ...
    'scientific_formal_run', logical(scientific_formal_run), ...
    'pause_check_boundary', 'BETWEEN_COMMON_TRIALS', ...
    'checkpoint_contract_version', ...
    constants.checkpoint_contract_version, ...
    'created_utc', utc_now_local());
end

function create_runtime_dirs_local(root)
names = {'control','checkpoints','tmp','incomplete','workers','logs', ...
    'status','merged'};
mkdir(root);
for index = 1:numel(names), mkdir(fullfile(root, names{index})); end
end

function write_immutable_protocol_local(root, protocol)
path_now = fullfile(root, 'protocol.json');
if isfile(path_now)
    error('stage8_1b_initialize_pilot_runtime:ProtocolExists', ...
        'protocol.json is immutable and already exists.');
end
stage8_1b_write_json_atomic(path_now, protocol);
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
