function context = stage8_1b_frozen_context(repo_dir, formal_run)
%STAGE8_1B_FROZEN_CONTEXT Load and verify the committed scientific context.

if nargin < 2, formal_run = true; end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>

plan = build_stage8_locked_plan(repo_dir, sim_cfg(), ...
    struct('require_formal_runtime', logical(formal_run)));
[thresholds, calibration] = load_stage8_1_locked_thresholds( ...
    repo_dir, step, plan, struct('formal_run', logical(formal_run), ...
    'require_tracked_artifacts', logical(formal_run)));
[snapshot, snapshot_hash] = ...
    capture_stage8_1_calibration_snapshot(calibration.artifact_root);
registry = materialize_stage8_k1_validation_plan(plan.validation);

constants = stage8_1b_constants();
actual = [string(plan.identity.stage8_stable_code_identity_hash), ...
    string(plan.stage8_plan_hash), ...
    string(plan.stage8_calibration_plan_hash), ...
    string(plan.stage8_validation_plan_hash), ...
    string(plan.measurement_model_registry.registry_hash), ...
    string(calibration.calibration_evidence_bundle_hash), ...
    string(calibration.threshold_set_hash)];
expected = [string(constants.stage8_stable_code_identity_hash), ...
    string(constants.stage8_plan_hash), ...
    string(constants.stage8_calibration_plan_hash), ...
    string(constants.stage8_validation_plan_hash), ...
    string(constants.measurement_registry_hash), ...
    string(constants.calibration_evidence_bundle_hash), ...
    string(constants.threshold_set_hash)];
if ~isequal(actual, expected)
    error('stage8_1b_frozen_context:FrozenIdentity', ...
        'One or more frozen Stage8 identities changed.');
end
if ~strcmp(calibration.calibration_freeze_status, ...
        'PASS_STAGE8_1_THRESHOLD_EVIDENCE_FREEZE') || ...
        ~strcmp(calibration.committed_threshold_preflight_status, ...
        'COMMITTED_THRESHOLD_PREFLIGHT_PASS')
    error('stage8_1b_frozen_context:ThresholdPreflight', ...
        'Committed threshold evidence did not pass formal preflight.');
end
verify_threshold_local(thresholds, constants.primary_measurement_config_id, ...
    constants.primary_threshold_hex, ...
    constants.primary_threshold_artifact_hash);
verify_threshold_local(thresholds, ...
    constants.sensitivity_measurement_config_id, ...
    constants.sensitivity_threshold_hex, ...
    constants.sensitivity_threshold_artifact_hash);
if height(registry) ~= constants.formal_row_count || ...
        numel(unique(string(registry.common_trial_id))) ~= ...
        constants.formal_common_trial_count
    error('stage8_1b_frozen_context:RegistryCardinality', ...
        'The frozen K1 validation registry cardinality changed.');
end

context = struct('repo_dir', repo_dir, 'step', step, 'plan', plan, ...
    'thresholds', thresholds, 'calibration', calibration, ...
    'calibration_snapshot', snapshot, ...
    'calibration_snapshot_hash', snapshot_hash, ...
    'registry', registry, 'constants', constants);
clear path_cleanup
end

function verify_threshold_local(thresholds, config_id, q_hex, artifact_hash)
selected = thresholds(string({thresholds.measurement_config_id}) == ...
    string(config_id));
if numel(selected) ~= 1 || ...
        ~strcmp(num2hex(selected.q_global), q_hex) || ...
        ~strcmp(selected.threshold_artifact_hash, artifact_hash)
    error('stage8_1b_frozen_context:ThresholdIdentity', ...
        'The committed threshold identity changed for %s.', config_id);
end
end
