function result = stage8_1b_sharded_merge_finalize(repo_dir, runtime_root)
%STAGE8_1B_SHARDED_MERGE_FINALIZE Merge 6000 checkpoints and finalize Phase B.

repo_dir = char(string(repo_dir));
runtime_root = char(string(runtime_root));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
protocol = jsondecode(fileread(fullfile(runtime_root, 'protocol.json')));
context = stage8_1b_frozen_context(repo_dir, true);
stage8_1b_verify_protocol(protocol, context);
constants = context.constants;
if ~strcmpi(canonical_local(runtime_root), ...
        canonical_local(constants.formal_runtime_root)) || ...
        double(protocol.common_trial_count) ~= 6000 || ...
        double(protocol.row_count) ~= 12000 || ...
        ~logical(protocol.scientific_formal_run)
    error('stage8_1b_sharded_merge_finalize:FormalProtocol', ...
        'Finalize requires the exact formal V2 runtime protocol.');
end
if ~isempty(dir(fullfile(runtime_root, 'tmp', '*.tmp'))) || ...
        ~isempty(dir(fullfile(runtime_root, 'workers', '*.current.lock')))
    error('stage8_1b_sharded_merge_finalize:ActiveWrite', ...
        'Finalize is forbidden while tmp files or current locks exist.');
end
worker_status_files = dir(fullfile(runtime_root, 'workers', ...
    'worker_*_status.json'));
for index = 1:numel(worker_status_files)
    worker = jsondecode(fileread(fullfile(worker_status_files(index).folder, ...
        worker_status_files(index).name)));
    if ~strcmp(string(worker.worker_state), "COMPLETE")
        error('stage8_1b_sharded_merge_finalize:WorkerState', ...
            'Every selected worker must be COMPLETE before finalization.');
    end
end
if numel(worker_status_files) < double(protocol.selected_worker_count)
    error('stage8_1b_sharded_merge_finalize:WorkerStatus', ...
        'Selected worker status files are incomplete.');
end

registry = context.registry;
pair_ids = unique(string(registry.common_trial_id), 'stable');
checkpoint_files = dir(fullfile(runtime_root, 'checkpoints', '*.mat'));
if numel(checkpoint_files) ~= 6000 || numel(pair_ids) ~= 6000
    error('stage8_1b_sharded_merge_finalize:CheckpointCardinality', ...
        'Exactly 6000 final checkpoints are required.');
end
row_cells = cell(numel(pair_ids), 1);
content_hashes = strings(numel(pair_ids), 1);
runtime_seconds = zeros(numel(pair_ids), 1);
for index = 1:numel(pair_ids)
    expected = registry(registry.common_trial_id == pair_ids(index), :);
    path_now = fullfile(runtime_root, 'checkpoints', ...
        [char(pair_ids(index)), '.mat']);
    if ~isfile(path_now)
        error('stage8_1b_sharded_merge_finalize:MissingCheckpoint', ...
            'Missing formal checkpoint: %s.', pair_ids(index));
    end
    stage8_1b_validate_checkpoint(path_now, protocol, expected);
    loaded = load(path_now, 'checkpoint', '-mat');
    row_cells{index} = loaded.checkpoint.rows;
    content_hashes(index) = string(loaded.checkpoint.content_hash);
    runtime_seconds(index) = double(loaded.checkpoint.runtime_sec);
end
if numel(unique(content_hashes)) ~= 6000
    error('stage8_1b_sharded_merge_finalize:DuplicateContent', ...
        'Formal checkpoint content hashes must be unique per common trial.');
end
trials = sortrows(vertcat(row_cells{:}), 'evaluation_row_index');
if height(trials) ~= 12000 || ...
        numel(unique(string(trials.common_trial_id))) ~= 6000 || ...
        ~isequal(double(trials.evaluation_row_index), (1:12000).')
    error('stage8_1b_sharded_merge_finalize:RowCardinality', ...
        'Merged raw trials are incomplete, duplicated, or misordered.');
end
[summary, gate, paired_sensitivity] = ...
    summarize_stage8_k1_validation(trials, context.plan.validation.K1);
if height(summary) ~= 14 || height(paired_sensitivity) ~= 6000
    error('stage8_1b_sharded_merge_finalize:DerivedCardinality', ...
        'Merged summary or paired sensitivity cardinality is invalid.');
end
coverage = groupsummary(trials, ...
    {'stratum_id','measurement_config_id'});
if height(coverage) ~= 12 || any(coverage.GroupCount ~= 1000)
    error('stage8_1b_sharded_merge_finalize:Coverage', ...
        'Every stratum/configuration must have exactly 1000 rows.');
end
full_parent = string(summary.measurement_config_id) == ...
    "SENSITIVITY_FULL_PARENT_5X5";
if nnz(full_parent) ~= 7 || any(string(summary.authorization_role(full_parent)) ~= ...
        "SENSITIVITY_ONLY_NOT_USED_FOR_STAGE8_2_AUTHORIZATION") || ...
        gate.sensitivity_used_for_authorization_flag
    error('stage8_1b_sharded_merge_finalize:AuthorizationRole', ...
        'FULL_PARENT must remain sensitivity-only.');
end

output = struct('trials', trials, 'summary', summary, 'gate', gate, ...
    'paired_sensitivity', paired_sensitivity, ...
    'threshold_contract', build_stage8_threshold_contract(context.plan), ...
    'stage8_stable_code_identity_hash', ...
    constants.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', constants.stage8_plan_hash, ...
    'stage8_calibration_plan_hash', ...
    constants.stage8_calibration_plan_hash, ...
    'stage8_validation_plan_hash', ...
    constants.stage8_validation_plan_hash, ...
    'measurement_registry_hash', constants.measurement_registry_hash, ...
    'calibration_evidence_bundle_hash', ...
    constants.calibration_evidence_bundle_hash, ...
    'threshold_set_hash', constants.threshold_set_hash, ...
    'calibration_artifact_snapshot', context.calibration_snapshot, ...
    'calibration_artifact_snapshot_hash', ...
    context.calibration_snapshot_hash, ...
    'committed_threshold_preflight_status', ...
    'COMMITTED_THRESHOLD_PREFLIGHT_PASS', ...
    'validation_execution_status', ...
    'STAGE8_1_K1_VALIDATION_COMPLETED', ...
    'threshold_lookup_only_flag', true, ...
    'threshold_modification_flag', false, ...
    'paired_common_trial_count', 6000, 'method_row_count', 12000, ...
    'execution_scope', ...
    'FORMAL_STAGE8_1_K1_VALIDATION_SHARDED_RESUMABLE_V2', ...
    'phase_factor', 1, ...
    'runtime', active_wall_seconds_local(runtime_root));
output.validation_trial_set_hash = stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_TRIAL_SET_V1', trials);
output.validation_summary_hash = stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_SUMMARY_V1', summary);
output.paired_sensitivity_hash = stage8_stable_hash( ...
    'STAGE8_1_PAIRED_SENSITIVITY_V1', paired_sensitivity);
output.primary_gate_hash = stage8_stable_hash( ...
    'STAGE8_1_PRIMARY_GATE_V1', gate);
validated = validate_stage8_1_validation_output( ...
    context.plan, context.calibration, output);
if ~strcmp(validated.validation_trial_set_hash, ...
        output.validation_trial_set_hash)
    error('stage8_1b_sharded_merge_finalize:Validator', ...
        'Final validator did not retain the merged trial hash.');
end
merged_root = fullfile(runtime_root, 'merged');
save(fullfile(merged_root, 'stage8_1b_merged_output.mat'), ...
    'output', 'validated', 'content_hashes', 'runtime_seconds', '-v7.3');

committed_calibration_evidence = struct( ...
    'repo_dir', repo_dir, 'artifact_root', step);
final = run_stage8_1_finalize( ...
    context.plan, committed_calibration_evidence, output, step, struct( ...
    'formal_run', true, ...
    'execution_authorization', 'AUTHORIZE_STAGE8_1_FINALIZE'));
if final.stage8_2_executed_flag || ...
        ~final.stage8_2_separate_authorization_required_flag || ...
        final.validation_gate_pass ~= output.gate.gate_pass
    error('stage8_1b_sharded_merge_finalize:Stage82Boundary', ...
        'Finalizer violated the Stage8.2 authorization boundary.');
end
expected_names = sort([ ...
    "stage8_1_k1_validation_trials.csv", ...
    "stage8_1_k1_validation_summary.csv", ...
    "stage8_1_k1_paired_sensitivity.csv", ...
    "stage8_1_validation_provenance.csv", ...
    "stage8_1_keypoints.csv", "stage8_1_report.md", ...
    "stage8_1_validation_evidence_manifest.csv", ...
    "stage8_1_runtime_diagnostics.csv"]);
result_files = dir(fullfile(step, 'results'));
actual_names = sort(string({result_files(~[result_files.isdir]).name}));
actual_names(actual_names == ".gitkeep") = [];
if ~isequal(actual_names, expected_names)
    error('stage8_1b_sharded_merge_finalize:ResultManifest', ...
        'Finalizer did not write exactly the eight authorized artifacts.');
end
result = struct('protocol_stage', 'FINALIZED_RESULTS_WRITTEN', ...
    'checkpoint_count', 6000, 'row_count', 12000, ...
    'summary_row_count', 14, 'paired_sensitivity_row_count', 6000, ...
    'validation_gate_pass', logical(output.gate.gate_pass), ...
    'validation_gate_status', output.gate.gate_status, ...
    'validation_trial_set_hash', output.validation_trial_set_hash, ...
    'validation_summary_hash', output.validation_summary_hash, ...
    'paired_sensitivity_hash', output.paired_sensitivity_hash, ...
    'primary_gate_hash', output.primary_gate_hash, ...
    'threshold_set_hash', output.threshold_set_hash, ...
    'calibration_evidence_bundle_hash', ...
    output.calibration_evidence_bundle_hash, ...
    'calibration_snapshot_hash', output.calibration_artifact_snapshot_hash, ...
    'active_wall_sec', output.runtime, ...
    'summed_successful_trial_compute_sec', sum(runtime_seconds), ...
    'stage8_2_executed_flag', false, ...
    'stage8_2_separate_authorization_required_flag', true, ...
    'written_artifact_count', 8, 'completed_utc', utc_now_local());
stage8_1b_write_json_atomic( ...
    fullfile(merged_root, 'finalization_audit.json'), result);
clear path_cleanup
end

function total_sec = active_wall_seconds_local(root)
files = dir(fullfile(root, 'workers', 'attempt_*.json'));
starts = zeros(0, 1);
ends = zeros(0, 1);
for index = 1:numel(files)
    value = jsondecode(fileread(fullfile(files(index).folder, files(index).name)));
    if isempty(value.started_utc) || isempty(value.ended_utc) || ...
            strcmp(string(value.completion_status), "ERROR_STOPPED")
        continue;
    end
    starts(end + 1, 1) = parse_utc_local(value.started_utc); %#ok<AGROW>
    ends(end + 1, 1) = parse_utc_local(value.ended_utc); %#ok<AGROW>
end
if isempty(starts)
    error('stage8_1b_sharded_merge_finalize:Runtime', ...
        'No completed worker attempt intervals are available.');
end
[starts, order] = sort(starts);
ends = ends(order);
current_start = starts(1);
current_end = ends(1);
total_sec = 0;
for index = 2:numel(starts)
    if starts(index) <= current_end
        if ends(index) > current_end, current_end = ends(index); end
    else
        total_sec = total_sec + seconds(current_end - current_start);
        current_start = starts(index);
        current_end = ends(index);
    end
end
total_sec = total_sec + seconds(current_end - current_start);
end

function value = parse_utc_local(text_value)
parsed = datetime(char(string(text_value)), 'TimeZone', 'UTC', ...
    'InputFormat', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''');
value = posixtime(parsed);
end

function value = canonical_local(value)
value = char(java.io.File(char(string(value))).getCanonicalPath());
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
