function protocol = stage8_1b_initialize_runtime( ...
    repo_dir, runtime_root, pilot_decision_path)
%STAGE8_1B_INITIALIZE_RUNTIME Create the immutable formal runtime protocol.

repo_dir = char(string(repo_dir));
runtime_root = char(string(runtime_root));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
decision = jsondecode(fileread(char(string(pilot_decision_path))));
required = {'gate0_pass','gate1_pass','gate2a_pass','pilot_decision', ...
    'selected_worker_count','selected_execution_mode','fallback_reason'};
if ~all(isfield(decision, required)) || ~decision.gate0_pass || ...
        ~decision.gate1_pass || ~decision.gate2a_pass || ...
        ~ismember(double(decision.selected_worker_count), [1, 2])
    error('stage8_1b_initialize_runtime:PilotDecision', ...
        'Formal Init requires passing Gate 0, Gate 1, and Gate 2A.');
end
context = stage8_1b_frozen_context(repo_dir, true);
protocol_path = fullfile(runtime_root, 'protocol.json');
if isfile(protocol_path)
    protocol = jsondecode(fileread(protocol_path));
    stage8_1b_verify_protocol(protocol, context);
    clear path_cleanup
    return;
end
if isfolder(fullfile(runtime_root, 'checkpoints')) && ...
        ~isempty(dir(fullfile(runtime_root, 'checkpoints', '*.mat')))
    error('stage8_1b_initialize_runtime:OrphanCheckpoints', ...
        'Formal checkpoints exist without an immutable protocol.');
end
create_runtime_dirs_local(runtime_root);
[status, head] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', context.repo_dir));
if status ~= 0, error('stage8_1b_initialize_runtime:Git', ...
        'Unable to resolve protocol runner commit.'); end
constants = context.constants;
protocol = struct( ...
    'protocol_version', constants.protocol_version, ...
    'execution_authorization', constants.execution_authorization, ...
    'repo_dir', context.repo_dir, 'runtime_root', runtime_root, ...
    'protocol_runner_commit', strtrim(head), ...
    'protocol_source_tree_hash', ...
    stage8_1b_protocol_source_tree_hash(context.repo_dir), ...
    'threshold_evidence_commit', constants.threshold_evidence_commit, ...
    'stage8_stable_code_identity_hash', ...
    constants.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', constants.stage8_plan_hash, ...
    'stage8_calibration_plan_hash', ...
    constants.stage8_calibration_plan_hash, ...
    'stage8_validation_plan_hash', ...
    constants.stage8_validation_plan_hash, ...
    'measurement_registry_hash', constants.measurement_registry_hash, ...
    'calibration_evidence_bundle_hash', ...
    constants.calibration_evidence_bundle_hash, ...
    'threshold_set_hash', constants.threshold_set_hash, ...
    'calibration_snapshot_hash', context.calibration_snapshot_hash, ...
    'matlab_release', 'R2022b', 'threads_per_worker', 1, ...
    'requested_worker_count', 2, ...
    'selected_worker_count', double(decision.selected_worker_count), ...
    'selected_execution_mode', char(string(decision.selected_execution_mode)), ...
    'pilot_decision', char(string(decision.pilot_decision)), ...
    'fallback_reason', char(string(decision.fallback_reason)), ...
    'status_interval_minutes', 15, ...
    'automatic_start_enabled', false, ...
    'automatic_pause_enabled', false, ...
    'automatic_shutdown_enabled', false, ...
    'status_task_name', constants.status_task_name, ...
    'partition_rule', 'ODD_EVEN_GLOBAL_COMMON_TRIAL_INDEX', ...
    'stratum_ids', {cellstr(string( ...
    context.plan.validation.K1.strata.stratum_id))}, ...
    'trials_per_stratum', constants.formal_trials_per_stratum, ...
    'common_trial_count', constants.formal_common_trial_count, ...
    'row_count', constants.formal_row_count, 'Bsep', constants.Bsep, ...
    'scientific_formal_run', true, ...
    'pause_check_boundary', 'BETWEEN_COMMON_TRIALS', ...
    'checkpoint_contract_version', ...
    constants.checkpoint_contract_version, ...
    'created_utc', utc_now_local());
stage8_1b_write_json_atomic(protocol_path, protocol);
writetable(context.calibration_snapshot, ...
    fullfile(runtime_root, 'frozen_calibration_snapshot.csv'));
stage8_1b_verify_protocol(protocol, context);
clear path_cleanup
end

function create_runtime_dirs_local(root)
if ~isfolder(root), mkdir(root); end
names = {'control','checkpoints','tmp','incomplete','workers','logs', ...
    'status','merged','pilot'};
for index = 1:numel(names)
    path_now = fullfile(root, names{index});
    if ~isfolder(path_now), mkdir(path_now); end
end
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
