function result = stage8_1b_pilot_gate1(repo_dir, pilot_root)
%STAGE8_1B_PILOT_GATE1 Compare the external evaluator to the reference runner.

repo_dir = char(string(repo_dir));
pilot_root = char(string(pilot_root));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if ~isfolder(pilot_root), mkdir(pilot_root); end
result_path = fullfile(pilot_root, 'gate1_result.json');
result = struct('gate1_pass', false, 'protocol_stage', ...
    'GATE1_REFERENCE_RUNNING', 'last_error', '');
stage8_1b_write_json_atomic(result_path, result);
try
    context = stage8_1b_frozen_context(repo_dir, true);
    reference_clock = tic;
    reference = run_stage8_1_k1_validation( ...
        context.plan.validation, context.plan.local_domain, ...
        context.plan.measurement_model_registry, context.thresholds, ...
        build_stage8_stage5_locked_config(), struct( ...
        'formal_run', false, 'max_common_trials_per_stratum', 10, ...
        'evaluation_callback', [], 'fit_options', struct(), ...
        'Bsep', 199, 'run_separation', true, ...
        'execution_authorization', '', 'frozen_plan', context.plan));
    reference_wall_sec = toc(reference_clock);

    selected = context.registry( ...
        context.registry.trial_index_within_stratum <= 10, :);
    pair_ids = unique(string(selected.common_trial_id), 'stable');
    external_cells = cell(numel(pair_ids), 1);
    external_clock = tic;
    for index = 1:numel(pair_ids)
        pair_rows = selected(selected.common_trial_id == pair_ids(index), :);
        external_cells{index} = stage8_1b_evaluate_common_trial( ...
            pair_rows, context.plan, context.thresholds, struct( ...
            'formal_run', false, 'fit_options', struct(), ...
            'Bsep', 199, 'run_separation', true));
    end
    external_trials = sortrows(vertcat(external_cells{:}), ...
        'evaluation_row_index');
    external_wall_sec = toc(external_clock);
    [external_summary, external_gate, external_paired] = ...
        summarize_stage8_k1_validation( ...
        external_trials, context.plan.validation.K1);

    reference_trials = sortrows(reference.trials, 'evaluation_row_index');
    reference_hash = stage8_stable_hash( ...
        'STAGE8_1_VALIDATION_TRIAL_SET_V1', reference_trials);
    external_hash = stage8_stable_hash( ...
        'STAGE8_1_VALIDATION_TRIAL_SET_V1', external_trials);
    row_equal = strcmp(reference_hash, external_hash) && ...
        height(reference_trials) == 120 && height(external_trials) == 120;
    lambda_equal = isequal(num2hex(double(reference_trials.lambda_12)), ...
        num2hex(double(external_trials.lambda_12)));
    state_equal = isequal(string(reference_trials.state), ...
        string(external_trials.state));
    separation_equal = isequal(string(reference_trials.separation_status), ...
        string(external_trials.separation_status));
    element_hash_equal = isequal(string(reference_trials.element_trial_hash), ...
        string(external_trials.element_trial_hash));
    derived_equal = strcmp(stage8_stable_hash(reference.summary), ...
        stage8_stable_hash(external_summary)) && ...
        strcmp(stage8_stable_hash(reference.paired_sensitivity), ...
        stage8_stable_hash(external_paired)) && ...
        strcmp(stage8_stable_hash('STAGE8_1_PRIMARY_GATE_V1', ...
        reference.gate), stage8_stable_hash( ...
        'STAGE8_1_PRIMARY_GATE_V1', external_gate));
    gate1_pass = row_equal && lambda_equal && state_equal && ...
        separation_equal && element_hash_equal && derived_equal;
    natural_separation_trigger_count = nnz( ...
        isfinite(external_trials.lambda_12) & ...
        external_trials.lambda_12 > external_trials.q_global);
    result = struct('gate1_pass', gate1_pass, ...
        'protocol_stage', ternary_local(gate1_pass, ...
        'GATE1_REFERENCE_PASS', 'GATE1_REFERENCE_FAIL_STOPPED'), ...
        'reference_row_hash', reference_hash, ...
        'external_row_hash', external_hash, ...
        'row_equality', row_equal, 'lambda_num2hex_equality', lambda_equal, ...
        'state_equality', state_equal, ...
        'separation_status_equality', separation_equal, ...
        'element_trial_hash_equality', element_hash_equal, ...
        'summary_gate_paired_equality', derived_equal, ...
        'natural_separation_trigger_count', ...
        natural_separation_trigger_count, ...
        'forced_separation_fixture_required', ...
        natural_separation_trigger_count == 0, ...
        'reference_wall_sec', reference_wall_sec, ...
        'external_wall_sec', external_wall_sec, ...
        'last_error', '');
    save(fullfile(pilot_root, 'gate1_rows.mat'), 'reference', ...
        'external_trials', 'external_summary', 'external_gate', ...
        'external_paired', '-mat');
    stage8_1b_write_json_atomic(result_path, result);
    if ~gate1_pass
        error('stage8_1b_pilot_gate1:ReferenceMismatch', ...
            'External common-trial evaluator differs from the reference runner.');
    end
catch exception
    if ~isfield(result, 'reference_row_hash')
        result.protocol_stage = 'GATE1_REFERENCE_FAIL_STOPPED';
        result.last_error = getReport(exception, 'extended', ...
            'hyperlinks', 'off');
        stage8_1b_write_json_atomic(result_path, result);
    end
    rethrow(exception);
end
clear path_cleanup
end

function value = ternary_local(condition, yes_value, no_value)
if condition, value = yes_value; else, value = no_value; end
end
