function result = stage8_1b_formal_preflight(repo_dir, output_root)
%STAGE8_1B_FORMAL_PREFLIGHT Execute Gate 0 after the tools commit.

repo_dir = char(string(repo_dir));
output_root = char(string(output_root));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if ~isfolder(output_root), mkdir(output_root); end
result_path = fullfile(output_root, 'gate0_preflight.json');
result = struct('gate0_pass', false, 'protocol_stage', ...
    'GATE0_FORMAL_PREFLIGHT_RUNNING', 'checked_utc', utc_now_local(), ...
    'last_error', '');
stage8_1b_write_json_atomic(result_path, result);
try
    if ~strcmp(version('-release'), '2022b') || maxNumCompThreads ~= 1
        error('stage8_1b_formal_preflight:Runtime', ...
            'Gate 0 requires MATLAB R2022b -singleCompThread.');
    end
    context = stage8_1b_frozen_context(repo_dir, true);
    constants = context.constants;
    [head_status, head] = system(sprintf( ...
        'git -C "%s" rev-parse HEAD', repo_dir));
    [status_code, status_text] = system(sprintf( ...
        'git -C "%s" status --porcelain=v1 --untracked-files=all', ...
        repo_dir));
    [ancestor_status, ~] = system(sprintf( ...
        'git -C "%s" merge-base --is-ancestor %s HEAD', ...
        repo_dir, constants.threshold_evidence_commit));
    step_relative = ['beamspace_ml_v18/source/stepwise_signal_model/steps/', ...
        'step_12_6_k12_bootstrap_resolution'];
    [diff_status, step_diff] = system(sprintf( ...
        'git -C "%s" diff --name-only %s..HEAD -- "%s"', ...
        repo_dir, constants.threshold_evidence_commit, step_relative));
    if head_status ~= 0 || status_code ~= 0 || ...
            ~isempty(strtrim(status_text)) || ancestor_status ~= 0 || ...
            diff_status ~= 0 || ~isempty(strtrim(step_diff))
        error('stage8_1b_formal_preflight:Repository', ...
            'Git clean/ancestry/frozen-step checks failed.');
    end
    calibration_files = dir(fullfile(step, 'calibration', '*.csv'));
    results_files = dir(fullfile(step, 'results'));
    result_names = string({results_files(~[results_files.isdir]).name});
    if numel(calibration_files) ~= 13 || ...
            numel(result_names) ~= 1 || result_names ~= ".gitkeep"
        error('stage8_1b_formal_preflight:Artifacts', ...
            'Calibration must contain 13 CSVs and results only .gitkeep.');
    end
    writetable(context.calibration_snapshot, ...
        fullfile(output_root, 'gate0_calibration_snapshot.csv'));
    result = struct( ...
        'gate0_pass', true, ...
        'protocol_stage', 'GATE0_FORMAL_PREFLIGHT_PASS', ...
        'checked_utc', utc_now_local(), ...
        'protocol_runner_commit', strtrim(head), ...
        'protocol_source_tree_hash', ...
        stage8_1b_protocol_source_tree_hash(repo_dir), ...
        'stage8_stable_code_identity_hash', ...
        constants.stage8_stable_code_identity_hash, ...
        'stage8_plan_hash', constants.stage8_plan_hash, ...
        'stage8_calibration_plan_hash', ...
        constants.stage8_calibration_plan_hash, ...
        'stage8_validation_plan_hash', ...
        constants.stage8_validation_plan_hash, ...
        'measurement_registry_hash', constants.measurement_registry_hash, ...
        'calibration_evidence_bundle_hash', ...
        constants.calibration_evidence_bundle_hash, ...
        'threshold_set_hash', constants.threshold_set_hash, ...
        'calibration_snapshot_hash', context.calibration_snapshot_hash, ...
        'primary_threshold_artifact_hash', ...
        constants.primary_threshold_artifact_hash, ...
        'sensitivity_threshold_artifact_hash', ...
        constants.sensitivity_threshold_artifact_hash, ...
        'calibration_freeze_status', ...
        context.calibration.calibration_freeze_status, ...
        'committed_threshold_preflight_status', ...
        context.calibration.committed_threshold_preflight_status, ...
        'calibration_csv_count', numel(calibration_files), ...
        'results_directory_clean', true, 'stage8_step_diff_empty', true, ...
        'last_error', '');
    stage8_1b_write_json_atomic(result_path, result);
catch exception
    result.protocol_stage = 'GATE0_FAIL_STOPPED';
    result.checked_utc = utc_now_local();
    result.last_error = getReport(exception, 'extended', ...
        'hyperlinks', 'off');
    stage8_1b_write_json_atomic(result_path, result);
    rethrow(exception);
end
clear path_cleanup
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
