function audit = stage8_1b_validate_checkpoint( ...
    checkpoint_path, protocol, expected_rows)
%STAGE8_1B_VALIDATE_CHECKPOINT Validate one immutable common-trial file.

if nargin < 3, expected_rows = table(); end
if ischar(protocol) || (isstring(protocol) && isscalar(protocol))
    protocol = jsondecode(fileread(char(protocol)));
end
loaded = load(char(string(checkpoint_path)), 'checkpoint', '-mat');
if ~isfield(loaded, 'checkpoint') || ...
        ~(isstruct(loaded.checkpoint) && isscalar(loaded.checkpoint))
    error('stage8_1b_validate_checkpoint:Payload', ...
        'Checkpoint does not contain one scalar checkpoint struct.');
end
checkpoint = loaded.checkpoint;
required = {'protocol_version','checkpoint_contract_version', ...
    'common_trial_id','global_common_trial_index','rows', ...
    'stage8_stable_code_identity_hash','stage8_plan_hash', ...
    'stage8_validation_plan_hash','measurement_registry_hash', ...
    'calibration_evidence_bundle_hash','threshold_set_hash', ...
    'calibration_snapshot_hash','threshold_lookup_only_flag', ...
    'threshold_modification_flag','completion_status','content_hash', ...
    'runtime_sec','worker_id','attempt_id','created_utc'};
if ~all(isfield(checkpoint, required))
    error('stage8_1b_validate_checkpoint:Contract', ...
        'Checkpoint is missing one or more required fields.');
end
expected_names = {'evaluation_row_index','stratum_index','stratum_id', ...
    'common_trial_id','pairing_key','trial_index_within_stratum', ...
    'measurement_config_id','noise_profile_id','L','parameter_seed', ...
    'element_noise_seed','separation_auxiliary_seed','center_az_deg', ...
    'center_el_deg','snr_db','element_trial_hash', ...
    'threshold_calibration_hash','threshold_artifact_hash','q_global', ...
    'lambda_12','state','false_split_flag','false_resolved_flag', ...
    'K2_UNRESOLVED_flag','SEARCH_NOT_CONVERGED_flag', ...
    'NUMERIC_RANK_DEFICIENT_flag','decision_available_flag', ...
    'fit1_validity_status','fit2_validity_status','separation_status'};
if ~istable(checkpoint.rows) || ...
        ~isequal(checkpoint.rows.Properties.VariableNames, expected_names)
    error('stage8_1b_validate_checkpoint:RowSchema', ...
        'Checkpoint rows do not preserve the frozen row schema and order.');
end
protocol_fields = {'protocol_version','checkpoint_contract_version', ...
    'stage8_stable_code_identity_hash','stage8_plan_hash', ...
    'stage8_validation_plan_hash','measurement_registry_hash', ...
    'calibration_evidence_bundle_hash','threshold_set_hash', ...
    'calibration_snapshot_hash'};
for index = 1:numel(protocol_fields)
    field = protocol_fields{index};
    if ~isfield(protocol, field) || ...
            ~strcmp(string(checkpoint.(field)), string(protocol.(field)))
        error('stage8_1b_validate_checkpoint:ProtocolIdentity', ...
            'Checkpoint field %s differs from the protocol.', field);
    end
end
if ~(istable(checkpoint.rows) && height(checkpoint.rows) == 2) || ...
        numel(unique(string(checkpoint.rows.common_trial_id))) ~= 1 || ...
        string(checkpoint.rows.common_trial_id(1)) ~= ...
        string(checkpoint.common_trial_id) || ...
        ~isequal(sort(string(checkpoint.rows.measurement_config_id)), ...
        sort(["PRIMARY_RECT_E14_A31"; "SENSITIVITY_FULL_PARENT_5X5"]))
    error('stage8_1b_validate_checkpoint:Rows', ...
        'Checkpoint rows are not one complete paired common trial.');
end
text_fields = {'stratum_id','common_trial_id','pairing_key', ...
    'measurement_config_id','noise_profile_id','element_trial_hash', ...
    'threshold_calibration_hash','threshold_artifact_hash','state', ...
    'fit1_validity_status','fit2_validity_status','separation_status'};
logical_fields = {'false_split_flag','false_resolved_flag', ...
    'K2_UNRESOLVED_flag','SEARCH_NOT_CONVERGED_flag', ...
    'NUMERIC_RANK_DEFICIENT_flag','decision_available_flag'};
numeric_fields = setdiff(expected_names, [text_fields, logical_fields], ...
    'stable');
if any(~cellfun(@(name) isstring(checkpoint.rows.(name)), text_fields)) || ...
        any(~cellfun(@(name) islogical(checkpoint.rows.(name)), logical_fields)) || ...
        any(~cellfun(@(name) isnumeric(checkpoint.rows.(name)), numeric_fields))
    error('stage8_1b_validate_checkpoint:RowTypes', ...
        'Checkpoint row column types differ from the frozen row contract.');
end
if ~isequal(sort(double(checkpoint.rows.evaluation_row_index)), ...
        [2 * double(checkpoint.global_common_trial_index) - 1; ...
        2 * double(checkpoint.global_common_trial_index)])
    error('stage8_1b_validate_checkpoint:GlobalIndex', ...
        'Checkpoint global index differs from its evaluation rows.');
end
if ~logical(checkpoint.threshold_lookup_only_flag) || ...
        logical(checkpoint.threshold_modification_flag) || ...
        ~strcmp(string(checkpoint.completion_status), "COMPLETE_PASS")
    error('stage8_1b_validate_checkpoint:Completion', ...
        'Checkpoint threshold/completion flags are invalid.');
end
if ~(isnumeric(checkpoint.runtime_sec) && isscalar(checkpoint.runtime_sec) && ...
        isfinite(checkpoint.runtime_sec) && checkpoint.runtime_sec >= 0 && ...
        isnumeric(checkpoint.worker_id) && isscalar(checkpoint.worker_id) && ...
        checkpoint.worker_id >= 1 && checkpoint.worker_id == fix(checkpoint.worker_id) && ...
        strlength(string(checkpoint.attempt_id)) > 0 && ...
        strlength(string(checkpoint.created_utc)) > 0)
    error('stage8_1b_validate_checkpoint:Diagnostics', ...
        'Checkpoint runtime diagnostics are invalid.');
end
computed_hash = stage8_1b_checkpoint_content_hash(checkpoint);
if ~strcmp(string(checkpoint.content_hash), string(computed_hash))
    error('stage8_1b_validate_checkpoint:ContentHash', ...
        'Checkpoint scientific content hash is invalid.');
end
if ~isempty(expected_rows)
    expected_rows = sortrows(expected_rows, 'evaluation_row_index');
    actual_rows = sortrows(checkpoint.rows, 'evaluation_row_index');
    registry_names = expected_rows.Properties.VariableNames;
    if ~all(ismember(registry_names, actual_rows.Properties.VariableNames)) || ...
            ~strcmp(stage8_stable_hash(actual_rows(:, registry_names)), ...
            stage8_stable_hash(expected_rows))
        error('stage8_1b_validate_checkpoint:Registry', ...
            'Checkpoint rows differ from the frozen registry.');
    end
end
audit = struct('valid', true, ...
    'common_trial_id', char(string(checkpoint.common_trial_id)), ...
    'global_common_trial_index', ...
    double(checkpoint.global_common_trial_index), ...
    'content_hash', char(string(computed_hash)), ...
    'runtime_sec', double(checkpoint.runtime_sec), ...
    'worker_id', double(checkpoint.worker_id), ...
    'created_utc', char(string(checkpoint.created_utc)));
end
