function result = stage8_1b_forced_separation_fixture( ...
    repo_dir, output_path)
%STAGE8_1B_FORCED_SEPARATION_FIXTURE Exercise Bsep=199 when pilot has none.

repo_dir = char(string(repo_dir));
output_path = char(string(output_path));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
context = stage8_1b_frozen_context(repo_dir, true);
selected = context.registry( ...
    context.registry.trial_index_within_stratum <= 10, :);
pair_ids = unique(string(selected.common_trial_id), 'stable');
rows = table();
diagnostics = struct();
for index = 1:numel(pair_ids)
    pair = selected(selected.common_trial_id == pair_ids(index), :);
    [candidate, diagnostic_now] = stage8_1b_evaluate_common_trial( ...
        pair, context.plan, context.thresholds, struct( ...
        'formal_run', false, 'Bsep', 199, 'run_separation', true, ...
        'fit_options', struct(), 'force_separation_fixture', true));
    if diagnostic_now.separation_trigger_row_count > 0
        rows = candidate;
        diagnostics = diagnostic_now;
        break;
    end
end
if isempty(rows)
    error('stage8_1b_forced_separation_fixture:NoValidFit', ...
        'No pilot fixture produced a valid K2 fit for forced separation.');
end
result = struct('pass', true, ...
    'common_trial_id', diagnostics.common_trial_id, ...
    'row_hash', stage8_stable_hash( ...
    'STAGE8_1B_FORCED_SEPARATION_FIXTURE_V1', rows), ...
    'lambda_hex', {cellstr(num2hex(double(rows.lambda_12)))}, ...
    'state', {cellstr(string(rows.state))}, ...
    'separation_status', {cellstr(string(rows.separation_status))}, ...
    'Bsep', 199, 'formal_substream_count', 199);
save(output_path, 'rows', 'result', '-mat');
stage8_1b_write_json_atomic([output_path, '.json'], result);
clear path_cleanup
end
