function [result_table, context] = test_group_noise_propagation()
%TEST_GROUP_NOISE_PROPAGATION Validate the full recovered-group covariance.

Ge = [1.0, 0.25; 0.35, 1.0; 0.15, -0.30; -0.20, 0.45];
Rphi = toeplitz(0.55 .^ (0:2));
[model, debug] = propagate_group_recovery_noise(Ge, Rphi, struct());
reference_H = pinv(Ge);
reference_R_group = reference_H * reference_H';
algebra_error = norm(model.R_group - reference_R_group, 'fro') / ...
    norm(reference_R_group, 'fro');

rng(125101, 'twister');
checkpoints = [2000; 20000];
Nmax = checkpoints(end);
C_input = kron(Rphi, eye(size(Ge, 1)));
C_expected = kron(Rphi, model.R_group);
L_input = chol(C_input, 'lower');
E = complex(randn(size(C_input, 1), Nmax), ...
    randn(size(C_input, 1), Nmax)) / sqrt(2);
noise = L_input * E;
recovered = kron(eye(size(Rphi, 1)), debug.H_e) * noise;
sample_error = zeros(numel(checkpoints), 1);
alpha_error = zeros(numel(checkpoints), 1);
for idx = 1:numel(checkpoints)
    count = checkpoints(idx);
    sample_covariance = recovered(:, 1:count) * ...
        recovered(:, 1:count)' / count;
    sample_error(idx) = norm(sample_covariance - C_expected, 'fro') / ...
        norm(C_expected, 'fro');
    first_column = sample_covariance(1:size(Ge, 2), 1:size(Ge, 2));
    alpha_error(idx) = max(abs(real(diag(first_column)) - ...
        model.group_noise_scale));
end

rank_deficient = [Ge(:, 1), Ge(:, 1)];
[rank_model, ~] = propagate_group_recovery_noise( ...
    rank_deficient, Rphi, struct());
pass_flag = algebra_error < 1e-12 && sample_error(end) < 0.04 && ...
    sample_error(end) < sample_error(1) && alpha_error(end) < 0.03 && ...
    strcmp(model.status, 'GROUP_NOISE_PROPAGATION_RETURNED') && ...
    strcmp(rank_model.status, 'GROUP_NOISE_PROPAGATION_RANK_UNCERTIFIED');

statistical_calibration_status = repmat("NOT_CALIBRATED_STAGE5", 2, 1);
phase_factor = ones(2, 1);
pass_column = repmat(pass_flag, 2, 1);
algebra_relative_error = repmat(algebra_error, 2, 1);
rank_Ge = repmat(model.rank_Ge, 2, 1);
propagation_status = repmat(string(model.status), 2, 1);
group_noise_scale = repmat(string(mat2str( ...
    model.group_noise_scale.', 12)), 2, 1);
cross_group_noise_correlation = repmat(string(mat2str( ...
    model.cross_group_noise_correlation, 12)), 2, 1);
rank_deficient_status = repmat(string(rank_model.status), 2, 1);
result_table = table(checkpoints, sample_error, alpha_error, ...
    algebra_relative_error, rank_Ge, propagation_status, group_noise_scale, ...
    cross_group_noise_correlation, rank_deficient_status, ...
    statistical_calibration_status, pass_column, phase_factor, ...
    'VariableNames', {'n_samples','full_covariance_relative_error', ...
    'max_group_scale_absolute_error','algebra_relative_error','rank_Ge', ...
    'propagation_status', ...
    'group_noise_scale','cross_group_noise_correlation', ...
    'rank_deficient_status','statistical_calibration_status', ...
    'pass_flag','phase_factor'});
assert(pass_flag, 'test_group_noise_propagation:Failed', ...
    'The recovered-group noise propagation validation failed.');

context = struct('algebra_error', algebra_error, ...
    'sample_error', sample_error, 'alpha_error', alpha_error, ...
    'R_group', model.R_group, ...
    'cross_group_noise_correlation', model.cross_group_noise_correlation, ...
    'rank_deficient_status', rank_model.status, 'num_svd', 2);
end
