function [result_table, context] = test_upstream_group_gate(cfg)
%TEST_UPSTREAM_GROUP_GATE Verify that uncertified grouping stops stage 5.

array_meta = arr_cyl(cfg, cfg.beam.azSectorCenter);
[Uq, bank_info] = build_fixed_conditional_azimuth_beam_bank( ...
    [7.4, 8.0, 8.6], 10, array_meta, ...
    struct('lambda', cfg.arr.lambda));
X = complex(zeros(cfg.beam.subNaz, 2));
prepare_opts = struct('eta_condition_deg', 10, ...
    'condition_source', 'ESTIMATED_ELEVATION', ...
    'upstream_group_support_status', 'GROUP_MMV_RANK_UNCERTIFIED', ...
    'estimate_returned_flag', false, 'structural_gate_pass_flag', false, ...
    'array_coordinates', bank_info.array_coordinates, ...
    'lambda', cfg.arr.lambda, 'beam_bank_hash', bank_info.beam_bank_hash);
[conditional_data, conditional_model] = prepare_conditional_azimuth_data( ...
    X, Uq, eye(cfg.beam.subNaz), 1, prepare_opts);
locked = build_stage5_locked_config();
[domain, ~] = build_common_registered_local_domain( ...
    locked.conventional_center_deg, locked.domain_options);
[conditional_estimate, ~] = estimate_conditional_azimuth_dml( ...
    conditional_data, 1, domain, conditional_model, struct());

fixture = build_stage5_physical_fixture( ...
    stage5_design_spec(cfg, 'K1', 0), cfg, locked);
joint_opts = struct('require_upstream_group_gate', true, ...
    'upstream_estimate_returned_flag', false, ...
    'upstream_structural_gate_pass_flag', false, ...
    'upstream_group_support_status', 'GROUP_MMV_RANK_UNCERTIFIED');
[joint_estimate, joint_history] = refine_joint_sequential_dml( ...
    fixture.full_data, [8, 10], fixture.domain, fixture.full_model, joint_opts);
conditional_stopped = strcmp(conditional_estimate.conditional_estimate_status, ...
    'UPSTREAM_GROUP_STAGE_UNCERTIFIED') && ...
    conditional_estimate.num_score_eval == 0;
joint_stopped = strcmp(joint_estimate.joint_refinement_status, ...
    'JOINT_REFINEMENT_NOT_RUN_UPSTREAM_UNCERTIFIED') && ...
    joint_estimate.num_score_eval == 0 && isempty(joint_history);
pass_flag = conditional_stopped && joint_stopped;

component = ["conditional_azimuth"; "joint_refinement"];
method_estimate_status = [string(conditional_estimate.conditional_estimate_status); ...
    string(joint_estimate.joint_refinement_status)];
num_score_eval = [conditional_estimate.num_score_eval; joint_estimate.num_score_eval];
upstream_group_support_status = repmat("GROUP_MMV_RANK_UNCERTIFIED", 2, 1);
statistical_calibration_status = repmat("NOT_CALIBRATED_STAGE5", 2, 1);
pass_column = [conditional_stopped; joint_stopped];
phase_factor = ones(2, 1);
result_table = table(component, method_estimate_status, num_score_eval, ...
    upstream_group_support_status, statistical_calibration_status, ...
    pass_column, phase_factor, 'VariableNames', {'component', ...
    'method_estimate_status','num_score_eval','upstream_group_support_status', ...
    'statistical_calibration_status','pass_flag','phase_factor'});
assert(pass_flag, 'test_upstream_group_gate:Failed', ...
    'An uncertified upstream group was processed by stage 5.');
context = struct('conditional_estimate', conditional_estimate, ...
    'joint_estimate', joint_estimate);
end
