function [result_table, context] = ...
    test_oracle_estimated_perturbed_elevation(cfg)
%TEST_ORACLE_ESTIMATED_PERTURBED_ELEVATION Run all registered condition chains.

locked = build_stage5_locked_config();
spec = stage5_design_spec(cfg, 'Q1_K2', 0.001);
spec.name = 'design_three_elevation_condition_chains';
spec.target_angles_deg(:, 2) = 10.1;
fixture = build_stage5_physical_fixture(spec, cfg, locked);
grid_step = locked.elevation_offsets_deg(2) - ...
    locked.elevation_offsets_deg(1);
fraction = [0, NaN, -0.5, -0.25, -0.1, 0.1, 0.25, 0.5];
source = ["ORACLE_ELEVATION"; "ESTIMATED_ELEVATION"; ...
    repmat("PERTURBED_ELEVATION", 6, 1)];
eta_condition = zeros(numel(fraction), 1);
eta_condition(1) = fixture.eta_true_deg;
eta_condition(2) = fixture.stage4_est.eta_hat_deg;
eta_condition(3:end) = fixture.eta_true_deg + fraction(3:end).' * grid_step;
rows = cell(numel(fraction), 1);
chains = cell(numel(fraction), 1);
for idx = 1:numel(fraction)
    chain = run_stage5_conditional_chain( ...
        fixture, eta_condition(idx), source(idx));
    [~, match] = match_target_sets(chain.initial_angles_deg, ...
        spec.target_angles_deg, struct());
    rows{idx} = struct('scenario', string(spec.name), ...
        'condition_source', source(idx), ...
        'elevation_grid_fraction', fraction(idx), ...
        'eta_condition_deg', eta_condition(idx), ...
        'elevation_condition_error_deg', ...
        eta_condition(idx) - fixture.eta_true_deg, ...
        'az_hat_deg', string(vector_text_local( ...
        chain.initial_angles_deg(:, 1).')), ...
        'azimuth_rmse_deg', match.azimuth_rmse_deg, ...
        'pair_rmse_deg', match.pair_rmse_deg, ...
        'conditional_estimate_status', ...
        string(chain.group_estimate{1}.conditional_estimate_status), ...
        'statistical_calibration_status', "NOT_CALIBRATED_STAGE5", ...
        'pass_flag', chain.returned_flag && isfinite(match.pair_rmse_deg), ...
        'phase_factor', 1);
    chains{idx} = chain;
end
result_table = struct2table(vertcat(rows{:}));
oracle_rmse = result_table.azimuth_rmse_deg(1);
estimated_rmse = result_table.azimuth_rmse_deg(2);
perturbed_rmse = mean(result_table.azimuth_rmse_deg(3:end));
context = struct('fixture', fixture, 'chains', {chains}, ...
    'oracle_to_estimated_degradation', estimated_rmse - oracle_rmse, ...
    'estimated_to_perturbed_degradation', perturbed_rmse - estimated_rmse, ...
    'azimuth_bias_vs_elevation_error_correlation', ...
    correlation_local(result_table.elevation_condition_error_deg(3:end), ...
    result_table.azimuth_rmse_deg(3:end)));
assert(all(result_table.pass_flag), ...
    'test_oracle_estimated_perturbed_elevation:Failed', ...
    'At least one registered elevation-condition chain did not return.');
end

function value = correlation_local(x, y)
C = corrcoef(x, y);
if numel(C) == 4
    value = C(1, 2);
else
    value = NaN;
end
end

function text = vector_text_local(value)
text = strtrim(sprintf('%.12g ', value));
end
