function result_table = test_stage5_scope_rules(step_dir)
%TEST_STAGE5_SCOPE_RULES Scan active public stage-5 code for forbidden routes.

common_dir = fullfile(step_dir, 'common');
files = { ...
    'propagate_group_recovery_noise.m', ...
    'build_fixed_conditional_azimuth_beam_bank.m', ...
    'prepare_conditional_azimuth_data.m', ...
    'build_conditional_azimuth_manifold.m', ...
    'estimate_conditional_azimuth_dml.m', ...
    'prepare_full_sequential_dml_data.m', ...
    'build_full_sequential_local_manifold.m', ...
    'refine_joint_sequential_dml.m', ...
    'build_stage5_configuration_hash.m', ...
    'build_common_registered_local_domain.m'};
source = '';
for idx = 1:numel(files)
    source = [source, newline, fileread(fullfile(common_dir, files{idx}))]; %#ok<AGROW>
end
lower_source = lower(source);
rule = ["legacy_composite_token_absent"; "truncated_candidate_token_absent"; ...
    "score_gap_control_branch_absent"; "phase_factor_two_absent"; ...
    "fixed_ridge_absent"; "confidence_wording_absent"; ...
    "candidate_dependent_measurement_absent"; ...
    "reference_dependent_domain_absent"];
value = false(numel(rule), 1);
value(1) = ~contains(lower_source, lower(['C', '05']));
value(2) = ~contains(lower_source, lower(['top', 'K']));
value(3) = isempty(regexp(lower_source, ...
    'if[^\n]*(score[^\n]*gap|gap[^\n]*score)', 'once'));
value(4) = isempty(regexp(lower_source, ...
    '(phasefactor|phase_factor)\s*=\s*2', 'once'));
value(5) = isempty(regexp(lower_source, ...
    '(ridge[^\n]*1e-10|1e-10[^\n]*ridge)', 'once'));
value(6) = ~contains(lower_source, lower(['high ', 'confidence']));
value(7) = isempty(regexp(lower_source, ...
    'candidate[^\n]*(rebuild|regenerate)[^\n]*(wseq|whitener)', 'once'));
domain_source = lower(fileread(fullfile(common_dir, ...
    'build_common_registered_local_domain.m')));
value(8) = ~contains(domain_source, lower(['tr', 'uth']));
statistical_calibration_status = repmat("NOT_CALIBRATED_STAGE5", ...
    numel(rule), 1);
pass_flag = value;
phase_factor = ones(numel(rule), 1);
result_table = table(rule, value, statistical_calibration_status, ...
    pass_flag, phase_factor);
assert(all(pass_flag), 'test_stage5_scope_rules:Failed', ...
    'Active stage-5 public code contains a forbidden route.');
end
