function [result_table, context] = test_full_sequential_data_equivalence(cfg)
%TEST_FULL_SEQUENTIAL_DATA_EQUIVALENCE Validate Zseq, Cseq, and whitening.

locked = build_stage5_locked_config();
fixture = build_stage5_physical_fixture( ...
    stage5_design_spec(cfg, 'Q1_K2', 0), cfg, locked);
[Zel, V] = form_elevation_dbf_cube( ...
    fixture.Yelem, locked.el_beam_deg, cfg);
[Zseq_cube, Uset] = form_azimuth_dbf_cube( ...
    Zel, locked.az_beam_deg, locked.el_beam_deg, cfg);
[Wseq_reference, ~] = build_sequential_beam_matrix( ...
    V, Uset, fixture.array_meta);
Zseq_staged = reshape(Zseq_cube, size(fixture.Wseq, 2), []);
staged_error = norm(Zseq_staged - fixture.full_data.Zseq_raw, 'fro') / ...
    max(norm(fixture.full_data.Zseq_raw, 'fro'), eps);
beam_matrix_error = norm(Wseq_reference - fixture.Wseq, 'fro') / ...
    norm(fixture.Wseq, 'fro');
C_explicit = fixture.Wseq' * fixture.Rn_elem * fixture.Wseq;
explicit_covariance_error = norm(C_explicit - fixture.full_model.Cseq, 'fro') / ...
    norm(C_explicit, 'fro');

rng(125104, 'twister');
sample_count = 5000;
chunk_size = 250;
sum_z = complex(zeros(size(C_explicit, 1), 1));
sum_zz = complex(zeros(size(C_explicit)));
for start_index = 1:chunk_size:sample_count
    count = min(chunk_size, sample_count - start_index + 1);
    noise = complex(randn(size(fixture.Wseq, 1), count), ...
        randn(size(fixture.Wseq, 1), count)) / sqrt(2);
    Z = fixture.Wseq' * noise;
    sum_z = sum_z + sum(Z, 2);
    sum_zz = sum_zz + Z * Z';
end
mean_z = sum_z / sample_count;
C_sample = sum_zz / sample_count - mean_z * mean_z';
sample_covariance_error = norm(C_sample - C_explicit, 'fro') / ...
    norm(C_explicit, 'fro');
whitening_error = fixture.full_debug.whitening_error;
hash_match = strcmp(fixture.full_data.fixed_measurement_hash, ...
    fixture.full_model.fixed_measurement_hash);
pass_flag = staged_error < 1e-12 && beam_matrix_error < 1e-12 && ...
    explicit_covariance_error < 1e-12 && sample_covariance_error < 0.08 && ...
    whitening_error < 1e-10 && hash_match;

metric = ["staged_direct_relative_error"; "beam_matrix_relative_error"; ...
    "explicit_covariance_relative_error"; ...
    "monte_carlo_covariance_relative_error"; "whitening_relative_error"];
value = [staged_error; beam_matrix_error; explicit_covariance_error; ...
    sample_covariance_error; whitening_error];
registered_gate = [1e-12; 1e-12; 1e-12; 0.08; 1e-10];
pass_column = value < registered_gate;
statistical_calibration_status = repmat("NOT_CALIBRATED_STAGE5", 5, 1);
phase_factor = ones(5, 1);
result_table = table(metric, value, registered_gate, ...
    statistical_calibration_status, pass_column, phase_factor, ...
    'VariableNames', {'metric','value','registered_gate', ...
    'statistical_calibration_status','pass_flag','phase_factor'});
assert(pass_flag, 'test_full_sequential_data_equivalence:Failed', ...
    'The original full-sequential data validation failed.');
context = struct('fixture', fixture, 'staged_error', staged_error, ...
    'explicit_covariance_error', explicit_covariance_error, ...
    'sample_covariance_error', sample_covariance_error, ...
    'whitening_error', whitening_error, 'sample_count', sample_count, ...
    'num_eig', 1);
end
