function [result_table, context] = test_conditional_azimuth_noise_whitening(cfg)
%TEST_CONDITIONAL_AZIMUTH_NOISE_WHITENING Validate conditional covariance.

array_meta = arr_cyl(cfg, cfg.beam.azSectorCenter);
[Uq, bank_info] = build_fixed_conditional_azimuth_beam_bank( ...
    [7.4, 8.0, 8.6], 10, array_meta, ...
    struct('lambda', cfg.arr.lambda));
Nphi = cfg.beam.subNaz;
Rphi = toeplitz(0.65 .^ (0:Nphi - 1));
alpha = 1.7;
sample_count = 30000;
rng(125103, 'twister');
E = complex(randn(Nphi, sample_count), randn(Nphi, sample_count)) / sqrt(2);
Xnoise = sqrt(alpha) * chol(Rphi, 'lower') * E;
opts = struct('eta_condition_deg', 10, 'condition_source', 'DESIGN', ...
    'upstream_group_support_status', 'GROUP_REGISTERED_MODEL_CERTIFIED', ...
    'estimate_returned_flag', true, 'structural_gate_pass_flag', true, ...
    'array_coordinates', bank_info.array_coordinates, ...
    'lambda', cfg.arr.lambda, 'beam_bank_hash', bank_info.beam_bank_hash);
[data, ~, debug] = prepare_conditional_azimuth_data( ...
    Xnoise, Uq, Rphi, alpha, opts);
C_sample = data.Zphi_white * data.Zphi_white' / sample_count;
I = eye(size(C_sample));
sample_whitening_error = norm(C_sample - I, 'fro') / norm(I, 'fro');
pass_flag = debug.whitening_error < 1e-10 && ...
    sample_whitening_error < 0.03 && debug.whitening_rank == size(Uq, 2);

n_samples = sample_count;
analytic_whitening_error = debug.whitening_error;
whitening_rank = debug.whitening_rank;
registered_gate = 0.03;
statistical_calibration_status = "NOT_CALIBRATED_STAGE5";
phase_factor = 1;
result_table = table(n_samples, analytic_whitening_error, ...
    sample_whitening_error, whitening_rank, registered_gate, ...
    statistical_calibration_status, pass_flag, phase_factor);
assert(pass_flag, 'test_conditional_azimuth_noise_whitening:Failed', ...
    'The fixed conditional covariance did not whiten to identity.');
context = struct('analytic_whitening_error', debug.whitening_error, ...
    'sample_whitening_error', sample_whitening_error, ...
    'sample_count', sample_count, 'num_eig', 1);
end
