function [result_table, context] = test_joint_refinement_monotonicity(cfg)
%TEST_JOINT_REFINEMENT_MONOTONICITY Check fixed-grid score monotonicity.

locked = build_stage5_locked_config();
fixture = build_stage5_physical_fixture( ...
    stage5_design_spec(cfg, 'Q1_K2', 0), cfg, locked);
conditional_chain = run_stage5_conditional_chain( ...
    fixture, fixture.stage4_est.eta_hat_deg, 'ESTIMATED_ELEVATION');
initial_angles = conditional_chain.initial_angles_deg;
opts = joint_options_local(locked, fixture);
[estimate, history, debug] = refine_joint_sequential_dml( ...
    fixture.full_data, initial_angles, fixture.domain, ...
    fixture.full_model, opts);
reference = run_local_full_dml_reference( ...
    fixture.full_data, fixture.K, fixture.domain, fixture.full_model);
normalized_score_gap = (reference.score - estimate.score) / ...
    max(abs(reference.score), eps);
score_difference = diff(history.score);
numeric_tolerance = 64 * numel(fixture.full_data.Zseq_white) * ...
    eps(max(1, max(abs(history.score))));
minimum_increment = min([0; score_difference]);
pass_flag = debug.monotonicity_violation_count == 0 && ...
    minimum_increment >= -numeric_tolerance && ...
    normalized_score_gap <= 1e-10 && estimate.estimate_returned_flag;

iteration = history.iteration;
score = history.score;
rss = history.rss;
max_angle_update_deg = history.max_angle_update_deg;
relative_score_change = history.relative_score_change;
monotonicity_violation_flag = history.monotonicity_violation_flag;
statistical_calibration_status = history.statistical_calibration_status;
phase_factor = history.phase_factor;
pass_column = repmat(pass_flag, height(history), 1);
result_table = table(iteration, score, rss, max_angle_update_deg, ...
    relative_score_change, monotonicity_violation_flag, ...
    statistical_calibration_status, pass_column, phase_factor, ...
    'VariableNames', {'iteration','score','rss','max_angle_update_deg', ...
    'relative_score_change','monotonicity_violation_flag', ...
    'statistical_calibration_status','pass_flag','phase_factor'});
if ~pass_flag
    disp(result_table);
    fprintf('normalized_score_gap=%.16g, violations=%d, tolerance=%.16g\n', ...
        normalized_score_gap, debug.monotonicity_violation_count, ...
        numeric_tolerance);
    disp(estimate.angles_hat_deg);
    disp(reference.angles_hat_deg);
end
assert(pass_flag, 'test_joint_refinement_monotonicity:Failed', ...
    'The joint coordinate update violated monotonicity or missed local full.');
context = struct('fixture', fixture, 'estimate', estimate, ...
    'history', history, 'debug', debug, 'reference', reference, ...
    'conditional_chain', conditional_chain, ...
    'normalized_score_gap', normalized_score_gap, ...
    'numeric_tolerance', numeric_tolerance);
end

function opts = joint_options_local(locked, fixture)
opts = struct('max_iter', locked.max_iter, ...
    'relative_score_tolerance', locked.relative_score_tolerance, ...
    'angle_tolerance_deg', locked.angle_tolerance_deg, ...
    'require_upstream_group_gate', true, ...
    'upstream_estimate_returned_flag', ...
    fixture.stage4_est.estimate_returned_flag, ...
    'upstream_structural_gate_pass_flag', ...
    fixture.stage4_est.structural_gate_pass_flag, ...
    'upstream_group_support_status', fixture.stage4_est.support_status, ...
    'method_status_scope', 'METHOD_AND_UPSTREAM_REGISTERED_MODEL', ...
    'num_multi_start', locked.main_num_multi_start);
end
