function result_table = test_baseline_status_scope(step_dir)
%TEST_BASELINE_STATUS_SCOPE Keep fixture support separate from baselines.

stage4_path = fullfile(step_dir, 'results', 'elevation_group_trial.csv');
stage4 = readtable(stage4_path, 'TextType', 'string');
peak = stage4.method == "elevation_beam_peak";
stage4_pass = any(peak) && all(stage4.method_status_scope(peak) == ...
    "UPSTREAM_FIXTURE_ONLY") && ...
    all(stage4.method_certification_status(peak) == ...
    "NOT_APPLICABLE_BASELINE") && ...
    all(~stage4.registered_model_certified_flag(peak));

method = ["DIRECT_AP_COORDINATE_ASCENT_FIXED_CENTER"; ...
    "LOCAL_FULL_DML_REFERENCE"; "CONVENTIONAL_DBF"];
upstream_group_support_status = repmat( ...
    "GROUP_REGISTERED_MODEL_SUPPORTED_UNCALIBRATED", 3, 1);
method_estimate_status = ["JOINT_REFINEMENT_CONVERGED"; ...
    "LOCAL_FULL_REFERENCE_RETURNED"; "CONVENTIONAL_DBF_RETURNED"];
method_status_scope = repmat("METHOD_ONLY", 3, 1);
registered_model_certified_flag = false(3, 1);
statistical_calibration_status = repmat("NOT_CALIBRATED_STAGE5", 3, 1);
pass_flag = method_status_scope == "METHOD_ONLY" & ...
    ~registered_model_certified_flag & stage4_pass;
phase_factor = ones(3, 1);
result_table = table(method, upstream_group_support_status, ...
    method_estimate_status, method_status_scope, ...
    registered_model_certified_flag, statistical_calibration_status, ...
    pass_flag, phase_factor);
assert(all(pass_flag), 'test_baseline_status_scope:Failed', ...
    'A baseline inherited registered-model certification from its fixture.');
end
