function [result_table, context] = test_conditional_azimuth_fixed_measurement(cfg)
%TEST_CONDITIONAL_AZIMUTH_FIXED_MEASUREMENT Verify fixed U/T/hash across search.

array_meta = arr_cyl(cfg, cfg.beam.azSectorCenter);
[Uq, bank_info] = build_fixed_conditional_azimuth_beam_bank( ...
    [7.4, 8.0, 8.6], 10, array_meta, ...
    struct('lambda', cfg.arr.lambda));
rng(125102, 'twister');
X = complex(randn(cfg.beam.subNaz, 4), ...
    randn(cfg.beam.subNaz, 4)) / sqrt(2);
opts = struct('eta_condition_deg', 10, 'condition_source', 'DESIGN', ...
    'upstream_group_support_status', 'GROUP_REGISTERED_MODEL_CERTIFIED', ...
    'estimate_returned_flag', true, 'structural_gate_pass_flag', true, ...
    'array_coordinates', bank_info.array_coordinates, ...
    'lambda', cfg.arr.lambda, 'beam_bank_hash', bank_info.beam_bank_hash);
[~, model] = prepare_conditional_azimuth_data( ...
    X, Uq, eye(cfg.beam.subNaz), 1, opts);
U_before = model.Uq;
T_before = model.Tphi_q;
hash_before = model.fixed_measurement_hash;
candidate_sets = {7.4, 8.0, [7.6, 8.4]};
hash_match = false(numel(candidate_sets), 1);
object_match = false(numel(candidate_sets), 1);
for idx = 1:numel(candidate_sets)
    [~, ~, info] = build_conditional_azimuth_manifold( ...
        candidate_sets{idx}, model, struct());
    hash_match(idx) = strcmp(info.fixed_measurement_hash, hash_before);
    object_match(idx) = isequal(model.Uq, U_before) && ...
        isequal(model.Tphi_q, T_before);
end
pass_flag = all(hash_match & object_match);
candidate = string(cellfun(@vector_text_local, candidate_sets, ...
    'UniformOutput', false)).';
fixed_measurement_hash = repmat(string(hash_before), numel(candidate_sets), 1);
statistical_calibration_status = repmat("NOT_CALIBRATED_STAGE5", ...
    numel(candidate_sets), 1);
phase_factor = ones(numel(candidate_sets), 1);
result_table = table(candidate, fixed_measurement_hash, hash_match, ...
    object_match, statistical_calibration_status, phase_factor, ...
    'VariableNames', {'candidate_az_deg','fixed_measurement_hash', ...
    'hash_match','fixed_objects_unchanged','statistical_calibration_status', ...
    'phase_factor'});
assert(pass_flag, 'test_conditional_azimuth_fixed_measurement:Failed', ...
    'A candidate changed a fixed conditional measurement object.');
context = struct('fixed_measurement_hash', hash_before, ...
    'candidate_count', numel(candidate_sets), 'pass_flag', pass_flag);
end

function text = vector_text_local(value)
text = strtrim(sprintf('%.12g ', value));
end
