function result_table = test_no_truth_dependent_domain(step_dir)
%TEST_NO_TRUTH_DEPENDENT_DOMAIN Audit the active domain constructor contract.

builder_path = fullfile(step_dir, 'common', ...
    'build_common_registered_local_domain.m');
source = fileread(builder_path);
reserved_token = lower(['tr', 'uth']);
token_absent = ~contains(lower(source), reserved_token);
signature_argument_count = nargin('build_common_registered_local_domain');
locked = build_stage5_locked_config();
[domain_a, info_a] = build_common_registered_local_domain( ...
    locked.conventional_center_deg, locked.domain_options);
[domain_b, info_b] = build_common_registered_local_domain( ...
    locked.conventional_center_deg, locked.domain_options);
reproducible_hash = strcmp(domain_a.domain_hash, domain_b.domain_hash) && ...
    strcmp(info_a.domain_hash, info_b.domain_hash);
common_domain_flag = info_a.method_common_flag;
no_post_result_expansion = ~info_a.post_result_expansion_allowed_flag;
pass_flag = token_absent && signature_argument_count == 2 && ...
    reproducible_hash && common_domain_flag && no_post_result_expansion;

rule = ["reserved_reference_token_absent"; ...
    "constructor_has_two_arguments"; "domain_hash_reproducible"; ...
    "method_common_domain"; "post_result_expansion_disabled"];
value = [token_absent; signature_argument_count == 2; reproducible_hash; ...
    common_domain_flag; no_post_result_expansion];
statistical_calibration_status = repmat("NOT_CALIBRATED_STAGE5", 5, 1);
pass_column = value;
phase_factor = ones(5, 1);
result_table = table(rule, value, statistical_calibration_status, ...
    pass_column, phase_factor, 'VariableNames', {'rule','value', ...
    'statistical_calibration_status','pass_flag','phase_factor'});
assert(pass_flag, 'test_no_truth_dependent_domain:Failed', ...
    'The active registered-domain contract permits reference leakage.');
end
