function [result_table, context] = test_joint_refinement_canonical_order(cfg)
%TEST_JOINT_REFINEMENT_CANONICAL_ORDER Verify label-swap set invariance.

locked = build_stage5_locked_config();
fixture = build_stage5_physical_fixture( ...
    stage5_design_spec(cfg, 'Q1_K2', 0), cfg, locked);
initial = [7.4, 10.0; 8.6, 10.0];
opts = joint_options_local(locked, fixture);
[estimate_a, ~, debug_a] = refine_joint_sequential_dml( ...
    fixture.full_data, initial, fixture.domain, fixture.full_model, opts);
[estimate_b, ~, debug_b] = refine_joint_sequential_dml( ...
    fixture.full_data, flipud(initial), fixture.domain, fixture.full_model, opts);
[matched_b, match] = match_target_sets( ...
    estimate_b.angles_hat_deg, estimate_a.angles_hat_deg, struct());
set_difference = norm(matched_b - estimate_a.angles_hat_deg, 'fro');
score_difference = abs(estimate_b.score - estimate_a.score) / ...
    max(abs(estimate_a.score), eps);
pass_flag = set_difference < 1e-12 && score_difference < 1e-12 && ...
    debug_a.monotonicity_violation_count == 0 && ...
    debug_b.monotonicity_violation_count == 0;

case_name = ["original_labels"; "swapped_labels"];
az_hat_deg = [string(vector_text_local(estimate_a.az_hat_deg)); ...
    string(vector_text_local(estimate_b.az_hat_deg))];
el_hat_deg = [string(vector_text_local(estimate_a.el_hat_deg)); ...
    string(vector_text_local(estimate_b.el_hat_deg))];
score = [estimate_a.score; estimate_b.score];
canonical_order = repmat("elevation_then_azimuth", 2, 1);
statistical_calibration_status = repmat("NOT_CALIBRATED_STAGE5", 2, 1);
pass_column = repmat(pass_flag, 2, 1);
phase_factor = ones(2, 1);
result_table = table(case_name, az_hat_deg, el_hat_deg, score, ...
    canonical_order, statistical_calibration_status, pass_column, phase_factor, ...
    'VariableNames', {'case_name','az_hat_deg','el_hat_deg','score', ...
    'canonical_order','statistical_calibration_status','pass_flag','phase_factor'});
assert(pass_flag, 'test_joint_refinement_canonical_order:Failed', ...
    'A target-label swap changed the final canonical set.');
context = struct('fixture', fixture, 'estimate_a', estimate_a, ...
    'estimate_b', estimate_b, 'match', match, ...
    'set_difference', set_difference, 'score_difference', score_difference);
end

function opts = joint_options_local(locked, fixture)
opts = struct('max_iter', locked.max_iter, ...
    'relative_score_tolerance', locked.relative_score_tolerance, ...
    'angle_tolerance_deg', locked.angle_tolerance_deg, ...
    'require_upstream_group_gate', true, ...
    'upstream_estimate_returned_flag', ...
    fixture.stage4_est.estimate_returned_flag, ...
    'upstream_structural_gate_pass_flag', ...
    fixture.stage4_est.structural_gate_pass_flag, ...
    'upstream_group_support_status', fixture.stage4_est.support_status);
end

function text = vector_text_local(value)
text = strtrim(sprintf('%.12g ', value));
end
