function [result_table, context] = test_stage5_method_suite_design(cfg)
%TEST_STAGE5_METHOD_SUITE_DESIGN Validate all registered method wrappers.

locked = build_stage5_locked_config();
fixture = build_stage5_physical_fixture( ...
    stage5_design_spec(cfg, 'Q1_K2', 0), cfg, locked);
suite = run_stage5_method_suite(fixture, 1);
result_table = suite.method_table;
expected = ["MAIN_GROUPED_CONDITIONAL_JOINT"; ...
    "GROUPED_CONDITIONAL_ONLY"; ...
    "DIRECT_AP_COORDINATE_ASCENT_FIXED_CENTER"; ...
    "LOCAL_FULL_DML_REFERENCE"; "CONVENTIONAL_DBF"];
method_set_pass = isequal(sort(result_table.method), sort(expected));
main = result_table.method == "MAIN_GROUPED_CONDITIONAL_JOINT";
reference = result_table.method == "LOCAL_FULL_DML_REFERENCE";
baseline = result_table.method == ...
    "DIRECT_AP_COORDINATE_ASCENT_FIXED_CENTER";
pass_flag = method_set_pass && all(result_table.pass_flag) && ...
    result_table.normalized_score_gap_to_local_full(main) <= 1e-10 && ...
    result_table.num_score_eval_total(main) < ...
    result_table.num_score_eval_total(reference) && ...
    result_table.num_multi_start(baseline) == 2 && ...
    all(result_table.statistical_calibration_status == ...
    "NOT_CALIBRATED_STAGE5");
if ~pass_flag
    disp(result_table);
end
assert(pass_flag, 'test_stage5_method_suite_design:Failed', ...
    'The registered stage-5 method suite failed its design contract.');
context = struct('fixture', fixture, 'suite', suite, ...
    'method_set_pass', method_set_pass);
end
