function [result_table, context] = test_conditional_azimuth_q1_k2(cfg)
%TEST_CONDITIONAL_AZIMUTH_Q1_K2 Validate Kq=1 and same-elevation Kq=2.

locked = build_stage5_locked_config();
modes = {'K1', 'Q1_K2'};
rows = cell(numel(modes), 1);
fixtures = cell(numel(modes), 1);
chains = cell(numel(modes), 1);
for idx = 1:numel(modes)
    spec = stage5_design_spec(cfg, modes{idx}, 0);
    fixture = build_stage5_physical_fixture(spec, cfg, locked);
    chain = run_stage5_conditional_chain( ...
        fixture, fixture.stage4_est.eta_hat_deg, 'ESTIMATED_ELEVATION');
    [~, match] = match_target_sets(chain.initial_angles_deg, ...
        spec.target_angles_deg, struct());
    expected_Kq = max(fixture.oracle_Kq);
    group_rank = chain.group_estimate{1}.rank_Gphi;
    pass_flag = fixture.stage4_est.estimate_returned_flag && ...
        chain.returned_flag && match.azimuth_rmse_deg < 1e-10 && ...
        group_rank == expected_Kq;
    rows{idx} = struct('scenario', string(spec.name), ...
        'oracle_Q', fixture.Q, 'oracle_Kq', expected_Kq, ...
        'az_hat_deg', string(vector_text_local( ...
        chain.initial_angles_deg(:, 1).')), ...
        'azimuth_rmse_deg', match.azimuth_rmse_deg, ...
        'rank_Gphi', group_rank, ...
        'conditional_estimate_status', ...
        string(chain.group_estimate{1}.conditional_estimate_status), ...
        'statistical_calibration_status', "NOT_CALIBRATED_STAGE5", ...
        'pass_flag', pass_flag, 'phase_factor', 1);
    fixtures{idx} = fixture;
    chains{idx} = chain;
end
result_table = struct2table(vertcat(rows{:}));
assert(all(result_table.pass_flag), ...
    'test_conditional_azimuth_q1_k2:Failed', ...
    'A registered Kq=1 or Kq=2 conditional search failed.');
context = struct('fixtures', {fixtures}, 'chains', {chains}, ...
    'num_score_eval', sum(cellfun(@(x) x.num_score_eval, chains)), ...
    'num_svd', sum(cellfun(@(x) x.num_svd, chains)));
end

function text = vector_text_local(value)
text = strtrim(sprintf('%.12g ', value));
end
