function [trial_table, identifiability_table, recovery_table, context] = ...
    test_elevation_group_scenarios(cfg, el_beam_deg)
%TEST_ELEVATION_GROUP_SCENARIOS Exercise all registered phase-4 scenarios.

specs = scenario_specs_local(cfg);
fixtures = cell(numel(specs) + 1, 1);
for idx = 1:numel(specs)
    fixtures{idx} = build_stage4_physical_fixture( ...
        specs(idx), cfg, el_beam_deg);
end
fixtures{end} = build_stage4_structural_fixture(cfg, el_beam_deg);

trial_rows = cell(0, 1);
ident_rows = cell(0, 1);
recovery_rows = cell(0, 1);
total_score_calls = 0;
total_svd_calls = 0;
total_runtime_sec = 0;
common_group_sum_relative_error = NaN;
max_structurally_supported_truth_residual = 0;

for idx = 1:numel(fixtures)
    fixture = fixtures{idx};
    [bank, candidate_parameters_deg] = build_registered_candidate_bank( ...
        fixture.search_grid_deg, fixture.Q, fixture.group_model);

    estimate_tic = tic;
    [est, est_debug] = estimate_elevation_groups_dml( ...
        fixture.data, fixture.Q, fixture.search_grid_deg, ...
        fixture.group_model, struct());
    estimate_runtime_sec = toc(estimate_tic);
    main_error_deg = ordered_angle_error_local( ...
        est.eta_hat_deg, fixture.eta_true_deg);
    main_pass = estimate_pass_local(est, main_error_deg, fixture);
    trial_rows{end + 1, 1} = make_trial_row_local( ...
        fixture, 'grouped_svd_dml', 'registered_local_full_reference', ...
        est, main_error_deg, estimate_runtime_sec, main_pass, ...
        'group_row_whitener'); %#ok<AGROW>
    total_score_calls = total_score_calls + est.num_score_eval;
    total_svd_calls = total_svd_calls + est.num_svd;
    total_runtime_sec = total_runtime_sec + estimate_runtime_sec;

    element_tic = tic;
    [element_est, ~] = estimate_elevation_groups_dml( ...
        fixture.element_data, fixture.Q, fixture.search_grid_deg, ...
        fixture.element_model, struct());
    element_runtime_sec = toc(element_tic);
    element_error_deg = ordered_angle_error_local( ...
        element_est.eta_hat_deg, fixture.eta_true_deg);
    element_pass = estimate_pass_local( ...
        element_est, element_error_deg, fixture);
    trial_rows{end + 1, 1} = make_trial_row_local( ...
        fixture, 'vertical_element_domain_dml', ...
        'registered_local_full_reference', element_est, ...
        element_error_deg, element_runtime_sec, element_pass, ...
        'element_row_whitener'); %#ok<AGROW>
    total_score_calls = total_score_calls + element_est.num_score_eval;
    total_svd_calls = total_svd_calls + element_est.num_svd;
    total_runtime_sec = total_runtime_sec + element_runtime_sec;

    truth_diag_opts = struct('evidence_kind', 'TRUTH_STRUCTURAL', ...
        'row_whitening_rank', fixture.data.row_whitening_rank, ...
        'column_whitening_rank', fixture.data.column_whitening_rank, ...
        'physical_beam_count', fixture.data.physical_beam_count, ...
        'observation_regime', fixture.observation_regime, ...
        'estimate_status', est.estimate_status, ...
        'local_manifold_bank', {bank}, ...
        'local_parameter_deg', candidate_parameters_deg, ...
        'reference_parameter_deg', fixture.eta_true_deg, ...
        'rank_multiplier', 1);
    truth_diag = diagnose_elevation_group_identifiability( ...
        fixture.Ge_true, fixture.Ce_true_recovery, truth_diag_opts);
    score_opts = struct('requested_rank', fixture.Q, ...
        'rank_multiplier', 1, 'compute_projector_checks', false);
    [~, truth_rss] = beamspace_dml_score_svd( ...
        fixture.signal_data.Z_score_mmv, fixture.Ge_true, score_opts);
    total_score_calls = total_score_calls + 1;
    total_svd_calls = total_svd_calls + truth_diag.num_svd + 1;
    truth_rss_relative = truth_rss / max( ...
        norm(fixture.signal_data.Z_score_mmv, 'fro') ^ 2, ...
        realmin(class(fixture.signal_data.Z_score_mmv)));
    truth_residual = max( ...
        fixture.truth_recovery_model_relative_residual, ...
        fixture.truth_score_model_relative_residual);
    if ~strcmp(fixture.expected_support_status, ...
            'GROUP_MMV_RANK_UNCERTIFIED')
        max_structurally_supported_truth_residual = max( ...
            max_structurally_supported_truth_residual, ...
            max(truth_residual, truth_rss_relative));
    end
    ident_pass = identifiability_pass_local( ...
        fixture, truth_diag, est, truth_rss_relative);
    ident_rows{end + 1, 1} = make_ident_row_local( ...
        fixture, truth_diag, est, truth_rss_relative, ...
        ident_pass); %#ok<AGROW>

    if fixture.Q == 1
        peak_tic = tic;
        peak_est = beam_peak_baseline_local(fixture);
        peak_runtime_sec = toc(peak_tic);
        peak_error_deg = ordered_angle_error_local( ...
            peak_est.eta_hat_deg, fixture.eta_true_deg);
        peak_pass = isfinite(peak_error_deg) && ...
            peak_error_deg <= max(diff(fixture.el_beam_deg));
        trial_rows{end + 1, 1} = make_trial_row_local( ...
            fixture, 'elevation_beam_peak', 'single_peak_q1_only', ...
            peak_est, peak_error_deg, peak_runtime_sec, peak_pass, ...
            'group_row_whitener'); %#ok<AGROW>
        total_runtime_sec = total_runtime_sec + peak_runtime_sec;
    end

    if est.estimate_returned_flag && est.structural_gate_pass_flag
        [Xphi_hat, Ce_hat, recovery_debug] = ...
            recover_group_azimuth_data( ...
            fixture.data, est.Ge_hat, struct('rank_multiplier', 1));
        truth = struct('Xphi', {fixture.Xphi_true}, ...
            'Ce_recovery', fixture.Ce_true_recovery, ...
            'Ge', fixture.Ge_true);
        recovery_metrics = evaluate_group_recovery_against_truth( ...
            Xphi_hat, Ce_hat, est.Ge_hat, truth, struct());
        total_svd_calls = total_svd_calls + recovery_debug.num_svd + ...
            recovery_metrics.num_svd;
        recovery_subspace_gate = recovery_subspace_gate_local( ...
            fixture.noise_kind);
        for q = 1:fixture.Q
            recovery_pass = recovery_debug.recovery_returned_flag && ...
                recovery_metrics.relative_fro_error_by_group(q) <= ...
                fixture.recovery_gate && ...
                recovery_metrics.subspace_chordal_distance_by_group(q) <= ...
                recovery_subspace_gate && ...
                recovery_metrics.max_offdiagonal_crosstalk <= 5e-9 && ...
                recovery_metrics.diagonal_mixing_error <= 5e-9;
            recovery_rows{end + 1, 1} = make_recovery_row_local( ...
                fixture, q, est, recovery_debug, recovery_metrics, ...
                recovery_subspace_gate, recovery_pass); %#ok<AGROW>
        end
        if strcmp(fixture.scenario, 'k2_q1_common_elevation_l3')
            common_group_sum_relative_error = ...
                recovery_metrics.relative_fro_error_by_group(1);
        end
    else
        rejection_pass = strcmp(fixture.expected_estimate_status, ...
            'ESTIMATE_NOT_RUN_STRUCTURAL_RANK_FAILURE') && ...
            strcmp(est.estimate_status, fixture.expected_estimate_status) && ...
            strcmp(est.support_status, fixture.expected_support_status) && ...
            ~est.estimate_returned_flag;
        recovery_rows{end + 1, 1} = make_rejection_recovery_row_local( ...
            fixture, est, rejection_pass); %#ok<AGROW>
    end

    if ~main_pass || ~element_pass || ~ident_pass
        fprintf('Scenario gate failed: %s\n', fixture.scenario);
        disp(est_debug);
    end
end

trial_table = struct2table(vertcat(trial_rows{:}));
identifiability_table = struct2table(vertcat(ident_rows{:}));
recovery_table = struct2table(vertcat(recovery_rows{:}));
peak_rows = trial_table.method == "elevation_beam_peak";
baseline_scope_pass = all(trial_table.upstream_group_support_status(peak_rows) == ...
    trial_table.expected_upstream_group_support_status(peak_rows)) && ...
    all(trial_table.method_status_scope(peak_rows) == "UPSTREAM_FIXTURE_ONLY") && ...
    all(trial_table.method_certification_status(peak_rows) == ...
    "NOT_APPLICABLE_BASELINE") && ...
    all(trial_table.support_status(peak_rows) == "NOT_APPLICABLE_BASELINE") && ...
    all(~trial_table.registered_model_certified_flag(peak_rows)) && ...
    all(~trial_table.structural_gate_pass_flag(peak_rows));
if any(~trial_table.pass_flag)
    disp(trial_table(~trial_table.pass_flag, :));
end
if any(~identifiability_table.pass_flag)
    disp(identifiability_table(~identifiability_table.pass_flag, :));
end
if any(~recovery_table.pass_flag)
    disp(recovery_table(~recovery_table.pass_flag, :));
end
assert(all(trial_table.pass_flag), ...
    'test_elevation_group_scenarios:TrialFailed', ...
    'An elevation-group estimator or baseline gate failed.');
assert(all(identifiability_table.pass_flag), ...
    'test_elevation_group_scenarios:IdentifiabilityFailed', ...
    'An elevation-group registered-support gate failed.');
assert(all(recovery_table.pass_flag), ...
    'test_elevation_group_scenarios:RecoveryFailed', ...
    'An elevation-group recovery gate failed.');
assert(baseline_scope_pass, ...
    'test_elevation_group_scenarios:BaselineStatusScope', ...
    'The elevation-beam baseline inherited registered-model certification.');
assert(common_group_sum_relative_error < 5e-10, ...
    'test_elevation_group_scenarios:CommonGroupSum', ...
    'The common-elevation Q1 recovery did not equal the within-group sum.');

context = struct();
context.fixtures = fixtures;
context.total_score_calls = total_score_calls;
context.total_svd_calls = total_svd_calls;
context.total_multi_start = 0;
context.total_estimator_runtime_sec = total_runtime_sec;
context.common_group_sum_relative_error = common_group_sum_relative_error;
context.max_structurally_supported_truth_residual = ...
    max_structurally_supported_truth_residual;
context.baseline_status_scope_pass = baseline_scope_pass;
context.num_physical_scenarios = numel(specs);
context.num_structural_counterexamples = 1;
context.ap_pr_baseline_status = ...
    'not_run_no_audited_exact_reproduction_available';
end

function specs = scenario_specs_local(cfg)
full_aperture = 1:cfg.beam.subNaz;
center = (cfg.beam.subNaz + 1) / 2;
reduced_aperture = (center - 4):(center + 4);
specs = make_spec_local('k1_q1_l1_noiseless', ...
    [8.0, 10.0], 1, 1, full_aperture, 'none', 0, 120301, ...
    9.0:0.1:11.0, 0.051, 5e-10);
specs(end + 1) = make_spec_local('k1_q1_l4_white_noise', ...
    [8.2, 10.3], [1, exp(0.2j), 0.9 * exp(-0.3j), ...
    1.1 * exp(0.5j)], 1, full_aperture, 'white', 0.005, 120302, ...
    9.3:0.1:11.3, 0.11, 0.08);
specs(end + 1) = make_spec_local('k2_q2_distinct_elevation_l1', ...
    [7.4, 9.2; 8.8, 11.0], [1; 0.8 * exp(0.4j)], [1; 2], ...
    full_aperture, 'none', 0, 120303, 8.6:0.2:11.4, 0.101, 5e-9);
specs(end + 1) = make_spec_local('k2_q1_common_elevation_l3', ...
    [7.2, 10.0; 9.1, 10.0], ...
    [1, 0.8 * exp(0.2j), 1.1 * exp(-0.3j); ...
    0.7 * exp(0.5j), 0.9 * exp(-0.2j), 0.6 * exp(0.8j)], ...
    [1; 1], full_aperture, 'none', 0, 120304, ...
    9.0:0.1:11.0, 0.051, 5e-9);
specs(end + 1) = make_spec_local('k2_q2_extremely_close_l1', ...
    [7.5, 10.0; 9.5, 10.05], [1; 0.8 * exp(0.6j)], [1; 2], ...
    full_aperture, 'none', 0, 120305, 9.95:0.025:10.10, ...
    0.013, 5e-8);
specs(end + 1) = make_spec_local('k2_q2_weak_secondary_l4', ...
    [7.3, 9.4; 9.0, 11.2], ...
    [1, exp(0.2j), exp(-0.4j), exp(0.6j); ...
    0.03 * exp(0.1j), 0.03 * exp(-0.5j), ...
    0.03 * exp(0.7j), 0.03 * exp(-0.9j)], ...
    [1; 2], full_aperture, 'none', 0, 120306, ...
    8.8:0.2:11.6, 0.101, 5e-8);
coherent_waveform = [1, exp(0.3j), 0.9 * exp(-0.2j), ...
    1.1 * exp(0.5j)];
specs(end + 1) = make_spec_local('k2_q2_coherent_sources_l4', ...
    [7.3, 9.4; 9.0, 11.2], ...
    [coherent_waveform; 0.7 * exp(0.4j) * coherent_waveform], ...
    [1; 2], full_aperture, 'none', 0, 120307, ...
    8.8:0.2:11.6, 0.101, 5e-8);
specs(end + 1) = make_spec_local('k2_q2_reduced_aperture_l1', ...
    [7.3, 9.4; 9.0, 11.2], [1; 0.8 * exp(0.4j)], [1; 2], ...
    reduced_aperture, 'none', 0, 120308, ...
    8.8:0.2:11.6, 0.101, 5e-8);
specs(end + 1) = make_spec_local('k2_q2_correlated_noise_l4', ...
    [7.3, 9.4; 9.0, 11.2], ...
    [1, exp(0.2j), exp(-0.4j), exp(0.6j); ...
    0.8 * exp(0.1j), 0.7 * exp(-0.5j), ...
    0.9 * exp(0.7j), 0.75 * exp(-0.9j)], ...
    [1; 2], full_aperture, 'correlated_rows_and_columns', ...
    0.003, 120309, 8.8:0.2:11.6, 0.21, 0.15);
end

function spec = make_spec_local(name, target_angles_deg, source_snapshots, ...
    group_index, aperture_index, noise_kind, noise_sigma, seed, ...
    search_grid_deg, angle_gate_deg, recovery_gate)
spec = struct('name', name, 'target_angles_deg', target_angles_deg, ...
    'source_snapshots', source_snapshots, 'group_index', group_index, ...
    'aperture_index', aperture_index, 'noise_kind', noise_kind, ...
    'noise_sigma', noise_sigma, 'seed', seed, ...
    'search_grid_deg', search_grid_deg, 'angle_gate_deg', angle_gate_deg, ...
    'recovery_gate', recovery_gate);
end

function row = make_trial_row_local(fixture, method, search_reference, ...
    est, angle_error_deg, runtime_sec, pass_flag, whitener_role)
if strcmp(whitener_role, 'element_row_whitener')
    data = fixture.element_data;
    row_error = fixture.element_whitening_info.whitening_error;
else
    data = fixture.data;
    row_error = fixture.row_whitening_error;
end
row = struct();
row.scenario = string(fixture.scenario);
row.fixture_kind = string(fixture.fixture_kind);
row.method = string(method);
row.search_reference = string(search_reference);
row.K = fixture.K;
row.oracle_Q = fixture.Q;
row.Nphi = fixture.Nphi;
row.L = fixture.L;
row.aperture_columns = numel(fixture.aperture_index);
row.noise_model = string(fixture.noise_kind);
row.observation_regime = string(data.observation_regime);
row.coefficient_rank_evidence_kind = ...
    string(est.coefficient_rank_evidence_kind);
row.row_whitening_rank = data.row_whitening_rank;
row.column_whitening_rank = data.column_whitening_rank;
row.column_whitening_applied = data.column_whitening_applied;
row.column_covariance_model = string(data.column_covariance_model);
row.Z_score_column_count = data.mmv_score_column_count;
row.Z_recovery_column_count = data.mmv_physical_column_count;
row.row_whitening_error = row_error;
row.column_whitening_error = fixture.column_whitening_error;
row.truth_on_registered_grid_flag = fixture.truth_on_registered_grid_flag;
row.search_domain_source = string(fixture.search_domain_source);
row.truth_eta_deg = vector_text_local(fixture.eta_true_deg);
row.eta_hat_deg = vector_text_local(est.eta_hat_deg);
row.max_abs_error_deg = angle_error_deg;
row.score = est.score;
row.rss = est.rss;
row.rank_Ge = est.rank_Ge;
row.rank_Ce_hat_diagnostic = est.rank_Ce_hat_diagnostic;
row.rank_Z_score_diagnostic = est.rank_Z_score_diagnostic;
row.rank_Z_recovery_diagnostic = est.rank_Z_recovery_diagnostic;
row.num_score_eval = est.num_score_eval;
row.num_svd = est.num_svd;
row.num_multi_start = 0;
row.runtime_sec = runtime_sec;
row.estimate_status = string(est.estimate_status);
row.support_status = string(est.support_status);
row.upstream_group_support_status = string(fixture.expected_support_status);
row.expected_upstream_group_support_status = ...
    string(fixture.expected_support_status);
if strcmp(method, 'elevation_beam_peak')
    row.method_status_scope = "UPSTREAM_FIXTURE_ONLY";
    row.method_certification_status = "NOT_APPLICABLE_BASELINE";
    row.expected_support_status = "NOT_APPLICABLE_BASELINE";
elseif strcmp(method, 'vertical_element_domain_dml')
    row.method_status_scope = "METHOD_REGISTERED_REFERENCE";
    row.method_certification_status = string(est.support_status);
    row.expected_support_status = string(fixture.expected_support_status);
else
    row.method_status_scope = "METHOD_AND_UPSTREAM_REGISTERED_MODEL";
    row.method_certification_status = string(est.support_status);
    row.expected_support_status = string(fixture.expected_support_status);
end
row.statistical_calibration_status = ...
    string(est.statistical_calibration_status);
row.registered_model_certified_flag = ...
    est.registered_model_certified_flag;
row.structural_gate_pass_flag = est.structural_gate_pass_flag;
row.estimate_returned_flag = est.estimate_returned_flag;
row.expected_estimate_status = string(fixture.expected_estimate_status);
row.pass_flag = pass_flag;
row.phase_factor = 1;
end

function row = make_ident_row_local( ...
    fixture, truth_diag, est, truth_rss_relative, pass_flag)
row = struct();
row.scenario = string(fixture.scenario);
row.fixture_kind = string(fixture.fixture_kind);
row.K = fixture.K;
row.oracle_Q = fixture.Q;
row.B_e = truth_diag.B_e;
row.Nphi = fixture.Nphi;
row.L = fixture.L;
row.Nphi_gt_Q_flag = fixture.Nphi > fixture.Q;
row.observation_regime = string(fixture.observation_regime);
row.coefficient_rank_evidence_kind = ...
    string(truth_diag.coefficient_rank_evidence_kind);
row.row_whitening_rank = truth_diag.row_whitening_rank;
row.column_whitening_rank = truth_diag.column_whitening_rank;
row.column_whitening_applied = fixture.data.column_whitening_applied;
row.column_covariance_model = string(fixture.column_covariance_model);
row.truth_on_registered_grid_flag = fixture.truth_on_registered_grid_flag;
row.search_domain_source = string(fixture.search_domain_source);
row.rank_Ge = truth_diag.rank_Ge;
row.singular_values_Ge = vector_text_local( ...
    truth_diag.singular_values_Ge);
row.sigma_min_Ge = truth_diag.singular_values_Ge(end);
row.sigma_ratio_Ge = truth_diag.singular_values_Ge(end) / ...
    truth_diag.singular_values_Ge(1);
row.rank_threshold_Ge = truth_diag.rank_threshold_Ge;
row.rank_Ce_truth = truth_diag.rank_Ce_evidence;
row.singular_values_Ce_truth = vector_text_local( ...
    truth_diag.singular_values_Ce_evidence);
row.rank_threshold_Ce = truth_diag.rank_threshold_Ce_evidence;
row.rank_Ce_hat_diagnostic = est.rank_Ce_hat_diagnostic;
row.rank_Z_score_diagnostic = est.rank_Z_score_diagnostic;
row.rank_Z_recovery_diagnostic = est.rank_Z_recovery_diagnostic;
row.registered_bank_min_chordal_distance = ...
    truth_diag.registered_bank_min_chordal_distance;
row.registered_bank_exact_alias_tolerance = ...
    truth_diag.registered_bank_exact_alias_tolerance;
row.registered_bank_candidates_checked = ...
    truth_diag.registered_bank_candidates_checked;
row.registered_bank_rank_deficient_candidates = ...
    truth_diag.registered_bank_rank_deficient_candidates;
row.registered_bank_exact_alias_flag = ...
    truth_diag.registered_bank_exact_alias_flag;
row.truth_recovery_model_relative_residual = ...
    fixture.truth_recovery_model_relative_residual;
row.truth_score_model_relative_residual = ...
    fixture.truth_score_model_relative_residual;
row.truth_dml_rss_relative = truth_rss_relative;
row.estimate_status = string(est.estimate_status);
row.support_status = string(est.support_status);
row.truth_evidence_support_status = string(truth_diag.support_status);
row.statistical_calibration_status = ...
    string(est.statistical_calibration_status);
row.registered_model_certified_flag = ...
    est.registered_model_certified_flag;
row.structural_gate_pass_flag = est.structural_gate_pass_flag;
row.estimate_returned_flag = est.estimate_returned_flag;
row.expected_estimate_status = string(fixture.expected_estimate_status);
row.expected_support_status = string(fixture.expected_support_status);
row.pass_flag = pass_flag;
row.phase_factor = 1;
end

function row = make_recovery_row_local(fixture, q, est, debug, metrics, ...
    subspace_gate, pass_flag)
row = recovery_row_base_local(fixture, est);
row.group_index = q;
row.evaluation_scope = string(metrics.evaluation_scope);
row.relative_fro_error = metrics.relative_fro_error_by_group(q);
row.registered_fro_gate = fixture.recovery_gate;
row.subspace_chordal_distance = ...
    metrics.subspace_chordal_distance_by_group(q);
row.registered_subspace_gate = subspace_gate;
row.subspace_rank_estimate = metrics.subspace_rank_estimate(q);
row.subspace_rank_truth = metrics.subspace_rank_truth(q);
row.max_offdiagonal_crosstalk = metrics.max_offdiagonal_crosstalk;
row.diagonal_mixing_error = metrics.diagonal_mixing_error;
row.rank_Ge = debug.rank_Ge;
row.rank_Ce_hat_diagnostic = debug.rank_Ce_hat_diagnostic;
row.recovery_solve_status = string(debug.solve_status);
row.pass_flag = pass_flag;
end

function row = make_rejection_recovery_row_local(fixture, est, pass_flag)
row = recovery_row_base_local(fixture, est);
row.group_index = 0;
row.evaluation_scope = "TEST_ONLY_TRUTH_EVALUATOR_NOT_RUN";
row.relative_fro_error = NaN;
row.registered_fro_gate = NaN;
row.subspace_chordal_distance = NaN;
row.registered_subspace_gate = NaN;
row.subspace_rank_estimate = NaN;
row.subspace_rank_truth = NaN;
row.max_offdiagonal_crosstalk = NaN;
row.diagonal_mixing_error = NaN;
row.rank_Ge = est.rank_Ge;
row.rank_Ce_hat_diagnostic = est.rank_Ce_hat_diagnostic;
row.recovery_solve_status = "RECOVERY_NOT_RUN_STRUCTURAL_GATE";
row.pass_flag = pass_flag;
end

function row = recovery_row_base_local(fixture, est)
row = struct();
row.scenario = string(fixture.scenario);
row.Nphi = fixture.Nphi;
row.L = fixture.L;
row.observation_regime = string(fixture.observation_regime);
row.coefficient_rank_evidence_kind = ...
    string(est.coefficient_rank_evidence_kind);
row.row_whitening_rank = fixture.data.row_whitening_rank;
row.column_whitening_rank = fixture.data.column_whitening_rank;
row.column_whitening_applied = fixture.data.column_whitening_applied;
row.column_covariance_model = string(fixture.column_covariance_model);
row.truth_on_registered_grid_flag = fixture.truth_on_registered_grid_flag;
row.search_domain_source = string(fixture.search_domain_source);
row.estimate_status = string(est.estimate_status);
row.support_status = string(est.support_status);
row.statistical_calibration_status = ...
    string(est.statistical_calibration_status);
row.registered_model_certified_flag = ...
    est.registered_model_certified_flag;
row.structural_gate_pass_flag = est.structural_gate_pass_flag;
row.estimate_returned_flag = est.estimate_returned_flag;
row.expected_estimate_status = string(fixture.expected_estimate_status);
row.expected_support_status = string(fixture.expected_support_status);
row.phase_factor = 1;
end

function est = beam_peak_baseline_local(fixture)
energy = sum(abs(reshape(fixture.Zel_raw, ...
    size(fixture.Zel_raw, 1), [])) .^ 2, 2);
[score, index] = max(energy);
est = struct();
est.eta_hat_deg = fixture.el_beam_deg(index);
est.score = score;
est.rss = sum(energy) - score;
est.rank_Ge = NaN;
est.rank_Ce_hat_diagnostic = NaN;
est.rank_Z_score_diagnostic = NaN;
est.rank_Z_recovery_diagnostic = NaN;
est.num_score_eval = numel(fixture.el_beam_deg);
est.num_svd = 0;
est.estimate_status = 'ESTIMATE_RETURNED';
est.support_status = 'NOT_APPLICABLE_BASELINE';
est.statistical_calibration_status = 'NOT_CALIBRATED_STAGE4';
est.registered_model_certified_flag = false;
est.structural_gate_pass_flag = false;
est.estimate_returned_flag = true;
est.coefficient_rank_evidence_kind = ...
    fixture.coefficient_rank_evidence_kind;
end

function pass_flag = estimate_pass_local(est, angle_error_deg, fixture)
pass_flag = strcmp(est.estimate_status, fixture.expected_estimate_status) && ...
    strcmp(est.support_status, fixture.expected_support_status) && ...
    strcmp(est.statistical_calibration_status, 'NOT_CALIBRATED_STAGE4');
if strcmp(fixture.expected_estimate_status, ...
        'ESTIMATE_NOT_RUN_STRUCTURAL_RANK_FAILURE')
    pass_flag = pass_flag && ~est.estimate_returned_flag && ...
        ~est.structural_gate_pass_flag && ...
        (est.rank_Ce_hat_diagnostic < fixture.Q || ...
        est.rank_Z_score_diagnostic < fixture.Q || ...
        est.rank_Z_recovery_diagnostic < fixture.Q);
else
    pass_flag = pass_flag && est.estimate_returned_flag && ...
        est.structural_gate_pass_flag && est.rank_Ge == fixture.Q && ...
        est.rank_Ce_hat_diagnostic == fixture.Q && ...
        angle_error_deg <= fixture.angle_gate_deg;
    if strcmp(fixture.observation_regime, 'NOISY_UNCALIBRATED')
        pass_flag = pass_flag && ~est.registered_model_certified_flag;
    else
        pass_flag = pass_flag && est.registered_model_certified_flag;
    end
end
end

function pass_flag = identifiability_pass_local( ...
    fixture, truth_diag, est, truth_rss_relative)
pass_flag = strcmp(truth_diag.support_status, ...
    fixture.expected_support_status) && ...
    strcmp(est.support_status, fixture.expected_support_status) && ...
    ~truth_diag.registered_bank_exact_alias_flag && ...
    fixture.truth_recovery_model_relative_residual < 5e-12 && ...
    fixture.truth_score_model_relative_residual < 5e-12 && ...
    truth_rss_relative < 5e-12 && ...
    strcmp(truth_diag.statistical_calibration_status, ...
    'NOT_CALIBRATED_STAGE4');
if strcmp(fixture.expected_support_status, ...
        'GROUP_MMV_RANK_UNCERTIFIED')
    pass_flag = pass_flag && truth_diag.rank_Ce_evidence < fixture.Q && ...
        fixture.Nphi > fixture.Q && ~truth_diag.structural_gate_pass_flag;
else
    pass_flag = pass_flag && truth_diag.rank_Ge == fixture.Q && ...
        truth_diag.rank_Ce_evidence == fixture.Q && ...
        truth_diag.structural_gate_pass_flag;
end
end

function error_deg = ordered_angle_error_local(estimate_deg, truth_deg)
if numel(estimate_deg) ~= numel(truth_deg) || any(~isfinite(estimate_deg))
    error_deg = NaN;
else
    error_deg = max(abs(sort(estimate_deg(:)) - sort(truth_deg(:))));
end
end

function gate = recovery_subspace_gate_local(noise_kind)
if strcmp(noise_kind, 'none')
    gate = 5e-7;
else
    gate = 0.35;
end
end

function text = vector_text_local(values)
text = string(strtrim(sprintf('%.12g ', values)));
end
