function result_table = test_public_api_has_no_truth_dependency(step_dir)
%TEST_PUBLIC_API_HAS_NO_TRUTH_DEPENDENCY Enforce the public/test boundary.

common_files = dir(fullfile(step_dir, 'common', '**', '*.m'));
combined = '';
for idx = 1:numel(common_files)
    combined = [combined, newline, ...
        fileread(fullfile(common_files(idx).folder, ...
        common_files(idx).name))]; %#ok<AGROW>
end
private_evaluator = fullfile(step_dir, 'tests', 'private', ...
    'evaluate_group_recovery_against_truth.m');

Z = reshape(complex(1:6, 7:12), 2, 3, 1);
[data, ~] = prepare_elevation_group_mmv_data( ...
    Z, eye(2), eye(3), struct( ...
    'observation_regime', 'NOISELESS_STRUCTURAL', ...
    'column_covariance_model', 'identity'));
recovery_rejects_private_field = false;
try
    recover_group_azimuth_data(data, eye(2), ...
        struct('true_Ce', eye(2)));
catch exception
    recovery_rejects_private_field = strcmp(exception.identifier, ...
        'recover_group_azimuth_data:UnknownOption');
end
recovery_rejects_extra_bundle_field = false;
bad_recovery_data = data;
bad_recovery_data.truth = 1;
try
    recover_group_azimuth_data(bad_recovery_data, eye(2), struct());
catch exception
    recovery_rejects_extra_bundle_field = strcmp(exception.identifier, ...
        'recover_group_azimuth_data:UnknownDataField');
end
estimator_rejects_extra_bundle_field = false;
bad_data = data;
bad_data.truth = 1;
model = struct('V', eye(2), 'whitener', eye(2), ...
    'z_el_m', [0; 0.25], 'lambda', 1, 'phase_factor', 1, ...
    'model_id', 'public_api_boundary_test');
try
    estimate_elevation_groups_dml( ...
        bad_data, 1, [0, 10], model, struct());
catch exception
    estimator_rejects_extra_bundle_field = strcmp(exception.identifier, ...
        'estimate_elevation_groups_dml:UnknownDataField');
end

rule = ["common_has_no_true_ce_field"; "common_has_no_true_ge_field"; ...
    "private_truth_evaluator_exists"; ...
    "recovery_rejects_test_only_option"; ...
    "recovery_rejects_extra_bundle_field"; ...
    "estimator_rejects_extra_bundle_field"];
hit_count = [numel(regexp(combined, 'true_Ce', 'match')); ...
    numel(regexp(combined, 'true_Ge', 'match')); ...
    double(exist(private_evaluator, 'file') == 2); ...
    double(recovery_rejects_private_field); ...
    double(recovery_rejects_extra_bundle_field); ...
    double(estimator_rejects_extra_bundle_field)];
pass_flag = [hit_count(1) == 0; hit_count(2) == 0; ...
    hit_count(3) == 1; hit_count(4) == 1; hit_count(5) == 1; ...
    hit_count(6) == 1];
phase_factor = ones(size(hit_count));
result_table = table(rule, hit_count, pass_flag, phase_factor);
assert(all(pass_flag), 'test_public_api_has_no_truth_dependency:Failed', ...
    'The stage-4 public/test truth boundary is not closed.');
end
