function [result_table, context] = test_stage4_status_semantics()
%TEST_STAGE4_STATUS_SEMANTICS Validate independent execution/support states.

Ge = [1, 0; 0, 1; 1, 1];
G_other = [1, 0; 0, 1; 1, -1];
Ce_full = [1, 0, 1; 0, 1, 1];
Ce_rank_one = [1, 2, 3; exp(0.4j) * [1, 2, 3]];
bank = {Ge; G_other};
parameters = [0, 1; 0, 2];

cases = cell(5, 1);
cases{1} = run_diag_local('noiseless_full_rank', Ge, Ce_full, ...
    'TRUTH_STRUCTURAL', 'NOISELESS_STRUCTURAL', 'ESTIMATE_RETURNED', ...
    bank, parameters, [0, 1], 3, 3, 3, ...
    'GROUP_REGISTERED_MODEL_CERTIFIED');
cases{2} = run_diag_local('noisy_full_rank', Ge, Ce_full, ...
    'ESTIMATED_DIAGNOSTIC', 'NOISY_UNCALIBRATED', ...
    'ESTIMATE_RETURNED', bank, parameters, [0, 1], 3, 3, 3, ...
    'GROUP_REGISTERED_MODEL_SUPPORTED_UNCALIBRATED');
cases{3} = run_diag_local('exact_rank_ce_below_q', Ge, Ce_rank_one, ...
    'TRUTH_STRUCTURAL', 'NOISELESS_STRUCTURAL', ...
    'ESTIMATE_NOT_RUN_STRUCTURAL_RANK_FAILURE', bank, parameters, ...
    [0, 1], 3, 3, 3, 'GROUP_MMV_RANK_UNCERTIFIED');
Ge_rank_one = [1, 1; 2, 2; 3, 3];
rank_bank = {Ge_rank_one; G_other};
cases{4} = run_diag_local('rank_ge_below_q', Ge_rank_one, Ce_full, ...
    'TRUTH_STRUCTURAL', 'NOISELESS_STRUCTURAL', ...
    'NO_FULL_RANK_CANDIDATE', rank_bank, parameters, [0, 1], 3, 3, 3, ...
    'GROUP_MANIFOLD_RANK_UNCERTIFIED');
Ge_alias = [1; 2; 3];
cases{5} = run_diag_local('exact_registered_alias', Ge_alias, 1, ...
    'TRUTH_STRUCTURAL', 'NOISELESS_STRUCTURAL', 'ESTIMATE_RETURNED', ...
    {Ge_alias; 2 * Ge_alias}, [0; 1], 0, 3, 3, 3, ...
    'GROUP_REGISTERED_ALIAS_UNCERTIFIED');

result_table = struct2table(vertcat(cases{:}));
assert(all(result_table.pass_flag), 'test_stage4_status_semantics:Failed', ...
    'A stage-4 status-semantics gate failed.');
context = struct('num_svd', sum(result_table.num_svd));
end

function row = run_diag_local(name, Ge, Ce, evidence_kind, regime, ...
    estimate_status, bank, parameters, reference, physical_beams, ...
    row_rank, column_rank, expected_support)
opts = struct('evidence_kind', evidence_kind, ...
    'row_whitening_rank', row_rank, ...
    'column_whitening_rank', column_rank, ...
    'physical_beam_count', physical_beams, ...
    'observation_regime', regime, 'estimate_status', estimate_status, ...
    'local_manifold_bank', {bank}, 'local_parameter_deg', parameters, ...
    'reference_parameter_deg', reference, 'rank_multiplier', 1);
diag_out = diagnose_elevation_group_identifiability(Ge, Ce, opts);
expected_certified = strcmp(expected_support, ...
    'GROUP_REGISTERED_MODEL_CERTIFIED');
expected_gate = ismember(expected_support, ...
    {'GROUP_REGISTERED_MODEL_CERTIFIED', ...
    'GROUP_REGISTERED_MODEL_SUPPORTED_UNCALIBRATED'});
expected_returned = strcmp(estimate_status, 'ESTIMATE_RETURNED');
old_field_absent = ~isfield(diag_out, ...
    'high_confidence_group_flag');
pass_flag = strcmp(diag_out.support_status, expected_support) && ...
    strcmp(diag_out.statistical_calibration_status, ...
    'NOT_CALIBRATED_STAGE4') && ...
    diag_out.registered_model_certified_flag == expected_certified && ...
    diag_out.structural_gate_pass_flag == expected_gate && ...
    diag_out.estimate_returned_flag == expected_returned && old_field_absent;

row = struct();
row.case_name = string(name);
row.estimate_status = string(diag_out.estimate_status);
row.support_status = string(diag_out.support_status);
row.statistical_calibration_status = ...
    string(diag_out.statistical_calibration_status);
row.registered_model_certified_flag = ...
    diag_out.registered_model_certified_flag;
row.structural_gate_pass_flag = diag_out.structural_gate_pass_flag;
row.estimate_returned_flag = diag_out.estimate_returned_flag;
row.observation_regime = string(diag_out.observation_regime);
row.coefficient_rank_evidence_kind = ...
    string(diag_out.coefficient_rank_evidence_kind);
row.row_whitening_rank = diag_out.row_whitening_rank;
row.column_whitening_rank = diag_out.column_whitening_rank;
row.column_whitening_applied = false;
row.column_covariance_model = "identity";
row.truth_on_registered_grid_flag = true;
row.search_domain_source = "registered_status_unit_test_bank";
row.rank_Ge = diag_out.rank_Ge;
row.rank_Ce_hat_diagnostic = diag_out.rank_Ce_evidence;
row.rank_Z_score_diagnostic = NaN;
row.rank_Z_recovery_diagnostic = NaN;
row.registered_bank_exact_alias_flag = ...
    diag_out.registered_bank_exact_alias_flag;
row.old_confidence_field_absent_flag = old_field_absent;
row.num_svd = diag_out.num_svd;
row.pass_flag = pass_flag;
row.phase_factor = 1;
end
