function plan = build_stage5_scenario_plan(cfg)
%BUILD_STAGE5_SCENARIO_PLAN Freeze design, validation, and holdout cases.

full_aperture = 1:cfg.beam.subNaz;
center = (cfg.beam.subNaz + 1) / 2;
reduced_aperture = (center - 8):(center + 8);
independent = source_pair_local(4, 0.8, false);
coherent = source_pair_local(4, 0.8, true);

plan = make_spec_local('design_grid_q1_k2_l4', 'DESIGN', ...
    [7.6, 10.0; 8.4, 10.0], independent, [1; 1], ...
    'none', 0, 126001, full_aperture, 1, ...
    'grid_aligned,same_elevation,K2,L_gt_1');
plan(end + 1) = make_spec_local('design_grid_q2_k1_k1_l4', 'DESIGN', ...
    [7.6, 9.8; 8.4, 10.2], independent, [1; 2], ...
    'none', 0, 126002, full_aperture, 1, ...
    'grid_aligned,Q2,K1_plus_K1,L_gt_1');
plan(end + 1) = make_spec_local('validation_azimuth_half_grid', 'VALIDATION', ...
    [7.7, 10.0; 8.3, 10.0], independent, [1; 1], ...
    'white', 0.003, 126003, full_aperture, 1, ...
    'azimuth_offgrid_half_step,same_elevation');
plan(end + 1) = make_spec_local('validation_elevation_half_grid', 'VALIDATION', ...
    [7.6, 9.9; 8.4, 10.1], independent, [1; 2], ...
    'white', 0.003, 126004, full_aperture, 1, ...
    'elevation_offgrid_half_step,Q2');
plan(end + 1) = make_spec_local('validation_both_half_grid', 'VALIDATION', ...
    [7.7, 9.9; 8.3, 10.1], independent, [1; 2], ...
    'white', 0.003, 126005, full_aperture, 1, ...
    'azimuth_and_elevation_offgrid_half_step,Q2');
plan(end + 1) = make_spec_local('validation_fixed_center_bias', 'VALIDATION', ...
    [7.5, 10.0; 8.1, 10.0], independent, [1; 1], ...
    'white', 0.003, 126006, full_aperture, 1, ...
    'fixed_conventional_center_bias,same_elevation');
plan(end + 1) = make_spec_local('normal_core_offgrid_white_l4', ...
    'NORMAL_HOLDOUT', [7.7, 10.1; 8.3, 10.1], independent, [1; 1], ...
    'white', 0.004, 126100, full_aperture, 200, ...
    'core_noisy,paired_noise,both_offgrid,L_gt_1');
plan(end + 1) = make_spec_local('normal_q2_white_l4', ...
    'NORMAL_HOLDOUT', [7.6, 9.8; 8.4, 10.2], independent, [1; 2], ...
    'white', 0.004, 126400, full_aperture, 5, ...
    'Q2,K1_plus_K1,paired_noise,L_gt_1');
plan(end + 1) = make_spec_local('stress_domain_boundary', ...
    'STRESS_HOLDOUT', [7.4, 10.0; 8.6, 10.0], independent, [1; 1], ...
    'white', 0.004, 126500, full_aperture, 5, ...
    'domain_boundary,same_elevation');
plan(end + 1) = make_spec_local('stress_partial_out_of_domain', ...
    'STRESS_HOLDOUT', [7.2, 10.0; 8.4, 10.0], independent, [1; 1], ...
    'white', 0.004, 126600, full_aperture, 5, ...
    'partial_out_of_registered_domain,unconditional_failure');
plan(end + 1) = make_spec_local('stress_extremely_close_elevation_white', ...
    'STRESS_HOLDOUT', [7.6, 9.95; 8.4, 10.05], independent, [1; 2], ...
    'white', 0.004, 126700, full_aperture, 5, ...
    'extremely_close_elevation,white_noise,Q2');
plan(end + 1) = make_spec_local('stress_two_dimensional_close', ...
    'STRESS_HOLDOUT', [7.9, 9.9; 8.1, 10.1], independent, [1; 2], ...
    'white', 0.004, 126800, full_aperture, 5, ...
    'two_dimensional_close,Q2,both_offgrid');
plan(end + 1) = make_spec_local('stress_weak_secondary_same_elevation', ...
    'STRESS_HOLDOUT', [7.6, 10.0; 8.4, 10.0], ...
    source_pair_local(4, 0.05, false), [1; 1], ...
    'white', 0.004, 126900, full_aperture, 5, ...
    'weak_secondary,same_elevation');
plan(end + 1) = make_spec_local('stress_coherent_same_elevation', ...
    'STRESS_HOLDOUT', [7.6, 10.0; 8.4, 10.0], coherent, [1; 1], ...
    'white', 0.004, 127000, full_aperture, 5, ...
    'coherent_waveform,same_elevation');
plan(end + 1) = make_spec_local('stress_proportional_group_coefficients', ...
    'STRESS_HOLDOUT', [7.6, 9.8; 8.4, 10.2], coherent, [1; 2], ...
    'white', 0.004, 127100, full_aperture, 5, ...
    'coherent_waveform,near_proportional_group_coefficients,Q2');
plan(end + 1) = make_spec_local('stress_core_coherent_weak_l4', ...
    'STRESS_HOLDOUT', [7.7, 10.0; 8.3, 10.0], ...
    source_pair_local(4, 0.12, true), [1; 1], ...
    'white', 0.004, 127200, full_aperture, 200, ...
    'core_noisy,paired_noise,coherent_and_weak,same_elevation');
plan(end + 1) = make_spec_local('stress_correlated_rz_rphi', ...
    'STRESS_HOLDOUT', [7.6, 10.0; 8.4, 10.0], independent, [1; 1], ...
    'correlated', 0.003, 127500, full_aperture, 5, ...
    'correlated_Rz_Rphi,same_elevation');
plan(end + 1) = make_spec_local('stress_reduced_circumferential_aperture', ...
    'STRESS_HOLDOUT', [7.6, 10.0; 8.4, 10.0], independent, [1; 1], ...
    'white', 0.004, 127600, reduced_aperture, 5, ...
    'reduced_circumferential_aperture,same_elevation');
plan(end + 1) = make_spec_local('stress_single_snapshot_l1', ...
    'STRESS_HOLDOUT', [7.6, 10.0; 8.4, 10.0], ...
    source_pair_local(1, 0.8, false), [1; 1], ...
    'white', 0.004, 127700, full_aperture, 5, ...
    'L_equals_1,same_elevation');
end

function S = source_pair_local(L, ratio, coherent)
base = [1, exp(0.2j), 0.9 * exp(-0.4j), 1.1 * exp(0.6j)];
base = base(1:L);
if coherent
    second = ratio * exp(0.4j) * base;
else
    alternative = [exp(0.4j), 0.8 * exp(-0.2j), ...
        1.05 * exp(0.7j), 0.75 * exp(-0.8j)];
    second = ratio * alternative(1:L);
end
S = [base; second];
end

function spec = make_spec_local(name, split, angles, sources, groups, ...
    noise_kind, noise_sigma, seed, aperture, nmc, feature_tags)
spec = struct('name', name, 'data_split', split, ...
    'target_angles_deg', angles, 'source_snapshots', sources, ...
    'group_index', groups, 'noise_kind', noise_kind, ...
    'noise_sigma', noise_sigma, 'seed', seed, ...
    'aperture_index', aperture, 'nmc', nmc, ...
    'feature_tags', feature_tags);
end
