function constants = stage8_k2_sb_constants()
%STAGE8_K2_SB_CONSTANTS Frozen structured-subspace comparison contract.

constants = struct( ...
    'protocol', 'STAGE8_K2_SUBSPACE_BASELINE_COMPARISON_V1', ...
    'authorization', ...
    'AUTHORIZE_STAGE8_K2_SUBSPACE_BASELINE_COMPARISON_AND_FF_INTEGRATION_V1', ...
    'branch', 'work/stage8-k2-subspace-baselines-v1', ...
    'base_commit', '1705b160c08313d2ade9fc701085e8ce4bed4f7c', ...
    'expected_origin_main', ...
    '247fad2208e77b04f7062e22b0fd3fd8a81bfc1f', ...
    'actual_origin_research_at_start', ...
    'a7139204d717923cb89d0d629b67f1b3ab7ae94d', ...
    'primary_measurement_config_id', 'PRIMARY_RECT_E14_A31', ...
    'noise_profile_ids', ...
    ["WHITE"; "STAGE5_TOEPLITZ_CORRELATED"], ...
    'snapshot_counts', [1, 4, 8], ...
    'snr_db_values', [-6, 0, 6], ...
    'profile_ids', ["P1"; "P2"; "P3"; "P4"], ...
    'trial_count', 72, 'new_method_row_count', 216, ...
    'method_ids', ...
    ["ELEMENT_VERTICAL_GFBSS_MUSIC_AZ_CML"; ...
    "ELEMENT_VERTICAL_FBSS_ROOT_MUSIC_AZ_CML"; ...
    "ELEMENT_VERTICAL_FBSS_LS_ESPRIT_AZ_CML"], ...
    'reference_method_ids', ...
    ["TANGENT_PROFILE_SAFE"; ...
    "FULL4D_BEAMSPACE_CML_MULTISTART"; ...
    "FULL4D_ELEMENT_CML_MULTISTART"; ...
    "BEAMSPACE_MUSIC_K2"; "ELEMENT_MUSIC_K2"], ...
    'N_el', 32, 'N_az', 65, 'K', 2, ...
    'smoothing_length', 31, 'smoothing_subarray_count', 2, ...
    'elevation_grid_deg', 9.8:0.001:10.2, ...
    'elevation_domain_deg', [9.8, 10.2], ...
    'elevation_distinct_tolerance_deg', 1e-6, ...
    'azimuth_grid_deg', 7.4:0.02:8.6, ...
    'azimuth_domain_deg', [7.4, 8.6], ...
    'top_start_count', 4, 'max_sweeps', 8, ...
    'scan_nodes_per_coordinate', 9, ...
    'fminbnd_TolX_deg', 1e-4, 'fminbnd_MaxFunEvals', 80, ...
    'relative_score_tolerance', 1e-8, ...
    'coordinate_update_tolerance_deg', 1e-4, ...
    'rank_multiplier', 1, 'paired_tie_tolerance_deg', 1e-6, ...
    'zero_separation_tolerance_deg', 1e-12, ...
    'root_unit_circle_tolerance', 1e-7, ...
    'root_duplicate_tolerance_deg', 1e-5, ...
    'factorization_tolerance', 1e-10, ...
    'structure_tolerance', 1e-12, ...
    'runtime_root', ...
    'E:\bs_innovation_runtime\stage8_k2_subspace_baselines_v1');
end
