function output = stage8_k2_sb_run(repo_dir, runtime_root)
%STAGE8_K2_SB_RUN Run smoke then the formal 72-trial comparison once.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_sb_run:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
if nargin < 2 || isempty(runtime_root)
    runtime_root = stage8_k2_sb_constants().runtime_root;
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
runtime_root = char(java.io.File(char(string(runtime_root))).getCanonicalPath());
if isfolder(runtime_root) || isfile(runtime_root)
    error('stage8_k2_sb_run:RuntimeExists', ...
        ['Runtime root already exists. Remove only this exact uncommitted ', ...
        'runtime before restarting from the beginning.']);
end
if ~mkdir(runtime_root)
    error('stage8_k2_sb_run:RuntimeCreate', ...
        'Unable to create the isolated runtime root.');
end

scope = stage8_k2_sb_add_paths(repo_dir); %#ok<NASGU>
context = stage8_k2_sb_build_context(repo_dir);
resources = stage8_k2_sb_prepare_resources(context);
registry = context.registry;
constants = context.constants;

smoke_selectors = { ...
    "P1", 8, 6, "WHITE"; ...
    "P3", 8, 6, "WHITE"; ...
    "P4", 8, 6, "WHITE"; ...
    "P3", 8, 6, "STAGE5_TOEPLITZ_CORRELATED"};
smoke_rows_cell = cell(size(smoke_selectors, 1), 1);
smoke_diagnostics_cell = cell(size(smoke_selectors, 1), 1);
smoke_conditional_execution_count = 0;
fprintf('Running four registered smoke trials...\n');
for index = 1:size(smoke_selectors, 1)
    selected = registry.profile_id == smoke_selectors{index, 1} & ...
        registry.L == smoke_selectors{index, 2} & ...
        registry.snr_db == smoke_selectors{index, 3} & ...
        registry.noise_profile_id == smoke_selectors{index, 4};
    spec = registry(selected, :);
    if height(spec) ~= 1
        error('stage8_k2_sb_run:SmokeSelector', ...
            'A smoke selector did not resolve to exactly one trial.');
    end
    trial = stage8_k2_cb_generate_trial(spec, context.cb_context);
    [smoke_rows_cell{index}, smoke_diagnostics_cell{index}] = ...
        stage8_k2_sb_evaluate_trial(spec, trial, context, resources, ...
        "SMOKE");
    rows_now = smoke_rows_cell{index};
    diagnostics_now = smoke_diagnostics_cell{index};
    valid_rows = rows_now.fit_valid;
    elevation_valid = diagnostics_now.applicable & ...
        diagnostics_now.elevation_fit_valid;
    conditional_executed = elevation_valid & ...
        diagnostics_now.conditional_az_cml_status ~= ...
        "NOT_RUN_ELEVATION_INVALID";
    smoke_conditional_execution_count = ...
        smoke_conditional_execution_count + nnz(conditional_executed);
    if ~trial.element_hash_match_flag || ...
            any(rows_now.applicable & rows_now.fit_status == "NOT_RUN") || ...
            any(valid_rows & (~isfinite(rows_now.loglik) | ...
            ~isfinite(rows_now.joint_RMSE_deg))) || ...
            any(rows_now.truth_used_in_fit_flag) || ...
            any(rows_now.profile_used_in_fit_flag) || ...
            any(rows_now.tangent_used_in_start_flag) || ...
            any(rows_now.core_used_in_start_flag) || ...
            any(elevation_valid & ~conditional_executed)
        error('stage8_k2_sb_run:SmokeFailure', ...
            'A smoke trial failed its non-performance execution contract.');
    end
    fprintf('Smoke %d/4 PASS: %s\n', index, char(spec.trial_id));
end
if smoke_conditional_execution_count == 0
    error('stage8_k2_sb_run:SmokeConditionalCML', ...
        'No smoke elevation estimate reached the conditional CML backend.');
end
smoke_rows = vertcat(smoke_rows_cell{:});
smoke_diagnostics = vertcat(smoke_diagnostics_cell{:});
writetable(smoke_rows, fullfile(runtime_root, 'smoke_rows.csv'));
writetable(smoke_diagnostics, ...
    fullfile(runtime_root, 'smoke_elevation_diagnostics.csv'));

fprintf('Reconstructing all 72 formal trials before fitting...\n');
trials = cell(constants.trial_count, 1);
reconstruction = cell(constants.trial_count, 1);
for index = 1:height(registry)
    trials{index} = stage8_k2_cb_generate_trial( ...
        registry(index, :), context.cb_context);
    reconstruction{index} = struct( ...
        'trial_id', registry.trial_id(index), ...
        'element_trial_hash', trials{index}.element_trial_hash, ...
        'expected_element_trial_hash', ...
        context.cb_context.frozen_trial_identity.element_trial_hash(index), ...
        'hash_match_flag', trials{index}.element_hash_match_flag);
end
reconstruction_table = struct2table(vertcat(reconstruction{:}));
if height(reconstruction_table) ~= constants.trial_count || ...
        ~all(reconstruction_table.hash_match_flag)
    error('stage8_k2_sb_run:Reconstruction', ...
        'Formal execution requires 72/72 exact element hashes.');
end
writetable(reconstruction_table, ...
    fullfile(runtime_root, 'trial_reconstruction.csv'));
fprintf('Trial reconstruction PASS: 72/72 exact hashes.\n');

row_tables = cell(constants.trial_count, 1);
diagnostic_tables = cell(constants.trial_count, 1);
for index = 1:height(registry)
    [row_tables{index}, diagnostic_tables{index}] = ...
        stage8_k2_sb_evaluate_trial(registry(index, :), trials{index}, ...
        context, resources, "FORMAL");
    fprintf('Formal subspace %d/72 complete: %s\n', ...
        index, char(registry.trial_id(index)));
end
new_rows = vertcat(row_tables{:});
elevation_diagnostics = vertcat(diagnostic_tables{:});
writetable(new_rows, fullfile(runtime_root, 'new_method_rows.csv'));
writetable(elevation_diagnostics, ...
    fullfile(runtime_root, 'formal_elevation_diagnostics.csv'));
output = stage8_k2_sb_summarize(new_rows, elevation_diagnostics, ...
    context, resources, runtime_root);
output.smoke_rows = smoke_rows;
output.smoke_diagnostics = smoke_diagnostics;
output.reconstruction = reconstruction_table;
fprintf('STAGE8_K2_SUBSPACE_BASELINE_COMPARISON_RUNTIME_COMPLETE\n');
end
