function output = stage8_k2_sb_run_tests(repo_dir)
%STAGE8_K2_SB_RUN_TESTS Run the ten registered theory/implementation tests.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_sb_run_tests:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
scope = stage8_k2_sb_add_paths(repo_dir); %#ok<NASGU>
context = stage8_k2_sb_build_context(repo_dir);
resources = stage8_k2_sb_prepare_resources(context);
tests = { ...
    @() test_cylinder_kronecker_factorization(context), ...
    @() test_vertical_shift_invariance(context), ...
    @() test_noise_kronecker_az_whitening(context), ...
    @() test_fbss_coherent_rank_restoration(context), ...
    @() test_gfbss_music_fixture(context), ...
    @() test_root_music_fixture(context), ...
    @() test_esprit_fixture(context), ...
    @() test_conditional_az_cml_fixture(context, resources), ...
    @() test_applicability_contract(context), ...
    @() test_trial_reconstruction_hash(context)};
names = ["T1_CYLINDER_KRONECKER"; "T2_VERTICAL_SHIFT"; ...
    "T3_NOISE_KRONECKER_AZ_WHITENING"; "T4_FBSS_RANK"; ...
    "T5_GFBSS_MUSIC"; "T6_ROOT_MUSIC"; "T7_ESPRIT"; ...
    "T8_CONDITIONAL_AZ_CML"; "T9_APPLICABILITY"; ...
    "T10_TRIAL_HASH"];
results = cell(numel(tests), 1);
for index = 1:numel(tests)
    results{index} = tests{index}();
    if ~isstruct(results{index}) || ~isfield(results{index}, 'pass') || ...
            ~results{index}.pass
        error('stage8_k2_sb_run_tests:Failure', ...
            'Registered test failed: %s', names(index));
    end
    fprintf('%s PASS\n', names(index));
end
output = struct('pass', true, 'test_count', numel(tests), ...
    'test_names', names, 'results', {results}, ...
    'context_hash', context.context_hash);
fprintf('STAGE8_K2_SUBSPACE_BASELINE_TESTS_PASS 10/10\n');
end
