function output = stage8_k2_sb_summarize( ...
    new_rows, elevation_diagnostics, context, resources, runtime_root)
%STAGE8_K2_SB_SUMMARIZE Validate and write all registered evidence tables.

constants = context.constants;
integrity = validate_new_rows_local(new_rows, elevation_diagnostics, context);
references = stage8_k2_sb_frozen_reference_rows(context, new_rows);
rows = [references; new_rows];
rows = sortrows(rows, {'global_trial_index','method_id'});
summary = summary_local(rows, constants);
profile_summary = profile_summary_local(rows, constants);
applicability = applicability_local(rows, constants);
complexity = complexity_local(rows);
structure = stage8_k2_sb_structure_diagnostics(context);

runtime_paths = evidence_paths_local(runtime_root);
repo_paths = evidence_paths_local(fullfile(context.repo_dir, ...
    'innovation-mining'));
write_tables_local(rows, summary, profile_summary, applicability, ...
    complexity, elevation_diagnostics, runtime_paths);
write_tables_local(rows, summary, profile_summary, applicability, ...
    complexity, elevation_diagnostics, repo_paths);
write_report_local(runtime_paths.report, rows, summary, profile_summary, ...
    elevation_diagnostics, integrity, structure, resources, constants, ...
    runtime_root);
write_report_local(repo_paths.report, rows, summary, profile_summary, ...
    elevation_diagnostics, integrity, structure, resources, constants, ...
    runtime_root);
output = struct('rows', rows, 'new_rows', new_rows, ...
    'references', references, 'summary', summary, ...
    'profile_summary', profile_summary, ...
    'applicability', applicability, 'complexity', complexity, ...
    'elevation_diagnostics', elevation_diagnostics, ...
    'integrity', integrity, 'structure', structure, ...
    'runtime_paths', runtime_paths, 'repo_paths', repo_paths);
end

function integrity = validate_new_rows_local(rows, diagnostics, context)
constants = context.constants;
counts_ok = height(rows) == constants.new_method_row_count && ...
    height(diagnostics) == constants.new_method_row_count;
for index = 1:numel(constants.method_ids)
    counts_ok = counts_ok && ...
        nnz(rows.method_id == constants.method_ids(index)) == ...
        constants.trial_count;
end
hash_ok = all(rows.element_hash_match_flag) && ...
    numel(unique(rows.trial_id)) == constants.trial_count;
for index = 1:height(context.registry)
    selected = rows.trial_id == context.registry.trial_id(index);
    expected = context.cb_context.frozen_trial_identity.element_trial_hash(index);
    hash_ok = hash_ok && nnz(selected) == numel(constants.method_ids) && ...
        all(rows.element_trial_hash(selected) == expected);
end
truth_ok = ~any(rows.truth_used_in_fit_flag) && ...
    ~any(rows.profile_used_in_fit_flag) && ...
    ~any(rows.tangent_used_in_start_flag) && ...
    ~any(rows.core_used_in_start_flag) && ...
    ~any(diagnostics.truth_used_in_fit_flag) && ...
    ~any(diagnostics.profile_used_in_fit_flag);
expected_applicable = [54, 27, 27];
applicability_ok = true;
outcomes_ok = true;
for index = 1:numel(constants.method_ids)
    subset = rows(rows.method_id == constants.method_ids(index), :);
    applicability_ok = applicability_ok && ...
        nnz(subset.applicable) == expected_applicable(index);
    outcomes_ok = outcomes_ok && ...
        all(subset.fit_status(subset.applicable) ~= "NOT_RUN") && ...
        all(~subset.fit_valid(~subset.applicable)) && ...
        all(subset.applicability_status(subset.applicable) == "APPLICABLE") && ...
        all(subset.applicability_status(~subset.applicable) ~= "APPLICABLE");
end
p2 = rows.profile_id == "P2";
applicability_ok = applicability_ok && all(~rows.applicable(p2)) && ...
    all(rows.applicability_status(p2) == ...
    "NOT_APPLICABLE_EQUAL_ELEVATION_MULTIPLICITY");
root_colored = rows.method_id == ...
    "ELEMENT_VERTICAL_FBSS_ROOT_MUSIC_AZ_CML" & ...
    rows.noise_profile_id ~= "WHITE" & ~p2;
esprit_colored = rows.method_id == ...
    "ELEMENT_VERTICAL_FBSS_LS_ESPRIT_AZ_CML" & ...
    rows.noise_profile_id ~= "WHITE" & ~p2;
applicability_ok = applicability_ok && all(~rows.applicable(root_colored)) && ...
    all(rows.applicability_status(root_colored) == ...
    "NOT_APPLICABLE_COLORED_NOISE_STANDARD_ROOT_MUSIC") && ...
    all(~rows.applicable(esprit_colored)) && ...
    all(rows.applicability_status(esprit_colored) == ...
    "NOT_APPLICABLE_COLORED_NOISE_STANDARD_ESPRIT");
integrity = struct('counts_ok', counts_ok, 'element_hashes_ok', hash_ok, ...
    'truth_isolation_ok', truth_ok, ...
    'applicability_contract_ok', applicability_ok, ...
    'explicit_outcomes_ok', outcomes_ok, ...
    'experiment_integrity_ok', counts_ok && hash_ok && truth_ok && ...
    applicability_ok && outcomes_ok);
if ~integrity.experiment_integrity_ok
    error('stage8_k2_sb_summarize:Integrity', ...
        'Formal subspace comparison failed a protocol integrity contract.');
end
end

function summary = summary_local(rows, constants)
items = repmat(summary_template_local(), 0, 1);
all_methods = [constants.reference_method_ids; constants.method_ids];
for index = 1:numel(all_methods)
    subset = rows(rows.method_id == all_methods(index), :);
    item = metric_item_local(subset);
    item.row_type = "METHOD";
    item.method_id = all_methods(index);
    items(end + 1, 1) = item; %#ok<AGROW>
end
for new_index = 1:numel(constants.method_ids)
    for reference_index = 1:numel(constants.reference_method_ids)
        items(end + 1, 1) = pair_item_local(rows, ...
            constants.method_ids(new_index), ...
            constants.reference_method_ids(reference_index), ...
            constants); %#ok<AGROW>
    end
end
for first = 1:numel(constants.method_ids)-1
    for second = first+1:numel(constants.method_ids)
        items(end + 1, 1) = pair_item_local(rows, ...
            constants.method_ids(first), constants.method_ids(second), ...
            constants); %#ok<AGROW>
    end
end
summary = struct2table(items);
end

function item = metric_item_local(subset)
item = summary_template_local();
valid = subset(subset.applicable & subset.fit_valid, :);
item.total_row_count = height(subset);
item.applicable_count = nnz(subset.applicable);
item.valid_count = height(valid);
item.applicable_but_invalid_count = ...
    nnz(subset.applicable & ~subset.fit_valid);
metrics = {'joint_RMSE_deg','azimuth_RMSE_deg','elevation_RMSE_deg', ...
    'center_error_deg','axis_error_deg','separation_error_deg', ...
    'separation_vector_error_deg','runtime_sec'};
for index = 1:numel(metrics)
    name = metrics{index};
    item.(['median_', name]) = median_local(valid.(name));
    item.(['p90_', name]) = percentile_local(valid.(name), 90);
end
item.mean_score_calls = mean_local(subset.score_call_count(subset.applicable));
item.mean_svd_calls = mean_local(subset.svd_call_count(subset.applicable));
item.mean_eig_calls = mean_local(subset.eig_call_count(subset.applicable));
end

function item = pair_item_local(rows, left_id, right_id, constants)
item = summary_template_local();
item.row_type = "PAIRED";
item.method_id = left_id;
item.reference_method_id = right_id;
item.comparison_id = left_id + "_vs_" + right_id;
left = rows(rows.method_id == left_id, :);
right = rows(rows.method_id == right_id, :);
[~, left_index, right_index] = intersect( ...
    left.trial_id, right.trial_id, 'stable');
selected = left.applicable(left_index) & left.fit_valid(left_index) & ...
    right.applicable(right_index) & right.fit_valid(right_index);
left_index = left_index(selected);
right_index = right_index(selected);
delta = left.joint_RMSE_deg(left_index) - ...
    right.joint_RMSE_deg(right_index);
item.paired_count = numel(delta);
item.wins = nnz(delta < -constants.paired_tie_tolerance_deg);
item.ties = nnz(abs(delta) <= constants.paired_tie_tolerance_deg);
item.losses = nnz(delta > constants.paired_tie_tolerance_deg);
end

function item = summary_template_local()
item = struct('row_type', "", 'comparison_id', "", ...
    'method_id', "", 'reference_method_id', "", ...
    'total_row_count', 0, 'applicable_count', 0, 'valid_count', 0, ...
    'applicable_but_invalid_count', 0, ...
    'median_joint_RMSE_deg', NaN, 'p90_joint_RMSE_deg', NaN, ...
    'median_azimuth_RMSE_deg', NaN, 'p90_azimuth_RMSE_deg', NaN, ...
    'median_elevation_RMSE_deg', NaN, 'p90_elevation_RMSE_deg', NaN, ...
    'median_center_error_deg', NaN, 'p90_center_error_deg', NaN, ...
    'median_axis_error_deg', NaN, 'p90_axis_error_deg', NaN, ...
    'median_separation_error_deg', NaN, ...
    'p90_separation_error_deg', NaN, ...
    'median_separation_vector_error_deg', NaN, ...
    'p90_separation_vector_error_deg', NaN, ...
    'median_runtime_sec', NaN, 'p90_runtime_sec', NaN, ...
    'mean_score_calls', NaN, 'mean_svd_calls', NaN, ...
    'mean_eig_calls', NaN, 'paired_count', 0, ...
    'wins', 0, 'ties', 0, 'losses', 0);
end

function output = profile_summary_local(rows, constants)
items = repmat(profile_template_local(), 0, 1);
methods = [constants.reference_method_ids; constants.method_ids];
definitions = ["PROFILE", "P1"; "PROFILE", "P2"; ...
    "PROFILE", "P3"; "PROFILE", "P4"; ...
    "L", "1"; "L", "4"; "L", "8"; ...
    "SNR_DB", "-6"; "SNR_DB", "0"; "SNR_DB", "6"; ...
    "NOISE", "WHITE"; "NOISE", "STAGE5_TOEPLITZ_CORRELATED"];
for method_index = 1:numel(methods)
    method_rows = rows(rows.method_id == methods(method_index), :);
    for definition_index = 1:size(definitions, 1)
        scope_type = definitions(definition_index, 1);
        scope_value = definitions(definition_index, 2);
        if scope_type == "PROFILE"
            selected = method_rows.profile_id == scope_value;
        elseif scope_type == "L"
            selected = method_rows.L == str2double(scope_value);
        elseif scope_type == "SNR_DB"
            selected = method_rows.snr_db == str2double(scope_value);
        else
            selected = method_rows.noise_profile_id == scope_value;
        end
        metric = metric_item_local(method_rows(selected, :));
        item = profile_template_local();
        item.method_id = methods(method_index);
        item.scope_type = scope_type;
        item.scope_value = scope_value;
        copy_names = setdiff(fieldnames(item), ...
            {'method_id','scope_type','scope_value'});
        for name_index = 1:numel(copy_names)
            item.(copy_names{name_index}) = metric.(copy_names{name_index});
        end
        items(end + 1, 1) = item; %#ok<AGROW>
    end
end
output = struct2table(items);
end

function item = profile_template_local()
metric = summary_template_local();
remove = {'row_type','comparison_id','method_id','reference_method_id', ...
    'paired_count','wins','ties','losses'};
metric = rmfield(metric, remove);
item = struct('method_id', "", 'scope_type', "", 'scope_value', "");
names = fieldnames(metric);
for index = 1:numel(names)
    item.(names{index}) = metric.(names{index});
end
end

function output = applicability_local(rows, constants)
items = cell(0, 1);
methods = [constants.reference_method_ids; constants.method_ids];
for method_index = 1:numel(methods)
    method_rows = rows(rows.method_id == methods(method_index), :);
    scopes = {"ALL", "ALL", true(height(method_rows), 1)};
    for profile = constants.profile_ids.'
        scopes(end + 1, :) = {"PROFILE", profile, ...
            method_rows.profile_id == profile}; %#ok<AGROW>
    end
    for noise = constants.noise_profile_ids.'
        scopes(end + 1, :) = {"NOISE", noise, ...
            method_rows.noise_profile_id == noise}; %#ok<AGROW>
    end
    for scope_index = 1:size(scopes, 1)
        subset = method_rows(scopes{scope_index, 3}, :);
        statuses = unique(subset.applicability_status, 'stable');
        if isempty(statuses)
            statuses = "NO_REGISTERED_ROWS";
        end
        for status_index = 1:numel(statuses)
            status = statuses(status_index);
            if status == "NO_REGISTERED_ROWS"
                status_rows = subset;
            else
                status_rows = subset(subset.applicability_status == status, :);
            end
            items{end + 1, 1} = struct('method_id', methods(method_index), ...
                'scope_type', string(scopes{scope_index, 1}), ...
                'scope_value', string(scopes{scope_index, 2}), ...
                'applicability_status', status, ...
                'row_count', height(status_rows), ...
                'applicable_count', nnz(status_rows.applicable), ...
                'valid_count', nnz(status_rows.fit_valid)); %#ok<AGROW>
        end
    end
end
output = struct2table(vertcat(items{:}));
end

function output = complexity_local(rows)
methods = unique(rows.method_id, 'stable');
items = cell(numel(methods), 1);
for index = 1:numel(methods)
    subset = rows(rows.method_id == methods(index) & rows.applicable, :);
    items{index} = struct('method_id', methods(index), ...
        'applicable_count', height(subset), ...
        'valid_count', nnz(subset.fit_valid), ...
        'mean_score_calls', mean_local(subset.score_call_count), ...
        'mean_svd_calls', mean_local(subset.svd_call_count), ...
        'mean_eig_calls', mean_local(subset.eig_call_count), ...
        'mean_coarse_candidates', ...
        mean_local(subset.coarse_candidate_count), ...
        'mean_continuous_starts', ...
        mean_local(subset.continuous_start_count), ...
        'median_runtime_sec', median_local(subset.runtime_sec), ...
        'p90_runtime_sec', percentile_local(subset.runtime_sec, 90));
end
output = struct2table(vertcat(items{:}));
end

function paths = evidence_paths_local(directory)
prefix = fullfile(directory, '40_stage8_k2_subspace_baseline_');
paths = struct('report', [prefix, 'comparison.md'], ...
    'trials', [prefix, 'trials.csv'], ...
    'summary', [prefix, 'summary.csv'], ...
    'profile_summary', [prefix, 'profile_summary.csv'], ...
    'applicability', [prefix, 'applicability.csv'], ...
    'complexity', [prefix, 'complexity.csv'], ...
    'elevation_diagnostics', [prefix, 'elevation_diagnostics.csv']);
end

function write_tables_local(rows, summary, profile_summary, ...
    applicability, complexity, diagnostics, paths)
writetable(rows, paths.trials);
writetable(summary, paths.summary);
writetable(profile_summary, paths.profile_summary);
writetable(applicability, paths.applicability);
writetable(complexity, paths.complexity);
writetable(diagnostics, paths.elevation_diagnostics);
end

function write_report_local(path_now, rows, summary, profile_summary, ...
    diagnostics, integrity, structure, resources, constants, runtime_root)
[status, head] = system('git rev-parse HEAD');
if status ~= 0, head = 'UNKNOWN'; else, head = strtrim(head); end
fid = fopen(path_now, 'w');
if fid < 0
    error('stage8_k2_sb_summarize:ReportOpen', ...
        'Unable to create the comparison report.');
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# Stage8 K2 Structured Subspace Baseline Comparison\n\n');
fprintf(fid, 'Terminal status: `STAGE8_K2_SUBSPACE_BASELINE_COMPARISON_COMPLETE`\n\n');
fprintf(fid, 'Protocol: `%s`\n\n', constants.protocol);
fprintf(fid, 'Execution HEAD: `%s`\n\n', head);
fprintf(fid, 'Runtime root: `%s`\n\n', strrep(runtime_root, filesep, '/'));
fprintf(fid, ['The new methods are `MORE-INFORMATIVE ELEMENT-DOMAIN ', ...
    'CLASSICAL REFERENCES`; they do not share Tangent''s 15-dimensional ', ...
    'beamspace hardware interface.\n\n']);
fprintf(fid, '## Integrity and structure\n\n');
fprintf(fid, '- Trial reconstruction: `72/72` exact element hashes.\n');
fprintf(fid, '- New method rows: `%d/216`; reference rows read from evidence 34: `%d`.\n', ...
    height(diagnostics), height(rows) - height(diagnostics));
fprintf(fid, '- Truth isolation: `%d`; applicability: `%d`; explicit outcomes: `%d`.\n', ...
    integrity.truth_isolation_ok, integrity.applicability_contract_ok, ...
    integrity.explicit_outcomes_ok);
fprintf(fid, '- Cylindrical Kronecker residual max: `%.17g`.\n', ...
    structure.kronecker_factorization_residual_max);
fprintf(fid, '- Vertical shift residual max: `%.17g`.\n', ...
    structure.vertical_shift_residual_max);
fprintf(fid, '- Noise Kronecker residual max: `%.17g`; colored residual: `%.17g`.\n', ...
    structure.noise_kronecker_residual_max, ...
    structure.colored_noise_factorization_residual);
fprintf(fid, '- Azimuth whitening residual max: `%.17g`.\n\n', ...
    structure.azimuth_whitening_residual_max);

fprintf(fid, '## Overall method results\n\n');
fprintf(fid, '| Method | Applicable | Valid | Invalid | Joint RMSE median/p90 deg | Az RMSE median/p90 | El RMSE median/p90 | Runtime median/p90 s |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|---:|\n');
methods = summary(summary.row_type == "METHOD", :);
for index = 1:height(methods)
    fprintf(fid, '| %s | %d | %d | %d | %.6g / %.6g | %.6g / %.6g | %.6g / %.6g | %.6g / %.6g |\n', ...
        char(methods.method_id(index)), methods.applicable_count(index), ...
        methods.valid_count(index), methods.applicable_but_invalid_count(index), ...
        methods.median_joint_RMSE_deg(index), methods.p90_joint_RMSE_deg(index), ...
        methods.median_azimuth_RMSE_deg(index), methods.p90_azimuth_RMSE_deg(index), ...
        methods.median_elevation_RMSE_deg(index), methods.p90_elevation_RMSE_deg(index), ...
        methods.median_runtime_sec(index), methods.p90_runtime_sec(index));
end

fprintf(fid, '\n## Elevation and conditional-CML diagnostics\n\n');
fprintf(fid, '| Method | Applicable | Elevation valid | Conditional az CML valid |\n');
fprintf(fid, '|---|---:|---:|---:|\n');
for index = 1:numel(constants.method_ids)
    selected = diagnostics.method_id == constants.method_ids(index) & ...
        diagnostics.applicable;
    fprintf(fid, '| %s | %d | %d | %d |\n', ...
        char(constants.method_ids(index)), nnz(selected), ...
        nnz(diagnostics.elevation_fit_valid(selected)), ...
        nnz(diagnostics.conditional_az_cml_valid(selected)));
end

fprintf(fid, '\n## Pairwise common-subset comparisons\n\n');
fprintf(fid, '| Comparison (left vs right) | Common valid | Wins | Ties | Losses |\n');
fprintf(fid, '|---|---:|---:|---:|---:|\n');
pairs = summary(summary.row_type == "PAIRED", :);
for index = 1:height(pairs)
    fprintf(fid, '| %s | %d | %d | %d | %d |\n', ...
        char(pairs.comparison_id(index)), pairs.paired_count(index), ...
        pairs.wins(index), pairs.ties(index), pairs.losses(index));
end
fprintf(fid, '\nTie tolerance is reporting-only at `1e-6 deg`.\n\n');

fprintf(fid, '## Stratified spread\n\n');
fprintf(fid, '| Method | Dimension | Best median joint RMSE | Worst median joint RMSE |\n');
fprintf(fid, '|---|---|---:|---:|\n');
for method_index = 1:numel(constants.method_ids)
    for scope = ["PROFILE", "L", "SNR_DB", "NOISE"]
        selected = profile_summary.method_id == ...
            constants.method_ids(method_index) & ...
            profile_summary.scope_type == scope & ...
            isfinite(profile_summary.median_joint_RMSE_deg);
        values = profile_summary.median_joint_RMSE_deg(selected);
        fprintf(fid, '| %s | %s | %.6g | %.6g |\n', ...
            char(constants.method_ids(method_index)), char(scope), ...
            min_or_nan_local(values), max_or_nan_local(values));
    end
end

fprintf(fid, '\n## Interpretation\n\n');
music = rows(ismember(rows.method_id, ...
    ["BEAMSPACE_MUSIC_K2", "ELEMENT_MUSIC_K2"]), :);
fprintf(fid, ['1. Frozen standard MUSIC produced `%d` valid rows among `%d` ', ...
    'applicable method-trials. The coherent/near-coherent K2 sample ', ...
    'covariance exposes one dominant peak without spatial smoothing; this ', ...
    'is why the frozen two-dimensional peak picker returned fewer than two ', ...
    'peaks.\n'], nnz(music.fit_valid), nnz(music.applicable));
gdiag = diagnostics(diagnostics.method_id == ...
    "ELEMENT_VERTICAL_GFBSS_MUSIC_AZ_CML" & diagnostics.applicable, :);
fprintf(fid, ['2. The coherent synthetic fixture restores a two-dimensional ', ...
    'vertical signal subspace after P=2 FBSS. Formal GFBSS-MUSIC found two ', ...
    'elevations in `%d/%d` applicable trials.\n'], ...
    nnz(gdiag.elevation_fit_valid), height(gdiag));
root = diagnostics(diagnostics.method_id == ...
    "ELEMENT_VERTICAL_FBSS_ROOT_MUSIC_AZ_CML" & diagnostics.applicable, :);
esprit = diagnostics(diagnostics.method_id == ...
    "ELEMENT_VERTICAL_FBSS_LS_ESPRIT_AZ_CML" & diagnostics.applicable, :);
fprintf(fid, ['3. Root-MUSIC root-selection success is `%d/%d`; LS-ESPRIT ', ...
    'eigenvalue success is `%d/%d` on their white-noise structural subset.\n'], ...
    nnz(root.elevation_fit_valid), height(root), ...
    nnz(esprit.elevation_fit_valid), height(esprit));
fprintf(fid, ['4. Compare the azimuth and elevation RMSE columns above: a ', ...
    'larger azimuth component indicates that the conditional-azimuth CML ', ...
    'backend, rather than elevation extraction, is the dominant endpoint ', ...
    'error source. Its valid rates are reported independently.\n']);
tangent = methods(methods.method_id == "TANGENT_PROFILE_SAFE", :);
fprintf(fid, ['5. Tangent remains the default compressed K2 method. Its ', ...
    'overall median joint RMSE/runtime are `%.6g deg / %.6g s`; the new ', ...
    'element-domain references use all 2080 active elements and their ', ...
    '3721-pair CML cost, so their accuracy/cost is contextual rather than a ', ...
    'hardware-equivalent replacement.\n'], tangent.median_joint_RMSE_deg, ...
    tangent.median_runtime_sec);
fprintf(fid, ['6. P1/P3/P4 and L/SNR/noise differences are quantified in ', ...
    'the stratified table and `40_*_profile_summary.csv`; no performance ', ...
    'threshold is applied.\n']);
fprintf(fid, ['7. P2 has equal elevations and therefore only one unique ', ...
    'vertical spatial frequency. All 54 P2 method rows are structural N/A, ', ...
    'not failures or Tangent wins.\n']);
fprintf(fid, ['8. Full-UCA phase-mode methods are excluded because the ', ...
    'registered observation uses only a 65-of-192 active sector. Expanding ', ...
    'to a complete UCA would change both aperture and input data.\n\n']);
fprintf(fid, 'Default K2: `TANGENT_PROFILE_SAFE`.\n\n');
fprintf(fid, 'Production integration: `false`. Tangent scientific code changed: `false`.\n');
assert(resources.resource_count == 2);
end

function value = mean_local(values)
values = values(isfinite(values));
if isempty(values), value = NaN; else, value = mean(values); end
end

function value = median_local(values)
values = values(isfinite(values));
if isempty(values), value = NaN; else, value = median(values); end
end

function value = percentile_local(values, percentage)
values = sort(values(isfinite(values)));
if isempty(values)
    value = NaN;
    return;
end
position = 1 + (numel(values) - 1) * percentage / 100;
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    weight = position - lower;
    value = (1 - weight) * values(lower) + weight * values(upper);
end
end

function value = min_or_nan_local(values)
if isempty(values), value = NaN; else, value = min(values); end
end

function value = max_or_nan_local(values)
if isempty(values), value = NaN; else, value = max(values); end
end
