function constants = stage8_k2_sb_constants()
% Default scientific budgets; experiment registration lives in RTC constants.
constants = struct( ...
    'N_el', 32, 'N_az', 65, 'K', 2, ...
    'smoothing_length', 31, 'smoothing_subarray_count', 2, ...
    'elevation_grid_deg', 9.8:0.001:10.2, ...
    'elevation_domain_deg', [9.8, 10.2], ...
    'elevation_distinct_tolerance_deg', 1e-6, ...
    'azimuth_grid_deg', 7.4:0.02:8.6, ...
    'azimuth_domain_deg', [7.4, 8.6], ...
    'top_start_count', 4, 'max_sweeps', 8, ...
    'scan_nodes_per_coordinate', 9, ...
    'fminbnd_TolX_deg', 1e-4, 'fminbnd_MaxFunEvals', 80, ...
    'relative_score_tolerance', 1e-8, ...
    'coordinate_update_tolerance_deg', 1e-4, ...
    'rank_multiplier', 1, 'paired_tie_tolerance_deg', 1e-6, ...
    'zero_separation_tolerance_deg', 1e-12, ...
    'root_unit_circle_tolerance', 1e-7, ...
    'root_duplicate_tolerance_deg', 1e-5, ...
    'factorization_tolerance', 1e-10, ...
    'structure_tolerance', 1e-12);
end
