function context = stage8_k2_sb_build_context(repo_dir)
%STAGE8_K2_SB_BUILD_CONTEXT Reuse frozen trial and measurement identities.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_sb_build_context:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
constants = stage8_k2_sb_constants();
cb_context = stage8_k2_cb_build_context(repo_dir);
registry = stage8_k2_cb_build_registry(cb_context);
if height(registry) ~= constants.trial_count || ...
        cb_context.constants.trial_count ~= constants.trial_count || ...
        ~isequal(cb_context.plan.local_domain.domain_bounds_deg, ...
        [constants.azimuth_domain_deg, constants.elevation_domain_deg])
    error('stage8_k2_sb_build_context:FrozenContract', ...
        'The frozen registry or local angular domain changed.');
end

models = repmat(struct('noise_profile_id', "", 'model', struct(), ...
    'noise_factors', struct()), numel(constants.noise_profile_ids), 1);
for index = 1:numel(constants.noise_profile_ids)
    noise_id = constants.noise_profile_ids(index);
    model = resolve_stage8_measurement_model( ...
        cb_context.plan.measurement_model_registry, ...
        constants.primary_measurement_config_id, noise_id);
    factors = stage8_k2_sb_noise_factors(model, constants);
    models(index) = struct('noise_profile_id', noise_id, ...
        'model', model, 'noise_factors', factors);
end

reference_path = fullfile(repo_dir, 'innovation-mining', ...
    '34_stage8_k2_classical_baseline_trials.csv');
if ~isfile(reference_path)
    error('stage8_k2_sb_build_context:ReferenceEvidence', ...
        'Frozen evidence-34 trial rows are missing.');
end
context = struct('repo_dir', repo_dir, 'constants', constants, ...
    'cb_context', cb_context, 'registry', registry, 'models', models, ...
    'reference_trials_path', reference_path, ...
    'single_cpi_flag', true, 'same_range_doppler_cell_flag', true, ...
    'cross_cpi_data_used_flag', false, ...
    'tracking_input_used_flag', false, ...
    'K_estimated_inside_module_flag', false);
context.context_hash = stage8_k2_cb_stable_hash(constants.protocol, ...
    cb_context.context_hash, registry, constants.base_commit);
end
