function factors = stage8_k2_sb_noise_factors(model, constants)
%STAGE8_K2_SB_NOISE_FACTORS Verify the registered Kronecker covariance.

if nargin < 2 || isempty(constants)
    constants = stage8_k2_sb_constants();
end
required = {'Rn_elem','noise_factorization','noise_profile_id'};
if ~(isstruct(model) && isscalar(model) && all(isfield(model, required)))
    error('stage8_k2_sb_noise_factors:Model', ...
        'A registered Stage8 element-noise model is required.');
end
factor = model.noise_factorization;
factor_required = {'R_el','R_az','L_el','L_az','rho_el','rho_az'};
if ~all(isfield(factor, factor_required))
    error('stage8_k2_sb_noise_factors:Factorization', ...
        'The model lacks its separable element-noise factors.');
end
R_el = full(factor.R_el);
R_az = full(factor.R_az);
if ~isequal(size(R_el), [constants.N_el, constants.N_el]) || ...
        ~isequal(size(R_az), [constants.N_az, constants.N_az])
    error('stage8_k2_sb_noise_factors:Dimensions', ...
        'Registered noise factors do not match the active subarray.');
end
Rn_expected = kron(R_az, R_el);
covariance_error = norm(full(model.Rn_elem) - Rn_expected, 'fro') / ...
    max(1, norm(Rn_expected, 'fro'));
L_el = chol(R_el, 'lower');
L_az = chol(R_az, 'lower');
factor_error = max( ...
    norm(L_el * L_el' - R_el, 'fro') / max(1, norm(R_el, 'fro')), ...
    norm(L_az * L_az' - R_az, 'fro') / max(1, norm(R_az, 'fro')));
W_az = L_az \ eye(constants.N_az);
az_whitening_error = norm(W_az * R_az * W_az' - ...
    eye(constants.N_az), 'fro') / sqrt(constants.N_az);
if max([covariance_error, factor_error, az_whitening_error]) > ...
        constants.factorization_tolerance
    error('stage8_k2_sb_noise_factors:Identity', ...
        'Registered Kronecker noise factorization failed verification.');
end
factors = struct('noise_profile_id', string(model.noise_profile_id), ...
    'R_el', R_el, 'R_az', R_az, 'L_el', L_el, 'L_az', L_az, ...
    'W_az', W_az, 'rho_el', factor.rho_el, 'rho_az', factor.rho_az, ...
    'covariance_error', covariance_error, ...
    'factorization_error', factor_error, ...
    'az_whitening_error', az_whitening_error);
end
