function [rows, diagnostics] = stage8_k2_sb_evaluate_trial( ...
    spec, trial, context, resources, run_role)
%STAGE8_K2_SB_EVALUATE_TRIAL Run all registered methods without fit truth.

if nargin < 5 || isempty(run_role)
    run_role = "FORMAL";
end
constants = context.constants;
entry_index = find([resources.entries.noise_profile_id] == ...
    string(spec.noise_profile_id), 1);
if isempty(entry_index)
    error('stage8_k2_sb_evaluate_trial:Resource', ...
        'No exact resource matches the trial noise profile.');
end
entry = resources.entries(entry_index);
if string(entry.model.fixed_measurement_hash) ~= ...
        string(trial.model.fixed_measurement_hash)
    error('stage8_k2_sb_evaluate_trial:ModelIdentity', ...
        'Trial and resource measurement models disagree.');
end

applicability = cell(numel(constants.method_ids), 1);
for index = 1:numel(constants.method_ids)
    applicability{index} = stage8_k2_sb_applicability( ...
        spec, constants.method_ids(index));
end
any_applicable = any(cellfun(@(item) item.applicable, applicability));
preprocess_runtime = 0;
vertical_info = struct('hermitian_residual', NaN);
fbss_info = struct('hermitian_residual', NaN, ...
    'forward_backward_residual', NaN);
raw_eigenvalues = NaN(1, 3);
fb_eigenvalues = NaN(1, 3);
if any_applicable
    clock = tic;
    [R_vertical, vertical_info] = stage8_k2_sb_vertical_covariance( ...
        trial.Y_element, entry.noise_factors, constants);
    [R_fb, R_noise_subarray, fbss_info] = ...
        stage8_k2_sb_fbss_covariance(R_vertical, ...
        entry.noise_factors.R_el, constants);
    Y_white = entry.whitening.whitener * trial.Y_element;
    preprocess_runtime = toc(clock);
    raw_values = sort(real(eig(R_vertical)), 'descend');
    fb_values = sort(real(eig(R_fb)), 'descend');
    raw_eigenvalues = raw_values(1:3).';
    fb_eigenvalues = fb_values(1:3).';
end

row_structs = repmat(stage8_k2_cb_row_template(), ...
    numel(constants.method_ids), 1);
diagnostic_structs = repmat(diagnostic_template_local(), ...
    numel(constants.method_ids), 1);
for index = 1:numel(constants.method_ids)
    method_id = constants.method_ids(index);
    rule = applicability{index};
    if ~rule.applicable
        combined = empty_combined_local(method_id);
        combined.applicable = false;
        combined.applicability_status = rule.status;
        combined.fit_status = rule.status;
        elevation = empty_elevation_local(method_id, rule.status);
        conditional = empty_conditional_local("NOT_RUN_STRUCTURAL_NA");
    else
        if method_id == "ELEMENT_VERTICAL_GFBSS_MUSIC_AZ_CML"
            elevation = stage8_k2_sb_gfbss_music( ...
                R_fb, R_noise_subarray, trial.model, constants);
        elseif method_id == "ELEMENT_VERTICAL_FBSS_ROOT_MUSIC_AZ_CML"
            elevation = stage8_k2_sb_root_music( ...
                R_fb, trial.model, constants);
        else
            elevation = stage8_k2_sb_ls_esprit( ...
                R_fb, trial.model, constants);
        end
        if elevation.fit_valid
            conditional = stage8_k2_sb_conditional_az_cml( ...
                Y_white, elevation.elevations_hat_deg, trial.model, ...
                entry.whitening, constants);
        else
            conditional = empty_conditional_local( ...
                "NOT_RUN_ELEVATION_INVALID");
        end
        combined = combine_local(method_id, elevation, conditional, ...
            preprocess_runtime);
    end
    row_structs(index) = stage8_k2_sb_result_row( ...
        spec, trial, combined, constants);
    diagnostic_structs(index) = diagnostic_local(spec, trial, method_id, ...
        rule, elevation, conditional, raw_eigenvalues, fb_eigenvalues, ...
        vertical_info, fbss_info, run_role);
end
rows = struct2table(row_structs);
diagnostics = struct2table(diagnostic_structs);
end

function combined = combine_local(method_id, elevation, conditional, preprocessing)
combined = empty_combined_local(method_id);
combined.applicable = true;
combined.applicability_status = "APPLICABLE";
combined.fit_valid = elevation.fit_valid && conditional.fit_valid;
if ~elevation.fit_valid
    combined.fit_status = elevation.fit_status;
    combined.optimizer_status = "NOT_RUN_ELEVATION_INVALID";
elseif ~conditional.fit_valid
    combined.fit_status = conditional.fit_status;
    combined.optimizer_status = conditional.optimizer_status;
else
    combined.fit_status = "SUBSPACE_ELEVATION_AND_AZ_CML_VALID";
    combined.optimizer_status = conditional.optimizer_status;
    combined.angles_hat_deg = conditional.angles_hat_deg;
    combined.rss = conditional.rss;
    combined.loglik_concentrated = conditional.loglik_concentrated;
    combined.effective_rank = conditional.effective_rank;
    combined.selected_start_id = conditional.selected_start_id;
    combined.sweep_count = conditional.sweep_count;
end
combined.score_call_count = elevation.score_call_count + ...
    conditional.score_call_count;
combined.svd_call_count = elevation.svd_call_count + ...
    conditional.svd_call_count;
combined.eig_call_count = elevation.eig_call_count + ...
    conditional.eig_call_count;
combined.runtime_sec = preprocessing + elevation.runtime_sec + ...
    conditional.runtime_sec;
combined.online_runtime_sec = combined.runtime_sec;
combined.coarse_candidate_count = conditional.coarse_candidate_count;
combined.continuous_start_count = conditional.continuous_start_count;
if isfield(elevation, 'local_peak_count')
    combined.local_peak_count = elevation.local_peak_count;
elseif isfield(elevation, 'registered_root_count')
    combined.local_peak_count = elevation.registered_root_count;
else
    combined.local_peak_count = double(elevation.fit_valid) * 2;
end
end

function combined = empty_combined_local(method_id)
combined = struct('method_id', method_id, ...
    'observation_domain', "ELEMENT", 'applicable', true, ...
    'applicability_status', "APPLICABLE", 'fit_valid', false, ...
    'fit_status', "NOT_RUN", 'optimizer_status', "NOT_RUN", ...
    'selected_source', method_id, 'selected_start_id', "", ...
    'angles_hat_deg', NaN(2, 2), 'rss', NaN, ...
    'loglik_concentrated', NaN, 'effective_rank', 0, ...
    'score_call_count', 0, 'svd_call_count', 0, ...
    'eig_call_count', 0, 'runtime_sec', 0, ...
    'online_runtime_sec', 0, 'precompute_runtime_sec_amortized', 0, ...
    'coarse_candidate_count', 0, 'continuous_start_count', 0, ...
    'sweep_count', 0, 'local_peak_count', 0, ...
    'truth_used_in_fit_flag', false, ...
    'profile_used_in_fit_flag', false, ...
    'tangent_used_in_start_flag', false, ...
    'core_used_in_start_flag', false, ...
    'full_manifold_used_flag', true);
end

function elevation = empty_elevation_local(method_id, status)
elevation = struct('method_id', method_id, 'applicable', false, ...
    'applicability_status', status, 'fit_valid', false, ...
    'fit_status', status, 'elevations_hat_deg', [NaN, NaN], ...
    'selection_values', [NaN, NaN], 'score_call_count', 0, ...
    'svd_call_count', 0, 'eig_call_count', 0, 'runtime_sec', 0);
end

function conditional = empty_conditional_local(status)
conditional = struct('fit_valid', false, 'fit_status', status, ...
    'optimizer_status', status, 'angles_hat_deg', NaN(2, 2), ...
    'rss', NaN, 'loglik_concentrated', NaN, 'effective_rank', 0, ...
    'selected_start_id', "", 'sweep_count', 0, ...
    'score_call_count', 0, 'svd_call_count', 0, ...
    'eig_call_count', 0, 'runtime_sec', 0, ...
    'coarse_candidate_count', 0, 'continuous_start_count', 0);
end

function row = diagnostic_local(spec, trial, method_id, rule, elevation, ...
    conditional, raw_eigenvalues, fb_eigenvalues, vertical_info, ...
    fbss_info, run_role)
row = diagnostic_template_local();
row.global_trial_index = double(spec.global_trial_index);
row.trial_id = string(spec.trial_id);
row.method_id = method_id;
row.run_role = string(run_role);
row.noise_profile_id = string(spec.noise_profile_id);
row.L = double(spec.L);
row.snr_db = double(spec.snr_db);
row.profile_id = string(spec.profile_id);
row.element_trial_hash = string(trial.element_trial_hash);
row.element_hash_match_flag = logical(trial.element_hash_match_flag);
row.applicable = logical(rule.applicable);
row.applicability_status = string(rule.status);
row.elevation_fit_valid = logical(elevation.fit_valid);
row.elevation_fit_status = string(elevation.fit_status);
row.elevations_hat_deg = string(mat2str( ...
    elevation.elevations_hat_deg, 17));
row.elevation_selection_values = string(mat2str( ...
    get_local(elevation, 'selection_values', [NaN, NaN]), 17));
row.elevation_candidate_count = double(get_local(elevation, ...
    'elevation_candidate_count', get_local(elevation, ...
    'registered_root_count', double(elevation.fit_valid) * 2)));
row.root_count = double(get_local(elevation, 'root_count', 0));
row.registered_root_count = double(get_local(elevation, ...
    'registered_root_count', 0));
row.selected_root_moduli = string(mat2str(get_local(elevation, ...
    'selected_root_moduli', [NaN, NaN]), 17));
row.esprit_eigenvalue_moduli = string(mat2str(get_local(elevation, ...
    'eigenvalue_moduli', [NaN, NaN]), 17));
row.conditional_az_cml_valid = logical(conditional.fit_valid);
row.conditional_az_cml_status = string(conditional.fit_status);
row.raw_vertical_eigenvalues_top3 = string(mat2str(raw_eigenvalues, 17));
row.fbss_eigenvalues_top3 = string(mat2str(fb_eigenvalues, 17));
row.vertical_hermitian_residual = double(vertical_info.hermitian_residual);
row.fbss_hermitian_residual = double(fbss_info.hermitian_residual);
row.fbss_structure_residual = double( ...
    fbss_info.forward_backward_residual);
row.truth_used_in_fit_flag = false;
row.profile_used_in_fit_flag = false;
end

function row = diagnostic_template_local()
row = struct('global_trial_index', 0, 'trial_id', "", ...
    'method_id', "", 'run_role', "", 'noise_profile_id', "", ...
    'L', 0, 'snr_db', NaN, 'profile_id', "", ...
    'element_trial_hash', "", 'element_hash_match_flag', false, ...
    'applicable', false, 'applicability_status', "NOT_RUN", ...
    'elevation_fit_valid', false, 'elevation_fit_status', "NOT_RUN", ...
    'elevations_hat_deg', "", 'elevation_selection_values', "", ...
    'elevation_candidate_count', 0, 'root_count', 0, ...
    'registered_root_count', 0, 'selected_root_moduli', "", ...
    'esprit_eigenvalue_moduli', "", ...
    'conditional_az_cml_valid', false, ...
    'conditional_az_cml_status', "NOT_RUN", ...
    'raw_vertical_eigenvalues_top3', "", ...
    'fbss_eigenvalues_top3', "", ...
    'vertical_hermitian_residual', NaN, ...
    'fbss_hermitian_residual', NaN, ...
    'fbss_structure_residual', NaN, ...
    'truth_used_in_fit_flag', false, ...
    'profile_used_in_fit_flag', false);
end

function value = get_local(input, field, default)
if isfield(input, field)
    value = input.(field);
else
    value = default;
end
end
