function resources = stage8_k2_sb_prepare_resources(context)
%STAGE8_K2_SB_PREPARE_RESOURCES Build exact reusable element whiteners.

entries = repmat(struct('noise_profile_id', "", 'model', struct(), ...
    'noise_factors', struct(), 'whitening', struct(), ...
    'precompute_runtime_sec', 0), numel(context.models), 1);
for index = 1:numel(context.models)
    clock = tic;
    source = context.models(index);
    dummy = complex(zeros(size(source.model.Rn_elem, 1), 1));
    [white, whitening] = stage8_k2_cb_whiten_element_data( ...
        dummy, source.model);
    if any(white(:) ~= 0)
        error('stage8_k2_sb_prepare_resources:ZeroWhitening', ...
            'A zero input did not remain zero after whitening.');
    end
    entries(index) = struct('noise_profile_id', ...
        source.noise_profile_id, 'model', source.model, ...
        'noise_factors', source.noise_factors, ...
        'whitening', whitening, ...
        'precompute_runtime_sec', toc(clock));
end
resources = struct('entries', entries, ...
    'resource_count', numel(entries), ...
    'truth_used_in_precompute_flag', false);
end
