clc
clear
close all

step_dir = fileparts(mfilename('fullpath'));
steps_dir = fileparts(step_dir);
project_dir = fileparts(steps_dir);
package_dir = fileparts(fileparts(project_dir));
repo_dir = fileparts(package_dir);
common_dir = fullfile(step_dir, 'common');
tests_dir = fullfile(step_dir, 'tests');
result_dir = fullfile(step_dir, 'results');
figure_dir = fullfile(step_dir, 'figures');

addpath(fullfile(steps_dir, 'step_12_0_receive_model_correction', 'common'));
addpath(fullfile(steps_dir, 'step_12_1_sequential_dbf_model', 'common'));
addpath(fullfile(steps_dir, 'step_12_2_stable_dml_backend', 'common'));
addpath(fullfile(steps_dir, 'step_12_3_grouped_conditional_dml', 'common'));
addpath(common_dir);
addpath(tests_dir);
addpath(fullfile(project_dir, 'core', 'config'));
addpath(fullfile(project_dir, 'core', 'array'));
cd(repo_dir);

stage_tic = tic;
cfg = sim_cfg();
[plan, plan_outputs] = freeze_stage7_locked_plan( ...
    cfg, repo_dir, step_dir, result_dir);
plan_file_hashes = plan_hashes_local(plan_outputs);
fprintf('Stage7 plan frozen before FIM: %s\n', plan.hashes.stage7_plan_hash);

context = prepare_stage7_fim_context(plan, cfg);
tests = run_stage7_unit_tests(context, step_dir, package_dir);
[analyzer_count, analyzer_table] = code_analyzer_local(step_dir);
scope_violation_count = nnz(~tests.scope.pass_flag) + ...
    nnz(~tests.no_model_order.pass_flag);
technical_prepass = tests.all_tests_pass && analyzer_count == 0 && ...
    scope_violation_count == 0;
assert(technical_prepass, 'run_step12_5:TechnicalPrepass', ...
    'Stage 7 stopped before exact enumeration because a technical gate failed.');

online_benchmark = benchmark_stage7_online_dbf_runtime(context);
[enumeration, enumeration_complexity] = enumerate_exact_subset_design(context);
enumeration.measured_online_dbf_runtime = NaN(height(enumeration), 1);
for profile_index = 1:height(online_benchmark)
    match = enumeration.B_e == online_benchmark.B_e(profile_index) & ...
        enumeration.B_a == online_benchmark.B_a(profile_index);
    enumeration.measured_online_dbf_runtime(match) = ...
        online_benchmark.measured_online_dbf_runtime(profile_index);
end
assert(all(isfinite(enumeration.measured_online_dbf_runtime)), ...
    'run_step12_5:OnlineRuntime', ...
    'Every rectangular subset must have a measured online DBF runtime.');
writetable(enumeration, fullfile(result_dir, 'fim_subset_enumeration.csv'));
fprintf('Stage7 exact enumeration complete: %d subsets\n', height(enumeration));
assert(all(enumeration.data_processing_violation_count == 0), ...
    'run_step12_5:DataProcessing', ...
    'A numerical data-processing violation was detected.');
[operating, pareto] = select_stage7_operating_points(enumeration, context);
writetable(operating, fullfile(result_dir, 'fim_operating_points.csv'));
fprintf('Stage7 FIM operating gates: %d/%d pass\n', ...
    nnz(operating.fim_gate_pass), height(operating));

greedy_rows = cell(numel(plan.controls.eta_operating_points), 1);
greedy_traces = cell(numel(plan.controls.eta_operating_points), 1);
for index = 1:numel(plan.controls.eta_operating_points)
    eta0 = plan.controls.eta_operating_points(index);
    [greedy_result, greedy_trace] = ...
        greedy_exchange_exact_subset_design(eta0, context, struct());
    greedy_result.eta0 = eta0;
    greedy_rows{index} = greedy_result;
    greedy_trace.eta0 = repmat(eta0, height(greedy_trace), 1);
    greedy_traces{index} = greedy_trace;
end
greedy_table = struct2table(vertcat(greedy_rows{:}));
greedy_trace_table = vertcat(greedy_traces{:});
greedy_gap = build_stage7_greedy_gap_table(operating, greedy_table);
fprintf('Stage7 greedy comparison complete\n');
methods = build_stage7_method_registry(operating, greedy_table, context);
fprintf('Stage7 finite method registry: %d methods\n', height(methods));
strongest_fixed = select_stage7_strongest_fixed_baseline( ...
    methods, enumeration);
[fim_validation, fim_holdout] = ...
    build_stage7_selected_fim_details(methods, context);
selected_family = unique(methods.subset_id, 'stable');
selected_rows = plan.subset_family(ismember(plan.subset_family.subset_id, ...
    selected_family), :);
center_single = plan.subset_family( ...
    plan.subset_family.elevation_mask_integer == 4 & ...
    plan.subset_family.azimuth_mask_integer == 4, :);
selected_rows = [center_single; selected_rows];
[~, unique_selected] = unique(selected_rows.subset_id, 'stable');
selected_rows = selected_rows(unique_selected, :);
tangent = test_stage6_subset_tangent_consistency(context, selected_rows);

scenario_count = numel(context.scenarios);
precompute_counts = context.precompute_counts;
fim_context_info = whos('context');
memory_workspace_bytes = 8 * ...
    (context.cfg.arr.Nel * context.cfg.beam.subNaz) ^ 2;
finite = prepare_stage7_finite_sample_context(context, methods);
clear context
if any(operating.fim_gate_pass)
    [finite_trials, finite_complexity] = ...
        run_stage7_finite_sample_validation(finite);
    [finite_summary, finite_aggregate] = summarize_stage7_finite_sample_trials( ...
        finite_trials, methods, strongest_fixed);
    finite_summary = add_stage7_finite_plan_metadata( ...
        finite_summary, plan.finite_sample_plan);
    [decision, operating] = apply_stage7_finite_sample_pareto_gate( ...
        operating, finite_aggregate, strongest_fixed, finite.context);
    risk = build_stage7_fim_risk_table( ...
        methods, enumeration, finite_aggregate, finite_summary);
else
    [finite_trials, finite_summary, finite_aggregate, risk, ...
        finite_complexity] = empty_stage7_finite_outputs(methods, enumeration);
    operating.scheme_A_pass = false(height(operating), 1);
    operating.scheme_B_pass = false(height(operating), 1);
    operating.finite_sample_pareto_pass = false(height(operating), 1);
    operating.strongest_fixed_baseline = ...
        repmat(strongest_fixed, height(operating), 1);
    operating.decision_status = repmat("FIM_GATE_REJECTED", ...
        height(operating), 1);
    decision = struct('stage_status', 'PARTIAL', ...
        'stage8_technical_permission', false, ...
        'strongest_fixed_baseline', char(strongest_fixed), ...
        'fim_operating_point_pass_count', 0, ...
        'finite_sample_pareto_pass_count', 0, ...
        'baseline_success_rate', NaN, 'full_parent_success_rate', NaN);
end
baseline_status = build_stage7_baseline_status( ...
    methods, finite.context, operating, greedy_table);

post_stage6 = verify_stage6_frozen_evidence(package_dir);
post_stage5 = verify_stage5_frozen_results(package_dir);
post_step11 = verify_step11_frozen_results(package_dir);
upstream_post_pass = all(post_stage6.pass_flag) && ...
    all(post_stage5.pass_flag) && all(post_step11.pass_flag);
plan_unchanged = isequal(plan_file_hashes, plan_hashes_local(plan_outputs));
[git_status, ~] = system('git diff --check');
technical_final = technical_prepass && upstream_post_pass && plan_unchanged && ...
    git_status == 0 && height(enumeration) == 961;
assert(technical_final, 'run_step12_5:FinalTechnicalGate', ...
    'A final Stage 7 technical gate failed.');

runtime_sec = toc(stage_tic);
greedy_candidate_evaluations = sum(greedy_table.greedy_evaluation_count) / ...
    scenario_count;
complexity = struct();
complexity.FIM_evaluations = enumeration_complexity.FIM_evaluations + ...
    sum(greedy_table.greedy_evaluation_count) + ...
    height(methods) * scenario_count;
complexity.covariance_decompositions = ...
    enumeration_complexity.covariance_decompositions + ...
    2 * greedy_candidate_evaluations + 2 * height(methods);
complexity.whitener_eigendecompositions = ...
    enumeration_complexity.whitener_eigendecompositions + ...
    2 * greedy_candidate_evaluations + 2 * height(methods);
complexity.manifold_evaluations = ...
    precompute_counts.receive_manifold_evaluations + ...
    1 + sum(plan.finite_sample_plan.Nmc);
complexity.derivative_evaluations = ...
    precompute_counts.derivative_evaluations;
complexity.generalized_eigenvalue_evaluations = ...
    enumeration_complexity.generalized_eigenvalue_evaluations + ...
    2 * sum(greedy_table.greedy_evaluation_count) + ...
    2 * height(methods) * scenario_count;
complexity.greedy_candidate_evaluations = greedy_candidate_evaluations;
complexity.finite_sample_DML_score_calls = ...
    finite_complexity.charged_method_score_calls;
complexity.finite_sample_SVD_calls = finite_complexity.charged_method_svd_calls;
complexity.runtime_sec = runtime_sec;
complexity.peak_memory_estimate_bytes = peak_memory_estimate_local( ...
    fim_context_info.bytes, memory_workspace_bytes, finite_trials, enumeration);
complexity.result_data_volume_bytes = 0;

validation = struct('code_analyzer_count', analyzer_count, ...
    'code_analyzer_table', analyzer_table, ...
    'scope_violation_count', scope_violation_count, ...
    'plan_unchanged', plan_unchanged, 'git_diff_check_status', git_status, ...
    'technical_pass', technical_final);
bundle = struct('plan', plan, 'tests', tests, 'validation', validation, ...
    'enumeration', enumeration, 'pareto', pareto, 'operating', operating, ...
    'greedy_gap', greedy_gap, 'greedy_trace', greedy_trace_table, ...
    'fim_validation', fim_validation, 'fim_holdout', fim_holdout, ...
    'tangent', tangent, 'finite_summary', finite_summary, ...
    'finite_aggregate', finite_aggregate, 'risk', risk, ...
    'baseline_status', baseline_status, ...
    'online_benchmark', online_benchmark, 'decision', decision, ...
    'complexity', complexity);
write_stage7_results_bundle(result_dir, bundle);
plot_stage7_results(figure_dir, enumeration, operating, greedy_gap, ...
    finite_summary(finite_summary.data_split == "THRESHOLD_HOLDOUT", :), risk);

fprintf('Step12.5 Stage 7 result: %s\n', decision.stage_status);
fprintf('Subsets/scenarios: %d/%d; FIM operating passes: %d/3\n', ...
    height(enumeration), scenario_count, decision.fim_operating_point_pass_count);
fprintf('Finite Pareto passes: %d/3; strongest fixed: %s\n', ...
    decision.finite_sample_pareto_pass_count, decision.strongest_fixed_baseline);
fprintf('Analyzer/scope/data-processing violations: %d/%d/%d\n', ...
    analyzer_count, scope_violation_count, ...
    sum(enumeration.data_processing_violation_count));
fprintf('Runtime: %.3f s\nResults: %s\nFigures: %s\n', ...
    runtime_sec, result_dir, figure_dir);
fprintf('This run stops at Stage 7. Stage 8 was not executed.\n');

function hashes = plan_hashes_local(outputs)
names = sort(fieldnames(outputs));
hashes = strings(numel(names), 1);
for index = 1:numel(names)
    bytes = uint8(fileread(outputs.(names{index})));
    hashes(index) = stage7_stable_hash(names{index}, bytes);
end
end

function [count, table_out] = code_analyzer_local(step_dir)
files = dir(fullfile(step_dir, '**', '*.m'));
rows = cell(0, 1);
for file_index = 1:numel(files)
    path_now = fullfile(files(file_index).folder, files(file_index).name);
    messages = checkcode(path_now, '-id');
    for message_index = 1:numel(messages)
        rows{end + 1, 1} = struct('file', string(path_now), ...
            'line', messages(message_index).line, ...
            'message_id', string(messages(message_index).id), ...
            'message', string(messages(message_index).message)); %#ok<AGROW>
    end
end
count = numel(rows);
if count == 0, table_out = table(); else, table_out = struct2table(vertcat(rows{:})); end
end

function bytes = peak_memory_estimate_local( ...
    context_bytes, workspace_bytes, trials, enumeration)
if ~istable(trials) || ~istable(enumeration)
    error('run_step12_5:MemoryInputs', ...
        'Memory accounting requires finite-trial and enumeration tables.');
end
info_trials = whos('trials');
info_enumeration = whos('enumeration');
bytes = context_bytes + info_trials.bytes + info_enumeration.bytes + ...
    workspace_bytes;
end
