function rows = stage8_k2_snr_evaluate_trial(spec, trial, snr_metrics, context)
%STAGE8_K2_SNR_EVALUATE_TRIAL Evaluate three frozen methods on one new trial.

fits = stage8_k2_snr_fit_methods( ...
    trial.Y_element, trial.model, context.tp_context);
items = {fits.lite, fits.plus, fits.tangent};
rows_struct = repmat(template_local(), 3, 1);
for index = 1:3
    result = items{index};
    row = template_local();
    row.trial_id = string(spec.trial_id);
    row.paired_original_trial_id = string(spec.paired_original_trial_id);
    row.method_id = context.constants.method_ids(index);
    row.noise_profile_id = string(spec.noise_profile_id);
    row.L = double(spec.L);
    row.profile_id = string(spec.profile_id);
    row.snr_control_domain = string(spec.snr_control_domain);
    row.white_beamspace_snr_target_db = ...
        double(spec.white_beamspace_snr_target_db);
    row.element_snr_expected_db = snr_metrics.element_snr_expected_db;
    row.element_snr_realized_db = snr_metrics.element_snr_realized_db;
    row.raw_beam_snr_expected_db = snr_metrics.raw_beam_snr_expected_db;
    row.raw_beam_snr_realized_db = snr_metrics.raw_beam_snr_realized_db;
    row.white_beam_snr_expected_db = snr_metrics.white_beam_snr_expected_db;
    row.white_beam_snr_realized_db = snr_metrics.white_beam_snr_realized_db;
    row.k2_projected_snr_expected_db = ...
        snr_metrics.k2_projected_snr_expected_db;
    row.k2_projected_snr_realized_db = ...
        snr_metrics.k2_projected_snr_realized_db;
    row.fit_valid = logical(result.fit_valid);
    row.fit_status = string(result.fit_status);
    row.selected_source = string(result.selected_source);
    row.angles_hat_deg = string(mat2str(result.angles_hat_deg, 17));
    row.RSS = double(result.rss);
    row.loglik = double(result.loglik_concentrated);
    row.effective_rank = double(result.effective_rank);
    errors = stage8_k2_snr_geometry_metrics( ...
        result.angles_hat_deg, trial.truth_angles_deg, context.constants);
    names = fieldnames(errors);
    for name_index = 1:numel(names)
        row.(names{name_index}) = errors.(names{name_index});
    end
    if index < 3
        row.upgrade_flag = logical( ...
            result.diagnostics.continuous_upgrade_flag);
        row.fallback_flag = logical(result.diagnostics.fallback_flag);
        if row.fallback_flag
            row.fallback_reason = "FROZEN_FIXED_GRID_SELECTED";
        else
            row.fallback_reason = "NOT_APPLICABLE";
        end
    else
        row.upgrade_flag = logical(fits.tangent_diagnostics.upgrade_flag);
        row.fallback_flag = logical(fits.tangent_diagnostics.fallback_flag);
        row.fallback_reason = string( ...
            fits.tangent_diagnostics.fallback_reason);
    end
    row.score_call_count = double(result.score_call_count);
    row.SVD_call_count = double(result.svd_call_count);
    row.runtime_sec = double(result.runtime_sec);
    row.truth_used_in_fit_flag = logical(result.truth_used_in_fit_flag);
    rows_struct(index) = row;
end
rows = struct2table(rows_struct);
end

function row = template_local()
row = struct('trial_id', "", 'paired_original_trial_id', "", ...
    'method_id', "", 'noise_profile_id', "", 'L', 0, ...
    'profile_id', "", 'snr_control_domain', "", ...
    'white_beamspace_snr_target_db', NaN, ...
    'element_snr_expected_db', NaN, 'element_snr_realized_db', NaN, ...
    'raw_beam_snr_expected_db', NaN, 'raw_beam_snr_realized_db', NaN, ...
    'white_beam_snr_expected_db', NaN, ...
    'white_beam_snr_realized_db', NaN, ...
    'k2_projected_snr_expected_db', NaN, ...
    'k2_projected_snr_realized_db', NaN, ...
    'fit_valid', false, 'fit_status', "NOT_RUN", ...
    'selected_source', "NOT_RUN", 'angles_hat_deg', "", ...
    'RSS', NaN, 'loglik', NaN, 'effective_rank', 0, ...
    'joint_RMSE_deg', NaN, 'azimuth_RMSE_deg', NaN, ...
    'elevation_RMSE_deg', NaN, 'center_error_deg', NaN, ...
    'direction_axis_error_deg', NaN, 'rho_error_deg', NaN, ...
    'rho_relative_error', NaN, 'separation_vector_error_deg', NaN, ...
    'upgrade_flag', false, 'fallback_flag', false, ...
    'fallback_reason', "NOT_RUN", 'score_call_count', 0, ...
    'SVD_call_count', 0, 'runtime_sec', 0, ...
    'truth_used_in_fit_flag', false);
end
