function constants = stage8_k2_snr_constants()
%STAGE8_K2_SNR_CONSTANTS Fixed SNR-domain validation contract.

constants = struct( ...
    'protocol', ...
    'STAGE8_K2_SNR_DOMAIN_AUDIT_AND_WHITE_BEAMSPACE_REPARAMETERIZATION_V1', ...
    'authorization', ...
    'AUTHORIZE_STAGE8_K2_SNR_DOMAIN_AUDIT_AND_DIRECT_TANGENT_BRANCH_EXECUTION_V1', ...
    'branch', 'experiment/stage8-k2-tangent', ...
    'starting_commit', ...
    'dcde540e3f3af793c0b8beb18e41a798af64739a', ...
    'expected_origin_main', ...
    '247fad2208e77b04f7062e22b0fd3fd8a81bfc1f', ...
    'expected_origin_research', ...
    'a7139204d717923cb89d0d629b67f1b3ab7ae94d', ...
    'primary_measurement_config_id', 'PRIMARY_RECT_E14_A31', ...
    'control_domain', ...
    'WHITENED_SEQUENTIAL_BEAMSPACE_EXPECTED_TOTAL_SNR', ...
    'white_snr_targets_db', [-6, 0, 6], ...
    'method_ids', ["CORE_LITE"; "CORE_PLUS"; ...
    "TANGENT_PROFILE_SAFE"], ...
    'trial_count', 72, 'method_row_count', 216, ...
    'source_scale_relative_tolerance', 1e-12, ...
    'snr_db_tolerance', 1e-10, ...
    'raw_covariance_tolerance', 1e-12, ...
    'whitening_tolerance', 1e-10, ...
    'white_scale_relative_tolerance', 1e-12, ...
    'paired_tie_tolerance_deg', 1e-6, ...
    'zero_separation_tolerance_deg', 1e-12, ...
    'runtime_root', ...
    'E:\bs_innovation_runtime\stage8_k2_snr_domain_validation_v1');
end
