function output = stage8_k2_snr_run_tests(repo_dir)
%STAGE8_K2_SNR_RUN_TESTS Run the ten registered SNR validation tests.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_snr_run_tests:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
scope = stage8_k2_snr_add_paths(repo_dir); %#ok<NASGU>
context = stage8_k2_snr_build_context(repo_dir);
tests = { ...
    @() test_original_72_hash_identity(context), ...
    @() test_element_snr_definition(context), ...
    @() test_raw_beam_covariance_identity(context), ...
    @() test_whitening_identity(context), ...
    @() test_white_snr_scaling_contract(context), ...
    @() test_expected_vs_realized_noise_contract(context), ...
    @() test_paired_seed_and_source_shape(context), ...
    @() test_projected_k2_snr_fixture(context), ...
    @() test_no_truth_leakage(context), ...
    @() test_four_trial_smoke(context)};
names = ["T1_ORIGINAL_72_HASH"; "T2_ELEMENT_SNR"; ...
    "T3_RAW_BEAM_COVARIANCE"; "T4_FROZEN_WHITENER_NUMERIC_QUALITY"; ...
    "T5_WHITE_SNR_SCALING"; "T6_EXPECTED_VS_REALIZED"; ...
    "T7_PAIRED_SOURCE_NOISE"; "T8_PROJECTED_K2_SNR"; ...
    "T9_TRUTH_ISOLATION"; "T10_FOUR_TRIAL_SMOKE"];
results = cell(numel(tests), 1);
for index = 1:numel(tests)
    results{index} = tests{index}();
    if ~isstruct(results{index}) || ~isfield(results{index}, 'pass') || ...
            ~results{index}.pass
        error('stage8_k2_snr_run_tests:Failure', ...
            'Registered test failed: %s', names(index));
    end
    fprintf('%s PASS\n', names(index));
end
output = struct('pass', true, 'test_count', numel(tests), ...
    'test_names', names, 'results', {results}, ...
    'context_hash', context.context_hash);
fprintf('STAGE8_K2_SNR_DOMAIN_VALIDATION_TESTS_PASS 10/10\n');
end
