function metric = stage8_k2_snr_projected_k2_metric( ...
    signal_white, noise_white, C_w, truth_angles_deg, model)
%STAGE8_K2_SNR_PROJECTED_K2_METRIC Compute the truth-only center residual SNR.

if ~(isequal(size(truth_angles_deg), [2, 2]) && ...
        all(isfinite(truth_angles_deg(:))))
    error('stage8_k2_snr_projected_k2_metric:Truth', ...
        'truth_angles_deg must be finite 2-by-2 endpoints.');
end
center = mean(truth_angles_deg, 1);
[g_center, ~, ~] = build_full_sequential_local_manifold( ...
    center, model, struct('rank_multiplier', 1));
energy = real(g_center' * g_center);
if ~(isfinite(energy) && energy > 0)
    error('stage8_k2_snr_projected_k2_metric:CenterManifold', ...
        'The true-center whitened manifold has invalid energy.');
end
projector = eye(size(C_w, 1), 'like', C_w) - ...
    (g_center * g_center') / energy;
signal_projected = projector * signal_white;
noise_projected = projector * noise_white;
signal_energy = norm(signal_projected, 'fro') ^ 2;
noise_expected_energy = size(signal_white, 2) * real(trace( ...
    projector * C_w * projector'));
noise_realized_energy = norm(noise_projected, 'fro') ^ 2;
metric = struct('signal_energy', signal_energy, ...
    'noise_expected_energy', noise_expected_energy, ...
    'noise_realized_energy', noise_realized_energy, ...
    'snr_expected_db', ratio_db_local(signal_energy, ...
    noise_expected_energy), ...
    'snr_realized_db', ratio_db_local(signal_energy, ...
    noise_realized_energy), ...
    'projector', projector, 'truth_only_diagnostic_flag', true);
end

function value = ratio_db_local(numerator, denominator)
if denominator > 0 && numerator > 0
    value = 10 * log10(numerator / denominator);
elseif denominator > 0 && numerator == 0
    value = -Inf;
else
    value = NaN;
end
end
