function trial = stage8_k2_snr_generate_white_control_trial(spec, context)
%STAGE8_K2_SNR_GENERATE_WHITE_CONTROL_TRIAL Scale by expected white SNR only.

required = {'paired_original_trial_id','white_beamspace_snr_target_db', ...
    'snr_control_domain'};
if ~(istable(spec) && height(spec) == 1 && ...
        all(ismember(required, spec.Properties.VariableNames)))
    error('stage8_k2_snr_generate_white_control_trial:Spec', ...
        'spec is not one white-beamspace-control registry row.');
end
if spec.snr_control_domain ~= string(context.constants.control_domain)
    error('stage8_k2_snr_generate_white_control_trial:ControlDomain', ...
        'The SNR control domain is not the registered expected-white domain.');
end
fixture = stage8_k2_snr_build_source_fixture(spec, context);
signal_unscaled = fixture.manifold.A * fixture.source_unscaled;
raw_unscaled = fixture.model.W_I' * signal_unscaled;
white_unscaled = fixture.model.T_I * raw_unscaled;
C_b = fixture.model.C_I;
C_w = fixture.model.T_I * C_b * fixture.model.T_I';
gamma_target = 10 ^ (spec.white_beamspace_snr_target_db / 10);
expected_white_noise_energy = spec.L * real(trace(C_w));
source_scale = sqrt(gamma_target * expected_white_noise_energy / ...
    max(norm(white_unscaled, 'fro') ^ 2, realmin));
source = fixture.source_unscaled * source_scale;
signal = fixture.manifold.A * source;
[noise, noise_debug] = generate_stage8_element_noise( ...
    fixture.model, spec.L, 1, spec.noise_seed);
Y_element = signal + noise;
element_expected = norm(signal, 'fro') ^ 2 / ...
    (spec.L * real(trace(fixture.model.Rn_elem)));
white_expected = norm(fixture.model.T_I * ...
    (fixture.model.W_I' * signal), 'fro') ^ 2 / ...
    expected_white_noise_energy;
relative_error = abs(white_expected - gamma_target) / max(1, gamma_target);
if relative_error > context.constants.white_scale_relative_tolerance
    error('stage8_k2_snr_generate_white_control_trial:Scaling', ...
        'Expected whitened-beamspace SNR scaling failed its contract.');
end
element_trial_hash = stage8_k2_snr_stable_hash( ...
    context.constants.protocol, 'WHITE_CONTROL_ELEMENT_TRIAL', ...
    char(spec.trial_id), Y_element, fixture.truth_angles_deg, ...
    double(spec.white_beamspace_snr_target_db), ...
    double(10 * log10(element_expected)), double(spec.source_seed), ...
    double(spec.noise_seed), char(spec.noise_profile_id));
trial = struct('Y_element', Y_element, ...
    'truth_angles_deg', fixture.truth_angles_deg, ...
    'model', fixture.model, 'source_matrix', source, ...
    'source_unscaled', fixture.source_unscaled, ...
    'source_scale', source_scale, 'signal_element', signal, ...
    'noise_element', noise, 'source_phase_rad', fixture.source_phase_rad, ...
    'source_info', fixture.source_info, 'noise_debug', noise_debug, ...
    'element_trial_hash', string(element_trial_hash), ...
    'white_snr_target_linear', gamma_target, ...
    'white_snr_scaling_relative_error', relative_error, ...
    'truth_used_in_fit_flag', false);
end
