function fits = stage8_k2_snr_fit_methods(Y_element, model, tp_context)
%STAGE8_K2_SNR_FIT_METHODS Data-only adapter to the three frozen fit paths.

domain = tp_context.plan.local_domain;
noise_model = model.noise_factorization;
lite = estimate_stage8_known_k_local_cell(Y_element, model, domain, ...
    tp_context.stage5_locked, noise_model, 2, ...
    struct('mode', 'CORE_LITE', 'return_diagnostics', true));
plus = estimate_stage8_known_k_local_cell(Y_element, model, domain, ...
    tp_context.stage5_locked, noise_model, 2, ...
    struct('mode', 'CORE_PLUS', 'return_diagnostics', true));
[tangent, tangent_diagnostics] = stage8_k2_tp_fit_safe( ...
    Y_element, model, tp_context);
fits = struct('lite', lite, 'plus', plus, 'tangent', tangent, ...
    'tangent_diagnostics', tangent_diagnostics);
end
