function output = stage8_k2_snr_run(repo_dir, runtime_root)
%STAGE8_K2_SNR_RUN Execute tests, Phase A, smoke, Phase B, and evidence.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_snr_run:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
constants = stage8_k2_snr_constants();
if nargin < 2 || isempty(runtime_root)
    runtime_root = constants.runtime_root;
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
runtime_root = char(java.io.File(char(string(runtime_root))).getCanonicalPath());
expected_runtime = char(java.io.File(constants.runtime_root).getCanonicalPath());
if ~strcmp(runtime_root, expected_runtime)
    error('stage8_k2_snr_run:RuntimeRoot', ...
        'Formal runtime is fixed at %s.', expected_runtime);
end
if ~strcmp(version('-release'), '2022b') || maxNumCompThreads ~= 1
    error('stage8_k2_snr_run:MATLABRuntime', ...
        'Formal execution requires MATLAB R2022b with -singleCompThread.');
end
try
    pool = gcp('nocreate');
catch
    pool = [];
end
if ~isempty(pool)
    error('stage8_k2_snr_run:ParallelPool', ...
        'Formal execution forbids an active parallel pool.');
end
scope = stage8_k2_snr_add_paths(repo_dir); %#ok<NASGU>
preflight = preflight_local(repo_dir, constants);
if ~preflight.pass
    error('stage8_k2_snr_run:Preflight', ...
        'STAGE8_K2_SNR_DOMAIN_VALIDATION_INVALID: %s', preflight.last_error);
end
if isfolder(runtime_root) || isfile(runtime_root)
    error('stage8_k2_snr_run:RuntimeExists', ...
        ['Formal runtime already exists. Remove only this exact uncommitted ', ...
        'runtime and restart from the beginning.']);
end
if ~mkdir(runtime_root)
    error('stage8_k2_snr_run:RuntimeCreate', ...
        'Unable to create the isolated formal runtime directory.');
end

total_clock = tic;
fprintf('Running ten registered tests...\n');
test_output = stage8_k2_snr_run_tests(repo_dir);
context = stage8_k2_snr_build_context(repo_dir);

fprintf('Phase A: reconstructing and auditing 72 original trials...\n');
phase_a_clock = tic;
audit_rows = cell(constants.trial_count, 1);
original_trials = cell(constants.trial_count, 1);
for index = 1:height(context.original_registry)
    spec = context.original_registry(index, :);
    trial = stage8_k2_snr_rebuild_original_trial(spec, context);
    metrics = stage8_k2_snr_compute_metrics(trial);
    original_trials{index} = trial;
    audit_rows{index} = audit_row_local(spec, trial, metrics);
    fprintf('Phase A %d/72 complete: %s\n', index, char(spec.trial_id));
end
audit = struct2table(vertcat(audit_rows{:}));
phase_a_runtime_sec = toc(phase_a_clock);
validate_phase_a_local(audit, context);
writetable(audit, fullfile(runtime_root, 'phase_a_original_snr_audit.csv'));
save(fullfile(runtime_root, 'phase_a_complete.mat'), 'audit', ...
    'phase_a_runtime_sec', '-mat');
fprintf('Phase A integrity PASS: 72/72 exact hashes.\n');

registry = stage8_k2_snr_build_white_control_registry(context);
fprintf('Phase B: running four registered smoke trials...\n');
smoke_clock = tic;
[smoke_rows, smoke_snr] = smoke_local(registry, context);
smoke_runtime_sec = toc(smoke_clock);
writetable(smoke_rows, fullfile(runtime_root, 'phase_b_smoke_method_rows.csv'));
writetable(smoke_snr, fullfile(runtime_root, 'phase_b_smoke_snr_rows.csv'));

fprintf('Phase B: running 72 paired white-control trials...\n');
phase_b_clock = tic;
method_blocks = cell(constants.trial_count, 1);
snr_rows = cell(constants.trial_count, 1);
for index = 1:height(registry)
    spec = registry(index, :);
    trial = stage8_k2_snr_generate_white_control_trial(spec, context);
    metrics = stage8_k2_snr_compute_metrics(trial);
    snr_rows{index} = white_snr_row_local(spec, trial, metrics);
    method_blocks{index} = stage8_k2_snr_evaluate_trial( ...
        spec, trial, metrics, context);
    fprintf('Phase B %d/72 complete: %s\n', index, char(spec.trial_id));
end
white_snr_trials = struct2table(vertcat(snr_rows{:}));
method_rows = vertcat(method_blocks{:});
phase_b_runtime_sec = toc(phase_b_clock);
registry.element_trial_hash = white_snr_trials.element_trial_hash;
validate_phase_b_local(registry, white_snr_trials, method_rows, context);
writetable(registry, fullfile(runtime_root, 'white_control_registry.csv'));
writetable(white_snr_trials, ...
    fullfile(runtime_root, 'white_control_snr_trials.csv'));
writetable(method_rows, ...
    fullfile(runtime_root, 'white_control_method_rows.csv'));
save(fullfile(runtime_root, 'phase_b_complete.mat'), 'registry', ...
    'white_snr_trials', 'method_rows', 'phase_b_runtime_sec', '-mat');

timing = struct('phase_a_runtime_sec', phase_a_runtime_sec, ...
    'smoke_runtime_sec', smoke_runtime_sec, ...
    'phase_b_runtime_sec', phase_b_runtime_sec, ...
    'total_runtime_sec', toc(total_clock));
output = stage8_k2_snr_summarize(audit, registry, white_snr_trials, ...
    method_rows, context, runtime_root, test_output, timing);
output.preflight = preflight;
output.timing = timing;
save(fullfile(runtime_root, 'complete_run.mat'), 'output', 'preflight', ...
    'test_output', 'timing', '-mat');
fprintf('STAGE8_K2_SNR_DOMAIN_VALIDATION_COMPLETE\n');
end

function row = audit_row_local(spec, trial, metrics)
row = struct('trial_id', string(spec.trial_id), ...
    'element_trial_hash', string(trial.element_trial_hash), ...
    'noise_profile_id', string(spec.noise_profile_id), ...
    'L', double(spec.L), 'profile_id', string(spec.profile_id), ...
    'original_element_snr_label_db', double(spec.snr_db));
row = append_fields_local(row, metrics);
end

function row = white_snr_row_local(spec, trial, metrics)
row = struct('trial_id', string(spec.trial_id), ...
    'paired_original_trial_id', string(spec.paired_original_trial_id), ...
    'global_trial_index', double(spec.global_trial_index), ...
    'element_trial_hash', string(trial.element_trial_hash), ...
    'noise_profile_id', string(spec.noise_profile_id), ...
    'L', double(spec.L), 'profile_id', string(spec.profile_id), ...
    'source_seed', double(spec.source_seed), ...
    'noise_seed', double(spec.noise_seed), ...
    'snr_control_domain', string(spec.snr_control_domain), ...
    'white_beamspace_snr_target_db', ...
    double(spec.white_beamspace_snr_target_db), ...
    'white_snr_scaling_relative_error', ...
    double(trial.white_snr_scaling_relative_error));
row = append_fields_local(row, metrics);
end

function row = append_fields_local(row, fields)
names = fieldnames(fields);
for index = 1:numel(names)
    row.(names{index}) = fields.(names{index});
end
end

function validate_phase_a_local(audit, context)
constants = context.constants;
if height(audit) ~= constants.trial_count || ...
        numel(unique(audit.trial_id)) ~= constants.trial_count || ...
        numel(unique(audit.element_trial_hash)) ~= constants.trial_count || ...
        any(abs(audit.element_snr_expected_db - ...
        audit.original_element_snr_label_db) > constants.snr_db_tolerance) || ...
        any(audit.raw_covariance_residual > ...
        constants.raw_covariance_tolerance) || ...
        any(audit.whitening_covariance_residual > ...
        constants.whitening_tolerance) || ...
        any(~audit.truth_only_diagnostic_flag) || ...
        any(audit.fitting_rerun_flag)
    error('stage8_k2_snr_run:PhaseAIntegrity', ...
        'STAGE8_K2_SNR_DOMAIN_VALIDATION_INVALID: Phase A failed.');
end
[found, positions] = ismember(audit.trial_id, ...
    context.frozen_trial_identity.trial_id);
if ~all(found) || any(audit.element_trial_hash ~= ...
        context.frozen_trial_identity.element_trial_hash(positions))
    error('stage8_k2_snr_run:PhaseAHash', ...
        'STAGE8_K2_SNR_DOMAIN_VALIDATION_INVALID: hashes are not 72/72.');
end
end

function [all_rows, all_snr] = smoke_local(registry, context)
selectors = ["P1", "WHITE"; "P2", "WHITE"; ...
    "P3", "STAGE5_TOEPLITZ_CORRELATED"; ...
    "P4", "STAGE5_TOEPLITZ_CORRELATED"];
row_blocks = cell(4, 1);
snr_blocks = cell(4, 1);
for index = 1:4
    selected = registry.profile_id == selectors(index, 1) & ...
        registry.noise_profile_id == selectors(index, 2) & ...
        registry.L == 4 & registry.white_beamspace_snr_target_db == 0;
    spec = registry(selected, :);
    if height(spec) ~= 1
        error('stage8_k2_snr_run:SmokeSelector', ...
            'A registered smoke selector is not unique.');
    end
    trial = stage8_k2_snr_generate_white_control_trial(spec, context);
    metrics = stage8_k2_snr_compute_metrics(trial);
    row_blocks{index} = stage8_k2_snr_evaluate_trial( ...
        spec, trial, metrics, context);
    snr_blocks{index} = struct2table( ...
        white_snr_row_local(spec, trial, metrics));
    tangent = row_blocks{index}( ...
        row_blocks{index}.method_id == "TANGENT_PROFILE_SAFE", :);
    if any(row_blocks{index}.fit_status == "NOT_RUN") || ...
            any(row_blocks{index}.truth_used_in_fit_flag) || ...
            height(tangent) ~= 1 || ~tangent.fit_valid || ...
            ~isfinite(tangent.RSS) || ~isfinite(tangent.loglik)
        error('stage8_k2_snr_run:SmokeFailure', ...
            'A smoke trial failed its explicit safe-result contract.');
    end
    fprintf('Smoke %d/4 PASS: %s\n', index, char(spec.trial_id));
end
all_rows = vertcat(row_blocks{:});
all_snr = vertcat(snr_blocks{:});
end

function validate_phase_b_local(registry, snr_rows, methods, context)
constants = context.constants;
if height(registry) ~= constants.trial_count || ...
        height(snr_rows) ~= constants.trial_count || ...
        height(methods) ~= constants.method_row_count || ...
        numel(unique(registry.element_trial_hash)) ~= constants.trial_count || ...
        numel(unique(methods.trial_id + "|" + methods.method_id)) ~= ...
        constants.method_row_count || ...
        any(abs(snr_rows.white_beam_snr_expected_db - ...
        snr_rows.white_beamspace_snr_target_db) > constants.snr_db_tolerance) || ...
        any(methods.truth_used_in_fit_flag)
    error('stage8_k2_snr_run:PhaseBIntegrity', ...
        'STAGE8_K2_SNR_DOMAIN_VALIDATION_INVALID: Phase B failed.');
end
for index = 1:height(registry)
    rows = methods(methods.trial_id == registry.trial_id(index), :);
    if height(rows) ~= numel(constants.method_ids) || ...
            numel(unique(rows.method_id)) ~= numel(constants.method_ids)
        error('stage8_k2_snr_run:MethodPairing', ...
            'A white-control trial lacks three unique method outcomes.');
    end
end
end

function audit = preflight_local(repo_dir, constants)
audit = struct('pass', false, 'last_error', '', 'branch', '', ...
    'head', '', 'remote', '', 'origin_main', '', 'origin_research', '', ...
    'worktree_clean', false, 'starting_commit_is_ancestor', false, ...
    'frozen_paths_clean', false);
try
    audit.branch = git_output_local(repo_dir, 'branch --show-current');
    audit.head = git_output_local(repo_dir, 'rev-parse HEAD');
    audit.remote = git_output_local(repo_dir, ...
        'rev-parse origin/experiment/stage8-k2-tangent');
    audit.origin_main = git_output_local(repo_dir, 'rev-parse origin/main');
    audit.origin_research = git_output_local(repo_dir, ...
        'rev-parse origin/research/stage8-k2-vincent-anchored');
    audit.worktree_clean = isempty(git_output_local(repo_dir, ...
        'status --porcelain=v1 --untracked-files=all'));
    audit.starting_commit_is_ancestor = git_status_local(repo_dir, sprintf( ...
        'merge-base --is-ancestor %s HEAD', constants.starting_commit));
    frozen_commands = { ...
        sprintf('diff --quiet %s -- tools/stage8_k2_tangent_profile', ...
        constants.starting_commit), ...
        sprintf('diff --quiet %s -- tools/stage8_k2_classical_baselines', ...
        constants.starting_commit), ...
        sprintf('diff --quiet %s -- tools/stage8_k2_subspace_baselines', ...
        constants.starting_commit), ...
        sprintf('diff --quiet %s -- beamspace_ml_v18', ...
        constants.starting_commit), ...
        sprintf('diff --quiet %s -- ":(glob)innovation-mining/31_*"', ...
        constants.starting_commit), ...
        sprintf('diff --quiet %s -- ":(glob)innovation-mining/32_*"', ...
        constants.starting_commit), ...
        sprintf('diff --quiet %s -- ":(glob)innovation-mining/33_*"', ...
        constants.starting_commit), ...
        sprintf('diff --quiet %s -- ":(glob)innovation-mining/34_*"', ...
        constants.starting_commit), ...
        sprintf('diff --quiet %s -- ":(glob)innovation-mining/39_*"', ...
        constants.starting_commit), ...
        sprintf('diff --quiet %s -- ":(glob)innovation-mining/40_*"', ...
        constants.starting_commit)};
    audit.frozen_paths_clean = all(cellfun( ...
        @(command) git_status_local(repo_dir, command), frozen_commands));
    checks = strcmp(audit.branch, constants.branch) && ...
        strcmp(audit.head, audit.remote) && ...
        strcmp(audit.origin_main, constants.expected_origin_main) && ...
        strcmp(audit.origin_research, constants.expected_origin_research) && ...
        audit.worktree_clean && audit.starting_commit_is_ancestor && ...
        audit.frozen_paths_clean;
    if ~checks
        error('Branch, remote, immutable refs, clean tree, or frozen scope failed.');
    end
    audit.pass = true;
catch exception
    audit.last_error = exception.message;
end
end

function output = git_output_local(repo_dir, arguments)
[status, output] = system(sprintf('git -C "%s" %s', repo_dir, arguments));
if status ~= 0
    error('stage8_k2_snr_run:Git', 'Git command failed: %s', arguments);
end
output = strtrim(output);
end

function pass = git_status_local(repo_dir, arguments)
[status, ~] = system(sprintf('git -C "%s" %s', repo_dir, arguments));
pass = status == 0;
end
