function metrics = stage8_k2_snr_compute_metrics(trial)
%STAGE8_K2_SNR_COMPUTE_METRICS Compute element, raw, white, and K2 SNRs.

required = {'signal_element','noise_element','truth_angles_deg','model'};
if ~(isstruct(trial) && isscalar(trial) && all(isfield(trial, required)))
    error('stage8_k2_snr_compute_metrics:Trial', ...
        'trial is missing a signal, noise, truth, or model field.');
end
signal = trial.signal_element;
noise = trial.noise_element;
model = trial.model;
L = size(signal, 2);
if ~isequal(size(signal), size(noise)) || ...
        size(signal, 1) ~= size(model.W_I, 1)
    error('stage8_k2_snr_compute_metrics:Shape', ...
        'Signal and noise must share the frozen element shape.');
end
C_b_from_element = model.W_I' * model.Rn_elem * model.W_I;
raw_covariance_residual = norm(model.C_I - C_b_from_element, 'fro') / ...
    max(1, norm(model.C_I, 'fro'));
C_b = model.C_I;
C_w = model.T_I * C_b * model.T_I';
r = model.whitening_rank;
whitening_covariance_residual = norm(C_w - eye(r), 'fro') / sqrt(r);

signal_raw = model.W_I' * signal;
noise_raw = model.W_I' * noise;
signal_white = model.T_I * signal_raw;
noise_white = model.T_I * noise_raw;
element_signal_energy = norm(signal, 'fro') ^ 2;
element_expected_noise = L * real(trace(model.Rn_elem));
element_realized_noise = norm(noise, 'fro') ^ 2;
raw_signal_energy = norm(signal_raw, 'fro') ^ 2;
raw_expected_noise = L * real(trace(C_b));
raw_realized_noise = norm(noise_raw, 'fro') ^ 2;
white_signal_energy = norm(signal_white, 'fro') ^ 2;
white_expected_noise = L * real(trace(C_w));
white_realized_noise = norm(noise_white, 'fro') ^ 2;

element_expected_db = ratio_db_local(element_signal_energy, ...
    element_expected_noise);
raw_expected_db = ratio_db_local(raw_signal_energy, raw_expected_noise);
white_expected_db = ratio_db_local(white_signal_energy, white_expected_noise);
beam_denominators = L * real(diag(C_b));
beam_numerators = sum(abs(signal_raw) .^ 2, 2);
beam_snr = beam_numerators ./ beam_denominators;
[peak_snr, peak_index] = max(beam_snr);
projected = stage8_k2_snr_projected_k2_metric( ...
    signal_white, noise_white, C_w, trial.truth_angles_deg, model);

metrics = struct( ...
    'N_element', size(signal, 1), ...
    'raw_beam_count', size(model.W_I, 2), ...
    'whitening_rank', r, ...
    'element_signal_energy', element_signal_energy, ...
    'element_noise_expected_energy', element_expected_noise, ...
    'element_noise_realized_energy', element_realized_noise, ...
    'element_snr_expected_db', element_expected_db, ...
    'element_snr_realized_db', ratio_db_local(element_signal_energy, ...
    element_realized_noise), ...
    'raw_beam_signal_energy', raw_signal_energy, ...
    'raw_beam_noise_expected_energy', raw_expected_noise, ...
    'raw_beam_noise_realized_energy', raw_realized_noise, ...
    'raw_beam_snr_expected_db', raw_expected_db, ...
    'raw_beam_snr_realized_db', ratio_db_local(raw_signal_energy, ...
    raw_realized_noise), ...
    'white_beam_signal_energy', white_signal_energy, ...
    'white_beam_noise_expected_energy', white_expected_noise, ...
    'white_beam_noise_realized_energy', white_realized_noise, ...
    'white_beam_snr_expected_db', white_expected_db, ...
    'white_beam_snr_realized_db', ratio_db_local(white_signal_energy, ...
    white_realized_noise), ...
    'raw_receive_gain_db', raw_expected_db - element_expected_db, ...
    'white_receive_gain_db', white_expected_db - element_expected_db, ...
    'raw_peak_beam_index', peak_index, ...
    'raw_peak_beam_snr_expected_db', 10 * log10(peak_snr), ...
    'raw_median_beam_snr_expected_db', 10 * log10(median(beam_snr)), ...
    'true_center_projected_signal_energy', projected.signal_energy, ...
    'true_center_projected_noise_expected_energy', ...
    projected.noise_expected_energy, ...
    'true_center_projected_noise_realized_energy', ...
    projected.noise_realized_energy, ...
    'k2_projected_snr_expected_db', projected.snr_expected_db, ...
    'k2_projected_snr_realized_db', projected.snr_realized_db, ...
    'raw_covariance_residual', raw_covariance_residual, ...
    'whitening_covariance_residual', whitening_covariance_residual, ...
    'whitening_trace', real(trace(C_w)), ...
    'truth_only_diagnostic_flag', true, ...
    'fitting_rerun_flag', false);
end

function value = ratio_db_local(numerator, denominator)
if denominator > 0 && numerator > 0
    value = 10 * log10(numerator / denominator);
elseif denominator > 0 && numerator == 0
    value = -Inf;
else
    value = NaN;
end
end
