function output = stage8_k2_snr_summarize( ...
    audit, registry, white_snr_trials, method_rows, context, ...
    runtime_root, test_output, timing)
%STAGE8_K2_SNR_SUMMARIZE Validate and write the registered evidence bundle.

constants = context.constants;
validate_inputs_local(audit, registry, white_snr_trials, method_rows, constants);
phase_a_summary = phase_a_summary_local(audit);
phase_b_summary = phase_b_summary_local(method_rows, constants);
comparison = comparison_local(audit, method_rows, context);
evidence_dir = fullfile(context.repo_dir, 'innovation-mining');
paths = struct( ...
    'audit_trials', fullfile(evidence_dir, ...
    '42_stage8_k2_original_snr_audit_trials.csv'), ...
    'audit_summary', fullfile(evidence_dir, ...
    '42_stage8_k2_original_snr_audit_summary.csv'), ...
    'white_registry', fullfile(evidence_dir, ...
    '42_stage8_k2_white_beamspace_control_registry.csv'), ...
    'white_snr_trials', fullfile(evidence_dir, ...
    '42_stage8_k2_white_beamspace_control_snr_trials.csv'), ...
    'method_results', fullfile(evidence_dir, ...
    '42_stage8_k2_white_beamspace_control_method_results.csv'), ...
    'white_summary', fullfile(evidence_dir, ...
    '42_stage8_k2_white_beamspace_control_summary.csv'), ...
    'comparison', fullfile(evidence_dir, ...
    '42_stage8_k2_snr_control_comparison.csv'), ...
    'report', fullfile(evidence_dir, ...
    '42_stage8_k2_snr_domain_validation.md'), ...
    'manifest', fullfile(evidence_dir, ...
    '42_stage8_k2_snr_runtime_manifest.json'));

writetable(audit, paths.audit_trials);
writetable(phase_a_summary, paths.audit_summary);
writetable(registry, paths.white_registry);
writetable(white_snr_trials, paths.white_snr_trials);
writetable(method_rows, paths.method_results);
writetable(phase_b_summary, paths.white_summary);
writetable(comparison, paths.comparison);
write_report_local(paths.report, audit, registry, ...
    phase_b_summary, constants, timing);

artifact_names = { ...
    'audit_trials','audit_summary','white_registry','white_snr_trials', ...
    'method_results','white_summary','comparison','report'};
artifacts = repmat(struct('artifact_id', '', 'path', '', 'sha256', ''), ...
    numel(artifact_names), 1);
for index = 1:numel(artifact_names)
    name = artifact_names{index};
    artifacts(index) = struct('artifact_id', name, ...
        'path', relative_path_local(paths.(name), context.repo_dir), ...
        'sha256', stage8_k2_snr_file_sha256(paths.(name)));
end
manifest = struct( ...
    'status', 'STAGE8_K2_SNR_DOMAIN_VALIDATION_COMPLETE', ...
    'protocol', constants.protocol, 'authorization', constants.authorization, ...
    'branch', constants.branch, 'starting_head', constants.starting_commit, ...
    'prompt_commit', git_output_local(context.repo_dir, ...
    'log -1 --format=%H --grep="docs(stage8-k2): define SNR domain validation"'), ...
    'tool_commit', git_output_local(context.repo_dir, ...
    'log -1 --format=%H --grep="analysis(stage8-k2): add beamspace SNR audit and control"'), ...
    'formal_run_head', git_output_local(context.repo_dir, 'rev-parse HEAD'), ...
    'matlab_release', version('-release'), ...
    'max_computational_threads', maxNumCompThreads, ...
    'runtime_root', runtime_root, ...
    'test_count', test_output.test_count, ...
    'original_hash_match_count', constants.trial_count, ...
    'white_registry_count', height(registry), ...
    'white_unique_hash_count', numel(unique(registry.element_trial_hash)), ...
    'method_row_count', height(method_rows), ...
    'truth_leakage_count', nnz(method_rows.truth_used_in_fit_flag), ...
    'max_white_target_error_db', max(abs( ...
    white_snr_trials.white_beam_snr_expected_db - ...
    white_snr_trials.white_beamspace_snr_target_db)), ...
    'phase_a_runtime_sec', timing.phase_a_runtime_sec, ...
    'smoke_runtime_sec', timing.smoke_runtime_sec, ...
    'phase_b_runtime_sec', timing.phase_b_runtime_sec, ...
    'total_runtime_sec', timing.total_runtime_sec, ...
    'tangent_algorithm_modified', false, 'whitening_removed', false, ...
    'monte_carlo_executed', false, ...
    'next_monte_carlo_authorized', false, ...
    'artifacts', artifacts);
write_json_local(paths.manifest, manifest);
copy_runtime_evidence_local(paths, runtime_root);
output = struct('status', manifest.status, 'phase_a_summary', phase_a_summary, ...
    'phase_b_summary', phase_b_summary, 'comparison', comparison, ...
    'manifest', manifest, 'evidence_paths', paths);
end

function validate_inputs_local(audit, registry, white_snr, methods, constants)
if height(audit) ~= constants.trial_count || ...
        height(registry) ~= constants.trial_count || ...
        height(white_snr) ~= constants.trial_count || ...
        height(methods) ~= constants.method_row_count || ...
        numel(unique(audit.trial_id)) ~= constants.trial_count || ...
        numel(unique(registry.trial_id)) ~= constants.trial_count || ...
        numel(unique(registry.element_trial_hash)) ~= constants.trial_count || ...
        numel(unique(methods.trial_id + "|" + methods.method_id)) ~= ...
        constants.method_row_count
    error('stage8_k2_snr_summarize:Cardinality', ...
        'Result rows are missing, duplicated, or have nonunique hashes.');
end
if any(methods.truth_used_in_fit_flag) || ...
        any(~isfinite(white_snr.white_beam_snr_expected_db)) || ...
        any(abs(white_snr.white_beam_snr_expected_db - ...
        white_snr.white_beamspace_snr_target_db) > constants.snr_db_tolerance)
    error('stage8_k2_snr_summarize:Integrity', ...
        'Truth isolation or expected-white-SNR integrity failed.');
end
valid = methods.fit_valid;
if any(valid & (~isfinite(methods.RSS) | ~isfinite(methods.loglik) | ...
        ~isfinite(methods.joint_RMSE_deg)))
    error('stage8_k2_snr_summarize:FiniteValidRows', ...
        'A valid method row contains a nonfinite registered output.');
end
end

function summary = phase_a_summary_local(audit)
scopes = scopes_local(audit, 'original_element_snr_label_db');
rows = repmat(phase_a_template_local(), numel(scopes), 1);
for index = 1:numel(scopes)
    subset = audit(scopes(index).mask, :);
    row = phase_a_template_local();
    row.scope_type = scopes(index).type;
    row.scope_value = scopes(index).value;
    row.N = height(subset);
    row.element_expected_snr_median_db = finite_stat_local( ...
        subset.element_snr_expected_db, 'median');
    row.element_expected_snr_min_db = finite_stat_local( ...
        subset.element_snr_expected_db, 'min');
    row.element_expected_snr_max_db = finite_stat_local( ...
        subset.element_snr_expected_db, 'max');
    row.element_realized_snr_median_db = finite_stat_local( ...
        subset.element_snr_realized_db, 'median');
    row.element_realized_snr_p90_db = percentile_local( ...
        subset.element_snr_realized_db, 90);
    row.raw_expected_snr_median_db = finite_stat_local( ...
        subset.raw_beam_snr_expected_db, 'median');
    row.raw_expected_snr_min_db = finite_stat_local( ...
        subset.raw_beam_snr_expected_db, 'min');
    row.raw_expected_snr_max_db = finite_stat_local( ...
        subset.raw_beam_snr_expected_db, 'max');
    row.white_expected_snr_median_db = finite_stat_local( ...
        subset.white_beam_snr_expected_db, 'median');
    row.white_expected_snr_min_db = finite_stat_local( ...
        subset.white_beam_snr_expected_db, 'min');
    row.white_expected_snr_max_db = finite_stat_local( ...
        subset.white_beam_snr_expected_db, 'max');
    row.raw_peak_beam_snr_median_db = finite_stat_local( ...
        subset.raw_peak_beam_snr_expected_db, 'median');
    row.raw_peak_beam_snr_p90_db = percentile_local( ...
        subset.raw_peak_beam_snr_expected_db, 90);
    row.white_receive_gain_median_db = finite_stat_local( ...
        subset.white_receive_gain_db, 'median');
    row.white_receive_gain_min_db = finite_stat_local( ...
        subset.white_receive_gain_db, 'min');
    row.white_receive_gain_max_db = finite_stat_local( ...
        subset.white_receive_gain_db, 'max');
    row.k2_projected_expected_snr_median_db = finite_stat_local( ...
        subset.k2_projected_snr_expected_db, 'median');
    row.k2_projected_expected_snr_p90_db = percentile_local( ...
        subset.k2_projected_snr_expected_db, 90);
    rows(index) = row;
end
summary = struct2table(rows);
end

function row = phase_a_template_local()
row = struct('scope_type', "", 'scope_value', "", 'N', 0, ...
    'element_expected_snr_median_db', NaN, ...
    'element_expected_snr_min_db', NaN, ...
    'element_expected_snr_max_db', NaN, ...
    'element_realized_snr_median_db', NaN, ...
    'element_realized_snr_p90_db', NaN, ...
    'raw_expected_snr_median_db', NaN, ...
    'raw_expected_snr_min_db', NaN, 'raw_expected_snr_max_db', NaN, ...
    'white_expected_snr_median_db', NaN, ...
    'white_expected_snr_min_db', NaN, ...
    'white_expected_snr_max_db', NaN, ...
    'raw_peak_beam_snr_median_db', NaN, ...
    'raw_peak_beam_snr_p90_db', NaN, ...
    'white_receive_gain_median_db', NaN, ...
    'white_receive_gain_min_db', NaN, ...
    'white_receive_gain_max_db', NaN, ...
    'k2_projected_expected_snr_median_db', NaN, ...
    'k2_projected_expected_snr_p90_db', NaN);
end

function summary = phase_b_summary_local(method_rows, constants)
scopes = scopes_local(method_rows, 'white_beamspace_snr_target_db');
rows = repmat(phase_b_template_local(), 0, 1);
for scope_index = 1:numel(scopes)
    scope = scopes(scope_index);
    for method_index = 1:numel(constants.method_ids)
        method_id = constants.method_ids(method_index);
        subset = method_rows(scope.mask & method_rows.method_id == method_id, :);
        valid = subset.fit_valid;
        row = phase_b_template_local();
        row.row_type = "METHOD";
        row.scope_type = scope.type;
        row.scope_value = scope.value;
        row.method_id = method_id;
        row.total_count = height(subset);
        row.valid_count = nnz(valid);
        row.valid_rate = nnz(valid) / max(1, height(subset));
        row = assign_method_stats_local(row, subset, valid);
        rows(end + 1, 1) = row; %#ok<AGROW>
    end
    for reference = ["CORE_LITE", "CORE_PLUS"]
        tangent = method_rows(scope.mask & ...
            method_rows.method_id == "TANGENT_PROFILE_SAFE", :);
        baseline = method_rows(scope.mask & method_rows.method_id == reference, :);
        tangent = sortrows(tangent, 'trial_id');
        baseline = sortrows(baseline, 'trial_id');
        if height(tangent) ~= height(baseline) || ...
                any(tangent.trial_id ~= baseline.trial_id)
            error('stage8_k2_snr_summarize:Pairing', ...
                'A paired method comparison lost trial identity.');
        end
        common = tangent.fit_valid & baseline.fit_valid & ...
            isfinite(tangent.joint_RMSE_deg) & ...
            isfinite(baseline.joint_RMSE_deg);
        delta = tangent.joint_RMSE_deg(common) - ...
            baseline.joint_RMSE_deg(common);
        row = phase_b_template_local();
        row.row_type = "PAIRWISE";
        row.scope_type = scope.type;
        row.scope_value = scope.value;
        row.method_id = "TANGENT_PROFILE_SAFE";
        row.reference_method_id = reference;
        row.comparison_id = "TANGENT_VS_" + reference;
        row.paired_count = nnz(common);
        row.wins = nnz(delta < -constants.paired_tie_tolerance_deg);
        row.ties = nnz(abs(delta) <= constants.paired_tie_tolerance_deg);
        row.losses = nnz(delta > constants.paired_tie_tolerance_deg);
        rows(end + 1, 1) = row; %#ok<AGROW>
    end
end
summary = struct2table(rows);
end

function row = assign_method_stats_local(row, subset, valid)
metric_names = {'joint_RMSE_deg','center_error_deg', ...
    'direction_axis_error_deg','rho_error_deg','rho_relative_error', ...
    'separation_vector_error_deg','runtime_sec'};
prefixes = {'joint_RMSE_deg','center_error_deg', ...
    'axis_error_deg','rho_error_deg','rho_relative_error', ...
    'separation_vector_error_deg','runtime_sec'};
for index = 1:numel(metric_names)
    values = subset.(metric_names{index})(valid);
    row.(['median_', prefixes{index}]) = finite_stat_local(values, 'median');
    row.(['p90_', prefixes{index}]) = percentile_local(values, 90);
end
row.upgrade_rate = mean(double(subset.upgrade_flag));
row.fallback_rate = mean(double(subset.fallback_flag));
row.mean_score_call_count = mean(double(subset.score_call_count));
row.mean_SVD_call_count = mean(double(subset.SVD_call_count));
row.resulting_element_snr_median_db = finite_stat_local( ...
    subset.element_snr_expected_db, 'median');
row.resulting_element_snr_min_db = finite_stat_local( ...
    subset.element_snr_expected_db, 'min');
row.resulting_element_snr_max_db = finite_stat_local( ...
    subset.element_snr_expected_db, 'max');
row.realized_white_snr_median_db = finite_stat_local( ...
    subset.white_beam_snr_realized_db, 'median');
row.realized_white_snr_p90_db = percentile_local( ...
    subset.white_beam_snr_realized_db, 90);
end

function row = phase_b_template_local()
row = struct('row_type', "", 'scope_type', "", 'scope_value', "", ...
    'method_id', "", 'reference_method_id', "", ...
    'total_count', 0, 'valid_count', 0, 'valid_rate', NaN, ...
    'median_joint_RMSE_deg', NaN, 'p90_joint_RMSE_deg', NaN, ...
    'median_center_error_deg', NaN, 'p90_center_error_deg', NaN, ...
    'median_axis_error_deg', NaN, 'p90_axis_error_deg', NaN, ...
    'median_rho_error_deg', NaN, 'p90_rho_error_deg', NaN, ...
    'median_rho_relative_error', NaN, 'p90_rho_relative_error', NaN, ...
    'median_separation_vector_error_deg', NaN, ...
    'p90_separation_vector_error_deg', NaN, ...
    'upgrade_rate', NaN, 'fallback_rate', NaN, ...
    'mean_score_call_count', NaN, 'mean_SVD_call_count', NaN, ...
    'median_runtime_sec', NaN, 'p90_runtime_sec', NaN, ...
    'resulting_element_snr_median_db', NaN, ...
    'resulting_element_snr_min_db', NaN, ...
    'resulting_element_snr_max_db', NaN, ...
    'realized_white_snr_median_db', NaN, ...
    'realized_white_snr_p90_db', NaN, ...
    'comparison_id', "", 'paired_count', 0, ...
    'wins', 0, 'ties', 0, 'losses', 0);
end

function comparison = comparison_local(audit, method_rows, context)
rows = repmat(comparison_template_local(), 0, 1);
labels = context.constants.white_snr_targets_db;
methods = context.constants.method_ids;
for label = labels
    for method_index = 1:numel(methods)
        method_id = methods(method_index);
        frozen = context.frozen_method_rows( ...
            context.frozen_method_rows.snr_db == label & ...
            context.frozen_method_rows.method_id == method_id, :);
        [found, positions] = ismember(frozen.trial_id, audit.trial_id);
        if ~all(found)
            error('stage8_k2_snr_summarize:OriginalJoin', ...
                'Evidence 31 could not be joined to the Phase A audit.');
        end
        joined = audit(positions, :);
        row = comparison_template_local();
        row.experiment_id = "ORIGINAL_ELEMENT_CONTROL";
        row.control_domain = "ELEMENT_INPUT_EXPECTED_TOTAL_SNR";
        row.numeric_snr_label_db = label;
        row.method_id = method_id;
        row.trial_count = height(frozen);
        row.valid_rate = mean(double(frozen.fit_valid));
        row.element_snr_expected_median_db = median( ...
            joined.element_snr_expected_db);
        row.element_snr_expected_min_db = min(joined.element_snr_expected_db);
        row.element_snr_expected_max_db = max(joined.element_snr_expected_db);
        row.white_snr_expected_median_db = median( ...
            joined.white_beam_snr_expected_db);
        row.white_snr_expected_min_db = min(joined.white_beam_snr_expected_db);
        row.white_snr_expected_max_db = max(joined.white_beam_snr_expected_db);
        valid = logical(frozen.fit_valid);
        row.joint_RMSE_median_deg = finite_stat_local( ...
            frozen.joint_RMSE_deg(valid), 'median');
        row.joint_RMSE_p90_deg = percentile_local( ...
            frozen.joint_RMSE_deg(valid), 90);
        row.interpretation_note = ...
            "HISTORICAL_LABEL_CONTROLS_ELEMENT_INPUT_SNR";
        rows(end + 1, 1) = row; %#ok<AGROW>

        current = method_rows( ...
            method_rows.white_beamspace_snr_target_db == label & ...
            method_rows.method_id == method_id, :);
        row = comparison_template_local();
        row.experiment_id = "PAIRED_WHITE_BEAMSPACE_CONTROL";
        row.control_domain = string(context.constants.control_domain);
        row.numeric_snr_label_db = label;
        row.method_id = method_id;
        row.trial_count = height(current);
        row.valid_rate = mean(double(current.fit_valid));
        row.element_snr_expected_median_db = median( ...
            current.element_snr_expected_db);
        row.element_snr_expected_min_db = min(current.element_snr_expected_db);
        row.element_snr_expected_max_db = max(current.element_snr_expected_db);
        row.white_snr_expected_median_db = median( ...
            current.white_beam_snr_expected_db);
        row.white_snr_expected_min_db = min(current.white_beam_snr_expected_db);
        row.white_snr_expected_max_db = max(current.white_beam_snr_expected_db);
        valid = current.fit_valid;
        row.joint_RMSE_median_deg = finite_stat_local( ...
            current.joint_RMSE_deg(valid), 'median');
        row.joint_RMSE_p90_deg = percentile_local( ...
            current.joint_RMSE_deg(valid), 90);
        row.interpretation_note = ...
            "LABEL_CONTROLS_EXPECTED_WHITENED_BEAMSPACE_SNR";
        rows(end + 1, 1) = row; %#ok<AGROW>
    end
end
comparison = struct2table(rows);
end

function row = comparison_template_local()
row = struct('experiment_id', "", 'control_domain', "", ...
    'numeric_snr_label_db', NaN, 'method_id', "", 'trial_count', 0, ...
    'valid_rate', NaN, 'element_snr_expected_median_db', NaN, ...
    'element_snr_expected_min_db', NaN, ...
    'element_snr_expected_max_db', NaN, ...
    'white_snr_expected_median_db', NaN, ...
    'white_snr_expected_min_db', NaN, ...
    'white_snr_expected_max_db', NaN, ...
    'joint_RMSE_median_deg', NaN, 'joint_RMSE_p90_deg', NaN, ...
    'interpretation_note', "");
end

function scopes = scopes_local(table_now, snr_name)
scopes = repmat(struct('type', "", 'value', "", 'mask', false(0, 1)), 0, 1);
scopes(end + 1) = struct('type', "ALL", 'value', "ALL", ...
    'mask', true(height(table_now), 1));
snr_values = unique(table_now.(snr_name), 'stable');
for value = reshape(snr_values, 1, [])
    scopes(end + 1) = struct('type', "SNR", 'value', string(value), ...
        'mask', table_now.(snr_name) == value); %#ok<AGROW>
end
for value = reshape(unique(table_now.profile_id, 'stable'), 1, [])
    scopes(end + 1) = struct('type', "PROFILE", 'value', value, ...
        'mask', table_now.profile_id == value); %#ok<AGROW>
end
for value = reshape(unique(table_now.noise_profile_id, 'stable'), 1, [])
    scopes(end + 1) = struct('type', "NOISE", 'value', value, ...
        'mask', table_now.noise_profile_id == value); %#ok<AGROW>
end
for value = reshape(unique(table_now.L, 'stable'), 1, [])
    scopes(end + 1) = struct('type', "L", 'value', string(value), ...
        'mask', table_now.L == value); %#ok<AGROW>
end
for snr = reshape(snr_values, 1, [])
    for profile = reshape(unique(table_now.profile_id, 'stable'), 1, [])
        scopes(end + 1) = struct('type', "SNR_X_PROFILE", ...
            'value', string(snr) + "|" + profile, ...
            'mask', table_now.(snr_name) == snr & ...
            table_now.profile_id == profile); %#ok<AGROW>
    end
    for noise = reshape(unique(table_now.noise_profile_id, 'stable'), 1, [])
        scopes(end + 1) = struct('type', "SNR_X_NOISE", ...
            'value', string(snr) + "|" + noise, ...
            'mask', table_now.(snr_name) == snr & ...
            table_now.noise_profile_id == noise); %#ok<AGROW>
    end
end
end

function write_report_local(path_now, audit, registry, summary, constants, timing)
fid = fopen(path_now, 'w');
if fid < 0
    error('stage8_k2_snr_summarize:ReportOpen', ...
        'Unable to open the validation report.');
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# Stage8 K2 SNR Domain Validation\n\n');
fprintf(fid, 'Status: `STAGE8_K2_SNR_DOMAIN_VALIDATION_COMPLETE`\n\n');
fprintf(fid, 'Protocol: `%s`\n\n', constants.protocol);
fprintf(fid, '## Integrity\n\n');
fprintf(fid, '- Original element hashes: `72/72 exact`.\n');
fprintf(fid, '- White-control registry: `72/72`, unique hashes: `72/72`.\n');
fprintf(fid, '- Method rows: `216/216`; truth leakage: `0`.\n');
fprintf(fid, '- Maximum white-target error: `%.3g dB`.\n', max(abs( ...
    registry.resulting_white_beamspace_snr_expected_db - ...
    registry.white_beamspace_snr_target_db)));
fprintf(fid, '- Maximum raw covariance residual: `%.3g`.\n', ...
    max(audit.raw_covariance_residual));
fprintf(fid, '- Maximum whitening residual: `%.3g`.\n\n', ...
    max(audit.whitening_covariance_residual));
fprintf(fid, '## Original element-SNR mapping\n\n');
fprintf(fid, '| Element label (dB) | White SNR min | median | max |\n');
fprintf(fid, '|---:|---:|---:|---:|\n');
for label = constants.white_snr_targets_db
    rows = audit(audit.original_element_snr_label_db == label, :);
    fprintf(fid, '| %g | %.6f | %.6f | %.6f |\n', label, ...
        min(rows.white_beam_snr_expected_db), ...
        median(rows.white_beam_snr_expected_db), ...
        max(rows.white_beam_snr_expected_db));
end
fprintf(fid, '\nOverall raw peak-beam expected SNR: median `%.6f dB`, ', ...
    median(audit.raw_peak_beam_snr_expected_db));
fprintf(fid, 'p90 `%.6f dB`. Overall white receive gain: median ', ...
    percentile_local(audit.raw_peak_beam_snr_expected_db, 90));
fprintf(fid, '`%.6f dB`, range `[%.6f, %.6f] dB`.\n\n', ...
    median(audit.white_receive_gain_db), min(audit.white_receive_gain_db), ...
    max(audit.white_receive_gain_db));
fprintf(fid, '## White-beamspace-controlled results\n\n');
fprintf(fid, '| Method | Valid rate | Joint RMSE median | p90 | Fallback rate | Runtime median (s) |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|\n');
for method = reshape(constants.method_ids, 1, [])
    row = summary(summary.row_type == "METHOD" & ...
        summary.scope_type == "ALL" & summary.method_id == method, :);
    fprintf(fid, '| %s | %.6f | %.6f | %.6f | %.6f | %.6f |\n', ...
        char(method), row.valid_rate, row.median_joint_RMSE_deg, ...
        row.p90_joint_RMSE_deg, row.fallback_rate, row.median_runtime_sec);
end
fprintf(fid, ['\nDetailed `-6/0/+6 dB`, P1-P4, noise, L, geometry, ', ...
    'fallback, cost, and runtime rows are recorded in the summary CSV.\n\n']);
fprintf(fid, '## Interpretation\n\n');
fprintf(fid, ['The original numeric label controls expected total-energy SNR ', ...
    'at the element input. The paired experiment controls expected ', ...
    'total-energy SNR after the frozen sequential measurement and ', ...
    'whitener. Equal numeric labels do not represent equal input-energy ', ...
    'conditions, so they are not used to claim that an SNR definition ', ...
    'improves or degrades an algorithm.\n\n']);
fprintf(fid, ['All registered complex beams are formed from the same ', ...
    '`Y_element`; this is not a temporal scan. The SNRs are internal ', ...
    'receive-estimation coordinates and exclude transmit broad-beam loss, ', ...
    'RCS/range/radar equation, CFAR, range-Doppler detection, CPI pulse ', ...
    'integration, unknown K, and tracking. Whitening remains unchanged and ', ...
    'defines the correct noise geometry.\n\n']);
fprintf(fid, '## Statistical boundary\n\n');
fprintf(fid, ['Each factor cell has one source/noise realization. This is ', ...
    'an SNR-definition audit and paired reparameterization experiment, not ', ...
    'a statistically sufficient Monte Carlo study. It cannot establish ', ...
    'confidence intervals, stable P90 behavior, or outlier probabilities. ', ...
    'No 800/1200-trial Monte Carlo run was executed or authorized.\n\n']);
fprintf(fid, 'Runtime: Phase A `%.3f s`, smoke `%.3f s`, Phase B `%.3f s`, total `%.3f s`.\n\n', ...
    timing.phase_a_runtime_sec, timing.smoke_runtime_sec, ...
    timing.phase_b_runtime_sec, timing.total_runtime_sec);
fprintf(fid, 'Default K2 remains `TANGENT_PROFILE_SAFE`; Tangent is frozen.\n');
clear cleanup
end

function write_json_local(path_now, value)
fid = fopen(path_now, 'w');
if fid < 0
    error('stage8_k2_snr_summarize:ManifestOpen', ...
        'Unable to open the runtime manifest.');
end
cleanup = onCleanup(@() fclose(fid));
encoded = jsonencode(value, 'PrettyPrint', true);
fwrite(fid, encoded, 'char');
fwrite(fid, newline, 'char');
clear cleanup
end

function copy_runtime_evidence_local(paths, runtime_root)
names = fieldnames(paths);
for index = 1:numel(names)
    source = paths.(names{index});
    [~, name, extension] = fileparts(source);
    destination = fullfile(runtime_root, [name, extension]);
    [ok, message] = copyfile(source, destination, 'f');
    if ~ok
        error('stage8_k2_snr_summarize:RuntimeEvidence', '%s', message);
    end
end
end

function value = finite_stat_local(values, operation)
values = double(values(isfinite(values)));
if isempty(values)
    value = NaN;
else
    value = feval(operation, values);
end
end

function value = percentile_local(values, percentile)
values = sort(double(values(isfinite(values))));
if isempty(values)
    value = NaN;
elseif numel(values) == 1
    value = values(1);
else
    position = 1 + (numel(values) - 1) * percentile / 100;
    lower_index = floor(position);
    upper_index = ceil(position);
    weight = position - lower_index;
    value = (1 - weight) * values(lower_index) + ...
        weight * values(upper_index);
end
end

function relative = relative_path_local(path_now, repo_dir)
prefix = [char(java.io.File(repo_dir).getCanonicalPath()), filesep];
canonical = char(java.io.File(path_now).getCanonicalPath());
if startsWith(lower(canonical), lower(prefix))
    relative = strrep(canonical(numel(prefix) + 1:end), filesep, '/');
else
    relative = canonical;
end
end

function output = git_output_local(repo_dir, arguments)
[status, output] = system(sprintf('git -C "%s" %s', repo_dir, arguments));
if status ~= 0
    error('stage8_k2_snr_summarize:Git', ...
        'Git command failed: %s', arguments);
end
output = strtrim(output);
end
