function registry = build_stage8_core_v2_2_final_registry(local_domain)
%BUILD_STAGE8_CORE_V2_2_FINAL_REGISTRY Fixed 72 K1 plus 72 K2 registry.

if nargin < 1 || isempty(local_domain)
    bounds = [7.4, 8.6, 9.6, 10.4];
else
    bounds = local_domain.domain_bounds_deg;
end
noise_ids = ["WHITE"; "STAGE5_TOEPLITZ_CORRELATED"];
k1_profiles = { ...
    'C1_ON_GRID', [8.00, 10.00]; ...
    'C2_OFF_GRID_NE', [8.10, 10.10]; ...
    'C3_OFF_GRID_SW', [7.90, 9.90]; ...
    'C4_NEAR_CELL_EDGE', [8.45, 10.15]};
k2_profiles = { ...
    'P1', [8.00, 10.00], 0.30, 45, 0, 0; ...
    'P2', [8.20, 10.00], 0.20, 0, -6, 0; ...
    'P3', [7.90, 10.10], 0.15, 90, 0, 0.9; ...
    'P4', [8.10, 9.95], 0.10, 135, -6, 0.9};
rows = cell(144, 1);
global_index = 0;
k1_index = 0;
for noise_index = 1:numel(noise_ids)
    for L = [1, 4, 8]
        for snr_db = [-6, 0, 6]
            for profile_index = 1:size(k1_profiles, 1)
                global_index = global_index + 1;
                k1_index = k1_index + 1;
                center = k1_profiles{profile_index, 2};
                rows{global_index} = row_local(global_index, ...
                    sprintf('V22_K1_N%d_L%d_S%s_%s', noise_index, L, ...
                    signed_token_local(snr_db), k1_profiles{profile_index, 1}), ...
                    1, noise_ids(noise_index), L, snr_db, ...
                    k1_profiles{profile_index, 1}, center, NaN, NaN, ...
                    NaN, NaN, NaN, 2926073000 + k1_index - 1, ...
                    'NOT_APPLICABLE');
            end
        end
    end
end
k2_index = 0;
for noise_index = 1:numel(noise_ids)
    for L = [1, 4, 8]
        for snr_db = [-6, 0, 6]
            for profile_index = 1:size(k2_profiles, 1)
                global_index = global_index + 1;
                k2_index = k2_index + 1;
                profile = k2_profiles(profile_index, :);
                correlation = profile{6};
                correlation_contract = 'SPECIFIED_CORRELATION';
                if L == 1
                    correlation = 1;
                    correlation_contract = 'L1_FULLY_COHERENT_BY_CONTRACT';
                end
                rows{global_index} = row_local(global_index, ...
                    sprintf('V22_K2_N%d_L%d_S%s_%s', noise_index, L, ...
                    signed_token_local(snr_db), profile{1}), ...
                    2, noise_ids(noise_index), L, snr_db, profile{1}, ...
                    profile{2}, profile{3}, profile{4}, profile{5}, ...
                    correlation, 2926074000 + k2_index - 1, ...
                    2926075000 + k2_index - 1, correlation_contract);
            end
        end
    end
end
registry = struct2table(vertcat(rows{:}));
validate_registry_local(registry, bounds);
end

function row = row_local(index, id, K, noise, L, snr, profile, center, ...
    separation, direction, secondary_power, correlation, source_seed, ...
    noise_seed, correlation_contract)
row = struct('global_trial_index', double(index), ...
    'trial_id', string(id), 'trial_type', string(sprintf('K%d', K)), ...
    'K', double(K), 'noise_profile_id', string(noise), 'L', double(L), ...
    'snr_db', double(snr), 'profile_id', string(profile), ...
    'center_az_deg', double(center(1)), 'center_el_deg', double(center(2)), ...
    'separation_deg', double(separation), 'direction_deg', double(direction), ...
    'secondary_power_db', double(secondary_power), ...
    'correlation_magnitude', double(correlation), ...
    'source_seed', double(source_seed), 'noise_seed', double(noise_seed), ...
    'source_correlation_contract', string(correlation_contract), ...
    'cpi_id', "ONE_SYNTHETIC_CPI", ...
    'range_doppler_cell_id', "ONE_SELECTED_RANGE_DOPPLER_CELL", ...
    'single_cpi_flag', true, 'same_range_doppler_cell_flag', true, ...
    'cross_cpi_data_used_flag', false, ...
    'tracking_input_used_flag', false, ...
    'K_estimated_inside_module_flag', false);
end

function validate_registry_local(registry, bounds)
if height(registry) ~= 144 || nnz(registry.K == 1) ~= 72 || ...
        nnz(registry.K == 2) ~= 72 || ...
        numel(unique(registry.trial_id)) ~= 144 || ...
        numel(unique(registry.noise_seed)) ~= 144
    error('build_stage8_core_v2_2_final_registry:Cardinality', ...
        'The fixed 144-trial registry is invalid.');
end
k2 = registry(registry.K == 2, :);
if numel(unique(k2.source_seed)) ~= 72 || ...
        any(k2.source_seed < 2926074000) || ...
        any(k2.noise_seed < 2926075000)
    error('build_stage8_core_v2_2_final_registry:Seeds', ...
        'K2 source/noise seeds violate the registered disjoint ranges.');
end
for index = 1:height(k2)
    direction = [cosd(k2.direction_deg(index)), ...
        sind(k2.direction_deg(index))];
    targets = [ ...
        [k2.center_az_deg(index), k2.center_el_deg(index)] - ...
        k2.separation_deg(index) * direction / 2; ...
        [k2.center_az_deg(index), k2.center_el_deg(index)] + ...
        k2.separation_deg(index) * direction / 2];
    if any(targets(:, 1) < bounds(1) | targets(:, 1) > bounds(2) | ...
            targets(:, 2) < bounds(3) | targets(:, 2) > bounds(4))
        error('build_stage8_core_v2_2_final_registry:Domain', ...
            'A registered K2 endpoint lies outside the frozen local domain.');
    end
end
if any(registry.cross_cpi_data_used_flag) || ...
        any(registry.tracking_input_used_flag) || ...
        any(registry.K_estimated_inside_module_flag)
    error('build_stage8_core_v2_2_final_registry:Scenario', ...
        'The single-CPI known-K scenario flags are invalid.');
end
end

function token = signed_token_local(value)
if value < 0
    token = sprintf('M%d', abs(value));
else
    token = sprintf('P%d', value);
end
end
