function context = build_stage8_core_v2_2_validation_context(repo_dir, require_formal_runtime)
%BUILD_STAGE8_CORE_V2_2_VALIDATION_CONTEXT Load immutable frozen dependencies.

if nargin < 2, require_formal_runtime = true; end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
plan = build_stage8_locked_plan(repo_dir, sim_cfg(), ...
    struct('require_formal_runtime', logical(require_formal_runtime)));
context = struct('repo_dir', repo_dir, 'plan', plan, ...
    'stage5_locked', build_stage8_stage5_locked_config(), ...
    'primary_measurement_config_id', 'PRIMARY_RECT_E14_A31', ...
    'single_cpi_flag', true, 'cross_cpi_data_used_flag', false, ...
    'tracking_input_used_flag', false);
end
