function output = finalize_stage8_core_v2_2_final_validation(repo_dir, runtime_root)
%FINALIZE_STAGE8_CORE_V2_2_FINAL_VALIDATION Write corrected final evidence.

if isfile(fullfile(runtime_root, 'pause.request'))
    error('finalize_stage8_core_v2_2_final_validation:Pause', ...
        'Finalize is unavailable while a pause is requested.');
end
protocol = validate_protocol_local(runtime_root);
[f0, f1a, f1b] = load_gate_audits_local(runtime_root);
context = build_stage8_core_v2_2_validation_context(repo_dir, true);
registry = build_stage8_core_v2_2_final_registry(context.plan.local_domain);
validate_registry_local(registry, protocol);
checkpoint_audit = validate_checkpoints_local(runtime_root, registry);
targets = target_paths_local(repo_dir);
for index = 1:numel(targets)
    if isfile(targets{index})
        error('finalize_stage8_core_v2_2_final_validation:Overwrite', ...
            'Finalize refuses to overwrite %s.', targets{index});
    end
end

summary = summarize_stage8_core_v2_2_final_validation(runtime_root);
if height(summary.trials) ~= 288 || ...
        ~ismember(summary.decision.final_state, allowed_states_local())
    error('finalize_stage8_core_v2_2_final_validation:Summary', ...
        'The corrected final summary contract failed.');
end
writetable(summary.trials, targets{2});
writetable(summary.summary, targets{3});
writetable(summary.q_analysis, targets{4});
writetable(summary.complexity, targets{5});
write_report_local(targets{1}, summary, protocol, f0, f1a, f1b, ...
    checkpoint_audit);
finalized = struct('protocol', protocol, 'f0', f0, 'f1a', f1a, ...
    'f1b', f1b, 'checkpoint_audit', checkpoint_audit, ...
    'summary', summary, 'target_paths', {targets}, ...
    'finalized_utc', char(datetime('now', 'TimeZone', 'UTC')));
save(fullfile(runtime_root, 'finalized.mat'), 'finalized', '-mat');
output = struct('report_path', targets{1}, 'trials_path', targets{2}, ...
    'summary_path', targets{3}, 'q_analysis_path', targets{4}, ...
    'complexity_path', targets{5}, 'decision', summary.decision, ...
    'checkpoint_audit', checkpoint_audit);
end

function targets = target_paths_local(repo_dir)
root = fullfile(repo_dir, 'innovation-mining');
targets = { ...
    fullfile(root, ...
    '29_stage8_core_v2_2_corrected_final_single_cpi_known_k_validation.md'), ...
    fullfile(root, ...
    '29_stage8_core_v2_2_corrected_final_single_cpi_known_k_trials.csv'), ...
    fullfile(root, ...
    '29_stage8_core_v2_2_corrected_final_single_cpi_known_k_summary.csv'), ...
    fullfile(root, ...
    '29_stage8_core_v2_2_corrected_final_single_cpi_known_k_q_analysis.csv'), ...
    fullfile(root, ...
    '29_stage8_core_v2_2_corrected_final_single_cpi_known_k_complexity.csv')};
end

function protocol = validate_protocol_local(runtime_root)
path_now = fullfile(runtime_root, 'protocol.mat');
if ~isfile(path_now)
    error('finalize_stage8_core_v2_2_final_validation:ProtocolMissing', ...
        'The corrected protocol is missing.');
end
loaded = load(path_now, 'protocol', '-mat');
required = {'protocol_version','trial_count','k1_trial_count', ...
    'k2_trial_count','result_row_count','f0_status','f1a_status', ...
    'f1b_status','registry_contract_hash','runtime_root'};
if ~isfield(loaded, 'protocol') || ...
        ~all(isfield(loaded.protocol, required))
    error('finalize_stage8_core_v2_2_final_validation:ProtocolPayload', ...
        'The corrected protocol payload is incomplete.');
end
protocol = loaded.protocol;
expected_version = ['STAGE8_CORE_V2_2_SINGLE_CPI_KNOWN_K_FINAL_FREEZE_' ...
    'F1_ORACLE_CORRECTION_V1'];
valid = strcmp(protocol.protocol_version, expected_version) && ...
    strcmp(canonical_path_local(protocol.runtime_root), ...
    canonical_path_local(runtime_root)) && ...
    protocol.trial_count == 144 && protocol.k1_trial_count == 72 && ...
    protocol.k2_trial_count == 72 && protocol.result_row_count == 288 && ...
    strcmp(protocol.f0_status, 'F0_BOUNDARY_AND_ENVIRONMENT_PASS') && ...
    strcmp(protocol.f1a_status, 'F1A_CANONICAL_ORACLE_CONTRACT_PASS') && ...
    strcmp(protocol.f1b_status, ...
    'F1B_PRODUCTION_24_TRIAL_REGRESSION_PASS');
if ~valid
    error('finalize_stage8_core_v2_2_final_validation:ProtocolIdentity', ...
        'The runtime is not the corrected final-freeze protocol.');
end
end

function validate_registry_local(registry, protocol)
valid = istable(registry) && height(registry) == 144 && ...
    nnz(registry.K == 1) == 72 && nnz(registry.K == 2) == 72 && ...
    numel(unique(registry.trial_id)) == 144 && ...
    all(registry.single_cpi_flag) && ...
    all(registry.same_range_doppler_cell_flag) && ...
    ~any(registry.cross_cpi_data_used_flag) && ...
    ~any(registry.tracking_input_used_flag) && ...
    ~any(registry.K_estimated_inside_module_flag);
hash = stage8_core_v2_2_stable_hash( ...
    'STAGE8_CORE_V2_2_FINAL_REGISTRY_V1', table2struct(registry));
if ~valid || ~strcmp(hash, protocol.registry_contract_hash)
    error('finalize_stage8_core_v2_2_final_validation:RegistryIdentity', ...
        'The unchanged final registry identity failed.');
end
end

function [f0, f1a, f1b] = load_gate_audits_local(runtime_root)
f0 = load_audit_local(runtime_root, 'f0_audit.mat', 'f0', ...
    'F0_BOUNDARY_AND_ENVIRONMENT_PASS');
f1a = load_audit_local(runtime_root, 'f1a_oracle_audit.mat', 'f1a', ...
    'F1A_CANONICAL_ORACLE_CONTRACT_PASS');
f1b = load_audit_local(runtime_root, ...
    'f1b_production_regression_audit.mat', 'f1b', ...
    'F1B_PRODUCTION_24_TRIAL_REGRESSION_PASS');
end

function audit = load_audit_local(runtime_root, filename, variable, status)
path_now = fullfile(runtime_root, filename);
if ~isfile(path_now)
    error('finalize_stage8_core_v2_2_final_validation:AuditMissing', ...
        'Required gate audit is missing: %s.', filename);
end
loaded = load(path_now, variable, '-mat');
if ~isfield(loaded, variable)
    error('finalize_stage8_core_v2_2_final_validation:AuditPayload', ...
        'Required gate audit payload is missing: %s.', filename);
end
audit = loaded.(variable);
if ~isfield(audit, 'pass') || ~audit.pass || ...
        ~isfield(audit, 'status') || ~strcmp(audit.status, status)
    error('finalize_stage8_core_v2_2_final_validation:AuditStatus', ...
        'Required gate audit is not passing: %s.', filename);
end
end

function audit = validate_checkpoints_local(runtime_root, registry)
paths = dir(fullfile(runtime_root, 'checkpoints', '*.mat'));
temporary = dir(fullfile(runtime_root, 'tmp', '*'));
temporary = temporary(~[temporary.isdir]);
if numel(paths) ~= 144 || ~isempty(temporary)
    error('finalize_stage8_core_v2_2_final_validation:Completeness', ...
        'Finalize requires 144 checkpoints and zero temporary files.');
end
k1_count = 0;
k2_count = 0;
trial_ids = strings(numel(paths), 1);
element_hashes = strings(numel(paths), 1);
for index = 1:numel(paths)
    loaded = load(fullfile(paths(index).folder, paths(index).name), ...
        'checkpoint', '-mat');
    if ~isfield(loaded, 'checkpoint')
        error('finalize_stage8_core_v2_2_final_validation:CheckpointPayload', ...
            'A checkpoint payload is missing.');
    end
    checkpoint = loaded.checkpoint;
    required = {'trial_id','global_trial_index','K','element_trial_hash', ...
        'spec','trial','core_lite','core_plus','completion_status'};
    spec = registry(registry.trial_id == string(checkpoint.trial_id), :);
    if ~all(isfield(checkpoint, required)) || ...
            height(spec) ~= 1 || ~isequaln(checkpoint.spec, spec) || ...
            checkpoint.global_trial_index ~= spec.global_trial_index || ...
            checkpoint.K ~= spec.K || ...
            ~strcmp(checkpoint.completion_status, 'COMPLETE_PASS') || ...
            ~strcmp(checkpoint.element_trial_hash, ...
            checkpoint.trial.element_trial_hash) || ...
            ~ismember(checkpoint.K, [1, 2])
        error('finalize_stage8_core_v2_2_final_validation:CheckpointContract', ...
            'A checkpoint violates the corrected final contract.');
    end
    validate_result_local(checkpoint.core_lite, checkpoint.K, 'CORE_LITE');
    validate_result_local(checkpoint.core_plus, checkpoint.K, 'CORE_PLUS');
    if checkpoint.K == 1
        assert_same_k1_local(checkpoint.core_lite, checkpoint.core_plus);
    end
    trial_ids(index) = string(checkpoint.trial_id);
    element_hashes(index) = string(checkpoint.element_trial_hash);
    k1_count = k1_count + double(checkpoint.K == 1);
    k2_count = k2_count + double(checkpoint.K == 2);
end
if k1_count ~= 72 || k2_count ~= 72 || ...
        numel(unique(trial_ids)) ~= 144 || ...
        numel(unique(element_hashes)) ~= 144
    error('finalize_stage8_core_v2_2_final_validation:CheckpointShape', ...
        'Checkpoint K blocks or identities are incomplete.');
end
audit = struct('pass', true, 'checkpoint_count', numel(paths), ...
    'k1_checkpoint_count', k1_count, 'k2_checkpoint_count', k2_count, ...
    'result_row_count', 2 * numel(paths), 'tmp_checkpoint_count', 0, ...
    'pause_request_absent', true);
end

function validate_result_local(result, K, mode)
valid = result.K == K && strcmp(result.mode, mode) && ...
    result.single_cpi_flag && ...
    result.same_range_doppler_cell_flag && ...
    ~result.cross_cpi_data_used_flag && ...
    ~result.tracking_input_used_flag && ...
    ~result.K_estimated_inside_module_flag && ...
    ~result.truth_used_in_fit_flag;
if ~valid
    error('finalize_stage8_core_v2_2_final_validation:ResultFlags', ...
        'A final result violates the single-CPI known-K boundary.');
end
end

function value = canonical_path_local(value)
value = char(java.io.File(char(string(value))).getCanonicalPath());
end

function assert_same_k1_local(lite, plus)
same = isequal(num2hex(lite.angles_hat_deg), ...
    num2hex(plus.angles_hat_deg)) && ...
    isequal(num2hex(lite.rss), num2hex(plus.rss)) && ...
    isequal(num2hex(lite.loglik_concentrated), ...
    num2hex(plus.loglik_concentrated)) && ...
    lite.fit_valid == plus.fit_valid && ...
    strcmp(lite.fit_status, plus.fit_status) && ...
    strcmp(lite.selected_source, plus.selected_source) && ...
    strcmp(lite.selected_start_id, plus.selected_start_id) && ...
    strcmp(selected_solver_status_local(lite), ...
    selected_solver_status_local(plus));
if ~same
    error('finalize_stage8_core_v2_2_final_validation:K1ModeIdentity', ...
        'A K1 checkpoint violates CORE_LITE/CORE_PLUS identity.');
end
end

function status = selected_solver_status_local(result)
if strcmp(result.selected_source, 'CONTINUOUS_UPGRADE')
    candidate = result.continuous_candidate;
else
    candidate = result.fixed_grid_candidate;
end
status = char(string(candidate.solver_status));
end

function write_report_local(path_now, output, protocol, f0, f1a, f1b, audit)
fid = fopen(path_now, 'w', 'n', 'UTF-8');
if fid < 0
    error('finalize_stage8_core_v2_2_final_validation:Write', ...
        'Cannot write final report.');
end
cleanup = onCleanup(@() fclose(fid));
row = output.summary(1, :);
lite_complexity = output.complexity(output.complexity.mode == "CORE_LITE", :);
plus_complexity = output.complexity(output.complexity.mode == "CORE_PLUS", :);
trials = output.trials;
k2_plus = trials(trials.K == 2 & trials.mode == "CORE_PLUS", :);
profile_ids = unique(k2_plus.profile_id, 'stable');

fprintf(fid, '# Stage8 Core-V2.2 Corrected Final Single-CPI Known-K Validation\n\n');
fprintf(fid, 'Protocol: `%s`\n\n', protocol.protocol_version);
fprintf(fid, 'Old invalid report: `28_stage8_core_v2_2_final_single_cpi_known_k_validation.md`\n\n');
fprintf(fid, ['Correction: F1 canonical K1 oracle changed from impossible ' ...
    'H1+H2 equality to final conventional H1 only.\n\n']);
fprintf(fid, 'Production scientific code changed: `false`\n\n');
fprintf(fid, 'Registry/seeds changed: `false`\n\n');
fprintf(fid, 'Decision rules changed: `false`\n\n');
fprintf(fid, 'F0: `%s`\n\n', f0.status);
fprintf(fid, 'F1A: `%s`\n\n', f1a.status);
fprintf(fid, '- Canonical K1 oracle: `%s`\n', f1a.canonical_k1_method_id);
fprintf(fid, '- Noncanonical H2 K1 difference trials: `%d`\n', ...
    f1a.h1_h2_k1_difference_count);
fprintf(fid, '- Scientific H1/H2 K1 difference trials: `%d`\n\n', ...
    f1a.h1_h2_k1_scientific_difference_count);
fprintf(fid, 'F1B: `%s`\n\n', f1b.status);
fprintf(fid, '- Element hashes: `%d/%d`\n', ...
    f1b.element_hash_match_count, f1b.element_hash_expected_count);
fprintf(fid, '- K1 mode identity: `%d/%d`\n', ...
    f1b.k1_mode_identity_match_count, ...
    f1b.k1_mode_identity_expected_count);
fprintf(fid, '- K1 H1 canonical: `%d/%d`\n', ...
    f1b.k1_h1_canonical_match_count, ...
    f1b.k1_h1_canonical_expected_count);
fprintf(fid, '- K2 CORE_LITE B0: `%d/%d`\n', ...
    f1b.k2_core_lite_b0_match_count, ...
    f1b.k2_core_lite_b0_expected_count);
fprintf(fid, '- K2 CORE_PLUS H2: `%d/%d`\n\n', ...
    f1b.k2_core_plus_h2_match_count, ...
    f1b.k2_core_plus_h2_expected_count);
fprintf(fid, 'Independent validation: K1 `%d/72`, K2 `%d/72`, rows `%d/288`.\n\n', ...
    audit.k1_checkpoint_count, audit.k2_checkpoint_count, ...
    audit.result_row_count);

fprintf(fid, '## CORE_LITE\n\n');
fprintf(fid, '- Valid: K1 `%d/72`, K2 `%d/72`\n', ...
    row.k1_core_lite_valid, row.k2_core_lite_valid);
fprintf(fid, '- K1 overall median/p90 RMSE: `%.17g / %.17g deg`\n', ...
    row.k1_median_rmse_deg, row.k1_p90_rmse_deg);
fprintf(fid, '- K1 off-grid median/p90 RMSE: `%.17g / %.17g deg`\n', ...
    row.k1_off_grid_median_rmse_deg, row.k1_off_grid_p90_rmse_deg);
fprintf(fid, '- K1 paired wins/ties/losses: `%d/%d/%d`\n', ...
    row.k1_wins, row.k1_ties, row.k1_losses);
fprintf(fid, '- Mean score/SVD calls: `%.17g / %.17g`\n', ...
    lite_complexity.mean_score_calls, lite_complexity.mean_svd_calls);
fprintf(fid, '- Runtime median/p90: `%.17g / %.17g sec`\n\n', ...
    lite_complexity.median_runtime_sec, lite_complexity.p90_runtime_sec);

fprintf(fid, '## CORE_PLUS\n\n');
fprintf(fid, '- Valid: K2 `%d/72`\n', row.k2_core_plus_valid);
fprintf(fid, '- K2 overall median/p90 RMSE: `%.17g / %.17g deg`\n', ...
    row.k2_plus_median_rmse_deg, row.k2_plus_p90_rmse_deg);
for index = 1:numel(profile_ids)
    subset = k2_plus(k2_plus.profile_id == profile_ids(index), :);
    fprintf(fid, '- K2 profile `%s` median RMSE: `%.17g deg`\n', ...
        char(profile_ids(index)), median(subset.joint_rmse_deg));
end
fprintf(fid, '- K2 paired wins/ties/losses: `%d/%d/%d`\n', ...
    row.k2_plus_wins, row.k2_ties, row.k2_plus_losses);
fprintf(fid, '- K2 upgrades/fallbacks: `%d/%d`\n', ...
    row.k2_upgrade_count, row.k2_fallback_count);
fprintf(fid, '- Mean score/SVD calls: `%.17g / %.17g`\n', ...
    plus_complexity.mean_score_calls, plus_complexity.mean_svd_calls);
fprintf(fid, '- Runtime median/p90: `%.17g / %.17g sec`\n\n', ...
    plus_complexity.median_runtime_sec, plus_complexity.p90_runtime_sec);

fprintf(fid, '## Q Quartiles\n\n');
for index = 1:height(output.q_analysis)
    q = output.q_analysis(index, :);
    fprintf(fid, '- `%s`: n=%d, median q=%.17g, median RMSE=%.17g deg, fallback=%.17g\n', ...
        char(q.q_quartile), q.trial_count, q.median_q, ...
        q.median_joint_rmse_deg, q.fallback_rate);
end
fprintf(fid, '\nFinal state: `%s`\n\n', output.decision.final_state);
fprintf(fid, 'SINGLE_CPI\nSINGLE_RANGE_DOPPLER_CELL\n');
fprintf(fid, 'KNOWN_K_CONDITIONAL_ESTIMATION\nNO_TRACKING_INPUT\n');
fprintf(fid, 'NO_CROSS_CPI_INPUT\nNO_MODEL_ORDER_CLAIM\n');
fprintf(fid, 'NO_FORMAL_STAGE8_1_PASS\nNO_STAGE8_2_AUTHORIZATION\n\n');
fprintf(fid, 'Model-order: DEFERRED\n');
fprintf(fid, 'Formal 6000-trial: DEFERRED_NOT_FAILED\n');
fprintf(fid, 'Stage8.2: NOT_EXECUTED\n');
clear cleanup
end

function states = allowed_states_local()
states = { ...
    'STAGE8_CORE_V2_2_FINAL_FREEZE_PASS_CORE_PLUS_OPTIONAL', ...
    'STAGE8_CORE_V2_2_FINAL_FREEZE_PASS_CORE_LITE_ONLY', ...
    'STAGE8_CORE_V2_2_FINAL_KNOWN_K_CORE_NOT_CONFIRMED', ...
    'STAGE8_CORE_V2_2_EXPERIMENT_INVALID'};
end
