function trial = generate_stage8_core_v2_2_trial(spec, context)
%GENERATE_STAGE8_CORE_V2_2_TRIAL Generate one independent element trial.

if ~(istable(spec) && height(spec) == 1)
    error('generate_stage8_core_v2_2_trial:Spec', ...
        'spec must be one final-registry row.');
end
model = resolve_stage8_measurement_model( ...
    context.plan.measurement_model_registry, ...
    context.primary_measurement_config_id, spec.noise_profile_id);
if spec.K == 1
    truth = [spec.center_az_deg, spec.center_el_deg];
    [Y_element, simulation] = generate_stage8_k1_element_trial( ...
        truth, spec.snr_db, spec.L, model, spec.noise_seed);
    source = simulation.source_matrix;
    signal = simulation.signal_element;
    noise = simulation.noise_element;
    phase = NaN;
else
    direction = [cosd(spec.direction_deg), sind(spec.direction_deg)];
    center = [spec.center_az_deg, spec.center_el_deg];
    truth = [center - spec.separation_deg * direction / 2; ...
        center + spec.separation_deg * direction / 2];
    bounds = context.plan.local_domain.domain_bounds_deg;
    if any(truth(:, 1) < bounds(1) | truth(:, 1) > bounds(2) | ...
            truth(:, 2) < bounds(3) | truth(:, 2) > bounds(4))
        error('generate_stage8_core_v2_2_trial:Domain', ...
            'Both K2 endpoints must remain inside the frozen local domain.');
    end
    rng_state = rng;
    cleanup = onCleanup(@() rng(rng_state));
    rng(spec.source_seed, 'twister');
    phase = 2 * pi * rand();
    clear cleanup
    manifold = build_stage8_element_manifold(truth, model);
    [source, source_info] = construct_deterministic_source_matrix( ...
        2, spec.L, spec.secondary_power_db, ...
        spec.correlation_magnitude, phase, char(spec.trial_id));
    unscaled = manifold.A * source;
    target_energy = 10 ^ (spec.snr_db / 10) * numel(unscaled);
    source = source * sqrt(target_energy / ...
        max(norm(unscaled, 'fro') ^ 2, realmin));
    signal = manifold.A * source;
    [noise, noise_debug] = generate_stage8_element_noise( ...
        model, spec.L, 1, spec.noise_seed);
    Y_element = signal + noise;
    simulation = struct('source_info', source_info, ...
        'noise_debug', noise_debug, 'source_phase_rad', phase, ...
        'source_seed_used_flag', true);
end
element_trial_hash = stage8_core_v2_2_stable_hash( ...
    'STAGE8_CORE_V2_2_FINAL_ELEMENT_TRIAL_V1', char(spec.trial_id), ...
    Y_element, truth, double(spec.K), double(spec.L), ...
    double(spec.snr_db), double(spec.source_seed), double(spec.noise_seed), ...
    char(spec.noise_profile_id));
trial = struct('Y_element', Y_element, 'truth_angles_deg', truth, ...
    'model', model, 'source_matrix', source, 'signal_element', signal, ...
    'noise_element', noise, 'simulation', simulation, ...
    'source_phase_rad', phase, 'element_trial_hash', element_trial_hash, ...
    'cpi_id', char(spec.cpi_id), ...
    'range_doppler_cell_id', char(spec.range_doppler_cell_id), ...
    'single_cpi_flag', true, 'same_range_doppler_cell_flag', true, ...
    'cross_cpi_data_used_flag', false, ...
    'tracking_input_used_flag', false, ...
    'truth_used_in_fit_flag', false);
end
