function output = run_stage8_core_v2_2_final_validation(repo_dir, runtime_root, action)
%RUN_STAGE8_CORE_V2_2_FINAL_VALIDATION Single-process corrected final run.

if nargin < 1 || isempty(repo_dir)
    repo_dir = fileparts(fileparts(fileparts(fileparts(fileparts( ...
        fileparts(fileparts(mfilename('fullpath'))))))));
end
if nargin < 2 || isempty(runtime_root)
    runtime_root = fullfile('E:\bs_innovation_runtime', ...
        'stage8_core_v2_2_single_cpi_known_k_final_f1_oracle_correction_v1');
end
if nargin < 3 || isempty(action), action = 'Status'; end
action = upper(char(string(action)));
repo_dir = canonical_path_local(repo_dir);
runtime_root = canonical_path_local(runtime_root);
reject_old_runtime_local(runtime_root);

switch action
    case 'PREFLIGHT'
        output = f0_local(repo_dir, runtime_root);
    case 'START'
        output = start_local(repo_dir, runtime_root);
    case 'STATUS'
        output = status_local(runtime_root);
    case 'PAUSE'
        validate_protocol_local(runtime_root);
        write_text_local(fullfile(runtime_root, 'pause.request'), 'PAUSE\n');
        output = status_local(runtime_root);
    case 'RESUME'
        protocol = validate_protocol_local(runtime_root);
        pause_path = fullfile(runtime_root, 'pause.request');
        if isfile(pause_path), delete(pause_path); end
        output = resume_local(repo_dir, runtime_root, protocol);
    case 'FINALIZE'
        validate_protocol_local(runtime_root);
        output = finalize_stage8_core_v2_2_final_validation( ...
            repo_dir, runtime_root);
    otherwise
        error('run_stage8_core_v2_2_final_validation:Action', ...
            ['Action must be Preflight, Start, Status, Pause, Resume, ' ...
            'or Finalize.']);
end
end

function output = start_local(repo_dir, runtime_root)
f0 = f0_local(repo_dir, runtime_root);
if ~f0.pass
    save_preflight_failure_audit_local(runtime_root, f0);
    error('run_stage8_core_v2_2_final_validation:F0', ...
        'F0_FAIL_STOPPED: %s', f0.last_error);
end
prepare_new_runtime_local(runtime_root);
save(fullfile(runtime_root, 'f0_audit.mat'), 'f0', '-mat');
try
    f1a = test_f1_canonical_oracle_contract(repo_dir);
catch exception
    f1a = failed_audit_local('F1A_FAIL_STOPPED', exception);
    save(fullfile(runtime_root, 'f1a_oracle_audit.mat'), 'f1a', '-mat');
    rethrow(exception);
end
save(fullfile(runtime_root, 'f1a_oracle_audit.mat'), 'f1a', '-mat');
try
    f1b = test_historical_24_trial_regression(repo_dir);
catch exception
    f1b = failed_audit_local('F1B_FAIL_STOPPED', exception);
    save(fullfile(runtime_root, ...
        'f1b_production_regression_audit.mat'), 'f1b', '-mat');
    rethrow(exception);
end
save(fullfile(runtime_root, ...
    'f1b_production_regression_audit.mat'), 'f1b', '-mat');

context = build_stage8_core_v2_2_validation_context(repo_dir, true);
registry = build_stage8_core_v2_2_final_registry(context.plan.local_domain);
assert_registry_local(registry);
initialize_protocol_local(runtime_root, repo_dir, registry, f0, f1a, f1b);
output = execute_pending_local(context, registry, runtime_root);
end

function output = resume_local(repo_dir, runtime_root, protocol)
current_head = git_local(repo_dir, 'rev-parse HEAD');
if ~strcmp(current_head, protocol.git_head)
    error('run_stage8_core_v2_2_final_validation:ResumeHead', ...
        'Resume requires the exact Start commit.');
end
context = build_stage8_core_v2_2_validation_context(repo_dir, true);
registry = build_stage8_core_v2_2_final_registry(context.plan.local_domain);
assert_registry_local(registry);
actual_hash = registry_hash_local(registry);
if ~strcmp(actual_hash, protocol.registry_contract_hash)
    error('run_stage8_core_v2_2_final_validation:RegistryIdentity', ...
        'The corrected protocol registry identity changed.');
end
output = execute_pending_local(context, registry, runtime_root);
end

function output = execute_pending_local(context, registry, runtime_root)
completed = false(height(registry), 1);
for index = 1:height(registry)
    checkpoint_path = checkpoint_path_local( ...
        runtime_root, registry.trial_id(index));
    if isfile(checkpoint_path)
        validate_checkpoint_local(checkpoint_path, registry(index, :));
        completed(index) = true;
    end
end
for index = 1:height(registry)
    if completed(index), continue; end
    if isfile(fullfile(runtime_root, 'pause.request'))
        break;
    end
    spec = registry(index, :);
    trial = generate_stage8_core_v2_2_trial(spec, context);
    lite = estimate_stage8_known_k_local_cell( ...
        trial.Y_element, trial.model, context.plan.local_domain, ...
        context.stage5_locked, trial.model.noise_factorization, spec.K, ...
        struct('mode', 'CORE_LITE'));
    plus = estimate_stage8_known_k_local_cell( ...
        trial.Y_element, trial.model, context.plan.local_domain, ...
        context.stage5_locked, trial.model.noise_factorization, spec.K, ...
        struct('mode', 'CORE_PLUS'));
    if spec.K == 1
        assert_same_k1_local(lite, plus);
    end
    checkpoint = struct('trial_id', char(spec.trial_id), ...
        'global_trial_index', double(spec.global_trial_index), ...
        'K', double(spec.K), 'element_trial_hash', trial.element_trial_hash, ...
        'spec', spec, 'trial', trial, 'core_lite', lite, ...
        'core_plus', plus, 'completion_status', 'COMPLETE_PASS');
    checkpoint_path = checkpoint_path_local(runtime_root, spec.trial_id);
    tmp_path = fullfile(runtime_root, 'tmp', ...
        [char(string(spec.trial_id)), '.mat.tmp']);
    if isfile(tmp_path)
        error('run_stage8_core_v2_2_final_validation:StaleTmp', ...
            'A stale temporary checkpoint exists for %s.', spec.trial_id);
    end
    save(tmp_path, 'checkpoint', '-mat');
    validate_checkpoint_local(tmp_path, spec);
    if isfile(checkpoint_path)
        error('run_stage8_core_v2_2_final_validation:Collision', ...
            'A completed checkpoint appeared while processing %s.', ...
            spec.trial_id);
    end
    [moved, message] = movefile(tmp_path, checkpoint_path);
    if ~moved
        error('run_stage8_core_v2_2_final_validation:AtomicMove', '%s', message);
    end
    validate_checkpoint_local(checkpoint_path, spec);
    completed(index) = true;
end
output = status_local(runtime_root);
output.completed_trial_count = nnz(completed);
output.remaining_trial_count = height(registry) - nnz(completed);
end

function result = f0_local(repo_dir, runtime_root)
result = struct('pass', false, 'status', 'F0_FAIL_STOPPED', ...
    'last_error', '', 'branch', '', 'head', '', 'origin_head', '', ...
    'origin_main', '', 'worktree_clean', false, ...
    'anchor_is_ancestor', false, 'frozen_paths_clean', false, ...
    'old_runtime_audit', struct(), 'new_evidence_absent', false, ...
    'matlab_external_count', NaN, 'lock_count', 0, ...
    'coordinator_count', NaN);
try
    if ~strcmp(version('-release'), '2022b') || maxNumCompThreads ~= 1
        error('MATLAB R2022b with -singleCompThread is required.');
    end
    result.branch = git_local(repo_dir, 'branch --show-current');
    result.head = git_local(repo_dir, 'rev-parse HEAD');
    result.origin_head = git_local(repo_dir, ...
        'rev-parse origin/experiment/stage8-core-v2');
    result.origin_main = git_local(repo_dir, 'rev-parse origin/main');
    status = git_local(repo_dir, ...
        'status --porcelain=v1 --untracked-files=all');
    result.worktree_clean = isempty(strtrim(status));
    result.anchor_is_ancestor = is_ancestor_local(repo_dir, anchor_local());
    result.frozen_paths_clean = frozen_paths_clean_local(repo_dir);
    result.old_runtime_audit = old_runtime_audit_local();
    result.new_evidence_absent = new_evidence_absent_local(repo_dir);
    result.lock_count = numel(dir(fullfile(runtime_root, '**', '*.lock')));
    result.matlab_external_count = external_matlab_count_local();
    result.coordinator_count = coordinator_count_local();
    result.pass = strcmp(result.branch, 'experiment/stage8-core-v2') && ...
        strcmp(result.head, result.origin_head) && ...
        strcmp(result.origin_main, ...
        '247fad2208e77b04f7062e22b0fd3fd8a81bfc1f') && ...
        result.worktree_clean && result.anchor_is_ancestor && ...
        result.frozen_paths_clean && result.old_runtime_audit.pass && ...
        result.new_evidence_absent && result.lock_count == 0 && ...
        result.matlab_external_count == 0 && result.coordinator_count == 0;
    if result.pass
        result.status = 'F0_BOUNDARY_AND_ENVIRONMENT_PASS';
    else
        result.last_error = ['Branch, remote, frozen-path, runtime, process, ' ...
            'or clean-tree check failed.'];
    end
catch exception
    result.last_error = getReport(exception, 'extended', 'hyperlinks', 'off');
end
end

function clean = frozen_paths_clean_local(repo_dir)
base = 'beamspace_ml_v18/source/stepwise_signal_model/steps/';
protected = { ...
    [base, 'step_12_7_known_k_local_cell_refinement/common'], ...
    [base, 'step_12_7_known_k_local_cell_refinement/validation/', ...
    'build_stage8_core_v2_2_final_registry.m'], ...
    [base, 'step_12_7_known_k_local_cell_refinement/validation/', ...
    'generate_stage8_core_v2_2_trial.m'], ...
    [base, 'step_12_7_known_k_local_cell_refinement/validation/', ...
    'build_stage8_core_v2_2_validation_context.m'], ...
    [base, 'step_12_0_receive_model_correction'], ...
    [base, 'step_12_1_sequential_dbf_model'], ...
    [base, 'step_12_2_stable_dml_backend'], ...
    [base, 'step_12_3_grouped_conditional_dml'], ...
    [base, 'step_12_4_near_pair_tangent_asymptotics'], ...
    [base, 'step_12_5_1_stage7_closure_audit'], ...
    [base, 'step_12_5_exact_subset_fim_beam_design'], ...
    [base, 'step_12_6_k12_bootstrap_resolution'], ...
    'tools/stage8_r1_continuous_decisive', ...
    'tools/stage8_core_v2_known_k', ...
    'innovation-mining/15_*', 'innovation-mining/16_*', ...
    'innovation-mining/23_*', 'innovation-mining/24_*', ...
    'innovation-mining/26_*', 'innovation-mining/27_*', ...
    'innovation-mining/28_*'};
clean = true;
for index = 1:numel(protected)
    command = sprintf('git -C "%s" diff --quiet %s..HEAD -- "%s"', ...
        repo_dir, anchor_local(), protected{index});
    [code, ~] = system(command);
    if code > 1
        error('run_stage8_core_v2_2_final_validation:FrozenAudit', ...
            'Git frozen-path audit failed for %s.', protected{index});
    end
    clean = clean && code == 0;
end
end

function audit = old_runtime_audit_local()
root = fullfile('E:\bs_innovation_runtime', ...
    'stage8_core_v2_2_single_cpi_known_k_final_v1');
f0_path = fullfile(root, 'f0_audit.mat');
f1_path = fullfile(root, 'f1_audit.mat');
tmp_inventory = stage8_core_v2_2_directory_inventory( ...
    fullfile(root, 'tmp'));
audit = struct('runtime_root', root, 'present', isfolder(root), ...
    'f0_present', isfile(f0_path), 'f1_present', isfile(f1_path), ...
    'protocol_present', isfile(fullfile(root, 'protocol.mat')), ...
    'checkpoint_count', numel(dir(fullfile(root, 'checkpoints', '*.mat'))), ...
    'tmp_count', tmp_inventory.file_count, ...
    'tmp_file_count', tmp_inventory.file_count, ...
    'tmp_directory_count', tmp_inventory.directory_count, ...
    'tmp_file_names', tmp_inventory.file_names, ...
    'tmp_directory_names', tmp_inventory.directory_names, ...
    'f0_sha256', '', 'f1_sha256', '', 'pass', false);
if audit.f0_present, audit.f0_sha256 = file_sha256_local(f0_path); end
if audit.f1_present, audit.f1_sha256 = file_sha256_local(f1_path); end
audit.pass = audit.present && audit.f0_present && audit.f1_present && ...
    ~audit.protocol_present && audit.checkpoint_count == 0 && ...
    audit.tmp_file_count == 0 && audit.tmp_directory_count == 0 && ...
    strcmpi(audit.f0_sha256, ...
    '3C459B74EDE8D2BB6594F28CEED0E1D02B392B27CAE43EE04A3ACF51390DB912') && ...
    strcmpi(audit.f1_sha256, ...
    'E86E554347D7500F63D4738C0F37DC63348E5AB3BD1D0686AF217D493351F345');
end

function path_now = save_preflight_failure_audit_local(runtime_root, f0)
failure_root = fullfile(fileparts(runtime_root), ...
    'stage8_core_v2_2_preflight_failures');
if ~isfolder(failure_root)
    [created, message] = mkdir(failure_root);
    if ~created
        error('run_stage8_core_v2_2_final_validation:PreflightAuditRoot', ...
            '%s', message);
    end
end
stamp = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyyMMdd''T''HHmmssSSS''Z'''));
path_now = fullfile(failure_root, [stamp, '_f0_audit.mat']);
if isfile(path_now)
    error('run_stage8_core_v2_2_final_validation:PreflightAuditCollision', ...
        'A preflight failure audit already exists at %s.', path_now);
end
save(path_now, 'f0', '-mat');
end

function absent = new_evidence_absent_local(repo_dir)
names = { ...
    '29_stage8_core_v2_2_corrected_final_single_cpi_known_k_validation.md', ...
    '29_stage8_core_v2_2_corrected_final_single_cpi_known_k_trials.csv', ...
    '29_stage8_core_v2_2_corrected_final_single_cpi_known_k_summary.csv', ...
    '29_stage8_core_v2_2_corrected_final_single_cpi_known_k_q_analysis.csv', ...
    '29_stage8_core_v2_2_corrected_final_single_cpi_known_k_complexity.csv'};
absent = true;
for index = 1:numel(names)
    absent = absent && ~isfile(fullfile(repo_dir, ...
        'innovation-mining', names{index}));
end
end

function initialize_protocol_local(runtime_root, repo_dir, registry, f0, f1a, f1b)
path_now = fullfile(runtime_root, 'protocol.mat');
if isfile(path_now) || ...
        ~isempty(dir(fullfile(runtime_root, 'checkpoints', '*.mat')))
    error('run_stage8_core_v2_2_final_validation:Protocol', ...
        'Protocol initialization requires an empty checkpoint set.');
end
protocol = struct('protocol_version', protocol_version_local(), ...
    'repo_dir', repo_dir, 'runtime_root', runtime_root, ...
    'git_head', f0.head, 'origin_main', f0.origin_main, ...
    'f0_status', f0.status, 'f1a_status', f1a.status, ...
    'f1b_status', f1b.status, 'trial_count', height(registry), ...
    'k1_trial_count', nnz(registry.K == 1), ...
    'k2_trial_count', nnz(registry.K == 2), ...
    'result_row_count', 2 * height(registry), ...
    'registry_contract_hash', registry_hash_local(registry), ...
    'threads_per_worker', 1, 'worker_count', 1, ...
    'single_cpi_flag', true, 'known_k_flag', true, ...
    'created_utc', char(datetime('now', 'TimeZone', 'UTC')));
save(path_now, 'protocol', '-mat');
writetable(registry, fullfile(runtime_root, 'registry.csv'));
end

function protocol = validate_protocol_local(runtime_root)
path_now = fullfile(runtime_root, 'protocol.mat');
if ~isfile(path_now)
    error('run_stage8_core_v2_2_final_validation:ProtocolMissing', ...
        'The corrected Start-created protocol is required.');
end
loaded = load(path_now, 'protocol', '-mat');
required = {'protocol_version','runtime_root','f0_status','f1a_status', ...
    'f1b_status','trial_count','k1_trial_count','k2_trial_count', ...
    'result_row_count','registry_contract_hash','git_head'};
if ~isfield(loaded, 'protocol') || ...
        ~all(isfield(loaded.protocol, required))
    error('run_stage8_core_v2_2_final_validation:ProtocolPayload', ...
        'The corrected protocol payload is incomplete.');
end
protocol = loaded.protocol;
valid = strcmp(protocol.protocol_version, protocol_version_local()) && ...
    strcmp(canonical_path_local(protocol.runtime_root), runtime_root) && ...
    strcmp(protocol.f0_status, 'F0_BOUNDARY_AND_ENVIRONMENT_PASS') && ...
    strcmp(protocol.f1a_status, 'F1A_CANONICAL_ORACLE_CONTRACT_PASS') && ...
    strcmp(protocol.f1b_status, ...
    'F1B_PRODUCTION_24_TRIAL_REGRESSION_PASS') && ...
    protocol.trial_count == 144 && protocol.k1_trial_count == 72 && ...
    protocol.k2_trial_count == 72 && protocol.result_row_count == 288;
if ~valid
    error('run_stage8_core_v2_2_final_validation:ProtocolIdentity', ...
        'Runtime protocol is not the corrected V1 identity.');
end
validate_gate_audits_local(runtime_root);
end

function validate_gate_audits_local(runtime_root)
specs = { ...
    'f0_audit.mat', 'f0', 'F0_BOUNDARY_AND_ENVIRONMENT_PASS'; ...
    'f1a_oracle_audit.mat', 'f1a', ...
    'F1A_CANONICAL_ORACLE_CONTRACT_PASS'; ...
    'f1b_production_regression_audit.mat', 'f1b', ...
    'F1B_PRODUCTION_24_TRIAL_REGRESSION_PASS'};
for index = 1:size(specs, 1)
    path_now = fullfile(runtime_root, specs{index, 1});
    if ~isfile(path_now)
        error('run_stage8_core_v2_2_final_validation:GateAudit', ...
            'Required gate audit is missing: %s.', specs{index, 1});
    end
    loaded = load(path_now, specs{index, 2}, '-mat');
    if ~isfield(loaded, specs{index, 2})
        error('run_stage8_core_v2_2_final_validation:GateAuditPayload', ...
            'Gate audit payload is missing: %s.', specs{index, 1});
    end
    audit = loaded.(specs{index, 2});
    if ~isfield(audit, 'pass') || ~audit.pass || ...
            ~isfield(audit, 'status') || ...
            ~strcmp(audit.status, specs{index, 3})
        error('run_stage8_core_v2_2_final_validation:GateAuditStatus', ...
            'Gate audit is not passing: %s.', specs{index, 1});
    end
end
end

function validate_checkpoint_local(path_now, spec)
loaded = load(path_now, 'checkpoint', '-mat');
if ~isfield(loaded, 'checkpoint')
    error('run_stage8_core_v2_2_final_validation:Checkpoint', ...
        'Checkpoint payload is missing.');
end
checkpoint = loaded.checkpoint;
required = {'trial_id','global_trial_index','K','element_trial_hash', ...
    'spec','trial','core_lite','core_plus','completion_status'};
if ~isstruct(checkpoint) || ~all(isfield(checkpoint, required)) || ...
        ~strcmp(checkpoint.completion_status, 'COMPLETE_PASS') || ...
        ~strcmp(checkpoint.trial_id, char(spec.trial_id)) || ...
        checkpoint.global_trial_index ~= spec.global_trial_index || ...
        checkpoint.K ~= spec.K || ~isequaln(checkpoint.spec, spec) || ...
        ~strcmp(checkpoint.element_trial_hash, ...
        checkpoint.trial.element_trial_hash)
    error('run_stage8_core_v2_2_final_validation:CheckpointContract', ...
        'Checkpoint contract differs from the registry.');
end
for result = {checkpoint.core_lite, checkpoint.core_plus}
    value = result{1};
    if value.K ~= spec.K || ~value.single_cpi_flag || ...
            ~value.same_range_doppler_cell_flag || ...
            value.cross_cpi_data_used_flag || value.tracking_input_used_flag || ...
            value.K_estimated_inside_module_flag || value.truth_used_in_fit_flag
        error('run_stage8_core_v2_2_final_validation:CheckpointFlags', ...
            'One result violates the single-CPI known-K contract.');
    end
end
if spec.K == 1
    assert_same_k1_local(checkpoint.core_lite, checkpoint.core_plus);
end
end

function assert_same_k1_local(lite, plus)
same = isequal(num2hex(lite.angles_hat_deg), ...
    num2hex(plus.angles_hat_deg)) && ...
    isequal(num2hex(lite.rss), num2hex(plus.rss)) && ...
    isequal(num2hex(lite.loglik_concentrated), ...
    num2hex(plus.loglik_concentrated)) && ...
    lite.fit_valid == plus.fit_valid && ...
    strcmp(lite.fit_status, plus.fit_status) && ...
    strcmp(lite.selected_source, plus.selected_source) && ...
    strcmp(lite.selected_start_id, plus.selected_start_id) && ...
    strcmp(selected_solver_status_local(lite), ...
    selected_solver_status_local(plus));
if ~same
    error('run_stage8_core_v2_2_final_validation:K1ModeIdentity', ...
        'CORE_LITE and CORE_PLUS K1 outputs differ.');
end
end

function status = selected_solver_status_local(result)
if strcmp(result.selected_source, 'CONTINUOUS_UPGRADE')
    candidate = result.continuous_candidate;
else
    candidate = result.fixed_grid_candidate;
end
status = char(string(candidate.solver_status));
end

function output = status_local(runtime_root)
checkpoints = dir(fullfile(runtime_root, 'checkpoints', '*.mat'));
temporary = dir(fullfile(runtime_root, 'tmp', '*'));
temporary = temporary(~[temporary.isdir]);
output = struct('runtime_root', runtime_root, ...
    'protocol_version', protocol_status_local(runtime_root), ...
    'f0_status', audit_status_local(runtime_root, 'f0_audit.mat', 'f0'), ...
    'f1a_status', audit_status_local(runtime_root, ...
    'f1a_oracle_audit.mat', 'f1a'), ...
    'f1b_status', audit_status_local(runtime_root, ...
    'f1b_production_regression_audit.mat', 'f1b'), ...
    'completed_trial_count', numel(checkpoints), ...
    'remaining_trial_count', max(0, 144 - numel(checkpoints)), ...
    'tmp_checkpoint_count', numel(temporary), ...
    'pause_requested', isfile(fullfile(runtime_root, 'pause.request')), ...
    'lock_count', numel(dir(fullfile(runtime_root, '**', '*.lock'))), ...
    'finalized', isfile(fullfile(runtime_root, 'finalized.mat')));
end

function value = protocol_status_local(runtime_root)
value = 'ABSENT';
path_now = fullfile(runtime_root, 'protocol.mat');
if ~isfile(path_now), return; end
loaded = load(path_now, 'protocol', '-mat');
if isfield(loaded, 'protocol') && isfield(loaded.protocol, 'protocol_version')
    value = char(string(loaded.protocol.protocol_version));
else
    value = 'INVALID';
end
end

function value = audit_status_local(runtime_root, filename, variable)
value = 'ABSENT';
path_now = fullfile(runtime_root, filename);
if ~isfile(path_now), return; end
loaded = load(path_now, variable, '-mat');
if isfield(loaded, variable) && ...
        isfield(loaded.(variable), 'status')
    value = char(string(loaded.(variable).status));
else
    value = 'INVALID';
end
end

function prepare_new_runtime_local(root)
if isfile(root)
    error('run_stage8_core_v2_2_final_validation:RuntimeFile', ...
        'The corrected runtime path is an existing file.');
end
if isfolder(root)
    items = dir(root);
    items = items(~ismember({items.name}, {'.','..'}));
    if ~isempty(items)
        error('run_stage8_core_v2_2_final_validation:RuntimeNotEmpty', ...
            'The corrected runtime already contains files or directories.');
    end
    rmdir(root);
end
mkdir(root);
mkdir(fullfile(root, 'checkpoints'));
mkdir(fullfile(root, 'tmp'));
end

function reject_old_runtime_local(runtime_root)
old_root = canonical_path_local(fullfile('E:\bs_innovation_runtime', ...
    'stage8_core_v2_2_single_cpi_known_k_final_v1'));
if strcmpi(runtime_root, old_root)
    error('run_stage8_core_v2_2_final_validation:OldRuntime', ...
        'The immutable old V1 runtime cannot be used by this protocol.');
end
end

function assert_registry_local(registry)
valid = istable(registry) && height(registry) == 144 && ...
    nnz(registry.K == 1) == 72 && nnz(registry.K == 2) == 72 && ...
    numel(unique(registry.trial_id)) == 144 && ...
    numel(unique(registry.noise_seed)) == 144 && ...
    all(registry.single_cpi_flag) && ...
    all(registry.same_range_doppler_cell_flag) && ...
    ~any(registry.cross_cpi_data_used_flag) && ...
    ~any(registry.tracking_input_used_flag) && ...
    ~any(registry.K_estimated_inside_module_flag);
if ~valid
    error('run_stage8_core_v2_2_final_validation:Registry', ...
        'The unchanged 144-trial registry contract failed.');
end
end

function hash = registry_hash_local(registry)
hash = stage8_core_v2_2_stable_hash( ...
    'STAGE8_CORE_V2_2_FINAL_REGISTRY_V1', table2struct(registry));
end

function path_now = checkpoint_path_local(root, trial_id)
path_now = fullfile(root, 'checkpoints', ...
    [char(string(trial_id)), '.mat']);
end

function audit = failed_audit_local(status, exception)
audit = struct('pass', false, 'status', status, ...
    'last_error', getReport(exception, 'extended', 'hyperlinks', 'off'));
end

function value = git_local(repo_dir, arguments)
[status, value] = system(sprintf('git -C "%s" %s', repo_dir, arguments));
if status ~= 0
    error('run_stage8_core_v2_2_final_validation:Git', ...
        'Git command failed: %s.', arguments);
end
value = strtrim(value);
end

function value = is_ancestor_local(repo_dir, commit)
[status, ~] = system(sprintf( ...
    'git -C "%s" merge-base --is-ancestor %s HEAD', repo_dir, commit));
value = status == 0;
end

function count = external_matlab_count_local()
pid = feature('getpid');
command = sprintf(['powershell -NoProfile -Command "$all = @(' ...
    'Get-CimInstance Win32_Process); $excluded = @(%d); ' ...
    '$cursor = $all | Where-Object { $_.ProcessId -eq %d }; ' ...
    'while ($null -ne $cursor -and $cursor.ParentProcessId -gt 0) { ' ...
    '$parentId = $cursor.ParentProcessId; $excluded += $parentId; ' ...
    '$cursor = $all | Where-Object { $_.ProcessId -eq $parentId } }; ' ...
    '$items = @($all | Where-Object { $_.Name -match ''^MATLAB'' -and ' ...
    '$_.ProcessId -notin $excluded }); $items.Count"'], pid, pid);
[status, output] = system(command);
if status ~= 0 || ~isfinite(str2double(strtrim(output)))
    error('run_stage8_core_v2_2_final_validation:MatlabProcessAudit', ...
        'Unable to audit external MATLAB processes.');
end
count = str2double(strtrim(output));
end

function count = coordinator_count_local()
pid = feature('getpid');
command = sprintf(['powershell -NoProfile -Command "$items = @(' ...
    'Get-CimInstance Win32_Process | Where-Object { ' ...
    '$_.ProcessId -ne $PID -and $_.ProcessId -ne %d -and ' ...
    '$_.CommandLine -match ''stage8.*coordinator|coordinator.*stage8'' -and ' ...
    '$_.CommandLine -notmatch ''Get-CimInstance Win32_Process'' }); ' ...
    '$items.Count"'], pid);
[status, output] = system(command);
if status ~= 0 || ~isfinite(str2double(strtrim(output)))
    error('run_stage8_core_v2_2_final_validation:CoordinatorAudit', ...
        'Unable to audit Stage8 coordinator processes.');
end
count = str2double(strtrim(output));
end

function hash = file_sha256_local(path_now)
[status, output] = system(sprintf('certutil -hashfile "%s" SHA256', path_now));
tokens = regexp(output, '[0-9A-Fa-f]{64}', 'match');
if status ~= 0 || numel(tokens) ~= 1
    error('run_stage8_core_v2_2_final_validation:FileHash', ...
        'Unable to compute SHA-256 for %s.', path_now);
end
hash = upper(tokens{1});
end

function value = protocol_version_local()
value = ['STAGE8_CORE_V2_2_SINGLE_CPI_KNOWN_K_FINAL_FREEZE_' ...
    'F1_ORACLE_CORRECTION_V1'];
end

function value = anchor_local()
value = '4d37901fb24b6ac22ec126c4a275cfe4359d4c7f';
end

function value = canonical_path_local(value)
value = char(java.io.File(char(string(value))).getCanonicalPath());
end

function write_text_local(path_now, text)
fid = fopen(path_now, 'w', 'n', 'UTF-8');
if fid < 0
    error('run_stage8_core_v2_2_final_validation:Write', ...
        'Cannot write %s.', path_now);
end
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, text, 'char');
clear cleanup
end
