function output = summarize_stage8_core_v2_2_final_validation(runtime_root)
%SUMMARIZE_STAGE8_CORE_V2_2_FINAL_VALIDATION Build rows and freeze metrics.

checkpoint_paths = dir(fullfile(runtime_root, 'checkpoints', '*.mat'));
if numel(checkpoint_paths) ~= 144
    error('summarize_stage8_core_v2_2_final_validation:Checkpoints', ...
        'Exactly 144 validated checkpoints are required.');
end
rows = cell(288, 1);
row_index = 0;
for index = 1:numel(checkpoint_paths)
    loaded = load(fullfile(checkpoint_paths(index).folder, ...
        checkpoint_paths(index).name), 'checkpoint', '-mat');
    checkpoint = loaded.checkpoint;
    if ~strcmp(checkpoint.completion_status, 'COMPLETE_PASS')
        error('summarize_stage8_core_v2_2_final_validation:Checkpoint', ...
            'A checkpoint is not complete.');
    end
    row_index = row_index + 1;
    rows{row_index} = row_local(checkpoint, checkpoint.core_lite, 'CORE_LITE');
    row_index = row_index + 1;
    rows{row_index} = row_local(checkpoint, checkpoint.core_plus, 'CORE_PLUS');
end
trials = struct2table(vertcat(rows{:}));
trials = sortrows(trials, {'global_trial_index','mode'});
summary = summary_local(trials);
q_analysis = q_analysis_local(trials);
complexity = complexity_local(trials);
decision = decision_local(trials);
output = struct('trials', trials, 'summary', summary, ...
    'q_analysis', q_analysis, 'complexity', complexity, ...
    'decision', decision);
end

function row = row_local(checkpoint, result, mode)
spec = checkpoint.spec;
truth = checkpoint.trial.truth_angles_deg;
estimate = match_targets_local(result.angles_hat_deg, truth);
error_now = estimate - truth;
joint_rmse = sqrt(mean(sum(error_now .^ 2, 2)));
fixed = result.fixed_grid_candidate;
fixed_estimate = match_targets_local(fixed.angles_hat_deg, truth);
fixed_error = fixed_estimate - truth;
fixed_grid_joint_rmse_deg = sqrt(mean(sum(fixed_error .^ 2, 2)));
continuous = result.continuous_candidate;
[q, condition] = geometry_local(spec, checkpoint.trial.model, fixed);
continuous_rss = NaN;
continuous_loglik = NaN;
continuous_valid = false;
if ~isempty(fieldnames(continuous))
    continuous_rss = continuous.rss;
    continuous_loglik = continuous.loglik_concentrated;
    continuous_valid = continuous.fit_valid;
end
upgrade = false;
fallback = false;
if isfield(result.diagnostics, 'continuous_upgrade_flag')
    upgrade = logical(result.diagnostics.continuous_upgrade_flag);
    fallback = logical(result.diagnostics.fallback_flag);
end
row = struct('global_trial_index', double(spec.global_trial_index), ...
    'trial_id', string(spec.trial_id), 'K', double(spec.K), ...
    'mode', string(mode), 'noise_profile_id', string(spec.noise_profile_id), ...
    'L', double(spec.L), 'snr_db', double(spec.snr_db), ...
    'profile_id', string(spec.profile_id), ...
    'element_trial_hash', string(checkpoint.element_trial_hash), ...
    'fit_valid', logical(result.fit_valid), ...
    'fit_status', string(result.fit_status), ...
    'selected_source', string(result.selected_source), ...
    'selected_start_id', string(result.selected_start_id), ...
    'angles_hat_deg', string(mat2str(result.angles_hat_deg, 17)), ...
    'joint_rmse_deg', double(joint_rmse), 'rss', double(result.rss), ...
    'loglik_concentrated', double(result.loglik_concentrated), ...
    'effective_rank', double(result.effective_rank), ...
    'score_call_count', double(result.score_call_count), ...
    'svd_call_count', double(result.svd_call_count), ...
    'runtime_sec', double(result.runtime_sec), ...
    'fixed_grid_angles_deg', string(mat2str(fixed.angles_hat_deg, 17)), ...
    'fixed_grid_joint_rmse_deg', double(fixed_grid_joint_rmse_deg), ...
    'fixed_grid_rss', double(fixed.rss), ...
    'fixed_grid_loglik', double(fixed.loglik_concentrated), ...
    'fixed_grid_valid', logical(fixed.fit_valid), ...
    'fixed_grid_condition_number', double(condition), ...
    'continuous_rss', double(continuous_rss), ...
    'continuous_loglik', double(continuous_loglik), ...
    'continuous_valid', logical(continuous_valid), ...
    'continuous_upgrade_flag', logical(upgrade), ...
    'fallback_flag', logical(fallback), 'q', double(q), ...
    'single_cpi_flag', logical(result.single_cpi_flag), ...
    'same_range_doppler_cell_flag', ...
    logical(result.same_range_doppler_cell_flag), ...
    'cross_cpi_data_used_flag', logical(result.cross_cpi_data_used_flag), ...
    'tracking_input_used_flag', logical(result.tracking_input_used_flag), ...
    'K_estimated_inside_module_flag', ...
    logical(result.K_estimated_inside_module_flag), ...
    'truth_used_in_fit_flag', logical(result.truth_used_in_fit_flag));
end

function [q, condition] = geometry_local(spec, model, fixed)
if spec.K ~= 2
    q = NaN;
    condition = NaN;
    return;
end
direction = [cosd(spec.direction_deg), sind(spec.direction_deg)];
center = [spec.center_az_deg, spec.center_el_deg];
truth = [center - spec.separation_deg * direction / 2; ...
    center + spec.separation_deg * direction / 2];
geometry = compute_stage8_projected_separation_geometry(truth, model);
q = geometry.q;
[G, ~] = build_full_sequential_local_manifold(fixed.angles_hat_deg, ...
    model, struct('rank_multiplier', 1));
condition = cond(G' * G);
end

function estimate = match_targets_local(estimate, truth)
if size(estimate, 1) == 1
    return;
end
identity_cost = sum((estimate - truth) .^ 2, 'all');
swap_cost = sum((estimate([2, 1], :) - truth) .^ 2, 'all');
if swap_cost < identity_cost
    estimate = estimate([2, 1], :);
end
end

function summary = summary_local(trials)
k1_lite = trials(trials.K == 1 & trials.mode == "CORE_LITE", :);
k1_b0_rmse = fixed_grid_rmse_local(k1_lite);
off = k1_lite(k1_lite.profile_id ~= "C1_ON_GRID", :);
off_b0 = fixed_grid_rmse_local(off);
k2_lite = trials(trials.K == 2 & trials.mode == "CORE_LITE", :);
k2_plus = trials(trials.K == 2 & trials.mode == "CORE_PLUS", :);
if height(k1_lite) ~= 72 || height(k2_lite) ~= 72 || height(k2_plus) ~= 72
    error('summarize_stage8_core_v2_2_final_validation:Rows', ...
        'Expected paired 72-trial blocks are missing.');
end
[wins, ties, losses] = paired_outcomes_local(off.joint_rmse_deg, off_b0);
[k2_wins, k2_ties, k2_losses] = paired_outcomes_local( ...
    k2_plus.joint_rmse_deg, k2_lite.joint_rmse_deg);
ci_k1 = bootstrap_median_ci_local(off.joint_rmse_deg - off_b0);
ci_k2 = bootstrap_median_ci_local( ...
    k2_plus.joint_rmse_deg - k2_lite.joint_rmse_deg);
summary = table( ...
    nnz(k1_lite.fit_valid), nnz(k2_lite.fit_valid), nnz(k2_plus.fit_valid), ...
    median(k1_lite.joint_rmse_deg), percentile_local(k1_lite.joint_rmse_deg, 90), ...
    median(off.joint_rmse_deg), percentile_local(off.joint_rmse_deg, 90), ...
    median(k1_b0_rmse), median(off_b0), wins, ties, losses, ...
    ci_k1(1), ci_k1(2), median(k2_lite.joint_rmse_deg), ...
    percentile_local(k2_lite.joint_rmse_deg, 90), ...
    median(k2_plus.joint_rmse_deg), ...
    percentile_local(k2_plus.joint_rmse_deg, 90), ...
    k2_wins, k2_ties, k2_losses, ci_k2(1), ci_k2(2), ...
    nnz(k1_lite.continuous_upgrade_flag), nnz(k1_lite.fallback_flag), ...
    nnz(k2_plus.continuous_upgrade_flag), nnz(k2_plus.fallback_flag), ...
    'VariableNames', {'k1_core_lite_valid','k2_core_lite_valid', ...
    'k2_core_plus_valid','k1_median_rmse_deg','k1_p90_rmse_deg', ...
    'k1_off_grid_median_rmse_deg','k1_off_grid_p90_rmse_deg', ...
    'k1_b0_median_rmse_deg','k1_off_grid_b0_median_rmse_deg', ...
    'k1_wins','k1_ties','k1_losses','k1_bootstrap_ci_low_deg', ...
    'k1_bootstrap_ci_high_deg','k2_lite_median_rmse_deg', ...
    'k2_lite_p90_rmse_deg','k2_plus_median_rmse_deg', ...
    'k2_plus_p90_rmse_deg','k2_plus_wins','k2_ties','k2_plus_losses', ...
    'k2_bootstrap_ci_low_deg','k2_bootstrap_ci_high_deg', ...
    'k1_upgrade_count','k1_fallback_count','k2_upgrade_count', ...
    'k2_fallback_count'});
end

function rmse = fixed_grid_rmse_local(rows)
rmse = rows.fixed_grid_joint_rmse_deg;
end

function [wins, ties, losses] = paired_outcomes_local(left, right)
tolerance = 64 * eps(max(1, max(abs([left(:); right(:)]))));
wins = nnz(left < right - tolerance);
losses = nnz(left > right + tolerance);
ties = numel(left) - wins - losses;
end

function ci = bootstrap_median_ci_local(differences)
rng_state = rng;
cleanup = onCleanup(@() rng(rng_state));
rng(3026073000, 'twister');
B = 1000;
n = numel(differences);
samples = zeros(B, 1);
for index = 1:B
    samples(index) = median(differences(randi(n, n, 1)));
end
ci = [percentile_local(samples, 2.5), percentile_local(samples, 97.5)];
clear cleanup
end

function q_analysis = q_analysis_local(trials)
rows = trials(trials.K == 2 & trials.mode == "CORE_PLUS", :);
[~, order] = sort(rows.q);
rows = rows(order, :);
quartile = strings(height(rows), 1);
for index = 1:height(rows)
    quartile(index) = "Q" + string(min(4, ceil(4 * index / height(rows))));
end
groups = unique(quartile, 'stable');
cells = cell(numel(groups), 1);
for index = 1:numel(groups)
    subset = rows(quartile == groups(index), :);
    cells{index} = table(groups(index), height(subset), median(subset.q), ...
        median(subset.joint_rmse_deg), mean(subset.fallback_flag), ...
        'VariableNames', {'q_quartile','trial_count','median_q', ...
        'median_joint_rmse_deg','fallback_rate'});
end
q_analysis = vertcat(cells{:});
end

function complexity = complexity_local(trials)
modes = ["CORE_LITE"; "CORE_PLUS"];
cells = cell(numel(modes), 1);
for index = 1:numel(modes)
    subset = trials(trials.mode == modes(index), :);
    cells{index} = table(modes(index), mean(subset.score_call_count), ...
        mean(subset.svd_call_count), median(subset.runtime_sec), ...
        percentile_local(subset.runtime_sec, 90), ...
        'VariableNames', {'mode','mean_score_calls','mean_svd_calls', ...
        'median_runtime_sec','p90_runtime_sec'});
end
complexity = vertcat(cells{:});
end

function decision = decision_local(trials)
lite = trials(trials.mode == "CORE_LITE", :);
plus = trials(trials.mode == "CORE_PLUS", :);
off = lite(lite.K == 1 & lite.profile_id ~= "C1_ON_GRID", :);
off_b0 = fixed_grid_rmse_local(off);
[wins, ~, losses] = paired_outcomes_local(off.joint_rmse_deg, off_b0);
lite_pass = all(lite.fit_valid) && ...
    ~any(lite.truth_used_in_fit_flag) && ...
    ~any(lite.tracking_input_used_flag | lite.cross_cpi_data_used_flag) && ...
    median(off.joint_rmse_deg) < median(off_b0) && wins > losses;
k2_lite = lite(lite.K == 2, :);
k2_plus = plus(plus.K == 2, :);
[plus_wins, ~, plus_losses] = paired_outcomes_local( ...
    k2_plus.joint_rmse_deg, k2_lite.joint_rmse_deg);
plus_pass = lite_pass && all(plus.fit_valid) && ...
    median(k2_plus.joint_rmse_deg) <= median(k2_lite.joint_rmse_deg) && ...
    plus_wins >= plus_losses;
if plus_pass
    state = 'STAGE8_CORE_V2_2_FINAL_FREEZE_PASS_CORE_PLUS_OPTIONAL';
elseif lite_pass
    state = 'STAGE8_CORE_V2_2_FINAL_FREEZE_PASS_CORE_LITE_ONLY';
else
    state = 'STAGE8_CORE_V2_2_FINAL_KNOWN_K_CORE_NOT_CONFIRMED';
end
decision = struct('core_lite_final_pass', lite_pass, ...
    'core_plus_optional_confirmed', plus_pass, 'final_state', state, ...
    'k1_off_grid_wins', wins, 'k1_off_grid_losses', losses, ...
    'k2_plus_wins', plus_wins, 'k2_plus_losses', plus_losses);
end

function value = percentile_local(values, percentile)
values = sort(values(:));
if isempty(values), value = NaN; return; end
position = 1 + (numel(values) - 1) * percentile / 100;
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    value = values(lower) + (position - lower) * ...
        (values(upper) - values(lower));
end
end
