function result = test_projected_k2_snr_fixture(context)
%TEST_PROJECTED_K2_SNR_FIXTURE Check zero and nonzero separation behavior.

fixture = stage8_k2_snr_test_fixture(context);
base = fixture.original_trials{1};
model = base.model;
center = mean(base.truth_angles_deg, 1);
zero_truth = [center; center];
zero_manifold = build_stage8_element_manifold(zero_truth, model);
zero_source = ones(2, size(base.signal_element, 2));
zero_element = zero_manifold.A * zero_source;
C_b = model.C_I;
C_w = model.T_I * C_b * model.T_I';
zero_white = model.T_I * (model.W_I' * zero_element);
noise_white = model.T_I * (model.W_I' * base.noise_element);
zero_metric = stage8_k2_snr_projected_k2_metric( ...
    zero_white, noise_white, C_w, zero_truth, model);
nonzero_white = model.T_I * (model.W_I' * base.signal_element);
nonzero_metric = stage8_k2_snr_projected_k2_metric( ...
    nonzero_white, noise_white, C_w, base.truth_angles_deg, model);
assert(zero_metric.signal_energy <= ...
    1e-20 * max(1, norm(zero_white, 'fro') ^ 2), ...
    'test_projected_k2_snr_fixture:ZeroSeparation', ...
    'A zero-separation signal did not collapse under center projection.');
assert(isfinite(nonzero_metric.signal_energy) && ...
    nonzero_metric.signal_energy >= 0 && ...
    isfinite(nonzero_metric.noise_expected_energy) && ...
    nonzero_metric.noise_expected_energy > 0, ...
    'test_projected_k2_snr_fixture:NonzeroSeparation', ...
    'The nonzero-separation projected metric is invalid.');
result = struct('pass', true, ...
    'zero_projected_signal_energy', zero_metric.signal_energy, ...
    'nonzero_projected_signal_energy', nonzero_metric.signal_energy);
end
