function result = test_white_snr_scaling_contract(context)
%TEST_WHITE_SNR_SCALING_CONTRACT Exercise four profiles at all three targets.

fixture = stage8_k2_snr_test_fixture(context);
registry = fixture.white_registry;
selectors = ["P1", "WHITE"; "P2", "WHITE"; ...
    "P3", "STAGE5_TOEPLITZ_CORRELATED"; ...
    "P4", "STAGE5_TOEPLITZ_CORRELATED"];
errors = zeros(12, 1);
cursor = 0;
for profile_index = 1:size(selectors, 1)
    for target = context.constants.white_snr_targets_db
        selected = registry.profile_id == selectors(profile_index, 1) & ...
            registry.noise_profile_id == selectors(profile_index, 2) & ...
            registry.L == 4 & ...
            registry.white_beamspace_snr_target_db == target;
        spec = registry(selected, :);
        assert(height(spec) == 1, ...
            'test_white_snr_scaling_contract:Selector', ...
            'A scaling fixture selector is not unique.');
        trial = stage8_k2_snr_generate_white_control_trial(spec, context);
        metric = stage8_k2_snr_compute_metrics(trial);
        cursor = cursor + 1;
        errors(cursor) = abs(metric.white_beam_snr_expected_db - target);
    end
end
assert(max(errors) <= context.constants.snr_db_tolerance, ...
    'test_white_snr_scaling_contract:Tolerance', ...
    'Expected white SNR missed a registered target.');
result = struct('pass', true, 'case_count', cursor, ...
    'max_error_db', max(errors));
end
