function result = test_paired_seed_and_source_shape(context)
%TEST_PAIRED_SEED_AND_SOURCE_SHAPE Verify all original/new pair invariants.

fixture = stage8_k2_snr_test_fixture(context);
registry = fixture.white_registry;
max_source_error = 0;
max_noise_error = 0;
max_phase_error = 0;
for index = 1:height(registry)
    original = fixture.original_trials{index};
    white = stage8_k2_snr_generate_white_control_trial( ...
        registry(index, :), context);
    max_source_error = max(max_source_error, norm( ...
        original.source_unscaled / norm(original.source_unscaled, 'fro') - ...
        white.source_unscaled / norm(white.source_unscaled, 'fro'), 'fro'));
    max_noise_error = max(max_noise_error, ...
        norm(original.noise_element - white.noise_element, 'fro'));
    max_phase_error = max(max_phase_error, ...
        abs(original.source_phase_rad - white.source_phase_rad));
    assert(registry.source_seed(index) == ...
        context.original_registry.source_seed(index) && ...
        registry.noise_seed(index) == ...
        context.original_registry.noise_seed(index), ...
        'test_paired_seed_and_source_shape:Seed', ...
        'A paired registry row changed a source or noise seed.');
end
assert(max([max_source_error, max_noise_error, max_phase_error]) <= 1e-13, ...
    'test_paired_seed_and_source_shape:Pairing', ...
    'Paired source shape, phase, or noise realization changed.');
result = struct('pass', true, 'pair_count', height(registry), ...
    'max_normalized_source_error', max_source_error, ...
    'max_noise_error', max_noise_error, 'max_phase_error', max_phase_error);
end
