function result = test_four_trial_smoke(context)
%TEST_FOUR_TRIAL_SMOKE Run the registered P1-P4 0 dB white-control smoke set.

registry = stage8_k2_snr_test_fixture(context).white_registry;
selectors = ["P1", "WHITE"; "P2", "WHITE"; ...
    "P3", "STAGE5_TOEPLITZ_CORRELATED"; ...
    "P4", "STAGE5_TOEPLITZ_CORRELATED"];
rows_cell = cell(4, 1);
for index = 1:4
    selected = registry.profile_id == selectors(index, 1) & ...
        registry.noise_profile_id == selectors(index, 2) & ...
        registry.L == 4 & registry.white_beamspace_snr_target_db == 0;
    spec = registry(selected, :);
    assert(height(spec) == 1, 'test_four_trial_smoke:Selector', ...
        'A smoke selector did not resolve to one trial.');
    trial = stage8_k2_snr_generate_white_control_trial(spec, context);
    metrics = stage8_k2_snr_compute_metrics(trial);
    rows_cell{index} = stage8_k2_snr_evaluate_trial( ...
        spec, trial, metrics, context);
    rows = rows_cell{index};
    tangent = rows(rows.method_id == "TANGENT_PROFILE_SAFE", :);
    assert(height(rows) == 3 && all(rows.fit_status ~= "NOT_RUN") && ...
        ~any(rows.truth_used_in_fit_flag) && height(tangent) == 1 && ...
        tangent.fit_valid && isfinite(tangent.RSS) && ...
        isfinite(tangent.loglik), ...
        'test_four_trial_smoke:Outcome', ...
        'A smoke trial lacks explicit outcomes or a usable safe Tangent fit.');
end
all_rows = vertcat(rows_cell{:});
result = struct('pass', true, 'trial_count', 4, ...
    'method_row_count', height(all_rows), ...
    'tangent_valid_count', nnz(all_rows.method_id == ...
    "TANGENT_PROFILE_SAFE" & all_rows.fit_valid));
end
