function result = test_whitening_identity(context)
%TEST_WHITENING_IDENTITY Verify frozen whitener rank and registered numerical quality.

noise_ids = unique(context.original_registry.noise_profile_id, 'stable');
residuals = zeros(numel(noise_ids), 1);
for index = 1:numel(noise_ids)
    model = resolve_stage8_measurement_model( ...
        context.plan.measurement_model_registry, ...
        context.primary_measurement_config_id, noise_ids(index));
    assert(size(model.T_I, 1) == model.whitening_rank, ...
        'test_whitening_identity:Rank', ...
        'The whitener row count differs from model.whitening_rank.');
    C_w = model.T_I * model.C_I * model.T_I';
    residuals(index) = norm(C_w - eye(model.whitening_rank), 'fro') / ...
        sqrt(model.whitening_rank);
    assert(isfinite(residuals(index)), ...
        'test_whitening_identity:Finite', ...
        'A frozen whitener has a nonfinite numerical-quality residual.');
    fprintf(['T4 %s rank=%d residual=%.17g tolerance=%.17g ', ...
        'trace=%.17g\n'], ...
        noise_ids(index), model.whitening_rank, residuals(index), ...
        context.constants.whitening_tolerance, real(trace(C_w)));
end
assert(max(residuals) <= context.constants.whitening_tolerance, ...
    'test_whitening_identity:Tolerance', ...
    'A frozen whitener exceeds the registered numerical-quality tolerance.');
result = struct('pass', true, 'max_residual', max(residuals));
end
