function result = test_validation_parameter_noise_seeds_disjoint()
%TEST_VALIDATION_PARAMETER_NOISE_SEEDS_DISJOINT Check three RNG role blocks.

plan = build_stage8_validation_plan();
registry = materialize_stage8_k1_validation_plan(plan);
parameter = unique(registry.parameter_seed);
noise = unique(registry.element_noise_seed);
auxiliary = unique(registry.separation_auxiliary_seed);
pass = plan.K1.seed_block_stride >= 3000 && ...
    numel(parameter) == 6000 && numel(noise) == 6000 && ...
    numel(auxiliary) == 6000 && isempty(intersect(parameter, noise)) && ...
    isempty(intersect(parameter, auxiliary)) && ...
    isempty(intersect(noise, auxiliary));
assert(pass, 'test_validation_parameter_noise_seeds_disjoint:Failed', ...
    'Validation parameter/noise/auxiliary RNG roles overlap.');
result = table(pass, plan.K1.seed_block_stride, ...
    'VariableNames', {'pass_flag','seed_block_stride'});
end
