function result = test_mean_contract_failure_writes_cell_artifact(fixture)
%TEST_MEAN_CONTRACT_FAILURE_WRITES_CELL_ARTIFACT Preserve failure metadata.

folder = tempname;
mkdir(folder);
cleanup = onCleanup(@() rmdir(folder, 's'));
first = build_stage8_1a_mini_cell(fixture.mini, 2);
second = first;
second.global_cell_index = 2;
second.calibration_cell_id = 'MINI_CALIBRATION_CELL_2';
second.cell_input_hash = stage8_stable_hash(first.cell_input_hash, 2);
opts = struct('cell_indices', [1;2], 'checkpoint_dir', folder, ...
    'cell_options', struct('Bboot_per_cell', 2, ...
    'fit_callback', @tampered_fit_local, ...
    'bootstrap_callback', @unexpected_bootstrap_local, ...
    'initialization_callback', @stage8_1a_mini_initialization_callback));
shard = run_stage8_1_calibration_shard([first;second], ...
    fixture.mini.domain, fixture.mini.registry, ...
    fixture.mini.stage5_locked, opts);
checkpoint = fullfile(folder, 'stage8_1_cell_001.mat');
loaded = load(checkpoint, 'artifact');
artifact = loaded.artifact;
failure = artifact.failure_details(1, :);
pass = numel(shard.artifacts) == 1 && ...
    strcmp(shard.status, 'CALIBRATION_SHARD_FAILURE') && ...
    strcmp(artifact.status, ...
    'CALIBRATION_CELL_BOOTSTRAP_MEAN_CONTRACT_FAILURE') && ...
    artifact.failure_count == 1 && all(isnan(artifact.lambda_samples)) && ...
    isnan(artifact.q_cell_0p95) && failure.bootstrap_index == 1 && ...
    failure.bootstrap_seed == first.bootstrap_seed_start && ...
    failure.failure_status == "STRUCTURAL_MANIFOLD_IDENTITY_FAILURE" && ...
    failure.G_absolute_residual > 0 && failure.G_backward_bound >= 0 && ...
    failure.G_max_bound_ratio > 1 && ...
    failure.model_hash == string(first.fixed_measurement_hash) && ...
    failure.cell_input_hash == string(first.cell_input_hash) && ...
    failure.mean_contract_version == ...
    "STAGE8_BOOTSTRAP_MEAN_BACKWARD_ERROR_V1" && ...
    strcmp(artifact.cell_artifact_hash, ...
    stage8_calibration_artifact_hash(artifact)) && ...
    ~isfile(fullfile(folder, 'stage8_1_cell_002.mat'));
assert(pass, 'test_mean_contract_failure_writes_cell_artifact:Failed', ...
    'A mean-contract failure did not write and stop at an auditable cell artifact.');
result = table(pass, artifact.failure_count, failure.G_max_bound_ratio, ...
    failure.mean_max_bound_ratio, 'VariableNames', ...
    {'pass_flag','failure_count','G_max_bound_ratio','mean_max_bound_ratio'});
clear cleanup
end

function [fit, debug] = tampered_fit_local(K, index, data, context, model)
[fit, debug] = stage8_1a_mock_fit_callback( ...
    K, index, data, context, model);
if K == 1 && index == 0
    fit.G_hat(1, 1) = fit.G_hat(1, 1) + 1;
end
end

function [data, debug] = unexpected_bootstrap_local(varargin) %#ok<STOUT>
error('test_mean_contract_failure_writes_cell_artifact:BootstrapCalled', ...
    'Bootstrap generation must not run after a failed preflight.');
end
