function result = test_threshold_lookup_has_no_scene_inputs()
%TEST_THRESHOLD_LOOKUP_HAS_NO_SCENE_INPUTS Verify the strict two-input API.

[artifact, contract] = build_stage8_1a_threshold_fixture( ...
    "PRIMARY_RECT_E14_A31");
artifact.q_global = 7;
artifact.q_global_hex = num2hex(7);
artifact.threshold_artifact_hash = stage8_threshold_artifact_hash(artifact);
threshold = lookup_locked_lrt_threshold( ...
    'PRIMARY_RECT_E14_A31', artifact, contract);
stage8_assert_error(@() lookup_locked_lrt_threshold( ...
    'PRIMARY_RECT_E14_A31', artifact, setfield(contract, ...
    'scene_id', 'FORBIDDEN')), ... %#ok<SFLD>
    'validate_stage8_threshold_contract:ForbiddenInput');
pass = nargin('lookup_locked_lrt_threshold') == 3 && ...
    threshold.q_global == 7;
assert(pass, 'test_threshold_lookup_has_no_scene_inputs:Failed', ...
    'Threshold lookup accepted more than the frozen two inputs.');
result = table(pass, ...
    'VariableNames', {'pass_flag'});
end
