function result = test_validation_threshold_lookup_only()
%TEST_VALIDATION_THRESHOLD_LOOKUP_ONLY Check locked hashes reach every row.

fixture = build_stage8_1a_mini_fixture();
plan = build_stage8_validation_plan();
plan.K1.measurement_config_ids = ["MINI_PRIMARY";"MINI_PARENT"];
thresholds = thresholds_local();
output = run_stage8_1_k1_validation(plan, fixture.domain, ...
    fixture.registry, thresholds, fixture.stage5_locked, struct( ...
    'max_common_trials_per_stratum', 1, ...
    'evaluation_callback', @evaluation_local));
expected = ["MINI_PRIMARY_THRESHOLD";"MINI_PARENT_THRESHOLD"];
pass = output.threshold_lookup_only_flag && ...
    all(ismember(unique(output.trials.threshold_calibration_hash), expected));
assert(pass, 'test_validation_threshold_lookup_only:Failed', ...
    'Validation did not use only the supplied locked thresholds.');
result = table(pass, 'VariableNames', {'pass_flag'});
end

function evaluation = evaluation_local(~, ~, ~, ~)
evaluation = struct('state', 'K1', 'lambda_12', 0, ...
    'fit1_validity_status', 'VALID_FOR_LRT', ...
    'fit2_validity_status', 'VALID_FOR_LRT', ...
    'separation_status', 'NOT_RUN_LRT_DID_NOT_EXCEED_THRESHOLD');
end

function thresholds = thresholds_local()
base = struct('measurement_config_id', '', 'q_global', 5, ...
    'alpha', 0.05, 'calibration_hash', '', ...
    'threshold_status', 'LOCKED_BOOTSTRAP_THRESHOLD', ...
    'threshold_policy', ...
    'ONE_GLOBAL_THRESHOLD_PER_FIXED_MEASUREMENT_CONFIG');
thresholds = repmat(base, 2, 1);
thresholds(1).measurement_config_id = 'MINI_PRIMARY';
thresholds(1).calibration_hash = 'MINI_PRIMARY_THRESHOLD';
thresholds(2).measurement_config_id = 'MINI_PARENT';
thresholds(2).calibration_hash = 'MINI_PARENT_THRESHOLD';
end
