function result = test_stage8_1_writer_determinism()
%TEST_STAGE8_1_WRITER_DETERMINISM Exclude runtime from bundle identity.

folder1 = tempname;
folder2 = tempname;
folder3 = tempname;
mkdir(folder1);
mkdir(folder2);
mkdir(folder3);
cleanup = onCleanup(@() cleanup_local(folder1, folder2, folder3));
first = write_stage8_1_results_bundle( ...
    build_stage8_1a_writer_bundle(1), folder1, struct());
second = write_stage8_1_results_bundle( ...
    build_stage8_1a_writer_bundle(999), folder2, struct());
finalized = finalize_smoke_local(folder3);
pass = strcmp(first.stage8_1_evidence_bundle_hash, ...
    second.stage8_1_evidence_bundle_hash) && ...
    isequal(first.manifest.relative_path, second.manifest.relative_path) && ...
    isequal(first.manifest.sha256, second.manifest.sha256) && ...
    ~finalized.stage8_2_executed_flag && ...
    finalized.stage8_2_separate_authorization_required_flag;
assert(pass, 'test_stage8_1_writer_determinism:Failed', ...
    'Runtime changed the deterministic Stage8.1 bundle identity.');
result = table(pass, string(first.stage8_1_evidence_bundle_hash), ...
    'VariableNames', {'pass_flag','bundle_hash'});
clear cleanup
end

function evidence = finalize_smoke_local(folder)
fixture = build_stage8_1a_mini_fixture();
cell_input = build_stage8_1a_mini_cell(fixture, 2);
[artifact, ~] = run_stage8_1_calibration_cell( ...
    cell_input, fixture.domain, fixture.registry, fixture.stage5_locked, ...
    struct('Bboot_per_cell', 2, ...
    'fit_callback', @stage8_1a_mock_fit_callback, ...
    'initialization_callback', @stage8_1a_mini_initialization_callback));
calibration_cells = table(string(cell_input.measurement_config_id), ...
    string(cell_input.calibration_cell_id), cell_input.global_cell_index, ...
    string(cell_input.noise_profile_id), string(cell_input.model_key), ...
    string(cell_input.fixed_measurement_hash), ...
    cell_input.calibration_data_seed, cell_input.bootstrap_seed_start, ...
    cell_input.bootstrap_seed_end, 'VariableNames', ...
    {'measurement_config_id','calibration_cell_id','global_cell_index', ...
    'noise_profile_id','model_key','fixed_measurement_hash', ...
    'calibration_data_seed','bootstrap_seed_start','bootstrap_seed_end'});
source_manifest = table("MINI_SOURCE", "MINI_HASH", ...
    'VariableNames', {'path','sha256'});
registry = fixture.registry;
registry.registry_hash = 'MINI_MEASUREMENT_REGISTRY';
validation_plan = build_stage8_validation_plan();
validation_plan.K1.measurement_config_ids = ...
    ["MINI_PRIMARY";"MINI_PARENT"];
validation_plan.K1.primary_measurement_config_id = 'MINI_PRIMARY';
validation_plan.K1.sensitivity_measurement_config_id = 'MINI_PARENT';
plan = struct('measurement_model_registry', registry, ...
    'identity', struct('stage8_stable_code_identity_hash', ...
    'MINI_STAGE8_SOURCE', ...
    'source_manifest', source_manifest), ...
    'stage8_plan_hash', 'MINI_STAGE8_PLAN', ...
    'stage8_calibration_plan_hash', 'MINI_CALIBRATION_PLAN', ...
    'stage8_validation_plan_hash', 'MINI_VALIDATION_PLAN', ...
    'stage8_holdout_plan_hash', 'MINI_HOLDOUT_PLAN', ...
    'stage7_1_evidence_bundle_hash', 'MINI_STAGE7_1', ...
    'calibration', struct('cells', calibration_cells, ...
    'Bboot_per_cell', 2), 'validation', validation_plan);
[thresholds, contract, threshold_set_hash] = ...
    build_stage8_1a_threshold_fixture( ...
    validation_plan.K1.measurement_config_ids);
trial_config = string({thresholds.measurement_config_id}).';
trial_hash = string({thresholds.threshold_artifact_hash}).';
trials = table(trial_config, trial_hash, 'VariableNames', ...
    {'measurement_config_id','threshold_artifact_hash'});
tiny = table("OVERALL", 0, 'VariableNames', {'summary_scope','rate'});
paired = table("MINI_TRIAL", "K1", "K1", false, false, false, ...
    'VariableNames', {'common_trial_id','primary_state', ...
    'full_parent_state','false_split_discordance', ...
    'false_resolved_discordance','nondecision_discordance'});
validation = struct('trials', trials, 'summary', tiny, ...
    'paired_sensitivity', paired, 'threshold_contract', contract, ...
    'threshold_set_hash', threshold_set_hash, ...
    'gate', struct('gate_status', 'STAGE8_1_K1_VALIDATION_PASS', ...
    'gate_pass', true), 'runtime', 0);
evidence = run_stage8_1_finalize(plan, cell_input, artifact, ...
    thresholds, validation, folder, struct());
end

function cleanup_local(folder1, folder2, folder3)
if isfolder(folder1), rmdir(folder1, 's'); end
if isfolder(folder2), rmdir(folder2, 's'); end
if isfolder(folder3), rmdir(folder3, 's'); end
end
