function result = test_formal_shard_materializes_only_requested_cells()
%TEST_FORMAL_SHARD_MATERIALIZES_ONLY_REQUESTED_CELLS Check subset execution.

fixture = build_stage8_1a_mini_fixture();
plan = build_stage8_1a_mini_calibration_plan(fixture, 3);
[cells, debug] = materialize_stage8_calibration_cells( ...
    plan, fixture.domain, fixture.registry, fixture.stage5_locked, ...
    struct('formal_run', true, 'materialization_mode', 'FORMAL_SHARD', ...
    'cell_indices', 2, 'source_identity', 'SHARD_TEST_SOURCE'));
pass = numel(cells) == 1 && cells.global_cell_index == 2 && ...
    debug.materialized_cell_count == 1 && ...
    strcmp(debug.materialization_mode, 'FORMAL_SHARD');
assert(pass, 'test_formal_shard_materializes_only_requested_cells:Failed', ...
    'FORMAL_SHARD materialized cells outside the requested subset.');
result = table(pass, debug.materialized_cell_count, ...
    'VariableNames', {'pass_flag','materialized_cell_count'});
end
