function result = test_bootstrap_label_matching()
%TEST_BOOTSTRAP_LABEL_MATCHING Verify minimum-cost permutation matching.

reference = [7.8,9.9;8.2,10.1];
bootstrap = [8.19,10.09;7.81,9.91];
[matched, assignment, info] = match_bootstrap_target_labels( ...
    bootstrap, reference);
pass = isequal(assignment, [2,1]) && ...
    norm(matched - bootstrap([2,1], :), 'fro') == 0 && ...
    ~info.truth_used_flag;
assert(pass, 'test_bootstrap_label_matching:Failed', ...
    'Bootstrap labels were not matched by minimum two-dimensional cost.');
result = table(pass, info.total_squared_angular_cost, ...
    'VariableNames', {'pass_flag','matching_cost'});
end
