function result = test_stage8_no_stage7_selection_mutation(repo_dir)
%TEST_STAGE8_NO_STAGE7_SELECTION_MUTATION Verify the frozen Stage7 scope.

scope = ['beamspace_ml_v18/source/stepwise_signal_model/steps/', ...
    'step_12_5_exact_subset_fim_beam_design'];
[status, output] = system(sprintf( ...
    'git -C "%s" status --porcelain=v1 --untracked-files=all -- "%s"', ...
    repo_dir, scope));
pass = status == 0 && isempty(strtrim(output));
assert(pass, 'test_stage8_no_stage7_selection_mutation:Failed', ...
    'The frozen Stage7 implementation or evidence was modified.');
result = table(pass, ...
    'VariableNames', {'pass_flag'});
end
