function result = test_bootstrap_sample_uses_fitted_k1()
%TEST_BOOTSTRAP_SAMPLE_USES_FITTED_K1 Verify mean and fitted ML scale.

fit1 = struct('K', 1, 'G_hat', [1;2], ...
    'S_hat', [1+1j,2-0.5j], 'sigma2_hat', 0.25, ...
    'estimate_returned_flag', true, ...
    'fixed_measurement_hash', 'BOOTSTRAP_FIXTURE', ...
    'effective_whitening_dimension', 2, 'snapshot_count', 2, ...
    'phase_factor', 1);
[sample, debug] = simulate_bootstrap_under_k1(fit1, struct('seed', 19));
expected = fit1.G_hat * fit1.S_hat + ...
    sqrt(fit1.sigma2_hat) * debug.standard_complex_noise;
error_value = norm(sample.Zseq_white - expected, 'fro');
pass = error_value == 0 && debug.sigma2_hat == fit1.sigma2_hat;
assert(pass, 'test_bootstrap_sample_uses_fitted_k1:Failed', ...
    'The bootstrap sample did not use fitted G, S, and sigma2.');
result = table(pass, error_value, ...
    'VariableNames', {'pass_flag','absolute_error'});
end
