function result = test_group_noise_invalid_does_not_use_unit_fallback()
%TEST_GROUP_NOISE_INVALID_DOES_NOT_USE_UNIT_FALLBACK Ban alpha_q=1 fallback.

contract = validate_stage8_group_noise_scale(NaN);
source = string(fileread(fullfile(fileparts(fileparts( ...
    mfilename('fullpath'))), 'common', ...
    'build_stage8_initialization_context_from_data.m')));
pass = isnan(contract.scale) && ~contract.unit_fallback_used_flag && ...
    ~contains(source, 'alpha_q = 1');
assert(pass, 'test_group_noise_invalid_does_not_use_unit_fallback:Failed', ...
    'Invalid group-noise scale still uses a silent unit fallback.');
result = table(pass, contract.scale, ...
    'VariableNames', {'pass_flag','invalid_scale'});
end
