function result = test_stage8_validation_holdout_seed_isolation()
%TEST_STAGE8_VALIDATION_HOLDOUT_SEED_ISOLATION Verify all registered seeds.

validation = build_stage8_validation_plan();
holdout = build_stage8_holdout_plan();
seeds = [validation.K1.seed,validation.K2.seed,holdout.K1.seed, ...
    holdout.K2.seed,holdout.mismatch.seed];
pass = numel(unique(seeds)) == numel(seeds) && ...
    isequal(seeds, [20260722,20260724,20260723,20260725,20260726]) && ...
    ~holdout.K1.threshold_recalibration_allowed && ...
    ~holdout.K2.threshold_recalibration_allowed;
assert(pass, 'test_stage8_validation_holdout_seed_isolation:Failed', ...
    'Validation and independent holdout seeds are not isolated.');
result = table(pass, ...
    'VariableNames', {'pass_flag'});
end
