function result = test_stage8_calibration_split_isolation()
%TEST_STAGE8_CALIBRATION_SPLIT_ISOLATION Verify cells, count, and seed block.

calibration = build_stage8_calibration_plan();
validation = build_stage8_validation_plan();
holdout = build_stage8_holdout_plan();
seeds = calibration.cells.seed;
other = [validation.K1.seed,validation.K2.seed, ...
    holdout.K1.seed,holdout.K2.seed,holdout.mismatch.seed];
pass = height(calibration.cells) == 300 && ...
    calibration.total_bootstrap_count == 59700 && ...
    isempty(intersect(seeds, other)) && ...
    strcmp(calibration.execution_status, 'FROZEN_NOT_EXECUTED_STAGE8_0');
assert(pass, 'test_stage8_calibration_split_isolation:Failed', ...
    'Calibration cells or seed isolation changed.');
result = table(pass, height(calibration.cells), ...
    calibration.total_bootstrap_count, 'VariableNames', ...
    {'pass_flag','cell_count','planned_bootstrap_count'});
end
