function result = test_calibration_data_and_bootstrap_seeds_disjoint(plan)
%TEST_CALIBRATION_DATA_AND_BOOTSTRAP_SEEDS_DISJOINT Check seed namespaces.

if nargin < 1, plan = build_stage8_calibration_plan(); end
data_seeds = plan.cells.calibration_data_seed;
bootstrap_seeds = reshape((plan.cells.bootstrap_seed_start + ...
    (0:plan.Bboot_per_cell - 1)).', [], 1);
pass = numel(unique(data_seeds)) == 300 && ...
    numel(unique(bootstrap_seeds)) == 59700 && ...
    isempty(intersect(data_seeds, bootstrap_seeds));
assert(pass, 'test_calibration_data_and_bootstrap_seeds_disjoint:Failed', ...
    'Calibration data and bootstrap seeds are not disjoint.');
result = table(pass, numel(data_seeds), numel(bootstrap_seeds), ...
    'VariableNames', {'pass_flag','data_seed_count','bootstrap_seed_count'});
end
