function result = test_committed_threshold_loader_requires_tracked_artifacts()
%TEST_COMMITTED_THRESHOLD_LOADER_REQUIRES_TRACKED_ARTIFACTS Verify one Stage8.1A3 contract.

result = stage8_1a3_contract_case('committed_threshold_loader_requires_tracked_artifacts');
end
