function result = test_stage8_1b_two_commit_lifecycle(~)
%TEST_STAGE8_1B_TWO_COMMIT_LIFECYCLE Execute the miniature split lifecycle.

checkpoint_root = tempname;
artifact_root = tempname;
mkdir(checkpoint_root);
mkdir(artifact_root);
cleanup = onCleanup(@() cleanup_local(checkpoint_root, artifact_root));
fixture = build_stage8_1a_two_commit_fixture();
indices = (1:height(fixture.plan.calibration.cells)).';
write_stage8_checkpoint_fixture(checkpoint_root, ...
    fixture.plan.calibration, fixture.contract, indices);
frozen = run_stage8_1_freeze_threshold_evidence( ...
    tempdir, checkpoint_root, artifact_root, struct( ...
    'formal_run', false, 'frozen_plan', fixture.plan));
stage8_assert_error(@() run_stage8_1_freeze_threshold_evidence( ...
    tempdir, checkpoint_root, artifact_root, struct( ...
    'formal_run', false, 'frozen_plan', fixture.plan)), ...
    'write_stage8_1_registry_bundle:ExistingArtifact');
no_validation_placeholder = ~isfolder(fullfile(artifact_root, 'results'));
[thresholds, calibration] = load_stage8_1_locked_thresholds( ...
    tempdir, artifact_root, fixture.plan, struct( ...
    'formal_run', false, 'require_tracked_artifacts', false));
roundtrip = all(arrayfun(@(item) isequal( ...
    num2hex(item.q_global), item.q_global_hex), thresholds));
stage8_assert_error(@() load_stage8_1_locked_thresholds( ...
    tempdir, artifact_root, fixture.plan, struct( ...
    'formal_run', true, 'require_tracked_artifacts', false)), ...
    ['load_stage8_1_locked_thresholds:', ...
    'FORMAL_TRACKED_CALIBRATION_EVIDENCE_REQUIRED']);
stage8_assert_error(@() ...
    run_stage8_1_k1_validation_from_frozen_thresholds( ...
    tempdir, struct('formal_run', true, ...
    'require_tracked_artifacts', false)), ...
    ['run_stage8_1_k1_validation_from_frozen_thresholds:', ...
    'FORMAL_TRACKED_CALIBRATION_EVIDENCE_REQUIRED']);
stage8_assert_error(@() run_stage8_1_finalize( ...
    struct(), struct(), struct(), artifact_root, struct( ...
    'formal_run', true, 'require_tracked_artifacts', false)), ...
    ['run_stage8_1_finalize:', ...
    'FORMAL_TRACKED_CALIBRATION_EVIDENCE_REQUIRED']);
[before, before_hash] = ...
    capture_stage8_1_calibration_snapshot(artifact_root);
validation = run_stage8_1_k1_validation_from_frozen_thresholds( ...
    tempdir, struct('formal_run', false, ...
    'require_tracked_artifacts', false, ...
    'calibration_root', artifact_root, ...
    'frozen_plan', fixture.plan, ...
    'evaluation_callback', @evaluation_local, ...
    'Bsep', 2, 'run_separation', false));
validated = validate_stage8_1_validation_output( ...
    fixture.plan, calibration, validation);
finalized = run_stage8_1_finalize(fixture.plan, calibration, ...
    validation, artifact_root, struct('formal_run', false, ...
    'require_tracked_artifacts', false));
stage8_assert_error(@() run_stage8_1_finalize( ...
    fixture.plan, calibration, validation, artifact_root, struct( ...
    'formal_run', false, 'require_tracked_artifacts', false)), ...
    'write_stage8_1_registry_bundle:ExistingArtifact');
[after, after_hash] = ...
    capture_stage8_1_calibration_snapshot(artifact_root);
calibration_unchanged = isequal(before, after) && ...
    strcmp(before_hash, after_hash);
committed_preflight = strcmp( ...
    validation.committed_threshold_preflight_status, ...
    'COMMITTED_THRESHOLD_PREFLIGHT_PASS');
final_references_calibration = strcmp( ...
    finalized.calibration_evidence_bundle_hash, ...
    frozen.calibration_evidence_bundle_hash) && ...
    all(finalized.manifest.calibration_evidence_bundle_hash == ...
    string(frozen.calibration_evidence_bundle_hash));
pass = no_validation_placeholder && roundtrip && ...
    committed_preflight && ~validated.recomputed_primary_gate_pass && ...
    calibration_unchanged && ...
    final_references_calibration && ~finalized.stage8_2_executed_flag && ...
    finalized.stage8_2_separate_authorization_required_flag;
assert(pass, 'test_stage8_1b_two_commit_lifecycle:Failed', ...
    'The executable miniature two-commit lifecycle failed.');
result = table(pass, no_validation_placeholder, roundtrip, ...
    committed_preflight, calibration_unchanged, ...
    final_references_calibration, ...
    'VariableNames', {'pass_flag','no_validation_placeholder', ...
    'threshold_roundtrip','committed_threshold_preflight', ...
    'calibration_bytes_unchanged', ...
    'final_references_calibration'});
clear cleanup
end

function evaluation = evaluation_local(~, ~, ~, ~)
evaluation = struct('state', 'K1', 'lambda_12', 0, ...
    'fit1_validity_status', 'VALID_FOR_LRT', ...
    'fit2_validity_status', 'VALID_FOR_LRT', ...
    'separation_status', 'NOT_RUN_MINIATURE_CONTRACT');
end

function cleanup_local(checkpoint_root, artifact_root)
if isfolder(checkpoint_root), rmdir(checkpoint_root, 's'); end
if isfolder(artifact_root), rmdir(artifact_root, 's'); end
end
