function result = test_stage8_1_artifact_registry()
%TEST_STAGE8_1_ARTIFACT_REGISTRY Check every required evidence path.

registry = stage8_1_artifact_registry();
required = [ ...
    "calibration/stage8_1_plan_registry.csv"; ...
    "calibration/stage8_1_measurement_registry.csv"; ...
    "calibration/stage8_1_calibration_cells.csv"; ...
    "calibration/stage8_1_seed_registry.csv"; ...
    "calibration/stage8_1_cell_results.csv"; ...
    "calibration/stage8_1_lambda_samples.csv"; ...
    "calibration/stage8_1_locked_thresholds.csv"; ...
    "calibration/stage8_1_complexity.csv"; ...
    "calibration/stage8_1_provenance.csv"; ...
    "calibration/stage8_1_source_manifest.csv"; ...
    "calibration/stage8_1_evidence_manifest.csv"; ...
    "results/stage8_1_k1_validation_trials.csv"; ...
    "results/stage8_1_k1_validation_summary.csv"; ...
    "results/stage8_1_k1_paired_sensitivity.csv"; ...
    "results/stage8_1_keypoints.csv"; ...
    "results/stage8_1_report.md"; ...
    "results/stage8_1_runtime_diagnostics.csv"];
pass = height(registry.table) == numel(required) && ...
    all(ismember(required, registry.table.relative_path)) && ...
    nnz(registry.table.manifest_self_excluded_flag) == 1 && ...
    nnz(registry.table.runtime_excluded_flag) == 1;
assert(pass, 'test_stage8_1_artifact_registry:Failed', ...
    'The Stage8.1 artifact registry is incomplete.');
result = table(pass, height(registry.table), ...
    'VariableNames', {'pass_flag','artifact_count'});
end
