function result = test_tampered_G_hat_fails_structural_identity(fixture)
%TEST_TAMPERED_G_HAT_FAILS_STRUCTURAL_IDENTITY Reject a changed manifold.

fit = fixture.fit;
fit.G_hat(1, 1) = fit.G_hat(1, 1) + 1;
evaluation = evaluate_stage8_bootstrap_mean_identity(fit, fixture.mini.model);
pass = ~evaluation.overall_pass && ~evaluation.G_identity_pass && ...
    strcmp(evaluation.failure_status, ...
    'STRUCTURAL_MANIFOLD_IDENTITY_FAILURE') && ...
    evaluation.G_max_bound_ratio > 1;
assert(pass, 'test_tampered_G_hat_fails_structural_identity:Failed', ...
    'A materially changed fitted manifold passed the structural contract.');
result = table(pass, evaluation.G_max_bound_ratio, ...
    'VariableNames', {'pass_flag','G_max_bound_ratio'});
end
