function result = test_no_fixed_relative_mean_gate_in_formal_path()
%TEST_NO_FIXED_RELATIVE_MEAN_GATE_IN_FORMAL_PATH Scan production sources.

step_dir = fileparts(fileparts(mfilename('fullpath')));
generator = string(fileread(fullfile( ...
    step_dir, 'common', 'simulate_stage8_element_bootstrap.m')));
helper = string(fileread(fullfile( ...
    step_dir, 'common', 'evaluate_stage8_bootstrap_mean_identity.m')));
relative_comparison = regexp(generator + newline + helper, ...
    ['(?i)(mean\w*relative\w*|relative\w*mean\w*)', ...
    '\s*[<>]=?\s*[0-9]'], 'once');
pass = ~contains(generator, '1e-10') && isempty(relative_comparison) && ...
    contains(generator, 'opts.formal_run && ~mean_identity.overall_pass') && ...
    contains(helper, 'mean_max_bound_ratio <=');
assert(pass, 'test_no_fixed_relative_mean_gate_in_formal_path:Failed', ...
    'The formal bootstrap path contains a fixed relative mean-error gate.');
result = table(pass, 'VariableNames', {'pass_flag'});
end
