function result = ...
    test_associative_roundoff_old_relative_can_exceed_1e10_gate(fixture)
%TEST_ASSOCIATIVE_ROUNDOFF_OLD_RELATIVE_CAN_EXCEED_1E10_GATE Use cell 151.

matches = arrayfun(@(item) item.cell_input.global_cell_index == 151, ...
    fixture.cases);
evaluation = fixture.cases(matches).evaluation;
pass = evaluation.mean_old_relative_residual > 1e-10 && ...
    evaluation.overall_pass && evaluation.mean_max_bound_ratio <= 1;
assert(pass, ...
    'test_associative_roundoff_old_relative_can_exceed_1e10_gate:Failed', ...
    'Cell 151 did not distinguish old relative error from the formal bound.');
result = table(pass, evaluation.mean_old_relative_residual, ...
    evaluation.mean_max_bound_ratio, 'VariableNames', ...
    {'pass_flag','old_relative_mean_error','mean_max_bound_ratio'});
end
