function result = test_stage8_1_writer_determinism()
%TEST_STAGE8_1_WRITER_DETERMINISM Exclude runtime from bundle identity.

folder1 = tempname;
folder2 = tempname;
mkdir(folder1);
mkdir(folder2);
cleanup = onCleanup(@() cleanup_local(folder1, folder2));
first = write_stage8_1_results_bundle( ...
    build_stage8_1a_writer_bundle(1), folder1, struct());
second = write_stage8_1_results_bundle( ...
    build_stage8_1a_writer_bundle(999), folder2, struct());
stage8_assert_error(@() write_stage8_1_results_bundle( ...
    build_stage8_1a_writer_bundle(1), tempdir, ...
    struct('formal_run', true)), ...
    ['write_stage8_1_results_bundle:', ...
    'FORMAL_MONOLITHIC_STAGE8_1_WRITER_FORBIDDEN']);
pass = strcmp(first.stage8_1_evidence_bundle_hash, ...
    second.stage8_1_evidence_bundle_hash) && ...
    isequal(first.manifest.relative_path, second.manifest.relative_path) && ...
    isequal(first.manifest.sha256, second.manifest.sha256);
assert(pass, 'test_stage8_1_writer_determinism:Failed', ...
    'Runtime changed the deterministic Stage8.1 bundle identity.');
result = table(pass, string(first.stage8_1_evidence_bundle_hash), ...
    'VariableNames', {'pass_flag','bundle_hash'});
clear cleanup
end

function cleanup_local(folder1, folder2)
if isfolder(folder1), rmdir(folder1, 's'); end
if isfolder(folder2), rmdir(folder2, 's'); end
end
