function result = test_stage8_1_no_stage8_2_execution(step_dir)
%TEST_STAGE8_1_NO_STAGE8_2_EXECUTION Scan all formal Stage8.1 runners.

if nargin < 1, step_dir = fileparts(fileparts(mfilename('fullpath'))); end
paths = ["run_stage8_1_calibration.m";"run_stage8_1_k1_validation.m"; ...
    "run_stage8_1_finalize.m"];
text_all = "";
for path_index = 1:numel(paths)
    text_all = text_all + newline + lower(string(fileread( ...
        fullfile(step_dir, paths(path_index)))));
end
pass = ~contains(text_all, 'run_stage8_2') && ...
    contains(text_all, 'stage8_2_executed_flag = false') && ...
    contains(text_all, 'separate_authorization_required_flag = true');
stage8_assert_error(@() run_stage8_1_calibration('', struct()), ...
    'run_stage8_1_calibration:Authorization');
plan = build_stage8_validation_plan();
stage8_assert_error(@() run_stage8_1_k1_validation( ...
    plan, struct(), struct(), struct(), struct(), ...
    struct('formal_run', true)), ...
    'run_stage8_1_k1_validation:Authorization');
stage8_assert_error(@() run_stage8_1_finalize( ...
    struct(), struct(), struct(), struct(), struct(), tempdir, ...
    struct('formal_run', true)), ...
    'run_stage8_1_finalize:Authorization');
assert(pass, 'test_stage8_1_no_stage8_2_execution:Failed', ...
    'A Stage8.1 runner can execute Stage8.2.');
result = table(pass, 'VariableNames', {'pass_flag'});
end
