function result = test_stage8_plan_hash_determinism(repo_dir, cfg)
%TEST_STAGE8_PLAN_HASH_DETERMINISM Rebuild the complete locked plan twice.

plan1 = build_stage8_locked_plan(repo_dir, cfg, struct());
plan2 = build_stage8_locked_plan(repo_dir, cfg, struct());
pass = strcmp(plan1.stage8_plan_hash, plan2.stage8_plan_hash) && ...
    strcmp(plan1.stage8_source_tree_hash, plan2.stage8_source_tree_hash) && ...
    strcmp(plan1.stage8_dependency_tree_hash, ...
    plan2.stage8_dependency_tree_hash);
assert(pass, 'test_stage8_plan_hash_determinism:Failed', ...
    'The complete Stage8 locked plan hash is nondeterministic.');
result = table(pass, string(plan1.stage8_plan_hash), ...
    'VariableNames', {'pass_flag','stage8_plan_hash'});
end
