function result = test_stage8_stable_identity_excludes_runtime_head(repo_dir)
%TEST_STAGE8_STABLE_IDENTITY_EXCLUDES_RUNTIME_HEAD Vary metadata only.

identity1 = build_stage8_code_identity(repo_dir, struct( ...
    'runtime_head_metadata_override', repmat('1', 1, 40)));
identity2 = build_stage8_code_identity(repo_dir, struct( ...
    'runtime_head_metadata_override', repmat('2', 1, 40)));
pass = strcmp(identity1.stage8_source_tree_hash, ...
    identity2.stage8_source_tree_hash) && ...
    strcmp(identity1.stage8_stable_code_identity_hash, ...
    identity2.stage8_stable_code_identity_hash) && ...
    ~strcmp(identity1.runtime_head_commit, identity2.runtime_head_commit);
assert(pass, 'test_stage8_stable_identity_excludes_runtime_head:Failed', ...
    'Runtime HEAD metadata changed the stable Stage8 identity.');
result = table(pass, string(identity1.stage8_stable_code_identity_hash), ...
    'VariableNames', {'pass_flag','stable_code_identity'});
end
