function result = test_k1_fit_noiseless_single_target()
%TEST_K1_FIT_NOISELESS_SINGLE_TARGET Verify both K1 starts and exact fit.

fixture = build_stage8_synthetic_fixture('K1');
[fit, ~] = fit_local_model_k(fixture.full_data, 1, fixture.domain, ...
    fixture.model, fixture.init_context, struct());
starts = fit.all_start_results;
errors = arrayfun(@(item) max(abs( ...
    item.angles_hat_deg - fixture.target_angles_deg), [], 'all'), starts);
error_deg = max(errors);
pass = ~fit.estimate_returned_flag && fit.num_start == 2 && ...
    all([starts.estimate_returned_flag]) && all([starts.converged_flag]) && ...
    all([starts.effective_rank] == 1) && error_deg == 0 && ...
    fit.numeric_invalid_start_count == 2 && ...
    ~fit.selected_from_valid_start_set_flag && ...
    all(strcmp({starts.selection_eligibility_status}, ...
    'FIT_NUMERIC_INVALID'));
assert(pass, 'test_k1_fit_noiseless_single_target:Failed', ...
    'The zero-residual K1 boundary violated valid-start selection.');
result = table(pass, fit.num_start, error_deg, ...
    'VariableNames', {'pass_flag','num_start','maximum_error_deg'});
end
