function result = test_q_global_aggregates_both_noise_profiles()
%TEST_Q_GLOBAL_AGGREGATES_BOTH_NOISE_PROFILES Verify one config threshold.

global_cell_index = (1:4).';
calibration_cell_id = "CELL_" + string(global_cell_index);
measurement_config_id = repmat("MINI_PRIMARY", 4, 1);
noise_profile_id = ["WHITE";"STAGE5_TOEPLITZ_CORRELATED"; ...
    "WHITE";"STAGE5_TOEPLITZ_CORRELATED"];
model_key = "MODEL_" + string(global_cell_index);
fixed_measurement_hash = "MODEL_HASH_" + string(global_cell_index);
calibration_data_seed = 100 + global_cell_index;
bootstrap_seed_start = 1000 * global_cell_index;
bootstrap_seed_end = bootstrap_seed_start + 1;
cells = table(global_cell_index, calibration_cell_id, ...
    measurement_config_id, noise_profile_id, model_key, ...
    fixed_measurement_hash, calibration_data_seed, ...
    bootstrap_seed_start, bootstrap_seed_end);
plan = struct('cells', cells, 'calibration_plan_hash', 'MINI_PLAN', ...
    'Bboot_per_cell', 2);
base = struct('measurement_config_id', 'MINI_PRIMARY', ...
    'noise_profile_id', '', 'calibration_cell_id', '', ...
    'global_cell_index', 0, 'bootstrap_seed_start', 0, ...
    'bootstrap_seed_end', 0, 'lambda_samples', [1;2], ...
    'q_cell_0p95', 0, 'source_identity', 'MINI_SOURCE', ...
    'plan_hash', 'MINI_PLAN', 'model_key', '', 'model_hash', '', ...
    'cell_input_hash', '', 'data_seed', 0, 'cell_artifact_hash', '', ...
    'status', 'CALIBRATION_CELL_PASS', 'runtime', 0, 'phase_factor', 1);
artifacts = repmat(base, 4, 1);
for index = 1:4
    artifacts(index).noise_profile_id = char(noise_profile_id(index));
    artifacts(index).calibration_cell_id = char(calibration_cell_id(index));
    artifacts(index).global_cell_index = index;
    artifacts(index).bootstrap_seed_start = bootstrap_seed_start(index);
    artifacts(index).bootstrap_seed_end = bootstrap_seed_end(index);
    artifacts(index).lambda_samples = [index;index + 0.5];
    artifacts(index).q_cell_0p95 = index + 0.5;
    artifacts(index).model_key = char(model_key(index));
    artifacts(index).model_hash = char(fixed_measurement_hash(index));
    artifacts(index).cell_input_hash = sprintf('INPUT_%d', index);
    artifacts(index).data_seed = calibration_data_seed(index);
    payload = rmfield(artifacts(index), ...
        {'runtime','cell_artifact_hash','phase_factor'});
    artifacts(index).cell_artifact_hash = stage8_stable_hash( ...
        'STAGE8_1_CALIBRATION_CELL_ARTIFACT_V1', payload);
end
[threshold, ~] = aggregate_stage8_1_calibration(artifacts, plan, struct());
pass = threshold.q_global == 4.5 && threshold.noise_profile_count == 2 && ...
    height(threshold.cell_quantiles) == 4;
assert(pass, 'test_q_global_aggregates_both_noise_profiles:Failed', ...
    'q_global did not aggregate all cells from both noise profiles.');
result = table(pass, threshold.q_global, ...
    'VariableNames', {'pass_flag','q_global'});
end
