function result = test_formal_bootstrap_retains_element_data()
%TEST_FORMAL_BOOTSTRAP_RETAINS_ELEMENT_DATA Check formal data bundle fields.

fixture = build_stage8_1a_mini_fixture();
[context, ~] = stage8_1a_mini_initialization_callback( ...
    fixture.full_k1, fixture.model, fixture.domain);
[fit, ~] = stage8_1a_mock_fit_callback( ...
    1, 0, fixture.full_k1, context, fixture.model);
sample = simulate_bootstrap_under_k1(fit, fixture.model, ...
    struct('seed', 31, 'formal_run', true));
required = {'Y_element','Zseq_raw','Zseq_white', ...
    'fixed_measurement_hash','bootstrap_seed','bootstrap_model_K', ...
    'phase_factor'};
pass = all(isfield(sample, required)) && ...
    size(sample.Y_element, 1) == size(fixture.model.W_I, 1);
assert(pass, 'test_formal_bootstrap_retains_element_data:Failed', ...
    'Formal bootstrap dropped element-domain observations.');
result = table(pass, 'VariableNames', {'pass_flag'});
end
