function result = test_threshold_lookup_has_no_scene_inputs()
%TEST_THRESHOLD_LOOKUP_HAS_NO_SCENE_INPUTS Verify the strict two-input API.

artifact = struct('measurement_config_id', 'PRIMARY_RECT_E14_A31', ...
    'q_global', 7, 'alpha', 0.05, 'calibration_hash', 'UNIT_HASH', ...
    'threshold_status', 'LOCKED_BOOTSTRAP_THRESHOLD', ...
    'threshold_policy', ...
    'ONE_GLOBAL_THRESHOLD_PER_FIXED_MEASUREMENT_CONFIG');
threshold = lookup_locked_lrt_threshold('PRIMARY_RECT_E14_A31', artifact);
stage8_assert_error(@() lookup_locked_lrt_threshold( ...
    'PRIMARY_RECT_E14_A31', artifact, struct('scene_id', 'FORBIDDEN')), ...
    'MATLAB:TooManyInputs');
pass = nargin('lookup_locked_lrt_threshold') == 2 && ...
    threshold.q_global == 7;
assert(pass, 'test_threshold_lookup_has_no_scene_inputs:Failed', ...
    'Threshold lookup accepted more than the frozen two inputs.');
result = table(pass, ...
    'VariableNames', {'pass_flag'});
end
