function result = test_each_bootstrap_sample_refits_k1_and_k2()
%TEST_EACH_BOOTSTRAP_SAMPLE_REFITS_K1_AND_K2 Audit refit counters.

fixture = build_stage8_synthetic_fixture('K1_NOISY');
cell_now = struct('measurement_config_id', 'SYNTHETIC_CONFIG', ...
    'calibration_cell_id', 'SYNTHETIC_CELL_1', 'seed', 3101, ...
    'full_data', fixture.full_data, ...
    'initialization_factory', fixture.initialization_factory);
model = fixture.model;
model.measurement_config_id = 'SYNTHETIC_CONFIG';
[~, debug] = calibrate_global_bootstrap_threshold(cell_now, ...
    fixture.domain, model, struct('Bboot_per_cell', 2));
pass = debug.complete_refit_flag && debug.K1_fit_count == 3 && ...
    debug.K2_fit_count == 2;
assert(pass, 'test_each_bootstrap_sample_refits_k1_and_k2:Failed', ...
    'Every calibration sample must refit both K1 and K2.');
result = table(pass, debug.K1_fit_count, debug.K2_fit_count, ...
    'VariableNames', {'pass_flag','K1_fit_count','K2_fit_count'});
end
