function result = test_cell151_prepatch_case_passes_backward_contract(fixture)
%TEST_CELL151_PREPATCH_CASE_PASSES_BACKWARD_CONTRACT Regress cell 151.

matches = arrayfun(@(item) item.cell_input.global_cell_index == 151, ...
    fixture.cases);
assert(nnz(matches) == 1, ...
    'test_cell151_prepatch_case_passes_backward_contract:Cardinality', ...
    'The real fixture must contain cell 151 exactly once.');
item = fixture.cases(matches);
evaluation = item.evaluation;
cell_input = item.cell_input;
pass = strcmp(cell_input.calibration_cell_id, 'C2_001') && ...
    strcmp(cell_input.measurement_config_id, ...
    'SENSITIVITY_FULL_PARENT_5X5') && ...
    strcmp(cell_input.noise_profile_id, 'WHITE') && ...
    cell_input.calibration_data_seed == 2026072250 && ...
    cell_input.bootstrap_seed_start == 2126222100 && ...
    evaluation.overall_pass && evaluation.mean_absolute_residual > 0 && ...
    strcmp(evaluation.failure_status, 'BOOTSTRAP_MEAN_IDENTITY_PASS');
assert(pass, ...
    'test_cell151_prepatch_case_passes_backward_contract:Failed', ...
    'The exact pre-A5 cell 151 case did not pass the backward-error contract.');
result = table(pass, evaluation.G_max_bound_ratio, ...
    evaluation.mean_max_bound_ratio, evaluation.mean_old_relative_residual, ...
    evaluation.fitted_mean_norm, 'VariableNames', {'pass_flag', ...
    'G_max_bound_ratio','mean_max_bound_ratio', ...
    'old_relative_mean_error','fitted_mean_norm'});
end
