function result = test_primary_validation_gate_uses_6000_trials()
%TEST_PRIMARY_VALIDATION_GATE_USES_6000_TRIALS Check primary overall n.

[trials, K1] = build_stage8_1a_validation_trials();
[summary, gate, ~] = summarize_stage8_k1_validation(trials, K1);
row = summary(summary.measurement_config_id == ...
    string(K1.primary_measurement_config_id) & ...
    summary.summary_scope == "OVERALL", :);
pass = height(row) == 1 && row.common_trial_count == 6000 && ...
    strcmp(gate.authorization_measurement_config_id, ...
    K1.primary_measurement_config_id);
assert(pass, 'test_primary_validation_gate_uses_6000_trials:Failed', ...
    'The primary overall gate must use 6000 common trials.');
result = table(pass, row.common_trial_count, ...
    'VariableNames', {'pass_flag','primary_overall_trial_count'});
end
