function result = test_validation_auxiliary_substreams_deterministic()
%TEST_VALIDATION_AUXILIARY_SUBSTREAMS_DETERMINISTIC Check Bsep schedule.

first = build_stage8_separation_seed_schedule(2226074200, 199);
second = build_stage8_separation_seed_schedule(2226074200, 199);
pass = isequal(first, second) && ...
    all(first.separation_auxiliary_seed == 2226074200) && ...
    isequal(first.substream, (1:199).');
assert(pass, ...
    'test_validation_auxiliary_substreams_deterministic:Failed', ...
    'Separation auxiliary seed/substream scheduling is nondeterministic.');
result = table(pass, height(first), ...
    'VariableNames', {'pass_flag','substream_count'});
end
