function result = test_validation_common_trials_pair_measurement_configs()
%TEST_VALIDATION_COMMON_TRIALS_PAIR_MEASUREMENT_CONFIGS Check shared Y.

[output, expected_count] = miniature_validation_local();
ids = unique(output.trials.common_trial_id);
pass = numel(ids) == expected_count;
for id_index = 1:numel(ids)
    rows = output.trials(output.trials.common_trial_id == ids(id_index), :);
    pass = pass && height(rows) == 2 && ...
        numel(unique(rows.measurement_config_id)) == 2 && ...
        numel(unique(rows.element_trial_hash)) == 1 && ...
        numel(unique(rows.element_seed)) == 1;
end
assert(pass, ...
    'test_validation_common_trials_pair_measurement_configs:Failed', ...
    'The two measurement configurations did not share element trials.');
result = table(pass, output.paired_common_trial_count, ...
    output.method_row_count, 'VariableNames', ...
    {'pass_flag','common_trial_count','method_row_count'});
end

function [output, expected_count] = miniature_validation_local()
fixture = build_stage8_1a_mini_fixture();
plan = build_stage8_validation_plan();
plan.K1.measurement_config_ids = ["MINI_PRIMARY";"MINI_PARENT"];
thresholds = thresholds_local();
output = run_stage8_1_k1_validation(plan, fixture.domain, ...
    fixture.registry, thresholds, fixture.stage5_locked, struct( ...
    'max_common_trials_per_stratum', 1, ...
    'evaluation_callback', @evaluation_local));
expected_count = height(plan.K1.strata);
end

function evaluation = evaluation_local(~, ~, ~, ~)
evaluation = struct('state', 'K1', 'lambda_12', 0, ...
    'fit1_validity_status', 'VALID_FOR_LRT', ...
    'fit2_validity_status', 'VALID_FOR_LRT', ...
    'separation_status', 'NOT_RUN_LRT_DID_NOT_EXCEED_THRESHOLD');
end

function thresholds = thresholds_local()
base = struct('measurement_config_id', '', 'q_global', 5, ...
    'alpha', 0.05, 'calibration_hash', '', ...
    'threshold_status', 'LOCKED_BOOTSTRAP_THRESHOLD', ...
    'threshold_policy', ...
    'ONE_GLOBAL_THRESHOLD_PER_FIXED_MEASUREMENT_CONFIG');
thresholds = repmat(base, 2, 1);
thresholds(1).measurement_config_id = 'MINI_PRIMARY';
thresholds(1).calibration_hash = 'MINI_PRIMARY_THRESHOLD';
thresholds(2).measurement_config_id = 'MINI_PARENT';
thresholds(2).calibration_hash = 'MINI_PARENT_THRESHOLD';
end
