function result = test_calibration_validation_holdout_seed_spaces_disjoint( ...
    calibration, validation, holdout)
%TEST_CALIBRATION_VALIDATION_HOLDOUT_SEED_SPACES_DISJOINT Check all splits.

if nargin < 1, calibration = build_stage8_calibration_plan(); end
if nargin < 2, validation = build_stage8_validation_plan(); end
if nargin < 3, holdout = build_stage8_holdout_plan(); end
calibration_seeds = [calibration.cells.calibration_data_seed;reshape( ...
    (calibration.cells.bootstrap_seed_start + ...
    (0:calibration.Bboot_per_cell - 1)).', [], 1)];
validation_rows = materialize_stage8_k1_validation_plan(validation);
validation_seeds = unique([validation_rows.parameter_seed; ...
    validation_rows.element_noise_seed; ...
    validation_rows.separation_auxiliary_seed]);
holdout_seeds = [validation.K2.seed;holdout.K1.seed;holdout.K2.seed; ...
    holdout.mismatch.seed];
pass = isempty(intersect(calibration_seeds, validation_seeds)) && ...
    isempty(intersect(calibration_seeds, holdout_seeds)) && ...
    isempty(intersect(validation_seeds, holdout_seeds));
assert(pass, ...
    'test_calibration_validation_holdout_seed_spaces_disjoint:Failed', ...
    'Calibration, validation, and holdout seed spaces overlap.');
result = table(pass, 'VariableNames', {'pass_flag'});
end
