function result = test_stage8_1b_two_commit_lifecycle(~)
%TEST_STAGE8_1B_TWO_COMMIT_LIFECYCLE Execute the miniature split lifecycle.

checkpoint_root = tempname;
artifact_root = tempname;
mkdir(checkpoint_root);
mkdir(artifact_root);
cleanup = onCleanup(@() cleanup_local(checkpoint_root, artifact_root));
fixture = build_stage8_1a_two_commit_fixture();
indices = (1:height(fixture.plan.calibration.cells)).';
write_stage8_checkpoint_fixture(checkpoint_root, ...
    fixture.plan.calibration, fixture.contract, indices);
frozen = run_stage8_1_freeze_threshold_evidence( ...
    tempdir, checkpoint_root, artifact_root, struct( ...
    'formal_run', false, 'frozen_plan', fixture.plan));
no_validation_placeholder = ~isfolder(fullfile(artifact_root, 'results'));
[thresholds, calibration] = load_stage8_1_locked_thresholds( ...
    tempdir, artifact_root, fixture.plan, struct( ...
    'formal_run', false, 'require_tracked_artifacts', false));
roundtrip = all(arrayfun(@(item) isequal( ...
    num2hex(item.q_global), item.q_global_hex), thresholds));
before = calibration_snapshot_local(artifact_root);
validation = build_stage8_1a_bound_validation_output( ...
    fixture.plan, calibration, 'K1', 'K1');
validated = validate_stage8_1_validation_output( ...
    fixture.plan, calibration, validation);
finalized = run_stage8_1_finalize(fixture.plan, calibration, ...
    validation, artifact_root, struct('formal_run', false, ...
    'require_tracked_artifacts', false));
after = calibration_snapshot_local(artifact_root);
calibration_unchanged = isequal(before, after);
final_references_calibration = strcmp( ...
    finalized.calibration_evidence_bundle_hash, ...
    frozen.calibration_evidence_bundle_hash) && ...
    all(finalized.manifest.calibration_evidence_bundle_hash == ...
    string(frozen.calibration_evidence_bundle_hash));
pass = no_validation_placeholder && roundtrip && ...
    ~validated.recomputed_primary_gate_pass && calibration_unchanged && ...
    final_references_calibration && ~finalized.stage8_2_executed_flag && ...
    finalized.stage8_2_separate_authorization_required_flag;
assert(pass, 'test_stage8_1b_two_commit_lifecycle:Failed', ...
    'The executable miniature two-commit lifecycle failed.');
result = table(pass, no_validation_placeholder, roundtrip, ...
    calibration_unchanged, final_references_calibration, ...
    'VariableNames', {'pass_flag','no_validation_placeholder', ...
    'threshold_roundtrip','calibration_bytes_unchanged', ...
    'final_references_calibration'});
clear cleanup
end

function snapshot = calibration_snapshot_local(root)
files = dir(fullfile(root, 'calibration', '*'));
files = files(~[files.isdir]);
relative_path = string({files.name}).';
sha256 = strings(numel(files), 1);
for index = 1:numel(files)
    sha256(index) = string(stage8_sha256_file( ...
        fullfile(files(index).folder, files(index).name)));
end
snapshot = sortrows(table(relative_path, sha256), 'relative_path');
end

function cleanup_local(checkpoint_root, artifact_root)
if isfolder(checkpoint_root), rmdir(checkpoint_root, 's'); end
if isfolder(artifact_root), rmdir(artifact_root, 's'); end
end
