function result = test_stage8_1_writer_determinism()
%TEST_STAGE8_1_WRITER_DETERMINISM Exclude runtime from bundle identity.

folder1 = tempname;
folder2 = tempname;
folder3 = tempname;
mkdir(folder1);
mkdir(folder2);
mkdir(folder3);
cleanup = onCleanup(@() cleanup_local(folder1, folder2, folder3));
first = write_stage8_1_results_bundle( ...
    build_stage8_1a_writer_bundle(1), folder1, struct());
second = write_stage8_1_results_bundle( ...
    build_stage8_1a_writer_bundle(999), folder2, struct());
finalized = finalize_smoke_local(folder3);
pass = strcmp(first.stage8_1_evidence_bundle_hash, ...
    second.stage8_1_evidence_bundle_hash) && ...
    isequal(first.manifest.relative_path, second.manifest.relative_path) && ...
    isequal(first.manifest.sha256, second.manifest.sha256) && ...
    ~finalized.stage8_2_executed_flag && ...
    finalized.stage8_2_separate_authorization_required_flag;
assert(pass, 'test_stage8_1_writer_determinism:Failed', ...
    'Runtime changed the deterministic Stage8.1 bundle identity.');
result = table(pass, string(first.stage8_1_evidence_bundle_hash), ...
    'VariableNames', {'pass_flag','bundle_hash'});
clear cleanup
end

function evidence = finalize_smoke_local(folder)
fixture = build_stage8_1a_mini_fixture();
cell_input = build_stage8_1a_mini_cell(fixture, 2);
[artifact, ~] = run_stage8_1_calibration_cell( ...
    cell_input, fixture.domain, fixture.registry, fixture.stage5_locked, ...
    struct('Bboot_per_cell', 2, ...
    'fit_callback', @stage8_1a_mock_fit_callback, ...
    'initialization_callback', @stage8_1a_mini_initialization_callback));
calibration_cells = table(string(cell_input.measurement_config_id), ...
    string(cell_input.calibration_cell_id), cell_input.global_cell_index, ...
    string(cell_input.noise_profile_id), string(cell_input.model_key), ...
    string(cell_input.fixed_measurement_hash), ...
    cell_input.calibration_data_seed, cell_input.bootstrap_seed_start, ...
    cell_input.bootstrap_seed_end, 'VariableNames', ...
    {'measurement_config_id','calibration_cell_id','global_cell_index', ...
    'noise_profile_id','model_key','fixed_measurement_hash', ...
    'calibration_data_seed','bootstrap_seed_start','bootstrap_seed_end'});
source_manifest = table("MINI_SOURCE", "MINI_HASH", ...
    'VariableNames', {'path','sha256'});
plan = struct('measurement_model_registry', fixture.registry, ...
    'identity', struct('stage8_stable_code_identity_hash', 'MINI_SOURCE', ...
    'source_manifest', source_manifest), ...
    'stage8_plan_hash', 'MINI_STAGE8_PLAN', ...
    'stage8_calibration_plan_hash', 'MINI_CALIBRATION_PLAN', ...
    'stage8_validation_plan_hash', 'MINI_VALIDATION_PLAN', ...
    'stage8_holdout_plan_hash', 'MINI_HOLDOUT_PLAN', ...
    'stage7_1_evidence_bundle_hash', 'MINI_STAGE7_1', ...
    'calibration', struct('cells', calibration_cells, ...
    'Bboot_per_cell', 2), 'validation', build_stage8_validation_plan());
thresholds = threshold_local();
tiny = table("OVERALL", 0, 'VariableNames', {'summary_id','rate'});
validation = struct('trials', tiny, 'summary', tiny, ...
    'gate', struct('gate_status', 'STAGE8_1_K1_VALIDATION_PASS', ...
    'gate_pass', true), 'runtime', 0);
evidence = run_stage8_1_finalize(plan, cell_input, artifact, ...
    thresholds, validation, folder, struct());
end

function thresholds = threshold_local()
base = struct('measurement_config_id', '', 'q_global', 1, ...
    'alpha', 0.05, 'calibration_hash', '', ...
    'threshold_status', 'LOCKED_BOOTSTRAP_THRESHOLD');
thresholds = repmat(base, 2, 1);
thresholds(1).measurement_config_id = 'MINI_PRIMARY';
thresholds(1).calibration_hash = 'MINI_PRIMARY_THRESHOLD';
thresholds(2).measurement_config_id = 'MINI_PARENT';
thresholds(2).calibration_hash = 'MINI_PARENT_THRESHOLD';
end

function cleanup_local(folder1, folder2, folder3)
if isfolder(folder1), rmdir(folder1, 's'); end
if isfolder(folder2), rmdir(folder2, 's'); end
if isfolder(folder3), rmdir(folder3, 's'); end
end
