function result = test_stage8_1b_two_commit_lifecycle(step_dir)
%TEST_STAGE8_1B_TWO_COMMIT_LIFECYCLE Check frozen evidence sequencing.

if nargin < 1, step_dir = fileparts(fileparts(mfilename('fullpath'))); end
text = string(fileread(fullfile(step_dir, 'README.md')));
pass = contains(text, ...
    'docs(stage8.1): freeze k1 bootstrap thresholds') && ...
    contains(text, ...
    'docs(stage8.1): validate k1 false-split control') && ...
    contains(text, 'checkpoint root outside the Git repository') && ...
    contains(text, 'clean threshold evidence commit');
assert(pass, 'test_stage8_1b_two_commit_lifecycle:Failed', ...
    'README does not freeze the two-commit Stage8.1B lifecycle.');
result = table(pass, 'VariableNames', {'pass_flag'});
end
