function result = test_stage8_measurement_matches_rect_e14_a31(cfg)
%TEST_STAGE8_MEASUREMENT_MATCHES_RECT_E14_A31 Verify the primary subset.

[model, debug] = build_stage8_measurement_model( ...
    'PRIMARY_RECT_E14_A31', 'WHITE', cfg, struct());
pool = build_stage7_candidate_pool(cfg);
expected_channels = reshape((2:4).' + ((1:5) - 1) * 5, 1, []);
expected_channels = expected_channels(:).';
pass = strcmp(model.subset_id, 'RECT_E14_A31') && ...
    isequal(model.channels, expected_channels) && debug.B_el == 3 && ...
    debug.B_az == 5 && debug.B_out == 15 && ...
    norm(model.W_I - pool.W0(:, expected_channels), 'fro') == 0;
assert(pass, 'test_stage8_measurement_matches_rect_e14_a31:Failed', ...
    'The primary Stage8 model does not match frozen RECT_E14_A31.');
result = table(pass, debug.B_el, debug.B_az, debug.B_out, ...
    'VariableNames', {'pass_flag','B_el','B_az','B_out'});
end
