function result = test_real_initialization_context_k2_partition_fields()
%TEST_REAL_INITIALIZATION_CONTEXT_K2_PARTITION_FIELDS Check fixed partitions.

fixture = build_stage8_1a_mini_fixture();
context = build_stage8_initialization_context_from_data( ...
    fixture.full_k2, fixture.model, fixture.domain, ...
    fixture.stage5_locked, fixture.model.noise_factorization, struct());
required = {'grouped_q1_kq2_angles_deg', ...
    'grouped_q2_kq1_plus_kq1_angles_deg', ...
    'grouped_q1_kq2_status','grouped_q2_kq1_plus_kq1_status'};
pass = all(isfield(context, required)) && ...
    isequal(size(context.grouped_q1_kq2_angles_deg), [2, 2]) && ...
    isequal(size(context.grouped_q2_kq1_plus_kq1_angles_deg), [2, 2]);
assert(pass, 'test_real_initialization_context_k2_partition_fields:Failed', ...
    'The Q1/Kq2 or Q2/Kq1+Kq1 initialization field is missing.');
result = table(pass, 'VariableNames', {'pass_flag'});
end
