function result = test_separation_confidence_zero_excluded()
%TEST_SEPARATION_CONFIDENCE_ZERO_EXCLUDED Verify a zero-radius exact refit.

fixture = build_stage8_synthetic_fixture('K2_SAME_ELEVATION');
[fit1, ~] = fit_local_model_k(fixture.full_data, 1, fixture.domain, ...
    fixture.model, fixture.init_context, struct());
context = fixture.init_context;
context.k1_fit = fit1;
[fit2, ~] = fit_local_model_k(fixture.full_data, 2, fixture.domain, ...
    fixture.model, context, struct());
samples = repmat(reshape(fit2.angles_hat_deg, 2, 2, 1), 1, 1, 3);
callback = build_stage8_refit_callback(fit2, samples);
[confidence, ~] = bootstrap_separation_confidence(fit2, ...
    fixture.domain, fixture.model, struct('Bsep', 3, ...
    'refit_callback', callback, 'seed', 7101));
pass = confidence.zero_excluded_flag && confidence.r_conf_squared == 0 && ...
    confidence.engineering_halfwidth_pass;
assert(pass, 'test_separation_confidence_zero_excluded:Failed', ...
    'An exact nonzero fitted separation must exclude zero.');
result = table(pass, confidence.r_conf_squared, ...
    'VariableNames', {'pass_flag','r_conf_squared'});
end
