function result = test_full_parent_not_used_for_authorization()
%TEST_FULL_PARENT_NOT_USED_FOR_AUTHORIZATION Ensure sensitivity cannot offset.

[trials, K1] = build_stage8_1a_validation_trials('K2_RESOLVED', 'K1');
[summary, gate, ~] = summarize_stage8_k1_validation(trials, K1);
sensitivity = summary(summary.measurement_config_id == ...
    string(K1.sensitivity_measurement_config_id), :);
pass = ~gate.gate_pass && ...
    ~gate.sensitivity_used_for_authorization_flag && ...
    strcmp(gate.sensitivity_status, ...
    'SENSITIVITY_ONLY_NOT_USED_FOR_STAGE8_2_AUTHORIZATION') && ...
    all(sensitivity.false_split_rate == 0);
assert(pass, 'test_full_parent_not_used_for_authorization:Failed', ...
    'FULL_PARENT sensitivity offset a failing primary gate.');
result = table(pass, gate.gate_pass, ...
    'VariableNames', {'pass_flag','primary_gate_pass'});
end
