function result = test_k1_embedded_start_contains_k1_column()
%TEST_K1_EMBEDDED_START_CONTAINS_K1_COLUMN Verify exact numerical nesting.

fixture = build_stage8_synthetic_fixture('K2_SAME_ELEVATION');
[fit1, ~] = fit_local_model_k(fixture.full_data, 1, fixture.domain, ...
    fixture.model, fixture.init_context, struct());
[starts, ~] = build_k2_initializations(fixture.full_data, ...
    fixture.domain, fixture.model, fixture.init_context, fit1, struct());
[G, ~] = build_full_sequential_local_manifold( ...
    starts(3).angles_deg, fixture.model, struct());
column_error = norm(G(:, 1) - fit1.G_hat(:, 1)) / norm(fit1.G_hat(:, 1));
pass = starts(3).available_flag && starts(3).nested_rss_pass && ...
    column_error <= 64 * eps(max(size(G)));
assert(pass, 'test_k1_embedded_start_contains_k1_column:Failed', ...
    'The nested K2 start does not contain the fitted K1 column.');
result = table(pass, column_error, starts(3).nested_rss_pass, ...
    'VariableNames', {'pass_flag','column_error','nested_rss_pass'});
end
