function result = verify_stage7_1_frozen_evidence(package_dir)
%VERIFY_STAGE7_1_FROZEN_EVIDENCE Recheck the deterministic Stage7.1 bundle.

root = fullfile(package_dir, 'source', 'stepwise_signal_model', 'steps', ...
    'step_12_5_1_stage7_closure_audit');
manifest = readtable(fullfile(root, 'results', ...
    'stage7_1_evidence_manifest.csv'), 'TextType', 'string');
selected = manifest.included_in_deterministic_bundle == 1;
frozen = manifest(selected, :);
result = verify_stage8_manifest_rows(root, frozen.relative_path, ...
    frozen.byte_count, frozen.sha256);
bundle = unique(manifest.stage7_1_evidence_bundle_hash);
expected = "af40f8a7e8a0edfc7077594ebf08257cd0c7385d10902bc8dd624c83434bc322";
assert(height(frozen) == 13 && all(result.pass_flag) && ...
    isscalar(bundle) && bundle == expected, ...
    'verify_stage7_1_frozen_evidence:Failed', ...
    'The deterministic Stage7.1 evidence bundle changed.');
end
