function result = verify_stage6_frozen_evidence(package_dir)
%VERIFY_STAGE6_FROZEN_EVIDENCE Recheck the deterministic Stage6 bundle.

root = fullfile(package_dir, 'source', 'stepwise_signal_model', 'steps', ...
    'step_12_4_near_pair_tangent_asymptotics');
manifest = readtable(fullfile(root, 'results', ...
    'stage6_evidence_manifest.csv'), 'TextType', 'string');
selected = manifest.included_in_deterministic_bundle == 1;
frozen = manifest(selected, :);
result = verify_stage8_manifest_rows(root, frozen.relative_path, ...
    frozen.byte_count, frozen.sha256);
bundle = unique(manifest.stage6_evidence_bundle_hash);
expected = "0c1f444603398e03865043af4e4c6e4a414dd15a3cc90e0539b19c56e990c839";
assert(height(frozen) == 21 && all(result.pass_flag) && ...
    isscalar(bundle) && bundle == expected, ...
    'verify_stage6_frozen_evidence:Failed', ...
    'The deterministic Stage6 evidence bundle changed.');
end
