function constants = stage8_k2_cb_constants()
% Default scientific budgets; experiment registration lives in RTC constants.
constants = struct( ...
    'snr_db_values', 0, 'profile_ids', 0, ...
    'music_applicable_L', [4, 8], ...
    'top_start_count', 6, ...
    'max_sweeps', 12, ...
    'scan_nodes_per_coordinate', 9, ...
    'fminbnd_TolX_deg', 1e-4, ...
    'fminbnd_MaxFunEvals', 80, ...
    'minimum_separation_deg', 1e-3, ...
    'relative_score_tolerance', 1e-8, ...
    'endpoint_update_tolerance_deg', 1e-3, ...
    'rank_multiplier', 1, ...
    'music_grid_step_deg', 0.005, ...
    'music_grid_chunk_size', 2048, ...
    'paired_tie_tolerance_deg', 1e-6, ...
    'zero_separation_tolerance_deg', 1e-12);
end
