function resources = stage8_k2_cb_prepare_resources(context)
%STAGE8_K2_CB_PREPARE_RESOURCES Build fixed MUSIC dictionaries and whiteners.

constants = context.constants;
domain = context.plan.local_domain;
az_grid = exact_axis_local(domain.domain_bounds_deg(1), ...
    domain.domain_bounds_deg(2), constants.music_grid_step_deg);
el_grid = exact_axis_local(domain.domain_bounds_deg(3), ...
    domain.domain_bounds_deg(4), constants.music_grid_step_deg);
[az_mesh, el_mesh] = ndgrid(az_grid, el_grid);
points = [az_mesh(:), el_mesh(:)];

models = cell(numel(constants.noise_profile_ids), 1);
whitenings = cell(numel(constants.noise_profile_ids), 1);
for index = 1:numel(constants.noise_profile_ids)
    models{index} = resolve_stage8_measurement_model( ...
        context.plan.measurement_model_registry, ...
        context.primary_measurement_config_id, ...
        constants.noise_profile_ids(index));
    dummy = complex(zeros(size(models{index}.Rn_elem, 1), 1));
    [~, whitenings{index}] = stage8_k2_cb_whiten_element_data( ...
        dummy, models{index});
end

physical_clock = tic;
physical = build_stage8_element_manifold(points, models{1});
A_element = physical.A;
physical_runtime = toc(physical_clock);
entry_cells = cell(numel(constants.noise_profile_ids), 1);
for index = 1:numel(constants.noise_profile_ids)
    transform_clock = tic;
    A_element_white = whitenings{index}.whitener * A_element;
    G_beamspace = models{index}.T_I * (models{index}.W_I' * A_element);
    transform_runtime = toc(transform_clock);
    entry_cells{index} = struct( ...
        'noise_profile_id', constants.noise_profile_ids(index), ...
        'model', models{index}, 'whitening', whitenings{index}, ...
        'A_element_white', A_element_white, ...
        'G_beamspace', G_beamspace, ...
        'physical_dictionary_runtime_sec', physical_runtime, ...
        'transform_runtime_sec', transform_runtime, ...
        'standalone_precompute_runtime_sec', ...
        physical_runtime + transform_runtime);
end
entries = vertcat(entry_cells{:});
resources = struct('az_grid_deg', az_grid, 'el_grid_deg', el_grid, ...
    'grid_points_deg', points, 'grid_size', size(az_mesh), ...
    'grid_point_count', size(points, 1), 'entries', entries, ...
    'physical_dictionary_runtime_sec', physical_runtime, ...
    'truth_used_in_precompute_flag', false, ...
    'profile_used_in_precompute_flag', false);
end

function axis = exact_axis_local(lower, upper, step)
count = round((upper - lower) / step);
axis = lower + (0:count) * step;
axis(end) = upper;
if abs(axis(1) - lower) > 1e-12 || abs(axis(end) - upper) > 1e-12
    error('stage8_k2_cb_prepare_resources:Grid', ...
        'The fixed MUSIC grid does not cover the frozen domain exactly.');
end
end
