function [rows, diagnostics] = stage8_k2_cb_evaluate_trial( ...
    spec, trial, context, resources)
%STAGE8_K2_CB_EVALUATE_TRIAL Run registered baselines without fitting truth.

constants = context.constants;
entry_index = find([resources.entries.noise_profile_id] == ...
    string(spec.noise_profile_id), 1);
if isempty(entry_index)
    error('stage8_k2_cb_evaluate_trial:Resource', ...
        'No fixed resource entry matches the trial noise profile.');
end
entry = resources.entries(entry_index);
if string(entry.model.fixed_measurement_hash) ~= ...
        string(trial.model.fixed_measurement_hash)
    error('stage8_k2_cb_evaluate_trial:ModelIdentity', ...
        'Trial and fixed resource measurement models disagree.');
end
full_data = build_stage8_full_data_from_element( ...
    trial.Y_element, trial.model, ...
    struct('data_role', 'SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
[Y_element_white, whitening_now] = ...
    stage8_k2_cb_whiten_element_data(trial.Y_element, trial.model);
if norm(whitening_now.whitener - entry.whitening.whitener, 'fro') > 1e-10
    error('stage8_k2_cb_evaluate_trial:WhiteningIdentity', ...
        'Per-trial and fixed element whiteners disagree.');
end

diagnostic = context.corrected_diagnostics( ...
    context.corrected_diagnostics.trial_id == spec.trial_id, :);
if height(diagnostic) ~= 1 || diagnostic.element_trial_hash ~= ...
        trial.element_trial_hash
    error('stage8_k2_cb_evaluate_trial:DiagnosticPairing', ...
        'Corrected Tangent diagnostics do not pair to this trial.');
end
raw_tangent_loglik = double(diagnostic.raw_tangent_loglik);

beam_cml = stage8_k2_cb_full4d_cml(full_data.Zseq_white, ...
    trial.model, context.plan.local_domain, 'BEAMSPACE', struct(), constants);
beam_cml.online_runtime_sec = beam_cml.runtime_sec;
beam_cml.selected_source = "FULL4D_NUMERICAL_MULTISTART";
incomplete = beam_cml.fit_valid && isfinite(raw_tangent_loglik) && ...
    beam_cml.loglik_concentrated + ...
    64 * eps(max(1, abs(raw_tangent_loglik))) < raw_tangent_loglik;
beam_row = stage8_k2_cb_result_row(spec, trial, beam_cml, ...
    'FORMAL_BASELINE_RUN', raw_tangent_loglik, constants);
beam_row.numerical_optimization_incomplete_flag = incomplete;
if incomplete
    beam_row.numerical_optimization_status = ...
        "NUMERICAL_OPTIMIZATION_INCOMPLETE";
else
    beam_row.numerical_optimization_status = "NOT_DETECTED";
end

beam_music = stage8_k2_cb_music(full_data.Zseq_white, entry, ...
    resources, 'BEAMSPACE', double(spec.L), constants);
beam_music_row = stage8_k2_cb_result_row(spec, trial, beam_music, ...
    'FORMAL_BASELINE_RUN', raw_tangent_loglik, constants);
element_music = stage8_k2_cb_music(Y_element_white, entry, ...
    resources, 'ELEMENT', double(spec.L), constants);
element_music_row = stage8_k2_cb_result_row(spec, trial, element_music, ...
    'FORMAL_BASELINE_RUN', raw_tangent_loglik, constants);

row_structs = [beam_row; beam_music_row; element_music_row];
if double(spec.L) == constants.element_reference_L
    element_cml = stage8_k2_cb_full4d_cml(Y_element_white, ...
        trial.model, context.plan.local_domain, 'ELEMENT', ...
        entry.whitening, constants);
    element_cml.online_runtime_sec = element_cml.runtime_sec;
    element_cml.selected_source = "FULL4D_NUMERICAL_MULTISTART";
    element_row = stage8_k2_cb_result_row(spec, trial, element_cml, ...
        'FORMAL_BASELINE_RUN', raw_tangent_loglik, constants);
    row_structs = [row_structs; element_row];
end
rows = struct2table(row_structs);
diagnostics = struct('trial_id', string(spec.trial_id), ...
    'element_trial_hash', trial.element_trial_hash, ...
    'hash_match_flag', trial.element_hash_match_flag, ...
    'beam_cml_valid', beam_cml.fit_valid, ...
    'beam_cml_coarse_candidate_count', ...
    beam_cml.coarse_candidate_count, ...
    'beam_cml_continuous_start_count', ...
    beam_cml.continuous_start_count, ...
    'element_cml_applicable', ...
    double(spec.L) == constants.element_reference_L, ...
    'beam_music_applicable', beam_music.applicable, ...
    'element_music_applicable', element_music.applicable, ...
    'truth_isolation_flag', ~any(rows.truth_used_in_fit_flag) && ...
    ~any(rows.profile_used_in_fit_flag) && ...
    ~any(rows.tangent_used_in_start_flag) && ...
    ~any(rows.core_used_in_start_flag), ...
    'numerical_optimization_incomplete_flag', incomplete);
end
