function rows = stage8_k2_cb_frozen_rows(context, registry)
%STAGE8_K2_CB_FROZEN_ROWS Normalize evidence-31 rows without refitting.

constants = context.constants;
frozen = context.frozen_method_rows;
output = repmat(stage8_k2_cb_row_template(), height(frozen), 1);
for index = 1:height(frozen)
    source = frozen(index, :);
    spec = registry(registry.trial_id == source.trial_id, :);
    if height(spec) ~= 1
        error('stage8_k2_cb_frozen_rows:RegistryPairing', ...
            'A frozen method row has no unique registry row.');
    end
    angles = parse_angles_local(source.angles_hat_deg);
    trial = struct('element_trial_hash', source.element_trial_hash, ...
        'element_hash_match_flag', true, ...
        'truth_angles_deg', stage8_k2_cb_truth_from_spec(spec));
    result = struct('method_id', source.method_id, ...
        'observation_domain', "BEAMSPACE", 'applicable', true, ...
        'applicability_status', "APPLICABLE", ...
        'fit_valid', logical(source.fit_valid), ...
        'fit_status', source.fit_status, ...
        'optimizer_status', "FROZEN_EVIDENCE", ...
        'selected_source', source.selected_source, ...
        'selected_start_id', "", 'angles_hat_deg', angles, ...
        'rss', double(source.RSS), ...
        'loglik_concentrated', double(source.loglik), ...
        'effective_rank', double(source.effective_rank), ...
        'score_call_count', double(source.score_call_count), ...
        'svd_call_count', double(source.SVD_call_count), ...
        'eig_call_count', 0, 'runtime_sec', double(source.runtime_sec), ...
        'online_runtime_sec', double(source.runtime_sec), ...
        'precompute_runtime_sec_amortized', 0, ...
        'coarse_candidate_count', 0, 'continuous_start_count', 0, ...
        'sweep_count', 0, 'local_peak_count', 0, ...
        'truth_used_in_fit_flag', logical(source.truth_used_in_fit_flag), ...
        'profile_used_in_fit_flag', false, ...
        'tangent_used_in_start_flag', false, ...
        'core_used_in_start_flag', false, ...
        'full_manifold_used_flag', source.method_id == ...
        "TANGENT_PROFILE_SAFE");
    diagnostic = context.corrected_diagnostics( ...
        context.corrected_diagnostics.trial_id == source.trial_id, :);
    raw_loglik = NaN;
    if source.method_id == "TANGENT_PROFILE_SAFE"
        raw_loglik = double(diagnostic.raw_tangent_loglik);
    end
    output(index) = stage8_k2_cb_result_row(spec, trial, result, ...
        'FROZEN_EVIDENCE_31_32', raw_loglik, constants);
end
rows = struct2table(output);
end

function angles = parse_angles_local(value)
text = char(string(value));
text = strrep(text, '[', ' ');
text = strrep(text, ']', ' ');
text = strrep(text, ';', ' ');
numbers = sscanf(text, '%f');
if numel(numbers) ~= 4
    angles = NaN(2, 2);
else
    angles = [numbers(1), numbers(2); numbers(3), numbers(4)];
end
end
