function [A_white, info] = stage8_k2_cb_build_element_manifold( ...
    target_angles_deg, model, whitening)
%STAGE8_K2_CB_BUILD_ELEMENT_MANIFOLD Build and exactly whiten element columns.

if ~(isstruct(whitening) && isfield(whitening, 'whitener'))
    error('stage8_k2_cb_build_element_manifold:Whitening', ...
        'A verified element whitener is required.');
end
manifold = build_stage8_element_manifold(target_angles_deg, model);
A_white = whitening.whitener * manifold.A;
info = struct('target_angles_deg', target_angles_deg, ...
    'element_order', string(manifold.element_order), ...
    'whitening_method', string(whitening.method), ...
    'whitening_error', whitening.whitening_error, ...
    'full_element_manifold_used_flag', true);
end
