function metrics = stage8_k2_cb_metrics(angles_hat_deg, truth_angles_deg, constants)
%STAGE8_K2_CB_METRICS Match two targets and compute registered geometry errors.

if nargin < 3 || isempty(constants)
    constants = stage8_k2_cb_constants();
end
metrics = struct('matched_angles_deg', NaN(2, 2), ...
    'joint_RMSE_deg', NaN, 'azimuth_RMSE_deg', NaN, ...
    'elevation_RMSE_deg', NaN, 'center_error_deg', NaN, ...
    'axis_error_deg', NaN, 'separation_true_deg', NaN, ...
    'separation_hat_deg', NaN, 'separation_error_deg', NaN, ...
    'separation_vector_error_deg', NaN);
if ~(isequal(size(angles_hat_deg), [2, 2]) && ...
        all(isfinite(angles_hat_deg(:))) && ...
        isequal(size(truth_angles_deg), [2, 2]) && ...
        all(isfinite(truth_angles_deg(:))))
    return;
end
identity_error = sum((angles_hat_deg - truth_angles_deg) .^ 2, 'all');
swapped = angles_hat_deg([2, 1], :);
swap_error = sum((swapped - truth_angles_deg) .^ 2, 'all');
if swap_error < identity_error
    matched = swapped;
else
    matched = angles_hat_deg;
end
error_now = matched - truth_angles_deg;
d_true = truth_angles_deg(2, :) - truth_angles_deg(1, :);
d_hat = matched(2, :) - matched(1, :);
rho_true = norm(d_true);
rho_hat = norm(d_hat);
axis_error = NaN;
if rho_hat > constants.zero_separation_tolerance_deg && rho_true > 0
    cosine = abs(dot(d_hat / rho_hat, d_true / rho_true));
    axis_error = acosd(min(1, max(0, cosine)));
end
metrics = struct('matched_angles_deg', matched, ...
    'joint_RMSE_deg', sqrt(mean(sum(error_now .^ 2, 2))), ...
    'azimuth_RMSE_deg', sqrt(mean(error_now(:, 1) .^ 2)), ...
    'elevation_RMSE_deg', sqrt(mean(error_now(:, 2) .^ 2)), ...
    'center_error_deg', norm(mean(matched, 1) - ...
    mean(truth_angles_deg, 1)), ...
    'axis_error_deg', axis_error, ...
    'separation_true_deg', rho_true, ...
    'separation_hat_deg', rho_hat, ...
    'separation_error_deg', abs(rho_hat - rho_true), ...
    'separation_vector_error_deg', norm(d_hat - d_true));
end
