function output = stage8_k2_cb_summarize( ...
    rows, registry, resources, repo_dir, runtime_root)
%STAGE8_K2_CB_SUMMARIZE Write comparison tables without a performance gate.

constants = stage8_k2_cb_constants();
integrity = validate_inputs_local(rows, registry, constants);
summary = comparison_summary_local(rows, registry, constants);
profile_summary = stratified_summary_local(rows, constants);
applicability = applicability_local(rows, constants);
complexity = complexity_local(rows, constants);
paths_runtime = evidence_paths_local(runtime_root);
paths_repo = evidence_paths_local(fullfile(repo_dir, 'innovation-mining'));
write_tables_local(rows, summary, profile_summary, applicability, ...
    complexity, paths_runtime);
write_tables_local(rows, summary, profile_summary, applicability, ...
    complexity, paths_repo);
write_report_local(paths_runtime.report, rows, summary, registry, ...
    resources, integrity, constants, runtime_root);
write_report_local(paths_repo.report, rows, summary, registry, ...
    resources, integrity, constants, runtime_root);
output = struct('rows', rows, 'summary', summary, ...
    'profile_summary', profile_summary, ...
    'applicability', applicability, 'complexity', complexity, ...
    'integrity', integrity, 'runtime_paths', paths_runtime, ...
    'repo_paths', paths_repo);
end

function summary = comparison_summary_local(rows, registry, constants)
definitions = { ...
    'ALL_72', true(height(registry), 1), ...
    ["CORE_LITE"; "CORE_PLUS"; "TANGENT_PROFILE_SAFE"; ...
    "FULL4D_BEAMSPACE_CML_MULTISTART"]; ...
    'ELEMENT_REFERENCE_24', registry.L == constants.element_reference_L, ...
    ["TANGENT_PROFILE_SAFE"; "FULL4D_BEAMSPACE_CML_MULTISTART"; ...
    "FULL4D_ELEMENT_CML_MULTISTART"]; ...
    'MUSIC_APPLICABLE_48', ismember(registry.L, ...
    constants.music_applicable_L), ...
    ["TANGENT_PROFILE_SAFE"; "FULL4D_BEAMSPACE_CML_MULTISTART"; ...
    "BEAMSPACE_MUSIC_K2"; "ELEMENT_MUSIC_K2"]};
items = repmat(summary_template_local(), 0, 1);
for definition_index = 1:size(definitions, 1)
    set_id = string(definitions{definition_index, 1});
    trial_ids = registry.trial_id(definitions{definition_index, 2});
    methods = definitions{definition_index, 3};
    for method_index = 1:numel(methods)
        subset = rows(rows.method_id == methods(method_index) & ...
            ismember(rows.trial_id, trial_ids), :);
        items(end + 1, 1) = metric_row_local( ...
            "METHOD", set_id, "ALL", "ALL", ...
            methods(method_index), subset); %#ok<AGROW>
    end
end
pair_definitions = { ...
    'ALL_72', 'TANGENT_PROFILE_SAFE', ...
    'FULL4D_BEAMSPACE_CML_MULTISTART'; ...
    'ELEMENT_REFERENCE_24', 'TANGENT_PROFILE_SAFE', ...
    'FULL4D_BEAMSPACE_CML_MULTISTART'; ...
    'ELEMENT_REFERENCE_24', 'TANGENT_PROFILE_SAFE', ...
    'FULL4D_ELEMENT_CML_MULTISTART'; ...
    'ELEMENT_REFERENCE_24', 'FULL4D_BEAMSPACE_CML_MULTISTART', ...
    'FULL4D_ELEMENT_CML_MULTISTART'; ...
    'MUSIC_APPLICABLE_48', 'TANGENT_PROFILE_SAFE', ...
    'FULL4D_BEAMSPACE_CML_MULTISTART'; ...
    'MUSIC_APPLICABLE_48', 'TANGENT_PROFILE_SAFE', ...
    'BEAMSPACE_MUSIC_K2'; ...
    'MUSIC_APPLICABLE_48', 'TANGENT_PROFILE_SAFE', ...
    'ELEMENT_MUSIC_K2'; ...
    'MUSIC_APPLICABLE_48', 'FULL4D_BEAMSPACE_CML_MULTISTART', ...
    'BEAMSPACE_MUSIC_K2'};
for index = 1:size(pair_definitions, 1)
    set_id = string(pair_definitions{index, 1});
    definition_index = find(string(definitions(:, 1)) == set_id, 1);
    trial_ids = registry.trial_id(definitions{definition_index, 2});
    items(end + 1, 1) = paired_row_local(rows, trial_ids, set_id, ...
        string(pair_definitions{index, 2}), ...
        string(pair_definitions{index, 3}), constants); %#ok<AGROW>
end
summary = struct2table(items);
end

function table_out = stratified_summary_local(rows, constants)
methods = [constants.frozen_method_ids; constants.baseline_method_ids];
items = repmat(summary_template_local(), 0, 1);
for method_index = 1:numel(methods)
    method_rows = rows(rows.method_id == methods(method_index), :);
    for profile = constants.profile_ids.'
        subset = method_rows(method_rows.profile_id == profile, :);
        items(end + 1, 1) = metric_row_local("METHOD", "NATURAL", ...
            "PROFILE", profile, methods(method_index), subset); %#ok<AGROW>
    end
    for snr = constants.snr_db_values
        subset = method_rows(method_rows.snr_db == snr, :);
        items(end + 1, 1) = metric_row_local("METHOD", "NATURAL", ...
            "SNR_DB", string(sprintf('%+d', snr)), ...
            methods(method_index), subset); %#ok<AGROW>
    end
    for L = constants.snapshot_counts
        subset = method_rows(method_rows.L == L, :);
        items(end + 1, 1) = metric_row_local("METHOD", "NATURAL", ...
            "L", string(sprintf('%d', L)), ...
            methods(method_index), subset); %#ok<AGROW>
    end
    for noise = constants.noise_profile_ids.'
        subset = method_rows(method_rows.noise_profile_id == noise, :);
        items(end + 1, 1) = metric_row_local("METHOD", "NATURAL", ...
            "NOISE", noise, methods(method_index), subset); %#ok<AGROW>
    end
end
table_out = struct2table(items);
end

function table_out = applicability_local(rows, constants)
methods = [constants.frozen_method_ids; constants.baseline_method_ids];
items = cell(0, 1);
for method_index = 1:numel(methods)
    method_rows = rows(rows.method_id == methods(method_index), :);
    scopes = [0, constants.snapshot_counts];
    for scope = scopes
        if scope == 0
            subset = method_rows;
            scope_value = "ALL";
        else
            subset = method_rows(method_rows.L == scope, :);
            scope_value = string(sprintf('%d', scope));
        end
        statuses = unique(subset.applicability_status, 'stable');
        if isempty(statuses)
            statuses = "NO_REGISTERED_ROWS";
        end
        for status = statuses.'
            selected = subset(subset.applicability_status == status, :);
            items{end + 1, 1} = struct('method_id', methods(method_index), ...
                'scope_type', "L", 'scope_value', scope_value, ...
                'applicability_status', status, ...
                'row_count', height(selected), ...
                'applicable_count', nnz(selected.applicable), ...
                'valid_count', nnz(selected.fit_valid)); %#ok<AGROW>
        end
    end
end
table_out = struct2table(vertcat(items{:}));
end

function table_out = complexity_local(rows, constants)
methods = [constants.frozen_method_ids; constants.baseline_method_ids];
items = cell(numel(methods), 1);
for index = 1:numel(methods)
    subset = rows(rows.method_id == methods(index) & rows.applicable, :);
    items{index} = struct('method_id', methods(index), ...
        'applicable_count', height(subset), ...
        'valid_count', nnz(subset.fit_valid), ...
        'mean_score_calls', mean_or_nan_local(subset.score_call_count), ...
        'mean_svd_calls', mean_or_nan_local(subset.svd_call_count), ...
        'mean_eig_calls', mean_or_nan_local(subset.eig_call_count), ...
        'mean_coarse_candidates', ...
        mean_or_nan_local(subset.coarse_candidate_count), ...
        'mean_continuous_starts', ...
        mean_or_nan_local(subset.continuous_start_count), ...
        'median_runtime_sec', median_or_nan_local(subset.runtime_sec), ...
        'p90_runtime_sec', percentile_or_nan_local(subset.runtime_sec, 90), ...
        'median_online_runtime_sec', ...
        median_or_nan_local(subset.online_runtime_sec), ...
        'total_amortized_precompute_sec', ...
        sum(subset.precompute_runtime_sec_amortized));
end
table_out = struct2table(vertcat(items{:}));
end

function row = metric_row_local( ...
    row_type, comparison_set, scope_type, scope_value, method_id, subset)
row = summary_template_local();
row.row_type = row_type;
row.comparison_set = comparison_set;
row.scope_type = scope_type;
row.scope_value = scope_value;
row.method_id = method_id;
row.total_row_count = height(subset);
row.applicable_count = nnz(subset.applicable);
row.valid_count = nnz(subset.applicable & subset.fit_valid);
valid = subset.applicable & subset.fit_valid;
metrics = {'joint_RMSE_deg','center_error_deg','axis_error_deg', ...
    'separation_error_deg','separation_vector_error_deg','runtime_sec'};
prefixes = {'joint_RMSE_deg','center_error_deg','axis_error_deg', ...
    'separation_error_deg','separation_vector_error_deg','runtime_sec'};
for index = 1:numel(metrics)
    if strcmp(metrics{index}, 'runtime_sec')
        selected = subset.applicable;
    else
        selected = valid;
    end
    values = subset.(metrics{index})(selected & ...
        isfinite(subset.(metrics{index})));
    row.(['median_', prefixes{index}]) = median_or_nan_local(values);
    row.(['p90_', prefixes{index}]) = percentile_or_nan_local(values, 90);
end
end

function row = paired_row_local(rows, trial_ids, set_id, left_id, right_id, constants)
row = summary_template_local();
row.row_type = "PAIRED";
row.comparison_set = set_id;
row.scope_type = "PAIR";
row.scope_value = left_id + "_vs_" + right_id;
row.method_id = left_id;
row.comparison_id = row.scope_value;
left = sortrows(rows(rows.method_id == left_id & ...
    ismember(rows.trial_id, trial_ids), :), 'trial_id');
right = sortrows(rows(rows.method_id == right_id & ...
    ismember(rows.trial_id, trial_ids), :), 'trial_id');
if height(left) ~= height(right) || ~isequal(left.trial_id, right.trial_id)
    error('stage8_k2_cb_summarize:PairedIdentity', ...
        'Paired comparison rows do not share the same trial IDs.');
end
finite = left.applicable & right.applicable & left.fit_valid & ...
    right.fit_valid & isfinite(left.joint_RMSE_deg) & ...
    isfinite(right.joint_RMSE_deg);
delta = left.joint_RMSE_deg - right.joint_RMSE_deg;
row.paired_count = nnz(finite);
row.wins = nnz(finite & delta < -constants.paired_tie_tolerance_deg);
row.ties = nnz(finite & abs(delta) <= ...
    constants.paired_tie_tolerance_deg);
row.losses = nnz(finite & delta > constants.paired_tie_tolerance_deg);
row.total_row_count = height(left);
row.applicable_count = nnz(left.applicable & right.applicable);
row.valid_count = row.paired_count;
end

function row = summary_template_local()
row = struct('row_type', "", 'comparison_set', "", ...
    'scope_type', "", 'scope_value', "", 'method_id', "", ...
    'total_row_count', 0, 'applicable_count', 0, 'valid_count', 0, ...
    'median_joint_RMSE_deg', NaN, 'p90_joint_RMSE_deg', NaN, ...
    'median_center_error_deg', NaN, 'p90_center_error_deg', NaN, ...
    'median_axis_error_deg', NaN, 'p90_axis_error_deg', NaN, ...
    'median_separation_error_deg', NaN, ...
    'p90_separation_error_deg', NaN, ...
    'median_separation_vector_error_deg', NaN, ...
    'p90_separation_vector_error_deg', NaN, ...
    'median_runtime_sec', NaN, 'p90_runtime_sec', NaN, ...
    'comparison_id', "", 'paired_count', 0, ...
    'wins', 0, 'ties', 0, 'losses', 0);
end

function integrity = validate_inputs_local(rows, registry, constants)
expected = struct('CORE_LITE', 72, 'CORE_PLUS', 72, ...
    'TANGENT_PROFILE_SAFE', 72, ...
    'FULL4D_BEAMSPACE_CML_MULTISTART', 72, ...
    'FULL4D_ELEMENT_CML_MULTISTART', 24, ...
    'BEAMSPACE_MUSIC_K2', 72, 'ELEMENT_MUSIC_K2', 72);
names = fieldnames(expected);
counts_ok = height(rows) == 456 && height(registry) == 72;
for index = 1:numel(names)
    counts_ok = counts_ok && nnz(rows.method_id == string(names{index})) == ...
        expected.(names{index});
end
hash_ok = all(rows.element_hash_match_flag);
truth_ok = ~any(rows.truth_used_in_fit_flag) && ...
    ~any(rows.profile_used_in_fit_flag) && ...
    ~any(rows.tangent_used_in_start_flag) && ...
    ~any(rows.core_used_in_start_flag);
beam = rows(rows.method_id == "FULL4D_BEAMSPACE_CML_MULTISTART", :);
coarse_ok = height(beam) == constants.trial_count && ...
    all(beam.coarse_candidate_count == 210);
music = rows(ismember(rows.method_id, ...
    ["BEAMSPACE_MUSIC_K2", "ELEMENT_MUSIC_K2"]), :);
music_ok = all(~music.applicable(music.L == 1)) && ...
    all(music.applicability_status(music.L == 1) == ...
    "NOT_APPLICABLE_INSUFFICIENT_SAMPLE_SUBSPACE_RANK") && ...
    all(music.applicable(ismember(music.L, constants.music_applicable_L)));
element = rows(rows.method_id == "FULL4D_ELEMENT_CML_MULTISTART", :);
element_subset_ok = height(element) == 24 && ...
    all(element.L == constants.element_reference_L);
integrity = struct('counts_ok', counts_ok, 'element_hashes_ok', hash_ok, ...
    'truth_isolation_ok', truth_ok, 'coarse_enumeration_ok', coarse_ok, ...
    'music_applicability_ok', music_ok, ...
    'element_reference_subset_ok', element_subset_ok, ...
    'experiment_integrity_ok', counts_ok && hash_ok && truth_ok && ...
    coarse_ok && music_ok && element_subset_ok);
if ~integrity.experiment_integrity_ok
    error('stage8_k2_cb_summarize:Integrity', ...
        'Formal comparison failed a protocol integrity contract.');
end
end

function paths = evidence_paths_local(directory)
prefix = fullfile(directory, '34_stage8_k2_classical_baseline_');
paths = struct('report', [prefix, 'comparison.md'], ...
    'trials', [prefix, 'trials.csv'], ...
    'summary', [prefix, 'summary.csv'], ...
    'profile_summary', [prefix, 'profile_summary.csv'], ...
    'applicability', [prefix, 'applicability.csv'], ...
    'complexity', [prefix, 'complexity.csv']);
end

function write_tables_local(rows, summary, profile_summary, ...
    applicability, complexity, paths)
writetable(rows, paths.trials);
writetable(summary, paths.summary);
writetable(profile_summary, paths.profile_summary);
writetable(applicability, paths.applicability);
writetable(complexity, paths.complexity);
end

function write_report_local(path_now, rows, summary, registry, ...
    resources, integrity, constants, runtime_root)
[status, head] = system('git rev-parse HEAD');
if status ~= 0, head = 'UNKNOWN'; else, head = strtrim(head); end
fid = fopen(path_now, 'w');
if fid < 0
    error('stage8_k2_cb_summarize:ReportOpen', ...
        'Unable to create the comparison report.');
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# Stage8 K2 Classical Baseline Comparison\n\n');
fprintf(fid, 'Protocol: `%s`\n\n', constants.protocol);
fprintf(fid, 'Execution HEAD: `%s`\n\n', head);
fprintf(fid, 'Runtime root: `%s`\n\n', strrep(runtime_root, filesep, '/'));
fprintf(fid, 'Trial reconstruction: `72/72` exact element hashes.\n\n');
fprintf(fid, ['Integrity: counts `%d`; hashes `%d`; truth isolation `%d`; ', ...
    'coarse enumeration `%d`; MUSIC applicability `%d`; ', ...
    'element subset `%d`.\n\n'], ...
    integrity.counts_ok, integrity.element_hashes_ok, ...
    integrity.truth_isolation_ok, integrity.coarse_enumeration_ok, ...
    integrity.music_applicability_ok, integrity.element_reference_subset_ok);
fprintf(fid, '## Fair-set accuracy\n\n');
fprintf(fid, '| Set | Method | Applicable | Valid | Median/p90 joint RMSE deg | Median/p90 center deg | Median/p90 axis deg | Median/p90 rho error deg | Median/p90 vector error deg |\n');
fprintf(fid, '|---|---|---:|---:|---:|---:|---:|---:|---:|\n');
metrics = summary(summary.row_type == "METHOD", :);
for index = 1:height(metrics)
    fprintf(fid, '| %s | %s | %d | %d | %.17g / %.17g | %.17g / %.17g | %.17g / %.17g | %.17g / %.17g | %.17g / %.17g |\n', ...
        char(metrics.comparison_set(index)), char(metrics.method_id(index)), ...
        metrics.applicable_count(index), metrics.valid_count(index), ...
        metrics.median_joint_RMSE_deg(index), ...
        metrics.p90_joint_RMSE_deg(index), ...
        metrics.median_center_error_deg(index), ...
        metrics.p90_center_error_deg(index), ...
        metrics.median_axis_error_deg(index), ...
        metrics.p90_axis_error_deg(index), ...
        metrics.median_separation_error_deg(index), ...
        metrics.p90_separation_error_deg(index), ...
        metrics.median_separation_vector_error_deg(index), ...
        metrics.p90_separation_vector_error_deg(index));
end
fprintf(fid, '\n## Paired joint-RMSE counts\n\n');
fprintf(fid, '| Set | Comparison | Pairs | Wins | Ties | Losses |\n');
fprintf(fid, '|---|---|---:|---:|---:|---:|\n');
pairs = summary(summary.row_type == "PAIRED", :);
for index = 1:height(pairs)
    fprintf(fid, '| %s | %s | %d | %d | %d | %d |\n', ...
        char(pairs.comparison_set(index)), ...
        char(pairs.comparison_id(index)), pairs.paired_count(index), ...
        pairs.wins(index), pairs.ties(index), pairs.losses(index));
end
fprintf(fid, '\nTie tolerance is reporting-only at `1e-6 deg`.\n\n');
fprintf(fid, '## Applicability and numerical diagnostics\n\n');
music_l1 = rows(ismember(rows.method_id, ...
    ["BEAMSPACE_MUSIC_K2", "ELEMENT_MUSIC_K2"]) & rows.L == 1, :);
fprintf(fid, '- MUSIC applicable: `%d/96` method-trial rows; L=1 N/A: `%d/48`.\n', ...
    nnz(rows.applicable & ismember(rows.method_id, ...
    ["BEAMSPACE_MUSIC_K2", "ELEMENT_MUSIC_K2"])), ...
    nnz(~music_l1.applicable));
fprintf(fid, '- Beamspace numerical-optimization-incomplete flags: `%d/72`.\n', ...
    nnz(rows.numerical_optimization_incomplete_flag));
fprintf(fid, '- MUSIC fixed grid: `%d` points; no smoothing or truth-based peak distance.\n\n', ...
    resources.grid_point_count);
fprintf(fid, '## P2/P4 interpretation matrix\n\n');
fprintf(fid, 'Quantitative P2/P4 evidence is retained in the trial, summary, and profile-summary CSV files. This generated report applies no automatic performance gate. Final descriptive review must distinguish: A, fixed Tangent center/axis restriction; B, beamspace information loss; C, common ML threshold/statistical ambiguity; and D, effective Tangent dimension reduction.\n\n');
fprintf(fid, 'P2/P4 diagnosis: `DESCRIPTIVE_REVIEW_REQUIRED`.\n\n');
fprintf(fid, 'Alpha-rho motivation: `INCONCLUSIVE_PENDING_DESCRIPTIVE_REVIEW`.\n\n');
fprintf(fid, '## Boundaries\n\n');
fprintf(fid, 'The two full4D methods are finite deterministic multistart numerical approximations, not global-optimum proofs. Element and beamspace likelihood values are not compared directly. MUSIC L=1 N/A rows are not failures or Tangent wins. No Tangent, alpha-rho, automatic-K, bootstrap, production, or upstream-branch change is authorized.\n');
assert(height(registry) == 72 && height(rows) == 456);
end

function value = mean_or_nan_local(values)
values = values(isfinite(values));
if isempty(values), value = NaN; else, value = mean(values); end
end

function value = median_or_nan_local(values)
values = values(isfinite(values));
if isempty(values), value = NaN; else, value = median(values); end
end

function value = percentile_or_nan_local(values, percentage)
values = sort(values(isfinite(values)));
if isempty(values)
    value = NaN;
    return;
end
position = 1 + (numel(values) - 1) * percentage / 100;
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    weight = position - lower;
    value = (1 - weight) * values(lower) + weight * values(upper);
end
end
