function constants = stage8_k2_cb_constants()
%STAGE8_K2_CB_CONSTANTS Frozen classical-baseline comparison contract.

constants = struct( ...
    'protocol', 'STAGE8_K2_CLASSICAL_BASELINE_COMPARISON_V1', ...
    'authorization', ...
    'AUTHORIZE_STAGE8_K2_CLASSICAL_BASELINE_COMPARISON_V1', ...
    'branch', 'experiment/stage8-k2-classical-baselines-v1', ...
    'base_commit', '721c30aa96f1687c757004613c23e9fb6a814afd', ...
    'expected_origin_tangent', ...
    '721c30aa96f1687c757004613c23e9fb6a814afd', ...
    'expected_origin_core_v2', ...
    '9bcb4f7e0d4ec314e5a822deb0ea02216c10c8f7', ...
    'expected_origin_main', ...
    '247fad2208e77b04f7062e22b0fd3fd8a81bfc1f', ...
    'primary_measurement_config_id', 'PRIMARY_RECT_E14_A31', ...
    'noise_profile_ids', ...
    ["WHITE"; "STAGE5_TOEPLITZ_CORRELATED"], ...
    'snapshot_counts', [1, 4, 8], ...
    'snr_db_values', [-6, 0, 6], ...
    'profile_ids', ["P1"; "P2"; "P3"; "P4"], ...
    'trial_count', 72, ...
    'frozen_method_ids', ...
    ["CORE_LITE"; "CORE_PLUS"; "TANGENT_PROFILE_SAFE"], ...
    'baseline_method_ids', ...
    ["FULL4D_BEAMSPACE_CML_MULTISTART"; ...
    "FULL4D_ELEMENT_CML_MULTISTART"; ...
    "BEAMSPACE_MUSIC_K2"; "ELEMENT_MUSIC_K2"], ...
    'element_reference_L', 4, ...
    'music_applicable_L', [4, 8], ...
    'top_start_count', 6, ...
    'max_sweeps', 12, ...
    'scan_nodes_per_coordinate', 9, ...
    'fminbnd_TolX_deg', 1e-4, ...
    'fminbnd_MaxFunEvals', 80, ...
    'minimum_separation_deg', 1e-3, ...
    'relative_score_tolerance', 1e-8, ...
    'endpoint_update_tolerance_deg', 1e-3, ...
    'rank_multiplier', 1, ...
    'music_grid_step_deg', 0.005, ...
    'music_grid_chunk_size', 2048, ...
    'paired_tie_tolerance_deg', 1e-6, ...
    'zero_separation_tolerance_deg', 1e-12, ...
    'runtime_root', ...
    'E:\bs_innovation_runtime\stage8_k2_classical_baselines_v1');
end
