function context = stage8_k2_cb_build_context(repo_dir)
%STAGE8_K2_CB_BUILD_CONTEXT Load frozen models and evidence identities.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_cb_build_context:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
constants = stage8_k2_cb_constants();
plan = build_stage8_locked_plan(repo_dir, sim_cfg(), ...
    struct('require_formal_runtime', false));
expected_bounds = [7.4, 8.6, 9.8, 10.2];
if ~isequal(plan.local_domain.domain_bounds_deg, expected_bounds) || ...
        height(plan.measurement_registry) ~= 4
    error('stage8_k2_cb_build_context:FrozenPlan', ...
        'The frozen Stage8 domain or measurement registry changed.');
end

evidence_dir = fullfile(repo_dir, 'innovation-mining');
frozen_path = fullfile(evidence_dir, ...
    '31_stage8_k2_tangent_profile_trials.csv');
diagnostic_path = fullfile(evidence_dir, ...
    '32_stage8_k2_tangent_profile_corrected_diagnostics.csv');
if ~isfile(frozen_path) || ~isfile(diagnostic_path)
    error('stage8_k2_cb_build_context:Evidence', ...
        'Frozen evidence 31/32 is missing.');
end
frozen = readtable(frozen_path, 'TextType', 'string');
diagnostics = readtable(diagnostic_path, 'TextType', 'string');
validate_frozen_local(frozen, diagnostics, constants);
identity = build_identity_local(frozen, constants);

context = struct('repo_dir', repo_dir, 'constants', constants, ...
    'plan', plan, 'stage5_locked', build_stage8_stage5_locked_config(), ...
    'primary_measurement_config_id', ...
    constants.primary_measurement_config_id, ...
    'frozen_trials_path', frozen_path, ...
    'corrected_diagnostics_path', diagnostic_path, ...
    'frozen_method_rows', frozen, ...
    'corrected_diagnostics', diagnostics, ...
    'frozen_trial_identity', identity, ...
    'single_cpi_flag', true, ...
    'same_range_doppler_cell_flag', true, ...
    'cross_cpi_data_used_flag', false, ...
    'tracking_input_used_flag', false, ...
    'K_estimated_inside_module_flag', false);
context.context_hash = stage8_k2_cb_stable_hash(constants.protocol, ...
    plan.local_domain.domain_hash, plan.stage8_measurement_plan_hash, ...
    identity, constants.base_commit);
end

function validate_frozen_local(frozen, diagnostics, constants)
required = {'trial_id','method_id','noise_profile_id','L','snr_db', ...
    'profile_id','source_seed','noise_seed','element_trial_hash', ...
    'fit_valid','angles_hat_deg','RSS','loglik','joint_RMSE_deg', ...
    'score_call_count','SVD_call_count','runtime_sec', ...
    'truth_used_in_fit_flag'};
if height(frozen) ~= constants.trial_count * ...
        numel(constants.frozen_method_ids) || ...
        ~all(ismember(required, frozen.Properties.VariableNames)) || ...
        height(diagnostics) ~= constants.trial_count || ...
        ~all(ismember({'trial_id','element_trial_hash', ...
        'raw_tangent_loglik','direction_axis_error_deg'}, ...
        diagnostics.Properties.VariableNames))
    error('stage8_k2_cb_build_context:EvidenceSchema', ...
        'Frozen evidence 31/32 violates the expected schema or count.');
end
for index = 1:numel(constants.frozen_method_ids)
    if nnz(frozen.method_id == constants.frozen_method_ids(index)) ~= ...
            constants.trial_count
        error('stage8_k2_cb_build_context:MethodCount', ...
            'A frozen method does not contain exactly 72 rows.');
    end
end
if any(logical(frozen.truth_used_in_fit_flag)) || ...
        numel(unique(diagnostics.trial_id)) ~= constants.trial_count
    error('stage8_k2_cb_build_context:EvidenceIntegrity', ...
        'Frozen truth isolation or diagnostic identity is invalid.');
end
end

function identity = build_identity_local(frozen, constants)
ids = unique(frozen.trial_id, 'stable');
rows = cell(numel(ids), 1);
for index = 1:numel(ids)
    subset = frozen(frozen.trial_id == ids(index), :);
    hashes = unique(subset.element_trial_hash);
    if height(subset) ~= numel(constants.frozen_method_ids) || ...
            numel(hashes) ~= 1
        error('stage8_k2_cb_build_context:TrialIdentity', ...
            'Frozen methods do not share one element hash per trial.');
    end
    rows{index} = struct('trial_id', ids(index), ...
        'element_trial_hash', hashes(1), ...
        'noise_profile_id', subset.noise_profile_id(1), ...
        'L', double(subset.L(1)), 'snr_db', double(subset.snr_db(1)), ...
        'profile_id', subset.profile_id(1), ...
        'source_seed', double(subset.source_seed(1)), ...
        'noise_seed', double(subset.noise_seed(1)));
end
identity = struct2table(vertcat(rows{:}));
if height(identity) ~= constants.trial_count
    error('stage8_k2_cb_build_context:TrialCount', ...
        'Frozen evidence does not contain 72 unique trials.');
end
end
