function cleanup = stage8_k2_cb_add_paths(repo_dir)
%STAGE8_K2_CB_ADD_PATHS Scope frozen dependencies and this isolated tool.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_cb_add_paths:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
old_path = path;
cleanup = onCleanup(@() path(old_path));

project_dir = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model');
steps_dir = fullfile(project_dir, 'steps');
directories = { ...
    fullfile(project_dir, 'core', 'config'), ...
    fullfile(project_dir, 'core', 'array'), ...
    fullfile(steps_dir, 'step_12_0_receive_model_correction', 'common'), ...
    fullfile(steps_dir, 'step_12_1_sequential_dbf_model', 'common'), ...
    fullfile(steps_dir, 'step_12_2_stable_dml_backend', 'common'), ...
    fullfile(steps_dir, 'step_12_3_grouped_conditional_dml', 'common'), ...
    fullfile(steps_dir, 'step_12_4_near_pair_tangent_asymptotics', 'common'), ...
    fullfile(steps_dir, 'step_12_5_exact_subset_fim_beam_design', 'common'), ...
    fullfile(steps_dir, 'step_12_6_k12_bootstrap_resolution'), ...
    fullfile(steps_dir, 'step_12_6_k12_bootstrap_resolution', 'common'), ...
    fullfile(steps_dir, 'step_12_7_known_k_local_cell_refinement', 'common'), ...
    fullfile(steps_dir, 'step_12_7_known_k_local_cell_refinement', 'validation'), ...
    fullfile(repo_dir, 'tools', 'stage8_k2_tangent_profile', 'matlab'), ...
    fullfile(repo_dir, 'tools', 'stage8_k2_classical_baselines', 'matlab'), ...
    fullfile(repo_dir, 'tools', 'stage8_k2_classical_baselines', 'tests')};
for index = 1:numel(directories)
    if ~isfolder(directories{index})
        error('stage8_k2_cb_add_paths:MissingDependency', ...
            'Required directory is missing: %s', directories{index});
    end
    addpath(directories{index});
end
end
