function contract = build_stage6_provenance_contract( ...
    repo_dir, plan_inputs, opts)
%BUILD_STAGE6_PROVENANCE_CONTRACT Build stable plan and implementation ids.

if nargin < 3 || isempty(opts), opts = struct(); end
opts = normalize_options_local(opts);
validate_plan_inputs_local(plan_inputs);

git_provenance = read_stage6_git_provenance(repo_dir, ...
    plan_inputs.baseline_commit, opts.git_provenance_options);
scope = collect_stage6_source_scope(repo_dir, struct());
[source_manifest, source_tree_hash] = build_git_blob_manifest( ...
    repo_dir, scope.source_paths, scope.source_scope_version, struct());
[dependency_manifest, dependency_tree_hash] = build_git_blob_manifest( ...
    repo_dir, scope.dependency_paths, scope.dependency_scope_version, struct());

controls_contract = select_controls_local(plan_inputs.controls);
measurement_configs = rmfield(plan_inputs.configs, ...
    {'is_primary_configuration','diagnostic_role'});
classification = struct( ...
    'config_id', {plan_inputs.configs.config_id}, ...
    'is_primary_configuration', ...
    num2cell([plan_inputs.configs.is_primary_configuration]), ...
    'diagnostic_role', {plan_inputs.configs.diagnostic_role});

controls_hash = stable_stage6_hash(controls_contract);
measurement_plan_hash = stable_stage6_hash(measurement_configs, ...
    plan_inputs.controls.phase_factor, ...
    plan_inputs.controls.measurement_version_id);
experiment_plan_hash = stable_stage6_hash(controls_hash, ...
    measurement_plan_hash, plan_inputs.centers_deg, plan_inputs.directions, ...
    plan_inputs.separation_deg, classification, source_tree_hash, ...
    dependency_tree_hash);
provenance_hash = stable_stage6_hash(plan_inputs.baseline_commit, ...
    source_tree_hash, dependency_tree_hash, controls_hash, ...
    measurement_plan_hash, experiment_plan_hash, ...
    plan_inputs.controls.phase_factor, plan_inputs.matlab_release_contract);

contract = struct();
contract.baseline_commit = plan_inputs.baseline_commit;
contract.runtime_head_commit = git_provenance.runtime_head_commit;
contract.baseline_ancestor_flag = git_provenance.baseline_ancestor_flag;
contract.working_tree_clean_at_start = git_provenance.working_tree_clean_flag;
contract.git_status_porcelain = git_provenance.git_status_porcelain;
contract.provenance_status = git_provenance.provenance_status;
contract.stage6_source_tree_hash = source_tree_hash;
contract.stage6_dependency_tree_hash = dependency_tree_hash;
contract.stage6_controls_hash = controls_hash;
contract.stage6_measurement_plan_hash = measurement_plan_hash;
contract.stage6_experiment_plan_hash = experiment_plan_hash;
contract.stage6_provenance_hash = provenance_hash;
contract.source_manifest = source_manifest;
contract.dependency_manifest = dependency_manifest;
contract.source_scope_version = scope.source_scope_version;
contract.dependency_scope_version = scope.dependency_scope_version;
contract.provenance_contract_version = 'STAGE6_PROVENANCE_CONTRACT_V1';
contract.matlab_release_contract = plan_inputs.matlab_release_contract;
contract.phase_factor = plan_inputs.controls.phase_factor;
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('build_stage6_provenance_contract:Options', ...
        'opts must be a scalar struct.');
end
allowed = {'git_provenance_options'};
unknown = setdiff(fieldnames(opts), allowed);
if ~isempty(unknown)
    error('build_stage6_provenance_contract:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
if ~isfield(opts, 'git_provenance_options')
    opts.git_provenance_options = struct();
end
end

function validate_plan_inputs_local(inputs)
required = {'baseline_commit','controls','configs','centers_deg', ...
    'directions','separation_deg','matlab_release_contract'};
if ~(isstruct(inputs) && isscalar(inputs) && all(isfield(inputs, required)))
    error('build_stage6_provenance_contract:PlanInputs', ...
        'plan_inputs is missing a required stable plan object.');
end
if inputs.controls.phase_factor ~= 1
    error('build_stage6_provenance_contract:PhaseFactor', ...
        'Stage 6 provenance requires phase_factor=1.');
end
end

function selected = select_controls_local(controls)
fields = { ...
    'phase_factor','matlab_precision', ...
    'first_derivative_step_rad','second_derivative_step_rad', ...
    'third_derivative_step_rad','derivative_sensitivity_scales', ...
    'numeric_floor_multiplier','rank_multiplier', ...
    'negative_eigenvalue_tolerance_multiplier', ...
    'null_tolerance_multiplier','near_null_ratio', ...
    'first_derivative_relative_error_gate', ...
    'stage5_manifold_consistency_gate', ...
    'second_derivative_relative_error_gate', ...
    'third_derivative_relative_error_gate', ...
    'sigma2_ratio_error_gate','coherence_ratio_error_gate', ...
    'normalized_gram_ratio_error_gate', ...
    'exact_identity_relative_error_gate', ...
    'exact_identity_roundoff_multiplier', ...
    'invariance_relative_error_gate','synthetic_null_slope_gate', ...
    'synthetic_null_ratio_error_gate','theory_sigma2_constant', ...
    'theory_coherence_constant','theory_normalized_gram_constant', ...
    'method_version_id'};
if ~all(isfield(controls, fields))
    error('build_stage6_provenance_contract:Controls', ...
        'The controls object is missing a stable contract field.');
end
selected = struct();
for index = 1:numel(fields)
    selected.(fields{index}) = controls.(fields{index});
end
end
