function table_out = build_stage6_reproduction_comparison_output( ...
    comparison, summary)
%BUILD_STAGE6_REPRODUCTION_COMPARISON_OUTPUT Attach fixed summary metadata.

required_summary = {'artifact_count','row_count_compared', ...
    'numeric_value_count','exact_value_count','missing_artifact_count', ...
    'row_key_mismatch_count','numeric_failure_count','exact_failure_count', ...
    'maximum_absolute_difference','maximum_relative_difference', ...
    'comparison_status','pass_flag'};
if ~(istable(comparison) && ~isempty(comparison) && istable(summary) && ...
        height(summary) == 1 && all(ismember(required_summary, ...
        summary.Properties.VariableNames)))
    error('build_stage6_reproduction_comparison_output:Inputs', ...
        'Comparison rows and one valid summary row are required.');
end
table_out = comparison;
table_out.summary_artifact_count = repmat( ...
    summary.artifact_count(1), height(table_out), 1);
table_out.summary_row_count_compared = repmat( ...
    summary.row_count_compared(1), height(table_out), 1);
table_out.summary_numeric_value_count = repmat( ...
    summary.numeric_value_count(1), height(table_out), 1);
table_out.summary_exact_value_count = repmat( ...
    summary.exact_value_count(1), height(table_out), 1);
table_out.summary_missing_artifact_count = repmat( ...
    summary.missing_artifact_count(1), height(table_out), 1);
table_out.summary_row_key_mismatch_count = repmat( ...
    summary.row_key_mismatch_count(1), height(table_out), 1);
table_out.summary_numeric_failure_count = repmat( ...
    summary.numeric_failure_count(1), height(table_out), 1);
table_out.summary_exact_failure_count = repmat( ...
    summary.exact_failure_count(1), height(table_out), 1);
table_out.summary_maximum_absolute_difference = repmat( ...
    summary.maximum_absolute_difference(1), height(table_out), 1);
table_out.summary_maximum_relative_difference = repmat( ...
    summary.maximum_relative_difference(1), height(table_out), 1);
table_out.summary_comparison_status = repmat( ...
    string(summary.comparison_status(1)), height(table_out), 1);
table_out.summary_pass_flag = repmat( ...
    logical(summary.pass_flag(1)), height(table_out), 1);
end
