function contract = build_stage6_reproduction_comparison_contract()
%BUILD_STAGE6_REPRODUCTION_COMPARISON_CONTRACT Freeze old/new CSV semantics.

artifact_id = [ ...
    "stage6_configuration_registry"; ...
    "measurement_hash_registry"; ...
    "first_derivative_validation"; ...
    "higher_directional_derivative_validation"; ...
    "projected_metric_properties"; ...
    "tangent_eigenvalues"; ...
    "secant_tangent_nondegenerate"; ...
    "secant_tangent_tail_summary"; ...
    "secant_tangent_exact_null"; ...
    "secant_tangent_near_null"; ...
    "synthetic_null_validation"; ...
    "two_column_exact_identity"; ...
    "geometry_invariance_validation"; ...
    "column_norm_asymmetry"; ...
    "stage6_keypoints"];
n = numel(artifact_id);
relative_path = "results/" + artifact_id + ".csv";
key_columns = cell(n, 1);
ignored_columns = cell(n, 1);
exact_columns = cell(n, 1);
expected_identity_change_columns = cell(n, 1);
expected_new_columns = cell(n, 1);
ignored_row_keys = cell(n, 1);
expected_identity_change_row_keys = cell(n, 1);
exact_value_row_keys = cell(n, 1);
comparison_scope = repmat("NUMERIC_EVIDENCE", n, 1);

global_ignored = [ ...
    "baseline_commit"; "stage6_source_tree_hash"; ...
    "stage6_dependency_tree_hash"; "stage6_controls_hash"; ...
    "stage6_measurement_plan_hash"; "stage6_experiment_plan_hash"; ...
    "stage6_provenance_hash"; "provenance_contract_version"; ...
    "baseline_ancestor_flag"; "working_tree_clean_at_start"; ...
    "runtime_head_commit"; "validation_runtime_sec"; ...
    "registered_experiment_runtime_sec"; "process_peak_memory"; ...
    "matlab_process_peak_memory_bytes"; "file_byte_count"; ...
    "result_data_volume_bytes"; "figure_volume_bytes"];
common_exact = ["pass_flag"; "phase_factor"; "theory_status"; ...
    "prior_art_status"];
for index = 1:n
    ignored_columns{index} = global_ignored;
    expected_identity_change_columns{index} = "fixed_measurement_hash";
    expected_new_columns{index} = strings(0, 1);
    ignored_row_keys{index} = strings(0, 1);
    expected_identity_change_row_keys{index} = strings(0, 1);
    exact_value_row_keys{index} = strings(0, 1);
end

set_local("stage6_configuration_registry", "config_id", [ ...
    "is_primary_configuration"; "az_beam_count"; "el_beam_count"; ...
    "sequential_channel_count"; "whitening_rank"; ...
    "noise_covariance_id"; "az_beam_deg"; "el_beam_deg"; ...
    "beam_indices"; "fixed_objects_candidate_independent_flag"; ...
    common_exact], "CONFIGURATION_REGISTRY");
set_local("measurement_hash_registry", "config_id", [ ...
    "Wseq_hash"; "Cseq_hash"; "Tseq_hash"; "array_geometry_hash"; ...
    "hash_length"; common_exact], "MEASUREMENT_IDENTITY");
set_local("first_derivative_validation", ...
    ["config_id"; "center_az_deg"; "center_el_deg"], [ ...
    "finite_difference_step_rad"; "derivative_unit"; common_exact], ...
    "DERIVATIVE_NUMERICS");
set_local("higher_directional_derivative_validation", ...
    ["config_id"; "center_az_deg"; "center_el_deg"; "direction_id"], [ ...
    "direction_az_component"; "direction_el_component"; ...
    "first_step_rad"; "second_step_rad"; "third_step_rad"; ...
    "derivative_unit"; common_exact], "DERIVATIVE_NUMERICS");
set_local("projected_metric_properties", ...
    ["config_id"; "center_az_deg"; "center_el_deg"], [ ...
    "negative_eigenvalue_tolerance"; common_exact], "TANGENT_GEOMETRY");
set_local("tangent_eigenvalues", ...
    ["config_id"; "center_az_deg"; "center_el_deg"], [ ...
    "rank_T"; "null_tolerance"; "tangent_class"; common_exact], ...
    "TANGENT_GEOMETRY");
set_local("secant_tangent_nondegenerate", ...
    ["config_id"; "center_az_deg"; "center_el_deg"; "direction_id"; ...
    "separation_norm_rad"], [ ...
    "direction_az_component"; "direction_el_component"; ...
    "numeric_floor"; "numeric_floor_reached_flag"; ...
    "coherence_roundoff_clipped_flag"; "Wseq_hash"; "Cseq_hash"; ...
    "Tseq_hash"; "case_status"; "direction_class"; common_exact], ...
    "SECANT_NUMERICS");
set_local("secant_tangent_tail_summary", ...
    ["config_id"; "center_az_deg"; "center_el_deg"; "direction_id"], [ ...
    "valid_point_count"; "tail_point_count"; ...
    "taylor_residual_decrease_flag"; "tail_status"; common_exact], ...
    "ASYMPTOTIC_TAIL");
set_local("secant_tangent_exact_null", ...
    ["config_id"; "center_az_deg"; "center_el_deg"; "direction_id"], [ ...
    "null_status"; common_exact], "NULL_CLASSIFICATION");
set_local("secant_tangent_near_null", ...
    ["config_id"; "center_az_deg"; "center_el_deg"; "direction_id"], [ ...
    "null_status"; common_exact], "NULL_CLASSIFICATION");
set_local("synthetic_null_validation", ...
    ["config_id"; "direction_id"; "separation_norm_rad"], ...
    common_exact, "SYNTHETIC_NULL_NUMERICS");
set_local("two_column_exact_identity", ...
    ["config_id"; "center_az_deg"; "center_el_deg"; "direction_id"; ...
    "separation_norm_rad"], [ ...
    "identity_numerically_saturated_flag"; common_exact], ...
    "EXACT_IDENTITY");
set_local("geometry_invariance_validation", ...
    ["config_id"; "transform_id"], common_exact, "GEOMETRY_INVARIANCE");
set_local("column_norm_asymmetry", ...
    ["config_id"; "center_az_deg"; "center_el_deg"; "direction_id"; ...
    "separation_norm_rad"], common_exact, "COLUMN_NORM_DIAGNOSTIC");
set_local("stage6_keypoints", "metric", [ ...
    "unit"; "status"; "pass_flag"; "theory_status_detail"; ...
    "physical_null_status"; "phase_factor"; "theory_status"; ...
    "prior_art_status"], "KEYPOINT_SUMMARY");

config_index = find(artifact_id == "stage6_configuration_registry", 1);
expected_new_columns{config_index} = "global_beam_indices";
keypoint_index = find(artifact_id == "stage6_keypoints", 1);
ignored_row_keys{keypoint_index} = [ ...
    "validation_runtime_sec"; "fixed_model_memory_bytes"; ...
    "result_data_volume_bytes"; "figure_volume_bytes"; "figure_count"];
expected_identity_change_row_keys{keypoint_index} = ...
    "metric=registered_test_row_count";
exact_value_row_keys{keypoint_index} = "metric=" + [ ...
    "active_phase_factor"; "registered_measurement_config_count"; ...
    "registered_primary_secant_case_count"; "minimum_tail_point_count"; ...
    "mathematical_validation_pass"; "code_analyzer_message_count"; ...
    "stage6_scope_violation_count"; "stage5_frozen_file_count"; ...
    "stage5_frozen_hash_mismatch_count"; "step11_frozen_file_count"; ...
    "step11_frozen_hash_mismatch_count"; ...
    "receive_manifold_evaluation_count"; "secant_svd_count"; ...
    "metric_eigendecomposition_count"; "derivative_evaluation_count"; ...
    "direct_identical_prior_art_found_flag"; "stage6_overall_pass"];

numeric_absolute_tolerance = repmat(1e-14, n, 1);
numeric_relative_tolerance = repmat(1e-12, n, 1);
contract = table(artifact_id, relative_path, key_columns, ignored_columns, ...
    numeric_absolute_tolerance, numeric_relative_tolerance, exact_columns, ...
    comparison_scope, expected_identity_change_columns, ...
    expected_new_columns, ignored_row_keys, ...
    expected_identity_change_row_keys, exact_value_row_keys);

    function set_local(id, keys, exact, scope)
        row_index = find(artifact_id == string(id), 1);
        key_columns{row_index} = unique(string(keys(:)), 'stable');
        exact_columns{row_index} = unique([string(keys(:)); ...
            string(exact(:))], 'stable');
        comparison_scope(row_index) = string(scope);
    end
end
