function write_stage6_comparison_csv(path_now, comparison)
%WRITE_STAGE6_COMPARISON_CSV Serialize comparison evidence in fixed order.

columns = {'artifact_id','relative_path','row_key','column_name', ...
    'comparison_kind','old_value_text','new_value_text','old_numeric_value', ...
    'new_numeric_value','absolute_difference','relative_difference', ...
    'absolute_tolerance','relative_tolerance', ...
    'expected_identity_change_flag','pass_flag'};
summary_columns = {'summary_artifact_count','summary_row_count_compared', ...
    'summary_numeric_value_count','summary_exact_value_count', ...
    'summary_missing_artifact_count','summary_row_key_mismatch_count', ...
    'summary_numeric_failure_count','summary_exact_failure_count', ...
    'summary_maximum_absolute_difference', ...
    'summary_maximum_relative_difference','summary_comparison_status', ...
    'summary_pass_flag'};
if isstring(path_now), path_now = char(path_now); end
if ~(ischar(path_now) && isrow(path_now) && ~isempty(path_now) && ...
        istable(comparison) && all(ismember(columns, ...
        comparison.Properties.VariableNames)))
    error('write_stage6_comparison_csv:Inputs', ...
        'A path and valid comparison table are required.');
end
if all(ismember(summary_columns, comparison.Properties.VariableNames))
    columns = [columns, summary_columns];
end
parent = fileparts(path_now);
if ~isempty(parent) && exist(parent, 'dir') ~= 7, mkdir(parent); end
writetable(comparison(:, columns), path_now);
end
