function row = stage8_k2_mc_snr_row(spec, trial, metrics)
%STAGE8_K2_MC_SNR_ROW Materialize one registered SNR result row.

row = struct('trial_id', string(spec.trial_id), ...
    'global_trial_index', double(spec.global_trial_index), ...
    'element_trial_hash', string(trial.element_trial_hash), ...
    'measurement_hash', string(trial.measurement_hash), ...
    'noise_profile_id', string(spec.noise_profile_id), ...
    'L', double(spec.L), 'profile_id', string(spec.profile_id), ...
    'white_beamspace_snr_target_db', ...
    double(spec.white_beamspace_snr_target_db), ...
    'replicate_id', double(spec.replicate_id), ...
    'base_realization_index', double(spec.base_realization_index), ...
    'source_seed', double(spec.source_seed), ...
    'noise_seed', double(spec.noise_seed), ...
    'snr_control_domain', string(spec.snr_control_domain), ...
    'white_snr_scaling_relative_error', ...
    double(trial.white_snr_scaling_relative_error), ...
    'whitening_residual', ...
    double(metrics.whitening_covariance_residual));
names = fieldnames(metrics);
for index = 1:numel(names)
    row.(names{index}) = metrics.(names{index});
end
row = struct2table(row);
end
