function [trial, metrics] = stage8_k2_mc_generate_trial(spec, context)
%STAGE8_K2_MC_GENERATE_TRIAL Reuse frozen generation and bind MC identity.

required = {'trial_id','base_realization_id','replicate_id', ...
    'base_realization_index','white_beamspace_snr_target_db', ...
    'source_seed','noise_seed','noise_profile_id','L','profile_id'};
if ~(istable(spec) && height(spec) == 1 && ...
        all(ismember(required, spec.Properties.VariableNames)))
    error('stage8_k2_mc_generate_trial:Spec', ...
        'spec is not one registered MC trial row.');
end
trial = stage8_k2_snr_generate_white_control_trial( ...
    spec, context.snr_context);
metrics = stage8_k2_snr_compute_metrics(trial);
model = trial.model;
measurement_hash = stage8_k2_mc_stable_hash( ...
    'MEASUREMENT', char(spec.noise_profile_id), ...
    context.primary_measurement_config_id, model.W_I, model.C_I, ...
    model.T_I, model.Rn_elem, double(model.whitening_rank));
element_trial_hash = stage8_k2_mc_stable_hash( ...
    context.constants.protocol, 'ELEMENT_TRIAL', char(spec.trial_id), ...
    trial.Y_element, trial.truth_angles_deg, ...
    double(spec.white_beamspace_snr_target_db), ...
    double(metrics.element_snr_expected_db), ...
    double(spec.source_seed), double(spec.noise_seed), ...
    char(spec.noise_profile_id), double(spec.L), char(spec.profile_id), ...
    double(spec.replicate_id), double(spec.base_realization_index), ...
    measurement_hash);
trial.frozen_snr_tool_hash = trial.element_trial_hash;
trial.element_trial_hash = string(element_trial_hash);
trial.measurement_hash = string(measurement_hash);
if ismember('measurement_hash', spec.Properties.VariableNames) && ...
        strlength(spec.measurement_hash) > 0 && ...
        spec.measurement_hash ~= trial.measurement_hash
    error('stage8_k2_mc_generate_trial:MeasurementHash', ...
        'Generated measurement identity differs from the registry.');
end
if ismember('element_trial_hash', spec.Properties.VariableNames) && ...
        strlength(spec.element_trial_hash) > 0 && ...
        spec.element_trial_hash ~= trial.element_trial_hash
    error('stage8_k2_mc_generate_trial:TrialHash', ...
        'Generated scientific trial hash differs from the registry.');
end
if abs(metrics.white_beam_snr_expected_db - ...
        spec.white_beamspace_snr_target_db) > ...
        context.constants.snr_db_tolerance
    error('stage8_k2_mc_generate_trial:WhiteTarget', ...
        'Expected white SNR missed its registered target.');
end
end
