function digest = stage8_k2_mc_checkpoint_hash(checkpoint)
%STAGE8_K2_MC_CHECKPOINT_HASH Hash runtime-independent checkpoint content.

methods = sortrows(checkpoint.method_rows, 'method_id');
if ismember('runtime_sec', methods.Properties.VariableNames)
    methods.runtime_sec(:) = 0;
end
digest = stage8_k2_mc_stable_hash( ...
    'CHECKPOINT_SCIENTIFIC_CONTENT', ...
    char(string(checkpoint.protocol)), ...
    char(string(checkpoint.checkpoint_contract_version)), ...
    checkpoint.registry_row, char(string(checkpoint.element_trial_hash)), ...
    checkpoint.snr_row, methods, char(string(checkpoint.code_identity)), ...
    char(string(checkpoint.registry_hash)), ...
    char(string(checkpoint.completion_status)));
end
