function [checkpoint, path_now] = stage8_k2_mc_checkpoint_write( ...
    runtime_root, spec, trial, snr_row, method_rows, context, ...
    registry_hash, runtime_sec)
%STAGE8_K2_MC_CHECKPOINT_WRITE Write, validate, and atomically commit a trial.

path_now = stage8_k2_mc_checkpoint_path(runtime_root, spec);
if isfile(path_now)
    error('stage8_k2_mc_checkpoint_write:Exists', ...
        'A final checkpoint already exists: %s', path_now);
end
temporary = [path_now, '.tmp'];
if isfile(temporary)
    delete(temporary);
end
checkpoint = struct( ...
    'protocol', context.constants.protocol, ...
    'checkpoint_contract_version', ...
    context.constants.checkpoint_contract_version, ...
    'registry_row', spec, ...
    'element_trial_hash', char(trial.element_trial_hash), ...
    'snr_row', snr_row, 'method_rows', method_rows, ...
    'scientific_hash', '', ...
    'code_identity', context.code_identity.tree_hash, ...
    'registry_hash', registry_hash, ...
    'completed_utc', stage8_k2_mc_utc_now(), ...
    'runtime_sec', double(runtime_sec), ...
    'completion_status', 'COMPLETE');
checkpoint.scientific_hash = stage8_k2_mc_checkpoint_hash(checkpoint);
save(temporary, 'checkpoint', '-mat');
stage8_k2_mc_checkpoint_validate( ...
    temporary, spec, context, registry_hash);
[ok, message] = movefile(temporary, path_now);
if ~ok
    error('stage8_k2_mc_checkpoint_write:Move', '%s', message);
end
stage8_k2_mc_checkpoint_validate( ...
    path_now, spec, context, registry_hash);
end
