function merged = stage8_k2_mc_merge( ...
    runtime_root, registry, context, registry_hash)
%STAGE8_K2_MC_MERGE Validate and merge all immutable checkpoints.

scan = stage8_k2_mc_scan_checkpoints( ...
    runtime_root, registry, context, registry_hash);
constants = context.constants;
if scan.completed_count ~= constants.trial_count || ...
        scan.tmp_count ~= 0 || scan.unexpected_count ~= 0
    error('stage8_k2_mc_merge:CheckpointCount', ...
        'Final merge requires 1680 valid checkpoints and zero temporary files.');
end
snr_blocks = cell(constants.trial_count, 1);
method_blocks = cell(constants.trial_count, 1);
for index = 1:constants.trial_count
    snr_blocks{index} = scan.checkpoints{index}.snr_row;
    method_blocks{index} = scan.checkpoints{index}.method_rows;
end
snr_rows = sortrows(vertcat(snr_blocks{:}), 'global_trial_index');
method_rows = sortrows(vertcat(method_blocks{:}), ...
    {'global_trial_index','method_id'});
if height(snr_rows) ~= constants.trial_count || ...
        height(method_rows) ~= constants.method_row_count || ...
        numel(unique(snr_rows.element_trial_hash)) ~= ...
        constants.trial_count || ...
        numel(unique(method_rows.trial_id + "|" + ...
        method_rows.method_id)) ~= constants.method_row_count || ...
        any(method_rows.truth_used_in_fit_flag) || ...
        any(abs(snr_rows.white_beam_snr_expected_db - ...
        snr_rows.white_beamspace_snr_target_db) > ...
        constants.snr_db_tolerance) || ...
        any(snr_rows.raw_covariance_residual > ...
        constants.raw_covariance_tolerance) || ...
        any(snr_rows.whitening_residual > constants.whitening_tolerance)
    error('stage8_k2_mc_merge:Integrity', ...
        'Merged row counts, hashes, SNR, truth, or covariance are invalid.');
end
merged_dir = fullfile(runtime_root, 'merged');
writetable(registry, fullfile(merged_dir, 'registry.csv'));
writetable(snr_rows, fullfile(merged_dir, 'snr_trials.csv'));
writetable(method_rows, fullfile(merged_dir, 'method_results.csv'));
merged = struct('registry', registry, 'snr_rows', snr_rows, ...
    'method_rows', method_rows, 'scan', scan, ...
    'total_active_runtime_sec', sum(scan.runtime_sec), ...
    'median_trial_runtime_sec', median(scan.runtime_sec));
end
