function status = stage8_k2_mc_status_write( ...
    runtime_root, registry, progress, current_spec, constants, stage)
%STAGE8_K2_MC_STATUS_WRITE Atomically publish current progress.

completed = progress.completed_count;
runtime_values = progress.runtime_sec(isfinite(progress.runtime_sec));
if isempty(runtime_values)
    median_trial = NaN;
    elapsed_active = 0;
    eta = NaN;
else
    median_trial = median(runtime_values);
    elapsed_active = sum(runtime_values);
    eta = median_trial * (height(registry) - completed);
end
if isempty(current_spec)
    current = struct('trial_id', "NONE", 'snr_db', NaN, ...
        'profile_id', "NONE", 'noise_profile_id', "NONE", ...
        'L', NaN, 'replicate_id', NaN);
else
    current = struct('trial_id', string(current_spec.trial_id), ...
        'snr_db', double(current_spec.white_beamspace_snr_target_db), ...
        'profile_id', string(current_spec.profile_id), ...
        'noise_profile_id', string(current_spec.noise_profile_id), ...
        'L', double(current_spec.L), ...
        'replicate_id', double(current_spec.replicate_id));
end
status = struct('protocol', constants.protocol, 'stage', char(stage), ...
    'completed', completed, 'total', height(registry), ...
    'remaining', height(registry) - completed, ...
    'current_trial', char(current.trial_id), ...
    'elapsed_active_sec', elapsed_active, ...
    'median_trial_sec', median_trial, 'eta_sec', eta, ...
    'current_snr_db', current.snr_db, ...
    'current_profile', char(current.profile_id), ...
    'current_noise', char(current.noise_profile_id), ...
    'current_L', current.L, 'current_replicate', current.replicate_id, ...
    'core_lite_fallback_count', progress.fallback_counts(1), ...
    'core_plus_fallback_count', progress.fallback_counts(2), ...
    'tangent_fallback_count', progress.fallback_counts(3), ...
    'last_update_utc', stage8_k2_mc_utc_now());
encoded = jsonencode(status, 'PrettyPrint', true);
stage8_k2_mc_write_text_atomic(fullfile(runtime_root, 'status', ...
    'latest_status.json'), [encoded, newline]);
text_now = sprintf([ ...
    'Stage: %s\nCompleted: %d / %d\nRemaining: %d\n', ...
    'Current trial: %s\nElapsed active sec: %.6f\n', ...
    'Median trial sec: %.6f\nETA sec: %.6f\n', ...
    'Current SNR/profile/noise/L/replicate: %g / %s / %s / %g / %g\n', ...
    'Fallback Core-Lite/Core-Plus/Tangent: %d / %d / %d\n', ...
    'Last update UTC: %s\n'], ...
    char(stage), completed, height(registry), height(registry) - completed, ...
    char(current.trial_id), elapsed_active, median_trial, eta, ...
    current.snr_db, char(current.profile_id), char(current.noise_profile_id), ...
    current.L, current.replicate_id, progress.fallback_counts(1), ...
    progress.fallback_counts(2), progress.fallback_counts(3), ...
    status.last_update_utc);
stage8_k2_mc_write_text_atomic(fullfile(runtime_root, 'status', ...
    'latest_status.txt'), text_now);
end
