function audit = stage8_k2_mc_checkpoint_validate( ...
    path_now, expected_spec, context, registry_hash)
%STAGE8_K2_MC_CHECKPOINT_VALIDATE Validate one final or temporary file.

required = {'protocol','checkpoint_contract_version','registry_row', ...
    'element_trial_hash','snr_row','method_rows','scientific_hash', ...
    'code_identity','registry_hash','completed_utc','runtime_sec', ...
    'completion_status'};
if ~isfile(path_now)
    error('stage8_k2_mc_checkpoint_validate:Missing', ...
        'Checkpoint is missing: %s', path_now);
end
loaded = load(path_now, 'checkpoint', '-mat');
if ~isfield(loaded, 'checkpoint') || ~isstruct(loaded.checkpoint) || ...
        ~isscalar(loaded.checkpoint) || ...
        ~all(isfield(loaded.checkpoint, required))
    error('stage8_k2_mc_checkpoint_validate:Schema', ...
        'Checkpoint schema is invalid: %s', path_now);
end
checkpoint = loaded.checkpoint;
constants = context.constants;
if ~strcmp(checkpoint.protocol, constants.protocol) || ...
        ~strcmp(checkpoint.checkpoint_contract_version, ...
        constants.checkpoint_contract_version) || ...
        ~strcmp(checkpoint.completion_status, 'COMPLETE') || ...
        ~strcmp(checkpoint.code_identity, ...
        context.code_identity.tree_hash) || ...
        ~strcmp(checkpoint.registry_hash, registry_hash)
    error('stage8_k2_mc_checkpoint_validate:Identity', ...
        'Checkpoint protocol, code, registry, or status is invalid.');
end
if ~(istable(checkpoint.registry_row) && ...
        height(checkpoint.registry_row) == 1) || ...
        ~strcmp(stage8_k2_mc_stable_hash( ...
        'REGISTRY_ROW', checkpoint.registry_row), ...
        stage8_k2_mc_stable_hash('REGISTRY_ROW', expected_spec))
    error('stage8_k2_mc_checkpoint_validate:RegistryRow', ...
        'Checkpoint registry row differs from the frozen registry.');
end
snr_row = checkpoint.snr_row;
methods = checkpoint.method_rows;
if ~(istable(snr_row) && height(snr_row) == 1 && ...
        istable(methods) && height(methods) == 3) || ...
        snr_row.trial_id ~= expected_spec.trial_id || ...
        any(methods.trial_id ~= expected_spec.trial_id) || ...
        ~isequal(sort(methods.method_id), sort(constants.method_ids)) || ...
        string(checkpoint.element_trial_hash) ~= ...
        expected_spec.element_trial_hash || ...
        snr_row.element_trial_hash ~= expected_spec.element_trial_hash
    error('stage8_k2_mc_checkpoint_validate:Rows', ...
        'Checkpoint result rows do not match the registered trial.');
end
target_error = abs(snr_row.white_beam_snr_expected_db - ...
    snr_row.white_beamspace_snr_target_db);
if target_error > constants.snr_db_tolerance || ...
        any(methods.truth_used_in_fit_flag) || ...
        any(methods.fit_status == "NOT_RUN")
    error('stage8_k2_mc_checkpoint_validate:Integrity', ...
        'Checkpoint SNR, outcome, or truth-isolation integrity failed.');
end
valid = methods.fit_valid;
if any(valid & (~isfinite(methods.RSS) | ~isfinite(methods.loglik) | ...
        ~isfinite(methods.joint_RMSE_deg)))
    error('stage8_k2_mc_checkpoint_validate:Finite', ...
        'A valid method row contains nonfinite registered outputs.');
end
actual_hash = stage8_k2_mc_checkpoint_hash(checkpoint);
if ~strcmp(actual_hash, checkpoint.scientific_hash)
    error('stage8_k2_mc_checkpoint_validate:ScientificHash', ...
        'Checkpoint scientific hash is invalid.');
end
audit = struct('pass', true, 'path', string(path_now), ...
    'trial_id', string(expected_spec.trial_id), ...
    'scientific_hash', string(actual_hash), ...
    'runtime_sec', double(checkpoint.runtime_sec), ...
    'target_error_db', double(target_error));
end
