function registry = stage8_k2_mc_build_registry(context)
%STAGE8_K2_MC_BUILD_REGISTRY Build and scientifically bind 1680 trials.

constants = context.constants;
profiles = context.tp_context.constants.profiles;
rows = cell(constants.trial_count, 1);
trial_index = 0;
for noise_index = 1:numel(constants.noise_profile_ids)
    noise_id = constants.noise_profile_ids(noise_index);
    for L_index = 1:numel(constants.snapshot_counts)
        L = constants.snapshot_counts(L_index);
        for profile_index = 1:numel(profiles)
            profile = profiles(profile_index);
            correlation = profile.correlation_magnitude;
            correlation_contract = "SPECIFIED_CORRELATION";
            if L == 1
                correlation = 1;
                correlation_contract = "L1_FULLY_COHERENT_BY_CONTRACT";
            end
            for replicate_id = 1:constants.replicate_count
                base_index = ((((noise_index - 1) * 3 + ...
                    (L_index - 1)) * 4 + (profile_index - 1)) * 10 + ...
                    (replicate_id - 1));
                source_seed = constants.source_seed_base + base_index;
                noise_seed = constants.noise_seed_base + base_index;
                base_id = string(sprintf('MC1_BASE_N%d_L%d_%s_R%02d', ...
                    noise_index, L, profile.profile_id, replicate_id));
                for snr_index = 1:numel(constants.white_snr_targets_db)
                    target = constants.white_snr_targets_db(snr_index);
                    trial_index = trial_index + 1;
                    trial_id = string(sprintf( ...
                        'MC1_K2_N%d_L%d_S%s_%s_R%02d', noise_index, L, ...
                        signed_token_local(target), profile.profile_id, ...
                        replicate_id));
                    rows{trial_index} = struct( ...
                        'global_trial_index', double(trial_index), ...
                        'trial_id', trial_id, 'K', 2, ...
                        'noise_profile_id', noise_id, ...
                        'noise_index', double(noise_index), ...
                        'L', double(L), 'L_index', double(L_index), ...
                        'profile_id', string(profile.profile_id), ...
                        'profile_index', double(profile_index), ...
                        'center_az_deg', profile.center_deg(1), ...
                        'center_el_deg', profile.center_deg(2), ...
                        'separation_deg', profile.separation_deg, ...
                        'direction_deg', profile.direction_deg, ...
                        'secondary_power_db', profile.secondary_power_db, ...
                        'correlation_magnitude', double(correlation), ...
                        'source_correlation_contract', correlation_contract, ...
                        'white_beamspace_snr_target_db', double(target), ...
                        'snr_db', double(target), ...
                        'snr_index', double(snr_index), ...
                        'replicate_id', double(replicate_id), ...
                        'base_realization_index', double(base_index), ...
                        'base_realization_id', base_id, ...
                        'paired_original_trial_id', base_id, ...
                        'source_seed', double(source_seed), ...
                        'noise_seed', double(noise_seed), ...
                        'snr_control_domain', string(constants.control_domain), ...
                        'protocol_id', string(constants.protocol), ...
                        'cpi_id', "ONE_SYNTHETIC_CPI", ...
                        'range_doppler_cell_id', ...
                        "ONE_SELECTED_RANGE_DOPPLER_CELL", ...
                        'single_cpi_flag', true, ...
                        'same_range_doppler_cell_flag', true, ...
                        'cross_cpi_data_used_flag', false, ...
                        'tracking_input_used_flag', false, ...
                        'K_estimated_inside_module_flag', false);
                end
            end
        end
    end
end
registry = struct2table(vertcat(rows{:}));
registry.measurement_hash = strings(height(registry), 1);
registry.element_trial_hash = strings(height(registry), 1);
registry.resulting_element_snr_expected_db = nan(height(registry), 1);
registry.resulting_raw_beamspace_snr_expected_db = nan(height(registry), 1);
registry.resulting_white_beamspace_snr_expected_db = nan(height(registry), 1);
for index = 1:height(registry)
    [trial, metrics] = stage8_k2_mc_generate_trial( ...
        registry(index, :), context);
    registry.measurement_hash(index) = trial.measurement_hash;
    registry.element_trial_hash(index) = trial.element_trial_hash;
    registry.resulting_element_snr_expected_db(index) = ...
        metrics.element_snr_expected_db;
    registry.resulting_raw_beamspace_snr_expected_db(index) = ...
        metrics.raw_beam_snr_expected_db;
    registry.resulting_white_beamspace_snr_expected_db(index) = ...
        metrics.white_beam_snr_expected_db;
    if mod(index, 240) == 0
        fprintf('Registry scientific identity %d/%d complete.\n', ...
            index, constants.trial_count);
    end
end
validate_registry_local(registry, context);
end

function validate_registry_local(registry, context)
constants = context.constants;
if height(registry) ~= constants.trial_count || ...
        numel(unique(registry.trial_id)) ~= constants.trial_count || ...
        numel(unique(registry.element_trial_hash)) ~= ...
        constants.trial_count || ...
        numel(unique(registry.base_realization_index)) ~= ...
        constants.base_realization_count || ...
        numel(unique(registry.source_seed)) ~= ...
        constants.base_realization_count || ...
        numel(unique(registry.noise_seed)) ~= ...
        constants.base_realization_count || ...
        any(abs(registry.resulting_white_beamspace_snr_expected_db - ...
        registry.white_beamspace_snr_target_db) > ...
        constants.snr_db_tolerance)
    error('stage8_k2_mc_build_registry:Cardinality', ...
        'Registry cardinality, hashes, seeds, or target SNR is invalid.');
end
for base_index = 0:(constants.base_realization_count - 1)
    subset = registry(registry.base_realization_index == base_index, :);
    if height(subset) ~= numel(constants.white_snr_targets_db) || ...
            numel(unique(subset.source_seed)) ~= 1 || ...
            numel(unique(subset.noise_seed)) ~= 1 || ...
            ~isequal(sort(subset.white_beamspace_snr_target_db).', ...
            sort(constants.white_snr_targets_db))
        error('stage8_k2_mc_build_registry:CommonRandomNumbers', ...
            'A base realization does not contain seven paired SNR trials.');
    end
end
if any(registry.L == 1 & (registry.correlation_magnitude ~= 1 | ...
        registry.source_correlation_contract ~= ...
        "L1_FULLY_COHERENT_BY_CONTRACT")) || ...
        any(registry.protocol_id ~= string(constants.protocol)) || ...
        any(registry.snr_control_domain ~= string(constants.control_domain))
    error('stage8_k2_mc_build_registry:Contract', ...
        'Registry source or protocol contract is invalid.');
end
end

function token = signed_token_local(value)
if value < 0
    token = sprintf('M%d', abs(value));
else
    token = sprintf('P%d', value);
end
end
