function context = stage8_k2_mc_build_context(repo_dir)
%STAGE8_K2_MC_BUILD_CONTEXT Load frozen models and evidence identity.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_mc_build_context:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
constants = stage8_k2_mc_constants();
snr_context = stage8_k2_snr_build_context(repo_dir);
if ~isequal(snr_context.tp_context.constants.noise_profile_ids, ...
        constants.noise_profile_ids) || ...
        ~isequal(snr_context.tp_context.constants.snapshot_counts, ...
        constants.snapshot_counts) || ...
        ~isequal(string({snr_context.tp_context.constants.profiles.profile_id}).', ...
        constants.profile_ids)
    error('stage8_k2_mc_build_context:FrozenFactors', ...
        'Frozen noise, L, or P1-P4 factors changed.');
end

manifest_path = fullfile(repo_dir, 'innovation-mining', ...
    '42_stage8_k2_snr_runtime_manifest.json');
if ~isfile(manifest_path)
    error('stage8_k2_mc_build_context:Evidence42', ...
        'The completed 42 runtime manifest is missing.');
end
manifest = jsondecode(fileread(manifest_path));
if ~strcmp(manifest.status, ...
        'STAGE8_K2_SNR_DOMAIN_VALIDATION_COMPLETE') || ...
        manifest.original_hash_match_count ~= 72 || ...
        manifest.white_registry_count ~= 72 || ...
        manifest.method_row_count ~= 216 || ...
        manifest.truth_leakage_count ~= 0
    error('stage8_k2_mc_build_context:Evidence42Status', ...
        'The 42 evidence is not a completed valid SNR-domain bundle.');
end
artifact_hashes = strings(numel(manifest.artifacts), 1);
for index = 1:numel(manifest.artifacts)
    artifact = manifest.artifacts(index);
    path_now = fullfile(repo_dir, strrep(artifact.path, '/', filesep));
    actual = stage8_k2_mc_file_sha256(path_now);
    if ~strcmpi(actual, artifact.sha256)
        error('stage8_k2_mc_build_context:Evidence42Hash', ...
            'Evidence 42 SHA-256 mismatch: %s', artifact.path);
    end
    artifact_hashes(index) = string(lower(actual));
end
manifest_hash = stage8_k2_mc_file_sha256(manifest_path);
code_identity = stage8_k2_mc_code_identity(repo_dir);
context = struct('repo_dir', repo_dir, 'constants', constants, ...
    'snr_context', snr_context, 'tp_context', snr_context.tp_context, ...
    'plan', snr_context.plan, ...
    'primary_measurement_config_id', ...
    constants.primary_measurement_config_id, ...
    'evidence42_manifest', manifest, ...
    'evidence42_manifest_path', manifest_path, ...
    'evidence42_manifest_sha256', string(manifest_hash), ...
    'evidence42_artifact_sha256', artifact_hashes, ...
    'code_identity', code_identity);
context.evidence42_identity = stage8_k2_mc_stable_hash( ...
    'EVIDENCE_42', manifest_hash, artifact_hashes);
context.context_hash = stage8_k2_mc_stable_hash(constants.protocol, ...
    snr_context.context_hash, context.evidence42_identity, ...
    code_identity.tree_hash);
end
