function table_out = test_fim_source_common_scale_invariance(context)
%TEST_FIM_SOURCE_COMMON_SCALE_INVARIANCE Verify common source scaling.

scenario = context.scenarios(context.design_indices(3));
manifold = build_stage7_element_manifold( ...
    scenario.target_angles_deg, context.plan.pool, context.cfg);
noise = context.noise_models{scenario.noise_index};
G_element = apply_stage7_element_whitener(manifold.A, noise, context.cfg);
dG_element = struct( ...
    'azimuth', apply_stage7_element_whitener( ...
        manifold.dA_az, noise, context.cfg), ...
    'elevation', apply_stage7_element_whitener( ...
        manifold.dA_el, noise, context.cfg));

channels = [7,8,9,12,13,14,17,18,19];
model = build_exact_subset_model(context.plan.pool, channels, noise, struct());
G_subset = model.T_I * scenario.raw_G0(channels, :);
dG_subset = struct( ...
    'azimuth', model.T_I * scenario.raw_dG0_az(channels, :), ...
    'elevation', model.T_I * scenario.raw_dG0_el(channels, :));

beta = 1.7 * exp(1j * 0.37);
element_original = effective_deterministic_fim( ...
    G_element, dG_element, scenario.S, 1, struct());
subset_original = effective_deterministic_fim( ...
    G_subset, dG_subset, scenario.S, 1, struct());
element_scaled = effective_deterministic_fim( ...
    G_element, dG_element, beta * scenario.S, 1, struct());
subset_scaled = effective_deterministic_fim( ...
    G_subset, dG_subset, beta * scenario.S, 1, struct());

scale = abs(beta) ^ 2;
element_error = norm(element_scaled.F - scale * element_original.F, 'fro') / ...
    norm(scale * element_original.F, 'fro');
subset_error = norm(subset_scaled.F - scale * subset_original.F, 'fro') / ...
    norm(scale * subset_original.F, 'fro');
eta_original = relative_fim_retention( ...
    element_original.F, subset_original.F, struct('expected_rank', 4));
eta_scaled = relative_fim_retention( ...
    element_scaled.F, subset_scaled.F, struct('expected_rank', 4));
eta_error = abs(eta_scaled.eta - eta_original.eta);

metric = [element_error;subset_error;eta_error];
tolerance = [1e-12;1e-12;1e-12];
table_out = stage7_test_table( ...
    ["ELEMENT_FIM_SCALE";"SUBSET_FIM_SCALE";"ETA_INVARIANCE"], ...
    metric, tolerance, metric <= tolerance);
end
