function table_out = test_stage7_clean_tree_guard(repo_dir)
%TEST_STAGE7_CLEAN_TREE_GUARD Verify classification and enforced failure.

case_id = ["EMPTY_CHAR";"EMPTY_STRING";"MODIFIED";"UNTRACKED"; ...
    "MULTILINE";"DIRTY_STATUS";"DIRTY_GUARD"];
actual = [is_stage7_git_status_clean(''); ...
    is_stage7_git_status_clean(""); ...
    is_stage7_git_status_clean(' M tracked.m'); ...
    is_stage7_git_status_clean('?? untracked.m'); ...
    is_stage7_git_status_clean(sprintf(' M a.m\n?? b.m\n'))];
expected = [true;true;false;false;false];

baseline = repmat('a', 1, 40);
head = repmat('b', 1, 40);
origin = repmat('c', 1, 40);
dirty_opts = struct('runtime_head_commit_override', head, ...
    'origin_main_commit_override', origin, ...
    'baseline_ancestor_flag_override', true, ...
    'git_status_porcelain_override', ' M tracked.m', ...
    'enforce_guards', false, 'phase_factor', 1);
dirty = read_stage7_git_provenance(repo_dir, baseline, dirty_opts);
dirty_opts.enforce_guards = true;
guard_failed = false;
try
    read_stage7_git_provenance(repo_dir, baseline, dirty_opts);
catch exception
    guard_failed = strcmp(exception.identifier, ...
        'read_stage7_git_provenance:STAGE7_DIRTY_WORKTREE_AT_START');
end

pass_flag = [actual == expected; ...
    ~dirty.working_tree_clean_flag && ...
    strcmp(dirty.provenance_status, 'STAGE7_DIRTY_WORKTREE_AT_START'); ...
    guard_failed];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_stage7_clean_tree_guard:Failed', ...
    'Stage 7 clean-tree guard failed.');
end
