function table_out = test_fim_center_difference_coordinate_invariance(context)
%TEST_FIM_CENTER_DIFFERENCE_COORDINATE_INVARIANCE Verify congruence retention.

scenario = context.scenarios(context.design_indices(2));
[subset_fim, ~] = stage7_subset_fim_for_scenario( ...
    context, context.design_indices(2), 14, 14);
J = [1,0,-0.5,0;0,1,0,-0.5;1,0,0.5,0;0,1,0,0.5];
original = relative_fim_retention(scenario.F_element, subset_fim.F, ...
    struct('expected_rank', 4));
transformed = relative_fim_retention(J' * scenario.F_element * J, ...
    J' * subset_fim.F * J, struct('expected_rank', 4));
error_value = norm(original.generalized_eigenvalues - ...
    transformed.generalized_eigenvalues) / ...
    max(norm(original.generalized_eigenvalues), realmin);
table_out = stage7_test_table("CENTER_DIFFERENCE", ...
    error_value, 1e-9, error_value <= 1e-9);
end
