function table_out = test_stage7_source_manifest_determinism(repo_dir)
%TEST_STAGE7_SOURCE_MANIFEST_DETERMINISM Verify Git identity behavior.

paths = ["z/file.m";"a/README.md"];
modes = ["100644";"100644"];
blobs = [string(repmat('1', 1, 40));string(repmat('2', 1, 40))];
base = table(paths, modes, blobs, ["LF";"CRLF"], ...
    'VariableNames', {'relative_path','git_mode','git_blob_hash', ...
    'working_tree_form'});
[manifest, base_hash] = hash_stage7_git_blob_manifest( ...
    base, 'TEST_STAGE7_SOURCE_SCOPE_V1');
[~, reorder_hash] = hash_stage7_git_blob_manifest( ...
    base([2,1], :), 'TEST_STAGE7_SOURCE_SCOPE_V1');
checkout = base;
checkout.working_tree_form = ["CRLF";"LF"];
[~, checkout_hash] = hash_stage7_git_blob_manifest( ...
    checkout, 'TEST_STAGE7_SOURCE_SCOPE_V1');
changed = base;
changed.git_blob_hash(1) = string(repmat('3', 1, 40));
[~, changed_hash] = hash_stage7_git_blob_manifest( ...
    changed, 'TEST_STAGE7_SOURCE_SCOPE_V1');

scope = collect_stage7_source_scope(repo_dir, struct());
[source_manifest, source_hash] = build_stage7_git_blob_manifest( ...
    repo_dir, scope.source_paths, scope.source_scope_version, struct());
[dependency_manifest, dependency_hash] = build_stage7_git_blob_manifest( ...
    repo_dir, scope.dependency_paths, scope.dependency_scope_version, struct());
required_dependencies = ["build_receive_cyl_steering_vec.m"; ...
    "build_receive_cyl_steering_with_derivatives.m"; ...
    "build_sequential_beam_matrix.m";"form_elevation_dbf_cube.m"; ...
    "form_azimuth_dbf_cube.m";"build_psd_whitener.m"; ...
    "stable_numeric_rank.m";"beamspace_dml_score_svd.m"; ...
    "build_full_sequential_local_manifold.m"; ...
    "refine_joint_sequential_dml.m";"stage6_evidence_manifest.csv"; ...
    "stage6_provenance_contract.csv"];
actual_names = strings(height(dependency_manifest), 1);
for index = 1:height(dependency_manifest)
    [~, name, extension] = fileparts(dependency_manifest.relative_path(index));
    actual_names(index) = name + extension;
end

case_id = ["SORTED_MANIFEST";"ORDER_INVARIANCE"; ...
    "CHECKOUT_EOL_INVARIANCE";"BLOB_CHANGE_SENSITIVITY"; ...
    "SOURCE_SCOPE_NONEMPTY";"SOURCE_SCOPE_EXCLUDES_RESULTS"; ...
    "DEPENDENCY_SCOPE_REQUIRED";"SOURCE_HASH_SHA256"; ...
    "DEPENDENCY_HASH_SHA256"];
pass_flag = [issorted(manifest.relative_path); ...
    strcmp(base_hash, reorder_hash);strcmp(base_hash, checkout_hash); ...
    ~strcmp(base_hash, changed_hash);height(source_manifest) > 0; ...
    ~any(contains(source_manifest.relative_path, '/results/') | ...
    contains(source_manifest.relative_path, '/figures/')); ...
    all(ismember(required_dependencies, actual_names)); ...
    strlength(string(source_hash)) == 64; ...
    strlength(string(dependency_hash)) == 64];
table_out = table(case_id, pass_flag);
assert(all(pass_flag), 'test_stage7_source_manifest_determinism:Failed', ...
    'Stage 7 source/dependency manifest contract failed.');
end
