function table_out = test_stage7_candidate_pool_mapping(context)
%TEST_STAGE7_CANDIDATE_POOL_MAPPING Verify the 25 canonical global mappings.

pool = context.plan.pool;
expected_channel = (1:25).';
expected_el = repmat((1:5).', 5, 1);
expected_az = repelem((1:5).', 5);
metric = [norm(size(pool.W0) - [2080, 25]); ...
    max(abs(pool.table.sequential_channel_id - expected_channel)); ...
    max(abs(pool.table.global_elevation_beam_id - expected_el)); ...
    max(abs(pool.table.global_azimuth_beam_id - expected_az)); ...
    max(abs(strlength(pool.table.physical_weight_hash) - 64))];
table_out = stage7_test_table( ...
    ["W0_DIMENSION";"CHANNEL_IDS";"ELEVATION_IDS"; ...
    "AZIMUTH_IDS";"WEIGHT_HASH_LENGTH"], metric, zeros(5, 1), metric == 0);
end
