function [reference_rows, reference_hybrid_rows, audit] = ...
    build_stage8_core_v2_live_reference_rows(repo_dir)
%BUILD_STAGE8_CORE_V2_LIVE_REFERENCE_ROWS Rebuild frozen rows in memory.

path_before = path;
path_cleanup = onCleanup(@() path(path_before));
tests_dir = fileparts(mfilename('fullpath'));
step_dir = fileparts(tests_dir);
addpath(fullfile(repo_dir, 'tools', ...
    'stage8_r1_continuous_decisive', 'matlab'));
addpath(fullfile(repo_dir, 'tools', ...
    'stage8_core_v2_known_k', 'matlab'));
addpath(fullfile(step_dir, 'common'));
addpath(tests_dir);

context = stage8_r1_context(repo_dir, true);
registry = stage8_r1_build_registry(context, 'FORMAL');
assert_live_local(height(registry) == 24 && ...
    nnz(registry.truth_K == 1) == 16 && ...
    nnz(registry.truth_K == 2) == 8, 'registry_shape');

row_cells = cell(height(registry), 1);
diagnostic_hash_match_count = 0;
for index = 1:height(registry)
    spec = registry(index, :);
    [rows, diagnostics] = stage8_core_v2_evaluate_trial(spec, context);
    trial_hashes = unique(string(rows.element_trial_hash));
    valid = height(rows) == 3 && numel(trial_hashes) == 1 && ...
        diagnostics.method_row_count == 3 && ...
        string(diagnostics.element_trial_hash) == trial_hashes(1);
    assert_live_local(valid, ...
        sprintf('%s_live_B0_B1_B2_shape', char(spec.trial_id)));
    diagnostic_hash_match_count = diagnostic_hash_match_count + 1;
    row_cells{index} = rows;
end
reference_rows = sortrows(vertcat(row_cells{:}), ...
    {'global_trial_index', 'method_id'});
assert_live_local(height(reference_rows) == 72 && ...
    numel(unique(reference_rows.trial_id)) == 24 && ...
    all_trial_groups_valid_local(reference_rows), ...
    'live_reference_rows');

[reference_hybrid_rows, hybrid_audit] = ...
    stage8_core_v2_build_hybrid_rows(reference_rows);
assert_live_local(height(reference_hybrid_rows) == 48 && ...
    numel(unique(reference_hybrid_rows.trial_id)) == 24 && ...
    hybrid_audit.truth_leakage_count == 0, 'live_hybrid_rows');

source26 = readtable(fullfile(repo_dir, 'innovation-mining', ...
    '26_stage8_core_v2_known_k_pruning_trials.csv'), ...
    'TextType', 'string');
source27 = readtable(fullfile(repo_dir, 'innovation-mining', ...
    '27_stage8_core_v2_1_safe_hybrid_trials.csv'), ...
    'TextType', 'string');
assert_live_local(height(source26) == 72 && ...
    numel(unique(source26.trial_id)) == 24, 'source26_identity_shape');
assert_live_local(height(source27) == 48 && ...
    numel(unique(source27.trial_id)) == 24, 'source27_identity_shape');

source26_identity_match_count = compare_identity_rows_local( ...
    reference_rows, source26, ...
    {'element_trial_hash', 'fit_valid', 'fit_status', 'solver_status', ...
    'selected_start_id'}, 'source26');
source27_identity_match_count = compare_identity_rows_local( ...
    reference_hybrid_rows, source27, ...
    {'element_trial_hash', 'fit_valid', 'fit_status', 'solver_status', ...
    'selected_source', 'selected_start_id', 'continuous_upgrade_flag', ...
    'fallback_flag'}, 'source27');

reference_truth_leakage_count = nnz( ...
    reference_rows.truth_used_in_initialization_flag | ...
    reference_rows.truth_used_in_fit_flag);
hybrid_truth_leakage_count = nnz( ...
    reference_hybrid_rows.truth_used_in_initialization_flag | ...
    reference_hybrid_rows.truth_used_in_fit_flag | ...
    reference_hybrid_rows.selection_truth_used_flag);
assert_live_local(reference_truth_leakage_count == 0 && ...
    hybrid_truth_leakage_count == 0, 'truth_leakage');

audit = struct('pass', true, ...
    'registry_trial_count', height(registry), ...
    'registry_k1_trial_count', nnz(registry.truth_K == 1), ...
    'registry_k2_trial_count', nnz(registry.truth_K == 2), ...
    'reference_row_count', height(reference_rows), ...
    'reference_hybrid_row_count', height(reference_hybrid_rows), ...
    'diagnostic_hash_match_count', diagnostic_hash_match_count, ...
    'source26_identity_match_count', source26_identity_match_count, ...
    'source27_identity_match_count', source27_identity_match_count, ...
    'reference_truth_leakage_count', reference_truth_leakage_count, ...
    'hybrid_truth_leakage_count', hybrid_truth_leakage_count, ...
    'csv_numeric_fields_used_as_bit_oracle', false, ...
    'live_reference_used', true, ...
    'live_reference_serialization_roundtrip_count', 0, ...
    'hybrid_audit', hybrid_audit);
clear path_cleanup
end

function valid = all_trial_groups_valid_local(rows)
ids = unique(string(rows.trial_id));
valid = true;
for index = 1:numel(ids)
    trial = rows(rows.trial_id == ids(index), :);
    valid = valid && height(trial) == 3 && ...
        numel(unique(trial.method_id)) == 3 && ...
        numel(unique(trial.element_trial_hash)) == 1;
end
end

function match_count = compare_identity_rows_local( ...
    live_rows, historical_rows, fields, label)
match_count = 0;
for index = 1:height(live_rows)
    live = live_rows(index, :);
    historical = historical_rows( ...
        historical_rows.trial_id == live.trial_id & ...
        historical_rows.method_id == live.method_id, :);
    assert_live_local(height(historical) == 1, sprintf( ...
        '%s_%s_%s_pairing', label, char(live.trial_id), ...
        char(live.method_id)));
    for field_index = 1:numel(fields)
        field = fields{field_index};
        if ismember(field, {'fit_valid', 'continuous_upgrade_flag', ...
                'fallback_flag'})
            same = logical(live.(field)) == logical(historical.(field));
        else
            same = string(live.(field)) == string(historical.(field));
        end
        assert_live_local(same, sprintf('%s_%s_%s_%s', label, ...
            char(live.trial_id), char(live.method_id), field));
    end
    match_count = match_count + 1;
end
end

function assert_live_local(condition, field)
if ~condition
    error('build_stage8_core_v2_live_reference_rows:Contract', ...
        'LIVE_REFERENCE_FAIL_STOPPED: %s.', field);
end
end
