function audit = test_f1_canonical_oracle_contract(repo_dir)
%TEST_F1_CANONICAL_ORACLE_CONTRACT Validate the corrected historical map.

canonical_k1 = "H1_DIRECT_SAFE_HYBRID_KNOWN_K";
noncanonical_k1 = "H2_GROUPED_SAFE_HYBRID_KNOWN_K";
canonical_k2_lite = "B0_FIXED_GRID_KNOWN_K";
canonical_k2_plus = "H2_GROUPED_SAFE_HYBRID_KNOWN_K";
known_difference_trial = "R1_K1_N2_L1_SP6_INSIDE_OFF_GRID";

source26 = readtable(fullfile(repo_dir, 'innovation-mining', ...
    '26_stage8_core_v2_known_k_pruning_trials.csv'), 'TextType', 'string');
source27 = readtable(fullfile(repo_dir, 'innovation-mining', ...
    '27_stage8_core_v2_1_safe_hybrid_trials.csv'), 'TextType', 'string');
h1_k1 = source27(source27.truth_K == 1 & ...
    source27.method_id == canonical_k1, :);
h2_k1 = source27(source27.truth_K == 1 & ...
    source27.method_id == noncanonical_k1, :);
b0_k2 = source26(source26.truth_K == 2 & ...
    source26.method_id == canonical_k2_lite, :);
h2_k2 = source27(source27.truth_K == 2 & ...
    source27.method_id == canonical_k2_plus, :);

assert_contract_local(height(h1_k1) == 16 && height(h2_k1) == 16, ...
    'Historical K1 H1/H2 rows must be exactly 16 plus 16.');
assert_contract_local(height(b0_k2) == 8 && height(h2_k2) == 8, ...
    'Historical K2 B0/H2 rows must be exactly 8 plus 8.');
assert_contract_local(all(h1_k1.method_id == canonical_k1) && ...
    all(h2_k1.method_id == noncanonical_k1) && ...
    all(b0_k2.method_id == canonical_k2_lite) && ...
    all(h2_k2.method_id == canonical_k2_plus), ...
    'Canonical method IDs are not unique.');
validate_pairing_local(h1_k1, h2_k1, 1, 'K1 H1/H2');
validate_pairing_local(b0_k2, h2_k2, 2, 'K2 B0/H2');
all_ids = unique([string(h1_k1.trial_id); string(b0_k2.trial_id)]);
assert_contract_local(numel(all_ids) == 24, ...
    'The canonical map must cover exactly 24 unique trial IDs.');

comparison_fields = {'final_angles','RSS','loglik','fit_valid', ...
    'fit_status','solver_status','selected_source','selected_start_id', ...
    'continuous_upgrade_flag','fallback_flag','element_trial_hash'};
scientific_fields = ["final_angles", "RSS", "loglik"];
difference_trials = strings(0, 1);
difference_fields = strings(0, 1);
difference_records = strings(0, 1);
scientific_difference_trials = strings(0, 1);
ids = sort(string(h1_k1.trial_id));
for index = 1:numel(ids)
    left = h1_k1(h1_k1.trial_id == ids(index), :);
    right = h2_k1(h2_k1.trial_id == ids(index), :);
    for field_index = 1:numel(comparison_fields)
        field = comparison_fields{field_index};
        if ~field_equal_local(left, right, field)
            difference_trials(end + 1, 1) = ids(index); %#ok<AGROW>
            difference_fields(end + 1, 1) = string(field); %#ok<AGROW>
            difference_records(end + 1, 1) = ...
                ids(index) + ":" + string(field); %#ok<AGROW>
            if ismember(string(field), scientific_fields)
                scientific_difference_trials(end + 1, 1) = ...
                    ids(index); %#ok<AGROW>
            end
        end
    end
end
difference_trials = unique(difference_trials, 'stable');
difference_fields = unique(difference_fields, 'stable');
scientific_difference_trials = unique(scientific_difference_trials, 'stable');
assert_contract_local(ismember(known_difference_trial, ...
    scientific_difference_trials), ...
    'The known noncanonical H2 K1 scientific difference was not recorded.');

audit = struct('pass', true, ...
    'status', 'F1A_CANONICAL_ORACLE_CONTRACT_PASS', ...
    'canonical_k1_method_id', char(canonical_k1), ...
    'noncanonical_k1_method_id', char(noncanonical_k1), ...
    'noncanonical_k1_classification', ...
    'NONCANONICAL_GROUPED_K1_DEVELOPMENT_ROUTE', ...
    'canonical_k2_core_lite_method_id', char(canonical_k2_lite), ...
    'canonical_k2_core_plus_method_id', char(canonical_k2_plus), ...
    'historical_k1_trial_count', height(h1_k1), ...
    'historical_k2_trial_count', height(b0_k2), ...
    'historical_unique_trial_count', numel(all_ids), ...
    'h1_h2_k1_difference_count', numel(difference_trials), ...
    'h1_h2_k1_scientific_difference_count', ...
    numel(scientific_difference_trials), ...
    'h1_h2_k1_difference_fields', difference_fields, ...
    'h1_h2_k1_difference_trials', difference_trials, ...
    'h1_h2_k1_difference_records', difference_records, ...
    'known_noncanonical_difference_trial', char(known_difference_trial), ...
    'known_noncanonical_difference_recorded', true);
end

function validate_pairing_local(left, right, expected_k, label)
left_ids = sort(string(left.trial_id));
right_ids = sort(string(right.trial_id));
assert_contract_local(isequal(left_ids, right_ids) && ...
    numel(unique(left_ids)) == numel(left_ids), ...
    sprintf('%s pairing is incomplete.', label));
for index = 1:numel(left_ids)
    left_row = left(left.trial_id == left_ids(index), :);
    right_row = right(right.trial_id == left_ids(index), :);
    same = height(left_row) == 1 && height(right_row) == 1 && ...
        left_row.truth_K == expected_k && right_row.truth_K == expected_k && ...
        left_row.element_trial_hash == right_row.element_trial_hash;
    assert_contract_local(same, ...
        sprintf('%s identity differs for %s.', label, left_ids(index)));
end
end

function same = field_equal_local(left, right, field)
switch field
    case 'final_angles'
        left_value = parse_historical_angle_matrix(left.(field), 1);
        right_value = parse_historical_angle_matrix(right.(field), 1);
        same = isequal(num2hex(left_value), num2hex(right_value));
    case {'RSS','loglik'}
        same = isequal(num2hex(double(left.(field))), ...
            num2hex(double(right.(field))));
    otherwise
        same = isequaln(left.(field), right.(field));
end
end

function assert_contract_local(condition, message)
if ~condition
    error('test_f1_canonical_oracle_contract:Contract', ...
        'F1A_FAIL_STOPPED: %s', message);
end
end
