function audit = test_f0_process_snapshot_no_self_match()
%TEST_F0_PROCESS_SNAPSHOT_NO_SELF_MATCH Audit one real process snapshot.

snapshot = stage8_core_v2_2_process_snapshot();
current_pid = double(feature('getpid'));
assert(height(snapshot) > 0);
assert(any(snapshot.process_id == current_pid));
classified = stage8_core_v2_2_classify_process_snapshot( ...
    snapshot, current_pid);
assert(any(classified.current_lineage_ids == current_pid));
shell_names = ["powershell.exe", "powershell", "pwsh.exe", "pwsh", ...
    "cmd.exe", "cmd"];
query_mask = ismember(lower(strtrim(snapshot.name)), shell_names) & ...
    contains(lower(snapshot.command_line), ...
    lower("Get-CimInstance Win32_Process"));
query_process_ids = snapshot.process_id(query_mask);
assert(~isempty(query_process_ids));
assert(~any(ismember(query_process_ids, ...
    classified.legacy_orchestrator_matches.process_id)));

eligible = classified.external_matlab_count == 0 && ...
    classified.mwpython_count == 0 && ...
    classified.legacy_orchestrator_count == 0;
if ~eligible
    audit = struct('pass', false, ...
        'status', 'SKIP_ENVIRONMENT_NOT_ELIGIBLE', ...
        'snapshot_row_count', height(snapshot), ...
        'query_process_count', nnz(query_mask), ...
        'current_lineage_ids', classified.current_lineage_ids, ...
        'external_matlab_matches', classified.external_matlab_matches, ...
        'mwpython_matches', classified.mwpython_matches, ...
        'legacy_orchestrator_matches', ...
        classified.legacy_orchestrator_matches);
    return;
end
audit = struct('pass', true, ...
    'status', 'F0_PROCESS_SNAPSHOT_NO_SELF_MATCH_PASS', ...
    'snapshot_row_count', height(snapshot), ...
    'query_process_count', nnz(query_mask), ...
    'current_lineage_ids', classified.current_lineage_ids, ...
    'external_matlab_count', classified.external_matlab_count, ...
    'mwpython_count', classified.mwpython_count, ...
    'legacy_orchestrator_count', classified.legacy_orchestrator_count);
end
