function audit = test_historical_24_trial_regression(repo_dir)
%TEST_HISTORICAL_24_TRIAL_REGRESSION Run the public production interface.

path_before = path;
path_cleanup = onCleanup(@() path(path_before));
tool_dir = fullfile(repo_dir, 'tools', ...
    'stage8_r1_continuous_decisive', 'matlab');
addpath(tool_dir);
context = stage8_r1_context(repo_dir, true);
registry = stage8_r1_build_registry(context, 'FORMAL');
assert_f1b_local(height(registry) == 24 && ...
    nnz(registry.truth_K == 1) == 16 && ...
    nnz(registry.truth_K == 2) == 8, '', 'registry_shape');

source26 = readtable(fullfile(repo_dir, 'innovation-mining', ...
    '26_stage8_core_v2_known_k_pruning_trials.csv'), 'TextType', 'string');
source27 = readtable(fullfile(repo_dir, 'innovation-mining', ...
    '27_stage8_core_v2_1_safe_hybrid_trials.csv'), 'TextType', 'string');
h1_k1 = source27(source27.truth_K == 1 & ...
    source27.method_id == "H1_DIRECT_SAFE_HYBRID_KNOWN_K", :);
b0_k2 = source26(source26.truth_K == 2 & ...
    source26.method_id == "B0_FIXED_GRID_KNOWN_K", :);
h2_k2 = source27(source27.truth_K == 2 & ...
    source27.method_id == "H2_GROUPED_SAFE_HYBRID_KNOWN_K", :);
assert_f1b_local(height(h1_k1) == 16 && height(b0_k2) == 8 && ...
    height(h2_k2) == 8, '', 'historical_shape');

element_hash_match_count = 0;
k1_mode_identity_match_count = 0;
k1_h1_canonical_match_count = 0;
k2_core_lite_b0_match_count = 0;
k2_core_plus_h2_match_count = 0;
truth_leakage_count = 0;
tracking_input_count = 0;
cross_cpi_input_count = 0;
k_estimated_inside_count = 0;
for index = 1:height(registry)
    spec = registry(index, :);
    trial_id = char(spec.trial_id);
    trial = stage8_r1_generate_trial(spec, context);
    historical_hash = historical_hash_local( ...
        source26, source27, spec.trial_id);
    assert_f1b_local(string(trial.element_trial_hash) == historical_hash, ...
        trial_id, 'element_trial_hash');
    element_hash_match_count = element_hash_match_count + 1;

    lite = estimate_stage8_known_k_local_cell( ...
        trial.Y_element, trial.model, context.plan.local_domain, ...
        context.stage5_locked, trial.model.noise_factorization, ...
        spec.truth_K, struct('mode', 'CORE_LITE'));
    plus = estimate_stage8_known_k_local_cell( ...
        trial.Y_element, trial.model, context.plan.local_domain, ...
        context.stage5_locked, trial.model.noise_factorization, ...
        spec.truth_K, struct('mode', 'CORE_PLUS'));
    [truth_leakage_count, tracking_input_count, ...
        cross_cpi_input_count, k_estimated_inside_count] = ...
        add_boundary_counts_local(lite, truth_leakage_count, ...
        tracking_input_count, cross_cpi_input_count, ...
        k_estimated_inside_count);
    [truth_leakage_count, tracking_input_count, ...
        cross_cpi_input_count, k_estimated_inside_count] = ...
        add_boundary_counts_local(plus, truth_leakage_count, ...
        tracking_input_count, cross_cpi_input_count, ...
        k_estimated_inside_count);

    if spec.truth_K == 1
        compare_results_local(lite, plus, trial_id, 'K1_mode_identity');
        k1_mode_identity_match_count = ...
            k1_mode_identity_match_count + 1;
        historical = one_row_local(h1_k1, spec.trial_id, ...
            'K1_H1_canonical');
        compare_historical_local(lite, historical, trial, ...
            'K1_CORE_LITE_H1');
        compare_historical_local(plus, historical, trial, ...
            'K1_CORE_PLUS_H1');
        k1_h1_canonical_match_count = ...
            k1_h1_canonical_match_count + 1;
    else
        historical = one_row_local(b0_k2, spec.trial_id, 'K2_B0');
        assert_f1b_local(strcmp(lite.selected_source, ...
            'FIXED_GRID_CORE_LITE'), trial_id, ...
            'K2_CORE_LITE.selected_source');
        compare_historical_local(lite, historical, trial, ...
            'K2_CORE_LITE_B0');
        k2_core_lite_b0_match_count = ...
            k2_core_lite_b0_match_count + 1;

        historical = one_row_local(h2_k2, spec.trial_id, 'K2_H2');
        compare_historical_local(plus, historical, trial, ...
            'K2_CORE_PLUS_H2');
        assert_f1b_local(logical(plus.diagnostics.continuous_upgrade_flag) ...
            == logical(historical.continuous_upgrade_flag), trial_id, ...
            'K2_CORE_PLUS.continuous_upgrade_flag');
        assert_f1b_local(logical(plus.diagnostics.fallback_flag) ...
            == logical(historical.fallback_flag), trial_id, ...
            'K2_CORE_PLUS.fallback_flag');
        k2_core_plus_h2_match_count = ...
            k2_core_plus_h2_match_count + 1;
    end
end

all_pass = element_hash_match_count == 24 && ...
    k1_mode_identity_match_count == 16 && ...
    k1_h1_canonical_match_count == 16 && ...
    k2_core_lite_b0_match_count == 8 && ...
    k2_core_plus_h2_match_count == 8 && ...
    truth_leakage_count == 0 && tracking_input_count == 0 && ...
    cross_cpi_input_count == 0 && k_estimated_inside_count == 0;
assert_f1b_local(all_pass, '', 'final_counts');
audit = struct('pass', true, ...
    'status', 'F1B_PRODUCTION_24_TRIAL_REGRESSION_PASS', ...
    'element_hash_match_count', element_hash_match_count, ...
    'element_hash_expected_count', 24, ...
    'k1_mode_identity_match_count', k1_mode_identity_match_count, ...
    'k1_mode_identity_expected_count', 16, ...
    'k1_h1_canonical_match_count', k1_h1_canonical_match_count, ...
    'k1_h1_canonical_expected_count', 16, ...
    'k2_core_lite_b0_match_count', k2_core_lite_b0_match_count, ...
    'k2_core_lite_b0_expected_count', 8, ...
    'k2_core_plus_h2_match_count', k2_core_plus_h2_match_count, ...
    'k2_core_plus_h2_expected_count', 8, ...
    'truth_leakage_count', truth_leakage_count, ...
    'tracking_input_count', tracking_input_count, ...
    'cross_cpi_input_count', cross_cpi_input_count, ...
    'k_estimated_inside_module_count', k_estimated_inside_count);
clear path_cleanup
end

function hash = historical_hash_local(source26, source27, trial_id)
rows26 = source26(source26.trial_id == string(trial_id), :);
rows27 = source27(source27.trial_id == string(trial_id), :);
hashes = unique([string(rows26.element_trial_hash); ...
    string(rows27.element_trial_hash)]);
assert_f1b_local(numel(hashes) == 1, char(trial_id), ...
    'historical_element_trial_hash');
hash = hashes(1);
end

function row = one_row_local(rows, trial_id, label)
row = rows(rows.trial_id == string(trial_id), :);
assert_f1b_local(height(row) == 1, char(trial_id), label);
end

function compare_results_local(left, right, trial_id, label)
assert_hex_local(left.angles_hat_deg, right.angles_hat_deg, ...
    trial_id, [label, '.angles']);
assert_hex_local(left.rss, right.rss, trial_id, [label, '.RSS']);
assert_hex_local(left.loglik_concentrated, ...
    right.loglik_concentrated, trial_id, [label, '.loglik']);
assert_f1b_local(left.fit_valid == right.fit_valid, ...
    trial_id, [label, '.fit_valid']);
assert_f1b_local(strcmp(left.fit_status, right.fit_status), ...
    trial_id, [label, '.fit_status']);
assert_f1b_local(strcmp(left.selected_source, right.selected_source), ...
    trial_id, [label, '.selected_source']);
assert_f1b_local(strcmp(left.selected_start_id, right.selected_start_id), ...
    trial_id, [label, '.selected_start_id']);
assert_f1b_local(strcmp(selected_solver_status_local(left), ...
    selected_solver_status_local(right)), trial_id, ...
    [label, '.solver_status']);
end

function compare_historical_local(result, historical, trial, label)
trial_id = char(historical.trial_id);
K = double(historical.truth_K);
angles = parse_historical_angle_matrix(historical.final_angles, K);
assert_hex_local(result.angles_hat_deg, angles, ...
    trial_id, [label, '.angles']);
assert_hex_local(result.rss, double(historical.RSS), ...
    trial_id, [label, '.RSS']);
assert_hex_local(result.loglik_concentrated, double(historical.loglik), ...
    trial_id, [label, '.loglik']);
assert_f1b_local(result.fit_valid == logical(historical.fit_valid), ...
    trial_id, [label, '.fit_valid']);
assert_f1b_local(strcmp(result.fit_status, char(historical.fit_status)), ...
    trial_id, [label, '.fit_status']);
assert_f1b_local(strcmp(selected_solver_status_local(result), ...
    char(historical.solver_status)), trial_id, [label, '.solver_status']);
assert_f1b_local(strcmp(result.selected_start_id, ...
    char(historical.selected_start_id)), trial_id, ...
    [label, '.selected_start_id']);
assert_f1b_local(string(trial.element_trial_hash) == ...
    historical.element_trial_hash, trial_id, ...
    [label, '.element_trial_hash']);
if K == 1 || contains(label, 'CORE_PLUS')
    assert_f1b_local(strcmp(result.selected_source, ...
        char(historical.selected_source)), trial_id, ...
        [label, '.selected_source']);
end
end

function status = selected_solver_status_local(result)
if strcmp(result.selected_source, 'CONTINUOUS_UPGRADE')
    candidate = result.continuous_candidate;
else
    candidate = result.fixed_grid_candidate;
end
status = char(string(candidate.solver_status));
end

function assert_hex_local(actual, expected, trial_id, field)
assert_f1b_local(isequal(num2hex(double(actual)), ...
    num2hex(double(expected))), trial_id, field);
end

function assert_f1b_local(condition, trial_id, field)
if ~condition
    error('test_historical_24_trial_regression:Mismatch', ...
        'F1B_FAIL_STOPPED: exact mismatch at %s:%s.', trial_id, field);
end
end

function [truth_count, tracking_count, cross_cpi_count, k_count] = ...
    add_boundary_counts_local(result, truth_count, tracking_count, ...
    cross_cpi_count, k_count)
truth_count = truth_count + double(result.truth_used_in_fit_flag);
tracking_count = tracking_count + double(result.tracking_input_used_flag);
cross_cpi_count = cross_cpi_count + ...
    double(result.cross_cpi_data_used_flag);
k_count = k_count + double(result.K_estimated_inside_module_flag);
if isfield(result, 'diagnostics') && ~isempty(fieldnames(result.diagnostics))
    diagnostics = result.diagnostics;
    truth_count = truth_count + ...
        double(diagnostics.truth_used_in_initialization_flag) + ...
        double(diagnostics.truth_used_in_fit_flag);
    tracking_count = tracking_count + ...
        double(diagnostics.tracking_input_used_flag);
    cross_cpi_count = cross_cpi_count + ...
        double(diagnostics.cross_cpi_data_used_flag);
    if isfield(diagnostics, 'selection') && ...
            isfield(diagnostics.selection, 'selection_truth_used_flag')
        truth_count = truth_count + ...
            double(diagnostics.selection.selection_truth_used_flag);
    end
end
end
