function audit = test_historical_24_trial_regression(repo_dir)
%TEST_HISTORICAL_24_TRIAL_REGRESSION Run the public production interface.

path_before = path;
path_cleanup = onCleanup(@() path(path_before));
tool_dir = fullfile(repo_dir, 'tools', ...
    'stage8_r1_continuous_decisive', 'matlab');
addpath(tool_dir);
context = stage8_r1_context(repo_dir, true);
registry = stage8_r1_build_registry(context, 'FORMAL');
assert_f1b_local(height(registry) == 24 && ...
    nnz(registry.truth_K == 1) == 16 && ...
    nnz(registry.truth_K == 2) == 8, '', 'registry_shape');

source27 = readtable(fullfile(repo_dir, 'innovation-mining', ...
    '27_stage8_core_v2_1_safe_hybrid_trials.csv'), ...
    'TextType', 'string');
csv_oracle_audit = audit_lossy_csv_oracle_local(source27);
fprintf('CSV_NUMERIC_NOT_REGISTERED_AS_BIT_ORACLE_PASS\n');

[reference_rows, reference_hybrid_rows, reference_audit] = ...
    build_stage8_core_v2_live_reference_rows(repo_dir);
assert_f1b_local(reference_audit.pass && ...
    reference_audit.reference_row_count == 72 && ...
    reference_audit.reference_hybrid_row_count == 48 && ...
    reference_audit.source26_identity_match_count == 72 && ...
    reference_audit.source27_identity_match_count == 48 && ...
    ~reference_audit.csv_numeric_fields_used_as_bit_oracle && ...
    reference_audit.live_reference_used && ...
    reference_audit.live_reference_serialization_roundtrip_count == 0, ...
    '', 'live_reference_audit');

h1_k1 = reference_hybrid_rows( ...
    reference_hybrid_rows.truth_K == 1 & ...
    reference_hybrid_rows.method_id == ...
    "H1_DIRECT_SAFE_HYBRID_KNOWN_K", :);
b0_k2 = reference_rows(reference_rows.truth_K == 2 & ...
    reference_rows.method_id == "B0_FIXED_GRID_KNOWN_K", :);
h2_k2 = reference_hybrid_rows( ...
    reference_hybrid_rows.truth_K == 2 & ...
    reference_hybrid_rows.method_id == ...
    "H2_GROUPED_SAFE_HYBRID_KNOWN_K", :);
assert_f1b_local(height(h1_k1) == 16 && height(b0_k2) == 8 && ...
    height(h2_k2) == 8, '', 'live_reference_shape');

element_hash_match_count = 0;
k1_mode_identity_match_count = 0;
k1_h1_canonical_match_count = 0;
k2_core_lite_b0_match_count = 0;
k2_core_plus_h2_match_count = 0;
truth_leakage_count = 0;
tracking_input_count = 0;
cross_cpi_input_count = 0;
k_estimated_inside_count = 0;
for index = 1:height(registry)
    spec = registry(index, :);
    trial_id = char(spec.trial_id);
    trial = stage8_r1_generate_trial(spec, context);
    live_hash = live_hash_local(reference_rows, spec.trial_id);
    assert_f1b_local(string(trial.element_trial_hash) == live_hash, ...
        trial_id, 'element_trial_hash');
    element_hash_match_count = element_hash_match_count + 1;

    lite = estimate_stage8_known_k_local_cell( ...
        trial.Y_element, trial.model, context.plan.local_domain, ...
        context.stage5_locked, trial.model.noise_factorization, ...
        spec.truth_K, struct('mode', 'CORE_LITE'));
    plus = estimate_stage8_known_k_local_cell( ...
        trial.Y_element, trial.model, context.plan.local_domain, ...
        context.stage5_locked, trial.model.noise_factorization, ...
        spec.truth_K, struct('mode', 'CORE_PLUS'));
    [truth_leakage_count, tracking_input_count, ...
        cross_cpi_input_count, k_estimated_inside_count] = ...
        add_boundary_counts_local(lite, truth_leakage_count, ...
        tracking_input_count, cross_cpi_input_count, ...
        k_estimated_inside_count);
    [truth_leakage_count, tracking_input_count, ...
        cross_cpi_input_count, k_estimated_inside_count] = ...
        add_boundary_counts_local(plus, truth_leakage_count, ...
        tracking_input_count, cross_cpi_input_count, ...
        k_estimated_inside_count);

    if spec.truth_K == 1
        compare_results_local(lite, plus, trial_id, 'K1_mode_identity');
        k1_mode_identity_match_count = ...
            k1_mode_identity_match_count + 1;
        live = one_row_local(h1_k1, spec.trial_id, 'K1_live_H1');
        compare_live_local(lite, live, trial, ...
            'K1_CORE_LITE_H1', true);
        compare_live_local(plus, live, trial, ...
            'K1_CORE_PLUS_H1', true);
        k1_h1_canonical_match_count = ...
            k1_h1_canonical_match_count + 1;
    else
        live = one_row_local(b0_k2, spec.trial_id, 'K2_live_B0');
        assert_f1b_local(strcmp(lite.selected_source, ...
            'FIXED_GRID_CORE_LITE'), trial_id, ...
            'K2_CORE_LITE.selected_source');
        compare_live_local(lite, live, trial, ...
            'K2_CORE_LITE_B0', false);
        k2_core_lite_b0_match_count = ...
            k2_core_lite_b0_match_count + 1;

        live = one_row_local(h2_k2, spec.trial_id, 'K2_live_H2');
        compare_live_local(plus, live, trial, ...
            'K2_CORE_PLUS_H2', true);
        assert_f1b_local( ...
            logical(plus.diagnostics.continuous_upgrade_flag) == ...
            logical(live.continuous_upgrade_flag), trial_id, ...
            'K2_CORE_PLUS.continuous_upgrade_flag');
        assert_f1b_local(logical(plus.diagnostics.fallback_flag) == ...
            logical(live.fallback_flag), trial_id, ...
            'K2_CORE_PLUS.fallback_flag');
        k2_core_plus_h2_match_count = ...
            k2_core_plus_h2_match_count + 1;
    end
end

all_pass = element_hash_match_count == 24 && ...
    k1_mode_identity_match_count == 16 && ...
    k1_h1_canonical_match_count == 16 && ...
    k2_core_lite_b0_match_count == 8 && ...
    k2_core_plus_h2_match_count == 8 && ...
    truth_leakage_count == 0 && tracking_input_count == 0 && ...
    cross_cpi_input_count == 0 && k_estimated_inside_count == 0;
assert_f1b_local(all_pass, '', 'final_counts');
audit = struct('pass', true, ...
    'status', 'F1B_PRODUCTION_24_TRIAL_REGRESSION_PASS', ...
    'live_reference_status', ...
    'F1B_PRODUCTION_24_TRIAL_LIVE_REFERENCE_PASS', ...
    'element_hash_match_count', element_hash_match_count, ...
    'element_hash_expected_count', 24, ...
    'k1_mode_identity_match_count', k1_mode_identity_match_count, ...
    'k1_mode_identity_expected_count', 16, ...
    'k1_h1_canonical_match_count', k1_h1_canonical_match_count, ...
    'k1_h1_canonical_expected_count', 16, ...
    'k1_live_h1_match_count', k1_h1_canonical_match_count, ...
    'k2_core_lite_b0_match_count', k2_core_lite_b0_match_count, ...
    'k2_core_lite_b0_expected_count', 8, ...
    'k2_core_plus_h2_match_count', k2_core_plus_h2_match_count, ...
    'k2_core_plus_h2_expected_count', 8, ...
    'truth_leakage_count', truth_leakage_count, ...
    'tracking_input_count', tracking_input_count, ...
    'cross_cpi_input_count', cross_cpi_input_count, ...
    'k_estimated_inside_module_count', k_estimated_inside_count, ...
    'csv_numeric_fields_used_as_bit_oracle', false, ...
    'live_reference_used', true, ...
    'live_reference_serialization_roundtrip_count', 0, ...
    'csv_oracle_audit', csv_oracle_audit, ...
    'reference_audit', reference_audit);
fprintf('%s\n', audit.live_reference_status);
clear path_cleanup
end

function audit = audit_lossy_csv_oracle_local(source27)
k1 = source27(source27.truth_K == 1 & ...
    source27.method_id == "H1_DIRECT_SAFE_HYBRID_KNOWN_K", :);
assert_f1b_local(height(k1) == 16, '', 'csv_k1_shape');
first = k1(1, :);
tokens = regexp(char(first.final_angles), ...
    '[-+]?(?:(?:\d+\.?\d*)|(?:\.\d+))(?:[eE][-+]?\d+)?', 'match');
digit_counts = cellfun(@significant_digit_count_local, tokens);
valid = isstring(source27.final_angles) && ...
    isnumeric(source27.RSS) && isnumeric(source27.loglik) && ...
    numel(tokens) == 2 && all(digit_counts == 17);
assert_f1b_local(valid, char(first.trial_id), ...
    'csv_numeric_oracle_format_audit');
audit = struct('pass', true, ...
    'status', 'CSV_NUMERIC_NOT_REGISTERED_AS_BIT_ORACLE_PASS', ...
    'final_angles_storage_class', class(source27.final_angles), ...
    'rss_storage_class', class(source27.RSS), ...
    'loglik_storage_class', class(source27.loglik), ...
    'first_k1_final_angle_digit_counts', digit_counts, ...
    'csv_numeric_fields_used_as_bit_oracle', false);
end

function count = significant_digit_count_local(token)
mantissa = regexp(token, '^[^eE]+', 'match', 'once');
digits = regexprep(mantissa, '[^0-9]', '');
count = numel(digits);
end

function hash = live_hash_local(reference_rows, trial_id)
rows = reference_rows(reference_rows.trial_id == string(trial_id), :);
hashes = unique(string(rows.element_trial_hash));
assert_f1b_local(height(rows) == 3 && numel(hashes) == 1, ...
    char(trial_id), 'live_element_trial_hash');
hash = hashes(1);
end

function row = one_row_local(rows, trial_id, label)
row = rows(rows.trial_id == string(trial_id), :);
assert_f1b_local(height(row) == 1, char(trial_id), label);
end

function compare_results_local(left, right, trial_id, label)
assert_hex_local(left.angles_hat_deg, right.angles_hat_deg, ...
    trial_id, [label, '.angles']);
assert_hex_local(left.rss, right.rss, trial_id, [label, '.RSS']);
assert_hex_local(left.loglik_concentrated, ...
    right.loglik_concentrated, trial_id, [label, '.loglik']);
assert_f1b_local(left.fit_valid == right.fit_valid, ...
    trial_id, [label, '.fit_valid']);
assert_f1b_local(strcmp(left.fit_status, right.fit_status), ...
    trial_id, [label, '.fit_status']);
assert_f1b_local(strcmp(left.selected_source, right.selected_source), ...
    trial_id, [label, '.selected_source']);
assert_f1b_local(strcmp(left.selected_start_id, right.selected_start_id), ...
    trial_id, [label, '.selected_start_id']);
assert_f1b_local(strcmp(selected_solver_status_local(left), ...
    selected_solver_status_local(right)), trial_id, ...
    [label, '.solver_status']);
end

function compare_live_local(result, live, trial, label, compare_source)
trial_id = char(live.trial_id);
K = double(live.truth_K);
angles = parse_historical_angle_matrix(live.final_angles, K);
assert_hex_local(result.angles_hat_deg, angles, ...
    trial_id, [label, '.angles']);
assert_hex_local(result.rss, live.RSS, trial_id, [label, '.RSS']);
assert_hex_local(result.loglik_concentrated, live.loglik, ...
    trial_id, [label, '.loglik']);
assert_f1b_local(result.fit_valid == logical(live.fit_valid), ...
    trial_id, [label, '.fit_valid']);
assert_f1b_local(strcmp(result.fit_status, char(live.fit_status)), ...
    trial_id, [label, '.fit_status']);
assert_f1b_local(strcmp(selected_solver_status_local(result), ...
    char(live.solver_status)), trial_id, [label, '.solver_status']);
assert_f1b_local(strcmp(result.selected_start_id, ...
    char(live.selected_start_id)), trial_id, ...
    [label, '.selected_start_id']);
assert_f1b_local(string(trial.element_trial_hash) == ...
    live.element_trial_hash, trial_id, [label, '.element_trial_hash']);
if compare_source
    assert_f1b_local(strcmp(result.selected_source, ...
        char(live.selected_source)), trial_id, ...
        [label, '.selected_source']);
end
end

function status = selected_solver_status_local(result)
if strcmp(result.selected_source, 'CONTINUOUS_UPGRADE')
    candidate = result.continuous_candidate;
else
    candidate = result.fixed_grid_candidate;
end
status = char(string(candidate.solver_status));
end

function assert_hex_local(actual, expected, trial_id, field)
actual_hex = num2hex(double(actual));
expected_hex = num2hex(double(expected));
if ~isequal(actual_hex, expected_hex)
    error('test_historical_24_trial_regression:Mismatch', ...
        ['F1B_FAIL_STOPPED: trial_id=%s field=%s new num2hex=%s ' ...
        'live reference num2hex=%s.'], trial_id, field, ...
        hex_text_local(actual_hex), hex_text_local(expected_hex));
end
end

function text = hex_text_local(hex)
text = char(strjoin(string(cellstr(hex)), ','));
end

function assert_f1b_local(condition, trial_id, field)
if ~condition
    error('test_historical_24_trial_regression:Mismatch', ...
        'F1B_FAIL_STOPPED: exact mismatch at %s:%s.', trial_id, field);
end
end

function [truth_count, tracking_count, cross_cpi_count, k_count] = ...
    add_boundary_counts_local(result, truth_count, tracking_count, ...
    cross_cpi_count, k_count)
truth_count = truth_count + double(result.truth_used_in_fit_flag);
tracking_count = tracking_count + double(result.tracking_input_used_flag);
cross_cpi_count = cross_cpi_count + ...
    double(result.cross_cpi_data_used_flag);
k_count = k_count + double(result.K_estimated_inside_module_flag);
if isfield(result, 'diagnostics') && ~isempty(fieldnames(result.diagnostics))
    diagnostics = result.diagnostics;
    truth_count = truth_count + ...
        double(diagnostics.truth_used_in_initialization_flag) + ...
        double(diagnostics.truth_used_in_fit_flag);
    tracking_count = tracking_count + ...
        double(diagnostics.tracking_input_used_flag);
    cross_cpi_count = cross_cpi_count + ...
        double(diagnostics.cross_cpi_data_used_flag);
    if isfield(diagnostics, 'selection') && ...
            isfield(diagnostics.selection, 'selection_truth_used_flag')
        truth_count = truth_count + ...
            double(diagnostics.selection.selection_truth_used_flag);
    end
end
end
