function test_no_truth_or_tracking_dependency()
%TEST_NO_TRUTH_OR_TRACKING_DEPENDENCY Audit the public fitting source text.

common_dir = fileparts(fileparts(mfilename('fullpath')));
sources = { ...
    fullfile(common_dir, 'common', 'estimate_stage8_known_k_local_cell.m'), ...
    fullfile(common_dir, 'common', 'fit_stage8_core_lite.m'), ...
    fullfile(common_dir, 'common', 'fit_stage8_core_plus.m'), ...
    fullfile(common_dir, 'common', 'select_stage8_safe_known_k_candidate.m')};
for index = 1:numel(sources)
    text = fileread(sources{index});
    assert(isempty(regexp(text, 'truth_angles|truth_separation|truth_difficulty', ...
        'once')));
    assert(isempty(regexp(text, 'previous[_-]?cpi|tracking[_-]?data|q_global', ...
        'once')));
end
end
