function test_public_input_contract(repo_dir)
%TEST_PUBLIC_INPUT_CONTRACT Verify the sole public function boundary.

fixture = build_stage8_core_v2_2_test_fixture(repo_dir);
trial = fixture.trial;
context = fixture.context;
result = estimate_stage8_known_k_local_cell(trial.Y_element, trial.model, ...
    context.plan.local_domain, context.stage5_locked, ...
    trial.model.noise_factorization, 1, struct());
assert(result.K == 1 && strcmp(result.mode, 'CORE_LITE'));
assert(result.single_cpi_flag && result.same_range_doppler_cell_flag);
assert(~result.cross_cpi_data_used_flag && ...
    ~result.tracking_input_used_flag && ...
    ~result.K_estimated_inside_module_flag && ...
    ~result.truth_used_in_fit_flag);
assert_throws_local(@() estimate_stage8_known_k_local_cell( ...
    trial.Y_element, trial.model, context.plan.local_domain, ...
    context.stage5_locked, trial.model.noise_factorization, 3, struct()));
assert_throws_local(@() estimate_stage8_known_k_local_cell( ...
    trial.Y_element, trial.model, context.plan.local_domain, ...
    context.stage5_locked, trial.model.noise_factorization, 1, ...
    struct('mode', 'CORE_LITE', 'truth_angles_deg', [8, 10])));
assert_throws_local(@() estimate_stage8_known_k_local_cell( ...
    trial.Y_element, trial.model, context.plan.local_domain, ...
    context.stage5_locked, trial.model.noise_factorization, 1, ...
    struct('mode', 'AUTO')));
end

function assert_throws_local(action)
thrown = false;
try
    action();
catch
    thrown = true;
end
assert(thrown);
end
