function audit = test_f0_process_classifier_contract()
%TEST_F0_PROCESS_CLASSIFIER_CONTRACT Verify exact process classification.

case_a = snapshot_local( ...
    [100, 90, 80], [90, 80, 0], ...
    ["matlab.exe", "matlab.exe", "powershell.exe"], ...
    ["", "", "powershell.exe -NoProfile"], ...
    ["", "", ""]);
classified_a = stage8_core_v2_2_classify_process_snapshot(case_a, 100);
assert(classified_a.external_matlab_count == 0);
assert(isequal(classified_a.current_lineage_ids, [100, 90, 80]));

case_b = append_local(case_a, ...
    snapshot_local([50, 200], [0, 50], ...
    ["explorer.exe", "matlab.exe"], ["", ""], ["", ""]));
classified_b = stage8_core_v2_2_classify_process_snapshot(case_b, 100);
assert(classified_b.external_matlab_count == 1);
assert(isequal(classified_b.external_matlab_matches.process_id, 200));

case_c = append_local(case_b, ...
    snapshot_local(300, 50, "mwpython.exe", "", ""));
classified_c = stage8_core_v2_2_classify_process_snapshot(case_c, 100);
assert(classified_c.mwpython_count == 1);
assert(isequal(classified_c.mwpython_matches.process_id, 300));

generic_text = [ ...
    "cmd.exe /c stage8.*coordinator|coordinator.*stage8", ...
    "powershell Get-CimInstance Win32_Process coordinator_count"];
case_d = append_local(case_a, ...
    snapshot_local([400, 401], [80, 400], ...
    ["cmd.exe", "powershell.exe"], generic_text, ["", ""]));
classified_d = stage8_core_v2_2_classify_process_snapshot(case_d, 100);
assert(classified_d.legacy_orchestrator_count == 0);

case_e = append_local(case_a, ...
    snapshot_local(500, 20, "powershell.exe", ...
    "powershell.exe -File C:\tools\Stage8K1Sharded.ps1 -Action Start", ...
    "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"));
classified_e = stage8_core_v2_2_classify_process_snapshot(case_e, 100);
assert(classified_e.legacy_orchestrator_count == 1);
assert(isequal(classified_e.legacy_orchestrator_matches.process_id, 500));
assert(isequal(classified_e.legacy_orchestrator_matches.matched_basename, ...
    "Stage8K1Sharded.ps1"));
assert(classified_e.coordinator_count == 1);

ordinary_text = [ ...
    "powershell Get-Content stage8 coordinator notes.txt", ...
    "cmd.exe /c type stage8_coordinator.log"];
case_f = append_local(case_a, ...
    snapshot_local([600, 601], [20, 20], ...
    ["powershell.exe", "cmd.exe"], ordinary_text, ["", ""]));
classified_f = stage8_core_v2_2_classify_process_snapshot(case_f, 100);
assert(classified_f.legacy_orchestrator_count == 0);

audit = struct('pass', true, ...
    'status', 'F0_PROCESS_CLASSIFIER_CONTRACT_PASS', ...
    'current_matlab_lineage_pass', true, ...
    'external_matlab_pass', true, 'mwpython_pass', true, ...
    'generic_coordinator_text_no_match_pass', true, ...
    'exact_legacy_script_match_pass', true, ...
    'ordinary_text_no_match_pass', true);
end

function snapshot = snapshot_local(pid, ppid, name, command_line, path)
process_id = double(pid(:));
parent_process_id = double(ppid(:));
name = string(name(:));
executable_path = string(path(:));
command_line = string(command_line(:));
snapshot = table(process_id, parent_process_id, name, executable_path, ...
    command_line);
end

function combined = append_local(left, right)
combined = [left; right];
end
