function output = stage8_k2_wacb_summarize( ...
    merged, context, runtime_root, runtime_state, preflight)
%STAGE8_K2_WACB_SUMMARIZE Write registered data, plots, report, and manifest.

repo_dir = context.repo_dir;
root = fullfile(repo_dir, 'innovation-mining');
figure_dir = fullfile(root, 'figures');
constants = context.constants;
plot_data = stage8_k2_wacb_build_plot_data(merged, context);
summaries = stage8_k2_wacb_summaries( ...
    plot_data, merged.diagnostics, constants);
paths = output_paths_local(root);
writetable(merged.registry_audit, paths.registry_audit);
writetable(merged.new_rows, paths.new_results);
writetable(merged.diagnostics, paths.diagnostics);
writetable(plot_data, paths.plot_data);
writetable(summaries.overall, paths.summary);
writetable(summaries.profile, paths.profile_summary);
writetable(summaries.noise, paths.noise_summary);
writetable(summaries.snapshot, paths.snapshot_summary);
writetable(summaries.exact, paths.exact_summary);
writetable(summaries.applicability, paths.applicability_summary);
writetable(summaries.failure, paths.failure_summary);
writetable(summaries.pairwise, paths.pairwise);
writetable(summaries.complexity, paths.complexity);
writetable(summaries.eigenstructure, paths.eigenstructure);

representative_spectra = merged.representative_spectra; %#ok<NASGU>
save(paths.representative_mat, 'representative_spectra', '-v7.3');
index_rows = repmat(struct('global_trial_index', 0, 'trial_id', "", ...
    'noise_profile_id', "", 'profile_id', "", ...
    'white_beamspace_snr_target_db', NaN, 'L', 0, 'replicate_id', 0, ...
    'element_music_payload', true, 'gfbss_applicable', false, ...
    'root_applicable', false, 'esprit_applicable', false), ...
    constants.representative_count, 1);
for index = 1:numel(representative_spectra)
    item = representative_spectra{index};
    index_rows(index) = struct( ...
        'global_trial_index', item.global_trial_index, ...
        'trial_id', item.trial_id, 'noise_profile_id', item.noise_profile_id, ...
        'profile_id', item.profile_id, ...
        'white_beamspace_snr_target_db', item.white_snr_db, ...
        'L', item.L, 'replicate_id', item.replicate_id, ...
        'element_music_payload', true, ...
        'gfbss_applicable', logical(item.gfbss.applicable), ...
        'root_applicable', logical(item.root_music.applicable), ...
        'esprit_applicable', logical(item.esprit.applicable));
end
representative_index = sortrows(struct2table(index_rows), ...
    'global_trial_index');
writetable(representative_index, paths.representative_index);

plot_inputs = [string(paths.plot_data); string(paths.summary); ...
    string(paths.profile_summary); string(paths.failure_summary); ...
    string(paths.pairwise); string(paths.complexity); ...
    string(paths.eigenstructure); string(paths.representative_mat); ...
    string(paths.representative_index)];
plot_hashes = repmat(struct('path', '', 'sha256', ''), ...
    numel(plot_inputs), 1);
for index = 1:numel(plot_inputs)
    plot_hashes(index) = struct( ...
        'path', relative_path_local(plot_inputs(index), repo_dir), ...
        'sha256', stage8_k2_wacb_file_sha256(plot_inputs(index)));
end
plot_manifest = struct('protocol', constants.protocol, ...
    'method_display_order', constants.all_method_ids, ...
    'comparison_tiers', [ ...
    "TIER_A_WHITE_SEQUENTIAL_BEAMSPACE"; ...
    "TIER_B_FULL_ELEMENT_2D_MANIFOLD"; ...
    "TIER_C_VERTICAL_ULA_PLUS_AZ_CML"], ...
    'valid_rate_denominator', 'APPLICABLE_ROWS', ...
    'rmse_denominator', 'APPLICABLE_AND_FIT_VALID_ROWS', ...
    'na_handling', 'STRUCTURAL_NA_EXCLUDED_FROM_FAILURE_AND_RMSE', ...
    'snr_coordinate', ...
    'WHITENED_SEQUENTIAL_BEAMSPACE_EXPECTED_TOTAL_SNR', ...
    'representative_trial_count', constants.representative_count, ...
    'plot_data_hashes', plot_hashes, ...
    'recommended_recipes', ["VALID_RATE_AND_CONDITIONAL_RMSE"; ...
    "COMPARISON_TIERS_SEPARATE"; "COMMON_VALID_PAIRWISE_ONLY"]);
stage8_k2_wacb_write_json_atomic(paths.plot_manifest, plot_manifest);
figure_paths = stage8_k2_wacb_plot_from_committed_data( ...
    repo_dir, root, figure_dir);

interpretation = interpretation_local(summaries.overall, constants);
write_report_local(paths.report, merged, summaries, interpretation, constants);
artifact_paths = [ ...
    string(paths.registry_audit); string(paths.new_results); ...
    string(paths.diagnostics); string(paths.plot_data); ...
    string(paths.summary); string(paths.profile_summary); ...
    string(paths.noise_summary); string(paths.snapshot_summary); ...
    string(paths.exact_summary); string(paths.applicability_summary); ...
    string(paths.failure_summary); string(paths.pairwise); ...
    string(paths.complexity); string(paths.eigenstructure); ...
    string(paths.representative_mat); string(paths.representative_index); ...
    string(paths.plot_manifest); string(paths.report); figure_paths(:)];
artifact_ids = [ ...
    "registry_audit"; "new_method_results"; "new_method_diagnostics"; ...
    "all_method_plot_data"; "summary"; "profile_summary"; ...
    "noise_summary"; "snapshot_summary"; "exact_cell_summary"; ...
    "applicability_summary"; "failure_summary"; "pairwise_vs_tangent"; ...
    "complexity_summary"; "eigenstructure_summary"; ...
    "representative_spectra"; "representative_spectra_index"; ...
    "plot_data_manifest"; "comparison_report"; ...
    "figure_valid_rate"; "figure_rmse_median"; "figure_rmse_p90"; ...
    "figure_elevation_valid"; "figure_conditional_valid"; ...
    "figure_failure"; "figure_runtime"; "figure_pairwise"; ...
    "figure_profile"; "figure_element_spectra"; ...
    "figure_gfbss_spectra"; "figure_root_esprit"];
if numel(artifact_paths) ~= 30 || numel(artifact_ids) ~= 30
    error('stage8_k2_wacb_summarize:ArtifactCount', ...
        'The registered artifact inventory must contain 30 files.');
end
artifacts = repmat(struct('artifact_id', '', 'path', '', 'sha256', ''), ...
    numel(artifact_paths), 1);
for index = 1:numel(artifact_paths)
    if ~isfile(artifact_paths(index))
        error('stage8_k2_wacb_summarize:ArtifactMissing', ...
            'A registered output artifact is missing.');
    end
    artifacts(index) = struct('artifact_id', char(artifact_ids(index)), ...
        'path', relative_path_local(artifact_paths(index), repo_dir), ...
        'sha256', stage8_k2_wacb_file_sha256(artifact_paths(index)));
end
controller = controller_counts_local(runtime_root);
manifest = struct('status', 'FINALIZED_AWAITING_INDEPENDENT_AUDIT', ...
    'terminal_status', ...
    'STAGE8_K2_WHITE_SNR_ALL_CLASSICAL_BASELINE_FINALIZED_AWAITING_AUDIT', ...
    'protocol', constants.protocol, 'authorization', constants.authorization, ...
    'branch', constants.branch, 'source_white_classic_head', ...
    constants.source_commit, 'prompt_commit', constants.prompt_commit, ...
    'formal_run_head', preflight.head, 'matlab_release', version('-release'), ...
    'max_computational_threads', maxNumCompThreads, ...
    'runtime_root', runtime_root, 'test_count', 13, ...
    'registry_count', height(merged.registry), ...
    'checkpoint_count', merged.scan.completed_count, ...
    'new_method_row_count', height(merged.new_rows), ...
    'diagnostic_row_count', height(merged.diagnostics), ...
    'all_method_row_count', height(plot_data), ...
    'element_music_applicable_count', nnz(merged.new_rows.method_id == ...
    "ELEMENT_MUSIC_K2" & merged.new_rows.applicable), ...
    'gfbss_applicable_count', nnz(merged.new_rows.method_id == ...
    "ELEMENT_VERTICAL_GFBSS_MUSIC_AZ_CML" & merged.new_rows.applicable), ...
    'root_music_applicable_count', nnz(merged.new_rows.method_id == ...
    "ELEMENT_VERTICAL_FBSS_ROOT_MUSIC_AZ_CML" & ...
    merged.new_rows.applicable), ...
    'ls_esprit_applicable_count', nnz(merged.new_rows.method_id == ...
    "ELEMENT_VERTICAL_FBSS_LS_ESPRIT_AZ_CML" & ...
    merged.new_rows.applicable), ...
    'representative_spectra_count', height(representative_index), ...
    'truth_leakage_count', nnz(merged.new_rows.truth_used_in_fit_flag), ...
    'profile_leakage_count', nnz(merged.new_rows.profile_used_in_fit_flag), ...
    'tangent_start_count', nnz(merged.new_rows.tangent_used_in_start_flag), ...
    'core_start_count', nnz(merged.new_rows.core_used_in_start_flag), ...
    'full4d_start_count', nnz(merged.new_rows.full4d_used_in_start_flag), ...
    'existing_method_rerun_count', 0, 'tangent_rerun_count', 0, ...
    'core_rerun_count', 0, 'full4d_rerun_count', 0, ...
    'beamspace_music_rerun_count', 0, ...
    'maximum_white_target_error_db', ...
    max(merged.registry_audit.white_target_error_db), ...
    'registry_hash', runtime_state.registry_hash, ...
    'code_identity', context.code_identity.tree_hash, ...
    'evidence44_identity', context.evidence44.identity, ...
    'evidence46_identity', context.evidence46.identity, ...
    'evidence44_manifest_sha256', context.evidence44.manifest_sha256, ...
    'evidence46_manifest_sha256', context.evidence46.manifest_sha256, ...
    'total_active_runtime_sec', merged.total_active_runtime_sec, ...
    'median_trial_runtime_sec', merged.median_trial_runtime_sec, ...
    'trial_launch_count', controller.trial_launch_count, ...
    'resume_launch_count', controller.resume_launch_count, ...
    'finalization_launch_count', controller.finalization_launch_count, ...
    'audit_launch_count', controller.audit_launch_count, ...
    'interpretation', interpretation, 'independent_audit_status', 'PENDING', ...
    'independent_artifact_hash_match_count', 0, ...
    'tangent_algorithm_modified', false, 'production_modified', false, ...
    'merge_back', false, 'artifacts', artifacts, ...
    'next', 'INDEPENDENT_AUDIT');
stage8_k2_wacb_write_json_atomic(paths.runtime_manifest, manifest);
save(fullfile(runtime_root, 'merged', 'finalized_tables.mat'), ...
    'plot_data', 'summaries', 'interpretation', 'manifest', '-mat');
output = struct('status', 'FINALIZED_AWAITING_INDEPENDENT_AUDIT', ...
    'manifest_path', paths.runtime_manifest, ...
    'artifact_count', numel(artifacts), ...
    'next', 'RUN_FRESH_STAGE8_K2_WACB_VERIFY_SESSION');
end

function paths = output_paths_local(root)
prefix = '48_stage8_k2_white_snr_';
paths = struct( ...
    'registry_audit', fullfile(root, [prefix, ...
    'all_classical_registry_audit.csv']), ...
    'new_results', fullfile(root, [prefix, ...
    'new_classical_method_results.csv']), ...
    'diagnostics', fullfile(root, [prefix, ...
    'new_classical_diagnostics.csv']), ...
    'plot_data', fullfile(root, [prefix, 'all_method_plot_data.csv']), ...
    'summary', fullfile(root, [prefix, 'all_method_summary.csv']), ...
    'profile_summary', fullfile(root, [prefix, ...
    'all_method_profile_summary.csv']), ...
    'noise_summary', fullfile(root, [prefix, ...
    'all_method_noise_summary.csv']), ...
    'snapshot_summary', fullfile(root, [prefix, ...
    'all_method_snapshot_summary.csv']), ...
    'exact_summary', fullfile(root, [prefix, ...
    'all_method_exact_cell_summary.csv']), ...
    'applicability_summary', fullfile(root, [prefix, ...
    'all_method_applicability_summary.csv']), ...
    'failure_summary', fullfile(root, [prefix, ...
    'all_method_failure_summary.csv']), ...
    'pairwise', fullfile(root, [prefix, ...
    'all_method_pairwise_vs_tangent.csv']), ...
    'complexity', fullfile(root, [prefix, ...
    'all_method_complexity_summary.csv']), ...
    'eigenstructure', fullfile(root, [prefix, ...
    'subspace_eigenstructure_summary.csv']), ...
    'representative_mat', fullfile(root, [prefix, ...
    'representative_spectra.mat']), ...
    'representative_index', fullfile(root, [prefix, ...
    'representative_spectra_index.csv']), ...
    'plot_manifest', fullfile(root, [prefix, 'plot_data_manifest.json']), ...
    'runtime_manifest', fullfile(root, [prefix, ...
    'all_classical_runtime_manifest.json']), ...
    'report', fullfile(root, [prefix, ...
    'all_classical_comparison.md']));
end

function interpretation = interpretation_local(overall, constants)
methods = constants.method_ids;
items = repmat(struct('method_id', '', 'scientific_state', '', ...
    'first_valid_rate_ge_050_snr_db', NaN, ...
    'first_robustly_comparable_snr_db', NaN), numel(methods), 1);
for index = 1:numel(methods)
    selected = sortrows(overall(overall.method_id == methods(index), :), ...
        'white_beamspace_snr_target_db');
    first_valid = find(selected.valid_rate >= 0.5, 1);
    first_robust = find(selected.comparability_class == ...
        "ROBUSTLY_COMPARABLE", 1);
    if isempty(first_valid), valid_snr = NaN; else
        valid_snr = selected.white_beamspace_snr_target_db(first_valid); end
    if isempty(first_robust), robust_snr = NaN; else
        robust_snr = selected.white_beamspace_snr_target_db(first_robust); end
    if any(selected.comparability_class == "ROBUSTLY_COMPARABLE")
        state = 'ROBUST_REGION_IDENTIFIED';
    elseif any(selected.valid_count > 0)
        state = 'APPLICABILITY_LIMITED';
    elseif any(selected.applicable_count > 0)
        state = 'NO_VALID_REGION';
    else
        state = 'STRUCTURAL_REFERENCE_ONLY';
    end
    items(index) = struct('method_id', char(methods(index)), ...
        'scientific_state', state, ...
        'first_valid_rate_ge_050_snr_db', valid_snr, ...
        'first_robustly_comparable_snr_db', robust_snr);
end
interpretation = items;
end

function write_report_local(path_now, merged, summaries, interpretation, constants)
lines = [ ...
    "# Stage8 K2 Unified White-SNR All-Classical Comparison"; ""; ...
    "Status: `FINALIZED_AWAITING_INDEPENDENT_AUDIT`"; ""; ...
    "The comparison reconstructed 1680 immutable evidence-44 trials and ran"; ...
    "only the four preregistered new methods. The six evidence-44/46 methods"; ...
    "were read without refitting (`existing_method_rerun_count = 0`)."; ""; ...
    "## Integrity"; ""; ...
    "- checkpoints: `1680/1680`;"; ...
    "- new method rows: `6720`;"; ...
    "- new diagnostic rows: `6720`;"; ...
    "- unified plot rows: `16800`;"; ...
    "- representative spectra: `56`;"; ...
    "- truth/profile/start leakage: `0`;"; ...
    "- Element MUSIC applicable: `1120`;"; ...
    "- GFBSS-MUSIC applicable: `1260`;"; ...
    "- Root-MUSIC applicable: `630`;"; ...
    "- LS-ESPRIT applicable: `630`."; ""; ...
    "## Interpretation boundary"; ""; ...
    "White SNR is the common experimental coordinate, not an estimator input"; ...
    "for element-domain methods. Structural N/A rows are excluded from RMSE"; ...
    "and are not counted as Tangent wins. Pairwise statements use common-valid"; ...
    "trials only. Exact-cell P90 values with N=10 are descriptive, not stable"; ...
    "tail estimates. The three comparison tiers are not interchangeable"; ...
    "hardware interfaces. No global superiority claim, online selector, or"; ...
    "production threshold is created."; ""; ...
    "## New-method scientific states"; ""];
for index = 1:numel(interpretation)
    lines(end + 1) = "- `" + string(interpretation(index).method_id) + ...
        "`: `" + string(interpretation(index).scientific_state) + "`."; %#ok<AGROW>
end
lines = [lines; ""; "Next: `INDEPENDENT_AUDIT`"];
if height(merged.new_rows) ~= constants.new_method_row_count || ...
        height(summaries.overall) ~= 70
    error('stage8_k2_wacb_summarize:ReportIntegrity', ...
        'Report inputs are incomplete.');
end
stage8_k2_wacb_write_text_atomic(path_now, join(lines, newline) + newline);
end

function controller = controller_counts_local(runtime_root)
controller = struct('trial_launch_count', 0, 'resume_launch_count', 0, ...
    'finalization_launch_count', 0, 'audit_launch_count', 0);
path_now = fullfile(runtime_root, 'controller', 'controller_state.json');
if ~isfile(path_now), return; end
stored = jsondecode(fileread(path_now));
names = fieldnames(controller);
for index = 1:numel(names)
    if isfield(stored, names{index})
        controller.(names{index}) = double(stored.(names{index}));
    end
end
end

function path_relative = relative_path_local(path_now, repo_dir)
canonical = char(java.io.File(char(string(path_now))).getCanonicalPath());
prefix = [char(java.io.File(repo_dir).getCanonicalPath()), filesep];
if ~startsWith(lower(canonical), lower(prefix))
    error('stage8_k2_wacb_summarize:ArtifactScope', ...
        'Artifact is outside the repository.');
end
path_relative = strrep(canonical(numel(prefix) + 1:end), filesep, '/');
end
