function digest = stage8_k2_wacb_checkpoint_hash(checkpoint)
%STAGE8_K2_WACB_CHECKPOINT_HASH Hash all scientific checkpoint content.

copy = checkpoint;
copy.scientific_hash = '';
digest = stage8_k2_wacb_stable_hash('TRIAL_CHECKPOINT', ...
    copy.protocol, copy.checkpoint_contract_version, ...
    copy.evidence44_registry_row, copy.registry_row, ...
    copy.trial_identity, copy.new_method_rows, copy.diagnostic_rows, ...
    copy.representative_spectrum, copy.code_identity, ...
    copy.registry_hash, copy.runtime_sec, copy.completion_status);
end
