function merged = stage8_k2_wacb_merge( ...
    runtime_root, registry, context, registry_hash)
%STAGE8_K2_WACB_MERGE Validate and merge all immutable checkpoints.

scan = stage8_k2_wacb_scan_checkpoints( ...
    runtime_root, registry, context, registry_hash);
constants = context.constants;
if scan.completed_count ~= constants.trial_count || scan.tmp_count ~= 0 || ...
        scan.unexpected_count ~= 0 || scan.unexpected_tmp_count ~= 0
    error('stage8_k2_wacb_merge:CheckpointCount', ...
        'Merge requires 1680 valid checkpoints and zero temporary files.');
end
row_blocks = cell(constants.trial_count, 1);
diagnostic_blocks = cell(constants.trial_count, 1);
representative = cell(constants.representative_count, 1);
representative_index = 0;
audit_rows = repmat(struct('global_trial_index', 0, 'trial_id', "", ...
    'element_trial_hash', "", 'measurement_hash', "", ...
    'checkpoint_valid', false, 'scientific_hash', "", ...
    'white_target_error_db', NaN, 'runtime_sec', NaN), ...
    constants.trial_count, 1);
for index = 1:constants.trial_count
    checkpoint = scan.checkpoints{index};
    row_blocks{index} = checkpoint.new_method_rows;
    diagnostic_blocks{index} = checkpoint.diagnostic_rows;
    if checkpoint.representative_spectrum.included
        representative_index = representative_index + 1;
        representative{representative_index} = ...
            checkpoint.representative_spectrum;
    end
    audit_rows(index) = struct( ...
        'global_trial_index', double(registry.global_trial_index(index)), ...
        'trial_id', string(registry.trial_id(index)), ...
        'element_trial_hash', ...
        string(checkpoint.trial_identity.element_trial_hash), ...
        'measurement_hash', ...
        string(checkpoint.trial_identity.measurement_hash), ...
        'checkpoint_valid', true, ...
        'scientific_hash', string(checkpoint.scientific_hash), ...
        'white_target_error_db', ...
        double(checkpoint.trial_identity.white_target_error_db), ...
        'runtime_sec', double(checkpoint.runtime_sec));
end
new_rows = sortrows(vertcat(row_blocks{:}), ...
    {'global_trial_index','method_id'});
diagnostics = sortrows(vertcat(diagnostic_blocks{:}), ...
    {'global_trial_index','method_id'});
registry_audit = struct2table(audit_rows);
if height(new_rows) ~= constants.new_method_row_count || ...
        height(diagnostics) ~= constants.diagnostic_row_count || ...
        representative_index ~= constants.representative_count || ...
        numel(unique(new_rows.trial_id + "|" + new_rows.method_id)) ~= ...
        constants.new_method_row_count || ...
        nnz(new_rows.method_id == "ELEMENT_MUSIC_K2" & ...
        new_rows.applicable) ~= constants.element_music_applicable_count || ...
        nnz(new_rows.method_id == ...
        "ELEMENT_VERTICAL_GFBSS_MUSIC_AZ_CML" & new_rows.applicable) ~= ...
        constants.gfbss_applicable_count || ...
        nnz(new_rows.method_id == ...
        "ELEMENT_VERTICAL_FBSS_ROOT_MUSIC_AZ_CML" & new_rows.applicable) ~= ...
        constants.root_applicable_count || ...
        nnz(new_rows.method_id == ...
        "ELEMENT_VERTICAL_FBSS_LS_ESPRIT_AZ_CML" & new_rows.applicable) ~= ...
        constants.esprit_applicable_count || ...
        any(new_rows.truth_used_in_fit_flag) || ...
        any(new_rows.profile_used_in_fit_flag) || ...
        any(new_rows.tangent_used_in_start_flag) || ...
        any(new_rows.core_used_in_start_flag) || ...
        any(new_rows.full4d_used_in_start_flag) || ...
        max(registry_audit.white_target_error_db) > constants.snr_db_tolerance
    error('stage8_k2_wacb_merge:Integrity', ...
        'Merged counts, applicability, identity, or isolation failed.');
end
writetable(registry, fullfile(runtime_root, 'merged', 'registry.csv'));
writetable(registry_audit, fullfile(runtime_root, 'merged', ...
    'registry_audit.csv'));
writetable(new_rows, fullfile(runtime_root, 'merged', ...
    'new_method_results.csv'));
writetable(diagnostics, fullfile(runtime_root, 'merged', ...
    'new_method_diagnostics.csv'));
save(fullfile(runtime_root, 'merged', 'merged_rows.mat'), ...
    'new_rows', 'diagnostics', 'registry_audit', '-mat');
merged = struct('registry', registry, 'registry_audit', registry_audit, ...
    'new_rows', new_rows, 'diagnostics', diagnostics, ...
    'representative_spectra', {representative}, 'scan', scan, ...
    'total_active_runtime_sec', sum(scan.runtime_sec), ...
    'median_trial_runtime_sec', median(scan.runtime_sec));
end
