function registry = stage8_k2_wacb_build_registry(context)
%STAGE8_K2_WACB_BUILD_REGISTRY Bind applicability to evidence-44 trials.

registry = context.evidence44.registry;
constants = context.constants;
registry.element_music_applicable_flag = ismember(double(registry.L), ...
    constants.music_applicable_L);
registry.gfbss_applicable_flag = registry.profile_id ~= "P2";
registry.root_applicable_flag = registry.profile_id ~= "P2" & ...
    registry.noise_profile_id == "WHITE";
registry.esprit_applicable_flag = registry.root_applicable_flag;
registry.representative_spectrum_flag = double(registry.L) == 8 & ...
    double(registry.replicate_id) == 1;
if height(registry) ~= constants.trial_count || ...
        nnz(registry.element_music_applicable_flag) ~= ...
        constants.element_music_applicable_count || ...
        nnz(registry.gfbss_applicable_flag) ~= constants.gfbss_applicable_count || ...
        nnz(registry.root_applicable_flag) ~= constants.root_applicable_count || ...
        nnz(registry.esprit_applicable_flag) ~= constants.esprit_applicable_count || ...
        nnz(registry.representative_spectrum_flag) ~= ...
        constants.representative_count || ...
        numel(unique(registry.trial_id)) ~= constants.trial_count || ...
        numel(unique(registry.element_trial_hash)) ~= constants.trial_count
    error('stage8_k2_wacb_build_registry:Contract', ...
        'Registry cardinality or applicability counts changed.');
end
end
