function row = stage8_k2_wacb_diagnostic_row( ...
    spec, trial, method_id, rule, fit, common)
%STAGE8_K2_WACB_DIAGNOSTIC_ROW Serialize registered estimator diagnostics.

row = template_local();
row.trial_id = string(spec.trial_id);
row.global_trial_index = double(spec.global_trial_index);
row.element_trial_hash = string(trial.element_trial_hash);
row.measurement_hash = string(trial.measurement_hash);
row.method_id = string(method_id);
row.noise_profile_id = string(spec.noise_profile_id);
row.L = double(spec.L);
row.profile_id = string(spec.profile_id);
row.replicate_id = double(spec.replicate_id);
row.white_beamspace_snr_target_db = ...
    double(spec.white_beamspace_snr_target_db);
row.applicable = logical(rule.applicable);
row.applicability_status = string(rule.status);
row.applicability_uses_registered_scenario_flag = logical( ...
    rule.uses_registered_scenario_flag);
if method_id == "ELEMENT_MUSIC_K2"
    result = fit.element_music;
    row.elevation_fit_valid = logical(result.fit_valid);
    row.elevation_fit_status = string(result.fit_status);
    row.element_music_sample_rank = double(result.effective_rank);
    row.element_music_rank_threshold = double(get_local( ...
        result, 'sample_rank_threshold', NaN));
    row.element_music_local_peak_count = double(result.local_peak_count);
    row.element_music_top10_peaks = string(mat2str( ...
        get_local(result, 'peak_values', [NaN, NaN]), 17));
    row.sample_eigenvalues_top6 = string(mat2str(top_local( ...
        get_local(result, 'sample_eigenvalues', []), 6), 17));
    row.conditional_az_cml_status = "NOT_APPLICABLE";
    row.fit_valid = logical(result.fit_valid);
    row.fit_status = string(result.fit_status);
else
    item = fit.structured(find([fit.structured.method_id] == method_id, 1));
    elevation = item.elevation;
    conditional = item.conditional;
    result = item.combined;
    row.elevation_fit_valid = logical(elevation.fit_valid);
    row.elevation_fit_status = string(elevation.fit_status);
    row.elevations_hat_deg = string(mat2str( ...
        elevation.elevations_hat_deg, 17));
    row.elevation_selection_values = string(mat2str(get_local( ...
        elevation, 'selection_values', [NaN, NaN]), 17));
    row.gfbss_candidate_count = double(get_local( ...
        elevation, 'elevation_candidate_count', 0));
    row.gfbss_selected_elevations = row.elevations_hat_deg;
    row.root_polynomial_degree = double(max(0, ...
        get_local(elevation, 'root_count', 1) - 1));
    row.all_root_count = double(get_local(elevation, 'root_count', 0));
    row.registered_root_count = double(get_local( ...
        elevation, 'registered_root_count', 0));
    row.selected_roots = string(mat2str(get_local( ...
        elevation, 'selected_roots', [NaN, NaN]), 17));
    row.root_moduli = string(mat2str(get_local( ...
        elevation, 'selected_root_moduli', [NaN, NaN]), 17));
    eigenvalues = get_local(elevation, 'esprit_eigenvalues', [NaN, NaN]);
    row.esprit_shift_matrix_rank = double(get_local( ...
        elevation, 'shift_matrix_rank', 0));
    row.esprit_eigenvalue_real = string(mat2str(real(eigenvalues), 17));
    row.esprit_eigenvalue_imag = string(mat2str(imag(eigenvalues), 17));
    row.esprit_eigenvalue_modulus = string(mat2str(abs(eigenvalues), 17));
    row.esprit_eigenvalue_phase = string(mat2str(angle(eigenvalues), 17));
    row.conditional_az_cml_executed = logical(elevation.fit_valid);
    row.conditional_az_cml_valid = logical(conditional.fit_valid);
    row.conditional_az_cml_status = string(conditional.fit_status);
    row.coarse_candidate_count = double(conditional.coarse_candidate_count);
    row.continuous_start_count = double(conditional.continuous_start_count);
    row.best_coarse_loglik = double(get_local( ...
        conditional, 'best_coarse_loglik', NaN));
    row.selected_start = string(conditional.selected_start_id);
    row.sweep_count = double(conditional.sweep_count);
    row.fit_valid = logical(result.fit_valid);
    row.fit_status = string(result.fit_status);
end
if common.executed
    row.raw_vertical_eigenvalues_top6 = string(mat2str( ...
        top_local(common.raw_eigenvalues, 6), 17));
    row.fbss_eigenvalues_top6 = string(mat2str( ...
        top_local(common.fbss_eigenvalues, 6), 17));
    row.raw_signal_noise_eigengap = eigengap_local( ...
        common.raw_eigenvalues);
    row.fbss_signal_noise_eigengap = eigengap_local( ...
        common.fbss_eigenvalues);
    row.vertical_covariance_condition_proxy = common.raw_condition_proxy;
    row.fbss_condition_proxy = common.fbss_condition_proxy;
    row.vertical_hermitian_residual = ...
        common.vertical_info.hermitian_residual;
    row.fbss_hermitian_residual = common.fbss_info.hermitian_residual;
    row.fb_structure_residual = ...
        common.fbss_info.forward_backward_residual;
    row.noise_whitening_residual = ...
        common.vertical_info.az_whitening_error;
end
row.truth_used_in_fit_flag = false;
row.profile_used_in_fit_flag = false;
end

function values = top_local(values, count)
values = values(:).';
values = values(1:min(count, numel(values)));
if numel(values) < count
    values(end + 1:count) = NaN;
end
end

function value = eigengap_local(values)
if numel(values) >= 3
    value = double(values(2) / max(abs(values(3)), realmin('double')));
else
    value = NaN;
end
end

function row = template_local()
row = struct('trial_id', "", 'global_trial_index', 0, ...
    'element_trial_hash', "", 'measurement_hash', "", 'method_id', "", ...
    'noise_profile_id', "", 'L', 0, 'profile_id', "", ...
    'replicate_id', 0, 'white_beamspace_snr_target_db', NaN, ...
    'applicable', false, ...
    'applicability_status', "NOT_RUN", ...
    'applicability_uses_registered_scenario_flag', false, ...
    'fit_valid', false, 'fit_status', "NOT_RUN", ...
    'raw_vertical_eigenvalues_top6', "", ...
    'fbss_eigenvalues_top6', "", 'raw_signal_noise_eigengap', NaN, ...
    'fbss_signal_noise_eigengap', NaN, ...
    'vertical_covariance_condition_proxy', NaN, ...
    'fbss_condition_proxy', NaN, 'vertical_hermitian_residual', NaN, ...
    'fbss_hermitian_residual', NaN, 'fb_structure_residual', NaN, ...
    'noise_whitening_residual', NaN, 'sample_eigenvalues_top6', "", ...
    'element_music_sample_rank', 0, ...
    'element_music_rank_threshold', NaN, ...
    'element_music_local_peak_count', 0, ...
    'element_music_top10_peaks', "", 'elevation_fit_valid', false, ...
    'elevation_fit_status', "NOT_RUN", 'elevations_hat_deg', "", ...
    'elevation_selection_values', "", 'gfbss_candidate_count', 0, ...
    'gfbss_top10_elevation_peaks', "", ...
    'gfbss_selected_elevations', "", 'root_polynomial_degree', 0, ...
    'all_root_count', 0, 'registered_root_count', 0, ...
    'top10_registered_root_elevations', "", 'root_moduli', "", ...
    'root_phases', "", 'selected_roots', "", ...
    'esprit_shift_matrix_rank', 0, 'S1_singular_values', "", ...
    'esprit_eigenvalue_real', "", 'esprit_eigenvalue_imag', "", ...
    'esprit_eigenvalue_modulus', "", 'esprit_eigenvalue_phase', "", ...
    'conditional_az_cml_executed', false, ...
    'conditional_az_cml_valid', false, ...
    'conditional_az_cml_status', "NOT_RUN", ...
    'coarse_candidate_count', 0, 'continuous_start_count', 0, ...
    'best_coarse_loglik', NaN, 'selected_start', "", ...
    'sweep_count', 0, 'truth_used_in_fit_flag', false, ...
    'profile_used_in_fit_flag', false);
end

function value = get_local(input, field, default)
if isfield(input, field)
    value = input.(field);
else
    value = default;
end
end
