function output = stage8_k2_wacb_run(repo_dir, runtime_root)
%STAGE8_K2_WACB_RUN Run, resume, or finalize the registered comparison.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_wacb_run:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
constants = stage8_k2_wacb_constants();
if nargin < 2 || isempty(runtime_root)
    runtime_root = constants.runtime_root;
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
runtime_root = char(java.io.File(char(string(runtime_root))).getCanonicalPath());
expected_runtime = char(java.io.File(constants.runtime_root).getCanonicalPath());
if ~strcmp(runtime_root, expected_runtime)
    error('stage8_k2_wacb_run:RuntimeRoot', ...
        'Formal runtime is fixed at %s.', expected_runtime);
end
assert_runtime_local('stage8_k2_wacb_run');
scope = stage8_k2_wacb_add_paths(repo_dir); %#ok<NASGU>
context = stage8_k2_wacb_build_context(repo_dir);
preflight = stage8_k2_wacb_preflight(repo_dir, constants, false);
if ~preflight.pass
    error('stage8_k2_wacb_run:Preflight', ...
        'STAGE8_K2_WHITE_SNR_ALL_CLASSICAL_BASELINE_COMPARISON_INVALID: %s', ...
        preflight.last_error);
end
registry = stage8_k2_wacb_build_registry(context);
runtime_state = stage8_k2_wacb_registry_prepare( ...
    runtime_root, registry, context, preflight);
registry_hash = runtime_state.registry_hash;
scan = stage8_k2_wacb_scan_checkpoints( ...
    runtime_root, registry, context, registry_hash);
progress = stage8_k2_wacb_progress(scan);
stage8_k2_wacb_status_write(runtime_root, registry, progress, [], ...
    constants, runtime_state.mode);
fprintf('%s: %d/1680 validated checkpoints; %d remaining.\n', ...
    runtime_state.mode, scan.completed_count, scan.remaining_count);

ready_path = fullfile(runtime_root, 'ready_to_finalize.mat');
if scan.remaining_count > 0
    for noise_index = 1:numel(constants.noise_profile_ids)
        noise_id = constants.noise_profile_ids(noise_index);
        selected = find(registry.noise_profile_id == noise_id & ...
            ~scan.completed_mask);
        if isempty(selected)
            continue;
        end
        fprintf('Preparing one-noise Element MUSIC dictionary: %s\n', ...
            char(noise_id));
        resources = stage8_k2_wacb_prepare_noise_resources(context, noise_id);
        for position = 1:numel(selected)
            index = selected(position);
            spec = registry(index, :);
            trial_clock = tic;
            [trial, ~, identity] = ...
                stage8_k2_wacb_reconstruct_trial(spec, context);
            [rows, diagnostics, representative] = ...
                stage8_k2_wacb_evaluate_trial( ...
                spec, trial, context, resources);
            trial_runtime = toc(trial_clock);
            [checkpoint, ~] = stage8_k2_wacb_checkpoint_write( ...
                runtime_root, spec, identity, rows, diagnostics, ...
                representative, context, registry_hash, trial_runtime);
            scan.completed_mask(index) = true;
            scan.completed_count = scan.completed_count + 1;
            scan.remaining_count = scan.remaining_count - 1;
            scan.checkpoints{index} = checkpoint;
            scan.runtime_sec(index) = checkpoint.runtime_sec;
            progress = stage8_k2_wacb_progress(scan);
            stage8_k2_wacb_status_write(runtime_root, registry, progress, ...
                spec, constants, "TRIALS_RUNNING");
            if mod(scan.completed_count, constants.status_stride) == 0 || ...
                    scan.completed_count == constants.trial_count
                values = progress.runtime_sec(isfinite(progress.runtime_sec));
                median_runtime = median(values);
                fprintf([ ...
                    'WACB %d/1680: %s; median %.3f s; ETA %.1f s; ', ...
                    'Element %d valid/%d single/%d N-A; ', ...
                    'GFBSS %d/%d; Root %d/%d; ESPRIT %d/%d.\n'], ...
                    scan.completed_count, char(spec.trial_id), ...
                    median_runtime, median_runtime * scan.remaining_count, ...
                    progress.element_music_valid_count, ...
                    progress.element_music_single_peak_count, ...
                    progress.element_music_na_count, ...
                    progress.gfbss_elevation_valid_count, ...
                    progress.gfbss_end_to_end_valid_count, ...
                    progress.root_elevation_valid_count, ...
                    progress.root_end_to_end_valid_count, ...
                    progress.esprit_elevation_valid_count, ...
                    progress.esprit_end_to_end_valid_count);
            end
            clear trial rows diagnostics representative checkpoint
        end
        clear resources
        java.lang.System.gc();
    end
end

scan = stage8_k2_wacb_scan_checkpoints( ...
    runtime_root, registry, context, registry_hash);
if scan.completed_count ~= constants.trial_count
    error('stage8_k2_wacb_run:IncompleteScan', ...
        'The trial pass returned without all checkpoints.');
end
if ~isfile(ready_path)
    write_ready_local(ready_path, scan, context, registry_hash);
    progress = stage8_k2_wacb_progress(scan);
    stage8_k2_wacb_status_write(runtime_root, registry, progress, [], ...
        constants, "READY_TO_FINALIZE");
    output = struct('status', 'READY_TO_FINALIZE', ...
        'completed_count', scan.completed_count, ...
        'registry_hash', registry_hash, ...
        'next', 'FRESH_SINGLE_THREAD_FINALIZATION_SESSION');
    fprintf('READY_TO_FINALIZE\n');
    return;
end

validate_ready_local(ready_path, context, registry_hash);
merged = stage8_k2_wacb_merge( ...
    runtime_root, registry, context, registry_hash);
output = stage8_k2_wacb_summarize( ...
    merged, context, runtime_root, runtime_state, preflight);
complete_path = fullfile(runtime_root, 'complete_run.mat');
save(complete_path, 'output', 'preflight', '-mat');
progress = stage8_k2_wacb_progress(merged.scan);
stage8_k2_wacb_status_write(runtime_root, registry, progress, [], ...
    constants, "FINALIZED_AWAITING_INDEPENDENT_AUDIT");
fprintf('FINALIZED_AWAITING_INDEPENDENT_AUDIT\n');
end

function assert_runtime_local(identifier)
if ~strcmp(version('-release'), '2022b') || maxNumCompThreads ~= 1
    error([identifier, ':MATLABRuntime'], ...
        'Formal execution requires MATLAB R2022b with -singleCompThread.');
end
try
    pool = gcp('nocreate');
catch
    pool = [];
end
if ~isempty(pool)
    error([identifier, ':ParallelPool'], ...
        'Formal execution forbids an active parallel pool.');
end
end

function write_ready_local(path_now, scan, context, registry_hash)
ready_state = struct('protocol', context.constants.protocol, ...
    'code_identity', context.code_identity.tree_hash, ...
    'registry_hash', registry_hash, ...
    'evidence44_identity', context.evidence44.identity, ...
    'evidence46_identity', context.evidence46.identity, ...
    'checkpoint_count', scan.completed_count, ...
    'tmp_count', scan.tmp_count, ...
    'total_active_runtime_sec', sum(scan.runtime_sec), ...
    'median_trial_runtime_sec', median(scan.runtime_sec), ...
    'ready_utc', stage8_k2_mc_utc_now());
temporary = [path_now, '.tmp'];
save(temporary, 'ready_state', '-mat');
[ok, message] = movefile(temporary, path_now);
if ~ok, error('stage8_k2_wacb_run:ReadyMove', '%s', message); end
end

function validate_ready_local(path_now, context, registry_hash)
loaded = load(path_now, 'ready_state', '-mat');
if ~isfield(loaded, 'ready_state')
    error('stage8_k2_wacb_run:ReadySchema', 'Ready marker is invalid.');
end
ready = loaded.ready_state;
if ~strcmp(ready.protocol, context.constants.protocol) || ...
        ~strcmp(ready.code_identity, context.code_identity.tree_hash) || ...
        ~strcmp(ready.registry_hash, registry_hash) || ...
        string(ready.evidence44_identity) ~= context.evidence44.identity || ...
        string(ready.evidence46_identity) ~= context.evidence46.identity || ...
        ready.checkpoint_count ~= context.constants.trial_count || ...
        ready.tmp_count ~= 0
    error('stage8_k2_wacb_run:ReadyIdentity', ...
        'Ready-to-finalize marker identity is invalid.');
end
end
