function summaries = stage8_k2_wacb_summaries(plot_data, diagnostics, constants)
%STAGE8_K2_WACB_SUMMARIES Build all registered descriptive summary tables.

summaries = struct();
summaries.overall = summarize_local(plot_data, ...
    {'method_id','white_beamspace_snr_target_db'}, 'SNR_OVERALL');
summaries.profile = summarize_local(plot_data, ...
    {'method_id','white_beamspace_snr_target_db','profile_id'}, ...
    'SNR_PROFILE');
summaries.noise = summarize_local(plot_data, ...
    {'method_id','white_beamspace_snr_target_db','noise_profile_id'}, ...
    'SNR_NOISE');
summaries.snapshot = summarize_local(plot_data, ...
    {'method_id','white_beamspace_snr_target_db','L'}, 'SNR_SNAPSHOT');
summaries.exact = summarize_local(plot_data, ...
    {'method_id','white_beamspace_snr_target_db','noise_profile_id', ...
    'L','profile_id'}, 'EXACT_CELL');
summaries.applicability = summarize_local(plot_data, {'method_id'}, ...
    'METHOD_APPLICABILITY');
summaries.failure = failure_local(plot_data);
summaries.pairwise = pairwise_local(plot_data, constants);
summaries.complexity = complexity_local(plot_data);
summaries.eigenstructure = eigenstructure_local( ...
    diagnostics, plot_data);
end

function output = summarize_local(data, fields, scope)
keys = strings(height(data), 1);
for index = 1:numel(fields)
    keys = keys + "|" + string(data.(fields{index}));
end
[unique_keys, ~, groups] = unique(keys); %#ok<ASGLU>
rows = repmat(summary_template_local(), numel(unique_keys), 1);
for index = 1:numel(unique_keys)
    subset = data(groups == index, :);
    row = summary_template_local();
    row.summary_scope = string(scope);
    row.method_id = string(subset.method_id(1));
    if ismember('white_beamspace_snr_target_db', fields)
        row.white_beamspace_snr_target_db = ...
            double(subset.white_beamspace_snr_target_db(1));
    end
    if ismember('profile_id', fields)
        row.profile_id = string(subset.profile_id(1));
    end
    if ismember('noise_profile_id', fields)
        row.noise_profile_id = string(subset.noise_profile_id(1));
    end
    if ismember('L', fields)
        row.L = double(subset.L(1));
    end
    row.total_count = height(subset);
    row.applicable_count = nnz(subset.applicable);
    row.valid_count = nnz(subset.applicable & subset.fit_valid);
    row.structural_na_count = nnz(~subset.applicable);
    row.algorithmic_invalid_count = nnz(subset.applicable & ~subset.fit_valid);
    row.applicability_rate = ratio_local( ...
        row.applicable_count, row.total_count);
    row.valid_rate = ratio_local(row.valid_count, row.applicable_count);
    valid = subset.applicable & subset.fit_valid;
    metrics = {'joint_RMSE_deg','azimuth_RMSE_deg', ...
        'elevation_RMSE_deg','center_error_deg','axis_error_deg', ...
        'rho_error_deg','rho_relative_error','separation_vector_error_deg'};
    for metric_index = 1:numel(metrics)
        values = double(subset.(metrics{metric_index})(valid));
        values = values(isfinite(values));
        row.([metrics{metric_index}, '_median']) = median_or_nan_local(values);
        row.([metrics{metric_index}, '_p90']) = percentile_local(values, 90);
    end
    row.runtime_sec_median = median_or_nan_local( ...
        finite_local(double(subset.runtime_sec(subset.applicable))));
    row.runtime_sec_p90 = percentile_local( ...
        finite_local(double(subset.runtime_sec(subset.applicable))), 90);
    row.score_call_count_median = median_or_nan_local( ...
        finite_local(double(subset.score_call_count(subset.applicable))));
    row.SVD_call_count_median = median_or_nan_local( ...
        finite_local(double(subset.SVD_call_count(subset.applicable))));
    row.eig_call_count_median = median_or_nan_local( ...
        finite_local(double(subset.eig_call_count(subset.applicable))));
    if row.applicable_count == 0
        row.comparability_class = "STRUCTURAL_NA";
    elseif row.applicable_count >= 30 && row.valid_count >= 30 && ...
            row.valid_rate >= 0.5
        row.comparability_class = "ROBUSTLY_COMPARABLE";
    elseif row.valid_count > 0
        row.comparability_class = "APPLICABILITY_LIMITED";
    else
        row.comparability_class = "NO_VALID_OUTPUT";
    end
    rows(index) = row;
end
output = struct2table(rows);
output = sortrows(output, ...
    {'method_id','white_beamspace_snr_target_db','profile_id', ...
    'noise_profile_id','L'});
end

function output = failure_local(data)
keys = data.method_id + "|" + string(data.white_beamspace_snr_target_db) + ...
    "|" + data.applicability_status + "|" + data.fit_status + ...
    "|" + data.failure_stage;
[unique_keys, ~, groups] = unique(keys); %#ok<ASGLU>
rows = repmat(struct('method_id', "", ...
    'white_beamspace_snr_target_db', NaN, 'applicability_status', "", ...
    'fit_status', "", 'failure_stage', "", 'row_count', 0), ...
    numel(unique_keys), 1);
for index = 1:numel(unique_keys)
    subset = data(groups == index, :);
    rows(index) = struct('method_id', string(subset.method_id(1)), ...
        'white_beamspace_snr_target_db', ...
        double(subset.white_beamspace_snr_target_db(1)), ...
        'applicability_status', string(subset.applicability_status(1)), ...
        'fit_status', string(subset.fit_status(1)), ...
        'failure_stage', string(subset.failure_stage(1)), ...
        'row_count', height(subset));
end
output = sortrows(struct2table(rows), ...
    {'method_id','white_beamspace_snr_target_db','fit_status'});
end

function output = pairwise_local(data, constants)
methods = setdiff(constants.all_method_ids, "TANGENT_PROFILE_SAFE", 'stable');
rows = repmat(struct('method_id', "", ...
    'white_beamspace_snr_target_db', NaN, 'paired_valid_count', 0, ...
    'new_wins', 0, 'ties', 0, 'tangent_wins', 0, ...
    'delta_rmse_new_minus_tangent_median_deg', NaN), ...
    numel(methods) * numel(constants.white_snr_targets_db), 1);
row_index = 0;
for method_index = 1:numel(methods)
    for snr = constants.white_snr_targets_db
        row_index = row_index + 1;
        selected = sortrows(data(data.method_id == methods(method_index) & ...
            data.white_beamspace_snr_target_db == snr, :), ...
            'global_trial_index');
        tangent = sortrows(data(data.method_id == "TANGENT_PROFILE_SAFE" & ...
            data.white_beamspace_snr_target_db == snr, :), ...
            'global_trial_index');
        if height(selected) ~= height(tangent) || ...
                ~isequal(selected.trial_id, tangent.trial_id)
            error('stage8_k2_wacb_summaries:Pairing', ...
                'A method does not pair to Tangent by trial.');
        end
        valid = selected.applicable & selected.fit_valid & tangent.fit_valid;
        delta = double(selected.joint_RMSE_deg(valid) - ...
            tangent.joint_RMSE_deg(valid));
        tolerance = 1e-6;
        rows(row_index) = struct('method_id', methods(method_index), ...
            'white_beamspace_snr_target_db', snr, ...
            'paired_valid_count', numel(delta), ...
            'new_wins', nnz(delta < -tolerance), ...
            'ties', nnz(abs(delta) <= tolerance), ...
            'tangent_wins', nnz(delta > tolerance), ...
            'delta_rmse_new_minus_tangent_median_deg', ...
            median_or_nan_local(delta));
    end
end
output = struct2table(rows);
end

function output = complexity_local(data)
keys = data.method_id + "|" + string(data.white_beamspace_snr_target_db);
[unique_keys, ~, groups] = unique(keys); %#ok<ASGLU>
rows = repmat(struct('method_id', "", ...
    'white_beamspace_snr_target_db', NaN, 'applicable_count', 0, ...
    'runtime_sec_median', NaN, 'runtime_sec_p90', NaN, ...
    'score_call_count_median', NaN, 'SVD_call_count_median', NaN, ...
    'eig_call_count_median', NaN), numel(unique_keys), 1);
for index = 1:numel(unique_keys)
    subset = data(groups == index & data.applicable, :);
    source = data(groups == index, :);
    rows(index) = struct('method_id', string(source.method_id(1)), ...
        'white_beamspace_snr_target_db', ...
        double(source.white_beamspace_snr_target_db(1)), ...
        'applicable_count', height(subset), ...
        'runtime_sec_median', median_or_nan_local( ...
        finite_local(double(subset.runtime_sec))), ...
        'runtime_sec_p90', percentile_local( ...
        finite_local(double(subset.runtime_sec)), 90), ...
        'score_call_count_median', median_or_nan_local( ...
        finite_local(double(subset.score_call_count))), ...
        'SVD_call_count_median', median_or_nan_local( ...
        finite_local(double(subset.SVD_call_count))), ...
        'eig_call_count_median', median_or_nan_local( ...
        finite_local(double(subset.eig_call_count))));
end
output = sortrows(struct2table(rows), ...
    {'method_id','white_beamspace_snr_target_db'});
end

function output = eigenstructure_local(diagnostics, plot_data)
structured = diagnostics(diagnostics.method_id ~= "ELEMENT_MUSIC_K2", :);
keys = structured.method_id + "|" + ...
    string(structured.white_beamspace_snr_target_db);
[unique_keys, ~, groups] = unique(keys); %#ok<ASGLU>
rows = repmat(struct('method_id', "", ...
    'white_beamspace_snr_target_db', NaN, 'total_count', 0, ...
    'applicable_count', 0, 'elevation_valid_count', 0, ...
    'elevation_valid_rate', NaN, 'conditional_executed_count', 0, ...
    'conditional_valid_count', 0, 'conditional_valid_rate', NaN, ...
    'end_to_end_valid_count', 0, 'end_to_end_valid_rate', NaN, ...
    'raw_eigengap_median', NaN, 'fbss_eigengap_median', NaN, ...
    'registered_root_count_median', NaN), numel(unique_keys), 1);
for index = 1:numel(unique_keys)
    subset = structured(groups == index, :);
    applicable = subset.applicable;
    method_rows = plot_data(plot_data.method_id == subset.method_id(1) & ...
        plot_data.white_beamspace_snr_target_db == ...
        subset.white_beamspace_snr_target_db(1), :);
    rows(index) = struct('method_id', string(subset.method_id(1)), ...
        'white_beamspace_snr_target_db', ...
        double(subset.white_beamspace_snr_target_db(1)), ...
        'total_count', height(subset), 'applicable_count', nnz(applicable), ...
        'elevation_valid_count', nnz(applicable & subset.elevation_fit_valid), ...
        'elevation_valid_rate', ratio_local(nnz(applicable & ...
        subset.elevation_fit_valid), nnz(applicable)), ...
        'conditional_executed_count', nnz(applicable & ...
        subset.conditional_az_cml_executed), ...
        'conditional_valid_count', nnz(applicable & ...
        subset.conditional_az_cml_valid), ...
        'conditional_valid_rate', ratio_local(nnz(applicable & ...
        subset.conditional_az_cml_valid), nnz(applicable & ...
        subset.conditional_az_cml_executed)), ...
        'end_to_end_valid_count', nnz(method_rows.applicable & ...
        method_rows.fit_valid), ...
        'end_to_end_valid_rate', ratio_local(nnz(method_rows.applicable & ...
        method_rows.fit_valid), nnz(method_rows.applicable)), ...
        'raw_eigengap_median', median_or_nan_local(finite_local(double( ...
        subset.raw_signal_noise_eigengap(applicable)))), ...
        'fbss_eigengap_median', median_or_nan_local(finite_local(double( ...
        subset.fbss_signal_noise_eigengap(applicable)))), ...
        'registered_root_count_median', median_or_nan_local(finite_local( ...
        double(subset.registered_root_count(applicable)))));
end
output = sortrows(struct2table(rows), ...
    {'method_id','white_beamspace_snr_target_db'});
end

function row = summary_template_local()
row = struct('summary_scope', "", 'method_id', "", ...
    'white_beamspace_snr_target_db', NaN, 'profile_id', "ALL", ...
    'noise_profile_id', "ALL", 'L', NaN, 'total_count', 0, ...
    'applicable_count', 0, 'valid_count', 0, 'structural_na_count', 0, ...
    'algorithmic_invalid_count', 0, 'applicability_rate', NaN, ...
    'valid_rate', NaN, 'comparability_class', "", ...
    'joint_RMSE_deg_median', NaN, 'joint_RMSE_deg_p90', NaN, ...
    'azimuth_RMSE_deg_median', NaN, 'azimuth_RMSE_deg_p90', NaN, ...
    'elevation_RMSE_deg_median', NaN, 'elevation_RMSE_deg_p90', NaN, ...
    'center_error_deg_median', NaN, 'center_error_deg_p90', NaN, ...
    'axis_error_deg_median', NaN, 'axis_error_deg_p90', NaN, ...
    'rho_error_deg_median', NaN, 'rho_error_deg_p90', NaN, ...
    'rho_relative_error_median', NaN, 'rho_relative_error_p90', NaN, ...
    'separation_vector_error_deg_median', NaN, ...
    'separation_vector_error_deg_p90', NaN, ...
    'runtime_sec_median', NaN, 'runtime_sec_p90', NaN, ...
    'score_call_count_median', NaN, 'SVD_call_count_median', NaN, ...
    'eig_call_count_median', NaN);
end

function value = ratio_local(numerator, denominator)
if denominator == 0
    value = NaN;
else
    value = double(numerator) / double(denominator);
end
end

function values = finite_local(values)
values = values(isfinite(values));
end

function value = median_or_nan_local(values)
values = values(isfinite(values));
if isempty(values), value = NaN; else, value = median(values); end
end

function value = percentile_local(values, percentile)
values = sort(values(isfinite(values)));
if isempty(values)
    value = NaN;
    return;
end
position = 1 + (numel(values) - 1) * percentile / 100;
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    value = values(lower) + (position - lower) * ...
        (values(upper) - values(lower));
end
end
