function output = stage8_k2_wacb_fit_new_methods(fit_input, constants)
%STAGE8_K2_WACB_FIT_NEW_METHODS Call only frozen estimator interfaces.

if nargin < 2 || isempty(constants)
    constants = stage8_k2_wacb_constants();
end
forbidden = {'truth','truth_angles_deg','profile_id','profile_label', ...
    'tangent','tangent_result','core','core_result','full4d', ...
    'full4d_result','RMSE','joint_RMSE_deg','working_region_label', ...
    'k2_projected_snr','white_snr_target_db','other_method_estimates'};
present = intersect(fieldnames(fit_input), forbidden);
if ~isempty(present)
    error('stage8_k2_wacb_fit_new_methods:TruthIsolation', ...
        'Fit input contains prohibited field: %s', present{1});
end
required = {'Y_element','model','L','resource_entry','music_resources', ...
    'applicability'};
if ~isstruct(fit_input) || ~all(isfield(fit_input, required))
    error('stage8_k2_wacb_fit_new_methods:Input', ...
        'The data-only fit input is incomplete.');
end
rules = fit_input.applicability;
if ~isstruct(rules) || numel(rules) ~= numel(constants.method_ids)
    error('stage8_k2_wacb_fit_new_methods:Applicability', ...
        'Four structural applicability records are required.');
end
entry = fit_input.resource_entry;
if string(entry.noise_profile_id) ~= string(fit_input.model.noise_profile_id)
    error('stage8_k2_wacb_fit_new_methods:ModelIdentity', ...
        'Trial and resource noise models disagree.');
end
Y_white = entry.whitening.whitener * fit_input.Y_element;

music = stage8_k2_cb_music(Y_white, ...
    fit_input.music_resources.music_entry, fit_input.music_resources, ...
    'ELEMENT', double(fit_input.L), constants);
music.precompute_runtime_sec_amortized = ...
    fit_input.music_resources.standalone_precompute_runtime_sec / 560;
music.runtime_sec = music.online_runtime_sec + ...
    music.precompute_runtime_sec_amortized;

common = empty_common_local();
structured = repmat(empty_structured_local(""), 3, 1);
if any([rules(2:4).applicable])
    clock = tic;
    [R_vertical, vertical_info] = stage8_k2_sb_vertical_covariance( ...
        fit_input.Y_element, entry.noise_factors, constants);
    [R_fb, R_noise_subarray, fbss_info] = ...
        stage8_k2_sb_fbss_covariance(R_vertical, ...
        entry.noise_factors.R_el, constants);
    preprocess_runtime = toc(clock);
    raw_values = sort(real(eig(R_vertical)), 'descend');
    fb_values = sort(real(eig(R_fb)), 'descend');
    common = struct('executed', true, 'R_vertical', R_vertical, ...
        'R_fb', R_fb, 'R_noise_subarray', R_noise_subarray, ...
        'vertical_info', vertical_info, 'fbss_info', fbss_info, ...
        'raw_eigenvalues', raw_values, 'fbss_eigenvalues', fb_values, ...
        'raw_condition_proxy', condition_proxy_local(raw_values), ...
        'fbss_condition_proxy', condition_proxy_local(fb_values), ...
        'preprocess_runtime_sec', preprocess_runtime);
end

for index = 1:3
    method_id = constants.method_ids(index + 1);
    rule = rules(index + 1);
    if ~rule.applicable
        elevation = empty_elevation_local(method_id, rule.status);
        conditional = empty_conditional_local("NOT_RUN_STRUCTURAL_NA");
        combined = empty_combined_local(method_id, rule.status, false);
    else
        if method_id == "ELEMENT_VERTICAL_GFBSS_MUSIC_AZ_CML"
            elevation = stage8_k2_sb_gfbss_music(common.R_fb, ...
                common.R_noise_subarray, fit_input.model, constants);
        elseif method_id == "ELEMENT_VERTICAL_FBSS_ROOT_MUSIC_AZ_CML"
            elevation = stage8_k2_sb_root_music( ...
                common.R_fb, fit_input.model, constants);
        else
            elevation = stage8_k2_sb_ls_esprit( ...
                common.R_fb, fit_input.model, constants);
        end
        if elevation.fit_valid
            conditional = stage8_k2_sb_conditional_az_cml( ...
                Y_white, elevation.elevations_hat_deg, fit_input.model, ...
                entry.whitening, constants);
        else
            conditional = empty_conditional_local( ...
                "NOT_RUN_ELEVATION_INVALID");
        end
        combined = combine_local(method_id, elevation, conditional, ...
            common.preprocess_runtime_sec);
    end
    structured(index) = struct('method_id', method_id, ...
        'combined', combined, 'elevation', elevation, ...
        'conditional', conditional, 'rule', rule);
end
output = struct('element_music', music, 'structured', structured, ...
    'common', common, 'Y_element_white', Y_white, ...
    'truth_used_in_fit_flag', false, ...
    'profile_used_in_fit_flag', false, ...
    'tangent_used_in_start_flag', false, ...
    'core_used_in_start_flag', false, ...
    'full4d_used_in_start_flag', false);
end

function value = condition_proxy_local(values)
positive = values(values > max(size(values)) * ...
    eps(max(1, max(abs(values)))));
if isempty(positive)
    value = Inf;
else
    value = max(positive) / min(positive);
end
end

function combined = combine_local(method_id, elevation, conditional, preprocessing)
combined = empty_combined_local(method_id, "APPLICABLE", true);
combined.fit_valid = elevation.fit_valid && conditional.fit_valid;
if ~elevation.fit_valid
    combined.fit_status = elevation.fit_status;
    combined.failure_stage = "ELEVATION";
elseif ~conditional.fit_valid
    combined.fit_status = conditional.fit_status;
    combined.optimizer_status = conditional.optimizer_status;
    combined.failure_stage = "CONDITIONAL_AZIMUTH";
else
    combined.fit_status = "SUBSPACE_ELEVATION_AND_AZ_CML_VALID";
    combined.optimizer_status = conditional.optimizer_status;
    combined.angles_hat_deg = conditional.angles_hat_deg;
    combined.rss = conditional.rss;
    combined.loglik_concentrated = conditional.loglik_concentrated;
    combined.effective_rank = conditional.effective_rank;
    combined.selected_start_id = conditional.selected_start_id;
    combined.sweep_count = conditional.sweep_count;
    combined.failure_stage = "NONE";
end
combined.score_call_count = elevation.score_call_count + ...
    conditional.score_call_count;
combined.svd_call_count = elevation.svd_call_count + ...
    conditional.svd_call_count;
combined.eig_call_count = elevation.eig_call_count + ...
    conditional.eig_call_count;
combined.preprocess_runtime_sec = preprocessing;
combined.elevation_runtime_sec = elevation.runtime_sec;
combined.conditional_az_runtime_sec = conditional.runtime_sec;
combined.runtime_sec = preprocessing + elevation.runtime_sec + ...
    conditional.runtime_sec;
combined.online_runtime_sec = combined.runtime_sec;
combined.coarse_candidate_count = conditional.coarse_candidate_count;
combined.continuous_start_count = conditional.continuous_start_count;
if isfield(elevation, 'local_peak_count')
    combined.local_peak_count = elevation.local_peak_count;
elseif isfield(elevation, 'registered_root_count')
    combined.local_peak_count = elevation.registered_root_count;
else
    combined.local_peak_count = double(elevation.fit_valid) * 2;
end
end

function combined = empty_combined_local(method_id, status, applicable)
combined = struct('method_id', method_id, ...
    'observation_domain', "ELEMENT", 'applicable', logical(applicable), ...
    'applicability_status', string(status), 'fit_valid', false, ...
    'fit_status', string(status), 'optimizer_status', "NOT_RUN", ...
    'failure_stage', "STRUCTURAL_NA", 'selected_source', method_id, ...
    'selected_start_id', "", 'angles_hat_deg', NaN(2, 2), ...
    'rss', NaN, 'loglik_concentrated', NaN, 'effective_rank', 0, ...
    'score_call_count', 0, 'svd_call_count', 0, 'eig_call_count', 0, ...
    'runtime_sec', 0, 'online_runtime_sec', 0, ...
    'precompute_runtime_sec_amortized', 0, ...
    'preprocess_runtime_sec', 0, 'elevation_runtime_sec', 0, ...
    'conditional_az_runtime_sec', 0, 'coarse_candidate_count', 0, ...
    'continuous_start_count', 0, 'sweep_count', 0, ...
    'local_peak_count', 0, 'truth_used_in_fit_flag', false, ...
    'profile_used_in_fit_flag', false, ...
    'tangent_used_in_start_flag', false, ...
    'core_used_in_start_flag', false, ...
    'full4d_used_in_start_flag', false, ...
    'full_manifold_used_flag', true);
end

function elevation = empty_elevation_local(method_id, status)
elevation = struct('method_id', method_id, 'applicable', false, ...
    'applicability_status', string(status), 'fit_valid', false, ...
    'fit_status', string(status), 'elevations_hat_deg', [NaN, NaN], ...
    'selection_values', [NaN, NaN], 'score_call_count', 0, ...
    'svd_call_count', 0, 'eig_call_count', 0, 'runtime_sec', 0);
end

function conditional = empty_conditional_local(status)
conditional = struct('fit_valid', false, 'fit_status', string(status), ...
    'optimizer_status', string(status), 'angles_hat_deg', NaN(2, 2), ...
    'rss', NaN, 'loglik_concentrated', NaN, 'effective_rank', 0, ...
    'selected_start_id', "", 'sweep_count', 0, ...
    'score_call_count', 0, 'svd_call_count', 0, ...
    'eig_call_count', 0, 'runtime_sec', 0, ...
    'coarse_candidate_count', 0, 'continuous_start_count', 0);
end

function common = empty_common_local()
common = struct('executed', false, 'R_vertical', [], 'R_fb', [], ...
    'R_noise_subarray', [], 'vertical_info', struct(), ...
    'fbss_info', struct(), 'raw_eigenvalues', [], ...
    'fbss_eigenvalues', [], 'raw_condition_proxy', NaN, ...
    'fbss_condition_proxy', NaN, 'preprocess_runtime_sec', 0);
end

function item = empty_structured_local(method_id)
status = "NOT_RUN";
item = struct('method_id', string(method_id), ...
    'combined', empty_combined_local(string(method_id), status, false), ...
    'elevation', empty_elevation_local(string(method_id), status), ...
    'conditional', empty_conditional_local(status), ...
    'rule', struct('applicable', false, 'status', status, ...
    'uses_registered_scenario_flag', false));
end
