function evidence = stage8_k2_wacb_load_evidence46(repo_dir, constants)
%STAGE8_K2_WACB_LOAD_EVIDENCE46 Load and verify immutable evidence 46.

if nargin < 2 || isempty(constants)
    constants = stage8_k2_wacb_constants();
end
root = fullfile(repo_dir, 'innovation-mining');
manifest_path = fullfile(root, ...
    '46_stage8_k2_white_snr_classical_baseline_runtime_manifest.json');
results_path = fullfile(root, ...
    '46_stage8_k2_white_snr_classical_baseline_results.csv');
audit_path = fullfile(root, ...
    '46_stage8_k2_white_snr_classical_baseline_registry_audit.csv');
if ~isfile(manifest_path) || ~isfile(results_path) || ~isfile(audit_path)
    error('stage8_k2_wacb_load_evidence46:Missing', ...
        'A required evidence-46 file is missing.');
end
manifest_hash = stage8_k2_wacb_file_sha256(manifest_path);
if ~strcmpi(manifest_hash, constants.evidence46_manifest_sha256)
    error('stage8_k2_wacb_load_evidence46:ManifestIdentity', ...
        'The evidence-46 manifest SHA-256 changed.');
end
manifest = jsondecode(fileread(manifest_path));
required = {'status','independent_audit_status','baseline_row_count', ...
    'checkpoint_count','registry_count','truth_leakage_count', ...
    'profile_leakage_count','tangent_start_count','core_start_count', ...
    'independent_reconstruction_match_count', ...
    'independent_artifact_hash_match_count', ...
    'independent_baseline_rerun_count','artifacts','merge_back'};
if ~all(isfield(manifest, required)) || ...
        ~strcmp(manifest.status, ...
        'STAGE8_K2_WHITE_SNR_CLASSICAL_BASELINE_COMPARISON_COMPLETE') || ...
        ~strcmp(manifest.independent_audit_status, 'PASS') || ...
        manifest.registry_count ~= constants.trial_count || ...
        manifest.baseline_row_count ~= 5040 || ...
        manifest.checkpoint_count ~= constants.trial_count || ...
        manifest.truth_leakage_count ~= 0 || ...
        manifest.profile_leakage_count ~= 0 || ...
        manifest.tangent_start_count ~= 0 || manifest.core_start_count ~= 0 || ...
        manifest.independent_reconstruction_match_count ~= ...
        constants.trial_count || ...
        manifest.independent_artifact_hash_match_count ~= ...
        constants.evidence46_artifact_count || ...
        manifest.independent_baseline_rerun_count ~= 0 || ...
        logical(manifest.merge_back) || ...
        numel(manifest.artifacts) ~= constants.evidence46_artifact_count
    error('stage8_k2_wacb_load_evidence46:ManifestStatus', ...
        'Evidence 46 is not the independently audited completed bundle.');
end

artifact_ids = strings(numel(manifest.artifacts), 1);
artifact_paths = strings(numel(manifest.artifacts), 1);
artifact_hashes = strings(numel(manifest.artifacts), 1);
for index = 1:numel(manifest.artifacts)
    artifact = manifest.artifacts(index);
    path_now = fullfile(repo_dir, strrep(artifact.path, '/', filesep));
    if ~isfile(path_now)
        error('stage8_k2_wacb_load_evidence46:ArtifactMissing', ...
            'Evidence-46 artifact is missing: %s', artifact.path);
    end
    actual = stage8_k2_wacb_file_sha256(path_now);
    if ~strcmpi(actual, artifact.sha256)
        error('stage8_k2_wacb_load_evidence46:ArtifactHash', ...
            'Evidence-46 SHA-256 mismatch: %s', artifact.path);
    end
    artifact_ids(index) = string(artifact.artifact_id);
    artifact_paths(index) = string(artifact.path);
    artifact_hashes(index) = string(lower(actual));
end
rows = readtable(results_path, 'TextType', 'string');
audit = readtable(audit_path, 'TextType', 'string');
required_rows = {'global_trial_index','trial_id','element_trial_hash', ...
    'measurement_hash','method_id','fit_valid','fit_status', ...
    'truth_used_in_fit_flag','profile_used_in_fit_flag', ...
    'tangent_used_in_start_flag','core_used_in_start_flag'};
if height(rows) ~= 5040 || height(audit) ~= constants.trial_count || ...
        ~all(ismember(required_rows, rows.Properties.VariableNames)) || ...
        numel(unique(rows.trial_id + "|" + rows.method_id)) ~= 5040 || ...
        any(rows.truth_used_in_fit_flag) || any(rows.profile_used_in_fit_flag) || ...
        any(rows.tangent_used_in_start_flag) || any(rows.core_used_in_start_flag) || ...
        any(~logical(audit.checkpoint_valid))
    error('stage8_k2_wacb_load_evidence46:TableIntegrity', ...
        'Evidence-46 rows or registry audit failed integrity checks.');
end
evidence_identity = stage8_k2_wacb_stable_hash('EVIDENCE_46', ...
    manifest_hash, artifact_ids, artifact_paths, artifact_hashes);
evidence = struct('manifest', manifest, 'manifest_path', manifest_path, ...
    'manifest_sha256', string(manifest_hash), 'results', rows, ...
    'registry_audit', audit, 'artifact_ids', artifact_ids, ...
    'artifact_paths', artifact_paths, 'artifact_sha256', artifact_hashes, ...
    'identity', string(evidence_identity));
end
