function audit = stage8_k2_wacb_checkpoint_validate( ...
    path_now, expected_spec, context, registry_hash)
%STAGE8_K2_WACB_CHECKPOINT_VALIDATE Validate final or temporary checkpoint.

required = {'protocol','checkpoint_contract_version', ...
    'evidence44_registry_row','registry_row','trial_identity', ...
    'new_method_rows','diagnostic_rows','representative_spectrum', ...
    'scientific_hash','code_identity','registry_hash','completed_utc', ...
    'runtime_sec','completion_status'};
if ~isfile(path_now)
    error('stage8_k2_wacb_checkpoint_validate:Missing', ...
        'Checkpoint is missing: %s', path_now);
end
loaded = load(path_now, 'checkpoint', '-mat');
if ~isfield(loaded, 'checkpoint') || ~isstruct(loaded.checkpoint) || ...
        ~isscalar(loaded.checkpoint) || ...
        ~all(isfield(loaded.checkpoint, required))
    error('stage8_k2_wacb_checkpoint_validate:Schema', ...
        'Checkpoint schema is invalid: %s', path_now);
end
checkpoint = loaded.checkpoint;
constants = context.constants;
if ~strcmp(checkpoint.protocol, constants.protocol) || ...
        ~strcmp(checkpoint.checkpoint_contract_version, ...
        constants.checkpoint_contract_version) || ...
        ~strcmp(checkpoint.completion_status, 'COMPLETE') || ...
        ~strcmp(checkpoint.code_identity, context.code_identity.tree_hash) || ...
        ~strcmp(checkpoint.registry_hash, registry_hash)
    error('stage8_k2_wacb_checkpoint_validate:Identity', ...
        'Checkpoint protocol, code, registry, or status is invalid.');
end
if ~(istable(checkpoint.registry_row) && ...
        height(checkpoint.registry_row) == 1) || ...
        ~strcmp(stage8_k2_wacb_stable_hash( ...
        'REGISTRY_ROW', checkpoint.registry_row), ...
        stage8_k2_wacb_stable_hash('REGISTRY_ROW', expected_spec))
    error('stage8_k2_wacb_checkpoint_validate:RegistryRow', ...
        'Checkpoint registry row differs from the frozen registry.');
end
expected_evidence = context.evidence44.registry( ...
    context.evidence44.registry.trial_id == expected_spec.trial_id, :);
if height(expected_evidence) ~= 1 || ...
        ~strcmp(stage8_k2_wacb_stable_hash( ...
        'EVIDENCE44_ROW', checkpoint.evidence44_registry_row), ...
        stage8_k2_wacb_stable_hash('EVIDENCE44_ROW', expected_evidence))
    error('stage8_k2_wacb_checkpoint_validate:EvidenceRow', ...
        'Checkpoint evidence-44 row changed.');
end
rows = checkpoint.new_method_rows;
diagnostics = checkpoint.diagnostic_rows;
if ~(istable(rows) && height(rows) == 4 && ...
        istable(diagnostics) && height(diagnostics) == 4) || ...
        any(rows.trial_id ~= expected_spec.trial_id) || ...
        any(diagnostics.trial_id ~= expected_spec.trial_id) || ...
        ~isequal(sort(rows.method_id), sort(constants.method_ids)) || ...
        ~isequal(sort(diagnostics.method_id), sort(constants.method_ids)) || ...
        any(rows.element_trial_hash ~= expected_spec.element_trial_hash) || ...
        any(rows.measurement_hash ~= expected_spec.measurement_hash) || ...
        any(diagnostics.element_trial_hash ~= expected_spec.element_trial_hash)
    error('stage8_k2_wacb_checkpoint_validate:Rows', ...
        'Checkpoint result or diagnostic rows do not match the trial.');
end
identity = checkpoint.trial_identity;
if ~isstruct(identity) || string(identity.trial_id) ~= expected_spec.trial_id || ...
        string(identity.element_trial_hash) ~= ...
        expected_spec.element_trial_hash || ...
        string(identity.measurement_hash) ~= expected_spec.measurement_hash || ...
        double(identity.source_seed) ~= double(expected_spec.source_seed) || ...
        double(identity.noise_seed) ~= double(expected_spec.noise_seed) || ...
        double(identity.white_target_error_db) > constants.snr_db_tolerance
    error('stage8_k2_wacb_checkpoint_validate:TrialIdentity', ...
        'Reconstructed trial identity failed.');
end
expected_applicable = [ ...
    logical(expected_spec.element_music_applicable_flag); ...
    logical(expected_spec.gfbss_applicable_flag); ...
    logical(expected_spec.root_applicable_flag); ...
    logical(expected_spec.esprit_applicable_flag)];
for index = 1:numel(constants.method_ids)
    row = rows(rows.method_id == constants.method_ids(index), :);
    if logical(row.applicable) ~= expected_applicable(index)
        error('stage8_k2_wacb_checkpoint_validate:Applicability', ...
            'A method applicability flag changed.');
    end
end
if any(rows.fit_status == "NOT_RUN") || ...
        any(rows.truth_used_in_fit_flag) || ...
        any(rows.profile_used_in_fit_flag) || ...
        any(rows.tangent_used_in_start_flag) || ...
        any(rows.core_used_in_start_flag) || ...
        any(rows.full4d_used_in_start_flag) || ...
        any(diagnostics.truth_used_in_fit_flag) || ...
        any(diagnostics.profile_used_in_fit_flag)
    error('stage8_k2_wacb_checkpoint_validate:Isolation', ...
        'Outcome or fit-isolation integrity failed.');
end
valid = rows.fit_valid;
if any(valid & ~isfinite(rows.joint_RMSE_deg)) || ...
        any(valid & strlength(rows.angles_hat_deg) == 0) || ...
        logical(checkpoint.representative_spectrum.included) ~= ...
        logical(expected_spec.representative_spectrum_flag)
    error('stage8_k2_wacb_checkpoint_validate:Metrics', ...
        'A valid row or representative marker is inconsistent.');
end
actual_hash = stage8_k2_wacb_checkpoint_hash(checkpoint);
if ~strcmp(actual_hash, checkpoint.scientific_hash)
    error('stage8_k2_wacb_checkpoint_validate:ScientificHash', ...
        'Checkpoint scientific hash is invalid.');
end
audit = struct('pass', true, 'path', string(path_now), ...
    'trial_id', string(expected_spec.trial_id), ...
    'scientific_hash', string(actual_hash), ...
    'runtime_sec', double(checkpoint.runtime_sec), ...
    'white_target_error_db', double(identity.white_target_error_db));
end
