function status = stage8_k2_wacb_status_write( ...
    runtime_root, registry, progress, current_spec, constants, stage)
%STAGE8_K2_WACB_STATUS_WRITE Atomically publish scientific progress.

values = progress.runtime_sec(isfinite(progress.runtime_sec));
if isempty(values)
    median_trial = NaN;
    elapsed = 0;
    eta = NaN;
else
    median_trial = median(values);
    elapsed = sum(values);
    eta = median_trial * (height(registry) - progress.completed_count);
end
if isempty(current_spec)
    current = struct('trial_id', "NONE", 'snr', NaN, 'noise', "NONE", ...
        'L', NaN, 'profile', "NONE", 'replicate', NaN);
else
    current = struct('trial_id', string(current_spec.trial_id), ...
        'snr', double(current_spec.white_beamspace_snr_target_db), ...
        'noise', string(current_spec.noise_profile_id), ...
        'L', double(current_spec.L), ...
        'profile', string(current_spec.profile_id), ...
        'replicate', double(current_spec.replicate_id));
end
status = struct('protocol', constants.protocol, 'stage', char(stage), ...
    'completed', progress.completed_count, 'total', height(registry), ...
    'remaining', height(registry) - progress.completed_count, ...
    'current_trial', char(current.trial_id), ...
    'current_noise', char(current.noise), 'current_snr_db', current.snr, ...
    'current_L', current.L, 'current_profile', char(current.profile), ...
    'current_replicate', current.replicate, ...
    'elapsed_active_sec', elapsed, 'median_trial_sec', median_trial, ...
    'eta_sec', eta, ...
    'element_music_valid_count', progress.element_music_valid_count, ...
    'element_music_single_peak_count', ...
    progress.element_music_single_peak_count, ...
    'element_music_na_count', progress.element_music_na_count, ...
    'gfbss_elevation_valid_count', progress.gfbss_elevation_valid_count, ...
    'gfbss_end_to_end_valid_count', ...
    progress.gfbss_end_to_end_valid_count, ...
    'root_elevation_valid_count', progress.root_elevation_valid_count, ...
    'root_end_to_end_valid_count', progress.root_end_to_end_valid_count, ...
    'esprit_elevation_valid_count', progress.esprit_elevation_valid_count, ...
    'esprit_end_to_end_valid_count', ...
    progress.esprit_end_to_end_valid_count, ...
    'conditional_az_cml_valid_count', ...
    progress.conditional_az_cml_valid_count, ...
    'last_update_utc', stage8_k2_mc_utc_now());
stage8_k2_wacb_write_json_atomic(fullfile(runtime_root, 'status', ...
    'latest_status.json'), status);
text_now = sprintf([ ...
    'Stage: %s\nCompleted: %d / %d\nRemaining: %d\n', ...
    'Current trial: %s\nCurrent noise/SNR/L/profile/replicate: ', ...
    '%s / %g / %g / %s / %g\nElapsed active sec: %.6f\n', ...
    'Median trial sec: %.6f\nETA sec: %.6f\n', ...
    'Element MUSIC valid/single-peak/N-A: %d / %d / %d\n', ...
    'GFBSS elevation/end-to-end valid: %d / %d\n', ...
    'Root elevation/end-to-end valid: %d / %d\n', ...
    'ESPRIT elevation/end-to-end valid: %d / %d\n', ...
    'Conditional az CML valid: %d\nLast update UTC: %s\n'], ...
    char(stage), progress.completed_count, height(registry), ...
    height(registry) - progress.completed_count, char(current.trial_id), ...
    char(current.noise), current.snr, current.L, char(current.profile), ...
    current.replicate, elapsed, median_trial, eta, ...
    progress.element_music_valid_count, ...
    progress.element_music_single_peak_count, ...
    progress.element_music_na_count, progress.gfbss_elevation_valid_count, ...
    progress.gfbss_end_to_end_valid_count, ...
    progress.root_elevation_valid_count, ...
    progress.root_end_to_end_valid_count, ...
    progress.esprit_elevation_valid_count, ...
    progress.esprit_end_to_end_valid_count, ...
    progress.conditional_az_cml_valid_count, status.last_update_utc);
stage8_k2_wacb_write_text_atomic(fullfile(runtime_root, 'status', ...
    'latest_status.txt'), text_now);
end
