function plot_data = stage8_k2_wacb_build_plot_data(merged, context)
%STAGE8_K2_WACB_BUILD_PLOT_DATA Normalize read-only 44/46 plus new rows.

constants = context.constants;
sources = {context.evidence44.method_rows, ...
    context.evidence46.results, merged.new_rows};
blocks = cell(3, 1);
for source_index = 1:3
    source = sources{source_index};
    normalized = repmat(template_local(), height(source), 1);
    for index = 1:height(source)
        item = source(index, :);
        trial_id = string(item.trial_id);
        registry = context.evidence44.registry( ...
            context.evidence44.registry.trial_id == trial_id, :);
        snr = context.evidence44.snr_rows( ...
            context.evidence44.snr_rows.trial_id == trial_id, :);
        if height(registry) ~= 1 || height(snr) ~= 1
            error('stage8_k2_wacb_build_plot_data:Pairing', ...
                'An input row does not pair to evidence 44.');
        end
        row = template_local();
        row.trial_id = trial_id;
        row.global_trial_index = double(registry.global_trial_index);
        row.element_trial_hash = string(registry.element_trial_hash);
        row.measurement_hash = string(registry.measurement_hash);
        row.method_id = string(item.method_id);
        [row.method_family, row.observation_domain, row.comparison_tier, ...
            row.same_hardware_interface_to_tangent] = ...
            labels_local(row.method_id);
        row.white_beamspace_snr_target_db = ...
            double(registry.white_beamspace_snr_target_db);
        row.noise_profile_id = string(registry.noise_profile_id);
        row.L = double(registry.L);
        row.profile_id = string(registry.profile_id);
        row.replicate_id = double(registry.replicate_id);
        row.base_realization_index = double(registry.base_realization_index);
        snr_names = {'element_snr_expected_db','element_snr_realized_db', ...
            'raw_beam_snr_expected_db','raw_beam_snr_realized_db', ...
            'white_beam_snr_expected_db','white_beam_snr_realized_db', ...
            'k2_projected_snr_expected_db','k2_projected_snr_realized_db'};
        for name_index = 1:numel(snr_names)
            row.(snr_names{name_index}) = double(snr.(snr_names{name_index}));
        end
        row.applicable = logical(table_value_local(item, 'applicable', true));
        row.applicability_status = string(table_value_local(item, ...
            'applicability_status', 'APPLICABLE'));
        row.fit_valid = logical(table_value_local(item, 'fit_valid', false));
        row.fit_status = string(table_value_local(item, 'fit_status', ''));
        row.failure_stage = string(table_value_local(item, 'failure_stage', ...
            default_failure_local(row)));
        row.angles_hat_deg = string(table_value_local(item, ...
            'angles_hat_deg', '[NaN NaN;NaN NaN]'));
        metrics = {'joint_RMSE_deg','azimuth_RMSE_deg', ...
            'elevation_RMSE_deg','center_error_deg','rho_error_deg', ...
            'rho_relative_error','separation_vector_error_deg', ...
            'runtime_sec','score_call_count','eig_call_count'};
        for name_index = 1:numel(metrics)
            row.(metrics{name_index}) = double(table_value_local( ...
                item, metrics{name_index}, NaN));
        end
        row.axis_error_deg = double(table_value_local(item, ...
            'axis_error_deg', table_value_local(item, ...
            'direction_axis_error_deg', NaN)));
        row.SVD_call_count = double(table_value_local(item, ...
            'SVD_call_count', table_value_local(item, 'svd_call_count', 0)));
        row.local_peak_count = double(table_value_local(item, ...
            'local_peak_count', 0));
        row.truth_used_in_fit_flag = logical(table_value_local(item, ...
            'truth_used_in_fit_flag', false));
        row.profile_used_in_fit_flag = logical(table_value_local(item, ...
            'profile_used_in_fit_flag', false));
        row.tangent_used_in_start_flag = logical(table_value_local(item, ...
            'tangent_used_in_start_flag', false));
        row.core_used_in_start_flag = logical(table_value_local(item, ...
            'core_used_in_start_flag', false));
        row.full4d_used_in_start_flag = logical(table_value_local(item, ...
            'full4d_used_in_start_flag', false));
        if source_index == 3
            diagnostic = merged.diagnostics( ...
                merged.diagnostics.trial_id == trial_id & ...
                merged.diagnostics.method_id == row.method_id, :);
            row.elevation_fit_valid = logical( ...
                diagnostic.elevation_fit_valid);
            row.elevation_fit_status = string( ...
                diagnostic.elevation_fit_status);
            row.conditional_az_cml_valid = logical( ...
                diagnostic.conditional_az_cml_valid);
            row.conditional_az_cml_status = string( ...
                diagnostic.conditional_az_cml_status);
            row.registered_root_count = double( ...
                diagnostic.registered_root_count);
        end
        normalized(index) = row;
    end
    blocks{source_index} = struct2table(normalized);
end
plot_data = sortrows(vertcat(blocks{:}), ...
    {'global_trial_index','method_id'});
if height(plot_data) ~= constants.all_method_row_count || ...
        numel(unique(plot_data.trial_id)) ~= constants.trial_count || ...
        numel(unique(plot_data.trial_id + "|" + plot_data.method_id)) ~= ...
        constants.all_method_row_count || ...
        any(plot_data.truth_used_in_fit_flag)
    error('stage8_k2_wacb_build_plot_data:Integrity', ...
        'The unified 16800-row table failed identity or isolation.');
end
for index = 1:constants.trial_count
    selected = plot_data.global_trial_index == index;
    if nnz(selected) ~= 10 || ...
            ~isequal(sort(plot_data.method_id(selected)), ...
            sort(constants.all_method_ids))
        error('stage8_k2_wacb_build_plot_data:Multiplicity', ...
            'A trial does not contain exactly the registered ten methods.');
    end
end
end

function row = template_local()
row = struct('trial_id', "", 'global_trial_index', 0, ...
    'element_trial_hash', "", 'measurement_hash', "", 'method_id', "", ...
    'method_family', "", 'observation_domain', "", ...
    'comparison_tier', "", 'same_hardware_interface_to_tangent', false, ...
    'white_beamspace_snr_target_db', NaN, ...
    'element_snr_expected_db', NaN, 'element_snr_realized_db', NaN, ...
    'raw_beam_snr_expected_db', NaN, 'raw_beam_snr_realized_db', NaN, ...
    'white_beam_snr_expected_db', NaN, ...
    'white_beam_snr_realized_db', NaN, ...
    'k2_projected_snr_expected_db', NaN, ...
    'k2_projected_snr_realized_db', NaN, ...
    'noise_profile_id', "", 'L', 0, 'profile_id', "", ...
    'replicate_id', 0, 'base_realization_index', 0, ...
    'applicable', false, 'applicability_status', "NOT_RUN", ...
    'fit_valid', false, 'fit_status', "NOT_RUN", ...
    'failure_stage', "NOT_RUN", 'angles_hat_deg', "", ...
    'joint_RMSE_deg', NaN, 'azimuth_RMSE_deg', NaN, ...
    'elevation_RMSE_deg', NaN, 'center_error_deg', NaN, ...
    'axis_error_deg', NaN, 'rho_error_deg', NaN, ...
    'rho_relative_error', NaN, 'separation_vector_error_deg', NaN, ...
    'runtime_sec', NaN, 'score_call_count', 0, 'SVD_call_count', 0, ...
    'eig_call_count', 0, 'local_peak_count', 0, ...
    'elevation_fit_valid', false, 'elevation_fit_status', "NOT_APPLICABLE", ...
    'conditional_az_cml_valid', false, ...
    'conditional_az_cml_status', "NOT_APPLICABLE", ...
    'registered_root_count', 0, 'truth_used_in_fit_flag', false, ...
    'profile_used_in_fit_flag', false, 'tangent_used_in_start_flag', false, ...
    'core_used_in_start_flag', false, 'full4d_used_in_start_flag', false);
end

function [family, domain, tier, same] = labels_local(method)
if ismember(method, ["CORE_LITE","CORE_PLUS","TANGENT_PROFILE_SAFE", ...
        "FULL4D_BEAMSPACE_CML_MULTISTART","BEAMSPACE_MUSIC_K2"])
    tier = "TIER_A_WHITE_SEQUENTIAL_BEAMSPACE";
    domain = "BEAMSPACE";
    same = true;
elseif ismember(method, ["FULL4D_ELEMENT_CML_MULTISTART", ...
        "ELEMENT_MUSIC_K2"])
    tier = "TIER_B_FULL_ELEMENT_2D_MANIFOLD";
    domain = "ELEMENT";
    same = false;
else
    tier = "TIER_C_VERTICAL_ULA_PLUS_AZ_CML";
    domain = "ELEMENT";
    same = false;
end
if contains(method, "MUSIC")
    family = "MUSIC";
elseif contains(method, "ESPRIT")
    family = "ESPRIT_PLUS_AZ_CML";
elseif contains(method, "ROOT")
    family = "ROOT_MUSIC_PLUS_AZ_CML";
elseif contains(method, "CML")
    family = "CML";
else
    family = "REGISTERED_STAGE8";
end
end

function value = table_value_local(row, name, default)
if ismember(name, row.Properties.VariableNames)
    value = row.(name);
else
    value = default;
end
end

function value = default_failure_local(row)
if ~row.applicable
    value = "STRUCTURAL_NA";
elseif row.fit_valid
    value = "NONE";
else
    value = "ALGORITHM_INVALID";
end
end
