function resources = stage8_k2_wacb_prepare_noise_resources(context, noise_id)
%STAGE8_K2_WACB_PREPARE_NOISE_RESOURCES Build one element MUSIC dictionary.

constants = context.constants;
noise_id = string(noise_id);
entry_index = find([context.models.noise_profile_id] == noise_id, 1);
if isempty(entry_index)
    error('stage8_k2_wacb_prepare_noise_resources:Noise', ...
        'Unknown registered noise profile.');
end
source = context.models(entry_index);
domain = context.plan.local_domain.domain_bounds_deg;
az_grid = exact_axis_local(domain(1), domain(2), ...
    constants.music_grid_step_deg);
el_grid = exact_axis_local(domain(3), domain(4), ...
    constants.music_grid_step_deg);
[az_mesh, el_mesh] = ndgrid(az_grid, el_grid);
points = [az_mesh(:), el_mesh(:)];
clock = tic;
physical = build_stage8_element_manifold(points, source.model);
A_element_white = source.whitening.whitener * physical.A;
precompute_runtime = toc(clock);
music_entry = struct('noise_profile_id', noise_id, ...
    'model', source.model, 'whitening', source.whitening, ...
    'A_element_white', A_element_white, ...
    'G_beamspace', complex(zeros(0, size(A_element_white, 2))), ...
    'physical_dictionary_runtime_sec', precompute_runtime, ...
    'transform_runtime_sec', 0, ...
    'standalone_precompute_runtime_sec', precompute_runtime);
structured_entry = struct('noise_profile_id', noise_id, ...
    'model', source.model, 'noise_factors', source.noise_factors, ...
    'whitening', source.whitening, ...
    'precompute_runtime_sec', 0);
resources = struct('noise_profile_id', noise_id, ...
    'az_grid_deg', az_grid, 'el_grid_deg', el_grid, ...
    'grid_points_deg', points, 'grid_size', size(az_mesh), ...
    'grid_point_count', size(points, 1), 'entries', music_entry, ...
    'music_entry', music_entry, 'structured_entry', structured_entry, ...
    'standalone_precompute_runtime_sec', precompute_runtime, ...
    'truth_used_in_precompute_flag', false, ...
    'profile_used_in_precompute_flag', false);
end

function axis = exact_axis_local(lower, upper, step)
count = round((upper - lower) / step);
axis = lower + (0:count) * step;
axis(end) = upper;
if abs(axis(1) - lower) > 1e-12 || abs(axis(end) - upper) > 1e-12
    error('stage8_k2_wacb_prepare_noise_resources:Grid', ...
        'The fixed MUSIC grid does not cover the frozen domain.');
end
end
