function [checkpoint, path_now] = stage8_k2_wacb_checkpoint_write( ...
    runtime_root, spec, identity, rows, diagnostics, representative, ...
    context, registry_hash, runtime_sec)
%STAGE8_K2_WACB_CHECKPOINT_WRITE Validate and atomically commit one trial.

path_now = stage8_k2_wacb_checkpoint_path(runtime_root, spec);
if isfile(path_now)
    error('stage8_k2_wacb_checkpoint_write:Exists', ...
        'A final checkpoint already exists: %s', path_now);
end
temporary = [path_now, '.tmp'];
if isfile(temporary)
    delete(temporary);
end
evidence_row = context.evidence44.registry( ...
    context.evidence44.registry.trial_id == spec.trial_id, :);
if height(evidence_row) ~= 1
    error('stage8_k2_wacb_checkpoint_write:EvidenceRow', ...
        'The immutable evidence-44 registry row is not unique.');
end
checkpoint = struct('protocol', context.constants.protocol, ...
    'checkpoint_contract_version', ...
    context.constants.checkpoint_contract_version, ...
    'evidence44_registry_row', evidence_row, 'registry_row', spec, ...
    'trial_identity', identity, 'new_method_rows', rows, ...
    'diagnostic_rows', diagnostics, ...
    'representative_spectrum', representative, ...
    'scientific_hash', '', ...
    'code_identity', context.code_identity.tree_hash, ...
    'registry_hash', registry_hash, ...
    'completed_utc', stage8_k2_mc_utc_now(), ...
    'runtime_sec', double(runtime_sec), 'completion_status', 'COMPLETE');
checkpoint.scientific_hash = stage8_k2_wacb_checkpoint_hash(checkpoint);
save(temporary, 'checkpoint', '-mat');
stage8_k2_wacb_checkpoint_validate( ...
    temporary, spec, context, registry_hash);
[ok, message] = movefile(temporary, path_now);
if ~ok
    error('stage8_k2_wacb_checkpoint_write:Move', '%s', message);
end
stage8_k2_wacb_checkpoint_validate(path_now, spec, context, registry_hash);
end
