function context = stage8_k2_wacb_build_context(repo_dir)
%STAGE8_K2_WACB_BUILD_CONTEXT Bind frozen trials, evidence, and models.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_wacb_build_context:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
constants = stage8_k2_wacb_constants();
mc_context = stage8_k2_mc_build_context(repo_dir);
cb_context = stage8_k2_cb_build_context(repo_dir);
evidence44 = stage8_k2_wacb_load_evidence44(repo_dir, constants);
evidence46 = stage8_k2_wacb_load_evidence46(repo_dir, constants);
code_identity = stage8_k2_wacb_code_identity(repo_dir);
if ~isequal(mc_context.plan.local_domain.domain_bounds_deg, ...
        cb_context.plan.local_domain.domain_bounds_deg) || ...
        ~strcmp(mc_context.plan.stage8_measurement_plan_hash, ...
        cb_context.plan.stage8_measurement_plan_hash) || ...
        ~isequal(mc_context.constants.white_snr_targets_db, ...
        constants.white_snr_targets_db) || ...
        ~isequal(mc_context.constants.noise_profile_ids, ...
        constants.noise_profile_ids) || ...
        ~isequal(mc_context.constants.snapshot_counts, ...
        constants.snapshot_counts) || ...
        ~isequal(mc_context.constants.profile_ids, constants.profile_ids)
    error('stage8_k2_wacb_build_context:FrozenContext', ...
        'Frozen Monte Carlo and classical contexts no longer agree.');
end
models = repmat(struct('noise_profile_id', "", 'model', struct(), ...
    'noise_factors', struct(), 'whitening', struct()), ...
    numel(constants.noise_profile_ids), 1);
for index = 1:numel(constants.noise_profile_ids)
    noise_id = constants.noise_profile_ids(index);
    model = resolve_stage8_measurement_model( ...
        cb_context.plan.measurement_model_registry, ...
        constants.primary_measurement_config_id, noise_id);
    factors = stage8_k2_sb_noise_factors(model, constants);
    dummy = complex(zeros(size(model.Rn_elem, 1), 1));
    [~, whitening] = stage8_k2_cb_whiten_element_data(dummy, model);
    models(index) = struct('noise_profile_id', noise_id, ...
        'model', model, 'noise_factors', factors, 'whitening', whitening);
end
context = struct('repo_dir', repo_dir, 'constants', constants, ...
    'mc_context', mc_context, 'cb_context', cb_context, ...
    'plan', cb_context.plan, 'evidence44', evidence44, ...
    'evidence46', evidence46, 'models', models, ...
    'code_identity', code_identity, ...
    'primary_measurement_config_id', constants.primary_measurement_config_id);
context.context_hash = stage8_k2_wacb_stable_hash( ...
    constants.protocol, evidence44.identity, evidence46.identity, ...
    cb_context.plan.local_domain.domain_hash, ...
    cb_context.plan.stage8_measurement_plan_hash, ...
    code_identity.tree_hash, constants.source_commit);
end
