function progress = stage8_k2_wacb_progress(scan)
%STAGE8_K2_WACB_PROGRESS Aggregate bounded status from validated checkpoints.

names = {'element_music_valid_count','element_music_single_peak_count', ...
    'element_music_na_count','gfbss_elevation_valid_count', ...
    'gfbss_end_to_end_valid_count','root_elevation_valid_count', ...
    'root_end_to_end_valid_count','esprit_elevation_valid_count', ...
    'esprit_end_to_end_valid_count','conditional_az_cml_valid_count'};
for index = 1:numel(names)
    progress.(names{index}) = 0;
end
for index = find(scan.completed_mask).'
    checkpoint = scan.checkpoints{index};
    rows = checkpoint.new_method_rows;
    diagnostics = checkpoint.diagnostic_rows;
    music = rows(rows.method_id == "ELEMENT_MUSIC_K2", :);
    progress.element_music_valid_count = ...
        progress.element_music_valid_count + double(music.fit_valid);
    progress.element_music_single_peak_count = ...
        progress.element_music_single_peak_count + double( ...
        music.applicable && music.fit_status == "MUSIC_FEWER_THAN_TWO_PEAKS");
    progress.element_music_na_count = progress.element_music_na_count + ...
        double(~music.applicable);
    methods = ["GFBSS", "ELEMENT_VERTICAL_GFBSS_MUSIC_AZ_CML"; ...
        "ROOT", "ELEMENT_VERTICAL_FBSS_ROOT_MUSIC_AZ_CML"; ...
        "ESPRIT", "ELEMENT_VERTICAL_FBSS_LS_ESPRIT_AZ_CML"];
    for method_index = 1:size(methods, 1)
        diagnostic = diagnostics(diagnostics.method_id == ...
            methods(method_index, 2), :);
        row = rows(rows.method_id == methods(method_index, 2), :);
        elevation_name = lower(char(methods(method_index, 1))) + ...
            "_elevation_valid_count";
        end_name = lower(char(methods(method_index, 1))) + ...
            "_end_to_end_valid_count";
        progress.(char(elevation_name)) = progress.(char(elevation_name)) + ...
            double(diagnostic.elevation_fit_valid);
        progress.(char(end_name)) = progress.(char(end_name)) + ...
            double(row.fit_valid);
        progress.conditional_az_cml_valid_count = ...
            progress.conditional_az_cml_valid_count + ...
            double(diagnostic.conditional_az_cml_valid);
    end
end
progress.completed_count = scan.completed_count;
progress.runtime_sec = scan.runtime_sec;
end
