function [trial, metrics, identity] = stage8_k2_wacb_reconstruct_trial( ...
    spec, context)
%STAGE8_K2_WACB_RECONSTRUCT_TRIAL Rebuild one exact evidence-44 trial.

[trial, metrics] = stage8_k2_mc_generate_trial(spec, context.mc_context);
target_error = abs(double(metrics.white_beam_snr_expected_db) - ...
    double(spec.white_beamspace_snr_target_db));
if string(trial.element_trial_hash) ~= string(spec.element_trial_hash) || ...
        string(trial.measurement_hash) ~= string(spec.measurement_hash) || ...
        target_error > context.constants.snr_db_tolerance
    error('stage8_k2_wacb_reconstruct_trial:Identity', ...
        'Reconstructed hash, seeds, measurement, or white target changed.');
end
identity = struct('trial_id', string(spec.trial_id), ...
    'measurement_hash', string(trial.measurement_hash), ...
    'element_trial_hash', string(trial.element_trial_hash), ...
    'source_seed', double(spec.source_seed), ...
    'noise_seed', double(spec.noise_seed), ...
    'white_target_error_db', target_error, ...
    'element_hash_match_flag', true, ...
    'measurement_hash_match_flag', true);
end
