function [protocol, checkpoint, expected_rows] = build_checkpoint_fixture()
%BUILD_CHECKPOINT_FIXTURE Minimal deterministic checkpoint contract fixture.

constants = stage8_1b_constants();
evaluation_row_index = [1; 2];
common_trial_id = ["K1V_TEST_T0001"; "K1V_TEST_T0001"];
measurement_config_id = ["PRIMARY_RECT_E14_A31"; ...
    "SENSITIVITY_FULL_PARENT_5X5"];
expected_rows = table(evaluation_row_index, common_trial_id, ...
    measurement_config_id);
rows = expected_rows;
rows.lambda_12 = [1.25; 1.50];
rows.state = ["K1"; "K1"];
rows.separation_status = [ ...
    "NOT_RUN_LRT_DID_NOT_EXCEED_THRESHOLD"; ...
    "NOT_RUN_LRT_DID_NOT_EXCEED_THRESHOLD"];
protocol = struct( ...
    'protocol_version', constants.protocol_version, ...
    'checkpoint_contract_version', ...
    constants.checkpoint_contract_version, ...
    'stage8_stable_code_identity_hash', ...
    constants.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', constants.stage8_plan_hash, ...
    'stage8_validation_plan_hash', ...
    constants.stage8_validation_plan_hash, ...
    'measurement_registry_hash', constants.measurement_registry_hash, ...
    'calibration_evidence_bundle_hash', ...
    constants.calibration_evidence_bundle_hash, ...
    'threshold_set_hash', constants.threshold_set_hash, ...
    'calibration_snapshot_hash', 'UNIT_CALIBRATION_SNAPSHOT');
checkpoint = struct( ...
    'protocol_version', protocol.protocol_version, ...
    'checkpoint_contract_version', protocol.checkpoint_contract_version, ...
    'common_trial_id', 'K1V_TEST_T0001', ...
    'global_common_trial_index', 1, 'rows', rows, ...
    'stage8_stable_code_identity_hash', ...
    protocol.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', protocol.stage8_plan_hash, ...
    'stage8_validation_plan_hash', protocol.stage8_validation_plan_hash, ...
    'measurement_registry_hash', protocol.measurement_registry_hash, ...
    'calibration_evidence_bundle_hash', ...
    protocol.calibration_evidence_bundle_hash, ...
    'threshold_set_hash', protocol.threshold_set_hash, ...
    'calibration_snapshot_hash', protocol.calibration_snapshot_hash, ...
    'threshold_lookup_only_flag', true, ...
    'threshold_modification_flag', false, ...
    'completion_status', 'COMPLETE_PASS', 'content_hash', '', ...
    'runtime_sec', 2.5, 'worker_id', 1, ...
    'attempt_id', 'UNIT_ATTEMPT', ...
    'created_utc', '2026-07-27T00:00:00.000Z');
checkpoint.content_hash = stage8_1b_checkpoint_content_hash(checkpoint);
end
