function result = test_external_runner_matches_reference(repo_dir)
%TEST_EXTERNAL_RUNNER_MATCHES_REFERENCE Run one real common trial per stratum.

context = stage8_1b_frozen_context(repo_dir, false);
reference = run_stage8_1_k1_validation( ...
    context.plan.validation, context.plan.local_domain, ...
    context.plan.measurement_model_registry, context.thresholds, ...
    build_stage8_stage5_locked_config(), struct( ...
    'formal_run', false, 'max_common_trials_per_stratum', 1, ...
    'evaluation_callback', [], 'fit_options', struct(), ...
    'Bsep', 199, 'run_separation', false, ...
    'execution_authorization', '', 'frozen_plan', context.plan));
selected = context.registry( ...
    context.registry.trial_index_within_stratum <= 1, :);
pair_ids = unique(string(selected.common_trial_id), 'stable');
external = cell(numel(pair_ids), 1);
for index = 1:numel(pair_ids)
    pair = selected(selected.common_trial_id == pair_ids(index), :);
    external{index} = stage8_1b_evaluate_common_trial( ...
        pair, context.plan, context.thresholds, struct( ...
        'formal_run', false, 'fit_options', struct(), ...
        'Bsep', 199, 'run_separation', false));
end
external_trials = sortrows(vertcat(external{:}), 'evaluation_row_index');
reference_trials = sortrows(reference.trials, 'evaluation_row_index');
reference_hash = stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_TRIAL_SET_V1', reference_trials);
external_hash = stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_TRIAL_SET_V1', external_trials);
assert(height(reference_trials) == 12);
assert(strcmp(reference_hash, external_hash));
assert(isequal(num2hex(double(reference_trials.lambda_12)), ...
    num2hex(double(external_trials.lambda_12))));
assert(isequal(string(reference_trials.state), ...
    string(external_trials.state)));
result = struct('pass', true, 'reference_row_hash', reference_hash, ...
    'external_row_hash', external_hash, 'row_count', 12);
end
