function result = test_pilot_parallel_crash_fallback()
%TEST_PILOT_PARALLEL_CRASH_FALLBACK Preserve Gate 0/1/2A and select one worker.

root = tempname;
mkdir(fullfile(root, 'gate1'));
cleanup = onCleanup(@() rmdir(root, 's'));
write_json_local(fullfile(root, 'gate0_preflight.json'), ...
    struct('gate0_pass', true));
write_json_local(fullfile(root, 'gate1', 'gate1_result.json'), struct( ...
    'gate1_pass', true, 'external_row_hash', 'ROW_HASH', ...
    'reference_row_hash', 'ROW_HASH', ...
    'forced_separation_fixture_required', false, ...
    'natural_separation_trigger_count', 1));
write_json_local(fullfile(root, 'gate2a_result.json'), comparison_local(true));
write_json_local(fullfile(root, 'gate2b_result.json'), comparison_local(false));
write_json_local(fullfile(root, 'pilot_resources.json'), struct( ...
    'resume_file_identity_pass', true, 'speedup', 0, ...
    'peak_total_memory_utilization', 0.5, ...
    'minimum_available_physical_bytes', 8 * 1024^3, ...
    'sustained_pagefile_thrashing', false, ...
    'worker_crash_or_oom', true, ...
    'resource_failure_reason', 'WORKER_CRASH_OR_OOM', ...
    'single_worker_wall_sec', 10, 'two_worker_active_wall_sec', 0, ...
    'peak_private_memory_bytes', 1024));
decision = stage8_1b_sharded_pilot(root);
assert(decision.gate0_pass && decision.gate1_pass && decision.gate2a_pass);
assert(~decision.gate2b_pass && decision.selected_worker_count == 1);
assert(strcmp(decision.selected_execution_mode, 'ONE_WORKER_RESUMABLE'));
assert(strcmp(decision.fallback_reason, 'TWO_WORKER_CRASH_OR_OOM'));
result = struct('pass', true, 'pilot_decision', decision.pilot_decision, ...
    'fallback_reason', decision.fallback_reason);
clear cleanup
end

function value = comparison_local(pass)
value = struct('pass', logical(pass), 'baseline_row_hash', 'ROW_HASH', ...
    'candidate_row_hash', ternary_local(pass, 'ROW_HASH', ''), ...
    'checkpoint_hash_equality', logical(pass), ...
    'lambda_num2hex_equality', logical(pass));
end

function value = ternary_local(condition, yes_value, no_value)
if condition, value = yes_value; else, value = no_value; end
end

function write_json_local(path_now, value)
stage8_1b_write_json_atomic(path_now, value);
end
