function contract = build_stage8_1a_checkpoint_contract(calibration_plan)
%BUILD_STAGE8_1A_CHECKPOINT_CONTRACT Bind synthetic checkpoints to a plan.

contract = struct( ...
    'stage8_stable_code_identity_hash', 'CHECKPOINT_TEST_SOURCE', ...
    'stage8_plan_hash', 'CHECKPOINT_TEST_STAGE8_PLAN', ...
    'stage8_calibration_plan_hash', ...
    calibration_plan.calibration_plan_hash, ...
    'measurement_registry_hash', 'CHECKPOINT_TEST_REGISTRY');
end
