function [fit1, fit2, lrt, threshold, separation, diagnostics] = ...
    build_stage8_classifier_fixture()
%BUILD_STAGE8_CLASSIFIER_FIXTURE Return a valid resolved decision fixture.

fit1 = struct('estimate_returned_flag', true, 'converged_flag', true, ...
    'effective_rank', 1);
fit2 = struct('estimate_returned_flag', true, 'converged_flag', true, ...
    'effective_rank', 2);
lrt = struct('lrt_status', 'OK', 'nested_rss_pass', true, ...
    'lambda_12', 12);
threshold = struct('threshold_status', 'LOCKED_BOOTSTRAP_THRESHOLD', ...
    'q_global', 5);
separation = struct('confidence_status', 'OK', ...
    'valid_bootstrap_fraction', 1, 'minimum_valid_fraction', 0.90, ...
    'zero_excluded_flag', true, 'engineering_halfwidth_pass', true);
diagnostics = struct('out_of_local_cell_flag', false);
end
