function plan = build_stage8_1a_mini_calibration_plan(fixture, cell_count)
%BUILD_STAGE8_1A_MINI_CALIBRATION_PLAN Build a small materialization plan.

if nargin < 2, cell_count = 3; end
model = resolve_stage8_measurement_model( ...
    fixture.registry, 'MINI_PRIMARY', 'WHITE');
rows = cell(cell_count, 1);
for cell_index = 1:cell_count
    rows{cell_index} = struct( ...
        'measurement_config_id', "MINI_PRIMARY", ...
        'calibration_cell_id', sprintf('MINI_C_%03d', cell_index), ...
        'center_az_deg', 7.8 + 0.2 * cell_index, ...
        'center_el_deg', 10, 'snr_db', 0, 'L', 1, ...
        'noise_profile_id', "WHITE", ...
        'model_key', string(model.model_key), ...
        'fixed_measurement_hash', string(model.fixed_measurement_hash), ...
        'Bboot_per_cell', 2, 'global_cell_index', cell_index, ...
        'calibration_data_seed', 9000 + cell_index, ...
        'bootstrap_seed_start', 19000 + 1000 * cell_index, ...
        'bootstrap_seed_end', 19001 + 1000 * cell_index, ...
        'seed_block_stride', 1000, ...
        'bootstrap_seed_formula', ...
        "bootstrap_seed_start + bootstrap_index - 1");
end
cells = struct2table(vertcat(rows{:}));
plan = struct('cells', cells, 'Bboot_per_cell', 2, ...
    'calibration_plan_hash', stage8_stable_hash( ...
    'STAGE8_1A_MINI_CALIBRATION_PLAN', cells));
end
