function [thresholds, contract, threshold_set_hash] = ...
    build_stage8_1a_threshold_fixture(config_ids)
%BUILD_STAGE8_1A_THRESHOLD_FIXTURE Build provenance-valid mini thresholds.

if nargin < 1
    config_ids = ["MINI_PRIMARY";"MINI_PARENT"];
end
config_ids = string(config_ids(:));
contract = struct( ...
    'stage8_stable_code_identity_hash', 'MINI_STAGE8_SOURCE', ...
    'stage8_plan_hash', 'MINI_STAGE8_PLAN', ...
    'stage8_calibration_plan_hash', 'MINI_CALIBRATION_PLAN', ...
    'measurement_registry_hash', 'MINI_MEASUREMENT_REGISTRY');
base = struct( ...
    'stage8_stable_code_identity_hash', ...
    contract.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', contract.stage8_plan_hash, ...
    'stage8_calibration_plan_hash', ...
    contract.stage8_calibration_plan_hash, ...
    'measurement_registry_hash', contract.measurement_registry_hash, ...
    'measurement_config_id', '', 'q_global', 5, 'alpha', 0.05, ...
    'calibration_hash', '', 'source_identity', ...
    contract.stage8_stable_code_identity_hash, ...
    'threshold_status', 'LOCKED_BOOTSTRAP_THRESHOLD', ...
    'threshold_policy', ...
    'ONE_GLOBAL_THRESHOLD_PER_FIXED_MEASUREMENT_CONFIG', ...
    'threshold_artifact_hash', '');
thresholds = repmat(base, numel(config_ids), 1);
for config_index = 1:numel(config_ids)
    thresholds(config_index).measurement_config_id = ...
        char(config_ids(config_index));
    thresholds(config_index).calibration_hash = sprintf( ...
        'MINI_THRESHOLD_%d', config_index);
    thresholds(config_index).threshold_artifact_hash = ...
        stage8_threshold_artifact_hash(thresholds(config_index));
end
[~, threshold_set_hash] = validate_stage8_locked_threshold_set( ...
    config_ids, thresholds, contract);
end
