function bundle = build_stage8_1a_writer_bundle(runtime_value)
%BUILD_STAGE8_1A_WRITER_BUNDLE Build a complete tiny writer payload.

if nargin < 1
    runtime_value = 1;
end
ids = string((1:2).');
tiny = table(ids, [1;2], 'VariableNames', {'id','value'});
bundle = struct('plan_registry', tiny, 'measurement_registry', tiny, ...
    'calibration_cells', tiny, 'seed_registry', tiny, ...
    'cell_results', tiny, 'lambda_samples', tiny, ...
    'locked_thresholds', tiny, 'complexity', tiny, ...
    'provenance', tiny, 'source_manifest', tiny, ...
    'k1_validation_trials', tiny, 'k1_validation_summary', tiny, ...
    'k1_validation_paired_sensitivity', tiny, ...
    'keypoints', tiny, 'report_text', sprintf('# Mini report\n'), ...
    'runtime_diagnostics', table(runtime_value, ...
    'VariableNames', {'runtime_sec'}));
end
