function fixture = build_stage8_1a_two_commit_fixture()
%BUILD_STAGE8_1A_TWO_COMMIT_FIXTURE Build a complete miniature frozen plan.

base = build_stage8_1a_mini_fixture();
config_ids = ["MINI_PRIMARY";"MINI_PARENT"];
noise_ids = ["WHITE";"STAGE5_TOEPLITZ_CORRELATED"];
rows = cell(4, 1);
row_index = 0;
for config_index = 1:2
    for noise_index = 1:2
        row_index = row_index + 1;
        model = resolve_stage8_measurement_model(base.registry, ...
            config_ids(config_index), noise_ids(noise_index));
        rows{row_index} = struct( ...
            'measurement_config_id', config_ids(config_index), ...
            'calibration_cell_id', sprintf('MINI_C_%03d', row_index), ...
            'center_az_deg', 8, 'center_el_deg', 10, ...
            'snr_db', 0, 'L', 1, ...
            'noise_profile_id', noise_ids(noise_index), ...
            'model_key', string(model.model_key), ...
            'fixed_measurement_hash', string(model.fixed_measurement_hash), ...
            'Bboot_per_cell', 2, 'global_cell_index', row_index, ...
            'calibration_data_seed', 9000 + row_index, ...
            'bootstrap_seed_start', 19000 + 10 * row_index, ...
            'bootstrap_seed_end', 19001 + 10 * row_index, ...
            'seed_block_stride', 10, ...
            'bootstrap_seed_formula', ...
            "bootstrap_seed_start + bootstrap_index - 1");
    end
end
cells = struct2table(vertcat(rows{:}));
calibration = struct('cells', cells, 'Bboot_per_cell', 2);
calibration.calibration_plan_hash = stage8_stable_hash( ...
    'STAGE8_1A_TWO_COMMIT_CALIBRATION_PLAN', cells);
validation = build_stage8_validation_plan();
validation.K1.measurement_config_ids = config_ids;
validation.K1.primary_measurement_config_id = 'MINI_PRIMARY';
validation.K1.sensitivity_measurement_config_id = 'MINI_PARENT';
validation.K1.trials_per_stratum = 1;
validation.K1.trials_per_config = height(validation.K1.strata);
validation.K1.common_element_trial_count = height(validation.K1.strata);
validation.K1.config_evaluation_row_count = 2 * height(validation.K1.strata);
validation.K1.strata.trials_per_stratum(:) = 1;
validation.validation_plan_hash = stage8_stable_hash( ...
    validation.K1, validation.K2);
identity_hash = 'MINI_STAGE8_SOURCE';
measurement_registry = base.registry;
measurement_registry.registry_hash = 'MINI_MEASUREMENT_REGISTRY';
source_manifest = table("100644", "MINI_BLOB", "mini/source.m", ...
    'VariableNames', {'git_mode','git_blob_hash','relative_path'});
plan_hash = stage8_stable_hash('MINI_STAGE8_PLAN', ...
    calibration.calibration_plan_hash, validation.validation_plan_hash, ...
    measurement_registry.registry_hash);
plan = struct('identity', struct( ...
    'stage8_stable_code_identity_hash', identity_hash, ...
    'source_manifest', source_manifest), ...
    'stage8_plan_hash', plan_hash, ...
    'stage8_calibration_plan_hash', calibration.calibration_plan_hash, ...
    'stage8_validation_plan_hash', validation.validation_plan_hash, ...
    'stage8_holdout_plan_hash', 'MINI_HOLDOUT_PLAN', ...
    'measurement_model_registry', measurement_registry, ...
    'calibration', calibration, 'validation', validation, ...
    'controls', struct('alpha', 0.05), ...
    'local_domain', base.domain, ...
    'local_domain_hash', base.domain.domain_hash);
fixture = struct('base', base, 'plan', plan, ...
    'contract', build_stage8_threshold_contract(plan));
end
