function output = build_stage8_1a_bound_validation_output( ...
    plan, calibration, primary_state, sensitivity_state)
%BUILD_STAGE8_1A_BOUND_VALIDATION_OUTPUT Build hash-bound paired mini output.

if nargin < 3, primary_state = 'K1'; end
if nargin < 4, sensitivity_state = 'K1'; end
trials = materialize_stage8_k1_validation_plan(plan.validation);
primary_id = string(plan.validation.K1.primary_measurement_config_id);
state = repmat(string(sensitivity_state), height(trials), 1);
state(string(trials.measurement_config_id) == primary_id) = ...
    string(primary_state);
trials.state = state;
threshold_hash = strings(height(trials), 1);
for config_index = 1:numel(calibration.locked_thresholds)
    threshold = calibration.locked_thresholds(config_index);
    selected = string(trials.measurement_config_id) == ...
        string(threshold.measurement_config_id);
    threshold_hash(selected) = string(threshold.threshold_artifact_hash);
end
trials.threshold_artifact_hash = threshold_hash;
[summary, gate, paired] = summarize_stage8_k1_validation( ...
    trials, plan.validation.K1);
output = struct('trials', trials, 'summary', summary, 'gate', gate, ...
    'paired_sensitivity', paired, 'runtime', 0, ...
    'stage8_stable_code_identity_hash', ...
    plan.identity.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', plan.stage8_plan_hash, ...
    'stage8_calibration_plan_hash', plan.stage8_calibration_plan_hash, ...
    'stage8_validation_plan_hash', plan.stage8_validation_plan_hash, ...
    'measurement_registry_hash', ...
    plan.measurement_model_registry.registry_hash, ...
    'calibration_evidence_bundle_hash', ...
    calibration.calibration_evidence_bundle_hash, ...
    'threshold_set_hash', calibration.threshold_set_hash, ...
    'validation_trial_set_hash', stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_TRIAL_SET_V1', ...
    sortrows(trials, 'evaluation_row_index')), ...
    'validation_summary_hash', stage8_stable_hash( ...
    'STAGE8_1_VALIDATION_SUMMARY_V1', summary), ...
    'paired_sensitivity_hash', stage8_stable_hash( ...
    'STAGE8_1_PAIRED_SENSITIVITY_V1', paired), ...
    'primary_gate_hash', stage8_stable_hash( ...
    'STAGE8_1_PRIMARY_GATE_V1', gate), ...
    'validation_execution_status', ...
    'STAGE8_1_K1_VALIDATION_COMPLETED');
end
