function fixture = build_stage8_1a_mini_fixture()
%BUILD_STAGE8_1A_MINI_FIXTURE Build small element-domain Stage8.1 models.

phi = deg2rad([-12;-4;4;12]);
z = [0,0.45];
X = cos(phi) * ones(1, 2);
Y = sin(phi) * ones(1, 2);
Z = ones(4, 1) * z;
array_meta = struct('XAct', X, 'YAct', Y, 'ZAct', Z, ...
    'xActVec', X(:), 'yActVec', Y(:), 'zActVec', Z(:));
cfg = struct('arr', struct('lambda', 1, 'dz', 0.45, 'Nel', 2, ...
    'Naz', 4, 'R', 1), 'beam', struct('spatialPhaseFactor', 1, ...
    'subNaz', 4, 'azSectorCenter', 0));
[domain, ~] = build_common_registered_local_domain([8,10], struct( ...
    'azimuth_offsets_deg', -0.6:0.2:0.6, ...
    'elevation_offsets_deg', -0.2:0.2:0.2, ...
    'domain_id', 'STAGE8_1A_MINI_DOMAIN', ...
    'domain_source', 'MINIATURE_DATA_DRIVEN_FIXTURE', ...
    'configuration_hash', 'STAGE8_1A_MINI_CONFIGURATION', ...
    'phase_factor', 1));
config_ids = ["MINI_PRIMARY";"MINI_PARENT"];
noise_ids = ["WHITE";"STAGE5_TOEPLITZ_CORRELATED"];
entries = cell(4, 1);
rows = cell(4, 1);
row_index = 0;
for config_index = 1:2
    for noise_index = 1:2
        row_index = row_index + 1;
        [R_el, R_az] = covariance_local(noise_index);
        Rn = kron(R_az, R_el);
        W = eye(8);
        T = inv(chol(Rn, 'lower'));
        key = sprintf('%s__%s', config_ids(config_index), ...
            noise_ids(noise_index));
        fixed_hash = stage8_stable_hash('STAGE8_1A_MINI_MODEL', key, Rn);
        factor = struct('factorization_type', ...
            'SEPARABLE_MATRIX_NORMAL', 'R_el', R_el, 'R_az', R_az, ...
            'L_el', chol(R_el, 'lower'), 'L_az', chol(R_az, 'lower'), ...
            'rho_el', 0, 'rho_az', 0, ...
            'factorization_hash', stage8_stable_hash(R_el, R_az));
        model = struct('measurement_config_id', char(config_ids(config_index)), ...
            'measurement_role', 'MINIATURE', 'subset_id', ...
            sprintf('MINI_SUBSET_%d', config_index), 'model_key', key, ...
            'channels', 1:8, 'Wseq', W, 'W_I', W, ...
            'Cseq', Rn, 'C_I', Rn, 'Tseq', T, 'T_I', T, ...
            'whitening_rank', 8, 'array_meta', array_meta, ...
            'lambda', 1, 'phase_factor', 1, ...
            'element_order', 'elevation_fastest_azimuth_slowest', ...
            'noise_profile_id', char(noise_ids(noise_index)), ...
            'Rn_elem', Rn, 'noise_factorization', factor, ...
            'element_noise_factorization', factor, ...
            'factorized_sequential', struct('V', eye(2), ...
            'Uset', complex(zeros(4, 1, 2))), ...
            'array_configuration', cfg, ...
            'fixed_measurement_hash', fixed_hash, ...
            'stage7_parent_pool_hash', 'MINI_PARENT_POOL', ...
            'subset_model_hash', stage8_stable_hash(key));
        entries{row_index} = model;
        rows{row_index} = struct( ...
            'measurement_config_id', config_ids(config_index), ...
            'noise_profile_id', noise_ids(noise_index), ...
            'model_key', string(key), ...
            'fixed_measurement_hash', string(fixed_hash), ...
            'subset_id', string(model.subset_id), 'B_el', 2, ...
            'B_az', 4, 'B_out', 8, 'whitening_rank', 8, ...
            'noise_factorization_hash', string(factor.factorization_hash), ...
            'array_geometry_hash', "MINI_ARRAY", 'phase_factor', 1);
    end
end
entries = vertcat(entries{:});
registry_table = struct2table(vertcat(rows{:}));
registry = struct('entries', entries, 'table', registry_table, ...
    'registry_hash', stage8_stable_hash(registry_table), ...
    'entry_count', 4, 'registry_version', 'STAGE8_1A_MINI_REGISTRY', ...
    'phase_factor', 1);
stage5_locked = build_stage8_stage5_locked_config();
model = resolve_stage8_measurement_model(registry, 'MINI_PRIMARY', 'WHITE');
[Y_k1, ~] = generate_stage8_k1_element_trial([8,10], 12, 8, model, 8101);
full_k1 = build_stage8_full_data_from_element(Y_k1, model, struct());
angles_k2 = [7.8,9.8;8.2,10.2];
manifold_k2 = build_stage8_element_manifold(angles_k2, model);
S_k2 = [1,0.5+0.2j,-0.2+0.7j,0.8-0.1j; ...
    0.3j,0.9-0.2j,0.6+0.1j,-0.4+0.5j];
Y_k2 = manifold_k2.A * S_k2;
full_k2 = build_stage8_full_data_from_element(Y_k2, model, struct());
fixture = struct('cfg', cfg, 'domain', domain, 'registry', registry, ...
    'stage5_locked', stage5_locked, 'model', model, ...
    'full_k1', full_k1, 'full_k2', full_k2, ...
    'angles_k2', angles_k2);
end

function [R_el, R_az] = covariance_local(noise_index)
if noise_index == 1
    R_el = eye(2);
    R_az = eye(4);
else
    R_el = toeplitz(0.2 .^ (0:1));
    R_az = toeplitz(0.3 .^ (0:3));
end
end
