function [fit1, fit2] = build_stage8_lrt_fixture(r_C, L, rss1, rss2)
%BUILD_STAGE8_LRT_FIXTURE Build contract-complete adjacent fit summaries.

n = r_C * L;
fit1 = base_local(1, r_C, L, rss1, n);
fit2 = base_local(2, r_C, L, rss2, n);
end

function fit = base_local(K, r_C, L, rss, n)
sigma2 = rss / n;
fit = struct('K', K, 'rss', rss, ...
    'sigma2_hat', sigma2, ...
    'loglik_concentrated', -n * (log(pi * sigma2) + 1), ...
    'n_complex_observations', n, ...
    'effective_whitening_dimension', r_C, 'snapshot_count', L, ...
    'observation_hash', 'SAME_Z', ...
    'fixed_measurement_hash', 'SAME_MEASUREMENT', ...
    'local_domain_hash', 'SAME_DOMAIN', ...
    'solver_contract_hash', 'SAME_SOLVER', 'phase_factor', 1, ...
    'estimate_returned_flag', true, 'converged_flag', true, ...
    'effective_rank', K);
end
