function fixture = build_stage8_1a5_real_fixture(plan)
%BUILD_STAGE8_1A5_REAL_FIXTURE Fit eight registered low-SNR real cases.

rows = plan.calibration.cells;
center = rows.center_az_deg == 8 & rows.center_el_deg == 10;
off_center = rows.center_az_deg == 7.6 & rows.center_el_deg == 9.8;
selected = rows.snr_db == -12 & rows.L == 1 & (center | off_center);
cell_indices = rows.global_cell_index(selected);
expected_indices = [1;2;31;32;151;152;181;182];
assert(isequal(sort(cell_indices), expected_indices), ...
    'build_stage8_1a5_real_fixture:Plan', ...
    'The registered A5 low-SNR regression cells changed.');

stage5_locked = build_stage8_stage5_locked_config();
[cells, materialization_debug] = materialize_stage8_calibration_cells( ...
    plan.calibration, plan.local_domain, plan.measurement_model_registry, ...
    stage5_locked, struct('cell_indices', cell_indices, ...
    'formal_run', false, 'materialization_mode', 'UNIT_TEST', ...
    'source_identity', plan.identity.stage8_stable_code_identity_hash));
fit_options = struct('max_iter', plan.solver.max_iter, ...
    'relative_score_tolerance', plan.solver.relative_score_tolerance, ...
    'angle_tolerance_deg', plan.solver.angle_tolerance_deg, ...
    'rank_multiplier', plan.solver.rank_multiplier, ...
    'solver_contract_hash', plan.solver_contract_hash);
template = struct('cell_input', struct(), 'model', struct(), ...
    'fit', struct(), 'fit_validity', struct(), 'evaluation', struct());
cases = repmat(template, numel(cells), 1);
for index = 1:numel(cells)
    model = resolve_stage8_measurement_model( ...
        plan.measurement_model_registry, cells(index).measurement_config_id, ...
        cells(index).noise_profile_id);
    [fit, ~] = fit_local_model_k(cells(index).full_data, 1, ...
        plan.local_domain, model, cells(index).initialization_context, ...
        fit_options);
    expected = struct('fixed_measurement_hash', ...
        model.fixed_measurement_hash, 'local_domain_hash', ...
        plan.local_domain.domain_hash, 'solver_contract_hash', ...
        fit.solver_contract_hash, 'observation_hash', fit.observation_hash);
    [valid, validity] = validate_stage8_fit_for_lrt(fit, 1, expected);
    assert(valid, 'build_stage8_1a5_real_fixture:Fit', ...
        'Registered real case %d did not return a valid K1 fit: %s.', ...
        cells(index).global_cell_index, validity.status);
    cases(index).cell_input = cells(index);
    cases(index).model = model;
    cases(index).fit = fit;
    cases(index).fit_validity = validity;
    cases(index).evaluation = ...
        evaluate_stage8_bootstrap_mean_identity(fit, model);
end
fixture = struct('cases', cases, 'cell_indices', cell_indices, ...
    'materialization_debug', materialization_debug, ...
    'stage5_locked', stage5_locked, 'phase_factor', 1);
end
