function context = stage8_synthetic_initialization_factory(~)
%STAGE8_SYNTHETIC_INITIALIZATION_FACTORY Fixed starts for unit fixtures only.

context = struct('grouped_q1_kq1_angles_deg', [8.0,10.0], ...
    'conventional_singleton_peak_deg', [8.0,10.0], ...
    'grouped_q1_kq2_angles_deg', [7.8,10.0;8.2,10.0], ...
    'grouped_q2_kq1_plus_kq1_angles_deg', [7.8,9.8;8.2,10.2], ...
    'initialization_scope', 'DETERMINISTIC_SYNTHETIC_FIXTURE_ONLY');
end
