function [context, debug] = stage8_1a_mini_initialization_callback( ...
    data, model, domain)
%STAGE8_1A_MINI_INITIALIZATION_CALLBACK Build data-keyed miniature starts.

context = struct('grouped_q1_kq1_angles_deg', [8,10], ...
    'conventional_singleton_peak_deg', [8,10], ...
    'grouped_q1_kq2_angles_deg', [7.8,10;8.2,10], ...
    'grouped_q2_kq1_plus_kq1_angles_deg', [7.8,9.8;8.2,10.2], ...
    'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'local_domain_hash', domain.domain_hash, ...
    'observation_hash', stage8_stable_hash(data.Zseq_white), ...
    'factory_invocation_hash', stage8_stable_hash(data.Zseq_white), ...
    'num_score_eval', 0, 'num_svd', 0, 'runtime', 0, 'phase_factor', 1);
debug = struct('num_score_eval', 0, 'num_svd', 0, ...
    'factory_invocation_hash', context.factory_invocation_hash, ...
    'phase_factor', 1);
end
