function result = stage8_1a4_contract_case(case_id)
%STAGE8_1A4_CONTRACT_CASE Execute one formal-runtime safety assertion.

switch string(case_id)
    case "unreturned_registered_start_does_not_crash"
        [failed, score_required] = unreturned_result_local('FAILED');
        [~, diagnostics] = select_stage8_valid_registered_start( ...
            [failed;valid_result_local('VALID')], 1, identity_local());
        pass = ~score_required && diagnostics.unreturned_start_count == 1;
    case "unreturned_start_is_not_selected"
        failed = unreturned_result_local('FAILED');
        valid = valid_result_local('VALID');
        valid.loglik_concentrated = -5;
        index = select_stage8_valid_registered_start( ...
            [failed;valid], 1, identity_local());
        pass = index == 2;
    case "valid_start_survives_peer_runtime_failure"
        failed = unreturned_result_local('FAILED');
        failed.num_score_eval = 13;
        failed.num_svd = 7;
        failed.runtime = 0.5;
        valid = valid_result_local('VALID');
        [index, ~, rows] = select_stage8_valid_registered_start( ...
            [failed;valid], 1, identity_local());
        pass = index == 2 && sum([rows.num_score_eval]) == 14 && ...
            sum([rows.num_svd]) == 8 && sum([rows.runtime]) == 0.5;
    case "all_unreturned_starts_return_search_not_converged"
        rows = [unreturned_result_local('FAILED_1'); ...
            unreturned_result_local('FAILED_2')];
        [index, diagnostics] = select_stage8_valid_registered_start( ...
            rows, 1, identity_local());
        fit_status = stage8_no_valid_start_fit_status(diagnostics);
        pass = index == 0 && diagnostics.unreturned_start_count == 2 && ...
            strcmp(fit_status, 'SEARCH_NOT_CONVERGED');
    case "unreturned_start_still_appears_in_all_start_results"
        failed = unreturned_result_local('FAILED_REGISTERED_START');
        [~, ~, rows] = select_stage8_valid_registered_start( ...
            [failed;valid_result_local('VALID')], 1, identity_local());
        pass = numel(rows) == 2 && ...
            strcmp(rows(1).initialization_id, 'FAILED_REGISTERED_START') && ...
            strcmp(rows(1).fit_status, 'NUMERICAL_SEARCH_FAILURE') && ...
            strcmp(rows(1).selection_eligibility_status, 'FIT_NOT_RETURNED');
    case "start_failure_counters_are_disjoint"
        rows = classification_rows_local();
        [~, diagnostics] = select_stage8_valid_registered_start( ...
            rows, 1, identity_local());
        counts = [diagnostics.valid_start_count, ...
            diagnostics.initialization_failed_start_count, ...
            diagnostics.unreturned_start_count, ...
            diagnostics.nonconverged_start_count, ...
            diagnostics.rank_deficient_start_count, ...
            diagnostics.numeric_invalid_start_count];
        pass = isequal(counts, ones(1, 6)) && ...
            diagnostics.classified_start_count == numel(rows);
    case "fit_local_model_has_no_dead_rank_failure_counter"
        step_dir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
        source = string(fileread(fullfile( ...
            step_dir, 'common', 'fit_local_model_k.m')));
        pass = ~contains(source, 'rank_failure_count') && ...
            contains(source, 'record_stage8_start_refinement_result');
    case "formal_loader_cannot_disable_tracked_artifacts"
        stage8_assert_error(@() load_stage8_1_locked_thresholds( ...
            tempdir, tempdir, struct(), struct('formal_run', true, ...
            'require_tracked_artifacts', false)), ...
            ['load_stage8_1_locked_thresholds:', ...
            'FORMAL_TRACKED_CALIBRATION_EVIDENCE_REQUIRED']);
        pass = true;
    case "formal_validation_wrapper_cannot_disable_tracked_artifacts"
        stage8_assert_error(@() ...
            run_stage8_1_k1_validation_from_frozen_thresholds( ...
            tempdir, struct('formal_run', true, ...
            'require_tracked_artifacts', false)), ...
            ['run_stage8_1_k1_validation_from_frozen_thresholds:', ...
            'FORMAL_TRACKED_CALIBRATION_EVIDENCE_REQUIRED']);
        pass = true;
    case "formal_finalizer_cannot_disable_tracked_artifacts"
        stage8_assert_error(@() run_stage8_1_finalize( ...
            struct(), struct(), struct(), tempdir, struct( ...
            'formal_run', true, 'require_tracked_artifacts', false)), ...
            ['run_stage8_1_finalize:', ...
            'FORMAL_TRACKED_CALIBRATION_EVIDENCE_REQUIRED']);
        pass = true;
    case "nonformal_loader_may_use_untracked_fixture"
        context = build_stage8_1a_frozen_evidence_fixture();
        [~, evidence] = load_stage8_1_locked_thresholds( ...
            tempdir, context.artifact_root, context.fixture.plan, struct( ...
            'formal_run', false, 'require_tracked_artifacts', false));
        pass = strcmp(evidence.committed_threshold_preflight_status, ...
            'COMMITTED_THRESHOLD_PREFLIGHT_PASS');
    case "formal_threshold_freeze_forbids_overwrite"
        stage8_assert_error(@() run_stage8_1_freeze_threshold_evidence( ...
            tempdir, tempdir, tempdir, struct('formal_run', true, ...
            'overwrite', true)), ...
            ['run_stage8_1_freeze_threshold_evidence:', ...
            'FORMAL_EVIDENCE_OVERWRITE_FORBIDDEN']);
        pass = true;
    case "formal_validation_finalize_forbids_overwrite"
        stage8_assert_error(@() run_stage8_1_finalize( ...
            struct(), struct(), struct(), tempdir, struct( ...
            'formal_run', true, 'overwrite', true)), ...
            ['run_stage8_1_finalize:', ...
            'FORMAL_EVIDENCE_OVERWRITE_FORBIDDEN']);
        pass = true;
    case "formal_calibration_artifact_root_is_registered"
        [repo_dir, step_dir] = repository_paths_local();
        actual = validate_stage8_formal_artifact_root( ...
            repo_dir, step_dir, 'CALIBRATION', struct( ...
            'require_empty_lifecycle', true));
        pass = strcmpi(canonical_path_local(actual), ...
            canonical_path_local(step_dir));
    case "formal_validation_artifact_root_is_registered"
        [repo_dir, step_dir] = repository_paths_local();
        actual = validate_stage8_formal_artifact_root( ...
            repo_dir, step_dir, 'VALIDATION', struct( ...
            'require_empty_lifecycle', true));
        pass = strcmpi(canonical_path_local(actual), ...
            canonical_path_local(step_dir));
    case "formal_artifact_root_rejects_external_folder"
        [repo_dir, ~] = repository_paths_local();
        folder = tempname;
        mkdir(folder);
        cleanup = onCleanup(@() rmdir(folder, 's'));
        stage8_assert_error(@() validate_stage8_formal_artifact_root( ...
            repo_dir, folder, 'CALIBRATION', struct()), ...
            'validate_stage8_formal_artifact_root:RegisteredRootRequired');
        pass = true;
    case "checkpoint_root_remains_external"
        [repo_dir, ~] = repository_paths_local();
        folder = tempname;
        mkdir(folder);
        cleanup = onCleanup(@() rmdir(folder, 's'));
        actual = validate_stage8_formal_checkpoint_root(repo_dir, folder);
        pass = strcmpi(canonical_path_local(actual), ...
            canonical_path_local(folder));
    case "existing_calibration_artifact_blocks_formal_freeze"
        [repo_dir, step_dir] = repository_paths_local();
        sentinel = fullfile(step_dir, 'calibration', ...
            'stage8_1_plan_registry.csv');
        sentinel_cleanup = create_sentinel_local(sentinel); %#ok<NASGU>
        checkpoint = tempname;
        mkdir(checkpoint);
        checkpoint_cleanup = onCleanup(@() rmdir(checkpoint, 's'));
        stage8_assert_error(@() run_stage8_1_freeze_threshold_evidence( ...
            repo_dir, checkpoint, step_dir, struct('formal_run', true, ...
            'execution_authorization', ...
            'AUTHORIZE_STAGE8_1B_THRESHOLD_FREEZE')), ...
            'validate_stage8_formal_artifact_root:ExistingArtifact');
        pass = true;
    case "existing_validation_artifact_blocks_formal_finalize"
        [repo_dir, step_dir] = repository_paths_local();
        sentinel = fullfile(step_dir, 'results', ...
            'stage8_1_k1_validation_trials.csv');
        sentinel_cleanup = create_sentinel_local(sentinel); %#ok<NASGU>
        committed = struct('repo_dir', repo_dir, ...
            'artifact_root', step_dir);
        stage8_assert_error(@() run_stage8_1_finalize( ...
            struct(), committed, struct(), step_dir, struct( ...
            'formal_run', true, 'execution_authorization', ...
            'AUTHORIZE_STAGE8_1_FINALIZE')), ...
            'validate_stage8_formal_artifact_root:ExistingArtifact');
        pass = true;
    case "calibration_sha_unchanged_after_validation"
        context = build_stage8_1a_frozen_evidence_fixture();
        before = capture_stage8_1_calibration_snapshot( ...
            context.artifact_root);
        output = miniature_validation_local(context);
        after = capture_stage8_1_calibration_snapshot( ...
            context.artifact_root);
        pass = isequal(before, after) && ...
            strcmp(output.committed_threshold_preflight_status, ...
            'COMMITTED_THRESHOLD_PREFLIGHT_PASS');
    case "public_validation_wrapper_requires_committed_thresholds"
        stage8_assert_error(@() ...
            run_stage8_1_k1_validation_from_frozen_thresholds( ...
            tempdir, struct('formal_run', false, ...
            'locked_thresholds', struct())), ...
            'run_stage8_1_k1_validation_from_frozen_thresholds:UnknownOption');
        pass = true;
    case "public_finalizer_reloads_thresholds_from_disk"
        context = build_stage8_1a_frozen_evidence_fixture();
        validation = build_stage8_1a_bound_validation_output( ...
            context.fixture.plan, context.calibration);
        supplied = context.calibration;
        supplied.locked_thresholds(1).q_global = 1e9;
        [validation_root, root_cleanup] = validation_root_local(); %#ok<ASGLU>
        evidence = run_stage8_1_finalize(context.fixture.plan, supplied, ...
            validation, validation_root, struct('formal_run', false, ...
            'require_tracked_artifacts', false));
        pass = strcmp(evidence.threshold_set_hash, ...
            context.calibration.threshold_set_hash);
    otherwise
        error('stage8_1a4_contract_case:UnknownCase', ...
            'Unknown Stage8.1A4 case: %s.', case_id);
end
assert(pass, 'stage8_1a4_contract_case:Failed', ...
    'Stage8.1A4 contract case failed: %s.', case_id);
result = table(pass, string(case_id), ...
    'VariableNames', {'pass_flag','case_id'});
end

function [result, score_required] = unreturned_result_local(id)
result = valid_result_local(id);
estimate = struct('angles_hat_deg', [NaN,NaN], 'score', NaN, ...
    'rss', NaN, 'estimate_returned_flag', false, ...
    'joint_refinement_status', 'NUMERICAL_SEARCH_FAILURE', ...
    'num_score_eval', 1, 'num_svd', 1, 'runtime', 0);
[result, score_required] = record_stage8_start_refinement_result( ...
    result, estimate, table(), struct('synthetic_failure', true));
end

function result = valid_result_local(id)
identity = identity_local();
result = struct('K', 1, 'initialization_id', char(id), ...
    'initialization_status', 'INITIALIZATION_AVAILABLE', ...
    'initialization_available_flag', true, ...
    'estimate_returned_flag', true, 'converged_flag', true, ...
    'effective_rank', 1, 'rss', 1, 'sigma2_hat', 1, ...
    'loglik_concentrated', 1, 'fixed_measurement_hash', ...
    identity.fixed_measurement_hash, 'local_domain_hash', ...
    identity.local_domain_hash, 'solver_contract_hash', ...
    identity.solver_contract_hash, 'observation_hash', ...
    identity.observation_hash, 'phase_factor', 1, ...
    'angles_hat_deg', [8,10], 'score', 1, ...
    'fit_status', 'JOINT_REFINEMENT_CONVERGED', ...
    'num_score_eval', 1, 'num_svd', 1, 'runtime', 0, ...
    'history', table(), 'refinement_debug', struct());
end

function identity = identity_local()
identity = struct('fixed_measurement_hash', 'M', ...
    'local_domain_hash', 'D', 'solver_contract_hash', 'S', ...
    'observation_hash', 'O');
end

function rows = classification_rows_local()
initialization_failed = valid_result_local('INITIALIZATION_FAILED');
initialization_failed.initialization_available_flag = false;
unreturned = unreturned_result_local('UNRETURNED');
nonconverged = valid_result_local('NONCONVERGED');
nonconverged.converged_flag = false;
nonconverged.effective_rank = 0;
rank_deficient = valid_result_local('RANK_DEFICIENT');
rank_deficient.effective_rank = 0;
numeric_invalid = valid_result_local('NUMERIC_INVALID');
numeric_invalid.rss = NaN;
rows = [initialization_failed;unreturned;nonconverged;rank_deficient; ...
    numeric_invalid;valid_result_local('VALID')];
end

function [repo_dir, step_dir] = repository_paths_local()
step_dir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
repo_dir = fileparts(fileparts(fileparts(fileparts(fileparts(step_dir)))));
end

function cleanup = create_sentinel_local(path_now)
writetable(table("SYNTHETIC_SENTINEL", ...
    'VariableNames', {'fixture'}), path_now);
cleanup = onCleanup(@() delete_if_present_local(path_now));
end

function delete_if_present_local(path_now)
if isfile(path_now), delete(path_now); end
end

function output = miniature_validation_local(context)
output = run_stage8_1_k1_validation_from_frozen_thresholds( ...
    tempdir, struct('formal_run', false, ...
    'require_tracked_artifacts', false, ...
    'calibration_root', context.artifact_root, ...
    'frozen_plan', context.fixture.plan, ...
    'evaluation_callback', @evaluation_local, ...
    'Bsep', 2, 'run_separation', false));
end

function evaluation = evaluation_local(~, ~, ~, ~)
evaluation = struct('state', 'K1', 'lambda_12', 0, ...
    'fit1_validity_status', 'VALID_FOR_LRT', ...
    'fit2_validity_status', 'VALID_FOR_LRT', ...
    'separation_status', 'NOT_RUN_MINIATURE_CONTRACT');
end

function [root, cleanup] = validation_root_local()
root = tempname;
mkdir(root);
cleanup = onCleanup(@() rmdir(root, 's'));
end

function value = canonical_path_local(value)
value = char(java.io.File(char(value)).getCanonicalPath());
end
