function [fit, debug] = stage8_1a_mock_fit_callback( ...
    K, ~, data, context, model)
%STAGE8_1A_MOCK_FIT_CALLBACK Return a valid nested miniature fit pair.

if K == 1
    angles = [8,10];
else
    angles = [8,10;8.4,10.2];
end
[G, ~] = build_full_sequential_local_manifold(angles, model, struct());
[score, rss, sigma2, loglik, effective_rank] = concentrated_dml_rss( ...
    data.Zseq_white, G, struct('requested_rank', K, ...
    'compute_projector_checks', false));
[S, ~] = solve_fitted_source_coefficients(G, data.Zseq_white, struct());
fit = struct('K', K, 'angles_hat_deg', angles, 'G_hat', G, ...
    'S_hat', S, 'score', score, 'rss', rss, ...
    'sigma2_hat', sigma2, 'loglik_concentrated', loglik, ...
    'effective_rank', effective_rank, 'fit_status', ...
    'JOINT_REFINEMENT_CONVERGED', 'estimate_returned_flag', true, ...
    'converged_flag', true, 'num_score_eval', 1, 'num_svd', 1, ...
    'runtime', 0, 'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'local_domain_hash', context.local_domain_hash, ...
    'solver_contract_hash', 'STAGE8_1A_MOCK_SOLVER', ...
    'observation_hash', stage8_stable_hash(data.Zseq_white), ...
    'effective_whitening_dimension', size(data.Zseq_white, 1), ...
    'snapshot_count', size(data.Zseq_white, 2), ...
    'n_complex_observations', numel(data.Zseq_white), 'phase_factor', 1);
debug = struct('mock_fit_flag', true, 'phase_factor', 1);
end
