function write_stage8_checkpoint_fixture( ...
    checkpoint_root, calibration_plan, contract, cell_indices, subfolder)
%WRITE_STAGE8_CHECKPOINT_FIXTURE Write identity-valid synthetic checkpoints.

if nargin < 4
    cell_indices = (1:height(calibration_plan.cells)).';
end
if nargin < 5, subfolder = ''; end
folder = fullfile(checkpoint_root, subfolder);
if ~isfolder(folder), mkdir(folder); end
for output_index = 1:numel(cell_indices)
    cell_index = cell_indices(output_index);
    row = calibration_plan.cells(cell_index, :);
    Bboot = row.Bboot_per_cell;
    lambda_samples = (1:Bboot).' / Bboot + cell_index / 1000;
    q_cell = stage8_type1_quantile(lambda_samples, 0.95);
    artifact = struct( ...
        'measurement_config_id', char(row.measurement_config_id), ...
        'noise_profile_id', char(row.noise_profile_id), ...
        'calibration_cell_id', char(row.calibration_cell_id), ...
        'global_cell_index', row.global_cell_index, ...
        'data_seed', row.calibration_data_seed, ...
        'bootstrap_seed_start', row.bootstrap_seed_start, ...
        'bootstrap_seed_end', row.bootstrap_seed_end, ...
        'lambda_samples', lambda_samples, 'q_cell_0p95', q_cell, ...
        'failure_count', 0, 'K1_fit_count', Bboot + 1, ...
        'K2_fit_count', Bboot, 'score_call_count', 2 * Bboot, ...
        'svd_call_count', 2 * Bboot, 'runtime', 0, ...
        'source_identity', contract.stage8_stable_code_identity_hash, ...
        'plan_hash', contract.stage8_calibration_plan_hash, ...
        'model_key', char(row.model_key), ...
        'model_hash', char(row.fixed_measurement_hash), ...
        'cell_input_hash', stage8_calibration_cell_input_hash( ...
        row, contract.stage8_stable_code_identity_hash, ...
        contract.stage8_calibration_plan_hash), ...
        'status', 'CALIBRATION_CELL_PASS', 'cell_artifact_hash', '');
    artifact.cell_artifact_hash = stage8_calibration_artifact_hash(artifact);
    path_now = fullfile(folder, sprintf( ...
        'stage8_1_cell_%03d.mat', row.global_cell_index));
    save(path_now, 'artifact', '-v7');
end
end
