function result = test_pair_manifold_mixed_provider()
%TEST_PAIR_MANIFOLD_MIXED_PROVIDER Cover all cache/direct column patterns.

fixture = stage8_k2_tcc_test_fixture();
model = fixture.model;
provider = stage8_k2_tcc_build_provider( ...
    'EXACT_CACHE_OR_DIRECT', model, fixture.cache, struct());
cases = { ...
    [7.8, 10.0; 8.2, 10.0], ["CACHE_EXACT"; "CACHE_EXACT"]; ...
    [7.8, 10.0; 8.204, 10.0], ["CACHE_EXACT"; "DIRECT_FALLBACK"]; ...
    [7.804, 10.0; 8.2, 10.0], ["DIRECT_FALLBACK"; "CACHE_EXACT"]; ...
    [7.804, 10.0; 8.204, 10.0], ...
        ["DIRECT_FALLBACK"; "DIRECT_FALLBACK"]};
max_relative_error = 0;
max_singular_error = 0;
for index = 1:size(cases, 1)
    angles = cases{index, 1};
    expected_sources = cases{index, 2};
    [candidate, candidate_info, provider_info] = ...
        stage8_k2_tcc_get_pair_manifold(angles, model, provider, struct());
    [reference, reference_info] = stage8_k2_tcc_build_g_direct( ...
        angles, model, struct('compute_rank', true));
    relative_error = norm(candidate - reference, 'fro') / ...
        max(norm(reference, 'fro'), realmin);
    singular_error = max(abs(candidate_info.singular_values_Gseq - ...
        reference_info.singular_values_Gseq));
    max_relative_error = max(max_relative_error, relative_error);
    max_singular_error = max(max_singular_error, singular_error);
    assert(isequal(provider_info.column_sources, expected_sources) && ...
        relative_error <= 1e-10 && ...
        candidate_info.rank_Gseq == reference_info.rank_Gseq && ...
        singular_error <= 1e-10 * max(1, ...
        max(reference_info.singular_values_Gseq)) && ...
        abs(candidate_info.rank_threshold_Gseq - ...
        reference_info.rank_threshold_Gseq) <= 1e-12, ...
        'test_pair_manifold_mixed_provider:Mismatch', ...
        'A mixed provider case changed the ordered pair manifold.');
end
result = struct('pass', true, ...
    'max_relative_error', max_relative_error, ...
    'max_singular_value_error', max_singular_error, ...
    'case_count', size(cases, 1));
fprintf(['test_pair_manifold_mixed_provider PASS relative=%.17g ', ...
    'singular=%.17g\n'], max_relative_error, max_singular_error);
end
