function result = test_profile_score_equivalence()
%TEST_PROFILE_SCORE_EQUIVALENCE Compare concentrated DML values.

fixture = stage8_k2_tcc_test_fixture();
model = fixture.model;
angles = [7.8, 10.0; 8.204, 10.0];
direct_provider = stage8_k2_tcc_build_provider( ...
    'DIRECT_ONLY', model, [], struct());
hybrid_provider = stage8_k2_tcc_build_provider( ...
    'EXACT_CACHE_OR_DIRECT', model, fixture.cache, struct());
[G_direct, direct_info] = stage8_k2_tcc_get_pair_manifold( ...
    angles, model, direct_provider, struct());
[G_hybrid, hybrid_info] = stage8_k2_tcc_get_pair_manifold( ...
    angles, model, hybrid_provider, struct());
[score_direct, rss_direct, sigma_direct, loglik_direct, rank_direct] = ...
    concentrated_dml_rss(fixture.Z_white, G_direct, struct( ...
    'requested_rank', 2, 'rank_multiplier', 1, ...
    'compute_projector_checks', false));
[score_hybrid, rss_hybrid, sigma_hybrid, loglik_hybrid, rank_hybrid] = ...
    concentrated_dml_rss(fixture.Z_white, G_hybrid, struct( ...
    'requested_rank', 2, 'rank_multiplier', 1, ...
    'compute_projector_checks', false));
differences = [abs(score_direct - score_hybrid), ...
    abs(rss_direct - rss_hybrid), abs(sigma_direct - sigma_hybrid), ...
    abs(loglik_direct - loglik_hybrid)];
references = [score_direct, rss_direct, sigma_direct, loglik_direct];
assert(direct_info.rank_Gseq == hybrid_info.rank_Gseq && ...
    rank_direct == rank_hybrid && ...
    all(differences <= 1e-8 * max(1, abs(references))), ...
    'test_profile_score_equivalence:Mismatch', ...
    'The hybrid manifold changed a concentrated DML score.');
result = struct('pass', true, 'max_scalar_abs_error', max(differences), ...
    'rank', rank_direct);
fprintf('test_profile_score_equivalence PASS error=%.17g\n', ...
    max(differences));
end
