function result = test_exact_cache_matches_direct_g()
%TEST_EXACT_CACHE_MATCHES_DIRECT_G Verify real exact hits.

fixture = stage8_k2_tcc_test_fixture();
model = fixture.model;
cache = fixture.cache;
queries = [7.4, 9.8; 7.8, 10.0; 8.2, 10.1; 8.6, 10.2];
max_relative_error = 0;
for index = 1:size(queries, 1)
    [cached, lookup_info] = stage8_k2_tcc_lookup_exact( ...
        cache, queries(index, :), model, struct());
    direct = stage8_k2_tcc_build_g_direct(queries(index, :), model, struct());
    relative_error = norm(cached - direct) / max(norm(direct), realmin);
    max_relative_error = max(max_relative_error, relative_error);
    assert(lookup_info.cache_hit && lookup_info.identity_valid && ...
        relative_error <= 1e-10, ...
        'test_exact_cache_matches_direct_g:Mismatch', ...
        'An exact cache column did not match direct G.');
end
[~, miss_info] = stage8_k2_tcc_lookup_exact( ...
    cache, [8.004, 10.0], model, struct());
assert(~miss_info.cache_hit && ...
    strcmp(miss_info.cache_miss_reason, 'OFF_GRID_EXACT_KEY'), ...
    'test_exact_cache_matches_direct_g:OffGrid', ...
    'An off-grid query was rounded into a cache hit.');
result = struct('pass', true, ...
    'max_relative_error', max_relative_error, ...
    'off_grid_miss_reason', miss_info.cache_miss_reason);
fprintf('test_exact_cache_matches_direct_g PASS relative=%.17g\n', ...
    max_relative_error);
end
