function result = test_compact_checkpoint_resume(repo_dir)
%TEST_COMPACT_CHECKPOINT_RESUME Verify runtime fields do not change science.

tool_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(tool_root, 'matlab'));
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
row = stage8_compact_row_template();
row.diagnostic_row_index = 1;
row.evaluation_row_index = 1;
row.diagnostic_trial_id = "UNIT_K2";
row.common_trial_id = "UNIT_K2";
row.global_trial_index = 1;
row.trial_type = "K2";
row.stratum_id = "UNIT";
row.measurement_config_id = "PRIMARY_RECT_E14_A31";
row.element_trial_hash = "UNIT_ELEMENT";
row.truth_used_in_fit_flag = false;
row.truth_used_in_classifier_flag = false;
rows = struct2table(row);
constants = stage8_compact_constants();
checkpoint = struct('protocol_version', constants.protocol_version, ...
    'checkpoint_contract_version', constants.checkpoint_contract_version, ...
    'diagnostic_trial_id', 'UNIT_K2', ...
    'global_trial_index', 1, 'trial_type', 'K2', 'stratum_id', 'UNIT', ...
    'profile_id', 2, ...
    'rows', rows, 'truth_metrics', struct('truth_used_in_fit_flag', false), ...
    'seeds', struct('parameter_seed', 1, 'element_noise_seed', 101, ...
    'separation_auxiliary_seed', 201), ...
    'element_trial_hash', 'UNIT_ELEMENT', ...
    'stage8_stable_code_identity_hash', ...
    constants.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', constants.stage8_plan_hash, ...
    'stage8_calibration_plan_hash', ...
    constants.stage8_calibration_plan_hash, ...
    'stage8_validation_plan_hash', constants.stage8_validation_plan_hash, ...
    'measurement_registry_hash', constants.measurement_registry_hash, ...
    'calibration_evidence_bundle_hash', ...
    constants.calibration_evidence_bundle_hash, ...
    'threshold_set_hash', constants.threshold_set_hash, ...
    'threshold_artifact_hashes', string({ ...
    constants.primary_threshold_artifact_hash, ...
    constants.sensitivity_threshold_artifact_hash}), ...
    'diagnostic_protocol_source_hash', 'UNIT_SOURCE', ...
    'completion_status', 'COMPLETE_PASS', 'runtime_sec', 10, ...
    'worker_id', 1, 'pid', 100, 'attempt_id', 'A', ...
    'created_utc', '2026-01-01T00:00:00.000Z');
left = stage8_compact_checkpoint_hash(checkpoint);
checkpoint.runtime_sec = 99;
checkpoint.worker_id = 4;
checkpoint.pid = 200;
checkpoint.attempt_id = 'B';
checkpoint.created_utc = '2026-01-02T00:00:00.000Z';
checkpoint.rows.row_runtime_sec(:) = 88;
right = stage8_compact_checkpoint_hash(checkpoint);
assert(strcmp(left, right));
result = struct('pass', true, 'scientific_content_hash', left, ...
    'runtime_independent_fields_pass', true);
clear path_cleanup
end
