function registry = stage8_compact_build_registry(context)
%STAGE8_COMPACT_BUILD_REGISTRY Materialize 108 independent element trials.

constants = stage8_compact_constants();
strata = context.plan.validation.K1.strata;
rows = cell(constants.element_trial_count, 1);
global_index = 0;
row_index = 1;
for stratum_index = 1:height(strata)
    stratum = strata(stratum_index, :);
    block = constants.k1_seed_base + constants.seed_block_stride * ...
        (stratum_index - 1);
    for trial_index = 1:10
        global_index = global_index + 1;
        trial_id = sprintf('CD_K1_L%d_N%d_T%02d', stratum.L, ...
            noise_number_local(stratum.noise_profile_id), trial_index);
        rows{global_index} = registry_row_local(global_index, row_index, ...
            trial_id, "K1", stratum, trial_index, 0, ...
            block + trial_index - 1, block + 100 + trial_index - 1, ...
            block + 200 + trial_index - 1, 2, false, NaN, NaN, NaN, ...
            NaN, NaN, NaN, NaN);
        row_index = row_index + 2;
    end
end

separations = [0.35,0.30,0.24,0.20,0.15,0.18,0.10,0.05];
snr_values = [6,6,0,0,0,-6,-6,-9];
secondary_power = [0,-6,-6,-12,-6,-6,-12,-12];
correlations = [0,0.9,0.9,0.9,0.99,0.9,0.99,0.99];
directions = [0,30,60,90,120,150,45,135];
offsets = [0,0;-0.10,0;0.10,0;0,-0.10;0,0.10; ...
    -0.10,-0.05;0.10,0.05;0,0];
for stratum_index = 1:height(strata)
    stratum = strata(stratum_index, :);
    block = constants.k2_seed_base + constants.seed_block_stride * ...
        (stratum_index - 1);
    for profile_index = 1:8
        global_index = global_index + 1;
        sentinel = ismember(profile_index, [1, 8]);
        expected_rows = 1 + double(sentinel);
        trial_id = sprintf('CD_K2_L%d_N%d_P%02d', stratum.L, ...
            noise_number_local(stratum.noise_profile_id), profile_index);
        correlation = correlations(profile_index);
        if stratum.L == 1, correlation = 1; end
        rows{global_index} = registry_row_local(global_index, row_index, ...
            trial_id, "K2", stratum, profile_index, profile_index, ...
            block + profile_index - 1, block + 100 + profile_index - 1, ...
            block + 200 + profile_index - 1, expected_rows, sentinel, ...
            separations(profile_index), snr_values(profile_index), ...
            secondary_power(profile_index), correlation, ...
            directions(profile_index), offsets(profile_index, 1), ...
            offsets(profile_index, 2));
        row_index = row_index + expected_rows;
    end
end
registry = struct2table(vertcat(rows{:}));
if height(registry) ~= constants.element_trial_count || ...
        row_index - 1 ~= constants.row_count || ...
        nnz(registry.trial_type == "K1") ~= constants.k1_element_trial_count || ...
        nnz(registry.trial_type == "K2") ~= constants.k2_element_trial_count
    error('stage8_compact_build_registry:Cardinality', ...
        'Compact diagnostic registry cardinality is invalid.');
end
end

function row = registry_row_local(global_index, row_start, trial_id, ...
    trial_type, stratum, trial_in_stratum, profile_id, parameter_seed, ...
    noise_seed, separation_seed, expected_rows, sentinel, separation, snr, ...
    secondary_power, correlation, direction, offset_az, offset_el)
row = struct('global_trial_index', double(global_index), ...
    'row_start_index', double(row_start), ...
    'expected_row_count', double(expected_rows), ...
    'diagnostic_trial_id', string(trial_id), 'trial_type', string(trial_type), ...
    'stratum_index', double(stratum.stratum_index), ...
    'stratum_id', string(stratum.stratum_id), 'L', double(stratum.L), ...
    'noise_profile_id', string(stratum.noise_profile_id), ...
    'trial_index_within_stratum', double(trial_in_stratum), ...
    'profile_id', double(profile_id), ...
    'parameter_seed', double(parameter_seed), ...
    'element_noise_seed', double(noise_seed), ...
    'separation_auxiliary_seed', double(separation_seed), ...
    'sentinel_flag', logical(sentinel), ...
    'separation_deg', double(separation), 'snr_db', double(snr), ...
    'secondary_power_db', double(secondary_power), ...
    'correlation_magnitude', double(correlation), ...
    'direction_deg', double(direction), 'center_offset_az_deg', ...
    double(offset_az), 'center_offset_el_deg', double(offset_el));
end

function value = noise_number_local(noise_profile_id)
if string(noise_profile_id) == "WHITE", value = 1; else, value = 2; end
end
