function final = stage8_compact_merge_report(repo_dir, runtime_root)
%STAGE8_COMPACT_MERGE_REPORT Validate 108 checkpoints and write four outputs.

repo_dir = char(string(repo_dir));
runtime_root = char(string(runtime_root));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
addpath(fullfile(repo_dir, 'tools', 'stage8_1b_validation_sharded', 'matlab'));
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
protocol = jsondecode(fileread(fullfile(runtime_root, 'protocol.json')));
context = stage8_compact_context(repo_dir, true);
stage8_compact_verify_protocol(protocol, context);
constants = context.compact_constants;
if double(protocol.element_trial_count) ~= constants.element_trial_count || ...
        double(protocol.row_count) ~= constants.row_count || ...
        numel(dir(fullfile(runtime_root, 'tmp', '*.tmp'))) ~= 0 || ...
        numel(dir(fullfile(runtime_root, 'workers', '*.current.lock'))) ~= 0
    error('stage8_compact_merge_report:RuntimeState', ...
        'Finalize requires the complete formal compact runtime with no tmp/lock.');
end
registry = context.compact_registry;
checkpoint_files = dir(fullfile(runtime_root, 'checkpoints', '*.mat'));
if numel(checkpoint_files) ~= constants.element_trial_count
    error('stage8_compact_merge_report:CheckpointCount', ...
        'Finalize requires exactly 108 checkpoint files.');
end
cells = cell(height(registry), 1);
scientific_hashes = strings(height(registry), 1);
for index = 1:height(registry)
    path_now = fullfile(runtime_root, 'checkpoints', ...
        [char(registry.diagnostic_trial_id(index)), '.mat']);
    stage8_compact_validate_checkpoint(path_now, protocol, registry(index, :));
    loaded = load(path_now, 'checkpoint', '-mat');
    cells{index} = loaded.checkpoint.rows;
    scientific_hashes(index) = ...
        string(loaded.checkpoint.scientific_content_hash);
end
trials = sortrows(vertcat(cells{:}), 'diagnostic_row_index');
validate_trials_local(trials, registry, constants);
[~, calibration_before] = ...
    capture_stage8_1_calibration_snapshot(context.calibration.artifact_root);

k1 = trials(trials.trial_type == "K1", :);
k2 = trials(trials.trial_type == "K2", :);
[k1_summary, ~, ~] = summarize_stage8_k1_validation( ...
    k1, context.plan.validation.K1);
metrics = build_summary_local(k1, k2, k1_summary, constants);
profiles = build_profiles_local(k2);
diagnostic = diagnostic_conclusion_local(k1, k2, constants);

output_root = fullfile(repo_dir, 'innovation-mining');
stem = fullfile(output_root, '23_stage8_compact_algorithm_diagnostic');
paths = { [stem, '.md'], [stem, '_trials.csv'], ...
    [stem, '_summary.csv'], [stem, '_profiles.csv'] };
if any(cellfun(@isfile, paths))
    error('stage8_compact_merge_report:ExistingOutput', ...
        'Compact diagnostic outputs already exist and will not be overwritten.');
end
temporary = { [stem, '.tmp.md'], [stem, '_trials.tmp.csv'], ...
    [stem, '_summary.tmp.csv'], [stem, '_profiles.tmp.csv'] };
temporary_cleanup = onCleanup(@() delete_temporary_local(temporary));
writetable(trials, temporary{2});
writetable(metrics, temporary{3});
writetable(profiles, temporary{4});
write_report_local(temporary{1}, protocol, diagnostic, metrics, ...
    profiles, scientific_hashes);
if height(readtable(temporary{2}, 'TextType', 'string')) ~= 180 || ...
        isempty(readtable(temporary{3}, 'TextType', 'string')) || ...
        isempty(readtable(temporary{4}, 'TextType', 'string'))
    error('stage8_compact_merge_report:OutputValidation', ...
        'Temporary output validation failed.');
end
[~, calibration_after] = ...
    capture_stage8_1_calibration_snapshot(context.calibration.artifact_root);
if ~strcmp(calibration_before, calibration_after) || ...
        ~strcmp(calibration_after, context.calibration_snapshot_hash)
    error('stage8_compact_merge_report:CalibrationMutation', ...
        'Calibration artifacts changed during finalize.');
end
for index = 1:numel(paths)
    [moved, message] = movefile(temporary{index}, paths{index});
    if ~moved
        error('stage8_compact_merge_report:AtomicMove', '%s', message);
    end
end
clear temporary_cleanup
output_hashes = strings(numel(paths), 1);
for index = 1:numel(paths)
    output_hashes(index) = string(stage8_sha256_file(paths{index}));
end
final = struct('status', 'STAGE8_COMPACT_DIAGNOSTIC_FINALIZED', ...
    'diagnostic_conclusion', diagnostic.conclusion, ...
    'element_trial_count', 108, 'row_count', 180, ...
    'k1_element_trial_count', 60, 'k1_row_count', 120, ...
    'k2_element_trial_count', 48, 'k2_row_count', 60, ...
    'output_paths', {paths}, 'output_sha256', output_hashes, ...
    'calibration_snapshot_hash', calibration_after, ...
    'formal_6000_trial_status', ...
    'FULL_STAGE8_1B_K1_VALIDATION_DEFERRED_NOT_FAILED', ...
    'stage8_2_executed_flag', false, ...
    'finalized_utc', utc_now_local());
stage8_1b_write_json_atomic(fullfile(runtime_root, 'merged', ...
    'finalization_audit.json'), final);
clear path_cleanup
end

function delete_temporary_local(paths)
for index = 1:numel(paths)
    if isfile(paths{index}), delete(paths{index}); end
end
end

function validate_trials_local(trials, registry, constants)
if height(trials) ~= constants.row_count || ...
        numel(unique(string(trials.diagnostic_trial_id))) ~= ...
        constants.element_trial_count || ...
        numel(unique(double(trials.diagnostic_row_index))) ~= ...
        constants.row_count || any(trials.truth_used_in_fit_flag) || ...
        any(trials.truth_used_in_classifier_flag)
    error('stage8_compact_merge_report:Cardinality', ...
        'Merged trial cardinality or truth isolation failed.');
end
k1 = trials.trial_type == "K1";
k2 = trials.trial_type == "K2";
if nnz(k1) ~= constants.k1_row_count || ...
        nnz(k2) ~= constants.k2_row_count || ...
        nnz(k2 & trials.measurement_config_id == ...
        string(constants.primary_measurement_config_id)) ~= 48 || ...
        nnz(k2 & trials.measurement_config_id == ...
        string(constants.sensitivity_measurement_config_id)) ~= 12
    error('stage8_compact_merge_report:TrialTypes', ...
        'K1/K2 configuration cardinality is invalid.');
end
for index = 1:height(context_strata_local(registry))
    strata = context_strata_local(registry);
    id = strata(index);
    if nnz(k1 & trials.stratum_id == id) ~= 20 || ...
            nnz(k2 & trials.stratum_id == id) ~= 10
        error('stage8_compact_merge_report:StratumCoverage', ...
            'Every stratum requires 20 K1 rows and 10 K2 rows.');
    end
end
end

function values = context_strata_local(registry)
values = unique(string(registry.stratum_id), 'stable');
end

function summary = build_summary_local(k1, k2, k1_summary, constants)
rows = cell(0, 1);
primary_id = string(constants.primary_measurement_config_id);
sensitivity_id = string(constants.sensitivity_measurement_config_id);
for config = [primary_id, sensitivity_id]
    selected = k1.measurement_config_id == config;
    state = string(k1.state(selected));
    rows{end + 1, 1} = metric_row_local('K1','OVERALL',config, ...
        'false_split_rate', nnz(ismember(state, ...
        ["K2_RESOLVED","K2_UNRESOLVED"])), nnz(selected)); %#ok<AGROW>
    rows{end + 1, 1} = metric_row_local('K1','OVERALL',config, ...
        'nondecision_rate', nnz(ismember(state, ...
        ["SEARCH_NOT_CONVERGED","NUMERIC_RANK_DEFICIENT"])), ...
        nnz(selected)); %#ok<AGROW>
end
strata = unique(string(k1.stratum_id), 'stable');
for index = 1:numel(strata)
    selected = k1.measurement_config_id == primary_id & ...
        k1.stratum_id == strata(index);
    state = string(k1.state(selected));
    rows{end + 1, 1} = metric_row_local('K1',strata(index), ...
        primary_id,'false_split_rate',nnz(ismember(state, ...
        ["K2_RESOLVED","K2_UNRESOLVED"])),nnz(selected)); %#ok<AGROW>
end
for config = [primary_id, sensitivity_id]
    selected = k2.measurement_config_id == config;
    valid = k2.valid_k1_fit_flag(selected) & k2.valid_k2_fit_flag(selected);
    rows{end + 1, 1} = metric_row_local('K2','OVERALL',config, ...
        'valid_fit_fraction', nnz(valid), nnz(selected)); %#ok<AGROW>
    rows{end + 1, 1} = metric_row_local('K2','OVERALL',config, ...
        'lrt_split_detection_rate', ...
        nnz(k2.lrt_split_detected_flag(selected)), nnz(selected)); %#ok<AGROW>
    rows{end + 1, 1} = metric_row_local('K2','OVERALL',config, ...
        'joint_refinement_improvement_fraction', ...
        nnz(k2.joint_refinement_improved_flag(selected) & valid), ...
        nnz(valid)); %#ok<AGROW>
    rows{end + 1, 1} = scalar_metric_row_local('K2','OVERALL',config, ...
        'median_joint_2d_rmse_deg', ...
        median(k2.joint_2d_rmse_deg(selected & ...
        k2.valid_k2_fit_flag), 'omitnan')); %#ok<AGROW>
    rows{end + 1, 1} = scalar_metric_row_local('K2','OVERALL',config, ...
        'median_separation_vector_error_deg', ...
        median(k2.separation_vector_error_deg(selected & ...
        k2.valid_k2_fit_flag), 'omitnan')); %#ok<AGROW>
end
for index = 1:height(k1_summary)
    row = k1_summary(index, :);
    rows{end + 1, 1} = scalar_metric_row_local('K1_WILSON_DIAGNOSTIC', ...
        row.summary_scope, row.measurement_config_id, ...
        'false_split_wilson_upper_not_formal_gate', ...
        row.false_split_wilson_upper); %#ok<AGROW>
end
summary = struct2table(vertcat(rows{:}));
end

function profiles = build_profiles_local(k2)
keys = unique(k2(:, {'measurement_config_id','stratum_id','L', ...
    'noise_profile_id','profile_id'}), 'rows', 'stable');
rows = cell(height(keys), 1);
for index = 1:height(keys)
    selected = k2.measurement_config_id == keys.measurement_config_id(index) & ...
        k2.stratum_id == keys.stratum_id(index) & ...
        k2.profile_id == keys.profile_id(index);
    current = k2(selected, :);
    valid = current.valid_k1_fit_flag & current.valid_k2_fit_flag;
    rows{index} = struct('measurement_config_id', ...
        keys.measurement_config_id(index), ...
        'stratum_id', keys.stratum_id(index), 'L', keys.L(index), ...
        'noise_profile_id', keys.noise_profile_id(index), ...
        'profile_id', keys.profile_id(index), 'row_count', height(current), ...
        'valid_fit_fraction', nnz(valid) / height(current), ...
        'lrt_split_detection_rate', ...
        nnz(current.lrt_split_detected_flag) / height(current), ...
        'separation_evaluated_rate', ...
        nnz(current.separation_evaluated_flag) / height(current), ...
        'joint_refinement_improvement_fraction', ...
        ratio_local(nnz(current.joint_refinement_improved_flag & valid), ...
        nnz(valid)), 'mean_joint_2d_rmse_deg', ...
        mean(current.joint_2d_rmse_deg(valid), 'omitnan'), ...
        'mean_separation_vector_error_deg', ...
        mean(current.separation_vector_error_deg(valid), 'omitnan'));
end
profiles = struct2table(vertcat(rows{:}));
end

function diagnostic = diagnostic_conclusion_local(k1, k2, constants)
primary = string(constants.primary_measurement_config_id);
k1p = k1.measurement_config_id == primary;
k1_state = string(k1.state(k1p));
false_split_rate = nnz(ismember(k1_state, ...
    ["K2_RESOLVED","K2_UNRESOLVED"])) / nnz(k1p);
nondecision_rate = nnz(ismember(k1_state, ...
    ["SEARCH_NOT_CONVERGED","NUMERIC_RANK_DEFICIENT"])) / nnz(k1p);
k2p = k2.measurement_config_id == primary;
valid = k2.valid_k1_fit_flag(k2p) & k2.valid_k2_fit_flag(k2p);
valid_fraction = nnz(valid) / nnz(k2p);
detection_rate = nnz(k2.lrt_split_detected_flag(k2p)) / nnz(k2p);
improvement_fraction = ratio_local(nnz( ...
    k2.joint_refinement_improved_flag(k2p) & valid), nnz(valid));
strata = unique(string(k2.stratum_id(k2p)), 'stable');
all_strata_valid = true;
for index = 1:numel(strata)
    selected = k2p & k2.stratum_id == strata(index);
    all_strata_valid = all_strata_valid && any( ...
        k2.valid_k1_fit_flag(selected) & k2.valid_k2_fit_flag(selected));
end
promising = false_split_rate <= 0.10 && nondecision_rate <= 0.10 && ...
    valid_fraction >= 0.85 && detection_rate >= 0.70 && ...
    improvement_fraction >= 0.60 && all_strata_valid;
clear_failure = false_split_rate > 0.25 || nondecision_rate > 0.25 || ...
    valid_fraction < 0.70 || detection_rate < 0.30;
if promising
    conclusion = 'STAGE8_COMPACT_DIAGNOSTIC_PROMISING';
elseif clear_failure
    conclusion = 'STAGE8_COMPACT_DIAGNOSTIC_CLEAR_FAILURE';
else
    conclusion = 'STAGE8_COMPACT_DIAGNOSTIC_MIXED';
end
sentinel = k2.sentinel_flag;
primary_sentinel = sentinel & k2.measurement_config_id == primary;
sensitivity_sentinel = sentinel & k2.measurement_config_id == ...
    string(constants.sensitivity_measurement_config_id);
diagnostic = struct('conclusion', conclusion, ...
    'k1_primary_false_split_rate', false_split_rate, ...
    'k1_primary_nondecision_rate', nondecision_rate, ...
    'k2_primary_valid_fit_fraction', valid_fraction, ...
    'k2_primary_lrt_split_detection_rate', detection_rate, ...
    'k2_primary_joint_refinement_improvement_fraction', ...
    improvement_fraction, 'all_six_strata_have_valid_k2_fit', ...
    all_strata_valid, 'k2_primary_median_joint_2d_rmse_deg', ...
    median(k2.joint_2d_rmse_deg(k2p & k2.valid_k2_fit_flag), 'omitnan'), ...
    'k2_primary_median_separation_vector_error_deg', ...
    median(k2.separation_vector_error_deg(k2p & ...
    k2.valid_k2_fit_flag), 'omitnan'), ...
    'sentinel_primary_lrt_detection_rate', ...
    mean(k2.lrt_split_detected_flag(primary_sentinel)), ...
    'sentinel_full_parent_lrt_detection_rate', ...
    mean(k2.lrt_split_detected_flag(sensitivity_sentinel)));
end

function row = metric_row_local(section, scope, config, metric, numerator, denominator)
row = struct('section', string(section), 'scope', string(scope), ...
    'measurement_config_id', string(config), 'metric', string(metric), ...
    'numerator', double(numerator), 'denominator', double(denominator), ...
    'value', ratio_local(numerator, denominator));
end

function row = scalar_metric_row_local(section, scope, config, metric, value)
row = struct('section', string(section), 'scope', string(scope), ...
    'measurement_config_id', string(config), 'metric', string(metric), ...
    'numerator', NaN, 'denominator', NaN, 'value', double(value));
end

function value = ratio_local(numerator, denominator)
if denominator == 0, value = NaN; else, value = numerator / denominator; end
end

function write_report_local(path_now, protocol, d, summary, profiles, hashes)
fid = fopen(path_now, 'w', 'n', 'UTF-8');
if fid < 0, error('stage8_compact_merge_report:Report', ...
        'Unable to create diagnostic report.'); end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# Stage8 Compact K1/K2 Algorithm Diagnostic\n\n');
fprintf(fid, '**DIAGNOSTIC_ONLY**  \n');
fprintf(fid, '**NOT_FORMAL_STAGE8_1_K1_VALIDATION**  \n');
fprintf(fid, '**DOES_NOT_AUTHORIZE_STAGE8_2**  \n');
fprintf(fid, '**FULL_6000_TRIAL_VALIDATION_DEFERRED_NOT_FAILED**\n\n');
fprintf(fid, '- Protocol: `%s`\n', protocol.protocol_version);
fprintf(fid, '- Runner commit: `%s`\n', protocol.protocol_runner_commit);
fprintf(fid, '- Execution mode: `%s` (%d workers)\n', ...
    protocol.selected_execution_mode, protocol.selected_worker_count);
fprintf(fid, '- Element trials / rows: 108 / 180\n');
fprintf(fid, '- Scientific checkpoint hashes: %d valid\n\n', numel(hashes));
fprintf(fid, '## Diagnostic Conclusion\n\n`%s`\n\n', d.conclusion);
fprintf(fid, 'These thresholds are screening heuristics, not a formal Wilson gate.\n\n');
fprintf(fid, '| Metric | Value |\n|---|---:|\n');
fprintf(fid, '| PRIMARY K1 false-split point rate | %.6f |\n', ...
    d.k1_primary_false_split_rate);
fprintf(fid, '| PRIMARY K1 nondecision point rate | %.6f |\n', ...
    d.k1_primary_nondecision_rate);
fprintf(fid, '| PRIMARY K2 valid-fit fraction | %.6f |\n', ...
    d.k2_primary_valid_fit_fraction);
fprintf(fid, '| PRIMARY K2 LRT split-detection rate | %.6f |\n', ...
    d.k2_primary_lrt_split_detection_rate);
fprintf(fid, '| PRIMARY K2 joint-refinement improvement fraction | %.6f |\n', ...
    d.k2_primary_joint_refinement_improvement_fraction);
fprintf(fid, '| PRIMARY K2 median joint 2D RMSE (deg) | %.6g |\n', ...
    d.k2_primary_median_joint_2d_rmse_deg);
fprintf(fid, '| PRIMARY K2 median separation-vector error (deg) | %.6g |\n', ...
    d.k2_primary_median_separation_vector_error_deg);
fprintf(fid, '| PRIMARY sentinel LRT detection | %.6f |\n', ...
    d.sentinel_primary_lrt_detection_rate);
fprintf(fid, '| FULL_PARENT sentinel LRT detection | %.6f |\n', ...
    d.sentinel_full_parent_lrt_detection_rate);
fprintf(fid, '\nAll six strata contain a valid K2 fit: `%s`.\n\n', ...
    string(d.all_six_strata_have_valid_k2_fit));
fprintf(fid, 'The summary CSV contains %d diagnostic metric rows; ', height(summary));
fprintf(fid, 'the profile CSV contains %d configuration/profile rows.\n', ...
    height(profiles));
fprintf(fid, '\nStage8.2 executed: `false`.\n');
clear cleanup
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
