function audit = stage8_compact_validate_checkpoint(path_now, protocol, spec)
%STAGE8_COMPACT_VALIDATE_CHECKPOINT Validate one immutable element trial.

if ischar(protocol) || (isstring(protocol) && isscalar(protocol))
    protocol = jsondecode(fileread(char(protocol)));
end
loaded = load(char(string(path_now)), 'checkpoint', '-mat');
if ~isfield(loaded, 'checkpoint') || ...
        ~(isstruct(loaded.checkpoint) && isscalar(loaded.checkpoint))
    error('stage8_compact_validate_checkpoint:Payload', ...
        'Checkpoint must contain one scalar checkpoint struct.');
end
checkpoint = loaded.checkpoint;
constants = stage8_compact_constants();
required = {'protocol_version','checkpoint_contract_version', ...
    'diagnostic_trial_id','global_trial_index','trial_type','stratum_id', ...
    'profile_id','rows','truth_metrics','seeds','element_trial_hash', ...
    'stage8_stable_code_identity_hash','stage8_plan_hash', ...
    'stage8_calibration_plan_hash','stage8_validation_plan_hash', ...
    'measurement_registry_hash','calibration_evidence_bundle_hash', ...
    'threshold_set_hash','threshold_artifact_hashes', ...
    'diagnostic_protocol_source_hash','runtime_sec', ...
    'separation_trigger_count','completion_status', ...
    'scientific_content_hash','worker_id','pid','attempt_id', ...
    'created_utc'};
if ~all(isfield(checkpoint, required))
    error('stage8_compact_validate_checkpoint:Contract', ...
        'Checkpoint is missing required fields.');
end
protocol_fields = {'protocol_version','checkpoint_contract_version', ...
    'stage8_stable_code_identity_hash','stage8_plan_hash', ...
    'stage8_calibration_plan_hash','stage8_validation_plan_hash', ...
    'measurement_registry_hash','calibration_evidence_bundle_hash', ...
    'threshold_set_hash'};
for index = 1:numel(protocol_fields)
    field = protocol_fields{index};
    if ~strcmp(string(checkpoint.(field)), string(protocol.(field)))
        error('stage8_compact_validate_checkpoint:ProtocolIdentity', ...
            'Checkpoint field %s differs from protocol.', field);
    end
end
if ~strcmp(string(checkpoint.diagnostic_protocol_source_hash), ...
        string(protocol.diagnostic_protocol_source_hash))
    error('stage8_compact_validate_checkpoint:ToolIdentity', ...
        'Checkpoint tool source hash differs from protocol.');
end
expected_artifacts = string({constants.primary_threshold_artifact_hash, ...
    constants.sensitivity_threshold_artifact_hash});
if ~isequal(string(checkpoint.threshold_artifact_hashes), ...
        expected_artifacts)
    error('stage8_compact_validate_checkpoint:ThresholdArtifacts', ...
        'Checkpoint threshold artifact identities changed.');
end
if ~(istable(spec) && height(spec) == 1) || ...
        string(checkpoint.diagnostic_trial_id) ~= ...
        string(spec.diagnostic_trial_id) || ...
        double(checkpoint.global_trial_index) ~= ...
        double(spec.global_trial_index) || ...
        string(checkpoint.trial_type) ~= string(spec.trial_type) || ...
        double(checkpoint.profile_id) ~= double(spec.profile_id) || ...
        string(checkpoint.stratum_id) ~= string(spec.stratum_id)
    error('stage8_compact_validate_checkpoint:Registry', ...
        'Checkpoint differs from the compact registry.');
end
rows = checkpoint.rows;
required_rows = fieldnames(stage8_compact_row_template());
if ~(istable(rows) && height(rows) == spec.expected_row_count) || ...
        ~all(ismember(required_rows, rows.Properties.VariableNames)) || ...
        numel(unique(string(rows.diagnostic_trial_id))) ~= 1 || ...
        string(rows.diagnostic_trial_id(1)) ~= ...
        string(spec.diagnostic_trial_id) || ...
        any(double(rows.global_trial_index) ~= spec.global_trial_index) || ...
        any(string(rows.element_trial_hash) ~= ...
        string(checkpoint.element_trial_hash))
    error('stage8_compact_validate_checkpoint:Rows', ...
        'Checkpoint rows do not form one complete element trial.');
end
expected_indices = (double(spec.row_start_index): ...
    double(spec.row_start_index + spec.expected_row_count - 1)).';
if ~isequal(sort(double(rows.diagnostic_row_index)), expected_indices)
    error('stage8_compact_validate_checkpoint:RowIndex', ...
        'Checkpoint diagnostic row indices are invalid.');
end
if any(rows.truth_used_in_fit_flag) || ...
        any(rows.truth_used_in_classifier_flag) || ...
        ~strcmp(string(checkpoint.completion_status), "COMPLETE_PASS")
    error('stage8_compact_validate_checkpoint:TruthIsolation', ...
        'Truth isolation or completion contract failed.');
end
expected_configs = string(constants.primary_measurement_config_id);
if string(spec.trial_type) == "K1" || logical(spec.sentinel_flag)
    expected_configs(end + 1, 1) = string( ...
        constants.sensitivity_measurement_config_id);
end
if ~isequal(sort(string(rows.measurement_config_id)), ...
        sort(expected_configs))
    error('stage8_compact_validate_checkpoint:ConfigurationCoverage', ...
        'Checkpoint configuration rows differ from the registry contract.');
end
computed = stage8_compact_checkpoint_hash(checkpoint);
if ~strcmp(string(computed), string(checkpoint.scientific_content_hash))
    error('stage8_compact_validate_checkpoint:ScientificHash', ...
        'Checkpoint scientific hash is invalid.');
end
audit = struct('valid', true, ...
    'diagnostic_trial_id', char(string(checkpoint.diagnostic_trial_id)), ...
    'global_trial_index', double(checkpoint.global_trial_index), ...
    'trial_type', char(string(checkpoint.trial_type)), ...
    'row_count', height(rows), 'runtime_sec', double(checkpoint.runtime_sec), ...
    'separation_trigger_count', ...
    double(checkpoint.separation_trigger_count), ...
    'scientific_content_hash', char(string(computed)), ...
    'created_utc', char(string(checkpoint.created_utc)));
end
