function result = stage8_compact_gate_c2(repo_dir, output_root)
%STAGE8_COMPACT_GATE_C2 Verify deterministic K2 generation and truth isolation.

repo_dir = char(string(repo_dir));
output_root = char(string(output_root));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
addpath(fullfile(repo_dir, 'tools', 'stage8_1b_validation_sharded', 'matlab'));
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if ~isfolder(output_root), mkdir(output_root); end
result_path = fullfile(output_root, 'gate_c2_result.json');
result = struct('gate_c2_pass', false, ...
    'status', 'COMPACT_GATE_C2_K2_GENERATION_FAIL_STOPPED', ...
    'checked_utc', utc_now_local(), 'last_error', '');
stage8_1b_write_json_atomic(result_path, result);
try
    context = stage8_compact_context(repo_dir, true);
    registry = context.compact_registry;
    selectors = {1,"WHITE",1; 4,"STAGE5_TOEPLITZ_CORRELATED",3; ...
        8,"WHITE",5; 8,"STAGE5_TOEPLITZ_CORRELATED",7};
    labels = ["L1_WHITE_EASY";"L4_CORRELATED_MODERATE"; ...
        "L8_WHITE_CLOSE_HIGH_CORRELATION";"L8_CORRELATED_HARD"];
    details = repmat(struct('label', '', 'diagnostic_trial_id', '', ...
        'element_trial_hash', '', 'y_num2hex_equality', false, ...
        'element_trial_hash_equality', false, ...
        'source_total_energy_contract_pass', false, ...
        'secondary_power_contract_pass', false, ...
        'correlation_contract_pass', false, ...
        'endpoints_in_domain_pass', false, ...
        'seed_roles_separated_pass', false, ...
        'truth_used_in_fit_flag', true, ...
        'truth_used_in_classifier_flag', true), size(selectors, 1), 1);
    all_pass = true;
    for index = 1:size(selectors, 1)
        selected = registry(registry.trial_type == "K2" & ...
            registry.L == selectors{index, 1} & ...
            registry.noise_profile_id == selectors{index, 2} & ...
            registry.profile_id == selectors{index, 3}, :);
        if height(selected) ~= 1
            error('stage8_compact_gate_c2:Selection', ...
                'C2 selector did not resolve exactly one K2 trial.');
        end
        [left, left_contract] = ...
            stage8_compact_generate_k2_trial(selected, context);
        [right, right_contract] = ...
            stage8_compact_generate_k2_trial(selected, context);
        repeated_y = complex_num2hex_equal_local( ...
            left.Y_element, right.Y_element);
        repeated_hash = strcmp(left.element_trial_hash, ...
            right.element_trial_hash);
        contract_pass = left_contract.source_total_energy_contract_pass && ...
            left_contract.secondary_power_contract_pass && ...
            left_contract.correlation_contract_pass && ...
            left_contract.endpoints_in_domain_pass && ...
            left_contract.seed_roles_separated_pass && ...
            ~left_contract.truth_used_in_fit_flag && ...
            ~left_contract.truth_used_in_classifier_flag && ...
            isequal(left_contract, right_contract);
        if selected.L == 1
            contract_pass = contract_pass && ...
                left_contract.correlation_magnitude == 1;
        end
        details(index) = struct('label', char(labels(index)), ...
            'diagnostic_trial_id', char(selected.diagnostic_trial_id), ...
            'element_trial_hash', left.element_trial_hash, ...
            'y_num2hex_equality', repeated_y, ...
            'element_trial_hash_equality', repeated_hash, ...
            'source_total_energy_contract_pass', ...
            left_contract.source_total_energy_contract_pass, ...
            'secondary_power_contract_pass', ...
            left_contract.secondary_power_contract_pass, ...
            'correlation_contract_pass', ...
            left_contract.correlation_contract_pass, ...
            'endpoints_in_domain_pass', ...
            left_contract.endpoints_in_domain_pass, ...
            'seed_roles_separated_pass', ...
            left_contract.seed_roles_separated_pass, ...
            'truth_used_in_fit_flag', ...
            left_contract.truth_used_in_fit_flag, ...
            'truth_used_in_classifier_flag', ...
            left_contract.truth_used_in_classifier_flag);
        all_pass = all_pass && repeated_y && repeated_hash && contract_pass;
    end
    sentinel = registry(registry.trial_type == "K2" & ...
        registry.L == 1 & registry.noise_profile_id == "WHITE" & ...
        registry.profile_id == 1, :);
    [sentinel_trial, ~] = stage8_compact_generate_k2_trial(sentinel, context);
    constants = context.compact_constants;
    config_ids = [string(constants.primary_measurement_config_id); ...
        string(constants.sensitivity_measurement_config_id)];
    shared_y = true;
    for index = 1:numel(config_ids)
        model = resolve_stage8_measurement_model( ...
            context.plan.measurement_model_registry, config_ids(index), ...
            sentinel.noise_profile_id);
        data = build_stage8_full_data_from_element( ...
            sentinel_trial.Y_element, model, struct());
        shared_y = shared_y && complex_num2hex_equal_local( ...
            data.Y_element, sentinel_trial.Y_element);
    end
    all_pass = all_pass && shared_y;
    if ~all_pass
        error('stage8_compact_gate_c2:Contract', ...
            'One or more C2 generation contracts failed.');
    end
    result = struct('gate_c2_pass', true, ...
        'status', 'COMPACT_GATE_C2_K2_GENERATION_PASS', ...
        'checked_utc', utc_now_local(), 'trial_count', numel(details), ...
        'details', details, ...
        'primary_full_parent_shared_y_element_pass', shared_y, ...
        'truth_used_in_fit_flag', false, ...
        'truth_used_in_classifier_flag', false, ...
        'last_error', '');
    stage8_1b_write_json_atomic(result_path, result);
catch exception
    result.checked_utc = utc_now_local();
    result.last_error = getReport(exception, 'extended', 'hyperlinks', 'off');
    stage8_1b_write_json_atomic(result_path, result);
    rethrow(exception);
end
clear path_cleanup
end

function pass = complex_num2hex_equal_local(left, right)
pass = isequal(num2hex(real(left)), num2hex(real(right))) && ...
    isequal(num2hex(imag(left)), num2hex(imag(right)));
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
