function stage8_compact_verify_protocol(protocol, context)
%STAGE8_COMPACT_VERIFY_PROTOCOL Verify immutable protocol and repository.

constants = stage8_compact_constants();
required = {'protocol_version','execution_authorization','protocol_role', ...
    'repo_dir','runtime_root', ...
    'protocol_runner_commit','diagnostic_protocol_source_hash', ...
    'threshold_evidence_commit','compact_anchor_commit', ...
    'stage8_stable_code_identity_hash','stage8_plan_hash', ...
    'stage8_calibration_plan_hash','stage8_validation_plan_hash', ...
    'measurement_registry_hash','calibration_evidence_bundle_hash', ...
    'threshold_set_hash','calibration_snapshot_hash','matlab_release', ...
    'threads_per_worker','selected_worker_count','trial_indices', ...
    'element_trial_count','row_count','Bsep','partition_rule', ...
    'checkpoint_contract_version','formal_6000_trial_status', ...
    'formal_6000_trial_authorization_status','stage8_2_executed_flag', ...
    'stage8_2_authorized_flag'};
if ~(isstruct(protocol) && isscalar(protocol) && ...
        all(isfield(protocol, required)))
    error('stage8_compact_verify_protocol:Contract', ...
        'Immutable protocol is incomplete.');
end
actual = [string(protocol.protocol_version), ...
    string(protocol.execution_authorization), ...
    string(protocol.threshold_evidence_commit), ...
    string(protocol.compact_anchor_commit), ...
    string(protocol.stage8_stable_code_identity_hash), ...
    string(protocol.stage8_plan_hash), ...
    string(protocol.stage8_calibration_plan_hash), ...
    string(protocol.stage8_validation_plan_hash), ...
    string(protocol.measurement_registry_hash), ...
    string(protocol.calibration_evidence_bundle_hash), ...
    string(protocol.threshold_set_hash), ...
    string(protocol.checkpoint_contract_version)];
expected = [string(constants.protocol_version), ...
    string(constants.execution_authorization), ...
    string(constants.threshold_evidence_commit), ...
    string(constants.compact_anchor_commit), ...
    string(constants.stage8_stable_code_identity_hash), ...
    string(constants.stage8_plan_hash), ...
    string(constants.stage8_calibration_plan_hash), ...
    string(constants.stage8_validation_plan_hash), ...
    string(constants.measurement_registry_hash), ...
    string(constants.calibration_evidence_bundle_hash), ...
    string(constants.threshold_set_hash), ...
    string(constants.checkpoint_contract_version)];
if ~isequal(actual, expected) || ...
        ~strcmp(string(protocol.calibration_snapshot_hash), ...
        string(context.calibration_snapshot_hash)) || ...
        ~strcmp(string(protocol.repo_dir), string(context.repo_dir)) || ...
        ~strcmp(string(protocol.formal_6000_trial_status), ...
        "FULL_STAGE8_1B_K1_VALIDATION_DEFERRED_NOT_FAILED") || ...
        ~strcmp(string(protocol.formal_6000_trial_authorization_status), ...
        "FORMAL_6000_TRIAL_AUTHORIZATION_SUSPENDED") || ...
        logical(protocol.stage8_2_executed_flag) || ...
        logical(protocol.stage8_2_authorized_flag)
    error('stage8_compact_verify_protocol:FrozenIdentity', ...
        'Protocol frozen identities differ from committed evidence.');
end
worker_count = double(protocol.selected_worker_count);
indices = double(protocol.trial_indices(:));
registry = context.compact_registry;
if ~ismember(worker_count, 1:4) || numel(unique(indices)) ~= numel(indices) || ...
        any(indices < 1 | indices > height(registry)) || ...
        double(protocol.element_trial_count) ~= numel(indices) || ...
        double(protocol.row_count) ~= sum(registry.expected_row_count(indices)) || ...
        double(protocol.Bsep) ~= 199 || ...
        ~strcmp(string(protocol.matlab_release), "R2022b") || ...
        double(protocol.threads_per_worker) ~= 1 || ...
        ~strcmp(string(protocol.partition_rule), ...
        "MOD_GLOBAL_TRIAL_INDEX_MINUS_ONE")
    error('stage8_compact_verify_protocol:RuntimeContract', ...
        'Worker, registry, MATLAB, or Bsep protocol fields are invalid.');
end
if ~strcmp(version('-release'), '2022b') || maxNumCompThreads ~= 1
    error('stage8_compact_verify_protocol:SingleThread', ...
        'Workers require MATLAB R2022b -singleCompThread.');
end
if ~isempty(ver('parallel')) && ~isempty(gcp('nocreate'))
    error('stage8_compact_verify_protocol:ParallelPool', ...
        'Parallel pools are forbidden.');
end
[head_status, head] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', context.repo_dir));
[git_status, worktree] = system(sprintf( ...
    'git -C "%s" status --porcelain=v1 --untracked-files=all', ...
    context.repo_dir));
if head_status ~= 0 || git_status ~= 0 || ...
        ~strcmp(strtrim(head), char(string(protocol.protocol_runner_commit))) || ...
        ~isempty(strtrim(worktree)) || ...
        ~strcmp(string(stage8_compact_source_hash(context.repo_dir)), ...
        string(protocol.diagnostic_protocol_source_hash))
    error('stage8_compact_verify_protocol:RepositoryState', ...
        'HEAD, worktree, or compact tool source differs from protocol.');
end
verify_ancestry_and_step_local(context.repo_dir, constants);
verify_results_local(context.step);
verify_runtime_registry_local(protocol, registry, indices);
end

function verify_runtime_registry_local(protocol, registry, indices)
registry_path = fullfile(char(string(protocol.runtime_root)), 'registry.csv');
snapshot_path = fullfile(char(string(protocol.runtime_root)), ...
    'frozen_calibration_snapshot.csv');
if ~isfile(registry_path) || ~isfile(snapshot_path)
    error('stage8_compact_verify_protocol:RuntimeFiles', ...
        'Runtime registry or calibration snapshot is missing.');
end
saved = readtable(registry_path, 'TextType', 'string');
expected = registry(indices, :);
if height(saved) ~= height(expected) || ...
        ~isequal(double(saved.global_trial_index), ...
        double(expected.global_trial_index)) || ...
        ~isequal(string(saved.diagnostic_trial_id), ...
        string(expected.diagnostic_trial_id))
    error('stage8_compact_verify_protocol:RuntimeRegistry', ...
        'Runtime registry differs from the immutable trial selection.');
end
end

function verify_ancestry_and_step_local(repo_dir, constants)
[anchor_status, ~] = system(sprintf( ...
    'git -C "%s" merge-base --is-ancestor %s HEAD', ...
    repo_dir, constants.compact_anchor_commit));
[threshold_status, ~] = system(sprintf( ...
    'git -C "%s" merge-base --is-ancestor %s HEAD', ...
    repo_dir, constants.threshold_evidence_commit));
step_relative = ['beamspace_ml_v18/source/stepwise_signal_model/steps/', ...
    'step_12_6_k12_bootstrap_resolution'];
[diff_status, step_diff] = system(sprintf( ...
    'git -C "%s" diff --name-only %s..HEAD -- "%s"', ...
    repo_dir, constants.compact_anchor_commit, step_relative));
if anchor_status ~= 0 || threshold_status ~= 0 || diff_status ~= 0 || ...
        ~isempty(strtrim(step_diff))
    error('stage8_compact_verify_protocol:FrozenStep', ...
        'Commit ancestry or frozen Stage8 step diff is invalid.');
end
end

function verify_results_local(step)
items = dir(fullfile(step, 'results'));
names = string({items(~[items.isdir]).name});
if numel(names) ~= 1 || names ~= ".gitkeep"
    error('stage8_compact_verify_protocol:Results', ...
        'Formal results directory must contain only .gitkeep.');
end
end
