function result = stage8_compact_gate_c0(repo_dir, output_root, process_audit_path)
%STAGE8_COMPACT_GATE_C0 Verify frozen identities from a clean tool commit.

repo_dir = char(string(repo_dir));
output_root = char(string(output_root));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
addpath(fullfile(repo_dir, 'tools', 'stage8_1b_validation_sharded', 'matlab'));
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>
if ~isfolder(output_root), mkdir(output_root); end
result_path = fullfile(output_root, 'gate_c0_result.json');
result = struct('gate_c0_pass', false, ...
    'status', 'COMPACT_GATE_C0_FAIL_STOPPED', ...
    'checked_utc', utc_now_local(), 'last_error', '');
stage8_1b_write_json_atomic(result_path, result);
try
    if ~strcmp(version('-release'), '2022b') || maxNumCompThreads ~= 1
        error('stage8_compact_gate_c0:Runtime', ...
            'Gate C0 requires MATLAB R2022b -singleCompThread.');
    end
    audit = jsondecode(fileread(char(string(process_audit_path))));
    required_audit = {'matlab_count','mwpython_count', ...
        'coordinator_count','active_lock_count'};
    if ~all(isfield(audit, required_audit)) || ...
            any([audit.matlab_count, audit.mwpython_count, ...
            audit.coordinator_count, audit.active_lock_count] ~= 0)
        error('stage8_compact_gate_c0:ProcessAudit', ...
            'Pre-launch MATLAB/coordinator/lock counts were not all zero.');
    end
    context = stage8_compact_context(repo_dir, true);
    constants = context.compact_constants;
    [head_status, head] = system(sprintf( ...
        'git -C "%s" rev-parse HEAD', repo_dir));
    [status_code, status_text] = system(sprintf( ...
        'git -C "%s" status --porcelain=v1 --untracked-files=all', repo_dir));
    [anchor_ancestor, ~] = system(sprintf( ...
        'git -C "%s" merge-base --is-ancestor %s HEAD', ...
        repo_dir, constants.compact_anchor_commit));
    [threshold_ancestor, ~] = system(sprintf( ...
        'git -C "%s" merge-base --is-ancestor %s HEAD', ...
        repo_dir, constants.threshold_evidence_commit));
    step_relative = ['beamspace_ml_v18/source/stepwise_signal_model/steps/', ...
        'step_12_6_k12_bootstrap_resolution'];
    [diff_status, step_diff] = system(sprintf( ...
        'git -C "%s" diff --name-only %s..HEAD -- "%s"', ...
        repo_dir, constants.compact_anchor_commit, step_relative));
    if head_status ~= 0 || status_code ~= 0 || ...
            ~isempty(strtrim(status_text)) || anchor_ancestor ~= 0 || ...
            threshold_ancestor ~= 0 || diff_status ~= 0 || ...
            ~isempty(strtrim(step_diff))
        error('stage8_compact_gate_c0:Repository', ...
            'Git clean, ancestry, or frozen-step checks failed.');
    end
    calibration_files = dir(fullfile(step, 'calibration', '*.csv'));
    tracked_count = tracked_calibration_count_local(repo_dir, step);
    results_files = dir(fullfile(step, 'results'));
    result_names = string({results_files(~[results_files.isdir]).name});
    if numel(calibration_files) ~= 13 || tracked_count ~= 13 || ...
            numel(result_names) ~= 1 || result_names ~= ".gitkeep"
        error('stage8_compact_gate_c0:Artifacts', ...
            'Calibration tracking or formal results preflight failed.');
    end
    actual = [string(context.plan.identity.stage8_stable_code_identity_hash), ...
        string(context.plan.stage8_plan_hash), ...
        string(context.plan.stage8_calibration_plan_hash), ...
        string(context.plan.stage8_validation_plan_hash), ...
        string(context.plan.measurement_model_registry.registry_hash), ...
        string(context.calibration.calibration_evidence_bundle_hash), ...
        string(context.calibration.threshold_set_hash)];
    expected = [string(constants.stage8_stable_code_identity_hash), ...
        string(constants.stage8_plan_hash), ...
        string(constants.stage8_calibration_plan_hash), ...
        string(constants.stage8_validation_plan_hash), ...
        string(constants.measurement_registry_hash), ...
        string(constants.calibration_evidence_bundle_hash), ...
        string(constants.threshold_set_hash)];
    if ~isequal(actual, expected) || ...
            ~strcmp(context.calibration.calibration_freeze_status, ...
            'PASS_STAGE8_1_THRESHOLD_EVIDENCE_FREEZE') || ...
            ~strcmp(context.calibration.committed_threshold_preflight_status, ...
            'COMMITTED_THRESHOLD_PREFLIGHT_PASS')
        error('stage8_compact_gate_c0:FrozenIdentity', ...
            'Formal loader or frozen identity checks failed.');
    end
    writetable(context.calibration_snapshot, ...
        fullfile(output_root, 'gate_c0_calibration_snapshot.csv'));
    result = struct('gate_c0_pass', true, ...
        'status', 'COMPACT_GATE_C0_FROZEN_IDENTITY_PASS', ...
        'checked_utc', utc_now_local(), ...
        'protocol_runner_commit', strtrim(head), ...
        'diagnostic_protocol_source_hash', ...
        stage8_compact_source_hash(repo_dir), ...
        'stage8_stable_code_identity_hash', ...
        constants.stage8_stable_code_identity_hash, ...
        'stage8_plan_hash', constants.stage8_plan_hash, ...
        'stage8_calibration_plan_hash', ...
        constants.stage8_calibration_plan_hash, ...
        'stage8_validation_plan_hash', ...
        constants.stage8_validation_plan_hash, ...
        'measurement_registry_hash', constants.measurement_registry_hash, ...
        'calibration_evidence_bundle_hash', ...
        constants.calibration_evidence_bundle_hash, ...
        'threshold_set_hash', constants.threshold_set_hash, ...
        'calibration_snapshot_hash', context.calibration_snapshot_hash, ...
        'primary_threshold_artifact_hash', ...
        constants.primary_threshold_artifact_hash, ...
        'sensitivity_threshold_artifact_hash', ...
        constants.sensitivity_threshold_artifact_hash, ...
        'calibration_freeze_status', ...
        context.calibration.calibration_freeze_status, ...
        'committed_threshold_preflight_status', ...
        context.calibration.committed_threshold_preflight_status, ...
        'calibration_csv_count', numel(calibration_files), ...
        'tracked_calibration_csv_count', tracked_count, ...
        'results_directory_clean', true, ...
        'stage8_step_diff_empty', true, ...
        'matlab_release', version('-release'), ...
        'max_num_comp_threads', maxNumCompThreads, ...
        'last_error', '');
    stage8_1b_write_json_atomic(result_path, result);
catch exception
    result.checked_utc = utc_now_local();
    result.last_error = getReport(exception, 'extended', 'hyperlinks', 'off');
    stage8_1b_write_json_atomic(result_path, result);
    rethrow(exception);
end
clear path_cleanup
end

function count = tracked_calibration_count_local(repo_dir, step)
relative = strrep(fullfile(strrep(step, [repo_dir, filesep], ''), ...
    'calibration', '*.csv'), filesep, '/');
[status, output] = system(sprintf( ...
    'git -C "%s" ls-files -- "%s"', repo_dir, relative));
if status ~= 0
    error('stage8_compact_gate_c0:GitFiles', ...
        'Unable to enumerate tracked calibration CSVs.');
end
lines = splitlines(strtrim(string(output)));
if isscalar(lines) && strlength(lines) == 0, count = 0; else, count = numel(lines); end
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
