function protocol = stage8_compact_initialize_runtime( ...
    repo_dir, runtime_root, worker_count, trial_indices, execution_mode, opts)
%STAGE8_COMPACT_INITIALIZE_RUNTIME Create one immutable compact runtime.

if nargin < 6 || isempty(opts), opts = struct(); end
opts = normalize_options_local(opts);
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
runtime_root = char(java.io.File(char(string(runtime_root))).getCanonicalPath());
worker_count = double(worker_count);
trial_indices = double(trial_indices(:));
tool_dir = fileparts(mfilename('fullpath'));
addpath(tool_dir);
addpath(fullfile(repo_dir, 'tools', 'stage8_1b_validation_sharded', 'matlab'));
step = fullfile(repo_dir, 'beamspace_ml_v18', 'source', ...
    'stepwise_signal_model', 'steps', ...
    'step_12_6_k12_bootstrap_resolution');
addpath(step);
path_cleanup = stage8_runtime_path_scope(); %#ok<NASGU>

context = stage8_compact_context(repo_dir, true);
registry = context.compact_registry;
if ~ismember(worker_count, 1:4) || worker_count ~= fix(worker_count) || ...
        isempty(trial_indices) || ...
        numel(unique(trial_indices)) ~= numel(trial_indices) || ...
        any(trial_indices < 1 | trial_indices > height(registry))
    error('stage8_compact_initialize_runtime:Selection', ...
        'Worker count or compact trial selection is invalid.');
end
trial_indices = sort(trial_indices);
selected = registry(ismember(registry.global_trial_index, trial_indices), :);
if height(selected) ~= numel(trial_indices)
    error('stage8_compact_initialize_runtime:Registry', ...
        'The compact registry did not resolve every selected trial.');
end
if opts.require_gate_decision
    decision = verify_gate_decision_local(opts.gate_decision_path, ...
        worker_count, execution_mode, repo_dir);
else
    decision = empty_gate_decision_local();
end

protocol_path = fullfile(runtime_root, 'protocol.json');
if isfile(protocol_path)
    protocol = jsondecode(fileread(protocol_path));
    stage8_compact_verify_protocol(protocol, context);
    if ~isequal(double(protocol.trial_indices(:)), trial_indices) || ...
            double(protocol.selected_worker_count) ~= worker_count
        error('stage8_compact_initialize_runtime:ImmutableProtocol', ...
            'Existing protocol selection differs from the requested runtime.');
    end
    clear path_cleanup
    return;
end
if isfolder(fullfile(runtime_root, 'checkpoints')) && ...
        ~isempty(dir(fullfile(runtime_root, 'checkpoints', '*.mat')))
    error('stage8_compact_initialize_runtime:OrphanCheckpoints', ...
        'Checkpoints exist without an immutable protocol.');
end
create_runtime_dirs_local(runtime_root);
[head_status, head] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', repo_dir));
[git_status, worktree] = system(sprintf( ...
    'git -C "%s" status --porcelain=v1 --untracked-files=all', repo_dir));
if head_status ~= 0 || git_status ~= 0 || ~isempty(strtrim(worktree))
    error('stage8_compact_initialize_runtime:Repository', ...
        'Runtime initialization requires a clean committed repository.');
end
constants = context.compact_constants;
protocol = struct( ...
    'protocol_version', constants.protocol_version, ...
    'checkpoint_contract_version', constants.checkpoint_contract_version, ...
    'execution_authorization', constants.execution_authorization, ...
    'protocol_role', char(string(opts.protocol_role)), ...
    'repo_dir', repo_dir, 'runtime_root', runtime_root, ...
    'protocol_runner_commit', strtrim(head), ...
    'diagnostic_protocol_source_hash', ...
    stage8_compact_source_hash(repo_dir), ...
    'threshold_evidence_commit', constants.threshold_evidence_commit, ...
    'compact_anchor_commit', constants.compact_anchor_commit, ...
    'stage8_stable_code_identity_hash', ...
    constants.stage8_stable_code_identity_hash, ...
    'stage8_plan_hash', constants.stage8_plan_hash, ...
    'stage8_calibration_plan_hash', ...
    constants.stage8_calibration_plan_hash, ...
    'stage8_validation_plan_hash', ...
    constants.stage8_validation_plan_hash, ...
    'measurement_registry_hash', constants.measurement_registry_hash, ...
    'calibration_evidence_bundle_hash', ...
    constants.calibration_evidence_bundle_hash, ...
    'threshold_set_hash', constants.threshold_set_hash, ...
    'calibration_snapshot_hash', context.calibration_snapshot_hash, ...
    'matlab_release', 'R2022b', 'threads_per_worker', 1, ...
    'requested_worker_count', 4, ...
    'selected_worker_count', worker_count, ...
    'selected_execution_mode', char(string(execution_mode)), ...
    'partition_rule', 'MOD_GLOBAL_TRIAL_INDEX_MINUS_ONE', ...
    'trial_indices', trial_indices, ...
    'element_trial_count', height(selected), ...
    'row_count', sum(selected.expected_row_count), ...
    'Bsep', constants.Bsep, 'status_interval_minutes', 15, ...
    'inter_trial_grace_sec', double(opts.inter_trial_grace_sec), ...
    'pause_check_boundary', 'BETWEEN_COMPLETE_ELEMENT_TRIALS', ...
    'formal_6000_trial_status', ...
    'FULL_STAGE8_1B_K1_VALIDATION_DEFERRED_NOT_FAILED', ...
    'formal_6000_trial_authorization_status', ...
    'FORMAL_6000_TRIAL_AUTHORIZATION_SUSPENDED', ...
    'stage8_2_executed_flag', false, ...
    'stage8_2_authorized_flag', false, ...
    'gate_c0_status', char(string(decision.gate_c0_status)), ...
    'gate_c1_status', char(string(decision.gate_c1_status)), ...
    'gate_c2_status', char(string(decision.gate_c2_status)), ...
    'gate_c3_status', char(string(decision.gate_c3_status)), ...
    'gate_c4_status', char(string(decision.gate_c4_status)), ...
    'created_utc', utc_now_local());
stage8_1b_write_json_atomic(protocol_path, protocol);
writetable(selected, fullfile(runtime_root, 'registry.csv'));
writetable(context.calibration_snapshot, ...
    fullfile(runtime_root, 'frozen_calibration_snapshot.csv'));
stage8_compact_verify_protocol(protocol, context);
clear path_cleanup
end

function opts = normalize_options_local(opts)
if ~(isstruct(opts) && isscalar(opts))
    error('stage8_compact_initialize_runtime:Options', ...
        'opts must be a scalar struct.');
end
defaults = struct('protocol_role', 'COMPACT_DIAGNOSTIC', ...
    'inter_trial_grace_sec', 0, 'require_gate_decision', false, ...
    'gate_decision_path', '');
unknown = setdiff(fieldnames(opts), fieldnames(defaults));
if ~isempty(unknown)
    error('stage8_compact_initialize_runtime:UnknownOption', ...
        'Unknown option: %s.', unknown{1});
end
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(opts, names{index}), opts.(names{index}) = defaults.(names{index}); end
end
if ~(isscalar(opts.inter_trial_grace_sec) && ...
        isfinite(opts.inter_trial_grace_sec) && opts.inter_trial_grace_sec >= 0)
    error('stage8_compact_initialize_runtime:Grace', ...
        'inter_trial_grace_sec must be finite and nonnegative.');
end
end

function decision = verify_gate_decision_local(path_now, worker_count, mode, repo_dir)
if ~isfile(path_now)
    error('stage8_compact_initialize_runtime:GateDecision', ...
        'Formal compact Init requires pilot_decision.json.');
end
decision = jsondecode(fileread(path_now));
required = {'gate_c0_status','gate_c1_status','gate_c2_status', ...
    'gate_c3_status','gate_c4_status','gate_c0_pass','gate_c1_pass', ...
    'gate_c2_pass','gate_c3_pass','gate_c4_pass', ...
    'selected_worker_count','selected_execution_mode', ...
    'protocol_runner_commit','diagnostic_protocol_source_hash'};
[head_status, head] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD', repo_dir));
if ~all(isfield(decision, required)) || ...
        ~all([decision.gate_c0_pass, decision.gate_c1_pass, ...
        decision.gate_c2_pass, decision.gate_c3_pass, decision.gate_c4_pass]) || ...
        double(decision.selected_worker_count) ~= worker_count || ...
        string(decision.selected_execution_mode) ~= string(mode) || ...
        head_status ~= 0 || ...
        ~strcmp(string(decision.protocol_runner_commit), ...
        string(strtrim(head))) || ...
        ~strcmp(string(decision.diagnostic_protocol_source_hash), ...
        string(stage8_compact_source_hash(repo_dir)))
    error('stage8_compact_initialize_runtime:GateDecision', ...
        'Pilot decision is incomplete or differs from the requested mode.');
end
end

function decision = empty_gate_decision_local()
decision = struct('gate_c0_status', 'PILOT_RUNTIME_NOT_APPLICABLE', ...
    'gate_c1_status', 'PILOT_RUNTIME_NOT_APPLICABLE', ...
    'gate_c2_status', 'PILOT_RUNTIME_NOT_APPLICABLE', ...
    'gate_c3_status', 'PILOT_RUNTIME_NOT_APPLICABLE', ...
    'gate_c4_status', 'PILOT_RUNTIME_NOT_APPLICABLE');
end

function create_runtime_dirs_local(root)
if ~isfolder(root), mkdir(root); end
names = {'control','checkpoints','tmp','incomplete','workers','logs', ...
    'status','merged','pilot'};
for index = 1:numel(names)
    path_now = fullfile(root, names{index});
    if ~isfolder(path_now), mkdir(path_now); end
end
end

function value = utc_now_local()
value = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
