function row = stage8_compact_row_template()
%STAGE8_COMPACT_ROW_TEMPLATE Return the stable 180-row diagnostic schema.

row = struct( ...
    'diagnostic_row_index', NaN, 'evaluation_row_index', NaN, ...
    'diagnostic_trial_id', "", 'common_trial_id', "", ...
    'global_trial_index', NaN, 'trial_type', "", ...
    'stratum_index', NaN, 'stratum_id', "", 'pairing_key', "", ...
    'trial_index_within_stratum', NaN, 'profile_id', NaN, ...
    'sentinel_flag', false, 'measurement_config_id', "", ...
    'noise_profile_id', "", 'L', NaN, 'parameter_seed', NaN, ...
    'element_noise_seed', NaN, 'separation_auxiliary_seed', NaN, ...
    'center_az_deg', NaN, 'center_el_deg', NaN, 'snr_db', NaN, ...
    'secondary_power_db', NaN, 'correlation_magnitude', NaN, ...
    'correlation_phase_rad', NaN, 'true_separation_deg', NaN, ...
    'direction_deg', NaN, 'element_trial_hash', "", ...
    'threshold_calibration_hash', "", 'threshold_artifact_hash', "", ...
    'q_global', NaN, 'lambda_12', NaN, 'state', "", ...
    'diagnostic_state', "", 'false_split_flag', false, ...
    'false_resolved_flag', false, 'K2_UNRESOLVED_flag', false, ...
    'SEARCH_NOT_CONVERGED_flag', false, ...
    'NUMERIC_RANK_DEFICIENT_flag', false, ...
    'decision_available_flag', false, 'lrt_split_detected_flag', false, ...
    'separation_evaluated_flag', false, 'fit1_validity_status', "", ...
    'fit2_validity_status', "", 'separation_status', "", ...
    'valid_k1_fit_flag', false, 'valid_k2_fit_flag', false, ...
    'truth_target1_az_deg', NaN, 'truth_target1_el_deg', NaN, ...
    'truth_target2_az_deg', NaN, 'truth_target2_el_deg', NaN, ...
    'k1_estimate_az_deg', NaN, 'k1_estimate_el_deg', NaN, ...
    'k2_selected_start_id', "", ...
    'initial_target1_az_deg', NaN, 'initial_target1_el_deg', NaN, ...
    'initial_target2_az_deg', NaN, 'initial_target2_el_deg', NaN, ...
    'final_target1_az_deg', NaN, 'final_target1_el_deg', NaN, ...
    'final_target2_az_deg', NaN, 'final_target2_el_deg', NaN, ...
    'azimuth_rmse_deg', NaN, 'elevation_rmse_deg', NaN, ...
    'joint_2d_rmse_deg', NaN, 'initial_joint_2d_rmse_deg', NaN, ...
    'joint_refinement_improved_flag', false, ...
    'true_separation_az_deg', NaN, 'true_separation_el_deg', NaN, ...
    'estimated_separation_az_deg', NaN, ...
    'estimated_separation_el_deg', NaN, ...
    'separation_vector_error_deg', NaN, 'score_call_count', NaN, ...
    'svd_call_count', NaN, 'truth_used_in_fit_flag', false, ...
    'truth_used_in_classifier_flag', false, 'row_runtime_sec', NaN);
end
