function rows = test_stage8_k2_tecs_c1_static(~, runtime_root)
%TEST_STAGE8_K2_TECS_C1_STATIC Full certified finite-domain C1 gates.

design = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'design_freeze.json')));
single_count = 0;
pair_count = 0;
ordered_count = 0;
for identity = 1:2
    capture = load(fullfile(runtime_root, 'baseline_capture', ...
        sprintf('pass_a_identity_%02d.mat', identity)));
    expected_identity = design.measurement_identity_hashes{identity};
    [model, dictionary] = stage8_k2_tecs_select_capture_identity( ...
        capture.value, expected_identity);
    artifact = stage8_k2_tecs_promote_c1_artifact(dictionary);
    config = struct('run_id',design.run_id, ...
        'baseline_commit',design.baseline_commit, ...
        'key_schema_hash',design.key_schema_hash, ...
        'scope','MEASUREMENT_IDENTITY_SESSION', ...
        'fixed_measurement_hash',model.fixed_measurement_hash, ...
        'enabled_layers',{{'C1'}}, ...
        'artifacts',struct('C1',artifact));
    session = stage8_k2_tecs_cache_session(config);
    provider = stage8_k2_tecs_build_provider(session);
    assert(~provider.per_call_timing_enabled && ...
        ~provider.raw_event_logging_enabled);
    for first = 1:21
        [columns, info] = session.lookup_c1( ...
            artifact.key_angles_deg(first, :), model);
        assert(info.cache_hit && ...
            isequaln(columns{1}, artifact.G(:, first)));
        single_count = single_count + 1;
    end
    for first = 1:21
        for second = first:21
            angles = artifact.key_angles_deg([first,second], :);
            [G, manifold_info, provider_info] = ...
                stage8_k2_tecs_provider_pair( ...
                angles, model, provider, struct('rank_multiplier',1));
            expected = artifact.G(:, [first,second]);
            [rank_expected, singular_expected, threshold_expected] = ...
                stage8_k2_tcc_stable_matrix_rank(expected, 1);
            assert(isequaln(G, expected) && ...
                manifold_info.rank_Gseq == rank_expected && ...
                isequaln(manifold_info.singular_values_Gseq, ...
                    singular_expected) && ...
                isequaln(manifold_info.rank_threshold_Gseq, ...
                    threshold_expected) && ...
                provider_info.cache_hit_count == 2 && ...
                isnan(provider_info.lookup_runtime_sec) && ...
                isnan(provider_info.direct_runtime_sec) && ...
                isnan(provider_info.rank_runtime_sec) && ...
                isnan(provider_info.total_runtime_sec));
            pair_count = pair_count + 1;
        end
    end
    for first = 1:21
        for second = 1:21
            [columns, info] = session.lookup_c1( ...
                artifact.key_angles_deg([first,second], :), model);
            assert(all(info.cache_hit) && ...
                isequaln([columns{1},columns{2}], ...
                artifact.G(:, [first,second])));
            ordered_count = ordered_count + 1;
        end
    end
    near = artifact.key_angles_deg(1, :);
    near(1) = near(1) + 1e-9;
    [~, near_info] = session.lookup_c1(near, model);
    assert(~near_info.cache_hit && ...
        near_info.cache_miss_reason == "OFF_GRID_EXACT_KEY");
    wrong_model = model;
    wrong_model.fixed_measurement_hash = repmat('0', 1, 64);
    [~, wrong_info] = session.lookup_c1( ...
        artifact.key_angles_deg(1, :), wrong_model);
    assert(~wrong_info.cache_hit && ~wrong_info.identity_valid);

    off_grid = artifact.key_angles_deg([1,2], :);
    off_grid(:, 1) = off_grid(:, 1) + 1e-4;
    [legacy_G, ~, legacy_info] = ...
        build_full_sequential_local_manifold( ...
        off_grid, model, struct('rank_multiplier',1));
    [fallback_G, fallback_info, provider_info] = ...
        stage8_k2_tecs_provider_pair( ...
        off_grid, model, provider, struct('rank_multiplier',1));
    assert(isequaln(fallback_G, legacy_G) && ...
        isequaln(fallback_info, legacy_info) && ...
        provider_info.cache_hit_count == 0 && ...
        provider_info.physical_producer_call_count == 1);
    session.set_failure_injection('PRODUCER_FAILURE');
    assert_throws_local(@() stage8_k2_tecs_provider_pair( ...
        off_grid, model, provider, struct('rank_multiplier',1)), ...
        'stage8_k2_tecs_provider_pair:InjectedProducerFailure');
    session.set_failure_injection('NONE');
    timed_provider = stage8_k2_tecs_build_provider(session, ...
        struct('per_call_timing_enabled',true));
    [~, ~, timed_info] = stage8_k2_tecs_provider_pair( ...
        artifact.key_angles_deg([1,2], :), model, timed_provider, ...
        struct('rank_multiplier',1));
    assert(all(isfinite([timed_info.lookup_runtime_sec, ...
        timed_info.direct_runtime_sec, timed_info.rank_runtime_sec, ...
        timed_info.total_runtime_sec])));
    snapshot = session.snapshot();
    assert(snapshot.bytes_peak <= 536870912 && ...
        snapshot.truth_leakage_count == 0 && ...
        snapshot.collision_count == 0);
    delete(session);
end
assert(single_count == 42 && pair_count == 462 && ordered_count == 882);
static = load(fullfile(runtime_root, 'baseline_capture', ...
    'pass_a_static_certification.mat'));
assert(static.value.all_pass && height(static.value.rows) == 1386 && ...
    all(static.value.rows.static_pass));
names = ["C1_42_singles";"C1_462_canonical_pairs"; ...
    "C1_882_ordered_nested";"C1_near_miss_rejection"; ...
    "C1_identity_rejection";"C1_frozen_miss_fallback"; ...
    "C1_producer_failure_propagation";"C1_memory_bound"; ...
    "C1_truth_collision_zero";"C1_formal_per_call_timing_disabled"; ...
    "C1_existing_1386_static_contract"];
rows = table(names, true(numel(names), 1), ...
    repmat("PASS", numel(names), 1), ...
    'VariableNames',{'test_name','pass','message'});
end

function assert_throws_local(callback, identifier)
threw = false;
try
    callback();
catch exception
    threw = strcmp(exception.identifier, identifier);
end
assert(threw, 'Expected error %s.', identifier);
end
