function rows = test_stage8_k2_tecs_component_protocol(repo_dir, runtime_root)
%TEST_STAGE8_K2_TECS_COMPONENT_PROTOCOL Freeze-ready replay construction.

design = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'design_freeze.json')));
first = stage8_k2_tecs_build_component_schedule(design, {'C1'});
second = stage8_k2_tecs_build_component_schedule(design, {'C1'});
assert(isequal(first, second) && height(first) == 70 && ...
    nnz(first.included_in_statistics) == 60 && ...
    numel(unique(first.schedule_row_hash)) == 70);
temporary = [tempname, '.csv'];
cleanup = onCleanup(@() delete_if_present_local(temporary));
writetable(first, temporary);
round_trip = readtable(temporary, 'TextType','string');
assert(strcmp(stage8_k2_tcc_stable_hash( ...
    'TECS_COMPONENT_SCHEDULE_V1', first), ...
    stage8_k2_tcc_stable_hash( ...
    'TECS_COMPONENT_SCHEDULE_V1', round_trip)));
clear cleanup
for identity = 1:2
    selected = first.identity_index == identity;
    current = first(selected, :);
    measured = current(current.included_in_statistics == 1, :);
    assert(height(current) == 35 && ...
        nnz(measured.pair_order == "AB") == 15 && ...
        nnz(measured.pair_order == "BA") == 15);
end
expected_warmup_1 = ["AB";"BA";"AB";"BA";"AB"];
expected_warmup_2 = ["BA";"AB";"BA";"AB";"BA"];
assert(isequal(first.pair_order(1:5), expected_warmup_1) && ...
    isequal(first.pair_order(36:40), expected_warmup_2));
[fixtures, fixture] = stage8_k2_tecs_build_c1_replay_fixture( ...
    repo_dir, runtime_root);
assert(fixture.total_pair_event_count == 2952 && ...
    fixture.total_column_event_count == 5904 && ...
    strcmp(fixture.status, 'C1_PASS_A_EVENT_LINK_EXACT') && ...
    numel(fixtures) == 2 && ...
    sum(arrayfun(@(item) height(item.events), fixtures)) == 2952);
for identity = 1:2
    assert(strcmp(fixtures(identity).fixed_measurement_hash, ...
        design.measurement_identity_hashes{identity}) && ...
        ~any(contains(lower(string( ...
        fixtures(identity).events.Properties.VariableNames)), 'truth')));
end
[component, component_hash] = stage8_k2_tecs_code_manifest( ...
    repo_dir, 'COMPONENT_CORE');
assert(height(component) == 6 && strlength(component_hash) == 64 && ...
    numel(unique(component.relative_path)) == 6);
artifact_registry = stage8_k2_tecs_read_c1_artifact_registry(runtime_root);
assert(height(artifact_registry) == 2 && ...
    all(artifact_registry.entry_count == 21) && ...
    all(artifact_registry.status == "IMMUTABLE_C1_ARTIFACT_VALIDATED") && ...
    all(isfile(artifact_registry.artifact_path)));
lifecycle_source = fileread(fullfile(repo_dir, 'tools', ...
    'stage8_k2_tangent_exact_cache_stack', 'matlab', ...
    'stage8_k2_tecs_run_lifecycle.m'));
assert(contains(lifecycle_source, ...
    'row.cache_hit_count = pair.candidate.hit_count;') && ...
    contains(lifecycle_source, ...
    'row.cache_miss_count = pair.candidate.miss_count;') && ...
    ~contains(lifecycle_source, 'pair.candidate.cache_hit_count') && ...
    ~contains(lifecycle_source, 'pair.candidate.cache_miss_count'));
evidence_source = fileread(fullfile(repo_dir, 'tools', ...
    'stage8_k2_tangent_exact_cache_stack', 'matlab', ...
    'stage8_k2_tecs_write_evidence.m'));
assert(contains(evidence_source, ...
    'economics.schema_version=repmat("STAGE8_K2_TECS_ECONOMICS_V1"') && ...
    contains(evidence_source, ...
    'economics=movevars(economics,''schema_version'',''Before'',1);'));
stage_ids=["K2_PUBLIC";"K2_CORE_LITE";"K2_HELPER_K1"; ...
    "K2_START_BUILD";"K2_NESTED_ANCHOR"; ...
    "K2_REGISTERED_REFINEMENT";"K2_FINAL_CERTIFICATION";"K2_SELECTION"];
stage_values=[0.35;0.30;0.09;0.08;0.05;0.13;0.01;0.02];
raw_stage=struct('stage_id',cellstr(stage_ids), ...
    'inclusive_runtime_sec',num2cell(stage_values));
[reconciled,unattributed,reconciliation,minimum,accounting]= ...
    stage8_k2_tecs_reconcile_stage_timing(raw_stage,0.40);
core=reconciled(reconciled.stage_id=="K2_CORE_LITE",:);
helper=reconciled(reconciled.stage_id=="K2_HELPER_K1",:);
assert(abs(core.exclusive_runtime_sec-0.06)<1e-12 && ...
    helper.accounting_role=="OVERLAP_DIAGNOSTIC" && ...
    ~helper.included_in_reconciliation && ...
    isnan(helper.exclusive_runtime_sec) && abs(unattributed-0.05)<1e-12 && ...
    abs(reconciliation)<1e-12 && minimum>=0 && ...
    accounting.overlap_diagnostic_stage_count==1);
names = ["component_schedule_deterministic"; ...
    "component_schedule_csv_roundtrip_hash"; ...
    "component_schedule_balance";"component_warmup_order"; ...
    "C1_replay_fixture_pass_a_exact_link"; ...
    "component_core_manifest_complete"; ...
    "C1_artifact_registry_csv_contract"; ...
    "lifecycle_snapshot_counter_projection"; ...
    "evidence_economics_schema_version"; ...
    "stage_reconciliation_overlap_accounting"];
rows = table(names, true(numel(names), 1), ...
    repmat("PASS", numel(names), 1), ...
    'VariableNames',{'test_name','pass','message'});
end

function delete_if_present_local(path_now)
if isfile(path_now), delete(path_now); end
end
