function rows = test_stage8_k2_tecs_key_contract()
%TEST_STAGE8_K2_TECS_KEY_CONTRACT Exact serialization/key mutation gates.

base = struct( ...
    'cache_schema_version','V1', ...
    'baseline_commit',repmat('a', 1, 40), ...
    'frozen_function_hash',repmat('b', 1, 64), ...
    'function_role','TEST', ...
    'producer_stage','P','consumer_stage','C', ...
    'fixed_measurement_hash',repmat('c', 1, 64), ...
    'measurement_config_id','M','noise_profile_id','N', ...
    'observation_bytes_hash',repmat('d', 1, 64), ...
    'local_domain_hash',repmat('e', 1, 64), ...
    'stage5_locked_hash',repmat('f', 1, 64), ...
    'complete_options_hash',repmat('1', 1, 64), ...
    'K',2,'requested_rank',2,'rank_multiplier',1, ...
    'ordered_angle_tuple_IEEE754_bytes',[7.5,8.5;7.6,8.6], ...
    'pair_ordering','ORDERED','numeric_class','double', ...
    'shape',[2,2],'device_backend','CPU', ...
    'MATLAB_release','R2022b', ...
    'requested_output_contract','FULL');
[hash1, bytes1] = stage8_k2_tecs_sha256('TEST_COMPLETE_KEY', base);
[hash2, bytes2] = stage8_k2_tecs_sha256('TEST_COMPLETE_KEY', base);
assert(strcmp(hash1, hash2) && isequal(bytes1, bytes2));

mutations = { ...
    'identity_rejection','fixed_measurement_hash',repmat('9', 1, 64); ...
    'observation_rejection','observation_bytes_hash',repmat('8', 1, 64); ...
    'options_mutation_rejection','complete_options_hash',repmat('7', 1, 64); ...
    'ordered_pair_distinction','ordered_angle_tuple_IEEE754_bytes', ...
        flipud(base.ordered_angle_tuple_IEEE754_bytes); ...
    'wrong_numeric_class_rejection','numeric_class','single'; ...
    'wrong_output_contract_rejection','requested_output_contract','G_ONLY'};
for index = 1:size(mutations, 1)
    changed = base;
    changed.(mutations{index, 2}) = mutations{index, 3};
    changed_hash = stage8_k2_tecs_sha256('TEST_COMPLETE_KEY', changed);
    assert(~strcmp(hash1, changed_hash), mutations{index, 1});
end
positive = stage8_k2_tecs_serialize(+0.0);
negative = stage8_k2_tecs_serialize(-0.0);
assert(~isequal(positive, negative));
assert_throws_local(@() stage8_k2_tecs_serialize(NaN), ...
    'stage8_k2_tecs_serialize:Nonfinite');
assert_throws_local(@() stage8_k2_tecs_serialize(Inf), ...
    'stage8_k2_tecs_serialize:Nonfinite');
assert_throws_local(@() stage8_k2_tecs_serialize(@sin), ...
    'stage8_k2_tecs_serialize:UnsupportedType');

names = ["exact_key_round_trip"; string(mutations(:, 1)); ...
    "signed_zero_behavior";"NaN_Inf_behavior"; ...
    "unsupported_handle_function_rejection"];
rows = table(names, true(numel(names), 1), ...
    repmat("PASS", numel(names), 1), ...
    'VariableNames',{'test_name','pass','message'});
end

function assert_throws_local(callback, identifier)
threw = false;
try
    callback();
catch exception
    threw = strcmp(exception.identifier, identifier);
end
assert(threw, 'Expected error %s.', identifier);
end
