function rows = test_stage8_k2_tecs_session_contract(runtime_root)
%TEST_STAGE8_K2_TECS_SESSION_CONTRACT Generic session, scope and resume gates.

design = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'design_freeze.json')));
config = struct('run_id',design.run_id, ...
    'baseline_commit',design.baseline_commit, ...
    'key_schema_hash',design.key_schema_hash, ...
    'scope','TRIAL_INVOCATION', ...
    'fixed_measurement_hash',design.measurement_identity_hashes{1}, ...
    'enabled_layers',{{'TEST'}});
session = stage8_k2_tecs_cache_session(config);
key1 = struct('observation_hash','A','options',1,'angles',[1,2]);
key2 = struct('observation_hash','B','options',1,'angles',[1,2]);
[hit, ~] = session.lookup_exact('TEST', key1);
assert(~hit);
insert = session.store_exact('TEST', key1, struct('value',pi));
assert(insert.inserted);
[hit, value] = session.lookup_exact('TEST', key1);
assert(hit && isequaln(value, struct('value',pi)));
value.value = 0;
[~, value_again] = session.lookup_exact('TEST', key1);
assert(value_again.value == pi);
assert_throws_local(@() session.store_exact( ...
    'TEST', key1, struct('value',0)), ...
    'stage8_k2_tecs_cache_session:ImmutableEntry');

[forced_hash, ~] = stage8_k2_tecs_sha256('TECS_TEST_KEY', key2);
[~, wrong_bytes] = stage8_k2_tecs_sha256('TECS_TEST_KEY', key1);
session.debug_inject_bucket('TEST', forced_hash, wrong_bytes, 1);
assert_throws_local(@() session.lookup_exact('TEST', key2), ...
    'stage8_k2_tecs_cache_session:HashCollision');
assert_throws_local(@() session.store_exact('TEST', ...
    struct('truth_angle',1), 1), ...
    'stage8_k2_tecs_cache_session:TruthLeakage');

session.set_failure_injection('CORRUPT_NEXT_LOOKUP');
assert_throws_local(@() session.lookup_exact('TEST', key1), ...
    'stage8_k2_tecs_cache_session:CacheCorruption');
session.set_failure_injection('LOOKUP_FAILURE');
assert_throws_local(@() session.lookup_exact('TEST', key1), ...
    'stage8_k2_tecs_cache_session:InjectedLookupFailure');
session.set_failure_injection('NONE');
before = session.snapshot();
assert(before.bytes_peak >= before.bytes_current && before.entry_count >= 1);
session.record_physical_producer_call(2);
session.reset('TRIAL_INVOCATION');
after = session.snapshot();
assert(after.entry_count == 0 && after.bytes_current == 0 && ...
    after.physical_producer_call_count == 2 && after.eviction_count == 0);

checkpoint = checkpoint_fixture_local(design);
expected = struct('run_id',checkpoint.run_id, ...
    'design_freeze_hash',checkpoint.design_freeze_hash, ...
    'trial_registry_hash',checkpoint.trial_registry_hash);
stage8_k2_tecs_validate_checkpoint_identity(checkpoint, expected);
corrupt = checkpoint;
corrupt.run_id = 'WRONG';
assert_throws_local(@() stage8_k2_tecs_validate_checkpoint_identity( ...
    corrupt, expected), ...
    'stage8_k2_tecs_validate_checkpoint_identity:Mismatch');

names = ["miss_fallback";"immutable_entry_behavior"; ...
    "hash_collision_payload_rejection";"truth_isolation"; ...
    "cache_corruption_rejection";"failure_injection"; ...
    "memory_accounting";"scope_reset"; ...
    "logical_vs_physical_counters";"deterministic_no_eviction"; ...
    "checkpoint_identity";"checkpoint_corruption_resume_mismatch"];
rows = table(names, true(numel(names), 1), ...
    repmat("PASS", numel(names), 1), ...
    'VariableNames',{'test_name','pass','message'});
delete(session);
end

function checkpoint = checkpoint_fixture_local(design)
checkpoint = struct( ...
    'checkpoint_unit_kind','AUDIT_TRIAL','pass','PASS_A', ...
    'unit_complete',true,'baseline_commit',design.baseline_commit, ...
    'initial_execution_start_commit',design.initial_execution_start_commit, ...
    'run_id',design.run_id,'stage_commit_ledger_hash','HASH', ...
    'integration_code_commit','NOT_APPLICABLE', ...
    'prompt_hash',design.execution_prompt_hash, ...
    'baseline_snapshot_hash',design.baseline_snapshot_hash, ...
    'cache_code_hash','NOT_APPLICABLE', ...
    'frozen_function_hashes',{design.frozen_function_hashes}, ...
    'trial_registry_hash',design.trial_registry_hash, ...
    'key_schema_hash',design.key_schema_hash, ...
    'semantic_output_projection_hash', ...
        design.semantic_output_projection_hash, ...
    'hook_allowlist_hash',design.hook_allowlist_hash, ...
    'timing_protocol_hash','NOT_CLOSED', ...
    'phase_schedule_hash','FROZEN_REGISTRY', ...
    'final_measurement_candidate_hash','NOT_FROZEN_PASS_A', ...
    'design_freeze_hash',design.freeze_payload_hash, ...
    'component_freeze_hash_or_sentinel','NOT_CLOSED', ...
    'timing_freeze_hash_or_sentinel','NOT_CLOSED', ...
    'final_candidate_freeze_hash_or_sentinel','NOT_CLOSED', ...
    'MATLAB_release',design.MATLAB_release, ...
    'singleCompThread',true, ...
    'cache_reset_lifecycle_rule','DESIGN_FREEZE_RULE');
end

function assert_throws_local(callback, identifier)
threw = false;
try
    callback();
catch exception
    threw = strcmp(exception.identifier, identifier);
end
assert(threw, 'Expected error %s.', identifier);
end
