function result = test_stage8_k2_tecs_hook_dispatch(repo_dir, runtime_root)
%TEST_STAGE8_K2_TECS_HOOK_DISPATCH Exercise the frozen provider seam.

fixture = stage8_k2_tecs_build_runtime_fixture(repo_dir, runtime_root);
identity = fixture.identities(1);
session = stage8_k2_tecs_make_session( ...
    fixture, identity.fixed_measurement_hash, {'C1'});
provider = stage8_k2_tecs_build_provider(session);
angles = identity.artifact.key_angles_deg(1:2, :);
[G, info, provider_info] = stage8_k2_tcc_get_pair_manifold( ...
    angles, identity.model, provider, struct('rank_multiplier', 1));
expected = identity.artifact.G(:, 1:2);
[expected_rank, expected_singular, expected_threshold] = ...
    stage8_k2_tcc_stable_matrix_rank(expected, 1);
snapshot = session.snapshot();
pass = isequaln(G, expected) && ...
    info.rank_Gseq == expected_rank && ...
    isequaln(info.singular_values_Gseq, expected_singular) && ...
    isequaln(info.rank_threshold_Gseq, expected_threshold) && ...
    strcmp(provider_info.mode, 'TECS_EXACT_STACK') && ...
    provider_info.cache_hit_count == 2 && ...
    provider_info.cache_miss_count == 0 && ...
    snapshot.physical_producer_call_count == 0 && ...
    snapshot.collision_count == 0 && snapshot.truth_leakage_count == 0;
delete(session);
assert(pass, 'test_stage8_k2_tecs_hook_dispatch:Mismatch', ...
    'The allowed hook did not dispatch exactly to the TECS provider.');
result = table("hook_dispatch", true, ...
    "TECS hook returned 2 certified hits and 0 producer calls", ...
    'VariableNames', {'test_name','pass','message'});
end
