function result = test_beamspace_cml_contains_fixed_grid()
%TEST_BEAMSPACE_CML_CONTAINS_FIXED_GRID Verify exhaustive pair starts.

test_dir = fileparts(mfilename('fullpath'));
repo_dir = fileparts(fileparts(fileparts(test_dir)));
scope = stage8_k2_cb_add_paths(repo_dir); %#ok<NASGU>
context = stage8_k2_cb_build_context(repo_dir);
registry = stage8_k2_cb_build_registry(context);
selected = registry.profile_id == "P1" & registry.L == 4 & ...
    registry.snr_db == 0 & registry.noise_profile_id == "WHITE";
spec = registry(selected, :);
trial = stage8_k2_cb_generate_trial(spec, context);
data = build_stage8_full_data_from_element(trial.Y_element, trial.model, ...
    struct('data_role', 'TEST_DATA_ONLY'));
fit = stage8_k2_cb_full4d_cml(data.Zseq_white, trial.model, ...
    context.plan.local_domain, 'BEAMSPACE', struct(), context.constants);
tolerance = 64 * eps(max(1, abs(fit.best_coarse_loglik)));
assert(fit.fit_valid && fit.coarse_candidate_count == nchoosek(21, 2) && ...
    fit.continuous_start_count == 6 && ...
    fit.loglik_concentrated + tolerance >= fit.best_coarse_loglik && ...
    ~fit.truth_used_in_fit_flag && ~fit.tangent_used_in_start_flag && ...
    ~fit.core_used_in_start_flag, ...
    'test_beamspace_cml_contains_fixed_grid:Containment', ...
    'Full4D CML did not retain the exhaustive frozen-grid baseline.');
result = struct('pass', true, ...
    'coarse_candidate_count', fit.coarse_candidate_count, ...
    'continuous_start_count', fit.continuous_start_count, ...
    'best_coarse_loglik', fit.best_coarse_loglik, ...
    'final_loglik', fit.loglik_concentrated);
fprintf('test_beamspace_cml_contains_fixed_grid PASS\n');
end
