function result = test_structured_direct_equivalence(fixture)
%TEST_STRUCTURED_DIRECT_EQUIVALENCE Compare orchestration and frozen calls.

selected = fixture.registry.profile_id == "P1" & ...
    fixture.registry.noise_profile_id == "WHITE" & ...
    double(fixture.registry.L) == 8 & ...
    double(fixture.registry.white_beamspace_snr_target_db) == 22 & ...
    double(fixture.registry.replicate_id) == 1;
spec = fixture.registry(selected, :);
[trial, ~] = stage8_k2_wacb_reconstruct_trial(spec, fixture.context);
resources = stage8_k2_wacb_test_resources(fixture.context, "WHITE");
rules = rules_local(spec, fixture.context.constants);
fit_input = struct('Y_element', trial.Y_element, 'model', trial.model, ...
    'L', 8, 'resource_entry', resources.structured_entry, ...
    'music_resources', resources, 'applicability', rules);
adapted = stage8_k2_wacb_fit_new_methods(fit_input, fixture.context.constants);
direct = { ...
    stage8_k2_sb_gfbss_music(adapted.common.R_fb, ...
    adapted.common.R_noise_subarray, trial.model, fixture.context.constants), ...
    stage8_k2_sb_root_music(adapted.common.R_fb, ...
    trial.model, fixture.context.constants), ...
    stage8_k2_sb_ls_esprit(adapted.common.R_fb, ...
    trial.model, fixture.context.constants)};
for index = 1:3
    actual = adapted.structured(index).elevation;
    expected = direct{index};
    assert(actual.fit_valid == expected.fit_valid && ...
        actual.fit_status == expected.fit_status && ...
        isequaln(actual.elevations_hat_deg, expected.elevations_hat_deg), ...
        'test_structured_direct_equivalence:Elevation', ...
        'A structured elevation adapter differs from its direct call.');
    if actual.fit_valid
        Y_white = resources.structured_entry.whitening.whitener * ...
            trial.Y_element;
        conditional = stage8_k2_sb_conditional_az_cml(Y_white, ...
            actual.elevations_hat_deg, trial.model, ...
            resources.structured_entry.whitening, fixture.context.constants);
        adapted_conditional = adapted.structured(index).conditional;
        assert(conditional.fit_valid == adapted_conditional.fit_valid && ...
            conditional.fit_status == adapted_conditional.fit_status && ...
            isequaln(conditional.angles_hat_deg, ...
            adapted_conditional.angles_hat_deg), ...
            'test_structured_direct_equivalence:Conditional', ...
            'Conditional azimuth orchestration differs from direct call.');
    end
end
result = struct('pass', true, 'method_count', 3, ...
    'conditional_methods_checked', nnz(arrayfun(@(item) ...
    item.elevation.fit_valid, adapted.structured)));
end

function rules = rules_local(spec, constants)
rules = repmat(struct('applicable', false, 'status', "", ...
    'uses_registered_scenario_flag', false), 4, 1);
for index = 1:4
    rules(index) = stage8_k2_wacb_applicability(spec, constants.method_ids(index));
end
end
