function result = test_plot_only_regeneration(fixture)
%TEST_PLOT_ONLY_REGENERATION Generate all figures from data-only fixtures.

root = tempname;
data_dir = fullfile(root, 'data');
output_dir = fullfile(root, 'figures');
mkdir(root); mkdir(data_dir); mkdir(output_dir);
cleanup = onCleanup(@() cleanup_local(root));
data = stage8_k2_wacb_plot_fixture(fixture.context.constants);
writetable(data.overall, fullfile(data_dir, ...
    '48_stage8_k2_white_snr_all_method_summary.csv'));
writetable(data.profile, fullfile(data_dir, ...
    '48_stage8_k2_white_snr_all_method_profile_summary.csv'));
writetable(data.failure, fullfile(data_dir, ...
    '48_stage8_k2_white_snr_all_method_failure_summary.csv'));
writetable(data.pairwise, fullfile(data_dir, ...
    '48_stage8_k2_white_snr_all_method_pairwise_vs_tangent.csv'));
writetable(data.complexity, fullfile(data_dir, ...
    '48_stage8_k2_white_snr_all_method_complexity_summary.csv'));
writetable(data.eigenstructure, fullfile(data_dir, ...
    '48_stage8_k2_white_snr_subspace_eigenstructure_summary.csv'));
representative_spectra = data.representative_spectra; %#ok<NASGU>
save(fullfile(data_dir, ...
    '48_stage8_k2_white_snr_representative_spectra.mat'), ...
    'representative_spectra', '-mat');
fid = fopen(fullfile(data_dir, ...
    '48_stage8_k2_white_snr_plot_data_manifest.json'), 'w');
fprintf(fid, '{"fixture":true}\n'); fclose(fid);
paths = stage8_k2_wacb_plot_from_committed_data( ...
    fixture.repo_dir, data_dir, output_dir);
source = fileread(which('stage8_k2_wacb_plot_from_committed_data'));
prohibited = {'stage8_k2_mc_generate_trial','stage8_k2_cb_music(', ...
    'stage8_k2_sb_gfbss_music(','stage8_k2_sb_root_music(', ...
    'stage8_k2_sb_ls_esprit(','stage8_k2_sb_conditional_az_cml('};
assert(numel(paths) == 12 && all(arrayfun(@isfile, paths)) && ...
    ~any(cellfun(@(token) contains(source, token), prohibited)), ...
    'test_plot_only_regeneration:Contract', ...
    'Plot-only regeneration used a fit path or missed a figure.');
result = struct('pass', true, 'figure_count', numel(paths), ...
    'runtime_required', false, 'fit_path_count', 0);
clear cleanup
end

function cleanup_local(path_now)
if isfolder(path_now), rmdir(path_now, 's'); end
end
