function result = test_frozen_constants_identity(fixture)
%TEST_FROZEN_CONSTANTS_IDENTITY Compare all reused algorithm constants.

now = fixture.context.constants;
wcb = stage8_k2_wcb_constants();
sb = stage8_k2_sb_constants();
pass = now.music_grid_step_deg == wcb.music_grid_step_deg && ...
    now.music_grid_chunk_size == wcb.music_grid_chunk_size && ...
    isequal(now.music_applicable_L, wcb.music_applicable_L) && ...
    now.N_el == sb.N_el && now.N_az == sb.N_az && now.K == sb.K && ...
    now.smoothing_length == sb.smoothing_length && ...
    now.smoothing_subarray_count == sb.smoothing_subarray_count && ...
    isequal(now.elevation_grid_deg, sb.elevation_grid_deg) && ...
    isequal(now.elevation_domain_deg, sb.elevation_domain_deg) && ...
    isequal(now.azimuth_grid_deg, sb.azimuth_grid_deg) && ...
    isequal(now.azimuth_domain_deg, sb.azimuth_domain_deg) && ...
    now.top_start_count == sb.top_start_count && ...
    now.max_sweeps == sb.max_sweeps && ...
    now.scan_nodes_per_coordinate == sb.scan_nodes_per_coordinate && ...
    now.fminbnd_TolX_deg == sb.fminbnd_TolX_deg && ...
    now.fminbnd_MaxFunEvals == sb.fminbnd_MaxFunEvals && ...
    now.root_unit_circle_tolerance == sb.root_unit_circle_tolerance && ...
    now.root_duplicate_tolerance_deg == sb.root_duplicate_tolerance_deg && ...
    now.rank_multiplier == sb.rank_multiplier && ...
    now.paired_tie_tolerance_deg == sb.paired_tie_tolerance_deg;
assert(pass, 'test_frozen_constants_identity:Changed', ...
    'A frozen Element MUSIC or structured-method constant changed.');
result = struct('pass', true, 'constant_groups_checked', 15);
end
