function result = test_element_music_direct_equivalence(fixture)
%TEST_ELEMENT_MUSIC_DIRECT_EQUIVALENCE Compare adapter with frozen direct call.

cases = {"WHITE", 1, -6; "WHITE", 4, 10; ...
    "STAGE5_TOEPLITZ_CORRELATED", 1, 6; ...
    "STAGE5_TOEPLITZ_CORRELATED", 4, 14};
statuses = strings(size(cases, 1), 1);
for index = 1:size(cases, 1)
    selected = fixture.registry.profile_id == "P2" & ...
        fixture.registry.noise_profile_id == cases{index, 1} & ...
        double(fixture.registry.L) == cases{index, 2} & ...
        double(fixture.registry.white_beamspace_snr_target_db) == ...
        cases{index, 3} & double(fixture.registry.replicate_id) == 1;
    spec = fixture.registry(selected, :);
    assert(height(spec) == 1, ...
        'test_element_music_direct_equivalence:Selection', ...
        'A representative selector is not unique.');
    [trial, ~] = stage8_k2_wacb_reconstruct_trial(spec, fixture.context);
    resources = stage8_k2_wacb_test_resources( ...
        fixture.context, spec.noise_profile_id);
    rules = rules_local(spec, fixture.context.constants);
    fit_input = struct('Y_element', trial.Y_element, 'model', trial.model, ...
        'L', double(spec.L), 'resource_entry', resources.structured_entry, ...
        'music_resources', resources, 'applicability', rules);
    adapted = stage8_k2_wacb_fit_new_methods( ...
        fit_input, fixture.context.constants).element_music;
    Y_white = resources.structured_entry.whitening.whitener * trial.Y_element;
    direct = stage8_k2_cb_music(Y_white, resources.music_entry, ...
        resources, 'ELEMENT', double(spec.L), fixture.context.constants);
    assert(adapted.applicable == direct.applicable && ...
        adapted.fit_valid == direct.fit_valid && ...
        adapted.fit_status == direct.fit_status && ...
        adapted.effective_rank == direct.effective_rank && ...
        adapted.local_peak_count == direct.local_peak_count && ...
        isequaln(adapted.angles_hat_deg, direct.angles_hat_deg), ...
        'test_element_music_direct_equivalence:Mismatch', ...
        'Element MUSIC adapter differs from its frozen direct call.');
    statuses(index) = adapted.fit_status;
end
result = struct('pass', true, 'case_count', 4, 'statuses', statuses);
end

function rules = rules_local(spec, constants)
rules = repmat(struct('applicable', false, 'status', "", ...
    'uses_registered_scenario_flag', false), 4, 1);
for index = 1:4
    rules(index) = stage8_k2_wacb_applicability(spec, constants.method_ids(index));
end
end
