function result = test_eight_trial_smoke(fixture)
%TEST_EIGHT_TRIAL_SMOKE Run the eight preregistered non-performance cases.

cases = { ...
    "P1", "WHITE", 8, 10; ...
    "P2", "WHITE", 8, 14; ...
    "P3", "WHITE", 4, 18; ...
    "P4", "WHITE", 1, 22; ...
    "P1", "STAGE5_TOEPLITZ_CORRELATED", 8, 10; ...
    "P2", "STAGE5_TOEPLITZ_CORRELATED", 4, 14; ...
    "P3", "STAGE5_TOEPLITZ_CORRELATED", 8, 18; ...
    "P4", "STAGE5_TOEPLITZ_CORRELATED", 1, 22};
statuses = strings(8, 4);
for index = 1:size(cases, 1)
    selected = fixture.registry.profile_id == cases{index, 1} & ...
        fixture.registry.noise_profile_id == cases{index, 2} & ...
        double(fixture.registry.L) == cases{index, 3} & ...
        double(fixture.registry.white_beamspace_snr_target_db) == ...
        cases{index, 4} & double(fixture.registry.replicate_id) == 1;
    spec = fixture.registry(selected, :);
    assert(height(spec) == 1, 'test_eight_trial_smoke:Selection', ...
        'A preregistered smoke selector is not unique.');
    resources = stage8_k2_wacb_test_resources( ...
        fixture.context, spec.noise_profile_id);
    [trial, ~] = stage8_k2_wacb_reconstruct_trial(spec, fixture.context);
    [rows, diagnostics] = stage8_k2_wacb_evaluate_trial( ...
        spec, trial, fixture.context, resources);
    assert(height(rows) == 4 && height(diagnostics) == 4 && ...
        all(rows.fit_status ~= "NOT_RUN") && ...
        all((~rows.applicable) | rows.fit_valid | ...
        (rows.applicable & ~rows.fit_valid)) && ...
        ~any(rows.truth_used_in_fit_flag) && ...
        ~any(rows.profile_used_in_fit_flag) && ...
        ~any(rows.tangent_used_in_start_flag) && ...
        ~any(rows.core_used_in_start_flag) && ...
        ~any(rows.full4d_used_in_start_flag), ...
        'test_eight_trial_smoke:Outcome', ...
        'A smoke case lacks an explicit outcome or violates isolation.');
    statuses(index, :) = rows.fit_status.';
    fprintf('T12 smoke %d/8 PASS: %s\n', index, char(spec.trial_id));
end
result = struct('pass', true, 'case_count', 8, 'statuses', statuses, ...
    'performance_gate_count', 0);
end
