function result = test_representative_spectra_consistency(fixture)
%TEST_REPRESENTATIVE_SPECTRA_CONSISTENCY Re-select saved diagnostic outputs.

selected = fixture.registry.profile_id == "P1" & ...
    fixture.registry.noise_profile_id == "WHITE" & ...
    double(fixture.registry.L) == 8 & ...
    double(fixture.registry.white_beamspace_snr_target_db) == 18 & ...
    double(fixture.registry.replicate_id) == 1;
spec = fixture.registry(selected, :);
[trial, ~] = stage8_k2_wacb_reconstruct_trial(spec, fixture.context);
resources = stage8_k2_wacb_test_resources(fixture.context, "WHITE");
[rows, diagnostics, payload] = stage8_k2_wacb_evaluate_trial( ...
    spec, trial, fixture.context, resources);
music = rows(rows.method_id == "ELEMENT_MUSIC_K2", :);
gfbss_diagnostic = diagnostics(diagnostics.method_id == ...
    "ELEMENT_VERTICAL_GFBSS_MUSIC_AZ_CML", :);
assert(payload.included && ...
    payload.element_music.fit_valid == logical(music.fit_valid) && ...
    string(payload.element_music.selected_status) ~= "" && ...
    payload.gfbss.selected_status == gfbss_diagnostic.elevation_fit_status && ...
    string(payload.root_music.selected_status) ~= "" && ...
    string(payload.esprit.selected_status) ~= "", ...
    'test_representative_spectra_consistency:Mismatch', ...
    'Saved representative payload does not match formal selections.');
result = struct('pass', true, 'trial_id', spec.trial_id, ...
    'method_payload_count', 4);
end
