function result = test_evidence44_46_identity(fixture)
%TEST_EVIDENCE44_46_IDENTITY Verify both immutable completed bundles.

e44 = fixture.context.evidence44;
e46 = fixture.context.evidence46;
assert(height(e44.registry) == 1680 && height(e44.snr_rows) == 1680 && ...
    height(e44.method_rows) == 5040 && numel(e44.artifact_ids) == 15 && ...
    height(e46.results) == 5040 && height(e46.registry_audit) == 1680 && ...
    numel(e46.artifact_ids) == 15 && ...
    strcmp(e46.manifest.independent_audit_status, 'PASS') && ...
    e46.manifest.independent_baseline_rerun_count == 0, ...
    'test_evidence44_46_identity:Contract', ...
    'Evidence 44/46 identity, count, or independent audit changed.');
result = struct('pass', true, 'evidence44_identity', e44.identity, ...
    'evidence46_identity', e46.identity, 'existing_method_rerun_count', 0);
end
