function result = test_all_method_plot_fixture(fixture)
%TEST_ALL_METHOD_PLOT_FIXTURE Check ten-way classification and pair direction.

constants = fixture.context.constants;
rows = repmat(row_local(), 20, 1);
index = 0;
for trial_index = 1:2
    for method_index = 1:10
        index = index + 1;
        row = row_local();
        row.trial_id = "FIXTURE_" + string(trial_index);
        row.global_trial_index = trial_index;
        row.method_id = constants.all_method_ids(method_index);
        row.white_beamspace_snr_target_db = 10;
        row.applicable = method_index ~= 10 || trial_index == 2;
        row.fit_valid = row.applicable && method_index ~= 9;
        if ~row.applicable
            row.applicability_status = "STRUCTURAL_NA";
            row.fit_status = "STRUCTURAL_NA";
            row.failure_stage = "STRUCTURAL_NA";
        elseif row.fit_valid
            row.applicability_status = "APPLICABLE";
            row.fit_status = "VALID";
            row.failure_stage = "NONE";
            row.joint_RMSE_deg = 0.1 + method_index / 100;
        else
            row.applicability_status = "APPLICABLE";
            row.fit_status = "INVALID";
            row.failure_stage = "ALGORITHM_INVALID";
        end
        rows(index) = row;
    end
end
data = struct2table(rows);
diagnostics = diagnostic_fixture_local(constants);
summaries = stage8_k2_wacb_summaries(data, diagnostics, constants);
assert(height(data) == 20 && ...
    all(groupcounts(data, 'trial_id').GroupCount == 10) && ...
    nnz(~data.applicable) == 1 && ...
    nnz(data.applicable & ~data.fit_valid) == 2 && ...
    constants.all_method_row_count == 16800 && ...
    any(summaries.failure.failure_stage == "STRUCTURAL_NA") && ...
    all(ismember({'new_wins','ties','tangent_wins'}, ...
    summaries.pairwise.Properties.VariableNames)), ...
    'test_all_method_plot_fixture:Contract', ...
    'Ten-method classification, target schema, or pair direction failed.');
result = struct('pass', true, 'fixture_trial_count', 2, ...
    'methods_per_trial', 10, 'formal_target_rows', 16800);
end

function row = row_local()
row = struct('trial_id', "", 'global_trial_index', 0, 'method_id', "", ...
    'white_beamspace_snr_target_db', NaN, 'profile_id', "P1", ...
    'noise_profile_id', "WHITE", 'L', 8, 'replicate_id', 1, ...
    'applicable', true, 'applicability_status', "APPLICABLE", ...
    'fit_valid', true, 'fit_status', "VALID", 'failure_stage', "NONE", ...
    'joint_RMSE_deg', 0.1, 'azimuth_RMSE_deg', 0.1, ...
    'elevation_RMSE_deg', 0.1, 'center_error_deg', 0.1, ...
    'axis_error_deg', 0.1, 'rho_error_deg', 0.1, ...
    'rho_relative_error', 0.1, 'separation_vector_error_deg', 0.1, ...
    'runtime_sec', 0.1, 'score_call_count', 1, ...
    'SVD_call_count', 1, 'eig_call_count', 1);
end

function diagnostics = diagnostic_fixture_local(constants)
rows = repmat(struct('method_id', "", ...
    'white_beamspace_snr_target_db', 10, 'applicable', true, ...
    'elevation_fit_valid', true, 'conditional_az_cml_executed', true, ...
    'conditional_az_cml_valid', true, ...
    'raw_signal_noise_eigengap', 2, 'fbss_signal_noise_eigengap', 3, ...
    'registered_root_count', 2), 6, 1);
index = 0;
for method_index = 2:4
    for duplicate = 1:2
        index = index + 1;
        rows(index).method_id = constants.method_ids(method_index);
    end
end
diagnostics = struct2table(rows);
end
