function signature = stage8_k2_tcc_pass0_signature( ...
    element_trial_hash, k1, fixed, tangent, diagnostics)
%STAGE8_K2_TCC_PASS0_SIGNATURE Frozen estimator fields for qualification.

signature = struct( ...
    'element_trial_hash', char(string(element_trial_hash)), ...
    'K1_public_center_deg', k1.angles_hat_deg, ...
    'K1_public_fit_valid', logical(k1.fit_valid), ...
    'K1_center_deg', diagnostics.K1_center_deg, ...
    'K1_fit_valid', logical(diagnostics.K1_fit_valid), ...
    'fixed_K2_angles_deg', fixed.angles_hat_deg, ...
    'fixed_K2_fit_valid', logical(fixed.fit_valid), ...
    'fixed_K2_loglik', double(fixed.loglik_concentrated), ...
    'direction_hat', diagnostics.direction_hat, ...
    'metric_rank', double(diagnostics.metric_rank), ...
    'metric_condition', double(diagnostics.metric_condition), ...
    'rho_hat_deg', double(diagnostics.rho_hat_deg), ...
    'raw_tangent_candidate_valid', ...
    logical(diagnostics.raw_tangent_candidate_valid), ...
    'raw_tangent_loglik', double(diagnostics.raw_tangent_loglik), ...
    'raw_tangent_angles_deg', diagnostics.raw_tangent_angles_deg, ...
    'final_angles_deg', tangent.angles_hat_deg, ...
    'final_fit_valid', logical(tangent.fit_valid), ...
    'final_rss', double(tangent.rss), ...
    'final_loglik', double(tangent.loglik_concentrated), ...
    'final_rank', double(tangent.effective_rank), ...
    'selected_start_id', char(string(tangent.selected_start_id)), ...
    'selected_source', char(string(tangent.selected_source)), ...
    'upgrade_flag', logical(diagnostics.upgrade_flag), ...
    'fallback_flag', logical(diagnostics.fallback_flag), ...
    'fallback_reason', char(string(diagnostics.fallback_reason)), ...
    'score_call_count', double(tangent.score_call_count), ...
    'SVD_call_count', double(tangent.svd_call_count), ...
    'truth_used_in_fit_flag', logical(tangent.truth_used_in_fit_flag), ...
    'selection_truth_used_flag', ...
    logical(diagnostics.selection_truth_used_flag));
end
