function constants = stage8_k2_tcc_constants()
%STAGE8_K2_TCC_CONSTANTS Fixed Level-A provider contract.

constants = struct( ...
    'cache_version', 'STAGE8_K2_TCC_LEVEL_A_V1', ...
    'phase_factor', 1, ...
    'steering_phase_sign', 1, ...
    'numeric_class', 'double', ...
    'grid_step_deg', 0.01, ...
    'grid_key_tolerance_deg', 1e-11, ...
    'rank_multiplier', 1, ...
    'default_domain_bounds_deg', [7.4, 8.6, 9.8, 10.2]);
end
