function trial = stage8_k2_tcc_generate_frozen_trial(spec, context)
%STAGE8_K2_TCC_GENERATE_FROZEN_TRIAL Recreate one frozen TP1 trial once.

if ~(istable(spec) && height(spec) == 1)
    error('stage8_k2_tcc_generate_frozen_trial:Spec', ...
        'spec must be exactly one registered trial row.');
end
model = resolve_stage8_measurement_model( ...
    context.plan.measurement_model_registry, ...
    context.primary_measurement_config_id, spec.noise_profile_id);
direction = [cosd(spec.direction_deg), sind(spec.direction_deg)];
center = [spec.center_az_deg, spec.center_el_deg];
truth = [center - spec.separation_deg * direction / 2; ...
    center + spec.separation_deg * direction / 2];
bounds = context.plan.local_domain.domain_bounds_deg;
if any(truth(:, 1) < bounds(1) | truth(:, 1) > bounds(2) | ...
        truth(:, 2) < bounds(3) | truth(:, 2) > bounds(4))
    error('stage8_k2_tcc_generate_frozen_trial:TruthDomain', ...
        'Both K2 truth endpoints must remain inside the frozen domain.');
end
rng_state = rng;
rng_cleanup = onCleanup(@() rng(rng_state));
rng(spec.source_seed, 'twister');
source_phase_rad = 2 * pi * rand();
clear rng_cleanup
manifold = build_stage8_element_manifold(truth, model);
[source, source_info] = construct_deterministic_source_matrix( ...
    2, spec.L, spec.secondary_power_db, spec.correlation_magnitude, ...
    source_phase_rad, char(spec.trial_id));
unscaled = manifold.A * source;
target_energy = 10 ^ (spec.snr_db / 10) * numel(unscaled);
source = source * sqrt(target_energy / ...
    max(norm(unscaled, 'fro') ^ 2, realmin));
signal = manifold.A * source;
[noise, noise_debug] = generate_stage8_element_noise( ...
    model, spec.L, 1, spec.noise_seed);
Y_element = signal + noise;
element_trial_hash = stage8_k2_tp_stable_hash( ...
    'ELEMENT_TRIAL', char(spec.trial_id), Y_element, truth, ...
    double(spec.L), double(spec.snr_db), double(spec.source_seed), ...
    double(spec.noise_seed), char(spec.noise_profile_id));
trial = struct('Y_element', Y_element, 'truth_angles_deg', truth, ...
    'model', model, 'source_matrix', source, ...
    'signal_element', signal, 'noise_element', noise, ...
    'source_phase_rad', source_phase_rad, 'source_info', source_info, ...
    'noise_debug', noise_debug, 'element_trial_hash', element_trial_hash, ...
    'single_cpi_flag', true, 'same_range_doppler_cell_flag', true, ...
    'cross_cpi_data_used_flag', false, ...
    'tracking_input_used_flag', false, ...
    'truth_used_in_fit_flag', false);
end
