function output = stage8_k2_tcc_run_static_certification( ...
    context, registry, runtime_dir)
%STAGE8_K2_TCC_RUN_STATIC_CERTIFICATION Certify 21/231/441 per identity.

if nargin < 3 || isempty(runtime_dir)
    error('stage8_k2_tcc_run_static_certification:RuntimeDir', ...
        'An external runtime directory is required.');
end
noise_ids = unique(registry.noise_profile_id, 'stable');
all_rows = cell(numel(noise_ids), 1);
dictionaries = cell(numel(noise_ids), 1);
models = cell(numel(noise_ids), 1);
dictionary_info = cell(numel(noise_ids), 1);
for identity_index = 1:numel(noise_ids)
    spec = registry(find(registry.noise_profile_id == ...
        noise_ids(identity_index), 1, 'first'), :);
    trial = stage8_k2_tcc_generate_frozen_trial(spec, context);
    model = trial.model;
    [dictionary, build_info] = ...
        stage8_k2_tcc_build_registered_dictionary( ...
        model, context.plan.local_domain, struct());
    models{identity_index} = model;
    dictionaries{identity_index} = dictionary;
    dictionary_info{identity_index} = build_info;
    all_rows{identity_index} = certify_identity_local( ...
        model, context.plan.local_domain, dictionary);
    partial = struct('noise_ids', noise_ids(1:identity_index), ...
        'rows', {all_rows(1:identity_index)}, ...
        'dictionaries', {dictionaries(1:identity_index)}, ...
        'models', {models(1:identity_index)}, ...
        'dictionary_info', {dictionary_info(1:identity_index)});
    atomic_save_local(fullfile(runtime_dir, sprintf( ...
        'pass_a_identity_%02d.mat', identity_index)), partial);
end
rows = vertcat(all_rows{:});
if height(rows) ~= numel(noise_ids) * (21 + 231 + 441)
    error('stage8_k2_tcc_run_static_certification:Cardinality', ...
        'Static certification did not produce 693 rows per identity.');
end
output = struct('rows', rows, 'dictionaries', {dictionaries}, ...
    'models', {models}, 'dictionary_info', {dictionary_info}, ...
    'identity_count', numel(noise_ids), ...
    'single_count', nnz(rows.case_type == "SINGLE"), ...
    'canonical_pair_count', nnz(rows.case_type == "CANONICAL_PAIR"), ...
    'ordered_nested_count', nnz(rows.case_type == "ORDERED_NESTED"), ...
    'all_pass', all(rows.static_pass), ...
    'continuous_numeric_pass', all(rows.continuous_numeric_pass), ...
    'discrete_decision_pass', all(rows.discrete_decision_pass));
atomic_save_local(fullfile(runtime_dir, 'pass_a_static_certification.mat'), ...
    output);
end

function rows = certify_identity_local(model, ~, dictionary)
angles = double(dictionary.key_table{:, {'az_deg','el_deg'}});
key_count = size(angles, 1);
legacy_single = cell(key_count, 1);
direct_single = cell(key_count, 1);
dictionary_single = cell(key_count, 1);
row_cells = cell(key_count + key_count * (key_count + 1) / 2 + ...
    key_count ^ 2, 1);
row_index = 0;
for key = 1:key_count
    [legacy_single{key}, ~, legacy_info] = ...
        build_full_sequential_local_manifold(angles(key, :), model, ...
        struct('rank_multiplier', 1));
    [direct_single{key}, direct_info] = stage8_k2_tcc_build_g_direct( ...
        angles(key, :), model, struct('compute_rank', true, ...
        'rank_multiplier', 1));
    [dictionary_single{key}, lookup] = stage8_k2_tcc_registered_lookup( ...
        dictionary, angles(key, :), model);
    [rank_dictionary, sigma_dictionary, threshold_dictionary] = ...
        stage8_k2_tcc_stable_matrix_rank(dictionary_single{key}, 1);
    row_index = row_index + 1;
    row_cells{row_index} = case_row_local(model, 'SINGLE', ...
        sprintf('SINGLE_%02d', key), angles(key, :), [NaN, NaN], ...
        char(dictionary.key_table.key_id(key)), 'NOT_APPLICABLE', ...
        legacy_single{key}, direct_single{key}, dictionary_single{key}, ...
        legacy_info, direct_info, rank_dictionary, sigma_dictionary, ...
        threshold_dictionary, max(lookup.key_error_deg), NaN, NaN);
end

for first = 1:key_count
    for second = first:key_count
        pair_angles = [angles(first, :);angles(second, :)];
        [legacy, ~, legacy_info] = build_full_sequential_local_manifold( ...
            pair_angles, model, struct('rank_multiplier', 1));
        [direct, direct_info] = stage8_k2_tcc_build_g_direct( ...
            pair_angles, model, struct('compute_rank', true, ...
            'rank_multiplier', 1));
        [dictionary_G, lookup] = stage8_k2_tcc_registered_lookup( ...
            dictionary, pair_angles, model);
        [rank_dictionary, sigma_dictionary, threshold_dictionary] = ...
            stage8_k2_tcc_stable_matrix_rank(dictionary_G, 1);
        row_index = row_index + 1;
        row_cells{row_index} = case_row_local(model, 'CANONICAL_PAIR', ...
            sprintf('PAIR_%02d_%02d', first, second), ...
            angles(first, :), angles(second, :), ...
            char(dictionary.key_table.key_id(first)), ...
            char(dictionary.key_table.key_id(second)), legacy, direct, ...
            dictionary_G, legacy_info, direct_info, rank_dictionary, ...
            sigma_dictionary, threshold_dictionary, ...
            max(lookup.key_error_deg), NaN, NaN);
    end
end

for first = 1:key_count
    for second = 1:key_count
        nested_angles = [angles(first, :);angles(second, :)];
        [legacy, ~, legacy_info] = build_full_sequential_local_manifold( ...
            nested_angles, model, struct('rank_multiplier', 1));
        [direct, direct_info] = stage8_k2_tcc_build_g_direct( ...
            nested_angles, model, struct('compute_rank', true, ...
            'rank_multiplier', 1));
        [dictionary_G, lookup] = stage8_k2_tcc_registered_lookup( ...
            dictionary, nested_angles, model);
        [rank_dictionary, sigma_dictionary, threshold_dictionary] = ...
            stage8_k2_tcc_stable_matrix_rank(dictionary_G, 1);
        % Static A3 certifies that ordered assembly reuses the exact same
        % canonical dictionary columns.  Observation-dependent production
        % fit1.G/RSS/nested-pass checks are intentionally deferred to B.
        first_error = relative_column_error_local( ...
            dictionary_G(:, 1), dictionary_single{first});
        second_error = relative_column_error_local( ...
            dictionary_G(:, 2), dictionary_single{second});
        row_index = row_index + 1;
        row_cells{row_index} = case_row_local(model, 'ORDERED_NESTED', ...
            sprintf('NESTED_%02d_%02d', first, second), ...
            angles(first, :), angles(second, :), ...
            char(dictionary.key_table.key_id(first)), ...
            char(dictionary.key_table.key_id(second)), legacy, direct, ...
            dictionary_G, legacy_info, direct_info, rank_dictionary, ...
            sigma_dictionary, threshold_dictionary, ...
            max(lookup.key_error_deg), first_error, second_error);
    end
end
rows = struct2table(vertcat(row_cells{:}));
end

function row = case_row_local(model, case_type, case_id, angle1, angle2, ...
    key1, key2, legacy, direct, dictionary_G, legacy_info, direct_info, ...
    rank_dictionary, sigma_dictionary, threshold_dictionary, key_error, ...
    first_error, second_error)
scale_G = max(1, max(abs(legacy(:))));
legacy_direct_rel = norm(legacy - direct, 'fro') / ...
    max(norm(legacy, 'fro'), realmin);
legacy_direct_abs = max(abs(legacy(:) - direct(:)));
direct_dictionary_rel = norm(direct - dictionary_G, 'fro') / ...
    max(norm(direct, 'fro'), realmin);
direct_dictionary_abs = max(abs(direct(:) - dictionary_G(:)));
sigma_direct = pad_sigma_local(direct_info.singular_values_Gseq);
sigma_dictionary = pad_sigma_local(sigma_dictionary);
sigma_error = max(abs(sigma_direct - sigma_dictionary), [], 'omitnan');
if isempty(sigma_error) || ~isfinite(sigma_error)
    sigma_error = 0;
end
scale_sigma = max(1, max(abs(sigma_direct), [], 'omitnan'));
threshold_difference = abs(direct_info.rank_threshold_Gseq - ...
    threshold_dictionary);
rank_match = direct_info.rank_Gseq == rank_dictionary && ...
    legacy_info.rank_Gseq == direct_info.rank_Gseq;
column_bound = 64 * eps(max(size(legacy)));
column_pass = true;
if strcmp(case_type, 'ORDERED_NESTED')
    column_pass = first_error <= column_bound && second_error <= column_bound;
end
numeric_pass = key_error <= 1e-11 && ...
    legacy_direct_rel <= 1e-12 && ...
    legacy_direct_abs <= 1e-12 * scale_G && ...
    direct_dictionary_rel <= 1e-10 && ...
    sigma_error <= 1e-10 * scale_sigma && ...
    threshold_difference <= 1e-12 && column_pass;
discrete_pass = rank_match;
failure = strings(0, 1);
if ~numeric_pass, failure(end + 1) = "CONTINUOUS_NUMERIC_CONTRACT"; end
if ~discrete_pass, failure(end + 1) = "RANK_DECISION_CONTRACT"; end
row = struct( ...
    'measurement_identity', string(model.fixed_measurement_hash), ...
    'case_type', string(case_type), 'case_id', string(case_id), ...
    'angle1_az', double(angle1(1)), 'angle1_el', double(angle1(2)), ...
    'angle2_az', double(angle2(1)), 'angle2_el', double(angle2(2)), ...
    'key1', string(key1), 'key2', string(key2), ...
    'exact_key_error_deg', double(key_error), ...
    'legacy_vs_direct_G_rel_error', double(legacy_direct_rel), ...
    'legacy_vs_direct_G_abs_error', double(legacy_direct_abs), ...
    'direct_vs_dictionary_G_rel_error', double(direct_dictionary_rel), ...
    'direct_vs_dictionary_G_abs_error', double(direct_dictionary_abs), ...
    'singular_value_abs_error', double(sigma_error), ...
    'sigma1_direct', double(sigma_direct(1)), ...
    'sigma2_direct', double(sigma_direct(2)), ...
    'sigma1_dictionary', double(sigma_dictionary(1)), ...
    'sigma2_dictionary', double(sigma_dictionary(2)), ...
    'rank_threshold_direct', double(direct_info.rank_threshold_Gseq), ...
    'rank_threshold_dictionary', double(threshold_dictionary), ...
    'rank_threshold_abs_difference', double(threshold_difference), ...
    'rank_direct', double(direct_info.rank_Gseq), ...
    'rank_dictionary', double(rank_dictionary), ...
    'rank_match', logical(rank_match), ...
    'first_column_rel_error', double(first_error), ...
    'second_column_rel_error', double(second_error), ...
    'continuous_numeric_pass', logical(numeric_pass), ...
    'discrete_decision_pass', logical(discrete_pass), ...
    'static_pass', logical(numeric_pass && discrete_pass), ...
    'failure_reason', strjoin(failure, '|'));
end

function sigma = pad_sigma_local(values)
sigma = NaN(1, 2);
values = double(values(:).');
sigma(1:min(2, numel(values))) = values(1:min(2, numel(values)));
end

function value = relative_column_error_local(left, right)
value = norm(left - right) / max(norm(right), realmin);
end

function atomic_save_local(path_now, value)
folder = fileparts(path_now);
if ~isfolder(folder), mkdir(folder); end
temporary = [path_now, '.tmp'];
save(temporary, 'value', '-v7.3');
movefile(temporary, path_now, 'f');
end
