function output = stage8_k2_tcc_run_query_audit( ...
    context, registry, static_output, protocol, runtime_dir, options)
%STAGE8_K2_TCC_RUN_QUERY_AUDIT Run/resume 72 direct+shadow trial audits.

if nargin < 6 || isempty(options), options = struct(); end
if ~isfield(options, 'trial_indices')
    options.trial_indices = 1:height(registry);
end
if ~isfield(options, 'shard_id'), options.shard_id = 0; end
trial_indices = double(options.trial_indices(:).');
checkpoint_dir = fullfile(runtime_dir, 'checkpoints', 'pass_b');
if ~isfolder(checkpoint_dir), mkdir(checkpoint_dir); end
trial_outputs = cell(numel(trial_indices), 1);
session_id = char(java.util.UUID.randomUUID());
for local_index = 1:numel(trial_indices)
    trial_index = trial_indices(local_index);
    spec = registry(trial_index, :);
    checkpoint_path = fullfile(checkpoint_dir, ...
        [char(spec.trial_id), '.mat']);
    expected_identity = identity_hash_for_noise_local( ...
        static_output.dictionaries, spec.noise_profile_id);
    expected = checkpoint_metadata_local( ...
        protocol, spec, expected_identity, session_id);
    [reusable, checkpoint] = read_checkpoint_local( ...
        checkpoint_path, expected);
    if reusable
        trial_outputs{local_index} = checkpoint.payload;
        fprintf('PASSB RESUME %d/%d %s\n', trial_index, ...
            height(registry), char(spec.trial_id));
        continue;
    end
    trial = stage8_k2_tcc_generate_frozen_trial(spec, context);
    dictionary = dictionary_for_model_local( ...
        static_output.dictionaries, trial.model);
    full_data = build_stage8_full_data_from_element( ...
        trial.Y_element, trial.model, struct( ...
        'data_role', 'SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
    trial_metadata = struct('trial_id', char(spec.trial_id), ...
        'noise_profile_id', char(spec.noise_profile_id), ...
        'L', double(spec.L), 'snr_db', double(spec.snr_db), ...
        'profile_id', char(spec.profile_id), ...
        'element_trial_hash', trial.element_trial_hash, ...
        'fixed_measurement_hash', trial.model.fixed_measurement_hash);
    stage8_k2_tcc_audit_state('CONFIGURE', struct('mode', 'QUERY', ...
        'dictionary', dictionary, 'model', trial.model, ...
        'Zseq_white', full_data.Zseq_white, ...
        'trial_metadata', trial_metadata));
    [result, diagnostics] = stage8_k2_tp_fit_safe( ...
        trial.Y_element, trial.model, context);
    query = stage8_k2_tcc_audit_state('GET_QUERY');
    helper = helper_comparison_local(query.fit_snapshots);
    initialization = initialization_comparison_local( ...
        query.initialization_snapshots);
    rows = query_rows_local(query.stage_rows, spec, trial.model);
    totals = mismatch_totals_local(rows);
    nested_pass = ~isempty(query.nested_records) && ...
        all(~[query.nested_records.nested_mismatch]);
    truth_pass = ~query.truth_used_in_fit_flag && ...
        ~query.cache_truth_used_flag && ~query.placement_truth_used_flag && ...
        ~result.truth_used_in_fit_flag && ...
        ~diagnostics.selection_truth_used_flag;
    trial_pass = all(struct2array(totals) == 0) && ...
        helper.pass && initialization.pass && nested_pass && truth_pass;
    payload = struct('spec', spec, 'trial_metadata', trial_metadata, ...
        'result', result, 'diagnostics', diagnostics, 'query', query, ...
        'query_rows', rows, 'helper_comparison', helper, ...
        'initialization_comparison', initialization, ...
        'mismatch_totals', totals, 'nested_pass', nested_pass, ...
        'truth_pass', truth_pass, 'trial_pass', trial_pass);
    checkpoint = struct('metadata', expected, 'payload', payload, ...
        'unit_complete', true, 'atomic_checkpoint', true);
    atomic_checkpoint_local(checkpoint_path, checkpoint);
    trial_outputs{local_index} = payload;
    fprintf('PASSB RUN %d/%d %s pass=%d\n', trial_index, ...
        height(registry), char(spec.trial_id), trial_pass);
    if ~trial_pass
        error('stage8_k2_tcc_run_query_audit:HardStop', ...
            'A query/trajectory correctness contract failed for %s.', ...
            char(spec.trial_id));
    end
end

query_tables = cellfun(@(x) x.query_rows, trial_outputs, ...
    'UniformOutput', false);
query_rows = vertcat(query_tables{:});
helper_rows = struct2table(cellfun(@(x) x.helper_comparison, ...
    trial_outputs));
initialization_rows = struct2table(cellfun( ...
    @(x) x.initialization_comparison, trial_outputs));
trial_pass = cellfun(@(x) x.trial_pass, trial_outputs);
totals = mismatch_totals_local(query_rows);
output = struct('query_rows', query_rows, ...
    'helper_rows', helper_rows, ...
    'initialization_rows', initialization_rows, ...
    'trial_pass', trial_pass, 'query_audit_pass_count', nnz(trial_pass), ...
    'mismatch_totals', totals, ...
    'all_pass', all(trial_pass) && all(struct2array(totals) == 0), ...
    'helper_reuse_certified', all(helper_rows.pass), ...
    'initialization_reuse_certified', all(initialization_rows.pass), ...
    'truth_leakage_count', nnz(~cellfun(@(x) x.truth_pass, trial_outputs)), ...
    'trial_indices', trial_indices, 'shard_id', options.shard_id);
if numel(trial_indices) == height(registry)
    output_path = fullfile(runtime_dir, 'pass_b_query_audit.mat');
else
    output_path = fullfile(runtime_dir, sprintf( ...
        'pass_b_query_worker_%02d.mat', options.shard_id));
end
atomic_value_save_local(output_path, output);
end

function dictionary = dictionary_for_model_local(dictionaries, model)
match = cellfun(@(x) strcmp(x.fixed_measurement_hash, ...
    model.fixed_measurement_hash), dictionaries);
if nnz(match) ~= 1
    error('stage8_k2_tcc_run_query_audit:DictionaryIdentity', ...
        'Exactly one diagnostic dictionary must match the trial model.');
end
dictionary = dictionaries{find(match, 1)};
end

function identity = identity_hash_for_noise_local(dictionaries, noise_id)
match = cellfun(@(x) strcmp(x.noise_profile_id, char(string(noise_id))), ...
    dictionaries);
if nnz(match) ~= 1
    error('stage8_k2_tcc_run_query_audit:NoiseIdentity', ...
        'Exactly one diagnostic dictionary must match the noise profile.');
end
identity = dictionaries{find(match, 1)}.fixed_measurement_hash;
end

function rows = query_rows_local(stage_rows, spec, model)
if isempty(stage_rows)
    error('stage8_k2_tcc_run_query_audit:EmptyQuery', ...
        'The query logger produced no stage rows.');
end
if isfield(stage_rows, 'key_histogram')
    stage_rows = rmfield(stage_rows, 'key_histogram');
end
rows = struct2table(stage_rows);
n = height(rows);
rows = addvars(rows, repmat(string(spec.trial_id), n, 1), ...
    repmat(string(spec.noise_profile_id), n, 1), ...
    repmat(double(spec.L), n, 1), repmat(double(spec.snr_db), n, 1), ...
    repmat(string(spec.profile_id), n, 1), ...
    repmat(string(model.fixed_measurement_hash), n, 1), ...
    'Before', 1, 'NewVariableNames', {'trial_id','noise_profile_id', ...
    'L','snr_db','profile_id','fixed_measurement_hash'});
end

function totals = mismatch_totals_local(rows)
names = {'key_mismatch_count','rank_mismatch_count', ...
    'candidate_order_mismatch_count','tie_mismatch_count', ...
    'best_index_mismatch_count','accepted_update_mismatch_count', ...
    'trajectory_mismatch_count','selected_start_mismatch_count', ...
    'nested_pass_mismatch_count','final_selector_mismatch_count'};
totals = struct();
for index = 1:numel(names)
    if istable(rows)
        totals.(names{index}) = sum(rows.(names{index}));
    else
        totals.(names{index}) = sum([rows.(names{index})]);
    end
end
end

function comparison = helper_comparison_local(snapshots)
roles = string({snapshots.role});
public = snapshots(roles == "PUBLIC_K1_FIXED_SUBFIT");
helper = snapshots(roles == "K2_INTERNAL_HELPER_K1");
if numel(public) ~= 1 || numel(helper) ~= 1
    comparison = helper_failure_template_local( ...
        'HELPER_SNAPSHOT_CARDINALITY');
    return;
end
comparison = struct( ...
    'angles_match', isequaln(public.angles_deg, helper.angles_deg), ...
    'G_match', isequaln(public.G, helper.G), ...
    'rss_match', isequaln(public.rss, helper.rss), ...
    'sigma2_match', isequaln(public.sigma2, helper.sigma2), ...
    'loglik_match', isequaln(public.loglik, helper.loglik), ...
    'rank_match', isequaln(public.rank, helper.rank), ...
    'selected_start_match', public.selected_start == helper.selected_start, ...
    'fixed_measurement_hash_match', public.fixed_measurement_hash == ...
    helper.fixed_measurement_hash, ...
    'local_domain_hash_match', public.local_domain_hash == ...
    helper.local_domain_hash, ...
    'observation_hash_match', public.observation_hash == ...
    helper.observation_hash, ...
    'initialization_identity_match', public.initialization_identity == ...
    helper.initialization_identity, 'failure_reason', "");
flags = struct2array(rmfield(comparison, 'failure_reason'));
comparison.pass = all(flags);
if ~comparison.pass
    comparison.failure_reason = "PUBLIC_FIXED_VS_INTERNAL_HELPER_MISMATCH";
end
end

function value = helper_failure_template_local(reason)
value = struct('angles_match', false, 'G_match', false, ...
    'rss_match', false, 'sigma2_match', false, 'loglik_match', false, ...
    'rank_match', false, 'selected_start_match', false, ...
    'fixed_measurement_hash_match', false, ...
    'local_domain_hash_match', false, 'observation_hash_match', false, ...
    'initialization_identity_match', false, ...
    'failure_reason', string(reason), 'pass', false);
end

function comparison = initialization_comparison_local(snapshots)
roles = string({snapshots.role});
k1 = snapshots(roles == "K1_CONTEXT");
k2 = snapshots(roles == "K2_CONTEXT");
if numel(k1) ~= 1 || numel(k2) ~= 1
    comparison = struct('full_data_match', false, ...
        'initialization_identity_match', false, ...
        'initialization_output_match', false, ...
        'fixed_measurement_hash_match', false, 'pass', false, ...
        'failure_reason', "INITIALIZATION_SNAPSHOT_CARDINALITY");
    return;
end
comparison = struct( ...
    'full_data_match', k1.full_data_hash == k2.full_data_hash, ...
    'initialization_identity_match', k1.factory_invocation_hash == ...
    k2.factory_invocation_hash, ...
    'initialization_output_match', k1.initialization_output_hash == ...
    k2.initialization_output_hash, ...
    'fixed_measurement_hash_match', k1.fixed_measurement_hash == ...
    k2.fixed_measurement_hash, 'pass', false, 'failure_reason', "");
comparison.pass = comparison.full_data_match && ...
    comparison.initialization_identity_match && ...
    comparison.initialization_output_match && ...
    comparison.fixed_measurement_hash_match;
if ~comparison.pass
    comparison.failure_reason = "K1_K2_CONTEXT_OR_INITIALIZATION_MISMATCH";
end
end

function metadata = checkpoint_metadata_local(protocol, spec, identity, session_id)
metadata = struct('pass', 'PASS_B_QUERY_TRAJECTORY', ...
    'measurement_identity', char(string(identity)), ...
    'trial_id', char(spec.trial_id), 'repeat_index', 'NOT_APPLICABLE', ...
    'timing_mode', 'NOT_APPLICABLE', ...
    'level_a_closure_commit', protocol.level_a_closure_commit, ...
    'audit_start_commit', protocol.audit_start_commit, ...
    'audit_code_hash', protocol.audit_code_hash, ...
    'registry_hash', protocol.registry_hash, ...
    'MATLAB_release', version('-release'), 'singleCompThread', true, ...
    'timing_configuration_hash', protocol.timing_configuration_hash, ...
    'runtime_session_id', session_id);
end

function [reusable, checkpoint] = read_checkpoint_local(path_now, expected)
reusable = false;
checkpoint = struct();
if ~isfile(path_now), return; end
loaded = load(path_now, 'checkpoint');
if ~isfield(loaded, 'checkpoint'), return; end
checkpoint = loaded.checkpoint;
if ~isfield(checkpoint, 'metadata') || ...
        ~isfield(checkpoint, 'unit_complete') || ...
        ~logical(checkpoint.unit_complete)
    return;
end
actual = checkpoint.metadata;
names = setdiff(fieldnames(expected), {'runtime_session_id'});
for index = 1:numel(names)
    if ~isfield(actual, names{index}) || ...
            ~isequal(actual.(names{index}), expected.(names{index}))
        return;
    end
end
reusable = true;
end

function atomic_checkpoint_local(path_now, checkpoint)
temporary = [path_now, '.tmp'];
save(temporary, 'checkpoint', '-v7.3');
movefile(temporary, path_now, 'f');
end

function atomic_value_save_local(path_now, value)
temporary = [path_now, '.tmp'];
save(temporary, 'value', '-v7.3');
movefile(temporary, path_now, 'f');
end
