function output = stage8_k2_tcc_run_economics( ...
    static_output, query_output, runtime_output, micro_output, ...
    protocol, runtime_dir)
%STAGE8_K2_TCC_RUN_ECONOMICS Pass-E/F sequential counterfactual model.

if ~(static_output.all_pass && query_output.all_pass && ...
        runtime_output.all_pairs_complete)
    error('stage8_k2_tcc_run_economics:Correctness', ...
        'Pass E/F require completed correctness and runtime contracts.');
end
query = query_output.query_rows;
runtime_summary = runtime_output.runtime_summary;
micro = micro_output.summary;
identities = unique(query.fixed_measurement_hash, 'stable');
trial_rows = cell(numel(unique(query.trial_id)), 1);
exposure_cells = cell(numel(trial_rows), 1);
trial_ids = unique(query.trial_id, 'stable');
for trial_index = 1:numel(trial_ids)
    trial_id = trial_ids(trial_index);
    q = query(query.trial_id == trial_id, :);
    identity = q.fixed_measurement_hash(1);
    root = runtime_summary(runtime_summary.trial_id == trial_id & ...
        runtime_summary.timing_mode == "OFF" & ...
        runtime_summary.stage_id == "ROOT_TANGENT_PROFILE_SAFE", :);
    if height(root) ~= 1
        error('stage8_k2_tcc_run_economics:RuntimeRoot', ...
            'Each trial needs exactly one OFF root summary row.');
    end
    T0 = root.median_runtime_sec;
    structural = structural_saving_local(runtime_summary, trial_id);
    TS = T0 - structural.total;
    [delta_g, delta_cache, delta_cache_lower_micro, exposure] = ...
        query_savings_local(q, micro, identity);
    TSG = TS - delta_g.total;
    TSGC = TSG - delta_cache.total;
    k2_public = stage_median_local(runtime_summary, trial_id, 'K2_PUBLIC');
    core_structural = structural.k2_full_data + ...
        structural.k2_initialization + structural.k2_helper;
    core_direct = k2_public - core_structural - delta_g.k2;
    core_dictionary = core_direct - delta_cache.k2;
    delta_core = core_direct - core_dictionary;
    delta_tangent = TSG - TSGC;
    trial_rows{trial_index} = struct( ...
        'trial_id', trial_id, 'fixed_measurement_hash', identity, ...
        'noise_profile_id', q.noise_profile_id(1), 'L', q.L(1), ...
        'snr_db', q.snr_db(1), 'profile_id', q.profile_id(1), ...
        'T0', T0, 'TS', TS, 'TSG', TSG, 'TSGC', TSGC, ...
        'delta_structural', structural.total, ...
        'delta_g_only', delta_g.total, ...
        'delta_cache', delta_cache.total, ...
        'delta_cache_lower_micro', delta_cache_lower_micro, ...
        'core_direct', core_direct, ...
        'core_dictionary', core_dictionary, ...
        'delta_core', delta_core, 'delta_tangent', delta_tangent, ...
        'did_interaction_I', delta_tangent - delta_core);
    exposure.trial_id = repmat(trial_id, height(exposure), 1);
    exposure.fixed_measurement_hash = repmat(identity, height(exposure), 1);
    exposure_cells{trial_index} = exposure;
end
trial_counterfactual = struct2table(vertcat(trial_rows{:}));
exposure = vertcat(exposure_cells{:});

identity_rows = cell(numel(identities), 1);
lifecycle_cells = cell(numel(identities), 1);
for identity_index = 1:numel(identities)
    identity = identities(identity_index);
    trials = trial_counterfactual( ...
        trial_counterfactual.fixed_measurement_hash == identity, :);
    identity_exposure = exposure(exposure.fixed_measurement_hash == ...
        identity, :);
    costs = lifecycle_costs_local(micro, identity);
    point = sum(trials.delta_cache);
    micro_lower = sum(trials.delta_cache_lower_micro);
    instrumentation_penalty = instrumentation_penalty_local( ...
        runtime_output.paired_deltas, identity, height(trials));
    sensitivity = pooled_sensitivity_local( ...
        identity_exposure, micro_output.samples, identity, point);
    conservative_lower = micro_lower - instrumentation_penalty - sensitivity;
    per_run = mean(trials.delta_cache);
    if per_run > 0
        build_break_even = ceil(costs.build_inclusive / per_run);
        online_break_even = ceil(costs.online_only / per_run);
    else
        build_break_even = Inf;
        online_break_even = Inf;
    end
    identity_rows{identity_index} = economics_row_local( ...
        identity, sprintf('IDENTITY_%d_TRIALS', height(trials)), trials, ...
        identity_exposure, costs, conservative_lower, ...
        build_break_even, online_break_even, instrumentation_penalty, ...
        sensitivity);
    lifecycle_cells{identity_index} = lifecycle_curve_local( ...
        identity, per_run, costs);
end
economics = struct2table(vertcat(identity_rows{:}));
all_nonnegative = all(economics.predicted_delta_cache_point_sec >= 0);
overall = overall_row_local(economics, trial_counterfactual, exposure, ...
    all_nonnegative);
economics = [economics;struct2table(overall)];

lookup_faster = eligible_lookup_faster_local(exposure);
point = overall.predicted_delta_cache_point_sec;
lower = overall.conservative_timing_sensitivity_lower_bound_sec;
if point <= 0 || ~lookup_faster
    performance_status = "PREDICTED_SAVING_NONPOSITIVE";
elseif lower > 0 && all_nonnegative
    performance_status = "PREDICTED_SAVING_ROBUST_POSITIVE";
else
    performance_status = "PREDICTED_SAVING_INCONCLUSIVE";
end
economics.predicted_performance_status(:) = performance_status;
economics.economics_status(:) = ...
    "NOT_ASSESSED_NO_WORKLOAD_HORIZON";
economics.all_measurement_identities_nonnegative(:) = all_nonnegative;
lifecycle = vertcat(lifecycle_cells{:});
[recommended_placement, placement_ranking] = placement_local(exposure);
output = struct('trial_counterfactual', trial_counterfactual, ...
    'exposure', exposure, 'economics', economics, ...
    'lifecycle_curve', lifecycle, ...
    'predicted_performance_status', performance_status, ...
    'technical_certification_status', 'TECHNICALLY_CERTIFIED', ...
    'lookup_faster_than_direct_g_only', lookup_faster, ...
    'all_measurement_identities_nonnegative', all_nonnegative, ...
    'recommended_placement', recommended_placement, ...
    'placement_ranking', placement_ranking, ...
    'counterfactual_status', ...
    'COUNTERFACTUAL_ESTIMATE_NOT_INTEGRATED_RUNTIME', ...
    'JT_status', 'NOT_AVAILABLE_PRE_INTEGRATION', ...
    'exposure_adjusted_residual_JT', NaN, ...
    'timing_configuration_hash', protocol.timing_configuration_hash);
atomic_value_save_local(fullfile(runtime_dir, ...
    'pass_e_f_economics_attribution.mat'), output);
end

function structural = structural_saving_local(summary, trial_id)
structural = struct( ...
    'k2_full_data', stage_median_local(summary, trial_id, 'K2_FULL_DATA'), ...
    'tail_full_data', stage_median_local(summary, trial_id, 'TAIL_FULL_DATA'), ...
    'k2_initialization', stage_median_local( ...
    summary, trial_id, 'K2_INITIALIZATION_TOTAL'), ...
    'k2_helper', stage_median_local(summary, trial_id, 'K2_HELPER_K1'));
structural.total = structural.k2_full_data + structural.tail_full_data + ...
    structural.k2_initialization + structural.k2_helper;
end

function value = stage_median_local(summary, trial_id, stage_id)
row = summary(summary.trial_id == trial_id & ...
    summary.timing_mode == "TIMING_STAGE" & ...
    summary.stage_id == string(stage_id), :);
if isempty(row)
    value = 0;
else
    value = row.median_runtime_sec(1);
end
end

function [g, cache, cache_lower, exposure] = query_savings_local(q, micro, identity)
eliminated = startsWith(q.stage_id, "K2_INIT_") | ...
    q.stage_id == "K2_HELPER_K1" | ...
    contains(q.stage_id, "CURRENT_TCC_MODEL_INCOMPATIBLE");
q = q(~eliminated, :);
cost = micro_costs_local(micro, identity);
g = struct('single', 0, 'pair', 0, 'k2', 0, 'total', 0);
cache = struct('single', 0, 'pair', 0, 'k2', 0, 'total', 0);
cache_lower = 0;
rows = cell(height(q) * 2, 1);
row_index = 0;
for index = 1:height(q)
    eligible = q.g_only_eligible_build_count(index);
    pair_count = min(q.pair_count(index), eligible);
    single_count = max(0, eligible - pair_count);
    registered = q.registered_g_only_eligible_build_count(index);
    registered_pair = min(pair_count, registered);
    registered_single = max(0, registered - registered_pair);
    g_single = single_count * cost.g_delta_single;
    g_pair = pair_count * cost.g_delta_pair;
    c_single = registered_single * cost.cache_delta_single;
    c_pair = registered_pair * cost.cache_delta_pair;
    lower_single = registered_single * cost.cache_lower_single;
    lower_pair = registered_pair * cost.cache_lower_pair;
    g.single = g.single + g_single;
    g.pair = g.pair + g_pair;
    cache.single = cache.single + c_single;
    cache.pair = cache.pair + c_pair;
    cache_lower = cache_lower + lower_single + lower_pair;
    is_k2 = startsWith(q.stage_id(index), "K2_");
    if is_k2
        g.k2 = g.k2 + g_single + g_pair;
        cache.k2 = cache.k2 + c_single + c_pair;
    end
    if registered_single > 0
        row_index = row_index + 1;
        rows{row_index} = exposure_row_local(q.stage_id(index), ...
            'SINGLE', registered_single, cost.direct_single, ...
            cost.lookup_single, cost.cache_delta_single, c_single, ...
            lower_single);
    end
    if registered_pair > 0
        row_index = row_index + 1;
        rows{row_index} = exposure_row_local(q.stage_id(index), ...
            'PAIR', registered_pair, cost.direct_pair, cost.lookup_pair, ...
            cost.cache_delta_pair, c_pair, lower_pair);
    end
end
g.total = g.single + g.pair;
cache.total = cache.single + cache.pair;
rows = rows(1:row_index);
if isempty(rows)
    exposure = struct2table(repmat(exposure_row_local('', 'SINGLE', ...
        0, NaN, NaN, NaN, NaN, NaN), 0, 1));
else
    exposure = struct2table(vertcat(rows{:}));
end
end

function row = exposure_row_local(stage, class_id, count, direct, lookup, ...
    delta, contribution, lower)
row = struct('stage_id', string(stage), 'query_class', string(class_id), ...
    'eligible_query_count', double(count), ...
    'direct_g_only_sec_per_query', double(direct), ...
    'certified_lookup_sec_per_query', double(lookup), ...
    'delta_sec_per_query', double(delta), ...
    'predicted_contribution_sec', double(contribution), ...
    'conservative_micro_contribution_sec', double(lower));
end

function cost = micro_costs_local(micro, identity)
cost = struct( ...
    'legacy_single', micro_value_local(micro, identity, ...
    'LEGACY_FULL_SINGLE', 'median_runtime_sec'), ...
    'legacy_pair', micro_value_local(micro, identity, ...
    'LEGACY_FULL_PAIR', 'median_runtime_sec'), ...
    'direct_single', micro_value_local(micro, identity, ...
    'DIRECT_G_ONLY_SINGLE', 'median_runtime_sec'), ...
    'direct_pair', micro_value_local(micro, identity, ...
    'DIRECT_G_ONLY_PAIR', 'median_runtime_sec'), ...
    'rank_single', micro_value_local(micro, identity, ...
    'RANK_SINGLE', 'median_runtime_sec'), ...
    'rank_pair', micro_value_local(micro, identity, ...
    'RANK_PAIR', 'median_runtime_sec'), ...
    'lookup_single', micro_value_local(micro, identity, ...
    'CERTIFIED_REGISTERED_LOOKUP_SINGLE', 'median_runtime_sec'), ...
    'lookup_pair', micro_value_local(micro, identity, ...
    'CERTIFIED_REGISTERED_LOOKUP_PAIR', 'median_runtime_sec'));
cost.g_delta_single = cost.legacy_single - ...
    (cost.direct_single + cost.rank_single);
cost.g_delta_pair = cost.legacy_pair - ...
    (cost.direct_pair + cost.rank_pair);
cost.cache_delta_single = cost.direct_single - cost.lookup_single;
cost.cache_delta_pair = cost.direct_pair - cost.lookup_pair;
cost.cache_lower_single = micro_value_local(micro, identity, ...
    'DIRECT_G_ONLY_SINGLE', 'p10_runtime_sec') - ...
    micro_value_local(micro, identity, ...
    'CERTIFIED_REGISTERED_LOOKUP_SINGLE', 'p90_runtime_sec');
cost.cache_lower_pair = micro_value_local(micro, identity, ...
    'DIRECT_G_ONLY_PAIR', 'p10_runtime_sec') - ...
    micro_value_local(micro, identity, ...
    'CERTIFIED_REGISTERED_LOOKUP_PAIR', 'p90_runtime_sec');
end

function value = micro_value_local(micro, identity, benchmark, field)
row = micro(micro.fixed_measurement_hash == identity & ...
    micro.benchmark_id == string(benchmark), :);
if height(row) ~= 1
    error('stage8_k2_tcc_run_economics:Microbenchmark', ...
        'Missing identity-specific microbenchmark %s.', benchmark);
end
value = row.(field);
end

function costs = lifecycle_costs_local(micro, identity)
costs = struct( ...
    'build', micro_value_local(micro, identity, ...
    '21_KEY_BUILD', 'median_runtime_sec'), ...
    'load', micro_value_local(micro, identity, ...
    'DIAGNOSTIC_21_KEY_ARTIFACT_LOAD', 'median_runtime_sec'), ...
    'validate', micro_value_local(micro, identity, ...
    'IDENTITY_FULL_VALIDATE', 'median_runtime_sec'), ...
    'setup', micro_value_local(micro, identity, ...
    'PROVIDER_SETUP', 'median_runtime_sec'));
costs.build_inclusive = costs.build + costs.load + ...
    costs.validate + costs.setup;
costs.online_only = costs.load + costs.validate + costs.setup;
end

function penalty = instrumentation_penalty_local(pairs, identity, count)
values = pairs.instrumentation_overhead_sec( ...
    pairs.fixed_measurement_hash == identity);
penalty = max(0, prctile(values, 90)) * count;
end

function sensitivity = pooled_sensitivity_local(exposure, samples, identity, point)
other = samples(samples.fixed_measurement_hash ~= identity, :);
if isempty(other)
    sensitivity = 0;
    return;
end
single_direct = median(other.runtime_sec( ...
    other.benchmark_id == "DIRECT_G_ONLY_SINGLE"));
single_lookup = median(other.runtime_sec( ...
    other.benchmark_id == "CERTIFIED_REGISTERED_LOOKUP_SINGLE"));
pair_direct = median(other.runtime_sec( ...
    other.benchmark_id == "DIRECT_G_ONLY_PAIR"));
pair_lookup = median(other.runtime_sec( ...
    other.benchmark_id == "CERTIFIED_REGISTERED_LOOKUP_PAIR"));
single_count = sum(exposure.eligible_query_count( ...
    exposure.query_class == "SINGLE"));
pair_count = sum(exposure.eligible_query_count( ...
    exposure.query_class == "PAIR"));
alternative = single_count * (single_direct - single_lookup) + ...
    pair_count * (pair_direct - pair_lookup);
sensitivity = abs(point - alternative);
end

function row = economics_row_local(identity, aggregate, trials, exposure, ...
    costs, lower, build_be, online_be, instrumentation, sensitivity)
requested = sum(exposure.eligible_query_count);
unique_keys = 21;
row = struct( ...
    'fixed_measurement_hash', identity, ...
    'pipeline', "TANGENT_PROFILE_SAFE", ...
    'scenario_aggregate', string(aggregate), ...
    'measured_T0', sum(trials.T0), 'predicted_TS', sum(trials.TS), ...
    'predicted_TSG', sum(trials.TSG), ...
    'predicted_TSGC', sum(trials.TSGC), ...
    'predicted_delta_structural', sum(trials.delta_structural), ...
    'predicted_delta_g_only_given_structural', sum(trials.delta_g_only), ...
    'predicted_delta_cache_given_structural_g_only', ...
    sum(trials.delta_cache), ...
    'predicted_delta_cache_point_sec', sum(trials.delta_cache), ...
    'conservative_timing_sensitivity_lower_bound_sec', lower, ...
    'all_measurement_identities_nonnegative', true, ...
    'end_to_end_saving_percentage', ...
    100 * (sum(trials.T0) - sum(trials.TSGC)) / sum(trials.T0), ...
    'cache_build_sec', costs.build, 'cache_load_sec', costs.load, ...
    'cache_validate_once_sec', costs.validate, ...
    'cache_setup_sec', costs.setup, ...
    'online_only_break_even', online_be, ...
    'build_inclusive_break_even', build_be, ...
    'requested_columns', requested, 'unique_keys', unique_keys, ...
    'reuse_multiplicity', requested / unique_keys, ...
    'predicted_core_lite_direct', sum(trials.core_direct), ...
    'predicted_core_lite_dictionary', sum(trials.core_dictionary), ...
    'predicted_tangent_direct', sum(trials.TSG), ...
    'predicted_tangent_dictionary', sum(trials.TSGC), ...
    'predicted_delta_core', sum(trials.delta_core), ...
    'predicted_delta_tangent', sum(trials.delta_tangent), ...
    'predicted_did_interaction_I', sum(trials.did_interaction_I), ...
    'predicted_delta_tangent_exposure', ...
    sum(exposure.predicted_contribution_sec), ...
    'exposure_adjusted_residual_JT', NaN, ...
    'JT_status', "NOT_AVAILABLE_PRE_INTEGRATION", ...
    'predicted_performance_status', "PENDING_CLASSIFICATION", ...
    'economics_status', "NOT_ASSESSED_NO_WORKLOAD_HORIZON", ...
    'instrumentation_perturbation_penalty_sec', instrumentation, ...
    'identity_class_sensitivity_penalty_sec', sensitivity, ...
    'net_saving_build_inclusive_sec', ...
    sum(trials.delta_cache) - costs.build_inclusive, ...
    'net_saving_online_only_sec', ...
    sum(trials.delta_cache) - costs.online_only);
end

function row = overall_row_local(economics, trials, exposure, nonnegative)
row = table2struct(economics(1, :));
row.fixed_measurement_hash = "OVERALL_2_IDENTITIES";
row.scenario_aggregate = "OVERALL_72_TRIALS";
sum_fields = {'measured_T0','predicted_TS','predicted_TSG', ...
    'predicted_TSGC','predicted_delta_structural', ...
    'predicted_delta_g_only_given_structural', ...
    'predicted_delta_cache_given_structural_g_only', ...
    'predicted_delta_cache_point_sec', ...
    'conservative_timing_sensitivity_lower_bound_sec', ...
    'cache_build_sec','cache_load_sec','cache_validate_once_sec', ...
    'cache_setup_sec','requested_columns','unique_keys', ...
    'predicted_core_lite_direct','predicted_core_lite_dictionary', ...
    'predicted_tangent_direct','predicted_tangent_dictionary', ...
    'predicted_delta_core','predicted_delta_tangent', ...
    'predicted_did_interaction_I','predicted_delta_tangent_exposure', ...
    'instrumentation_perturbation_penalty_sec', ...
    'identity_class_sensitivity_penalty_sec', ...
    'net_saving_build_inclusive_sec','net_saving_online_only_sec'};
for index = 1:numel(sum_fields)
    row.(sum_fields{index}) = sum(economics.(sum_fields{index}));
end
row.end_to_end_saving_percentage = 100 * ...
    (row.measured_T0 - row.predicted_TSGC) / row.measured_T0;
row.reuse_multiplicity = row.requested_columns / row.unique_keys;
row.all_measurement_identities_nonnegative = nonnegative;
per_run = row.predicted_delta_cache_point_sec / height(trials);
build_cost = row.cache_build_sec + row.cache_load_sec + ...
    row.cache_validate_once_sec + row.cache_setup_sec;
online_cost = row.cache_load_sec + row.cache_validate_once_sec + ...
    row.cache_setup_sec;
if per_run > 0
    row.build_inclusive_break_even = ceil(build_cost / per_run);
    row.online_only_break_even = ceil(online_cost / per_run);
else
    row.build_inclusive_break_even = Inf;
    row.online_only_break_even = Inf;
end
row.predicted_delta_tangent_exposure = ...
    sum(exposure.predicted_contribution_sec);
end

function pass = eligible_lookup_faster_local(exposure)
groups = groupsummary(exposure, ...
    {'fixed_measurement_hash','query_class'}, 'sum', ...
    {'eligible_query_count','predicted_contribution_sec'});
groups = groups(groups.sum_eligible_query_count > 0, :);
pass = all(groups.sum_predicted_contribution_sec > 0);
end

function curve = lifecycle_curve_local(identity, per_run, costs)
N = [1;10;100;1000];
curve = table(repmat(identity, numel(N), 1), N, ...
    N * per_run - costs.build_inclusive, ...
    N * per_run - costs.online_only, 'VariableNames', ...
    {'fixed_measurement_hash','workload_N', ...
    'net_saving_build_inclusive_sec','net_saving_online_only_sec'});
end

function [placement, ranking] = placement_local(exposure)
ranking = groupsummary(exposure, 'stage_id', 'sum', ...
    {'eligible_query_count','predicted_contribution_sec'});
ranking = sortrows(ranking, 'sum_predicted_contribution_sec', 'descend');
if isempty(ranking) || ranking.sum_predicted_contribution_sec(1) <= 0
    placement = 'NO_MATERIAL_TCC_PLACEMENT';
elseif startsWith(ranking.stage_id(1), 'K1_FIXED')
    placement = 'CACHE_PLACEMENT_K1_FIXED_PREDICTED';
elseif ranking.stage_id(1) == "K2_NESTED_ANCHOR"
    placement = 'CACHE_PLACEMENT_NESTED_REGISTERED_PREDICTED';
elseif startsWith(ranking.stage_id(1), 'K2_')
    placement = 'CACHE_PLACEMENT_K2_REGISTERED_REFINEMENT_PREDICTED';
else
    placement = 'MULTIPLE_CACHE_PLACEMENT_CANDIDATES';
end
end

function atomic_value_save_local(path_now, value)
temporary = [path_now, '.tmp'];
save(temporary, 'value', '-v7.3');
movefile(temporary, path_now, 'f');
end
