function output = stage8_k2_tcc_run_microbenchmark( ...
    static_output, context, protocol, runtime_dir)
%STAGE8_K2_TCC_RUN_MICROBENCHMARK Run frozen Pass-D primitives.

benchmark_ids = [ ...
    "LEGACY_FULL_SINGLE","LEGACY_FULL_PAIR", ...
    "DIRECT_G_ONLY_SINGLE","DIRECT_G_ONLY_PAIR", ...
    "RANK_SINGLE","RANK_PAIR","IDENTITY_FULL_VALIDATE", ...
    "CURRENT_LEVEL_A_LOOKUP_SINGLE","CURRENT_LEVEL_A_LOOKUP_PAIR", ...
    "RAW_INDEXED_21_KEY_LOOKUP_SINGLE", ...
    "RAW_INDEXED_21_KEY_LOOKUP_PAIR", ...
    "CERTIFIED_REGISTERED_LOOKUP_SINGLE", ...
    "CERTIFIED_REGISTERED_LOOKUP_PAIR", ...
    "21_KEY_BUILD","PROVIDER_SETUP", ...
    "DIAGNOSTIC_21_KEY_ARTIFACT_LOAD"];
sample_cells = cell(numel(static_output.dictionaries), 1);
for identity_index = 1:numel(static_output.dictionaries)
    dictionary = static_output.dictionaries{identity_index};
    model = static_output.models{identity_index};
    domain = context.plan.local_domain;
    cache_options = struct('global_az_grid_deg', domain.az_grid_deg, ...
        'el_grid_deg', domain.el_grid_deg, ...
        'domain_bounds_deg', domain.domain_bounds_deg, ...
        'grid_step_deg', min([diff(domain.az_grid_deg), ...
        diff(domain.el_grid_deg)]), ...
        'measurement_config_id', model.measurement_config_id, ...
        'noise_profile_id', model.noise_profile_id, ...
        'rank_multiplier', 1);
    cache = stage8_k2_tcc_build_cache(model, cache_options);
    artifact_path = fullfile(runtime_dir, sprintf( ...
        'diagnostic_21_key_dictionary_%02d.mat', identity_index));
    save(artifact_path, 'dictionary', '-v7.3');
    angles = [dictionary.key_table.az_deg, dictionary.key_table.el_deg];
    pair_indices = nchoosek(1:dictionary.key_count, 2);
    pair_indices = [(1:dictionary.key_count).', ...
        (1:dictionary.key_count).';pair_indices];
    rows = cell(numel(benchmark_ids) * ...
        protocol.microbenchmark_repeat_target, 1);
    row_index = 0;
    for benchmark_index = 1:numel(benchmark_ids)
        benchmark_id = benchmark_ids(benchmark_index);
        for warmup = 1:protocol.microbenchmark_warmup_count
            invoke_local(benchmark_id, warmup, angles, pair_indices, ...
                dictionary, cache, model, domain, cache_options, ...
                artifact_path); %#ok<NASGU>
        end
        for repeat_index = 1:protocol.microbenchmark_repeat_target
            clock = tic;
            sink = invoke_local(benchmark_id, repeat_index, angles, ...
                pair_indices, dictionary, cache, model, domain, ...
                cache_options, artifact_path); %#ok<NASGU>
            elapsed = toc(clock);
            row_index = row_index + 1;
            rows{row_index} = struct( ...
                'fixed_measurement_hash', ...
                string(dictionary.fixed_measurement_hash), ...
                'noise_profile_id', string(dictionary.noise_profile_id), ...
                'benchmark_id', benchmark_id, ...
                'repeat_index', repeat_index, ...
                'runtime_sec', elapsed);
        end
    end
    sample_cells{identity_index} = struct2table(vertcat(rows{:}));
end
samples = vertcat(sample_cells{:});
summary = summarize_local(samples);
output = struct('samples', samples, 'summary', summary, ...
    'repeat_target', protocol.microbenchmark_repeat_target, ...
    'warmup_count', protocol.microbenchmark_warmup_count, ...
    'load_status', ...
    'DIAGNOSTIC_21_KEY_ARTIFACT_LOAD_MEASURED_NOT_PRODUCTION_FORMAT');
atomic_value_save_local(fullfile(runtime_dir, 'pass_d_microbenchmark.mat'), ...
    output);
end

function sink = invoke_local(id, repeat_index, angles, pairs, dictionary, ...
    cache, model, domain, cache_options, artifact_path)
if nargin < 10
    artifact_path = '';
end
single_index = mod(repeat_index - 1, size(angles, 1)) + 1;
pair_index = mod(repeat_index - 1, size(pairs, 1)) + 1;
indices = pairs(pair_index, :);
single_angle = angles(single_index, :);
pair_angles = angles(indices, :);
switch char(id)
    case 'LEGACY_FULL_SINGLE'
        sink = build_full_sequential_local_manifold( ...
            single_angle, model, struct('rank_multiplier', 1));
    case 'LEGACY_FULL_PAIR'
        sink = build_full_sequential_local_manifold( ...
            pair_angles, model, struct('rank_multiplier', 1));
    case 'DIRECT_G_ONLY_SINGLE'
        sink = stage8_k2_tcc_build_g_direct(single_angle, model, struct());
    case 'DIRECT_G_ONLY_PAIR'
        sink = stage8_k2_tcc_build_g_direct(pair_angles, model, struct());
    case 'RANK_SINGLE'
        G = dictionary.G(:, single_index);
        sink = stage8_k2_tcc_stable_matrix_rank(G, 1);
    case 'RANK_PAIR'
        G = dictionary.G(:, indices);
        sink = stage8_k2_tcc_stable_matrix_rank(G, 1);
    case 'IDENTITY_FULL_VALIDATE'
        sink = stage8_k2_tcc_validate_cache_identity( ...
            cache, model, cache_options);
    case 'CURRENT_LEVEL_A_LOOKUP_SINGLE'
        sink = stage8_k2_tcc_lookup_exact( ...
            cache, single_angle, model, cache_options);
    case 'CURRENT_LEVEL_A_LOOKUP_PAIR'
        first = stage8_k2_tcc_lookup_exact( ...
            cache, pair_angles(1, :), model, cache_options);
        second = stage8_k2_tcc_lookup_exact( ...
            cache, pair_angles(2, :), model, cache_options);
        sink = [first,second];
    case 'RAW_INDEXED_21_KEY_LOOKUP_SINGLE'
        sink = dictionary.G(:, single_index);
    case 'RAW_INDEXED_21_KEY_LOOKUP_PAIR'
        sink = dictionary.G(:, indices);
    case 'CERTIFIED_REGISTERED_LOOKUP_SINGLE'
        sink = stage8_k2_tcc_registered_lookup( ...
            dictionary, single_angle, model);
    case 'CERTIFIED_REGISTERED_LOOKUP_PAIR'
        sink = stage8_k2_tcc_registered_lookup( ...
            dictionary, pair_angles, model);
    case '21_KEY_BUILD'
        sink = stage8_k2_tcc_build_registered_dictionary( ...
            model, domain, struct());
    case 'PROVIDER_SETUP'
        sink = stage8_k2_tcc_build_provider( ...
            'EXACT_CACHE_OR_DIRECT', model, cache, cache_options);
    case 'DIAGNOSTIC_21_KEY_ARTIFACT_LOAD'
        sink = load(artifact_path, 'dictionary');
    otherwise
        error('stage8_k2_tcc_run_microbenchmark:Benchmark', ...
            'Unsupported benchmark: %s.', id);
end
end

function summary = summarize_local(samples)
identities = unique(samples.fixed_measurement_hash, 'stable');
benchmarks = unique(samples.benchmark_id, 'stable');
rows = cell(numel(identities) * numel(benchmarks), 1);
row_index = 0;
for identity_index = 1:numel(identities)
    for benchmark_index = 1:numel(benchmarks)
        subset = samples(samples.fixed_measurement_hash == ...
            identities(identity_index) & samples.benchmark_id == ...
            benchmarks(benchmark_index), :);
        values = subset.runtime_sec;
        row_index = row_index + 1;
        rows{row_index} = struct( ...
            'fixed_measurement_hash', identities(identity_index), ...
            'noise_profile_id', subset.noise_profile_id(1), ...
            'benchmark_id', benchmarks(benchmark_index), ...
            'repeat_count', numel(values), 'median_runtime_sec', ...
            median(values), 'p10_runtime_sec', prctile(values, 10), ...
            'p90_runtime_sec', prctile(values, 90), ...
            'min_runtime_sec', min(values), 'max_runtime_sec', max(values));
    end
end
summary = struct2table(vertcat(rows{:}));
end

function atomic_value_save_local(path_now, value)
temporary = [path_now, '.tmp'];
save(temporary, 'value', '-v7.3');
movefile(temporary, path_now, 'f');
end
