function output = stage8_k2_tcc_run_placement_audit( ...
    action, repo_dir, runtime_dir, options)
%STAGE8_K2_TCC_RUN_PLACEMENT_AUDIT Checkpointed Pass-A through evidence.

if nargin < 1 || isempty(action), action = 'PREPARE'; end
if nargin < 2 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0, error('stage8_k2_tcc_run_placement_audit:Repository', ...
            'Unable to locate repository root.'); end
    repo_dir = strtrim(repo_dir);
end
if nargin < 3 || isempty(runtime_dir)
    runtime_dir = ...
        'E:\bs_innovation_runtime\stage8_k2_tangent_pipeline_cache_placement_audit';
end
if nargin < 4 || isempty(options), options = struct(); end
if ~isfolder(runtime_dir), mkdir(runtime_dir); end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
context = stage8_k2_tp_build_context(repo_dir);
registry = stage8_k2_tp_build_registry( ...
    context.plan.local_domain, context.constants);
protocol = stage8_k2_tcc_audit_protocol(repo_dir, registry);
action = upper(char(string(action)));
switch action
    case 'PREPARE'
        output = struct('context_hash', context.context_hash, ...
            'registry', registry, 'protocol', protocol);
    case 'PASS_A'
        output = stage8_k2_tcc_run_static_certification( ...
            context, registry, runtime_dir);
    case 'PASS_B_WORKER'
        static_output = load_value_local(runtime_dir, ...
            'pass_a_static_certification.mat');
        output = stage8_k2_tcc_run_query_audit(context, registry, ...
            static_output, protocol, runtime_dir, options);
    case 'PASS_B_AGGREGATE'
        static_output = load_value_local(runtime_dir, ...
            'pass_a_static_certification.mat');
        aggregate_options = struct('trial_indices', 1:height(registry), ...
            'shard_id', 0);
        output = stage8_k2_tcc_run_query_audit(context, registry, ...
            static_output, protocol, runtime_dir, aggregate_options);
    case 'PASS_C_WORKER'
        output = stage8_k2_tcc_run_runtime_audit( ...
            context, registry, protocol, runtime_dir, options);
    case 'PASS_C_AGGREGATE'
        output = stage8_k2_tcc_run_runtime_audit(context, registry, ...
            protocol, runtime_dir, struct('mode', 'AGGREGATE'));
    case 'PASS_D'
        static_output = load_value_local(runtime_dir, ...
            'pass_a_static_certification.mat');
        output = stage8_k2_tcc_run_microbenchmark( ...
            static_output, context, protocol, runtime_dir);
    case 'PASS_EF'
        static_output = load_value_local(runtime_dir, ...
            'pass_a_static_certification.mat');
        query_output = load_value_local(runtime_dir, ...
            'pass_b_query_audit.mat');
        runtime_output = load_value_local(runtime_dir, ...
            'pass_c_runtime_audit.mat');
        micro_output = load_value_local(runtime_dir, ...
            'pass_d_microbenchmark.mat');
        output = stage8_k2_tcc_run_economics(static_output, query_output, ...
            runtime_output, micro_output, protocol, runtime_dir);
    case 'EVIDENCE'
        required = {'git_metadata'};
        if ~all(isfield(options, required))
            error('stage8_k2_tcc_run_placement_audit:GitMetadata', ...
                'EVIDENCE requires options.git_metadata.');
        end
        static_output = load_value_local(runtime_dir, ...
            'pass_a_static_certification.mat');
        query_output = load_value_local(runtime_dir, ...
            'pass_b_query_audit.mat');
        runtime_output = load_value_local(runtime_dir, ...
            'pass_c_runtime_audit.mat');
        micro_output = load_value_local(runtime_dir, ...
            'pass_d_microbenchmark.mat');
        economics_output = load_value_local(runtime_dir, ...
            'pass_e_f_economics_attribution.mat');
        output = stage8_k2_tcc_write_evidence(repo_dir, static_output, ...
            query_output, runtime_output, micro_output, economics_output, ...
            protocol, options.git_metadata);
    case 'ALL_SERIAL'
        static_output = stage8_k2_tcc_run_static_certification( ...
            context, registry, runtime_dir);
        query_output = stage8_k2_tcc_run_query_audit(context, registry, ...
            static_output, protocol, runtime_dir, struct());
        runtime_output = stage8_k2_tcc_run_runtime_audit(context, registry, ...
            protocol, runtime_dir, struct('mode', 'WORKER', ...
            'trial_indices', 1:height(registry), 'shard_id', 1, ...
            'aggregate_after_worker', true));
        micro_output = stage8_k2_tcc_run_microbenchmark( ...
            static_output, context, protocol, runtime_dir);
        economics_output = stage8_k2_tcc_run_economics(static_output, ...
            query_output, runtime_output, micro_output, protocol, runtime_dir);
        output = struct('static', static_output, 'query', query_output, ...
            'runtime', runtime_output, 'micro', micro_output, ...
            'economics', economics_output);
    otherwise
        error('stage8_k2_tcc_run_placement_audit:Action', ...
            'Unsupported action: %s.', action);
end
end

function value = load_value_local(runtime_dir, filename)
path_now = fullfile(runtime_dir, filename);
if ~isfile(path_now)
    error('stage8_k2_tcc_run_placement_audit:MissingPass', ...
        'Required pass output is missing: %s', path_now);
end
loaded = load(path_now, 'value');
if ~isfield(loaded, 'value')
    error('stage8_k2_tcc_run_placement_audit:PassFormat', ...
        'Pass output does not contain value: %s', path_now);
end
value = loaded.value;
end
