function [G, manifold_info, provider_info] = ...
    stage8_k2_tcc_get_pair_manifold(angles_deg, model, provider, options)
%STAGE8_K2_TCC_GET_PAIR_MANIFOLD Build ordered columns and rank once.

if nargin < 4 || isempty(options)
    options = struct();
end
if ~(isnumeric(angles_deg) && ismatrix(angles_deg) && ...
        size(angles_deg, 2) == 2 && ~isempty(angles_deg) && ...
        all(isfinite(angles_deg(:))))
    error('stage8_k2_tcc_get_pair_manifold:Angles', ...
        'angles_deg must be a finite K-by-2 matrix.');
end
K = size(angles_deg, 1);
clock = tic;
columns = cell(K, 1);
column_sources = strings(K, 1);
cache_hit_count = 0;
cache_miss_count = 0;
direct_fallback_count = 0;
identity_rejection_count = 0;
lookup_runtime = 0;
direct_runtime = 0;
for index = 1:K
    [columns{index}, single_info] = ...
        stage8_k2_tcc_get_single_target_g( ...
        angles_deg(index, :), model, provider);
    column_sources(index) = string(single_info.source);
    cache_hit_count = cache_hit_count + double(single_info.cache_hit);
    cache_miss_count = cache_miss_count + double( ...
        contains(string(single_info.cache_miss_reason), 'OFF_GRID') || ...
        contains(string(single_info.cache_miss_reason), 'UNAVAILABLE') || ...
        contains(string(single_info.cache_miss_reason), 'MISMATCH'));
    direct_fallback_count = direct_fallback_count + double( ...
        strcmp(single_info.source, 'DIRECT_FALLBACK') || ...
        strcmp(single_info.source, 'DIRECT_ONLY'));
    identity_rejection_count = identity_rejection_count + ...
        double(single_info.identity_rejection_count);
    lookup_runtime = lookup_runtime + double(single_info.lookup_runtime_sec);
    direct_runtime = direct_runtime + double(single_info.direct_runtime_sec);
end
G = [columns{:}];
rank_multiplier = 1;
if isfield(options, 'rank_multiplier') && ~isempty(options.rank_multiplier)
    rank_multiplier = options.rank_multiplier;
elseif isfield(provider, 'options') && ...
        isfield(provider.options, 'rank_multiplier')
    rank_multiplier = provider.options.rank_multiplier;
end
rank_clock = tic;
[rank_value, singular_values, threshold] = ...
    stage8_k2_tcc_stable_matrix_rank(G, rank_multiplier);
rank_runtime = toc(rank_clock);
manifold_info = struct('rank_Gseq', rank_value, ...
    'singular_values_Gseq', singular_values, ...
    'rank_threshold_Gseq', threshold, 'num_svd', 1, ...
    'target_angles_deg', double(angles_deg), ...
    'fixed_measurement_hash', provider.fixed_measurement_hash, ...
    'phase_factor', 1, 'direct_g_only_flag', true, ...
    'full_receive_geometry_used_flag', false, ...
    'Gseq_size', size(G));
provider_info = struct('mode', char(string(provider.mode)), ...
    'column_sources', column_sources, ...
    'cache_hit_count', cache_hit_count, ...
    'cache_miss_count', cache_miss_count, ...
    'direct_fallback_count', direct_fallback_count, ...
    'identity_rejection_count', identity_rejection_count, ...
    'lookup_runtime_sec', lookup_runtime, ...
    'direct_runtime_sec', direct_runtime, ...
    'rank_runtime_sec', rank_runtime, ...
    'total_runtime_sec', toc(clock), ...
    'fixed_measurement_hash', provider.fixed_measurement_hash);
end
