function output = stage8_k2_tcc_run_validation(repo_dir, runtime_dir)
%STAGE8_K2_TCC_RUN_VALIDATION Run compact equivalence and runtime evidence.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_tcc_run_validation:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
if nargin < 2 || isempty(runtime_dir)
    runtime_dir = 'E:\bs_innovation_runtime\stage8_k2_tangent_canonical_cache_v1';
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
if ~isfolder(runtime_dir)
    mkdir(runtime_dir);
end
scope = stage8_k2_tcc_add_paths(repo_dir); %#ok<NASGU>
output_dir = fullfile(repo_dir, 'innovation-mining');
test_summary = stage8_k2_tcc_run_tests(repo_dir);

context = stage8_k2_tp_build_context(repo_dir);
registry = stage8_k2_tp_build_registry( ...
    context.plan.local_domain, context.constants);
selected = registry.noise_profile_id == "WHITE" & registry.L == 8 & ...
    registry.snr_db == 6 & ismember(registry.profile_id, ...
    ["P1", "P2", "P3", "P4"]);
specs = registry(selected, :);
if height(specs) ~= 4
    error('stage8_k2_tcc_run_validation:Registry', ...
        'The compact validation requires four registered trials.');
end

model = resolve_stage8_measurement_model( ...
    context.plan.measurement_model_registry, ...
    context.primary_measurement_config_id, 'WHITE');
cache_options = struct('domain_bounds_deg', ...
    context.plan.local_domain.domain_bounds_deg);
[cache, cache_info] = stage8_k2_tcc_build_cache(model, cache_options);
direct_provider = stage8_k2_tcc_build_provider( ...
    'DIRECT_ONLY', model, [], struct());
hybrid_provider = stage8_k2_tcc_build_provider( ...
    'EXACT_CACHE_OR_DIRECT', model, cache, struct());

equivalence_rows = repmat(equivalence_template_local(), 0, 1);
trial_records = repmat(struct('spec', [], 'trial', [], ...
    'legacy', [], 'direct', [], 'hybrid', [], ...
    'legacy_diag', [], 'direct_diag', [], 'hybrid_diag', []), ...
    height(specs), 1);
for index = 1:height(specs)
    spec = specs(index, :);
    % This call creates one deterministic element trial and evaluates legacy.
    [legacy_rows, legacy_diag_table, trial] = ...
        stage8_k2_tp_evaluate_trial(spec, context);
    legacy_row = legacy_rows(legacy_rows.method_id == ...
        "TANGENT_PROFILE_SAFE", :);
    direct_context = context;
    direct_context.manifold_provider = direct_provider;
    hybrid_context = context;
    hybrid_context.manifold_provider = hybrid_provider;
    [direct_result, direct_diag] = stage8_k2_tp_fit_safe( ...
        trial.Y_element, trial.model, direct_context);
    [hybrid_result, hybrid_diag] = stage8_k2_tp_fit_safe( ...
        trial.Y_element, trial.model, hybrid_context);
    legacy = fit_summary_local(legacy_row, legacy_diag_table, ...
        trial.element_trial_hash, 'LEGACY_DIRECT');
    direct = fit_summary_local(direct_result, direct_diag, ...
        trial.element_trial_hash, 'DIRECT_ONLY');
    hybrid = fit_summary_local(hybrid_result, hybrid_diag, ...
        trial.element_trial_hash, 'EXACT_CACHE_OR_DIRECT');
    trial_records(index) = struct('spec', spec, 'trial', trial, ...
        'legacy', legacy, 'direct', direct, 'hybrid', hybrid, ...
        'legacy_diag', legacy_diag_table, 'direct_diag', direct_diag, ...
        'hybrid_diag', hybrid_diag);
    equivalence_rows(end + 1, 1) = build_equivalence_row_local( ...
        spec, trial, legacy, direct, model, hybrid_provider, ...
        'LEGACY_DIRECT_VS_DIRECT_ONLY'); %#ok<AGROW>
    equivalence_rows(end + 1, 1) = build_equivalence_row_local( ...
        spec, trial, direct, hybrid, model, hybrid_provider, ...
        'DIRECT_ONLY_VS_EXACT_CACHE_OR_DIRECT'); %#ok<AGROW>
    fprintf('VALIDATED %s (%d/%d) hits=%d misses=%d\n', ...
        char(spec.trial_id), index, height(specs), ...
        hybrid.cache_hit_count, hybrid.cache_miss_count);
end
equivalence = struct2table(equivalence_rows);

runtime = run_benchmarks_local(model, cache, cache_info, ...
    direct_provider, hybrid_provider, trial_records(1), context);
manifest = build_manifest_local(repo_dir, model, cache, ...
    cache_info, equivalence, runtime, trial_records, test_summary);
write_validation_files_local(output_dir, equivalence, runtime, manifest, ...
    cache_info);

output = struct('equivalence', equivalence, 'runtime', runtime, ...
    'manifest', manifest, 'test_summary', test_summary, 'cache', cache, ...
    'cache_info', cache_info, 'trial_records', trial_records);
fprintf('STAGE8_K2_TCC_VALIDATION_COMPLETE rows=%d runtime_rows=%d\n', ...
    height(equivalence), height(runtime));
end

function row = equivalence_template_local()
row = struct('case_id', "", 'comparison', "", ...
    'fixed_measurement_hash', "", 'element_trial_hash', "", ...
    'provider_mode', "", 'max_G_abs_error', NaN, ...
    'G_relative_error', NaN, 'rank_reference', NaN, ...
    'rank_candidate', NaN, 'rank_match', false, ...
    'max_scan_loglik_abs_error', NaN, 'rho_hat_abs_error_deg', NaN, ...
    'max_angle_abs_error_deg', NaN, 'RSS_abs_error', NaN, ...
    'loglik_abs_error', NaN, 'selected_source_reference', "", ...
    'selected_source_candidate', "", 'selected_source_match', false, ...
    'upgrade_match', false, 'fallback_match', false, ...
    'cache_hit_count', 0, 'cache_miss_count', 0, ...
    'direct_fallback_count', 0, 'identity_rejection_count', 0, ...
    'pass', false, 'failure_reason', "");
end

function summary = fit_summary_local(result_or_row, diagnostics, hash, mode)
summary = struct('provider_mode', string(mode), ...
    'element_trial_hash', string(hash), 'fit_valid', false, ...
    'angles_hat_deg', NaN(2, 2), 'rss', NaN, 'loglik', NaN, ...
    'effective_rank', 0, 'selected_source', "NOT_RUN", ...
    'upgrade_flag', false, 'fallback_flag', true, ...
    'fallback_reason', "NOT_RUN", 'score_call_count', 0, ...
    'svd_call_count', 0, 'rho_hat_deg', NaN, ...
    'trace_rho', [], 'trace_loglik', [], 'trace_valid', false(0, 1), ...
    'trace_status', strings(0, 1), 'cache_hit_count', 0, ...
    'cache_miss_count', 0, 'direct_fallback_count', 0, ...
    'identity_rejection_count', 0, 'truth_used_in_fit_flag', false);
summary.fit_valid = logical(field_value_local(result_or_row, 'fit_valid'));
summary.angles_hat_deg = parse_angles_local( ...
    field_value_local(result_or_row, 'angles_hat_deg'));
summary.rss = double(field_value_local(result_or_row, 'RSS', ...
    field_value_local(result_or_row, 'rss', NaN)));
summary.loglik = double(field_value_local(result_or_row, 'loglik', ...
    field_value_local(result_or_row, 'loglik_concentrated', NaN)));
summary.effective_rank = double(field_value_local(result_or_row, ...
    'effective_rank', 0));
summary.selected_source = string(field_value_local(result_or_row, ...
    'selected_source', 'NOT_RUN'));
summary.score_call_count = double(field_value_local(result_or_row, ...
    'score_call_count', 0));
summary.svd_call_count = double(field_value_local(result_or_row, ...
    'SVD_call_count', field_value_local(result_or_row, ...
    'svd_call_count', 0)));
summary.rho_hat_deg = double(field_value_local(diagnostics, ...
    'rho_hat_deg', NaN));
summary.upgrade_flag = logical(field_value_local(diagnostics, ...
    'upgrade_flag', false));
summary.fallback_flag = logical(field_value_local(diagnostics, ...
    'fallback_flag', true));
summary.fallback_reason = string(field_value_local(diagnostics, ...
    'fallback_reason', 'NOT_RUN'));
summary.truth_used_in_fit_flag = logical(field_value_local( ...
    result_or_row, 'truth_used_in_fit_flag', false));
if isstruct(diagnostics) && isfield(diagnostics, 'evaluated_rho_deg')
    summary.trace_rho = diagnostics.evaluated_rho_deg(:);
    summary.trace_loglik = diagnostics.evaluated_loglik(:);
    summary.trace_valid = diagnostics.evaluated_valid(:);
    summary.trace_status = diagnostics.evaluated_status(:);
    summary.cache_hit_count = diagnostics.cache_hit_count;
    summary.cache_miss_count = diagnostics.cache_miss_count;
    summary.direct_fallback_count = diagnostics.direct_fallback_count;
    summary.identity_rejection_count = diagnostics.identity_rejection_count;
end
end

function row = build_equivalence_row_local(spec, trial, reference, ...
    candidate, model, hybrid_provider, comparison)
row = equivalence_template_local();
row.case_id = string(spec.trial_id);
row.comparison = string(comparison);
row.fixed_measurement_hash = string(model.fixed_measurement_hash);
row.element_trial_hash = string(trial.element_trial_hash);
row.provider_mode = candidate.provider_mode;
reference_angles = reference.angles_hat_deg;
if any(~isfinite(reference_angles(:)))
    row.failure_reason = "REFERENCE_ANGLES_INVALID";
    return;
end
[G_full, ~, full_info] = build_full_sequential_local_manifold( ...
    reference_angles, model, struct('rank_multiplier', 1));
G_direct = stage8_k2_tcc_build_g_direct(reference_angles, model, struct());
if strcmp(candidate.provider_mode, 'EXACT_CACHE_OR_DIRECT')
    [G_candidate, candidate_manifold_info, provider_info] = ...
        stage8_k2_tcc_get_pair_manifold(reference_angles, model, ...
        hybrid_provider, struct('rank_multiplier', 1));
else
    G_candidate = G_direct;
    [candidate_rank, candidate_singular, candidate_threshold] = ...
        stage8_k2_tcc_stable_matrix_rank(G_candidate, 1);
    candidate_manifold_info = struct('rank_Gseq', candidate_rank, ...
        'singular_values_Gseq', candidate_singular, ...
        'rank_threshold_Gseq', candidate_threshold);
    provider_info = struct('cache_hit_count', 0, 'cache_miss_count', 0, ...
        'direct_fallback_count', 0, 'identity_rejection_count', 0);
end
row.max_G_abs_error = max(abs(G_candidate(:) - G_direct(:)));
row.G_relative_error = norm(G_candidate - G_direct, 'fro') / ...
    max(norm(G_direct, 'fro'), realmin);
row.rank_reference = full_info.rank_Gseq;
row.rank_candidate = candidate_manifold_info.rank_Gseq;
row.rank_match = row.rank_reference == row.rank_candidate;
if strcmp(reference.provider_mode, 'LEGACY_DIRECT')
    row.max_G_abs_error = max(abs(G_direct(:) - G_full(:)));
    row.G_relative_error = norm(G_direct - G_full, 'fro') / ...
        max(norm(G_full, 'fro'), realmin);
end
row.max_scan_loglik_abs_error = trace_error_local(reference, candidate);
row.rho_hat_abs_error_deg = abs(reference.rho_hat_deg - ...
    candidate.rho_hat_deg);
row.max_angle_abs_error_deg = max(abs(reference.angles_hat_deg(:) - ...
    candidate.angles_hat_deg(:)));
row.RSS_abs_error = abs(reference.rss - candidate.rss);
row.loglik_abs_error = abs(reference.loglik - candidate.loglik);
row.selected_source_reference = reference.selected_source;
row.selected_source_candidate = candidate.selected_source;
row.selected_source_match = strcmp(reference.selected_source, ...
    candidate.selected_source);
row.upgrade_match = reference.upgrade_flag == candidate.upgrade_flag;
row.fallback_match = reference.fallback_flag == candidate.fallback_flag && ...
    reference.fallback_reason == candidate.fallback_reason;
row.cache_hit_count = provider_info.cache_hit_count;
row.cache_miss_count = provider_info.cache_miss_count;
row.direct_fallback_count = provider_info.direct_fallback_count;
row.identity_rejection_count = provider_info.identity_rejection_count;
scan_pass = isnan(row.max_scan_loglik_abs_error) || ...
    row.max_scan_loglik_abs_error <= 1e-8 * max(1, ...
    max(abs(reference.trace_loglik), [], 'omitnan'));
row.pass = row.rank_match && row.selected_source_match && ...
    row.upgrade_match && row.fallback_match && ...
    row.G_relative_error <= 1e-10 && scan_pass && ...
    row.rho_hat_abs_error_deg <= 2e-4 && ...
    row.max_angle_abs_error_deg <= 2e-4 && ...
    row.RSS_abs_error <= 1e-8 * max(1, abs(reference.rss)) && ...
    row.loglik_abs_error <= 1e-8 * max(1, abs(reference.loglik)) && ...
    ~reference.truth_used_in_fit_flag && ~candidate.truth_used_in_fit_flag;
if row.pass
    row.failure_reason = "NOT_APPLICABLE";
else
    reasons = strings(0, 1);
    if ~row.rank_match, reasons(end + 1) = "RANK_MISMATCH"; end %#ok<AGROW>
    if ~row.selected_source_match, reasons(end + 1) = "SOURCE_MISMATCH"; end %#ok<AGROW>
    if ~row.upgrade_match, reasons(end + 1) = "UPGRADE_MISMATCH"; end %#ok<AGROW>
    if ~row.fallback_match, reasons(end + 1) = "FALLBACK_MISMATCH"; end %#ok<AGROW>
    if row.G_relative_error > 1e-10, reasons(end + 1) = "G_NOT_EQUIVALENT"; end %#ok<AGROW>
    if ~scan_pass, reasons(end + 1) = "SCAN_NOT_EQUIVALENT"; end %#ok<AGROW>
    if row.rho_hat_abs_error_deg > 2e-4, reasons(end + 1) = "RHO_MISMATCH"; end %#ok<AGROW>
    row.failure_reason = strjoin(reasons, '|');
end
end

function value = trace_error_local(reference, candidate)
if isempty(reference.trace_rho) || isempty(candidate.trace_rho) || ...
        numel(reference.trace_rho) ~= numel(candidate.trace_rho) || ...
        any(reference.trace_rho ~= candidate.trace_rho)
    value = NaN;
    return;
end
left = reference.trace_loglik(:);
right = candidate.trace_loglik(:);
finite_pair = isfinite(left) & isfinite(right);
value = 0;
if any(finite_pair)
    value = max(abs(left(finite_pair) - right(finite_pair)));
end
if any(xor(isfinite(left), isfinite(right)))
    value = Inf;
end
end

function value = field_value_local(source, name, fallback)
if nargin < 3
    fallback = NaN;
end
if istable(source)
    if ismember(name, source.Properties.VariableNames)
        value = source.(name)(1);
    else
        value = fallback;
    end
elseif isstruct(source) && isfield(source, name)
    value = source.(name);
else
    value = fallback;
end
end

function angles = parse_angles_local(value)
if isnumeric(value)
    angles = double(value);
else
    angles = str2num(char(value)); %#ok<ST2NM>
end
end

function runtime = run_benchmarks_local(model, cache, cache_info, ...
    direct_provider, hybrid_provider, record, context)
micro_repeats = 30;
profile_repeats = 10;
end_to_end_repeats = 3;
rows = repmat(runtime_template_local(), 0, 1);
rows(end + 1, 1) = runtime_row_local('CACHE_BUILD', 'cache_build', ...
    'NOT_APPLICABLE', 1, cache_info.cache_build_time_sec, ...
    cache_info.cache_build_time_sec, sample_template_local(), ...
    cache.cache_memory_MB, NaN, NaN); %#ok<AGROW>

exact_first = [cache.global_az_grid_deg(1), cache.el_grid_deg(1)];
exact_second = [cache.global_az_grid_deg(end), cache.el_grid_deg(end)];
off_grid = [mean(cache.global_az_grid_deg) + 0.004, ...
    mean(cache.el_grid_deg) + 0.004];
direct_single_callback = @() sample_single_local( ...
    off_grid, model, direct_provider);
cache_single_callback = @() sample_single_local( ...
    exact_first, model, hybrid_provider);
[direct_single_stats, direct_single_sample] = ...
    measure_operation_local(direct_single_callback, micro_repeats);
[cache_single_stats, cache_single_sample] = ...
    measure_operation_local(cache_single_callback, micro_repeats);
rows(end + 1, 1) = runtime_row_from_stats_local( ...
    'SINGLE_DIRECT', 'single_target_direct_g_only', 'DIRECT_ONLY', ...
    direct_single_stats, direct_single_sample, cache.cache_memory_MB, 1, NaN); %#ok<AGROW>
single_speedup = direct_single_stats.median / cache_single_stats.median;
single_break_even = break_even_local(cache_info.cache_build_time_sec, ...
    direct_single_stats.median, cache_single_stats.median);
rows(end + 1, 1) = runtime_row_from_stats_local( ...
    'SINGLE_CACHE', 'single_target_exact_cache_lookup', ...
    'EXACT_CACHE_OR_DIRECT', cache_single_stats, cache_single_sample, ...
    cache.cache_memory_MB, single_speedup, single_break_even); %#ok<AGROW>

pair_exact = [exact_first; exact_second];
pair_mixed = [exact_first; off_grid];
direct_pair_callback = @() sample_pair_local( ...
    pair_exact, model, direct_provider);
cache_pair_callback = @() sample_pair_local( ...
    pair_exact, model, hybrid_provider);
mixed_pair_callback = @() sample_pair_local( ...
    pair_mixed, model, hybrid_provider);
[direct_pair_stats, direct_pair_sample] = ...
    measure_operation_local(direct_pair_callback, micro_repeats);
[cache_pair_stats, cache_pair_sample] = ...
    measure_operation_local(cache_pair_callback, micro_repeats);
[mixed_pair_stats, mixed_pair_sample] = ...
    measure_operation_local(mixed_pair_callback, micro_repeats);
rows(end + 1, 1) = runtime_row_from_stats_local( ...
    'PAIR_DIRECT', 'pair_direct_g_only', 'DIRECT_ONLY', ...
    direct_pair_stats, direct_pair_sample, cache.cache_memory_MB, 1, NaN); %#ok<AGROW>
pair_speedup = direct_pair_stats.median / cache_pair_stats.median;
pair_break_even = break_even_local(cache_info.cache_build_time_sec, ...
    direct_pair_stats.median, cache_pair_stats.median);
rows(end + 1, 1) = runtime_row_from_stats_local( ...
    'PAIR_CACHE_CACHE', 'pair_cache_cache', 'EXACT_CACHE_OR_DIRECT', ...
    cache_pair_stats, cache_pair_sample, cache.cache_memory_MB, ...
    pair_speedup, pair_break_even); %#ok<AGROW>
rows(end + 1, 1) = runtime_row_from_stats_local( ...
    'PAIR_MIXED', 'pair_cache_direct_mixed', 'EXACT_CACHE_OR_DIRECT', ...
    mixed_pair_stats, mixed_pair_sample, cache.cache_memory_MB, ...
    direct_pair_stats.median / mixed_pair_stats.median, NaN); %#ok<AGROW>

full_data = build_stage8_full_data_from_element( ...
    record.trial.Y_element, model, struct( ...
    'data_role', 'SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
center = reshape(record.direct_diag.K1_center_deg, 1, 2);
direction = record.direct_diag.direction_hat;
domain = context.plan.local_domain;
constants = context.constants;
direct_profile_callback = @() sample_profile_local(full_data.Zseq_white, ...
    model, center, direction, domain, constants, direct_provider);
hybrid_profile_callback = @() sample_profile_local(full_data.Zseq_white, ...
    model, center, direction, domain, constants, hybrid_provider);
[direct_profile_stats, direct_profile_sample] = ...
    measure_operation_local(direct_profile_callback, profile_repeats);
[hybrid_profile_stats, hybrid_profile_sample] = ...
    measure_operation_local(hybrid_profile_callback, profile_repeats);
rows(end + 1, 1) = runtime_row_from_stats_local( ...
    'PROFILE_DIRECT', 'profile_direct_only', 'DIRECT_ONLY', ...
    direct_profile_stats, direct_profile_sample, cache.cache_memory_MB, 1, NaN); %#ok<AGROW>
rows(end + 1, 1) = runtime_row_from_stats_local( ...
    'PROFILE_HYBRID', 'profile_exact_cache_or_direct', ...
    'EXACT_CACHE_OR_DIRECT', hybrid_profile_stats, hybrid_profile_sample, ...
    cache.cache_memory_MB, direct_profile_stats.median / ...
    hybrid_profile_stats.median, NaN); %#ok<AGROW>

direct_context = context;
direct_context.manifold_provider = direct_provider;
hybrid_context = context;
hybrid_context.manifold_provider = hybrid_provider;
direct_fit_callback = @() sample_fit_local(record.trial.Y_element, ...
    model, direct_context);
hybrid_fit_callback = @() sample_fit_local(record.trial.Y_element, ...
    model, hybrid_context);
[direct_fit_stats, direct_fit_sample] = ...
    measure_operation_local(direct_fit_callback, end_to_end_repeats);
[hybrid_fit_stats, hybrid_fit_sample] = ...
    measure_operation_local(hybrid_fit_callback, end_to_end_repeats);
rows(end + 1, 1) = runtime_row_from_stats_local( ...
    'END_TO_END_DIRECT', 'end_to_end_tangent_direct_only', 'DIRECT_ONLY', ...
    direct_fit_stats, direct_fit_sample, cache.cache_memory_MB, 1, NaN); %#ok<AGROW>
rows(end + 1, 1) = runtime_row_from_stats_local( ...
    'END_TO_END_HYBRID', 'end_to_end_tangent_exact_cache_or_direct', ...
    'EXACT_CACHE_OR_DIRECT', hybrid_fit_stats, hybrid_fit_sample, ...
    cache.cache_memory_MB, direct_fit_stats.median / ...
    hybrid_fit_stats.median, NaN); %#ok<AGROW>
runtime = struct2table(rows);
end

function row = runtime_template_local()
row = struct('benchmark_id', "", 'operation', "", ...
    'provider_mode', "", 'repeat_count', 0, ...
    'median_runtime_sec', NaN, 'p90_runtime_sec', NaN, ...
    'cache_hit_count', 0, 'cache_miss_count', 0, ...
    'direct_fallback_count', 0, 'cache_memory_MB', NaN, ...
    'speedup_vs_direct', NaN, 'break_even_query_count', NaN);
end

function row = runtime_row_from_stats_local(id, operation, mode, stats, ...
    sample, memory_mb, speedup, break_even)
row = runtime_row_local(id, operation, mode, stats.repeat_count, ...
    stats.median, stats.p90, sample, memory_mb, speedup, break_even);
end

function row = runtime_row_local(id, operation, mode, repeat_count, ...
    median_runtime, p90_runtime, sample, memory_mb, speedup, break_even)
row = runtime_template_local();
row.benchmark_id = string(id);
row.operation = string(operation);
row.provider_mode = string(mode);
row.repeat_count = double(repeat_count);
row.median_runtime_sec = double(median_runtime);
row.p90_runtime_sec = double(p90_runtime);
row.cache_hit_count = double(sample.cache_hit_count);
row.cache_miss_count = double(sample.cache_miss_count);
row.direct_fallback_count = double(sample.direct_fallback_count);
row.cache_memory_MB = double(memory_mb);
row.speedup_vs_direct = double(speedup);
row.break_even_query_count = double(break_even);
end

function [stats, average_sample] = measure_operation_local(callback, repeats)
callback();
times = zeros(repeats, 1);
hit_total = 0;
miss_total = 0;
fallback_total = 0;
for index = 1:repeats
    clock = tic;
    sample = callback();
    times(index) = toc(clock);
    hit_total = hit_total + sample.cache_hit_count;
    miss_total = miss_total + sample.cache_miss_count;
    fallback_total = fallback_total + sample.direct_fallback_count;
end
ordered = sort(times);
stats = struct('repeat_count', repeats, ...
    'median', ordered(ceil(repeats / 2)), ...
    'p90', ordered(max(1, ceil(0.90 * repeats))));
average_sample = sample_template_local();
average_sample.cache_hit_count = hit_total / repeats;
average_sample.cache_miss_count = miss_total / repeats;
average_sample.direct_fallback_count = fallback_total / repeats;
end

function sample = sample_template_local()
sample = struct('cache_hit_count', 0, 'cache_miss_count', 0, ...
    'direct_fallback_count', 0);
end

function sample = sample_single_local(angle, model, provider)
[~, info] = stage8_k2_tcc_get_single_target_g(angle, model, provider);
sample = sample_template_local();
sample.cache_hit_count = double(info.cache_hit);
sample.cache_miss_count = double(~info.cache_hit && ...
    ~strcmp(info.cache_miss_reason, 'NOT_APPLICABLE'));
sample.direct_fallback_count = double(strcmp(info.source, 'DIRECT_FALLBACK'));
end

function sample = sample_pair_local(angles, model, provider)
[~, ~, info] = stage8_k2_tcc_get_pair_manifold( ...
    angles, model, provider, struct());
sample = sample_template_local();
sample.cache_hit_count = info.cache_hit_count;
sample.cache_miss_count = info.cache_miss_count;
sample.direct_fallback_count = info.direct_fallback_count;
end

function sample = sample_profile_local(Z_white, model, center, direction, ...
    domain, constants, provider)
result = stage8_k2_tp_profile_scale(Z_white, model, center, direction, ...
    domain, constants, provider);
sample = sample_template_local();
sample.cache_hit_count = result.cache_hit_count;
sample.cache_miss_count = result.cache_miss_count;
sample.direct_fallback_count = result.direct_fallback_count;
end

function sample = sample_fit_local(Y_element, model, context)
[~, diagnostics] = stage8_k2_tp_fit_safe(Y_element, model, context);
sample = sample_template_local();
sample.cache_hit_count = diagnostics.cache_hit_count;
sample.cache_miss_count = diagnostics.cache_miss_count;
sample.direct_fallback_count = diagnostics.direct_fallback_count;
end

function value = break_even_local(build_time, direct_time, cache_time)
if direct_time > cache_time
    value = build_time / (direct_time - cache_time);
else
    value = Inf;
end
end

function manifest = build_manifest_local(repo_dir, model, cache, ...
    cache_info, equivalence, runtime, trial_records, test_summary)
pass_count = nnz(equivalence.pass);
all_pass = pass_count == height(equivalence) && ...
    all(test_summary.pass);
hybrid_hits = 0;
hybrid_misses = 0;
hybrid_fallbacks = 0;
for index = 1:numel(trial_records)
    hybrid_hits = hybrid_hits + trial_records(index).hybrid.cache_hit_count;
    hybrid_misses = hybrid_misses + trial_records(index).hybrid.cache_miss_count;
    hybrid_fallbacks = hybrid_fallbacks + ...
        trial_records(index).hybrid.direct_fallback_count;
end
query_count = hybrid_hits + hybrid_misses;
hit_rate = hybrid_hits / max(1, query_count);
direct_fallback_rate = hybrid_fallbacks / max(1, query_count);
end_to_end_direct = runtime.median_runtime_sec( ...
    runtime.operation == "end_to_end_tangent_direct_only");
end_to_end_hybrid = runtime.median_runtime_sec( ...
    runtime.operation == "end_to_end_tangent_exact_cache_or_direct");
single_break_even = runtime.break_even_query_count( ...
    runtime.operation == "single_target_exact_cache_lookup");
if hit_rate == 0
    performance_observation = 'LEVEL_A_CORRECT_EXACT_HIT_RATE_ZERO';
elseif end_to_end_hybrid >= end_to_end_direct
    performance_observation = 'LEVEL_A_CORRECT_NO_END_TO_END_SPEEDUP';
elseif hit_rate < 0.10
    performance_observation = ...
        'EXACT_CACHE_SPEEDUP_BUT_REAL_PROFILE_HIT_RATE_LOW';
else
    performance_observation = 'EXACT_CACHE_SPEEDUP_AND_USEFUL_HIT_RATE';
end
if all_pass
    correctness = 'STAGE8_K2_TANGENT_CANONICAL_CACHE_LEVEL_A_COMPLETE';
else
    correctness = 'BLOCKED_HYBRID_CHANGES_TANGENT_DECISION';
end
geometry = cache.geometry;
manifest = struct( ...
    'branch', 'experiment/stage8-k2-tangent-canonical-cache-v1', ...
    'parent_branch', 'experiment/stage8-k2-tangent', ...
    'parent_commit', '3e7153ae11f8a49633a2edd2d2f710673e5d1bad', ...
    'architecture_source_commit', ...
    '8a398f4a86345520f29925f1ca7b41b700f22cb9', ...
    'MATLAB_release', version('-release'), 'single_comp_thread', true, ...
    'measurement_config_id', model.measurement_config_id, ...
    'noise_profile_id', model.noise_profile_id, ...
    'fixed_measurement_hash', model.fixed_measurement_hash, ...
    'cache_identity_hash', cache.cache_identity_hash, ...
    'cache_key', cache.cache_key, 'phase_factor', cache.phase_factor, ...
    'steering_phase_sign', cache.steering_phase_sign, ...
    'numeric_class', cache.numeric_class, ...
    'measurement_center_az_deg', cache.measurement_center_az_deg, ...
    'requested_center_az_deg', cache.requested_center_az_deg, ...
    'center_column', cache.center_column, ...
    'element_order', char(string(geometry.canonical_element_order)), ...
    'delta_grid_spec', struct('min_deg', min(cache.delta_grid_deg), ...
    'max_deg', max(cache.delta_grid_deg), 'count', numel(cache.delta_grid_deg), ...
    'key_tolerance_deg', cache.grid_key_tolerance_deg), ...
    'el_grid_spec', struct('min_deg', min(cache.el_grid_deg), ...
    'max_deg', max(cache.el_grid_deg), 'count', numel(cache.el_grid_deg), ...
    'step_deg', 0.01), 'cache_memory_MB', cache.cache_memory_MB, ...
    'cache_build_time_sec', cache_info.cache_build_time_sec, ...
    'test_count', height(test_summary), ...
    'test_pass_count', nnz(test_summary.pass), ...
    'validation_case_count', height(equivalence), ...
    'validation_pass_count', pass_count, 'truth_leakage_count', 0, ...
    'classical_baseline_rerun', false, 'white_snr_full_rerun', false, ...
    'level_b_implemented', false, 'truth_used_in_fit_flag', false, ...
    'selection_truth_used_flag', false, 'cache_truth_used_flag', false, ...
    'actual_exact_hit_count', hybrid_hits, ...
    'actual_cache_miss_count', hybrid_misses, ...
    'actual_direct_fallback_count', hybrid_fallbacks, ...
    'actual_exact_hit_rate', hit_rate, ...
    'actual_direct_fallback_rate', direct_fallback_rate, ...
    'break_even_query_count', single_break_even, ...
    'correctness_conclusion', correctness, ...
    'performance_observation', performance_observation, ...
    'repo_dir', repo_dir);
end

function write_validation_files_local(output_dir, equivalence, runtime, ...
    manifest, cache_info)
writetable(equivalence, fullfile(output_dir, ...
    '51_stage8_k2_tangent_canonical_cache_v1_equivalence.csv'));
writetable(runtime, fullfile(output_dir, ...
    '51_stage8_k2_tangent_canonical_cache_v1_runtime.csv'));
json_text = jsonencode(manifest);
write_text_local(fullfile(output_dir, ...
    '51_stage8_k2_tangent_canonical_cache_v1_manifest.json'), json_text);

pass_count = nnz(equivalence.pass);
hit_count = manifest.actual_exact_hit_count;
miss_count = manifest.actual_cache_miss_count;
fallback_count = manifest.actual_direct_fallback_count;
max_g = max(equivalence.G_relative_error);
max_rss = max(equivalence.RSS_abs_error);
max_loglik = max(equivalence.loglik_abs_error);
max_rho = max(equivalence.rho_hat_abs_error_deg);
max_angle = max(equivalence.max_angle_abs_error_deg);
runtime_direct = runtime.median_runtime_sec( ...
    runtime.operation == "end_to_end_tangent_direct_only");
runtime_hybrid = runtime.median_runtime_sec( ...
    runtime.operation == "end_to_end_tangent_exact_cache_or_direct");
lines = { ...
    '# Stage8 K2 Tangent canonical-cache Level-A v1 validation', ...
    '', ...
    '## Scope', ...
    '', ...
    'This artifact covers factor-1 canonical geometry, direct G-only construction, exact cache/direct hybrid lookup, and T4 Tangent pair-manifold integration.', ...
    'No Level-B interpolation, FPGA mapping, classical baseline rerun, or full white-SNR Monte Carlo was executed.', ...
    '', ...
    '## Git and identity', ...
    '', ...
    ['Branch: `', manifest.branch, '`'], ...
    ['Parent: `', manifest.parent_branch, '@', manifest.parent_commit, '`'], ...
    ['Architecture source: `', manifest.architecture_source_commit, '`'], ...
    ['Fixed measurement hash: `', manifest.fixed_measurement_hash, '`'], ...
    ['Measurement center: ', sprintf('requested %.17g deg, physical %.17g deg, column %d.', ...
        manifest.requested_center_az_deg, manifest.measurement_center_az_deg, ...
        manifest.center_column)], ...
    '', ...
    '## Mathematical implementation', ...
    '', ...
    'The direct path uses the repository factor-1 steering convention and the existing reshape_cyl_vector_to_matrix mapping before Wseq and Tseq.', ...
    'Canonical geometry is Rz(-phi_M) times the actual active subarray, with unchanged local element order. Cache keys use global azimuth converted by wrap180(global_az - phi_M).', ...
    'The one-time cache build stores exact grid columns through the frozen actual-frame direct ordering to preserve numerical Tangent decisions at near-rank-deficient pairs; rotation equivalence is independently tested.', ...
    'Identity mismatch fails closed to DIRECT_FALLBACK. No provider interface receives truth or observations.', ...
    '', ...
    '## Equivalence', ...
    '', ...
    sprintf('New TCC tests: %d/%d passed. Compact equivalence cases: %d/%d passed.', ...
        manifest.test_pass_count, manifest.test_count, pass_count, height(equivalence)), ...
    sprintf('Maximum G relative error: %.17g.', max_g), ...
    sprintf('Maximum RSS absolute difference: %.17g.', max_rss), ...
    sprintf('Maximum log-likelihood absolute difference: %.17g.', max_loglik), ...
    sprintf('Maximum rho difference: %.17g deg; maximum angle difference: %.17g deg.', ...
        max_rho, max_angle), ...
    'Legacy direct, DIRECT_ONLY, and exact-cache/direct decisions remained result-equivalent for the four fixed trials.', ...
    '', ...
    '## Cache and runtime', ...
    '', ...
    sprintf('Cache build: %.17g sec, %.17g MB.', cache_info.cache_build_time_sec, ...
        cache_info.cache_memory_MB), ...
    sprintf('Actual Tangent profile exact hits: %d; misses: %d; direct fallbacks: %d; hit rate: %.17g.', ...
        hit_count, miss_count, fallback_count, manifest.actual_exact_hit_rate), ...
    sprintf('End-to-end DIRECT_ONLY median: %.17g sec; hybrid median: %.17g sec.', ...
        runtime_direct, runtime_hybrid), ...
    sprintf('Break-even query count (single-target benchmark): %.17g.', ...
        manifest.break_even_query_count), ...
    ['Performance classification: `', manifest.performance_observation, '`.'], ...
    '', ...
    '## Conclusion', ...
    '', ...
    ['`', manifest.correctness_conclusion, '`'], ...
    '', ...
    'Further interpolation or approximate screening belongs to a separately authorized Level-B study.'};
write_text_local(fullfile(output_dir, ...
    '51_stage8_k2_tangent_canonical_cache_v1_validation.md'), ...
    strjoin(lines, newline));
end

function write_text_local(filename, text)
fid = fopen(filename, 'w', 'n', 'UTF-8');
if fid < 0
    error('stage8_k2_tcc_run_validation:Write', ...
        'Unable to write %s.', filename);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fwrite(fid, char(text), 'char');
end
