function output = stage8_k2_tcc_run_runtime_audit( ...
    context, registry, protocol, runtime_dir, options)
%STAGE8_K2_TCC_RUN_RUNTIME_AUDIT Run/resume paired OFF/STAGE timing.

if nargin < 5 || isempty(options), options = struct(); end
options = normalize_options_local(options, height(registry));
checkpoint_root = fullfile(runtime_dir, 'checkpoints', 'pass_c');
if ~isfolder(checkpoint_root), mkdir(checkpoint_root); end
if strcmp(options.mode, 'AGGREGATE')
    output = aggregate_local(registry, protocol, checkpoint_root, runtime_dir);
    return;
end

runtime_session_id = char(java.util.UUID.randomUUID());
pair_order = pair_order_local(height(registry), protocol);
trial_orders = trial_orders_local(height(registry), protocol);
trials = cell(height(options.trial_indices), 1);
for local_index = 1:numel(options.trial_indices)
    trial_index = options.trial_indices(local_index);
    trials{local_index} = stage8_k2_tcc_generate_frozen_trial( ...
        registry(trial_index, :), context);
end

for local_index = 1:numel(options.trial_indices)
    trial_index = options.trial_indices(local_index);
    if trial_has_incomplete_pair_local(registry(trial_index, :), ...
            trial_index, protocol, pair_order, checkpoint_root)
        warmup_trial_local(trials{local_index}, context, protocol);
    end
end

completed = 0;
for repeat_index = 1:protocol.repeat_target
    order = trial_orders(repeat_index, :);
    order = order(ismember(order, options.trial_indices));
    for order_index = 1:numel(order)
        trial_index = order(order_index);
        local_index = find(options.trial_indices == trial_index, 1);
        spec = registry(trial_index, :);
        trial = trials{local_index};
        order_code = pair_order(trial_index, repeat_index);
        [reusable, ~, ~] = read_pair_local(spec, trial.model, ...
            repeat_index, order_code, protocol, checkpoint_root);
        if reusable
            completed = completed + 1;
            fprintf('PASSC RESUME shard=%d r=%d trial=%s\n', ...
                options.shard_id, repeat_index, char(spec.trial_id));
            continue;
        end
        run_pair_local(spec, trial, context, repeat_index, order_code, ...
            runtime_session_id, protocol, checkpoint_root);
        completed = completed + 1;
        fprintf('PASSC RUN shard=%d %d/%d r=%d trial=%s order=%s\n', ...
            options.shard_id, completed, ...
            numel(options.trial_indices) * protocol.repeat_target, ...
            repeat_index, char(spec.trial_id), order_code);
    end
end
output = struct('mode', 'WORKER', 'shard_id', options.shard_id, ...
    'trial_indices', options.trial_indices, ...
    'completed_pair_count', completed, ...
    'runtime_session_id', runtime_session_id, ...
    'timing_configuration_hash', protocol.timing_configuration_hash);
atomic_value_save_local(fullfile(runtime_dir, sprintf( ...
    'pass_c_worker_%02d.mat', options.shard_id)), output);
if options.aggregate_after_worker
    output = aggregate_local(registry, protocol, checkpoint_root, runtime_dir);
end
end

function options = normalize_options_local(options, trial_count)
defaults = struct('mode', 'WORKER', 'trial_indices', 1:trial_count, ...
    'shard_id', 1, 'aggregate_after_worker', false);
names = fieldnames(defaults);
for index = 1:numel(names)
    if ~isfield(options, names{index})
        options.(names{index}) = defaults.(names{index});
    end
end
options.mode = upper(char(string(options.mode)));
options.trial_indices = double(options.trial_indices(:).');
if ~ismember(options.mode, {'WORKER','AGGREGATE'}) || ...
        any(options.trial_indices < 1 | options.trial_indices > trial_count) || ...
        numel(unique(options.trial_indices)) ~= numel(options.trial_indices)
    error('stage8_k2_tcc_run_runtime_audit:Options', ...
        'Runtime worker options are invalid.');
end
end

function orders = trial_orders_local(trial_count, protocol)
orders = zeros(protocol.repeat_target, trial_count);
rng_state = rng;
cleanup = onCleanup(@() rng(rng_state));
rng(protocol.trial_order_seed, 'twister');
for repeat_index = 1:protocol.repeat_target
    orders(repeat_index, :) = randperm(trial_count);
end
clear cleanup
end

function order = pair_order_local(trial_count, protocol)
rng_state = rng;
cleanup = onCleanup(@() rng(rng_state));
rng(protocol.pair_order_seed, 'twister');
trial_permutation = randperm(trial_count);
position = zeros(trial_count, 1);
position(trial_permutation) = 1:trial_count;
order = strings(trial_count, protocol.repeat_target);
for trial_index = 1:trial_count
    for repeat_index = 1:protocol.repeat_target
        if mod(position(trial_index) + repeat_index, 2) == 0
            order(trial_index, repeat_index) = "AB";
        else
            order(trial_index, repeat_index) = "BA";
        end
    end
end
clear cleanup
end

function warmup_trial_local(trial, context, protocol)
modes = {'OFF','TIMING_STAGE'};
for mode_index = 1:numel(modes)
    for warmup_index = 1:protocol.warmup_count
        stage8_k2_tcc_audit_state('CONFIGURE', ...
            struct('mode', modes{mode_index}));
        stage8_k2_tp_fit_safe(trial.Y_element, trial.model, context);
    end
end
end

function incomplete = trial_has_incomplete_pair_local(spec, trial_index, ...
    protocol, pair_order, checkpoint_root)
incomplete = false;
for repeat_index = 1:protocol.repeat_target
    dummy_model = struct('fixed_measurement_hash', 'NOT_CHECKED');
    [reusable, ~, ~] = read_pair_local(spec, dummy_model, repeat_index, ...
        pair_order(trial_index, repeat_index), protocol, checkpoint_root, ...
        true);
    if ~reusable
        incomplete = true;
        return;
    end
end
end

function run_pair_local(spec, trial, context, repeat_index, order_code, ...
    session_id, protocol, checkpoint_root)
pair_block_id = sprintf('%s_R%02d', char(spec.trial_id), repeat_index);
if order_code == "AB"
    modes = {'OFF','TIMING_STAGE'};
else
    modes = {'TIMING_STAGE','OFF'};
end
units = cell(2, 1);
for mode_index = 1:2
    mode = modes{mode_index};
    record = run_mode_local(mode, trial, context);
    metadata = unit_metadata_local(protocol, spec, trial.model, ...
        repeat_index, mode, pair_block_id, order_code, session_id);
    unit = struct('metadata', metadata, 'record', record, ...
        'unit_complete', true, 'paired_block_complete', false, ...
        'paired_block_contiguous', false, ...
        'pair_sequence_index', mode_index);
    atomic_checkpoint_local(unit_path_local(checkpoint_root, spec, ...
        repeat_index, mode), unit);
    units{mode_index} = unit;
end
if ~strcmp(units{1}.record.estimator_signature_hash, ...
        units{2}.record.estimator_signature_hash)
    error('stage8_k2_tcc_run_runtime_audit:EstimatorChanged', ...
        'OFF/STAGE changed an estimator output for %s repeat %d.', ...
        char(spec.trial_id), repeat_index);
end
for mode_index = 1:2
    units{mode_index}.paired_block_complete = true;
    units{mode_index}.paired_block_contiguous = true;
end
% Write the second unit first.  A crash before replacing the first leaves
% the pair incomplete, so resume reruns the entire contiguous block.
atomic_checkpoint_local(unit_path_local(checkpoint_root, spec, ...
    repeat_index, modes{2}), units{2});
atomic_checkpoint_local(unit_path_local(checkpoint_root, spec, ...
    repeat_index, modes{1}), units{1});
end

function record = run_mode_local(mode, trial, context)
stage8_k2_tcc_audit_state('CONFIGURE', struct('mode', mode));
root_clock = tic;
[result, diagnostics] = stage8_k2_tp_fit_safe( ...
    trial.Y_element, trial.model, context);
root_runtime = toc(root_clock);
if strcmp(mode, 'TIMING_STAGE')
    timing = stage8_k2_tcc_audit_state('GET_TIMING');
    [stage_rows, unattributed, reconciliation] = ...
        reconcile_stages_local(timing.stage_rows, root_runtime);
else
    stage_rows = struct([]);
    unattributed = NaN;
    reconciliation = NaN;
end
signature = estimator_signature_local(result, diagnostics, ...
    trial.element_trial_hash);
record = struct('timing_mode', string(mode), ...
    'root_runtime_sec', double(root_runtime), ...
    'stage_rows', stage_rows, ...
    'unattributed_sec', double(unattributed), ...
    'reconciliation_error_sec', double(reconciliation), ...
    'estimator_signature_hash', ...
    stage8_k2_tcc_stable_hash('PASS_C_ESTIMATOR_SIGNATURE', signature));
end

function signature = estimator_signature_local(result, diagnostics, hash)
signature = struct('element_trial_hash', hash, ...
    'angles_hat_deg', result.angles_hat_deg, ...
    'fit_valid', result.fit_valid, 'fit_status', result.fit_status, ...
    'selected_source', result.selected_source, ...
    'selected_start_id', result.selected_start_id, 'rss', result.rss, ...
    'loglik', result.loglik_concentrated, 'rank', result.effective_rank, ...
    'score_calls', result.score_call_count, ...
    'svd_calls', result.svd_call_count, ...
    'K1_center_deg', diagnostics.K1_center_deg, ...
    'direction_hat', diagnostics.direction_hat, ...
    'metric_rank', diagnostics.metric_rank, ...
    'metric_condition', diagnostics.metric_condition, ...
    'rho_hat_deg', diagnostics.rho_hat_deg, ...
    'raw_valid', diagnostics.raw_tangent_candidate_valid, ...
    'raw_loglik', diagnostics.raw_tangent_loglik, ...
    'upgrade', diagnostics.upgrade_flag, ...
    'fallback', diagnostics.fallback_flag, ...
    'fallback_reason', diagnostics.fallback_reason);
end

function [rows, unattributed, reconciliation] = ...
    reconcile_stages_local(raw_rows, root_runtime)
ids = string({raw_rows.stage_id});
values = [raw_rows.inclusive_runtime_sec];
time = containers.Map('KeyType', 'char', 'ValueType', 'double');
for index = 1:numel(ids)
    time(char(ids(index))) = double(values(index));
end
time('ROOT_TANGENT_PROFILE_SAFE') = root_runtime;
edges = hierarchy_edges_local();
all_ids = unique([string(keys(time)), edges(:, 1).', edges(:, 2).'], 'stable');
inclusive = zeros(numel(all_ids), 1);
exclusive = zeros(numel(all_ids), 1);
for index = 1:numel(all_ids)
    id = char(all_ids(index));
    if isKey(time, id), inclusive(index) = time(id); end
    children = edges(edges(:, 1) == all_ids(index), 2);
    child_sum = 0;
    for child_index = 1:numel(children)
        child = char(children(child_index));
        if isKey(time, child), child_sum = child_sum + time(child); end
    end
    exclusive(index) = inclusive(index) - child_sum;
end
root_index = find(all_ids == "ROOT_TANGENT_PROFILE_SAFE", 1);
unattributed = exclusive(root_index);
keep = (1:numel(all_ids)).' ~= root_index & ...
    (inclusive ~= 0 | exclusive ~= 0);
rows = repmat(struct('stage_id', "", 'inclusive_runtime_sec', 0, ...
    'exclusive_runtime_sec', 0, 'stage_share', 0), nnz(keep) + 1, 1);
indices = find(keep);
for row_index = 1:numel(indices)
    index = indices(row_index);
    rows(row_index) = struct('stage_id', all_ids(index), ...
        'inclusive_runtime_sec', inclusive(index), ...
        'exclusive_runtime_sec', exclusive(index), ...
        'stage_share', inclusive(index) / root_runtime);
end
rows(end) = struct('stage_id', "UNATTRIBUTED", ...
    'inclusive_runtime_sec', unattributed, ...
    'exclusive_runtime_sec', unattributed, ...
    'stage_share', unattributed / root_runtime);
reconciliation = root_runtime - ...
    (sum(exclusive(keep)) + unattributed);
end

function edges = hierarchy_edges_local()
edges = [ ...
    "ROOT_TANGENT_PROFILE_SAFE","K1_PUBLIC"; ...
    "ROOT_TANGENT_PROFILE_SAFE","K2_PUBLIC"; ...
    "ROOT_TANGENT_PROFILE_SAFE","TAIL_FULL_DATA"; ...
    "ROOT_TANGENT_PROFILE_SAFE","CENTER_MANIFOLD_DERIVATIVES"; ...
    "ROOT_TANGENT_PROFILE_SAFE","PROJECTED_DIRECTION"; ...
    "ROOT_TANGENT_PROFILE_SAFE","T4_PROFILE"; ...
    "ROOT_TANGENT_PROFILE_SAFE","FINAL_SAFE_SELECTOR"; ...
    "K1_PUBLIC","K1_CONTEXT"; "K1_PUBLIC","K1_CORE_LITE"; ...
    "K1_CONTEXT","K1_FULL_DATA"; ...
    "K1_CONTEXT","K1_INITIALIZATION_TOTAL"; ...
    "K1_INITIALIZATION_TOTAL","K1_INIT_CONVENTIONAL"; ...
    "K1_INITIALIZATION_TOTAL","K1_INIT_GROUP_PREPARE"; ...
    "K1_INITIALIZATION_TOTAL","K1_INIT_GROUP_Q1"; ...
    "K1_INITIALIZATION_TOTAL","K1_INIT_GROUP_Q2"; ...
    "K1_CORE_LITE","K1_FIXED_FIT"; ...
    "K1_CORE_LITE","K1_CONTINUOUS"; ...
    "K1_CORE_LITE","K1_SELECTION"; ...
    "K1_FIXED_FIT","K1_FIXED_START_BUILD"; ...
    "K1_FIXED_FIT","K1_FIXED_REGISTERED_REFINEMENT"; ...
    "K1_FIXED_FIT","K1_FIXED_FINAL_CERTIFICATION"; ...
    "K1_FIXED_FIT","K1_FIXED_REGISTERED_SELECTION"; ...
    "K2_PUBLIC","K2_CONTEXT"; "K2_PUBLIC","K2_CORE_LITE"; ...
    "K2_CONTEXT","K2_FULL_DATA"; ...
    "K2_CONTEXT","K2_INITIALIZATION_TOTAL"; ...
    "K2_INITIALIZATION_TOTAL","K2_INIT_CONVENTIONAL"; ...
    "K2_INITIALIZATION_TOTAL","K2_INIT_GROUP_PREPARE"; ...
    "K2_INITIALIZATION_TOTAL","K2_INIT_GROUP_Q1"; ...
    "K2_INITIALIZATION_TOTAL","K2_INIT_GROUP_Q2"; ...
    "K2_CORE_LITE","K2_HELPER_K1"; ...
    "K2_CORE_LITE","K2_START_BUILD"; ...
    "K2_CORE_LITE","K2_REGISTERED_REFINEMENT"; ...
    "K2_CORE_LITE","K2_FINAL_CERTIFICATION"; ...
    "K2_CORE_LITE","K2_SELECTION"; ...
    "K2_START_BUILD","K2_NESTED_ANCHOR"];
end

function [reusable, off_unit, stage_unit] = read_pair_local(spec, model, ...
    repeat_index, order_code, protocol, checkpoint_root, ignore_identity)
if nargin < 8, ignore_identity = false; end
off_unit = read_unit_local(unit_path_local( ...
    checkpoint_root, spec, repeat_index, 'OFF'));
stage_unit = read_unit_local(unit_path_local( ...
    checkpoint_root, spec, repeat_index, 'TIMING_STAGE'));
reusable = validate_unit_local(off_unit, spec, model, repeat_index, ...
    'OFF', order_code, protocol, ignore_identity) && ...
    validate_unit_local(stage_unit, spec, model, repeat_index, ...
    'TIMING_STAGE', order_code, protocol, ignore_identity);
if reusable
    reusable = off_unit.paired_block_complete && ...
        stage_unit.paired_block_complete && ...
        off_unit.paired_block_contiguous && ...
        stage_unit.paired_block_contiguous && ...
        strcmp(off_unit.metadata.runtime_session_id, ...
        stage_unit.metadata.runtime_session_id) && ...
        strcmp(off_unit.metadata.pair_block_id, ...
        stage_unit.metadata.pair_block_id) && ...
        strcmp(off_unit.record.estimator_signature_hash, ...
        stage_unit.record.estimator_signature_hash);
end
end

function unit = read_unit_local(path_now)
unit = struct();
if ~isfile(path_now), return; end
loaded = load(path_now, 'unit');
if isfield(loaded, 'unit'), unit = loaded.unit; end
end

function pass = validate_unit_local(unit, spec, model, repeat_index, mode, ...
    order_code, protocol, ignore_identity)
pass = isstruct(unit) && isscalar(unit) && ...
    all(isfield(unit, {'metadata','record','unit_complete', ...
    'paired_block_complete','paired_block_contiguous'})) && ...
    logical(unit.unit_complete);
if ~pass, return; end
m = unit.metadata;
pass = strcmp(m.pass, 'PASS_C_RUNTIME') && ...
    strcmp(m.trial_id, char(spec.trial_id)) && ...
    isequal(m.repeat_index, repeat_index) && strcmp(m.timing_mode, mode) && ...
    strcmp(m.pair_order, char(order_code)) && ...
    strcmp(m.level_a_closure_commit, protocol.level_a_closure_commit) && ...
    strcmp(m.audit_start_commit, protocol.audit_start_commit) && ...
    strcmp(m.audit_code_hash, protocol.audit_code_hash) && ...
    strcmp(m.registry_hash, protocol.registry_hash) && ...
    strcmp(m.MATLAB_release, version('-release')) && ...
    logical(m.singleCompThread) && ...
    strcmp(m.timing_configuration_hash, ...
    protocol.timing_configuration_hash);
if pass && ~ignore_identity
    pass = strcmp(m.measurement_identity, model.fixed_measurement_hash);
end
end

function metadata = unit_metadata_local(protocol, spec, model, repeat_index, ...
    mode, pair_block_id, order_code, session_id)
metadata = struct('pass', 'PASS_C_RUNTIME', ...
    'measurement_identity', model.fixed_measurement_hash, ...
    'trial_id', char(spec.trial_id), 'repeat_index', repeat_index, ...
    'timing_mode', mode, 'level_a_closure_commit', ...
    protocol.level_a_closure_commit, 'audit_start_commit', ...
    protocol.audit_start_commit, 'audit_code_hash', ...
    protocol.audit_code_hash, 'registry_hash', protocol.registry_hash, ...
    'MATLAB_release', version('-release'), 'singleCompThread', true, ...
    'timing_configuration_hash', protocol.timing_configuration_hash, ...
    'pair_block_id', pair_block_id, 'pair_order', char(order_code), ...
    'runtime_session_id', session_id);
end

function path_now = unit_path_local(root, spec, repeat_index, mode)
folder = fullfile(root, char(spec.trial_id));
if ~isfolder(folder), mkdir(folder); end
path_now = fullfile(folder, sprintf('R%02d_%s.mat', ...
    repeat_index, upper(mode)));
end

function output = aggregate_local(registry, protocol, checkpoint_root, runtime_dir)
pair_order = pair_order_local(height(registry), protocol);
mode_rows = cell(height(registry) * protocol.repeat_target * 2, 1);
stage_tables = cell(height(registry) * protocol.repeat_target, 1);
pair_rows = cell(height(registry) * protocol.repeat_target, 1);
mode_index = 0;
pair_index = 0;
for trial_index = 1:height(registry)
    spec = registry(trial_index, :);
    for repeat_index = 1:protocol.repeat_target
        [reusable, off_unit, stage_unit] = read_pair_local( ...
            spec, struct('fixed_measurement_hash', ...
            off_identity_local(checkpoint_root, spec, repeat_index)), ...
            repeat_index, pair_order(trial_index, repeat_index), ...
            protocol, checkpoint_root);
        if ~reusable
            error('stage8_k2_tcc_run_runtime_audit:Incomplete', ...
                'Pass C pair is incomplete: %s repeat %d.', ...
                char(spec.trial_id), repeat_index);
        end
        units = {off_unit,stage_unit};
        for current = 1:2
            mode_index = mode_index + 1;
            unit = units{current};
            mode_rows{mode_index} = mode_row_local(spec, unit);
        end
        pair_index = pair_index + 1;
        stage_tables{pair_index} = stage_table_local(spec, stage_unit);
        pair_rows{pair_index} = pair_row_local(spec, off_unit, stage_unit);
    end
end
raw_timing = struct2table(vertcat(mode_rows{:}));
stage_samples = vertcat(stage_tables{:});
paired_deltas = struct2table(vertcat(pair_rows{:}));
runtime_summary = summarize_runtime_local( ...
    raw_timing, stage_samples, paired_deltas, registry, protocol);
output = struct('raw_timing', raw_timing, ...
    'stage_samples', stage_samples, 'paired_deltas', paired_deltas, ...
    'runtime_summary', runtime_summary, ...
    'paired_block_count', height(paired_deltas), ...
    'all_pairs_complete', height(paired_deltas) == ...
    height(registry) * protocol.repeat_target);
atomic_value_save_local(fullfile(runtime_dir, 'pass_c_runtime_audit.mat'), ...
    output);
end

function identity = off_identity_local(root, spec, repeat_index)
unit = read_unit_local(unit_path_local(root, spec, repeat_index, 'OFF'));
if isempty(fieldnames(unit))
    identity = '';
else
    identity = unit.metadata.measurement_identity;
end
end

function row = mode_row_local(spec, unit)
row = struct('trial_id', string(spec.trial_id), ...
    'fixed_measurement_hash', string(unit.metadata.measurement_identity), ...
    'noise_profile_id', string(spec.noise_profile_id), ...
    'L', double(spec.L), 'snr_db', double(spec.snr_db), ...
    'profile_id', string(spec.profile_id), ...
    'repeat_index', double(unit.metadata.repeat_index), ...
    'pair_block_id', string(unit.metadata.pair_block_id), ...
    'runtime_session_id', string(unit.metadata.runtime_session_id), ...
    'pair_order', string(unit.metadata.pair_order), ...
    'timing_mode', string(unit.metadata.timing_mode), ...
    'root_runtime_sec', double(unit.record.root_runtime_sec), ...
    'stage_runtime_sec_or_NaN', ...
    ternary_local(strcmp(unit.metadata.timing_mode, 'TIMING_STAGE'), ...
    unit.record.root_runtime_sec, NaN), ...
    'unit_complete', logical(unit.unit_complete), ...
    'paired_block_complete', logical(unit.paired_block_complete), ...
    'paired_block_contiguous', logical(unit.paired_block_contiguous));
end

function rows = stage_table_local(spec, unit)
rows = struct2table(unit.record.stage_rows);
n = height(rows);
rows = addvars(rows, repmat(string(spec.trial_id), n, 1), ...
    repmat(string(unit.metadata.measurement_identity), n, 1), ...
    repmat(string(spec.noise_profile_id), n, 1), ...
    repmat(double(spec.L), n, 1), repmat(double(spec.snr_db), n, 1), ...
    repmat(string(spec.profile_id), n, 1), ...
    repmat(double(unit.metadata.repeat_index), n, 1), ...
    repmat(string(unit.metadata.pair_order), n, 1), ...
    'Before', 1, 'NewVariableNames', {'trial_id', ...
    'fixed_measurement_hash','noise_profile_id','L','snr_db', ...
    'profile_id','repeat_index','pair_order'});
rows.root_runtime_sec = repmat(unit.record.root_runtime_sec, n, 1);
rows.unattributed_sec = repmat(unit.record.unattributed_sec, n, 1);
rows.reconciliation_error_sec = repmat( ...
    unit.record.reconciliation_error_sec, n, 1);
end

function row = pair_row_local(spec, off_unit, stage_unit)
row = struct('trial_id', string(spec.trial_id), ...
    'fixed_measurement_hash', string(off_unit.metadata.measurement_identity), ...
    'noise_profile_id', string(spec.noise_profile_id), ...
    'L', double(spec.L), 'snr_db', double(spec.snr_db), ...
    'profile_id', string(spec.profile_id), ...
    'repeat_index', double(off_unit.metadata.repeat_index), ...
    'pair_order', string(off_unit.metadata.pair_order), ...
    'off_runtime_sec', double(off_unit.record.root_runtime_sec), ...
    'stage_runtime_sec', double(stage_unit.record.root_runtime_sec), ...
    'instrumentation_overhead_sec', double( ...
    stage_unit.record.root_runtime_sec - off_unit.record.root_runtime_sec));
end

function summary = summarize_runtime_local(raw, stages, pairs, registry, protocol)
rows = cell(height(registry), 1);
for trial_index = 1:height(registry)
    spec = registry(trial_index, :);
    trial_raw = raw(raw.trial_id == spec.trial_id, :);
    trial_stages = stages(stages.trial_id == spec.trial_id, :);
    trial_pairs = pairs(pairs.trial_id == spec.trial_id, :);
    stage_ids = unique(trial_stages.stage_id, 'stable');
    current = cell(numel(stage_ids) + 2, 1);
    index = 0;
    for mode = ["OFF","TIMING_STAGE"]
        index = index + 1;
        samples = trial_raw.root_runtime_sec(trial_raw.timing_mode == mode);
        current{index} = summary_row_local(spec, mode, ...
            "ROOT_TANGENT_PROFILE_SAFE", samples, ones(size(samples)), ...
            NaN(size(samples)), trial_stages, trial_pairs, protocol);
    end
    for stage_index = 1:numel(stage_ids)
        index = index + 1;
        stage_id = stage_ids(stage_index);
        subset = trial_stages(trial_stages.stage_id == stage_id, :);
        current{index} = summary_row_local(spec, "TIMING_STAGE", stage_id, ...
            subset.inclusive_runtime_sec, subset.stage_share, ...
            subset.exclusive_runtime_sec, subset, trial_pairs, protocol);
    end
    rows{trial_index} = struct2table(vertcat(current{:}));
end
trial_summary = vertcat(rows{:});
summary = [trial_summary;aggregate_trial_summaries_local(trial_summary)];
end

function row = summary_row_local(spec, mode, stage_id, samples, shares, ...
    exclusive, stage_rows, pairs, protocol)
repeat_count = numel(samples);
if repeat_count >= 10
    p90 = prctile(samples, 90);
    share_p90 = prctile(shares, 90);
    overhead_p90 = prctile(pairs.instrumentation_overhead_sec, 90);
else
    p90 = NaN; share_p90 = NaN; overhead_p90 = NaN;
end
row = struct('trial_id', string(spec.trial_id), ...
    'aggregation_level', "TRIAL", ...
    'scenario_aggregate', string(spec.trial_id), ...
    'fixed_measurement_hash', string(pairs.fixed_measurement_hash(1)), ...
    'noise_profile_id', string(spec.noise_profile_id), ...
    'L', double(spec.L), 'snr_db', double(spec.snr_db), ...
    'profile_id', string(spec.profile_id), ...
    'timing_mode', string(mode), 'stage_id', string(stage_id), ...
    'repeat_count', repeat_count, ...
    'median_runtime_sec', median(samples), ...
    'p90_runtime_sec', p90, 'min_runtime_sec', min(samples), ...
    'max_runtime_sec', max(samples), ...
    'median_stage_share', median(shares), ...
    'p90_stage_share', share_p90, 'min_stage_share', min(shares), ...
    'max_stage_share', max(shares), ...
    'median_exclusive_runtime_sec', median(exclusive, 'omitnan'), ...
    'median_unattributed_sec', median(stage_rows.unattributed_sec, 'omitnan'), ...
    'median_reconciliation_error_sec', ...
    median(stage_rows.reconciliation_error_sec, 'omitnan'), ...
    'pair_order_ab_count', nnz(pairs.pair_order == "AB"), ...
    'pair_order_ba_count', nnz(pairs.pair_order == "BA"), ...
    'paired_repeat_count', height(pairs), ...
    'paired_instrumentation_overhead_median_sec', ...
    median(pairs.instrumentation_overhead_sec), ...
    'paired_instrumentation_overhead_p90_sec', overhead_p90, ...
    'paired_instrumentation_overhead_min_sec', ...
    min(pairs.instrumentation_overhead_sec), ...
    'paired_instrumentation_overhead_max_sec', ...
    max(pairs.instrumentation_overhead_sec), ...
    'timing_configuration_hash', string(protocol.timing_configuration_hash));
end

function aggregate = aggregate_trial_summaries_local(summary)
definitions = cell(0, 2);
for value = unique(summary.noise_profile_id(summary.aggregation_level == ...
        "TRIAL"), 'stable').'
    definitions(end + 1, :) = {"NOISE_IDENTITY", value}; %#ok<AGROW>
end
for value = unique(summary.L(summary.aggregation_level == "TRIAL")).'
    definitions(end + 1, :) = {"L", value}; %#ok<AGROW>
end
for value = unique(summary.snr_db(summary.aggregation_level == "TRIAL")).'
    definitions(end + 1, :) = {"SNR", value}; %#ok<AGROW>
end
for value = unique(summary.profile_id(summary.aggregation_level == ...
        "TRIAL"), 'stable').'
    definitions(end + 1, :) = {"PROFILE", value}; %#ok<AGROW>
end
definitions(end + 1, :) = {"OVERALL", "ALL_72_TRIALS"};
keys = unique(summary(:, {'timing_mode','stage_id'}), 'rows', 'stable');
rows = cell(height(keys) * size(definitions, 1), 1);
row_index = 0;
for key_index = 1:height(keys)
    base = summary(summary.timing_mode == keys.timing_mode(key_index) & ...
        summary.stage_id == keys.stage_id(key_index) & ...
        summary.aggregation_level == "TRIAL", :);
    for definition_index = 1:size(definitions, 1)
        level = definitions{definition_index, 1};
        value = definitions{definition_index, 2};
        subset = aggregate_subset_local(base, level, value);
        if isempty(subset), continue; end
        row_index = row_index + 1;
        rows{row_index} = aggregate_row_local(subset, level, value);
    end
end
rows = rows(1:row_index);
if isempty(rows)
    aggregate = summary([],:);
else
    aggregate = struct2table(vertcat(rows{:}));
    aggregate = aggregate(:, summary.Properties.VariableNames);
end
end

function subset = aggregate_subset_local(base, level, value)
switch char(level)
    case 'NOISE_IDENTITY'
        subset = base(base.noise_profile_id == string(value), :);
    case 'L'
        subset = base(base.L == double(value), :);
    case 'SNR'
        subset = base(base.snr_db == double(value), :);
    case 'PROFILE'
        subset = base(base.profile_id == string(value), :);
    otherwise
        subset = base;
end
end

function row = aggregate_row_local(subset, level, value)
row = table2struct(subset(1, :));
token = sprintf('AGG_%s_%s', char(level), ...
    regexprep(char(string(value)), '[^A-Za-z0-9]+', '_'));
row.trial_id = string(token);
row.aggregation_level = string(level);
row.scenario_aggregate = string(value);
if numel(unique(subset.fixed_measurement_hash)) == 1
    row.fixed_measurement_hash = subset.fixed_measurement_hash(1);
else
    row.fixed_measurement_hash = "MULTIPLE_IDENTITIES";
end
if ~strcmp(level, 'NOISE_IDENTITY'), row.noise_profile_id = "ALL"; end
if ~strcmp(level, 'L'), row.L = NaN; end
if ~strcmp(level, 'SNR'), row.snr_db = NaN; end
if ~strcmp(level, 'PROFILE'), row.profile_id = "ALL"; end
row.repeat_count = height(subset);
row.median_runtime_sec = median(subset.median_runtime_sec);
row.p90_runtime_sec = prctile(subset.median_runtime_sec, 90);
row.min_runtime_sec = min(subset.median_runtime_sec);
row.max_runtime_sec = max(subset.median_runtime_sec);
row.median_stage_share = median(subset.median_stage_share);
row.p90_stage_share = prctile(subset.median_stage_share, 90);
row.min_stage_share = min(subset.median_stage_share);
row.max_stage_share = max(subset.median_stage_share);
row.median_exclusive_runtime_sec = ...
    median(subset.median_exclusive_runtime_sec, 'omitnan');
row.median_unattributed_sec = median(subset.median_unattributed_sec);
row.median_reconciliation_error_sec = ...
    median(subset.median_reconciliation_error_sec);
row.pair_order_ab_count = sum(subset.pair_order_ab_count);
row.pair_order_ba_count = sum(subset.pair_order_ba_count);
row.paired_repeat_count = sum(subset.paired_repeat_count);
overhead = subset.paired_instrumentation_overhead_median_sec;
row.paired_instrumentation_overhead_median_sec = median(overhead);
row.paired_instrumentation_overhead_p90_sec = prctile(overhead, 90);
row.paired_instrumentation_overhead_min_sec = min(overhead);
row.paired_instrumentation_overhead_max_sec = max(overhead);
end

function atomic_checkpoint_local(path_now, unit)
temporary = [path_now, '.tmp'];
save(temporary, 'unit', '-v7.3');
movefile(temporary, path_now, 'f');
end

function atomic_value_save_local(path_now, value)
temporary = [path_now, '.tmp'];
save(temporary, 'value', '-v7.3');
movefile(temporary, path_now, 'f');
end

function value = ternary_local(condition, yes_value, no_value)
if condition, value = yes_value; else, value = no_value; end
end
