function protocol = stage8_k2_tcc_audit_protocol(repo_dir, registry)
%STAGE8_K2_TCC_AUDIT_PROTOCOL Freeze hashes and all timed-run rules.

repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
protocol = struct();
protocol.protocol_id = ...
    'STAGE8_K2_TANGENT_PIPELINE_CACHE_PLACEMENT_AUDIT_V1';
protocol.level_a_closure_commit = ...
    'cf35e37a74366a8d9829de3a1f8b740a788bade1';
protocol.audit_start_commit = ...
    'aff3bb42df2b3d9b435cc57eacd3237826e7d87d';
protocol.repeat_target = 20;
protocol.warmup_count = 1;
protocol.warmup_rule = ...
    'ONE_UNTIMED_WARMUP_PER_TRIAL_PER_MODE_BEFORE_FORMAL_PAIRS';
protocol.trial_order_seed = 2026080801;
protocol.pair_order_seed = 2026080802;
protocol.ab_ba_balance_rule = ...
    'SEEDED_PARITY_BALANCE_PER_TRIAL_AND_REPEAT_WITH_ROUND_RANDOMIZATION';
protocol.timer_implementation = ...
    'MATLAB_TIC_TOC_EXTERNAL_ROOT_AND_ADDITIVE_INTERNAL_INCLUSIVE_TIMERS';
protocol.summary_quantile_convention = ...
    'MATLAB_PRCTILE_R2022B_LINEAR_INTERPOLATION';
protocol.conservative_lower_bound_formula = [ ...
    'CACHE_POINT_MINUS_MICROBENCHMARK_P10_P90_ENVELOPE_MINUS_', ...
    'POSITIVE_P90_PAIRED_INSTRUMENTATION_PERTURBATION_MINUS_', ...
    'IDENTITY_AND_QUERY_CLASS_SENSITIVITY_ENVELOPE'];
protocol.sensitivity_envelope_definition = [ ...
    'MAX_ABSOLUTE_CACHE_DELTA_CHANGE_ACROSS_IDENTITY_SPECIFIC_AND_', ...
    'SINGLE_PAIR_CLASS_SPECIFIC_P10_MEDIAN_P90_SUBSTITUTIONS'];
protocol.microbenchmark_repeat_target = 100;
protocol.microbenchmark_warmup_count = 10;
protocol.stage_schema = { ...
    'ROOT_TANGENT_PROFILE_SAFE','K1_PUBLIC','K2_PUBLIC', ...
    'TAIL_FULL_DATA','CENTER_MANIFOLD_DERIVATIVES', ...
    'PROJECTED_DIRECTION','T4_PROFILE','FINAL_SAFE_SELECTOR', ...
    'K1_CONTEXT','K1_FULL_DATA','K1_INITIALIZATION_TOTAL', ...
    'K1_INIT_CONVENTIONAL','K1_INIT_GROUP_PREPARE', ...
    'K1_INIT_GROUP_Q1','K1_INIT_GROUP_Q2','K1_CORE_LITE', ...
    'K1_FIXED_FIT','K1_FIXED_START_BUILD', ...
    'K1_FIXED_REGISTERED_REFINEMENT', ...
    'K1_FIXED_FINAL_CERTIFICATION','K1_CONTINUOUS','K1_SELECTION', ...
    'K2_CONTEXT','K2_FULL_DATA','K2_INITIALIZATION_TOTAL', ...
    'K2_INIT_CONVENTIONAL','K2_INIT_GROUP_PREPARE', ...
    'K2_INIT_GROUP_Q1','K2_INIT_GROUP_Q2','K2_CORE_LITE', ...
    'K2_HELPER_K1','K2_START_BUILD','K2_NESTED_ANCHOR', ...
    'K2_REGISTERED_REFINEMENT','K2_FINAL_CERTIFICATION', ...
    'K2_SELECTION'};
protocol.registry_hash = stage8_k2_tcc_stable_hash( ...
    'PLACEMENT_AUDIT_REGISTRY', registry);
[protocol.audit_code_hash, protocol.audit_code_files] = ...
    audit_code_hash_local(repo_dir);
timing_fields = rmfield(protocol, {'registry_hash','audit_code_hash', ...
    'audit_code_files','level_a_closure_commit','audit_start_commit', ...
    'protocol_id'});
protocol.timing_configuration_hash = stage8_k2_tcc_stable_hash( ...
    'PLACEMENT_AUDIT_TIMING_CONFIGURATION', timing_fields);
protocol.protocol_hash = stage8_k2_tcc_stable_hash( ...
    'PLACEMENT_AUDIT_PROTOCOL', protocol);
end

function [digest, relative_files] = audit_code_hash_local(repo_dir)
cache_dir = fullfile(repo_dir, 'tools', ...
    'stage8_k2_tangent_canonical_cache', 'matlab');
listing = dir(fullfile(cache_dir, '*.m'));
relative_files = cell(numel(listing), 1);
for index = 1:numel(listing)
    relative_files{index} = fullfile('tools', ...
        'stage8_k2_tangent_canonical_cache', 'matlab', listing(index).name);
end
extra = { ...
    fullfile('tools','stage8_k2_tangent_profile','matlab', ...
        'stage8_k2_tp_fit_safe.m'); ...
    fullfile('tools','stage8_k2_tangent_profile','matlab', ...
        'stage8_k2_tp_profile_scale.m'); ...
    fullfile('beamspace_ml_v18','source','stepwise_signal_model','steps', ...
        'step_12_3_grouped_conditional_dml','common', ...
        'refine_joint_sequential_dml.m'); ...
    fullfile('beamspace_ml_v18','source','stepwise_signal_model','steps', ...
        'step_12_6_k12_bootstrap_resolution','common', ...
        'build_k2_initializations.m'); ...
    fullfile('beamspace_ml_v18','source','stepwise_signal_model','steps', ...
        'step_12_6_k12_bootstrap_resolution','common', ...
        'build_stage8_initialization_context_from_data.m'); ...
    fullfile('beamspace_ml_v18','source','stepwise_signal_model','steps', ...
        'step_12_6_k12_bootstrap_resolution','common', ...
        'fit_local_model_k.m'); ...
    fullfile('beamspace_ml_v18','source','stepwise_signal_model','steps', ...
        'step_12_7_known_k_local_cell_refinement','common', ...
        'build_stage8_known_k_local_context.m'); ...
    fullfile('beamspace_ml_v18','source','stepwise_signal_model','steps', ...
        'step_12_7_known_k_local_cell_refinement','common', ...
        'estimate_stage8_known_k_local_cell.m'); ...
    fullfile('beamspace_ml_v18','source','stepwise_signal_model','steps', ...
        'step_12_7_known_k_local_cell_refinement','common', ...
        'fit_stage8_core_lite.m')};
relative_files = sort([relative_files;extra]);
contents = cell(size(relative_files));
for index = 1:numel(relative_files)
    path_now = fullfile(repo_dir, relative_files{index});
    if ~isfile(path_now)
        error('stage8_k2_tcc_audit_protocol:CodeFile', ...
            'Audit code file is missing: %s', path_now);
    end
    contents{index} = fileread(path_now);
end
digest = stage8_k2_tcc_stable_hash( ...
    'PLACEMENT_AUDIT_CODE', relative_files, contents);
end
