function manifest = stage8_k2_tcc_write_evidence(repo_dir, static_output, ...
    query_output, runtime_output, micro_output, economics_output, ...
    protocol, git_metadata)
%STAGE8_K2_TCC_WRITE_EVIDENCE Write only the six committed 52_* artifacts.

innovation_dir = fullfile(repo_dir, 'innovation-mining');
paths = struct( ...
    'report', fullfile(innovation_dir, ...
    '52_stage8_k2_tangent_pipeline_cache_placement_audit.md'), ...
    'static', fullfile(innovation_dir, ...
    '52_stage8_k2_tangent_pipeline_cache_static_certification.csv'), ...
    'query', fullfile(innovation_dir, ...
    '52_stage8_k2_tangent_pipeline_cache_query_audit.csv'), ...
    'runtime', fullfile(innovation_dir, ...
    '52_stage8_k2_tangent_pipeline_runtime_summary.csv'), ...
    'economics', fullfile(innovation_dir, ...
    '52_stage8_k2_tangent_pipeline_cache_economics.csv'), ...
    'manifest', fullfile(innovation_dir, ...
    '52_stage8_k2_tangent_pipeline_cache_placement_manifest.json'));
writetable(static_output.rows, paths.static);
writetable(query_output.query_rows, paths.query);
writetable(runtime_output.runtime_summary, paths.runtime);
writetable(economics_output.economics, paths.economics);
write_report_local(paths.report, static_output, query_output, ...
    runtime_output, micro_output, economics_output, protocol, git_metadata);
manifest = manifest_local(static_output, query_output, runtime_output, ...
    economics_output, protocol, git_metadata, paths);
write_json_local(paths.manifest, manifest);
end

function write_report_local(path_now, static_output, query_output, ...
    runtime_output, micro_output, economics_output, protocol, git)
fid = fopen(path_now, 'w');
if fid < 0
    error('stage8_k2_tcc_write_evidence:ReportOpen', ...
        'Unable to open the placement audit report.');
end
cleanup = onCleanup(@() fclose(fid));
s = static_output.rows;
q = query_output.query_rows;
r = runtime_output.runtime_summary;
m = micro_output.summary;
e = economics_output.economics;
overall = e(e.scenario_aggregate == "OVERALL_72_TRIALS", :);
totals = query_output.mismatch_totals;

fprintf(fid, '# Stage8 K2 Tangent Pipeline Canonical Dictionary Placement Audit\n\n');
fprintf(fid, 'Status: `STAGE8_K2_TANGENT_PIPELINE_CACHE_PLACEMENT_AUDIT_COMPLETE`\n\n');
fprintf(fid, 'Technical status: `TECHNICALLY_CERTIFIED`\n\n');
fprintf(fid, 'Predicted performance status: `%s`\n\n', ...
    economics_output.predicted_performance_status);
fprintf(fid, ['This is a diagnostic placement audit. The 21-key dictionary ', ...
    'was not integrated into the production estimator; every dictionary ', ...
    'decision check was a shadow replay.\n\n']);

fprintf(fid, '## A. Git\n\n');
fprintf(fid, '- Repository: `%s`\n', repo_dir_text_local(git.repository));
fprintf(fid, '- Branch: `%s`\n', git.branch);
fprintf(fid, '- Level-A closure commit: `%s`\n', ...
    protocol.level_a_closure_commit);
fprintf(fid, '- Audit start commit: `%s`\n', protocol.audit_start_commit);
fprintf(fid, '- Audit code commit: `%s`\n', git.audit_final_commit);
fprintf(fid, '- Evidence write base HEAD: `%s`\n', git.evidence_base_head);
fprintf(fid, '- Push: performed after evidence commit by the execution agent\n');
fprintf(fid, '- Prompt input file: preserved locally and excluded from commits\n\n');

fprintf(fid, '## B. Theory\n\n');
fprintf(fid, ['- Registered domain: azimuth `7.4:0.2:8.6` (7) and ', ...
    'elevation `9.8:0.2:10.2` (3); `|Omega| = 21`.\n']);
fprintf(fid, '- Single universe: `21` per identity.\n');
fprintf(fid, '- Canonical unordered K2 universe including diagonal: `231` per identity.\n');
fprintf(fid, '- Ordered nested universe: `441` per identity.\n');
fprintf(fid, '- Measurement identities: `2`, with `36` frozen trials each.\n');
fprintf(fid, ['- Closure: fixed registered starts remain in `Omega^K`; ', ...
    'grouped elevation/conditional azimuth outputs are selected from the ', ...
    'registered grids.\n']);
fprintf(fid, ['- Shared dictionary numeric representative: ', ...
    '`BALANCED_SINGLE_PAIR_DIRECT_ACCUMULATION_MIDPOINT`, resolving the ', ...
    'frozen single-column/two-column BLAS accumulation split without ', ...
    'changing any tolerance or production path.\n\n']);

fprintf(fid, '## C. Static certification\n\n');
fprintf(fid, '- Singles passed: `%d/%d`.\n', ...
    nnz(s.case_type == "SINGLE" & s.static_pass), ...
    nnz(s.case_type == "SINGLE"));
fprintf(fid, '- Canonical pairs passed: `%d/%d`.\n', ...
    nnz(s.case_type == "CANONICAL_PAIR" & s.static_pass), ...
    nnz(s.case_type == "CANONICAL_PAIR"));
fprintf(fid, '- Ordered nested assemblies passed: `%d/%d`.\n', ...
    nnz(s.case_type == "ORDERED_NESTED" & s.static_pass), ...
    nnz(s.case_type == "ORDERED_NESTED"));
fprintf(fid, '- Max legacy/direct G relative error: `%.17g`.\n', ...
    max(s.legacy_vs_direct_G_rel_error));
fprintf(fid, '- Max legacy/direct G absolute error: `%.17g`.\n', ...
    max(s.legacy_vs_direct_G_abs_error));
fprintf(fid, '- Max direct/dictionary G relative error: `%.17g`.\n', ...
    max(s.direct_vs_dictionary_G_rel_error));
fprintf(fid, '- Max singular-value difference: `%.17g`.\n', ...
    max(s.singular_value_abs_error));
fprintf(fid, '- Max exact-key error: `%.17g deg`.\n', ...
    max(s.exact_key_error_deg));
fprintf(fid, '- Max rank-threshold difference: `%.17g`.\n', ...
    max(s.rank_threshold_abs_difference));
fprintf(fid, '- Rank mismatch: `%d`.\n', nnz(~s.rank_match));
fprintf(fid, '- First/second-column identity mismatch: `%d`.\n', ...
    nnz((s.first_column_rel_error > 64 * eps(14) | ...
    s.second_column_rel_error > 64 * eps(14)) & ...
    s.case_type == "ORDERED_NESTED"));
fprintf(fid, '- Continuous numeric certification: `PASS`.\n');
fprintf(fid, '- Discrete decision certification: `PASS`.\n\n');

fprintf(fid, '## D. 72-trial trajectory\n\n');
write_mismatch_local(fid, 'Key', totals.key_mismatch_count);
write_mismatch_local(fid, 'Rank', totals.rank_mismatch_count);
write_mismatch_local(fid, 'Candidate-order', ...
    totals.candidate_order_mismatch_count);
write_mismatch_local(fid, 'Tie-set', totals.tie_mismatch_count);
write_mismatch_local(fid, 'Best-index', totals.best_index_mismatch_count);
write_mismatch_local(fid, 'Accepted-update', ...
    totals.accepted_update_mismatch_count);
write_mismatch_local(fid, 'Trajectory', totals.trajectory_mismatch_count);
write_mismatch_local(fid, 'Selected-start', ...
    totals.selected_start_mismatch_count);
write_mismatch_local(fid, 'Nested-pass', ...
    totals.nested_pass_mismatch_count);
write_mismatch_local(fid, 'Final-selector', ...
    totals.final_selector_mismatch_count);
fprintf(fid, '- Helper K1 fixed-subfit reuse: `%s` (`72/72`).\n', ...
    ternary_local(query_output.helper_reuse_certified, ...
    'CERTIFIED_K1_FIXED_HELPER_REUSE', 'FAILED'));
fprintf(fid, '- K1/K2 full-data and initialization output identity: `%s`.\n\n', ...
    ternary_local(query_output.initialization_reuse_certified, ...
    'CERTIFIED', 'FAILED'));

fprintf(fid, '## E. Query reuse\n\n');
fprintf(fid, '| Stage | Manifold builds | Requested columns | Unique keys | Reuse | Registered exact fraction |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|\n');
stage_ids = unique(q.stage_id, 'stable');
for index = 1:numel(stage_ids)
    rows = q(q.stage_id == stage_ids(index), :);
    builds = sum(rows.manifold_build_count);
    requested = sum(rows.requested_column_count);
    registered = sum(rows.registered_exact_column_count);
    histogram = histogram_sum_local(rows.key_histogram_json);
    unique_keys = nnz(histogram > 0);
    reuse = registered / max(unique_keys, 1);
    fprintf(fid, '| `%s` | %d | %d | %d | %.3f | %.6f |\n', ...
        stage_ids(index), builds, requested, unique_keys, reuse, ...
        registered / max(requested, 1));
end
fprintf(fid, '\n');

fprintf(fid, '## F. Runtime decomposition\n\n');
fprintf(fid, ['All values below are medians of trial-level medians for the ', ...
    '72-trial overall distribution; raw repeats were not pooled into one ', ...
    'homogeneous p90.\n\n']);
runtime_stage_line_local(fid, r, 'K1_PUBLIC', 'K1 public share');
runtime_stage_line_local(fid, r, 'K2_PUBLIC', 'K2 public share');
runtime_combined_line_local(fid, r, ...
    {'K1_INITIALIZATION_TOTAL','K2_INITIALIZATION_TOTAL'}, ...
    'Initialization inclusive share');
runtime_combined_line_local(fid, r, ...
    {'K1_FIXED_REGISTERED_REFINEMENT','K2_REGISTERED_REFINEMENT'}, ...
    'Fixed registered-refinement inclusive share');
runtime_stage_line_local(fid, r, 'K1_CONTINUOUS', 'Continuous K1 share');
runtime_stage_line_local(fid, r, 'CENTER_MANIFOLD_DERIVATIVES', ...
    'Center/derivative share');
runtime_stage_line_local(fid, r, 'T4_PROFILE', 'T4 share');
runtime_stage_line_local(fid, r, 'UNATTRIBUTED', 'Unattributed share');
overhead = overall_runtime_row_local(r, 'ROOT_TANGENT_PROFILE_SAFE');
fprintf(fid, ['- Paired instrumentation overhead median/p90/min/max: ', ...
    '`%.6g / %.6g / %.6g / %.6g s`.\n'], ...
    overhead.paired_instrumentation_overhead_median_sec, ...
    overhead.paired_instrumentation_overhead_p90_sec, ...
    overhead.paired_instrumentation_overhead_min_sec, ...
    overhead.paired_instrumentation_overhead_max_sec);
p1 = aggregate_runtime_row_local(r, 'PROFILE', 'P1', 'T4_PROFILE');
overall_t4 = overall_runtime_row_local(r, 'T4_PROFILE');
fprintf(fid, ['- Level-A P1 `T4 ~= 0.54%%`: current P1 median share is ', ...
    '`%.4f%%`, overall is `%.4f%%`; representativeness is `%s`.\n\n'], ...
    100 * p1.median_stage_share, 100 * overall_t4.median_stage_share, ...
    ternary_local(abs(p1.median_stage_share - overall_t4.median_stage_share) ...
    <= 0.0054, 'BROADLY_REPRESENTATIVE', 'NOT_REPRESENTATIVE'));

fprintf(fid, '## G. Microbenchmark\n\n');
fprintf(fid, '| Identity | Primitive | Median us | P10 us | P90 us |\n');
fprintf(fid, '|---|---|---:|---:|---:|\n');
for index = 1:height(m)
    fprintf(fid, '| `%s` | `%s` | %.3f | %.3f | %.3f |\n', ...
        short_hash_local(m.fixed_measurement_hash(index)), ...
        m.benchmark_id(index), 1e6 * m.median_runtime_sec(index), ...
        1e6 * m.p10_runtime_sec(index), 1e6 * m.p90_runtime_sec(index));
end
fprintf(fid, ['\nDiagnostic MAT load was measured as ', ...
    '`DIAGNOSTIC_21_KEY_ARTIFACT_LOAD`; it is not a production load format.\n\n']);

fprintf(fid, '## H. Counterfactual\n\n');
fprintf(fid, 'All values are `COUNTERFACTUAL_ESTIMATE_NOT_INTEGRATED_RUNTIME`.\n\n');
fprintf(fid, '- Measured T0: `%.6f s` (sum over 72 trial medians).\n', ...
    overall.measured_T0);
fprintf(fid, '- Predicted TS: `%.6f s`.\n', overall.predicted_TS);
fprintf(fid, '- Predicted TSG: `%.6f s`.\n', overall.predicted_TSG);
fprintf(fid, '- Predicted TSGC: `%.6f s`.\n', overall.predicted_TSGC);
fprintf(fid, '- Delta structural: `%.6f s`.\n', ...
    overall.predicted_delta_structural);
fprintf(fid, '- Delta G-only | structural: `%.6f s`.\n', ...
    overall.predicted_delta_g_only_given_structural);
fprintf(fid, '- Delta cache | structural,G-only: `%.6f s`.\n\n', ...
    overall.predicted_delta_cache_given_structural_g_only);

fprintf(fid, '## I. Lifecycle\n\n');
identity_rows = e(e.scenario_aggregate ~= "OVERALL_72_TRIALS", :);
for index = 1:height(identity_rows)
    fprintf(fid, ['- `%s`: build-inclusive break-even `%g`, online-only ', ...
        'break-even `%g`, 36-trial conditional saving `%.3f ms`, ', ...
        'end-to-end modeled saving `%.4f%%`, build-inclusive net ', ...
        '`%.3f ms`, online-only net `%.3f ms`.\n'], ...
        short_hash_local(identity_rows.fixed_measurement_hash(index)), ...
        identity_rows.build_inclusive_break_even(index), ...
        identity_rows.online_only_break_even(index), ...
        1e3 * identity_rows.predicted_delta_cache_point_sec(index), ...
        identity_rows.end_to_end_saving_percentage(index), ...
        1e3 * identity_rows.net_saving_build_inclusive_sec(index), ...
        1e3 * identity_rows.net_saving_online_only_sec(index));
end
fprintf(fid, ['- Deployment: `NOT_ASSESSED_NO_WORKLOAD_HORIZON`; ', ...
    'no economic PASS/FAIL or deployment justification is claimed.\n\n']);

fprintf(fid, '## J. Attribution\n\n');
fprintf(fid, '- Predicted Core-Lite direct/dictionary: `%.6f / %.6f s`.\n', ...
    overall.predicted_core_lite_direct, ...
    overall.predicted_core_lite_dictionary);
fprintf(fid, '- Predicted Tangent-safe direct/dictionary: `%.6f / %.6f s`.\n', ...
    overall.predicted_tangent_direct, overall.predicted_tangent_dictionary);
fprintf(fid, '- Predicted Delta Core: `%.6f s`.\n', ...
    overall.predicted_delta_core);
fprintf(fid, '- Predicted Delta Tangent: `%.6f s`.\n', ...
    overall.predicted_delta_tangent);
fprintf(fid, ['- `PREDICTED_DIFFERENCE_IN_DIFFERENCES_INTERACTION` I: ', ...
    '`%.6f s`; this is not causal synergy.\n'], ...
    overall.predicted_did_interaction_I);
fprintf(fid, '- Predicted Tangent exposure sum: `%.6f s`.\n', ...
    overall.predicted_delta_tangent_exposure);
fprintf(fid, '- `exposure_adjusted_residual_JT = NaN`.\n');
fprintf(fid, '- `JT_status = NOT_AVAILABLE_PRE_INTEGRATION`.\n');
fprintf(fid, ['- Q8b measured Tangent-specific residual: ', ...
    '`DEFERRED_TO_INTEGRATION`.\n\n']);

fprintf(fid, '## K. Decision\n\n');
fprintf(fid, '- Technical certification: `TECHNICALLY_CERTIFIED`.\n');
fprintf(fid, '- Cache conditional point estimate: `%.6f s` (`%.3f ms`).\n', ...
    overall.predicted_delta_cache_point_sec, ...
    1e3 * overall.predicted_delta_cache_point_sec);
fprintf(fid, '- Conservative timing/sensitivity lower bound: `%.6f s`.\n', ...
    overall.conservative_timing_sensitivity_lower_bound_sec);
fprintf(fid, '- Minimum per-identity cache conditional delta: `%.6f s`.\n', ...
    min(identity_rows.predicted_delta_cache_point_sec));
fprintf(fid, '- Certified lookup faster than direct G-only: `%d`.\n', ...
    economics_output.lookup_faster_than_direct_g_only);
fprintf(fid, '- Predicted performance status: `%s`.\n', ...
    economics_output.predicted_performance_status);
fprintf(fid, '- Recommended placement: `%s`.\n', ...
    economics_output.recommended_placement);
if economics_output.predicted_performance_status == ...
        "PREDICTED_SAVING_ROBUST_POSITIVE"
    next_action = 'RECOMMEND_FIXED_PATH_DICTIONARY_INTEGRATION';
else
    next_action = 'DO_NOT_INTEGRATE_FIXED_PATH_DICTIONARY_FROM_THIS_AUDIT';
end
fprintf(fid, '- Recommended next action: `%s`.\n\n', next_action);

fprintf(fid, '## Q1-Q8b direct answers\n\n');
fprintf(fid, ['1. Q1: the runtime shares are reported in Section F; K1/K2 ', ...
    'public fits and their initialization/refinement dominate according to ', ...
    'the measured stage table.\n']);
fprintf(fid, ['2. Q2: full-data, initialization, and helper-K1 repeated costs ', ...
    'are the structural delta `%.6f s` over 72 trial medians.\n'], ...
    overall.predicted_delta_structural);
fprintf(fid, ['3. Q3: fixed registered builds, requested columns, and DML ', ...
    'scores are enumerated by stage in the query CSV and Section E.\n']);
fprintf(fid, ['4. Q4: 21-key reuse multiplicity is reported per stage and is ', ...
    '`%.3f` overall for eligible registered columns.\n'], ...
    overall.reuse_multiplicity);
fprintf(fid, ['5. Q5: point estimate sign `%s`; conservative lower-bound sign ', ...
    '`%s`.\n'], sign_text_local(overall.predicted_delta_cache_point_sec), ...
    sign_text_local(overall.conservative_timing_sensitivity_lower_bound_sec));
fprintf(fid, '6. Q6: per-identity lifecycle and break-even are in Section I.\n');
fprintf(fid, '7. Q7: `%s`, classified by the frozen priority rules.\n', ...
    economics_output.predicted_performance_status);
fprintf(fid, ['8. Q8a: per-stage and single/pair exposure rows are retained ', ...
    'outside Git and aggregated in the economics evidence. Q8b: ', ...
    '`DEFERRED_TO_INTEGRATION`; `JT_status = NOT_AVAILABLE_PRE_INTEGRATION`.\n\n']);

fprintf(fid, '## Explicitly not executed\n\n');
scopes = {'NO_NEW_BRANCH','NO_LEVEL_B_INTERPOLATION', ...
    'NO_NEAREST_NEIGHBOR','NO_FIXED_PATH_DICTIONARY_INTEGRATION', ...
    'NO_CONTEXT_REUSE_INTEGRATION','NO_G_ONLY_PRODUCTION_REPLACEMENT', ...
    'NO_TANGENT_RECALIBRATION','NO_CLASSICAL_BASELINE_RERUN', ...
    'NO_NEW_MONTE_CARLO_PROTOCOL','NO_FPGA_CACHE_MAPPING', ...
    'NO_PARENT_BRANCH_MERGE','NO_PR_CREATED','NO_FORCE_PUSH'};
for index = 1:numel(scopes)
    fprintf(fid, '- `%s`\n', scopes{index});
end
fprintf(fid, '\nCompletion means audit complete, not dictionary integrated, measured speedup validated, or deployment justified.\n');
clear cleanup
end

function manifest = manifest_local(static_output, query_output, runtime_output, ...
    economics_output, protocol, git, paths)
totals = query_output.mismatch_totals;
trial_runtime = runtime_output.runtime_summary( ...
    runtime_output.runtime_summary.aggregation_level == "TRIAL" & ...
    runtime_output.runtime_summary.stage_id == ...
    "ROOT_TANGENT_PROFILE_SAFE", :);
if economics_output.predicted_performance_status == ...
        "PREDICTED_SAVING_ROBUST_POSITIVE"
    next_action = 'RECOMMEND_FIXED_PATH_DICTIONARY_INTEGRATION';
else
    next_action = 'DO_NOT_INTEGRATE_FIXED_PATH_DICTIONARY_FROM_THIS_AUDIT';
end
manifest = struct( ...
    'branch', git.branch, ...
    'level_a_closure_commit', protocol.level_a_closure_commit, ...
    'audit_start_commit', protocol.audit_start_commit, ...
    'audit_final_commit', git.audit_final_commit, ...
    'audit_code_hash', protocol.audit_code_hash, ...
    'registry_hash', protocol.registry_hash, ...
    'timing_configuration_hash', protocol.timing_configuration_hash, ...
    'theory_status', 'REGISTERED_CLOSURE_CERTIFIED', ...
    'performance_status', economics_output.predicted_performance_status, ...
    'MATLAB_release', version('-release'), 'single_comp_thread', true, ...
    'trial_count', 72, 'timed_repeat_target', protocol.repeat_target, ...
    'timed_repeat_actual_min', min(trial_runtime.repeat_count), ...
    'measurement_identity_count', static_output.identity_count, ...
    'registered_single_count', 21, 'canonical_pair_count', 231, ...
    'ordered_nested_count', 441, ...
    'static_pass_count', nnz(static_output.rows.static_pass), ...
    'query_audit_pass_count', query_output.query_audit_pass_count, ...
    'key_mismatch_total', totals.key_mismatch_count, ...
    'rank_mismatch_total', totals.rank_mismatch_count, ...
    'candidate_order_mismatch_total', ...
    totals.candidate_order_mismatch_count, ...
    'tie_mismatch_total', totals.tie_mismatch_count, ...
    'best_index_mismatch_total', totals.best_index_mismatch_count, ...
    'accepted_update_mismatch_total', ...
    totals.accepted_update_mismatch_count, ...
    'trajectory_mismatch_total', totals.trajectory_mismatch_count, ...
    'selected_start_mismatch_total', ...
    totals.selected_start_mismatch_count, ...
    'nested_pass_mismatch_total', totals.nested_pass_mismatch_count, ...
    'final_selector_mismatch_total', totals.final_selector_mismatch_count, ...
    'truth_leakage_count', query_output.truth_leakage_count, ...
    'classical_baseline_rerun', false, 'full_new_monte_carlo', false, ...
    'level_b_interpolation', false, ...
    'fixed_path_dictionary_integrated', false, ...
    'context_reuse_integrated', false, 'g_only_integrated', false, ...
    'technical_certification_status', 'TECHNICALLY_CERTIFIED', ...
    'predicted_performance_status', ...
    economics_output.predicted_performance_status, ...
    'deployment_status', 'NOT_ASSESSED_NO_WORKLOAD_HORIZON', ...
    'recommended_placement', economics_output.recommended_placement, ...
    'recommended_next_action', next_action, ...
    'completion_status', ...
    'STAGE8_K2_TANGENT_PIPELINE_CACHE_PLACEMENT_AUDIT_COMPLETE', ...
    'JT_status', 'NOT_AVAILABLE_PRE_INTEGRATION', ...
    'exposure_adjusted_residual_JT', NaN, ...
    'result_hashes', result_hashes_local(paths));
end

function hashes = result_hashes_local(paths)
names = {'report','static','query','runtime','economics'};
hashes = struct();
for index = 1:numel(names)
    hashes.(names{index}) = stage8_k2_tcc_stable_hash( ...
        'PLACEMENT_AUDIT_RESULT_FILE', fileread(paths.(names{index})));
end
end

function write_json_local(path_now, value)
fid = fopen(path_now, 'w');
if fid < 0, error('stage8_k2_tcc_write_evidence:JsonOpen', ...
        'Unable to open manifest JSON.'); end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', jsonencode(value, 'PrettyPrint', true));
clear cleanup
end

function write_mismatch_local(fid, label, value)
fprintf(fid, '- %s mismatch: `%d`.\n', label, value);
end

function histogram = histogram_sum_local(values)
histogram = zeros(1, 21);
for index = 1:numel(values)
    histogram = histogram + reshape(jsondecode(values(index)), 1, []);
end
end

function row = overall_runtime_row_local(runtime, stage_id)
row = aggregate_runtime_row_local(runtime, 'OVERALL', ...
    'ALL_72_TRIALS', stage_id);
end

function row = aggregate_runtime_row_local(runtime, level, value, stage_id)
row = runtime(runtime.aggregation_level == string(level) & ...
    runtime.scenario_aggregate == string(value) & ...
    runtime.timing_mode == "TIMING_STAGE" & ...
    runtime.stage_id == string(stage_id), :);
if height(row) ~= 1
    error('stage8_k2_tcc_write_evidence:RuntimeAggregate', ...
        'Runtime aggregate %s/%s/%s is unavailable.', level, value, stage_id);
end
end

function runtime_stage_line_local(fid, runtime, stage_id, label)
row = overall_runtime_row_local(runtime, stage_id);
fprintf(fid, '- %s: `%.4f%%` (median inclusive `%.6f s`).\n', ...
    label, 100 * row.median_stage_share, row.median_runtime_sec);
end

function runtime_combined_line_local(fid, runtime, stage_ids, label)
share = 0;
seconds = 0;
for index = 1:numel(stage_ids)
    row = overall_runtime_row_local(runtime, stage_ids{index});
    share = share + row.median_stage_share;
    seconds = seconds + row.median_runtime_sec;
end
fprintf(fid, '- %s: `%.4f%%` (sum of component medians `%.6f s`).\n', ...
    label, 100 * share, seconds);
end

function value = short_hash_local(hash)
text = char(string(hash));
value = text(1:min(12, numel(text)));
end

function value = ternary_local(condition, yes_value, no_value)
if condition, value = yes_value; else, value = no_value; end
end

function value = sign_text_local(number)
if number > 0, value = 'POSITIVE'; ...
elseif number < 0, value = 'NEGATIVE'; else, value = 'ZERO'; end
end

function value = repo_dir_text_local(value)
value = strrep(char(string(value)), '\', '/');
end
