function trials = stage8_k2_tecs_prepare_trial_bank(fixture)
%STAGE8_K2_TECS_PREPARE_TRIAL_BANK Materialize frozen data outside timers.

trials = cell(height(fixture.registry), 1);
for index = 1:height(fixture.registry)
    trials{index} = stage8_k2_tcc_generate_frozen_trial( ...
        fixture.registry(index, :), fixture.context);
    assert(strcmp(trials{index}.model.fixed_measurement_hash, ...
        char(string(fixture.semantic_snapshot.rows{index}. ...
        fixed_measurement_hash))), ...
        'stage8_k2_tecs_prepare_trial_bank:Identity');
end
end
