function output = stage8_k2_tecs_build_comparison_registry(runtime_root)
%STAGE8_K2_TECS_BUILD_COMPARISON_REGISTRY Freeze raw pair reuse and views.

modes = stage8_k2_tecs_build_mode_registry(runtime_root);
m0 = alias_local(modes, 'M0');
m1 = alias_local(modes, 'M1');
raw_rows = repmat(raw_template_local(), 2, 1);
raw_rows(1) = raw_local('NOOP_CONTROL', m0, m0, 'NOOP_CONTROL');
raw_rows(2) = raw_local('M0_VS_M1', m0, m1, 'TOTAL');
raw = struct2table(raw_rows);

views = repmat(view_template_local(), 5, 1);
views(1) = view_local('NOOP_CONTROL', 'NOOP_CONTROL', ...
    'NOOP_CONTROL', raw_rows(1), m0, "NOT_APPLICABLE");
views(2) = view_local('BLOO-C1_TOTAL', 'TOTAL_LOO', ...
    'BLOO-C1', raw_rows(1), m0, string(m1.candidate_canonical_mode_id));
views(3) = view_local('CM1_TOTAL', 'TOTAL', ...
    'CM1', raw_rows(2), m1, "NOT_APPLICABLE");
views(4) = view_local('M1_MARGINAL', 'MARGINAL', ...
    'M1', raw_rows(2), m1, "NOT_APPLICABLE");
views(5) = view_local('BLOO-C1_DIRECT', 'DIRECT_LOO', ...
    'BLOO-C1', raw_rows(2), m1, string(m1.candidate_canonical_mode_id));
view_table = struct2table(views);
payload = struct('raw', table2struct(raw), ...
    'views', table2struct(view_table), ...
    'reuse_rule', ['M0-vs-M0 raw pairs serve NOOP_CONTROL and ', ...
    'TOTAL_LOO; M0-vs-M1 raw pairs serve TOTAL, MARGINAL and ', ...
    'DIRECT_LOO because canonical modes, direction, trial, repeat ', ...
    'and pair order are identical.']);
output = struct('schema_version', ...
    'STAGE8_K2_TECS_SCREENING_COMPARISON_REGISTRY_V1', ...
    'raw', raw, 'views', view_table, ...
    'screening_comparison_set_hash', stage8_k2_tecs_sha256( ...
        'TECS_SCREENING_COMPARISON_SET_V1', payload));
end
function row = raw_local(label, baseline, candidate, primary_kind)
payload = struct('baseline_canonical_mode_id', ...
    char(baseline.candidate_canonical_mode_id), ...
    'candidate_canonical_mode_id', ...
    char(candidate.candidate_canonical_mode_id), ...
    'enabled_layer_set_hash', char(candidate.enabled_layer_set_hash), ...
    'precedence_hash', char(candidate.precedence_hash), ...
    'fallback_hash', char(candidate.fallback_hash), ...
    'paired_sign', 'TIME_A_BASELINE_MINUS_TIME_B_CANDIDATE');
row = raw_template_local();
row.comparison_id = "CMP_" + string(stage8_k2_tecs_sha256( ...
    'TECS_RAW_SCREENING_COMPARISON_V1', payload));
row.raw_label = string(label);
row.primary_comparison_kind = string(primary_kind);
row.baseline_canonical_mode_id = ...
    string(baseline.candidate_canonical_mode_id);
row.candidate_canonical_mode_id = ...
    string(candidate.candidate_canonical_mode_id);
row.enabled_layer_set_hash = string(candidate.enabled_layer_set_hash);
row.precedence_hash = string(candidate.precedence_hash);
row.fallback_hash = string(candidate.fallback_hash);
end

function row = view_local(id, kind, alias, raw, candidate, source_full)
row = view_template_local();
row.comparison_view_id = string(id);
row.comparison_id = raw.comparison_id;
row.comparison_kind = string(kind);
row.variant_alias_id = string(alias);
row.baseline_canonical_mode_id = raw.baseline_canonical_mode_id;
row.candidate_canonical_mode_id = raw.candidate_canonical_mode_id;
row.enabled_layer_set_hash = raw.enabled_layer_set_hash;
row.predecessor_canonical_mode_id = ...
    raw.baseline_canonical_mode_id;
row.source_full_canonical_mode_id = source_full;
row.alias_of_comparison_id = raw.comparison_id;
row.raw_sample_reused = true;
row.final_candidate_selection_eligible = strcmp(kind, 'TOTAL') && ...
    candidate.enabled_layer_count > 0;
end

function row = alias_local(modes, alias)
match = modes.aliases.variant_alias_id == string(alias);
assert(nnz(match) == 1);
row = modes.aliases(match, :);
canonical = modes.canonical.candidate_canonical_mode_id == ...
    row.candidate_canonical_mode_id;
row.enabled_layer_count = modes.canonical.enabled_layer_count(canonical);
end

function row = raw_template_local()
row = struct('comparison_id', "", 'raw_label', "", ...
    'primary_comparison_kind', "", ...
    'baseline_canonical_mode_id', "", ...
    'candidate_canonical_mode_id', "", ...
    'enabled_layer_set_hash', "", 'precedence_hash', "", ...
    'fallback_hash', "");
end

function row = view_template_local()
row = struct('comparison_view_id', "", 'comparison_id', "", ...
    'comparison_kind', "", 'variant_alias_id', "", ...
    'baseline_canonical_mode_id', "", ...
    'candidate_canonical_mode_id', "", ...
    'enabled_layer_set_hash', "", ...
    'predecessor_canonical_mode_id', "", ...
    'source_full_canonical_mode_id', "", ...
    'alias_of_comparison_id', "", 'raw_sample_reused', false, ...
    'final_candidate_selection_eligible', false);
end
