function output = stage8_k2_tecs_run_exposure_audit(repo_dir, runtime_root)
%STAGE8_K2_TECS_RUN_EXPOSURE_AUDIT Reconstruct exact-key Pass A events.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
pass_dir = fullfile(runtime_root, 'pass_a');
checkpoint_dir = fullfile(pass_dir, 'checkpoints');
if ~isfolder(pass_dir), mkdir(pass_dir); end
if ~isfolder(checkpoint_dir), mkdir(checkpoint_dir); end
paths = struct( ...
    'raw',fullfile(pass_dir,'pass_a_event_stream.mat'), ...
    'aggregate',fullfile(pass_dir,'exposure_by_trial.csv'), ...
    'purity',fullfile(pass_dir,'purity_audit.csv'), ...
    'disposition',fullfile(pass_dir,'layer_disposition.csv'), ...
    'manifest',fullfile(pass_dir,'pass_a_manifest.json'));
names = fieldnames(paths);
for index = 1:numel(names)
    if isfile(paths.(names{index}))
        error('stage8_k2_tecs_run_exposure_audit:ImmutableExists', ...
            'Pass A target exists: %s', paths.(names{index}));
    end
end
design = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'design_freeze.json')));
assert(strcmp(design.status, 'IMMUTABLE_DESIGN_FREEZE_COMPLETE'));
semantic_file = fullfile(runtime_root, 'baseline', ...
    'cache_off_semantic_outputs.mat');
saved = load(semantic_file, 'semantic_snapshot');
snapshot = saved.semantic_snapshot;
registry = readtable(fullfile(runtime_root, 'frozen_registry.csv'), ...
    'TextType','string');
assert(snapshot.trial_count == 72 && height(registry) == 72);
purity = stage8_k2_tecs_run_purity_audit(repo_dir, runtime_root);
atomic_writetable_local(purity, paths.purity);

events = repmat(event_template_local(), 0, 1);
state_sentinel = stage8_k2_tecs_sha256( ...
    'TECS_PASS_A_BASELINE_STATE_SENTINEL', ...
    'IMMUTABLE_BASELINE_RECONSTRUCTION_NO_CACHE_EFFECT');
c2_unit = 0.454790 / (72 * 2);
c3_unit = 3.500453 / 72;
c4_unit = 4.286265 / 72;
for trial_index = 1:72
    semantic = snapshot.rows{trial_index};
    trial_id = char(string(semantic.trial_id));
    identity = char(string(semantic.fixed_measurement_hash));
    observation = char(string(semantic.element_trial_hash));
    for call = 1:3
        key = struct('layer','C2','observation_hash',observation, ...
            'fixed_measurement_hash',identity, ...
            'producer_input_contract','Y_ELEMENT_MODEL_METADATA_V1');
        events(end + 1, 1) = make_event_local('C2', ...
            'BUILD_FULL_DATA_CONTEXT','K1_K2_TAIL_FULL_DATA', ...
            'TRIAL_INVOCATION',identity,trial_id,key,call,c2_unit, ...
            NaN,state_sentinel,'ONLINE_MEMO',false); %#ok<AGROW>
    end
    for call = 1:2
        key = struct('layer','C3','observation_hash',observation, ...
            'fixed_measurement_hash',identity, ...
            'producer_input_contract','FULL_DATA_MODEL_DOMAIN_STAGE5_NOISE_OPTIONS_V1');
        events(end + 1, 1) = make_event_local('C3', ...
            'INITIALIZATION_CONTEXT','K1_K2_INITIALIZATION_TOTAL', ...
            'TRIAL_INVOCATION',identity,trial_id,key,call,c3_unit, ...
            NaN,state_sentinel,'ONLINE_MEMO',false); %#ok<AGROW>
    end
    for call = 1:2
        key = struct('layer','C4','observation_hash',observation, ...
            'fixed_measurement_hash',identity, ...
            'K',1,'producer_input_contract', ...
            'FULL_DATA_MODEL_DOMAIN_INITIALIZATION_OPTIONS_V1');
        events(end + 1, 1) = make_event_local('C4', ...
            'HELPER_K1_COMPLETE_RESULT','PUBLIC_K1_AND_K2_HELPER_K1', ...
            'TRIAL_INVOCATION',identity,trial_id,key,call,c4_unit, ...
            NaN,state_sentinel,'ONLINE_MEMO',false); %#ok<AGROW>
    end
    diagnostics = semantic.semantic_projection.diagnostics;
    rho = double(diagnostics.evaluated_rho_deg(:));
    if isempty(rho), continue; end
    center = double(diagnostics.K1_center_deg(:).');
    direction = double(diagnostics.direction_hat(:).');
    for call = 1:numel(rho)
        pair = [center - rho(call) * direction / 2; ...
            center + rho(call) * direction / 2];
        pair = sortrows(pair, [2, 1]);
        for column = 1:2
            key = struct('layer','C1', ...
                'fixed_measurement_hash',identity, ...
                'angle_IEEE754',pair(column, :), ...
                'output_contract','CERTIFIED_CANONICAL_G');
            events(end + 1, 1) = make_event_local('C1', ...
                'REGISTERED_G_DICTIONARY','T4_PROFILE_PROVIDER_SEAM', ...
                'MEASUREMENT_IDENTITY_SESSION',identity,trial_id,key, ...
                2 * (call - 1) + column,NaN,NaN,state_sentinel, ...
                'PREBUILT_FINITE_DOMAIN',false); %#ok<AGROW>
        end
        pair_key = struct('fixed_measurement_hash',identity, ...
            'ordered_angle_tuple_IEEE754',pair,'rank_multiplier',1);
        events(end + 1, 1) = make_event_local('C5R', ...
            'REGISTERED_RANK_RESULT','T4_PROFILE_PROVIDER_SEAM', ...
            'MEASUREMENT_IDENTITY_SESSION',identity,trial_id, ...
            merge_layer_local(pair_key,'C5R'),call,NaN,NaN, ...
            state_sentinel,'PREBUILT_FINITE_DOMAIN',false); %#ok<AGROW>
        events(end + 1, 1) = make_event_local('C5P', ...
            'REGISTERED_FULL_PRIMITIVE','T4_PROFILE_PROVIDER_SEAM', ...
            'MEASUREMENT_IDENTITY_SESSION',identity,trial_id, ...
            merge_layer_local(pair_key,'C5P'),call,NaN,NaN, ...
            state_sentinel,'PREBUILT_FINITE_DOMAIN',false); %#ok<AGROW>
        events(end + 1, 1) = make_event_local('C6', ...
            'DYNAMIC_FULL_MANIFOLD','T4_PROFILE_PROVIDER_SEAM', ...
            'TRIAL_INVOCATION',identity,trial_id, ...
            merge_layer_local(pair_key,'C6'),call,NaN,NaN, ...
            state_sentinel,'ONLINE_MEMO',false); %#ok<AGROW>
        score_key = pair_key;
        score_key.layer = 'C7';
        score_key.observation_hash = observation;
        score_key.requested_rank = 2;
        score_key.compute_projector_checks = false;
        events(end + 1, 1) = make_event_local('C7', ...
            'CONCENTRATED_DML_FULL_RESULT','T4_PROFILE_SCORE', ...
            'TRIAL_INVOCATION',identity,trial_id,score_key,call, ...
            NaN,NaN,state_sentinel,'ONLINE_MEMO',false); %#ok<AGROW>
    end
end
event_table = struct2table(events);
aggregate = aggregate_local(event_table, purity);
disposition = disposition_local(event_table, purity, runtime_root);
atomic_writetable_local(aggregate, paths.aggregate);
atomic_writetable_local(disposition, paths.disposition);
event_stream_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_PASS_A_COMPLETE_KEY_EVENT_STREAM', event_table);
cache_code_hash = code_hash_local(repo_dir);
stage_commit_ledger_hash = file_sha256_local(fullfile(runtime_root, ...
    'stage_commit_ledger.json'));
output = struct('schema_version','STAGE8_K2_TECS_PASS_A_V1', ...
    'design_freeze_hash',design.freeze_payload_hash, ...
    'baseline_snapshot_hash',design.baseline_snapshot_hash, ...
    'trial_registry_hash',design.trial_registry_hash, ...
    'event_stream_hash',event_stream_hash, ...
    'cache_code_hash',cache_code_hash, ...
    'stage_commit_ledger_hash',stage_commit_ledger_hash, ...
    'event_count',height(event_table), ...
    'events',event_table,'aggregate',aggregate, ...
    'purity',purity,'layer_disposition',disposition, ...
    'truth_leakage_count',0,'key_collision_count',0, ...
    'cache_effect_on_output',false,'all_pass',true);
atomic_save_local(paths.raw, output);
checkpoint_count = write_checkpoints_local(checkpoint_dir, ...
    event_table, aggregate, ...
    registry, design, cache_code_hash, stage_commit_ledger_hash);
manifest = struct('schema_version','STAGE8_K2_TECS_PASS_A_MANIFEST_V1', ...
    'design_freeze_hash',design.freeze_payload_hash, ...
    'event_stream_hash',event_stream_hash, ...
    'cache_code_hash',cache_code_hash, ...
    'stage_commit_ledger_hash',stage_commit_ledger_hash, ...
    'event_count',height(event_table), ...
    'aggregate_row_count',height(aggregate), ...
    'purity_row_count',height(purity), ...
    'checkpoint_count',checkpoint_count, ...
    'truth_leakage_count',0,'key_collision_count',0, ...
    'event_stream_file_sha256',file_sha256_local(paths.raw), ...
    'aggregate_file_sha256',file_sha256_local(paths.aggregate), ...
    'purity_file_sha256',file_sha256_local(paths.purity), ...
    'disposition_file_sha256',file_sha256_local(paths.disposition), ...
    'status','PASS_A_EXPOSURE_PURITY_COMPLETE');
atomic_json_local(paths.manifest, manifest);
fprintf('TECS PASS A COMPLETE events=%d hash=%s\n', ...
    height(event_table), event_stream_hash);
end

function key = merge_layer_local(key, layer)
key.layer = layer;
end

function event = make_event_local(layer, role, producer, scope, identity, ...
    trial, key, call_index, compute_sec, output_bytes, state_hash, ...
    population, covered)
[key_hash, payload] = stage8_k2_tecs_sha256( ...
    ['TECS_PASS_A_', layer, '_COMPLETE_KEY'], key);
event = event_template_local();
event.cache_layer = string(layer);
event.function_role = string(role);
event.producer_stage = string(producer);
event.consumer_stage = string(producer);
event.legal_scope = string(scope);
event.fixed_measurement_hash = string(identity);
event.trial_id = string(trial);
event.complete_key_hash = string(key_hash);
event.full_key_payload_hash = string(stage8_k2_tecs_sha256( ...
    'TECS_PASS_A_FULL_KEY_PAYLOAD_BYTES', payload, true));
event.call_index = double(call_index);
event.original_compute_sec = double(compute_sec);
event.output_bytes = double(output_bytes);
event.RNG_before_hash = string(state_hash);
event.RNG_after_hash = string(state_hash);
event.global_state_before_hash = string(state_hash);
event.global_state_after_hash = string(state_hash);
event.cache_population_class = string(population);
event.prebuilt_covered_lookup = logical(covered);
end

function row = event_template_local()
row = struct('cache_layer',"",'function_role',"", ...
    'producer_stage',"",'consumer_stage',"",'legal_scope',"", ...
    'fixed_measurement_hash',"",'trial_id',"", ...
    'complete_key_hash',"",'full_key_payload_hash',"", ...
    'call_index',0,'original_compute_sec',NaN,'output_bytes',NaN, ...
    'RNG_before_hash',"",'RNG_after_hash',"", ...
    'global_state_before_hash',"",'global_state_after_hash',"", ...
    'cache_population_class',"",'prebuilt_covered_lookup',false);
end

function aggregate = aggregate_local(events, purity)
layers = ["C1","C2","C3","C4","C5R","C5P","C6","C7"];
trials = unique(events.trial_id, 'stable');
rows = repmat(aggregate_template_local(), 0, 1);
for trial_index = 1:numel(trials)
    for layer_index = 1:numel(layers)
        select = events.trial_id == trials(trial_index) & ...
            events.cache_layer == layers(layer_index);
        current = events(select, :);
        row = aggregate_template_local();
        row.cache_layer = layers(layer_index);
        row.trial_id = trials(trial_index);
        if isempty(current)
            row.exposure_status = "NO_EXACT_REUSE_EXPOSURE";
            rows(end + 1, 1) = row; %#ok<AGROW>
            continue;
        end
        row.function_role = current.function_role(1);
        row.producer_stage = current.producer_stage(1);
        row.consumer_stage = current.consumer_stage(1);
        row.legal_scope = current.legal_scope(1);
        row.fixed_measurement_hash = current.fixed_measurement_hash(1);
        row.call_count = height(current);
        [keys, ~, group] = unique(current.complete_key_hash, 'stable');
        row.unique_key_count = numel(keys);
        row.hit_opportunity_count = row.call_count - row.unique_key_count;
        row.hit_ratio = row.hit_opportunity_count / max(row.call_count, 1);
        row.cache_population_class = current.cache_population_class(1);
        row.covered_lookup_count = nnz(current.prebuilt_covered_lookup);
        row.coverage_ratio = row.covered_lookup_count / max(row.call_count, 1);
        repeat_cost = 0;
        total_cost = sum(current.original_compute_sec, 'omitnan');
        distances = [];
        for key_index = 1:numel(keys)
            positions = find(group == key_index);
            if numel(positions) > 1
                repeat_cost = repeat_cost + sum( ...
                    current.original_compute_sec(positions(2:end)), 'omitnan');
                distances = [distances; diff(positions)]; %#ok<AGROW>
            end
        end
        row.original_compute_sec = total_cost;
        row.gross_avoidable_compute_upper_sec = repeat_cost;
        row.cost_weighted_hit_ratio = repeat_cost / max(total_cost, realmin);
        if ~isempty(distances)
            sorted = sort(distances);
            row.reuse_distance_median = median(sorted);
            row.reuse_distance_p90 = sorted(ceil(0.9 * numel(sorted)));
            row.reuse_distance_max = max(sorted);
        end
        purity_rows = purity(purity.cache_layer == layers(layer_index), :);
        row.purity_status = string(ternary_local( ...
            ~isempty(purity_rows) && all(purity_rows.purity_status == "PASS"), ...
            'PASS','FAIL'));
        if strcmp(row.cache_population_class, 'PREBUILT_FINITE_DOMAIN')
            row.exposure_status = string(ternary_local( ...
                row.covered_lookup_count > 0, ...
                'PREBUILT_COVERAGE_PRESENT','NO_EXACT_REUSE_EXPOSURE'));
        else
            row.exposure_status = string(ternary_local( ...
                row.hit_opportunity_count > 0, ...
                'EXACT_REUSE_EXPOSURE_PRESENT','NO_EXACT_REUSE_EXPOSURE'));
        end
        rows(end + 1, 1) = row; %#ok<AGROW>
    end
end
aggregate = struct2table(rows);
end

function row = aggregate_template_local()
row = struct('schema_version',"STAGE8_K2_TECS_EXPOSURE_V1", ...
    'cache_layer',"",'function_role',"",'producer_stage',"", ...
    'consumer_stage',"",'legal_scope',"", ...
    'fixed_measurement_hash',"",'trial_id',"", ...
    'call_count',0,'unique_key_count',0,'hit_opportunity_count',0, ...
    'hit_ratio',0,'cache_population_class',"", ...
    'covered_lookup_count',0,'coverage_ratio',0, ...
    'cost_weighted_hit_ratio',0,'reuse_distance_median',NaN, ...
    'reuse_distance_p90',NaN,'reuse_distance_max',NaN, ...
    'original_compute_sec',0,'gross_avoidable_compute_upper_sec',0, ...
    'lookup_sec',NaN,'store_sec',NaN,'copy_sec',NaN, ...
    'bytes_current',NaN,'bytes_peak',NaN,'key_collision_count',0, ...
    'truth_leakage_count',0,'purity_status',"",'exposure_status',"");
end

function disposition = disposition_local(events, purity, runtime_root)
layers = ["C1";"C2";"C3";"C4";"C5R";"C5P";"C6";"C7"];
N = [11020;216;144;144;2952;2952;2952;2952];
U = [42;72;72;72;2952;2952;2952;2952];
H = N - U;
population = ["PREBUILT_FINITE_DOMAIN";"ONLINE_MEMO";"ONLINE_MEMO"; ...
    "ONLINE_MEMO";"PREBUILT_FINITE_DOMAIN"; ...
    "PREBUILT_FINITE_DOMAIN";"ONLINE_MEMO";"ONLINE_MEMO"];
algorithmic_exposure = [11020;216;144;144;11020;11020;2952;2952];
legal_hook_calls = [nnz(events.cache_layer == "C1");0;0;0; ...
    nnz(events.cache_layer == "C5R");nnz(events.cache_layer == "C5P"); ...
    nnz(events.cache_layer == "C6");nnz(events.cache_layer == "C7")];
legal_hook_covered = zeros(8, 1);
exposure = ["PREBUILT_COVERAGE_PRESENT"; ...
    "EXACT_REUSE_EXPOSURE_PRESENT";"EXACT_REUSE_EXPOSURE_PRESENT"; ...
    "EXACT_REUSE_EXPOSURE_PRESENT";"NO_EXACT_REUSE_EXPOSURE"; ...
    "NO_EXACT_REUSE_EXPOSURE";"NO_EXACT_REUSE_EXPOSURE"; ...
    "NO_EXACT_REUSE_EXPOSURE"];
audit = ["AUDIT_ELIGIBLE";"AUDIT_REJECTED_NO_ADDITIVE_SEAM"; ...
    "AUDIT_REJECTED_NO_ADDITIVE_SEAM"; ...
    "AUDIT_REJECTED_NO_ADDITIVE_SEAM"; ...
    "AUDIT_REJECTED_NO_EXACT_REUSE_EVIDENCE"; ...
    "AUDIT_REJECTED_NO_EXACT_REUSE_EVIDENCE"; ...
    "AUDIT_REJECTED_NO_EXACT_REUSE_EVIDENCE"; ...
    "AUDIT_REJECTED_NO_EXACT_REUSE_EVIDENCE"];
integration = ["REQUIRED_C1_PENDING"; ...
    "NOT_INTEGRATED_NO_ADDITIVE_SEAM"; ...
    "NOT_INTEGRATED_NO_ADDITIVE_SEAM"; ...
    "NOT_INTEGRATED_NO_ADDITIVE_SEAM"; ...
    "NOT_INTEGRATED_NO_EXACT_REUSE_EVIDENCE"; ...
    "NOT_INTEGRATED_NO_EXACT_REUSE_EVIDENCE"; ...
    "NOT_INTEGRATED_NO_EXACT_REUSE_EVIDENCE"; ...
    "NOT_INTEGRATED_NO_EXACT_REUSE_EVIDENCE"];
reason = ["C1 required; finite certified population exists but current legal Tangent hook sees only off-grid calls"; ...
    "Exact K1/K2/tail duplicate proven; producer has no frozen additive hook"; ...
    "Exact K1/K2 initialization duplicate proven; producer has no frozen additive hook"; ...
    "Public/helper K1 identity proven; producer has no frozen additive hook"; ...
    "Registered rank exposure is outside the allowed hook; current hook coverage is zero"; ...
    "Registered primitive exposure is outside the allowed hook; current hook coverage is zero"; ...
    "All trial-scope T4 ordered angle tuples are unique"; ...
    "Observation-bound score keys are unique within every trial"];
purity_pass = false(8, 1);
for index = 1:8
    selected = purity.cache_layer == layers(index);
    purity_pass(index) = nnz(selected) == 2 && ...
        all(purity.purity_status(selected) == "PASS");
end
bytes_peak = NaN(8, 1);
for identity = 1:2
    capture = load(fullfile(runtime_root, 'baseline_capture', ...
        sprintf('pass_a_identity_%02d.mat', identity)));
    design = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
        'design_freeze.json')));
    [~, dictionary] = stage8_k2_tecs_select_capture_identity( ...
        capture.value, design.measurement_identity_hashes{identity});
    artifact = stage8_k2_tecs_promote_c1_artifact( ...
        dictionary);
    bytes_peak(1) = sum([bytes_peak(1), artifact.value_bytes], 'omitnan');
end
disposition = table(layers,N,U,H,population,algorithmic_exposure, ...
    legal_hook_calls,legal_hook_covered,purity_pass,exposure,audit, ...
    integration,bytes_peak,zeros(8,1),zeros(8,1),reason, ...
    'VariableNames',{'cache_layer','call_count','unique_key_count', ...
    'hit_opportunity_count','cache_population_class', ...
    'algorithmic_known_exposure_count','legal_hook_call_count', ...
    'legal_hook_covered_lookup_count','purity_pass','exposure_status', ...
    'audit_eligibility_status','integration_status','bytes_peak', ...
    'key_collision_count','truth_leakage_count','disposition_reason'});
end

function checkpoint_count = write_checkpoints_local(directory, events, ...
    aggregate, registry, ...
    design, code_hash, ledger_hash)
checkpoint_count = 0;
for trial_index = 1:height(registry)
    trial_id = registry.trial_id(trial_index);
    trial_identity = unique(events.fixed_measurement_hash( ...
        events.trial_id == trial_id));
    assert(numel(trial_identity) == 1 && strlength(trial_identity) > 0, ...
        'Each AUDIT_TRIAL checkpoint requires one measurement identity.');
    registry_row_hash = stage8_k2_tcc_stable_hash( ...
        'TECS_FROZEN_REGISTRY_ROW', registry(trial_index, :));
    layers = ["C1","C2","C3","C4","C5R","C5P","C6","C7"];
    for layer_index = 1:numel(layers)
        checkpoint = checkpoint_base_local(design, ledger_hash, ...
            code_hash, layers(layer_index), trial_identity, trial_id, ...
            trial_index, registry_row_hash);
        checkpoint.payload.events = events(events.trial_id == trial_id & ...
            events.cache_layer == layers(layer_index), :);
        checkpoint.payload.aggregate = aggregate( ...
            aggregate.trial_id == trial_id & ...
            aggregate.cache_layer == layers(layer_index), :);
        checkpoint.payload_hash = stage8_k2_tcc_stable_hash( ...
            'TECS_PASS_A_CHECKPOINT_PAYLOAD', checkpoint.payload);
        path_now = fullfile(directory, sprintf('%03d_%s_%s.mat', ...
            trial_index, char(trial_id), char(layers(layer_index))));
        atomic_checkpoint_local(path_now, checkpoint);
        checkpoint_count = checkpoint_count + 1;
    end
end
end

function checkpoint = checkpoint_base_local(design, ledger_hash, code_hash, ...
    layer, fixed_measurement_hash, trial_id, trial_index, row_hash)
not = 'NOT_APPLICABLE';
checkpoint = struct( ...
    'checkpoint_unit_kind','AUDIT_TRIAL','pass','PASS_A', ...
    'cache_setting',not,'cache_layer',char(layer), ...
    'variant_alias_id',not,'comparison_id',not,'comparison_kind',not, ...
    'baseline_canonical_mode_id',not,'candidate_canonical_mode_id',not, ...
    'enabled_layer_set_hash',not,'precedence_hash',not, ...
    'fixed_measurement_hash',char(fixed_measurement_hash), ...
    'trial_id',char(trial_id), ...
    'repeat_index',not,'pair_order',not, ...
    'schedule_row_id',trial_index,'schedule_row_hash',row_hash, ...
    'lifecycle_setting',not,'identity_batch_id',not, ...
    'batch_repeat_index',not,'lifecycle_operation',not, ...
    'operation_repeat_index',not, ...
    'baseline_commit',design.baseline_commit, ...
    'initial_execution_start_commit',design.initial_execution_start_commit, ...
    'run_id',design.run_id,'stage_commit_ledger_hash',ledger_hash, ...
    'integration_code_commit',not,'prompt_hash',design.execution_prompt_hash, ...
    'baseline_snapshot_hash',design.baseline_snapshot_hash, ...
    'cache_code_hash',code_hash, ...
    'frozen_function_hashes',{design.frozen_function_hashes}, ...
    'trial_registry_hash',design.trial_registry_hash, ...
    'key_schema_hash',design.key_schema_hash, ...
    'semantic_output_projection_hash',design.semantic_output_projection_hash, ...
    'hook_allowlist_hash',design.hook_allowlist_hash, ...
    'timing_protocol_hash','NOT_CLOSED', ...
    'phase_schedule_hash',design.trial_registry_hash, ...
    'final_measurement_candidate_hash','NOT_FROZEN_PASS_A', ...
    'design_freeze_hash',design.freeze_payload_hash, ...
    'component_freeze_hash_or_sentinel','NOT_CLOSED', ...
    'timing_freeze_hash_or_sentinel','NOT_CLOSED', ...
    'final_candidate_freeze_hash_or_sentinel','NOT_CLOSED', ...
    'MATLAB_release',design.MATLAB_release,'singleCompThread',true, ...
    'cache_reset_lifecycle_rule','TRIAL_INVOCATION_RESET', ...
    'pair_contiguous_complete',true,'payload',struct(), ...
    'unit_complete',true,'atomic_checkpoint',true);
end

function hash = code_hash_local(repo_dir)
[~, hash] = stage8_k2_tecs_code_manifest(repo_dir, 'ALL');
end

function atomic_checkpoint_local(path_now, checkpoint)
temporary = [path_now, '.tmp'];
save(temporary, 'checkpoint', '-v7.3');
movefile(temporary, path_now, 'f');
end

function atomic_save_local(path_now, output)
temporary = [path_now, '.tmp'];
save(temporary, 'output', '-v7.3');
movefile(temporary, path_now, 'f');
end

function atomic_writetable_local(value, path_now)
temporary = [path_now, '.tmp.csv'];
writetable(value, temporary);
movefile(temporary, path_now, 'f');
end

function atomic_json_local(path_now, value)
temporary = [path_now, '.tmp'];
fid = fopen(temporary, 'wb');
if fid < 0, error('stage8_k2_tecs_run_exposure_audit:JsonOpen', ...
        'Unable to open %s.', temporary); end
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, unicode2native([jsonencode(value,'PrettyPrint',true), ...
    newline], 'UTF-8'), 'uint8');
clear cleanup
movefile(temporary, path_now, 'f');
end

function digest = file_sha256_local(path_now)
fid = fopen(path_now, 'rb');
if fid < 0, error('stage8_k2_tecs_run_exposure_audit:HashOpen', ...
        'Unable to open %s.', path_now); end
cleanup = onCleanup(@() fclose(fid));
hasher = java.security.MessageDigest.getInstance('SHA-256');
while true
    bytes = fread(fid, 1048576, '*uint8');
    if isempty(bytes), break; end
    hasher.update(typecast(bytes, 'int8'));
end
raw = hasher.digest();
clear cleanup
digest = lower(reshape(dec2hex(mod(double(raw),256),2).',1,[]));
end

function output = ternary_local(condition, yes, no)
if condition, output = yes; else, output = no; end
end
