function output = stage8_k2_tecs_run_screening(repo_dir, runtime_root)
%STAGE8_K2_TECS_RUN_SCREENING Pass E paired screening and selection.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
fixture = stage8_k2_tecs_build_runtime_fixture(repo_dir, runtime_root);
timing = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'timing_freeze.json')));
protocol = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'timing_protocol.json')));
assert(strcmp(timing.status, 'IMMUTABLE_TIMING_FREEZE_COMPLETE') && ...
    strcmp(timing.parent_freeze_hash, ...
    fixture.component.freeze_payload_hash), ...
    'stage8_k2_tecs_run_screening:FreezeChain', ...
    'The timing-freeze chain does not match the runtime fixture.');
[~, integration_hash] = stage8_k2_tecs_integration_manifest(repo_dir);
assert(strcmp(integration_hash, timing.cache_code_hash), ...
    'stage8_k2_tecs_run_screening:CodeDrift', ...
    'COMPONENT_FREEZE_INVALIDATED_STOP');

raw_registry = readtable(fullfile(runtime_root, 'freeze', ...
    'screening_raw_comparison_registry.csv'), 'TextType', 'string');
view_registry = readtable(fullfile(runtime_root, 'freeze', ...
    'screening_comparison_view_registry.csv'), 'TextType', 'string');
mode_registry = readtable(fullfile(runtime_root, 'freeze', ...
    'canonical_mode_registry.csv'), 'TextType', 'string');
alias_registry = readtable(fullfile(runtime_root, 'freeze', ...
    'mode_alias_registry.csv'), 'TextType', 'string');
schedule = readtable(fullfile(runtime_root, 'freeze', ...
    'screening_schedule.csv'), 'TextType', 'string');
schedule.trial_order_key = cellstr(string(schedule.trial_order_key));
schedule.included_in_statistics = ...
    logical(schedule.included_in_statistics);
warmup = readtable(fullfile(runtime_root, 'freeze', ...
    'formal_warmup_registry.csv'), 'TextType', 'string');
assert(strcmp(timing.screening_schedule_hash, stage8_k2_tecs_sha256( ...
    'TECS_SCREENING_SCHEDULE_V1', table2struct(schedule))) && ...
    height(schedule) == 864 && height(raw_registry) == 2, ...
    'stage8_k2_tecs_run_screening:ScheduleHash', ...
    'The screening schedule failed its frozen hash or cardinality check.');

pass_dir = fullfile(runtime_root, 'pass_e');
checkpoint_dir = fullfile(pass_dir, 'screening_checkpoints');
if ~isfolder(pass_dir), mkdir(pass_dir); end
if ~isfolder(checkpoint_dir), mkdir(checkpoint_dir); end
paths = struct('raw',fullfile(pass_dir,'screening_raw_samples.csv'), ...
    'summary',fullfile(pass_dir,'screening_summary.csv'), ...
    'proof',fullfile(pass_dir,'screening_selection_proof.json'), ...
    'manifest',fullfile(pass_dir,'screening_manifest.json'), ...
    'process',fullfile(pass_dir,'formal_process_snapshot.json'));
aggregate_names = fieldnames(paths);
for index = 1:numel(aggregate_names)
    if isfile(paths.(aggregate_names{index}))
        error('stage8_k2_tecs_run_screening:ImmutableExists', ...
            'Screening aggregate target exists: %s', ...
            paths.(aggregate_names{index}));
    end
end
process = process_snapshot_local('PASS_E_SCREENING');
assert(process.active_MATLAB_process_count == 1, ...
    'stage8_k2_tecs_run_screening:ProcessLimit', ...
    'Formal screening requires exactly one MATLAB process.');
stage8_k2_tecs_atomic_write_json(paths.process, process);

trials = stage8_k2_tecs_prepare_trial_bank(fixture);
rows = repmat(raw_template_local(), height(schedule), 1);
for comparison_index = 1:height(raw_registry)
    comparison_id = raw_registry.comparison_id(comparison_index);
    baseline_layers = layers_for_mode_local(mode_registry, ...
        raw_registry.baseline_canonical_mode_id(comparison_index));
    candidate_layers = layers_for_mode_local(mode_registry, ...
        raw_registry.candidate_canonical_mode_id(comparison_index));
    formal_warmup_local(trials, fixture, warmup, ...
        baseline_layers, candidate_layers);
    scheduled = find(schedule.comparison_id == comparison_id);
    for local_index = 1:numel(scheduled)
        schedule_index = scheduled(local_index);
        scheduled_row = schedule(schedule_index, :);
        checkpoint_path = fullfile(checkpoint_dir, sprintf( ...
            '%04d.mat', scheduled_row.schedule_row_id));
        expected = checkpoint_identity_local(fixture, timing, protocol, ...
            scheduled_row, raw_registry(comparison_index, :));
        if isfile(checkpoint_path)
            loaded = load(checkpoint_path, 'checkpoint');
            checkpoint = loaded.checkpoint;
            assert(checkpoint.unit_complete && ...
                checkpoint.pair_contiguous_complete && ...
                isequaln(checkpoint.identity, expected), ...
                'stage8_k2_tecs_run_screening:CheckpointIdentity', ...
                'CHECKPOINT_IDENTITY_MISMATCH_STOP');
            rows(schedule_index) = checkpoint.row;
            fprintf('TECS PASS E RESUME %d/%d %s\n', ...
                schedule_index, height(schedule), ...
                char(scheduled_row.trial_id));
            continue;
        end
        trial = trials{scheduled_row.global_trial_index};
        pair = run_pair_local(trial, fixture, baseline_layers, ...
            candidate_layers, char(scheduled_row.pair_order));
        row = raw_template_local();
        row.schedule_row_id = scheduled_row.schedule_row_id;
        row.schedule_row_hash = scheduled_row.schedule_row_hash;
        row.comparison_id = comparison_id;
        row.baseline_canonical_mode_id = ...
            raw_registry.baseline_canonical_mode_id(comparison_index);
        row.candidate_canonical_mode_id = ...
            raw_registry.candidate_canonical_mode_id(comparison_index);
        row.enabled_layer_set_hash = ...
            raw_registry.enabled_layer_set_hash(comparison_index);
        row.precedence_hash = ...
            raw_registry.precedence_hash(comparison_index);
        row.fixed_measurement_hash = ...
            scheduled_row.fixed_measurement_hash;
        row.global_trial_index = scheduled_row.global_trial_index;
        row.trial_id = scheduled_row.trial_id;
        row.repeat_index = scheduled_row.repeat_index;
        row.pair_order = scheduled_row.pair_order;
        row.time_a_sec = pair.time_a_sec;
        row.time_b_sec = pair.time_b_sec;
        row.paired_difference_sec = pair.time_a_sec - pair.time_b_sec;
        row.output_match = pair.output_match;
        row.cache_hit_count = pair.candidate.cache_hit_count;
        row.cache_miss_count = pair.candidate.cache_miss_count;
        row.physical_producer_call_count = ...
            pair.candidate.physical_producer_call_count;
        row.entry_count = pair.candidate.entry_count;
        row.bytes_current = pair.candidate.bytes_current;
        row.bytes_peak = pair.candidate.bytes_peak;
        row.key_collision_count = pair.candidate.key_collision_count;
        row.truth_leakage_count = pair.candidate.truth_leakage_count;
        row.pair_contiguous_complete = true;
        rows(schedule_index) = row;
        checkpoint = struct('schema_version', ...
            'STAGE8_K2_TECS_SCREENING_CHECKPOINT_V1', ...
            'identity',expected,'row',row,'unit_complete',true, ...
            'pair_contiguous_complete',true);
        atomic_checkpoint_local(checkpoint_path, checkpoint);
        fprintf(['TECS PASS E RUN %d/%d %s %s d=%.9g ', ...
            'hit=%d miss=%d\n'], schedule_index, height(schedule), ...
            char(row.trial_id), char(row.pair_order), ...
            row.paired_difference_sec, row.cache_hit_count, ...
            row.cache_miss_count);
        if ~row.output_match || row.key_collision_count ~= 0 || ...
                row.truth_leakage_count ~= 0
            error('stage8_k2_tecs_run_screening:TimedCorrectness', ...
                'A timed pair violated the frozen correctness contract.');
        end
    end
end
raw = struct2table(rows);
assert(all(raw.output_match) && ...
    all(raw.pair_contiguous_complete) && ...
    sum(raw.key_collision_count) == 0 && ...
    sum(raw.truth_leakage_count) == 0);
[summary, resolution] = summarize_local(raw, view_registry);
[proof, selected] = select_candidate_local(summary, resolution, ...
    mode_registry, alias_registry, view_registry, runtime_root);
stage8_k2_tecs_atomic_writetable(raw, paths.raw);
stage8_k2_tecs_atomic_writetable(summary, paths.summary);
stage8_k2_tecs_atomic_write_json(paths.proof, proof);
output = struct( ...
    'schema_version','STAGE8_K2_TECS_PASS_E_MANIFEST_V1', ...
    'design_freeze_hash',fixture.design.freeze_payload_hash, ...
    'component_freeze_hash',fixture.component.freeze_payload_hash, ...
    'timing_freeze_hash',timing.freeze_payload_hash, ...
    'timing_protocol_hash',protocol.timing_protocol_hash, ...
    'screening_schedule_hash',timing.screening_schedule_hash, ...
    'screening_comparison_set_hash', ...
        timing.screening_comparison_set_hash, ...
    'raw_sample_count',height(raw), ...
    'raw_comparison_count',height(raw_registry), ...
    'comparison_view_count',height(view_registry), ...
    'AB_count',nnz(raw.pair_order == "AB"), ...
    'BA_count',nnz(raw.pair_order == "BA"), ...
    'screening_resolution_sec',resolution, ...
    'screening_status',proof.screening_status, ...
    'recommended_runtime_mode_after_screening', ...
        proof.recommended_runtime_mode_after_screening, ...
    'final_measurement_candidate_alias_id', ...
        proof.final_measurement_candidate_alias_id, ...
    'final_measurement_candidate_canonical_mode_id', ...
        proof.final_measurement_candidate_canonical_mode_id, ...
    'raw_hash',stage8_k2_tecs_sha256( ...
        'TECS_SCREENING_RAW_V1',table2struct(raw)), ...
    'summary_hash',stage8_k2_tecs_sha256( ...
        'TECS_SCREENING_SUMMARY_V1',table2struct(summary)), ...
    'selection_proof_hash',proof.selection_proof_hash, ...
    'bytes_peak',max(raw.bytes_peak), ...
    'key_collision_count',sum(raw.key_collision_count), ...
    'truth_leakage_count',sum(raw.truth_leakage_count), ...
    'process_snapshot_file_sha256', ...
        stage8_k2_tecs_sha256_file(paths.process), ...
    'status','PASS_E_SCREENING_COMPLETE');
output.raw_file_sha256 = stage8_k2_tecs_sha256_file(paths.raw);
output.summary_file_sha256 = stage8_k2_tecs_sha256_file(paths.summary);
output.manifest_payload_hash = stage8_k2_tecs_sha256( ...
    'TECS_PASS_E_MANIFEST_V1', output);
stage8_k2_tecs_atomic_write_json(paths.manifest, output);
fprintf(['TECS PASS E COMPLETE candidate=%s alias=%s ', ...
    'status=%s resolution=%.9g\n'], ...
    selected.candidate_canonical_mode_id, selected.alias, ...
    proof.screening_status, resolution);
end
function pair = run_pair_local(trial, fixture, baseline_layers, ...
    candidate_layers, order)
if strcmp(order, 'AB')
    a = stage8_k2_tecs_run_root( ...
        trial, fixture.context, fixture, baseline_layers);
    b = stage8_k2_tecs_run_root( ...
        trial, fixture.context, fixture, candidate_layers);
else
    b = stage8_k2_tecs_run_root( ...
        trial, fixture.context, fixture, candidate_layers);
    a = stage8_k2_tecs_run_root( ...
        trial, fixture.context, fixture, baseline_layers);
end
output_match = a.fit_valid == b.fit_valid && ...
    strcmp(a.selected_source, b.selected_source) && ...
    strcmp(a.selected_start_id, b.selected_start_id) && ...
    a.logical_score_call_count == b.logical_score_call_count && ...
    a.logical_svd_call_count == b.logical_svd_call_count;
if isempty(baseline_layers) && isempty(candidate_layers)
    output_match = output_match && ...
        strcmp(a.result_checksum_hash, b.result_checksum_hash);
end
pair = struct('time_a_sec',a.elapsed_sec,'time_b_sec',b.elapsed_sec, ...
    'baseline',a,'candidate',b,'output_match',output_match);
end

function formal_warmup_local(trials, fixture, warmup, ...
    baseline_layers, candidate_layers)
fprintf('TECS FORMAL WARMUP START rows=%d\n', height(warmup));
for index = 1:height(warmup)
    trial = trials{warmup.global_trial_index(index)};
    run_pair_local(trial, fixture, baseline_layers, candidate_layers, 'AB');
    run_pair_local(trial, fixture, baseline_layers, candidate_layers, 'BA');
end
fprintf('TECS FORMAL WARMUP COMPLETE rows=%d\n', height(warmup));
end

function layers = layers_for_mode_local(registry, mode_id)
match = registry.candidate_canonical_mode_id == string(mode_id);
assert(nnz(match) == 1);
value = jsondecode(char(registry.ordered_enabled_layer_set(match)));
if isempty(value)
    layers = cell(0, 1);
elseif ischar(value)
    layers = {value};
elseif isstring(value)
    layers = cellstr(value(:));
elseif iscell(value)
    layers = reshape(cellstr(string(value)), [], 1);
else
    error('stage8_k2_tecs_run_screening:LayerSet', ...
        'The frozen mode layer-set encoding is unsupported.');
end
end

function [summary, resolution] = summarize_local(raw, views)
noop = views.comparison_kind == "NOOP_CONTROL";
noop_raw = raw(raw.comparison_id == views.comparison_id(noop), :);
trial_ids = unique(noop_raw.trial_id, 'stable');
e_median = 0;
for index = 1:numel(trial_ids)
    e_median = e_median + median(noop_raw.paired_difference_sec( ...
        noop_raw.trial_id == trial_ids(index)));
end
round_total = zeros(6, 1);
for repeat = 1:6
    round_total(repeat) = sum(noop_raw.paired_difference_sec( ...
        noop_raw.repeat_index == repeat));
end
resolution = max(abs([e_median; round_total]));

rows = repmat(summary_template_local(), 0, 1);
for view_index = 1:height(views)
    view = views(view_index, :);
    current = raw(raw.comparison_id == view.comparison_id, :);
    ids = unique(current.trial_id, 'stable');
    trial_points = zeros(numel(ids), 1);
    trial_baselines = zeros(numel(ids), 1);
    for trial_index = 1:numel(ids)
        samples = current(current.trial_id == ids(trial_index), :);
        row = summary_template_local();
        row.aggregation_level = "TRIAL";
        row.row_key = view.comparison_view_id + "|" + ids(trial_index);
        row.comparison_view_id = view.comparison_view_id;
        row.comparison_id = view.comparison_id;
        row.comparison_kind = view.comparison_kind;
        row.variant_alias_id = view.variant_alias_id;
        row.baseline_canonical_mode_id = ...
            view.baseline_canonical_mode_id;
        row.candidate_canonical_mode_id = ...
            view.candidate_canonical_mode_id;
        row.enabled_layer_set_hash = view.enabled_layer_set_hash;
        row.predecessor_canonical_mode_id = ...
            view.predecessor_canonical_mode_id;
        row.source_full_canonical_mode_id = ...
            view.source_full_canonical_mode_id;
        row.fixed_measurement_hash = samples.fixed_measurement_hash(1);
        row.trial_id = ids(trial_index);
        row.repeat_count = height(samples);
        row.AB_count = nnz(samples.pair_order == "AB");
        row.BA_count = nnz(samples.pair_order == "BA");
        row.paired_median_sec = median(samples.paired_difference_sec);
        row.paired_min_sec = min(samples.paired_difference_sec);
        row.paired_max_sec = max(samples.paired_difference_sec);
        row.bytes_peak = max(samples.bytes_peak);
        row.physical_call_reduction = -median( ...
            samples.physical_producer_call_count);
        row.screening_resolution_sec = resolution;
        trial_points(trial_index) = row.paired_median_sec;
        trial_baselines(trial_index) = median(samples.time_a_sec);
        rows(end + 1, 1) = row; %#ok<AGROW>
    end
    identities = unique(current.fixed_measurement_hash, 'stable');
    for identity_index = 1:numel(identities)
        member = current.fixed_measurement_hash == identities(identity_index);
        member_trials = unique(current.trial_id(member), 'stable');
        point = 0;
        for trial_index = 1:numel(member_trials)
            point = point + median(current.paired_difference_sec( ...
                current.trial_id == member_trials(trial_index)));
        end
        row = summary_template_local();
        row.aggregation_level = "IDENTITY";
        row.row_key = view.comparison_view_id + "|" + identities(identity_index);
        row.comparison_view_id = view.comparison_view_id;
        row.comparison_id = view.comparison_id;
        row.comparison_kind = view.comparison_kind;
        row.variant_alias_id = view.variant_alias_id;
        row.baseline_canonical_mode_id = view.baseline_canonical_mode_id;
        row.candidate_canonical_mode_id = view.candidate_canonical_mode_id;
        row.enabled_layer_set_hash = view.enabled_layer_set_hash;
        row.predecessor_canonical_mode_id = view.predecessor_canonical_mode_id;
        row.source_full_canonical_mode_id = view.source_full_canonical_mode_id;
        row.fixed_measurement_hash = identities(identity_index);
        row.repeat_count = 6;
        row.AB_count = 3 * numel(member_trials);
        row.BA_count = 3 * numel(member_trials);
        row.identity_point_sec = point;
        row.bytes_peak = max(current.bytes_peak(member));
        row.screening_resolution_sec = resolution;
        rows(end + 1, 1) = row; %#ok<AGROW>
    end
    row = summary_template_local();
    row.aggregation_level = "OVERALL";
    row.row_key = view.comparison_view_id;
    row.comparison_view_id = view.comparison_view_id;
    row.comparison_id = view.comparison_id;
    row.comparison_kind = view.comparison_kind;
    row.variant_alias_id = view.variant_alias_id;
    row.baseline_canonical_mode_id = view.baseline_canonical_mode_id;
    row.candidate_canonical_mode_id = view.candidate_canonical_mode_id;
    row.enabled_layer_set_hash = view.enabled_layer_set_hash;
    row.predecessor_canonical_mode_id = view.predecessor_canonical_mode_id;
    row.source_full_canonical_mode_id = view.source_full_canonical_mode_id;
    row.repeat_count = 6;
    row.AB_count = 3 * numel(ids);
    row.BA_count = 3 * numel(ids);
    row.overall_point_sec = sum(trial_points);
    row.total_point_sec = row.overall_point_sec;
    if view.comparison_kind == "MARGINAL" || ...
            view.comparison_kind == "DIRECT_LOO"
        row.marginal_point_sec = row.overall_point_sec;
    end
    row.baseline_runtime_sec = sum(trial_baselines);
    row.runtime_reduction_pct = 100 * row.overall_point_sec / ...
        row.baseline_runtime_sec;
    row.bytes_peak = max(current.bytes_peak);
    row.physical_call_reduction = -median( ...
        current.physical_producer_call_count);
    row.screening_resolution_sec = resolution;
    rows(end + 1, 1) = row; %#ok<AGROW>
end
summary = struct2table(rows);
end

function [proof, selected] = select_candidate_local(summary, resolution, ...
    modes, aliases, views, runtime_root)
correctness = jsondecode(fileread(fullfile(runtime_root, 'pass_c_d', ...
    'correctness_manifest.json')));
total_view = views.comparison_kind == "TOTAL" & ...
    views.final_candidate_selection_eligible;
assert(nnz(total_view) == 1 && correctness.M1_correctness_pass_count == 72);
view_id = views.comparison_view_id(total_view);
overall = summary.aggregation_level == "OVERALL" & ...
    summary.comparison_view_id == view_id;
identity = summary.aggregation_level == "IDENTITY" & ...
    summary.comparison_view_id == view_id;
point = summary.overall_point_sec(overall);
identity_points = summary.identity_point_sec(identity);
mode_id = summary.candidate_canonical_mode_id(overall);
mode = modes(modes.candidate_canonical_mode_id == mode_id, :);
representative = aliases(aliases.candidate_canonical_mode_id == mode_id & ...
    aliases.variant_alias_id == mode.representative_alias_id, :);
positive = point > 0 && all(identity_points >= 0) && ...
    summary.bytes_peak(overall) <= 536870912;
selected = struct('candidate_canonical_mode_id',char(mode_id), ...
    'alias',char(representative.variant_alias_id));
if positive
    status = 'POSITIVE_CACHE_ON_CANDIDATE_SELECTED';
    recommended = char(mode_id);
    pool = 'POSITIVE_ELIGIBLE_POOL';
else
    status = 'MEASURED_SAVING_NONPOSITIVE_SCREENING';
    m0 = aliases(aliases.variant_alias_id == "M0", :);
    recommended = char(m0.candidate_canonical_mode_id);
    pool = 'FALLBACK_CACHE_ON_POOL';
end
proof = struct( ...
    'schema_version','STAGE8_K2_TECS_SCREENING_SELECTION_PROOF_V1', ...
    'selection_pool',pool,'D_max_sec',point, ...
    'screening_resolution_sec',resolution, ...
    'timing_tie_set',{cellstr(mode_id)}, ...
    'select_after_layer_count',{cellstr(mode_id)}, ...
    'select_after_bytes_peak',{cellstr(mode_id)}, ...
    'selected_by_mode_id_lexical_tie_break',char(mode_id), ...
    'both_identity_nonnegative',all(identity_points >= 0), ...
    'overall_positive',point > 0, ...
    'memory_bound_pass',summary.bytes_peak(overall) <= 536870912, ...
    'screening_status',status, ...
    'recommended_runtime_mode_after_screening',recommended, ...
    'final_measurement_candidate_alias_id',selected.alias, ...
    'final_measurement_candidate_canonical_mode_id', ...
        selected.candidate_canonical_mode_id);
proof.selection_proof_hash = stage8_k2_tecs_sha256( ...
    'TECS_SCREENING_SELECTION_PROOF_V1', proof);
end

function identity = checkpoint_identity_local(fixture, timing, protocol, ...
    scheduled, comparison)
identity = struct( ...
    'checkpoint_unit_kind','SCREENING_PAIR','pass','PASS_E', ...
    'cache_setting','PAIRED_OFF_ON','cache_layer','NOT_APPLICABLE', ...
    'variant_alias_id','RAW_CANONICAL_COMPARISON', ...
    'comparison_id',char(scheduled.comparison_id), ...
    'comparison_kind',char(comparison.primary_comparison_kind), ...
    'baseline_canonical_mode_id', ...
        char(scheduled.baseline_canonical_mode_id), ...
    'candidate_canonical_mode_id', ...
        char(scheduled.candidate_canonical_mode_id), ...
    'enabled_layer_set_hash',char(scheduled.enabled_layer_set_hash), ...
    'precedence_hash',char(scheduled.precedence_hash), ...
    'fixed_measurement_hash',char(scheduled.fixed_measurement_hash), ...
    'trial_id',char(scheduled.trial_id), ...
    'repeat_index',double(scheduled.repeat_index), ...
    'pair_order',char(scheduled.pair_order), ...
    'schedule_row_id',double(scheduled.schedule_row_id), ...
    'schedule_row_hash',char(scheduled.schedule_row_hash), ...
    'lifecycle_setting','WARM','identity_batch_id','NOT_APPLICABLE', ...
    'batch_repeat_index','NOT_APPLICABLE', ...
    'lifecycle_operation','NOT_APPLICABLE', ...
    'operation_repeat_index','NOT_APPLICABLE', ...
    'run_id',fixture.design.run_id, ...
    'baseline_commit',fixture.design.baseline_commit, ...
    'initial_execution_start_commit', ...
        fixture.design.initial_execution_start_commit, ...
    'stage_commit_ledger_hash', ...
        timing.stage_commit_ledger_hash_at_timing_freeze, ...
    'integration_code_commit',timing.integration_code_commit, ...
    'prompt_hash',fixture.design.execution_prompt_hash, ...
    'baseline_snapshot_hash',fixture.design.baseline_snapshot_hash, ...
    'cache_code_hash',timing.cache_code_hash, ...
    'trial_registry_hash',fixture.design.trial_registry_hash, ...
    'key_schema_hash',fixture.design.key_schema_hash, ...
    'semantic_output_projection_hash', ...
        fixture.design.semantic_output_projection_hash, ...
    'hook_allowlist_hash',fixture.design.hook_allowlist_hash, ...
    'timing_protocol_hash',protocol.timing_protocol_hash, ...
    'phase_schedule_hash',timing.screening_schedule_hash, ...
    'final_measurement_candidate_hash','NOT_FROZEN_PASS_E', ...
    'design_freeze_hash',fixture.design.freeze_payload_hash, ...
    'component_freeze_hash',fixture.component.freeze_payload_hash, ...
    'timing_freeze_hash',timing.freeze_payload_hash, ...
    'final_candidate_freeze_hash','NOT_CLOSED', ...
    'MATLAB_release',version('-release'),'singleCompThread',true, ...
    'cache_reset_lifecycle_rule', ...
        'PRISTINE_SESSION_BEFORE_EACH_PAIR_EDGE');
end

function process = process_snapshot_local(pass_id)
[status, text] = system([ ...
    'powershell -NoProfile -Command "', ...
    '(Get-Process -Name MATLAB -ErrorAction SilentlyContinue | ', ...
    'Measure-Object).Count"']);
count = str2double(strtrim(text));
if status ~= 0 || ~isfinite(count), count = NaN; end
process = struct('schema_version','STAGE8_K2_TECS_PROCESS_SNAPSHOT_V1', ...
    'pass',pass_id,'active_MATLAB_process_count',count, ...
    'formal_MATLAB_process_limit',1,'parallel_pool_enabled',false, ...
    'singleCompThread',true,'captured_at_utc', ...
        char(datetime('now','TimeZone','UTC', ...
        'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z''')));
end

function row = raw_template_local()
row = struct('schema_version',"STAGE8_K2_TECS_SCREENING_RAW_V1", ...
    'schedule_row_id',0,'schedule_row_hash',"", ...
    'comparison_id',"",'baseline_canonical_mode_id',"", ...
    'candidate_canonical_mode_id',"",'enabled_layer_set_hash',"", ...
    'precedence_hash',"",'fixed_measurement_hash',"", ...
    'global_trial_index',0,'trial_id',"",'repeat_index',0, ...
    'pair_order',"",'time_a_sec',NaN,'time_b_sec',NaN, ...
    'paired_difference_sec',NaN,'output_match',false, ...
    'cache_hit_count',0,'cache_miss_count',0, ...
    'physical_producer_call_count',0,'entry_count',0, ...
    'bytes_current',0,'bytes_peak',0,'key_collision_count',0, ...
    'truth_leakage_count',0,'pair_contiguous_complete',false);
end

function row = summary_template_local()
row = struct('schema_version',"STAGE8_K2_TECS_SCREENING_V1", ...
    'aggregation_level',"",'row_key',"",'comparison_view_id',"", ...
    'variant_alias_id',"",'candidate_canonical_mode_id',"", ...
    'baseline_canonical_mode_id',"",'enabled_layer_set_hash',"", ...
    'alias_of_canonical_mode_id',"",'alias_of_comparison_id',"", ...
    'source_full_canonical_mode_id',"",'comparison_id',"", ...
    'comparison_kind',"",'predecessor_canonical_mode_id',"", ...
    'fixed_measurement_hash',"",'trial_id',"",'repeat_count',0, ...
    'AB_count',0,'BA_count',0,'paired_median_sec',NaN, ...
    'paired_min_sec',NaN,'paired_max_sec',NaN, ...
    'identity_point_sec',NaN,'overall_point_sec',NaN, ...
    'total_point_sec',NaN,'marginal_point_sec',NaN, ...
    'baseline_runtime_sec',NaN,'runtime_reduction_pct',NaN, ...
    'screening_resolution_sec',NaN,'bytes_peak',NaN, ...
    'physical_call_reduction',NaN,'final_candidate_eligible',false, ...
    'screening_status',"MEASURED_VIEW", ...
    'recommended_runtime_mode_after_screening',"", ...
    'final_measurement_candidate_alias_id',"", ...
    'final_measurement_candidate_canonical_mode_id',"");
end

function atomic_checkpoint_local(path_now, checkpoint)
temporary = [path_now, '.tmp'];
save(temporary, 'checkpoint', '-v7.3');
movefile(temporary, path_now, 'f');
end
