function [manifest, digest] = stage8_k2_tecs_integration_manifest(repo_dir)
%STAGE8_K2_TECS_INTEGRATION_MANIFEST Hash only the timed integration path.

[component_manifest, component_hash] = ...
    stage8_k2_tecs_code_manifest(repo_dir, 'COMPONENT_CORE');
hook_relative = fullfile('tools', 'stage8_k2_tangent_canonical_cache', ...
    'matlab', 'stage8_k2_tcc_get_pair_manifold.m');
hook_path = fullfile(repo_dir, hook_relative);
hook_hash = stage8_k2_tecs_sha256_file(hook_path);
hash_payload = struct( ...
    'schema_version', 'STAGE8_K2_TECS_INTEGRATION_MANIFEST_V1', ...
    'component_core_hash', component_hash, ...
    'component_core_manifest', table2struct(component_manifest), ...
    'hook_path', strrep(hook_relative, '\', '/'), ...
    'hook_sha256', hook_hash, ...
    'dispatch_mode', 'TECS_EXACT_STACK', ...
    'production_default_cache_setting', 'CACHE_OFF');
digest = stage8_k2_tecs_sha256( ...
    'TECS_INTEGRATION_IMPLEMENTATION_V1', hash_payload);
manifest = hash_payload;
manifest.integration_implementation_hash = digest;
end
