function [fixtures, manifest] = stage8_k2_tecs_build_c1_replay_fixture( ...
    repo_dir, runtime_root)
%STAGE8_K2_TECS_BUILD_C1_REPLAY_FIXTURE Reconstruct paired C1 hook events.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
design = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'design_freeze.json')));
semantic_saved = load(fullfile(runtime_root, 'baseline', ...
    'cache_off_semantic_outputs.mat'), 'semantic_snapshot');
semantic = semantic_saved.semantic_snapshot;
pass_a_saved = load(fullfile(runtime_root, 'pass_a', ...
    'pass_a_event_stream.mat'), 'output');
pass_a = pass_a_saved.output;
fixtures = repmat(struct('identity_index',0, ...
    'fixed_measurement_hash','', 'model',struct(), 'artifact',struct(), ...
    'events',table(), 'event_stream_hash',''), 2, 1);
identity_hashes = strings(2, 1);
event_counts = zeros(2, 1);
for identity_index = 1:2
    identity = char(string( ...
        design.measurement_identity_hashes{identity_index}));
    capture = load(fullfile(runtime_root, 'baseline_capture', ...
        sprintf('pass_a_identity_%02d.mat', identity_index)));
    [model, dictionary] = stage8_k2_tecs_select_capture_identity( ...
        capture.value, identity);
    artifact = stage8_k2_tecs_promote_c1_artifact(dictionary);
    assert(strcmp(model.fixed_measurement_hash, identity) && ...
        strcmp(artifact.fixed_measurement_hash, identity), ...
        'stage8_k2_tecs_build_c1_replay_fixture:Identity', ...
        'Frozen model and artifact identity differ from DESIGN_FREEZE.');
    rows = repmat(event_template_local(), 0, 1);
    global_pair_index = 0;
    for trial_index = 1:semantic.trial_count
        row = semantic.rows{trial_index};
        if ~strcmp(char(string(row.fixed_measurement_hash)), identity)
            continue;
        end
        diagnostics = row.semantic_projection.diagnostics;
        rho = double(diagnostics.evaluated_rho_deg(:));
        center = double(diagnostics.K1_center_deg(:).');
        direction = double(diagnostics.direction_hat(:).');
        for pair_call_index = 1:numel(rho)
            pair = [center - rho(pair_call_index) * direction / 2; ...
                center + rho(pair_call_index) * direction / 2];
            pair = sortrows(pair, [2, 1]);
            global_pair_index = global_pair_index + 1;
            current = event_template_local();
            current.fixed_measurement_hash = string(identity);
            current.trial_id = string(row.trial_id);
            current.global_trial_index = trial_index;
            current.pair_call_index = pair_call_index;
            current.global_pair_index = global_pair_index;
            current.angle_1_az_deg = pair(1, 1);
            current.angle_1_el_deg = pair(1, 2);
            current.angle_2_az_deg = pair(2, 1);
            current.angle_2_el_deg = pair(2, 2);
            current.column_1_key_hash = string(c1_key_hash_local( ...
                identity, pair(1, :)));
            current.column_2_key_hash = string(c1_key_hash_local( ...
                identity, pair(2, :)));
            rows(end + 1, 1) = current; %#ok<AGROW>
        end
    end
    events = struct2table(rows);
    expected = pass_a.events(pass_a.events.cache_layer == "C1" & ...
        pass_a.events.fixed_measurement_hash == string(identity), :);
    reconstructed = reshape([events.column_1_key_hash.'; ...
        events.column_2_key_hash.'], [], 1);
    assert(numel(reconstructed) == height(expected) && ...
        isequal(reconstructed, expected.complete_key_hash), ...
        'stage8_k2_tecs_build_c1_replay_fixture:EventLink', ...
        'Reconstructed C1 pairs do not exactly link to Pass A events.');
    event_hash = stage8_k2_tcc_stable_hash( ...
        'TECS_C1_COMPONENT_REPLAY_PAIRED_EVENT_STREAM_V1', events);
    fixtures(identity_index).identity_index = identity_index;
    fixtures(identity_index).fixed_measurement_hash = identity;
    fixtures(identity_index).model = model;
    fixtures(identity_index).artifact = artifact;
    fixtures(identity_index).events = events;
    fixtures(identity_index).event_stream_hash = event_hash;
    identity_hashes(identity_index) = string(event_hash);
    event_counts(identity_index) = height(events);
end
manifest = struct( ...
    'schema_version','STAGE8_K2_TECS_C1_REPLAY_FIXTURE_V1', ...
    'design_freeze_hash',design.freeze_payload_hash, ...
    'pass_a_event_stream_hash',pass_a.event_stream_hash, ...
    'identity_event_stream_hashes',{cellstr(identity_hashes)}, ...
    'identity_pair_event_counts',event_counts.', ...
    'total_pair_event_count',sum(event_counts), ...
    'total_column_event_count',2 * sum(event_counts), ...
    'truth_fields_present',false, ...
    'status','C1_PASS_A_EVENT_LINK_EXACT');
manifest.fixture_manifest_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_C1_REPLAY_FIXTURE_MANIFEST_V1', manifest);
assert(sum(event_counts) == 2952 && 2 * sum(event_counts) == 5904);
end

function hash = c1_key_hash_local(identity, angle)
key = struct('layer','C1','fixed_measurement_hash',identity, ...
    'angle_IEEE754',angle, ...
    'output_contract','CERTIFIED_CANONICAL_G');
hash = stage8_k2_tecs_sha256('TECS_PASS_A_C1_COMPLETE_KEY', key);
end

function row = event_template_local()
row = struct('fixed_measurement_hash',"",'trial_id',"", ...
    'global_trial_index',0,'pair_call_index',0,'global_pair_index',0, ...
    'angle_1_az_deg',0,'angle_1_el_deg',0, ...
    'angle_2_az_deg',0,'angle_2_el_deg',0, ...
    'column_1_key_hash',"",'column_2_key_hash',"");
end
