function [rows,unattributed,reconciliation,minimum,accounting] = ...
    stage8_k2_tecs_reconcile_stage_timing(raw,root)
%STAGE8_K2_TECS_RECONCILE_STAGE_TIMING Reconcile disjoint stage timing.
%
% K2_HELPER_K1 is instrumented by an outer helper timer while its internal
% start/refinement/final/selection timers reuse the same stage ID.  The
% audit accumulator therefore reports a self-nested sum rather than one
% disjoint inclusive interval.  Retain that value as an overlap diagnostic,
% while its real wall time remains accounted inside K2_CORE_LITE.

ids=string({raw.stage_id});values=double([raw.inclusive_runtime_sec]);
assert(numel(unique(ids))==numel(ids) && isfinite(root) && root>=0, ...
    'stage8_k2_tecs_reconcile_stage_timing:Input', ...
    'Stage IDs must be unique and root runtime must be finite/nonnegative.');
time=containers.Map('KeyType','char','ValueType','double');
for index=1:numel(ids),time(char(ids(index)))=values(index);end
time('ROOT_TANGENT_PROFILE_SAFE')=double(root);
edges=edges_local();overlap_ids="K2_HELPER_K1";
all_ids=unique([string(keys(time)),edges(:,1).',edges(:,2).'],'stable');
all_ids=all_ids(:);inclusive=zeros(numel(all_ids),1);
exclusive=zeros(numel(all_ids),1);overlap=ismember(all_ids,overlap_ids);
for index=1:numel(all_ids)
    id=char(all_ids(index));if isKey(time,id),inclusive(index)=time(id);end
    if overlap(index),exclusive(index)=NaN;continue;end
    children=edges(edges(:,1)==all_ids(index),2);child_sum=0;
    for child_index=1:numel(children)
        child=char(children(child_index));if isKey(time,child), ...
                child_sum=child_sum+time(child);end
    end
    exclusive(index)=inclusive(index)-child_sum;
end
root_index=find(all_ids=="ROOT_TANGENT_PROFILE_SAFE",1);
unattributed=exclusive(root_index);
keep=(1:numel(all_ids)).'~=root_index & ...
    (inclusive~=0|exclusive~=0|overlap);
included=keep&~overlap;roles=repmat("PRIMARY_DISJOINT",numel(all_ids),1);
roles(overlap)="OVERLAP_DIAGNOSTIC";
rows=table(all_ids(keep),inclusive(keep),exclusive(keep),roles(keep), ...
    included(keep),'VariableNames',{'stage_id','inclusive_runtime_sec', ...
    'exclusive_runtime_sec','accounting_role','included_in_reconciliation'});
reconciliation=root-(sum(exclusive(included))+unattributed);
minimum=min([exclusive(included);unattributed]);
accounting=struct('overlap_diagnostic_stage_ids',{{'K2_HELPER_K1'}}, ...
    'overlap_diagnostic_stage_count',nnz(overlap&inclusive~=0), ...
    'overlap_accounting_status', ...
    'SELF_NESTED_SAME_ID_RETAINED_AS_OVERLAP_DIAGNOSTIC', ...
    'primary_disjoint_stage_count',nnz(included));
end

function edges=edges_local()
edges=["ROOT_TANGENT_PROFILE_SAFE","K1_PUBLIC"; ...
"ROOT_TANGENT_PROFILE_SAFE","K2_PUBLIC";"ROOT_TANGENT_PROFILE_SAFE","TAIL_FULL_DATA"; ...
"ROOT_TANGENT_PROFILE_SAFE","CENTER_MANIFOLD_DERIVATIVES"; ...
"ROOT_TANGENT_PROFILE_SAFE","PROJECTED_DIRECTION";"ROOT_TANGENT_PROFILE_SAFE","T4_PROFILE"; ...
"ROOT_TANGENT_PROFILE_SAFE","FINAL_SAFE_SELECTOR";"K1_PUBLIC","K1_CONTEXT"; ...
"K1_PUBLIC","K1_CORE_LITE";"K1_CONTEXT","K1_FULL_DATA"; ...
"K1_CONTEXT","K1_INITIALIZATION_TOTAL";"K1_INITIALIZATION_TOTAL","K1_INIT_CONVENTIONAL"; ...
"K1_INITIALIZATION_TOTAL","K1_INIT_GROUP_PREPARE"; ...
"K1_INITIALIZATION_TOTAL","K1_INIT_GROUP_Q1";"K1_INITIALIZATION_TOTAL","K1_INIT_GROUP_Q2"; ...
"K1_CORE_LITE","K1_FIXED_FIT";"K1_CORE_LITE","K1_CONTINUOUS"; ...
"K1_CORE_LITE","K1_SELECTION";"K1_FIXED_FIT","K1_FIXED_START_BUILD"; ...
"K1_FIXED_FIT","K1_FIXED_REGISTERED_REFINEMENT"; ...
"K1_FIXED_FIT","K1_FIXED_FINAL_CERTIFICATION"; ...
"K1_FIXED_FIT","K1_FIXED_REGISTERED_SELECTION";"K2_PUBLIC","K2_CONTEXT"; ...
"K2_PUBLIC","K2_CORE_LITE";"K2_CONTEXT","K2_FULL_DATA"; ...
"K2_CONTEXT","K2_INITIALIZATION_TOTAL";"K2_INITIALIZATION_TOTAL","K2_INIT_CONVENTIONAL"; ...
"K2_INITIALIZATION_TOTAL","K2_INIT_GROUP_PREPARE"; ...
"K2_INITIALIZATION_TOTAL","K2_INIT_GROUP_Q1";"K2_INITIALIZATION_TOTAL","K2_INIT_GROUP_Q2"; ...
"K2_CORE_LITE","K2_START_BUILD";"K2_CORE_LITE","K2_REGISTERED_REFINEMENT"; ...
"K2_CORE_LITE","K2_FINAL_CERTIFICATION";"K2_CORE_LITE","K2_SELECTION"; ...
"K2_START_BUILD","K2_NESTED_ANCHOR"];
end
