function result = stage8_k2_tecs_run_component_replay(repo_dir, runtime_root)
%STAGE8_K2_TECS_RUN_COMPONENT_REPLAY Paired C1 component batch benchmark.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
pass_dir = fullfile(runtime_root, 'pass_b');
checkpoint_dir = fullfile(pass_dir, 'component_checkpoints');
if ~isfolder(checkpoint_dir), mkdir(checkpoint_dir); end
paths = struct( ...
    'raw',fullfile(pass_dir, 'component_raw_samples.csv'), ...
    'summary',fullfile(pass_dir, 'component_summary.csv'), ...
    'disposition',fullfile(pass_dir, 'component_result_disposition.csv'), ...
    'manifest',fullfile(pass_dir, 'component_replay_manifest.json'));
names = fieldnames(paths);
for index = 1:numel(names)
    if isfile(paths.(names{index}))
        error('stage8_k2_tecs_run_component_replay:ImmutableExists', ...
            'Component replay target exists: %s', paths.(names{index}));
    end
end
[design, freeze, schedule] = verify_freeze_local(repo_dir, runtime_root);
[fixtures, fixture_manifest] = stage8_k2_tecs_build_c1_replay_fixture( ...
    repo_dir, runtime_root);
assert(strcmp(fixture_manifest.fixture_manifest_hash, ...
    freeze.C1_paired_fixture_manifest_hash));
rows = repmat(raw_template_local(), height(schedule), 1);
for schedule_index = 1:height(schedule)
    schedule_row = schedule(schedule_index, :);
    identity_index = schedule_row.identity_index;
    fixture = fixtures(identity_index);
    checkpoint_path = fullfile(checkpoint_dir, sprintf( ...
        '%03d_C1_identity_%02d_%s_%02d.mat', ...
        schedule_row.schedule_row_id, identity_index, ...
        lower(char(schedule_row.schedule_phase)), ...
        schedule_row.batch_repeat_index));
    expected = checkpoint_expected_local(design, freeze, schedule_row);
    if isfile(checkpoint_path)
        saved = load(checkpoint_path, 'checkpoint');
        checkpoint = saved.checkpoint;
        stage8_k2_tecs_validate_checkpoint_identity(checkpoint, expected);
        assert(strcmp(checkpoint.payload_hash, ...
            stage8_k2_tcc_stable_hash( ...
            'TECS_COMPONENT_CHECKPOINT_PAYLOAD_V1', checkpoint.payload)), ...
            'stage8_k2_tecs_run_component_replay:CheckpointPayload', ...
            'A resumed component checkpoint payload hash is invalid.');
        rows(schedule_index) = checkpoint.payload.raw_row;
        fprintf('TECS COMPONENT RESUME %d/%d\n', ...
            schedule_index, height(schedule));
        continue;
    end
    angles = [fixture.events.angle_1_az_deg, ...
        fixture.events.angle_1_el_deg, ...
        fixture.events.angle_2_az_deg, ...
        fixture.events.angle_2_el_deg];
    config = struct('run_id',design.run_id, ...
        'baseline_commit',design.baseline_commit, ...
        'key_schema_hash',design.key_schema_hash, ...
        'scope','MEASUREMENT_IDENTITY_SESSION', ...
        'fixed_measurement_hash',fixture.fixed_measurement_hash, ...
        'enabled_layers',{{'C1'}}, ...
        'artifacts',struct('C1',fixture.artifact));
    session = stage8_k2_tecs_cache_session(config);
    provider = stage8_k2_tecs_build_provider(session, ...
        struct('per_call_timing_enabled',false));
    if schedule_row.pair_order == "AB"
        session.clear_counters();
        [time_off, checksum_off] = time_off_local(angles, fixture.model);
        session.clear_counters();
        [time_on, checksum_on] = time_on_local( ...
            angles, fixture.model, provider);
        on_snapshot = session.snapshot();
    else
        session.clear_counters();
        [time_on, checksum_on] = time_on_local( ...
            angles, fixture.model, provider);
        on_snapshot = session.snapshot();
        session.clear_counters();
        [time_off, checksum_off] = time_off_local(angles, fixture.model);
    end
    assert(isequaln(checksum_off, checksum_on), ...
        'stage8_k2_tecs_run_component_replay:OutputMismatch', ...
        'Component replay checksum differs between adjacent edges.');
    expected_columns = 2 * height(fixture.events);
    assert(on_snapshot.hit_count == 0 && ...
        on_snapshot.miss_count == expected_columns && ...
        on_snapshot.physical_producer_call_count == height(fixture.events) && ...
        on_snapshot.collision_count == 0 && ...
        on_snapshot.truth_leakage_count == 0 && ...
        on_snapshot.bytes_peak <= 536870912, ...
        'stage8_k2_tecs_run_component_replay:CounterContract', ...
        'C1 component counters, purity, or memory bounds are invalid.');
    row = raw_template_local();
    row.schema_version = "STAGE8_K2_TECS_COMPONENT_RAW_V1";
    row.schedule_row_id = schedule_row.schedule_row_id;
    row.schedule_row_hash = schedule_row.schedule_row_hash;
    row.cache_layer = "C1";
    row.fixed_measurement_hash = string(fixture.fixed_measurement_hash);
    row.identity_index = identity_index;
    row.identity_batch_id = schedule_row.identity_batch_id;
    row.batch_repeat_index = schedule_row.batch_repeat_index;
    row.pair_order = schedule_row.pair_order;
    row.schedule_phase = schedule_row.schedule_phase;
    row.included_in_statistics = schedule_row.included_in_statistics;
    row.event_pair_count = height(fixture.events);
    row.column_lookup_count = expected_columns;
    row.time_off_sec = time_off;
    row.time_on_sec = time_on;
    row.paired_difference_sec = time_off - time_on;
    row.cache_hit_count = on_snapshot.hit_count;
    row.cache_miss_count = on_snapshot.miss_count;
    row.physical_producer_call_count = ...
        on_snapshot.physical_producer_call_count;
    row.entry_count = on_snapshot.entry_count;
    row.bytes_current = on_snapshot.bytes_current;
    row.bytes_peak = on_snapshot.bytes_peak;
    row.key_collision_count = on_snapshot.collision_count;
    row.truth_leakage_count = on_snapshot.truth_leakage_count;
    row.output_checksum_hash = string(stage8_k2_tecs_sha256( ...
        'TECS_COMPONENT_OUTPUT_CHECKSUM_V1', checksum_on));
    row.pair_contiguous_complete = true;
    rows(schedule_index) = row;
    checkpoint = checkpoint_base_local(design, freeze, schedule_row, row);
    checkpoint.payload_hash = stage8_k2_tcc_stable_hash( ...
        'TECS_COMPONENT_CHECKPOINT_PAYLOAD_V1', checkpoint.payload);
    atomic_checkpoint_local(checkpoint_path, checkpoint);
    delete(session);
    fprintf('TECS COMPONENT %d/%d %s %s d=%.9f\n', ...
        schedule_index, height(schedule), char(row.schedule_phase), ...
        char(row.pair_order), row.paired_difference_sec);
end
raw = struct2table(rows);
assert(all(raw.pair_contiguous_complete) && ...
    nnz(raw.included_in_statistics) == 60 && ...
    nnz(~raw.included_in_statistics) == 10);
summary = summarize_local(raw);
disposition = disposition_local(summary, freeze);
raw_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_COMPONENT_RAW_SAMPLES_V1', raw);
summary_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_COMPONENT_SUMMARY_V1', summary);
disposition_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_COMPONENT_RESULT_DISPOSITION_V1', disposition);
stage8_k2_tecs_atomic_writetable(raw, paths.raw);
stage8_k2_tecs_atomic_writetable(summary, paths.summary);
stage8_k2_tecs_atomic_writetable(disposition, paths.disposition);
manifest = struct( ...
    'schema_version','STAGE8_K2_TECS_COMPONENT_REPLAY_MANIFEST_V1', ...
    'design_freeze_hash',design.freeze_payload_hash, ...
    'component_freeze_hash',freeze.freeze_payload_hash, ...
    'component_prototype_commit',freeze.component_prototype_commit, ...
    'prototype_code_hash',freeze.prototype_code_hash, ...
    'component_protocol_hash',freeze.component_protocol_hash, ...
    'component_schedule_hash',freeze.component_schedule_hash, ...
    'C1_paired_fixture_manifest_hash', ...
    fixture_manifest.fixture_manifest_hash, ...
    'raw_sample_count',height(raw),'warmup_pair_count',10, ...
    'measured_pair_count',60,'measured_AB_count',30, ...
    'measured_BA_count',30,'checkpoint_count',height(raw), ...
    'raw_samples_hash',raw_hash,'summary_hash',summary_hash, ...
    'component_result_disposition_hash',disposition_hash, ...
    'truth_leakage_count',sum(raw.truth_leakage_count), ...
    'key_collision_count',sum(raw.key_collision_count), ...
    'memory_bound_pass',all(raw.bytes_peak <= 536870912), ...
    'status','PASS_B_C1_COMPONENT_REPLAY_COMPLETE');
manifest.raw_samples_file_sha256 = ...
    stage8_k2_tecs_sha256_file(paths.raw);
manifest.summary_file_sha256 = ...
    stage8_k2_tecs_sha256_file(paths.summary);
manifest.disposition_file_sha256 = ...
    stage8_k2_tecs_sha256_file(paths.disposition);
manifest.manifest_payload_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_COMPONENT_REPLAY_MANIFEST_V1', manifest);
stage8_k2_tecs_atomic_write_json(paths.manifest, manifest);
for index = 1:numel(names)
    fileattrib(paths.(names{index}), '-w');
end
checkpoints = dir(fullfile(checkpoint_dir, '*.mat'));
for index = 1:numel(checkpoints)
    fileattrib(fullfile(checkpoints(index).folder, ...
        checkpoints(index).name), '-w');
end
result = struct('raw',raw,'summary',summary, ...
    'disposition',disposition,'manifest',manifest);
fprintf('TECS COMPONENT REPLAY COMPLETE point=%.9f sec\n', ...
    summary.component_point_sec(end));
end

function [design, freeze, schedule] = verify_freeze_local(repo_dir, runtime_root)
design = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'design_freeze.json')));
freeze = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'component_freeze.json')));
assert(strcmp(freeze.parent_freeze_hash, design.freeze_payload_hash) && ...
    strcmp(freeze.status, 'IMMUTABLE_COMPONENT_FREEZE_COMPLETE'));
assert(strcmp(stage8_k2_tecs_sha256_file(fullfile(runtime_root, ...
    'freeze','component_schedule.csv')), ...
    freeze.component_schedule_file_sha256) && ...
    strcmp(stage8_k2_tecs_sha256_file(fullfile(runtime_root, ...
    'freeze','component_protocol.json')), ...
    freeze.component_protocol_file_sha256) && ...
    strcmp(stage8_k2_tecs_sha256_file(fullfile(runtime_root, ...
    'freeze','component_prototype_registry.csv')), ...
    freeze.prototype_registry_file_sha256) && ...
    strcmp(stage8_k2_tecs_sha256_file(fullfile(runtime_root, ...
    'freeze','component_admission_rule.json')), ...
    freeze.component_admission_rule_file_sha256), ...
    'stage8_k2_tecs_run_component_replay:FreezeFileDrift', ...
    'A COMPONENT_FREEZE file differs from its frozen SHA-256.');
[~, code_hash] = stage8_k2_tecs_code_manifest(repo_dir, 'ALL');
[~, component_hash] = stage8_k2_tecs_code_manifest( ...
    repo_dir, 'COMPONENT_CORE');
assert(strcmp(code_hash, freeze.cache_code_hash) && ...
    strcmp(component_hash, freeze.prototype_code_hash), ...
    'stage8_k2_tecs_run_component_replay:CodeDrift', ...
    'Component or complete cache source hash drifted after freeze.');
assert(strcmp(stage8_k2_tecs_sha256_file(fullfile(runtime_root, ...
    'stage_commit_ledger.json')), ...
    freeze.stage_commit_ledger_hash_at_component_freeze), ...
    'stage8_k2_tecs_run_component_replay:LedgerDrift', ...
    'The stage commit ledger changed after COMPONENT_FREEZE.');
schedule = readtable(fullfile(runtime_root, 'freeze', ...
    'component_schedule.csv'), 'TextType','string');
assert(strcmp(stage8_k2_tcc_stable_hash( ...
    'TECS_COMPONENT_SCHEDULE_V1', schedule), ...
    freeze.component_schedule_hash), ...
    'stage8_k2_tecs_run_component_replay:ScheduleDrift', ...
    'The component schedule differs from its frozen stable hash.');
end

function expected = checkpoint_expected_local(design, freeze, row)
expected = struct( ...
    'checkpoint_unit_kind','COMPONENT_PAIR','pass','PASS_B', ...
    'cache_setting','PAIRED_OFF_ON','cache_layer','C1', ...
    'fixed_measurement_hash',char(row.fixed_measurement_hash), ...
    'pair_order',char(row.pair_order), ...
    'schedule_row_id',row.schedule_row_id, ...
    'schedule_row_hash',char(row.schedule_row_hash), ...
    'lifecycle_setting','WARM', ...
    'identity_batch_id',char(row.identity_batch_id), ...
    'batch_repeat_index',row.batch_repeat_index, ...
    'run_id',design.run_id, ...
    'stage_commit_ledger_hash', ...
    freeze.stage_commit_ledger_hash_at_component_freeze, ...
    'cache_code_hash',freeze.cache_code_hash, ...
    'phase_schedule_hash',freeze.component_schedule_hash, ...
    'design_freeze_hash',design.freeze_payload_hash, ...
    'component_freeze_hash_or_sentinel',freeze.freeze_payload_hash);
end

function checkpoint = checkpoint_base_local(design, freeze, row, raw_row)
not = 'NOT_APPLICABLE';
checkpoint = struct( ...
    'checkpoint_unit_kind','COMPONENT_PAIR','pass','PASS_B', ...
    'cache_setting','PAIRED_OFF_ON','cache_layer','C1', ...
    'variant_alias_id',not,'comparison_id',not,'comparison_kind',not, ...
    'baseline_canonical_mode_id',not,'candidate_canonical_mode_id',not, ...
    'enabled_layer_set_hash',not,'precedence_hash',not, ...
    'fixed_measurement_hash',char(row.fixed_measurement_hash), ...
    'trial_id',not,'repeat_index',not,'pair_order',char(row.pair_order), ...
    'schedule_row_id',row.schedule_row_id, ...
    'schedule_row_hash',char(row.schedule_row_hash), ...
    'lifecycle_setting','WARM', ...
    'identity_batch_id',char(row.identity_batch_id), ...
    'batch_repeat_index',row.batch_repeat_index, ...
    'lifecycle_operation',not,'operation_repeat_index',not, ...
    'baseline_commit',design.baseline_commit, ...
    'initial_execution_start_commit',design.initial_execution_start_commit, ...
    'run_id',design.run_id, ...
    'stage_commit_ledger_hash', ...
    freeze.stage_commit_ledger_hash_at_component_freeze, ...
    'integration_code_commit',not, ...
    'prompt_hash',design.execution_prompt_hash, ...
    'baseline_snapshot_hash',design.baseline_snapshot_hash, ...
    'cache_code_hash',freeze.cache_code_hash, ...
    'frozen_function_hashes',{design.frozen_function_hashes}, ...
    'trial_registry_hash',design.trial_registry_hash, ...
    'key_schema_hash',design.key_schema_hash, ...
    'semantic_output_projection_hash', ...
    design.semantic_output_projection_hash, ...
    'hook_allowlist_hash',design.hook_allowlist_hash, ...
    'timing_protocol_hash','NOT_CLOSED', ...
    'phase_schedule_hash',freeze.component_schedule_hash, ...
    'final_measurement_candidate_hash','NOT_CLOSED', ...
    'design_freeze_hash',design.freeze_payload_hash, ...
    'component_freeze_hash_or_sentinel',freeze.freeze_payload_hash, ...
    'timing_freeze_hash_or_sentinel','NOT_CLOSED', ...
    'final_candidate_freeze_hash_or_sentinel','NOT_CLOSED', ...
    'MATLAB_release',design.MATLAB_release,'singleCompThread',true, ...
    'cache_reset_lifecycle_rule', ...
    'PREBUILT_C1_IMMUTABLE_CLEAR_COUNTERS_PER_EDGE', ...
    'pair_contiguous_complete',true, ...
    'payload',struct('raw_row',raw_row), ...
    'unit_complete',true,'atomic_checkpoint',true);
end

function [runtime, checksum] = time_off_local(angles, model)
clock = tic;
checksum = batch_off_local(angles, model);
runtime = toc(clock);
end

function [runtime, checksum] = time_on_local(angles, model, provider)
clock = tic;
checksum = batch_on_local(angles, model, provider);
runtime = toc(clock);
end

function checksum = batch_off_local(angles, model)
checksum = [0, 0, 0];
for index = 1:size(angles, 1)
    pair = [angles(index, 1:2); angles(index, 3:4)];
    [G, ~, info] = build_full_sequential_local_manifold( ...
        pair, model, struct('rank_multiplier',1));
    checksum = checksum + [sum(real(G(:))), sum(imag(G(:))), ...
        double(info.rank_Gseq)];
end
end

function checksum = batch_on_local(angles, model, provider)
checksum = [0, 0, 0];
for index = 1:size(angles, 1)
    pair = [angles(index, 1:2); angles(index, 3:4)];
    [G, info] = stage8_k2_tecs_provider_pair( ...
        pair, model, provider, struct('rank_multiplier',1));
    checksum = checksum + [sum(real(G(:))), sum(imag(G(:))), ...
        double(info.rank_Gseq)];
end
end

function summary = summarize_local(raw)
rows = repmat(summary_template_local(), 3, 1);
for identity = 1:2
    selected = raw.included_in_statistics & raw.identity_index == identity;
    current = raw(selected, :);
    rows(identity) = summary_row_local(current, ...
        current.fixed_measurement_hash(1));
end
rows(3) = summary_template_local();
rows(3).schema_version = "STAGE8_K2_TECS_COMPONENT_SUMMARY_V1";
rows(3).cache_layer = "C1";
rows(3).fixed_measurement_hash = "OVERALL_2_IDENTITIES";
rows(3).measured_pair_count = sum([rows(1:2).measured_pair_count]);
rows(3).AB_count = sum([rows(1:2).AB_count]);
rows(3).BA_count = sum([rows(1:2).BA_count]);
rows(3).component_point_sec = sum([rows(1:2).component_point_sec]);
rows(3).bytes_peak = max([rows(1:2).bytes_peak]);
rows(3).both_identity_nonnegative = all( ...
    [rows(1:2).component_point_sec] >= 0);
rows(3).overall_positive = rows(3).component_point_sec > 0;
rows(3).performance_status = string(ternary_local( ...
    rows(3).both_identity_nonnegative && rows(3).overall_positive, ...
    'C1_COMPONENT_POSITIVE','C1_COMPONENT_NONPOSITIVE'));
rows(3).integration_status = ...
    "REQUIRED_C1_COMPONENT_COMPLETE_INTEGRATION_PENDING";
summary = struct2table(rows);
end

function row = summary_row_local(current, identity)
row = summary_template_local();
row.schema_version = "STAGE8_K2_TECS_COMPONENT_SUMMARY_V1";
row.cache_layer = "C1";
row.fixed_measurement_hash = string(identity);
row.measured_pair_count = height(current);
row.AB_count = nnz(current.pair_order == "AB");
row.BA_count = nnz(current.pair_order == "BA");
row.component_point_sec = median(current.paired_difference_sec);
row.paired_min_sec = min(current.paired_difference_sec);
row.paired_max_sec = max(current.paired_difference_sec);
row.bytes_peak = max(current.bytes_peak);
row.both_identity_nonnegative = row.component_point_sec >= 0;
row.overall_positive = false;
row.performance_status = "IDENTITY_COMPONENT_POINT";
row.integration_status = ...
    "REQUIRED_C1_COMPONENT_COMPLETE_INTEGRATION_PENDING";
end

function disposition = disposition_local(summary, freeze)
overall = summary(end, :);
disposition = table("C1",true,overall.component_point_sec, ...
    overall.both_identity_nonnegative,overall.overall_positive, ...
    "REQUIRED_TO_INTEGRATE_INDEPENDENT_OF_COMPONENT_SIGN", ...
    "INTEGRATION_PENDING_PASS_C_D",string(freeze.prototype_code_hash), ...
    'VariableNames',{'cache_layer','component_correctness_pass', ...
    'component_point_sec','both_identity_nonnegative','overall_positive', ...
    'component_performance_status','integration_status', ...
    'component_implementation_hash_at_replay'});
end

function row = raw_template_local()
row = struct('schema_version',"",'schedule_row_id',0, ...
    'schedule_row_hash',"",'cache_layer',"", ...
    'fixed_measurement_hash',"",'identity_index',0, ...
    'identity_batch_id',"",'batch_repeat_index',0,'pair_order',"", ...
    'schedule_phase',"",'included_in_statistics',0, ...
    'event_pair_count',0,'column_lookup_count',0, ...
    'time_off_sec',0,'time_on_sec',0,'paired_difference_sec',0, ...
    'cache_hit_count',0,'cache_miss_count',0, ...
    'physical_producer_call_count',0,'entry_count',0, ...
    'bytes_current',0,'bytes_peak',0,'key_collision_count',0, ...
    'truth_leakage_count',0,'output_checksum_hash',"", ...
    'pair_contiguous_complete',false);
end

function row = summary_template_local()
row = struct('schema_version',"",'cache_layer',"", ...
    'fixed_measurement_hash',"",'measured_pair_count',0, ...
    'AB_count',0,'BA_count',0,'component_point_sec',NaN, ...
    'paired_min_sec',NaN,'paired_max_sec',NaN,'bytes_peak',NaN, ...
    'both_identity_nonnegative',false,'overall_positive',false, ...
    'performance_status',"",'integration_status',"");
end

function atomic_checkpoint_local(path_now, checkpoint)
temporary = [path_now, '.tmp'];
save(temporary, 'checkpoint', '-v7.3');
[moved, message] = movefile(temporary, path_now, 'f');
if ~moved, error('stage8_k2_tecs_run_component_replay:Checkpoint', ...
        '%s', message); end
end

function output = ternary_local(condition, yes, no)
if condition, output = yes; else, output = no; end
end
