function registry = stage8_k2_tecs_build_formal_warmup_registry(fixture)
%STAGE8_K2_TECS_BUILD_FORMAL_WARMUP_REGISTRY Freeze executable profiles.

stage5_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_STAGE5_LOCKED_EXECUTABLE_PROFILE', fixture.context.stage5_locked);
constants_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_TANGENT_CONSTANTS_EXECUTABLE_PROFILE', fixture.context.constants);
domain_hash = char(fixture.context.plan.local_domain.domain_hash);
rows = repmat(struct('global_trial_index', 0, 'trial_id', "", ...
    'fixed_measurement_hash', "", 'executable_profile_hash', "", ...
    'noise_profile_id', "", 'L', 0, 'snr_db', 0, ...
    'profile_id', ""), height(fixture.registry), 1);
for index = 1:height(fixture.registry)
    spec = fixture.registry(index, :);
    identity_hash = char(string( ...
        fixture.semantic_snapshot.rows{index}.fixed_measurement_hash));
    identity = stage8_k2_tecs_identity_fixture(fixture, identity_hash);
    payload = struct( ...
        'fixed_measurement_hash', identity_hash, ...
        'measurement_config_id', identity.model.measurement_config_id, ...
        'noise_profile_id', char(spec.noise_profile_id), ...
        'L', double(spec.L), 'snr_db', double(spec.snr_db), ...
        'profile_id', char(spec.profile_id), ...
        'local_domain_hash', domain_hash, ...
        'stage5_locked_hash', stage5_hash, ...
        'Tangent_constants_protocol_hash', constants_hash, ...
        'known_K_mode_CORE_LITE', true, ...
        'K1_K2_execution_flags', ...
            'K1_PUBLIC_K2_PUBLIC_TAIL_TANGENT_FINAL_SELECTOR', ...
        'numeric_class', 'double', 'device_backend', 'CPU', ...
        'MATLAB_release', version('-release'));
    row = rows(index);
    row.global_trial_index = double(spec.global_trial_index);
    row.trial_id = string(spec.trial_id);
    row.fixed_measurement_hash = string(identity_hash);
    row.executable_profile_hash = stage8_k2_tecs_sha256( ...
        'TECS_EXECUTABLE_PROFILE_V1', payload);
    row.noise_profile_id = string(spec.noise_profile_id);
    row.L = double(spec.L);
    row.snr_db = double(spec.snr_db);
    row.profile_id = string(spec.profile_id);
    rows(index) = row;
end
all_rows = struct2table(rows);
[~, first] = unique(all_rows(:, ...
    {'fixed_measurement_hash','executable_profile_hash'}), 'rows', 'stable');
registry = sortrows(all_rows(sort(first), :), 'global_trial_index');
assert(height(registry) == 72, ...
    'stage8_k2_tecs_build_formal_warmup_registry:Cardinality', ...
    'Every frozen factorial trial selects a distinct executable profile.');
end
