function artifact = stage8_k2_tecs_promote_c1_artifact(dictionary)
%STAGE8_K2_TECS_PROMOTE_C1_ARTIFACT Promote certified diagnostic payload.

required = {'G','key_table','key_count','fixed_measurement_hash', ...
    'measurement_config_id','noise_profile_id','domain_hash', ...
    'phase_factor','numeric_class','dictionary_hash', ...
    'diagnostic_only_flag','production_integrated_flag'};
if ~(isstruct(dictionary) && isscalar(dictionary) && ...
        all(isfield(dictionary, required)) && ...
        dictionary.diagnostic_only_flag && ...
        ~dictionary.production_integrated_flag && ...
        dictionary.key_count == 21 && size(dictionary.G, 2) == 21)
    error('stage8_k2_tecs_promote_c1_artifact:Dictionary', ...
        'The source dictionary is not a certified 21-key diagnostic payload.');
end
angles = [double(dictionary.key_table.az_deg), ...
    double(dictionary.key_table.el_deg)];
semantic = struct( ...
    'schema_version','STAGE8_K2_TECS_C1_ARTIFACT_V1', ...
    'cache_layer','C1', ...
    'scope','MEASUREMENT_IDENTITY_SESSION', ...
    'population_class','PREBUILT_FINITE_DOMAIN', ...
    'output_class','CERTIFIED_CANONICAL_DICTIONARY_OUTPUT', ...
    'fixed_measurement_hash',dictionary.fixed_measurement_hash, ...
    'measurement_config_id',dictionary.measurement_config_id, ...
    'noise_profile_id',dictionary.noise_profile_id, ...
    'local_domain_hash',dictionary.domain_hash, ...
    'phase_factor',double(dictionary.phase_factor), ...
    'numeric_class',dictionary.numeric_class, ...
    'key_tolerance_deg',1e-11, ...
    'key_angles_deg',angles, ...
    'key_ids',{cellstr(string(dictionary.key_table.key_id))}, ...
    'G',dictionary.G, ...
    'source_dictionary_hash',dictionary.dictionary_hash, ...
    'experimental_integration_flag',true, ...
    'production_default_cache_on',false, ...
    'supports_interpolation',false, ...
    'supports_nearest_neighbor',false);
artifact = semantic;
artifact.artifact_hash = stage8_k2_tecs_sha256( ...
    'TECS_C1_PREBUILT_ARTIFACT', semantic);
probe = artifact; %#ok<NASGU>
info = whos('probe');
artifact.value_bytes = double(info.bytes);
artifact.entry_count = 21;
artifact.validate_once_status = 'CERTIFIED_PROMOTION_COMPLETE';
artifact.immutable = true;
end
