function freeze = stage8_k2_tecs_close_final_candidate_freeze( ...
    repo_dir, runtime_root)
%STAGE8_K2_TECS_CLOSE_FINAL_CANDIDATE_FREEZE Freeze Pass-F candidate.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
fixture = stage8_k2_tecs_build_runtime_fixture(repo_dir, runtime_root);
timing = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'timing_freeze.json')));
screening = jsondecode(fileread(fullfile(runtime_root, 'pass_e', ...
    'screening_manifest.json')));
proof = jsondecode(fileread(fullfile(runtime_root, 'pass_e', ...
    'screening_selection_proof.json')));
assert(strcmp(screening.status, 'PASS_E_SCREENING_COMPLETE') && ...
    strcmp(screening.timing_freeze_hash, timing.freeze_payload_hash) && ...
    strcmp(proof.selection_proof_hash, screening.selection_proof_hash), ...
    'stage8_k2_tecs_close_final_candidate_freeze:Screening');

mode_registry = readtable(fullfile(runtime_root, 'freeze', ...
    'canonical_mode_registry.csv'), 'TextType', 'string');
candidate_id = string(proof. ...
    final_measurement_candidate_canonical_mode_id);
candidate = mode_registry( ...
    mode_registry.candidate_canonical_mode_id == candidate_id, :);
assert(height(candidate) == 1 && candidate.enabled_layer_count > 0, ...
    'stage8_k2_tecs_close_final_candidate_freeze:Candidate');
schedules = stage8_k2_tecs_build_final_schedules(fixture, ...
    candidate_id, candidate.enabled_layer_set_hash, ...
    candidate.precedence_hash);
warm_hash = stage8_k2_tecs_sha256( ...
    'TECS_FINAL_WARM_SCHEDULE_V1', ...
    table2struct(schedules.final_warm));
cold_hash = stage8_k2_tecs_sha256( ...
    'TECS_COLD_LIFECYCLE_SCHEDULE_V1', ...
    table2struct(schedules.cold_lifecycle));
candidate_payload = struct( ...
    'candidate_alias_id',proof.final_measurement_candidate_alias_id, ...
    'candidate_canonical_mode_id',char(candidate_id), ...
    'enabled_layer_set_hash',char(candidate.enabled_layer_set_hash), ...
    'precedence_hash',char(candidate.precedence_hash), ...
    'fallback_hash',char(candidate.fallback_hash), ...
    'screening_raw_hash',screening.raw_hash, ...
    'screening_summary_hash',screening.summary_hash, ...
    'selection_proof_hash',proof.selection_proof_hash);
candidate_hash = stage8_k2_tecs_sha256( ...
    'TECS_FINAL_MEASUREMENT_CANDIDATE_V1', candidate_payload);

model_registry = readtable(fullfile(runtime_root, 'freeze', ...
    'candidate_model_registry.csv'), 'TextType', 'string');
matched = model_registry.matched_candidate_mode == candidate_id & ...
    model_registry.model_status == "MATCHABLE_FROZEN_MODEL";
if nnz(matched) == 1
    frozen_model_id = char(model_registry.model_id(matched));
    frozen_model_hash = char(model_registry.model_hash(matched));
    frozen_model_status = 'MATCHED';
else
    frozen_model_id = 'NONE';
    sentinel = struct('frozen_model_id','NONE', ...
        'frozen_model_status', ...
        'NOT_AVAILABLE_NO_MATCHED_FROZEN_MODEL', ...
        'candidate_canonical_mode_id',char(candidate_id), ...
        'candidate_model_registry_hash', ...
            timing.candidate_model_registry_hash);
    frozen_model_hash = stage8_k2_tecs_sha256( ...
        'TECS_NO_MATCHED_FROZEN_MODEL_SENTINEL_V1', sentinel);
    frozen_model_status = 'NOT_AVAILABLE_NO_MATCHED_FROZEN_MODEL';
end
freeze_dir = fullfile(runtime_root, 'freeze');
paths = struct('warm',fullfile(freeze_dir,'final_warm_schedule.csv'), ...
    'cold',fullfile(freeze_dir,'cold_lifecycle_schedule.csv'), ...
    'freeze',fullfile(freeze_dir,'final_candidate_freeze.json'));
names = fieldnames(paths);
for index = 1:numel(names)
    if isfile(paths.(names{index}))
        error('stage8_k2_tecs_close_final_candidate_freeze:ImmutableExists', ...
            'Final-candidate freeze target exists: %s', paths.(names{index}));
    end
end
stage8_k2_tecs_atomic_writetable(schedules.final_warm, paths.warm);
stage8_k2_tecs_atomic_writetable(schedules.cold_lifecycle, paths.cold);
freeze = struct( ...
    'schema_version','STAGE8_K2_TECS_FINAL_CANDIDATE_FREEZE_V1', ...
    'freeze_phase','FINAL_CANDIDATE_FREEZE', ...
    'parent_freeze_hash',timing.freeze_payload_hash, ...
    'created_before_pass','PASS_F_FINAL_WARM_AND_COLD_LIFECYCLE', ...
    'final_measurement_candidate_alias_id', ...
        proof.final_measurement_candidate_alias_id, ...
    'final_measurement_candidate_canonical_mode_id',char(candidate_id), ...
    'final_measurement_candidate_hash',candidate_hash, ...
    'frozen_model_id',frozen_model_id, ...
    'frozen_model_hash',frozen_model_hash, ...
    'frozen_model_status',frozen_model_status, ...
    'final_warm_schedule_hash',warm_hash, ...
    'cold_lifecycle_schedule_hash',cold_hash, ...
    'screening_raw_hash',screening.raw_hash, ...
    'screening_summary_hash',screening.summary_hash, ...
    'screening_resolution_and_select_proof_hash', ...
        proof.selection_proof_hash, ...
    'status','IMMUTABLE_FINAL_CANDIDATE_FREEZE_COMPLETE');
freeze.freeze_payload_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_FINAL_CANDIDATE_FREEZE_V1', freeze);
stage8_k2_tecs_atomic_write_json(paths.freeze, freeze);
append_repo_freeze_local(repo_dir, paths, freeze);
for index = 1:numel(names), set_read_only_local(paths.(names{index})); end
fprintf(['TECS FINAL CANDIDATE FREEZE COMPLETE hash=%s ', ...
    'candidate=%s alias=%s\n'], freeze.freeze_payload_hash, ...
    freeze.final_measurement_candidate_canonical_mode_id, ...
    freeze.final_measurement_candidate_alias_id);
end

function append_repo_freeze_local(repo_dir, paths, freeze)
csv_path = fullfile(repo_dir, 'innovation-mining', ...
    '53_stage8_k2_tangent_exact_cache_stack_freeze.csv');
current = readtable(csv_path, 'TextType', 'string');
assert(~any(current.freeze_phase == "FINAL_CANDIDATE_FREEZE"));
roles = ["FINAL_WARM_SCHEDULE";"COLD_LIFECYCLE_SCHEDULE"; ...
    "FINAL_CANDIDATE_FREEZE_RECORD"];
ordered = {paths.warm;paths.cold;paths.freeze};
rows = current([],:);
for index = 1:numel(ordered)
    row = current(1,:);
    row.schema_version(:) = "STAGE8_K2_TECS_FREEZE_CSV_V1";
    row.freeze_phase(:) = "FINAL_CANDIDATE_FREEZE";
    row.parent_freeze_hash(:) = string(freeze.parent_freeze_hash);
    row.freeze_payload_hash(:) = string(freeze.freeze_payload_hash);
    row.created_before_pass(:) = ...
        "PASS_F_FINAL_WARM_AND_COLD_LIFECYCLE";
    row.path(:) = string(strrep(ordered{index}, '\', '/'));
    row.role(:) = roles(index);
    row.baseline_hash(:) = "NOT_APPLICABLE_NEW_FREEZE_ARTIFACT";
    row.post_implementation_hash(:) = string( ...
        stage8_k2_tecs_sha256_file(ordered{index}));
    row.frozen_flag(:) = 1; row.allowed_change_flag(:) = 0;
    row.status(:) = "IMMUTABLE_FINAL_CANDIDATE_ARTIFACT";
    rows = [rows; row]; %#ok<AGROW>
end
stage8_k2_tecs_atomic_writetable([current; rows], csv_path);
end

function set_read_only_local(path_now)
[status, message] = fileattrib(path_now, '-w');
if ~status, error('stage8_k2_tecs_close_final_candidate_freeze:ReadOnly', ...
        '%s', message); end
end
