function freeze = stage8_k2_tecs_close_timing_freeze(repo_dir, runtime_root)
%STAGE8_K2_TECS_CLOSE_TIMING_FREEZE Freeze commit-2 timing protocol.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
assert_commit2_pushed_local(repo_dir, runtime_root);
fixture = stage8_k2_tecs_build_runtime_fixture(repo_dir, runtime_root);
pass_cd = jsondecode(fileread(fullfile(runtime_root, 'pass_c_d', ...
    'correctness_manifest.json')));
[integration_manifest, integration_hash] = ...
    stage8_k2_tecs_integration_manifest(repo_dir);
assert(strcmp(pass_cd.integration_implementation_hash, integration_hash) && ...
    pass_cd.M1_correctness_pass_count == 72 && ...
    pass_cd.post_hook_cache_off_qualification_pass_count == 72, ...
    'stage8_k2_tecs_close_timing_freeze:CorrectnessDrift', ...
    'Post-hook qualification does not match the committed integration.');
assert(strcmp(fixture.component.prototype_code_hash, ...
    integration_manifest.component_core_hash), ...
    'stage8_k2_tecs_close_timing_freeze:ComponentDrift', ...
    'COMPONENT_FREEZE_INVALIDATED_STOP');

freeze_dir = fullfile(runtime_root, 'freeze');
paths = struct( ...
    'mode', fullfile(freeze_dir, 'canonical_mode_registry.csv'), ...
    'alias', fullfile(freeze_dir, 'mode_alias_registry.csv'), ...
    'comparison_raw', fullfile(freeze_dir, ...
        'screening_raw_comparison_registry.csv'), ...
    'comparison_views', fullfile(freeze_dir, ...
        'screening_comparison_view_registry.csv'), ...
    'warmup', fullfile(freeze_dir, 'formal_warmup_registry.csv'), ...
    'artifact', fullfile(freeze_dir, 'c1_artifact_registry.csv'), ...
    'model', fullfile(freeze_dir, 'candidate_model_registry.csv'), ...
    'protocol', fullfile(freeze_dir, 'timing_protocol.json'), ...
    'schedule', fullfile(freeze_dir, 'screening_schedule.csv'), ...
    'freeze', fullfile(freeze_dir, 'timing_freeze.json'));
names = fieldnames(paths);
for index = 1:numel(names)
    if isfile(paths.(names{index}))
        error('stage8_k2_tecs_close_timing_freeze:ImmutableExists', ...
            'Timing-freeze target exists: %s', paths.(names{index}));
    end
end

artifact_registry = stage8_k2_tecs_build_c1_artifacts( ...
    repo_dir, runtime_root);
fixture = stage8_k2_tecs_build_runtime_fixture(repo_dir, runtime_root);
modes = stage8_k2_tecs_build_mode_registry(runtime_root);
comparison = stage8_k2_tecs_build_comparison_registry(runtime_root);
schedule = stage8_k2_tecs_build_screening_schedule( ...
    comparison, fixture.registry);
warmup = stage8_k2_tecs_build_formal_warmup_registry(fixture);
model_registry = build_model_registry_local( ...
    runtime_root, fixture, modes, integration_hash);

schedule_hash = stage8_k2_tecs_sha256( ...
    'TECS_SCREENING_SCHEDULE_V1', table2struct(schedule));
warmup_hash = stage8_k2_tecs_sha256( ...
    'TECS_FORMAL_WARMUP_REGISTRY_V1', table2struct(warmup));
artifact_registry_hash = stage8_k2_tecs_sha256( ...
    'TECS_C1_ARTIFACT_REGISTRY_V1', table2struct(artifact_registry));
reset_payload = struct( ...
    'make_session_sha256', stage8_k2_tecs_sha256_file(fullfile(repo_dir, ...
        'tools','stage8_k2_tangent_exact_cache_stack','matlab', ...
        'stage8_k2_tecs_make_session.m')), ...
    'session_core_sha256', stage8_k2_tecs_sha256_file(fullfile(repo_dir, ...
        'tools','stage8_k2_tangent_exact_cache_stack','matlab', ...
        'stage8_k2_tecs_cache_session.m')), ...
    'root_runner_sha256', stage8_k2_tecs_sha256_file(fullfile(repo_dir, ...
        'tools','stage8_k2_tangent_exact_cache_stack','matlab', ...
        'stage8_k2_tecs_run_root.m')), ...
    'rule', 'NEW_PRISTINE_SESSION_BEFORE_EACH_CACHE_ON_PAIR_EDGE');
reset_hash = stage8_k2_tecs_sha256( ...
    'TECS_CACHE_STATE_RESET_IMPLEMENTATION_V1', reset_payload);
no_op_hash = stage8_k2_tecs_sha256('TECS_NOOP_CONTROL_V1', struct( ...
    'A','M0_FROZEN_CACHE_OFF_ENTRY','B','SAME_M0_ENTRY_DISTINCT_LABEL', ...
    'label_inside_timed_region',false, ...
    'same_function_parameters_statement_order',true));

protocol = struct( ...
    'schema_version','STAGE8_K2_TECS_TIMING_PROTOCOL_V1', ...
    'MATLAB_release','R2022b','singleCompThread',true, ...
    'parallel_pool',false,'formal_MATLAB_processes',1, ...
    'root_timer','EXTERNAL_TIC_TOC_ONE_STAGE8_K2_TP_FIT_SAFE_CALL', ...
    'root_entry_path', ...
        'tools/stage8_k2_tangent_exact_cache_stack/matlab/stage8_k2_tecs_run_root.m', ...
    'root_entry_sha256',reset_payload.root_runner_sha256, ...
    'screening_paired_repeats',6,'screening_AB',3,'screening_BA',3, ...
    'final_WARM_paired_repeats',20,'final_WARM_AB',10, ...
    'final_WARM_BA',10,'COLD_batch_repeats',10, ...
    'COLD_AB',5,'COLD_BA',5, ...
    'component_warmup_pairs',5,'component_measured_pairs',30, ...
    'lifecycle_operation_warmup',5, ...
    'lifecycle_operation_measured',30, ...
    'formal_root_warmup_pairs_per_registry_row',2, ...
    'formal_root_warmup_order','AB_THEN_BA_DISCARDED', ...
    'formal_warmup_registry_hash',warmup_hash, ...
    'trial_order_seed',2026080902, ...
    'screening_pair_order_seed',2026080903, ...
    'final_pair_order_seed',2026080904, ...
    'cold_pair_order_seed',2026080905, ...
    'component_pair_order_seed',2026080906, ...
    'lifecycle_operation_order_seed',2026080907, ...
    'bootstrap_seed',2026080901,'bootstrap_resamples',10000, ...
    'bootstrap_lower_order_statistic_index',500, ...
    'descriptive_p10','SORTED_INDEX_CEIL_0_10_N', ...
    'descriptive_p90','SORTED_INDEX_CEIL_0_90_N', ...
    'median','MATLAB_MEDIAN_EVEN_MEAN_TWO_CENTERS', ...
    'memory_bound_bytes',536870912, ...
    'primary_cache_state','PRIMARY_WARM_ARTIFACT_READY_ONLINE_MEMO_EMPTY', ...
    'cache_state_reset_implementation_hash',reset_hash, ...
    'minimal_counters',{{'hit','miss','physical_producer_call', ...
        'entry','bytes_current','bytes_peak'}}, ...
    'no_op_control_hash',no_op_hash, ...
    'screening_comparison_set_hash', ...
        comparison.screening_comparison_set_hash, ...
    'candidate_selection_rule', ...
        'POSITIVE_POOL_THEN_DMAX_RHO_LAYER_COUNT_BYTES_MODE_ID;_FALLBACK_SAME_WITHOUT_POSITIVITY', ...
    'instrumentation_disabled',{{'shadow','raw_query_logging', ...
        'trajectory_capture','per_call_timing','stage_timing', ...
        'cache_debug_logging','filesystem_write_inside_timed_region'}}, ...
    'screening_schedule_algorithm_hash', ...
        fixture.design.schedule_generation_algorithm_hash, ...
    'final_schedule_algorithm_hash', ...
        fixture.design.schedule_generation_algorithm_hash, ...
    'cold_schedule_algorithm_hash', ...
        fixture.design.schedule_generation_algorithm_hash, ...
    'artifact_registry_hash',artifact_registry_hash, ...
    'integration_implementation_hash',integration_hash);
protocol.timing_protocol_hash = stage8_k2_tecs_sha256( ...
    'TECS_TIMING_PROTOCOL_V1', protocol);
model_registry = bind_model_registry_local( ...
    model_registry, protocol.timing_protocol_hash);
model_registry_hash = stage8_k2_tecs_sha256( ...
    'TECS_CANDIDATE_MODEL_REGISTRY_V1', table2struct(model_registry));

stage8_k2_tecs_atomic_writetable(modes.canonical, paths.mode);
stage8_k2_tecs_atomic_writetable(modes.aliases, paths.alias);
stage8_k2_tecs_atomic_writetable(comparison.raw, paths.comparison_raw);
stage8_k2_tecs_atomic_writetable(comparison.views, paths.comparison_views);
stage8_k2_tecs_atomic_writetable(warmup, paths.warmup);
stage8_k2_tecs_atomic_writetable(artifact_registry, paths.artifact);
stage8_k2_tecs_atomic_writetable(model_registry, paths.model);
stage8_k2_tecs_atomic_write_json(paths.protocol, protocol);
stage8_k2_tecs_atomic_writetable(schedule, paths.schedule);

head = git_output_local(repo_dir, 'rev-parse HEAD');
ledger_hash = stage8_k2_tecs_sha256_file(fullfile( ...
    runtime_root, 'stage_commit_ledger.json'));
component_result = jsondecode(fileread(fullfile(runtime_root, ...
    'pass_b', 'component_replay_manifest.json')));
freeze = struct( ...
    'schema_version','STAGE8_K2_TECS_TIMING_FREEZE_V1', ...
    'freeze_phase','TIMING_FREEZE', ...
    'parent_freeze_hash',fixture.component.freeze_payload_hash, ...
    'created_before_pass','PASS_E_SCREENING', ...
    'integration_code_commit',head, ...
    'stage_commit_ledger_hash_at_timing_freeze',ledger_hash, ...
    'cache_code_hash',integration_hash, ...
    'cache_state_reset_implementation_hash',reset_hash, ...
    'timing_protocol_hash',protocol.timing_protocol_hash, ...
    'screening_schedule_hash',schedule_hash, ...
    'screening_comparison_set_hash', ...
        comparison.screening_comparison_set_hash, ...
    'formal_warmup_registry_hash',warmup_hash, ...
    'component_result_disposition_hash', ...
        component_result.component_result_disposition_hash, ...
    'component_implementation_hashes_at_replay', ...
        fixture.component.prototype_code_hash, ...
    'component_implementation_hashes_at_integration', ...
        integration_manifest.component_core_hash, ...
    'canonical_mode_registry_hash', ...
        modes.canonical_mode_registry_hash, ...
    'mode_alias_registry_hash',modes.mode_alias_registry_hash, ...
    'C5_precedence_fallback_hash', ...
        fixture.design.C5_precedence_fallback_rule_hash, ...
    'candidate_model_registry_hash',model_registry_hash, ...
    'representative_alias_rule_hash', ...
        modes.representative_alias_rule_hash, ...
    'artifact_registry_hash',artifact_registry_hash, ...
    'status','IMMUTABLE_TIMING_FREEZE_COMPLETE');
freeze.freeze_payload_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_TIMING_FREEZE_V1', freeze);
stage8_k2_tecs_atomic_write_json(paths.freeze, freeze);
append_repo_freeze_local(repo_dir, paths, freeze);
for index = 1:numel(names), set_read_only_local(paths.(names{index})); end
fprintf('TECS TIMING FREEZE COMPLETE hash=%s commit=%s rows=%d\n', ...
    freeze.freeze_payload_hash, head, height(schedule));
end

function registry = build_model_registry_local( ...
    runtime_root, fixture, modes, integration_hash)
component = readtable(fullfile(runtime_root, 'pass_b', ...
    'component_summary.csv'), 'TextType', 'string');
overall = component.fixed_measurement_hash == "OVERALL_2_IDENTITIES";
assert(nnz(overall) == 1);
m1 = modes.aliases(modes.aliases.variant_alias_id == "M1", :);
delta = double(component.component_point_sec(overall));
registry = table( ...
    "PENDING", string(m1.candidate_canonical_mode_id), ...
    string('["C1"]'), "PREBUILT_FINITE_DOMAIN", ...
    "MEASUREMENT_IDENTITY_SESSION", 5904, delta, ...
    NaN, NaN, NaN, NaN, ...
    "NO_OVERLAP_SINGLE_LAYER", NaN, NaN, ...
    string(fixture.design.baseline_commit), ...
    string(fixture.design.baseline_snapshot_hash), ...
    string(fixture.design.trial_registry_hash), ...
    string(integration_hash), "PENDING", ...
    "NOT_MATCHABLE_INCOMPLETE_COMPONENT_COST", "PENDING", ...
    'VariableNames',{'model_id','matched_candidate_mode', ...
    'ordered_enabled_layer_set','population_class','scope', ...
    'component_exposure_count','measured_component_delta_sec', ...
    'measured_component_lookup_sec','measured_component_miss_sec', ...
    'measured_component_store_sec','measured_component_copy_sec', ...
    'overlap_partition_status','frozen_model_delta_sec', ...
    'historical_baseline_model_percent','baseline_commit', ...
    'baseline_semantic_snapshot_hash','trial_registry_hash', ...
    'integration_implementation_hash','timing_protocol_hash', ...
    'model_status','model_hash'});
end

function registry = bind_model_registry_local(registry, timing_hash)
registry.timing_protocol_hash(:) = string(timing_hash);
for index = 1:height(registry)
    payload = table2struct(removevars(registry(index, :), ...
        {'model_id','model_hash'}));
    hash = stage8_k2_tecs_sha256('TECS_FROZEN_MODEL_V1', payload);
    registry.model_hash(index) = string(hash);
    registry.model_id(index) = "MODEL_" + string(hash);
end
end

function assert_commit2_pushed_local(repo_dir, runtime_root)
head = git_output_local(repo_dir, 'rev-parse HEAD');
upstream = git_output_local(repo_dir, 'rev-parse @{u}');
assert(strcmp(head, upstream), ...
    'stage8_k2_tecs_close_timing_freeze:UnpushedCommit', ...
    'Commit 2 must be pushed and local/remote equal before timing freeze.');
ledger = jsondecode(fileread(fullfile(runtime_root, ...
    'stage_commit_ledger.json')));
assert(strcmp(ledger.pushed_commit, head), ...
    'stage8_k2_tecs_close_timing_freeze:Ledger', ...
    'RESUME_PROVENANCE_MISMATCH_STOP: ledger does not confirm commit 2.');
[status, ~] = system(sprintf(['git -C "%s" diff --quiet -- ', ...
    'tools/stage8_k2_tangent_exact_cache_stack ', ...
    'tools/stage8_k2_tangent_canonical_cache/matlab/', ...
    'stage8_k2_tcc_get_pair_manifold.m'], repo_dir));
assert(status == 0, ...
    'stage8_k2_tecs_close_timing_freeze:DirtyCode', ...
    'Timed source must be clean before TIMING_FREEZE.');
end

function value = git_output_local(repo_dir, command)
[status, value] = system(sprintf('git -C "%s" %s', repo_dir, command));
if status ~= 0, error('stage8_k2_tecs_close_timing_freeze:Git'); end
value = strtrim(value);
end

function append_repo_freeze_local(repo_dir, paths, freeze)
csv_path = fullfile(repo_dir, 'innovation-mining', ...
    '53_stage8_k2_tangent_exact_cache_stack_freeze.csv');
current = readtable(csv_path, 'TextType', 'string');
assert(~any(current.freeze_phase == "TIMING_FREEZE"));
roles = ["CANONICAL_MODE_REGISTRY";"MODE_ALIAS_REGISTRY"; ...
    "SCREENING_RAW_COMPARISON_REGISTRY"; ...
    "SCREENING_COMPARISON_VIEW_REGISTRY"; ...
    "FORMAL_WARMUP_REGISTRY";"C1_ARTIFACT_REGISTRY"; ...
    "CANDIDATE_MODEL_REGISTRY";"TIMING_PROTOCOL"; ...
    "SCREENING_SCHEDULE";"TIMING_FREEZE_RECORD"];
ordered = {paths.mode;paths.alias;paths.comparison_raw; ...
    paths.comparison_views;paths.warmup;paths.artifact;paths.model; ...
    paths.protocol;paths.schedule;paths.freeze};
rows = current([],:);
for index = 1:numel(ordered)
    row = current(1,:);
    row.schema_version(:) = "STAGE8_K2_TECS_FREEZE_CSV_V1";
    row.freeze_phase(:) = "TIMING_FREEZE";
    row.parent_freeze_hash(:) = string(freeze.parent_freeze_hash);
    row.freeze_payload_hash(:) = string(freeze.freeze_payload_hash);
    row.created_before_pass(:) = "PASS_E_SCREENING";
    row.path(:) = string(strrep(ordered{index}, '\', '/'));
    row.role(:) = roles(index);
    row.baseline_hash(:) = "NOT_APPLICABLE_NEW_FREEZE_ARTIFACT";
    row.post_implementation_hash(:) = string( ...
        stage8_k2_tecs_sha256_file(ordered{index}));
    row.frozen_flag(:) = 1; row.allowed_change_flag(:) = 0;
    row.status(:) = "IMMUTABLE_TIMING_ARTIFACT";
    rows = [rows; row]; %#ok<AGROW>
end
stage8_k2_tecs_atomic_writetable([current; rows], csv_path);
end

function set_read_only_local(path_now)
[status, message] = fileattrib(path_now, '-w');
if ~status, error('stage8_k2_tecs_close_timing_freeze:ReadOnly', ...
        '%s', message); end
end
