function output = stage8_k2_tecs_run_stage_reconciliation(repo_dir,runtime_root)
%STAGE8_K2_TECS_RUN_STAGE_RECONCILIATION Independent M0/M1 diagnostics.

scope=stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
fixture=stage8_k2_tecs_build_runtime_fixture(repo_dir,runtime_root);
final=jsondecode(fileread(fullfile(runtime_root,'freeze', ...
    'final_candidate_freeze.json')));
mode_registry=readtable(fullfile(runtime_root,'freeze', ...
    'canonical_mode_registry.csv'),'TextType','string');
m0=mode_registry(mode_registry.enabled_layer_count==0,:);
m1=mode_registry(mode_registry.candidate_canonical_mode_id==string( ...
    final.final_measurement_candidate_canonical_mode_id),:);
trials=stage8_k2_tecs_prepare_trial_bank(fixture);
rows=repmat(row_template_local(),72*2,1);cursor=0;
for trial_index=1:72
    signatures=strings(2,1);
    modes={m0;m1};
    for mode_index=1:2
        mode=modes{mode_index};
        layers=layers_local(mode.ordered_enabled_layer_set);
        [record,signature]=run_diagnostic_local( ...
            trials{trial_index},fixture,layers);
        signatures(mode_index)=signature;
        cursor=cursor+1;row=row_template_local();
        row.candidate_canonical_mode_id=mode.candidate_canonical_mode_id;
        row.fixed_measurement_hash=string( ...
            trials{trial_index}.model.fixed_measurement_hash);
        row.trial_id=fixture.registry.trial_id(trial_index);
        row.root_runtime_sec=record.root_runtime_sec;
        row.unattributed_sec=record.unattributed_sec;
        row.reconciliation_error_sec=record.reconciliation_error_sec;
        row.minimum_exclusive_sec=record.minimum_exclusive_sec;
        row.stage_row_count=height(record.stage_rows);
        row.estimator_signature_hash=signature;
        row.reconciliation_pass=abs(record.reconciliation_error_sec)<=1e-9 && ...
            record.minimum_exclusive_sec>=-1e-9;
        rows(cursor)=row;
        checkpoint_path=fullfile(runtime_root,'stage_diagnostics');
        if ~isfolder(checkpoint_path),mkdir(checkpoint_path);end
        value=record; %#ok<NASGU>
        save(fullfile(checkpoint_path,sprintf('%03d_%d.mat', ...
            trial_index,mode_index)),'value','-v7.3');
    end
    if signatures(1)~=signatures(2)
        error('stage8_k2_tecs_run_stage_reconciliation:Semantic', ...
            'STAGE_RECONCILIATION_FAILURE_STOP');
    end
end
summary=struct2table(rows);
if ~all(summary.reconciliation_pass)
    error('stage8_k2_tecs_run_stage_reconciliation:Reconciliation', ...
        'STAGE_RECONCILIATION_FAILURE_STOP');
end
directory=fullfile(runtime_root,'stage_diagnostics');
summary_path=fullfile(directory,'stage_reconciliation_summary.csv');
manifest_path=fullfile(directory,'stage_reconciliation_manifest.json');
stage8_k2_tecs_atomic_writetable(summary,summary_path);
output=struct('schema_version','STAGE8_K2_TECS_STAGE_RECONCILIATION_V1', ...
    'trial_count',72,'mode_count',2,'diagnostic_run_count',144, ...
    'reconciliation_pass_count',nnz(summary.reconciliation_pass), ...
    'minimum_exclusive_sec',min(summary.minimum_exclusive_sec), ...
    'maximum_abs_reconciliation_error_sec', ...
        max(abs(summary.reconciliation_error_sec)), ...
    'cache_stage_accounting', ...
        'CACHE_SESSION_SETUP_KEY_LOOKUP_MISS_STORE_COPY_VALIDATE_RESET_MEASURED_IN_LIFECYCLE;_ROOT_RECONCILIATION_ATTRIBUTES_THEIR_INTEGRATED_COST_TO_T4_PROFILE', ...
    'summary_hash',stage8_k2_tecs_sha256( ...
        'TECS_STAGE_RECONCILIATION_SUMMARY_V1',table2struct(summary)), ...
    'status','STAGE_RECONCILIATION_COMPLETE');
output.manifest_payload_hash=stage8_k2_tecs_sha256( ...
    'TECS_STAGE_RECONCILIATION_MANIFEST_V1',output);
stage8_k2_tecs_atomic_write_json(manifest_path,output);
fprintf('TECS STAGE RECONCILIATION COMPLETE 144/144\n');
end

function [record,signature]=run_diagnostic_local(trial,fixture,layers)
context=fixture.context;session=[];
if isempty(layers)
    if isfield(context,'manifold_provider'),context=rmfield(context,'manifold_provider');end
else
    session=stage8_k2_tecs_make_session( ...
        fixture,trial.model.fixed_measurement_hash,layers);
    context.manifold_provider=stage8_k2_tecs_build_provider(session);
end
stage8_k2_tcc_audit_state('CONFIGURE',struct('mode','TIMING_STAGE'));
clock=tic;[result,diagnostics]=stage8_k2_tp_fit_safe( ...
    trial.Y_element,trial.model,context);root=toc(clock);
timing=stage8_k2_tcc_audit_state('GET_TIMING');
[stage_rows,unattributed,reconciliation,minimum]= ...
    reconcile_local(timing.stage_rows,root);
if ~isempty(session),delete(session);end
projection=stage8_k2_tecs_root_projection(result,diagnostics,'CACHE_ON_DECISION');
signature=string(stage8_k2_tecs_sha256( ...
    'TECS_STAGE_DIAGNOSTIC_DECISION_V1',projection));
record=struct('root_runtime_sec',root,'stage_rows',stage_rows, ...
    'unattributed_sec',unattributed, ...
    'reconciliation_error_sec',reconciliation, ...
    'minimum_exclusive_sec',minimum);
end

function [rows,unattributed,reconciliation,minimum]=reconcile_local(raw,root)
ids=string({raw.stage_id});values=[raw.inclusive_runtime_sec];
time=containers.Map('KeyType','char','ValueType','double');
for index=1:numel(ids),time(char(ids(index)))=double(values(index));end
time('ROOT_TANGENT_PROFILE_SAFE')=root;edges=edges_local();
all_ids=unique([string(keys(time)),edges(:,1).',edges(:,2).'],'stable');
all_ids=all_ids(:);
inclusive=zeros(numel(all_ids),1);exclusive=zeros(numel(all_ids),1);
for index=1:numel(all_ids)
    id=char(all_ids(index));if isKey(time,id),inclusive(index)=time(id);end
    children=edges(edges(:,1)==all_ids(index),2);child_sum=0;
    for child_index=1:numel(children)
        child=char(children(child_index));if isKey(time,child), ...
                child_sum=child_sum+time(child);end
    end
    exclusive(index)=inclusive(index)-child_sum;
end
root_index=find(all_ids=="ROOT_TANGENT_PROFILE_SAFE",1);
unattributed=exclusive(root_index);keep=(1:numel(all_ids)).'~=root_index & ...
    (inclusive~=0|exclusive~=0);
rows=table(all_ids(keep),inclusive(keep),exclusive(keep), ...
    'VariableNames',{'stage_id','inclusive_runtime_sec','exclusive_runtime_sec'});
reconciliation=root-(sum(exclusive(keep))+unattributed);
minimum=min([exclusive(keep);unattributed]);
end

function edges=edges_local()
edges=["ROOT_TANGENT_PROFILE_SAFE","K1_PUBLIC"; ...
"ROOT_TANGENT_PROFILE_SAFE","K2_PUBLIC";"ROOT_TANGENT_PROFILE_SAFE","TAIL_FULL_DATA"; ...
"ROOT_TANGENT_PROFILE_SAFE","CENTER_MANIFOLD_DERIVATIVES"; ...
"ROOT_TANGENT_PROFILE_SAFE","PROJECTED_DIRECTION";"ROOT_TANGENT_PROFILE_SAFE","T4_PROFILE"; ...
"ROOT_TANGENT_PROFILE_SAFE","FINAL_SAFE_SELECTOR";"K1_PUBLIC","K1_CONTEXT"; ...
"K1_PUBLIC","K1_CORE_LITE";"K1_CONTEXT","K1_FULL_DATA"; ...
"K1_CONTEXT","K1_INITIALIZATION_TOTAL";"K1_INITIALIZATION_TOTAL","K1_INIT_CONVENTIONAL"; ...
"K1_INITIALIZATION_TOTAL","K1_INIT_GROUP_PREPARE"; ...
"K1_INITIALIZATION_TOTAL","K1_INIT_GROUP_Q1";"K1_INITIALIZATION_TOTAL","K1_INIT_GROUP_Q2"; ...
"K1_CORE_LITE","K1_FIXED_FIT";"K1_CORE_LITE","K1_CONTINUOUS"; ...
"K1_CORE_LITE","K1_SELECTION";"K1_FIXED_FIT","K1_FIXED_START_BUILD"; ...
"K1_FIXED_FIT","K1_FIXED_REGISTERED_REFINEMENT"; ...
"K1_FIXED_FIT","K1_FIXED_FINAL_CERTIFICATION"; ...
"K1_FIXED_FIT","K1_FIXED_REGISTERED_SELECTION";"K2_PUBLIC","K2_CONTEXT"; ...
"K2_PUBLIC","K2_CORE_LITE";"K2_CONTEXT","K2_FULL_DATA"; ...
"K2_CONTEXT","K2_INITIALIZATION_TOTAL";"K2_INITIALIZATION_TOTAL","K2_INIT_CONVENTIONAL"; ...
"K2_INITIALIZATION_TOTAL","K2_INIT_GROUP_PREPARE"; ...
"K2_INITIALIZATION_TOTAL","K2_INIT_GROUP_Q1";"K2_INITIALIZATION_TOTAL","K2_INIT_GROUP_Q2"; ...
"K2_CORE_LITE","K2_HELPER_K1";"K2_CORE_LITE","K2_START_BUILD"; ...
"K2_CORE_LITE","K2_REGISTERED_REFINEMENT";"K2_CORE_LITE","K2_FINAL_CERTIFICATION"; ...
"K2_CORE_LITE","K2_SELECTION";"K2_START_BUILD","K2_NESTED_ANCHOR"];
end

function layers=layers_local(text)
value=jsondecode(char(text));if isempty(value),layers=cell(0,1); ...
elseif ischar(value),layers={value};else,layers=reshape(cellstr(string(value)),[],1);end
end

function row=row_template_local()
row=struct('schema_version',"STAGE8_K2_TECS_STAGE_RECONCILIATION_ROW_V1", ...
    'candidate_canonical_mode_id',"",'fixed_measurement_hash',"", ...
    'trial_id',"",'root_runtime_sec',NaN,'unattributed_sec',NaN, ...
    'reconciliation_error_sec',NaN,'minimum_exclusive_sec',NaN, ...
    'stage_row_count',0,'estimator_signature_hash',"", ...
    'reconciliation_pass',false);
end
