function [model, dictionary] = stage8_k2_tecs_select_capture_identity( ...
    capture_value, fixed_measurement_hash)
%STAGE8_K2_TECS_SELECT_CAPTURE_IDENTITY Select one cumulative capture entry.

identity = char(string(fixed_measurement_hash));
if ~(isstruct(capture_value) && isscalar(capture_value) && ...
        all(isfield(capture_value, {'models','dictionaries'})))
    error('stage8_k2_tecs_select_capture_identity:Capture', ...
        'Capture value lacks models or dictionaries.');
end
model_match = cellfun(@(value) isstruct(value) && ...
    isfield(value, 'fixed_measurement_hash') && ...
    strcmp(char(string(value.fixed_measurement_hash)), identity), ...
    capture_value.models);
dictionary_match = cellfun(@(value) isstruct(value) && ...
    isfield(value, 'fixed_measurement_hash') && ...
    strcmp(char(string(value.fixed_measurement_hash)), identity), ...
    capture_value.dictionaries);
if nnz(model_match) ~= 1 || nnz(dictionary_match) ~= 1
    error('stage8_k2_tecs_select_capture_identity:Cardinality', ...
        'Each frozen identity must select exactly one model and dictionary.');
end
model = capture_value.models{find(model_match, 1)};
dictionary = capture_value.dictionaries{find(dictionary_match, 1)};
end
