function stage8_k2_tecs_validate_c1_value(artifact, identity)
%STAGE8_K2_TECS_VALIDATE_C1_VALUE Validate an in-memory C1 artifact.

required = {'artifact_hash','fixed_measurement_hash','key_angles_deg', ...
    'G','entry_count','value_bytes','immutable'};
if ~(isstruct(artifact) && isscalar(artifact) && ...
        all(isfield(artifact, required)) && artifact.immutable && ...
        artifact.entry_count == 21 && ...
        strcmp(artifact.fixed_measurement_hash, char(string(identity))))
    error('stage8_k2_tecs_validate_c1_value:Contract', ...
        'CACHE_CORRUPTION: C1 artifact contract is invalid.');
end
semantic = rmfield(artifact, {'artifact_hash','value_bytes', ...
    'entry_count','validate_once_status','immutable'});
actual = stage8_k2_tecs_sha256('TECS_C1_PREBUILT_ARTIFACT', semantic);
if ~strcmp(actual, artifact.artifact_hash)
    error('stage8_k2_tecs_validate_c1_value:Hash', ...
        'CACHE_CORRUPTION: C1 semantic artifact hash mismatch.');
end
end
