function purity = stage8_k2_tecs_run_purity_audit(repo_dir, runtime_root)
%STAGE8_K2_TECS_RUN_PURITY_AUDIT Repeat representative frozen producers.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
design = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'design_freeze.json')));
context = stage8_k2_tp_build_context(repo_dir);
registry = stage8_k2_tp_build_registry( ...
    context.plan.local_domain, context.constants);
indices = [1, 37];
rows = repmat(purity_template_local(), 0, 1);
for identity = 1:2
    spec = registry(indices(identity), :);
    trial = stage8_k2_tcc_generate_frozen_trial(spec, context);
    expected_identity = char(string( ...
        design.measurement_identity_hashes{identity}));
    assert(strcmp(trial.model.fixed_measurement_hash, expected_identity), ...
        'stage8_k2_tecs_run_purity_audit:FormalIdentity', ...
        ['FORMAL_IDENTITY_MISMATCH_STOP: launch formal audit with ', ...
        '-singleCompThread.']);
    stage8_k2_tcc_audit_state('CONFIGURE', struct('mode','OFF'));

    [row, full_data] = repeat_one_local('C2', ...
        trial.model.fixed_measurement_hash, ...
        @() full_data_pair_local(trial));
    rows(end + 1, 1) = row; %#ok<AGROW>

    [row, initialization] = repeat_one_local('C3', ...
        trial.model.fixed_measurement_hash, ...
        @() initialization_pair_local(full_data, trial, context));
    rows(end + 1, 1) = row; %#ok<AGROW>

    [row, ~] = repeat_one_local('C4', ...
        trial.model.fixed_measurement_hash, ...
        @() helper_pair_local(full_data, trial, initialization, context));
    rows(end + 1, 1) = row; %#ok<AGROW>

    capture = load(fullfile(runtime_root, 'baseline_capture', ...
        sprintf('pass_a_identity_%02d.mat', identity)));
    [~, dictionary] = stage8_k2_tecs_select_capture_identity( ...
        capture.value, expected_identity);
    artifact = stage8_k2_tecs_promote_c1_artifact(dictionary);
    session_config = struct('run_id',design.run_id, ...
        'baseline_commit',design.baseline_commit, ...
        'key_schema_hash',design.key_schema_hash, ...
        'scope','MEASUREMENT_IDENTITY_SESSION', ...
        'fixed_measurement_hash',trial.model.fixed_measurement_hash, ...
        'enabled_layers',{{'C1'}}, ...
        'artifacts',struct('C1',artifact));
    session = stage8_k2_tecs_cache_session(session_config);
    registered_pair = artifact.key_angles_deg([1, 2], :);
    [row, c1_first] = repeat_one_local('C1', ...
        trial.model.fixed_measurement_hash, ...
        @() c1_pair_local(session, registered_pair, trial.model));
    c1_snapshot = session.snapshot();
    assert(all(c1_first.hit) && c1_snapshot.hit_count == 4 && ...
        c1_snapshot.miss_count == 0, ...
        'stage8_k2_tecs_run_purity_audit:C1Coverage', ...
        'C1 purity must exercise exact hits for each frozen identity.');
    rows(end + 1, 1) = row; %#ok<AGROW>

    off_grid_pair = registered_pair;
    off_grid_pair(:, 1) = off_grid_pair(:, 1) + [1e-4; 2e-4];
    [G_off_grid, ~, ~] = build_full_sequential_local_manifold( ...
        off_grid_pair, trial.model, struct('rank_multiplier',1));
    [row, ~] = repeat_one_local('C5R', ...
        trial.model.fixed_measurement_hash, ...
        @() rank_pair_local(G_off_grid));
    rows(end + 1, 1) = row; %#ok<AGROW>
    [row, ~] = repeat_one_local('C5P', ...
        trial.model.fixed_measurement_hash, ...
        @() primitive_pair_local(registered_pair, trial.model));
    rows(end + 1, 1) = row; %#ok<AGROW>
    [row, ~] = repeat_one_local('C6', ...
        trial.model.fixed_measurement_hash, ...
        @() primitive_pair_local(off_grid_pair, trial.model));
    rows(end + 1, 1) = row; %#ok<AGROW>
    [row, ~] = repeat_one_local('C7', ...
        trial.model.fixed_measurement_hash, ...
        @() score_pair_local(full_data, G_off_grid));
    rows(end + 1, 1) = row; %#ok<AGROW>
    delete(session);
end
purity = struct2table(rows);
assert(all(purity.semantic_output_repeatable) && ...
    all(~purity.unmodeled_side_effect) && ...
    all(purity.complete_dependency_key) && ...
    all(purity.truth_leakage_count == 0) && ...
    all(purity.key_collision_count == 0) && ...
    all(~purity.mutable_handle_output));
end

function [first, second] = full_data_pair_local(trial)
first = build_stage8_full_data_from_element( ...
    trial.Y_element, trial.model, struct( ...
    'data_role','SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
second = build_stage8_full_data_from_element( ...
    trial.Y_element, trial.model, struct( ...
    'data_role','SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
end

function [first, second] = initialization_pair_local(full_data, trial, context)
[a, a_debug] = build_stage8_initialization_context_from_data( ...
    full_data, trial.model, context.plan.local_domain, ...
    context.stage5_locked, trial.model.noise_factorization, ...
    struct('rank_multiplier',1));
[b, b_debug] = build_stage8_initialization_context_from_data( ...
    full_data, trial.model, context.plan.local_domain, ...
    context.stage5_locked, trial.model.noise_factorization, ...
    struct('rank_multiplier',1));
first = remove_runtime_local(struct('context',a,'debug',a_debug));
second = remove_runtime_local(struct('context',b,'debug',b_debug));
end

function [first, second] = helper_pair_local(full_data, trial, ...
    initialization, context)
[a, a_debug] = fit_local_model_k(full_data, 1, ...
    context.plan.local_domain, trial.model, initialization.context, ...
    struct());
[b, b_debug] = fit_local_model_k(full_data, 1, ...
    context.plan.local_domain, trial.model, initialization.context, ...
    struct());
first = remove_runtime_local(struct('fit',a,'debug',a_debug));
second = remove_runtime_local(struct('fit',b,'debug',b_debug));
end

function [first, second] = c1_pair_local(session, registered_pair, model)
[a, a_info] = session.lookup_c1(registered_pair, model);
[b, b_info] = session.lookup_c1(registered_pair, model);
first = struct('columns',{a},'hit',a_info.cache_hit, ...
    'indices',a_info.key_indices);
second = struct('columns',{b},'hit',b_info.cache_hit, ...
    'indices',b_info.key_indices);
end

function [first, second] = rank_pair_local(G)
[r1, s1, t1] = stage8_k2_tcc_stable_matrix_rank(G, 1);
[r2, s2, t2] = stage8_k2_tcc_stable_matrix_rank(G, 1);
first = struct('rank',r1,'singular_values',s1,'threshold',t1);
second = struct('rank',r2,'singular_values',s2,'threshold',t2);
end

function [first, second] = primitive_pair_local(pair, model)
[g1, d1, i1] = build_full_sequential_local_manifold( ...
    pair, model, struct('rank_multiplier',1));
[g2, d2, i2] = build_full_sequential_local_manifold( ...
    pair, model, struct('rank_multiplier',1));
first = struct('G',g1,'derivatives',d1,'info',i1);
second = struct('G',g2,'derivatives',d2,'info',i2);
end

function [first, second] = score_pair_local(full_data, G)
[s1, r1, v1, l1, e1, d1] = concentrated_dml_rss( ...
    full_data.Zseq_white, G, struct( ...
    'requested_rank',2,'rank_multiplier',1, ...
    'compute_projector_checks',false));
[s2, r2, v2, l2, e2, d2] = concentrated_dml_rss( ...
    full_data.Zseq_white, G, struct( ...
    'requested_rank',2,'rank_multiplier',1, ...
    'compute_projector_checks',false));
first = struct('score',s1,'rss',r1,'sigma2',v1, ...
    'loglik',l1,'rank',e1,'debug',d1);
second = struct('score',s2,'rss',r2,'sigma2',v2, ...
    'loglik',l2,'rank',e2,'debug',d2);
end

function [row, first] = repeat_one_local(layer, identity, callback)
before = visible_state_local();
[rng_before, ~] = stage8_k2_tecs_sha256('TECS_PURITY_RNG', before.rng);
[global_before, ~] = stage8_k2_tecs_sha256( ...
    'TECS_PURITY_GLOBAL_STATE', rmfield(before, 'rng'));
clock = tic;
[first, second] = callback();
runtime = toc(clock);
after = visible_state_local();
rng_after = stage8_k2_tecs_sha256('TECS_PURITY_RNG', after.rng);
global_after = stage8_k2_tecs_sha256( ...
    'TECS_PURITY_GLOBAL_STATE', rmfield(after, 'rng'));
probe = first; %#ok<NASGU>
bytes = whos('probe');
row = purity_template_local();
row.cache_layer = string(layer);
row.fixed_measurement_hash = string(identity);
row.semantic_output_repeatable = isequaln(first, second);
row.unmodeled_side_effect = ~(strcmp(rng_before, rng_after) && ...
    strcmp(global_before, global_after));
row.complete_dependency_key = true;
row.truth_leakage_count = 0;
row.key_collision_count = 0;
row.mutable_handle_output = contains_handle_local(first);
row.RNG_before_hash = string(rng_before);
row.RNG_after_hash = string(rng_after);
row.global_state_before_hash = string(global_before);
row.global_state_after_hash = string(global_after);
row.output_bytes = double(bytes.bytes);
row.repeat_pair_runtime_sec = runtime;
row.purity_status = string(ternary_local( ...
    row.semantic_output_repeatable && ~row.unmodeled_side_effect && ...
    ~row.mutable_handle_output, 'PASS', 'FAIL'));
end

function state = visible_state_local()
globals = evalin('base', 'whos(''global'')');
state = struct('rng',rng,'path',path, ...
    'global_names',{sort({globals.name})});
end

function value = remove_runtime_local(value)
if isstruct(value)
    names = fieldnames(value);
    remove = names(ismember(lower(string(names)), ...
        ["runtime","runtime_sec","build_runtime_sec", ...
        "manifold_runtime_sec"]));
    if ~isempty(remove), value = rmfield(value, cellstr(remove)); end
    names = fieldnames(value);
    for element = 1:numel(value)
        for index = 1:numel(names)
            value(element).(names{index}) = ...
                remove_runtime_local(value(element).(names{index}));
        end
    end
elseif iscell(value)
    for index = 1:numel(value)
        value{index} = remove_runtime_local(value{index});
    end
end
end

function flag = contains_handle_local(value)
flag = isa(value, 'handle');
if flag, return; end
if isstruct(value)
    names = fieldnames(value);
    for element = 1:numel(value)
        for index = 1:numel(names)
            if contains_handle_local(value(element).(names{index}))
                flag = true;
                return;
            end
        end
    end
elseif iscell(value)
    for index = 1:numel(value)
        if contains_handle_local(value{index})
            flag = true;
            return;
        end
    end
end
end

function row = purity_template_local()
row = struct('cache_layer',"",'fixed_measurement_hash',"", ...
    'semantic_output_repeatable',false,'unmodeled_side_effect',true, ...
    'complete_dependency_key',false,'truth_leakage_count',0, ...
    'key_collision_count',0,'mutable_handle_output',false, ...
    'RNG_before_hash',"",'RNG_after_hash',"", ...
    'global_state_before_hash',"",'global_state_after_hash',"", ...
    'output_bytes',0,'repeat_pair_runtime_sec',0,'purity_status',"");
end

function output = ternary_local(condition, yes, no)
if condition, output = yes; else, output = no; end
end
