function validation = stage8_k2_tecs_validate_pass_a(repo_dir, runtime_root)
%STAGE8_K2_TECS_VALIDATE_PASS_A Re-read every Pass A artifact/checkpoint.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
design = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'design_freeze.json')));
manifest = jsondecode(fileread(fullfile(runtime_root, 'pass_a', ...
    'pass_a_manifest.json')));
saved = load(fullfile(runtime_root, 'pass_a', ...
    'pass_a_event_stream.mat'), 'output');
output = saved.output;
registry = readtable(fullfile(runtime_root, 'frozen_registry.csv'), ...
    'TextType','string');
[~, current_code_hash] = stage8_k2_tecs_code_manifest(repo_dir, 'ALL');
assert(strcmp(current_code_hash, manifest.cache_code_hash) && ...
    strcmp(output.cache_code_hash, manifest.cache_code_hash));
paths = struct( ...
    'raw',fullfile(runtime_root,'pass_a','pass_a_event_stream.mat'), ...
    'aggregate',fullfile(runtime_root,'pass_a','exposure_by_trial.csv'), ...
    'purity',fullfile(runtime_root,'pass_a','purity_audit.csv'), ...
    'disposition',fullfile(runtime_root,'pass_a','layer_disposition.csv'));
assert(strcmp(stage8_k2_tecs_sha256_file(paths.raw), ...
    manifest.event_stream_file_sha256) && ...
    strcmp(stage8_k2_tecs_sha256_file(paths.aggregate), ...
    manifest.aggregate_file_sha256) && ...
    strcmp(stage8_k2_tecs_sha256_file(paths.purity), ...
    manifest.purity_file_sha256) && ...
    strcmp(stage8_k2_tecs_sha256_file(paths.disposition), ...
    manifest.disposition_file_sha256));
assert(strcmp(stage8_k2_tcc_stable_hash( ...
    'TECS_PASS_A_COMPLETE_KEY_EVENT_STREAM', output.events), ...
    manifest.event_stream_hash) && output.event_count == 18216);
layers = ["C1","C2","C3","C4","C5R","C5P","C6","C7"];
checkpoint_dir = fullfile(runtime_root, 'pass_a', 'checkpoints');
checkpoint_files = dir(fullfile(checkpoint_dir, '*.mat'));
assert(numel(checkpoint_files) == 576 && manifest.checkpoint_count == 576);
event_row_count = 0;
aggregate_row_count = 0;
checkpoint_payload_hashes = strings(576, 1);
checkpoint_index = 0;
for trial_index = 1:height(registry)
    trial_id = registry.trial_id(trial_index);
    trial_events = output.events(output.events.trial_id == trial_id, :);
    identities = unique(trial_events.fixed_measurement_hash);
    assert(numel(identities) == 1);
    identity = identities(1);
    registry_row_hash = stage8_k2_tcc_stable_hash( ...
        'TECS_FROZEN_REGISTRY_ROW', registry(trial_index, :));
    for layer_index = 1:numel(layers)
        layer = layers(layer_index);
        checkpoint_index = checkpoint_index + 1;
        path_now = fullfile(checkpoint_dir, sprintf('%03d_%s_%s.mat', ...
            trial_index, char(trial_id), char(layer)));
        checkpoint_saved = load(path_now, 'checkpoint');
        checkpoint = checkpoint_saved.checkpoint;
        expected = struct( ...
            'checkpoint_unit_kind','AUDIT_TRIAL','pass','PASS_A', ...
            'cache_layer',char(layer), ...
            'fixed_measurement_hash',char(identity), ...
            'trial_id',char(trial_id), ...
            'schedule_row_id',trial_index, ...
            'schedule_row_hash',registry_row_hash, ...
            'run_id',design.run_id, ...
            'stage_commit_ledger_hash',manifest.stage_commit_ledger_hash, ...
            'cache_code_hash',manifest.cache_code_hash, ...
            'phase_schedule_hash',design.trial_registry_hash, ...
            'design_freeze_hash',design.freeze_payload_hash, ...
            'component_freeze_hash_or_sentinel','NOT_CLOSED');
        stage8_k2_tecs_validate_checkpoint_identity(checkpoint, expected);
        payload_hash = stage8_k2_tcc_stable_hash( ...
            'TECS_PASS_A_CHECKPOINT_PAYLOAD', checkpoint.payload);
        assert(strcmp(checkpoint.payload_hash, payload_hash));
        expected_events = output.events( ...
            output.events.trial_id == trial_id & ...
            output.events.cache_layer == layer, :);
        expected_aggregate = output.aggregate( ...
            output.aggregate.trial_id == trial_id & ...
            output.aggregate.cache_layer == layer, :);
        assert(isequaln(checkpoint.payload.events, expected_events) && ...
            isequaln(checkpoint.payload.aggregate, expected_aggregate));
        event_row_count = event_row_count + height(expected_events);
        aggregate_row_count = aggregate_row_count + ...
            height(expected_aggregate);
        checkpoint_payload_hashes(checkpoint_index) = string(payload_hash);
    end
end
assert(checkpoint_index == 576 && event_row_count == 18216 && ...
    aggregate_row_count == 576 && ...
    numel(unique(checkpoint_payload_hashes)) == 576);
allowed_exposure = ["EXACT_REUSE_EXPOSURE_PRESENT", ...
    "PREBUILT_COVERAGE_PRESENT","NO_EXACT_REUSE_EXPOSURE"];
allowed_audit = ["AUDIT_ELIGIBLE", ...
    "AUDIT_REJECTED_NO_EXACT_REUSE_EVIDENCE", ...
    "AUDIT_REJECTED_DEPENDENCY_INCOMPLETE", ...
    "AUDIT_REJECTED_PURITY_OR_SIDE_EFFECT", ...
    "AUDIT_REJECTED_COLLISION","AUDIT_REJECTED_TRUTH_LEAKAGE", ...
    "AUDIT_REJECTED_MEMORY_INFEASIBLE", ...
    "AUDIT_REJECTED_NO_ADDITIVE_SEAM"];
assert(all(ismember(output.layer_disposition.exposure_status, ...
    allowed_exposure)) && ...
    all(ismember(output.layer_disposition.audit_eligibility_status, ...
    allowed_audit)) && all(output.purity.purity_status == "PASS") && ...
    isequal(unique(output.purity.fixed_measurement_hash, 'stable'), ...
    string(design.measurement_identity_hashes(:))));
validation = struct( ...
    'schema_version','STAGE8_K2_TECS_PASS_A_VALIDATION_V1', ...
    'event_count',event_row_count,'aggregate_row_count',aggregate_row_count, ...
    'checkpoint_count',checkpoint_index, ...
    'checkpoint_payload_set_hash',stage8_k2_tcc_stable_hash( ...
    'TECS_PASS_A_CHECKPOINT_PAYLOAD_SET_V1', checkpoint_payload_hashes), ...
    'event_stream_hash',manifest.event_stream_hash, ...
    'cache_code_hash',manifest.cache_code_hash, ...
    'truth_leakage_count',output.truth_leakage_count, ...
    'key_collision_count',output.key_collision_count, ...
    'status','PASS_A_INDEPENDENT_REREAD_COMPLETE');
validation.validation_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_PASS_A_VALIDATION_V1', validation);
fprintf('TECS PASS A REREAD PASS checkpoints=%d hash=%s\n', ...
    checkpoint_index, validation.validation_hash);
end
