function output = stage8_k2_tecs_run_final_validation(repo_dir, runtime_root)
%STAGE8_K2_TECS_RUN_FINAL_VALIDATION Pass F 72x20 paired WARM timing.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
fixture = stage8_k2_tecs_build_runtime_fixture(repo_dir, runtime_root);
timing = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'timing_freeze.json')));
final = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'final_candidate_freeze.json')));
protocol = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'timing_protocol.json')));
assert(strcmp(final.status, ...
    'IMMUTABLE_FINAL_CANDIDATE_FREEZE_COMPLETE') && ...
    strcmp(final.parent_freeze_hash, timing.freeze_payload_hash), ...
    'stage8_k2_tecs_run_final_validation:FreezeChain', ...
    'The final-candidate freeze chain is invalid.');
[~, integration_hash] = stage8_k2_tecs_integration_manifest(repo_dir);
assert(strcmp(integration_hash, timing.cache_code_hash), ...
    'stage8_k2_tecs_run_final_validation:CodeDrift', ...
    'The integrated exact-cache implementation hash drifted.');
schedule = readtable(fullfile(runtime_root, 'freeze', ...
    'final_warm_schedule.csv'), 'TextType', 'string');
schedule.trial_order_key = cellstr(string(schedule.trial_order_key));
schedule.included_in_statistics = ...
    logical(schedule.included_in_statistics);
assert(height(schedule) == 1440 && ...
    strcmp(final.final_warm_schedule_hash, stage8_k2_tecs_sha256( ...
    'TECS_FINAL_WARM_SCHEDULE_V1',table2struct(schedule))));
mode_registry = readtable(fullfile(runtime_root, 'freeze', ...
    'canonical_mode_registry.csv'), 'TextType', 'string');
warmup = readtable(fullfile(runtime_root, 'freeze', ...
    'formal_warmup_registry.csv'), 'TextType', 'string');
baseline_layers = layers_for_mode_local(mode_registry, ...
    schedule.baseline_canonical_mode_id(1));
candidate_layers = layers_for_mode_local(mode_registry, ...
    schedule.candidate_canonical_mode_id(1));

pass_dir = fullfile(runtime_root, 'pass_f');
checkpoint_dir = fullfile(pass_dir, 'final_checkpoints');
if ~isfolder(pass_dir), mkdir(pass_dir); end
if ~isfolder(checkpoint_dir), mkdir(checkpoint_dir); end
paths = struct('raw',fullfile(pass_dir,'final_warm_raw_samples.csv'), ...
    'summary',fullfile(pass_dir,'final_warm_summary.csv'), ...
    'bootstrap',fullfile(pass_dir,'bootstrap_summary.json'), ...
    'manifest',fullfile(pass_dir,'final_warm_manifest.json'), ...
    'process',fullfile(pass_dir,'formal_process_snapshot.json'));
names = fieldnames(paths);
for index = 1:numel(names)
    if isfile(paths.(names{index}))
        error('stage8_k2_tecs_run_final_validation:ImmutableExists', ...
            'Final aggregate target exists: %s', paths.(names{index}));
    end
end
process = process_snapshot_local('PASS_F_FINAL_WARM');
assert(process.active_MATLAB_process_count == 1);
stage8_k2_tecs_atomic_write_json(paths.process, process);
trials = stage8_k2_tecs_prepare_trial_bank(fixture);
formal_warmup_local(trials, fixture, warmup, ...
    baseline_layers, candidate_layers);

rows = repmat(raw_template_local(), height(schedule), 1);
for schedule_index = 1:height(schedule)
    scheduled = schedule(schedule_index, :);
    checkpoint_path = fullfile(checkpoint_dir, sprintf( ...
        '%04d.mat', scheduled.schedule_row_id));
    expected = checkpoint_identity_local( ...
        fixture, timing, final, protocol, scheduled);
    if isfile(checkpoint_path)
        loaded = load(checkpoint_path, 'checkpoint');
        checkpoint = loaded.checkpoint;
        assert(checkpoint.unit_complete && ...
            checkpoint.pair_contiguous_complete && ...
            isequaln(checkpoint.identity, expected), ...
            'stage8_k2_tecs_run_final_validation:CheckpointIdentity', ...
            'CHECKPOINT_IDENTITY_MISMATCH_STOP');
        rows(schedule_index) = checkpoint.row;
        fprintf('TECS PASS F RESUME %d/%d %s\n', schedule_index, ...
            height(schedule), char(scheduled.trial_id));
        continue;
    end
    trial = trials{scheduled.global_trial_index};
    pair = run_pair_local(trial, fixture, baseline_layers, ...
        candidate_layers, char(scheduled.pair_order));
    row = raw_template_local();
    row.schedule_row_id = scheduled.schedule_row_id;
    row.schedule_row_hash = scheduled.schedule_row_hash;
    row.comparison_id = scheduled.comparison_id;
    row.comparison_kind = scheduled.comparison_kind;
    row.baseline_canonical_mode_id = ...
        scheduled.baseline_canonical_mode_id;
    row.candidate_canonical_mode_id = ...
        scheduled.candidate_canonical_mode_id;
    row.enabled_layer_set_hash = scheduled.enabled_layer_set_hash;
    row.precedence_hash = scheduled.precedence_hash;
    row.fixed_measurement_hash = scheduled.fixed_measurement_hash;
    row.global_trial_index = scheduled.global_trial_index;
    row.trial_id = scheduled.trial_id;
    row.repeat_index = scheduled.repeat_index;
    row.pair_order = scheduled.pair_order;
    row.time_off_sec = pair.time_a_sec;
    row.time_on_sec = pair.time_b_sec;
    row.paired_difference_sec = pair.time_a_sec - pair.time_b_sec;
    row.output_match = pair.output_match;
    row.cache_hit_count = pair.candidate.cache_hit_count;
    row.cache_miss_count = pair.candidate.cache_miss_count;
    row.physical_producer_call_count = ...
        pair.candidate.physical_producer_call_count;
    row.entry_count = pair.candidate.entry_count;
    row.bytes_current = pair.candidate.bytes_current;
    row.bytes_peak = pair.candidate.bytes_peak;
    row.key_collision_count = pair.candidate.key_collision_count;
    row.truth_leakage_count = pair.candidate.truth_leakage_count;
    row.pair_contiguous_complete = true;
    rows(schedule_index) = row;
    checkpoint = struct('schema_version', ...
        'STAGE8_K2_TECS_FINAL_WARM_CHECKPOINT_V1', ...
        'identity',expected,'row',row,'unit_complete',true, ...
        'pair_contiguous_complete',true);
    atomic_checkpoint_local(checkpoint_path, checkpoint);
    fprintf(['TECS PASS F RUN %d/%d %s %s d=%.9g ', ...
        'hit=%d miss=%d\n'], schedule_index, height(schedule), ...
        char(row.trial_id), char(row.pair_order), ...
        row.paired_difference_sec, row.cache_hit_count, ...
        row.cache_miss_count);
    if ~row.output_match || row.key_collision_count ~= 0 || ...
            row.truth_leakage_count ~= 0
        error('stage8_k2_tecs_run_final_validation:Correctness', ...
            'A final timed pair violated correctness/truth/collision.');
    end
end
raw = struct2table(rows);
bootstrap = stage8_k2_tecs_paired_bootstrap(raw, fixture.registry);
summary = summarize_local(raw, bootstrap);
overall = summary.aggregation_level == "OVERALL";
performance = performance_status_local(summary, raw);
stage8_k2_tecs_atomic_writetable(raw, paths.raw);
stage8_k2_tecs_atomic_writetable(summary, paths.summary);
stage8_k2_tecs_atomic_write_json(paths.bootstrap, bootstrap);
output = struct( ...
    'schema_version','STAGE8_K2_TECS_PASS_F_MANIFEST_V1', ...
    'design_freeze_hash',fixture.design.freeze_payload_hash, ...
    'component_freeze_hash',fixture.component.freeze_payload_hash, ...
    'timing_freeze_hash',timing.freeze_payload_hash, ...
    'final_candidate_freeze_hash',final.freeze_payload_hash, ...
    'timing_protocol_hash',protocol.timing_protocol_hash, ...
    'final_measurement_candidate_alias_id', ...
        final.final_measurement_candidate_alias_id, ...
    'final_measurement_candidate_canonical_mode_id', ...
        final.final_measurement_candidate_canonical_mode_id, ...
    'final_measurement_candidate_hash', ...
        final.final_measurement_candidate_hash, ...
    'raw_sample_count',height(raw),'trial_count',72, ...
    'repeat_count_per_trial',20,'AB_count',nnz(raw.pair_order == "AB"), ...
    'BA_count',nnz(raw.pair_order == "BA"), ...
    'overall_point_sec',summary.point_saving_sec(overall), ...
    'overall_lower_sec',summary.bootstrap_lower_sec(overall), ...
    'baseline_runtime_sec',summary.baseline_runtime_sec(overall), ...
    'runtime_reduction_pct',summary.runtime_reduction_pct(overall), ...
    'speedup_ratio',summary.speedup_ratio(overall), ...
    'AB_point_sec',summary.AB_point_sec(overall), ...
    'BA_point_sec',summary.BA_point_sec(overall), ...
    'performance_status',performance, ...
    'bytes_peak',max(raw.bytes_peak), ...
    'key_collision_count',sum(raw.key_collision_count), ...
    'truth_leakage_count',sum(raw.truth_leakage_count), ...
    'raw_hash',stage8_k2_tecs_sha256( ...
        'TECS_FINAL_WARM_RAW_V1',table2struct(raw)), ...
    'summary_hash',stage8_k2_tecs_sha256( ...
        'TECS_FINAL_WARM_SUMMARY_V1',table2struct(summary)), ...
    'bootstrap_implementation_hash',bootstrap.implementation_hash, ...
    'status','PASS_F_FINAL_WARM_COMPLETE');
output.raw_file_sha256 = stage8_k2_tecs_sha256_file(paths.raw);
output.summary_file_sha256 = stage8_k2_tecs_sha256_file(paths.summary);
output.manifest_payload_hash = stage8_k2_tecs_sha256( ...
    'TECS_PASS_F_MANIFEST_V1', output);
stage8_k2_tecs_atomic_write_json(paths.manifest, output);
fprintf(['TECS PASS F COMPLETE point=%.9g lower=%.9g ', ...
    'reduction=%.6f%% status=%s\n'], output.overall_point_sec, ...
    output.overall_lower_sec, output.runtime_reduction_pct, performance);
end
function pair = run_pair_local(trial, fixture, baseline_layers, ...
    candidate_layers, order)
if strcmp(order, 'AB')
    a = stage8_k2_tecs_run_root( ...
        trial, fixture.context, fixture, baseline_layers);
    b = stage8_k2_tecs_run_root( ...
        trial, fixture.context, fixture, candidate_layers);
else
    b = stage8_k2_tecs_run_root( ...
        trial, fixture.context, fixture, candidate_layers);
    a = stage8_k2_tecs_run_root( ...
        trial, fixture.context, fixture, baseline_layers);
end
match = a.fit_valid == b.fit_valid && ...
    strcmp(a.selected_source,b.selected_source) && ...
    strcmp(a.selected_start_id,b.selected_start_id) && ...
    a.logical_score_call_count == b.logical_score_call_count && ...
    a.logical_svd_call_count == b.logical_svd_call_count;
pair = struct('time_a_sec',a.elapsed_sec,'time_b_sec',b.elapsed_sec, ...
    'baseline',a,'candidate',b,'output_match',match);
end

function formal_warmup_local(trials, fixture, warmup, ...
    baseline_layers, candidate_layers)
fprintf('TECS FINAL FORMAL WARMUP START rows=%d\n', height(warmup));
for index = 1:height(warmup)
    trial = trials{warmup.global_trial_index(index)};
    run_pair_local(trial, fixture, baseline_layers, candidate_layers, 'AB');
    run_pair_local(trial, fixture, baseline_layers, candidate_layers, 'BA');
end
fprintf('TECS FINAL FORMAL WARMUP COMPLETE rows=%d\n', height(warmup));
end

function summary = summarize_local(raw, bootstrap)
trial_ids = unique(raw.trial_id, 'stable');
rows = repmat(summary_template_local(), 0, 1);
trial_points = zeros(72, 1);
trial_baselines = zeros(72, 1);
trial_ab = zeros(72, 1);
trial_ba = zeros(72, 1);
for index = 1:numel(trial_ids)
    samples = raw(raw.trial_id == trial_ids(index), :);
    sorted = sort(samples.paired_difference_sec);
    row = summary_template_local();
    row.aggregation_level = "TRIAL";
    row.scenario_aggregate = "FROZEN_TRIAL";
    row.fixed_measurement_hash = samples.fixed_measurement_hash(1);
    row.trial_id = trial_ids(index);
    row.repeat_count = 20; row.AB_count = 10; row.BA_count = 10;
    row.paired_median_sec = median(sorted);
    row.paired_p10_sec = sorted(ceil(0.10 * numel(sorted)));
    row.paired_p90_sec = sorted(ceil(0.90 * numel(sorted)));
    row.paired_min_sec = sorted(1); row.paired_max_sec = sorted(end);
    row.point_saving_sec = row.paired_median_sec;
    row.baseline_runtime_sec = median(samples.time_off_sec);
    trial_points(index) = row.point_saving_sec;
    trial_baselines(index) = row.baseline_runtime_sec;
    trial_ab(index) = median(samples.paired_difference_sec( ...
        samples.pair_order == "AB"));
    trial_ba(index) = median(samples.paired_difference_sec( ...
        samples.pair_order == "BA"));
    rows(end + 1, 1) = row; %#ok<AGROW>
end
identities = unique(raw.fixed_measurement_hash, 'stable');
for identity_index = 1:2
    member_trials = unique(raw.trial_id( ...
        raw.fixed_measurement_hash == identities(identity_index)), 'stable');
    indices = find(ismember(trial_ids, member_trials));
    row = summary_template_local();
    row.aggregation_level = "IDENTITY";
    row.scenario_aggregate = "FIXED_MEASUREMENT_IDENTITY_36_TRIALS";
    row.fixed_measurement_hash = identities(identity_index);
    row.repeat_count = 20; row.AB_count = 360; row.BA_count = 360;
    row.point_saving_sec = sum(trial_points(indices));
    bootstrap_match = strcmp(bootstrap.identity_hashes, ...
        char(identities(identity_index)));
    row.bootstrap_lower_sec = ...
        bootstrap.identity_lower_sec(bootstrap_match);
    row.baseline_runtime_sec = sum(trial_baselines(indices));
    row.runtime_reduction_pct = 100 * row.point_saving_sec / ...
        row.baseline_runtime_sec;
    row.speedup_ratio = row.baseline_runtime_sec / ...
        (row.baseline_runtime_sec - row.point_saving_sec);
    row.AB_point_sec = sum(trial_ab(indices));
    row.BA_point_sec = sum(trial_ba(indices));
    rows(end + 1, 1) = row; %#ok<AGROW>
end
row = summary_template_local();
row.aggregation_level = "OVERALL";
row.scenario_aggregate = "FIXED_72_TRIAL_FACTORIAL_WORKLOAD";
row.repeat_count = 20; row.AB_count = 720; row.BA_count = 720;
row.point_saving_sec = sum(trial_points);
row.bootstrap_lower_sec = bootstrap.overall_lower_sec;
row.baseline_runtime_sec = sum(trial_baselines);
row.runtime_reduction_pct = 100 * row.point_saving_sec / ...
    row.baseline_runtime_sec;
row.speedup_ratio = row.baseline_runtime_sec / ...
    (row.baseline_runtime_sec - row.point_saving_sec);
row.AB_point_sec = sum(trial_ab); row.BA_point_sec = sum(trial_ba);
rows(end + 1, 1) = row;
summary = struct2table(rows);
end

function status = performance_status_local(summary, raw)
overall = summary.aggregation_level == "OVERALL";
identities = summary.aggregation_level == "IDENTITY";
point = summary.point_saving_sec(overall);
if point <= 0
    status = 'MEASURED_CACHE_STACK_NONPOSITIVE';
elseif summary.bootstrap_lower_sec(overall) > 0 && ...
        all(summary.point_saving_sec(identities) >= 0) && ...
        summary.AB_point_sec(overall) >= 0 && ...
        summary.BA_point_sec(overall) >= 0 && ...
        max(raw.bytes_peak) <= 536870912
    status = 'MEASURED_CACHE_STACK_ROBUST_POSITIVE';
else
    status = 'MEASURED_CACHE_STACK_INCONCLUSIVE';
end
end

function layers = layers_for_mode_local(registry, mode_id)
match = registry.candidate_canonical_mode_id == string(mode_id);
assert(nnz(match) == 1);
value = jsondecode(char(registry.ordered_enabled_layer_set(match)));
if isempty(value), layers = cell(0, 1);
elseif ischar(value), layers = {value};
elseif iscell(value), layers = reshape(cellstr(string(value)), [], 1);
else, layers = cellstr(string(value(:)));
end
end

function identity = checkpoint_identity_local( ...
    fixture, timing, final, protocol, scheduled)
identity = struct( ...
    'checkpoint_unit_kind','FINAL_TRIAL_PAIR','pass','PASS_F', ...
    'cache_setting','PAIRED_OFF_ON','cache_layer','NOT_APPLICABLE', ...
    'variant_alias_id',final.final_measurement_candidate_alias_id, ...
    'comparison_id',char(scheduled.comparison_id), ...
    'comparison_kind','FINAL_TOTAL', ...
    'baseline_canonical_mode_id', ...
        char(scheduled.baseline_canonical_mode_id), ...
    'candidate_canonical_mode_id', ...
        char(scheduled.candidate_canonical_mode_id), ...
    'enabled_layer_set_hash',char(scheduled.enabled_layer_set_hash), ...
    'precedence_hash',char(scheduled.precedence_hash), ...
    'fixed_measurement_hash',char(scheduled.fixed_measurement_hash), ...
    'trial_id',char(scheduled.trial_id), ...
    'repeat_index',double(scheduled.repeat_index), ...
    'pair_order',char(scheduled.pair_order), ...
    'schedule_row_id',double(scheduled.schedule_row_id), ...
    'schedule_row_hash',char(scheduled.schedule_row_hash), ...
    'lifecycle_setting','WARM','identity_batch_id','NOT_APPLICABLE', ...
    'batch_repeat_index','NOT_APPLICABLE', ...
    'lifecycle_operation','NOT_APPLICABLE', ...
    'operation_repeat_index','NOT_APPLICABLE', ...
    'run_id',fixture.design.run_id, ...
    'baseline_commit',fixture.design.baseline_commit, ...
    'initial_execution_start_commit', ...
        fixture.design.initial_execution_start_commit, ...
    'stage_commit_ledger_hash', ...
        timing.stage_commit_ledger_hash_at_timing_freeze, ...
    'integration_code_commit',timing.integration_code_commit, ...
    'prompt_hash',fixture.design.execution_prompt_hash, ...
    'baseline_snapshot_hash',fixture.design.baseline_snapshot_hash, ...
    'cache_code_hash',timing.cache_code_hash, ...
    'trial_registry_hash',fixture.design.trial_registry_hash, ...
    'key_schema_hash',fixture.design.key_schema_hash, ...
    'semantic_output_projection_hash', ...
        fixture.design.semantic_output_projection_hash, ...
    'hook_allowlist_hash',fixture.design.hook_allowlist_hash, ...
    'timing_protocol_hash',protocol.timing_protocol_hash, ...
    'phase_schedule_hash',final.final_warm_schedule_hash, ...
    'final_measurement_candidate_hash', ...
        final.final_measurement_candidate_hash, ...
    'design_freeze_hash',fixture.design.freeze_payload_hash, ...
    'component_freeze_hash',fixture.component.freeze_payload_hash, ...
    'timing_freeze_hash',timing.freeze_payload_hash, ...
    'final_candidate_freeze_hash',final.freeze_payload_hash, ...
    'MATLAB_release',version('-release'),'singleCompThread',true, ...
    'cache_reset_lifecycle_rule', ...
        'PRISTINE_SESSION_BEFORE_EACH_PAIR_EDGE');
end

function process = process_snapshot_local(pass_id)
[status, text] = system([ ...
    'powershell -NoProfile -Command "', ...
    '(Get-Process -Name MATLAB -ErrorAction SilentlyContinue | ', ...
    'Measure-Object).Count"']);
count = str2double(strtrim(text));
if status ~= 0 || ~isfinite(count), count = NaN; end
process = struct('schema_version','STAGE8_K2_TECS_PROCESS_SNAPSHOT_V1', ...
    'pass',pass_id,'active_MATLAB_process_count',count, ...
    'formal_MATLAB_process_limit',1,'parallel_pool_enabled',false, ...
    'singleCompThread',true,'captured_at_utc', ...
        char(datetime('now','TimeZone','UTC', ...
        'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z''')));
end

function row = raw_template_local()
row = struct('schema_version',"STAGE8_K2_TECS_FINAL_RAW_V1", ...
    'schedule_row_id',0,'schedule_row_hash',"", ...
    'comparison_id',"",'comparison_kind',"FINAL_TOTAL", ...
    'baseline_canonical_mode_id',"", ...
    'candidate_canonical_mode_id',"",'enabled_layer_set_hash',"", ...
    'precedence_hash',"",'fixed_measurement_hash',"", ...
    'global_trial_index',0,'trial_id',"",'repeat_index',0, ...
    'pair_order',"",'time_off_sec',NaN,'time_on_sec',NaN, ...
    'paired_difference_sec',NaN,'output_match',false, ...
    'cache_hit_count',0,'cache_miss_count',0, ...
    'physical_producer_call_count',0,'entry_count',0, ...
    'bytes_current',0,'bytes_peak',0,'key_collision_count',0, ...
    'truth_leakage_count',0,'pair_contiguous_complete',false);
end

function row = summary_template_local()
row = struct('schema_version',"STAGE8_K2_TECS_RUNTIME_SUMMARY_V1", ...
    'lifecycle_setting',"WARM",'aggregation_level',"", ...
    'scenario_aggregate',"",'fixed_measurement_hash',"", ...
    'trial_id',"",'repeat_count',0,'AB_count',0,'BA_count',0, ...
    'paired_median_sec',NaN,'paired_p10_sec',NaN, ...
    'paired_p90_sec',NaN,'paired_min_sec',NaN,'paired_max_sec',NaN, ...
    'point_saving_sec',NaN,'bootstrap_lower_sec',NaN, ...
    'baseline_runtime_sec',NaN,'runtime_reduction_pct',NaN, ...
    'speedup_ratio',NaN,'AB_point_sec',NaN,'BA_point_sec',NaN, ...
    'bootstrap_resample_count',10000, ...
    'bootstrap_order_statistic_index',500);
end

function atomic_checkpoint_local(path_now, checkpoint)
temporary = [path_now, '.tmp'];
save(temporary, 'checkpoint', '-v7.3');
movefile(temporary, path_now, 'f');
end
