function manifest = stage8_k2_tecs_write_evidence(repo_dir,runtime_root)
%STAGE8_K2_TECS_WRITE_EVIDENCE Write aggregate Stage8 K2 TECS evidence.

scope=stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
repo_dir=char(java.io.File(char(string(repo_dir))).getCanonicalPath());
fixture=stage8_k2_tecs_build_runtime_fixture(repo_dir,runtime_root);
timing=jsondecode(fileread(fullfile(runtime_root,'freeze','timing_freeze.json')));
final=jsondecode(fileread(fullfile(runtime_root,'freeze','final_candidate_freeze.json')));
screening_manifest=jsondecode(fileread(fullfile(runtime_root,'pass_e','screening_manifest.json')));
final_manifest=jsondecode(fileread(fullfile(runtime_root,'pass_f','final_warm_manifest.json')));
lifecycle_manifest=jsondecode(fileread(fullfile(runtime_root,'lifecycle','lifecycle_manifest.json')));
stage_manifest=jsondecode(fileread(fullfile(runtime_root,'stage_diagnostics', ...
    'stage_reconciliation_manifest.json')));
correctness_manifest=jsondecode(fileread(fullfile(runtime_root,'pass_c_d', ...
    'correctness_manifest.json')));
assert(strcmp(final_manifest.status,'PASS_F_FINAL_WARM_COMPLETE') && ...
    strcmp(lifecycle_manifest.status,'LIFECYCLE_VALIDATION_COMPLETE') && ...
    strcmp(stage_manifest.status,'STAGE_RECONCILIATION_COMPLETE'));

prefix=fullfile(repo_dir,'innovation-mining','53_stage8_k2_tangent_exact_cache_stack_');
paths=struct('validation',[prefix,'validation.md'], ...
    'manifest',[prefix,'manifest.json'],'exposure',[prefix,'exposure.csv'], ...
    'correctness',[prefix,'correctness.csv'],'screening',[prefix,'screening.csv'], ...
    'runtime',[prefix,'runtime_summary.csv'],'lifecycle',[prefix,'lifecycle.csv'], ...
    'economics',[prefix,'economics.csv']);
names=fieldnames(paths);
for index=1:numel(names)
    if isfile(paths.(names{index}))
        error('stage8_k2_tecs_write_evidence:ImmutableExists', ...
            'Evidence target exists: %s',paths.(names{index}));
    end
end
exposure=build_exposure_local(runtime_root);
correctness=readtable(fullfile(runtime_root,'pass_c_d', ...
    'correctness_summary.csv'),'TextType','string');
screening=build_screening_local(runtime_root,screening_manifest);
[recommendation,retention,final_mode]=decision_local( ...
    final_manifest.performance_status,final,fixture,runtime_root);
runtime=build_runtime_local(runtime_root,final_manifest,final, ...
    recommendation,retention,final_mode);
lifecycle=readtable(fullfile(runtime_root,'lifecycle', ...
    'lifecycle_summary.csv'),'TextType','string');
lifecycle.cache_candidate_canonical_mode_id(:)=string( ...
    final.final_measurement_candidate_canonical_mode_id);
economics=build_economics_local(runtime,final_manifest,lifecycle_manifest, ...
    final,recommendation,retention,final_mode);
stage8_k2_tecs_atomic_writetable(exposure,paths.exposure);
stage8_k2_tecs_atomic_writetable(correctness,paths.correctness);
stage8_k2_tecs_atomic_writetable(screening,paths.screening);
stage8_k2_tecs_atomic_writetable(runtime,paths.runtime);
stage8_k2_tecs_atomic_writetable(lifecycle,paths.lifecycle);
stage8_k2_tecs_atomic_writetable(economics,paths.economics);

head=git_output_local(repo_dir,'rev-parse HEAD');
ledger_hash=stage8_k2_tecs_sha256_file(fullfile(runtime_root, ...
    'stage_commit_ledger.json'));
freeze_chain=stage8_k2_tecs_sha256('TECS_FREEZE_CHAIN_V1',struct( ...
    'design',fixture.design.freeze_payload_hash, ...
    'component',fixture.component.freeze_payload_hash, ...
    'timing',timing.freeze_payload_hash,'final',final.freeze_payload_hash));
result_hashes=struct( ...
    'freeze_csv',stage8_k2_tecs_sha256_file([prefix,'freeze.csv']), ...
    'exposure_csv',stage8_k2_tecs_sha256_file(paths.exposure), ...
    'correctness_csv',stage8_k2_tecs_sha256_file(paths.correctness), ...
    'screening_csv',stage8_k2_tecs_sha256_file(paths.screening), ...
    'runtime_summary_csv',stage8_k2_tecs_sha256_file(paths.runtime), ...
    'lifecycle_csv',stage8_k2_tecs_sha256_file(paths.lifecycle), ...
    'economics_csv',stage8_k2_tecs_sha256_file(paths.economics));
manifest=struct( ...
    'schema_version','STAGE8_K2_TECS_MANIFEST_V1', ...
    'branch','experiment/stage8-k2-tangent-canonical-cache-v1', ...
    'level_a_closure_commit','cf35e37a74366a8d9829de3a1f8b740a788bade1', ...
    'placement_audit_code_commit','354109c80203c7100f255aaf54aef4150b436ea6', ...
    'placement_audit_evidence_commit','efd040c7c9936eb40b08e9eef60f57b80dbfda65', ...
    'exact_cache_stack_baseline_commit',fixture.design.baseline_commit, ...
    'execution_start_commit',fixture.design.execution_start_commit, ...
    'initial_execution_start_commit',fixture.design.initial_execution_start_commit, ...
    'current_head_at_evidence_write_base',head,'run_id',fixture.design.run_id, ...
    'stage_commit_ledger_hash_at_evidence_write_base',ledger_hash, ...
    'integration_code_commit',timing.integration_code_commit, ...
    'evidence_write_base_commit',head, ...
    'prompt_hash',fixture.design.execution_prompt_hash, ...
    'design_freeze_hash',fixture.design.freeze_payload_hash, ...
    'component_freeze_hash',fixture.component.freeze_payload_hash, ...
    'timing_freeze_hash',timing.freeze_payload_hash, ...
    'final_candidate_freeze_hash',final.freeze_payload_hash, ...
    'freeze_chain_hash',freeze_chain, ...
    'baseline_snapshot_hash',fixture.design.baseline_snapshot_hash, ...
    'semantic_output_projection_hash',fixture.design.semantic_output_projection_hash, ...
    'hook_allowlist_hash',fixture.design.hook_allowlist_hash, ...
    'cache_code_hash',timing.cache_code_hash, ...
    'trial_registry_hash',fixture.design.trial_registry_hash, ...
    'key_schema_hash',fixture.design.key_schema_hash, ...
    'component_protocol_hash',fixture.component.component_protocol_hash, ...
    'component_schedule_hash',fixture.component.component_schedule_hash, ...
    'timing_protocol_hash',timing.timing_protocol_hash, ...
    'screening_schedule_hash',timing.screening_schedule_hash, ...
    'final_warm_schedule_hash',final.final_warm_schedule_hash, ...
    'cold_lifecycle_schedule_hash',final.cold_lifecycle_schedule_hash, ...
    'formal_warmup_registry_hash',timing.formal_warmup_registry_hash, ...
    'canonical_mode_registry_hash',timing.canonical_mode_registry_hash, ...
    'mode_alias_registry_hash',timing.mode_alias_registry_hash, ...
    'precedence_hash',read_json_field_local(runtime_root, ...
        'c5_precedence_fallback_rule.json','precedence_hash'), ...
    'fallback_hash',read_json_field_local(runtime_root, ...
        'c5_precedence_fallback_rule.json','fallback_hash'), ...
    'candidate_model_registry_hash',timing.candidate_model_registry_hash, ...
    'representative_alias_rule_hash',timing.representative_alias_rule_hash, ...
    'final_measurement_candidate_hash',final.final_measurement_candidate_hash, ...
    'final_measurement_candidate_alias_id',final.final_measurement_candidate_alias_id, ...
    'final_measurement_candidate_canonical_mode_id', ...
        final.final_measurement_candidate_canonical_mode_id, ...
    'recommended_runtime_mode_after_screening', ...
        screening_manifest.recommended_runtime_mode_after_screening, ...
    'screening_status',screening_manifest.screening_status, ...
    'MATLAB_release','R2022b','single_comp_thread',true,'trial_count',72, ...
    'measurement_identity_count',2, ...
    'canonical_cache_mode_ids',{cellstr(unique( ...
        screening.candidate_canonical_mode_id( ...
        screening.candidate_canonical_mode_id~="")))}, ...
    'admitted_layers',{{'C1'}}, ...
    'rejected_layers',{{'C2','C3','C4','C5R','C5P','C6','C7'}}, ...
    'correctness_status','PASS_C_D_72_OF_72', ...
    'performance_status',final_manifest.performance_status, ...
    'cold_build_point_status',lifecycle_manifest.cold_build_point_status, ...
    'cold_load_point_status',lifecycle_manifest.cold_load_point_status, ...
    'cold_build_break_even_status',lifecycle_manifest.cold_build_break_even_status, ...
    'cold_load_break_even_status',lifecycle_manifest.cold_load_break_even_status, ...
    'frozen_model_id',final.frozen_model_id, ...
    'frozen_model_hash',final.frozen_model_hash, ...
    'frozen_model_status',final.frozen_model_status, ...
    'model_residual_status','NOT_AVAILABLE_NO_MATCHED_FROZEN_MODEL', ...
    'deployment_status','NOT_ASSESSED_NO_WORKLOAD_HORIZON', ...
    'final_recommendation_status',recommendation, ...
    'layer_set_retention_status',retention, ...
    'final_recommended_experiment_mode',final_mode, ...
    'final_production_default_cache_setting','CACHE_OFF', ...
    'final_enabled_layers',{{'C1'}},'result_hashes',result_hashes, ...
    'stage_reconciliation_hash',stage_manifest.manifest_payload_hash, ...
    'completion_status','STAGE8_K2_TANGENT_EXACT_CACHE_STACK_VALIDATION_COMPLETE');
manifest.manifest_payload_hash=stage8_k2_tecs_sha256( ...
    'TECS_FINAL_EVIDENCE_MANIFEST_V1',manifest);
stage8_k2_tecs_atomic_write_json(paths.manifest,manifest);
markdown=build_markdown_local(manifest,final_manifest,lifecycle_manifest, ...
    screening_manifest,correctness_manifest,economics);
atomic_write_text_local(paths.validation,markdown);
fprintf('TECS EVIDENCE COMPLETE manifest=%s status=%s\n', ...
    manifest.manifest_payload_hash,manifest.completion_status);
end

function exposure=build_exposure_local(runtime_root)
exposure=readtable(fullfile(runtime_root,'pass_a','exposure_by_trial.csv'), ...
    'TextType','string');
disposition=readtable(fullfile(runtime_root,'pass_a','layer_disposition.csv'), ...
    'TextType','string');
component=readtable(fullfile(runtime_root,'pass_b','component_summary.csv'), ...
    'TextType','string');
n=height(exposure);exposure.predicted_net_saving_sec=NaN(n,1);
exposure.predicted_net_saving_source=repmat("NOT_MEASURED_PER_TRIAL",n,1);
exposure.component_repeat_count=zeros(n,1);exposure.component_AB_count=zeros(n,1);
exposure.component_BA_count=zeros(n,1);exposure.component_point_sec=NaN(n,1);
exposure.audit_eligibility_status=strings(n,1);exposure.integration_status=strings(n,1);
for index=1:height(disposition)
    member=exposure.cache_layer==disposition.cache_layer(index);
    exposure.audit_eligibility_status(member)= ...
        disposition.audit_eligibility_status(index);
    exposure.integration_status(member)=disposition.integration_status(index);
end
member=exposure.cache_layer=="C1";
overall=component.fixed_measurement_hash=="OVERALL_2_IDENTITIES";
exposure.component_repeat_count(member)=30;
exposure.component_AB_count(member)=15;exposure.component_BA_count(member)=15;
exposure.component_point_sec(member)=component.component_point_sec(overall);
exposure.predicted_net_saving_sec(member)=component.component_point_sec(overall);
exposure.predicted_net_saving_source(member)= ...
    "FROZEN_COMPONENT_REPLAY_OVERALL_POINT";
exposure.integration_status(member)="INTEGRATED";
end

function screening=build_screening_local(runtime_root,manifest)
screening=readtable(fullfile(runtime_root,'pass_e','screening_summary.csv'), ...
    'TextType','string');
screening.screening_status(:)=string(manifest.screening_status);
screening.recommended_runtime_mode_after_screening(:)=string( ...
    manifest.recommended_runtime_mode_after_screening);
screening.final_measurement_candidate_alias_id(:)=string( ...
    manifest.final_measurement_candidate_alias_id);
screening.final_measurement_candidate_canonical_mode_id(:)=string( ...
    manifest.final_measurement_candidate_canonical_mode_id);
candidate=screening.candidate_canonical_mode_id==string( ...
    manifest.final_measurement_candidate_canonical_mode_id) & ...
    screening.comparison_kind=="TOTAL";
screening.final_candidate_eligible(candidate)=true;
end

function runtime=build_runtime_local(runtime_root,pass,final, ...
    recommendation,retention,final_mode)
runtime=readtable(fullfile(runtime_root,'pass_f','final_warm_summary.csv'), ...
    'TextType','string');n=height(runtime);
runtime.final_measurement_candidate_alias_id=repmat(string( ...
    final.final_measurement_candidate_alias_id),n,1);
runtime.final_measurement_candidate_canonical_mode_id=repmat(string( ...
    final.final_measurement_candidate_canonical_mode_id),n,1);
runtime.recommended_runtime_mode_after_screening=repmat(string( ...
    jsondecode(fileread(fullfile(runtime_root,'pass_e', ...
    'screening_manifest.json'))).recommended_runtime_mode_after_screening),n,1);
runtime.timing_protocol_hash=repmat(string(jsondecode(fileread(fullfile( ...
    runtime_root,'freeze','timing_protocol.json'))).timing_protocol_hash),n,1);
runtime.frozen_model_id=repmat(string(final.frozen_model_id),n,1);
runtime.frozen_model_hash=repmat(string(final.frozen_model_hash),n,1);
runtime.frozen_model_status=repmat(string(final.frozen_model_status),n,1);
runtime.model_residual_status=repmat( ...
    "NOT_AVAILABLE_NO_MATCHED_FROZEN_MODEL",n,1);
runtime.final_recommendation_status=repmat(string(recommendation),n,1);
runtime.layer_set_retention_status=repmat(string(retention),n,1);
runtime.final_recommended_experiment_mode=repmat(string(final_mode),n,1);
runtime.performance_status=repmat(string(pass.performance_status),n,1);
end

function economics=build_economics_local(runtime,pass,lifecycle,final, ...
    recommendation,retention,final_mode)
overall=runtime.aggregation_level=="OVERALL";identities=runtime.aggregation_level=="IDENTITY";
baseline=runtime.baseline_runtime_sec(overall);saving=runtime.point_saving_sec(overall);
economics=table(364.872219,baseline-saving,saving, ...
    runtime.runtime_reduction_pct(overall),runtime.speedup_ratio(overall), ...
    runtime.bootstrap_lower_sec(overall),min(runtime.point_saving_sec(identities)), ...
    runtime.AB_point_sec(overall),runtime.BA_point_sec(overall),NaN,NaN,NaN, ...
    baseline,NaN,NaN,string(final.frozen_model_id),string(final.frozen_model_hash), ...
    string(final.frozen_model_status),"NOT_AVAILABLE_NO_MATCHED_FROZEN_MODEL", ...
    string(pass.performance_status),string(lifecycle.cold_build_point_status), ...
    string(lifecycle.cold_load_point_status), ...
    string(lifecycle.cold_build_break_even_status), ...
    string(lifecycle.cold_load_break_even_status), ...
    "NOT_ASSESSED_NO_WORKLOAD_HORIZON",string(recommendation),string(retention), ...
    string(final_mode),"CACHE_OFF", ...
    'VariableNames',{'historical_baseline_T0','measured_cache_stack_runtime', ...
    'measured_saving_sec','measured_runtime_reduction_pct','measured_speedup_ratio', ...
    'bootstrap_lower_sec','identity_min_point_sec','AB_point_sec','BA_point_sec', ...
    'frozen_model_point_sec','frozen_model_historical_baseline_pct', ...
    'frozen_model_pct_on_final_baseline','final_measured_baseline_sec', ...
    'runtime_interaction_residual_sec','runtime_interaction_residual_pct_on_final_baseline', ...
    'frozen_model_id','frozen_model_hash','frozen_model_status','model_residual_status', ...
    'performance_status','cold_build_point_status','cold_load_point_status', ...
    'cold_build_break_even_status','cold_load_break_even_status','deployment_status', ...
    'final_recommendation_status','layer_set_retention_status', ...
    'final_recommended_experiment_mode','final_production_default_cache_setting'});
economics.schema_version=repmat("STAGE8_K2_TECS_ECONOMICS_V1", ...
    height(economics),1);
economics=movevars(economics,'schema_version','Before',1);
end

function [recommendation,retention,mode]=decision_local(status,final,fixture,runtime_root)
if strcmp(status,'MEASURED_CACHE_STACK_ROBUST_POSITIVE')
    recommendation='RECOMMEND_PRODUCTIONIZATION_STUDY';
    retention='RETAIN_ALL_LAYERS_IN_FROZEN_CANDIDATE';
    mode=final.final_measurement_candidate_canonical_mode_id;
elseif strcmp(status,'MEASURED_CACHE_STACK_INCONCLUSIVE')
    recommendation='RETAIN_EXPERIMENTAL_EXACT_CACHE_STACK';
    retention='NO_RUNTIME_CACHE_LAYER_RETAINED';
    modes=stage8_k2_tecs_build_mode_registry(runtime_root);
    mode=char(modes.aliases.candidate_canonical_mode_id( ...
        modes.aliases.variant_alias_id=="M0"));
else
    recommendation='DO_NOT_RETAIN_NONPOSITIVE_LAYERS';
    retention='NO_RUNTIME_CACHE_LAYER_RETAINED';
    modes=stage8_k2_tecs_build_mode_registry(runtime_root);
    mode=char(modes.aliases.candidate_canonical_mode_id( ...
        modes.aliases.variant_alias_id=="M0"));
end
assert(strcmp(fixture.design.production_default_cache_setting,'CACHE_OFF'));
end

function text=build_markdown_local(manifest,pass,lifecycle,screening,correctness,economics)
e=economics(1,:);
lines=["# Stage8 K2 Tangent Exact Cache Stack Validation";""; ...
"## Outcome";""; ...
"- Completion: `"+string(manifest.completion_status)+"`"; ...
"- Correctness: `"+string(manifest.correctness_status)+"`"; ...
"- Performance: `"+string(pass.performance_status)+"`"; ...
"- Final recommendation: `"+string(manifest.final_recommendation_status)+"`"; ...
"- Production default: `CACHE_OFF`";"";"## Measured WARM result";""; ...
sprintf('- Paired point saving: %.9g s',e.measured_saving_sec); ...
sprintf('- One-sided 95%% lower bound: %.9g s',e.bootstrap_lower_sec); ...
sprintf('- Runtime reduction: %.6f%%',e.measured_runtime_reduction_pct); ...
sprintf('- Speedup ratio: %.9g',e.measured_speedup_ratio); ...
sprintf('- AB / BA points: %.9g s / %.9g s',e.AB_point_sec,e.BA_point_sec); ...
"";"## Exposure and correctness";""; ...
sprintf('- Pass C/D: %d/72; CACHE_OFF qualification: %d/72', ...
correctness.M1_correctness_pass_count, ...
correctness.post_hook_cache_off_qualification_pass_count); ...
sprintf('- Integrated C1 hook: %d hit, %d miss; collision=%d; truth leakage=%d', ...
correctness.cache_hit_count,correctness.cache_miss_count, ...
correctness.key_collision_count,correctness.truth_leakage_count); ...
"- C2-C4: rejected because no frozen additive seam."; ...
"- C5R/C5P/C6/C7: rejected because the legal scope had no exact reuse evidence."; ...
"";"## Theory boundaries (not interchangeable)";""; ...
"- `0.600809%`: conditional direct-G to lookup increment."; ...
"- `3.715591%`: C1 + structural gross zero-C2-C4-overhead hypothesis."; ...
"- `3.765156%`: adds a zero-incremental-C5R-hit-cost hypothesis."; ...
"- `3.952132%`: additive known-exposure G-dictionary zero-lookup ceiling."; ...
"- `4.001697%`: additive known-exposure primitive zero-hit-cost ceiling."; ...
"- `4.345031%`: prior structural+G-only+cache model, not a cache-only target."; ...
"";"## Lifecycle";""; ...
"- "+string(lifecycle.cold_build_point_status); ...
"- "+string(lifecycle.cold_load_point_status); ...
"- "+string(lifecycle.cold_build_break_even_status); ...
"- "+string(lifecycle.cold_load_break_even_status); ...
"";"## Provenance";""; ...
"- Integration commit: `"+string(manifest.integration_code_commit)+"`"; ...
"- Evidence write base: `"+string(manifest.evidence_write_base_commit)+"`"; ...
"- Run ID: `"+string(manifest.run_id)+"`"; ...
"- Freeze chain: `"+string(manifest.freeze_chain_hash)+"`"; ...
"- Screening status: `"+string(screening.screening_status)+"`"; ...
"";"No causal cache/Tangent synergy or deployment justification is claimed."];
text=[strjoin(cellstr(lines),newline),newline];
end

function value=read_json_field_local(runtime_root,name,field)
record=jsondecode(fileread(fullfile(runtime_root,'freeze',name)));value=record.(field);
end

function value=git_output_local(repo_dir,command)
[status,value]=system(sprintf('git -C "%s" %s',repo_dir,command)); ...
    if status~=0
        error('stage8_k2_tecs_write_evidence:Git', ...
            'Git command failed: %s.', command);
    end
    value=strtrim(value);
end

function atomic_write_text_local(path_now,value)
temporary=[path_now,'.tmp'];fid=fopen(temporary,'w');
if fid<0
    error('stage8_k2_tecs_write_evidence:TextOpen', ...
        'Unable to open evidence text output: %s.', path_now);
end
cleanup=onCleanup(@()fclose(fid));fwrite(fid,unicode2native(char(value),'UTF-8'),'uint8');
clear cleanup;movefile(temporary,path_now,'f');
end
