function session = stage8_k2_tecs_make_session(fixture, identity_hash, layers)
%STAGE8_K2_TECS_MAKE_SESSION Restore a pristine explicit cache session.

if nargin < 3 || isempty(layers), layers = {'C1'}; end
layers = cellstr(upper(string(layers)));
identity = stage8_k2_tecs_identity_fixture(fixture, identity_hash);
artifacts = struct();
if any(strcmp(layers, 'C1'))
    artifacts.C1 = identity.artifact;
end
config = struct( ...
    'run_id', fixture.design.run_id, ...
    'baseline_commit', fixture.design.baseline_commit, ...
    'key_schema_hash', fixture.design.key_schema_hash, ...
    'scope', 'MEASUREMENT_IDENTITY_SESSION', ...
    'fixed_measurement_hash', identity.fixed_measurement_hash, ...
    'enabled_layers', {layers}, 'artifacts', artifacts, ...
    'memory_limit_bytes', fixture.design.cache_memory_peak_limit_bytes);
session = stage8_k2_tecs_cache_session(config);
end
