function manifest = stage8_k2_tecs_run_static_certification(repo_dir, runtime_root)
%STAGE8_K2_TECS_RUN_STATIC_CERTIFICATION Persist the commit-1 static gate.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
pass_dir = fullfile(runtime_root, 'pass_b');
if ~isfolder(pass_dir), mkdir(pass_dir); end
summary_path = fullfile(pass_dir, 'static_test_summary.csv');
manifest_path = fullfile(pass_dir, 'static_test_manifest.json');
if isfile(summary_path) || isfile(manifest_path)
    error('stage8_k2_tecs_run_static_certification:ImmutableExists', ...
        'Static certification target already exists.');
end
design = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'design_freeze.json')));
pass_a = jsondecode(fileread(fullfile(runtime_root, 'pass_a', ...
    'pass_a_manifest.json')));
[code_manifest, cache_code_hash] = ...
    stage8_k2_tecs_code_manifest(repo_dir, 'ALL');
[component_manifest, component_code_hash] = ...
    stage8_k2_tecs_code_manifest(repo_dir, 'COMPONENT_CORE');
pass_a_validation = stage8_k2_tecs_validate_pass_a(repo_dir, runtime_root);
summary = stage8_k2_tecs_run_tests(repo_dir, runtime_root);
assert(all(summary.pass));
summary_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_PASS_B_STATIC_TEST_SUMMARY_V1', summary);
stage8_k2_tecs_atomic_writetable(summary, summary_path);
manifest = struct( ...
    'schema_version','STAGE8_K2_TECS_PASS_B_STATIC_MANIFEST_V1', ...
    'design_freeze_hash',design.freeze_payload_hash, ...
    'pass_a_event_stream_hash',pass_a.event_stream_hash, ...
    'pass_a_validation_hash',pass_a_validation.validation_hash, ...
    'pass_a_checkpoint_count',pass_a_validation.checkpoint_count, ...
    'cache_code_hash',cache_code_hash, ...
    'component_prototype_code_hash',component_code_hash, ...
    'complete_code_file_count',height(code_manifest), ...
    'component_core_file_count',height(component_manifest), ...
    'tecs_test_pass_count',nnz(summary.pass), ...
    'tecs_test_total_count',height(summary), ...
    'existing_tcc_test_pass_count',8, ...
    'existing_tcc_test_total_count',8, ...
    'C1_single_pass_count',42,'C1_single_total_count',42, ...
    'C1_pair_pass_count',462,'C1_pair_total_count',462, ...
    'C1_ordered_pass_count',882,'C1_ordered_total_count',882, ...
    'static_summary_hash',summary_hash, ...
    'static_summary_file_sha256', ...
    stage8_k2_tecs_sha256_file(summary_path), ...
    'truth_leakage_count',0,'key_collision_count',0, ...
    'status','PASS_B_PROTOTYPE_STATIC_CERTIFICATION_COMPLETE');
manifest.manifest_payload_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_PASS_B_STATIC_MANIFEST_V1', manifest);
stage8_k2_tecs_atomic_write_json(manifest_path, manifest);
fprintf('TECS PASS B STATIC COMPLETE %d/%d hash=%s\n', ...
    nnz(summary.pass), height(summary), summary_hash);
end
