function fixture = stage8_k2_tecs_build_runtime_fixture(repo_dir, runtime_root)
%STAGE8_K2_TECS_BUILD_RUNTIME_FIXTURE Load frozen trials and C1 identities.

repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
runtime_root = char(java.io.File(char(string(runtime_root))).getCanonicalPath());
design = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'design_freeze.json')));
component = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'component_freeze.json')));
baseline_manifest = jsondecode(fileread(fullfile(runtime_root, ...
    'baseline', 'baseline_snapshot_manifest.json')));
assert(strcmp(design.status, 'IMMUTABLE_DESIGN_FREEZE_COMPLETE') && ...
    strcmp(component.status, 'IMMUTABLE_COMPONENT_FREEZE_COMPLETE') && ...
    strcmp(baseline_manifest.baseline_snapshot_status, ...
    'IMMUTABLE_COMPLETE'), ...
    'stage8_k2_tecs_build_runtime_fixture:FreezeState');
assert(strcmp(component.parent_freeze_hash, design.freeze_payload_hash) && ...
    strcmp(design.baseline_snapshot_hash, ...
    baseline_manifest.baseline_snapshot_hash), ...
    'stage8_k2_tecs_build_runtime_fixture:FreezeChain');

registry = readtable(fullfile(runtime_root, 'frozen_registry.csv'), ...
    'TextType', 'string');
assert(height(registry) == 72 && ...
    isequal(double(registry.global_trial_index), (1:72).'), ...
    'stage8_k2_tecs_build_runtime_fixture:Registry');
context = stage8_k2_tp_build_context(repo_dir);
rebuilt_registry = stage8_k2_tp_build_registry( ...
    context.plan.local_domain, context.constants);
registry_hash = stage8_k2_tcc_stable_hash( ...
    'PLACEMENT_AUDIT_REGISTRY', rebuilt_registry);
assert(strcmp(registry_hash, design.trial_registry_hash) && ...
    isequal(string(rebuilt_registry.trial_id), string(registry.trial_id)), ...
    'stage8_k2_tecs_build_runtime_fixture:RegistryHash');

saved = load(fullfile(runtime_root, 'baseline', ...
    'cache_off_semantic_outputs.mat'), 'semantic_snapshot');
semantic_snapshot = saved.semantic_snapshot;
assert(semantic_snapshot.trial_count == 72 && ...
    strcmp(semantic_snapshot.registry_hash, design.trial_registry_hash), ...
    'stage8_k2_tecs_build_runtime_fixture:BaselineSnapshot');

identity_count = numel(design.measurement_identity_hashes);
identities = repmat(struct('fixed_measurement_hash', '', ...
    'model', struct(), 'dictionary', struct(), 'artifact', struct()), ...
    identity_count, 1);
for identity_index = 1:identity_count
    expected = char(string( ...
        design.measurement_identity_hashes{identity_index}));
    capture = load(fullfile(runtime_root, 'baseline_capture', ...
        sprintf('pass_a_identity_%02d.mat', identity_index)));
    [model, dictionary] = stage8_k2_tecs_select_capture_identity( ...
        capture.value, expected);
    artifact = stage8_k2_tecs_promote_c1_artifact(dictionary);
    immutable_path = fullfile(runtime_root, 'artifacts', ...
        ['C1_', expected, '.mat']);
    if isfile(immutable_path)
        artifact = stage8_k2_tecs_validate_c1_artifact( ...
            immutable_path, expected);
    end
    assert(strcmp(model.fixed_measurement_hash, expected) && ...
        strcmp(artifact.fixed_measurement_hash, expected), ...
        'stage8_k2_tecs_build_runtime_fixture:Identity');
    identities(identity_index).fixed_measurement_hash = expected;
    identities(identity_index).model = model;
    identities(identity_index).dictionary = dictionary;
    identities(identity_index).artifact = artifact;
end

fixture = struct( ...
    'schema_version', 'STAGE8_K2_TECS_RUNTIME_FIXTURE_V1', ...
    'repo_dir', repo_dir, 'runtime_root', runtime_root, ...
    'design', design, 'component', component, ...
    'baseline_manifest', baseline_manifest, 'registry', registry, ...
    'context', context, 'semantic_snapshot', semantic_snapshot, ...
    'identities', identities);
end
