function [G, manifold_info, provider_info] = ...
    stage8_k2_tecs_provider_pair(angles_deg, model, provider, options)
%STAGE8_K2_TECS_PROVIDER_PAIR C1 exact hit with frozen legacy miss path.

if nargin < 4 || isempty(options), options = struct(); end
if ~(isstruct(provider) && isscalar(provider) && ...
        isfield(provider, 'mode') && ...
        strcmp(provider.mode, 'TECS_EXACT_STACK') && ...
        isfield(provider, 'cache_session') && ...
        isa(provider.cache_session, 'stage8_k2_tecs_cache_session'))
    error('stage8_k2_tecs_provider_pair:Provider', ...
        'A TECS provider with an explicit session is required.');
end
if ~(isa(angles_deg, 'double') && isequal(size(angles_deg), [2, 2]) && ...
        all(isfinite(angles_deg(:))))
    error('stage8_k2_tecs_provider_pair:Angles', ...
        'angles_deg must be a finite double 2-by-2 ordered tuple.');
end
session = provider.cache_session;
timing_enabled = isfield(provider, 'per_call_timing_enabled') && ...
    isequal(provider.per_call_timing_enabled, true);
total_clock = [];
if timing_enabled, total_clock = tic; end
if timing_enabled, lookup_clock = tic; end
[cached_columns, lookup] = session.lookup_c1(angles_deg, model);
if timing_enabled
    lookup_runtime = toc(lookup_clock);
else
    lookup_runtime = NaN;
end
hit = lookup.cache_hit;
legacy_runtime = double(timing_enabled) * 0;
rank_runtime = double(timing_enabled) * 0;
if ~timing_enabled
    legacy_runtime = NaN;
    rank_runtime = NaN;
end
legacy_info = struct();
columns = cell(2, 1);
if any(~hit)
    if strcmp(session.failure_mode(), 'PRODUCER_FAILURE')
        error('stage8_k2_tecs_provider_pair:InjectedProducerFailure', ...
            'Injected frozen-producer failure.');
    end
    if timing_enabled, legacy_clock = tic; end
    [legacy_G, ~, legacy_info] = ...
        build_full_sequential_local_manifold(angles_deg, model, options);
    if timing_enabled, legacy_runtime = toc(legacy_clock); end
    session.record_physical_producer_call(1);
    for index = find(~hit).'
        columns{index} = legacy_G(:, index);
    end
end
for index = find(hit).'
    columns{index} = cached_columns{index};
end
G = [columns{1}, columns{2}];
if ~any(hit)
    manifold_info = legacy_info;
else
    multiplier = 1;
    if isfield(options, 'rank_multiplier')
        multiplier = options.rank_multiplier;
    end
    if timing_enabled, rank_clock = tic; end
    [rank_value, singular_values, threshold] = ...
        stage8_k2_tcc_stable_matrix_rank(G, multiplier);
    if timing_enabled, rank_runtime = toc(rank_clock); end
    manifold_info = struct( ...
        'rank_Gseq',rank_value, ...
        'singular_values_Gseq',singular_values, ...
        'rank_threshold_Gseq',threshold, ...
        'target_angles_deg',angles_deg, ...
        'full_receive_geometry_used_flag',any(~hit), ...
        'factorized_scoring_used_flag',false, ...
        'fixed_measurement_hash',model.fixed_measurement_hash, ...
        'phase_factor',1,'num_svd',1,'Gseq_size',size(G));
end
sources = repmat("LEGACY_FROZEN_FALLBACK", 2, 1);
sources(hit) = "C1_CERTIFIED_CANONICAL_DICTIONARY";
provider_info = struct( ...
    'mode','TECS_EXACT_STACK', ...
    'column_sources',sources, ...
    'cache_hit_count',double(nnz(hit)), ...
    'cache_miss_count',double(nnz(~hit)), ...
    'direct_fallback_count',double(nnz(~hit)), ...
    'identity_rejection_count',double(~lookup.identity_valid), ...
    'lookup_runtime_sec',lookup_runtime, ...
    'direct_runtime_sec',legacy_runtime, ...
    'rank_runtime_sec',rank_runtime, ...
    'total_runtime_sec',total_runtime_local(timing_enabled, total_clock), ...
    'fixed_measurement_hash',model.fixed_measurement_hash, ...
    'entry_count',lookup.entry_count, ...
    'bytes_current',lookup.bytes_current, ...
    'bytes_peak',lookup.bytes_peak, ...
    'physical_producer_call_count',double(any(~hit)));
end

function runtime = total_runtime_local(enabled, clock)
if enabled
    runtime = toc(clock);
else
    runtime = NaN;
end
end
