function output = stage8_k2_tecs_run_lifecycle(repo_dir, runtime_root)
%STAGE8_K2_TECS_RUN_LIFECYCLE Measure COLD and operation lifecycle costs.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
fixture = stage8_k2_tecs_build_runtime_fixture(repo_dir, runtime_root);
timing = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'timing_freeze.json')));
final = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'final_candidate_freeze.json')));
protocol = jsondecode(fileread(fullfile(runtime_root, 'freeze', ...
    'timing_protocol.json')));
[~, integration_hash] = stage8_k2_tecs_integration_manifest(repo_dir);
assert(strcmp(integration_hash, timing.cache_code_hash));
schedule = readtable(fullfile(runtime_root, 'freeze', ...
    'cold_lifecycle_schedule.csv'), 'TextType', 'string');
assert(height(schedule) == 740 && ...
    strcmp(final.cold_lifecycle_schedule_hash, stage8_k2_tecs_sha256( ...
    'TECS_COLD_LIFECYCLE_SCHEDULE_V1',table2struct(schedule))));
batch_schedule = schedule(schedule.schedule_unit_kind == ...
    "COLD_BATCH_PAIR", :);
operation_schedule = schedule(schedule.schedule_unit_kind == ...
    "LIFECYCLE_OPERATION", :);
assert(height(batch_schedule) == 40 && height(operation_schedule) == 700);
artifact_registry = readtable(fullfile(runtime_root, 'freeze', ...
    'c1_artifact_registry.csv'), 'TextType', 'string');
mode_registry = readtable(fullfile(runtime_root, 'freeze', ...
    'canonical_mode_registry.csv'), 'TextType', 'string');
warmup = readtable(fullfile(runtime_root, 'freeze', ...
    'formal_warmup_registry.csv'), 'TextType', 'string');
candidate_layers = layers_for_mode_local(mode_registry, ...
    string(final.final_measurement_candidate_canonical_mode_id));
assert(isequal(candidate_layers, {'C1'}));

pass_dir = fullfile(runtime_root, 'lifecycle');
batch_checkpoint_dir = fullfile(pass_dir, 'cold_checkpoints');
operation_checkpoint_dir = fullfile(pass_dir, 'operation_checkpoints');
cold_artifact_dir = fullfile(pass_dir, 'cold_build_artifacts');
directories = {pass_dir,batch_checkpoint_dir,operation_checkpoint_dir, ...
    cold_artifact_dir};
for index = 1:numel(directories)
    if ~isfolder(directories{index}), mkdir(directories{index}); end
end
paths = struct('cold_raw',fullfile(pass_dir,'cold_raw_samples.csv'), ...
    'operation_raw',fullfile(pass_dir,'operation_raw_samples.csv'), ...
    'summary',fullfile(pass_dir,'lifecycle_summary.csv'), ...
    'manifest',fullfile(pass_dir,'lifecycle_manifest.json'), ...
    'process',fullfile(pass_dir,'formal_process_snapshot.json'));
names = fieldnames(paths);
for index = 1:numel(names)
    if isfile(paths.(names{index}))
        error('stage8_k2_tecs_run_lifecycle:ImmutableExists', ...
            'Lifecycle aggregate target exists: %s', paths.(names{index}));
    end
end
process = process_snapshot_local('COLD_AND_LIFECYCLE');
assert(process.active_MATLAB_process_count == 1);
stage8_k2_tecs_atomic_write_json(paths.process, process);
trials = stage8_k2_tecs_prepare_trial_bank(fixture);

batch_rows = repmat(cold_raw_template_local(), height(batch_schedule), 1);
settings = ["COLD_BUILD";"COLD_LOAD"];
for setting_index = 1:2
    setting = settings(setting_index);
    formal_warmup_local(trials, fixture, warmup, candidate_layers);
    selected = find(batch_schedule.lifecycle_setting == setting);
    for local_index = 1:numel(selected)
        schedule_index = selected(local_index);
        scheduled = batch_schedule(schedule_index, :);
        checkpoint_path = fullfile(batch_checkpoint_dir, sprintf( ...
            '%04d.mat', scheduled.schedule_row_id));
        expected = batch_checkpoint_identity_local( ...
            fixture,timing,final,protocol,scheduled);
        if isfile(checkpoint_path)
            loaded = load(checkpoint_path, 'checkpoint');
            checkpoint = loaded.checkpoint;
            assert(checkpoint.unit_complete && ...
                checkpoint.pair_contiguous_complete && ...
                isequaln(checkpoint.identity,expected), ...
                'stage8_k2_tecs_run_lifecycle:CheckpointIdentity');
            batch_rows(schedule_index) = checkpoint.row;
            fprintf('TECS COLD RESUME %d/%d %s\n', ...
                schedule_index,height(batch_schedule),char(setting));
            continue;
        end
        identity_index = scheduled.identity_index;
        member = find(string(cellfun(@(trial) ...
            trial.model.fixed_measurement_hash,trials, ...
            'UniformOutput',false)) == scheduled.fixed_measurement_hash);
        assert(numel(member) == 36);
        immutable_path = char(artifact_registry.artifact_path( ...
            artifact_registry.fixed_measurement_hash == ...
            scheduled.fixed_measurement_hash));
        pair = cold_pair_local(trials(member),fixture,identity_index, ...
            char(setting),char(scheduled.pair_order),immutable_path, ...
            cold_artifact_dir,scheduled.schedule_row_id);
        row = cold_raw_template_local();
        row.schedule_row_id = scheduled.schedule_row_id;
        row.schedule_row_hash = scheduled.schedule_row_hash;
        row.comparison_id = scheduled.comparison_id;
        row.comparison_kind = scheduled.comparison_kind;
        row.baseline_canonical_mode_id = ...
            scheduled.baseline_canonical_mode_id;
        row.candidate_canonical_mode_id = ...
            scheduled.candidate_canonical_mode_id;
        row.enabled_layer_set_hash = scheduled.enabled_layer_set_hash;
        row.precedence_hash = scheduled.precedence_hash;
        row.fixed_measurement_hash = scheduled.fixed_measurement_hash;
        row.identity_batch_id = scheduled.identity_batch_id;
        row.identity_index = scheduled.identity_index;
        row.batch_repeat_index = scheduled.batch_repeat_index;
        row.pair_order = scheduled.pair_order;
        row.lifecycle_setting = scheduled.lifecycle_setting;
        row.time_off_sec = pair.time_a_sec;
        row.time_on_sec = pair.time_b_sec;
        row.paired_difference_sec = pair.time_a_sec - pair.time_b_sec;
        row.output_match = pair.output_match;
        row.cache_hit_count = pair.candidate.cache_hit_count;
        row.cache_miss_count = pair.candidate.cache_miss_count;
        row.physical_producer_call_count = ...
            pair.candidate.physical_producer_call_count;
        row.entry_count = pair.candidate.entry_count;
        row.bytes_current = pair.candidate.bytes_current;
        row.bytes_peak = pair.candidate.bytes_peak;
        row.key_collision_count = pair.candidate.collision_count;
        row.truth_leakage_count = pair.candidate.truth_leakage_count;
        row.pair_contiguous_complete = true;
        batch_rows(schedule_index) = row;
        checkpoint = struct('schema_version', ...
            'STAGE8_K2_TECS_COLD_CHECKPOINT_V1','identity',expected, ...
            'row',row,'unit_complete',true, ...
            'pair_contiguous_complete',true);
        atomic_checkpoint_local(checkpoint_path,checkpoint);
        fprintf('TECS COLD RUN %d/%d %s %s d=%.9g\n', ...
            schedule_index,height(batch_schedule),char(setting), ...
            char(row.pair_order),row.paired_difference_sec);
        if ~row.output_match || row.key_collision_count ~= 0 || ...
                row.truth_leakage_count ~= 0
            error('stage8_k2_tecs_run_lifecycle:Correctness');
        end
    end
end
cold_raw = struct2table(batch_rows);

operation_rows = repmat(operation_raw_template_local(), ...
    height(operation_schedule), 1);
for schedule_index = 1:height(operation_schedule)
    scheduled = operation_schedule(schedule_index, :);
    checkpoint_path = fullfile(operation_checkpoint_dir, sprintf( ...
        '%04d.mat', scheduled.schedule_row_id));
    expected = operation_checkpoint_identity_local( ...
        fixture,timing,final,protocol,scheduled);
    if isfile(checkpoint_path)
        loaded = load(checkpoint_path, 'checkpoint');
        checkpoint = loaded.checkpoint;
        assert(checkpoint.unit_complete && ...
            isequaln(checkpoint.identity,expected));
        operation_rows(schedule_index) = checkpoint.row;
        continue;
    end
    identity_index = scheduled.identity_index;
    immutable_path = char(artifact_registry.artifact_path( ...
        artifact_registry.fixed_measurement_hash == ...
        scheduled.fixed_measurement_hash));
    measured = measure_operation_local(fixture,identity_index, ...
        char(scheduled.lifecycle_operation),immutable_path, ...
        cold_artifact_dir,scheduled.schedule_row_id);
    row = operation_raw_template_local();
    row.schedule_row_id = scheduled.schedule_row_id;
    row.schedule_row_hash = scheduled.schedule_row_hash;
    row.candidate_canonical_mode_id = ...
        scheduled.candidate_canonical_mode_id;
    row.fixed_measurement_hash = scheduled.fixed_measurement_hash;
    row.identity_batch_id = scheduled.identity_batch_id;
    row.identity_index = scheduled.identity_index;
    row.lifecycle_operation = scheduled.lifecycle_operation;
    row.operation_repeat_index = scheduled.operation_repeat_index;
    row.operation_phase = scheduled.operation_phase;
    row.included_in_statistics = scheduled.included_in_statistics;
    row.operation_batch_size = measured.batch_size;
    row.elapsed_total_sec = measured.elapsed_total_sec;
    row.elapsed_per_operation_sec = measured.elapsed_total_sec / ...
        measured.batch_size;
    row.entry_count = measured.entry_count;
    row.bytes_peak = measured.bytes_peak;
    row.checksum_hash = string(measured.checksum_hash);
    row.operation_complete = true;
    operation_rows(schedule_index) = row;
    checkpoint = struct('schema_version', ...
        'STAGE8_K2_TECS_LIFECYCLE_OPERATION_CHECKPOINT_V1', ...
        'identity',expected,'row',row,'unit_complete',true, ...
        'pair_contiguous_complete',true);
    atomic_checkpoint_local(checkpoint_path,checkpoint);
    fprintf('TECS OP RUN %d/%d %s %s %.9g\n', ...
        schedule_index,height(operation_schedule), ...
        char(row.fixed_measurement_hash), ...
        char(row.lifecycle_operation),row.elapsed_per_operation_sec);
end
operation_raw = struct2table(operation_rows);
warm_summary = readtable(fullfile(runtime_root,'pass_f', ...
    'final_warm_summary.csv'),'TextType','string');
[summary,statuses] = summarize_local(cold_raw,operation_raw,warm_summary);
stage8_k2_tecs_atomic_writetable(cold_raw,paths.cold_raw);
stage8_k2_tecs_atomic_writetable(operation_raw,paths.operation_raw);
stage8_k2_tecs_atomic_writetable(summary,paths.summary);
output = struct( ...
    'schema_version','STAGE8_K2_TECS_LIFECYCLE_MANIFEST_V1', ...
    'design_freeze_hash',fixture.design.freeze_payload_hash, ...
    'component_freeze_hash',fixture.component.freeze_payload_hash, ...
    'timing_freeze_hash',timing.freeze_payload_hash, ...
    'final_candidate_freeze_hash',final.freeze_payload_hash, ...
    'timing_protocol_hash',protocol.timing_protocol_hash, ...
    'cold_raw_sample_count',height(cold_raw), ...
    'operation_raw_sample_count',height(operation_raw), ...
    'cold_build_point_status',statuses.cold_build_point_status, ...
    'cold_load_point_status',statuses.cold_load_point_status, ...
    'cold_build_break_even_status', ...
        statuses.cold_build_break_even_status, ...
    'cold_load_break_even_status', ...
        statuses.cold_load_break_even_status, ...
    'deployment_status','NOT_ASSESSED_NO_WORKLOAD_HORIZON', ...
    'cold_raw_hash',stage8_k2_tecs_sha256( ...
        'TECS_COLD_RAW_V1',table2struct(cold_raw)), ...
    'operation_raw_hash',stage8_k2_tecs_sha256( ...
        'TECS_LIFECYCLE_OPERATION_RAW_V1',table2struct(operation_raw)), ...
    'summary_hash',stage8_k2_tecs_sha256( ...
        'TECS_LIFECYCLE_SUMMARY_V1',table2struct(summary)), ...
    'bytes_peak',max([cold_raw.bytes_peak;operation_raw.bytes_peak]), ...
    'key_collision_count',sum(cold_raw.key_collision_count), ...
    'truth_leakage_count',sum(cold_raw.truth_leakage_count), ...
    'status','LIFECYCLE_VALIDATION_COMPLETE');
output.cold_raw_file_sha256 = stage8_k2_tecs_sha256_file(paths.cold_raw);
output.operation_raw_file_sha256 = ...
    stage8_k2_tecs_sha256_file(paths.operation_raw);
output.summary_file_sha256 = stage8_k2_tecs_sha256_file(paths.summary);
output.manifest_payload_hash = stage8_k2_tecs_sha256( ...
    'TECS_LIFECYCLE_MANIFEST_V1',output);
stage8_k2_tecs_atomic_write_json(paths.manifest,output);
fprintf('TECS LIFECYCLE COMPLETE build=%s load=%s\n', ...
    statuses.cold_build_point_status,statuses.cold_load_point_status);
end
function pair = cold_pair_local(trials,fixture,identity_index,setting, ...
    order,immutable_path,artifact_root,schedule_id)
if strcmp(order,'AB')
    a = run_off_batch_local(trials,fixture);
    b = run_on_batch_local(trials,fixture,identity_index,setting, ...
        immutable_path,artifact_root,schedule_id);
else
    b = run_on_batch_local(trials,fixture,identity_index,setting, ...
        immutable_path,artifact_root,schedule_id);
    a = run_off_batch_local(trials,fixture);
end
pair = struct('time_a_sec',a.elapsed_sec,'time_b_sec',b.elapsed_sec, ...
    'baseline',a,'candidate',b, ...
    'output_match',strcmp(a.result_hash,b.result_hash));
end

function output = run_off_batch_local(trials,fixture)
stage8_k2_tcc_audit_state('CONFIGURE',struct('mode','OFF'));
context = fixture.context;
if isfield(context,'manifold_provider'), ...
        context = rmfield(context,'manifold_provider'); end
semantic = cell(numel(trials),1);
drawnow; clock = tic;
for index = 1:numel(trials)
    [result,diagnostics] = stage8_k2_tp_fit_safe( ...
        trials{index}.Y_element,trials{index}.model,context);
    projection = stage8_k2_tecs_root_projection( ...
        result,diagnostics,'CACHE_ON_DECISION');
    semantic{index} = projection.result;
end
elapsed = toc(clock);
output = struct('elapsed_sec',elapsed,'result_hash', ...
    stage8_k2_tecs_sha256('TECS_COLD_BATCH_RESULT_V1',semantic), ...
    'cache_hit_count',0,'cache_miss_count',0, ...
    'physical_producer_call_count',0,'entry_count',0, ...
    'bytes_current',0,'bytes_peak',0,'collision_count',0, ...
    'truth_leakage_count',0);
end

function output = run_on_batch_local(trials,fixture,identity_index,setting, ...
    immutable_path,artifact_root,schedule_id)
identity = fixture.identities(identity_index);
stage8_k2_tcc_audit_state('CONFIGURE',struct('mode','OFF'));
drawnow; clock = tic;
if strcmp(setting,'COLD_BUILD')
    [dictionary,~] = stage8_k2_tcc_build_registered_dictionary( ...
        identity.model,fixture.context.plan.local_domain,struct());
    artifact = stage8_k2_tecs_promote_c1_artifact(dictionary); %#ok<NASGU>
    directory = fullfile(artifact_root,sprintf('%04d_%s', ...
        schedule_id,char(java.util.UUID.randomUUID())));
    mkdir(directory);
    path_now = fullfile(directory,'C1.mat');
    temporary = [path_now,'.tmp'];
    save(temporary,'artifact','-v7.3');
    movefile(temporary,path_now,'f');
else
    path_now = immutable_path;
end
loaded = load(path_now,'artifact');
stage8_k2_tecs_validate_c1_value( ...
    loaded.artifact,identity.fixed_measurement_hash);
local_fixture = fixture;
local_fixture.identities(identity_index).artifact = loaded.artifact;
session = stage8_k2_tecs_make_session(local_fixture, ...
    identity.fixed_measurement_hash,{'C1'});
provider = stage8_k2_tecs_build_provider(session, ...
    struct('per_call_timing_enabled',false));
context = fixture.context;
context.manifold_provider = provider;
semantic = cell(numel(trials),1);
for index = 1:numel(trials)
    [result,diagnostics] = stage8_k2_tp_fit_safe( ...
        trials{index}.Y_element,trials{index}.model,context);
    projection = stage8_k2_tecs_root_projection( ...
        result,diagnostics,'CACHE_ON_DECISION');
    semantic{index} = projection.result;
end
elapsed = toc(clock);
snapshot = session.snapshot(); delete(session);
output = snapshot;
output.elapsed_sec = elapsed;
output.result_hash = stage8_k2_tecs_sha256( ...
    'TECS_COLD_BATCH_RESULT_V1',semantic);
end

function measured = measure_operation_local(fixture,identity_index, ...
    operation,immutable_path,artifact_root,schedule_id)
identity = fixture.identities(identity_index);
batch_size = 1; checksum = 'NOT_APPLICABLE'; entry_count = 0; bytes_peak = 0;
switch operation
    case 'build'
        drawnow; clock = tic;
        [dictionary,~] = stage8_k2_tcc_build_registered_dictionary( ...
            identity.model,fixture.context.plan.local_domain,struct());
        artifact = stage8_k2_tecs_promote_c1_artifact(dictionary); %#ok<NASGU>
        directory = fullfile(artifact_root,sprintf('OP_%04d_%s', ...
            schedule_id,char(java.util.UUID.randomUUID()))); mkdir(directory);
        path_now = fullfile(directory,'C1.mat');
        temporary = [path_now,'.tmp']; save(temporary,'artifact','-v7.3');
        movefile(temporary,path_now,'f'); elapsed = toc(clock);
        checksum = artifact.artifact_hash; entry_count = 21;
        bytes_peak = artifact.value_bytes;
    case 'load'
        drawnow; clock = tic; loaded = load(immutable_path,'artifact'); ...
            elapsed = toc(clock);
        checksum = loaded.artifact.artifact_hash;
        entry_count = 21; bytes_peak = loaded.artifact.value_bytes;
    case 'validate'
        loaded = load(immutable_path,'artifact'); drawnow; clock = tic;
        stage8_k2_tecs_validate_c1_value( ...
            loaded.artifact,identity.fixed_measurement_hash);
        elapsed = toc(clock); checksum = loaded.artifact.artifact_hash;
    case 'setup'
        drawnow; clock = tic; session = stage8_k2_tecs_make_session( ...
            fixture,identity.fixed_measurement_hash,{'C1'}); elapsed = toc(clock);
        snapshot = session.snapshot(); delete(session);
        checksum = snapshot.key_schema_hash; entry_count = snapshot.entry_count;
        bytes_peak = snapshot.bytes_peak;
    case 'reset'
        session = stage8_k2_tecs_make_session( ...
            fixture,identity.fixed_measurement_hash,{'C1'});
        drawnow; clock = tic; session.reset('TRIAL_INVOCATION'); ...
            elapsed = toc(clock);
        snapshot = session.snapshot(); delete(session);
        checksum = snapshot.key_schema_hash; entry_count = snapshot.entry_count;
        bytes_peak = snapshot.bytes_peak;
    case {'hash','lookup_hit','lookup_miss','store','copy'}
        batch_size = 100;
        [elapsed,checksum,entry_count,bytes_peak] = ...
            micro_cache_operation_local(fixture,identity,operation,batch_size);
    otherwise
        error('stage8_k2_tecs_run_lifecycle:Operation');
end
measured = struct('elapsed_total_sec',elapsed,'batch_size',batch_size, ...
    'checksum_hash',checksum,'entry_count',entry_count, ...
    'bytes_peak',bytes_peak);
end

function [elapsed,checksum,entry_count,bytes_peak] = ...
    micro_cache_operation_local(fixture,identity,operation,batch_size)
session = stage8_k2_tecs_make_session( ...
    fixture,identity.fixed_measurement_hash,{'C1'});
hit_pair = identity.artifact.key_angles_deg(1:2,:);
miss_pair = hit_pair + 0.123456789;
base_key = struct('layer','MICRO','identity', ...
    identity.fixed_measurement_hash,'index',0);
value = identity.artifact.G(:,1);
if strcmp(operation,'copy')
    session.store_exact('MICRO',base_key,value);
end
drawnow; clock = tic;
switch operation
    case 'hash'
        for index = 1:batch_size
            base_key.index = index;
            checksum = stage8_k2_tecs_sha256('TECS_MICRO_HASH',base_key);
        end
    case 'lookup_hit'
        for index = 1:batch_size
            [~,info] = session.lookup_c1(hit_pair,identity.model);
        end
        checksum = char(join(string(info.key_indices),','));
    case 'lookup_miss'
        for index = 1:batch_size
            [~,info] = session.lookup_c1(miss_pair,identity.model);
        end
        checksum = char(join(info.cache_miss_reason,','));
    case 'store'
        for index = 1:batch_size
            base_key.index = index;
            info = session.store_exact('MICRO',base_key,value);
        end
        checksum = info.hash;
    case 'copy'
        for index = 1:batch_size
            [hit,copied,info] = session.lookup_exact('MICRO',base_key); %#ok<ASGLU>
        end
        checksum = info.hash;
end
elapsed = toc(clock); snapshot = session.snapshot(); delete(session);
entry_count = snapshot.entry_count; bytes_peak = snapshot.bytes_peak;
end

function formal_warmup_local(trials,fixture,warmup,candidate_layers)
for index = 1:height(warmup)
    trial = trials{warmup.global_trial_index(index)};
    run_warm_pair_local(trial,fixture,candidate_layers,'AB');
    run_warm_pair_local(trial,fixture,candidate_layers,'BA');
end
end

function run_warm_pair_local(trial,fixture,candidate_layers,order)
if strcmp(order,'AB')
    stage8_k2_tecs_run_root(trial,fixture.context,fixture,cell(0,1));
    stage8_k2_tecs_run_root(trial,fixture.context,fixture,candidate_layers);
else
    stage8_k2_tecs_run_root(trial,fixture.context,fixture,candidate_layers);
    stage8_k2_tecs_run_root(trial,fixture.context,fixture,cell(0,1));
end
end

function [summary,statuses] = summarize_local(cold,operations,warm)
rows = repmat(summary_template_local(),0,1);
measured = operations.included_in_statistics;
identities = unique(cold.fixed_measurement_hash,'stable');
operation_medians = struct();
for identity_index = 1:2
    identity = identities(identity_index);
    row = summary_template_local(); row.row_kind = "OPERATION_SUMMARY";
    row.cache_layer = "C1"; row.fixed_measurement_hash = identity;
    row.micro_warmup_repeat_count = 5; row.micro_measured_repeat_count = 30;
    names = ["build","load","validate","setup","hash", ...
        "lookup_hit","lookup_miss","store","copy","reset"];
    for index = 1:numel(names)
        values = operations.elapsed_per_operation_sec(measured & ...
            operations.fixed_measurement_hash == identity & ...
            operations.lifecycle_operation == names(index));
        assert(numel(values)==30);
        field = char(names(index) + "_sec"); row.(field) = median(values);
        operation_medians.(sprintf('i%d_%s',identity_index,names(index))) = ...
            median(values);
    end
    subset = operations(measured & ...
        operations.fixed_measurement_hash == identity,:);
    row.entry_count = max(subset.entry_count); row.bytes_peak = max(subset.bytes_peak);
    rows(end+1,1)=row; %#ok<AGROW>
end
settings=["COLD_BUILD";"COLD_LOAD"];
cold_total=zeros(2,1);
for setting_index=1:2
    setting=settings(setting_index);
    for identity_index=1:2
        subset=cold(cold.lifecycle_setting==setting & ...
            cold.fixed_measurement_hash==identities(identity_index),:);
        row=summary_template_local(); row.row_kind="LIFECYCLE_POINT";
        row.lifecycle_setting=setting; row.cache_layer="C1";
        row.fixed_measurement_hash=identities(identity_index);
        row.paired_repeat_count=10; row.AB_count=5; row.BA_count=5;
        row.net_saving_sec=median(subset.paired_difference_sec);
        row.bytes_peak=max(subset.bytes_peak); row.entry_count=max(subset.entry_count);
        cold_total(setting_index)=cold_total(setting_index)+row.net_saving_sec;
        rows(end+1,1)=row; %#ok<AGROW>
    end
    row=summary_template_local(); row.row_kind="LIFECYCLE_POINT";
    row.lifecycle_setting=setting; row.fixed_measurement_hash="OVERALL_2_IDENTITIES";
    row.paired_repeat_count=20; row.AB_count=10; row.BA_count=10;
    row.net_saving_sec=cold_total(setting_index);
    rows(end+1,1)=row; %#ok<AGROW>
end
warm_identity=warm(warm.aggregation_level=="IDENTITY",:);
warm_per_cycle=sum(warm_identity.point_saving_sec/36);
build_cost=0; load_cost=0;
for identity_index=1:2
    build_cost=build_cost+operation_medians.(sprintf('i%d_build',identity_index))+ ...
        operation_medians.(sprintf('i%d_load',identity_index))+ ...
        operation_medians.(sprintf('i%d_validate',identity_index))+ ...
        operation_medians.(sprintf('i%d_setup',identity_index));
    load_cost=load_cost+operation_medians.(sprintf('i%d_load',identity_index))+ ...
        operation_medians.(sprintf('i%d_validate',identity_index))+ ...
        operation_medians.(sprintf('i%d_setup',identity_index));
end
if warm_per_cycle>0
    build_break_even=floor(build_cost/warm_per_cycle)+1;
    load_break_even=floor(load_cost/warm_per_cycle)+1;
else
    build_break_even=Inf; load_break_even=Inf;
end
N=[1,2,5,10,20,36,72,100,1000];
for lifecycle=["COLD_BUILD","COLD_LOAD"]
    cost=build_cost; break_even=build_break_even;
    if lifecycle=="COLD_LOAD",cost=load_cost;break_even=load_break_even;end
    for index=1:numel(N)
        row=summary_template_local(); row.row_kind="BREAK_EVEN_CURVE";
        row.lifecycle_setting=lifecycle; row.cache_layer="C1";
        row.break_even_model_id= ...
            "BALANCED_TWO_IDENTITY_UNIFORM_FROZEN_REGISTRY_AVERAGE_MODEL";
        row.break_even_N=break_even; row.N_balanced_cycles=N(index);
        row.net_saving_sec=N(index)*warm_per_cycle-cost;
        if N(index)==36
            direct=cold_total(1); if lifecycle=="COLD_LOAD",direct=cold_total(2);end
            row.lifecycle_model_residual_sec=direct-row.net_saving_sec;
        end
        rows(end+1,1)=row; %#ok<AGROW>
    end
end
summary=struct2table(rows);
statuses=struct( ...
    'cold_build_point_status',ternary_local(cold_total(1)>0, ...
        'COLD_BUILD_72_TRIALS_POSITIVE','COLD_BUILD_72_TRIALS_NONPOSITIVE'), ...
    'cold_load_point_status',ternary_local(cold_total(2)>0, ...
        'COLD_LOAD_72_TRIALS_POSITIVE','COLD_LOAD_72_TRIALS_NONPOSITIVE'), ...
    'cold_build_break_even_status',ternary_local(isfinite(build_break_even), ...
        'COLD_BUILD_BREAK_EVEN_FINITE','COLD_BUILD_NO_BREAK_EVEN'), ...
    'cold_load_break_even_status',ternary_local(isfinite(load_break_even), ...
        'COLD_LOAD_BREAK_EVEN_FINITE','COLD_LOAD_NO_BREAK_EVEN'));
end

function value=ternary_local(flag,yes,no)
if flag,value=yes;else,value=no;end
end

function layers=layers_for_mode_local(registry,mode_id)
match=registry.candidate_canonical_mode_id==string(mode_id);assert(nnz(match)==1);
value=jsondecode(char(registry.ordered_enabled_layer_set(match)));
if isempty(value),layers=cell(0,1);elseif ischar(value),layers={value}; ...
else,layers=reshape(cellstr(string(value)),[],1);end
end

function identity=batch_checkpoint_identity_local(fixture,timing,final,protocol,row)
identity=common_identity_local(fixture,timing,final,protocol,row);
identity.checkpoint_unit_kind='COLD_BATCH_PAIR';identity.pass='LIFECYCLE_COLD';
identity.cache_setting='PAIRED_OFF_ON';identity.cache_layer='NOT_APPLICABLE';
identity.variant_alias_id=final.final_measurement_candidate_alias_id;
identity.comparison_id=char(row.comparison_id);
identity.comparison_kind=char(row.comparison_kind);
identity.trial_id='NOT_APPLICABLE';identity.repeat_index='NOT_APPLICABLE';
identity.pair_order=char(row.pair_order);
identity.lifecycle_setting=char(row.lifecycle_setting);
identity.identity_batch_id=char(row.identity_batch_id);
identity.batch_repeat_index=double(row.batch_repeat_index);
identity.lifecycle_operation='NOT_APPLICABLE';
identity.operation_repeat_index='NOT_APPLICABLE';
end

function identity=operation_checkpoint_identity_local(fixture,timing,final,protocol,row)
identity=common_identity_local(fixture,timing,final,protocol,row);
identity.checkpoint_unit_kind='LIFECYCLE_OPERATION';identity.pass='LIFECYCLE_OPERATION';
identity.cache_setting='CACHE_ON';identity.cache_layer='C1';
identity.variant_alias_id=final.final_measurement_candidate_alias_id;
identity.comparison_id='NOT_APPLICABLE';identity.comparison_kind='NOT_APPLICABLE';
identity.trial_id='NOT_APPLICABLE';identity.repeat_index='NOT_APPLICABLE';
identity.pair_order='NOT_APPLICABLE';identity.lifecycle_setting='WARM';
identity.identity_batch_id=char(row.identity_batch_id);
identity.batch_repeat_index='NOT_APPLICABLE';
identity.lifecycle_operation=char(row.lifecycle_operation);
identity.operation_repeat_index=double(row.operation_repeat_index);
end

function identity=common_identity_local(fixture,timing,final,protocol,row)
identity=struct('baseline_canonical_mode_id',char(row.baseline_canonical_mode_id), ...
    'candidate_canonical_mode_id',char(row.candidate_canonical_mode_id), ...
    'enabled_layer_set_hash',char(row.enabled_layer_set_hash), ...
    'precedence_hash',char(row.precedence_hash), ...
    'fixed_measurement_hash',char(row.fixed_measurement_hash), ...
    'schedule_row_id',double(row.schedule_row_id), ...
    'schedule_row_hash',char(row.schedule_row_hash), ...
    'run_id',fixture.design.run_id,'baseline_commit',fixture.design.baseline_commit, ...
    'initial_execution_start_commit',fixture.design.initial_execution_start_commit, ...
    'stage_commit_ledger_hash',timing.stage_commit_ledger_hash_at_timing_freeze, ...
    'integration_code_commit',timing.integration_code_commit, ...
    'prompt_hash',fixture.design.execution_prompt_hash, ...
    'baseline_snapshot_hash',fixture.design.baseline_snapshot_hash, ...
    'cache_code_hash',timing.cache_code_hash, ...
    'trial_registry_hash',fixture.design.trial_registry_hash, ...
    'key_schema_hash',fixture.design.key_schema_hash, ...
    'semantic_output_projection_hash',fixture.design.semantic_output_projection_hash, ...
    'hook_allowlist_hash',fixture.design.hook_allowlist_hash, ...
    'timing_protocol_hash',protocol.timing_protocol_hash, ...
    'phase_schedule_hash',final.cold_lifecycle_schedule_hash, ...
    'final_measurement_candidate_hash',final.final_measurement_candidate_hash, ...
    'design_freeze_hash',fixture.design.freeze_payload_hash, ...
    'component_freeze_hash',fixture.component.freeze_payload_hash, ...
    'timing_freeze_hash',timing.freeze_payload_hash, ...
    'final_candidate_freeze_hash',final.freeze_payload_hash, ...
    'MATLAB_release',version('-release'),'singleCompThread',true, ...
    'cache_reset_lifecycle_rule','FROZEN_COLD_OR_OPERATION_PRISTINE_STATE');
end

function process=process_snapshot_local(pass_id)
[status,text]=system(['powershell -NoProfile -Command "', ...
    '(Get-Process -Name MATLAB -ErrorAction SilentlyContinue | Measure-Object).Count"']);
count=str2double(strtrim(text));if status~=0||~isfinite(count),count=NaN;end
process=struct('schema_version','STAGE8_K2_TECS_PROCESS_SNAPSHOT_V1', ...
    'pass',pass_id,'active_MATLAB_process_count',count, ...
    'formal_MATLAB_process_limit',1,'parallel_pool_enabled',false, ...
    'singleCompThread',true,'captured_at_utc',char(datetime('now', ...
    'TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z''')));
end

function row=cold_raw_template_local()
row=struct('schema_version',"STAGE8_K2_TECS_COLD_RAW_V1", ...
    'schedule_row_id',0,'schedule_row_hash',"",'comparison_id',"", ...
    'comparison_kind',"",'baseline_canonical_mode_id',"", ...
    'candidate_canonical_mode_id',"",'enabled_layer_set_hash',"", ...
    'precedence_hash',"",'fixed_measurement_hash',"",'identity_batch_id',"", ...
    'identity_index',0,'batch_repeat_index',0,'pair_order',"", ...
    'lifecycle_setting',"",'time_off_sec',NaN,'time_on_sec',NaN, ...
    'paired_difference_sec',NaN,'output_match',false,'cache_hit_count',0, ...
    'cache_miss_count',0,'physical_producer_call_count',0,'entry_count',0, ...
    'bytes_current',0,'bytes_peak',0,'key_collision_count',0, ...
    'truth_leakage_count',0,'pair_contiguous_complete',false);
end

function row=operation_raw_template_local()
row=struct('schema_version',"STAGE8_K2_TECS_OPERATION_RAW_V1", ...
    'schedule_row_id',0,'schedule_row_hash',"", ...
    'candidate_canonical_mode_id',"",'fixed_measurement_hash',"", ...
    'identity_batch_id',"",'identity_index',0,'lifecycle_operation',"", ...
    'operation_repeat_index',0,'operation_phase',"", ...
    'included_in_statistics',false,'operation_batch_size',0, ...
    'elapsed_total_sec',NaN,'elapsed_per_operation_sec',NaN, ...
    'entry_count',0,'bytes_peak',0,'checksum_hash',"", ...
    'operation_complete',false);
end

function row=summary_template_local()
row=struct('schema_version',"STAGE8_K2_TECS_LIFECYCLE_V1", ...
    'row_kind',"",'cache_candidate_canonical_mode_id',"", ...
    'cache_layer',"",'lifecycle_setting',"",'fixed_measurement_hash',"", ...
    'batch_trial_count',36,'paired_repeat_count',0,'AB_count',0,'BA_count',0, ...
    'micro_warmup_repeat_count',0,'micro_measured_repeat_count',0, ...
    'build_sec',NaN,'load_sec',NaN,'validate_sec',NaN,'setup_sec',NaN, ...
    'hash_sec',NaN,'lookup_hit_sec',NaN,'lookup_miss_sec',NaN, ...
    'store_sec',NaN,'copy_sec',NaN,'reset_sec',NaN,'entry_count',NaN, ...
    'bytes_peak',NaN,'break_even_model_id',"",'break_even_N',NaN, ...
    'N_balanced_cycles',NaN,'net_saving_sec',NaN, ...
    'lifecycle_model_residual_sec',NaN);
end

function atomic_checkpoint_local(path_now,checkpoint)
temporary=[path_now,'.tmp'];save(temporary,'checkpoint','-v7.3'); ...
    movefile(temporary,path_now,'f');
end
