function output = stage8_k2_tecs_run_shadow_validation(repo_dir, runtime_root)
%STAGE8_K2_TECS_RUN_SHADOW_VALIDATION Pass C and post-hook correctness.

scope = stage8_k2_tecs_add_paths(repo_dir); %#ok<NASGU>
fixture = stage8_k2_tecs_build_runtime_fixture(repo_dir, runtime_root);
modes = stage8_k2_tecs_build_mode_registry(runtime_root);
m0 = mode_for_alias_local(modes, 'M0');
m1 = mode_for_alias_local(modes, 'M1');
[integration_manifest, integration_hash] = ...
    stage8_k2_tecs_integration_manifest(repo_dir);
ledger_hash = stage8_k2_tecs_sha256_file(fullfile( ...
    runtime_root, 'stage_commit_ledger.json'));
trajectory_saved = load(fullfile(runtime_root, 'baseline', ...
    'cache_off_discrete_trajectory.mat'), 'trajectory_rows');
baseline_counts = readtable(fullfile(runtime_root, 'baseline', ...
    'cache_off_logical_counts.csv'), 'TextType', 'string');

pass_dir = fullfile(runtime_root, 'pass_c_d');
checkpoint_dir = fullfile(pass_dir, 'correctness_checkpoints');
if ~isfolder(pass_dir), mkdir(pass_dir); end
if ~isfolder(checkpoint_dir), mkdir(checkpoint_dir); end
summary_path = fullfile(pass_dir, 'correctness_summary.csv');
manifest_path = fullfile(pass_dir, 'correctness_manifest.json');
if isfile(summary_path) || isfile(manifest_path)
    error('stage8_k2_tecs_run_shadow_validation:ImmutableExists', ...
        'Pass C/D aggregate target already exists.');
end

rows = repmat(correctness_template_local(), 72, 1);
for trial_index = 1:72
    spec = fixture.registry(trial_index, :);
    checkpoint_path = fullfile(checkpoint_dir, sprintf( ...
        '%03d_%s.mat', trial_index, char(spec.trial_id)));
    expected = checkpoint_identity_local(fixture, spec, trial_index, ...
        integration_hash, ledger_hash, m0, m1);
    if isfile(checkpoint_path)
        loaded = load(checkpoint_path, 'checkpoint');
        checkpoint = loaded.checkpoint;
        assert(checkpoint.unit_complete && ...
            isequaln(checkpoint.identity, expected), ...
            'stage8_k2_tecs_run_shadow_validation:CheckpointIdentity', ...
            'CHECKPOINT_IDENTITY_MISMATCH_STOP: %s', char(spec.trial_id));
        rows(trial_index) = checkpoint.row;
        fprintf('TECS PASS C/D RESUME %d/72 %s pass=%d\n', ...
            trial_index, char(spec.trial_id), checkpoint.row.correctness_pass);
        continue;
    end

    trial = stage8_k2_tcc_generate_frozen_trial(spec, fixture.context);
    identity = stage8_k2_tecs_identity_fixture( ...
        fixture, trial.model.fixed_measurement_hash);
    baseline_semantic = fixture.semantic_snapshot.rows{trial_index};
    baseline_trajectory = trajectory_saved.trajectory_rows{trial_index};

    [off_result, off_diagnostics, off_query] = run_query_local( ...
        trial, fixture.context, identity.dictionary, spec, []);
    off_projection = stage8_k2_tecs_root_projection( ...
        off_result, off_diagnostics, 'CACHE_OFF_BASELINE');
    baseline_off_projection = stage8_k2_tecs_root_projection( ...
        baseline_semantic.semantic_projection.result, ...
        baseline_semantic.semantic_projection.diagnostics, ...
        'CACHE_OFF_BASELINE');
    off_match = isequaln(off_projection, ...
        baseline_off_projection) && ...
        isequaln(off_query, baseline_trajectory.query_capture) && ...
        counts_match_local(off_result, baseline_counts(trial_index, :));

    shadow = shadow_lookup_local(fixture, identity, trial.model, ...
        off_diagnostics);

    session = stage8_k2_tecs_make_session( ...
        fixture, trial.model.fixed_measurement_hash, {'C1'});
    provider = stage8_k2_tecs_build_provider(session);
    [on_result, on_diagnostics, on_query] = run_query_local( ...
        trial, fixture.context, identity.dictionary, spec, provider);
    session_snapshot = session.snapshot();
    delete(session);
    reference_decision = stage8_k2_tecs_root_projection( ...
        baseline_semantic.semantic_projection.result, ...
        baseline_semantic.semantic_projection.diagnostics, ...
        'CACHE_ON_DECISION');
    on_decision = stage8_k2_tecs_root_projection( ...
        on_result, on_diagnostics, 'CACHE_ON_DECISION');
    decision_match = isequaln(on_decision, reference_decision);
    trajectory_match = isequaln(on_query, ...
        baseline_trajectory.query_capture);
    mismatch = mismatch_totals_local(on_query.stage_rows);
    mismatch_zero = all(struct2array(mismatch) == 0);
    cache_count_match = ...
        on_diagnostics.cache_hit_count == shadow.cache_hit_count && ...
        on_diagnostics.cache_miss_count == shadow.cache_miss_count && ...
        session_snapshot.physical_producer_call_count == ...
            numel(off_diagnostics.evaluated_rho_deg);
    truth_pass = ~on_result.truth_used_in_fit_flag && ...
        ~on_diagnostics.selection_truth_used_flag && ...
        ~on_query.truth_used_in_fit_flag && ...
        ~on_query.cache_truth_used_flag && ...
        session_snapshot.truth_leakage_count == 0;

    row = correctness_template_local();
    row.cache_candidate_canonical_mode_id = ...
        string(m1.candidate_canonical_mode_id);
    row.cache_layer = "C1";
    row.fixed_measurement_hash = ...
        string(trial.model.fixed_measurement_hash);
    row.trial_id = string(spec.trial_id);
    row.continuous_numeric_pass = decision_match && ...
        shadow.numeric_contract_pass;
    row.G_rel_error = shadow.max_G_rel_error;
    row.rank_match = shadow.rank_match && mismatch.rank_mismatch_count == 0;
    row.score_match = mismatch_zero && decision_match;
    row.candidate_order_match = ...
        mismatch.candidate_order_mismatch_count == 0;
    row.tie_match = mismatch.tie_mismatch_count == 0;
    row.best_index_match = mismatch.best_index_mismatch_count == 0;
    row.accepted_update_match = ...
        mismatch.accepted_update_mismatch_count == 0;
    row.trajectory_match = trajectory_match && ...
        mismatch.trajectory_mismatch_count == 0;
    row.selected_start_match = ...
        mismatch.selected_start_mismatch_count == 0 && ...
        strcmp(on_result.selected_start_id, ...
        baseline_semantic.semantic_projection.result.selected_start_id);
    row.nested_pass_match = ...
        mismatch.nested_pass_mismatch_count == 0;
    row.final_selector_match = ...
        mismatch.final_selector_mismatch_count == 0 && ...
        strcmp(on_result.selected_source, ...
        baseline_semantic.semantic_projection.result.selected_source);
    row.truth_isolation_pass = truth_pass;
    row.cache_off_baseline_match = off_match;
    row.cache_hit_count = on_diagnostics.cache_hit_count;
    row.cache_miss_count = on_diagnostics.cache_miss_count;
    row.physical_producer_call_count = ...
        session_snapshot.physical_producer_call_count;
    row.logical_score_call_count = on_result.score_call_count;
    row.logical_svd_call_count = on_result.svd_call_count;
    row.bytes_peak = session_snapshot.bytes_peak;
    row.key_collision_count = session_snapshot.collision_count;
    row.truth_leakage_count = session_snapshot.truth_leakage_count;
    row.correctness_pass = off_match && decision_match && ...
        trajectory_match && mismatch_zero && cache_count_match && ...
        shadow.all_pass && truth_pass && ...
        counts_match_local(on_result, baseline_counts(trial_index, :));
    if ~row.correctness_pass
        row.failure_reason = failure_reason_local(off_match, ...
            decision_match, trajectory_match, mismatch_zero, ...
            cache_count_match, shadow.all_pass, truth_pass);
    else
        row.failure_reason = "";
    end
    rows(trial_index) = row;
    checkpoint = struct('schema_version', ...
        'STAGE8_K2_TECS_CORRECTNESS_CHECKPOINT_V1', ...
        'identity', expected, 'row', row, ...
        'shadow', shadow, 'session_snapshot', session_snapshot, ...
        'unit_complete', true, 'pair_contiguous_complete', true);
    atomic_checkpoint_local(checkpoint_path, checkpoint);
    fprintf(['TECS PASS C/D RUN %d/72 %s pass=%d ', ...
        'hit=%d miss=%d\n'], trial_index, char(spec.trial_id), ...
        row.correctness_pass, row.cache_hit_count, row.cache_miss_count);
    if ~row.correctness_pass
        error('stage8_k2_tecs_run_shadow_validation:Mismatch', ...
            'SHADOW_NUMERIC_OR_DECISION_MISMATCH_STOP: %s (%s)', ...
            char(spec.trial_id), char(row.failure_reason));
    end
end

correctness = struct2table(rows);
assert(all(correctness.correctness_pass) && ...
    all(correctness.cache_off_baseline_match) && ...
    sum(correctness.cache_hit_count) == 0 && ...
    sum(correctness.cache_miss_count) == 5904 && ...
    sum(correctness.key_collision_count) == 0 && ...
    sum(correctness.truth_leakage_count) == 0, ...
    'stage8_k2_tecs_run_shadow_validation:HardStop', ...
    'SHADOW_NUMERIC_OR_DECISION_MISMATCH_STOP');
stage8_k2_tecs_atomic_writetable(correctness, summary_path);
output = struct( ...
    'schema_version', 'STAGE8_K2_TECS_PASS_C_D_MANIFEST_V1', ...
    'design_freeze_hash', fixture.design.freeze_payload_hash, ...
    'component_freeze_hash', fixture.component.freeze_payload_hash, ...
    'baseline_snapshot_hash', fixture.design.baseline_snapshot_hash, ...
    'integration_implementation_hash', integration_hash, ...
    'integration_manifest', integration_manifest, ...
    'stage_commit_ledger_hash', ledger_hash, ...
    'M0_canonical_mode_id', char(m0.candidate_canonical_mode_id), ...
    'M1_canonical_mode_id', char(m1.candidate_canonical_mode_id), ...
    'trial_count', height(correctness), ...
    'shadow_pass_count', nnz(correctness.correctness_pass), ...
    'post_hook_cache_off_qualification_pass_count', ...
        nnz(correctness.cache_off_baseline_match), ...
    'M1_correctness_pass_count', nnz(correctness.correctness_pass), ...
    'cache_hit_count', sum(correctness.cache_hit_count), ...
    'cache_miss_count', sum(correctness.cache_miss_count), ...
    'physical_producer_call_count', ...
        sum(correctness.physical_producer_call_count), ...
    'key_collision_count', sum(correctness.key_collision_count), ...
    'truth_leakage_count', sum(correctness.truth_leakage_count), ...
    'bytes_peak', max(correctness.bytes_peak), ...
    'correctness_summary_hash', stage8_k2_tecs_sha256( ...
        'TECS_PASS_C_D_CORRECTNESS_SUMMARY_V1', ...
        table2struct(correctness)), ...
    'correctness_summary_file_sha256', ...
        stage8_k2_tecs_sha256_file(summary_path), ...
    'status', 'PASS_C_D_SHADOW_AND_INTEGRATION_CORRECTNESS_COMPLETE');
output.manifest_payload_hash = stage8_k2_tecs_sha256( ...
    'TECS_PASS_C_D_MANIFEST_V1', output);
stage8_k2_tecs_atomic_write_json(manifest_path, output);
fprintf(['TECS PASS C/D COMPLETE 72/72 CACHE_OFF=72/72 ', ...
    'M1=72/72 hit=%d miss=%d hash=%s\n'], output.cache_hit_count, ...
    output.cache_miss_count, output.correctness_summary_hash);
end

function [result, diagnostics, query] = run_query_local( ...
    trial, base_context, dictionary, spec, provider)
full_data = build_stage8_full_data_from_element( ...
    trial.Y_element, trial.model, struct( ...
    'data_role', 'SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
metadata = struct('trial_id', char(spec.trial_id), ...
    'noise_profile_id', char(spec.noise_profile_id), ...
    'L', double(spec.L), 'snr_db', double(spec.snr_db), ...
    'profile_id', char(spec.profile_id), ...
    'element_trial_hash', trial.element_trial_hash, ...
    'fixed_measurement_hash', trial.model.fixed_measurement_hash);
stage8_k2_tcc_audit_state('CONFIGURE', struct('mode', 'QUERY', ...
    'dictionary', dictionary, 'model', trial.model, ...
    'Zseq_white', full_data.Zseq_white, 'trial_metadata', metadata));
context = base_context;
if isempty(provider)
    if isfield(context, 'manifold_provider')
        context = rmfield(context, 'manifold_provider');
    end
else
    context.manifold_provider = provider;
end
[result, diagnostics] = stage8_k2_tp_fit_safe( ...
    trial.Y_element, trial.model, context);
query = stage8_k2_tcc_audit_state('GET_QUERY');
end

function shadow = shadow_lookup_local(fixture, identity, model, diagnostics)
session = stage8_k2_tecs_make_session( ...
    fixture, identity.fixed_measurement_hash, {'C1'});
center = double(diagnostics.K1_center_deg(:).');
direction = double(diagnostics.direction_hat(:).');
rho = double(diagnostics.evaluated_rho_deg(:));
max_error = 0;
rank_match = true;
numeric_pass = true;
for index = 1:numel(rho)
    pair = [center - rho(index) * direction / 2; ...
        center + rho(index) * direction / 2];
    pair = sortrows(pair, [2, 1]);
    [cached, lookup] = session.lookup_c1(pair, model);
    if any(lookup.cache_hit)
        [oracle_G, ~, oracle_info] = ...
            build_full_sequential_local_manifold(pair, model, ...
            struct('rank_multiplier', 1));
        candidate_G = oracle_G;
        for column = find(lookup.cache_hit).'
            candidate_G(:, column) = cached{column};
            scale = max(1, norm(oracle_G(:, column), 'fro'));
            error_now = norm(candidate_G(:, column) - ...
                oracle_G(:, column), 'fro') / scale;
            max_error = max(max_error, error_now);
            numeric_pass = numeric_pass && error_now <= 1e-10;
        end
        [rank_value, singular_values, threshold] = ...
            stage8_k2_tcc_stable_matrix_rank(candidate_G, 1);
        rank_match = rank_match && ...
            rank_value == oracle_info.rank_Gseq && ...
            max(abs(singular_values - ...
            oracle_info.singular_values_Gseq)) <= ...
            1e-10 * max(1, max(abs( ...
            oracle_info.singular_values_Gseq))) && ...
            abs(threshold - oracle_info.rank_threshold_Gseq) <= ...
            1e-12 * max(1, abs(oracle_info.rank_threshold_Gseq));
    end
end
snapshot = session.snapshot();
delete(session);
shadow = struct('cache_hit_count', snapshot.hit_count, ...
    'cache_miss_count', snapshot.miss_count, ...
    'lookup_count', snapshot.hit_count + snapshot.miss_count, ...
    'max_G_rel_error', max_error, ...
    'numeric_contract_pass', numeric_pass, ...
    'rank_match', rank_match, ...
    'key_collision_count', snapshot.collision_count, ...
    'truth_leakage_count', snapshot.truth_leakage_count, ...
    'all_pass', numeric_pass && rank_match && ...
        snapshot.collision_count == 0 && ...
        snapshot.truth_leakage_count == 0);
end

function match = counts_match_local(result, baseline)
match = double(result.score_call_count) == double(baseline.score_call_count) && ...
    double(result.svd_call_count) == double(baseline.svd_call_count) && ...
    double(result.effective_rank) == double(baseline.effective_rank) && ...
    logical(result.fit_valid) == logical(baseline.fit_valid) && ...
    string(result.selected_source) == string(baseline.selected_source) && ...
    string(result.selected_start_id) == string(baseline.selected_start_id);
end

function totals = mismatch_totals_local(stage_rows)
names = {'key_mismatch_count','rank_mismatch_count', ...
    'candidate_order_mismatch_count','tie_mismatch_count', ...
    'best_index_mismatch_count','accepted_update_mismatch_count', ...
    'trajectory_mismatch_count','selected_start_mismatch_count', ...
    'nested_pass_mismatch_count','final_selector_mismatch_count'};
totals = struct();
for index = 1:numel(names)
    totals.(names{index}) = sum([stage_rows.(names{index})]);
end
end

function identity = checkpoint_identity_local(fixture, spec, index, ...
    integration_hash, ledger_hash, m0, m1)
row_hash = stage8_k2_tcc_stable_hash( ...
    'TECS_FROZEN_REGISTRY_ROW_V1', fixture.registry(index, :));
identity = struct( ...
    'checkpoint_unit_kind', 'CORRECTNESS_TRIAL', ...
    'pass', 'PASS_C_D', 'cache_setting', 'CACHE_ON', ...
    'cache_layer', 'C1', 'variant_alias_id', 'M1', ...
    'comparison_id', 'NOT_APPLICABLE', ...
    'comparison_kind', 'NOT_APPLICABLE', ...
    'baseline_canonical_mode_id', char(m0.candidate_canonical_mode_id), ...
    'candidate_canonical_mode_id', char(m1.candidate_canonical_mode_id), ...
    'enabled_layer_set_hash', char(m1.enabled_layer_set_hash), ...
    'precedence_hash', char(m1.precedence_hash), ...
    'fixed_measurement_hash', char(string( ...
        fixture.semantic_snapshot.rows{index}.fixed_measurement_hash)), ...
    'trial_id', char(spec.trial_id), 'repeat_index', 'NOT_APPLICABLE', ...
    'pair_order', 'NOT_APPLICABLE', ...
    'schedule_row_id', double(spec.global_trial_index), ...
    'schedule_row_hash', row_hash, ...
    'lifecycle_setting', 'NOT_APPLICABLE', ...
    'identity_batch_id', 'NOT_APPLICABLE', ...
    'batch_repeat_index', 'NOT_APPLICABLE', ...
    'lifecycle_operation', 'NOT_APPLICABLE', ...
    'operation_repeat_index', 'NOT_APPLICABLE', ...
    'run_id', fixture.design.run_id, ...
    'baseline_commit', fixture.design.baseline_commit, ...
    'initial_execution_start_commit', ...
        fixture.design.initial_execution_start_commit, ...
    'stage_commit_ledger_hash', ledger_hash, ...
    'integration_code_commit', 'NOT_COMMITTED_PASS_C_D', ...
    'prompt_hash', fixture.design.execution_prompt_hash, ...
    'baseline_snapshot_hash', fixture.design.baseline_snapshot_hash, ...
    'cache_code_hash', integration_hash, ...
    'trial_registry_hash', fixture.design.trial_registry_hash, ...
    'key_schema_hash', fixture.design.key_schema_hash, ...
    'semantic_output_projection_hash', ...
        fixture.design.semantic_output_projection_hash, ...
    'hook_allowlist_hash', fixture.design.hook_allowlist_hash, ...
    'timing_protocol_hash', 'NOT_CLOSED', ...
    'phase_schedule_hash', fixture.design.trial_registry_hash, ...
    'final_measurement_candidate_hash', 'NOT_CLOSED', ...
    'design_freeze_hash', fixture.design.freeze_payload_hash, ...
    'component_freeze_hash', fixture.component.freeze_payload_hash, ...
    'timing_freeze_hash', 'NOT_CLOSED', ...
    'final_candidate_freeze_hash', 'NOT_CLOSED', ...
    'MATLAB_release', version('-release'), ...
    'singleCompThread', true, ...
    'cache_reset_lifecycle_rule', ...
        'PRISTINE_SESSION_PER_TRIAL_PREBUILT_C1_ONLY');
end

function row = mode_for_alias_local(modes, alias)
match = modes.aliases.variant_alias_id == string(alias);
assert(nnz(match) == 1, ...
    'stage8_k2_tecs_run_shadow_validation:ModeAlias');
row = modes.aliases(match, :);
end

function row = correctness_template_local()
row = struct('schema_version', "STAGE8_K2_TECS_CORRECTNESS_V1", ...
    'cache_candidate_canonical_mode_id', "", 'cache_layer', "", ...
    'fixed_measurement_hash', "", 'trial_id', "", ...
    'continuous_numeric_pass', false, 'G_rel_error', NaN, ...
    'rank_match', false, 'score_match', false, ...
    'candidate_order_match', false, 'tie_match', false, ...
    'best_index_match', false, 'accepted_update_match', false, ...
    'trajectory_match', false, 'selected_start_match', false, ...
    'nested_pass_match', false, 'final_selector_match', false, ...
    'truth_isolation_pass', false, ...
    'cache_off_baseline_match', false, ...
    'cache_hit_count', 0, 'cache_miss_count', 0, ...
    'physical_producer_call_count', 0, ...
    'logical_score_call_count', 0, 'logical_svd_call_count', 0, ...
    'bytes_peak', 0, 'key_collision_count', 0, ...
    'truth_leakage_count', 0, 'correctness_pass', false, ...
    'failure_reason', "NOT_RUN");
end

function reason = failure_reason_local(off, decision, trajectory, ...
    mismatch, counters, shadow, truth)
flags = [off, decision, trajectory, mismatch, counters, shadow, truth];
names = ["CACHE_OFF_BASELINE","DECISION","TRAJECTORY", ...
    "AUDIT_MISMATCH","COUNTERS","SHADOW","TRUTH"];
reason = strjoin(cellstr(names(~flags)), '|');
end

function atomic_checkpoint_local(path_now, checkpoint)
temporary = [path_now, '.tmp'];
save(temporary, 'checkpoint', '-v7.3');
movefile(temporary, path_now, 'f');
end
