function sample = stage8_k2_tecs_run_root( ...
    trial, base_context, fixture, enabled_layers)
%STAGE8_K2_TECS_RUN_ROOT Execute exactly one externally timed root call.

enabled_layers = reshape(cellstr(upper(string(enabled_layers))), [], 1);
if ~(isempty(enabled_layers) || isequal(enabled_layers, {'C1'}))
    error('stage8_k2_tecs_run_root:Mode', ...
        'Only frozen M0 and required C1 are runnable in this study.');
end
stage8_k2_tcc_audit_state('CONFIGURE', struct('mode', 'OFF'));
context = base_context;
session = [];
if isempty(enabled_layers)
    if isfield(context, 'manifold_provider')
        context = rmfield(context, 'manifold_provider');
    end
else
    session = stage8_k2_tecs_make_session( ...
        fixture, trial.model.fixed_measurement_hash, enabled_layers);
    context.manifold_provider = stage8_k2_tecs_build_provider(session, ...
        struct('per_call_timing_enabled', false));
end
drawnow;
root_clock = tic;
[result, diagnostics] = stage8_k2_tp_fit_safe( ...
    trial.Y_element, trial.model, context);
elapsed_sec = toc(root_clock);

if isempty(session)
    cache = struct('hit_count', 0, 'miss_count', 0, ...
        'physical_producer_call_count', 0, 'entry_count', 0, ...
        'bytes_current', 0, 'bytes_peak', 0, 'eviction_count', 0, ...
        'collision_count', 0, 'truth_leakage_count', 0, ...
        'reset_count', 0);
else
    cache = session.snapshot();
    delete(session);
end
projection_mode = 'CACHE_OFF_BASELINE';
if ~isempty(enabled_layers), projection_mode = 'CACHE_ON_DECISION'; end
projection = stage8_k2_tecs_root_projection( ...
    result, diagnostics, projection_mode);
sample = struct( ...
    'elapsed_sec', elapsed_sec, ...
    'result_checksum_hash', stage8_k2_tecs_sha256( ...
        'TECS_TIMED_ROOT_DECISION_PROJECTION_V1', projection), ...
    'fit_valid', logical(result.fit_valid), ...
    'selected_source', char(result.selected_source), ...
    'selected_start_id', char(result.selected_start_id), ...
    'logical_score_call_count', double(result.score_call_count), ...
    'logical_svd_call_count', double(result.svd_call_count), ...
    'cache_hit_count', double(cache.hit_count), ...
    'cache_miss_count', double(cache.miss_count), ...
    'physical_producer_call_count', ...
        double(cache.physical_producer_call_count), ...
    'entry_count', double(cache.entry_count), ...
    'bytes_current', double(cache.bytes_current), ...
    'bytes_peak', double(cache.bytes_peak), ...
    'eviction_count', double(cache.eviction_count), ...
    'key_collision_count', double(cache.collision_count), ...
    'truth_leakage_count', double(cache.truth_leakage_count));
end
