function stage8_k2_tecs_validate_checkpoint_identity(checkpoint, expected)
%STAGE8_K2_TECS_VALIDATE_CHECKPOINT_IDENTITY Fail closed on provenance drift.

required = {'checkpoint_unit_kind','pass','unit_complete', ...
    'baseline_commit','initial_execution_start_commit','run_id', ...
    'stage_commit_ledger_hash','integration_code_commit','prompt_hash', ...
    'baseline_snapshot_hash','cache_code_hash','frozen_function_hashes', ...
    'trial_registry_hash','key_schema_hash', ...
    'semantic_output_projection_hash','hook_allowlist_hash', ...
    'timing_protocol_hash','phase_schedule_hash', ...
    'final_measurement_candidate_hash','design_freeze_hash', ...
    'component_freeze_hash_or_sentinel', ...
    'timing_freeze_hash_or_sentinel', ...
    'final_candidate_freeze_hash_or_sentinel','MATLAB_release', ...
    'singleCompThread','cache_reset_lifecycle_rule'};
if ~(isstruct(checkpoint) && isscalar(checkpoint) && ...
        all(isfield(checkpoint, required)) && checkpoint.unit_complete)
    error('stage8_k2_tecs_validate_checkpoint_identity:Incomplete', ...
        'CHECKPOINT_IDENTITY_MISMATCH_STOP: incomplete checkpoint.');
end
names = fieldnames(expected);
for index = 1:numel(names)
    name = names{index};
    if ~isfield(checkpoint, name) || ...
            ~isequaln(checkpoint.(name), expected.(name))
        error('stage8_k2_tecs_validate_checkpoint_identity:Mismatch', ...
            'CHECKPOINT_IDENTITY_MISMATCH_STOP: field %s differs.', name);
    end
end
end
