function provider = stage8_k2_tecs_build_provider(session, options)
%STAGE8_K2_TECS_BUILD_PROVIDER Build explicit experimental provider state.

if nargin < 2 || isempty(options), options = struct(); end
if ~(isa(session, 'stage8_k2_tecs_cache_session') && isvalid(session))
    error('stage8_k2_tecs_build_provider:Session', ...
        'An explicit live stage8_k2_tecs_cache_session is required.');
end
if ~(isstruct(options) && isscalar(options))
    error('stage8_k2_tecs_build_provider:Options', ...
        'Provider options must be a scalar struct.');
end
unknown = setdiff(fieldnames(options), {'per_call_timing_enabled'});
if ~isempty(unknown)
    error('stage8_k2_tecs_build_provider:UnknownOption', ...
        'Unknown provider option: %s.', unknown{1});
end
per_call_timing_enabled = false;
if isfield(options, 'per_call_timing_enabled')
    per_call_timing_enabled = options.per_call_timing_enabled;
end
if ~(islogical(per_call_timing_enabled) && isscalar(per_call_timing_enabled))
    error('stage8_k2_tecs_build_provider:TimingOption', ...
        'per_call_timing_enabled must be a scalar logical.');
end
snapshot = session.snapshot();
provider = struct( ...
    'mode','TECS_EXACT_STACK', ...
    'cache_setting','CACHE_ON', ...
    'cache_session',session, ...
    'fixed_measurement_hash',snapshot.fixed_measurement_hash, ...
    'enabled_layers',{snapshot.enabled_layers}, ...
    'per_call_timing_enabled',per_call_timing_enabled, ...
    'raw_event_logging_enabled',false, ...
    'production_default_cache_setting','CACHE_OFF', ...
    'created_by','stage8_k2_tecs_build_provider');
end
