function scope = collect_stage7_source_scope(repo_dir, opts)
%COLLECT_STAGE7_SOURCE_SCOPE Return executable and dependency identities.

if nargin < 2 || isempty(opts), opts = struct(); end
if ~(isstruct(opts) && isscalar(opts) && isempty(fieldnames(opts)))
    error('collect_stage7_source_scope:Options', ...
        'No options are currently supported.');
end
if isstring(repo_dir), repo_dir = char(repo_dir); end
if ~(ischar(repo_dir) && isrow(repo_dir) && exist(repo_dir, 'dir') == 7)
    error('collect_stage7_source_scope:RepoDir', ...
        'repo_dir must identify an existing directory.');
end

step_root = ['beamspace_ml_v18/source/stepwise_signal_model/steps/', ...
    'step_12_5_exact_subset_fim_beam_design'];
[status, output] = system(sprintf('git -C "%s" ls-files -- "%s"', ...
    repo_dir, step_root));
if status ~= 0
    error('collect_stage7_source_scope:Git', ...
        'Unable to enumerate tracked Stage 7 paths: %s', strtrim(output));
end
tracked = splitlines(string(regexprep(output, '[\r\n]+$', '')));
tracked(tracked == "") = [];
source_paths = tracked(endsWith(tracked, '.m') | ...
    tracked == string([step_root, '/README.md']));
source_paths = sort(source_paths);
if isempty(source_paths) || any(contains(source_paths, '/results/') | ...
        contains(source_paths, '/figures/'))
    error('collect_stage7_source_scope:SourceScope', ...
        'Stage 7 source scope is empty or includes generated evidence.');
end

dependency_paths = [ ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_0_receive_model_correction/common/build_receive_cyl_steering_vec.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_0_receive_model_correction/common/build_receive_cyl_steering_with_derivatives.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_1_sequential_dbf_model/common/build_sequential_beam_matrix.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_1_sequential_dbf_model/common/build_sequential_beamspace_manifold.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_1_sequential_dbf_model/common/form_elevation_dbf_cube.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_1_sequential_dbf_model/common/form_azimuth_dbf_cube.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_1_sequential_dbf_model/common/reshape_cyl_vector_to_matrix.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_1_sequential_dbf_model/common/reshape_cyl_matrix_to_vector.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_1_sequential_dbf_model/common/private/derive_cyl_array_layout.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_2_stable_dml_backend/common/beamspace_dml_score_svd.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_2_stable_dml_backend/common/build_psd_whitener.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_2_stable_dml_backend/common/stable_numeric_rank.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/build_full_sequential_local_manifold.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/refine_joint_sequential_dml.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_3_grouped_conditional_dml/common/private/stable_matrix_rank.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_4_near_pair_tangent_asymptotics/results/stage6_evidence_manifest.csv"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/steps/step_12_4_near_pair_tangent_asymptotics/results/stage6_provenance_contract.csv"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/core/config/sim_cfg.m"; ...
    "beamspace_ml_v18/source/stepwise_signal_model/core/array/arr_cyl.m"];
dependency_paths = sort(dependency_paths);
if numel(unique(dependency_paths)) ~= numel(dependency_paths)
    error('collect_stage7_source_scope:DuplicateDependency', ...
        'Dependency scope contains duplicate paths.');
end
allowed_evidence = endsWith(dependency_paths, ...
    ["/stage6_evidence_manifest.csv";"/stage6_provenance_contract.csv"]);
generated = contains(dependency_paths, '/results/') | ...
    contains(dependency_paths, '/figures/');
if any(generated & ~allowed_evidence)
    error('collect_stage7_source_scope:GeneratedDependency', ...
        'Only frozen Stage 6 identity artifacts may be dependencies.');
end
for index = 1:numel(dependency_paths)
    if exist(fullfile(repo_dir, char(dependency_paths(index))), 'file') ~= 2
        error('collect_stage7_source_scope:MissingDependency', ...
            'Missing registered dependency: %s.', dependency_paths(index));
    end
end

scope = struct('source_paths', source_paths, ...
    'dependency_paths', dependency_paths, ...
    'source_scope_version', 'STAGE7_EXECUTABLE_SOURCE_SCOPE_V1', ...
    'dependency_scope_version', ...
    'STAGE7_DIRECT_AND_STAGE6_IDENTITY_DEPENDENCY_SCOPE_V1');
end
