function pair = stage8_k2_tfbc_test_fixed_fit_pair(fixture, K)
%STAGE8_K2_TFBC_TEST_FIXED_FIT_PAIR Build matched full fixed fits.

trial = fixture.trials{1};
domain = fixture.context.plan.local_domain;
identity = stage8_k2_tfbc_identity_for_trial(fixture, trial);
data = build_stage8_full_data_from_element(trial.Y_element, trial.model, ...
    struct('data_role','SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
[legacy_init, ~] = build_stage8_initialization_context_from_data( ...
    data, trial.model, domain, fixture.context.stage5_locked, ...
    trial.model.noise_factorization, struct('rank_multiplier',1, ...
    'fixed_registered_manifold_provider',identity.provider_timed, ...
    'fixed_manifold_mode','LEGACY_FULL'));
[cache_init, ~] = build_stage8_initialization_context_from_data( ...
    data, trial.model, domain, fixture.context.stage5_locked, ...
    trial.model.noise_factorization, struct('rank_multiplier',1, ...
    'fixed_registered_manifold_provider',identity.provider_timed, ...
    'fixed_manifold_mode','REGISTERED_CACHE'));
legacy_options = struct('fixed_registered_manifold_provider', ...
    identity.provider_timed, 'fixed_manifold_mode','LEGACY_FULL');
cache_options = struct('fixed_registered_manifold_provider', ...
    identity.provider_timed, 'fixed_manifold_mode','REGISTERED_CACHE');
if K == 2
    legacy_helper = fit_local_model_k(data, 1, domain, trial.model, ...
        legacy_init, legacy_options);
    cache_helper = fit_local_model_k(data, 1, domain, trial.model, ...
        cache_init, cache_options);
    legacy_init.k1_fit = legacy_helper;
    cache_init.k1_fit = cache_helper;
end
[legacy_fit, legacy_debug] = fit_local_model_k( ...
    data, K, domain, trial.model, legacy_init, legacy_options);
[cache_fit, cache_debug] = fit_local_model_k( ...
    data, K, domain, trial.model, cache_init, cache_options);
pair = struct('legacy_fit',legacy_fit, 'cache_fit',cache_fit, ...
    'legacy_debug',legacy_debug, 'cache_debug',cache_debug, ...
    'legacy_initialization',legacy_init, ...
    'cache_initialization',cache_init, 'data',data, ...
    'trial',trial, 'identity',identity);
end
