function result = test_stage8_k2_tfbc_t4_bypass(fixture)
%TEST_STAGE8_K2_TFBC_T4_BYPASS Verify finite cache never serves T4.

trial = fixture.trials{1};
identity = stage8_k2_tfbc_identity_for_trial(fixture, trial);
stage8_k2_tfbc_diagnostics_state('RESET');
[legacy, legacy_diagnostics, legacy_hash] = stage8_k2_tfbc_fit_mode( ...
    trial, fixture.context, identity.provider_diagnostic, 'LEGACY_FULL');
[cached, cache_diagnostics, cache_hash] = stage8_k2_tfbc_fit_mode( ...
    trial, fixture.context, identity.provider_diagnostic, 'REGISTERED_CACHE');
exposure = stage8_k2_tfbc_diagnostics_state('SNAPSHOT');
t4_queries = cache_diagnostics.cache_hit_count + ...
    cache_diagnostics.cache_miss_count + ...
    cache_diagnostics.direct_fallback_count;
pass = strcmp(legacy_hash, cache_hash) && ...
    isequaln(stage8_k2_tfbc_strip_runtime(legacy), ...
    stage8_k2_tfbc_strip_runtime(cached)) && ...
    strcmp(legacy_diagnostics.manifold_provider_mode, 'LEGACY_DIRECT') && ...
    strcmp(cache_diagnostics.manifold_provider_mode, 'LEGACY_DIRECT') && ...
    t4_queries == 0 && exposure.cache_hit_count > 0 && ...
    exposure.cache_miss_count == 0;
assert(pass, 'test_stage8_k2_tfbc_t4_bypass:Failed');
result = struct('pass',pass, 't4_cache_queries',t4_queries, ...
    'fixed_cache_hits',exposure.cache_hit_count);
end
