function result = test_stage8_k2_tfbc_final_certification(fixture)
%TEST_STAGE8_K2_TFBC_FINAL_CERTIFICATION Preserve selected G/RSS/loglik.

pair = stage8_k2_tfbc_test_fixed_fit_pair(fixture, 2);
pass = isequal(pair.legacy_fit.G_hat, pair.cache_fit.G_hat) && ...
    isequal(pair.legacy_fit.rss, pair.cache_fit.rss) && ...
    isequal(pair.legacy_fit.loglik_concentrated, ...
    pair.cache_fit.loglik_concentrated) && ...
    strcmp(pair.legacy_fit.initialization_id, ...
    pair.cache_fit.initialization_id);
assert(pass, 'test_stage8_k2_tfbc_final_certification:Failed');
result = struct('pass',pass, 'selected_start_id', ...
    pair.cache_fit.initialization_id);
end
