function audit = stage8_k2_wcb_preflight(repo_dir, constants)
%STAGE8_K2_WCB_PREFLIGHT Enforce the pushed work-branch and frozen scope.

audit = struct('pass', false, 'branch', '', 'head', '', ...
    'remote_work', '', 'origin_tangent', '', 'origin_main', '', ...
    'origin_research', '', 'old_work', '', 'worktree_clean', false, ...
    'frozen_paths_clean', false, 'last_error', '');
try
    audit.branch = git_output_local(repo_dir, 'branch --show-current');
    audit.head = git_output_local(repo_dir, 'rev-parse HEAD');
    audit.remote_work = git_output_local(repo_dir, ...
        ['rev-parse origin/work/', ...
        'stage8-k2-white-snr-classical-baselines-v1']);
    audit.origin_tangent = git_output_local(repo_dir, ...
        'rev-parse origin/experiment/stage8-k2-tangent');
    audit.origin_main = git_output_local(repo_dir, 'rev-parse origin/main');
    audit.origin_research = git_output_local(repo_dir, ...
        'rev-parse origin/research/stage8-k2-vincent-anchored');
    audit.old_work = git_output_local(repo_dir, ...
        'rev-parse origin/work/stage8-k2-subspace-baselines-v1');
    audit.worktree_clean = isempty(git_output_local(repo_dir, ...
        'status --porcelain=v1 --untracked-files=all'));
    ancestor = git_status_local(repo_dir, sprintf( ...
        'merge-base --is-ancestor %s HEAD', constants.starting_commit));

    frozen = { ...
        'tools/stage8_k2_tangent_profile', ...
        'tools/stage8_k2_classical_baselines', ...
        'tools/stage8_k2_subspace_baselines', ...
        'tools/stage8_k2_snr_validation', ...
        'tools/stage8_k2_white_snr_monte_carlo', ...
        'beamspace_ml_v18'};
    prefixes = {'31','32','33','34','39','40','41','41A','42','43','44'};
    checks = true(numel(frozen) + numel(prefixes), 1);
    for index = 1:numel(frozen)
        checks(index) = git_status_local(repo_dir, sprintf( ...
            'diff --quiet %s..HEAD -- %s', ...
            constants.starting_commit, frozen{index}));
    end
    offset = numel(frozen);
    for index = 1:numel(prefixes)
        checks(offset + index) = git_status_local(repo_dir, sprintf( ...
            'diff --quiet %s..HEAD -- ":(glob)innovation-mining/%s_*"', ...
            constants.starting_commit, prefixes{index}));
    end
    audit.frozen_paths_clean = all(checks);
    if ~strcmp(audit.branch, constants.branch) || ...
            ~strcmp(audit.head, audit.remote_work) || ...
            ~strcmp(audit.origin_tangent, ...
            constants.expected_origin_tangent) || ...
            ~strcmp(audit.origin_main, constants.expected_origin_main) || ...
            ~strcmp(audit.origin_research, ...
            constants.expected_origin_research) || ...
            ~strcmp(audit.old_work, constants.expected_old_work) || ...
            ~audit.worktree_clean || ~ancestor || ~audit.frozen_paths_clean
        error('Branch, remote, immutable refs, clean tree, or scope failed.');
    end
    audit.pass = true;
catch exception
    audit.last_error = exception.message;
end
end

function output = git_output_local(repo_dir, arguments)
[status, output] = system(sprintf('git -C "%s" %s', repo_dir, arguments));
if status ~= 0
    error('stage8_k2_wcb_preflight:Git', ...
        'Git command failed: %s', arguments);
end
output = strtrim(output);
end

function pass = git_status_local(repo_dir, arguments)
[status, ~] = system(sprintf('git -C "%s" %s', repo_dir, arguments));
pass = status == 0;
end
