function fits = stage8_k2_wcb_fit_baselines(fit_input, constants)
%STAGE8_K2_WCB_FIT_BASELINES Fit registered baselines without evaluation data.

forbidden = {'truth','truth_angles_deg','profile_id','profile_label', ...
    'tangent','tangent_result','core','core_result','RMSE', ...
    'joint_RMSE_deg','working_region_label','white_snr_target_db'};
present = intersect(fieldnames(fit_input), forbidden);
if ~isempty(present)
    error('stage8_k2_wcb_fit_baselines:TruthIsolation', ...
        'Fit input contains prohibited evaluation field: %s', present{1});
end
required = {'Y_element','model','local_domain','resource_entry', ...
    'resources','L','run_element_cml'};
if ~isstruct(fit_input) || ~all(isfield(fit_input, required))
    error('stage8_k2_wcb_fit_baselines:Input', ...
        'The data-only fit input is incomplete.');
end

full_data = build_stage8_full_data_from_element( ...
    fit_input.Y_element, fit_input.model, ...
    struct('data_role', 'SINGLE_CPI_SINGLE_RANGE_DOPPLER_CELL'));
beam_cml = stage8_k2_cb_full4d_cml(full_data.Zseq_white, ...
    fit_input.model, fit_input.local_domain, 'BEAMSPACE', ...
    struct(), constants);
beam_cml.online_runtime_sec = beam_cml.runtime_sec;
beam_cml.selected_source = "FULL4D_NUMERICAL_MULTISTART";

beam_music = stage8_k2_cb_music(full_data.Zseq_white, ...
    fit_input.resource_entry, fit_input.resources, 'BEAMSPACE', ...
    double(fit_input.L), constants);
applicable_per_noise = numel(constants.music_applicable_L) * ...
    numel(constants.white_snr_targets_db) * ...
    numel(constants.profile_ids) * constants.replicate_count;
beam_music.precompute_runtime_sec_amortized = ...
    fit_input.resource_entry.standalone_precompute_runtime_sec / ...
    applicable_per_noise;
beam_music.runtime_sec = beam_music.online_runtime_sec + ...
    beam_music.precompute_runtime_sec_amortized;

if logical(fit_input.run_element_cml)
    [Y_element_white, whitening_now] = ...
        stage8_k2_cb_whiten_element_data( ...
        fit_input.Y_element, fit_input.model);
    if norm(whitening_now.whitener - ...
            fit_input.resource_entry.whitening.whitener, 'fro') > 1e-10
        error('stage8_k2_wcb_fit_baselines:WhiteningIdentity', ...
            'Per-trial and fixed element whiteners disagree.');
    end
    element_cml = stage8_k2_cb_full4d_cml(Y_element_white, ...
        fit_input.model, fit_input.local_domain, 'ELEMENT', ...
        fit_input.resource_entry.whitening, constants);
    element_cml.online_runtime_sec = element_cml.runtime_sec;
    element_cml.selected_source = "FULL4D_NUMERICAL_MULTISTART";
else
    element_cml = element_placeholder_local();
end

fits = struct('beamspace_full4d', beam_cml, ...
    'beamspace_music', beam_music, 'element_full4d', element_cml, ...
    'truth_used_in_fit_flag', false, ...
    'profile_used_in_fit_flag', false, ...
    'tangent_used_in_start_flag', false, ...
    'core_used_in_start_flag', false);
end

function result = element_placeholder_local()
status = "NOT_IN_REGISTERED_ELEMENT_REFERENCE_SUBSET";
result = struct('method_id', ...
    "FULL4D_ELEMENT_CML_MULTISTART", ...
    'observation_domain', "ELEMENT", 'applicable', false, ...
    'applicability_status', status, 'fit_valid', false, ...
    'fit_status', status, 'optimizer_status', "NOT_APPLICABLE", ...
    'angles_hat_deg', NaN(2, 2), 'rss', NaN, ...
    'loglik_concentrated', NaN, 'effective_rank', 0, ...
    'selected_start_id', "", 'sweep_count', 0, ...
    'score_call_count', 0, 'svd_call_count', 0, ...
    'eig_call_count', 0, 'runtime_sec', 0, ...
    'online_runtime_sec', 0, 'precompute_runtime_sec_amortized', 0, ...
    'coarse_candidate_count', 0, 'continuous_start_count', 0, ...
    'local_peak_count', 0, 'peak_values', [NaN, NaN], ...
    'truth_used_in_fit_flag', false, ...
    'profile_used_in_fit_flag', false, ...
    'tangent_used_in_start_flag', false, ...
    'core_used_in_start_flag', false, ...
    'full_manifold_used_flag', false);
end
