function [rows, diagnostics] = stage8_k2_wcb_evaluate_trial( ...
    spec, trial, context, resources)
%STAGE8_K2_WCB_EVALUATE_TRIAL Fit baselines, then add paired diagnostics.

entry_index = find([resources.entries.noise_profile_id] == ...
    string(spec.noise_profile_id), 1);
if isempty(entry_index)
    error('stage8_k2_wcb_evaluate_trial:Resource', ...
        'No fixed resource entry matches the trial noise profile.');
end
entry = resources.entries(entry_index);
if string(entry.model.fixed_measurement_hash) ~= ...
        string(trial.model.fixed_measurement_hash)
    error('stage8_k2_wcb_evaluate_trial:ModelIdentity', ...
        'Trial and fixed resource measurement models disagree.');
end
fit_input = struct('Y_element', trial.Y_element, ...
    'model', trial.model, 'local_domain', context.plan.local_domain, ...
    'resource_entry', entry, 'resources', resources, ...
    'L', double(spec.L), ...
    'run_element_cml', logical(spec.element_cml_registered_flag));
fits = stage8_k2_wcb_fit_baselines(fit_input, context.constants);

tangent = context.tangent_rows( ...
    context.tangent_rows.trial_id == spec.trial_id, :);
if height(tangent) ~= 1 || tangent.element_trial_hash ~= ...
        trial.element_trial_hash
    error('stage8_k2_wcb_evaluate_trial:TangentPairing', ...
        'The evidence-44 Tangent row does not pair to this trial.');
end
tangent_loglik = double(tangent.loglik);

beam_row = stage8_k2_wcb_result_row( ...
    spec, trial, fits.beamspace_full4d, context.constants);
tolerance = 64 * eps('double') * max(1, abs(tangent_loglik));
incomplete = beam_row.fit_valid && isfinite(tangent_loglik) && ...
    beam_row.loglik < tangent_loglik - tolerance;
beam_row.raw_tangent_loglik_reference = tangent_loglik;
beam_row.likelihood_tolerance = tolerance;
beam_row.numerical_optimization_incomplete_flag = incomplete;
beam_row.complete_likelihood_subset_flag = beam_row.fit_valid && ...
    beam_row.loglik >= tangent_loglik - tolerance;
if incomplete
    beam_row.numerical_optimization_status = ...
        "NUMERICAL_OPTIMIZATION_INCOMPLETE";
else
    beam_row.numerical_optimization_status = "NOT_DETECTED";
end

music_row = stage8_k2_wcb_result_row( ...
    spec, trial, fits.beamspace_music, context.constants);
element_row = stage8_k2_wcb_result_row( ...
    spec, trial, fits.element_full4d, context.constants);
rows = struct2table([beam_row; music_row; element_row]);
diagnostics = struct('trial_id', string(spec.trial_id), ...
    'element_trial_hash', string(trial.element_trial_hash), ...
    'measurement_hash', string(trial.measurement_hash), ...
    'beam_cml_valid', beam_row.fit_valid, ...
    'beam_cml_incomplete', incomplete, ...
    'music_valid', music_row.fit_valid, ...
    'music_single_peak', music_row.applicable && ...
    music_row.fit_status == "MUSIC_FEWER_THAN_TWO_PEAKS", ...
    'element_cml_completed', element_row.applicable, ...
    'truth_isolation_flag', ...
    ~any(rows.truth_used_in_fit_flag) && ...
    ~any(rows.profile_used_in_fit_flag) && ...
    ~any(rows.tangent_used_in_start_flag) && ...
    ~any(rows.core_used_in_start_flag));
end
