function audit = stage8_k2_wcb_checkpoint_validate( ...
    path_now, expected_spec, context, registry_hash)
%STAGE8_K2_WCB_CHECKPOINT_VALIDATE Validate one final or temporary file.

required = {'protocol','checkpoint_contract_version', ...
    'evidence44_registry_row','registry_row','trial_identity', ...
    'full4d_beamspace_row','beamspace_music_row','element_cml_row', ...
    'baseline_rows','scientific_hash','code_identity','registry_hash', ...
    'completed_utc','runtime_sec','completion_status'};
if ~isfile(path_now)
    error('stage8_k2_wcb_checkpoint_validate:Missing', ...
        'Checkpoint is missing: %s', path_now);
end
loaded = load(path_now, 'checkpoint', '-mat');
if ~isfield(loaded, 'checkpoint') || ~isstruct(loaded.checkpoint) || ...
        ~isscalar(loaded.checkpoint) || ...
        ~all(isfield(loaded.checkpoint, required))
    error('stage8_k2_wcb_checkpoint_validate:Schema', ...
        'Checkpoint schema is invalid: %s', path_now);
end
checkpoint = loaded.checkpoint;
constants = context.constants;
if ~strcmp(checkpoint.protocol, constants.protocol) || ...
        ~strcmp(checkpoint.checkpoint_contract_version, ...
        constants.checkpoint_contract_version) || ...
        ~strcmp(checkpoint.completion_status, 'COMPLETE') || ...
        ~strcmp(checkpoint.code_identity, context.code_identity.tree_hash) || ...
        ~strcmp(checkpoint.registry_hash, registry_hash)
    error('stage8_k2_wcb_checkpoint_validate:Identity', ...
        'Checkpoint protocol, code, registry, or status is invalid.');
end
if ~(istable(checkpoint.registry_row) && ...
        height(checkpoint.registry_row) == 1) || ...
        ~strcmp(stage8_k2_wcb_stable_hash( ...
        'REGISTRY_ROW', checkpoint.registry_row), ...
        stage8_k2_wcb_stable_hash('REGISTRY_ROW', expected_spec))
    error('stage8_k2_wcb_checkpoint_validate:RegistryRow', ...
        'Checkpoint registry row differs from the frozen baseline registry.');
end
expected_evidence = context.evidence44.registry( ...
    context.evidence44.registry.trial_id == expected_spec.trial_id, :);
if height(expected_evidence) ~= 1 || ...
        ~strcmp(stage8_k2_wcb_stable_hash( ...
        'EVIDENCE44_ROW', checkpoint.evidence44_registry_row), ...
        stage8_k2_wcb_stable_hash('EVIDENCE44_ROW', expected_evidence))
    error('stage8_k2_wcb_checkpoint_validate:EvidenceRow', ...
        'Checkpoint evidence-44 row changed.');
end

rows = checkpoint.baseline_rows;
if ~(istable(rows) && height(rows) == 3) || ...
        any(rows.trial_id ~= expected_spec.trial_id) || ...
        ~isequal(sort(rows.method_id), sort(constants.baseline_method_ids)) || ...
        any(rows.element_trial_hash ~= expected_spec.element_trial_hash) || ...
        any(rows.measurement_hash ~= expected_spec.measurement_hash) || ...
        ~strcmp(stage8_k2_wcb_stable_hash( ...
        checkpoint.full4d_beamspace_row, checkpoint.beamspace_music_row, ...
        checkpoint.element_cml_row), ...
        stage8_k2_wcb_stable_hash( ...
        rows(rows.method_id == "FULL4D_BEAMSPACE_CML_MULTISTART", :), ...
        rows(rows.method_id == "BEAMSPACE_MUSIC_K2", :), ...
        rows(rows.method_id == "FULL4D_ELEMENT_CML_MULTISTART", :)))
    error('stage8_k2_wcb_checkpoint_validate:Rows', ...
        'Checkpoint result rows do not match the registered trial.');
end
identity = checkpoint.trial_identity;
if ~isstruct(identity) || ...
        string(identity.trial_id) ~= expected_spec.trial_id || ...
        string(identity.element_trial_hash) ~= ...
        expected_spec.element_trial_hash || ...
        string(identity.measurement_hash) ~= expected_spec.measurement_hash || ...
        double(identity.white_target_error_db) > constants.snr_db_tolerance
    error('stage8_k2_wcb_checkpoint_validate:TrialIdentity', ...
        'Reconstructed trial identity failed.');
end

music = rows(rows.method_id == "BEAMSPACE_MUSIC_K2", :);
element = rows(rows.method_id == ...
    "FULL4D_ELEMENT_CML_MULTISTART", :);
if logical(music.applicable) ~= ...
        logical(expected_spec.music_applicable_flag) || ...
        logical(element.applicable) ~= ...
        logical(expected_spec.element_cml_registered_flag) || ...
        any(rows.fit_status == "NOT_RUN") || ...
        any(rows.truth_used_in_fit_flag) || ...
        any(rows.profile_used_in_fit_flag) || ...
        any(rows.tangent_used_in_start_flag) || ...
        any(rows.core_used_in_start_flag)
    error('stage8_k2_wcb_checkpoint_validate:Applicability', ...
        'Applicability, outcome, or fit-isolation integrity failed.');
end
valid = rows.fit_valid;
if any(valid & ~isfinite(rows.joint_RMSE_deg)) || ...
        any(valid & strlength(rows.angles_hat_deg) == 0)
    error('stage8_k2_wcb_checkpoint_validate:FiniteMetrics', ...
        'A valid row contains nonfinite registered metrics.');
end
cml = valid & contains(rows.method_id, "FULL4D");
if any(cml & (~isfinite(rows.RSS) | ~isfinite(rows.loglik)))
    error('stage8_k2_wcb_checkpoint_validate:FiniteLikelihood', ...
        'A valid CML row contains nonfinite likelihood outputs.');
end
actual_hash = stage8_k2_wcb_checkpoint_hash(checkpoint);
if ~strcmp(actual_hash, checkpoint.scientific_hash)
    error('stage8_k2_wcb_checkpoint_validate:ScientificHash', ...
        'Checkpoint scientific hash is invalid.');
end
audit = struct('pass', true, 'path', string(path_now), ...
    'trial_id', string(expected_spec.trial_id), ...
    'scientific_hash', string(actual_hash), ...
    'runtime_sec', double(checkpoint.runtime_sec), ...
    'white_target_error_db', double(identity.white_target_error_db));
end
