function [trial, metrics, identity] = stage8_k2_wcb_reconstruct_trial( ...
    spec, context)
%STAGE8_K2_WCB_RECONSTRUCT_TRIAL Rebuild and verify one evidence-44 trial.

[trial, metrics] = stage8_k2_mc_generate_trial(spec, context.mc_context);
target_error_db = abs(double(metrics.white_beam_snr_expected_db) - ...
    double(spec.white_beamspace_snr_target_db));
if trial.element_trial_hash ~= spec.element_trial_hash || ...
        trial.measurement_hash ~= spec.measurement_hash || ...
        target_error_db > context.constants.snr_db_tolerance
    error('stage8_k2_wcb_reconstruct_trial:Identity', ...
        'Reconstructed hash, measurement, or white-SNR target changed.');
end
identity = struct('trial_id', string(spec.trial_id), ...
    'measurement_hash', string(trial.measurement_hash), ...
    'element_trial_hash', string(trial.element_trial_hash), ...
    'white_target_error_db', target_error_db, ...
    'element_hash_match_flag', true, ...
    'measurement_hash_match_flag', true);
end
