function context = stage8_k2_wcb_build_context(repo_dir)
%STAGE8_K2_WCB_BUILD_CONTEXT Bind frozen models, evidence, and new code.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_wcb_build_context:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
constants = stage8_k2_wcb_constants();
mc_context = stage8_k2_mc_build_context(repo_dir);
cb_context = stage8_k2_cb_build_context(repo_dir);
evidence44 = stage8_k2_wcb_load_evidence44(repo_dir, constants);
code_identity = stage8_k2_wcb_code_identity(repo_dir);

if ~isequal(mc_context.plan.local_domain.domain_bounds_deg, ...
        cb_context.plan.local_domain.domain_bounds_deg) || ...
        ~strcmp(mc_context.plan.stage8_measurement_plan_hash, ...
        cb_context.plan.stage8_measurement_plan_hash) || ...
        ~isequal(mc_context.constants.white_snr_targets_db, ...
        constants.white_snr_targets_db) || ...
        ~isequal(mc_context.constants.noise_profile_ids, ...
        constants.noise_profile_ids) || ...
        ~isequal(mc_context.constants.snapshot_counts, ...
        constants.snapshot_counts) || ...
        ~isequal(mc_context.constants.profile_ids, constants.profile_ids)
    error('stage8_k2_wcb_build_context:FrozenContext', ...
        'Frozen Monte Carlo and classical contexts no longer agree.');
end

tangent_rows = evidence44.method_rows( ...
    evidence44.method_rows.method_id == "TANGENT_PROFILE_SAFE", :);
if height(tangent_rows) ~= constants.trial_count || ...
        any(~logical(tangent_rows.fit_valid))
    error('stage8_k2_wcb_build_context:TangentRows', ...
        'Evidence 44 must provide one valid Tangent row per trial.');
end
context = struct('repo_dir', repo_dir, 'constants', constants, ...
    'mc_context', mc_context, 'cb_context', cb_context, ...
    'plan', cb_context.plan, 'evidence44', evidence44, ...
    'tangent_rows', tangent_rows, 'code_identity', code_identity, ...
    'primary_measurement_config_id', ...
    constants.primary_measurement_config_id);
context.context_hash = stage8_k2_wcb_stable_hash( ...
    constants.protocol, evidence44.identity, ...
    cb_context.plan.local_domain.domain_hash, ...
    cb_context.plan.stage8_measurement_plan_hash, ...
    code_identity.tree_hash, constants.starting_commit);
end
