function output = stage8_k2_wcb_verify(repo_dir, runtime_root)
%STAGE8_K2_WCB_VERIFY Independently audit without rerunning a baseline.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_wcb_verify:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
constants = stage8_k2_wcb_constants();
if nargin < 2 || isempty(runtime_root)
    runtime_root = constants.runtime_root;
end
repo_dir = char(java.io.File(char(string(repo_dir))).getCanonicalPath());
runtime_root = char(java.io.File(char(string(runtime_root))).getCanonicalPath());
if ~strcmp(version('-release'), '2022b') || maxNumCompThreads ~= 1
    error('stage8_k2_wcb_verify:MATLABRuntime', ...
        'Independent audit requires MATLAB R2022b with -singleCompThread.');
end
try
    pool = gcp('nocreate');
catch
    pool = [];
end
if ~isempty(pool)
    error('stage8_k2_wcb_verify:ParallelPool', ...
        'Independent audit forbids an active parallel pool.');
end
scope = stage8_k2_wcb_add_paths(repo_dir); %#ok<NASGU>
context = stage8_k2_wcb_build_context(repo_dir);
branch_audit_local(repo_dir, constants);

registry_loaded = load(fullfile(runtime_root, 'registry', ...
    'registry.mat'), 'registry', 'registry_hash', '-mat');
formal_loaded = load(fullfile(runtime_root, ...
    'formal_execution_state.mat'), 'formal_state', '-mat');
registry = registry_loaded.registry;
registry_hash = registry_loaded.registry_hash;
formal = formal_loaded.formal_state;
expected_hash = stage8_k2_wcb_stable_hash( ...
    'BASELINE_REGISTRY', registry, context.evidence44.identity, ...
    constants.protocol);
head = git_output_local(repo_dir, 'rev-parse HEAD');
remote = git_output_local(repo_dir, ...
    'rev-parse origin/work/stage8-k2-white-snr-classical-baselines-v1');
if ~strcmp(registry_hash, expected_hash) || ...
        ~strcmp(formal.protocol, constants.protocol) || ...
        ~strcmp(formal.formal_head, head) || ~strcmp(head, remote) || ...
        ~strcmp(formal.context_hash, context.context_hash) || ...
        ~strcmp(formal.code_identity, context.code_identity.tree_hash) || ...
        ~strcmp(formal.registry_hash, registry_hash) || ...
        string(formal.evidence44_identity) ~= context.evidence44.identity || ...
        ~formal.test_output.pass || formal.test_output.test_count ~= 10
    error('stage8_k2_wcb_verify:FormalIdentity', ...
        'Formal registry, code, tests, or Git identity changed.');
end

merged = stage8_k2_wcb_merge( ...
    runtime_root, registry, context, registry_hash);
if merged.scan.completed_count ~= constants.trial_count || ...
        height(merged.baseline_rows) ~= constants.baseline_row_count
    error('stage8_k2_wcb_verify:CheckpointCount', ...
        'Independent checkpoint merge is incomplete.');
end

maximum_target_error = 0;
for index = 1:height(registry)
    [trial, ~, identity] = stage8_k2_wcb_reconstruct_trial( ...
        registry(index, :), context);
    if trial.element_trial_hash ~= registry.element_trial_hash(index) || ...
            trial.measurement_hash ~= registry.measurement_hash(index)
        error('stage8_k2_wcb_verify:Reconstruction', ...
            'Independent trial reconstruction identity changed.');
    end
    maximum_target_error = max(maximum_target_error, ...
        identity.white_target_error_db);
    clear trial
    if mod(index, 240) == 0
        fprintf('Independent reconstruction %d/1680\n', index);
    end
end
if maximum_target_error > constants.snr_db_tolerance
    error('stage8_k2_wcb_verify:WhiteTarget', ...
        'Independent white-SNR target audit failed.');
end

manifest_path = fullfile(repo_dir, 'innovation-mining', ...
    '46_stage8_k2_white_snr_classical_baseline_runtime_manifest.json');
if ~isfile(manifest_path)
    error('stage8_k2_wcb_verify:ManifestMissing', ...
        'The finalized runtime manifest is missing.');
end
manifest = jsondecode(fileread(manifest_path));
if ~strcmp(manifest.status, ...
        'STAGE8_K2_WHITE_SNR_CLASSICAL_BASELINE_FINALIZED_AWAITING_AUDIT') || ...
        ~strcmp(manifest.independent_audit_status, 'PENDING') || ...
        manifest.registry_count ~= constants.trial_count || ...
        manifest.baseline_row_count ~= constants.baseline_row_count || ...
        manifest.checkpoint_count ~= constants.trial_count || ...
        manifest.music_applicable_count ~= constants.music_applicable_count || ...
        manifest.element_cml_applicable_count ~= constants.element_cml_count || ...
        manifest.truth_leakage_count ~= 0 || ...
        numel(manifest.artifacts) ~= 15
    error('stage8_k2_wcb_verify:ManifestSchema', ...
        'The finalized manifest is incomplete or already audited.');
end
for index = 1:numel(manifest.artifacts)
    artifact = manifest.artifacts(index);
    path_now = fullfile(repo_dir, strrep(artifact.path, '/', filesep));
    if ~isfile(path_now) || ...
            ~strcmpi(stage8_k2_wcb_file_sha256(path_now), artifact.sha256)
        error('stage8_k2_wcb_verify:ArtifactHash', ...
            'Independent artifact hash failed: %s', artifact.path);
    end
end

results_path = fullfile(repo_dir, 'innovation-mining', ...
    '46_stage8_k2_white_snr_classical_baseline_results.csv');
audit_path = fullfile(repo_dir, 'innovation-mining', ...
    '46_stage8_k2_white_snr_classical_baseline_registry_audit.csv');
results = readtable(results_path, 'TextType', 'string');
registry_audit = readtable(audit_path, 'TextType', 'string');
if height(results) ~= constants.baseline_row_count || ...
        height(registry_audit) ~= constants.trial_count || ...
        numel(unique(results.trial_id + "|" + results.method_id)) ~= ...
        constants.baseline_row_count || ...
        any(results.truth_used_in_fit_flag) || ...
        any(~logical(registry_audit.checkpoint_valid)) || ...
        max(double(registry_audit.white_target_error_db)) > ...
        constants.snr_db_tolerance
    error('stage8_k2_wcb_verify:CommittedTables', ...
        'Independent result-table schema or integrity failed.');
end

audit = struct('status', ...
    'STAGE8_K2_WHITE_SNR_CLASSICAL_BASELINE_INDEPENDENT_AUDIT_PASS', ...
    'protocol', constants.protocol, 'formal_head', head, ...
    'code_identity', context.code_identity.tree_hash, ...
    'registry_hash', registry_hash, ...
    'evidence44_identity', context.evidence44.identity, ...
    'checkpoint_count', merged.scan.completed_count, ...
    'baseline_row_count', height(results), ...
    'reconstruction_match_count', height(registry), ...
    'maximum_white_target_error_db', maximum_target_error, ...
    'artifact_hash_match_count', numel(manifest.artifacts), ...
    'baseline_rerun_count', 0, 'completed_utc', stage8_k2_mc_utc_now());
audit_file = fullfile(runtime_root, 'audit', 'independent_audit.json');
write_json_atomic_local(audit_file, audit);
save(fullfile(runtime_root, 'audit', 'independent_audit.mat'), ...
    'audit', '-mat');

manifest.status = ...
    'STAGE8_K2_WHITE_SNR_CLASSICAL_BASELINE_COMPARISON_COMPLETE';
manifest.independent_audit_status = 'PASS';
manifest.independent_audit_utc = audit.completed_utc;
manifest.independent_reconstruction_match_count = height(registry);
manifest.independent_artifact_hash_match_count = numel(manifest.artifacts);
manifest.independent_baseline_rerun_count = 0;
manifest.next = 'USER_REVIEW';
write_json_atomic_local(manifest_path, manifest);
output = struct('status', ...
    'STAGE8_K2_WHITE_SNR_CLASSICAL_BASELINE_COMPARISON_COMPLETE', ...
    'audit', audit, 'manifest_path', manifest_path, ...
    'next', 'USER_REVIEW');
fprintf('%s\n', output.status);
end

function branch_audit_local(repo_dir, constants)
branch = git_output_local(repo_dir, 'branch --show-current');
head = git_output_local(repo_dir, 'rev-parse HEAD');
remote = git_output_local(repo_dir, ...
    'rev-parse origin/work/stage8-k2-white-snr-classical-baselines-v1');
tangent = git_output_local(repo_dir, ...
    'rev-parse origin/experiment/stage8-k2-tangent');
main = git_output_local(repo_dir, 'rev-parse origin/main');
research = git_output_local(repo_dir, ...
    'rev-parse origin/research/stage8-k2-vincent-anchored');
old_work = git_output_local(repo_dir, ...
    'rev-parse origin/work/stage8-k2-subspace-baselines-v1');
if ~strcmp(branch, constants.branch) || ~strcmp(head, remote) || ...
        ~strcmp(tangent, constants.expected_origin_tangent) || ...
        ~strcmp(main, constants.expected_origin_main) || ...
        ~strcmp(research, constants.expected_origin_research) || ...
        ~strcmp(old_work, constants.expected_old_work)
    error('stage8_k2_wcb_verify:BranchIdentity', ...
        'Independent audit Git identity failed.');
end
status = splitlines(string(git_output_local(repo_dir, ...
    'status --porcelain=v1 --untracked-files=all')));
status = status(strlength(status) > 0);
for index = 1:numel(status)
    path_now = extractAfter(status(index), 3);
    allowed = startsWith(path_now, "innovation-mining/46_") || ...
        startsWith(path_now, "innovation-mining/figures/46_");
    if ~allowed
        error('stage8_k2_wcb_verify:WorktreeScope', ...
            'Unexpected dirty path during independent audit: %s', path_now);
    end
end
end

function output = git_output_local(repo_dir, arguments)
[status, output] = system(sprintf('git -C "%s" %s', repo_dir, arguments));
if status ~= 0
    error('stage8_k2_wcb_verify:Git', ...
        'Git command failed: %s', arguments);
end
output = strtrim(output);
end

function write_json_atomic_local(path_now, value)
temporary = [path_now, '.tmp'];
encoded = jsonencode(value, 'PrettyPrint', true);
fid = fopen(temporary, 'w');
if fid < 0
    error('stage8_k2_wcb_verify:AuditOpen', ...
        'Unable to write an audit JSON file.');
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', encoded);
clear cleanup
[ok, message] = movefile(temporary, path_now, 'f');
if ~ok
    error('stage8_k2_wcb_verify:AuditMove', '%s', message);
end
end
