function status = stage8_k2_wcb_status_write( ...
    runtime_root, registry, progress, current_spec, constants, stage)
%STAGE8_K2_WCB_STATUS_WRITE Atomically publish current progress.

completed = progress.completed_count;
runtime_values = progress.runtime_sec(isfinite(progress.runtime_sec));
if isempty(runtime_values)
    median_trial = NaN;
    elapsed_active = 0;
    eta = NaN;
else
    median_trial = median(runtime_values);
    elapsed_active = sum(runtime_values);
    eta = median_trial * (height(registry) - completed);
end
if isempty(current_spec)
    current = struct('trial_id', "NONE", 'snr_db', NaN, ...
        'profile_id', "NONE", 'noise_profile_id', "NONE", ...
        'L', NaN, 'replicate_id', NaN);
else
    current = struct('trial_id', string(current_spec.trial_id), ...
        'snr_db', double(current_spec.white_beamspace_snr_target_db), ...
        'profile_id', string(current_spec.profile_id), ...
        'noise_profile_id', string(current_spec.noise_profile_id), ...
        'L', double(current_spec.L), ...
        'replicate_id', double(current_spec.replicate_id));
end
status = struct('protocol', constants.protocol, 'stage', char(stage), ...
    'completed', completed, 'total', height(registry), ...
    'remaining', height(registry) - completed, ...
    'current_trial', char(current.trial_id), ...
    'elapsed_active_sec', elapsed_active, ...
    'median_trial_sec', median_trial, 'eta_sec', eta, ...
    'current_snr_db', current.snr_db, ...
    'current_profile', char(current.profile_id), ...
    'current_noise', char(current.noise_profile_id), ...
    'current_L', current.L, 'current_replicate', current.replicate_id, ...
    'full4d_valid_count', progress.full4d_valid_count, ...
    'full4d_incomplete_count', progress.full4d_incomplete_count, ...
    'music_valid_count', progress.music_valid_count, ...
    'music_single_peak_count', progress.music_single_peak_count, ...
    'element_cml_completed_count', progress.element_cml_completed_count, ...
    'last_update_utc', stage8_k2_mc_utc_now());
encoded = jsonencode(status, 'PrettyPrint', true);
write_text_local(fullfile(runtime_root, 'status', ...
    'latest_status.json'), [encoded, newline]);
text_now = sprintf([ ...
    'Stage: %s\nCompleted: %d / %d\nRemaining: %d\n', ...
    'Current trial: %s\nElapsed active sec: %.6f\n', ...
    'Median trial sec: %.6f\nETA sec: %.6f\n', ...
    'Current SNR/profile/noise/L/replicate: %g / %s / %s / %g / %g\n', ...
    'Full4D valid/incomplete: %d / %d\n', ...
    'MUSIC valid/single-peak: %d / %d\n', ...
    'Element CML completed: %d\nLast update UTC: %s\n'], ...
    char(stage), completed, height(registry), height(registry) - completed, ...
    char(current.trial_id), elapsed_active, median_trial, eta, ...
    current.snr_db, char(current.profile_id), char(current.noise_profile_id), ...
    current.L, current.replicate_id, progress.full4d_valid_count, ...
    progress.full4d_incomplete_count, progress.music_valid_count, ...
    progress.music_single_peak_count, ...
    progress.element_cml_completed_count, status.last_update_utc);
write_text_local(fullfile(runtime_root, 'status', ...
    'latest_status.txt'), text_now);
end

function write_text_local(path_now, content)
temporary = [path_now, '.tmp'];
fid = fopen(temporary, 'w');
if fid < 0
    error('stage8_k2_wcb_status_write:Open', ...
        'Unable to write status file: %s', temporary);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', content);
clear cleanup
[ok, message] = movefile(temporary, path_now, 'f');
if ~ok
    error('stage8_k2_wcb_status_write:Move', '%s', message);
end
end
