function digest = stage8_k2_wcb_checkpoint_hash(checkpoint)
%STAGE8_K2_WCB_CHECKPOINT_HASH Hash runtime-independent scientific content.

rows = sortrows(checkpoint.baseline_rows, 'method_id');
runtime_fields = {'runtime_sec','online_runtime_sec', ...
    'precompute_runtime_sec_amortized'};
for index = 1:numel(runtime_fields)
    if ismember(runtime_fields{index}, rows.Properties.VariableNames)
        rows.(runtime_fields{index})(:) = 0;
    end
end
digest = stage8_k2_wcb_stable_hash( ...
    'CHECKPOINT_SCIENTIFIC_CONTENT', ...
    char(string(checkpoint.protocol)), ...
    char(string(checkpoint.checkpoint_contract_version)), ...
    checkpoint.evidence44_registry_row, checkpoint.registry_row, ...
    checkpoint.trial_identity, rows, ...
    char(string(checkpoint.code_identity)), ...
    char(string(checkpoint.registry_hash)), ...
    char(string(checkpoint.completion_status)));
end
