function registry = stage8_k2_wcb_build_registry(context)
%STAGE8_K2_WCB_BUILD_REGISTRY Bind baseline applicability to evidence 44.

registry = context.evidence44.registry;
constants = context.constants;
registry.music_applicable_flag = ismember(double(registry.L), ...
    constants.music_applicable_L);
registry.element_cml_registered_flag = ...
    ismember(double(registry.white_beamspace_snr_target_db), ...
    constants.element_snr_targets_db) & ...
    double(registry.L) == constants.element_snapshot_count & ...
    ismember(double(registry.replicate_id), constants.element_replicates);
if height(registry) ~= constants.trial_count || ...
        nnz(registry.music_applicable_flag) ~= ...
        constants.music_applicable_count || ...
        nnz(registry.element_cml_registered_flag) ~= ...
        constants.element_cml_count || ...
        ~isequal(sort(unique(double(registry.white_beamspace_snr_target_db))).', ...
        constants.white_snr_targets_db) || ...
        ~isequal(sort(unique(double(registry.L))).', ...
        constants.snapshot_counts) || ...
        ~isequal(sort(unique(registry.profile_id)), ...
        sort(constants.profile_ids)) || ...
        ~isequal(sort(unique(registry.noise_profile_id)), ...
        sort(constants.noise_profile_ids))
    error('stage8_k2_wcb_build_registry:Factors', ...
        'Baseline registry count or preregistered factors changed.');
end
end
