function output = stage8_k2_wcb_run_tests(repo_dir)
%STAGE8_K2_WCB_RUN_TESTS Run the ten preregistered contract tests.

if nargin < 1 || isempty(repo_dir)
    [status, repo_dir] = system('git rev-parse --show-toplevel');
    if status ~= 0
        error('stage8_k2_wcb_run_tests:Repository', ...
            'Unable to locate the repository root.');
    end
    repo_dir = strtrim(repo_dir);
end
scope = stage8_k2_wcb_add_paths(repo_dir); %#ok<NASGU>
context = stage8_k2_wcb_build_context(repo_dir);
registry = stage8_k2_wcb_build_registry(context);
fixture = struct('repo_dir', repo_dir, 'context', context, ...
    'registry', registry, 'registry_hash', ...
    stage8_k2_wcb_stable_hash('TEST_REGISTRY', registry));
tests = { ...
    @() test_evidence44_identity(fixture), ...
    @() test_1680_trial_hash_reconstruction(fixture), ...
    @() test_classical_budget_identity(fixture), ...
    @() test_full4d_contains_frozen_candidate(fixture), ...
    @() test_music_l1_not_applicable(fixture), ...
    @() test_music_two_peak_fixture(fixture), ...
    @() test_element_subset_cardinality(fixture), ...
    @() test_truth_isolation(fixture), ...
    @() test_checkpoint_roundtrip_resume(fixture), ...
    @() test_four_trial_smoke(fixture)};
names = ["T1_EVIDENCE44_IDENTITY"; ...
    "T2_1680_TRIAL_HASH_RECONSTRUCTION"; ...
    "T3_CLASSICAL_BUDGET_IDENTITY"; ...
    "T4_FULL4D_CONTAINS_FROZEN_CANDIDATE"; ...
    "T5_MUSIC_L1_NOT_APPLICABLE"; ...
    "T6_MUSIC_TWO_PEAK_FIXTURE"; ...
    "T7_ELEMENT_SUBSET_CARDINALITY"; ...
    "T8_TRUTH_ISOLATION"; ...
    "T9_CHECKPOINT_ROUNDTRIP_RESUME"; ...
    "T10_FOUR_TRIAL_SMOKE"];
results = cell(numel(tests), 1);
for index = 1:numel(tests)
    clock = tic;
    results{index} = tests{index}();
    if ~isstruct(results{index}) || ~isfield(results{index}, 'pass') || ...
            ~results{index}.pass
        error('stage8_k2_wcb_run_tests:Failure', ...
            'Registered test failed: %s', names(index));
    end
    results{index}.runtime_sec = toc(clock);
    fprintf('%s PASS (%.3f s)\n', names(index), ...
        results{index}.runtime_sec);
end
output = struct('pass', true, 'status', ...
    'STAGE8_K2_WHITE_SNR_CLASSICAL_BASELINE_TESTS_PASS', ...
    'test_count', numel(tests), 'test_names', names, ...
    'results', {results}, 'context_hash', context.context_hash, ...
    'registry_hash', fixture.registry_hash, ...
    'completed_utc', stage8_k2_mc_utc_now());
fprintf('STAGE8_K2_WHITE_SNR_CLASSICAL_BASELINE_TESTS_PASS 10/10\n');
end
