function merged = stage8_k2_wcb_merge( ...
    runtime_root, registry, context, registry_hash)
%STAGE8_K2_WCB_MERGE Validate and merge all immutable checkpoints.

scan = stage8_k2_wcb_scan_checkpoints( ...
    runtime_root, registry, context, registry_hash);
constants = context.constants;
if scan.completed_count ~= constants.trial_count || ...
        scan.tmp_count ~= 0 || scan.unexpected_count ~= 0 || ...
        scan.unexpected_tmp_count ~= 0
    error('stage8_k2_wcb_merge:CheckpointCount', ...
        'Final merge requires 1680 valid checkpoints and zero temp files.');
end
blocks = cell(constants.trial_count, 1);
audit_rows = repmat(struct('global_trial_index', 0, 'trial_id', "", ...
    'element_trial_hash', "", 'measurement_hash', "", ...
    'checkpoint_valid', false, 'scientific_hash', "", ...
    'white_target_error_db', NaN, 'runtime_sec', NaN), ...
    constants.trial_count, 1);
for index = 1:constants.trial_count
    checkpoint = scan.checkpoints{index};
    blocks{index} = checkpoint.baseline_rows;
    audit_rows(index) = struct( ...
        'global_trial_index', double(registry.global_trial_index(index)), ...
        'trial_id', string(registry.trial_id(index)), ...
        'element_trial_hash', ...
        string(checkpoint.trial_identity.element_trial_hash), ...
        'measurement_hash', ...
        string(checkpoint.trial_identity.measurement_hash), ...
        'checkpoint_valid', true, ...
        'scientific_hash', string(checkpoint.scientific_hash), ...
        'white_target_error_db', ...
        double(checkpoint.trial_identity.white_target_error_db), ...
        'runtime_sec', double(checkpoint.runtime_sec));
end
baseline_rows = sortrows(vertcat(blocks{:}), ...
    {'global_trial_index','method_id'});
registry_audit = struct2table(audit_rows);
if height(baseline_rows) ~= constants.baseline_row_count || ...
        numel(unique(baseline_rows.trial_id + "|" + ...
        baseline_rows.method_id)) ~= constants.baseline_row_count || ...
        nnz(baseline_rows.method_id == ...
        "FULL4D_BEAMSPACE_CML_MULTISTART") ~= ...
        constants.beamspace_full4d_count || ...
        nnz(baseline_rows.method_id == "BEAMSPACE_MUSIC_K2") ~= ...
        constants.music_row_count || ...
        nnz(baseline_rows.method_id == "BEAMSPACE_MUSIC_K2" & ...
        baseline_rows.applicable) ~= constants.music_applicable_count || ...
        nnz(baseline_rows.method_id == ...
        "FULL4D_ELEMENT_CML_MULTISTART" & ...
        baseline_rows.applicable) ~= constants.element_cml_count || ...
        any(baseline_rows.truth_used_in_fit_flag) || ...
        any(baseline_rows.profile_used_in_fit_flag) || ...
        any(baseline_rows.tangent_used_in_start_flag) || ...
        any(baseline_rows.core_used_in_start_flag) || ...
        max(registry_audit.white_target_error_db) > ...
        constants.snr_db_tolerance
    error('stage8_k2_wcb_merge:Integrity', ...
        'Merged counts, applicability, target, or fit isolation failed.');
end
writetable(registry, fullfile(runtime_root, 'merged', 'registry.csv'));
writetable(registry_audit, fullfile(runtime_root, 'merged', ...
    'registry_audit.csv'));
writetable(baseline_rows, fullfile(runtime_root, 'merged', ...
    'baseline_results.csv'));
merged = struct('registry', registry, ...
    'registry_audit', registry_audit, ...
    'baseline_rows', baseline_rows, 'scan', scan, ...
    'total_active_runtime_sec', sum(scan.runtime_sec), ...
    'median_trial_runtime_sec', median(scan.runtime_sec));
end
