function evidence = stage8_k2_wcb_load_evidence44(repo_dir, constants)
%STAGE8_K2_WCB_LOAD_EVIDENCE44 Load and verify immutable evidence 44.

if nargin < 2 || isempty(constants)
    constants = stage8_k2_wcb_constants();
end
evidence_dir = fullfile(repo_dir, 'innovation-mining');
manifest_path = fullfile(evidence_dir, ...
    '44_stage8_k2_white_snr_monte_carlo_runtime_manifest.json');
registry_path = fullfile(evidence_dir, ...
    '44_stage8_k2_white_snr_monte_carlo_registry.csv');
snr_path = fullfile(evidence_dir, ...
    '44_stage8_k2_white_snr_monte_carlo_snr_trials.csv');
methods_path = fullfile(evidence_dir, ...
    '44_stage8_k2_white_snr_monte_carlo_method_results.csv');
required_files = {manifest_path, registry_path, snr_path, methods_path};
if ~all(cellfun(@isfile, required_files))
    error('stage8_k2_wcb_load_evidence44:Missing', ...
        'One or more required evidence-44 files are missing.');
end

manifest_sha256 = stage8_k2_wcb_file_sha256(manifest_path);
if ~strcmpi(manifest_sha256, constants.evidence44_manifest_sha256)
    error('stage8_k2_wcb_load_evidence44:ManifestIdentity', ...
        'The evidence-44 manifest SHA-256 changed.');
end
manifest = jsondecode(fileread(manifest_path));
if ~strcmp(manifest.status, ...
        'STAGE8_K2_TANGENT_WHITE_SNR_MONTE_CARLO_COMPLETE') || ...
        ~strcmp(manifest.final_working_region_state, 'IDENTIFIED') || ...
        manifest.registry_count ~= constants.trial_count || ...
        manifest.snr_row_count ~= constants.trial_count || ...
        manifest.method_row_count ~= constants.existing_method_row_count || ...
        manifest.unique_trial_hash_count ~= constants.trial_count || ...
        manifest.base_realization_count ~= constants.base_realization_count || ...
        manifest.truth_leakage_count ~= 0 || ...
        ~strcmp(manifest.registry_hash, constants.evidence44_registry_hash) || ...
        numel(manifest.artifacts) ~= constants.evidence44_artifact_count
    error('stage8_k2_wcb_load_evidence44:ManifestStatus', ...
        'Evidence 44 is not the registered completed bundle.');
end

artifact_ids = strings(numel(manifest.artifacts), 1);
artifact_paths = strings(numel(manifest.artifacts), 1);
artifact_hashes = strings(numel(manifest.artifacts), 1);
for index = 1:numel(manifest.artifacts)
    artifact = manifest.artifacts(index);
    path_now = fullfile(repo_dir, strrep(artifact.path, '/', filesep));
    if ~isfile(path_now)
        error('stage8_k2_wcb_load_evidence44:ArtifactMissing', ...
            'Evidence-44 artifact is missing: %s', artifact.path);
    end
    actual = stage8_k2_wcb_file_sha256(path_now);
    if ~strcmpi(actual, artifact.sha256)
        error('stage8_k2_wcb_load_evidence44:ArtifactHash', ...
            'Evidence-44 SHA-256 mismatch: %s', artifact.path);
    end
    artifact_ids(index) = string(artifact.artifact_id);
    artifact_paths(index) = string(artifact.path);
    artifact_hashes(index) = string(lower(actual));
end

registry = readtable(registry_path, 'TextType', 'string');
snr_rows = readtable(snr_path, 'TextType', 'string');
method_rows = readtable(methods_path, 'TextType', 'string');
required_registry = {'global_trial_index','trial_id','noise_profile_id', ...
    'L','profile_id','white_beamspace_snr_target_db','replicate_id', ...
    'base_realization_index','source_seed','noise_seed', ...
    'measurement_hash','element_trial_hash'};
required_snr = {'global_trial_index','trial_id','element_trial_hash', ...
    'measurement_hash','white_beamspace_snr_target_db', ...
    'white_beam_snr_expected_db','fitting_rerun_flag'};
required_methods = {'global_trial_index','trial_id','element_trial_hash', ...
    'method_id','fit_valid','fit_status','angles_hat_deg','RSS','loglik', ...
    'joint_RMSE_deg','truth_used_in_fit_flag'};
if height(registry) ~= constants.trial_count || ...
        height(snr_rows) ~= constants.trial_count || ...
        height(method_rows) ~= constants.existing_method_row_count || ...
        ~all(ismember(required_registry, registry.Properties.VariableNames)) || ...
        ~all(ismember(required_snr, snr_rows.Properties.VariableNames)) || ...
        ~all(ismember(required_methods, method_rows.Properties.VariableNames))
    error('stage8_k2_wcb_load_evidence44:Schema', ...
        'Evidence-44 table schema or row count changed.');
end

registry = sortrows(registry, 'global_trial_index');
snr_rows = sortrows(snr_rows, 'global_trial_index');
method_rows = sortrows(method_rows, {'global_trial_index','method_id'});
if ~isequal(double(registry.global_trial_index), (1:constants.trial_count).') || ...
        ~isequal(registry.trial_id, snr_rows.trial_id) || ...
        ~isequal(registry.element_trial_hash, snr_rows.element_trial_hash) || ...
        ~isequal(registry.measurement_hash, snr_rows.measurement_hash) || ...
        numel(unique(registry.trial_id)) ~= constants.trial_count || ...
        numel(unique(registry.element_trial_hash)) ~= constants.trial_count || ...
        numel(unique(registry.base_realization_index)) ~= ...
        constants.base_realization_count || ...
        any(abs(double(snr_rows.white_beam_snr_expected_db) - ...
        double(snr_rows.white_beamspace_snr_target_db)) > ...
        constants.snr_db_tolerance) || ...
        any(logical(snr_rows.fitting_rerun_flag)) || ...
        any(logical(method_rows.truth_used_in_fit_flag))
    error('stage8_k2_wcb_load_evidence44:Integrity', ...
        'Evidence-44 registry, SNR, hash, or truth integrity failed.');
end

[groups, trial_ids] = findgroups(method_rows.trial_id);
counts = splitapply(@numel, method_rows.method_id, groups);
if numel(trial_ids) ~= constants.trial_count || any(counts ~= 3)
    error('stage8_k2_wcb_load_evidence44:MethodMultiplicity', ...
        'Each evidence-44 trial must contain exactly three method rows.');
end
for index = 1:constants.trial_count
    selected = method_rows.trial_id == registry.trial_id(index);
    if ~isequal(sort(method_rows.method_id(selected)), ...
            sort(constants.existing_method_ids)) || ...
            any(method_rows.element_trial_hash(selected) ~= ...
            registry.element_trial_hash(index))
        error('stage8_k2_wcb_load_evidence44:MethodIdentity', ...
            'An evidence-44 method set does not pair to its trial.');
    end
end

evidence_identity = stage8_k2_wcb_stable_hash('EVIDENCE_44', ...
    manifest_sha256, artifact_ids, artifact_paths, artifact_hashes, ...
    char(string(manifest.registry_hash)));
evidence = struct('manifest', manifest, ...
    'manifest_path', manifest_path, ...
    'manifest_sha256', string(manifest_sha256), ...
    'artifact_ids', artifact_ids, 'artifact_paths', artifact_paths, ...
    'artifact_sha256', artifact_hashes, ...
    'registry', registry, 'snr_rows', snr_rows, ...
    'method_rows', method_rows, ...
    'identity', string(evidence_identity));
end
